### ISSUE TITLE
core-js with System: Uncaught TypeError: $RegExp is not a function

### ISSUE THREAD

**Issue by phenomnomnominal** [systemjs/systemjs#1002]
I've been getting a few errors in Chrome when using core-js with System:

    Uncaught TypeError: $RegExp is not a function
    Uncaught TypeError: Object prototype may only be an Object or null: undefined

They happen in the es6.regexp.constructor and es6.number.constructor files, and I can't seem to work out how to get rid of them.

I found [this issue](https://github.com/zloirock/core-js/issues/133), but it wasn't much help (using TS not Babel), and then dug around a bit myself. It appears that the `Number` and `RegExp` objects that come off the imported global are wrong (neither of them have a `.prototype` property, which core-js expects. However `global.core.Number` and `global.core.RegExp` *do* have `.prototype`?

Any thoughts/ideas?

**Comment by guybedford** [comment]
I believe these polyfill features can be disabled in the babel-runtime transformer by setting `babelOptions.polyfill = false`? I'm not sure if that's the exact option for Babel 5 though, but I believe there is one.

**Comment by guybedford** [comment]
Otherwise you could always remove the use of the `runtime-transformer` entirely and use the babelHelpers global rather.

**Comment by phenomnomnominal** [comment]
Sorry, just saw that you had replied. This project *isn't* using Babel, this is a TS project where core-js is being included just like any other dependency.

**Comment by guybedford** [comment]
Sure, then it sounds like it might be related to how `global` is imported from CoreJS. If you can share details to help replicate that would help here.

**Comment by phenomnomnominal** [comment]
I started a new project with TS set up, installed core-js and ts, and ran it, and of course everything worked perfectly. I then noticed that it only happens in the real project when depCache has been run (and not when it has been bundled). Tried adding the depCache to the minimal project and it still works...

The difference is what is injected as `global`:

In the minimal app, it's just `window`:

![minimal](https://cloud.githubusercontent.com/assets/1086286/12279542/a6332a46-b9ec-11e5-8ab3-ab1094ae2a99.png)

In the proper app, it's something weird:

![fullapp](https://cloud.githubusercontent.com/assets/1086286/12279597/f23ec422-b9ec-11e5-9bbb-fc7a822eb920.png)

I know it's not much to go on, I've been digging into it for a few weeks and getting nowhere. Because it doesn't happen in the bundled app, these are only happening at dev time, so it's not a huge issue, but it's a bit annoying.

**Comment by guybedford** [comment]
Thanks for the feedback. Which version of SystemJS are you using here?

**Comment by phenomnomnominal** [comment]
0.19.9

**Comment by guybedford** [comment]
Did you try with the latest SystemJS?

**Comment by phenomnomnominal** [comment]
Yep, just updated now, and still the same issues.

**Comment by guybedford** [comment]
@phenomnomnominal I think this might be due to https://github.com/systemjs/systemjs/issues/848 where the depCache is altering the execution order of circular references, causing this circular reference to dereference somehow. It's probably best just to use normal bundling here.

**Comment by phenomnomnominal** [comment]
That actually sounds right, since there have been some occasions where one or both of the errors didn't happen. Okay, that's a good enough answer for now, thanks very much!

**Comment by nsuedu** [comment]
my English is bad.

      {
        test: /\.js[x]?$/,
        include: path.resolve(__dirname, "app"),
        loader: 'babel-loader',
      },
设置include，使babel只将你写的代码编译为es5.不必编译node_module中的依赖。
