### ISSUE TITLE
How to manage cache using SystemJS

### ISSUE THREAD

**Issue by jigargandhi** [systemjs/systemjs#1004]
Need a way to add prefix/suffix to or modify package names while loading the files to cache files in the browser.

Also no adequate documentation on how to do this exists.

**Comment by Bnaya** [comment]
On dev time you shouldn't use cache / use must revalidate headers.

On prod you should jspm build your code to a single js file, and then you can use any file revving gulp/grunt

**Comment by jigargandhi** [comment]
how about in the cases where I want do not want to use a single file for all my code for true benefits of asynchronous loading. Does systemjs/jspm help with that?

**Comment by Bnaya** [comment]
Read about 
https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#creating-a-dependency-cache

I don't know if JSPM have built it support for something like webpack chunks

**Comment by guybedford** [comment]
We didn't actually integrate any cache URL scheme features, as the idea was to simply use unique versioned URLs with far-future expires for these use cases.

Cache-urls can be provided with a custom locate hook though:

```javascript
var systemLocate = System.locate;
System.locate = function(load) {
  return systemLocate.call(this, load)
  .then(function(url) {
    if (url.match(/blah/))
     return url + 'cache-part';
    return url;
  });
};
```
