### ISSUE TITLE
can not load css dependency

### ISSUE THREAD

**Issue by matthieu-ravey** [systemjs/systemjs#1005]
Hi,

I have a dependency which itself has a css dependency and it fails to load it. Here is a repo where I reproduced the issue: https://github.com/matthieu-ravey/jspmselect2
Could you tell me what I should do to make it work ?

Thanks

**Comment by guybedford** [comment]
Try `jspm install css`.

The css plugin should be a dependency of select2, it seems that hasn't been included in the package.json config at https://github.com/select2/select2/blob/3.5.1/package.json, which is incorrect.

**Comment by matthieu-ravey** [comment]
Thanks that fixed it ;à

**Comment by guybedford** [comment]
:+1:
