### ISSUE TITLE
'parsed is not defined' error in version 0.19.10

### ISSUE THREAD

**Issue by NervosaX** [systemjs/systemjs#1006]
https://github.com/systemjs/systemjs/blob/8a688f7d21618967f382884caed8badd4d2012b2/lib/plugins.js#L69

It looks like it doesn't exist in the scope when being called...

**Comment by guybedford** [comment]
Thanks, I've added a fix, release to follow.

**Comment by guybedford** [comment]
This was released in 0.19.11.
