### ISSUE TITLE
breaking change in 0.19.10?

### ISSUE THREAD

**Issue by stefanocke** [systemjs/systemjs#1008]
Hi,

maybe it is similar to #1007 but it is not the same:

I have code like the following, which succesfully loads the module foobar/core in 0.19.9 but stopped to work in 0.19.10 / 0.19.11. It tries to load the already registered module from app/  there.

I also created a plunker: https://plnkr.co/edit/bRNHHfGvzp2Q6wMNqiTT?p=preview

```
    <script src="systemjs_0.19.9.js"></script>
        
    <script>System.config({
        defaultJSExtensions: true,
        paths: {
          '*': `app/*`
        }
      })</script>
    
    <script>
    System.register("foobar/core", [], true, function(require, exports, module) {})
      System.import('foobar/core')
        .then(function(m){ console.log('Loaded '+m)})
        .catch(function (e) {
          console.error(e,'!!! ERROR !!!');
        });
    </script>

```

P.S.: Imagine foobar/core is something like angular/core and comes from the script angular2/bundles/angular2.min.js.

**Comment by stefanocke** [comment]
P.S.:  Imagine foobar/core is something like angular/core and comes from the script angular2/bundles/angular2.min.js.

**Comment by guybedford** [comment]
Thanks, the Plunkr helped a lot to track this down. I've added a fix.

**Comment by guybedford** [comment]
Released in 0.19.12.

**Comment by stefanocke** [comment]
Thanks, works again for me.

**Comment by stefanocke** [comment]
Oh. I still experience breaking changes between 0.19.9 and 0.19.10. But now I can see them only in IE but not in chrome. And it seems to be a different issue than above. Will try to analyze it further...
