### ISSUE TITLE
did not call System.register or AMD define...

### ISSUE THREAD

**Issue by taxinvoice** [systemjs/systemjs#1009]
Any help why am getting this message?   I'm using visual studio 2013.

Error: http://localhost:37197/app/boot.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.
	Error loading http://localhost:37197/app/boot.js
Stack trace:
complete@http://localhost:37197/node_modules/systemjs/dist/system.src.js:2686:20
run@http://localhost:37197/node_modules/angular2/bundles/angular2-polyfills.js:138:14
zoneBoundFn@http://localhost:37197/node_modules/angular2/bundles/angular2-polyfills.js:111:14

**Comment by guybedford** [comment]
What is your SystemJS configuration for `boot.js`? It seems like SystemJS is trying to load it with script tag injection?

**Comment by taxinvoice** [comment]
my boot.js is

import {bootstrap}    from 'angular2/platform/browser'
import {AppComponent} from './app.component'

bootstrap(AppComponent);

**Comment by guybedford** [comment]
If you add a console.log into the `boot.js` file is the code being run?

I'd suggest trying to work on isolating the issue if you can. That is removing as much of the extraneous code that doesn't contribute to the issue as you can. A more isolated example would allow me to be able to suggest a fix much for you more easily. I do have limited time for this level of support though unfortunately.

**Comment by taxinvoice** [comment]
I will follow your suggestion and appreciate the quick response.

**Comment by taxinvoice** [comment]
I will follow your suggestion and appreciate the quick response.
I have isolated to to  this error:...
Uncaught Error: Module name "angular2/upgrade" has not been loaded yet for context: _. Use require([])


boot.ts

import {UpgradeAdapter} from 'angular2/upgrade'; ..this causes the error

**Comment by guybedford** [comment]
Thanks, there's just been a new release of SystemJS. Can you try with that and let me know if you're still getting the error then?

**Comment by taxinvoice** [comment]
Issue resolved, not sure what i did..resarted vs2013, reset vs projec typescript options.
