### ISSUE TITLE
Package main not found error message

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1013]
This is a common error message that would be very useful to provide.

With defaultJSExtensions disabled, when requesting a package by name, that has no main entry point set, we should throw a specific error for this.

**Comment by yeganehaym** [comment]
what do u mean it's disabled?
after updating my project to new systemjs version
my js file not found and i have to write js ext to detect js file but depenedcies not working and they need to js ext as well

```
 <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/systemjs/0.20.14/system.js"></script>
    <script type="text/javascript">

        System.defaultJSExtensions = true;
        System.import('app');
    </script>
```
