### ISSUE TITLE
Uncaught TypeError: _angular2.default.module(...).component is not a function

### ISSUE THREAD

**Issue by diit** [systemjs/systemjs#1014]
While running ```npm test ```
I get:
```
Chrome 47.0.2526 (Windows 10 0.0.0) ERROR
  Uncaught TypeError: _angular2.default.module(...).component is not a function
  at C:/xampp/projects/project/spec.bundle.js:31716 <- webpack:/C:/xampp/projects/project/client/app/common/hero/hero.js:5:0
```

**Comment by guybedford** [comment]
A little more context is needed here to be able to know if this is a SystemJS issue or not. Are you following any particular starter project here?

**Comment by diit** [comment]
Followed the startup guide and everything worked flawlessly except for the
testing. Have not customized or changed anything.

On Thu, Jan 7, 2016 at 8:49 AM, Guy Bedford <notifications@github.com>
wrote:

> A little more context is needed here to be able to know if this is a
> SystemJS issue or not. Are you following any particular starter project
> here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systemjs/systemjs/issues/1014#issuecomment-169668548>.
>



-- 
*Thanks,*
Dale Inverarity

**Comment by diit** [comment]
Closing, wrong repo - Sorry Guys!

**Comment by guybedford** [comment]
Sure, no problem!
