### ISSUE TITLE
Different instance imported for relative/absolute path

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1016]
This:

`import aModule from '../path/to/module.js'`

And this:

`import aModule from 'aboslute/path/to/module'`

In the same program, give different instances.

Using 0.19.8

**Comment by guybedford** [comment]
This certainly shouldn't be the case. Can you share the value of `Object.keys(System._loader.modules)`? That would help to find any non-unique names in the registry.

**Comment by guybedford** [comment]
Let me know if you still need any help here.

**Comment by Mosho1** [comment]
We are coming back to solve this issue (we worked around it).

I do see the following duplicated keys:

`"file:///D:/absolute/path/to/folder/client/build/lib/utils.js"`

and 

`"file:///client/build/lib/utils.js"`

Setting `baseURL` to `'file:///' + process.cwd().replace('\\', '/') + '/client'` rather than `/client` fixes the issue. Could you elaborate as to why this is happening?

**Comment by guybedford** [comment]
Always use `System.config({ baseURL: 'x'  })` over `System.baseURL = 'x'`.
