### ISSUE TITLE
Error while loading dependency, it's trying to require node modules

### ISSUE THREAD

**Issue by matthieu-ravey** [systemjs/systemjs#1017]
I installed a dependency (https://github.com/dankogai/js-base64) and when I import it it's trying to require('buffer') and it does not work. Here is a repo where I reproduces the issue: https://github.com/matthieu-ravey/jspmbase64 . What should I do in this case ?
Thanks

**Comment by guybedford** [comment]
SystemJS doesn't naturally work with Node-style dependencies. You need to create a map config to tell SystemJS where to find the code for the `buffer` package.

You probably want to install https://www.npmjs.com/package/buffer, note though that that in turn has dependencies as well.

If you only need the code to work in Node and not the browser, you can set the map for buffer to:

```javascript
System.config({
  map: {
   buffer: '@node/buffer'
  }
});
```

And it will use the internal Node implementation, but you'd need to install and configure the browserify version if you want it to work in the browser.

**Comment by matthieu-ravey** [comment]
In the code the require is supposed to be done only in node environment and it's supposed to work in the browser without `buffer`. The code requiring `buffer` looks like this:
```
if (typeof module !== 'undefined' && module.exports) {
        try {
            buffer = require('buffer').Buffer;
        } catch (err) {}
    }
```
If I load the script with `<script>` the code works fine in the browser, but with systemjs it's trying to execute this code, but it should not as far as I understand.

**Comment by guybedford** [comment]
@matthieu-ravey ok this is an easy case then. You can use the following configuration here:

```javascript
System.config({
  packages: {
    'path/to/js-base64': {
      map: {
        buffer: {
          node: '@node/buffer',
          browser: '@empty'
        }
      }
    }
  }
});
```

**Comment by matthieu-ravey** [comment]
@guybedford Thanks, it worked.

**Comment by guybedford** [comment]
:+1:
