### ISSUE TITLE
Breaking change with package configuration in 0.19.10? 

### ISSUE THREAD

**Issue by stefanocke** [systemjs/systemjs#1018]
Hello,
I have one more plunker, that worked with 0.19.9, but not with .10 and .11:

https://plnkr.co/edit/XUlJlMn3aRAVVuGfh1HQ?p=preview

In .9, component1 is succesfully loaded. In .10, the ".js" suffix is not appended and thus component1 is not loaded.
Maybe I have just a misunderstanding how paths and packages work together. But than there is still the question, what the configuration below should mean and why the meaning is different in .9 and .10

```
<script>System.config({
        paths: {
          'myapp/*' : 'app/*'
        },
        packages: {
              'myapp': {
                defaultExtension: 'js'
              }
        }
      })</script>
    
    <script>

      System.import('myapp/components/component1')
        .then(function(m){ console.log('Loaded components/component1:'+m)})
        .catch(function (e) {
          console.error(e,'!!! ERROR !!!');
        });
    </script>
```

**Comment by guybedford** [comment]
Released in 0.19.13.
