### ISSUE TITLE
Block Comment structure can cause Uncaught Error

### ISSUE THREAD

**Issue by DeanB2015** [systemjs/systemjs#1020]
If anyone encounters the  following error using SystemJS + TypeScript and ES5, please note the problem is with the block comments.  Changing the format or removing comments in the .js files will fix the problem.

    Uncaught Error: Module http://localhost:4400/scripts/xxxxxxx.js interpreted as global module format, but called System.register.
    system.src.js (2782,19)

The following block comments in my .ts file cause errors.

    // import {enableDebugTools} from 'angular2/platform/browser';
    /**
     * Used to demonstrate external module is loading and function is called.
     */

However, if I change the comments to use the following comment structure, I don't get an error:

     // import {enableDebugTools} from 'angular2/platform/browser';
     // Used to demonstrate external module is loading and function is called.

*Module format detection in SystemJS is not designed to be 100% accurate, it is designed to cater to the majority use case. -- Guy Bedford*

**Comment by zapping** [comment]
I faced a similar issue with comments on the import section and it throws a different sort of error.
http://stackoverflow.com/questions/40677324/comments-in-angular2
https://github.com/angular/angular/issues/12967
