### ISSUE TITLE
Unable to resolve jspm_packages when hitting routes more than 1 level deep

### ISSUE THREAD

**Issue by tilleryd** [systemjs/systemjs#1022]
When navigating to a route like `http://localhost:9000/foo/123` I get 404 errors on jspm_packages because the server is attempting to load them from the `/foo` path instead of the `/` root path.

`GET http://localhost:9000/foo/jspm_packages/npm/react@0.14.6.js 404 (Not Found)`

It's possible to fix this by changing the `paths` configuration in `system.config.js`.

From this:
```
paths: {
  "github:*": "jspm_packages/github/*",
  "npm:*": "jspm_packages/npm/*"
},
baseUrl: "/"
```

To this (adding a forward slash):
```
paths: {
  "github:*": "/jspm_packages/github/*",
  "npm:*": "/jspm_packages/npm/*"
},
baseUrl: "/"
```

However, the configuration is over written when running `jspm install something`.  The only solution I could come up with was to create a Gulp task that copies `system.config.js` over to the `dist` folder and modify the path using `replace`.

To summarize my application configuration; I copy all assets to a `dist` folder and run a Gulp task that starts BrowserSync and serves all files from `dist`.

`dist` folder
```
- dist/
  - css/
  - fonts/
  - icons/
  - js/
  - index.html
  - system.config.js
```

`index.html`
```
<html lang="en">
  <body>
    <div id="app"></div>
    <script src="/jspm_packages/system.js"></script>
    <script src="/system.config.js"></script>
    <script>System.import('/js/app')</script>
  </body>
</html>
```

Gulp `serve.js` task (BrowserSync config)
```
var serverOptions = {
  open: false,
  ui: false,
  notify: false,
  ghostMode: false,
  port: process.env.PORT || 9000,
  server: {
    baseDir: global.paths.dist,
    routes: {
      '/system.config.js': './src/system.config.js',
      '/jspm_packages': './src/jspm_packages'
    }
  },
  middleware: [
    historyApiFallback({
      historyApiFallback: true
    })
  ]
};
```

I'm using `react-router` but the issue seems due to URL paths in general, not a routing lib.  My solution is a workaround at best and I'm wondering what the correct solution is to resolve this issue.  Any help or suggestions will be greatly appreciated.  I do still love JSPM/SystemJS very much.  Thanks!

**Comment by guybedford** [comment]
With a paths configuration like:

```
paths: {
  "github:*": "jspm_packages/github/*",
  "npm:*": "jspm_packages/npm/*"
},
baseUrl: "/"
````

The path locations for jspm_packages will always be baseURL-relative. Paths are designed to always resolve this way, so that the page URL shouldn't affect the jspm_packages resolutions at all.

Can you perhaps try running `System.nomalize('github:x').then(console.log.bind(console))` and share that output with the exact config to help understand how you are getting the wrong path here?

**Comment by tilleryd** [comment]
I added `System.normalize('github:x').then(console.log.bind(console))`.  

Test 1:
Route: `http://localhost:9000/home`
Console log: `http://localhost:9000/jspm_packages/github/x.js`

Test 2:
Route: `http://localhost:9000/foo/123`
Console log: `http://localhost:9000/foo/jspm_packages/github/x.js`

react-router routes config:
```
  <Route path="/" component={Main}>
    <Route path="/home" component={Home} />
    <Route path="/foo/:id" component={Foo} />
  </Route>
```

SystemJS Config
```
System.config({
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "blacklist": []
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  baseUrl: '/',
  buildCSS: true,
  separateCSS: true,
  map: {
    ...
  }
});
```

**Comment by guybedford** [comment]
The problem here is that the baseURL is not being set properly I think.

It should be `System.config({ baseURL: '/' })` not `System.config({ baseUrl: '/' })`.

**Comment by tilleryd** [comment]
If you had a dollar for every time someone misconfigured baseURL you'd be a rich man.  Thanks!
