### ISSUE TITLE
Empty Angular object being injected (Uncaught (in promise) Error: angular.module is not a function)

### ISSUE THREAD

**Issue by Belpois** [systemjs/systemjs#1024]
Angular is available in global scope but is not being injected properly, upon inspecting the injected angular it is a an empty Object.

Using AngularJS v1.4.8

**Comment by guybedford** [comment]
Which starter project are you using here?

**Comment by Belpois** [comment]
It is a custom solution we use where I work, it includes Angular, JQuery among other libraries which are written in house and sourced from the internet, loaded using SystemJS written using TypeScript, we are having trouble getting angular to work properly with version SystemJS 0.19.14

We constantly get  "Uncaught (in promise) Error: angular.module is not a function", since when we try to call anything from angular its an empty object.

The problem though seems to happen even on a bare skeleton setup which only includes SystemJS and AngularJS. We also discovered that our Karma Tests also get an empty angular object.

We circumvented this issue by reverting to a version I knew it worked for us, SystemJS 0.19.8, will try and test out other versions if I get the chance.

**Here is a sample project I made that shows the error in action.
[sjsng-bug.zip](https://github.com/systemjs/systemjs/files/86467/sjsng-bug.zip)**

To run you need NodeJS+NPM and Gulp, then run the commands;
```
   npm install
```

```
   gulp server
```

Thanks! :)

**Comment by ipinak** [comment]
I experience the same issue and I'm using the same versions of angularJS and SystemJS.

**Comment by phatgolo** [comment]
+1

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/systemjs/systemjs/commit/19a032b6ecc07e399f4cfe0c0e6d56d5014e1567.

**Comment by Belpois** [comment]
Thanks!

**Comment by Belpois** [comment]
I updated to 0.19.16 and I can confirm that our solution is now working :)

**Comment by guybedford** [comment]
Released in 0.19.16.

**Comment by nicolashemonic** [comment]
Hi @guybedford, thank you for you awesome job with SystemJS, i love it! 
Unfortunately i experience the same issue with TypeScript code compiled to System module and jQuery v2.2.0 loaded through JSPM. At run time jQuery is loaded but i get the error  **Uncaught (in promise) Error: jQuery is not a function**
I tried to update SystemJS 0.19.17 but it doesn't fixed issue...
Thank you!

**Comment by guybedford** [comment]
@nicolashemonic I think you may want to look into the TypeScript 1.8 synthetic imports option here? See https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-default-import-interop-with-systemjs.

**Comment by guybedford** [comment]
I don't personally work on the TypeScript workflows so may well be wrong though!

**Comment by nicolashemonic** [comment]
I updated my TypeScript version to 1.8.0 (beta) for **allowSyntheticDefaultImports** option.
Then, i changed imports `import * as jQuery from 'jQuery'` to `import jQuery from 'jQuery'` and its works!
Thank you @guybedford

**Comment by npbenjohnson** [comment]
This angular issue is happening to me on bower-angular 1.5.7 and systemjs 0.19.31. window.angular is the angular object, `System.import('angular').then(function(a){a is {};})` putting in a meta override to make angular a global module fixes the problem, but also defeats the purpose of using bower-angular.

**Comment by asapach** [comment]
@npbenjohnson:  instead of `a` in `function(a){a is {};}` try `a.default`

**Comment by npbenjohnson** [comment]
a.default = undefined, a.prototype = Object

**Comment by guybedford** [comment]
Did you try setting the format to AMD?

**Comment by npbenjohnson** [comment]
Tried it http://127.0.0.1:8080/jspm_packages/github/angular/bower-angular@1.5.7/angular.js did not define.

It looks like angular does something strange to declare it's global. I didn't dig too far into it, but it puts angular on the window object first, and then I think it fills it in with ensure-functionality-is-there-when-called type methods. Right now having the global workaround works for me, some time today I'll try rolling back in system js a bit to see if I can find the change that broke it.

**Comment by npbenjohnson** [comment]
No amount of rolling back systemjs or angular made a difference so I guess it must be a use case I didn't have before. Is there a starting point plunkr or jsfiddle for jspm currently?

**Comment by guybedford** [comment]
@npbenjohnson I didn't realise you were using jspm here. It's as simple as `jspm install angular` for this. Make sure you're not using a custom override though, by uninstalling first if you perhaps are.
