### ISSUE TITLE
bundles.js: locate: iterates over loader.bundles' properties when no bundles

### ISSUE THREAD

**Issue by zumankii** [systemjs/systemjs#1025]
If load.name is not in loader.defined and there are no bundles in loader.bundles 'for (var b in loader.bundles)' iterates over loader's properties instead.

**Comment by guybedford** [comment]
@zumankii can you clarify what you mean here? `loader.bundles` certainly doesn't extend its prototype from the loader.

**Comment by zumankii** [comment]
I mean that when I have no bundles registered (the length of loader.bundles is 0) the for..in iterates the array's methods instead. 
In my case the variable 'b' is 'clear' during the first iteration which causes loader.bundles[b].indexOf(load.name) to throw an exception since loader.bundles[b] is undefined.

I can only reproduce the error when running our karma tests (both using karma-chrome-launcher and karma-phantomjs-launcher-nonet), so I can't rule out that the error is in our code(?). But when I downgrade jspm to 0.16.19 (which uses systemjs 0.19.9) there are no errors.

**Comment by guybedford** [comment]
@zumankii `loader.bundles` should be an object not an array.

**Comment by zumankii** [comment]
Yeah, you're right - I got tricked by the debugger :) In some way it appears to extend the array prototype in my case (see attached image).

![1025 0](https://cloud.githubusercontent.com/assets/7112643/12256643/309c3504-b8ff-11e5-94f7-3b9579706b71.png)

Maybe this rather is a "support case" than an issue then... But, still the error occurs in 0.19.14, but not in 0.19.9. Any ideas of how our setup can cause this?

**Comment by guybedford** [comment]
@zumankii yes `for of` in JavaScript iterates the prototype properties. I created https://github.com/systemjs/systemjs/issues/1027 to track a nicer error here.

**Comment by zumankii** [comment]
If anyone else do experience these problems in the future, I found out what caused loader.bundles to be set to an array; it appears that karma-jspm sets it when useBundles is not set to true (in karma config).
