### ISSUE TITLE
Bundles ignored

### ISSUE THREAD

**Issue by danfma** [systemjs/systemjs#1026]
After upgrading to the last jspm-cli, the jspm stopped loading my bundles, even if I redefine and reimport all of them.

Apparently, is an error with the SystemJS, because the jspm-cli is doing the work of configuration normally.

**Comment by guybedford** [comment]
@danfma is there any way you can share an example isolated replication here?

**Comment by danfma** [comment]
Ok, I will provide one.

**Comment by danfma** [comment]
I can't provide you with a working example by now, but I will put the steps here:

1. Create a new empty project directory
2. `npm install jspm`
3. `jspm init` (just changed the libraries dir from ./jspm_packages/ to libs/jspm)
4. `jspm install core-js`
5. `jspm bundle core-js libs/bundles/core-js.bundle.js --inject --minify --no-mangle` (bundle created)
6. create the index.html file importing the core-js
7. use the http-server, for example, to serve the directory.

index.html content:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sample</title>
</head>

<body class="page">
    <script src="libs/jspm/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import("core-js")
            .then(function () {
                console.log("LOADED");
            });
    </script>
</body>

</html>
```

After loading the page in the browser, you will see that the bundle definition was not respected and the SystemJS loaded all the files.

I used the jspm all the time, and apparently the error is of that tool, but after checking the files generated, there is no problem with them. And when I revert the jspm version, which forces an older version of the SystemJS, it works again.

**Comment by danfma** [comment]
The same example works with the jspm 0.16.19 which uses the systemjs 0.19.9.

**Comment by nillis** [comment]
I have a sample on the following plunkr:
https://plnkr.co/edit/d1ZRSwQttrnMkB7wnhQN?p=preview

Expected behaviour:
When loading a module which is part of a bundle, the bundle is loaded (0.16.9)

Actual behaviour:
When loading a module which is part of a bundle, the module is loaded (0.16.10)

**Comment by nillis** [comment]
Please open your console on the plunkr to see this behaviour. 
When 0.16.9 is loaded, the bundle.js is loaded (at least tried to).
When you change the SystemJS version in the head script to 0.16.10, then c.js is loaded instead of bundle.js.

When I don't use the defaultJSExtensions property and include all .js extensions in my bundle config and import, then the behaviour is the expected one for both versions.

I guess it has something todo with the map/normalization commites between 0.16.9 and 0.16.10:
https://github.com/systemjs/systemjs/compare/0.19.9...0.19.10

**Comment by PWKad** [comment]
@guybedford FWIW we've had a lot of questions today in the Aurelia gitter about bundling on latest system.js.  Trying to help track down issues at the moment, will provide more info when it comes in.

**Comment by drub0y** [comment]
Can confirm that going from JSPM `0.16.19` to `0.16.20` breaks bundle loading. Dependency wise that's going from SystemJS `0.19.9` to `0.19.14`. So somewhere from `0.19.10+` the bundle loading was broken.

**Comment by nillis** [comment]
The bundling is broken in SystemJS 0.19.10 when not including file extensions in your map/bundle.

**Comment by guybedford** [comment]
@danfma thanks for the great detailed replication. I've included a fix in https://github.com/systemjs/systemjs/commit/ba4b0b8b7f359b79760fb5b422aef80fa2d261f3, pending release.

**Comment by guybedford** [comment]
Released in 0.19.16.

**Comment by nillis** [comment]
Thx for the fast fix!

**Comment by drub0y** [comment]
+1, great job on the quick fix. Thanks!

**Comment by danfma** [comment]
Thanks!!
