### ISSUE TITLE
Bundle Vs individual modules

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#1029]
I came across an angular1 [example](https://github.com/fadihania/angular1-typescript-systemjs) using *typescript* and *systemjs*.

With angular1, angular2 or react, is it advisable to use **systemjs** to load individual modules instead of a single bundle file like *app.js*? What is the suggested approach for the future for a production environment?

I posted a similar question which you can see [here](https://github.com/fadihania/angular1-typescript-systemjs/issues/1).

**Comment by guybedford** [comment]
Bundling is always recommended with SystemJS currently.
