### ISSUE TITLE
CSP ideas

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#103]
Instead of a separate CSP loader, I think it would make more sense for "bundles" to always fetch with script tags.

With this change, we'd naturally have a CSP production through bundling.

**Comment by laurentgoudet** [comment]
In my case I need CSP support - as our CDN provider likes to make CORS hard - and RequireJS support, so I have to resort to the save & restore `define` hack. What do you meant by "Over time this use case will phase out as this module eventually becomes a polyfill only for older browsers"? Isn't CSP going to become more and more popular as an extra XSS protection layer?
