### ISSUE TITLE
TypeScript __moduleName support in builds

### ISSUE THREAD

**Issue by meriturva** [systemjs/systemjs#1030]
As you can see here: http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/ and https://github.com/angular/angular/issues/2383

to load relative templates we could use `module.id` when using CommonJs but what about SystemJs...do you have any advice? What we need, i guess, it is just base directory of component to assign to `moduleId` property as:

```
@Component({   
    selector: 'selector-name',
    moduleId: module.id,
    templateUrl: 'relativetemplate.html'
})
```

I already opened issue on angular repository: https://github.com/angular/angular/issues/6053

**Comment by guybedford** [comment]
For ES modules, we provide a `__moduleName` variable in SystemJS for this. See https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemimportmodulename--normalizedparentname---promisemodule.

**Comment by meriturva** [comment]
@guybedford due to use of TypeScript i think that we are stuck on https://github.com/Microsoft/TypeScript/issues/6359

right?

**Comment by guybedford** [comment]
@meriturva yes exactly, I'll leave this up to track.

**Comment by tbragaf** [comment]
@guybedford
__moduleName is being transpiled to $__moduleContext.id and $__moduleContext is a string.
So in my app $__moduleContext.id is undefined.

Any clue?

**Comment by guybedford** [comment]
@tbragaf which version of SystemJS are you using? Are you definitely getting this with the latest version?

**Comment by tbragaf** [comment]
@tbragaf v: 0.19.18

**Comment by guybedford** [comment]
@tbragaf thanks, ok somehow this got missed. Corrected in https://github.com/jspm/jspm-cli/commit/f746fe58093248f443baff49dc6c42d7ab66474a pending release.

**Comment by tbragaf** [comment]
@guybedford  :+1:

**Comment by tbragaf** [comment]
@guybedford I am not using jspm. Only traceur and systemjs
Will your changes affect any of those libs?

**Comment by tbragaf** [comment]
@guybedford
For me, I simply dig into the traceur code:
traceur/src/codegeneration/InstanciateModule.js and changed "return parseExpression `$__moduleContext.id`;" on line 138 to "return parseExpression `$__moduleContext`";

Which works but I don't know the possible side effects...

**Comment by guybedford** [comment]
Released in 0.19.19. This will be fully supported in this new form in the next beta release of TypeScript as well.

**Comment by born2net** [comment]
using latest jspm and ng2 still getting Error: ReferenceError: __moduleName is not defined
and not working as per how it should via https://angular.io/docs/ts/latest/guide/component-styles.html

ng2 0.14
jspm 0.16.33
regards

**Comment by guybedford** [comment]
@born2net what ES module transpiler are you using here? Make sure you're using the latest version of TypeScript, Traceur or Babel.

**Comment by born2net** [comment]
I am using TypeScript 1.8.9

**Comment by guybedford** [comment]
@born2net are you definitely compiling into the `system` module format with typescript?

**Comment by born2net** [comment]
ha yes you are right, I need to change back to system from commonjs, will do that asap (will need to make some other changes for this to work so I can test)... tx again...
