### ISSUE TITLE
Injecting Angular1 dependencies for a module

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#1032]
I posted a [question](http://stackoverflow.com/questions/34788098/how-to-load-angular1-dependencies-using-systemjs) on Stackoverflow about how to inject dependencies for a module in Angular1.

**Comment by henrjk** [comment]
I am seeing probably the same problem as well. I configured my app why jspm 0.17.0-beta.2  (systemjs 0.19.16).

The error I am seeing is shown below. When I stepped through this with the debugger the error did not occur after inserting a BP with a debugger statement at angular.js:4419createInjector.

I have also not seen the problem with jspm 0.16.x. I used a version between 0.16.15 to 0.16.19, which would mean system.js could have been from version 0.19.6 to 0.19.9.

Below is the problem I saw. @varghesep If you saw something different I might have to open my own issue.

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module AnvilConnectClient due to:
Error: [$injector:nomod] Module 'AnvilConnectClient' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.8/$injector/nomod?p0=AnvilConnectClient
    at http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:68:12
    at http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:2005:17
    at ensure (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:1929:38)
    at module (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:2003:14)
    at http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4435:22
    at forEach (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:340:20)
    at loadModules (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4419:5)
    at createInjector (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:4344:11)
    at doBootstrap (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:1676:20)
    at bootstrap (http://localhost:9000/jspm/jspm_packages/github/angular/bower-angular@1.4.8/angular.js:1697:12)
http://errors.angularjs.org/1.4.8/$injector/modulerr?p0=AnvilConnectClient&…ckages%2Fgithub%2Fangular%2Fbower-angular%401.4.8%2Fangular.js%3A1697%3A12)(anonymous function) @ angular.js:68(anonymous function) @ angular.js:4458forEach @ angular.js:340loadModules @ angular.js:4419createInjector @ angular.js:4344doBootstrap @ angular.js:1676bootstrap @ angular.js:1697angularInit @ angular.js:1591(anonymous function) @ angular.js:29013trigger @ angular.js:3057setTimeout (async)JQLite.ready @ angular.js:3062(anonymous function) @ angular.js:29012(anonymous function) @ angular.js:29016
```

**Comment by varghesep** [comment]
It is the similar error, but did not say exactly which module can't be built. In my example, it did not say it could not build *hub*. I had to remove the dependency and find out whether the code is loading without errors.

**Comment by henrjk** [comment]
I try to boil down my scenario into a smaller set. It may be a few days before I get to that though.

**Comment by henrjk** [comment]
In my scenario the issue is that the angular initialization happened on the DOMContentLoaded event. Apparently if this event happens too early the error above occurred.  

So this did not work (most of the times unless debugging or stripping things down to find a smaller repro scenario)
index.html:
```HTML
...
  <body ng-app=="AnvilConnectClient" >
...
    <script src="jspm/jspm_packages/system.src.js"></script>
    <script src="jspm/jspm.browser.js"></script>
    <script src="jspm/jspm.js"></script>
    <script>
        System.import('scripts/app.js')
   </script>
```

Changing angular to use [Manual initialization](https://docs.angularjs.org/guide/bootstrap#manual-initialization) appears to have fixed the problem:
```HTML
...
  <body>
...
    <script src="jspm/jspm_packages/system.src.js"></script>
    <script src="jspm/jspm.browser.js"></script>
    <script src="jspm/jspm.js"></script>
    <script>
        System.import('scripts/app.js').then(function() {
          angular.bootstrap(document, ['AnvilConnectClient']);
        })
   </script>
```

@varghesep Is this helping for your issue as well?
