### ISSUE TITLE
Question: how to configure interdependent packages.

### ISSUE THREAD

**Issue by vadimpopa** [systemjs/systemjs#1033]
This config used to work up to 0.19.9, but once I upgraded to 0.19.15 is making the browser to loop and run out of memory. And also I'm still confused how to configure interdependent packages. If you could take a look and let me know what's wrong here, and a short "How to", that would be great, and will be + another example in the docs. Thank you.

```
// in app.js , ionic.js is in root of ionic
import {App, IonicApp, Platform} from 'ionic/ionic';
```

```
  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "map": {
        "ionic": "ionic"
      },
      "modules": {
        "*.ts": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        },
        "*.html": {
          "loader": "text"
        }
      }
    },
    "npm:ionic-framework@2.0.0-alpha.44": {
      "defaultExtension": "js",
      "map": {
        "ionic": "./"
      },
      "modules": {
        "*.ts": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        },
        "*.html": {
          "loader": "text"
        }
      }
    }
  },
```

**Comment by vadimpopa** [comment]
So if I set the ionic map like this:
```
  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "js",
      "map": {
        "ionic": "npm:ionic-framework@2.0.0-alpha.44/"
      },
```

then "import from ionic/ionic" is working. But wondering if that's the correct way to do it, because if I upgrade ionic, than I need to change the mapping also, manually.

**Comment by guybedford** [comment]
I tried running this but then get an Angular error for some reason.

Can you try running:

```javascript
System.normalize('ionic', System.normalizeSync('app/')).then(console.log.bind(console));
```

And see if that is returning the expected result?

**Comment by vadimpopa** [comment]
Seems ok to me:
```
http://localhost:8080/jspm_packages/npm/ionic-framework@2.0.0-alpha.44/ionic.js
```
Dev it's ok. But when running for production, gulp-jspm is throwing an error.
```
Unhandled rejection Error: ENOENT: no such file or directory, open '/Users/vadim/Documents/Projects/jspm-ionic2-starter/jspm_packages/npm/ionic-framework@2.0.0-alpha.44/ionic'
    at Error (native)
From previous event:
    at /Users/vadim/Documents/Projects/jspm-ionic2-starter/node_modules/temp/lib/temp.js:252:7
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at DestroyableTransform._transform (/Users/vadim/Documents/Projects/jspm-ionic2-starter/node_modules/gulp-jspm/index.js:40:10)
```
Will try to figure out why in the next days. 
Is this this the right way of configuring ? and will have to upgrade manually when ionic version changes ?

**Comment by vadimpopa** [comment]
Ok, so moved forward with production also, and following config it's fine:
```javascript
  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "js",
      "map": {
        "ionic": "npm:ionic-framework@2.0.0-alpha.44/ionic.js"
      },
      "modules": {
        "*.js": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        },
        "*.html": {
          "loader": "text"
        }
      }
    }
  }
```

**Comment by vadimpopa** [comment]
Ok and just got the answer to my question about upgrading, for this there's: jspm update. You can close this thread. Thanks for trying to help.

**Comment by guybedford** [comment]
@vadimpopa this seems like it had something to do with the main configuration. Did you try adding a `"main": "ionic.js"` to the ionic package configuration above?

**Comment by vadimpopa** [comment]
@guybedford I got your point, but eventually didn't need that, as I removed "ionic.js" because I had to import outside the Ionic module also, in the /events case:

```javascript
import {App, IonicApp, Storage, SqlStorage} from 'ionic/ionic'; // it's from ionic/ionic.js
import {Events} from 'ionic/util/events'; // it's form ionic/util/events.js

  packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "map": {
        "ionic": "npm:ionic-framework@2.0.0-alpha.52",
        "rxjs": "npm:rxjs@5.0.0-beta.0"
      },
```

What I noticed, is that jspm update doesn't update the maps from packages. I need to manually update the version.

**Comment by guybedford** [comment]
@vadimpopa generally it is advised to use the top-level map for package dependencies (`jspm install ionic=npm:ionic-framework@2.0.0-alpha.52`).
