### ISSUE TITLE
jspm with plugin-babel and react preset: "cannot read property 'transform' of undefined"

### ISSUE THREAD

**Issue by DavidEwers** [systemjs/systemjs#1034]
I'm getting the above error in the Chrome console at system.js 4 @system.src.js:4837
I've got the jsx preset installed in jspm_packages along with the babel-plugin.
My config.js has the "transpiler" set as "plugin-babel".
My config.js has "presets": [ "react" ] and "blacklist": [] under "babelOptions."

In my "main.js" file I have:
- import React from 'react';
- import ReactDom from 'react-dom';
 (both are installed in jspm_packages)
- import showNavbars from '/path' (imports a function)
- showNavbars();

On my index.html I have:

    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
        System.import('/assets/js/main.js');
    </script>

I'm not even sure if this is a system.js issue or not. I'm getting the error from system.js, so I logged it here first. Also logged under jspm and babel-plugin.

**Comment by mnichols** [comment]
I got this when compiling riot. It is likely doing something like `require('babel').transform` but the `babel` module cannot be found so it is `undefined`.

**Comment by DavidEwers** [comment]
You're right. I had the config.js "presets" wrong. It should have been "babel-preset-react" to map to the files in the jspm_packages. But now I have a new problem. My server can't find the systemjs-babel-plugin@0.0.2.js. The http file path is totally correct and the file is sitting right there in the correct place.

**Comment by mnichols** [comment]
Yeh you have to include jspm.browser.js on the page maybe. In addition to
jspm.js. that fixed me up when I hit that

**Comment by guybedford** [comment]
Note that the Babel plugin is only compatible with jspm 0.17 beta.

**Comment by mnichols** [comment]
Yes I was using jspm beta 2 and noticed there is a jspm.js and a jspm.browser.js . I am not sure where the problems compiling riot were coming from, systemjs or their compiler. They do a `require('babel').transform` somewhere and even when I assign the babel dep to point to babel-core a whole other pandora's box of missing dependencies would open up, so I gave up.

**Comment by DavidEwers** [comment]
Thanks for your help, @mnichols . I'm just going to continuing using webstorm's file watchers to run babel-cli until jspm .17 comes out of beta. When it does, I'll try the babel-plugin again. Transforming in the browser is a better solution during development. You're right about the pandora's box. At some point you have to say enough! I need to start coding...
