### ISSUE TITLE
System.import bundle file

### ISSUE THREAD

**Issue by kzko** [systemjs/systemjs#1037]
This is more of a question on how System.import works.

I am trying to lazyload a jspm bundle like so in angularjs: 

            System.import('map/bundle_map.js').then(function (loadedFile) {
                console.log(loadedFile)  ----> returns "EMPTY" object {} and fails lazy-loading
                $ocLazyLoad.load(loadedFile['mapModule']).then(function() {
                    d.resolve(futureState);
                })
            });
bundle_map.js was generated through jspm-cli  bundling up map.js

in map.js we have something like, but which also imports a few other files (hence the bundle)

            var mapModule = angular.module('map', []) 
            export { mapModule }

If I were to try to import map.js directly (and not the bundle), the code is working file.

            System.import('map/map.js').then(function (loadedFile) {
                $ocLazyLoad.load(loadedFile['mapModule']).then(function() {
                    d.resolve(futureState);
                })
            });

Is there a way to make lazy-loading work in this case with the jspm bundle file?

**Comment by guybedford** [comment]
The bundle does not have a module value itself. You need to then separately `System.import('map/map.js')` to get the module from the bundle.
