### ISSUE TITLE
TypeScript exports function behaviour

### ISSUE THREAD

**Issue by nillis** [systemjs/systemjs#1040]
@guybedford What's your opinion on the problem bellow? 

http://stackoverflow.com/questions/33938561/how-to-use-momentjs-in-typescript-with-systemjs?answertab=votes#tab-top

**Comment by nillis** [comment]
I guess https://github.com/Microsoft/TypeScript/issues/5285 can be a solution in TS 1.8

**Comment by guybedford** [comment]
@nillis did you try `import moment from 'moment'`?

**Comment by frederikschubert** [comment]
You should install the typings for moment and moment-node and then import moment as a module.
```
import * as moment from "moment";
```

It is also important that you choose commonjs module format for moment. I had issues loading it while setting the format to system.
