### ISSUE TITLE
Module could not find global dependency

### ISSUE THREAD

**Issue by matthieu-ravey** [systemjs/systemjs#1045]
I've a module that has a dependency to moment and it can find it as a global variable. I've tried to add this to config.meta but neither worked:

```javascript
"ui-bootstrap-datetimepicker": {
      "globals": {
        "moment": "moment"
      }
    }
```

```javascript
"ui-bootstrap-datetimepicker": {
      "deps": [
        "moment"
      ]
    }
```

**Comment by guybedford** [comment]
You must ensure that the `ui-bootstrap-datetimepicker` path is the exact file path to the module such that `System.normalizeSync('ui-bootstrap-datetimepicker')` references the correct file otherwise meta won't apply properly.
