### ISSUE TITLE
TypeScript and defaultJSExtensions

### ISSUE THREAD

**Issue by nycdotnet** [systemjs/systemjs#1046]
Hi,

I have a concern about the deprecation of `defaultJSExtensions` with regards to how useful it is for integrating with TypeScript in the "Code in TypeScript but deliver JS files to the client" model (i.e. not using a TypeScript plugin).

I've prepared a sample project to hopefully demonstrate (readme.md has the steps required to build and run):
https://github.com/nycdotnet/defaultjsextensions-and-typescript

The example of the trouble centers around `web/myScript.ts`:

```typescript
import $ from 'jquery';
import iw from './myLibrary';

$("#result").html(iw);
```

This transpiles as:
```javascript
System.register(['jquery', './myLibrary'], function(exports_1) {
    "use strict";
    var jquery_1, myLibrary_1;
    return {
        setters:[
            function (jquery_1_1) {
                jquery_1 = jquery_1_1;
            },
            function (myLibrary_1_1) {
                myLibrary_1 = myLibrary_1_1;
            }],
        execute: function() {
            jquery_1.default("#result").html(myLibrary_1.default);
        }
    }
});
```

SystemJS is configured with this command:
```typescript
System.config({
  map: {
    'jquery': 'scripts/jquery/dist/jquery.min.js'
  },
  defaultJSExtensions: true
});
```

The code works wonderfully with `defaultJSExtensions` as `true`.  For any ambient definitions (such as 'jquery' in this case), we need to add a map entry, but there will likely be a set number per project that changes infrequently.  The **magic sauce** is that TypeScript is able to resolve the module './myLibrary' at compile-time as './myLibrary.ts', and SystemJS is able to resolve the same path as './myLibrary.js'.

Without `defaultJSExensions`, we have a problem.  The expectation of SystemJS is that we would have an import statement like this:
```typescript
import iw from './myLibrary.js';
```

However that doesn't work for TypeScript (`Cannot find module './myLibrary.js'.` - essentially it's looking for './myLibrary.js.ts').  While it would be possible to set up `map` entries for every script in a project, I think that seems like an unnecessary burden - though I suppose it could be automated as part of a build step.

I have a few ideas on how this might be fixed, but honestly continuing to support defaultJSExtensions would probably be the easiest.  We could perhaps also ask the TypeScript team to add a switch to append '.js' in the emit for module names when using module type System.  They seemed amenable to fixing the integration with SystemJS with regards to how default imports work for non-ES6 modules (will be fixed in TypeScript 1.8, currently in `typescript@next`), so perhaps they'd be willing to do this too.

**Comment by nycdotnet** [comment]
//cc: @weswigham @mhegazy @ahejlsberg
FYI: this was the fix for using the ES6 default import syntax with non-ES6 modules and TypeScript when using module type "system":  https://github.com/Microsoft/TypeScript/issues/5285

**Comment by guybedford** [comment]
The replacement for `System.defaultJSExtensions` is the package configuration `defaultExtension` option. The idea is that this becomes per-package configured. See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages.

**Comment by nycdotnet** [comment]
Thanks.

So to support the scenario I mentioned above, will this config be supported going forward?

```typescript
System.config({
  map: {
   'jquery': '/scripts/jquery/dist/jquery.min.js'
  },
  packages: {
    '': {
      defaultExtension: 'js'
    }
  }
});
```

Essentially the idea is that if the imported thing appears as a property of the `map` object, SystemJS will load the explicit path specified in the `map` entry, but if it does not appear as a `map` entry, SystemJS will load whatever path is specified plus `.js`.

Do I have that right?  If so, would you accept a PR for the docs?  I'll write it up.

**Comment by guybedford** [comment]
Because `/scripts/jquery/dist/jquery.min.js` is within the package that still goes through the package config, so you could have just as well have specified the map to `/script/jquery/dist/jquery.min`. 

Apart from that yes exactly although generally a catch-all package is discouraged. Rather have it for a `src` folder or similar.

**Comment by nycdotnet** [comment]
Hi,

Thanks for this info.  When you say a catch-all is discouraged, do you mean that you'd prefer to see some sort of namespacing with slashes?

If so, this might be tricky for folks using TypeScript because TS would need this mapping information to do its resolution at compile time.

I'll write up a PR for the docs soon.  Thanks!

**Comment by guybedford** [comment]
Yes exactly, but as long as you are sure you really intend `/` for defaultExtension. For example that will break loading other types of resources. Even just `/js` as the package name would be fine to restrict the resolution to that folder.

**Comment by pk-developer** [comment]
Probably it will help you 
https://github.com/TypeStrong/atom-typescript/issues/237#issuecomment-455837052
