### ISSUE TITLE
Importing a jquery and a jquery plugin doesn't work in combination

### ISSUE THREAD

**Issue by dmbrowne** [systemjs/systemjs#1048]
How exactly would I use/ configure system js to import a jquery plugin. I would like to import both `$` and `slick-carousel` in the same file and use them.

I'm using systemJs along with JSPM.

this is my system.config.js:
```js
{
  // rest of config clipped for demo purposes
  ...

  depCache: {
    'slick-carousel': ['jquery']
  },
  map: {
    "jquery": "github:components/jquery@2.1.4",
    "slick-carousel": "npm:slick-carousel@1.5.9"
  }

  ...
  // rest of config clipped for demo purposes
}
```

and this is my js file:
```js
import React, { PropTypes } from 'react';
import ReactDOM from 'react-dom';
import $ from 'jquery';
import slickCarousel from 'slick-carousel';

...

	componentDidMount () {
		let node = ReactDOM.findDOMNode(this);
		$(node).slick();
	}

...
```

The problem is, this doesn't work as I get the error `Uncaught TypeError: $(...).slick is not a function`. basically meaning that slick has not been loaded after jQuery.

<b>BUT if I remove the line `import $ from 'jquery';`, it works fine.</b>
*Whilst this may work, I would still like to implicitly import `$/ jQuery`, that way my editor doesn't tell me `$` hasn't been defined.* How do I do this?

**Comment by guybedford** [comment]
Use `deps` metadata for shimming rather -

```javascript
System.config({
  meta: {
    'slick-carousel': {
      deps: ['jquery']
    }
  }
});
```
