### ISSUE TITLE
Chrome devtools performance

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1054]
For some reason, Chrome devtools chokes up the performance considerably (up to 4x slower).

We need to work out exactly what is going on here, and if this is something we can mitigate, or a bug we can track on Chrome.

**Comment by guybedford** [comment]
Related: https://github.com/systemjs/systemjs/issues/908, https://github.com/JonahBraun/jspm-perf-test/issues/1.

**Comment by NervosaX** [comment]
Interestingly, if you go to the timeline tab in the chrome devtools, and start recording a timeline, the refresh is as quick as if the devtools are closed. I don't know what to make of this information...

**Comment by pangwa** [comment]
I met exactly the same issue with Chrome and systemjs. The load time is pretty long(1 minute or more) when the devtools window is open and checked the disable cache. 

I noticed there is a long time that the app seems to be hang(no xhr nor any output).

**Comment by unional** [comment]
Were this a Chrome issue and now is resolved? 🌷
