### ISSUE TITLE
No transpiler

### ISSUE THREAD

**Issue by amatiasq** [systemjs/systemjs#1057]
Related to https://github.com/ModuleLoader/es6-module-loader/issues/465

Since browsers are increasingly supporting ES6 I would like to use `SystemJS` without transpiler but it always tries to load `my-url.com/<System.transpiler>` how can I prevent this?

I understand this project is not only for ES6 modules so I don't understand transpiler to be mandatory here.

**Comment by guybedford** [comment]
You can set `System.config({ transpiler: false })` and it will then throw on the module it is trying to load as ES6. See also https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection.

**Comment by misterfresh** [comment]
Is it not possible to use System JS to load an ES6 module without transpiling it to ES5 ?
