### ISSUE TITLE
Resolved module is an empty object after directory restructure

### ISSUE THREAD

**Issue by mFingers** [systemjs/systemjs#1059]
I changed the directory structure of my JavaScript files from:

```
/Scripts
    config.js
    /jspm_modules
    <application specific files>
```
    
to

```
/Scripts
    config.js
    /jspm_modules
    /src
        <application specific files>
```

I bundle the files (using Gulp) as such:
```
var builder = new Builder('Scripts', 'Scripts/config.js');
builder.bundle('src/main.js', 'app/main.js', { minify: false });
```

- The only difference after the directory structure change is on the second line, where I qualify main.js with "src".
- `baseURL` in config.js is unchanged, as well (it's set to "app")

Prior to changing the directory structure, System.Import('main') worked just fine.  After the directory structure change, the resolved module that gets passed to the promise is just an empty object (it doesn't have any of my exported functions).

I did a diff on the transpiled code in app/main.js, and the only differences are the inclusion of "src" when loading modules (and in their variable names).

I'm sure I'm missing something simple here....

**Comment by mFingers** [comment]
I posted this to [StackOverflow](http://stackoverflow.com/q/35016525/182875), seemed more appropriate there?  I'll update this issue and close it when the SO is resolved.

**Comment by guybedford** [comment]
The names in the bundle will then be `src/...` so that your `System.import('main')` would need to become a `System.import('src/main')`. Alternatively you can set up a map for that - `System.config({ main: 'src/main' })`, or use a package configuration main.

**Comment by mFingers** [comment]
I knew it was something simple.  I hate to admit that understanding how the paths work has been a little bit of a problem for me....  Is [this the best source](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md) for documentation on this topic?

**Comment by guybedford** [comment]
It's definitely a priority to provide a better conceptual overview of SystemJS and how the resolution works. This is worth doing now that the project is finally stable as of 0.19.
