### ISSUE TITLE
Not pulling application typescript files from injected bundle

### ISSUE THREAD

**Issue by dougludlow** [systemjs/systemjs#1061]
I'm seeing an issue where I've created a bundle and injected it into the `config.js`, requests made for files in the bundle are loading the bundle **except** for the `.ts` files that actually make up the app.

When I reference the bundle in the html directly, things work just fine...

I'm not exactly sure where the issue resides, if it's an issue with plugin-typescript or with systemjs.

When I attempted to debug the code, I noticed that when the bundle was loaded from the config, the resulted decanonicalized modules had a `.js` extension appended to them. So my `app/boot.ts` would result in `http://localhost:5000/api/boot.ts.js`. It seems like the issue might be related to #670 and possibly #602, but those are both resolved.

I'm using jspm@0.16.25 which uses systemjs@0.19.17.

**Comment by guybedford** [comment]
Do you have a package configuration to ensure js extensions don't get added to the ts files? eg `packages: { api: { defaultExtension: 'ts' } }`. This is necessary even in the production app to ensure correct decanonialization.

**Comment by dougludlow** [comment]
@guybedford I do actually:

```
  packages: {
    "app": {
      "main": "boot",
      "defaultExtension": "ts",
      "meta": {
        "*.ts": {
          "loader": "ts"
        },
        "*.css": {
          "loader": "css"
        },
        "*.scss": {
          "loader": "scss"
        }
      }
    }
  },
```

**Comment by guybedford** [comment]
@dougludlow I believe this was fixed in https://github.com/systemjs/systemjs/commit/86be5c4ac790be35ad065bef031a0f2ebc1e93ce. This should be released Monday or Tuesday.
