### ISSUE TITLE
Can I define transpiler when calling import function?

### ISSUE THREAD

**Issue by PrimeObjects** [systemjs/systemjs#1067]

**Comment by guybedford** [comment]
No, configuration must be present during loading, and execution time is too late. You would need to configure then run System.import:

```javascript
System.transpiler = 'x';
System.import('y').then(...)
```

**Comment by PrimeObjects** [comment]
Hi Guybedford,

Thank you for the answer.

Will each change to transpiler apply globally? If I have some System.import import js and some import typescript on the same page, I have to change config right before calling everyone of them? Will it cause some conflict because of sharing the keep-changing global configuration even though it is not a real multi-thread lazy call environment?

Cheers
Gary

**Comment by guybedford** [comment]
@PrimeObjects it sounds like you want to be using loader plugins here rather than the transpiler.
