### ISSUE TITLE
Problem loading bundle: Multiple anonymous System.register calls in module

### ISSUE THREAD

**Issue by rsuter** [systemjs/systemjs#1068]
I have the following configuration in `index.html`: 

	System.config({
		baseURL: '/scripts',
		paths: {
			"package1/*": "package1/package.js"
		}
	});
	
	System.import('package1/a').then(null, console.error.bind(console));
	
The `package.js` file contains: 

	System.register('package1/a', [], function(exports_1) {
		...
	});

	System.register('package1/b', [], function(exports_1) {
		...
	});

When opening the `index.html` file, the following exception occurs: 

	Uncaught Error: Multiple anonymous System.register calls in module http://localhost:29569/scripts/package1/package.js. 
    If loading a bundle, ensure all the System.register calls are named.
	
However, all `System.register` calls are named and no anonymous calls are in the `package.js` file...

Is this a bug? Or am I using the library in a wrong way?

**Comment by guybedford** [comment]
Wildcard to single paths are not supported in this way. It sounds like you want to be using the bundles config rather:

```javascript
System.config({
  bundles: {
    'package1/package.js': ['package1/*']
  }
});
```

**Comment by guybedford** [comment]
Also because `package1/package.js` is within its own bundle config, that may cause a circular loading loop. It may be advisable to list the names manually, or not have the bundle within that path.

**Comment by rsuter** [comment]
It seems that bundles with wildcards (*) does not work... I have to list all modules manually...

**Comment by guybedford** [comment]
Bundle wildcards do work as of 0.19.17, but does require the bundle itself to be outside of the `package1` folder as mentioned - `bundles/package1.js` instead say. Just let me know if you have any further questions.

**Comment by rsuter** [comment]
ok, now it works... thx

**Comment by lilin1013** [comment]
I still have the same problem with following config
System.config({
            //    transpiler: 'typescript',
            //     typescriptOptions: { emitDecoratorMetadata: true },
            baseURL: '/',
            bundles: {
                "main_lib/build/composite.all.min.js": ["main_lib/src/*"]
            },
            packages: {
                'main_lib/src': {
                    defaultExtension: 'js',
                    map: {
                        app: "main_lib/src"
                    },
                }
            }
        });
        System.import('main_lib/src/boot.js').then(null, console.error.bind(console));

**Comment by lilin1013** [comment]
I still have the same problem with following config

```
`System.config({
            //    transpiler: 'typescript',
            //     typescriptOptions: { emitDecoratorMetadata: true },
            baseURL: '/',
            bundles: {
                "main_lib/build/composite.all.min.js": ["main_lib/src/*"]
            },
            packages: {
                'main_lib/src': {
                    defaultExtension: 'js',
                    map: {
                        app: "main_lib/src"
                    },
                }
            }
        });
        System.import('main_lib/src/boot.js').then(null, console.error.bind(console));`
```

**Comment by guybedford** [comment]
@lilin1013 does the `composite.all.min.js` file definitely contain named `System.register('main_lib/src/x'` statements?

**Comment by lilin1013** [comment]
@guybedford yes, it contains System.register('main_lib/src/x' statements.
when I bundle the files with systemjs builder it works. when I compare the difference, the output of systemjs builder contains "System.registerDynamic("main_lib/..." instead of "System.register("main_lib/".

**Comment by guybedford** [comment]
@lilin1013 could you perhaps share your full build file, or part of it? We may be able to improve the error message here.

**Comment by lilin1013** [comment]
bundle file from systemjs builder, which works
`System.registerDynamic("main_lib/node_modules/angular2/src/core/angular_entrypoint.js",["angular2/src/facade/lang"],!0,function(a,b,c){"use strict";var d=this,e=d.define;d.define=void 0;var f=this&&this.__decorate||function(a,b,c,d){var e,f=arguments.length,g=3>f?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)g=Reflect.decorate(a,b,c,d);else for(var h=a.length-1;h>=0;h--)(e=a[h])&&(g=(3>f?e(g):f>3?e(b,c,g):e(b,c))||g);return f>3&&g&&Object.defineProperty(b,c,g),g},g=this&&this.__metadata||function(a,b){return"object"==typeof Reflect&&"function"==typeof Reflect.metadata?Reflect.metadata(a,b):void 0},h=a("angular2/src/facade/lang"),i=function(){function a(a){this.name=a}return a=f([h.CONST(),g("design:paramtypes",[String])],a)}();return b.AngularEntrypoint=i,d.define=e,c.exports}),System.registerDynamic("main_lib/node_modules/angular2/src/common/pipes/async_pipe.js",["angular2/src/facade/lang","angular2/src/facade/async","angular2/core","./invalid_pipe_argument_exception"],!0,function(a,b,c){"use strict";var d=this,e=d.define;d.define=void 0;var f=this&&this.__decorate||function(a,b,c,d){var e,f=arguments.length,g=3>f?b:null===d?d=Object.getOwnPropertyDescriptor(b,c):d;if("object"==typeof Reflect&&"function"==typeof Reflect.decorate)g=Reflect.decorate(a,b,c,d);else for(var h=a.length-1;h>=0;h--)(e=a[h])&&(g=(3>f?e(g):f>3?e(b,c,g):e(b,c))||g);return f>3&&g&&Object.defineProperty(b,c,g),g},g=this&&this.__metadata||function(a,b){return"object"==typeof Reflect&&"function"==typeof Reflect.metadata?Reflect.metadata(a,b):void 0},h=a("angular2/src/facade/lang"),i=a("angular2/src/facade/async"),j=a("angular2/core"),k=a("./invalid_pipe_argument_exception"),l=function(){function a(){}return...`

**Comment by lilin1013** [comment]
bundle from uglify, which does work
`System.register(["angular2/platform/browser","main_lib/src/components/app.component.js"],function(a){"use strict";var b,c;return{setters:[function(a){b=a},function(a){c=a}],execute:function(){b.bootstrap(c.AppComponent)}}});System.register(["angular2/core","./header/header.component"],function(a){var b=this&&this.__decorate||function(a,b,c,d){var e=arguments.length,f=e<3?b:d===null?d=Object.getOwnPropertyDescriptor(b,c):d,g;if(typeof Reflect==="object"&&typeof Reflect.decorate==="function")f=Reflect.decorate(a,b,c,d);else for(var h=a.length-1;h>=0;h--)if(g=a[h])f=(e<3?g(f):e>3?g(b,c,f):g(b,c))||f;return e>3&&f&&Object.defineProperty(b,c,f),f};var c=this&&this.__metadata||function(a,b){if(typeof Reflect==="object"&&typeof Reflect.metadata==="function")return Reflect.metadata(a,b)};var d,e;var f;return{setters:[function(a){d=a},function(a){e=a}],execute:function(){f=function(){function a(){}a=b([d.Component({selector:"my-app",template:"\n        <header-app></header-app><div></div>\n    ",directives:[e.HeaderComponent],styleUrls:["main_lib/assets/styles/reset.css","main_lib/assets/styles/app.component.css"]}),c("design:paramtypes",[])],a);return a}();a("AppComponent",f)}}});
//# sourceMappingURL=../sourceMap.map`

**Comment by guybedford** [comment]
@lilin1013 the `System.register(["angular2/platform/browser","main_lib/src/components/app.component.js"]` shows that the statement is unnamed as it starts with an array instead of a string. This is exactly what the error message is referring to that it expects the module names to be provided in the bundle. Whatever tool you are using to generate this file, you'd need to ensure it provides this name string.

**Comment by lilin1013** [comment]
@guybedford I understand now. Thanks you !
