### ISSUE TITLE
index.js mapping affects folder paths

### ISSUE THREAD

**Issue by bisubus** [systemjs/systemjs#1069]
In [this plunker](http://plnkr.co/edit/Eprl516NZAVBv5TMrxQw?p=preview) it is evident that

      map: {
        './folder': './folder/index.js' 
      }

mapping in package affects all paths in `folder`, and `folder/index.js/piece.js` is being requested instead of `folder/piece.js`:

> Error: XHR error (404 Not Found) loading http://run.plnkr.co/rLC9WsoHvasLp8ee/package/folder/index.js/piece.js

Is there a documented way to avoid this behaviour, or is this a bug?

SystemJS 0.19.

**Comment by guybedford** [comment]
`map` configuration always does folder mappings. Paths configuration does not do folder mappings by default.

**Comment by bisubus** [comment]
@guybedford I see. But how is it going to work for the packages that do

    require('./folder');

and not

    require('./folder/index');

? Both variants can be are found in NPM packages, and the latter is much less popular due to excessive verbosity.

**Comment by guybedford** [comment]
@bisubus see [package configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages). Map can map into packages.
