### ISSUE TITLE
Bring URL polyfill into core

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1070]
The polyfill seems to have been added in 0.19.17. I personally use core-js (with babel) where the polyfill isn't included and I wouldn't want to include the system-polyfill since that would mean a lot of duplicated polyfills. Would you consider putting the URL polyfill in the main file?

**Comment by guybedford** [comment]
I'm not sure I follow?

**Comment by Mosho1** [comment]
The polyfill here:

https://github.com/systemjs/systemjs/blob/master/dist/system-polyfills.src.js#L7-L75

Since I use core-js to polyfill (for systemjs and other things), I have to add that one manually, as systemjs 0.19.17 won't work without it (but works with core-js instead of system-polyfills).

**Comment by guybedford** [comment]
It would be worth considering including it, and then even removing the auto-loading of polyfills and just telling users to use their own Promise polyfills. We'd need to do this in the next breaking release though. There will be the 0.20 deprecation release in the next month or so.

**Comment by Mosho1** [comment]
Sounds good, thanks!

**Comment by guybedford** [comment]
We can still bring URL into core while keeping that as a backwards compatible change (polyfills then just become promise, before being removed entirely)

**Comment by probins** [comment]
> removing the auto-loading of polyfills and just telling users to use their own Promise polyfills

+1

**Comment by guybedford** [comment]
Implemented in https://github.com/systemjs/systemjs/commit/18be7fa917e2004b6a368ee38afe800014cb13bc.

**Comment by Mosho1** [comment]
Thanks!

**Comment by guybedford** [comment]
Released in 0.19.25.
