### ISSUE TITLE
Getting define is not a function though add meta description

### ISSUE THREAD

**Issue by mazzy89** [systemjs/systemjs#1073]
My config is the following:

```javascript
<script>
      System.config({
        defaultJSExtensions: true,
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js',
            map: {
              esri: '//js.arcgis.com/3.15/esri'
            },
            meta: {
              'esri/*': {
                format: 'amd'
              }
            }
          }
        }
      });

      System.import('app/main')
        .then(null, console.error.bind(console));
    </script>
```

This is one of the file in my project which import `esri`

```typescript
import esri = require('esri');
import Map = require('esri/map');
import AGSPoint = require('esri/geometry/Point');

import { Component } from 'angular2/core'

@Component({
  templateUrl: 'app/home/home.html',
  styleUrls: [ 'app/home/home.css' ],
})
export class Home {
  map: Map;

  contructor() {
    this.map = this.createMap();
  }

  private createMap(): Map {
    const point = new Point(-122.45, 37.75); // long, lat
    point.log();

    const mapOptions: esri.MapOptions = {};
    mapOptions.basemap = "topo";
    mapOptions.center = point;
    mapOptions.zoom = 13;

    return new Map("map", mapOptions);
  }
}

class Point extends AGSPoint {

  log() {
    console.log(this.type, this.x, this.y);
  }
}
```

I get the error 

`Uncaught TypeError: define is not a function`

though I've added meta in the config. Any idea?

**Comment by amenadiel** [comment]
You need to add 

```js
window.define = System.amdDefine;
```

I guess esri libs are counting on a global `define` function.

**Comment by mazzy89** [comment]
@amenadiel where should I add it?

**Comment by mazzy89** [comment]
I've added it before System.config but still doesn't work

**Comment by mazzy89** [comment]
If I print window.define is not null and when I execute windows.define = System.amdDefine I get more error.

**Comment by amenadiel** [comment]
This is what I have in my `<head>` tag

```js
<script src="/jspm_packages/system.js"></script>
<script>
    window.define = System.amdDefine;
    window.require = System.amdRequire;
</script>
<script src="/config.js"></script>
<script>
	System.import('/js/app');
</script>
```

**Comment by mazzy89** [comment]
@amenadiel This is what I get:

``javascript
<html>

  <head>
    <base href="/">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Home</title>

    <link rel="stylesheet" href="//js.arcgis.com/3.15/esri/css/esri.css">
    <style></style>

    
    <script src="es6-shim/es6-shim.min.js"></script>
    <script src="systemjs/dist/system-polyfills.js"></script>

    <script src="angular2/bundles/angular2-polyfills.js"></script>
    <script src="systemjs/dist/system.src.js"></script>
    <script src="rxjs/bundles/Rx.js"></script>
    <script src="angular2/bundles/angular2.dev.js"></script>
    
    <script src="angular2/bundles/router.dev.js"></script>

    
    <script src="//js.arcgis.com/3.15/"></script>
    <script>
      window.define = System.amdDefine;
      window.require = System.amdRequire;
    </script>
    <script>

      System.config({
        defaultJSExtensions: true,
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js',
            map: {
              esri: '//js.arcgis.com/3.15/esri'
            },
            meta: {
              esri: {
                format: 'amd'
              }
            }
          }
        }
      });
    </script>
    <script>
      System.import('app/main')
        .then(null, console.error.bind(console));
    </script>
  </head>

  <body>
    <app>Loading map...</app>
  </body>

</html>
```javascript

And get the following error:

[https://www.dropbox.com/s/75p84kp8ifmiyt6/Screenshot%202016-02-03%2012.11.56.png?dl=0](url)

**Comment by guybedford** [comment]
@mazzy89 the error is actually exactly that the code is doing an invalid require within the AMD. If you expand the `Invalid Require` error message it should point out the line that is happening on in esri, where there will likely be an `x(...)` form. It would be interesting to know what that is to see if we can support it, but looking at the code for esri it seems to use a lot of very specific named AMD patterns that may be tricky to match. It may well be possible though.

**Comment by mazzy89** [comment]
@guybedford in other words there is nothing I can do now to work with esri in that way :-) need to figure out some other way.

**Comment by amenadiel** [comment]
I'm sure it doesn't solve things, but you're calling esri's JS before declaring `windows.define`. You should try

```js
<script>
      window.define = System.amdDefine;
      window.require = System.amdRequire;
</script>
<script src="//js.arcgis.com/3.15/"></script>
```

However, I'm puzzled at the script loading explicitly and then defining a mapping. How are you calling esri's libs in your main script? 

I also don't understand where is it configured that the entry point is `http://js.arcgis.com/3.15/init.js`.

**Comment by mazzy89** [comment]
@amenadiel I've tried but without luck.
