### ISSUE TITLE
Mangled characters pretending to be a sourcemap, corrupting files

### ISSUE THREAD

**Issue by nateabele** [systemjs/systemjs#1074]
So, this is definitely one of the weirder bugs I've encountered, but I'll see if I can step you through it. My HTML looks like this:

```html
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script src="depends.js"></script>

<script>
System.sourceMaps = false;
System.trace = true;
System.import('playground').catch(console.log.bind(console));
</script>
```

This is the file I'm importing (it does nothing):

```javascript
import { Observable } from 'rxjs/Observable';
```

In the browser, it transpiles to:

```javascript
(function(System) {(function(__moduleName){System.register([], function(exports_1) {
    return {
        setters:[],
        execute: function() {
        }
    }
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxheWdyb3VuZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInBsYXlncm91bmQuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9
})("http://foobar.dev:8000/src/playground.js");
})(System);
```

However, after running `jspm bundle 'rxjs' + 'typescript' rx-ts.js --inject --skip-source-maps --minify`, and adding a `<script />` tag for `rx-ts.js` just below `depends.js`, `playground.js` gets transpiled to this:

```javascript
(function(System) {(function(__moduleName){System.register([], function(exports_1) {
    return {
        setters:[],
        execute: function() {
        }
    }
});
eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxheWdyb3VuZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInBsYXlncm91bmQuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9
})("http://foobar.dev:8000/src/playground.js");
})(System);
```

...which gives me `Uncaught ReferenceError: eyJ2ZXJzaW9uIjozLCJma[...] is not defined`. Somehow, injecting Rx and TypeScript via a separate `<script />` tag is corrupting source map generation, such that it loses the `//# sourceMappingURL=data:application/json;base64,` prefix.

Any ideas? I'm on SystemJS 0.19.18.

**Comment by guybedford** [comment]
I take it you have `transpiler: 'typescript'` set here?

**Comment by nateabele** [comment]
Yes, sorry. I was able to solve the problem by disabling sourcemaps entirely in `typescriptOptions`, but obviously that's not ideal, and does nothing about the underlying issue. I'll put together a minimal reproduction in a plunkr later today, but let me know if there's anything else I can do to solve this in the meantime.

**Comment by guybedford** [comment]
Did you manage to find what the replication was here? Did you say the source map was removed during bundling itself? If so, then that would either be TypeScript or the SystemJS builder. We do source map removal with the regex at https://github.com/systemjs/builder/blob/master/lib/sourcemaps.js#L12, but that doesn't look like it would choke on `//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxheWdyb3VuZC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInBsYXlncm91bmQuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiJ9` here.

**Comment by nateabele** [comment]
Yeah, sorry, I wasn't able to reproduce it online. It's only an issue when running `jspm bundle`. Should I report it to [jspm/jspm-cli](https://github.com/jspm/jspm-cli) instead?

**Comment by guybedford** [comment]
If you can provide a reliable replication through jspm, certainly please do.
