### ISSUE TITLE
Please help, can't load a node module that has more requirements...

### ISSUE THREAD

**Issue by born2net** [systemjs/systemjs#1076]
I am trying to load via system.js a package: https://www.npmjs.com/package/is-equal

and inside is-equal it requires more internal dependencies: https://github.com/ljharb/is-equal/blob/master/index.js

and so system.js blows up as it can't resolve the further dependencies. as in

GET http://localhost:8080/node_modules/is-arrow-function.js 404 (Not Found)
any help is appreciated as I tried for 2 days to resolve this... HELPPP!!!

reference: https://github.com/born2net/studioEnterprise/blob/master/src/public/index_sys.html
regards

Sean.

**Comment by guybedford** [comment]
Yes, SystemJS does not follow the Node resolution so custom configuration is needed to route to the correct files, which can be quite detailed config.

jspm is designed to solve this resolution problem with `jspm install npm:is-equal`.

**Comment by born2net** [comment]
I thought google was broken as I could not find any solution :)
so let me ask, I tried to use browserify to rectify the issue, making signle bundle from that node package, but that also blew up system.js, any idea why?

**Comment by guybedford** [comment]
@born2net browserify and webpack use Node-style resolution, which is a completely different resolution system to SystemJS. It's best to pick an approach.
