### ISSUE TITLE
System.import 3.5x slower than directly calling module

### ISSUE THREAD

**Issue by bnolan** [systemjs/systemjs#1079]
If I have a module that I import using system.import, it is slower than importing that module by calling the module code directly.

[Codepen](http://codepen.io/anon/pen/YwOrmz).

    call in for loop: 101.268ms
    call from promise: 9160.368ms
    call using system.import: 32364.076ms

Code:

    (function() {
    	var _removeDefine = System.get("@@amd-helpers").createDefine();

    	define("template.html", [], function() {
    	  return "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>"
    	});

    	_removeDefine();
    })()

    var x = function () {
    	return "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>"
    }

    var reps = 100000;

    console.time('call using system.import');
    Promise.all(Array.from({ length: reps }).map(function () { 
    	return System.import("template.html") 
    })).then(() => { 
    	console.timeEnd('call using system.import');
    })

    console.time('call from promise');
    Promise.all(Array.from({ length: reps }).map(function () { 
    	return Promise.resolve(x());
    })).then(() => { 
    	console.timeEnd('call from promise');
    })

    console.time('call in for loop');
    for(i=0;i<reps;i++) {
    	y = x();
    }
    console.timeEnd('call in for loop');

We have about 250 modules in our app and it is making the load time extremely slow. The loading and parsing of the javascript by the browser is a negligible amount of time, compared to how long system takes to resolve imports.

**Comment by bnolan** [comment]
I would've imagined that the result of calling the function would be memoized by system and so would resolve instantly, and the difference between 'call frmo promise' and 'call using system.import' would be negligible.

Tested in chrome.

**Comment by bnolan** [comment]
Same behaviour in firefox. I think the `for()` loop timing is a bit confusing because the javascript runtimes probably realise you're doing the same thing 10000 times and inlines it.

**Comment by guybedford** [comment]
3 times slower doesn't sound bad at all here, considering it's the difference between a direct `Promise.resolve`, and a 5 - 10 step lookup in SystemJS. Purely by the number of lines of code being run that sounds about right.

I understand if you're having perf issues though. Are you running all your code as a bundle? Not a self executing bundle? Note there is also a Chrome devtools bug that results in much slower execution of bundles with devtools open (currently unexplained).

The loader pipeline does introduce overhead above and beyond direct code analysis of course. The other constraint SystemJS has is that by using a spec for "correctness", there is a performance cost to that.

**Comment by bnolan** [comment]
I wrote a brain-dead system fast loader for production that doesn't try to resolve circular dependencies, and doesn't use any promises.

On a subset sample of our app:

> With system - calling System.import takes 2300ms.
> With system-fast-loader - calling System.import takes 448ms.
> That's importing 83 modules.
> On a $30 android phone

Might be interesting to someone:

https://github.com/bnolan/system-fast-loader/blob/master/index.js

If we end up using it I'll polish it up and people can use it as an alternative to the full system loader in production.

**Comment by guybedford** [comment]
@bnolan nice work supporting the semantics. Without dynamic loading, this looks very similar to the SystemJS Builder SFX core https://github.com/systemjs/builder/blob/master/templates/sfx-core.js, but just exposed to the global window as `System`? What sort of use cases is this aiming to solve that SFX builds don't already?

**Comment by guybedford** [comment]
(See https://github.com/systemjs/builder/blob/master/templates/sfx-core.js#L393 for the exact line where the source makes the most sense)
