### ISSUE TITLE
bundles - locate hook: Unsafe for ... in loop which iterates over Array.prototype additions

### ISSUE THREAD

**Issue by peterjuras** [systemjs/systemjs#1080]
Hi!

The [locate hook (line 37)](https://github.com/systemjs/systemjs/blob/master/lib/bundles.js#L37) contains a for ... in loop which does not check whether the bundle b is a true property or a [prototype addition of the array](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...in#Iterating_over_own_properties_only). 

This leads to errors in some browsers (like PhantomJS), where Array.prototype additions are being added and will mistakenly be treated as a bundle. Example:

```js
Array.prototype.find = function() {}; // polyfill
const array = [];
for (val in array) {
  console.log(val);
}
```
In this example, nothing will be logged in e.g. chrome, but in PhantomJS 'find' will be logged.

One possible fix for this issue would be to check whether the bundle b is a true property of the object (or item within the array):

```js
// ...
if (!(load.name in loader.defined))
  for (var b in loader.bundles) {
    // INSERTED CODE
    if (!loader.bundles.hasOwnProperty(b)) {
      continue;
    }
    // END INSERTED CODE
    for (var i = 0; i < loader.bundles[b].length; i++) {
      // ...
```

**Comment by chauthai** [comment]
+1

**Comment by guybedford** [comment]
Out of interest, what Object prototype extensions are you using here?

**Comment by peterjuras** [comment]
We were using the [Polyfill for Array.prototype.find](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill), but we changed that now to the one from the babel/polyfill which makes everything working again without a fix in systemjs.

I still think that the loop should be careful about only looping through true array entries (maybe even using array.forEach instead), since this might not be the only usecase which breaks the loop.

**Comment by guybedford** [comment]
@peterjuras `bundles` is an object not an array though, and I don't know of Object.prototype polyfills currently that would upset that functioning.

**Comment by peterjuras** [comment]
Interesting, I can investigate this further tomorrow. I think I had a console.log in there which showed me that it was an empty array (maybe I didn't look right and saw the wrong braces), also why did setting Array.prototype.find impact an Object then? This might be due to curious behavior in PhantomJS then.

I'll let you know more once I investigated this further.

**Comment by peterjuras** [comment]
I can't reproduce the error anymore, but I still have weird behavior when it comes to the type of _loader.bundles_. In Chrome, bundles is and remains an Object. In Karma + PhantomJS however, it's type seems to switch(?) from Object to array:

This modified code (inserted console.log statements):
```js
/// ...
(function() {
  // bundles support (just like RequireJS)
  // bundle name is module name of bundle itself
  // bundle is array of modules defined by the bundle
  // when a module in the bundle is requested, the bundle is loaded instead
  // of the form SystemJS.bundles['mybundle'] = ['jquery', 'bootstrap/js/bootstrap']
  hookConstructor(function(constructor) {
    return function() {
      constructor.call(this);
      this.bundles = {};
      console.log('hookConstructor: this.bundles is: ' + JSON.stringify(this.bundles));
      this._loader.loadedBundles = {};
    };
  });

  // assign bundle metadata for bundle loads
  hook('locate', function(locate) {
    return function(load) {
      var loader = this;
      console.log('hookLocate: this.bundles is ' + JSON.stringify(this.bundles));
      var matched = false;
// ...
```
Results in this console output:
```bash
PhantomJS 2.1.1 (Mac OS X 0.0.0) LOG: 'hookConstructor: this.bundles is: {}'
PhantomJS 2.1.1 (Mac OS X 0.0.0) LOG: 'hookConstructor: this.bundles is: {}'
PhantomJS 2.1.1 (Mac OS X 0.0.0) LOG: 'hookLocate: this.bundles is []'
```

So it appears that the loader.bundles suddenly becomes an array. I'm not sure on which code is run in between these two functions, but I couldn't find any new assignments to bundles.

**Comment by peterjuras** [comment]
It might have something to do with how [karma-jspm is initializing jspm.](https://github.com/Workiva/karma-jspm/blob/7abacf6ad0304d09b30a2fad710f225585d5001b/src/adapter.js#L47)

**Comment by guybedford** [comment]
Yes that's incorrect. Closing as it's a Karma-jspm issue. Note that I'm not sure how well karma-jspm is maintained. It may also be worth looking at Karma SystemJS.

**Comment by peterjuras** [comment]
Thanks for your patience and the pointer to karma systemjs!
