### ISSUE TITLE
Behavior of meta.deps configuration changed

### ISSUE THREAD

**Issue by scvnc** [systemjs/systemjs#1082]
I noticed that when I define dependencies in `meta` section of the config they aren't necessarily being loaded as I anticipated anymore.

Essentially I have some common internal libraries that depend on each other by global variables/cjs.  I can replicate this issue in this example:

      paths: {
        "github:*": "jspm_packages/github/*",
        "npm:*": "jspm_packages/npm/*",
        "my.internal.lodash": "//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.2.1/lodash.min.js",
        "my.internal.lib": "dep2.js"
      },

      meta: {
        "my.internal.lodash": {
          "build": false,
          "format": "global"
        },
        "my.internal.lib": {
          "build": false,
          "deps": [
            "my.internal.lodash"
          ],
          "format": "global"
        }
      }

When I invoke `System.import('my.internal.lib');` I expect `my.internal.lodash` to be loaded and provided to `my.internal.lib`

In System.js 0.19.17 this works fine. In System.js 0.19.18 this no longer works.  Is this a feature regression or perhaps there is an alternative convention for doing this?

Here is a repository illustrating the issue:
https://github.com/scvnc/systemjs-deps-behavior-change

Observe the console output while using 0.19.17 versus latest

http://scvnc.github.io/systemjs-deps-behavior-change/index-systemjs-0.19.17.html
http://scvnc.github.io/systemjs-deps-behavior-change/index.html

**Comment by guybedford** [comment]
Thanks for the clear description, yes that is a regression. I believe I've added a fix in https://github.com/systemjs/systemjs/commit/dc0b5114b74cb57ebaaac32f5e19f5e92c7a1bdc, feel free to try out the patch, otherwise the next release will likely be in the next week or so.

**Comment by guybedford** [comment]
Actually this is a critical regression... I'll post out a release now.

**Comment by scvnc** [comment]
:+1: Thanks for your prompt fix.  It appears to work again when I use the version tagged in `0.19.20`
