### ISSUE TITLE
bundle config no longer triggering loading of bundle file

### ISSUE THREAD

**Issue by mwhite** [systemjs/systemjs#1083]
Some change from 0.19.17 to 0.19.20 inclusive caused the behavior of the following code to change from requesting `main.min.js` to requesting `src/main.js`:

```html
 <script src="/static/jspm_packages/system.js"></script>
  <script>
    System.config({
      baseURL: '/static/',
    });
  </script>
  <script src="/static/config.js"></script>  <!-- no bundles config -->
  
  <script>
    System.config({
      bundles: {
        'main.min': ['src/main']
      }
    });

    System.import('src/main');
  </script>
```

**Comment by guybedford** [comment]
Am I right in assuming that you do not have `defaultJSExtensions: true` set here?

**Comment by mwhite** [comment]
I do have `defaultJSExtensions: true` in `config.js` and that hasn't changed.

**Comment by guybedford** [comment]
Can you share your full configuration then? Also can you share the output of `console.log(JSON.stringify(System.bundles, null, 2))`?

**Comment by mwhite** [comment]
config.js: https://gist.github.com/mwhite/ce2637d19842a28cdd48

I switched back to 0.19.16 and when downloading 0.19.20 locally to try to reproduce again I'm not able to get the same problem, but there are some aspects to my SystemJS setup that change based on environment configuration, so I'm not 100% sure I'm reproducing correctly.

I was thinking maybe the cause of this might be obvious to you as one of the handful of commits since 0.19.16.  If not, then it's not a big deal with me if you don't want to investigate further unless someone else experiences the same issue.

Thanks!

**Comment by saimahaji** [comment]
Even when i upgrade from 0.19.16 to 0.19.20, its not loading file and giving error in some of modules unnecessarily.  defaultJSExtensions: true is set.

**Comment by guybedford** [comment]
Sure, just let me know if you have further problems though.
