### ISSUE TITLE
Change introduced in SystemJS v0.19.18 breaks HeinrichFilter/systemjs-plugin-googlemaps

### ISSUE THREAD

**Issue by HeinrichFilter** [systemjs/systemjs#1085]
I'm trying to fix systemjs-plugin-googlemaps. Specifically HeinrichFilter/systemjs-plugin-googlemaps#6

When I run the plugin with JSPM v0.16.25 (SystemJS v0.19.17) it works but with JSPM v0.16.26 (SystemJS v0.19.18) it fails with a `No 'Access-Control-Allow-Origin' header is present` error since the plugin doesn't get invoked.

I'm not sure the plugin and it's documentation was ever 100% correct. I would therefore appreciate any feedback to fix and improve the plugin.

# Steps to reproduce problem:
```
npm install jspm --save-dev
jspm init -y
jspm install systemjs-googlemaps=github:HeinrichFilter/systemjs-plugin-googlemaps
```

Update config.js to:
```js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    //...
    "google-maps": "https://maps.googleapis.com/maps/api/js"
  },

  meta: {
    "google-maps": {
      "build": false,
      "loader": "systemjs-googlemaps"
    }
  },

  map: {
    "systemjs-googlemaps": "github:HeinrichFilter/systemjs-plugin-googlemaps@0.1.1",
   //...
  }
});
```

Then `import GoogleMaps from 'google-maps';` causes the following error:
```
XMLHttpRequest cannot load https://maps.googleapis.com/maps/api/js.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.
```

# Steps to "fix" problem:
In `package.json` add:
```
"dependencies": {
    "jspm": "0.16.25"
  },
```
Run:
`rm -rf node_modules/ && rm -rf jspm_packages/ && npm install && jspm install`

Then the map loads as expected.

Related issues:
systemjs/builder#493

**Comment by guybedford** [comment]
Try altering your Google maps meta configuration to:

```javascript
meta: {
    "google-maps": {
      "build": false,
      "loader": "systemjs-googlemaps",
      "scriptLoad": true
    }
  },
```

**Comment by guybedford** [comment]
Sorry, that's wrong - the issue is that the `.js` extension is getting added. This was a valid regression actually, as paths are supposed to add the `js` extensions when using `defaultJSExtensions`.

**Comment by guybedford** [comment]
Try adding the following configuration to fix:

```javascript
System.config({
  packages: {
    'https://maps.googleapis.com': {
      defaultExtension: false
    }
  }
});
```

**Comment by HeinrichFilter** [comment]
Thanks you very much @guybedford, that works!

Now I can also get rid of the hack that manually removed the ".js" extension :smile:  (HeinrichFilter/systemjs-plugin-googlemaps@c4fd61927ceb98d5261e8632d86440d1b1f35210)

Would you mind if I create a PR to add the plugin to the SystemJS README? Or are there other things that should be improved first?

**Comment by guybedford** [comment]
Sure, feel free to send a PR.
