### ISSUE TITLE
Q: scriptLoad in production?

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1086]
The [`scriptLoad`](https://github.com/systemjs/systemjs/blob/7c2dd14b824eecea7d3252917fbc0918bc739a2c/lib/scriptLoader.js#L4) meta option is not really documented. My understanding is that it substitutes the default XHR loader for the `<script async>` loader mechanism (similar to RequireJS). This seems to solve a bunch of eval/sourcemaps issues in Firefox and IE/Edge in development. My question is: how safe is it in production? Are there performance implications? Are there any caveats to using it as the default setting?

(By production I mean using bundling and the `System.register(Dynamic)` format exclusively.)

**Comment by guybedford** [comment]
The cost of `scriptLoad` is that the AMD define must be owned by SystemJS for AMD, and the global `System` must be SystemJS as well. Then loading of CommonJS and in-browser transpilations are not supported. Effectively the System-CSP build is equivalent to `meta: { '*': { scriptLoad: true } }`.

**Comment by guybedford** [comment]
(apart from that though, `scriptLoad` is very robust though)
