### ISSUE TITLE
Benchmark.js issue

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#1087]
There is something going wrong when using [Benchmark.js](http://benchmarkjs.com/) with SystemJS / JSPM.  
There is also an issue with Webpack, but I'm not sure if that's related: https://github.com/bestiejs/benchmark.js/issues/106

When installing it with jspm from npm and run the following code, it fails on a line that requires `_` (lodash). So there is probably something going wrong with dependencies. 
``` javascript
import Benchmark from 'benchmark';
console.log('Benchmark(): ', Benchmark());
```

Also see: https://github.com/bestiejs/benchmark.js/issues/120

**Comment by guybedford** [comment]
It sounds like a configuration issue, let's track that in https://github.com/jspm/registry/issues/751 rather.
