### ISSUE TITLE
Normalization issue with package dependencies (with modified config js)

### ISSUE THREAD

**Issue by VivekPMenon** [systemjs/systemjs#1088]
Systemjs doesn't seem to normalize the dependencies of remotely fetched packages (in my case css plugin). For instance, our config looks like below (it is programmatically overwritten by us for specific reasons and it happens during deployment phase). when it is run on consumer apps, it is not able to find "css" package. Systemjs is looking it up in http://localhost/css.js path and it fails. Css plugin is actually present in http://localhost/jspm_packages/github/systemjs folder as it was generated during jspm install npm:remote-component. 

Can you please guide what is wrong with the whole setup?

```json
map: {
    "remote-component": "http://xxxxxx.com/remote-component/dist/index",  
    "http://xxxxxx.com/remote-component/dist/index": {
        "bootstrap": "github:twbs/bootstrap@3.3.6",
        "css": "github:systemjs/plugin-css@0.1.20"
     }   
}
```
 Failing at below statement

`import 'bootstrap/dist/css/bootstrap.css!css';`

**Comment by guybedford** [comment]
Contextual map is based on the package name, not the module name. It's also been renamed to package map. Try using:

```javascript
packages: {
    "http://xxxxxx.com/remote-component": {
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
}
```

**Comment by VivekPMenon** [comment]
Thanks for the reply. I tried the below and still the same issue. We are using jspm version  0.16.24.

```json
packages: {
    "http://xxxxxx.com/remote-component/dist/index": {
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
},
map: {
    "remote-component": "http://xxxxxx.com/remote-component/dist/index"
}
```

Please let me know if i am missing something here.

**Comment by guybedford** [comment]
Node that I left out the `dist/index` in the package config - packages are folder boundaries not modules (files).

**Comment by VivekPMenon** [comment]
Yes I did notice that and had tried below combination as well, with no success. 

```json
 packages: {
    "http://xxxx.com/remote-component": {
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
  },
  map: {
    "remote-component": "http://xxxx.com/remote-component"
  }
```
resulted in http://xxxx.com/remote-component.js not found error when i do 

`import 'remote-component';` 

Is  it like i should not have the package name inside the general map section ("remote-component": "http://xxxx.com/remote-component"), instead my source files should do import using the package name itself like below.

`import 'http://xxxx.com/remote-component';`

please let me know.

**Comment by VivekPMenon** [comment]
I tried below as well which resulted in the original error i was getting before (http://xxxx.com/css.js not found) 

```json
  packages: {
    "http://xxxx.com/remote-component": {
        main: "dist/index",
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
  },
  map: {
    "remote-component": "http://xxxx.com/remote-component"
  }
```

**Comment by guybedford** [comment]
What is the content of the index file? It sounds like it's not just doing a `import 'css'` then?

**Comment by VivekPMenon** [comment]
Here is all I have in Index.js and related file (non transpiled version).

**Index.js**
`import './feature1/feature1';`


**feature1.js**
```
import * as angular from 'angular';
import 'bootstrap/dist/css/bootstrap.css!css';

//angular module and directive definition stuff
```

**Comment by VivekPMenon** [comment]
Stepped through the SystemJs code and could find what the issue is.

in getPackage function, for loop iteration, name of the parent and name of the package is compared without toUpper or toLower. It may not be a bug as they would always be in lower case in default configjs. It was not working for us because, while we modify config.js we capitalize the remote endpoint and hence package resolution never worked.

Thanks for your guidance.

**Comment by guybedford** [comment]
@VivekPMenon can you share clearly where the casing issue is coming in? SystemJS is case sensitive yes.

**Comment by VivekPMenon** [comment]
Here is it. please notice server name ABCDEFG in capital letter in both packages and map section.

**Not able to resolve when config js is**

```json
packages: {
    "http://ABCDEFG.domain.com/remote-component": {
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
  },
  map: {
    "remote-component": "http://ABCEFG.domain.com/remote-component"
  }
```

**Able to resolve when it is**

```json
packages: {
    "http://abcdefg.domain.com/remote-component": {
        map: {
          "bootstrap": "github:twbs/bootstrap@3.3.6",
          "css": "github:systemjs/plugin-css@0.1.20"
        }
     }   
  },
  map: {
    "remote-component": "http://abcdefg.domain.com/remote-component"
  }
```

**Comment by guybedford** [comment]
It sounds like this would be the case if there is an implicit 301 redirect or something like that.

If you navigate to `http://ABCDEFG.domain.com/remote-component` in the browser, does that automatically redirect to the uncased version?

**Comment by VivekPMenon** [comment]
that's right. i get a 301 when i put the address on browser.

**Comment by guybedford** [comment]
Yes this would just be about ensuring all references use the same casing then.

**Comment by VivekPMenon** [comment]
That's right. Thanks for the guidance and quick response.
