### ISSUE TITLE
Clobbering existing global.System

### ISSUE THREAD

**Issue by RGBboy** [systemjs/systemjs#1090]
If I import systemjs into node, any existing global.System gets clobbered by it.

**Comment by guybedford** [comment]
Marked for the 0.20 release.

**Comment by guybedford** [comment]
This had to be reverted for SystemJS 0.20 in order to cater to AngularJS workflows unfortunately. There has still been no progress on a browser `System` global spec yet, so holding on this for now. We can certainly revisit for 1.0 if necessary.
