### ISSUE TITLE
Deprecate plugin locate hook

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1091]

**Comment by brainkim** [comment]
I'd like to understand the justification behind deprecating one of the original four loader hooks. Trying to figure my way around writing plugins right now and starting with seeing what I can do in `locate`.

**Comment by brainkim** [comment]
Sometimes I feel like I need to fetch something before I locate it (as when you want to fetch a resource based on a hash of its contents for caching reasons.

**Comment by guybedford** [comment]
In the new spec, there is no longer a separate resolve and locate stage. Note also that normalization determines what name is used for the module in the module registry. Also, the fetch hook is welcome to fetch any URL it likes anyway so you can still get the functionality. Effectively nothing is lost, and the contracts become clearer in the plugin system.
