### ISSUE TITLE
Getting 404 as if defaultExtension is being ignored.

### ISSUE THREAD

**Issue by Gacnt** [systemjs/systemjs#1093]
Hi guys, I'm trying to follow the [Angular 2 Minute Quickstar](https://angular.io/docs/ts/latest/quickstart.html) but I'm having issues, I've done this step in the tutorial:

```
doctype html
html
  head
    title= title
    link(rel='stylesheet', href='/stylesheets/style.css')
    script(src="/javascripts/dep/es6-shim.min.js")
    script(src="/javascripts/dep/system-polyfills.js")
  body
    block content

    script(src="/javascripts/dep/angular2-polyfills.js")
    script(src="/javascripts/dep/system.src.js")
    script(src="/javascripts/dep/Rx.js")
    script(src="/javascripts/dep/angular2.dev.js")

    script.
        System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                }
            }
        });
        System.import('./javascripts/app/main')
        .then(null, console.error.bind(console));
```

But when I refresh the page I get:

`GET http://localhost:3000/javascripts/app/main 404 (Not Found)`

Because it seems to not look for the `main.js` instead it looks for `main`. 

Any information would be great thanks.

**Comment by guybedford** [comment]
For the packages configuration to trigger you would need to change the packages config to `packages: { './javascripts/app': {...} }`.

**Comment by guybedford** [comment]
Just let me know if you need further help here.

**Comment by Gacnt** [comment]
@guybedford thanks. I meant to come back and close this but totally forgot, at the time I didn't understand SystemJS but thanks!!
