### ISSUE TITLE
Chrome-based browsers cannot reload

### ISSUE THREAD

**Issue by alvinsight** [systemjs/systemjs#1095]
Hi, first of all thanks for the fantastic work on jspm!  I've got an issue that makes the browser not being able to reload, the actual error that is displayed in the console comes from babel-browser.js, so maybe it's worth giving @kittens a poke? 

Anyway, I'm getting by so far with firefox, but I think it would be good to get it fixed, it could become a hindrance to the adoption of SystemJs/jspm, and we don't really want this.

Thank you, 
Alvin

**Comment by guybedford** [comment]
What is the error that you are getting, and with which version of jspm?

I'd suggest against poking 🐱unnecessarily though...

**Comment by guybedford** [comment]
Just let me know if you need further help here.

**Comment by alvinsight** [comment]
Hi,
I think it's fixed now actually, I updated my project's dependencies using ``` jspm dl-loader ``` and it looks like it solved it. It upgraded the version of Babel from 4.x.x to 5.8.35, so I'll let you know if I find anything else, but I'm happy to leave this closed.
Have a good day, and thanks for jspm, it's the reason why I'm using ES6 :)
