### ISSUE TITLE
Specify package config

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1097]
I've noticed that if you turn the warnings on in `System.config`, it complains about dependencies using the `map` section to map their dependencies, whereas is now reccomended that such configs are made in the `packages` section where each dependency can explicitly declare its own paths, maps, metas, and such.

However, I can't figure out how to configure the package.json of my libraries (which I list as dependencies of the main app) for them to become a package instead of an entry in the map section.

**Comment by guybedford** [comment]
If you're referring to jspm here, that would be jspm 0.17 support.

**Comment by amenadiel** [comment]
Yeah, I should have asked this in jspm, I don't know what was I thinking :disappointed:
