### ISSUE TITLE
0.17 JSX is not being translated by babel

### ISSUE THREAD

**Issue by jasonLaster** [systemjs/systemjs#1098]
Hi, I'm starting a new [project](https://github.com/jasonLaster/etsyian) with 0.17 and am seeing an "unrecognized token" error. I believe this is because the babel blacklist option is not set to `[]`. 

My hunch is that is not happening because `babelOptions` is only used by the `babelTranspile` function, which in my case is not being run. 

Here are the relevant files:
+ [config](https://github.com/jasonLaster/etsyian/blob/master/jspm.config.js)
+ [bootstrap.js](https://github.com/jasonLaster/etsyian/blob/master/src/bootstrap.js)

![screen shot 2016-02-12 at 5 25 47 pm](https://cloud.githubusercontent.com/assets/254562/13022276/370cad66-d1ae-11e5-9751-b53d1043cf99.png)

**Comment by jasonLaster** [comment]
quick update: after investigating it a little bit more, it's clear the error is coming from `plugin-babel` and the `babel.transform` call. 

I'm probably missing the right `react` preset or plugin.

**Comment by guybedford** [comment]
JSX support is not included in the SystemJS Babel plugin by default as it is not a standard track  language feature. See http://jspm.io/0.17-beta-guide/installing-the-jsx-babel-plugin.html for a jsx workflow. You can also install the jsx Babel plugin and use that as well.
