### ISSUE TITLE
Unhandled rejection in Pale Moon

### ISSUE THREAD

**Issue by wolfbeast** [systemjs/systemjs#1099]
To help out one of our users who was talking about a specific inability to scroll tags on the "myclibu.com" site, I've been trying to access their service to get a live example.
Unfortunately, it doesn't load at all and throws the error below.

According to the user, it worked previously in 25.8.1 but it currently isn't working. Pale Moon 26.0 has some issues so isn't a good testbed currently and its ES6 handling will revert to more 25.8-alike in the next update (v26's Promises are currently not correctly implemented).

Clibu forwarded us to you since it's apparently your lib/loader that throws this error.

Can you provide any pointers or work with us to make your loader work in Pale Moon, please?
Do you have a test suite that we can use to pinpoint the issue?

````
[12:20:04.521] "Potentially unhandled rejection [2] @http://myclibu.com/build.min.js:10
i@http://myclibu.com/jspm_packages/system.js:5
s@http://myclibu.com/jspm_packages/system.js:5
i/c<@http://myclibu.com/jspm_packages/system.js:5
@http://myclibu.com/build.min.js:10
i@http://myclibu.com/jspm_packages/system.js:5
s@http://myclibu.com/jspm_packages/system.js:5
i/c<@http://myclibu.com/jspm_packages/system.js:5
@http://myclibu.com/build.min.js:10
i@http://myclibu.com/jspm_packages/system.js:5
s@http://myclibu.com/jspm_packages/system.js:5
i/c<@http://myclibu.com/jspm_packages/system.js:5
@http://myclibu.com/build.min.js:10
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
i@http://myclibu.com/jspm_packages/system.js:5
n@http://myclibu.com/jspm_packages/system.js:5
e/</</</</</<.execute@http://myclibu.com/jspm_packages/system.js:5
y@http://myclibu.com/jspm_packages/system.js:4
w@http://myclibu.com/jspm_packages/system.js:4
p@http://myclibu.com/jspm_packages/system.js:4
h@http://myclibu.com/jspm_packages/system.js:4
d/</<@http://myclibu.com/jspm_packages/system.js:4
M@http://myclibu.com/jspm_packages/system-polyfills.js:4
H@http://myclibu.com/jspm_packages/system-polyfills.js:4
[7]</</</</R.prototype.when@http://myclibu.com/jspm_packages/system-polyfills.js:4
[7]</</</</b.prototype.run@http://myclibu.com/jspm_packages/system-polyfills.js:4
[3]</</</t.prototype._drain@http://myclibu.com/jspm_packages/system-polyfills.js:4
@http://myclibu.com/jspm_packages/system-polyfills.js:4
e@http://myclibu.com/jspm_packages/system-polyfills.js:4
"
````

**Comment by guybedford** [comment]
The error is happening in http://myclibu.com/build.min.js:10, the way to debug would be to use unminified sources or source maps and see what is actually going on there. SystemJS manages execution, so comes up in execution stacks, but this isn't the source of the error as far as I can tell.

**Comment by wolfbeast** [comment]
OK, I've bounced this back to them with the request to get in touch directly with you (if needed) to figure out what's going on.

**Comment by nevf** [comment]
@guybedford I've been back in touch with the Pale Moon developers and am providing assistance. 

Note however our app Clibu at http://myclibu.com works correctly on Firefox, Chrome and MS Edge. It isn't working on IE11 as per my issue: https://github.com/jspm/jspm-cli/issues/1492

**Comment by nevf** [comment]
@guybedford I've copied the ```build.min.js.map``` file up to the server, however I'm unable to see the content of the individual source in any of FF, Chrome or Edge. Any suggestions?

**Comment by guybedford** [comment]
I can't really advise with respect to standard debugging workflows, but the first thing to check would be that you have a `// sourceMappingURL=build.min.js.map` at the end of the `build.min.js` source.

**Comment by nevf** [comment]
@guybedford if you visit http://myclibu.com with Chrome, open the debugger and look at ```build.min.js ``` the last line is: ```//# sourceMappingURL=build.min.js.map```

This is built using the jspm cli.

**Comment by guybedford** [comment]
@nevf the source map is working fine, but if you want to be able to see the sources from it you need to host jspm_packages or use the source-map-contents option on build.
