### ISSUE TITLE
Plugins to not skip defaultExtension

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1100]
With defaultJSExtensions deprecated, we no longer need to have plugin syntax create an extension exception in the resolver. Rather we can have plugin syntax apply to a module that runs through the normal resolution. If a package has a default js extension, this would need to be disabled to support plugin syntax.

**Comment by aluanhaddad** [comment]
@guybedford First of all, thanks for all of your hard work. SystemJS and jspm are wonderful. 

I'm not sure this is the right place to ask this question, I found some tangentially related information in other discussions but nothing conclusive. So here goes:
 
Does the deprecation of `defaultJSExtensions` hint at future plans to deprecate the `defaultExtension` setting for package level configuration?

As a TypeScript user I think this would break my workflow with SystemJS + jspm, so I hope that there are no plans to deprecate `defaultExtension`.

**Comment by guybedford** [comment]
@aluanhaddad packages `defaultExtension` will never be deprecated, just `defaultJSExtensions`.

**Comment by aluanhaddad** [comment]
@guybedford Excellent! Thank you for clarifying.

**Comment by guybedford** [comment]
Implemented in [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1).
