### ISSUE TITLE
tty-browserify dependency on jspm init

### ISSUE THREAD

**Issue by VivekPMenon** [systemjs/systemjs#1104]
**Background:** We have set up an internal jspm git hub repository since there are security concerns going out of house for fetching packages. The packages which are approved to be used are stored in this internal repository. 

we found a behavior during **jspm init** that it pulls down tty-browserify (and a bunch of additional packages) on machines (windows) where GIT cmd is not added to the PATH variable. The moment we add GIT CMD to PATH, it no longer asks for such packages and number of folders we see under jspm_packages/github/jspm is minimal. Do you think of any specific reason for this behavior? 

Please let me know. If needed, I can attach the jspm init logs in both the cases.

**Comment by guybedford** [comment]
I'm not sure I see any causation here. Perhaps sharing the logs would help.

**Comment by guybedford** [comment]
Note this is a jspm issue though, please post an issue there for further discussion.
