### ISSUE TITLE
Any RequireJS-like urlArgs parameter to prevent caching?

### ISSUE THREAD

**Issue by darknessm0404** [systemjs/systemjs#1105]
Hi,

It's a simple question, I'm trying to move away from RequireJS, and the only feature I did not find (production environment use case) in is the urlArgs string parameter that transform 
something.js
in
something.js?cachedVersion=123456
for example.

Do you have a plugin for that in SystemJS, or what can I do to handle this in SystemJS?

**Comment by og-neth** [comment]
Thanks for posting this because this is causing issues in our development environment currently, and having to clear the cache manually from the browser is not efficient for our workflow. Hopefully we get some guidance on this soon. @darknessm0404 are you doing any unit testing right now with RequireJS? What's your set up like?

**Comment by sod** [comment]
@og-neth 
![disable cache](https://cloud.githubusercontent.com/assets/905328/13125601/bb6c2aac-d5c6-11e5-9586-e851204affed.png)

**Comment by og-neth** [comment]
@sod Yeah I forgot about that from my reading yesterday thank you for the reminder. I am still concerned about caching however once we go to prod with changes, but we'll figure that out, we use Akamai and hopefully we don't run into unexpected issues. Last time we used a module loader, we experienced some weird issues with caching and loading on our site once we went to PROD and we were forced to do away with module loading in our architecture.

**Comment by darknessm0404** [comment]
@og-neth No unit testing for my project in requirejs sorry.
@sod I edited my post so we understand that it's an option meant for production environment.

**Comment by guybedford** [comment]
This is not a feature in SystemJS and is not planned. It is trivial to add as a custom extension with something like https://github.com/systemjs/systemjs/issues/172#issuecomment-52262588, but caching should be handled at the server layers not the loader layer.
