### ISSUE TITLE
Relative url problem in system.js source code

### ISSUE THREAD

**Issue by darknessm0404** [systemjs/systemjs#1106]
Hello,

I am struggling in a deployed project on my development environment server where I host a bunch of files (all of them have the module name starting with "foundation/") in a different directory, using a config like this:
```
System.config({
    defaultJSExtensions: true,
    baseUrl:  '/MyProject/Scripts/'
    map: {
        'foundation': '../public/'
    }
});
```
Somewhere in my code I am using System.import('foundation/init')

The real path of MyProject is:
http://server:105/MyProject
So the base url is
http://server:105/MyProject/Scripts/

However in the code, if you look at the section:
`hook('normalize', function (normalize) {`

There is a "relative URL-normalization" section, that catches if the name starts with a "..", so it gets into the case where:
`name = new URL(name, baseURIObj).href;`

baseURIObj href is http://server:105/
So the name returned is replaced with http://server:105/public/init
Instead of http://server:105/MyProject/public/init

I don't understand the use of baseURIObj because later in the code (that is never reached) there is a:
`return new URL(name, getBaseURLObj.call(this)).href;`

That returns 

> http://server:105/MyProject/public/init

Am I mistaking or this case has not been tested outside a "localhost" or "root-only" project?

I have tried to replace `name = new URL(name, baseURIObj).href` with `return new URL(name, getBaseURLObj.call(this)).href;` but then I'm struggling with all other names that starts with 'foundation' which are getting redirected to ./public because the "this.map" has entries pointing to "./public" instead of "../public" as it is stated in the System.config.

I do not have enough knowledge in SystemJs source to fix that other problem, I'm getting stuck here.

**Comment by guybedford** [comment]
Thanks for posting. Yes this is a bug and is exactly https://github.com/systemjs/systemjs/issues/1010.
