### ISSUE TITLE
calling System.config({ }) seems to remove loaded modules

### ISSUE THREAD

**Issue by kisdaniel** [systemjs/systemjs#1110]
I have tried angular2 with systemjs (0.19.6), but as it tries to register main-s angular2/core dependency: 
`System.register(['angular2/core'], function(exports_1) { `
it tries to fetch already loaded angular2 core: http://localhost:9000/js/angular2/core 

if i change the order to:
0. before system.src.js everithing is unmodified
1. script: system.src.js
2. script: System.config
3. script: rxjs.js, angular2.dev.js
4. script: System.import

than it works! So it seems that it forgets all loaded modules after System.config! 

original not working code (from angular 2 quickstart):

```
<html>
  <head>
    <title>Angular 2 QuickStart</title>

    <!-- 1. Load libraries -->
    <!-- IE required polyfills, in this exact order -->
    <script src="js/es6-shim/es6-shim.min.js"></script>
    <script src="js/systemjs/dist/system-polyfills.js"></script>

    <script src="js/angular2/bundles/angular2-polyfills.js"></script>
    <script src="js/systemjs/dist/system.src.js"></script>
    <script src="js/rxjs/bundles/Rx.js"></script>
    <script src="js/angular2/bundles/angular2.dev.js"></script>

    <!-- 2. Configure SystemJS -->
    <script>
      System.config({
        baseURL: '/js',
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/main')
            .then(null, console.error.bind(console));
    </script>

  </head>

  <!-- 3. Display the application -->
  <body>

    <my-app>Loading...</my-app>
  </body>
</html>
```

**Comment by guybedford** [comment]
You need to configure SystemJS first before loading bundles because bundles run through normalization, and hence need configuration present in order to normalize correctly.
