### ISSUE TITLE
Cannot calculate test coverage due to lack of __esModule flags

### ISSUE THREAD

**Issue by piebe** [systemjs/systemjs#1114]
I am using systemjs bundles to make my code modular and compose my applications using these bundles. This works fine. Also running unittests works fine using karma-systemjs.

However when I try to calculate test coverage using instrumentation by isparta things stop working. The modules form the bundles can no longer be properly loaded. It appears this is caused by the fact that isparta transpiles module imports into commonjs require. The bundels are already transpiled and will not be instrumented so their modules will still be defined as systemjs modules. The commonjs require statements try to load the systemjs modules and fail because no __esModule flag is found... 

There appears to be a lot of discussion about the __esModule flag within the systemjs issues. To me it is unclear what the current status of the flag is and what future plans are (if any).

Is there a way to force the addition of the __esModule flag? And if not, will there be one in the future? 

see also [Default export/import from external module is not working as expected when running coverage #96](https://github.com/douglasduteil/isparta/issues/96)

**Comment by guybedford** [comment]
This sounds like an isparta issue rather than a SystemJS one. In particular transpiling to CommonJS for coverage is already creating differences. I'm working on some coverage approaches for SystemJS at the moment actually, will share some ideas soon along these lines.
