### ISSUE TITLE
Support plugin-relay-babel

### ISSUE THREAD

**Issue by subesokun** [systemjs/systemjs#1117]
Hi, I was playing around with Relay but now when I want to try it in combination with jspm I run into an issue when trying to use the relay plugin for babel. I'm using the latest jspm@0.17 and my babel options are

```json
"babelOptions": {
    "plugins": [
      "babel-relay-plugin"
    ]
  }
```

and I've also installed babel-relay-plugin as a dev dependency. But when I try to load now the app in the browser I get the following error

```
Uncaught (in promise) Error: Invalid introspection data supplied to `getBabelRelayPlugin()`. The resulting schema is not an object with a `__schema` property.
	Error loading http://localhost:3060/bootstrap.js
    at invariant (http://localhost:3060/jspm_packages/npm/babel-relay-plugin@0.6.3/lib/invariant.js:24:11)
    at getSchema (http://localhost:3060/jspm_packages/npm/babel-relay-plugin@0.6.3/lib/getBabelRelayPlugin.js:158:3)
    at getBabelRelayPlugin (http://localhost:3060/jspm_packages/npm/babel-relay-plugin@0.6.3/lib/getBabelRelayPlugin.js:36:16)
    at Function.b.memoisePluginContainer (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:4113)
    at Function.b.normalisePlugin (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:4627)
    at eval (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:5000)
    at Array.map (native)
    at Function.b.normalisePlugins (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:4725)
    at b.mergeOptions (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:5874)
    at b.init (http://localhost:3060/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-browser.js:4:7742)
```

The plugin is looking for a `__schema` property in the "`schemaProvider`" object but there isn't any set. Not sure which argument systemjs passes in as first argument when loading the plugin, but on this object the relay plugin expects somehow a `__schema` property.

Do you've any guess what goes wrong in my case? Thanks! :)

**Comment by guybedford** [comment]
In https://facebook.github.io/relay/docs/guides-babel-plugin.html#advanced-usage it seems that the schema needs to be passed in before setting the babel plugin?

**Comment by subesokun** [comment]
Thanks for the pointer! So in fact that means that I've to create a wrapper plugin for the relay plugin so that this wrapper returns a configured instance of it or...? I guess there is no other way to do such programmatic configuration via systemjs (e.g. via a "get-plugin-hook")?

**Comment by subesokun** [comment]
Found my answer here https://www.npmjs.com/package/babel-relay-plugin-loader :) I just need to figure out now how I can set such a metadata property as mentioned [here](https://www.npmjs.com/package/babel-relay-plugin-loader#usage) via systemjs / jspm. Any ideas, recommendations before I start hacking on it :)?

**Comment by subesokun** [comment]
Mhh I got stuck somehow half way. Instead of using the npm babel-relay-plugin-loader package I was writting my own little loader which I include as the following:

```json
babelOptions: {
  "plugins": [
    "babel-relay-plugin-loader"
  ]
},
map: {
  "babel-relay-plugin-loader": "../utils/babelrelaypluginloader"
}
```

```javascript
// babelrelaypluginloader.js

import getbabelRelayPlugin from 'babel-relay-plugin';
import schema from '../schema/schema.json';

export default getbabelRelayPlugin(schema.data);
```

But then even if I've a very simple javascript file which tries to import any package I'll receive the following error

```javascript
// index.js
import 'anypackage';

// Throws GET http://localhost:3060/jspm_packages/npm/util.json 404 (Not Found)
```

Even if I comment all lines in the `babelrelaypluginloader.js` I still get the same error. If I remove the relay plugin from the plugins list the app is loading normally again. Any ideas?

**Comment by guybedford** [comment]
@subesokun is `npm:util` contained in your config file at all? It sounds like it should be an installed peer dependency. Did you try running `jspm install npm:util --peer`?

**Comment by subesokun** [comment]
No, so far none of my dependencies required `npm:util` hence it's not in my config file. First if I try to add the plugin to the plugins list suddenly this dependency gets required (also if the `babelrelaypluginloader.js` is completely empty). I was trying now to install the `npm:util` package as peer dependency but I still get the same error. But I really wonder why suddenly this utils package is required just because I try to add an empty babel plugin.

**Comment by subesokun** [comment]
I've created now a repository for fiddling around with jspm and Relay but now I got stuck at the point that I'm not able to import the `babel-relay-plugin` via my custom babel Relay plugin loader. If the import statement in the `web/utils/babelrelaypluginloader.js` has been commented then the loader plugins gets loaded but if the import statment has been uncommented then jspm / systemjs will fail silently.

Any ideas :) ?

https://github.com/subesokun/relay-jspm-starter-kit

**Comment by guybedford** [comment]
Did you try adding a catch handler to your System.import statement or is it actually stalling?

**Comment by guybedford** [comment]
How's this coming along? Did you still need any help here?

**Comment by subesokun** [comment]
I've added following catch handler but still the app silently crashes :(

```javascript
System.import('relay-jspm-starter-kit')
  .catch(function(err) {
    console.error(err);
  });
```

Also in the log of my server I see that the `babel-relay-plugin` doesn't get loaded. In fact it stops after trying to load my self written `babel-relay-plugin-loader`.

```
GET /jspm_packages/system.js 304 6ms
GET /jspm.config.js 304 7ms
GET /jspm.browser.js 304 9ms
GET /src/main.js 304 0ms
GET /jspm_packages/npm/systemjs-plugin-babel@0.0.6.json 304 1ms
GET /jspm_packages/npm/systemjs-plugin-babel@0.0.6/plugin-babel.js 304 1ms
GET /jspm_packages/npm/systemjs-plugin-babel@0.0.6/systemjs-babel-browser.js 304 1ms
GET /utils/babelrelaypluginloader.js 200 5ms - 266
GET /jspm_packages/system.js.map 304 2ms
```

So I'm not sure how I can debug this as I don't get any errors :(

**Comment by subesokun** [comment]
Btw. is it valid to use es6 features and import statements in a babel plugin, see [babelrelaypluginloader.js](https://github.com/subesokun/relay-jspm-starter-kit/blob/master/web/utils/babelrelaypluginloader.js)? Not that this is the root cause of my problems.

**Comment by guybedford** [comment]
Ok yes that would be the issue here... because you're using this as a Babel plugin and then writing the plugin itself to be transpiled with Babel, it's trying to load the plugin to transpile the plugin causing a loop.

There's an open issue to at least catch this circularity in https://github.com/systemjs/plugin-babel/issues/22.

**Comment by Vanuan** [comment]
With babel 6 it's this error:
    Plugin 2 specified in "base" provided an invalid property of "default"

**Comment by guybedford** [comment]
@Vanuan was that loading an ES module plugin? If so, I've created https://github.com/systemjs/plugin-babel/issues/37 to track.

**Comment by Vanuan** [comment]
I think it's jspm:


```
babelOptions: {
  "plugins": [
    "babel-relay-plugin-loader"
  ]
},
map: {
  "babel-relay-plugin-loader": "../utils/babelrelaypluginloader"
}

// babelrelaypluginloader.js
import getbabelRelayPlugin from 'babel-relay-plugin';
import schema from '../schema/schema.json';

export default getbabelRelayPlugin(schema.data);

```

**Comment by guybedford** [comment]
@Vanuan if you're able to test out the fix suggested in that issue let me know.

**Comment by Vanuan** [comment]
Sure, what's the fix?
