### ISSUE TITLE
ignore bundles in development

### ISSUE THREAD

**Issue by leemason** [systemjs/systemjs#1118]
im working on a project using system js and jspm. then gulp to bundle up the assets for production use (using jspm api).

when a bundle is generated it adds the bundle to the {bundles: {}} config item in my root config.js file.

this is as expected, however how can i tell system js NOT to use the bundles during development?

ideally i would like to do:

```
System.config({bundles: {}}); or System.config({bundles: false});
```

in an if statement before any import statement when in development. but this doesnt seem to work?

**Comment by guybedford** [comment]
You can unset bundles via `System.bundles = {}`, but it would be best to consider the configuration as stateful based on the environment (ie do not do the injection for development, or inject into a special production config file only with a custom build task).
