### ISSUE TITLE
Typescript -> Babel -> ES5 support

### ISSUE THREAD

**Issue by cherrydev** [systemjs/systemjs#1121]
So, rather than provide full ES6 transpilation support for newer ES6 features such as generators, Typescript is now requiring these newer features to target ES6 as its output.  This means that in order to take advantage of these features you need to chain the ES6 output of typescript into a 6to5 transpiler like babel.  This seems to be one particular area where systemjs isn't quite flexible enough for this.

**Comment by guybedford** [comment]
Thanks for sharing, can you clarify what sort of features you are referring to here? Do you have a reference for this decision?

You can do this in SystemJS by chaining the TypeScript plugin http://github.com/frankwallis/plugin-typescript as the module plugin with Babel as the transpiler.

**Comment by cherrydev** [comment]
Sure.  There isn't a comprehensive list that I can find, but in particular, ES6 target is required for
* async / await
* generator functions
* iterator interfaces

That's taken from [here](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript)

I've tried using plugin-typescript as a loader, as you described, but using:
``transpiler: "plugin-babel",``
with

    packages: {
                "app": {
                        "main": "main",
                        "defaultExtension": "ts",
						"meta": {
							"*.ts": {
							  "loader": "ts"
							}
						}
                },
    ...
gets me es6 code transpiled by typescript, but it is not running the result through plugin-babel.  Any idea why?

**Comment by guybedford** [comment]
You'd need to specify "format": "esm" metadata, and output raw es modules from TypeScript, although I don't know that TypeScript have enabled this output yet actually.

**Comment by cherrydev** [comment]
My final config stanzas that were relevant were

        transpiler: "plugin-babel",
        typescriptOptions: {
                "target": "ES6",
                "module": "ES6",
                "emitDecoratorMetadata": true,
                "experimentalDecorators": true
        },
        ...
along with the packages stanza above.

**Comment by guybedford** [comment]
Nice, so it's working? Can we close this then?

**Comment by cherrydev** [comment]
Yes, I suppose so.  I'm pretty surprised that I haven't seen this used as an example anywhere so far.  Oh well, live on the bleeding edge...

**Comment by guybedford** [comment]
Sure. Yep the edge of these workflows is pretty close! It may be worth suggesting a note on this in the plugin project readme. Also if you hit further issues down the line do keep us posted.
