### ISSUE TITLE
Is there a solution to auto register an already downloaded script into SystemJS?

### ISSUE THREAD

**Issue by darknessm0404** [systemjs/systemjs#1123]
Hello,

I have a simple question.
I am trying to limitate the need of configuration on old projects that were not using SystemJS.
Most of them have the old-style < script > loading of jQuery in the <head> of the html page.

Is there anything I can do to auto-register these?
Something like: SystemJS.assign($, "jquery") to bind $ to the jquery module? I know it's dirty, but still useful for "legacy" projects.

For the moment the only fix I found was to create an "application.jquery.shim.js" that only returns window.jQuery
It works, but it means that if I have any other library that I want to load like this, it would mean to make N*alreadyRegisteredModule
If I could save some http calls it would be great.
I have seen SystemJS.register but I do not know if it's meant for that particular use?

Thank you in advance

**Comment by guybedford** [comment]
You can use System.set - `System.set(System.normalizeSync('jquery'), System.newModule({ default: $ }))`

**Comment by darknessm0404** [comment]
Well after the System.config call I have put this, but in the Chrome console I got this:
Uncaught (in promise) TypeError: $.extend is not a function(…)
The jquery dependency does not contain the real jquery, this is what I get inside
` define(["jquery"], function($){    //here   });`

Module {}
	default: (...)
	get default: ()
	set default: ()
	__proto__: Module

What should I do to get the full jquery library?

**Comment by guybedford** [comment]
@darknessm0404 internally this is handled by using `System.newModule({ default: $, __useDefault: true })`

**Comment by darknessm0404** [comment]
I have changed it to
`System.set(System.normalizeSync('jquery'), System.newModule({ 'default': $, '__useDefault': true }));`
and now it works!

Thank you very much for your fast answers! :)
