### ISSUE TITLE
Can we call multiple times SystemJS.config and how to properly debug SystemJS configuration

### ISSUE THREAD

**Issue by darknessm0404** [systemjs/systemjs#1124]
Hello,
### Is it "legal" to have multiple SystemJS.config calls?
I want some projects to load a module that can auto-set configuration if it has not been already declared in the project that is using it.
I am testing existence of modules with the API, and then auto-set a default configuration if it's not present (to retrieve them if necessary in the future).
Is it something that is OK with SystemJS? (just to be sure)
### How to debug cases where invalid path are loaded?
I have some cases where SystemJS tries to load an empty named js file:
**GET http://localhost:2902/.js 404** (Not Found)fetchTextFromURL @ system.js:1038(anonymous function) @ system.js:1593(anonymous function) @ system.js:1592leadingCommentAndMetaRegEx @ system.js:2605load.metadata.deps @ system.js:3169loader @ system.js:3434loader @ system.js:4050loader @ system.js:4256constructor.meta @ system.js:4499(anonymous function) @ system.js:294
system.js:1038 
**XHR finished loading: GET "http://localhost:2902/.js"**.fetchTextFromURL @ system.js:1038(anonymous function) @ system.js:1593(anonymous function) @ system.js:1592leadingCommentAndMetaRegEx @ system.js:2605load.metadata.deps @ system.js:3169loader @ system.js:3434loader @ system.js:4050loader @ system.js:4256constructor.meta @ system.js:4499(anonymous function) @ system.js:294
system.js:996 
**Uncaught (in promise) Error: **XHR error (404 Not Found) loading http://localhost:2902/.js(…)

I have placed a breakpoint in the prototype.config = function (cfg) however I do not set any empty path.
I have searched for hours (literaly) and have no idea why this is happening.

Thanks for your help.

**Comment by guybedford** [comment]
The `(…)` at the end of your error message contains the actual error message that provides useful debugging information to understand what was being loaded and why. Yes it's fine to have multiple System.config calls.

**Comment by darknessm0404** [comment]
Thanks for the answer.
But the (...) only shown this:

```
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:2902/.js
	
	Error loading http://localhost:2902/.js
    
	at error (http://quasrvdev:105/QuadraFoundation/Scripts/system.js:996:32)
    
	at XMLHttpRequest.xhr.onreadystatechange (http://quasrvdev:105/QuadraFoundation/Scripts/system.js:1017:33)
		error @ system.js:996xhr.onreadystatechange 
		      @ system.js:1017

```
So I have placed a few debuggers starting from the line 1017, then going up on the callstack and the promise stack until I reached the code that was requiring this module.
A dynamic require(arrayA) where arrayA contained an empty string was leading to this problem.
I have fixed the bug in the code that was causing it, now it's perfect! :)

Thank you!
