### ISSUE TITLE
Load Javascript file from angular2 component

### ISSUE THREAD

**Issue by mburger81** [systemjs/systemjs#1125]
I trie to load a javascript file from my angular2 component in an angular2-webpack-starter project.

In my index.html file I tried first to load this

`<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.23/system.js"></script>`

and in my component i try to load the js file in that way

```
System.import('https://wetter.ws.siag.it/Widget_v1.svc/web/loadSimpleWidget/it/0/Landscape.js').then(refToLoadedScript => {
            console.log('it works');
        });
```

bot I got this error

`XMLHttpRequest cannot load https://wetter.ws.siag.it/Widget_v1.svc/web/loadSimpleWidget/it/0/Landscape.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.`

so I googled and found I had to use system-csp so i load it in my index.html

`<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.23/system-csp-production.js"></script>`

but now I get this error
`EXCEPTION: Error: https://wetter.ws.siag.it/Widget_v1.svc/web/loadSimpleWidget/it/0/Landscape.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.`

Can you help me?

**Comment by guybedford** [comment]
Because this is a global script and not a module, you need to tell SystemJS what its global name is.

This can be done by first setting:

```javascript
System.config({
  meta: {
    'https://wetter.ws.siag.it/Widget_v1.svc/web/loadSimpleWidget/it/0/Landscape.js': {
      exports: 'meteoprovbz_Widget'
    }
  }
});
```

So SystemJS knows how to treat it as a module. Let me know if that helps.
