### ISSUE TITLE
Random dependencies loading error 

### ISSUE THREAD

**Issue by vhiairrassary** [systemjs/systemjs#1126]
Hello,

We use SystemJS for few weeks but **sometimes** dependencies are not satisfied. This always happen on [jsPlumb 1.5.5](https://github.com/sporritt/jsPlumb/releases/tag/1.5.5). Here is our configuration:

```
js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  buildCSS: false,

  packages: {
    "quill": {
      "main": "quill/quill.js"
    }
  },

  meta: {
    // ...
    "jsplumb": {
      "deps": [
        "jquery"
      ]
    },
    // ...
  },

  map: {
    // ...
    "jquery": "github:components/jquery@2.1.4",
    "jquery-getscrollbarwidth": "vendor/jquery/jquery.getscrollbarwidth.min",
    "jquery-ui": "github:components/jqueryui@1.10.4",
    "jquerycron": "vendor/jquerycron/jquery-cron-min",
    "jsplumb": "vendor/jsPlumb/jquery.jsPlumb-1.5.5.js",
    // ...
```

The error in Chrome 48 is:
```
Uncaught ReferenceError: jQuery is not defined__exec @ system.src.js:1436
(index):1 Uncaught (in promise) Uncaught ReferenceError: jQuery is not defined
	Evaluating http://v.example.com:3000/vendor/jsPlumb/jquery.jsPlumb-1.5.5.js
	Error loading http://v.example.com:3000/vendor/jsPlumb/jquery.jsPlumb-1.5.5.js as "jsplumb" from http://v.example.com:3000/compiled/src/app/en_US/sqlDesigner/directives/bimeSqlDesigner/bimeSqlDesigner.js
```

Can you help us to fix that please ? Thank you in advance

**Comment by guybedford** [comment]
With global modules, that rely on accessing a global identifer, it can happen that that global happens to be present by chance in the majority of cases and then fails randomly.

The way to avoid this is to:
1. Shim every module
2. Don't rely on global references ever in your own code, always importing the identifiers used (obviously you can't control what jsplumb does though)

In terms of tracking this down, it seems like jsplumb is configured correctly, so it is probably another library expecting to find jquery that also needs a shim like the one for jsplumb. Perhaps that is one of the other jquery plugins you have in use there.

**Comment by vhiairrassary** [comment]
Thank you for the answer, we are still working on it :)

**Comment by guybedford** [comment]
Sure, just let me know if I can help further.

**Comment by lijunle** [comment]
Hi, @vhiairrassary Do you have founds on your issues? I get into a similar problem.

In my case, Highchart.js depends on jQuery on the **evaluate time**, so the evaluate fails.

I think the `globals`, `deps` meta configurations are for **runtime** dependencies. I have no idea how to specify **evaluate time** dependencies. :disappointed:

**Comment by vhiairrassary** [comment]
@lijunle This issue still occur in development if the console is closed 😞
