### ISSUE TITLE
System.import ignoring package mapping

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1128]
I configured an app with an AMD library as a dependency, and to avoid declaring global mappings to each of its components, I declared a package config like so:

```js
"packages":{
  "my_lib":{
    "map":{
      "models":"./models",
      "collections":"./collections",
      "views":"./views"
    }
  }
}
```

This mapping works fine when this lib inner dependencies are requested with  `define`. For example

```js
define(['models/user','views/user_account'],function(User,UserAccount) {
  ...
});
```

however, if I try to use `System.import` to achieve the same dinamycally:

```js
var getUserModel=function() {
    return System.import('models/user').then(function(User) {  return User; });
}; 
```

System.js tries to load from a root folder, as if it was `/models/user.js`. I guess this has something to do with the second parameter of System.import, `normalizedParentName`, but I don't know if there's a way to get that parameter for an AMD lib, and hardcoding seems ugly.

**Comment by guybedford** [comment]
Yes this is how package map works - it is contextual to the package only. If you want it to work globally, use standard map config rather.
