### ISSUE TITLE
How to use meta with absolute urls? (globals does not work)

### ISSUE THREAD

**Issue by darknessm0404** [systemjs/systemjs#1132]
On an old project using an old version of jQuery, I have a case where I am trying to set a global (remote more recent jQuery file) to a remote script (recent signalR version) that is loaded by SystemJs.
```
<script src="old.jquery.js">

System.config({
    defaultJSExtensions: true,
    map: { 
         'jquery': 'http://srv:105/QuadraFoundation/scripts/jquery-2.1.4',
         "microsoft.signalr.client":"http://srv:105/QuadraFoundation/scripts/jquery.signalR-2.1.0"
    }
    meta: {
         'http://srv:105/QuadraFoundation/scripts/jquery-2.1.4': {
              format: 'cjs' // so it can load without overwritting window.jQuery current value, that is required by this old project
         },
         "http://srv:105/QuadraFoundation/scripts/jquery.signalR-2.1.0": {
                "globals":{
                        "jQuery":"http://srv:105/QuadraFoundation/scripts/jquery-2.1.4"
                  },
                  "format":"cjs" // with or without this format, it does not work
          }
    }
});
```

The problem is that the jquery-signalr does not receive the jquery-new version, so it fails somewhere with a call to $.hubConnection which is undefined (since jQuery signalR was added on the old version and not the new one, and it is not the desired effect).

- **Why is that?** Isn't it supposed to overwrite the window.jQuery while loading the jquery-signalr file?
- I don't understand why we have to use the full url of the files in the meta, it makes the configuration hard to read imo. I hoped we could only specify jQuery:'jquery' and it would map to the good one, but it needs the full url. Is it because the meta is meant to use rules that are defined before the call to .config() (if multiple calls to config are used)?

The only solution I have found for now is to wrap jQuery Signal R file inside an amd package and rewrite window.jQuery temporarily until the end of the file. It works that way.

Thanks in advance for your help.

**Comment by guybedford** [comment]
If you include the js extensions in the meta that should work here. This is actually a regression though that this doesn't work, which is fixed in https://github.com/systemjs/systemjs/issues/1130.
