### ISSUE TITLE
Cannot load angular2 .ts file again by System.Import or System.define after System.delete

### ISSUE THREAD

**Issue by borispk** [systemjs/systemjs#1134]
I have an angular2 application that requires to reload an update version component on the run. 

Firstly I use System.delete to delete the entry say System.delete("./app/home.ts"). Then, I use System.Import("./app/home.ts") to reload the modified component again.

The problem is, after System.delete called, the file "Home.ts" and "Home.ts!transpiled" are still in the "Source" tree of the Chome debugger. After the System.Import run, the "updated version of Home component" can be seen on the "Home.ts!transpiled" file in the Chome debugger tree. However, the content of "Home.ts" remain the same (cannot reflect the new change in Home file) in the Chome debugger tree. Also, the code executing the component is still the old version.

Can you please give me some instructions so that I can re-load the component and both "Home.ts" & "Home.ts!transpiled" can reflect the change in source file list of Chome debugger tree.

Thank you.

**Comment by guybedford** [comment]
Make sure that you are deleting the correct name in the registry via `System.delete(System.normalizeSync('./app/home.ts'))`.

**Comment by borispk** [comment]
Thanks, I tried ` System.delete(System.normalizeSync('./app/home.ts')) `, however, the home.ts and home.ts!transpiled still on the tree list of the "Sources" tab. And the System.import cannot take over the old code. I am wounding what wrong with my code...

**Comment by guybedford** [comment]
Did you confirm that the module exists that you deleted via `System.has(System.normalizeSync('app/home.ts')) == true`?

**Comment by borispk** [comment]
Thank you very much for your quick response, I tried the code and the details below:
`	var rtn = System.has(System.normalizeSync("app/home.ts"));
//rtn = true at this point, Source directory of chome has files "home.ts and home.ts!transpiled"
	System.delete(System.normalizeSync("app/home.ts"));
	rtn = System.has(System.normalizeSync("app/home.ts"));
//rtn = false at this point, files "home.ts and home.ts!transpiled" are STILL EXIST in source directory under Chome`

I expect when I execute the System.delete command, both "home.ts and home.ts!transpiled" will be disappear form the Chome Sources directory tree. I believe the System.delete command work in the sense that it erase some registry in SystemJS core, but not the browser memory (like inside Chome). Do you have some hints?

**Comment by guybedford** [comment]
The contents of the Chrome Sources is not managed by SystemJS, this is managed by Chrome itself. If the new code is executing correctly, then SystemJS is working correctly, regardless of what is coming up in the Chrome sources.

**Comment by borispk** [comment]
In his way,  I cannot use chrome for debug trace? I really meed to publish the code in chrome correct for both .ts and .ts! transplied.  Any other work around?

**Comment by borispk** [comment]
Further,  the new code loadee is not executable.  I think I have to bootstrap again under Angular2. It need further investigation.  However,  why the transcript code wutomaticwlly translated to js codr when the second time import?  Does tue teanslation done by SystemJS?  If so,  why the origional .ts file do no load to chrome as like as the fist time I load the component?  

I guess there is some magic on the transcoder tyat make the .ts file cannot see in chrome.

Thanks again for your help.
