### ISSUE TITLE
Forcing mapping of relative require paths

### ISSUE THREAD

**Issue by sparkbuzz** [systemjs/systemjs#1138]
We're currently generating a manifest from gulp-rev to hash our JavaScript files for production. And it works really well, we simply pass the manifest object to System.config() and SystemJS does the rest for us, the hashed scripts are loaded as expected.

**manifest.json** from **gulp-rev** looks something like this:

```
{
    "stuff/MyFile.js": "stuff/MyFile-1a3b5c7d.js"
    //...
}
```

We don't have to change references to require(''); files in order to load the hashed versions.

`var myStuff = require('stuff/MyFile.js');`

However, one tiny drawback is that IDE's like PHPStorm don't understand how to jump to definitions unless the path for the required file
`require('stuff/MyFile.js');`
becomes relative (and this moves closer to the way NodeJS works)
`require('./stuff/MyFile.js');`

Changing this fixes the IDE's ability to jump to source by, for example Command/Ctrl clicking on a require or variable.

The problem is, SystemJS can't find any files, as it's trying to load. Understandably we need to update manifest.json or the SystemJS map to look something like this:

```
{
    "./stuff/MyFile.js": "/stuff/MyFile-1a3b5c7d.js"
    //...
}
```

But, ot doesn't seem SystemJS picks up the mapping, it's as if SystemJS ignores the map the moment it sees a relative path in a require() statement.

Is this a case, and if so, how can we map requires with relative paths?

**Comment by sparkbuzz** [comment]
I think this has to do with url normalization. As far as I understand, SystemJS doesn't consider the map if the load url for the require calls starts with a / or ./, right?

**Comment by guybedford** [comment]
I wouldn't advise messing with the normalization rules. Perhaps look at transforming the configuration in the browser before sending it to SystemJS here?

**Comment by sparkbuzz** [comment]
Hi @guybedford I have tried transforming the paths before giving it to System.config(). I basically changed the keys in the map from, for example MyFile.js to ./MyFile.js, om an attempt to map a require('./MyFile.js');.

It seems the code completely ignores the map for require paths starting with ./

I did a little experiment and added the following code to https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L1565

```
// standard URL resolution
//if (!isPlain(name))
//  return urlResolve(name, parentName);

var re = /^((\.){1,2}\/)+/g;
name = name.replace(re, '');
```

Commenting out the isPlain() check, and mutating the name to remove and leading ./ gives me exactly the behaviour I want. Files are loading with relative paths, and mapped, and IDE is able to navigate happily with "Jump to Definition" feature.

I see there is a concept of hooks inside the SystemJS? Is it possible I can use/register a hook with SystemJS, during configuration to transform my require statements so relative paths can be mapped?

**Comment by guybedford** [comment]
Relative names can only be mapped through package configuration map, where the relative names are defined as package-relative. There is no other way to map relative names at all, because they are resolved through URL-normalization before running further map.

For example - `map: { './a': 'b' }` means map `[baseURI]/a` to `b`, not map `require('./a')` to b.

What I meant by altering the configuration before creating the System config was to convert it into the correct style of map to work with SystemJS. It sounds like you just want something like:

```javascript
System.config({
  packages: {
    "app": {
      "map": {
        "MyFile-asdf.js": "some-path-here.js"
      }
    }
  }
});
```

Where the above is generated by your tooling.

**Comment by amenadiel** [comment]
@guybedford

In the example above

**Comment by guybedford** [comment]
@amenadiel `System.import('MyFile-asdf.js', System.normalizeSync('app/asdf.js'))` (equivalent to a `import 'MyFile-asdf.js'` in a file located at `app/asdf.js`) would resolve to `System.normalizeSync('some-path-here')`. If you want `some-path-here.js` to be within app, then you can use a target of `./some-path-here.js`.

**Comment by Lcng** [comment]
@sparkbuzz You can treat `./stuff` as a package，and map the package like this:

```
(function () {
    System.config({
        paths: {
        },
        map: {
        },
        packages: {
            './stuff': { // ./stuff is a package
                map: {
                    './MyFile.js': 'stuff/MyFile-1a3b5c7d.js' // mapping relative path of a package is allowed
                }
            }
        }
    });
})();
```
Then `System.import('./stuff/MyFile.js')` will get `stuff/MyFile-1a3b5c7d.js`.

**Comment by Lcng** [comment]
@amenadiel Just treat `./` as a package..
