### ISSUE TITLE
Calling `normalize` with relative path and basedir which lacks trailing slash

### ISSUE THREAD

**Issue by MeoMix** [systemjs/systemjs#1139]
Hey,

I posted about this in Gitter, but I thought it'd be better to open an issue for it to discuss it more closely.

For reference, I'm using version `0.19.23 Standard`

I have this logic:

```
const result = System.normalizeSync('./foo.css', `${System.baseURL}common/css`);
const result2 = System.normalizeSync('./foo.css', `${System.baseURL}common/css/`);

console.log('result:', result);
console.log('result2:', result2);
```

the output is:

> result: http://dev.streamus.com:8080/common/foo.css
> result2: http://dev.streamus.com:8080/common/css/foo.css

I would expect `result` and `result2` to be equal.

My reasoning for this is that when I look at `path` documentation, https://nodejs.org/api/path.html#path_path_normalize_p, I see no instances where it appends a trailing slash. If there's no trailing slash I believe there should be an intelligent decision made as to whether the path points at a directory or a file.

Thoughts?

**Comment by guybedford** [comment]
Even on SystemJS 0.19.23, `System.normalizeSync('./foo.css', System.baseURL + 'common/css/');` definitely gives me the correct result of `common/css/foo.css` here. Perhaps you can share how to get the full replication.

**Comment by guybedford** [comment]
Oh I see your test case. We follow standard URL normalization logic so the above is certainly correct.
