### ISSUE TITLE
SystemJS config file is not just plain json

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [systemjs/systemjs#1140]
Hi, 

I'm working on adding SystemJS support to [dependency-tree](https://github.com/mrjoelkemp/node-dependency-tree), which returns a dependency tree as JSON given an entry point. To allow support for SystemsJS we would need to pass in the paths/map somehow. Currently [dependency-tree](https://github.com/mrjoelkemp/node-dependency-tree) would need to know about the specific System object instance and then call `System.paths` or `System.map` to get the actual key value pairs needed to resolve the paths. 

It would be nice if the SystemJS config could just be a JSON file that sits in a default location much like the package.json for node modules.  SystemJS could then internally call `System.config()` with the JSON config file. 

As a side note, it would also be nice to use the same path resolution code that SystemJS uses to resolve the paths for [dependency-tree](https://github.com/mrjoelkemp/node-dependency-tree). 

P.S: I'm more than willing to get my hands dirty with some pull requests if someone can just point me in the right direction.

**Comment by fictitious** [comment]
One of the use cases for SystemJS config file is to be included in the web page, like this:

        <script src="config.js"></script>

One config file that sits in a default location is often not enough - and it's good that you have to specify explicitly where your config is.

Plain json is not enough - with javascript, it's possible to have logic in config file that provides different settings for different environments, or do something else - here is one example: https://github.com/typhonjs-demos/backbone-parse-es6-todos-improved/blob/master/config/config-app-paths.js

That's some reasons why it's just plain javascript, and not json.

 > Currently dependency-tree would need to know about the specific System object instance 

One possible way is to use systemjs builder, which already has code for creating and configuring SystemJS instance. Something along these lines:

    var Builder = require('systemjs-builder');
    var builder = new Builder;
    builder.loadConfig('your-config-file.js').then(function() {
        // builder.loader is the SystemJS instance
    });

> As a side note, it would also be nice to use the same path resolution code that SystemJS uses to resolve the paths

As far as I remember this is what resolves module names to URLs:

    loader.normalize(name, parentName)

**Comment by marthinus-engelbrecht** [comment]
@fictitious Thanks, that solves my problem. The builder does everything I need.
