### ISSUE TITLE
SystemJS throwing CORS error

### ISSUE THREAD

**Issue by eestein** [systemjs/systemjs#1142]
I just updated to `SystemJS v0.19.23` and `JSPM v0.17`.
And right after I've done that, I started to receive this CORS error:

> XMLHttpRequest cannot load npm:typescript@1.8.7.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

[![enter image description here][1]][1]

Has anyone gone through that? Any ideas on how to solve it? I'm working on it since friday, even using `JSPM` and `SystemJS` gitters to try and get some help without luck =/

Thanks!

  [1]: http://i.stack.imgur.com/WZkqt.png

**Comment by guybedford** [comment]
In the upgrade path, the text explains both `jspm.browser.js` and `jspm.config.js` need to be in the page, with the browser file included first. See also http://jspm.io/0.17-beta-guide/creating-a-project.html, where this is explained at the end of the page as well.

**Comment by eestein** [comment]
@guybedford that was it... my bad, sorry for that!

now it's requesting for json.json.json file...

> http://localhost:8002/jspm_packages/npm/typescript@1.8.7.json.json.json

Should I open a new issue for that?
