### ISSUE TITLE
How can we load external / third party javascript files contains global code without module definition

### ISSUE THREAD

**Issue by rrawat-dev** [systemjs/systemjs#1147]
We want to load an external javascript file dynamically, which does not contain any module definition and creates some global objects. How can we achieve this using System js

**Comment by guybedford** [comment]
Try `System.import('https://path/to/file.js')`. If that gives you a CORS error, then set `scriptLoad` metadata. If that gives you a module-related error then set the format to global and use `exports` metadata.

**Comment by chriseyhorn** [comment]
@guybedford Can you elaborate on how to set the format to global and "use exports metadata" or point to the docs explaining how to do this?  I have done the System.import statement but get an AMD module did not define error.

**Comment by asapach** [comment]
https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta
See `format` and `exports`.

**Comment by chriseyhorn** [comment]
Ok got it, will System.import also work for a css file that the .js script uses?

**Comment by asapach** [comment]
https://github.com/systemjs/systemjs#plugins
https://github.com/systemjs/plugin-css
