### ISSUE TITLE
Unable to load the YouTube IFrame API

### ISSUE THREAD

**Issue by samueldjack** [systemjs/systemjs#1148]
I'm trying to load the YouTube IFrame API using the scriptLoad feature. My config.js is like this:
```json
    {
         ...
         "meta": {
              "youtube": {
              "scriptLoad":true,
              "format": "global",
              "exports": "YT",
              "defaultJSExtensions":false
          }
        },
        "map": {
            "youtube":"https://www.youtube.com/iframe_api"
            ...
         }
       ...
   }
```
When I use this config the console shows a failed GET request for `https://www.youtube.com/iframe_api.js ` - ie it has appended a `.js` extension. 

I hoped that setting defaultJSExtensions to false in the youttube section of meta would prevent this, but it didn't. 

What else can I try?

**Comment by guybedford** [comment]
defaultJSExtensions is a global property. Ideally don't use this global property if you can as it is being deprecated in the next release. But if you must then you can use package configuration to opt out of it with:

```javascript
System.config({
  packages: {
    'https://www.youtube.com': {
      defaultExtension: false,
      meta: {
        'iframe_api': {
          scriptLoad: true,
          format: 'global',
          exports: 'YT'
        }
      }
    }
  }
});
```

**Comment by samueldjack** [comment]
Thanks for the response Guy. However, I think there's a piece of the jigsaw I'm still missing. 

Given your config, how would I then import this in my code?

If I try `import "https://www.youtube.com/iframe_api"` then I get the No 'Access-Control-Allow-Origin' headers which show that it is using xhr to load the script.

The same thing happens if I do `import "youtube"` and add `"youtube":"https://www.youtube.com/iframe_api"` to my map section.

Is there something else I need in my config file?

**Comment by guybedford** [comment]
I just tested the above and it's definitely working fine for me with that config followed by `System.import('https://www.youtube.com/iframe_api')` (the same as an import).

**Comment by samueldjack** [comment]
It was my mistake. In updating my config I'd created a new "packages" node inside my original "packages" node, rather than merging the two!

All working now! Thanks for your help.
