### ISSUE TITLE
ignore require in commonjs format

### ISSUE THREAD

**Issue by joshunger** [systemjs/systemjs#1149]
I have an ES5 file that is being used by JSPM, Webpack, and Node.  I added the following code -

`typeof __webpack_require__ === 'function' ? require('image.png') : 'image.png'`

Is there a way to tell SystemJS to ignore this require?

Thanks.

**Comment by guybedford** [comment]
In SystemJS you can map individual requires to empty with map config - 

```
System.config({
  map: {
    'image.png': '@empty'
  }
});
```

Usually it's best to do this within package map configuration to isolate it as well.
