### ISSUE TITLE
amd define is undefined

### ISSUE THREAD

**Issue by cResults** [systemjs/systemjs#1152]
"jspm": "^0.16.19",

We are using System to help us transition from amd (require.js) to es6.  Most new work is being done with es6 modules and System is working great for that.  However, we have a large body of work written in amd that we expected to work with System.

Our index.html loads System and then uses System to import main.
```javascript
    <script src="/jspm_packages/system.js"></script>
    <script src="/src/form/config.js"></script>
    <script>System.import('/src/form/main.js');</script>
```
CASE 1:
the main file adds amd require and define to window as seen below.  It then uses require to pull in jquery, knockout, windowTools, and a dynamically defined viewmodel.  All of that works. 

The problem is inside the windowTools.Initialize method, define is undefined.

```javascript
//form/main.js:
window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;

require(['jquery',  'knockout', 'form/windowTools'], function ($, ko, _WindowTools) {
    require(['dynamicViewModelID'], function (vm) {
        _WindowTools.Initialize(vm);
    });
});
```

```javascript
//form/windowTools.js:
define(['jquery'],  //CASE 2: the define on this line is undefined in the case described in the post below
    function windowTools($) {
        function Initialize(vm) {
			//CASE 1: the define below is undefined in the case described in this post
			define('user', function () {
				return { id: '12', name:'Rodgers' };
			});
        }

        return {
            Initialize: Initialize
        };
    });
```

It would be great if there were a setting in the config, something like amd: true, that would add amd define and require to the window, so that it would be defined in all instances.  In the meantime, please advise how to make sure define is defined through out our application.

**Comment by cResults** [comment]
A second situation which appears on the surface to be another manifestation of the same issue is as follows.  

The karma.conf loads the test-main-karma.js which adds the amd methods define and require to the window.

Then test-main-karma.js requires jquery, knockout, Q, and windowTools.  When it pulls in the windowTools file (included in the previous post) the define method that is defining windowTools itself on line 1 is undefined.

In both cases it would be beneficial if there were a setting on the config that would just take care of adding define and require to the window.  Any guidance on how to make it work in the meantime will be much appreciated. 

Thank you for contributing very helpful library to the community.

```javascript
//karma.conf:
module.exports = function(config) {
  config.set({
    basePath: 'wwwroot',
    frameworks: ['jspm', 'jasmine-jquery', 'jasmine', 'jasmine-matchers'],
    jspm: {
        loadFiles: [
          'test/test-main-karma.js',
          'src/**/*.test.js',
        ],
        serveFiles: [
          'src/**/*!(.test).js',
          'src/**/*.html'
        ],
        paths: {
          "*": "*",
          'api/*': 'src/api/*',
          'form/*': 'src/form/*',
          'models/*': 'src/models/*',
          'testData/*': 'test/data/*'
        }
    },

    preprocessors: {
        'src/**/*.js': ['babel']
    },
    'babelPreprocessor': {
        options: {
            sourceMap: 'inline',
            modules: 'system',
            moduleIds: false,
            //loose: "all",
            optional: [
              "es7.decorators",
              "es7.classProperties",
              "es7.asyncFunctions",
              "es7.functionBind",
            ]
        }
    },

    reporters: ['progress'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  })
}

```

```javascript
//test-main-karma:
window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;

require([
    'jquery',
    'knockout',
    'q',
    'form/windowTools'
],
function ($, ko, Q) {
    window.$ = $;
    window.ko = ko;
    window.Q = Q;
    if (!ko.isObservableArray) {
        ko.isObservableArray = function (obj) {
            return ko.isObservable(obj) && !(obj.destroyAll === undefined);
        };
    }
});
```

**Comment by cResults** [comment]
As I read deeper into the module format documentation trying to find the piece I'm obviously missing, it is worth to noting that this app uses both amd-require and ES6 modules.

**Comment by guybedford** [comment]
The global define is temporarily removed when executing CommonJS or global modules. This is done to ensure that SystemJS can strictly enforce what format a module should act as in cases where it has a UMD pattern that we want to act as a CommonJS or global.

In these cases though, the global define is reverted to its original value after synchronous code execution, so that your setting of the global window.define should not be altered here.

The issue I think is actually that since you are setting the `window.define = System.amdDefine` inside an AMD module, this reversion code that resets the global define for the AMD module itself will undo your own assignment (it doesn't know that you assigned the global define, and thinks it still needs to revert the global define that it set).

Rather set `window.define = System.amdDefine` with a script tag.

I agree with you though that these catches are not obvious, and that a global setting would be a simpler approach here.

**Comment by cResults** [comment]
@guybedford thank you for the quick response.  Your post gave us the light we need to understand what we've been experiencing and resolved Case 1.  Your post also led us down the road to finding the answer for Case 2, which was solved by changing the preprocessors glob route to include the files in the test folder.

Thank you again for a valuable contribution to the community.
