### ISSUE TITLE
Web Worker Blob - Uncaught Error: Uncaught TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by shannonmpoole** [systemjs/systemjs#1153]
I know this is a weird edge case but I don't know how to solve it.

If you follow the example on [html5rocks](http://www.html5rocks.com/en/tutorials/workers/basics/#toc-inlineworkers) to inline a web worker you get the following error when you use importScripts to import the config after importing systemjs.

```
Uncaught Error: Uncaught TypeError: Failed to construct 'URL': Invalid URL
```

For example

```
var blob = new Blob([
            `self.onmessage = function(e) {
                var opts = e.data;
                if (opts.base) {
                    importScripts(\`\${opts.base}\${opts.packages}/system.js\`);
                    importScripts(\`\${opts.base}\${opts.config}\`); //<--throws error here
                    delete self.onmessage;
                }
            };`
        ]);

var worker = new Worker(URL.createObjectURL(blob));
worker.postMessage({
    base: document.baseURI,
    packages: 'jspm_packages',
    config: 'config.js'
});
```

I suspect it has to do with the internal baseURI detection not working correctly for blobs. I've double checked and the url does end up being correct in the worker `importScripts('http://localhost:8080/config.js')`. I think the error message is coming from something internal and not that url but Chrome debugging for web workers has not really been allowing me to step through it correctly so I can't find it exactly.

Any thoughts?

**Comment by shannonmpoole** [comment]
It seems that Firefox gave me a little more information:

```
TypeError: jspm_packages/github/jspm/nodelibs-assert@0.1.0 is not a valid URL.
```

**Comment by guybedford** [comment]
@shannonmpoole I think the issue here is that SystemJS needs t know the URL of the web worker itself so that relative requires can be made relative to that. By default the baseURL of the loader is set to the web worker URL.

Perhaps you can set a custom baseURL to work around this? Agreed it would be nice to handle this case somehow though.

**Comment by shannonmpoole** [comment]
@guybedford I originally tried to edit the baseURL in the config itself which didn't seem to have any affect. I also tried adding it to the worker before importing the config.

For example:
```
importScripts('http://localhost:8080/jspm_packages/system.js');
System.config({ baseURL: 'http://localhost:8080/' });
importScripts('http://localhost:8080/config.js'); //<--throws error here
```

I'm not sure how else to configure it.

**Comment by shannonmpoole** [comment]
@guybedford Never mind I must have messed something up. I started from scratch with jspm init and it seems to work ok now if I set the baseURL in the worker or in the config. Thanks for taking the time to look at this.

**Comment by guybedford** [comment]
:+1: thanks for letting me know. I don't think there would be an alternative unfortunately as the worker has no knowledge of the parent window href I believe.
