### ISSUE TITLE
Uncaught TypeError: Unexpected anonymous System.register call

### ISSUE THREAD

**Issue by roby2001** [systemjs/systemjs#1155]
Hey, I'm trying to set up my karma testing for angular2 following the example in [angular2-seed-master](https://github.com/mgechev/angular2-seed). After setting up my Karma and systemjs I'm getting the following error : 
`Chrome 48.0.2564 (Windows 8.1 0.0.0) ERROR
  Uncaught TypeError: Unexpected anonymous System.register call.
  at C:/Users/taigi100/Desktop/Refact/jspm_packages/system.src.js:2912`

With PhantomJs it's the same. Here are my config files : 

[ `karma.config.js`] (http://pastie.org/10756032)
[ `config.js` ](http://pastie.org/10756030)

**Comment by guybedford** [comment]
You mustn't include System.register modules with script tags in the page, they need to be explicitly imported by SystemJS itself.

**Comment by roby2001** [comment]
I don't think I am ? Here's my index.html : http://pastie.org/10758967

**Comment by guybedford** [comment]
In your karma.config.js, scripts declared to Karma to load will be loaded with script tags, which isn't compatible with the way SystemJs loads modules itself. I couldn't load your Karma config again here to check, but I think that may be the issue here.
