### ISSUE TITLE
Combine crossOrigin and authorization meanings

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1156]
When using XHR, we have `authorization` meta which can be `true` to indicate that XHR should be with credentials, or it can be an authorization string to imply withCredentials as well as setting this header.

When using script loading, we now have `crossOrigin` which can be set to `useCredentials` or to `anonymous`.

Ideally we can combine these two cases, with two meta properties that better capture a shared meaning here:

* withCredentials: true / false
* authorization: string

When an `authorization` string is set, we then automatically treat the XHR request as `withCredentials: true`. We then deprecate the path of `authorization` being set to a boolean.

When `withCredentials` is set to true with a `scriptLoad`, we then set `crossOrigin: useCredentials` on the script tag.

I think that unifies the meaning without any loss. Feedback welcome too.

//cc @asapach

**Comment by guybedford** [comment]
(Note that the implication above is to deprecate `crossOrigin` as a meta property)

**Comment by asapach** [comment]
@guybedford, the problem is that `crossOrigin` actually has 3 states:
* `none` (attribute/property not set) - works as a normal `<script>` tag
* `anonymous` - the user-agent sets the `Origin` header and expects the server to respond with a `Access-Control-Allow-Origin` header. If the server doesn't support CORS the request fails.
* `use-credentials` - in addition to the behavior above also sends the user credentials (basic auth or cookies, etc.) and expects the server to respond with `Access-Control-Allow-Credentials` header.

So if you remove the `crossOrigin` meta option I'm afraid there's no way to distinguish between `none` and `anonymous`.

**Comment by guybedford** [comment]
@asapach thanks for the feedback. The `anonymous` value is a security constraint though, designed to fit CORS support to existing script tag mechanisms. This is an important goal certainly, but I'm not sure I see the value in supporting it here.

**Comment by asapach** [comment]
@guybedford, I've explained the rationale behind it in #1135. I'll admit that 99% of systemjs users will never use it (or rather have use for it), but for us this is a showstopper: without it we'll not be able to enable error reporting in production. If you don't think it's worth supporting it in the core, could you at least please add a hook that would allow us to enable it in a plugin?

**Comment by guybedford** [comment]
Ah right, I forgot it was specifically the anonymous case that provides the correct errors for you here.

I guess it also works with `useCredentials` though?

**Comment by asapach** [comment]
Yes, any `crossOrigin` value other than `none` works.

**Comment by guybedford** [comment]
@asapach what do you think about making `crossOrigin: 'anonymous'` the default for scripts loaded by the module loader? That way we can align fully with the XHR workflow.

**Comment by asapach** [comment]
That would require CORS support on the back-end. If it's not enabled, requests will fail, which is an unpleasant surprise for developers.

**Comment by guybedford** [comment]
Ok sure. Let's keep it as it is then, which is fully transparent with how the browsers operate.
