### ISSUE TITLE
megawac/MutationObserver.js shim breaks SystemJS on IE10

### ISSUE THREAD

**Issue by laurentgoudet** [systemjs/systemjs#1157]
On browsers where the `system-polyfill.js` is loaded, and which don't have native `MutationObserver` support, the `megawac/MutationObserver.js` shim silently breaks SystemJS.

See this plunker where I forced `system-polyfill.js` to be loaded & the `MutationObserver` shim to be used for a live demo: https://plnkr.co/edit/zFhx1jg5umsDbOEMupK7?p=preview.

Looking at the code path, the shim doesn't support the `characterData` observer used by SystemJS and never calls the drain of the Promise shim. However, the shim documentation seems to suggest that it should work: "characterData: currently follows Mozilla's implementation in that it will only watch textNodes values and not, like in webkit, where setting .innerHTML will add a characterData mutation."

**Comment by guybedford** [comment]
This sounds like a compatibility issue between when.js (https://github.com/cujojs/when) and the mutation observer shim.

In a case like this, it may be advisable to alter system-polyfill.js to contain the URL polyfill combined with your own choice of Promise polyfill that doesn't have this conflict.

**Comment by megawac** [comment]
I haven't had a chance to look into this yet, but possibly related:
https://github.com/stefanpenner/es6-promise/pull/1
