### ISSUE TITLE
Conditional Loading and Paths

### ISSUE THREAD

**Issue by KingRial** [systemjs/systemjs#1159]
I'm trying to test how conditional loading works and I met the following issues:

I **created** an "environment.js"
```javascript
export let ENV = {
  customPath: 'test',
  customModule: 'custom-module'
};
export { ENV as default };
```
And **configured** SystemJS
```javascript
System.config({
  paths: {
    "*": "/*",
    "scripts:*": "scripts/*",
    "test:*": "tests/*"
  },
  map: {
    "ENV": "scripts:environment",
  }
});
```
After that I built a custom javascript module with the following "**import**" methods:

I'm trying to import a library using conditional loading and:
```javascript
import { default as ConditionallyLoaded } from 'test:#{ENV|ENV.customModule}';
```
is **working correctly** loading "_tests/custom-module.js_".

```javascript
import { default as ConditionallyLoaded } from '#{ENV|ENV.customPath}:custom-module';
```
It **fails**;
It will try to load the physical path "_test:/custom-module.js_" instead of using the path configured on SystemJS and translating it to "_tests/custom-module.js_"

I expected systemJS to parse the resulted string and then transform it to the correct path to load.

```javascript
import { default as ConditionallyLoaded } from '#{ENV|ENV.customPath}:#{ENV|ENV.customModule}';
```
It **fails**;
It won't parse the second conditional and will faill to load "test:/#{ENV|ENV.customModule}"

I expected systemJS to be able to handle multiple parse operations.

I am pretty new to SystemJS so I could be using the conditional loading in the wrong way instead of having met a bug.

P.S.
I am using [c9.io](https://ide.c9.io/kingrial/systemjs-playground) to play with the conditional loading.
Feel free to use that project to check the issue.

**Comment by guybedford** [comment]
Conditional substitution here happens at the end of normalization. That is,
it does not apply map or paths or anything else. The reason for this is to
ensure that even with this conditional branching, it is possible to predict
where a module will be loaded from.

Think of it like entering a relative URL, where it normalizes everything
with a placeholder, then only replaces that placeholder at the end.

**Comment by KingRial** [comment]
This explains a lot!
Thanks.
