### ISSUE TITLE
Issues with jspm config.js when system.js file is moved around

### ISSUE THREAD

**Issue by grofit** [systemjs/systemjs#1160]
This is a very odd one and I am not entirely sure if this bug should be raised here or within JSPM, however as system.js exhibits the problem it looks like this should be the owner although feel free to move.

So basically I have a scenario where I have a custom path and custom package in my jspm `config.js` file. This all works fine, however the `jspm_packages` folder is not getting put into the source control and there is a dependency upon the `system.js` file within there for an example.

Now the problem rears its head when I take the `system.js` file out of the `jspm_packages` folder and put it in another directory (in this case `libs`). This then stops working as it resolves the custom path variable, but doesn't resolve the packages.

Here is an SO question on the matter showing the config example:

http://stackoverflow.com/questions/36006012/moved-system-js-file-from-jspm-packages-to-another-folder-wont-resolve-packages

Now after struggling to find out why it was not working when it moved, one of the aurelia team mentioned using the `system.src.js` file instead to debug what is actually happening to stop the `packages` from being resolved. However the odd thing is when we use the debug `system.src.js` file it resolves correctly (when put in the other folder too).

This was done as part of the `aurelia-chart` repo, so you can see a working example of this issue if needed.

https://github.com/grofit/aurelia-chart

- Clone it
- Go to `examples/index.html`
- Change the `<script src="libs/system.src.js"></script>` to `<script src="libs/system.js"></script>`
- Run the index.html page
- It will look for `../dist/commonjs/.js` and fail rather than `../dist/commonjs/index.js`

If you were to do a `jspm install` and use the system.js within the created `jspm_packages` folder it would also work, however when the `system.js` file is taken out of that folder it stops working again.

Feel free to ping me if you have any other questions but it took me forever to track down the issue, and the use case here is unique as I want to bundle an example with an aurelia plugin without having to get the user to go to another site (i.e plunker) or cloning it to test it, most of the other aurelia plugins tend to make the user clone/gulp serve to see the thing working.

**Comment by guybedford** [comment]
This seems to be specific to SystemJS 0.19.6, and doesn't happen with later versions. I'd suggest upgrading if you can, otherwise create a custom minification of system.src.js, which also seems to work.
