### ISSUE TITLE
Unexpected anonymous register

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1162]
This error could do with rewording to mention not to include system register with a script tag.

**Comment by probins** [comment]
I'm confused. I've just been experimenting with modules converted with Babel 6 into `System.register` using `system-register-only.js`, and get this error. How else do I load this file other than in a script tag?

**Comment by guybedford** [comment]
Via a `System.import` is the solution that this issue is tracking documenting!

**Comment by probins** [comment]
ah right. :-)

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/5d20c2c797528a5dd8818c4cb4522572d152ccd8.
