### ISSUE TITLE
System.import source code instead of filepath

### ISSUE THREAD

**Issue by Alphapage** [systemjs/systemjs#1163]
Hello,

Is it possible to import javascript source code instead of requesting a filepath ?

I can't find this feature, but I think when you are requesting a filepath, systemjs only loads it contents: so the source code. How to avoid this step?

Thanks in advance for your comments.

**Comment by guybedford** [comment]
Have a look at `System.define(System.normalizeSync('name'), source)` or otherwise just using standard System.register bundling here.

**Comment by Alphapage** [comment]
I wasn't able to find the info. Thank you very much.

Another question related to this feature:
Do I need to import in reverse order ?
Here is an example:
```js
let testvar='a test';
export * from 'test';
```
```js
import * from 'test'
console.log(testvar);
```
I need to import the first one before the second which is executing the code.
Does systemjs provide an event when it needs to import a js file to be able to give it the source code via system.define ?

**Comment by guybedford** [comment]
The only events provided are the loader hooks themselves. System.normalize or System.locate can sometimes be hijacked for these sorts of uses, like the bundle config does, but it may not be advisable.
