### ISSUE TITLE
cache control

### ISSUE THREAD

**Issue by KlausSchade** [systemjs/systemjs#1165]
while developing it should be possible to control the caching of modules 
For example, I'm developing an angular app with several modules which are loaded from the main.js/main.ts file. When I modify a module this is not recognized by the systemjs loader.
My workaround looks like that:
```javascript
        var systemLocate = System.locate;
        System.locate = function(load) {
            var System = this;
            return Promise.resolve(systemLocate.call(this, load)).then(function(address) {
                if(address.indexOf("/app/") > -1) {
                    return address + System.cacheBust;
                }
                return address;
            });
        };
        System.cacheBust = '?bust=' + Date.now();
		System.import('app/main');
```
I found this thanks to [http://vadosware.com/2015/05/17/cache-busting-with-systemjsaurelia/](url)

**Comment by guybedford** [comment]
Sure, this has been discussed quite a bit before, with my viewpoint described at https://github.com/systemjs/systemjs/issues/172#issuecomment-52262588.

**Comment by KlausSchade** [comment]
Thanks for your answer, I agree, and obviously you gave the idea for that hook.
Maybe you could make a note in the documentation, so that other developers don't run in this problem.

**Comment by guybedford** [comment]
Definitely, it's worth mentioning.
