### ISSUE TITLE
enoent when using nodejs

### ISSUE THREAD

**Issue by Alphapage** [systemjs/systemjs#1166]
Hello,

I have created a little example to test or try systemjs based on main page tutorial, but it throws enoent when I set babel as the transpiler.
systemjs tries to find babel in the current folder __dirname, but not in node_modules.

What am I missing ? Is there a config to enable for nodejs ?

Thanks in advance for your help.

**Comment by guybedford** [comment]
You can use map configuration to tell SystemJS where to find Babel as described in the last code example in this section - https://github.com/systemjs/systemjs#browser.

**Comment by Alphapage** [comment]
As it is nodejs and npm environment, I thought systemjs had the ability to fetch from known folders node_modules local or global.
Maybe jspm has such a feature!

**Comment by guybedford** [comment]
Oh right, yes SystemJS will work out where to find Babel when running in Node. Note though that it is only compatible with Babel 5 in this form.

**Comment by Alphapage** [comment]
OK. Thank you for the info. I'm using babel6.
Do you plan to support babel 6 soon ?

**Comment by guybedford** [comment]
Babel 6 is supported through the plugin at systemjs/plugin-babel.
