### ISSUE TITLE
Package loading issues

### ISSUE THREAD

**Issue by chriseyhorn** [systemjs/systemjs#1167]
I have spent several hours trying to figure out how to get this package to load.  Here is what I have tried and the results.

`jspm install npm:cesium`

I then use `import 'cesium';`

With the default install I receive the following errors in my console.

> GET http://localhost:3000/lang.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/prim.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/logger.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/parse.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/optimize.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/pragma.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/transform.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/requirePatch.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/env.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/commonJs.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/source-map.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/jspm_packages/npm/requirejs@2.1.22/bin/process.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/jspm_packages/npm/requirejs@2.1.22/bin/parse-js.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/jspm_packages/npm/requirejs@2.1.22/bin/squeeze-more.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/jspm_packages/npm/requirejs@2.1.22/bin/consolidator.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.src.js:4935 GET http://localhost:3000/env/file.js 404 (Not Found)N @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935(anonymous function) @ system.src.js:4935
> system.js:4 Uncaught (in promise) Error: Error: XHR error (404 Not Found) loading http://localhost:3000/lang.js(…)

My next attempt was to specify an AMD override during registration.

`jspm install npm:cesium -o "{format:'amd'}"`

Same import statement and this is the error I receive in my console.

> Uncaught (in promise) Error: ReferenceError: require is not defined
> 	    at eval (http://localhost:3000/jspm_packages/npm/cesium@1.19.0/index.js:6:12)
> 	    at eval (native)
> 	Evaluating http://localhost:3000/jspm_packages/npm/cesium@1.19.0/index.js
> 	Error loading http://localhost:3000/jspm_packages/npm/cesium@1.19.0/index.js as "npm:cesium@1.19.0/index" from http://localhost:3000/jspm_packages/npm/cesium@1.19.0.js

Here is the index.js for the package:

`/* */ 
"format amd";
/*jshint node:true*/
'use strict';

var path = require('path');
var requirejs = require('requirejs');

requirejs.config({
                     paths : {
                         'Cesium' : path.join(__dirname, 'Source')
                     },
                     nodeRequire : require
                 });

module.exports = requirejs('Cesium/Cesium');`

Any help is very much appreciated.

**Comment by guybedford** [comment]
Loading requirejs within a main likely won't end well. Perhaps you can try loading `cesium/Source/Cesium/Cesium.js`?

**Comment by guybedford** [comment]
Just let me know if you need further help here at all. As a jspm package configuration issue, this is probably best to track in the jspm/registry project issue queue as well.

**Comment by ukitake** [comment]
I'm having the exact same problem as OP.  No matter what I do I get one of the two sets of errors he described above.  The workaround for now was to just import Cesium and Require with script tags :(

Any guidance?

**Comment by dinoboff** [comment]
Try with:
```
jspm install cesium -o '{
  "main": "Source/Cesium.js",
  "meta": {
    "*.js": {
      "format": "amd"
    }
  }
}'

**Comment by westandy** [comment]
Sorry for being late to this party, but "format":"cjs" // CommonJS seems to work.  "amd" gives me `(SystemJS) AMD module http://localhost:3000/node_modules/cesium/Build/Cesium/Cesium.js did not define`

**Comment by greenlaw** [comment]
@westandy could you post your full procedure/configuration?  Even with "format":"cjs" I'm still having the same issues as OP.  Thanks in advance.

**Comment by westandy** [comment]
Greenlaw, see if my post on SO helps:
http://stackoverflow.com/questions/40773620/get-cesium-systemjs-and-angular2-to-work/40776562?noredirect=1#comment68925563_40776562
