### ISSUE TITLE
system-csp-production - unexpected token export 

### ISSUE THREAD

**Issue by kresli** [systemjs/systemjs#1172]
Just created some simple example of using `system-csp-production.js` but whatever I'm trying I still getting an error for `unexpected token export`. Its error free soon as I switch to `system.js` so I assume the path in the bundle option in the `config.js` is set up incorrectly. However I was experimenting to change a setup in `config.js` with no luck. I've been reading the doc over and over, but can't find the solution. So Im not sure if this is a bug or my own mistake.
here is the sample repo: https://github.com/kresli/system-csp-production-babel-bundle-test
<img width="1075" alt="screen shot 2016-03-21 at 12 49 23" src="https://cloud.githubusercontent.com/assets/3826097/13919105/6df6ff52-ef63-11e5-9ab4-bfe720584e12.png">

Also another question, do I need install `babel-core` separately if I'm using SystemCSP?
Thanks.

**Comment by guybedford** [comment]
System CSP Production is only designed to load compiled modules - AMD, System.register or globals. You would need to run ES module syntax through a build process first to load them here.

**Comment by kresli** [comment]
Thank you for your response. 
So basically I can make it work if I load `testInjector.js` through the script tag.
testInjector: 
```
System.import( 'src/bundles/test-bundle' )
  .then( function(){
    System.import('src/modules/test');
  } )
```
First I register the bundle and then I'm fetching the source. Make sense, but this don't feel quite right. I will expect some setup in `config.js` to do it for me. Am I missing something here?

**Comment by guybedford** [comment]
See the bundles configuration here - `System.config({ bundles: { 'src/bundles/test-bundle': ['src/modules/test.js'] } })` will then allow it to work with a single `System.import('src/modules/test')`.
