### ISSUE TITLE
nodejs harmony

### ISSUE THREAD

**Issue by Alphapage** [systemjs/systemjs#1173]
Hello,

Nodejs doesn't support module for now, so I was thinking of using systemjs to bypass this limitation.
The doc tells that systemjs requires a transpiler, but with nodejs harmony you just need to convert es6 module to commonjs.

Is it possible to use nodejs harmony with systemjs ?

Thanks in advance for your help.

**Comment by probins** [comment]
Until import/export are supported natively, you need a transpiler to convert es6 into something that is supported natively. That applies to Node just as much as browsers. SystemJS doesn't 'bypass' anything. See https://github.com/ModuleLoader/es6-module-loader/issues/463 for discussion of a cut-down transpiler that only implements import/export.

**Comment by Alphapage** [comment]
Thank you for the info.
I need a little more help because I'm fighting with babel-plugin-transform-es2015-modules-commonjs plugin.
I'm using systemjs-plugin-babel with this config:
```js
System.config({
    map: {
        'systemjs-plugin-babel':  '/plugin-babel.js'
        , 'systemjs-babel-build':  '/systemjs-babel-node.js',
        'babel-plugin-transform-es2015-modules-commonjs': '/babel-plugin-transform-es2015-modules-commonjs'
    },
     transpiler: 'systemjs-plugin-babel',
  babelOptions: {
    sourceMaps:'inline',
    presets:[],
    plugins: ['babel-plugin-transform-es2015-modules-commonjs']
  }
});
```
I get enoent: unable to locate 'path' from '/path'

How do you achieve my goal ?

**Comment by probins** [comment]
I've not used this combination myself, but should the path read `...-commonjs.js`?

**Comment by Alphapage** [comment]
I think systemjs doesn't understand nodejs environment. So it tries to load path (or fs...) from the current folder instead of letting node execute the code.

**Comment by Alphapage** [comment]
Here is the link of a sample project:
https://github.com/Alphapage/testsystem.es6
```npm install``` then ```npm run debug:test```

**Comment by guybedford** [comment]
A minimal transpilation is being tracked in https://github.com/systemjs/plugin-babel/issues/28.
