### ISSUE TITLE
Requesting something in a bundle is case sensitive 

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1177]
Assume you have 

```javascript
'dist/billingmanager/billing/billing-build.js': ['billingmanager/billing/billing.js', 'billingmanager/billing/copayWidget.js', 'billingmanager/billing/invoicesVm.js', 'billingmanager/billing/bulkPaymentsVm.js', 'billingmanager/billing/creditCardPaymentProcessingVm.js', 'billingmanager/billing/bulkSignatureVm.js', 'billingmanager/billing/miscData.js', 'billingmanager/billing/bulkClaimsVm.js', 'billingmanager/billing/paymentVm.js', 'billingmanager/billing/listItemVm.js', 'billingmanager/billing/billingGridDropdownMenu2.htm!text', 'billingmanager/billing/copayWidget.htm!text'],
```

If a developer accidentally has something like

```javascript
System.import('billingmanager/billing/Billing.js').then(bundle => .....);
//(note the capital "B")
```

Then the individual file 'billingmanager/billing/Billing.js' will be requested, it'll parse, and then the bundle will be requested once the dependencies are discovered. 

Would an option for this to be case INsensitive be useful?  I haven't yet looked in the code for SystemJS, but I can't imagine this would be difficult to implement.  My apologies if such an option already exists; I looked but didn't see anything.

**Comment by guybedford** [comment]
SystemJS is case sensitive yes. I think it is for this reason that npm enforces lower casing conventions. The point to bear in mind is that the module loader itself, unless explicitly deciding not to be which it hasn't, will be case sensitive. So these painful cases may just be something to ensure tooling provides suitable warnings and handling of.

**Comment by guybedford** [comment]
Closing, but do let me know if you disagree here. Casing is still something to be properly dealt with in this ecosystem.

**Comment by arackaf** [comment]
I was thinking the best way, ideally, would be to open up your pipeline to further customization.  I haven't looked through the code, but I'm hoping it's feasible to just inject a function to check if a requested module is in a bundle.

```
(moduleName, bundles) => bundles.find(b => b.dependencies.some(d => d.toLowerCase == moduleName.toLowerCase);
```

Which would return the bundle to load, or undefined.  Just spit-balling though - I have no idea if that would work.

**Comment by arackaf** [comment]
Looking at SystemJS source, I didn't immediately see any good places for a hook to override the default bundle-locating behavior.  But thinking about it, I think I came up with a decent workaround—I hate to even call it that; I'm just hooking into normalize to correct incorrect paths.

I'll just leave it here in the off chance it might help someone.  @guybedford please let me know if you see any problems here.

```javascript
var isProduction = false;
var moduleNameNormalizer = {};

if (!/(localhost|locallike|192\.168\.|10\.1\.)/.test(window.location)){
    config.bundles = bundlePaths;
    isProduction = true;

    Object.keys(bundlePaths).forEach(name => {
        bundlePaths[name].forEach(item => {
            moduleNameNormalizer[item.toLowerCase()] = item;
        })
    });
}

var systemNormalize = System.normalize;
System.normalize = function (name, parentName, parentAddress) {
    if (isProduction) {
        let nameToCheck = name.toLowerCase(),
            foundValue = moduleNameNormalizer[nameToCheck] || moduleNameNormalizer[nameToCheck + '.js'];

        if (foundValue) {
            name = foundValue;
        }
    }

    //rest of normalize, if any, ie change `text!foo` to `foo!text`
```

**Comment by Munter** [comment]
I highly recommend you teach your developers to fix their typos instead of adding case insensitiveness in your tooling. Case insensitive file matching has only ever brought bad stuff with it

**Comment by arackaf** [comment]
The problem is *finding them*.  If I could go back in time I'd have every single file path be lowercase and hyphenated as needed.  That didn't happen.  Windows (which we work off of, and who hosts our application) is case insensitive.  So this seems like a reasonable workaround to prevent superfluous file loads in the case of file path with a mis-cased letter (which would otherwise be un-detectable)

**Comment by asapach** [comment]
We detect case sensitivity problems by running our modules through Karma - it's case sensitive.

**Comment by arackaf** [comment]
That's actually really smart.  Many roads lead to Rome :)

What I'm most interested in here is if someone who knows SystemJS well can comment on whether this approach has any potential pitfalls.  As far as I can tell, worst case would be me somehow normalizing the requested name wrongly, which would result in the very superfluous file load I'm trying to avoid (so no worse than the status quo).

Is there anything else here I'm not seeing?

**Comment by npbenjohnson** [comment]
I made [this middleware](https://github.com/npbenjohnson/case-sensitive-sanity-check) to get warnings about successful requests with wrong casing at runtime. If there were a hook you could do something similar with builder. @arackaf Case sensitivity also causes systemjs-hot-reloader to not detect changes on incorrect files.
