### ISSUE TITLE
Conditional loading of polyfills at the module tree

### ISSUE THREAD

**Issue by laurentgoudet** [systemjs/systemjs#1179]
Sorry if it has been asked, I couldn't find any similar issue.

One common front-end development task is to load polyfills for the features not yet fully supported by the targeted browsers.

The traditional approach in doing so is to always load the polyfills, as most of the time only feature detection could tell if a browser supports a polyfill or not. This leads to unnecessary bytes being loaded, for the benefit of only a fraction of the users. As time goes, browser support is often revised, but such polyfills are rarely cleaned up in complex environment.

Projects such has the well known https://github.com/SlexAxton/yepnope.js have tried to solve that. They are however often hard to integrate with other loaders & complex dependency trees.

I think it would be beneficial if SystemJS had native support for such a widely common use case. While that could be achieved through `System.import()`, having a declarative way to list the polyfills and their test conditions (through the SystemJS config) would allow for a much more powerful workflow (integrated with `System.builder` as well - to exclude these from the bundles). Modules would probably still need to import the polyfills, but at least these won't be loaded for every users.

**Comment by jpeters5392** [comment]
@laurentgoudet This could probably be accomplished through a custom SystemJS plugin.  Here is a rough outline of what you might be able to do.  The plugin would only load the imported polyfill if it was actually needed.  If all of your polyfills are in the same folder structure then you could using bundle arithmetic to exclude that folder from your bundling so that they are not bundled in with your app code.

```
// Not sure if it is supported to add custom configuration properties
System.config({
        map: {
            "somePolyfill": "vendor/polyfills/somePolyfill.js",
            "polyfill": "vendor/plugins/system-plugin-polyfill.js"
        },
	polyfills: {
  	    'somePolyfill': function(){return typeof window.Promise !== 'undefined';}
        }
});

// Plugin pseudo-code
var polyfills = Object.keys(System.polyfills);

exports.fetch = function(load, fetch) {
    return new Promise(function(resolve, reject) {
        polyfills.forEach(function(key) {
            if (System.normalize(key) === load.address) {
                if (!System.polyfills[key]()) {
                    // load the polyfill
                } else {
                    // we don't need the polyfill
                    resolve('');
                    return;
                }
            }
        });
    });
  };

// In your code file
import myPolyfill from 'somePolyfill!polyfill';
```

**Comment by guybedford** [comment]
Conditional loading is designed specifically for this. Try:

```javascript
import 'polyfill#?if-polyfill.js`
```

where `if-polyfill.js` exports a default condition evaluation of true or false.

This syntax is still somewhat experiemental and it's yet to be determined if it will be deprecated or not, hence the lack of documentation. The alternative is to do this through package config, which will definitely not be deprecated:

```javascript
System.config({
  packages: {
    'polyfilled-app': {
      map: {
        './polyfill.js': {
          './supports-native-feature.js': '@empty'
        }
      }
    }
  }
});
```

Where the code would be `import './polyfill.js'`.

**Comment by laurentgoudet** [comment]
Thanks, I actually think the package config is nicer as it allows to managed all the conditional loadings from a single location, as well as working with existing import linting solutions (e.g., [eslint-import-resolver-jspm](https://github.com/nfl/jspm-resolve/tree/master/plugins/eslint-import-resolver-jspm)). I'll give it a go soon.
