### ISSUE TITLE
Investigate Edge bug

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1182]
Posting to track Aurelia's critical bug in Edge. Apparently this can be replicated via the docs site at http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/what-is-aurelia with devtools closed showing incorrect loading behaviour.

**Comment by guybedford** [comment]
This is resolved by the implementation of https://github.com/systemjs/systemjs/issues/1070.

The work around is to include &lt;script src="url-polyfill.js"></script> before SystemJS where the file for url-polyfill.js is from https://github.com/ModuleLoader/es6-module-loader/blob/master/src/url-polyfill.js.

**Comment by guybedford** [comment]
@DavidRogers that needs to be included as well as the Promise polyfill before SystemJS.

**Comment by guybedford** [comment]
Released in 0.19.25.

**Comment by DavidRogers** [comment]
I forgot to mention that I did have the bluebird Promise polyfill included as well. (And they are both included before SystemJS).

**Comment by guybedford** [comment]
Can you investigate where in the pipeline it is not working? For example, is the bundle being executed? Does it work with devtools open? Are there errors being thrown Etc etc. There are many possible compatibility issues.

**Comment by DavidRogers** [comment]
It is the same aurelia issue (https://github.com/aurelia/framework/issues/227) that is referenced in this issue.The nature of this bug makes it very difficult to debug since everything works fine with devtools open. The referenced issue has a lot of good info in it that is better than what I could provide you.

**Comment by michaelmalonenz** [comment]
@DavidRogers @guybedford I experienced the same issue, but after removing Bluebird promises, it starts up as expected - even with decent performance (which is what Bluebird was addressing), so it's some sort of interaction there. I am using `jspm v0.16.32` and `systemjs v0.19.25`

**Comment by DavidRogers** [comment]
I can confirm that removing bluebird as @michaelmalonenz suggests does fix the issue.

**Comment by DerAlbertCom** [comment]
i can not confirm this. with or without bluebird, if you use `.globalResources()` in the configuration of aurelia it the application does not startup.

**Comment by SamDeBlock** [comment]
Probably related to bug in Edge, see:
https://github.com/aurelia/framework/issues/227#issuecomment-246425032
and https://github.com/Microsoft/ChakraCore/issues/1415

**Comment by sberney** [comment]
I agree with @SamDeBlock . We have been experiencing this issue too. I don't think SystemJS is at fault, but it does seem to provoke the bug. Not that it adds much information, but I [just summarized](https://github.com/aurelia/framework/issues/227#issuecomment-297122244) this.

You might consider adding a check [on this line](https://github.com/systemjs/systemjs/blob/0.19.47/dist/system.src.js#L4952) along the lines of

```javascript
if (typeof meta === 'function')
  meta = meta();
```

Which makes logical sense, but is not something I have tested, and given the suspected nature of this as a bug with *Edge*, it may not result in proper behavior either.
