### ISSUE TITLE
Support moduleId for relative URL paths (e.g. Angular2)

### ISSUE THREAD

**Issue by rogerbush8** [systemjs/systemjs#1185]
CommonJS has a feature which provides access to the base path to a component in the filesystem.  This can be used to have relative paths in, for example, Angular2 component directives (templateURL and styleURLs).  Relative paths for components are much nicer once projects get big, and in general when one starts moving toward web components and better dependency management.

The Angular2 "hero" tutorial uses SystemJS, and so anyone learning that and trying to make their first components run into this nit.

There are a lot of issues/requests for this, but I think they are being attributed to Angular2, whereas they may belong in SystemJS (better solved in the loader).

Here's an example for CommonJS

@Component({
  selector: 'home-button',
  templateUrl: 'home.html',
  moduleId: module.id,         // Not sure what this evaluates to but somehow includes base to path
  styleUrls: ['home.css']
})

// Without Relative URLs
@Component({
  selector: 'home-button',
  templateUrl: 'app/components/home/home.html',  // paths get harder to maintain with increasing complexity
  moduleId: module.id,         // Not sure what this evaluates to but somehow includes base to path
  styleUrls: ['app/components/home/home.css']
})

**Comment by guybedford** [comment]
Did you try doing just:

```
@Component({
selector: 'home-button',
templateUrl: './home.html',
moduleId: module.id, // Not sure what this evaluates to but somehow includes base to path
styleUrls: ['./home.css']
})
```

here? That should definitely work out surely?

Thanks for mentioning this though. It is a critical pattern in a module system, and there are a few ways of going about this, so it's important to get the details right.

I'd be interested to know what normalization Angular is actually running on the returned string values. It could be doing `System.normalizeSync(component.templateUrl)` or `System.decanonicalize(component.templateUrl)` or `System.normalize(component.templateUrl).then(...)` or even just `path.resolve(component/templateUrl)`. I guess it is probably doing the last one here, but let me know if I am wrong.

**Comment by rogerbush8** [comment]
The code you provided will only work if there are no intermediate directories.  That is, the path is relative to the root directory and not the file itself.  This works fine if you put all your files in a single directory, however, as you move toward componentization, you tend to put like files into the same subdirectory, and want paths that are shorter.

Note sure if this is helpful, but this looks like the mechanism (although I have not validated by looking through the code):  http://wiki.commonjs.org/wiki/Modules/1.1:

In a module, there must be a free variable "module", that is an Object.
The "module" object must have a read-only, don't delete "id" property that is the top-level "id" of the module. The "id" property must be such that require(module.id) will return the exports object from which the module.id originated. (That is to say module.id can be passed to another module, and requiring that must return the original module).
The "module" object may have a "uri" String that is the fully-qualified URI to the resource from which the module was created. The "uri" property must not exist in a sandbox.

Here is a short post, which doesn't explain much, but reiterates the value:  http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/

I will try to do a little spelunking through the angular code to see if I can answer your last questions.

**Comment by rogerbush8** [comment]
Here's a fairly concise explanation of the feature added to Angular2 w.r.t. CommonJS and it's benefit:

http://schwarty.com/2015/12/22/angular2-relative-paths-for-templateurl-and-styleurls/

**Comment by rogerbush8** [comment]
So I looked into this at a little more detail, and it seems like there is already enough mechanism to handle this reasonably well (and I'm not sure SystemJS needs any changes).  There are so many things working together, it's often difficult to figure out what to change and where.

Most using Angular2 are using Typescript.  I've found that angular2 works best when using the following Typescript compiler options:

  "compilerOptions": {
    "target": "es5",
    "module": "system",
...

So the module output type is system(js).  Let's assume the output format is 100% correct.  Looking at the output .js file, I see:

System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
...

Writing __moduleName to the console, from one of my components:

http://localhost:3000/app/employee/employee.js

And I see the addition of __moduleName was in a related, recently resolved ticket:

https://github.com/systemjs/systemjs/issues/340.

It's a simple matter to write a small helper function that solves my issue.  Since __moduleName is already in the Typescript system module output format, I'm thinking there's nothing to do on the SystemJS side that hasn't already been done, and a tiny amount of work would get this working in angular2.

I'll close this after you see it and file something in angular2.

Thanks for your help!

**Comment by rogerbush8** [comment]
N.B. this works (although would be nice to see this subsumed in angular2):

function rpath (file) {
    let s = getLocation (__moduleName).pathname;
    s = s.substr (1);
    s = s.substring (0, s.lastIndexOf ("/") + 1)
    return file ? s + file : s;
}

@Component ({
    selector : 'gga-need',
    directives : [ OverflowBadgeComponent, SiteCellComponent ],
    templateUrl : rpath ('site_need.html'),  // path is 'app/site_need/site_need.html'
    styleUrls : [ 'app/schedule/schedule.css' ]
})

**Comment by guybedford** [comment]
Right I see, so if you're writing ES modules you probably want to use the following then here:

```javascript
@Component({
selector: 'home-button',
templateUrl: './home.html',
moduleId: __moduleName,
styleUrls: ['./home.css']
})
```

We create a `__moduleName` global for ES modules, pending the contextual specification in ES modules (which will be coming). The point is that `module` is a purely CommonJS construct, so is only available for those types of modules.

**Comment by guybedford** [comment]
Ah, see you've got that :)

**Comment by Serboy** [comment]
Is there anyone here who encounter a problem like this?

Thanks,

@Component({
    moduleId: module.id, // <-- says moduleId should be a string
    selector: 'app',
    templateUrl: 'app.component.html'
})
