### ISSUE TITLE
Q: map config override

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1187]
I have the following scenario: modules `B` and `C` depend on module `A`:
```
B --+
    |--> A
C --+
```
and I would like to override this dependency to module `Alpha`:
```
B --+
    |--> Alpha
C --+
```
But `Alpha` needs to extend the original `A`:
```
B --+
    |--> Alpha --> A
C --+
```

I'm using the following pseudo-config:
```
System.config({
	packages: {
		"app": {
			map: {
				"./A": "app/Alpha"
			}
		}
	}
});
```

This breaks down on this dependency: `Alpha --> A`, because it effectively becomes a cyclic dependency: `Alpha --> Alpha`. Is there a way to override it and break out?

Currently I'm using a custom `normalize` hook that does something like this:
```js
// Alpha.js

import A from '~/A';
...
```
The hook then replaces `'~/'` with the original path.

Is there a better way to do this?

**Comment by guybedford** [comment]
Is `A` a file or a folder?

**Comment by guybedford** [comment]
```javascript
```

**Comment by guybedford** [comment]
An interesting workaround might be to use the extension in Alpha.js:

```javascript
import A from "./A.js";
```

since the mapping applies to the version without the extension.

**Comment by asapach** [comment]
Sorry, I wanted to simplify the example and might've overdone it. `A` is a script, and I'm actually using `defaultExtension: false`, so all the modules are referenced with extensions.

**Comment by guybedford** [comment]
Yeah there's no way to do it then unfortunately, you'd need to have the original at another location outside of the package with the custom map.

**Comment by asapach** [comment]
@guybedford, could you please reopen this as a missing feature?

This can be done in RequireJS: map `foo` to `bar`, but maintain the the `bar→foo` dependency:
```js
require.config({
  map: {
    '*': {
      foo: 'bar'
    },
    'bar': {
      foo: 'foo'
    }
  }
})
```
Repro: http://plnkr.co/edit/eSplVML1GQX3CMrJv1Sz?p=preview

However if you try to implement a similar setup in SystemJS:
```js
System.config({
  map: {
    'foo.js': 'bar.js',
    'bar.js': {
      'foo.js': 'foo.js'
    }
  }
})
```
`normalize` function goes into an infinite loop and locks up the browser: http://plnkr.co/edit/2LMXh84ld5wrl7fnclUW?p=info (enable Live Preview to see infinite loop in action).

Should I create a separate issue for the infinite loop?

**Comment by guybedford** [comment]
SystemJS takes a different approach to normalization than RequireJS by allowing package maps to be recursive.

If you really mean the file `foo.js` use `'foo.js': './foo.js'` in the package map.

**Comment by asapach** [comment]
OK, I've changed the example slightly to better account for the map config: http://plnkr.co/edit/gbIJc7wMT3h6Eytm37We?p=preview
Is this what you mean?
```js
System.config({
  packages: {
    app: {
      map: {
        './foo.js': './bar.js',
        './bar.js': {
          'app/foo.js': './foo.js'
        }
      }
    }
  }
});
```
This has no effect: `foo.js` is not loaded.

**Comment by guybedford** [comment]
```javascript
System.config({
  packages: {
    app: {
      map: {
        'foo.js': 'bar.js',
        'bar.js': {
          'app/foo.js': './foo.js'
        }
      }
    }
  }
});
```

map only applies to plain names - relative syntax skips the map system.

**Comment by asapach** [comment]
This doesn't work since `foo.js` is loaded, but `bar.js` is not: http://plnkr.co/edit/2zIFR6a4NyOuAlZExUsu?p=preview
Expected result is the `bar → foo` chain.

Are you sure about the relative syntax? Example taken from here: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages

**Comment by guybedford** [comment]
See http://plnkr.co/edit/q92ahjvSFcr5hZdUGmG7?p=preview.

**Comment by asapach** [comment]
OK, what about a longer chain, e.g. `baz → bar → foo`? All I get is `baz → foo`:
http://plnkr.co/edit/igCWNqWHBCIEEngs2a5z?p=preview

**Comment by guybedford** [comment]
I would suggest using folders as packages ('appbar/bar.js', 'appbaz/baz.js' where appbar and appbaz are each package configs) for the more complex case. Files as packages breaks down - I've posted https://github.com/systemjs/systemjs/issues/1366.
