### ISSUE TITLE
What's difference between systemjs & es6-module-loader

### ISSUE THREAD

**Issue by sarbbottam** [systemjs/systemjs#1196]
While searching for [dynamic import ES2015](https://www.google.com/?gws_rd=ssl#q=dynamic+import+ES2015), I came across [https://github.com/systemjs/systemjs/](https://github.com/systemjs/systemjs/) and [es6-module-loader](https://github.com/ModuleLoader/es6-module-loader)

Both seems to be serving similar purpose. Wondering what is the difference between them?

[Cross posted issue](https://github.com/ModuleLoader/es6-module-loader/issues/482).

**Comment by probins** [comment]
module-loader is a polyfill for what will eventually be implemented in browsers, no longer needed once that is implemented. SystemJS is a series of small add-ons to the loader, for example, to load legacy module types such as AMD.

**Comment by sarbbottam** [comment]
Thanks!
