### ISSUE TITLE
wildcard path eating package configuration?

### ISSUE THREAD

**Issue by rweng** [systemjs/systemjs#1198]
Hi there,

can you help me w/ http://stackoverflow.com/questions/36360753/systemjs-mapping-everything-else-to-node-modules or tell me if this is a bug. I tried various suggestions I found online to making this work, the most promising one I described in the stackoverflow post. However, it seems adding

        '*': './node_modules/*'

to my paths prevents the package configuration to take effect.

Thanks in advance,
Robin

**Comment by guybedford** [comment]
Sure no problem, I've answered there. In general is is best to post questions to the chat room or Google group, as issue queues are for code-specific discussions.
