### ISSUE TITLE
Very slow in Edge

### ISSUE THREAD

**Issue by glen-84** [systemjs/systemjs#1201]
Edge 25 takes about 10x longer to load the Aurelia skeleton application (ES2015, with and without bundling).

I also tried the latest version of SystemJS (v0.19.25).

<table>
  <tr>
    <th><br></th>
    <th>ES2016</th>
    <th>ES2016 (bundled)<br></th>
    <th>Webpack</th>
  </tr>
  <tr>
    <td>Chrome</td>
    <td>2-3s</td>
    <td>~2s</td>
    <td>~2s</td>
  </tr>
  <tr>
    <td>Firefox<br></td>
    <td>2-3s</td>
    <td>~2s</td>
    <td>~2s</td>
  </tr>
  <tr>
    <td>Edge<br></td>
    <td>24-25s<br></td>
    <td>~19s</td>
    <td>~2s</td>
  </tr>
</table>

This is a serious performance issue. I would really prefer to stay with SystemJS/JSPM, but if this isn't fixed soon we may have to move to Webpack :disappointed:.

**Comment by StrahilKazlachev** [comment]
I don't think this is SystemJS specific, check this:
* aurelia/framework#318
* https://www.danyow.net/edge-promise-perf/
* http://aurelia.io/docs.html#/aurelia/framework/1.0.0-beta.1.1.4/doc/article/app-configuration-and-startup - Promises in Edge(notice)

**Comment by guybedford** [comment]
It would be worth trying loading bluebird into the page before SystemJS to see how that affects the performance here.

**Comment by glen-84** [comment]
That does appear to fix the issue. Thanks.

Hopefully Microsoft will release a fix for this soon.

Do you want to close this issue or leave it open with a `browser-bug` label or similar?

**Comment by samshiles** [comment]
es6-promise also fixes this issue.

https://github.com/stefanpenner/es6-promise

**Comment by guybedford** [comment]
Thanks for the clarifications here. I've updated the polyfills section of the README to reflect this.
