### ISSUE TITLE
TypeScript transpiler does not support await

### ISSUE THREAD

**Issue by christyharagan** [systemjs/systemjs#1202]
Hey,

I'm using SystemJS, version: 0.19.25.

I have the following config code:

```js
SystemJS.config({
  transpiler: "typescript",
  typescriptOptions: {
    "target": "ES6",
    "module": "system"       
  }
})
```

(I have also tried ES5 and ES3, and tried omitting module too).

I then load some TypeScript code that contains the new async functions with the await command:

```ts
async function f() {
  await somePromise
}
```

And silently, nothing happens. No errors are reported. No code is run (beyond the actual module loading and transpilation itself since syntax errors are correctly reported). If I try commenting out all ```await``` commands, everything runs fine.

Needless to say, the code will compile and run fine if using ```tsc```. I also tried the plugin-typescript transpiler (that jspm defaults to), but the same problem occurs.

I would *guess* the issue is that the transpiler is defaulting to ES3 (and ignoring my target directive) and the transpiler is silently dying since ```await``` isn't yet supported in the ES3 target. But that's just a guess...

**Comment by christyharagan** [comment]
The other option *might* be that TypeScript generates a helper function that implements the async/await functionality and puts that at the start of the file. Perhaps this is interfering with SystemJS functionality.. But again, just a guess

**Comment by mhegazy** [comment]
The probelm is you are passing in strings for compiler options, where as this is expected to be a CopilerOptions object (see https://github.com/Microsoft/TypeScript/blob/master/lib/typescript.d.ts#L1445). 

The correct value should be:

```ts
SystemJS.config({
  transpiler: "typescript",
  typescriptOptions: {
    "target": 2 /* ts.ScriptTarget.ES6 */,
    "module": 4 /* ts.ModuleKind.System */       
  }
})
```

I would say this is a poor API design on our side, the API should accept the string values instead of the numeric values for enums. i have loged https://github.com/Microsoft/TypeScript/issues/7980 to track updating that.

**Comment by guybedford** [comment]
Thank you @mhegazy for the response here.

Note that we encourage using the plugin at https://github.com/frankwallis/plugin-typescript in SystemJS as it provides a much more comprehensive support layer on top of TypeScript compilation.

This internal transpilation layer will be deprecated in the next major, so it's advisable to use the plugin approach.

**Comment by christyharagan** [comment]
Thanks guys. All resolved! Closing.

**Comment by wardbell** [comment]
Can't get it to work in plunker ... neither enumeration nor the plugin. Anyone have a plunker link to something that works?
