### ISSUE TITLE
Preparing for 'script type=module' implementation

### ISSUE THREAD

**Issue by probins** [systemjs/systemjs#1205]
I have always assumed that the ES6 module parser and loader would be implemented in browsers at the same time (not surprising, as they were originally in the same spec), but it's now clear that this isn't going to happen. AIUI, the current status is that all the main browsers have implemented the parser in their JS engines, and at least Chrome and FF are working on implementing `<script type="module">`. This will enable the fetching and parsing of ES6 modules, so will be a great step forward, but (at least AIUI) it will be without the loader that we've been anticipating up till now. So, no `System` object, and no support for the way SystemJS currently works, such as using `System.import` or `System.config`, no plugins or depCache, and no maps, with import only from absolute or relative urls hard-coded into modules.

One possible way to implement dynamic import would be to use module script injection. If you don't mind the hard-coded urls, that might be a way to make use of module scripts. Another option would be to ignore module scripts and continue with the current polyfill. However, that would mean you can't take advantage of the native parsing of ES6 modules.

It might be better to wait and see what is actually implemented (see if all browsers implement the same thing :-)). I expect any initial release will be behind a flag, so it will be a while before it's ready for production. If I thought that the loader spec would be finalised soon, that would be the best option. But this is not progressing (hasn't been updated for months), so I thought I'd raise this issue so we can think about how best to handle this transition, and whether there's some way SystemJS can be adapted to module scripts.

**Comment by guybedford** [comment]
There is no interception of the pipeline at all with `<script type="module">`. The loader work represents those pipeline hooks, and SystemJS will continue to track these hooks as that is the foundational layer of its implementation.

Happy to discuss this further any time.

**Comment by probins** [comment]
ok, I suppose that's the answer I was expecting :-( I'll have to think some more about whether I can find a way to implement parts of SystemJS without the loader pipeline.

**Comment by probins** [comment]
just in case anyone's interested, I have now changed my code so it's ready for module scripts:
* change module specifiers from names/paths to absolute/relative urls, meaning that config.paths and baseURL are no longer needed
* use ES2015 import/export with dynamically created module script tag for import()
* transpile to System.register, and use that along with system-register-loader when import/export not supported (as is currently the case in production use)
* change UMD/other wrappers on 3rd-party packages used to ES2015/System.register
* I was previously using the JSON and text (for HTML) plugins, which use CJS so aren't compatible with ES2015/System.register loaders:
  * JSON was only for one file, which changed to a fetch.then (I may well revisit this at some point)
  * replace text plugin with a server-side script which does the same thing with ES2015/System.register output which can be directly imported (eventually I would like to replace this with whatever replaces HTML Imports)
* replace depCache with a similar function which imports dependencies every time import() is used

which all means I'm no longer using SystemJS, so this probably shouldn't be posted here :-) system-register-loader has the additional advantage of being 20% of the size of SystemJS and so faster to load, and probably faster to run too.

**Comment by guybedford** [comment]
Thanks for the summary. For anyone else interested in these directions, the System register loader described is available at https://github.com/ModuleLoader/system-register-loader.
