### ISSUE TITLE
Inconsistent interop between ESM and commonjs would cause a systematic breakdown

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1206]
Sorry for the title, but really want to get you attention on this subject because we would really need a solution to this soon. If not, it is very hard to unwind as people begins to distribute code in ES6 syntax already. (of course, unless I'm wrong. :smile:)

I have detailed the reasoning here https://github.com/Microsoft/TypeScript/issues/7398

But it does not only affect TypeScript or `.d.ts`, it would affect any package that distributes in ESM.
Can you validate if it would be a problem outside of TypeScript?

Thanks,
Unional

**Comment by unional** [comment]
IMO this can only be solved if a concrete specification is created for ESM <-> commonjs and all parties (transpiler: TypeScript, Babel, Traucer, Rollup, etc, and Node, browsers) all conform to it.

**Comment by guybedford** [comment]
I'm sorry but I really don't follow this. The interop is well-defined at this point, and we have integrated solutions into the tooling.

**Comment by unional** [comment]
Sorry, somehow I missed the notification on your comment.

The issue is not the implementation of the interop within `SystemJS`. It is the inconsistency between how the interop works in different system.

If the files are compiled down to ES5, it might be fine. But when the files are distributed in raw ES6 (in TypeScript for the revelant linked issue), the different expectation of how the interop works will cause problems.

E.g. one package expect the interop work as in `SystemJS` and another one in `Babel`. Then when the consuming application using both packages, the code will not work because the interop fails one way or the other.
