### ISSUE TITLE
Change baseURL afterwards

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#1208]
I've set the `baseURL` to `./` in my `config.js`. In my unit tests I have to change the `baseURL` so SystemJS can find its `jspm_packages` directory. Is it possible to change it afterwards?

`baseURL` should be changed to `../src`. When I do this in my `config.js` everything works as expected. But I can't change it directly in my `config.js` because it would break my production code. I tried a lot of things in my `index.html` of my unit tests but I don't get it running. For example I tried a

`System.baseURL = '../src';`

or a

```js
System.config({
  baseURL: "../src",
});
```

after my `<script src="../src/config.js"></script>` but then I get a console error that setting the `baseURL` is only possible once.

Also I tried a

`System.baseURL = System.baseURL.replace('test', 'src');`

But then SystemJS isn't looking for its `jspm_packages` (e.g. `http://localhost:7357/src/util.js` instead of `http://localhost:7357/src/jspm_packages/util.js`)

**Comment by guybedford** [comment]
The baseURL shouldn't be changed as it affects all normalization. It's advisable in testing workflows to use a custom loader instance for this sort of thing (https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemconstructor).
