### ISSUE TITLE
System.config() failing in IE8

### ISSUE THREAD

**Issue by heaper** [systemjs/systemjs#1210]
It looks like the guts of the **System.config** method is calling the native **hasOwnProperty** method, which is undefined on hosts objects in IE8 and throwing the following error:

``
'hasOwnProperty' is undefined
``

I think you're using Object.prototype.hasOwnProperty elsewhere to get around this limitation.

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/systemjs/systemjs/commit/fee71c52dfd15217c032f5ff2ed661ec797619b3 for the next release.

**Comment by guybedford** [comment]
Released in 0.19.28.
