### ISSUE TITLE
Add support for transpiling via Bublé

### ISSUE THREAD

**Issue by swernerx** [systemjs/systemjs#1213]
There is a new high-performant ES6 -> ES5 transpiler called Bublé. It would be amazing if we could use them as an alternative to Babel/TypeScript.

"Bublé limits itself to ES2015 that can be transpiled to compact, performant ES5"
https://gitlab.com/Rich-Harris/buble

See also this JSPM issue: https://github.com/jspm/jspm-cli/issues/1721 (I was not sure where this feature request belongs to)

**Comment by guybedford** [comment]
It would be a potential SystemJS plugin that could be made. Unfortunately Buble doesn't support compiling module syntax at all, which is the primary purpose of transpilers in SystemJS (otherwise it can just be thought of as a standard loader plugin).

**Comment by jxe** [comment]
Perhaps instead there should be a minimal transpiler that ONLY does the import/export transforms. Modern Chrome needs little else, and as you said other envs could use a loader plugin.
