### ISSUE TITLE
Debug + Sourcemaps not working in Node with TypeScript

### ISSUE THREAD

**Issue by christyharagan** [systemjs/systemjs#1216]
Hi all,

I am using SystemJS (I'm running v0.19.26) to load and transpile TypeScript code to run in Node. All well and good. Now I wish to debug the code with break-points etc. As I step into TypeScript code, it only shows the transpiled version - ignoring the source-mapping - and thus not showing me the original TypeScript.

I have tried this with the built-in typescript transpiler, the plugin-typescript loader, etc. All resources on the internet talk about this working in the browser, but no one seems to be doing this in NodeJS land.

I have tried this using a number of different debuggers (node-inspector, Visual Studio Code, WebStorm), so I'm confident it's not an issue there.

To illustrate my set-up, I have my main file I launch from:

```js
var System = require('systemjs')
global.ts = require('typescript')

System.transpiler = 'typescript'
System.config({
  typescriptOptions: {
    sourceMap: true
  }
}) // Setting this seems to be optional as source-maps seem to be generated by default...

System.import('./src/test.ts').then(function(m) {
  m.default()
})
```

Or to see the plugin-typescript version (which I used JSPM to set-up):

```js
var System = require('systemjs')

SystemJS.config({
  transpiler: "plugin-typescript",
  paths: {
    "github:*": "./jspm_packages/github/*",
    "npm:*": "./jspm_packages/npm/*"
  }
});

SystemJS.config({
  packageConfigPaths: [
    "github:*/*.json",
    "npm:@*/*.json",
    "npm:*.json"
  ],
  map: {
    "os": "github:jspm/nodelibs-os@0.2.0-alpha",
    "plugin-typescript": "github:frankwallis/plugin-typescript@4.0.5"
  },
  packages: {
    "github:frankwallis/plugin-typescript@4.0.5": {
      "map": {
        "typescript": "npm:typescript@1.8.10"
      }
    },
    "github:jspm/nodelibs-os@0.2.0-alpha": {
      "map": {
        "os-browserify": "npm:os-browserify@0.2.1"
      }
    }
  }
});

System.import('./src/test.ts').then(function(m) {
  m.default()
})
```

With my ```test.ts``` looking like:

```ts
export default function() {
  console.log('HI')
}
```

If I set a break-point in the default function in ```test.ts``` it never breaks, so if instead I set it on the ```import``` callback and step into ```m.default()``` it shows the transpiled code, and not the source TypeScript. 

I've checked the various transpilers, and both do generate source-map information, but it doesn't seem to hook-up the actual typescript source.

Please help! I've been tearing my hair out.

**Comment by christyharagan** [comment]
It's probably needless to say, but this is problematic, because it's not possible to set break-points ahead of time. This is because the only way to "access" the code is to step into it at runtime, which is really not a suitable solution.

Of course the work-around is the compile the code first, and just use systemjs as a module loader, but this rather seems to defeat the point of transpilation support.

**Comment by mhegazy** [comment]
How about if you set `"inlineSourceMaps": true, "inlineSources":true` instead of `"sourceMap": true`

**Comment by christyharagan** [comment]
Nope, that doesn't seem to make any difference :(

**Comment by christyharagan** [comment]
I'd be interested to see if anyone else has managed to get it working... If they have, then I'd love to see their configuration to understand what I'm invariably doing wrong.

On the other hand, I wonder if this is working at all...?

**Comment by mhegazy** [comment]
is there a sample i can look at, my local repro seems to be working fine.

**Comment by christyharagan** [comment]
@mhegazy Check out this gist here:

https://gist.github.com/christyharagan/063c5f0e0c5498cc1116b1fdda5a8067

I should be able to insert a break-point on line 2 of ```test.ts``` and the debugger should stop there. However, it does not. Moreover, if I instead put a break-point on line 12 of ```index.js``` and step into ```m.default()``` I do not see the original ```test.ts``` but the SystemJS transpiled code (including all the various wrapper code). 

Obviously, this is silly example since ```test.ts``` is also valid JavaScript, but hopefully you get the point

**Comment by unional** [comment]
Could `sourceMaps: 'inline'` be the solution?
https://github.com/systemjs/builder/issues/547

**Comment by christyharagan** [comment]
@unional: Yeah, I was looking at that and that seems a builder option. For sure, when I come to creating bundles, that will be a useful option.

But my workflow is for live development at the moment: I'm using SystemJS to pull my code together when I start my app and transpile on the fly, whilst still allowing me to debug it as if I had compiled the code as a pre-step using ```tsc```.

I'm getting the feeling this isn't a supported path yet. @guybedford: Can you confirm if I'm right here. If so, what effort would be involved in getting it working (if it's not too crazy involved, I'd be happy to take a look myself).

**Comment by guybedford** [comment]
@christyharagan interesting, thanks for posting this. Firstly I would suggest using the plugin-typescript SystemJS plugin over the transpiler option. But testing this with your case through jspm it does fail as you say. If I then switch the transpiler to Babel, the breakpoints work fine again.

It would definitely be worth investigating this further. There may be some minor offset issues in the source map that are being somehow introduced here.

**Comment by frankwallis** [comment]
If this is happening in VS code then it is probably related to https://github.com/Microsoft/TypeScript/issues/8347

**Comment by christyharagan** [comment]
Ok, I've had some more time to look at this, but I think I must be doing fundamentally wrong...

I tried a more direct approach: I compiled my TypeScript code separately via ```tsc```:

Original TypeScript:

```ts
export default function() {
  console.log('a')
}
```

Compiled JavaScript:

```js
System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    function default_1() {
        console.log('a');
    }
    exports_1("default", default_1);
    return {
        setters:[],
        execute: function() {
        }
    }
});
//# sourceMappingURL=a.js.map
```

Source map file:

```json
{"version":3,"file":"a.js","sourceRoot":"","sources":["../src/a.ts"],"names":[],"mappings":";;;IAAA;QACE,OAAO,CAAC,GAAG,CAAC,GAAG,CAAC,CAAA;IAClB,CAAC;IAFD,+BAEC,CAAA"}
```

And my "bootstrap" javascript file I use to kick off the program looks like this:

```js
var System = require('systemjs')

System.config({
  meta: {
    './dist/a.js': {
      format: 'register'
    }
  }
})

System.import('./dist/a.js').then(function(m) {
  m.default()
})
```

But when I run this, I still run into the same issue. Again, note: **I am running this in Node.js**:

When I step into the "a.js" file, I see:

```js
(function(System, SystemJS) {System.register([], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    function default_1() {
        console.log('a');
    }
    exports_1("default", default_1);
    return {
        setters:[],
        execute: function() {
        }
    }
});
//# sourceMappingURL=a.js.map
})(System, System);
//# sourceURL=file:///code/test-systemjs/dist/a.js
```

Which seems to be pointing to the compiled javascript file, not the original typescript file.

Also @guybedford : I can't get the babel transpilation working. I noticed babel has moved to babel-core (which, by the way, systemjs documentation is out of date), but try as I might I can't get it to work. Is there something I should be aware of,  or is the latest version of babel not supported?

**Comment by christyharagan** [comment]
@guybedford: I have tried Babel, and I can't get source maps to work with that either :( I do wonder if I'm missing something fundamental here. Again, noting I'm running on Node, but it doesn't seem to matter which debugger I use (I've tried a few, node-debug, vs, atom) and they all fail.

For completeness, my bootstrap code for Babel is:

```js
var System = require('systemjs')

System.config({
  map: {
    'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
    'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-browser.js'
  },
  transpiler: 'plugin-babel'
})

System.import('./src/a.js').then(function (m) {
  m.default()
})
```

Again, neither setting break-points in ```src/a.js``` work, or indeed, when I step into the module, does it show the original file, instead showing the systemjs wrapped version.

**Comment by guybedford** [comment]
@christyharagan I think you're actually the first to carefully test and report this... I just ran through your example step by step and I can confirm that the source maps are not working in node inspector for me. 

I just spent some time on it and managed to get it to work correctly in Node with this change - https://github.com/systemjs/systemjs/commit/36f995ee738e993df22ff8d341db6507dc0e1d29! So thank you for pressing here :)

Note though that dynamic transpiling won't be able to give the original source though because of the fact that NodeJS doesn't seem to be able to support a dynamic sourceMappingURL anyway that I know of. Although there may well be approaches here we can explore.

**Comment by christyharagan** [comment]
@guybedford : Thanks Guy. I'll check this out soon when I get a spare cycle.

**Comment by christyharagan** [comment]
Yup that works. Thanks! And it also - indirectly - provides a solution to the problem of setting breakpoints in the source code from say an editor:

Whilst this isn't possible using dynamic transpilation, my work-around is to use the systemjs builder. This does require an external build, but does have the advantage of allowing for things like incremental builds (which reduces start-up time - great for development work). Previously, however, even this wasn't working (I had to manually require the transpiled files, which isn't exactly dynamic), but with your commit, the source maps now do get picked up correctly.

I can't think of any other approach right now. I'll check to see if this is something the Node (or would it even be a V8 thing? or perhaps even something supportable at the editor level... I'll ask around) guys are looking to support.

However, unless any other bright spark knows of a better solution in the interim, I feel this can probably be closed. Unless I hear otherwise, I'll close this in a few days...

**Comment by guybedford** [comment]
Thanks for the udpate @christyharagan please do report further if you notice anything suspicious :)

**Comment by guybedford** [comment]
There should be a way to do source map injection in Node, but yes that is probably something to raise there as I don't expect it is currently possible.

**Comment by jonaskello** [comment]
I'm doing something similar. Although I have no bootstrap code, I just use `jspm run server.ts` to run an express server. I set sourceMaps to true in typescriptOptions. However all errors refers to line numbers in the transpiled code which makes troubleshooting really hard. @christyharagan did you manage to get dynamic transpilation with source maps to work? Is there some issue over at node that I could vote for to get this working?

**Comment by christyharagan** [comment]
Hey @jonaskello,

I didn't get it working, sadly, and went on to another approach. However, I believe there is work make this work. For example, inside Visual Studio Code, this issue tracks dynamic sourcemaps:

https://github.com/Microsoft/vscode-chrome-debug-core/issues/36

Essentially, I think the new v8-inspector protocol ought to support this, but it seems it isn't straight-forward.

**Comment by jonaskello** [comment]
@christyharagan Thanks for the update! I will subscribe to that issue. I guess [this issue](https://github.com/TypeStrong/ts-node/issues/46) is also related. From what I understand you can hook require in node to make compile happen but you cannot inject source-maps on the fly which I guess is the core problem. Still not sure if it is a nodejs problem or v8 problem though.
