### ISSUE TITLE
Globaldeps behavior for local dev

### ISSUE THREAD

**Issue by mikeyoon** [systemjs/systemjs#1217]
We have a hybrid SystemJS + Rails/Sprockets environment. The rails side loads in a bunch of JS like angular/jquery/etc for its own app, and then afterwards the SystemJS app loads on top of it. For prod builds, I can easily exclude shared dependencies with the bundle arithmetic and the globalDeps option, but I'm wondering if there's an option to do that when doing local development.

**Comment by guybedford** [comment]
Adding custom map configuration is the way to re-route dependencies during separate file loading in SystemJS, is that what you're after here?

**Comment by mikeyoon** [comment]
Possibly, would that look something like this then?

```
map: {
    "angular": "window.angular"
}
```

**Comment by guybedford** [comment]
Try something like - 

```javascript
map: {
  "angular": "angular-global.js"
}
```

angular-global.js
```javascript
export default angular;
```

**Comment by mikeyoon** [comment]
That worked great, thanks!
