### ISSUE TITLE
a failed import leave something in the state of System, which causes subsequent imports of the same dependency to fail

### ISSUE THREAD

**Issue by capaj** [systemjs/systemjs#1218]
This has been brought to my attention by this bug:
https://github.com/capaj/systemjs-hot-reloader/issues/75

I fixed it by a small hack here:
https://github.com/capaj/systemjs-hot-reloader/commit/0a9f98c7c60d3a018a6c263b49affa2e259d249d#diff-e06233ac325761e3eb8d1feadaf9c2d6R239

Just FIY-that delete return false. Which is a value indicating that the module has not been deleted I presume? Well it might not have been deleted, but it definitely deleted something, because it fixed the future reimport.
This is a usecase which probably doesn't come up until you do hot-reloading.

So I think that it should work even without me deleting the module manually. Agree @guybedford ?

**Comment by guybedford** [comment]
I believe this was actually specified in the original loader that errors should persist, but the WhatWG loader changes this behaviour, making errors no longer persist.

We could investigate removing that check certainly.

**Comment by guybedford** [comment]
This should be fixed up by the new behaviours in Implemented in [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1).
