### ISSUE TITLE
Importing multiple files using promises or can we use meta here ?

### ISSUE THREAD

**Issue by binarysqueeze** [systemjs/systemjs#1219]
Hi,

I wanted to have a standard JS file loaded first before my rest of my files so I used the promise system. It seems to work :-) I wondered if I am doing it correct ?

```
    System.import('./jspm_packages/github/photonstorm/phaser@2.4.6').then(function() {
        System.import('client/app');
    });
```
(there is also a separate typings file (typescript) which I have included in the files tags of the tsconfig which helps my IDE along

`    "./jspm_packages/github/photonstorm/phaser@2.4.6/typescript/phaser.comments.d.ts"`
)

I was wondering if the above could be done via the meta tag ? the meta tag seems to support typings and passing path or a boolean. I haven't managed to get this working.

Am I able to use the meta tag for above and which approach is better?

Thanks in advance

**Comment by guybedford** [comment]
You can use `deps` metadata to ensure that `client/app` depends on `github:photonstrom/phaser@2.4.6`.

But if `client/app` is your own code, it is best just to use `import 'photonstrom'` in that file itself.

If loading typings, see the typescript plugin project for help loading this.
