### ISSUE TITLE
Error after updating to latest version

### ISSUE THREAD

**Issue by BenevidesLecontes** [systemjs/systemjs#1221]
Hello! In previous version of System.js (0.16.0), i was using this code to load modules:
System.config({
    baseURL: '/',
    paths: {'*': '*.js'}
});

System['import'] = function (name:string, options?:any):any {
    return System.originalSystem.import.call(this,name, options).then(function (module) {
        return module;
    });
};

After update, i receive the error Uncaught TypeError: Cannot read property 'import' of undefined on this line return System.originalSystem.import.call(this,name, options).then(function (module) . Any help would be appreciated, thanks.

**Comment by guybedford** [comment]
There is no `originalSystem` set so you probably want to store originalImport yourself here via `var originalImport = System['import']` before re-assigning?

Note that paths setting extensions is no longer supported as well.

**Comment by BenevidesLecontes** [comment]
@guybedford thanks for the answer, solved my error.
