### ISSUE TITLE
can systemjs load a javascript file by force?

### ISSUE THREAD

**Issue by ciel** [systemjs/systemjs#1224]
I have a situation where I need to load a javascript file into my page; the whole site is managed (beautifully) by systemjs, but this new file doesn't ... seem to work with it. I get peculiar errors such as `Multiple defines for anonymous module`

The javascript file in question isn't really bad code; but it's obviously not written with module loading in mind. There's nothing I can really do about that, either.

It requires jquery to be loaded, as well.

The producer of the library, their "suggested" method of loading it is to use the old fashioned method of using `<script>` tags. That's fine and good, but the dependence on jQuery makes the situation complicated - as it's a pretty integral part of my systemjs configuration.

So I obviously can't just slap a script tag on the site and call it done. But systemjs won't load it, either.

Is there a way I can tell systemjs that I want to load a script file; regardless of how it fits into the whole module scheme? can I force it to just raw-load a given script file and tell it "yes, I know what I am doing. I don't care that this doesn't smell right"?

**Comment by asapach** [comment]
Try this meta: `{ format: 'global', scriptLoad: true }`

**Comment by ciel** [comment]
Should I still include it in the `map` section as well?

**Comment by ciel** [comment]
Hrnm, with that meta, I get the error...

`AMD define called while executing global module`

**Comment by asapach** [comment]
Yes, and you should also probably add `deps` on jquery.

**Comment by ciel** [comment]
Sigh. Yeah, I've got all that. It still won't load it seems. It's like they half-implemented module loading and then did it wrong.

**Comment by ciel** [comment]
Here's my `config` setup; the library giving me trouble is `mdb`.

````
System.config({
    defaultJSExtensions: true,
    map: {
        'typescript': 'assets/js/typescript.js',
        'jquery': 'assets/js/jquery.js',
        'jquery.json': 'assets/js/jquery.json.js',
        'marked': 'assets/js/marked.js',
        'marked.editor': 'assets/js/marked.editor.js',
        'angular': 'assets/js/angular.js',
        'angular.ng': 'assets/js/angular.ng.js',
        'bootstrap': 'assets/js/bootstrap.js',
        'mdb':'assets/js/libs/mdb.min.js',
        'app': 'app'
    },
    meta: {
        'assets/js/jquery.js': {
            format: 'amd',
            exports: '$',
            deps: [ 'shims.es', 'shims.es5', 'shims.es6' ]
        },
        'assets/js/jquery.json.js': {
            deps: ['assets/js/jquery.js']
        },
        'assets/js/angular.js': {
            exports: 'angular',
            deps: ['assets/js/jquery.js', 'assets/js/marked.js']
        },
        'assets/js/kendo/kendo.*.js': {
            deps: ['assets/js/jquery.js']
        },
        'assets/js/angular.ng.js': {
            deps: ['assets/js/angular.js', 'assets/js/bootstrap.js', 'assets/js/marked.js']
        },
        'assets/js/bootstrap.js': {
            deps: ['assets/js/jquery.js']
        },
        'assets/js/marked.editor.js':{
            deps:[ 'assets/js/marked.js']
        },
        'assets/js/libs/mdb.min.js':{
            format: 'global', scriptLoad: true,
            deps: ['assets/js/jquery.js']
        },
        'app/*': {
            deps: ['assets/js/angular.ng.js', 'assets/js/jquery.json.js', 'assets/js/marked.editor.js']
        }
    },
    paths: {
        'kendo.*': 'assets/js/kendo/kendo.*.js',
        'shims.*': 'assets/js/shims/*-shim.js'
    }
});

Promise.all([
    System.import('jquery'),
    System.import('angular'),
    System.import('angular.ng'),
    System.import('bootstrap'),
    System.import('mdb')
]).then(function() {
    $(document).on('angular', function() {
        angular.bootstrap(document, ['Lore']); $('body').removeClass('cloak');
    });
});
````

**Comment by asapach** [comment]
I give up :), sorry.

**Comment by ciel** [comment]
Thank you for your help. I think I finally got it working; The trick was to use the `format: global` but not the `loadScript` property.
