### ISSUE TITLE
'use strict' breaks importing

### ISSUE THREAD

**Issue by geri777** [systemjs/systemjs#1225]
This is a duplicate of #75 - please advice/reopen. I still have the same problem in version 0.18.2. Please see https://plnkr.co/edit/bhSTkcZw9XaKszXuIYZQ?p=preview
Many thanks

**Comment by guybedford** [comment]
In strict mode, declaring variables via `var global = ...` is not supported, so this is the correct behaviour.

**Comment by soulcorrosion** [comment]
Hi, I'm using v0.19.26.
I have a dependency from three.js We use the minified version which has a "use strict".
If I use a script tag with the three.min.js, it creates a global variable, as expected, called THREE.

If I do an import using System.js, having the module configured as global, it does not create the global variable. @guybedford what do you mean with "declaring variables via var global = ... is not supported"?

**Comment by guybedford** [comment]
@soulcorrosion firstly it's worth checking if it really was configured correctly to load as a global... if the meta wasn't quite right, it may have gone to default detection and run as AMD, which would then have not defined a global variable. I guess the thing to check first and foremost is if the value of the import is correct from the `System.import('three').then(function(THREE){ })` statement... if it is, that is probably the case.

**Comment by soulcorrosion** [comment]
Hi @guybedford, thanks for your reply. 
This is the way the meta is configured:

`System.config({
                meta: {
                    "libs/three.min.js": {
                        format: "global"
                    }                    
                }
});`

Then there is a file that will imported it, not via a System.import call but via es6 module syntax.

`import "libs/three.min";`

In a previous version of System.js, this was creating the global for me.
