### ISSUE TITLE
Conditional package maps

### ISSUE THREAD

**Issue by filipesilva** [systemjs/systemjs#1226]
Heya,

In the [Conditional Loading](http://jspm.io/0.17-beta-guide/conditional-loading.html) chapter of the jspm 0.17 Beta Guide there is a syntax for conditional package maps:

```
      "map": {
        "./text.js": {
          "~production": "./text-dev.js"
        }
      }
```
> The ~production syntax above means the NOT production condition will use src/text-dev.js instead of text.js. (...) By editing the production boolean property in jspm.browser.js, we can now control which branch of the component text SystemJS will load. 

Is this functionality available in SystemJS outside of JSPM? If so, does SystemJS Builder also support it?

Cheers

**Comment by guybedford** [comment]
Yes this feature is supported in SystemJS but undocumented.

When running SystemJS builder, it is supported via the `conditions` option, which supports forms like: `builder.bundle('main.js', { production: true })` for simple conditions and `builder.bundle('main.js', { 'my-condition|value': true })` for custom conditions.

**Comment by filipesilva** [comment]
Awesome! Is there a way to set this `conditions` option on SystemJS config as well, without using builder?

**Comment by guybedford** [comment]
`System.config({ production: true/false })` is supported for the production condition. the browser and node conditions are set automatically.

**Comment by filipesilva** [comment]
Awesome. Thank you for the help and quick replies!
