### ISSUE TITLE
How to minify bundled dependencies with JSPM?

### ISSUE THREAD

**Issue by playground** [systemjs/systemjs#1227]
I was under the impression that "jspm bundle lib/main build.js" will bundle up all the dependencies I specified in main.js into build.js with fully functional code and minified.  However looks like it's still dynamically loading in dependencies.  

According to Chrome, the page loaded with the following
1) With jspm bundle lib/main build.js
325 requests | 1.6M transferred | Finish 5.70 s | DOMContentLoaded: 982 ms | Load: 1.83 s

2) With "jspm depcache lib/main.js
693 requests | 1.9M transferred | Finish 5.85 s | DOMContentLoaded: 749 ms | Load: 999 ms

3) When including anguler2.min.js in script tag on the page
105 requests | 715 KB transferred | Finish 4.35 s | DOMContentLoaded: 1.01 s | Load: 2.19 s

These are tested on the same server with HTTP2 enabled
My questions are:
1) Is there a way in jspm that it will generate all dependencies code and minified in build.js
2) if I'm more concerned with page load performance especially for mobile, which option should I go with?  I'm still confused about how page performance is being measured.  Seems to get different answers from different people.

**Comment by guybedford** [comment]
When loading a bundle, it is important to first load the configuration files before the bundle into SystemJS, otherwise the bundle names will not match properly with the loads made and you will get "out of bundle" loading happening, which sounds like what the issue may be here.

**Comment by playground** [comment]
This is the order they are being loaded
system.js
config.js
build.js

Do you think because of HTTP2 build.js could be loaded before config.js?

**Comment by guybedford** [comment]
It's worth checking carefully what the requests are that are being made, and seeing:

a) if the module exists at all in the build file as a System.register or System.registerDynamic statement.
b) if it doesn't, then working out why it was not included in the build
c) if it is in the bundle, then working out what the name isn't matching up when requested

**Comment by playground** [comment]
@guybedford I'm using service worker in conjunction with jspm
I just noticed that assets are being loaded twice.  Not sure what is causing this behavior yet.  Have you seen this before?

![image](https://cloud.githubusercontent.com/assets/243495/14729703/463f0996-080e-11e6-83bb-1a12e0c14f1c.png)

![image](https://cloud.githubusercontent.com/assets/243495/14729726/7307d03e-080e-11e6-9868-207fb8ed79b7.png)

**Comment by guybedford** [comment]
I guess the service worker itself is requesting the resource as it is a different execution context? Just let me know if you need further help here at all.

**Comment by playground** [comment]
I'm in a process of upgrading to ng2 rc.1.  I wiil let you know if this issue still exists.  Thanks.
