### ISSUE TITLE
About scriptLoad dependencies

### ISSUE THREAD

**Issue by lizhong8532** [systemjs/systemjs#1229]
I am using SystemJS and Angular2 create a project.

I need in someone components import dependencies, SystemJS config below:

```
   meta: {
        'custom/graph': {
            format: 'global',
            scriptLoad: true,
            deps: [
                'A',
                'B'
            ]
        },

        A: {
            format: 'global',
            scriptLoad: true
        },

        B: {
            format: 'global',
            scriptLoad: true
        }

    },

    map: {
        A: 'assets/a.js',
        B: 'assets/b.js
    },
```

a.js (File size 2.1M)
```
var a = {};
...
```

b.js (File size 1k)
```
a.name = 3333; 
```

But the dependencies is not order successively loaded, When B module loaded and running so export error: Uncaught ReferenceError: a is not defined

I know the reason, Because the b.js is very small, it first loaded and running. And now a.js is in loading status

Tell me how fix this problem. Let it order loaded dependencies. else other way? 
Thanks everyone~~~!!!

**Comment by asapach** [comment]
Maybe you need to add dependency `B -> A`?

```
B: {
        format: 'global',
        scriptLoad: true,
        deps: ['A']
    }
```

**Comment by lizhong8532** [comment]
@asapach I try, But can not fix it, Open chrome network panel can no found a.js in list

**Comment by lizhong8532** [comment]
@asapach chrome console print : angular2-polyfills.js:390 Error: Error: http://localhost:3000/assets/js/b.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.(…)

**Comment by asapach** [comment]
Sounds like you also need to specify `exports`:
```
    A: {
        format: 'global',
        exports: 'a',
        scriptLoad: true
    }
```

**Comment by asapach** [comment]
And you can try experimenting with `scriptLoad` values to see if they have any effect.

**Comment by lizhong8532** [comment]
@asapach If a.js has more values, How exports all values?

a.js
```
var a = {};
var d = {};
```

```
A: {
        format: 'global',
        exports: ['a','d'],
        scriptLoad: true
    }
``` 

Like above code?
