### ISSUE TITLE
Issue with relative loading from a folder module wrongly considered as a file module by SystemJS

### ISSUE THREAD

**Issue by ymeine** [systemjs/systemjs#1233]
Hi community,

## Introduction

I'm using SystemJS as part of a project being a basis for many others. To quickly describe the relevant parts of the environment: 

- I have a custom web server, able to locate _modules_ of code in a flexible way, using content type negotiation, files layout rules, etc. One of the resolution algorithms implemented is the same as for Node.js (`folder` ⇒ `folder/index.js`, etc.)
- as a user, I consider a _module_ of code as a ___folder___: I'm never referring to a module as an explicit _file_
- __I can mix absolute and relative loading__

## Example

Now here is an example of what works in Node.js, and that I would like to be working with SystemJS.

### Working in Node.js

file `main.js` (entry point): 

```javascript
require('a/b');
```

which requires `a/b`, resolving to `a/b/index.js`

file `a/b/index.js`: 

```javascript
require('./c');
```

which requires `./c`, logically considered as `a/b/c`, and perfectly resolving to `a/b/c/index.js` (but it could be `a/b/c.js` if I chose to use a file instead of a folder).

### Failing in SystemJS

file `main.js` (entry point): 

```javascript
require('a/b');
```

which requires `a/b`, resolving to `a/b/index.js` on the server-side but considered as `a/b.js` on the client side.

file `a/b/index.js` (considered `a/b.js`): 

```javascript
require('./c');
```

which requires `./c`, logically considered as `a/b/c` by the user (me), but wrongly resolving to `a/c.js` by SystemJS (my server won't be able to resolve it properly).

This is because SystemJS is not aware that `a/b` had to be considered as a folder and not a file, and therefore there is a wrong nesting level.

## Question

I'm pretty beginner with SystemJS, and I tried to write a plugin to fix this. I implemented the `address` resolution using a `locate` hook, but this didn't help (and led to further issues).

My question is simple: what are the mechanisms to make SystemJS map any input to `require` to a canonical module id I would resolve myself? If not possible what workaround could I put in place to fix my above use case?

**Comment by amenadiel** [comment]
If you knew what modules you're going to require beforehand, the simplest solution would be to add a package config, inside which you would add mappings:

```js
SystemJS.config({
  "paths":{
    ...
  },
  "packages":{
    "ymeine":{
      "main" : "main.js",
      "map": {
         "a/b": "./a/b/index.js",
         "a/b/c": "./a/b/c/index.js"
      }
    }
  }.
  "map":{
    ...
  }
}):
```

The other option would be to use a custom loader, albeit I read somewhere that the locate hook was going to be deprecated (?)

```js
SystemJS.config({
  "paths":{
    ...
  },
  "meta":{
    "ymeine/*":{
      "loader" : "customloader.js"
    }
  }.
  "map":{
    ...
  }
}):
```

where the contents of `customloader.js` would be something like:

```js
var systemLocate = System.locate;
exports.locate = function(load) {
  var System = this;
  return Promise.resolve(systemLocate.call(this, load)).then(function(address) {
    return address + '/index.js';
  });
};
```

I believe the use of a custom loader would need you to turn off the defaultExtensions property, or declare the custom loader using a package config instead of meta. Anyway, it sounds like a brittle solution to me, I guess you would need to add some logic to avoid re-adding index.js to a resolved path.

**Comment by guybedford** [comment]
Thanks @amenadiel for the response here! @ymeine if you have any further questions do let me know.

**Comment by ymeine** [comment]
Hi, sorry for the late reply. First of all thanks @amenadiel for your suggestions.

However, using the mapping feature seems quite hard since I need to compute all the dependencies beforehand, and I think this wouldn't suit the case of loading dynamic resources.

Regarding the suggestion of the hook, I mentioned briefly in the description that I've tried it already, implementing the `locate` hook, but actually SystemJS doesn't use the result to resolve the module, just for fetching it (which is useless for me): therefore a file required with path `a/b` will be considered as `a/b.js` even if it is actually `a/b/index.js`. The problem is that if ever I require it using path `a/b/index` explicitly, SystemJs will think they are two different modules, while in the end they are the same.

This makes me realize now that while trying to simplify my use case, I might have been wrong in my initial description. I'm gonna try to explain the use case again, concisely and pragmatically.

While I said that a module is usually a folder in practice, it's not always the case and I want to support all cases anyway: both for authoring the module __and__ requiring it with a reference (call it _path_ or _id_). What matters is that while using a module reference in `require`, this can end up to __file directly__ or a __file in a folder__, and that subsequent `require`s inside that file will take into consideration the file system structure, not the logical module structure we could infer from the parameter of `require`.

Example: 

```
a/
	b/
		index.js
	c.js
	d.js
```

- `require('a/b')` will use folder `a/b`, resolving to file `a/b/index.js`, from which requiring `a/d.js` will look like `require('../d')`
- `require('a/c')` will use file `a/c.js`, from which requiring `a/d.js` will look like `require('./d')`

If I had taken the _module is folder_ principle for authoring my code, I would still have written `require('../d')` for my second case, which I find  very confusing when you look at the files.

So for me the issue is still open, don't hesitate if you need further clarifications.
