### ISSUE TITLE
need help with systemjs when using gulp-jasmine

### ISSUE THREAD

**Issue by HeavenlyHost** [systemjs/systemjs#1235]
So I may be new to this thing, but I am trying to use gulp to build, lint and test my demo solution. The app is using Angular 2, Gulp, SystemJS, gulp-tslint and gulp-jasmine, however I am unable to get the gulp-jasmine to run without falling over. It complains with the following

 events.js:141
      throw er; // Unhandled 'error' event
      ^
 TypeError: Invalid System.register call. Anonymous System.register calls can on
ly be made by modules loaded by SystemJS.import and not via script tags.
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:2981:17)
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:3655:29)
    at SystemJSNodeLoader.<anonymous> (D:\ng2demo\node_modules\systemjs\dist\sys
tem.src.js:4142:33)
    at SystemJSNodeLoader.reduceRegister_ (D:\ng2demo\node_modules\systemjs\dist
\system.src.js:4142:33)
    at SystemJSNodeLoader.pushRegister_ (D:\ng2demo\node_modules\systemjs\dist\s
ystem.src.js:2699:14)
    at SystemJSNodeLoader.SystemJSLoader.register (D:\ng2demo\node_modules\syste
mjs\dist\system.src.js:2937:10)
    at Object.<anonymous> (D:\ng2demo\app\assets\services\config.service.spec.js
:4:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

The JS file it is attempting to run is a spec written in TypeScript and transpiled to JS with gulp-typescript. So the top line of the file is...

System.register(['angular2/core', 'angular2/http', 'angular2/http/testing', './config.service'], function(exports_1, context_1) {
//Do Stuff
});

It is this line it has a problem with, any ideas ???

**Comment by sebasrodriguez** [comment]
Try adding this to your config. 

 meta: {
    "packageName": {
      "format": "register"
    },

**Comment by HeavenlyHost** [comment]
So I am confused, do I need to include this inside a gulp task as below or am I missing something...?
I just want to run the test in the command window NOT in the browser...

gulp.task('jas-sys-test', () => {
	var System = require('systemjs');

	System.config({
            packages: {
                'app': {defaultExtension: 'js'}
            },		
	    meta: {
		"packageName": {
		    "format": "register",
		},
	    },		
	});

	System.import('./app/assets/widgets/my.component.spec');
	System.import('./app/assets/services/my.service.spec');
	System.import('./app/assets/services/my2.service.spec');
	System.import('./app/assets/services/my3.service.spec');		
	
	gulp.src(['./app/**/*.spec.js'])
		.pipe(jasmine())
})

**Comment by HeavenlyHost** [comment]
So I updated my task and now I have the following, the problem is that when it gets into the spec the first line is the following 

import {Injector, provide} from "angular2/core";

unfortunately this is not referencing the node_modules/angular2 directory but rather the project root !!!

gulp.task('newtest', () => {

	System.config({
		baseURL: "/",
		transpiler: 'typescript',
		defaultJSExtensions: true,
		path: {
			"node_modules*": "node_modules/*"			
		},
		packages: {
			"app": {
				"defaultExtension": "js"
			}
		},      
		maps:{
			"angular2": "/node_modules/angular2",
		},
	});

	Promise.all([
		System.import('app/assets/services/config.service.spec'),
	]).then(function(){		
		gulp.src(['app/assets/services/config.service.spec'])
			.pipe(jasmineclassic())
	}).catch(console.error.bind(console));

});

**Comment by guybedford** [comment]
It may be advisable to follow an existing SystemJS testing workflow here. Combining gulp-jasmine and SystemJS in this way looks a little tricky to me - perhaps pick one approach or the other.
