### ISSUE TITLE
Document e.originalErr from a source maps perspective

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1236]
To get source maps as described in https://github.com/systemjs/systemjs/issues/511#issuecomment-213187283.

**Comment by mavericken** [comment]
I tried the strategy discussed in #511, but it wasn't enough.  I was using ChromeDevTools against a `node --inspect`.  It seems the promise handling was fighting me somehow, as I was able to get around it by breaking out of the promise using a timeout:
```
SystemJS.import("app").catch(function(err){
  if (err.originalErr) {
    setTimeout(()=>{throw err.originalErr},0)
  }
};
```
