### ISSUE TITLE
Can't get even most basic hello world with TypeScript working

### ISSUE THREAD

**Issue by henrify** [systemjs/systemjs#1238]
Giving SystemJS a try, but I can't find even basic hello world example without angular2 (which i don't use), and my best guess masterpiece doesn't work:

Incredible app.ts:

```
export function hello() {
	console.log("world");
}
```

Transpiled to app.js by Visual Studio with TypeScript 1.8.5:

```
System.register("app", [], function(exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    function hello() {
        console.log("world");
    }
    exports_1("hello", hello);
    return {
        setters:[],
        execute: function() {
        }
    }
});
//# sourceMappingURL=app.js.map
```

Which i try to load with:

```
<!DOCTYPE html>
<html><head><title>wtf</title>
	<script src="./node_modules/systemjs/dist/system.js"></script>
	<script>
		System.import('app.js')
			.then(function(module) {
				console.log("ok");
				for (prop in module) {
					console.log("module has prop: " + prop);
				}
			}, function() {
				console.log("not so much ok");
			});

	</script>
</head><body></body></html>
```

The http requests to load system.js and app.js are successful, 'ok' but nothing else is displayed on console, and when inspecting with debugger the 'module' is an empty object. No warnings or errors on console.

I don't know anything about SystemJS and must be missing something obvious? Might be brilliant to include basic hello world example in the docs though.

**Comment by guybedford** [comment]
The issue here is matching up the paths - SystemJS is looking for `app.js`, but the bundle defines `app` without the js extension. The way to fix this is to add this SystemJS configuration before loading the bundle script tag:

```
  System.config({
    defaultJSExtensions: true
  });
```

**Comment by henrify** [comment]
That was it, thanks.

But for new users like me the problem was totally non-obvious. Shouldn't that option be:
1. shown in examples
2. maybe the default behaviour
3. and/or result in runtime warning if it is clear that the user is messing up?

**Comment by guybedford** [comment]
The problem here is that the generated file should be using `app.js`, so it's an incompatibility of approaches between tools. Extensions are not added automatically in SystemJS and this option is being deprecated.

This is then exactly a documentation problem, which I'm personally prioritising as soon as jspm 0.17 documentation is updated. Documentation PRs are always welcome too.

**Comment by henrify** [comment]
If you are deprecating the option, doesn't it mean that you will brake compatibility with tsc generated bundles? Is this something that is being discussed with the TS team?

**Comment by guybedford** [comment]
defaultJSExtensions is being deprecated for the package-based defaultExtension option.

**Comment by henrify** [comment]
So in future I would just need to switch to:
defaultExtension: "js"
or something similar?
