### ISSUE TITLE
Loading SystemJS Dynamically fails IE

### ISSUE THREAD

**Issue by AStoker** [systemjs/systemjs#1239]
I am trying to load up SystemJS dynamically by injecting a script tag in the head of the document referencing SystemJS. This seems to work in all browsers but IE (Edge is fine). In IE, the file is loaded, and the first couple lines are at least executed (tested by just putting some console logs in the code), but `System` never gets defined on the window, and none of the console logs at the end of the file are hit. I am loading up files like so:
```
var fileref=document.createElement('script');         
fileref.async = false;         
fileref.setAttribute("type","text/javascript");         
fileref.setAttribute("src", "/jspm_packages/system.js"); 
fileref.onload = function(){console.log(System);} //IE breaks, System is undefined when executed
document.getElementsByTagName("head")[0].appendChild(fileref);
```

I am really hanging here. We need to load up SystemJS dynamically (and our config file) because we are insulating some code from having to worry about SystemJS (as it may change for us in the future), and instead just load up a script that configures the html page.

Is there a way to dynamically load up SystemJS with pure JavaScript?

**Comment by guybedford** [comment]
Try including the promise polyfill first as in https://github.com/systemjs/systemjs#promise-polyfill.

**Comment by AStoker** [comment]
Closing this, as it turns out that IE doesn't have Promise support, and that is what was needed for SystemJS to finish loading. Solution was to include the promise polyfill.
