### ISSUE TITLE
Can't load Node core modules

### ISSUE THREAD

**Issue by orand** [systemjs/systemjs#124]
I'm probably missing something basic, but I can't seem to load Node core modules such as `fs`, `path`, `http`, etc.  Here's what I'm doing.

```
// index.js
var System = require('systemjs');
System.import('./app')
    .then(function (m) {
        console.log(m);
    }, function (e) {
        console.log(e);
    });
```

```
// app.js
var fs = require('fs');
```

This produces the following output:

```
{ [Error: ENOENT, open '/Users/orand/Projects/SystemJSTest/fs.js']
  errno: 34,
  code: 'ENOENT',
  path: '/Users/orand/Projects/SystemJSTest/fs.js' }
```

How can I tell SystemJS to not treat Node core modules as if they are local files?

**Comment by lukesneeringer** [comment]
> It would be relatively simple to put together, but it's not something within the core goals of SystemJS and I'm not at a point where I can support another project. I'll happily share a gist example of a loader along these lines though if you are interested.

Would this still be possible, even though the OP's issue is solved?

**Comment by calvinmetcalf** [comment]
See https://github.com/calvinmetcalf/es6-translate

**Comment by PinkaminaDianePie** [comment]
seems to be es6-translate is outdated. is there new ways of resolving this issue?

**Comment by guybedford** [comment]
If you're referring to the original question, Node core modules can now be imported with `import {readFile} from '@node/fs'`, but that will only work in Node environments of course.

**Comment by PinkaminaDianePie** [comment]
@guybedford im getting this error ```[Error: Cannot find module '@node/fs']``` when trying load code of my module in new app.

**Comment by guybedford** [comment]
Where are you running the code to get that? Those requires only work in Node, and not the browser.

**Comment by PinkaminaDianePie** [comment]
im running this on node, im testing my package via ```npm link``` and import my package in new project with ```import '@node/package'```. And when i import ```fs``` in project everything is ok, but if i include it in  package it fails. and if i install package not via ```npm link``` but with ```npm install``` - it even dont transpile

**Comment by Flood** [comment]
Did you guys found a solution for this? I have the same problem.

**Comment by PinkaminaDianePie** [comment]
@Flood I moved to webpack on frontend and own polyfill on backend. It was too hard for me to maintain project with SystemJS as loader.

**Comment by Flood** [comment]
@PinkaminaDianePie Hmm ok, thanks, what a pain in the ass :/
