### ISSUE TITLE
babel reference breaks firefox

### ISSUE THREAD

**Issue by npbenjohnson** [systemjs/systemjs#1241]
For whatever reason, firefox gives up if you eval a script with unreachable code with dev tools open. 5.8.38 of babel core contains this:
```
module.exports = function toFastProperties(obj) {
	function f() {}
	f.prototype = obj;
	new f();
	return;
	eval(obj);
```

I logged a bug here https://bugzilla.mozilla.org/show_bug.cgi?id=1268326 assuming that the failure should either cause an error, or not fail and show a warning.

**Comment by npbenjohnson** [comment]
This is part of to-fast-properties, which is part of a bunch of things. Failing on unreachable code isn't actually part of the 'use strict' spec, but it fails on use strict in FF evals, so I guess development in FF is probably just broken until they fix it.

**Comment by guybedford** [comment]
Perhaps it would be worth using Babel 6 here then to avoid this issue.

**Comment by guybedford** [comment]
If you're able to share the exact underlying issue here that may help, as it sounds like this is just the way strict mode works?

**Comment by npbenjohnson** [comment]
There is definitely a bug, possibly relating to "toFastProperties" when debugging in firefox, but my initial thoughts were completely wrong, so I'm going to close this and I'll open a new one if I find something reproducible.

**Comment by npbenjohnson** [comment]
This was capaj/systemjs-hot-reloader#83, and the symptoms are something will fail sometimes somewhere, so my first guess was nonsense.
