### ISSUE TITLE
External extensionless resources in jspm project fail

### ISSUE THREAD

**Issue by npbenjohnson** [systemjs/systemjs#1243]
Based on #490 am I correct to assume that there is no way to load external extension-less resources in a JSPM project? Google APIs are hosted at bare endpoints, but with auto extensions on, [this example] (http://plnkr.co/edit/uF6N79pLQCmTvjJxS7X9?p=preview) doesn't work.

**Comment by guybedford** [comment]
@npbenjohnson this is exactly why `defaultJSExtensions` is being deprecated - having it disabled is the recommended behaviour.
