### ISSUE TITLE
Chai dependency loading fails for unknown reason 

### ISSUE THREAD

**Issue by npbenjohnson** [systemjs/systemjs#1244]
Using the package in the jspm registry, everything appears to be registered correctly:
```
    "chai": "npm:chai@3.5.0",
    "npm:chai@3.5.0": {
      "assertion-error": "npm:assertion-error@1.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "deep-eql": "npm:deep-eql@0.1.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2",
      "type-detect": "npm:type-detect@1.0.0"
    },
```
but when it is loaded, the require(dependency) statements inside Chai are resolved at (base)/(dependency).js as if the dependency wasn't registered
ex: require('assertion-error') resolves to localhost/assertion-error.js

**Comment by guybedford** [comment]
This is a jspm issue not a SystemJS one.

Are you running jspm 0.16 or jspm 0.17? I just tested it and this seems to work ok in jspm 0.17 for me.

**Comment by npbenjohnson** [comment]
I'm still on 0.16, I'm working around it by using the github version for now.
