### ISSUE TITLE
Do not evaluate scriptLoad:true files

### ISSUE THREAD

**Issue by Zenorbi** [systemjs/systemjs#1245]
If I specify SystemJS to use `scriptLoad:true` (it can, as the module is in amd or system.register format), do not call `eval` for the given load's source, as the source will be empty. The problem with evaluating empty modules, is that when I disable chrome's source map support, every file that chrome loads with script tag gets overwritten in the debugger by the empty
```
(function(System, SystemJS) {
})(System, System);
```
code which has sourceMap baked into it. This also affects Firefox.

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/systemjs/systemjs/commit/8d64131a03ad171b452d83dcda59a574ee27e037.

**Comment by guybedford** [comment]
Released in 0.19.27.
