### ISSUE TITLE
Maybe: Incorrect bundle evaluation

### ISSUE THREAD

**Issue by marvinscharle** [systemjs/systemjs#1247]
Hi everybody,

we're currently working on an Ionic project. This project is to use some parts of an existing web application bundled using SystemJS Builder. The bundle for the existing web application is bundled correctly but the bundle containing Ionic parts is (IMO) not evaluated properly by SystemJS.

Using the [SystemJS Builder Instructions](https://github.com/systemjs/builder) we created a bundle containing all external dependencies. The expected behavior is that SystemJS is using the bundle to import all dependencies. But unfortunately, for `ionic-angular` and `ionic-native` dependencies, SystemJS is issuing XHRs request to import (non-existing) files, despite the dependencies are bundled indeed.

**Steps to reproduce:**

Using [this repository](https://github.com/marvinscharle/ionic2-systemjs) and Ionic 2:

1. Install Ionic 2 `npm install -g ionic@beta`
2. run `npm install`
3. run `ionic serve`
4. open localhost in browser, display console or network requests

**Bundeling Process:**

[gulpfile.js](https://github.com/marvinscharle/ionic2-systemjs/blob/master/gulpfile.js) using instructions of [SystemJS Builder](https://github.com/systemjs/builder):

```js
    var builder = new Builder({
        packages: {
            app: {
                format: 'register',
                defaultExtension: 'js'
            }
        },
        paths: {
            '*': './node_modules/*',
            'app/*': 'app/*',
            "ionic-angular": './node_modules/ionic-angular/index.js',
            "ionic-native": './node_modules/ionic-native/dist/index.js'
        },
        defaultJSExtensions: true
    });

    // Combine angular dependencies into dependencies.js
    builder
        .bundle('app/**/*.js - [app/**/*]', './www/ng/dependencies.js')
        .then(function () {
            // Uglify using gulp
            gulp.src('./www/ng/dependencies.js')
                //.pipe(uglify({mangle: { keep_fnames: true}, compress: {keep_fnames: true} }))
                .pipe(gulp.dest('./www/ng'));
        })
        .catch(function (err) {
            console.log(err);
        });
```

Embedding in [index.html](https://github.com/marvinscharle/ionic2-systemjs/blob/master/www/index.html):

```html
<body>
<!-- cordova.js required for cordova apps -->
<script src="cordova.js"></script>
<script src="/ng/static.js"></script>
<script>
    System.config({
        baseURL: '/ng',
        defaultJSExtensions: true
    });
</script>

<script src="/ng/dependencies.js"></script>
<!-- this Ionic's root component and where the app will load -->
<script>
    System.import('app/app').then(null, console.error.bind(console));
</script>
<ion-app></ion-app>
</body>
```

**XHR-Requests:**

![screenshot 2016-04-28 23 05 28](https://cloud.githubusercontent.com/assets/5916903/14901457/bcb63392-0d95-11e6-8d63-0ca835c73594.png)

Is this related to SystemJS? Are we misconfiguring something wrong? Or is this related to `ionic-angular` / `ionic-native`?

**Comment by guybedford** [comment]
The configuration used to build the bundle needs to also be included before running the bundle in production. This is because a bundle is just a multiplexing replacing the need to do separate file requests, but not a static optimization.

If you include the same configuration, then for example the `ionic-angular` path will resolve correctly and be able to be shared properly with the bundle.

**Comment by marvinscharle** [comment]
Thank you @guybedford, this makes the functionality of `paths` inside bundles much clearer.
