### ISSUE TITLE
Packages don't work with normalized paths.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/systemjs#1249]
```js
SystemJS.config({
  transpiler: "plugin-typescript",
  format: "esm",
  packages: {
    "source": {
      defaultExtension: "ts",
      meta: {
        "*.ts": {
          loader: "plugin-typescript"
        }
      }
    }
  }
  baseURL: "/",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "*": "source/*"
  }
});
System.normalize('app').then(function(app) {
	console.log(app);
});
```

I would expect `http://localhost:8080/source/app.ts` to be logged but instead `http://localhost:8080/source/app` is logged.  This of course leads to problems with import since the file `source/app` does not exist.

The issue appears to be that because `app` was translated via the `*` path it becomes ineligible for further processing, including applying any package rules or top-level rules (moving the `defaultExtension out of the package doesn't resolve the issue).

No matter what I do I can't seem to be able to get the `defaultExtension` to apply to `app` in the above example.  Even if I change my `baseURL` to `/source` and remove the path mapping for `*`, it still won't apply the `defaultExtension`.

This is a problem because Aurelia attempts to load `app` because it needs to be language agnostic (allowing for `js`, `ts`, etc.).  However, as it stands currently, I don't believe there is any way to get SystemJS to correctly apply the extension.

**Comment by Zoltu** [comment]
Workaround for those running into this issue:

Provide a mapping of `app` to `source/app`.

**Comment by guybedford** [comment]
@Zoltu `paths: { '*': 'app/*' }` is no longer a supported pattern and will break the packages configuration as it will read the package config as `source/source` as configuration itself runs through paths config.

**Comment by Zoltu** [comment]
Am I correct in understanding then that the only way to get this sort of thing to work is via mappings (as mentioned in my workaround comment)?  Is there no other way to have references to root level resources (like `System.import('app')`) work?

**Comment by guybedford** [comment]
The recommended app folder pattern is now:

```javascript
System.config({
  paths: {
    'app/': 'path/to/src/'
  },
  packages: {
    app: {
      main: 'main.js'
    }
  }
});
```
