### ISSUE TITLE
System.import and DOM load race condition

### ISSUE THREAD

**Issue by cjkoski** [systemjs/systemjs#1253]
Hi.

I am looking for advice on how best to approach the race condition between System.import and DOM loading.

For instance:

If I have my JS defined such that

`
System.import('module').then(function(module) {
    //application logic here
});
`

And then later in the HTML I define the main div that the application interacts with:

`<div id='main-app-div'></div>`

Depending on how fast the module loads, sometimes the div will be defined and sometimes it will not - resulting in intermittent application load failures.

We have a temporary solution of wrapping System.import in $(document).ready, but this places a dependency on jQuery in order to use SystemJS to load modules.  That just feels wrong to me.

We also have tried fixing this problem by ensuring that main-app-div is output before System.import, and this works well, but watch out before you shoot your foot next time again.

So a couple of questions:

1.  Is there a way to control/configure when the System.import promise returned gets resolved in the loaded module?  IE,  I could load the required module, load the preferred version of jquery, and verify document.ready before System.Import's returned promise gets resolved and invoked.

2.  Anyone recommendations for best way to address this race condition?

**Comment by cjkoski** [comment]
Hi,

Update on this, we got around the race condition by making it a policy that if an app loaded over JSPM performs any interaction with the DOM..then that application is responsible for importing it's preferred compatible version of jQuery and using $(document).ready before any DOM stuff happens.

I'm still curious if anyone has come across a more elegant solution.

Cheers thanks all.

**Comment by amenadiel** [comment]
I made [a jQuery plugin](https://github.com/HuasoFoundries/jquery.waitforChild), a few months ago, that declares a listener on a given DOM node. You can detect whenever another object is appended to a DOM node, so in this case, when said object matches the declared selector, it triggers a callback.

However, it meant you'll still depend on jQuery. So here's a way that uses the browser's native parser to check if a given ID exists. If it doesn't, it will call itself in 1000ms. And again, and again, until it finds said element. 

```js
var eventuallyGetElement = function(theid, callback) {
    var theNodeImLokkingFor = document.getElementById('main-app-div');
    if (theNodeImLookingFor) {
        callback(theNodeImLookingFor);
    } else {
        window.setTimeout(function() {
            callback(eventuallyGetElement(theNodeImLookingFor));
        }, 1000);
    }
};

// and then later in the app
var something_with_the_node=function() {
    eventuallyGetElement('main-app-div', function(node) {
      // something with the found DOM Element
    });
};

```


It's a nasty solution and it might break havoc. And I, personally, would do it with promises, but if a dependency on jQuery is troubling you, then a Promise polyfill will make things worse.

**Comment by guybedford** [comment]
@cjkoski an alternative may be to include the script tag for SystemJS or the import statement at the end of the body in the HTML.

**Comment by born2net** [comment]
I did also ran into a racing situation on angular2 and bundled jspm file.
added documents ready or timeouts fixed it.
 I recommend adding this today documentation.
