### ISSUE TITLE
Consecutive System.config() calls overwrite metadata

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1255]
I've been trying to debug a weird issue I was seeing and it looks like it boils down to this: when `System.config()` is being called multiple times consecutive calls overwrite/invalidate metadata from the previous ones. In my example I'm setting `scriptLoad` attribute:

``` js
packages: {
  "app": {
    "defaultExtension": false,
    "meta": {
      "*.js": {
        "format": "register",
        "scriptLoad": true,
        "crossOrigin": "anonymous"
      }
    }
  }
}
```

And it gets invalidated after the second `config` is applied (even if it's empty):

``` js
System.config({
  packages: {
    "app/foo": {}
  }
});
```

Here you can see that `app/foo/bar.js` and `app/foo/baz.js` are being loaded via XHR rather than script tag:
![scripts](https://cloud.githubusercontent.com/assets/1755336/15029633/1abcd9e4-1257-11e6-802d-b9eef11207c6.PNG)

Here's a plunkr with reproducible setup: http://plnkr.co/edit/AThwKSTpVQo1ZO3okcxp?p=preview

**Comment by asapach** [comment]
Although thinking about it more, it could be that "nested" packages don't inherit from their "parents". Is that by design?

**Comment by guybedford** [comment]
Yes, only one package match is selected for a given module path with package nesting.

**Comment by asapach** [comment]
Perhaps that should be mentioned in the docs?

**Comment by guybedford** [comment]
Certainly, yes.
