### ISSUE TITLE
Shiming Global module with Node module not working

### ISSUE THREAD

**Issue by smamessier** [systemjs/systemjs#1256]
Hi guys, I'm working with [Three.js](https://github.com/mrdoob/three.js), there are two libraries I want to load:

- `three.js` which is the main file of the corresponding NodeJs module.
- `ColladaLoader.js` which is a plugin-in assuming the object `THREE` exists in the global namespace. The code of `ColladaLoader.js` looks like 
```
THREE.ColladaLoader = function () {
 function load() = {
     // Doing stuff with THREE.Matrix4, and other stuff using THREE
 }
}
```

I use systemjs the following way
```
System.config({
  meta: {
    'ColladaLoader': {
      exports: 'THREE.ColladaLoader',
      format: 'global',
      globals: {
        THREE: 'three'
      }
    }
  },
  packages: {
    'three': { main: 'three.js', defaultExtension: 'js'}
  },
  map: {
    'three': 'node_modules/three',
    'ColladaLoader': 'node_modules/three/examples/js/loaders/ColladaLoader.js'
  }
})
```

Both `ColladaLoader` and `three` module properly export, and are accessible from my code using:
```
import * as THREE from 'three';
import ColladaLoader from 'ColladaLoader';
```
However, using `ColladaLoader` fails and error message indicate that it doesn't resolve `THREE` to the nodeJS module `three` as it should be since I'm using `Custom globals` to shim it. (As documented in  https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#globals).

Thanks a lot for your help !

**Comment by smamessier** [comment]
Ok I did some additional inspection, it looks like the shimming is working during the execution of the Global script, however the variable `THREE` is not available at runtime anymore from the global module.

**Comment by guybedford** [comment]
I copied the structure you have here and was able to run `System.import('ColladaLoader')` and get the right module back fine. Can you share an example of what code I can run to get the error you had here?

**Comment by guybedford** [comment]
Let me know if you still need assistance at all.

**Comment by backspaces** [comment]
Er, .. did the config ever work? Or is there a slight adjustment needed?

I have the same problem, as do all module users of three.js, which has not yet figured out how they are going to evolve into modern JS.

.. and there are 177 such modules using THREE.Foo = ... !! You can see them in your project by running this in your project dir:
```
cd node_modules/three/examples/js/
grep '^ *THREE\.[^ .]* =' */*.js
```

I certainly have not figured out a config that would help me tame module use in three.js. I currently simply use a script tag for THREE, and use "empty imports"
```
import 'path/to/OrbitControls.js'
```
.. and use THREE.OrbitControls in my code.

This is painfully sad, but I see no way to create the right config to make this all work. But I can think of 177 reasons to keep trying!

**Comment by backspaces** [comment]
@smamessier @guybedford Did either of you find a config that works? One that allows:
```
import * as THREE from 'three';
import ColladaLoader from 'ColladaLoader';
```
.. such that ColladaLoader appears to import/access THREE during loading and later during execution of `loader = new ColladaLoader(..)`
