### ISSUE TITLE
Error Loading lib/npm/zone.js@0.6.12.js.json

### ISSUE THREAD

**Issue by jcmoore0** [systemjs/systemjs#1257]
Hi Guy - When loading zone.js, normalize changes defaultJSExtension to false and appends  '.js' to the name and the json cannot be found. Thanks,
John

**Comment by guybedford** [comment]
@jcmoore0 this request looks like it was made by jspm 0.17? If so, jspm 0.17 is not compatible with `defaultJSExtensions: true`. The default is for this to be disabled though.

**Comment by guybedford** [comment]
Just let me know if you still need further help here at all.

**Comment by jcmoore0** [comment]
Hi Guy - I am using jspm 0.17 with defaultJSExtensions: true.  
Everything works fine with the exception of zone.js.
The browser fails to find the file zone.js@0.6.12.json because an extra js is inserted:
 .../npm/zone.js@0.6.12.**js**.json

To get around this issue, I had to insert into system.src.js (line 2481):
        if (name === 'zone.js')
          defaultJSExtension = true;

Are you saying defaultJSExtension:true is no longer supported?
I am unclear on an alternate strategy.

Thanks again.
John

**Comment by guybedford** [comment]
Yes, `defaultJSExtensions` is not supported in jspm 0.17.
