### ISSUE TITLE
Error loading jspm_packages/github/jspm/nodelibs-buffer@0.1.0.js as "buffer"

### ISSUE THREAD

**Issue by playground** [systemjs/systemjs#1259]
Just upgraded to angular rc.1 and getting the following error.

Error: XHR error (404 Not Found) loading jspm_packages/github/jspm/nodelibs-buffer@0.1.0.js
Error loading jspm_packages/github/jspm/nodelibs-buffer@0.1.0.js as "buffer" from jspm_packages/npm/rxjs@5.0.0-beta.6/operator/buffer.js

**Comment by playground** [comment]
I got further along, now on to a different issue.

Error: Error: XHR error (404 Not Found) loading crypto.js
Error loading crypto.js as "crypto" from /jspm_packages/npm/reflect-metadata@0.1.3/Reflect.js

**Comment by guybedford** [comment]
Try adding map config to remove crypto - `map: { 'crypto': '@empty' }`. That's what we do in jspm for reflect metadata in the browser I believe.

**Comment by guybedford** [comment]
Just let me know if you still have any questions here.
