### ISSUE TITLE
angular2 and electron

### ISSUE THREAD

**Issue by kazemihabib** [systemjs/systemjs#1261]
I'm using angular2 and electron and systemjs . and when I want to import 'electron' in render process of electron  and when I import it like this:```import * as electron from 'electron';``` (I installed type definition of electron) . It tries to import the electron module from dist folder but it is not there it's in node_modules, then I tried to add this ```    'electron':                   '../../node_modules/electron-prebuilt',``` in map of systemjs.config but it didn't help.how can I config it?

**Comment by guybedford** [comment]
For electron support specifically, I've just added the ability to do `require('@node/electron')` in the latest release of SystemJS coming out this week. I'll post here when it's out so you can try it out.

**Comment by guybedford** [comment]
Sorry I mean `import electron from '@node/electron'` of course...

**Comment by kazemihabib** [comment]
thanks , and Is there a way to require other nodejs modules?

**Comment by guybedford** [comment]
Yes `import '@node/x'` will now support any packages from node_modules in Node.

**Comment by guybedford** [comment]
Released in 0.19.28.

**Comment by bdbayes** [comment]
I am attempting to use the ` import electron from '@node/electron' ` command, but when I run it through the TypeScript compiler, it returns the following error:
` error TS2307: Cannot find module '@node/electron'.`

**Comment by redders6600** [comment]
@bdbayes did you find a way to deal with typescript not understanding this sort of import?

**Comment by bdbayes** [comment]
@redders6600: I was able to find a solution.  By instead defining "electron" to point to "@node/electron" in the systemjs map, I was able to use the library normally by using the regular import syntax.

**Comment by uglycoyote** [comment]
@bdbayes thank you so much for this last comment, I have been searching the internet all day trying to understand how to get typescript and systemjs to bring node's "fs" into the render thread of an Electron application.  I had seen this "@node/fs" syntax a few times but I tried it and typescript didn't understand it.  Using "fs" : "@node/fs" in the systemjs map solved my problem completely.  Thanks again.

**Comment by timfish** [comment]
For anybody else who ends up here...
Like **redders6600**, I got this working by adding wrappers in a custom `d.ts`:

```typescript
declare module '@node/electron' {
  var electron: Electron.ElectronMainAndRenderer;
  export = electron;
}

declare module '@node/path' {
  import path = require("path");
  export = path;
}

declare module '@node/fs' {
  import fs = require("fs");
  export = fs;
}

declare module '@node/os' {
  import os = require("os");
  export = os;
}
```

**Comment by chandrasekarb** [comment]
I am using React js *.jsx and webpack how to use
 `declare module '@node/fs' {
  import fs = require("fs");
  export = fs;
}`

this code anybody give solution please

**Comment by timfish** [comment]
@chandrasekarb You are using SystemJS and Webpack together?

**Comment by chandrasekarb** [comment]
I am not using  SystemJS

**Comment by timfish** [comment]
Then why are you posting in the SystemJS repository? 

`'@node/fs'` will only work with SystemJS...

**Comment by Longfld** [comment]
here is angular 5 electron with systemjs 
https://github.com/Longfld/electron-angular-material
