### ISSUE TITLE
Module loading not working

### ISSUE THREAD

**Issue by calbertts** [systemjs/systemjs#1263]
I'm pretty new using SystemJS, just tried to follow the documentation but I'm experiencing some problems with the basic example.

I just published a repository with the basic example to load an ES6 module, that is supposed it has to work fine by using NodeJS.

[https://github.com/calbertts/systemjs_test](https://github.com/calbertts/systemjs_test)

Not sure if I'm missing something, I've also tried with **es6-module-loader** repository but I had the same result.

I'll really appreciate if you can help me with this.

**UPDATE:**
Currently I'm using `systemjs@0.19` and it doesn't work, but I've tried with `systemjs@0.15` and the module was loaded correctly.

When I installed the latest version it only installed two packages ("when" and "systemjs") but with 0.15 it installed also **es6-module-loader** and I guess that's why it's working with this version.

Is this a bug in the latest version or maybe I do not understand how this project should work.

**Comment by Vanuan** [comment]
Have you tried this:

```
If transpiling ES6, also install the transpiler:

  npm install traceur babel typescript 

```

**Comment by calbertts** [comment]
I already have Babel installed globally, not sure if it's enough.

**Comment by Vanuan** [comment]
What's stopping nodejs from termination in your example?

**Comment by calbertts** [comment]
It's failing silently, no errors, no messages, no exceptions, nothing.
I only can see my first console.log(...), but nothing else.

**Comment by Vanuan** [comment]
Is it failing or just terminating without errors? Have you tried adding setTimeout in the end?

**Comment by calbertts** [comment]
I just tried, but it seems like nothing is imported and the nodejs process is finishing normally, maybe SystemJS is swallowing an error internally.

By the way, I just updated the repository.

**Comment by Vanuan** [comment]
Have you tried adding catch?

> import().then().catch()

**Comment by calbertts** [comment]
OK cool, now I have a message:

> no such file or directory, open '/Users/Projects/systemjstest/babel

How it's supposed that I have to install babel?
Can I custom the path of the transpiler?

Currently it's installed globally, do I have to install it locally? but anyway I don't understand why it's looking for babel in the same folder where the app is.

**Comment by Vanuan** [comment]
I think you have to do this:

    npm install babel

**Comment by Vanuan** [comment]
It's not possible to require a global module:

http://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package

There's no special about systemjs.

**Comment by calbertts** [comment]
I did it, now I have locally installed on the project but it's still failing for the same reason.

**Comment by Vanuan** [comment]
does `require('babel')` work?

**Comment by calbertts** [comment]
No, I'm getting this:

> Error: The node API for `babel` has been moved to `babel-core`.

I supposed it's because I'm using Babel 6, what would be the right version to be used with systemjs?

**Comment by christyharagan** [comment]
The trick is to use plugin-babel:

https://github.com/systemjs/plugin-babel

The systemjs documentation needs updating, so it is a little confusing right now. I believe the intention is to deprecate the internal transpilation system in favour of these external plugins.

**Comment by calbertts** [comment]
I'm working on NodeJS, and it seems that plugin is a browser specific, actually I cannot install it by using NPM.

Any ideas?

**Comment by christyharagan** [comment]
npm install systemjs-plugin-babel

**Comment by calbertts** [comment]
Thanks it did the trick!..

Just for future references, after install SystemJS and System Plugin Babel, I had to configure in this way:

```
SystemJS.config({
    map: {
      'plugin-babel': 'node_modules/systemjs-plugin-babel/plugin-babel.js',
      'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-node.js'
    },
    transpiler: 'plugin-babel'
  })
```

Thanks guys.

**Comment by guybedford** [comment]
Thanks @christyharagan for the clarification. Yes a docs update will be coming soon!
