### ISSUE TITLE
module is not defined when transpiling Typescript using module: "commonjs"

### ISSUE THREAD

**Issue by filipesilva** [systemjs/systemjs#1266]
Heya,

I've a simple Angular 2 [quickstart app](https://github.com/angular/quickstart) running locally, which I've modified `app.component.ts` to also have `moduleId: module.id`:

```
import {Component} from '@angular/core';

@Component({
    moduleId: module.id,
    selector: 'my-app',
    template: '<h1>My First Angular 2 App</h1>'
})
export class AppComponent { }
```

Locally I compile to typescript, serve and use SystemJS to load it and it runs fine.

I also tried to do this in a plunker, using typescript compilation and setting `module: "commonjs"` on `typescriptOptions` but I seem to be getting `Error: ReferenceError: module is not defined`. The plunker can be found here: http://plnkr.co/edit/xZkh2B44LU0HA3GlOWaC?p=preview

I've read https://github.com/systemjs/systemjs/issues/1030 and it seems that a `__moduleName` property exists for ES Modules, but since I'm compiling to CommonJS modules I thought `module` would be available.

Is this scenario possible using SystemJS?

**Comment by johnpapa** [comment]
Very interested in the outcome of this as it affects the plunkers for all of the angular 2 docs

cc/ @wardbell

**Comment by mhegazy** [comment]
Please note that the values for `typescriptOptions` are enum values and not strings. so `module: "commonjs"` is an invalid value, and should be instead `module: ts.ModuleKind.CommonJS`. see issue https://github.com/systemjs/systemjs/issues/1202. 
Cleaning up the API on the TS side to accept strings is tracked by https://github.com/Microsoft/TypeScript/issues/7980

**Comment by filipesilva** [comment]
@mhegazy I tried following your suggestion and link, but the result seems to be the same:

- using `module: ts.ModuleKind.CommonJS`: http://plnkr.co/edit/XfrnCQ0zzEAs9Iqs8Uh8
- using https://github.com/frankwallis/plugin-typescript : http://plnkr.co/edit/CcP0uMNPJ7tr7VNMjbzH

Both still give me `Error: ReferenceError: module is not defined`.

**Comment by frankwallis** [comment]
I'm not sure if this is the *correct* solution but using ```__moduleName``` instead of ```module.id``` does work. There is more info [here](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#es6).

**Comment by filipesilva** [comment]
Heya @frankwallis, we were using `__moduleName` before in all the Angular 2 examples in www.angular.io and it worked well, but recently we changed our style guide recommendation to use `module.id` instead in order to better support non-SystemJS workflows.

We could end up changing it back, but would like to know what the real issue is with SystemJS TS transpilation vs tsc-transpilation in regards to `module.id`. 

I understand if it is not supported, or if there is a technical reason for why it cannot work... But would like to know if that is the case or if it is a bug, so we can act accordingly and update our recommendations.

**Comment by frankwallis** [comment]
The built in TypeScript transpiler always outputs in system format regardless of the ```module``` config option, see [here](https://github.com/systemjs/systemjs/blob/596b751b531d960acc73ff41678c4681d137ae75/dist/system.src.js#L1296). So SystemJS never sees the module in commonjs form so it does not apply the commonjs [wrapper](https://github.com/systemjs/systemjs/blob/596b751b531d960acc73ff41678c4681d137ae75/dist/system.src.js#L3910).

In the plugin-typescript example I don't think that plugin-typescript is actually being called, and it works for me in a different test, so I need to debug the plnkr a bit further.

**Comment by filipesilva** [comment]
Oh that's very good news, I'm happy enough knowing that I misused your plugin but that it solves the issue!

Maybe it was the way I loaded the typescript lib, since I used a script tag?

**Comment by frankwallis** [comment]
Here it is working with plugin-typescript: http://plnkr.co/edit/OWTrV0Y1Uf6b550luV4h?p=preview

There seems to be something a bit odd, because I had to rename it from ```ts``` into something else, and I seem to recall that when ```global.ts``` exists it uses the built-in transpiler?

**Comment by filipesilva** [comment]
That's awesome @frankwallis! 

There's no specific need to load `typescript` in a script tag, so I suppose the `typescript-wrapper.js` could be done away if typescript was loaded from within SystemJS. 

I tried loading it using `'module': 'global'` (and also every other mode) but that doesn't seem to work: http://plnkr.co/edit/mj4cb8Jbw7BhKzK1DVzB?p=preview

Is there a specific way that `typescript.js` needs to be loaded?

**Comment by filipesilva** [comment]
My bad, I was missing some meta information:
```
    meta: {
      'typescript': {
        "exports": "ts"
      }
    },
```
Fully works now: http://plnkr.co/edit/AWMbhbSLpEdnrDitmyWR?p=preview

Thanks for all the help @frankwallis and @mhegazy, this was really blocking us!
