### ISSUE TITLE
React.js component got broken after using `jspm bundle-sfx`

### ISSUE THREAD

**Issue by jeud** [systemjs/systemjs#1267]
I have done some googling so I think my problem might be related to `system.js`

I have a very simple React.js Component *app/index.js*

    import React, { Component } from 'react';
    import ReactDOM from 'react-dom';
    
    class ReactApp extends Component {
    
    	handleClick(event) {
    		console.log('Clicked ...');
    	}
    
    	render() {
    		return (
    			<div>
    				<h3>Hello World</h3>
    				<button className="btn btn-success" onClick={ this.handleClick.bind(this) }>Click</button>
    			</div>
    		);
    	}
    }
    
    ReactDOM.render(<ReactApp />, document.getElementById('reactApp'));

This component works fine using jspm (development mode) with `<script>` tag in the *index.html* as below

    <script type="text/javascript" src="jspm_packages/system.js"></script>
    <script type="text/javascript" src="config.js"></script>
    <script type="text/javascript">
    	System.import('app/index');
    </script>

After using `jspm bundle-sfx app/index dist/app.min.js` and editing *index.html* to

    <script type="text/javascript" src="dist/app.min.js"></script>

I then have got this error

[![enter image description here][1]][1]

    'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
    
    'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

I believe, I have done this using `jspm bundle-sfx` 2 months ago, it was working just fine, I have tried to google for some solution but no luck, please guide

Thanks

  [1]: http://i.stack.imgur.com/YwfRF.png

**Comment by guybedford** [comment]
These are not critical warnings here. The issue would be something else. I'm surprised there isn't any error though.

Perhaps try step debugging to see where in the code it is stopping? If you can share the `dist/app.js` (unminified) file I may be able to take a look.

**Comment by guybedford** [comment]
https://github.com/jspm/jspm-cli/issues/1803 is the better place for this... closing this as the duplicate.
