### ISSUE TITLE
Update systemjs documentation for using plugins for transpilation

### ISSUE THREAD

**Issue by christyharagan** [systemjs/systemjs#1268]
The systemjs documentation refers to outdated instructions on transpilation. For the case of Babel - at least - the instructions simply don't work anymore.

The documentation should be updated to reflect the new approach to transpilation using external plugins, perhaps with a reference to the old style (at least for TypeScript which does at least still work) until it is officially deprecated.

**Comment by guybedford** [comment]
👍

**Comment by aluanhaddad** [comment]
@christyharagan The non-plugin babel configuration still works as well. I used it several times today. That said, we all need to move to plugins. I find plugin-typescript to be very easy to use and configure.
