### ISSUE TITLE
globally defined module throwing errors, being treated as amd module

### ISSUE THREAD

**Issue by ciel** [systemjs/systemjs#1271]
Pursuant to [this topic](https://github.com/systemjs/systemjs/issues/1270) I've gathered more information and will try to present my problem in a better format.

I am trying to load in `showdownjs`, I have nothing that depends on it - but I need to use it within my code. Attempting to define it as a normal module _seemed_ to work at first, as I received no errors on loading - but when attempting to call `showdown` from within the code it yields an error that says `showdown is not defined`.

I __can__ load it raw, old fashioned using `<script>` tags and it __does__ work that way. So I know the library isn't broken, and I know the path is correct, and I know the code trying to use it is correct.

This is how I'm attempting to register it;

````
System.config({
    transpiler: "typescript",
    defaultJSExtensions: true,
    map: {
        'showdown'          : 'http://path-to-cdn/js/showdown.js'
    },
    meta: {
        'showdown': {
            exports: 'showdown',
        }
    }
});

Promise.all([
    System.import('showdown')
    // other imports
]).then(function(modules) {
    // showdown is not defined
});
````

After some discussion, it was told to me that I needed to load it as a global shim, so I tried this approach;

````
'showdown': {
            exports: 'showdown',
            format: 'amd',
            globals: {
                showdown: 'showdown'
            }
        },
````

and I get no errors on load, but when trying to call it in code again, it still fails. I tried to register it as `format: "global"` then;

````
        'showdown': {
            format: 'global', scriptLoad: true,
            globals: {
                showdown: 'showdown'
            }
        }
````

And this got the error `AMD define called while executing global module`.

I know I'm importing it right; I get the same result whether I use `Promise.all` or `import "showdown";`. I really have no idea what could be wrong here.

**Comment by guybedford** [comment]
You need to explicitly create a `var showdown` variable from the value returned by the `System.import` statement like:

```javascript
Promise.all([
    System.import('showdown')
    // other imports
]).then(function(modules) {
    var showdown = modules[0];
    // showdown is now defined
});
```
