### ISSUE TITLE
 Mixed dependency cycle detected

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/systemjs#1272]
I'm getting the error message in the title after knowingly introducing a cyclic dependency in my application. I think I'm right in saying that SystemJS can support cyclic dependency if you're exclusively using `System.register`-type modules (which I am), so I'm not sure if I'm doing something wrong, or if this is a bug. 

My application is split into modules, and these include a 'Framework' module which handles the application, a 'UI' module which defines some UI components, and some others which aren't of relevance. Basically my Framework module uses some of the UI components, and some UI components need to use the 'Framework' module to do things like host modals and popovers.

These modules are written in ES6, bundled using Rollup, and turned into SystemJS modules using Babel. The result is an ES5 module that is wrapped in a single `System.register` call.

There also tends to be a CSS file for each of these modules, so I load these together by loading through a `System.registerDynamic` module like so:

**framework.js**
```javascript

System.registerDynamic(["./framework/index","./framework/index.css!"], true, function(require, exports, module) {
    module.exports = require('./framework/index');
});
```
These are all either loaded in through `import` or `System.import`.

I think that's everything of relevance. Is there anything wrong with what I'm doing that may cause cyclic dependencies to not work? Let me know if there is any more detail I can give to help.

**Comment by guybedford** [comment]
Yes mixed cycles are not supported. Basically if you have A loads B loads C loads A, where A and B are ES6 and B is CommonJS / AMD / global, this throws due to the differences in how circular references work between the two systems.

**Comment by jamiewinder** [comment]
I'm not sure I am mixing module types? I'm certainly not knowingly. These are always System.register-type modules. Could my weird 'import JS and CSS, export JS' workaround above (see code snippet) be a factor?

**Comment by guybedford** [comment]
`System.register` is a different type of `System.registerDynamic`, so mixing counts even if it is `System.register` loads `System.registerDynamic` loads `System.register`.
