### ISSUE TITLE
Issue with relative loading in concatenated files

### ISSUE THREAD

**Issue by huyph** [systemjs/systemjs#1273]
This is a working angular 2 codes with relative module loading:

File name: `my.component.ts`
```typescript
declare var __moduleName: string;

@Component({
    selector: 'my-component',
    moduleId: __moduleName,
    templateUrl: './my.component.html'
})
export class MyComponent { }
```
_the codes are taken from one of the comments here (https://github.com/angular/angular/issues/6053)_

Inspecting the transpiled JS file: `my.component.js`, it shows that `__moduleName` is resolved by SystemJs to be a path to this JS file, with this piece of codes:
```javascript
  ...
  var __moduleName = context_1 && context_1.id;
  ...
```

So `__moduleName ` equals to `...<correct path>../my.component.js` That works well for dev environment.

However for build, if all JS files are concatenated into a single js. Now `__moduleName` is `undefined` because `..<not existed path>../my.component.js` is not existed this build environment

**Comment by guybedford** [comment]
Have you tried building as an ES module itself here? That way `__moduleName` can be defined in the new context of the build.

If that approach can work, we may be able to generalise the principles.

**Comment by guybedford** [comment]
(I mean `builder.buildStatic('main.js', { format: 'esm' })`)

**Comment by born2net** [comment]
I am using TS 1.8.10 and can't erroring out with:
```
EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'annotations' of undefined
  EXCEPTION: Error: Uncaught (in promise): TypeError: Cannot read property 'annotations' of undefined
  STACKTRACE:
```
when trying moduleId: __modulename

with ng2 rc.1 and ts 1.8.10 and not bundling, just using in browser with ts plugin

**Comment by guybedford** [comment]
@born2net note it is `__moduleName` not `__modulename`.

**Comment by born2net** [comment]
that did it ;) TX!!!
