### ISSUE TITLE
What does System.normalize do?

### ISSUE THREAD

**Issue by marthinus-engelbrecht** [systemjs/systemjs#1274]
Hi,

The obvious answer is it normalizes, but I'm currious as to what does it take into account to do the normalization? I can't find any concise documentation on this.

**Comment by guybedford** [comment]
Yes it's an important part of the project to understand and properly document. I've been working on this in https://github.com/systemjs/systemjs/blob/22374bbd9a040111acaf8a7681a876667b55cad1/docs/resolution-algorithm.md. The "spec-style" resolution algorithm is complete, but the information at the top is still patchy.

**Comment by guybedford** [comment]
Unfortunately the spec is easier to read in raw form (https://raw.githubusercontent.com/systemjs/systemjs/22374bbd9a040111acaf8a7681a876667b55cad1/docs/resolution-algorithm.md) because the indentation seems a little messed up still in markdown.

**Comment by marthinus-engelbrecht** [comment]
As always, thanks for taking the time to answer. Will give it a read.

**Comment by davis** [comment]
running into a weird thing where it's trying to read from file:// when using normalizeSync, but xhr doesn't allow loading from there...
![screen shot 2016-05-23 at 5 38 52 pm](https://cloud.githubusercontent.com/assets/4855619/15488642/3dbc58ce-210d-11e6-9b7c-53db81cb8c08.png)

**Comment by guybedford** [comment]
@davis either enable --file-access-from-files in Chrome or use a local server with the `System.baseURL` not set to a file URL.
