### ISSUE TITLE
`paths: { *: '*.js' }` exception?

### ISSUE THREAD

**Issue by SonofNun15** [systemjs/systemjs#1275]
Our systemJS configuration contains: 
```
	paths: {
		// CSS and HTML paths have to be more specific than JS paths to take precidence
		'components/*.html': 'components/*.html',
		'*': '*.js',
	},
```

We are using this to clean up the reference paths in the output from system builder per this issue: https://github.com/systemjs/builder/issues/475

We also have an application that uses the same configuration to import files without using the builder for dev workflows as opposed to production workflows.

When running the dev application, it is request for the javascript files WITHOUT the *.js extension, for example: `/source/ui.module`. 

Why would `paths: { *: '*.js' }` EVER fail to append the js extension to a request unless there is another path that is more specific? Are there some edge cases or interactions here that I am missing?

**Comment by SonofNun15** [comment]
Notice that although our path contains a more specific route for imports of html files (which have loaded with the text plugin), the ui.module import does NOT contain *.html, nor is it in the components folder.

**Comment by guybedford** [comment]
Are you saying that `System.normalize('/source/ui.module.js').then(console.log.bind(console))` is outputting `.../source/ui/module` or that `System.normalize('/source/ui.module')` is?

I really wouldn't advise using `paths: { '*': '*.js' }` as it was deprecated quite a while ago.

**Comment by SonofNun15** [comment]
`System.normalize('../source/ui.module')` is resulting in a request to `localhost:8080/source/ui.module` WITHOUT the .js extension.

**Comment by SonofNun15** [comment]
If you take a look at the issue referenced above related to building npm packages, how do you currently advise building libraries with bundled output files NOT containing `*.js` at the end of each module in the package?

**Comment by SonofNun15** [comment]
In other words, in our source tree, we have:

`/source/ui.module.js`

But in the bundled output we want:

`System.registerDynamic("components/ui.module"`.

We are currently achieving this by copying the js files into a components folder as part of the build and using `paths: { *: '*.js' }` to load the js files.

**Comment by guybedford** [comment]
What is your baseURL?

**Comment by SonofNun15** [comment]
Not set, defaults to `'/'`

**Comment by SonofNun15** [comment]
What bearing does baseURL have on this, for my understanding?

**Comment by SonofNun15** [comment]
I've had trouble following the sequencing of maps, paths, packages. Tricky to get the normalize to resolve just right without a clear understanding of how they all match up... :disappointed:

**Comment by guybedford** [comment]
`paths: {  '*': '*.js' }` will only apply to module names within the baseURL. The baseURL will default to the current page URL, so you may need to explicitly set it to `/`?

**Comment by SonofNun15** [comment]
Setting the baseURL explicitly to '/' does not appear to have helped, but it is interesting that `System.normalize('/source/ui.module').then(console.log.bind(console))` returns `ui.module` while `System.normalize('source/ui.module').then(console.log.bind(console))` returns `ui.module.js`.

Have you thought about workflows for building distributable libraries as per the issue above? I agree that using paths to strip the *.js from the export seems like a hack. Would be nice to have some easy hooks for manipulating the output names without affecting the process of loading / locating the files. This would have to be specific to the builder since SystemJS really only cares about loading modules, not exporting them with pretty names.

**Comment by guybedford** [comment]
Paths apply to "plain names", whereas `/source..` is interpreted as a URL and thus skips map and paths configurations. Another reason why wildcard paths are a bad construct (they will be fully deprecated thank goodness, and are a vestige from a very early discussion from the module loader spec in ES6).

Writing code without extensions is fine, that is what package configuraiton and `defaultExtension` is for. Bundles need to form a well defined namespace though, so automatically building in the extension is mandatory there to make the `System.register('x')` normalization process completely predictable as a concatenation to a full URL and not dependent on any deep configurations like we have with import normalization.

**Comment by SonofNun15** [comment]
So you are saying that we should go ahead and export the library with modules named:
`"source/ui.module.js"`. And then we should use a package to default the extensions to *.js so that when the other modules in this package / bundle request `"./ui.module"` this is normalized to "source/ui.module.js".

How do you namespace multiple packages when loading registered systemJS modules? If my library is exported under `source/*` using the builder and I import it into another package that also has a `source` folder with a file named `ui.module`, how do I make sure that this module can be loaded independently of the one from the imported library?

**Comment by SonofNun15** [comment]
It appears in my experience that once a module is registered in systemJS with `"source/ui.module"` this is a global module name. Any later request to import this name / path will get the registered module instead of any local file in the same path / folder. 

So copying the source files into a library folder is a hack to create a "namespace" if you will for the exported modules. Exporting `ui.module` from a `components` folder resulting in `components/ui.module` limits the name conflicts because this will only match against requests within `components/` instead of the more commonly used `source/`

**Comment by SonofNun15** [comment]
I'm hoping there is a better way to do this? :grinning:

**Comment by guybedford** [comment]
The registered name of any module is a full URL.

Bundles are not actually a distribution format - they are a multiplexing optimization allowing you to send multiple modules as a single file from a network perspective.

When you distribute your code, you can distribute the separate files along with a package configuration for SystemJS that contains the `defaultExtension: 'js'` option. The package itself would be in a folder, and that folder can be named anything by the consumer, allowing for module naming flexibility in their environment.

**Comment by SonofNun15** [comment]
What you are saying makes sense, but it does eliminate the benefit of using CDNs for shared caching. Library files are then only bundled within the final application being distributed, meaning that it will only be cached by returning users of that application. 

So you don't really see libraries getting distributed as bundles directly from a CDNs in the future? Ultimately HTTP2 is changing all of this anyway... work in progress

**Comment by guybedford** [comment]
@SonofNun15 glad it's making sense. Bundling should really be done on a per-app basis. Smart CDNs could do bundling like they do PUSH, but I'm not sure how much benefit there is there. Rather another focus to the same problem is to encourage creating optimized modules at the package level via `builder.buildStatic('my/component.js', { externals: ['react'] })` which can do things like Rollup optimization, so that you distribute something that is optimized as far as possible while still providing the ability to share external dependencies.
