### ISSUE TITLE
System instance not being injected into modules anymore

### ISSUE THREAD

**Issue by rksm** [systemjs/systemjs#1276]
When creating a new System loader instance, this instance was available as global System object inside the modules it imported until systemjs@0.19.27 but breaks in systemjs@0.19.28

loading.js
```js
var newSystem = new (System.constructor)();
newSystem["import"]("./test-module.js")
  .then(m => console.log(`Is the System instance in test-module.js the same as used for importing it? ${m.observedSystem === newSystem}`))
  .catch(err => console.error(err));
```

`test-module.js`

```js
export var observedSystem = System;
```

Result: `Is the System instance in test-module.js the same as used for importing it? false`
Expected: `s the System instance in test-module.js the same as used for importing it? true`

**Comment by guybedford** [comment]
Thanks yes that's a regression, fixed in https://github.com/systemjs/systemjs/commit/e0e6102cb2ba7ff5db4af68ba532b41908e14c9d.

**Comment by rksm** [comment]
👍
