### ISSUE TITLE
Question: synchronous System.locate, and counting on System._loader.loads at runtime

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1277]
1. After a module has been loaded, is there any way to get the address of a module in a synchronous fashion? It seems like the answer might be no (since SystemJS.locate returns a promise), but thought I'd check.

2. Since I really need to get the address of a module synchronously, I've discovered that when a module is being instantiated (i.e., the function passed to `System.register()` is called but not yet the execute function) that SystemJS._loader.loads contains the load object for the module, complete with its address. How bad of an assumption is it for me to depend on that behavior?

3. If 2) isn't a bad assumption already, I'd like to take it even a step further. It seems that during the instantiation of a module that one can find its address without even searching all the way through `SystemJS._loader.loads`. Instead, it seems that the first element in the array is always the load for the module. In other words, you don't have to find the correct load because `SystemJS._loader.loads[0]` is what you're looking for. How dirty is it to depend on that behavior, and can I count on it staying that way?

Explanation:
I just enhanced the Webpack plugin, [webpack-system-register](https://github.com/CanopyTax/webpack-system-register), to allow for dynamic, runtime computation of webpack's `output.publicPath`. The publicPath is set at runtime based on the URL address of the module that has been bundled with webpack/webpack-system-register.

In the process of building that, I realized that I really needed to have the address for the current Module in a synchronous fashion, since webpack expects the value synchronously. See [documentation](https://github.com/CanopyTax/webpack-system-register#configuration-options) and [code snippet](https://github.com/CanopyTax/webpack-system-register/blob/master/src/webpack-system-register.js#L150-L159) for further clarification.

**Comment by rksm** [comment]
I'm interested in the answers as well. Just wanted to add that a `System.trace = true` will populate `System.loads` on subsequent imports. In there you find the entries being loaded, complete with address and all.

**Comment by guybedford** [comment]
`System.normalizeSync` will give you the normalized path to a module. The only thing necessary to get from that output to a file system path is to do `split('!')[0]` in case it is a plugin. Let me know if that can work for you?

**Comment by guybedford** [comment]
Also `__moduleName` is this same value.

**Comment by joeldenning** [comment]
`System.normalizeSync('...').split('!')[0]` is not the same as `System.locate('...').then(url => ...)` in the case where the SystemJS plugin being used has a `locate` hook.

In what javascript scope is the `__moduleName` variable defined? I just checked in my project and `__moduleName` does not appear to be available when my module is eval'ed?

**Comment by guybedford** [comment]
The plugin locate hook is on the deprecation path in future... is there somewhere where you need this? `__moduleName` is only defined for ES modules. CommonJS has `module.id` and AMD has `require(['module'], function(module) { module.uri })`.

**Comment by joeldenning** [comment]
@rksm thanks for the tip with System.trace. It seems like I can get the correct object out of `System.loads` without System.trace being turned on, though

**Comment by joeldenning** [comment]
We're using the locate hook inside of the [sofe](https://github.com/CanopyTax/sofe/blob/master/src/sofe.js#L53) plugin. Is the locate hook being deprecated in favor of [Loader.prototype.resolve](https://whatwg.github.io/loader/#loader-load-resolve)? What would our migration path off of the locate hook look like? Maybe just switching to the `normalize` hook?

**Comment by guybedford** [comment]
@joeldenning the reason for deprecation is exactly the same reason you needed to do something like - https://github.com/CanopyTax/sofe/blob/master/src/sofe.js#L18. It should be possible to move all the logic you have in your custom locate into that custom normalize hook, and then __moduleName etc should give what you need too? Let me know if that might work?

Yes the new spec doesn't separate normalize and locate, and just has a single resolve. I'm not sure we want to open up the resolve hook at the modular plugin level though, there's some complexity there once you introduce resolver plugins, but it may be a possibility in due course.

**Comment by joeldenning** [comment]
Yeah that should work -- I created some issues to track the migration off of locate. Two more questions, though:

1. You mentioned that __moduleName `(function(__moduleName){System.register(.....)("http://localhost:8080/my-module.js")` is only defined for ES modules. Why is that the case? Why are `System.register` modules not also given the __moduleName? Maybe related to https://github.com/systemjs/systemjs/issues/340?

2. Does System.normalizeSync only work if the asynchronous System.normalize has already been called at least once? I'm guessing it throws an error if you try to `normalizeSync` before `normalize`?

**Comment by guybedford** [comment]
Sure no problem - 

1. __moduleName will be converted into a context argument in System.register when transpiling. This should be working in all transpilers today (Babel 6, Traceur, TypeScript), but if it isn't working just let me know.
2. System.normalizeSync is a separate function to System.normalize with the async parts removed (which is just conditional loading actually, and dynamic package configuration loading). You can hook it separately to support it as well.

**Comment by joeldenning** [comment]
Ah I see. I think for 1) I am pretty far off of the beaten path with my webpack-system-register plugin -- it's not a proper compiler but instead just wraps a webpack bundle in a System.register. That probably explains why I don't have the `__moduleName` available either as a variable in scope or as a property on the context. Thanks for your help on this.

**Comment by guybedford** [comment]
Sure, just let me know if you want to discuss further at all. I'm trying to be more available on Gitter these days. The __moduleName is available via - `System.register('x', [], function(export, context) { var __moduleName = context.id; })`.

**Comment by joeldenning** [comment]
Oh, that makes sense. I didn't know that there was even a second argument passed to System.register, I thought you were talking about the `this` context instead of a function argument. That will work even better for me than System.normalizeSync, once we've migrated off of the locate hook. Thanks again

**Comment by blittle** [comment]
@guybedford it looks like `normalize` currently isn't a hook (https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md), but rather monkey-patched https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md

Are there plans to make it a hook? In other words, it looks like currently I have to 
```javascript
  var systemNormalize = System.normalize;
  // override the normalization function
  System.normalize = function() { ... }
```
instead of:
```javascript
  export function normalize() { ... }
```

**Comment by guybedford** [comment]
@blittle the normalize hook is not currently exposed to plugins, rather you do need to extend the loader for this.

**Comment by blittle** [comment]
@guybedford is there a reason why it isn't? Especially if the `locate` hook is getting deprecated? Will the normalize hook eventually be exposed to plugins?

**Comment by guybedford** [comment]
There need to be some invariants in the normalization algorithm to ensure consistency when bundling for example, so opening this up to have these constraints lost is not something to be done without good reason.
