### ISSUE TITLE
trying to switch from commonjs to system, everything blows up...

### ISSUE THREAD

**Issue by born2net** [systemjs/systemjs#1278]
I am not sure if this is a system.js bug, jspm bug, or a bug in my brain, but all is working great when I was on commonjs in my jspm.config.js, now I am trying to make a switch over to system so I can use hot-reload, but everything blows up.

this is the change I did:

```
SystemJS.config({
  transpiler: "plugin-typescript",
  typescriptOptions: {
    "module": "system",
    "emitDecoratorMetadata": true,
    "tsconfig": true,
    "sourceMap": true
  },
  packages: {
    "StudioDashboard": {
      "main": "StudioDashboard.js"
    },
   ....
```

to use module system

and before with commonjs all worked, but now I get:

![err](https://cloud.githubusercontent.com/assets/5090936/15437463/0ad109e8-1e7c-11e6-89ec-f13953e2af26.PNG)

I can't even begin to think where to debug this...

regards

Sean

**Comment by guybedford** [comment]
Let's track in the jspm issue.
