### ISSUE TITLE
Assertion failed: loading or loaded

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1280]
I'm getting this error when hot reloading (using https://github.com/capaj/systemjs-hot-reloader).

It currently happens on a css file, I'm also using css modules.

Could you provide a few pointers for debugging this? Using 0.19.26

**Comment by guybedford** [comment]
The best would be to share a test case, as this is a low-level bug in the loader code.

**Comment by guybedford** [comment]
This happens when failed loads happen along side loading loads. I've removed this assertion for the next release.
