### ISSUE TITLE
[babel-template]  Cannot convert object to primitive value

### ISSUE THREAD

**Issue by micaelmbagira** [systemjs/systemjs#1281]
When using jspm with es6 and angular2 class annotations, I have the following error
>  hello.js: Cannot convert object to primitive value
  	    at Array.enter (webapp/jspm_packages/npm/babel-template@6.9.0/lib/index.js:123:13)
...

My code is 
```js
import {Component} from '@angular/core';

@Component({
  selector: 'App',
  template: '<h1>{{ hello }}</h1>'
})
export class Hello {
  constructor() {
    this.hello = 'Hello World!';
  }
}
```
Though, when I use a different syntax, I don't have the error anymore
```js
import {Component} from '@angular/core';

export const Hello =
  Component({
    selector: 'App',
    template: '<h1>{{ hello }}</h1>'
  })
  .Class({
    constructor() {
      this.hello = 'Hello World!';
    }
  });
```

I tried/compared with Webpack and it works with Webpack. 
I think the reason is that `Symbol()` type https://github.com/babel/babel/blob/master/packages/babel-template/src/index.js#L11 is converted into type `Object` in SystemJS...

**Comment by guybedford** [comment]
Perhaps the environment needs to have a `Symbol` polyfill present? We don't automatically include global polyfills in SystemJS's Babel plugin.

**Comment by micaelmbagira** [comment]
Actually it does, it has `core-js` which contains a polyfill for `Symbol`.

**Comment by micaelmbagira** [comment]
Fixed by adding `babel-plugin-transform-es2015-typeof-symbol`.
