### ISSUE TITLE
`this` in modules should be undefined

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1282]
Currently it is the global unfortunately. While likely very rarely relied on, changing this is perhaps still worth doing as a breaking change for 0.20 to be sure.

**Comment by npbenjohnson** [comment]
Is this in the native module spec? What is best practice for making node/browser/webworker compatible modules when "this" isn't the global?

**Comment by guybedford** [comment]
Yes this is in the spec. System.global is actually a spec currently, otherwise traditional techniques.

**Comment by guybedford** [comment]
Implemented in [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1).
