### ISSUE TITLE
Script loading failing with scriptLoad: true

### ISSUE THREAD

**Issue by rendmath** [systemjs/systemjs#1283]
I have a very simple AngularJS application using the ngRoute module.

Here is the system.config.js file:
```
System.config({
    defaultJSExtensions: true,
    map: {
        'angular': 'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular.min.js',
        'angular-route': 'https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-route.min.js',
    },
    meta: {
        'angular': { format: 'global', exports: 'angular' },
        'angular-route': { format: 'global', deps: ['angular'] },
        //'*.js': { scriptLoad: true }
    }
});

System.import('app').then(function () {
    angular.bootstrap(document, ['app']);
});
```

Here is the app.ts file:
```
import angular from 'angular';
import 'angular-route';

angular.module('app', ['ngRoute']);
```

But as soon as I uncomment the `scriptLoad` line, the application fails with this error: 
`Uncaught (in promise) Error: Error: https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.5/angular-route.min.js did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.`

It happens in all tested browsers (IE, Chrome and Firefox).

Unfortunately, I have not been able to make Visual Studio TypeScript debugging work without scriptLoad.

Edit: It also fails with the production-csp version.
Edit: I'm using SystemJS v0.19.28.

**Comment by guybedford** [comment]
This is correct, `scriptLoad` can not be used to load ES modules.

**Comment by rendmath** [comment]
It would make a worthy addition to the documentation.

Is it the intended behavior ?

**Comment by guybedford** [comment]
Yes this is certainly something to document.
