### ISSUE TITLE
Different modules instance when mixing System.register and require

### ISSUE THREAD

**Issue by djflex68** [systemjs/systemjs#1284]
Hello,

I've a question and I'm not sure this scenario is currently handled in SystemJS.
We wrote a big application based on RequireJS for 3 years. Now we are migrating to SystemJS.
Some parts of our code are based on the fact that RequireJS "require" caches module instances that have already been loaded. This way each time you call require, you get the same object instance. It seems this is not the behaviour I observe when mixing System.register and SystemJS legacy 'require'  using

`window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;`

If you perform require([dep1]), and later System.register([dep1], ....)  you get 2 different instances. It seems that both methods aren't sharing a common cache, am I wrong ? 
Is it possible to modify this behaviour ? 

Thanks

**Comment by guybedford** [comment]
The instances are shared in the registry, which is keyed by full module URLs (baseURL + module name). If something is running twice, it would need to correspond to two different normalized URLs. You can test normalization of System.register('x')` by doing `System.decanonicalize('x')` to see what it will be stored as in the registry. Also you can test normalization of `System.import('x')` by running `System.normalizeSync('x', 'http://parent/module/name.js')` or `System.normalize('x').then(console.log.bind(console))`. Matching those up is what is needed for bundling to work properly.

**Comment by djflex68** [comment]
I think my issue is linked to this line :
```
// return the defined module object
return loader.newModule(entry.declarative ? entry.module.exports : entry.esModule); 
```

In my case it seems that both entry.module.exports and entry.esModule are defined. but since  entry.declarative is false, entry.esModule is taken which in my case is not the expected instance. 
I read somewhere that is could be needed to specify exports.__esModule = true in AMD modules. Am I right ?

**Comment by guybedford** [comment]
This is the interop system between AMD / CommonJS and ES modules. It sounds like you're getting the namespace when you want the actual direct module reference from the AMD module then? If so it depends how you are importing the namespace in the first place.

For example if you are doing `import * as m from 'amd-module'` then you should change this to `import m from 'amd-module'`.

**Comment by djflex68** [comment]
Many thanks ! I think this corrects my problem :)
