### ISSUE TITLE
cannot seem to duplicate typescript transpilation

### ISSUE THREAD

**Issue by ciel** [systemjs/systemjs#1285]
I'm trying to transpile typescript and am having a difficult time setting up two different packages to do it. I've got one that works, and it is defined like this;

```
System.config({
    transpiler: "typescript",
    defaultJSExtensions: true,
    map: {
        // ... other maps ... //
    },
    meta: {
        // .. other metas .. //
        'js/*': {
            deps: ['jquery', 'json', 'typescript', 'angular']
        }
    },
    paths: {
        // .. other packages .. //
        'js/*'          : 'js/*.ts',
    },
    packages: {
        'js':{
            'defaultExtension': 'ts'
        }
    }
});

Promise.all([
    // ... other imports ... //
    System.import('js/main')
]).then(function () {
    $('.spinner-container').fadeOut(800); angular.bootstrap(document, ['ehrpg']);
});
```

It works well, so I tried to add another for a different set of libraries;

```
System.config({
    transpiler: "typescript",
    defaultJSExtensions: true,
    map: {
        // ... other maps ... //
    },
    meta: {
        // .. other metas .. //
        'js/*': {
            deps: ['jquery', 'json', 'typescript', 'angular']
        },
        'lib/*': {
            deps: ['jquery', 'json', 'typescript', 'angular']
        }
    },
    paths: {
        // .. other packages .. //
        'js/*'          : 'js/*.ts',
        'lib/*'         : 'lib/*.ts'
    },
    packages: {
        'js':{
            'defaultExtension': 'ts'
        },
        'lib':{
            'defaultExtension': 'ts'
        }
    }
});

Promise.all([
    // ... other imports ... //
    System.import('js/main')
]).then(function () {
    $('.spinner-container').fadeOut(800); angular.bootstrap(document, ['ehrpg']);
});
```

but this one refuses to work - it keeps trying to append `.js` to the end. Is there some reason for this?

**Comment by guybedford** [comment]
You shouldn't be using wildcard paths configuration to add extensions. I'd suggest removing the paths entries.

**Comment by ciel** [comment]
Then how am I supposed to map groups and packages together? I need to make sure that certain imports start in a specific base folder.

**Comment by guybedford** [comment]
If you need paths for aliasing then use:

```javascript
paths: {
        // .. other packages .. //
        'js/'          : 'js/',
        'lib/'         : 'lib/'
    },
```

but paths shouldn't be used to add extensions.

**Comment by ciel** [comment]
Hrnm, I think I get it. . . but that gives me the error that `lib/ is not defined` in things that are trying to call it.

**Comment by ciel** [comment]
Oh, I understand. The error is because it works and there's a flaw in my typescript. Thank you! I think I understand now!

**Comment by guybedford** [comment]
Sure, just let me know if you need more help here.

**Comment by ciel** [comment]
Then what are you supposed to use wildcards for? I'm confused on that.

**Comment by guybedford** [comment]
They're a vestige. They're being deprecated.
