### ISSUE TITLE
Packages path not relative to baseURL in meta section

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1287]
The SystemJS docs imply that package names are normalized relative to the baseURL, ie `[baseUrl]/[package name]`.  However, when I configure SystemJS like this

```
var config = {
    packages: {
        //but it works with /v0
        '/': {
            defaultExtension: 'js',
            map: { },
            meta: {
                'vendor/util1.global.js': { format: 'global' }
            }
        }
    },
    baseURL: '/v0'
};
```

`v0/vendor/util1.global.js` is NOT parsed as a global script, potentially causing errors if it's a UMD build.

I have this reproduced here: https://github.com/arackaf/system-js-configuration-sandbox 

As the code comment implies, if I make the package name `/[baseURL]` then it works fine.  

Should I just do that, or is this a bug?

**Comment by guybedford** [comment]
The package name `/` is a URL which means absolute base. When normalized relative to the baseURL, `new URL('/', 'http://site.com/v0')` normalizes to `'http://site.com/` which is then stored as the package URL.

The meta thus needs to include the `v0` part, unless you alter the package name to include the `/v0`.

Alternatively (and yes somewhat confusingly) you can make the package name `''` the empty string, and that then normalizes as `new URL('', 'http://site.com/v0')` which makes the package name `http://site.com/v0` giving also what you want. Of course explicitly writing `/v0` is probably best though here I think for clarity. I've tried to be as consistent as is possible, but that doesn't always mean it is completely intuitive unfortunately.

**Comment by arackaf** [comment]
Empty string works perfectly, and is absolutely what I want.  `/v0` can actually change based on environment—and eventually, based on ES6 browser support—so a single `''` with perhaps a comment to clarify seems ideal.

Thank you so much for replying.

**Comment by guybedford** [comment]
👍
