### ISSUE TITLE
Plugins not mapped correctly from System.import when mapped in a package

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1288]
Configuration

```
var config = {
    packages: {
        //but it works with /v0
        '/v0/': {
            defaultExtension: 'js',
            map: {
                text: 'assets/text'
            },
            meta: {
                'vendor/util1.global.js': { format: 'global' }
            }
        }
    },
    baseURL: '/v0/'
};
```

This fails

```
Promise.all([
    System.import('contacts/contacts'),
    System.import('contacts/contacts.htm!text')
]).then(([obj]) => checkit(() => obj.name == 'contacts', 'contacts loaded'));
```

It's looking for text.js at `http://localhost:54294/v0/text.js`

However, if I load a module which itself loads the same `contacts.htm!text`, then it works fine; it correctly resolves text.js to `http://localhost:54294/v0/assets/text.js`

This is reproduced here: https://github.com/arackaf/system-js-configuration-sandbox

**Comment by guybedford** [comment]
In this case, the scope of the text plugin is the parent context of the page itself. By default, for a top-level System.import statement, it will be normalized to an `undefined` parent.

That is `System.import('text')` will run the normalization of `System.normalize('text', undefined)`. In order to get the normalization of a package you need to do `import 'text'` from within a package parent, which would be equivalent to a `System.normalize('text', 'http://site.com/v0/package.js')` then using the contextual map configuration.

Perhaps try map via meta instead:

```javascript
meta: {
  '*.htm': { plugin: 'text' }
}
```

**Comment by arackaf** [comment]
It seems like the solution is to just throw this up at the top level as well.

```
map: {
    text: 'assets/text'
},
```

Seems to work.  I don't like repeating such things, but if the normalization is expected as you describe, it seems like this is the best solution.

Thanks for replying!

**Comment by arackaf** [comment]
Actually, it seems I don't even need text specified in the package at all; only globally.  So is the best practice to just specify loader paths globally, and not in the package?

**Comment by guybedford** [comment]
You're welcome to do that, as long as you know you won't have a namespace collission (eg something simple like a folder called `text` in your app will break it from working in a package dependency).

**Comment by arackaf** [comment]
A fair point - thank you.  The upside is that such a problem would blow up pretty quickly!

**Comment by arackaf** [comment]
@guybedford Sorry to bother you again.  I just have two quick follow-up questions.

First, wrt

> You're welcome to do that, as long as you know you won't have a namespace collission (eg something simple like a folder called text in your app will break it from working in a package dependency).

I would have had that same problem before, right?  I had a map entry for my text and css plugins already, so a real `text` or `css` path would have broken things anyway, right?

Also, is there any reason I shouldn't just make *all* of these map entries global, as they were before?  I'm only going through this work because the `defaultJSExtensions` option is deprecated, and it seems the packages route is the place where a replacement exists.  I'm just trying to find the best configuration with the new format.  Right now I don't have different parts of the application using different versions of utilities, and likely never will.  Should I just have a root packages entry of '' with my default file extension, and then all my old map entries global, from before?

**Comment by guybedford** [comment]
Yes you can certainly keep all the map configs as global - that's what we do in jspm as well as you typically want to be able to `System.import` directly all top-level dependencies. It's only for dependencies of dependencies that it is important to encapsulate the map.
