### ISSUE TITLE
Discussion: depCache

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1291]
The [docs for `depCache`](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#depcache) mention HTTP/2. I think it can also be pretty useful for HTTP/1 bundles. Consider an example: let's say we use bundle arithmetic to split the code into several bundles, which means that bundles actually depend on each other, e.g.:
`page1.bundle.js` → `common.bundle.js` → `vendor.bundle.js`
If you import `page1.bundle.js` the requests will actually be made sequentially for each bundle, because there's no way to know that there's a dependency.
However if you set:
```js
{
  depCache: {
    "page1.bundle.js": ["common.bundle.js", "vendor.bundle.js"]
  }
}
```
The requests will now be made in parallel, which should improve the performance.

Makes sense?

**Comment by guybedford** [comment]
That is definitely a useful approach yes. The exact bundling workflow is left to the user to optimize, and this is certainly an option.

**Comment by asapach** [comment]
Thanks for the confirmation. I'll update the issue with some real-life benchmarks once we implement this.

**Comment by guybedford** [comment]
Is this not already supported in SystemJS?

**Comment by asapach** [comment]
I mean implement this optimization in our project. Sorry for the confusion.

**Comment by asapach** [comment]
As promised, here are the results. Network conditions between the runs were slightly different, so sorry about minor inconsistencies.

Here's the baseline:
![baseline](https://cloud.githubusercontent.com/assets/1755336/15894313/e090855c-2d8d-11e6-9548-2b47b5b3d6b4.png)

There are two entry points on the page, so I've added them to `depCache`:
```js
{
  "entry1.js":["0.bundle.js","1.bundle.js","2.bundle.js",
               "3.bundle.js","4.bundle.js","5.bundle.js","8.bundle.js"]
  "entry2.js":["0.bundle.js","1.bundle.js","10.bundle.js"]
}
```

(The entry points are in `"8.bundle.js"` and `"10.bundle.js"` respectively.)

![depcache](https://cloud.githubusercontent.com/assets/1755336/15894420/7aa9de2c-2d8e-11e6-82cb-750d83dd7165.png)

The waterfall effect is less obvious, but still present for some reason; maybe because of the way browser queues up concurrent connections when the limit is reached. Nevertheless I would recommend this as a best practice for large scale applications.

**Comment by guybedford** [comment]
The memory profile in the second case is consistent with the 6 HTTP connection limit, which looks like the test was run over HTTP/1 over HTTP/2. There would definitely be better performance over HTTP/2 though... good to know this works out ok.
