### ISSUE TITLE
Aurelia SPA using SystemJS debug IE in Visual Studio

### ISSUE THREAD

**Issue by stefan505** [systemjs/systemjs#1292]
I would like to know if there's a better way of telling the config to load all `.js` files in a given directory (and all sub-directories) as scripts? Currently I'm doing this for each `.js` file:
```
meta: {
    "app/main.js": {
      "scriptLoad": true
    },
    "app/shell.js": {
      "scriptLoad": true
    }
...
}
```
This technique enables debugging directly within in Visual Studio (which is what I want). It is a bit tedious though, since I have to keep updating the `meta` section with changes / additions to my SPA. I've also tried using `packages` instead of `meta` to no avail:
```
    packages: {
        "app": {
            meta: {
                "**/*.js": {
                    scriptLoad: true
                }
            }
        }
    }
```

I'm aware that I can do this as well:
```
meta: {
        "app/*": {                                         // "app/**/*.js" doesn't work either
            "scriptLoad": true
        }
    }
```
However the above attempts to load even `.html` files as `.js`.

**Comment by guybedford** [comment]
Try

```javascript
meta: {
  "app/*.js": {
    "scriptLoad": true
  }
}
```

`**/*` wildcard meta isn't supported though as `*` is always deep in meta.

**Comment by stefan505** [comment]
Thanks @guybedford, your suggestion works to a point. For the Aurelia component `shells`, it loads `shell.js` ViewModel (as per my sample files above) correctly, but it attempts to load the `shell.html` View also as JS, since I get this error:
```
JavaScript critical error at line 1, column 1 in http://localhost:52058/app/shell.html\n\nSCRIPT1002: Syntax error
```

Do I need any other config?

**Comment by guybedford** [comment]
The above meta should certainly not result in an HTML file being loaded with a script tag.

**Comment by stefan505** [comment]
If I put the `meta` tag in like this, it errors:

```
meta: {
      "app/*.js": {
          "scriptLoad": true
      },
      "app/*.html": {
          "scriptLoad": false
      }
  },
```
If I wrap it inside a `packages` element, it works:
```
  packages: {
      "app": {
          meta: {
              "*.js": {
                  scriptLoad: true
              },
              "*.html": {
                  scriptLoad: false
              }
          }
      }
  },
```

**Comment by guybedford** [comment]
Are you using `defaultJSExtensions: true` here?

**Comment by stefan505** [comment]
Yes I am:
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: false,
...
```

**Comment by guybedford** [comment]
I'm still not quite sure why it would be breaking though as this case definitely seems to work out. Can you log the value of `Object.keys(System.meta)` in the case that isn't working? Also are you running the latest version of SystemJS here?

**Comment by stefan505** [comment]
The `Object.keys(System.meta)` is output as follows for the scenario that breaks:
```
[http://localhost:52058/app/*.js,http://localhost:52058/app/*.html.js]
    __proto__: []
    length: 2
    [0]: "http://localhost:52058/app/*.js"
    [1]: "http://localhost:52058/app/*.html.js"
```
The `jspm` version is:
```
0.16.35
Running against local jspm install.
```
Using `SystemJS v0.19.29`.

**Comment by guybedford** [comment]
Hmm, firstly the html file should not be getting a `scriptLoad` metadata then. But also the meta value is supposed to read `app/*.html` not `app/*.html.js`.

On a fresh SystemJS, if I run `System.config({ defaultJSExtensions: true, meta: { 'app/*.html': { asdf: 'asdf' } } })` then `Object.keys(System.meta)` contains a value for `app/*.html` not `app/*.html.js` so it would be interesting to know the configuration difference that might be causing that.

**Comment by guybedford** [comment]
Actually no, sorry `*.html` does normalize into `*.html.js` metadata because of defaultJSExtensions. The reason being that you could have written `meta: { 'x.asdf': { scriptLoad: true }  }` to mean `x.asdf.js` because of defaultJSExtensions.

You can try setting directly `System.meta['http://localhost:52058/app/*.html'] = { scriptLoad: false }` here too. Although you shouldn't need to have this explicit opt-out still as the opt-in shouldn't be catching it to begin with.

**Comment by stefan505** [comment]
Ok, @guybedford , I am happy to leave my config as it is now. Thanks for the assistance!
