### ISSUE TITLE
I'm using jspm with systemjs and gulp. when I'm bundling it was seaching for source map files with are in tranformed javascript files. but those source map files cannot find in the dist folder

### ISSUE THREAD

**Issue by ashanvabs** [systemjs/systemjs#1293]
its generating below error
`[15:52:39] Finished 'build-system' after 1.95 s
[15:52:39] Finished 'build' after 2 s
[15:52:39] Starting 'bundle'...
[15:52:39] 'bundle' errored after 394 ms
[15:52:39] Error on fetch for animal.js at file:///D:/vetserve/Vetserve.Web/src/
Vetserve.Web.Appts/dist/animal.js
        Error: ENOENT: no such file or directory, open 'D:\vetserve\Vetserve.Web
\src\Vetserve.Web.Appts\dist\animal.js.map'
    at Error (native)`

//dist/animal.js 

`define(["require", "exports"], function (require, exports) {
    "use strict";
    var Animal = (function () {
        function Animal() {
        }
        return Animal;
    }());
    exports.Animal = Animal;
});
//# sourceMappingURL=animal.js.map
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYW5pbWFsLmpzIiwic291cmNlUm9vdCI6Ii9zcmMiLCJzb3VyY2VzIjpbImFuaW1hbC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOztJQUFBO1FBQUE7UUFPQSxDQUFDO1FBQUQsYUFBQztJQUFELENBQUMsQUFQRCxJQU9DO0lBUFksY0FBTSxTQU9sQixDQUFBIn0=
`

**Comment by asapach** [comment]
Try this gulp plugin: https://www.npmjs.com/package/gulp-relative-sourcemaps-source

**Comment by ashanvabs** [comment]
thanks @asapach .The problem is in my process the are no any js.map files created in dist folder or outside.
