### ISSUE TITLE
Reload File after change it triggers 'did not call System.register or AMD...'

### ISSUE THREAD

**Issue by acostaf** [systemjs/systemjs#1294]
Hi Team

I am working with angular2 / typescript / Systemjs on Visual Studio and every time I change a file I must stop the browser delete all the .js files a recreate them again because the system throws **'did not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support'**

I am using  "systemjs": "^0.19.29"

System Config

	(function (global) {

		// map tells the System loader where to look for things
		var map = {
			'app': '/app', // 'dist',        
			'@angular': '/node_modules/@angular'
		};

		// packages tells the System loader how to load when no filename and/or no extension
		var packages = {
			'app': { main: 'main.js', defaultExtension: 'js' },
			'@angular/common': { main: 'common.umd.js', defaultExtension: 'js' },
			'@angular/core': { main: 'core.umd.js', defaultExtension: 'js' },
			'@angular/compiler': { main: 'compiler.umd.js', defaultExtension: 'js' },
			'@angular/http': { main: 'http.umd.js', defaultExtension: 'js' },
			'@angular/platform-browser': { main: 'platform-browser.umd.js', defaultExtension: 'js' },
			'@angular/platform-browser-dynamic': { main: 'platform-browser-dynamic.umd.js', defaultExtension: 'js' },
			'@angular/router': { main: 'router.umd.js', defaultExtension: 'js' },
			'@angular/router-deprecated': { main: 'router-deprecated.umd.js', defaultExtension: 'js' }
		};

		var config = {
			//globalEvaluationScope: false,
			meta: { 'app/*.js': { scriptLoad: true } },
			paths: {
				"rxjs/*": "/node_modules/rxjs/bundles/Rx.umd.min.js"
			},
			map: map,
			packages: packages
		};

		System.config(config);

	})(this);
`
`

**Comment by guybedford** [comment]
Can you share the name of the file that is giving this error, and the associated source code?

What is creating the js files in the first place that you have to delete them?

**Comment by acostaf** [comment]
Hi @guybedford file works fine every time (after having to delete and recreate it), issue happens when you change a simple thing on the file and save that triggers the TradeAdmin.Component.ts to be converted into TradeAdmin.Component.js and pressing f5 on the browser to reload the file then systemjs tells me **'did not call System.register or AMD define...'**

**Comment by guybedford** [comment]
If it was compiled correctly, the compiled file should start with `System.register(...` and it would never give the above error in that case. It would help to copy the contents of the network tab for that change file to see if it includes that or not.
