### ISSUE TITLE
System-csp-production version leaves window.define defined

### ISSUE THREAD

**Issue by mikeyoon** [systemjs/systemjs#1296]
Not sure if it's a bug or not, but the `system-csp-production.js` leaves `window.define` set, while `system.js` does not. Ideally, I'd like the csp version to not have define set, but it isn't hard to undefine it as well if it's there on purpose.

**Comment by guybedford** [comment]
Yes this is by design - System CSP production uses script injection to load all modules, so that loading AMD is only supported if the global define is always present.

We could make this a configuration option, but unsetting the global define is a good approach for working with it.

Is the global define interfering with your code here?

**Comment by mikeyoon** [comment]
Makes sense. We have a sort of less common usecase. There's a part of our app that loads user generated HTML, like plunkr or jsbin. Some HTML content may include external libraries like D3 or whatever, which assume they're in an AMD environment when they detect `window.define`, and fail to load correctly as a result.

A config option would bit a little cleaner than undefining, but not a huge win. Not sure if a config option could easily support cases where someone would prefer async loading of a deps, which I guess would need `define` until the entry point is running, instead of loading all bundles in script tags before the entry point (we do the latter).

**Comment by guybedford** [comment]
The alternative is to make it a breaking change in the next major not to set `window.define` at all, and rather document that it should be set if needing AMD support for SystemCSP. Perhaps that may be a good route forward.

**Comment by guybedford** [comment]
Marking this for the next major.

**Comment by guybedford** [comment]
SystemCSP is being removed as a separate build in 0.20. The define leak issue has been fixed for scriptLoad scenarios by not setting the global define, and assuming it is set manually for the environment. See [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1) for more info.
