### ISSUE TITLE
how to call a function that is loaded from the index file?

### ISSUE THREAD

**Issue by maik10s** [systemjs/systemjs#1297]
I have a function called loadData(), and I need call this from the index.

index.html
`System.import('app').catch(function(err){ console.error(err); });
 loadData("123333");`

this is the error.
Uncaught ReferenceError: loadData is not defined

**Comment by joeldenning** [comment]
Hey @maik10s, could you give more information about the `loadData` function? Is it exported as part of `app`? If so, maybe try the following:

```js
System
.import('app')
.then(function(app) { app.loadData("123333") })
.catch(function(err) { console.error(err): });
```
```

**Comment by maik10s** [comment]
Hey @joeldenning, thank you!!!
