### ISSUE TITLE
Issue importing a global module using an Adapter Module

### ISSUE THREAD

**Issue by SnareChops** [systemjs/systemjs#1299]
I am having an issue importing a global module (`moment`) from `window` into my application. To isolate this scenario I have recreated the issue in a test repo [here](https://github.com/SnareChops/system-import-moment-test) for replication (I have included all compiled code and dependencies for simplicity of testing, just run `index.html` in a browser)

The issue is that the end result of `import * as moment from 'moment';` (typescript) becomes an object instead of a function.

For example `typeof window.moment === 'function'` but `typeof moment === 'object'` once imported. You'd have to see it in the project to see what is going on, but what I am trying to accomplish is to take `window.moment` and import it into my project so that I can use it using the ES6 imports. I have created an adapter as recommended in the systemjs-builder project, which appears to be correct.

Do you know what might be going on in the module loader that might be changing this import?

**Comment by guybedford** [comment]
`import * as x` will always be a `Module` object according to the module specification. Use `import moment from 'moment'` rather here.

**Comment by SnareChops** [comment]
Perfect, that works.
