### ISSUE TITLE
Meta entries do not appear to be get appropriate defaultExtension from package

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1300]
This configuration

```
var config = {
    packages: {
        '': {
            defaultExtension: 'js'
        }
    },
    baseURL: '/v0/',
    map: {
        text: 'assets/text',
        global2: 'vendor/global2',
        global3: 'vendor/global3'
    },
    meta: {
        'vendor/global2.js': { deps: ['global3'] },
        'vendor/util1.global.js': { format: 'global' }
    }
};
```

Works perfectly.  If I `System.import('global2')` then `global2` AND `global3` come down perfectly.  Unfortunately, if I do this

```
meta: {
    'global2': { deps: ['global3'] },
    'vendor/util1.global.js': { format: 'global' }
}
```

then I get a 404, where, since SystemJS is looking for `v0/vendor/global2 // <--- no .js`

It seems the default js extension from the default, catch-all package is not carrying through.

Repository is here if you want to see https://github.com/arackaf/system-js-configuration-sandbox

**Comment by guybedford** [comment]
The reasoning for this is that meta configuration is allowed to provide extension information.

For example:

```javascript
{
  packages: {
    '': {
      defaultExtension: 'js'
    }
  },
  meta: {
    '*.css': { loader: 'css' }
  }
```

Would otherwise not allow `System.import('file.css')`. We allow the meta configuration to define extensions (making extensions necessary within meta configuration), in order to make these loader cases easier.

**Comment by arackaf** [comment]
Makes sense - thank you!
