### ISSUE TITLE
Map and meta not working together well from within the same package

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1301]
Similar to the case I just opened.  Consider this configuration

```
var config = {
    packages: {
        '': {
            defaultExtension: 'js',
            map: {
                global2: 'vendor/global2',
                global3: 'vendor/global3'
            },
            meta: {
                'vendor/global2.js': { deps: ['global3'] },
                'vendor/util1.global.js': { format: 'global' }
            }
        }
    },
    baseURL: '/v0/',
    map: {
        text: 'assets/text'
    }
};
```

Running `System.import('global2')` causes a 404 on `v0/global2.js`.  It seems the global2 map is ignored when inside a package like this. 

Repo is here.  Last commit is for this case.  Prior commit has the config from the previous case I opened here.

https://github.com/arackaf/system-js-configuration-sandbox

**Comment by guybedford** [comment]
The contextual import would be `System.import('global2', __moduleName)`.

There is supposed to be a spec for this where it will be a special contextual import like `import('global2')` which is already scoped, but no one has gotten around to putting that spec together yet.

**Comment by arackaf** [comment]
@guybedford  thanks - I think I understand.  So it seems this

```
var config = {
    packages: {
        '': {
            defaultExtension: 'js',
            map: {
                global3: 'vendor/global3'
            },
            meta: {
                'vendor/global2.js': { deps: ['global3'] },
                'vendor/util1.global.js': { format: 'global' }
            }
        }
    },
    baseURL: '/v0/',
    map: {
        text: 'assets/text'
    }
};
```

Works fine.  A call to `System.import('vendor/global2.js').then(() => {` does load global 3 implicitly.  

And then this

```
var config = {
    packages: {
        '': {
            defaultExtension: 'js',
            map: {
                global3: 'vendor/global3'
            },
            meta: {
                'vendor/util1.global.js': { format: 'global' }
            }
        }
    },
    baseURL: '/v0/',
    map: {
        text: 'assets/text'
    }
};
```

also causes global3 to load from the same `System.import('vendor/global2.js').then(() => {` assuming I add `require('global3')` to `global2.js`.  I assume the reason `System.import('global2')` doesn't work is because multiple packages can define the same value in their respective `map` sections, and a top-level System.import would have no way to know which you want.  Is that about right?

So the use case for package-level map entries would be for special handling of dependencies specific to *that* package?  ... Just as your docs show 1 package depending on a specific version of jQuery.

Is that all about right?

**Comment by guybedford** [comment]
Yes exactly, package external map (`map: { a: 'b' }`) is for handling multi-version namespaces, while package internal map is just for convenience mappings (`map: { 'app': '.' }` and `map: { './x': './y' }`.

Ideally `System.import('x', __moduleName)` would be syntactically much sweeter, as deferred dynamic loading should be treated as first-class in all this, and it will be in future.
