### ISSUE TITLE
disable dependencies for plain javascript files

### ISSUE THREAD

**Issue by macolo** [systemjs/systemjs#1302]
I would like to asynchronously load a plain javascript file I install from bower with system.js.

Example: `/static/vendor/gsap/src/minified/TimelineMax.min.js`

```
 System.config({
            defaultJSExtensions: "js",
            baseURL: '/static/',
            paths: {
                "jquery": 'js/libs/jquery.min.js',
                "TimelineMax": 'vendor/gsap/src/minified/TimelineMax.min.js',

            }
        });
```

Then I would like to load it with `System.import('TimelineMax')` - however this results in system.js loading many other "dependencies" from the wrong place:

```
System.import('TimelineMax')
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
system.src.js:5112 GET http://0.0.0.0:8042/static/TweenLite.js 404 http://0.0.0.0:8042/static/TweenLite.js(…)
```

Why does system.js want to load TweenLite.js - and is there a way to deactivate these unnessesary dependencies?

**Comment by guybedford** [comment]
The way to alter the way SystemJS detects the dependencies is to alter the module format the file is detected as.

This can be done with eg:

```javascript
meta: {
  'TimelineMax': { format: 'amd' }
}
```

if it supports `amd`, otherwise `global`.

**Comment by macolo** [comment]
Many thanks @guybedford - this is awesome!

For the history, I am including a link to the docs: https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#exports

Maybe this example use case could be added to the system.js documentation?

I've added this vital piece of info to http://blog.typodrive.com/2016/05/25/beyond-async-defer-javascript-dependency-handling-with-system-js/

**Comment by guybedford** [comment]
Glad to hear that. Sure a docs update will be coming, will bear this in mind.
