### ISSUE TITLE
3+ second load time on a 96kb jspm bundled app... <0.1 second on desktop

### ISSUE THREAD

**Issue by ohjames** [systemjs/systemjs#1304]
Not sure if systemjs is having issues on mobile or if the CPU on a Samsung Galaxy S6 is just too slow?

Our tests show the time between System.import and the module being run is usually around 3-3.5 seconds.

**Comment by guybedford** [comment]
What promise library are you using here? Have you tried using Bluebird?

**Comment by ohjames** [comment]
Yep this is using Bluebird, our `app-build.js` is actually bluebird concatenated with a jspm bundle, that way we can be absolutely sure the right promise implementation is being used. I forgot to mention it but the browser being used was Chrome. If we remove bluebird from the equation then the load is slightly slower (I guess the performance boost Bluebird brings makes up for the larger bundle).

**Comment by guybedford** [comment]
It sounds like this is just natural performance issues then, which leaves:

1. Reduce the size of the bundle
2. Create static bundles of module subtrees to reduce the number of System.register / System.registerDynamic statements in the bundle
3. Work on the performance fast paths in SystemJS itself

(3) is a priority over the coming couple of months, but obviously isn't a quick fix like the others.

**Comment by ohjames** [comment]
By natural performance issues do you mean that 96kb is too big a bundle for a mobile browser to deal with? On a previous project we had a bundle built with webpack that was >300kb and it loaded a fair bit faster than that. Sorry if I misinterpreted what you mean by that. Onto the other questions:

1. Most of our bundle is Aurelia and we've cut absolutely everything out we aren't using.
2. We only have one System.registerDynamic and it's for our `config.js`
3. Cool!

**Comment by guybedford** [comment]
Natural performance issues being it's certainly a weakness in SystemJS. I'm optimistic we can make significant performance gains though and it's top priority for my next cycle (finally!).

**Comment by ohjames** [comment]
Thanks for getting back to me so quickly! I notice there aren't any other issues in github about the performance so maybe we can keep this one open to track it?

It might be worth putting a small note in the docs about the load times on mobile, for us it's an extremely significant factor. We love absolutely everything about jspm/system.js but this one thing prevents us from being able to use it, I guess we'll port to webpack for now, but as soon as this issue is sorted out I'm sure jspm and system.js will become part of our common tooling again.

**Comment by guybedford** [comment]
@ohjames I've created a new SystemJS build in the current release called `system.perf.js`. If you're still able to test this out in your example app, and run the `System.perfSummary()`, it would be interesting to see the results here. There are some small performance improvements in this coming release (~30% normalization speedup in the benchmark).

**Comment by ohjames** [comment]
I'll need a 1500% speedup in this case for systemjs to be comparable with my webpack build but I'll try it out and let you know here.

**Comment by guybedford** [comment]
Note that the comparable build to webpack (with static linking) would be a static build through the builder instead of a bundle.

**Comment by ohjames** [comment]
So `jspm bundle` builds are much slower than another type of build I'm not familiar with? You should let the Aurelia guys know so they can update their build system to use this.

**Comment by ohjames** [comment]
When you `gulp bundle` with Aurelia on even the teensiest project you get these large delays on mobile. Would be such a shame if people get turned off jspm and systemjs due to this.

**Comment by m-j** [comment]
@guybedford: Could you further explain difference between static build through builder and bundle (or provide a link)? I have feeling that I may be making some mistake (I'm getting performance issues as well).

**Comment by lgdexter** [comment]
`jspm bundle-sfx` works wonders for me. The scripts are insanely fast and don't suffer from any of the performance issues that are plaguing `System.import`.

**Comment by MaximBalaganskiy** [comment]
I've tried to "marry" `aurelia-bundler` and `bundle-sfx` with no luck. My feeling is that the bundler needs to support this
