### ISSUE TITLE
When using TypeScript with jspm / systemjs and hot-reload, removing a debugger point does not work until browser is restarted

### ISSUE THREAD

**Issue by born2net** [systemjs/systemjs#1305]
When using TypeScript with jspm / systemjs and hot reload, removing a debugger point does not work until webstorm is restarted

This is potentially a chrome bug, I am not sure, so also opened at chrome repo: https://bugs.chromium.org/p/chromium/issues/detail?id=617450#

reference: 
https://github.com/capaj/systemjs-hot-reloader/issues/90#issuecomment-221508478

You can test with: 
1. git the project from https://github.com/born2net/ng2Boilerplate
2. launch the debug with command: npm run devserver (this will include hot-reload)
3. add break point and save which will launch the hot-reload and all works great
4. remove the break point, and yet the Webstorm will still stop at the removed bp location

And like I said, I understand that this is a poetntially Chrome bug, but I believe hot-reload is the killer application that will make sytsemjs and jspm the defacto package loader / bundler and so its really important hot-reload is bug free.

let me know if you need help setting all up, but should be easy to test

you can close this bug @guybedford if you feel its better to be resolved elsewhere, but like I said, we should definitely get it resolved as hot-reload, especially in the context of react or ng2 is AMAZING,

tx and let me know if you need help with reproducing,

Sean

**Comment by guybedford** [comment]
This does sound like more of a tooling problem that SystemJS itself. I wish I had the time to test all these environments and workflows but unfortunately I don't. Thanks for following up on these cases, as these things only work when someone pushes for that. If there is anything you need from me here please let me know though.
