### ISSUE TITLE
AMD module did not define

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#1306]
I installed [mocha](http://mochajs.org) in version `2.5.3`. Unfortunately I get following error

```
undefined:1 Uncaught (in promise) Error: TypeError: AMD module http://localhost:7357/4107/src/jspm_packages/npm/mocha@2.5.3/mocha.js did not define
	Error loading http://localhost:7357/4107/src/jspm_packages/npm/mocha@2.5.3/mocha.js as "npm:mocha@2.5.3/mocha.js" from http://localhost:7357/4107/src/jspm_packages/npm/mocha@2.5.3.js
```

With `2.5.2` everything worked fine in the past.

**Comment by guybedford** [comment]
Which version of jspm are you using here?

**Comment by screendriver** [comment]
`0.16.33`. In another project `0.16.34`

**Comment by guybedford** [comment]
Thanks, I've fixed the override in https://github.com/jspm/registry/commit/6e904637bba67bbded95563a9b6832468952f6e3.

**Comment by screendriver** [comment]
Thank you 👍
