### ISSUE TITLE
Please donate to systemjs and jspm for the great work... 

### ISSUE THREAD

**Issue by born2net** [systemjs/systemjs#1307]
just wanted to shout out to @guybedford  for this great lib, he spends a lot of his personal time and so we should support him with donations (I have) ... so please do

https://supporterhq.com/support/project/33df4abbec4d39260f49015d2457eafe/JSPM

**Comment by guybedford** [comment]
Thanks @born2net for the support! Closing with this 0.19.30 release.

**Comment by born2net** [comment]
my pleasure
