### ISSUE TITLE
importing index.js using just the directory name

### ISSUE THREAD

**Issue by mogusbi** [systemjs/systemjs#1308]
I'm attempting to import a module from using `import module from './myModule';`

myModule being **./myModule/index.js**, however I'm getting a 404 telling me that myModule.js could not be found. Is it possible to do this and do I have to do anything else to get this working?

My config;

```
defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  packages: {
    "dev/app": {
      "main": "main.js",
      "format": "es6",
      "defaultExtension": "js"
    }
  },

  map: {
    ....
  }
});
```

**Comment by guybedford** [comment]
SystemJS does not automatically add an `index.js` for directory requires.

**Comment by guybedford** [comment]
So you'd need to do `import myModule from './myModule/index.js'`

**Comment by gig177** [comment]
Why SystemJS doesn't provide this behavior?

**Comment by indieforger** [comment]
Exactly my thoughts @gig177.

@mongusbi why did you close the issue. Shouldn't we turn it into a feature request?
