### ISSUE TITLE
System is not defined when static bundling 

### ISSUE THREAD

**Issue by djflex68** [systemjs/systemjs#1310]
After static building an app that must be backwards-compatible with AMD "require", I'm getting at startup : 

`System is not defined `

I'm using the following line in main.js entry point :
`window["require"] = window["requirejs"] = System["amdRequire"];`

which works fine in Debug, but when bundling statically, System is not found anymore.

Is this the normal behaviour ? To get this to work I think the normal output should be something like : `window["require"] = window["requirejs"] = $__System["amdRequire"];`

But I don't know how to get this ?

Any help would be appreciated

**Comment by guybedford** [comment]
Yes this is correct - static builds do not contain any `System` loader. Dynamic loading use cases require using a normal bundle over a static build.

**Comment by djflex68** [comment]
Okay this is what I though, thanks
