### ISSUE TITLE
Inline script without template string

### ISSUE THREAD

**Issue by lastmjs** [systemjs/systemjs#1311]
Is there a way to load a module defined inside on an inline script, without having to define the code of the module with a template string?

**Comment by guybedford** [comment]
I guess the question here is why? `<script type="module">` with live ES module transpilation is supported in the ES6 Module Loader polyfill project, but is a terrible idea in production.

**Comment by lastmjs** [comment]
The reason is for use with web components. It's nice to put everything in an HTML file, and have the component's script with code right there with the mark-up. As SystemJS works now, I have to keep my JavaScript out of the HTML. For example, look at this component:

```
<link rel="import" href="node_modules/@polymer/polymer/polymer.html">
<link rel="import" href="node_modules/express-web-components/express-app.html">
<link rel="import" href="node_modules/express-web-components/express-middleware.html">
<link rel="import" href="node_modules/express-web-components/express-router.html">
 
<dom-module id="example-app">
    <template>
        <express-app port="5000">
            <express-middleware method="get" path="/" callback="[[index]]"></express-middleware>
            <express-middleware callback="[[notFound]]"></express-middleware>
        </express-app>
    </template>
 
    <script>
        class ExampleAppComponent {
            beforeRegister() {
                this.is = 'example-app';
            }
 
            ready() {
                this.index = (req, res) => {
                    res.send('Hola mundo!');
                };
 
                this.notFound = (req, res) => {
                    res.status(404);
                    res.send('not found');
                };
            }
        }
 
        Polymer(ExampleAppComponent);
    </script>
</dom-module>
```

I want to keep the JavaScript right in the script tag and just wrap it in a SystemJS call so that I can get imports and transpiring and everything. But to accomplish that right now I need to put all if the JavaScript in a separate file and then call System.import.

**Comment by aluanhaddad** [comment]
This increases the size of your component for little gain. You will run into tooling problems, such as lack of source map support, and lack of formatting for transpiled features in html editors. You are referencing Polymer as a global, in your example. `System.import` is about the only thing that should go in the content of a script tag these days.

**Comment by lastmjs** [comment]
I agree with the source maps issue, but I personally don't depend on that feature for debugging. Also, I believe my HTML editor (Atom) is handling at least syntax highlighting fine with JavaScript in the HTML. There may be some trade offs, I suppose my point is that there are also benefits, and it would be nice. The Polymer project has many examples of components self-contained in one HTML file, and I like that. I also like SystemJS and how easy it has made my development process while using ES next and TypeScript features. 

Besides that, maybe someone can answer this question: Why is `<script type="module">` a bad idea in production? Is it just a hit in performance?

**Comment by aluanhaddad** [comment]
It is a hit in performance for sure. Especially if you have a lot of components it's a very bad idea. I suppose you can use an HTML optimizer which minifies embedded JavaScript, assuming it supports modules in the first place, but regardless unless your script is extremely small come on you're going to hurt the maintainability of your code by just having too much in one file.
