### ISSUE TITLE
How to set defaultJSExtensions to true with package.json

### ISSUE THREAD

**Issue by sondreb** [systemjs/systemjs#1312]
Migrating from 0.1.6 to 0.1.7 beta and trying to get SystemJS.config to set the defaultJSExtensions: true inside the generated jspm.config.js file.

If I manually set the value in the jspm.config.js file, it will be removed upon next jspm update/install processing, so that is not a solution (I don't think 0.1.6 replaced the config, simply updated?).

From our package.json:
```
  "jspm": {
    "defaultExtension": "js",
    "main": "web/app/boot.js",
    "dependencies": {
         "adal-angular": "npm:adal-angular@^1.0.10",
```

This does nothing to the generated jspm.config.js file. I have also tried to set using defaultJSExtensions: true, but no difference.

Here is part of the output that is generated:

```
SystemJS.config({
  browserConfig: {
    "paths": {
      "npm:": "/jspm_packages/npm/",
      "github:": "/jspm_packages/github/"
    }
  },
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/"
    }
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.12"
    }
  }
});

SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json"
  ],
  map: {
    "adal-angular": "npm:adal-angular@1.0.10",
```

Until there is a solution, I'll keep manually editing the jspm.config.js whenever it is being updated.

**Comment by sondreb** [comment]
Setting the defaultJSExtensions: true doesn't seem to any longer be a workable solution, it makes the path to the .json files within jspm_packages/npm include .js in the file paths.

`"(SystemJS) Error: ENOENT: no such file or directory, open 'C:\src\web\jspm_packages\npm\zone.js@0.6.12.js.json' at Error (native)"`

Notice how it have appended .js before .json.

What would be the proper way to configure the defaultJSExtension for my own app code? I presume I must now add an override for all packages that I'm dependent upon which have not set defaultExtension, right?

**Comment by sondreb** [comment]
Manually adding this to the jspm.config.js make building with systemjs-builder work again, but how can I configure this so it's generated from package.json?

```
packages: {
    "app/": {
      "defaultExtension": 'js'
    },
```

**Comment by guybedford** [comment]
In jspm 0.17, all package configuration properties of SystemJS can be provided directly in the package.json of installed packages. So `defaultExtension` can work as a package.json property. Let me know if that answers your question here.

**Comment by pcompassion** [comment]
I need a bit of help, I put "defaultExtension": "js" under "jspm" inside package.json but still getting error. (as OP stated)

Where should I put `defaultExtension` in package.json?

**Comment by guybedford** [comment]
`defaultExtension` is a packages configuration property.
