### ISSUE TITLE
question(bundles): infinite bundle loop ?

### ISSUE THREAD

**Issue by douglasduteil** [systemjs/systemjs#1315]
Hi @guybedford 

I'm updating my `jspm-server` :)
However it feels like there is a regression on the bundles hook since 6 month.

It seems like in b141c9620749817bb999c008b66d33646d9e5678 you removed the test that ensure that a bundle woundn't check itself 
(cf. [b141c96/lib/bundleHook#L37](https://github.com/systemjs/systemjs/commit/b141c9620749817bb999c008b66d33646d9e5678#diff-98dd38c928164aee01f91c2e791c2ef8L37))

Without that it's become possible to infinity load the same bundle like : 

```js

System.config({
  bundles: {
    'infinite-bundle': ['infinite-bundle']
  }
});

System.import('infinite-bundle')
  .then(console.log.bind(console, 'NEVER CALLED'))

```

I know it's a stupid example... but you got my point right ?

![tumblr_ndeah4qfl51tkxxq7o1_400](https://cloud.githubusercontent.com/assets/730511/16023359/b9101140-31bc-11e6-9298-0e49172b9e99.gif)

**Comment by guybedford** [comment]
@douglasduteil the change copied does not alter that behaviour, it just explicitly writes out the `indexOf` loop while keeping the same check, and then supporting wildcards as well. It must be something else that changes this from being supported or not.

**Comment by guybedford** [comment]
It would be good to hear the justification for this feature as well, infinite loops like this are a possible behaviour in SystemJS, and happen in other places too. Infinite loops are possible in programming languages too :)

**Comment by douglasduteil** [comment]
Hum... Alright
