### ISSUE TITLE
0.17.0-beta.21 overwrites jspm.browser.js and removes wildcards

### ISSUE THREAD

**Issue by wolfmanfx** [systemjs/systemjs#1318]
Hi,

When I use the latest beta and call jspm install it overwrites the jspm.browser.js removes the wildcards and break the mapping.
To reproduce just checkout the MS sample
https://github.com/Microsoft/TypeScriptSamples/blob/master/jspm/jspm.browser.js
which do not work anymore.

is it a bug or expected behavior? If its expected how should be done now?

**Comment by guybedford** [comment]
Thanks so much for reporting. I've created https://github.com/Microsoft/TypeScriptSamples/pull/106 to fix up the sample here.

I've also added https://github.com/jspm/jspm-cli/commit/2a978827fb26cb73f91fa17a1bafd816457c9006 to fix the upgrade path.
