### ISSUE TITLE
"load.metadata.sourceMap must be set to an object" while bundle with traceur

### ISSUE THREAD

**Issue by m4r71n** [systemjs/systemjs#1319]
I'm trying to upgrade my jspm 0.16 project to 0.17-beta but while bundle I get the error `load.metadata.sourceMap must be set to an object`
I've created a demo repo to reproduce the error:
`git clone https://github.com/m4r71n/jspm-0.17.0-beta.22-traceur.git` 
just `npm install` to see it.

**Comment by guybedford** [comment]
Thanks so much for posting. This seems like it was a bug in the plugin-traceur project, I've posted a fix at https://github.com/systemjs/plugin-traceur with a 0.0.2 version. You can try the upgrade path again, or update the plugin via `jspm install plugin-traceur`.

**Comment by guybedford** [comment]
Just let me know as well if you still have any further issues here.

**Comment by m4r71n** [comment]
Thank you very much
