### ISSUE TITLE
Inline AMD Define now behaves differently 

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1320]
We previously had code like this in one of our modules, defined *inside* of a module. 

```javascript
define('scheduling-modutil', function(){ return modutil; });`
```

where define was set to `System.amdDefine;`  It's old code, and we don't normally do that, but it used to work.

Both the old builder and new compiled this into

```javascript
define("scheduling/scheduling.js", [], function() {
    return modutil;
  }) && define("scheduling-modutil", ["scheduling/scheduling.js"], function(m) {
    return m;
  });
```

Unfortunately this code no longer works from the bundle.  Changing the call from `define` to `System.amdDefine` directly did change the builder output, but the latest SystemJS still doesn't handle it correctly; it fires off a network request for `scheduling-modutil.js` which results in a 404.

The fix seems to be simply doing `System.set('scheduling-modutil', System.newModule(modutil));` but I'm hoping you can provide some insight into why this is now needed.

**Comment by guybedford** [comment]
It sounds like something is depending on `"scheduling-modutil"` then as a dependency, which would have to be from somewhere else?
