### ISSUE TITLE
System.newModule is freezing the module's object

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#1323]
If I make this call

`System.set('scheduling-modutil', System.newModule(modutil));`

and then *subsequently* modify the `modutil` object, anyone importing modutil will *not* see those mutations.

It's the *binding to* the module that should be immutable, right?  Ie, the object exported from a module should be able to be mutated as normal?

**Comment by guybedford** [comment]
The export slots are frozen at the time of creation of `System.newModule`, and at that point the existing bindings remain editable as getters only, but new export names can't be added.

**Comment by arackaf** [comment]
Ahh - I think I misunderstood how `System.newModule` was supposed to work.

So
```javascript
class c
export default c
```

Would be equivalent to 

`System.newModule({ default: c });`

**Comment by guybedford** [comment]
Yes exactly.

**Comment by abalmus** [comment]
Guys how about functions? Is it possible to add a function to the registry using System.set ??

**Comment by guybedford** [comment]
@abalmus yes via `System.set(System.normalizeSync('name'), System.newModule({ default: function() {}, exportName: function() {}, ... }))`
