### ISSUE TITLE
Error loading phaser libraries using es6 default imports

### ISSUE THREAD

**Issue by monagames** [systemjs/systemjs#1327]
First of all, sorry if I'm misusing system.js:

Whenever I try to import phaser, I get an error in my browser: 
```
system.js:4 Uncaught (in promise) Error: (SystemJS) TypeError: Cannot read property 'prototype' of undefined(…)
```

The library is loaded using es6 syntax with the help of typescript:

```ts
import Phaser from "phaser";

class Test extends Phaser.State {
    create() {
        console.log("Started");
    }
}
```

The same code (without the import) works if phaser.js is loaded as a global from the html page.

I have created an example here:  https://github.com/monagames/phaser-ts-systemjs. The index.html page produces the error described.

**Comment by guybedford** [comment]
Firstly, when getting an error in SystemJS make sure to expand the full error by clicking the `...` part.

Is `Phaser` defined? You may need to set the format via metadata to global perhaps.

**Comment by monagames** [comment]
The package is being loaded via jspm and it is loaded as a global. `phaser@2.5.0.js` contains:
```module.exports = require("github:photonstorm/phaser@2.5.0/build/phaser.js");```

Phaser is defined, but not as expected: as an object that contains Phaser and other modules exported in that library:
```js
Object {p2: Object, PIXI: Object, Phaser: Object}
```

**Comment by monagames** [comment]
Now I see this is not a problem in system.js, but in the way phaser package has been prepared. Phaser is exporting three globals, but its typescript typings are not defined consistently.

**Comment by guybedford** [comment]
@monagames you can alter the global by running Phaser as another module format if it exports it, or adding a shim override that alters the exported value to be eg `Phaser` directly instead of the object of the three globals.

Eg:

```
jspm install github:photonstorm/phaser -o "{shim:{'build/phaser.js':{exports:'Phaser'}}}"
```

Or

```
jspm install github:photonstorm/phaser -o "{format:'amd'}" # or cjs
```

**Comment by monagames** [comment]
Thanks, I've made some attempts to override its behaviour with jspm as you suggest, with no luck. I've also noticed that in addition to the default, the three modules are included in the global scope:
```js
import ph from "phaser";

console.log(Phaser); // the Phaser module
console.log(p2); // the p2 module
console.log(PIXI); // the PIXI module
console.log(ph); // the object with the three modules
```

So, it seems that phaser is escaping from the module loader boundaries and managing to define those three objects in the global scope.

**Comment by guybedford** [comment]
Sorry shim is without extensions - try:

```
jspm install github:photonstorm/phaser -o "{shim:{'build/phaser':{exports:'Phaser'}}}"
```

Globals are allowed to be defined in SystemJS for compatibility unless the `encapsulateGlobal: true` metadata option is explicitly set.

**Comment by monagames** [comment]
That did work! Thanks a lot!
