### ISSUE TITLE
babelOptions not merged on install

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#1328]
Hi,

I have two projects: `A` and `B`. `A` depends on `B` and `B` declares some `babelOptions` like `es7.classProperties`:

### config.js

```js
babelOptions: {
  "optional": [
    "runtime",
    "optimisation.modules.system",
    "es7.classProperties"
  ]
}
```

Unfortunately it seems that when `A` installs `B` it does **not** merge the `babelOptions` into his own config. So at runtime I get a `SyntaxError`. I have to add `es7.classProperties` right into my `config.js` in `A`.

This is a little bit awkward because `A` has now to know what features (`babelOptions`) all dependencies are using. I have a lot of dependencies in my project and don't want that the final executing project has to know everything about it's dependencies.

Is there an argument or option or something I am missing or is this a bug 🐛 ?

**Comment by guybedford** [comment]
In jspm 0.17 beta you can set the babelOptions via the package.json file itself to have this kind of a feature. But I think all the above options aren't necessary in jspm 0.17 anyway.

**Comment by guybedford** [comment]
In jspm 0.17 - they pass through the package.json via metadata:

package.json
```javascript
{
  "meta": {
    "*.js": { 
      "babelOptions": {...}
    }
  }
}
```

**Comment by screendriver** [comment]
Ok I understand. So I have to wait for `0.17`. Is there any release date for that? I saw that there were many beta releases in the last months.

**Comment by guybedford** [comment]
0.17 is available via `npm install jspm@beta` and is purely pending the docs update. SystemJS docs are taking priority though as it has more users, so it will likely be a month or so to get both done.
