### ISSUE TITLE
Safari Not Loading Namespace/Module Imports Like Chrome, FF, and Edge

### ISSUE THREAD

**Issue by Izzmo** [systemjs/systemjs#1329]
Situation:

I am loading HandlebarsJS and the Intl helper from Yahoo. I mapped the js file so I could use it as a module import. Works perfectly in everything but Safari.

So I do this:

`import * as Handlebars from 'handlebars';`
`import * as HandlebarsIntl from 'handlebars-intl';`

I can then start using it as if it was a regular `<script>` load and it was in the `windows` object of the browser.

However, in Safari, it is loading it similar to how `System.import(..)` passes back a module in the Promise. You have to reference the module name as a property of the passed back variable such as:

`System.Import('my-page', m => { m.doSomething(); });`

So, in order to fix this.. I basically have to do a check on the module import to see if it has it's own property and then use that instead of the top-level variable.

Is there any way around this?

**Comment by guybedford** [comment]
Any chance you can share the steps to reproduce here?

**Comment by Izzmo** [comment]
I am closing this ticket. Looks like the handlebars helper library had a dependency on the `Intl` standard which isn't implemented in Safari causing the two modules to load improperly and give this weird result.
