### ISSUE TITLE
Semver versioning and v1.0.0

### ISSUE THREAD

**Issue by jesperronn** [systemjs/systemjs#1332]
I just updated a project from systemjs `0.19.27` to `0.19.31`. However, reading the [release list](https://github.com/systemjs/systemjs/releases) revealed some new features. Since systemjs is such a crucial part of many of the projects I build, I would like to know if you consider semantic versioning?

Semantic versioning would help me when I update outdated packages. It will be much easier for me to assess the work and risk of updating.

Sorry if this has already been brought up elsewhere, but I couldn't find it in the issues here.

**Comment by guybedford** [comment]
Did you hit any specific breaking changes that caused you to post this? The project does follow semver, so if there are breaking changes that is likely a bug.
