### ISSUE TITLE
Looking for Configuration for babel-plugin-transform-eval in SystemJS

### ISSUE THREAD

**Issue by philmaker1** [systemjs/systemjs#1334]
I have Babel running and working within SystemJS in the browser. I don't plan to deploy with Babel running in the browser. But still does anyone know how to configure babel-plugin-transform-eval to run in the browser with SystemJS and Babel?

This is what I have tried:

System.config({
  map: {
    'plugin-babel': '/libraries/jspm_packages/npm/systemjs-plugin-babel@0.0.11/plugin-babel.js',
    'systemjs-babel-build': '/libraries/jspm_packages/npm/systemjs-plugin-babel@0.0.11/systemjs-babel-browser.js',
    'text': '/libraries/jspm_packages/github/systemjs/plugin-text@0.0.8/text.js',
    'babel-plugin-transform-eval': '/libraries/node_modules/babel-plugin-transform-eval/lib/index.js'
  },
  transpiler: 'plugin-babel',
  babelOptions: {
    // plugins: ['babel-plugin-transform-eval']
    plugins: ['transform-eval']
  }
});

**Comment by guybedford** [comment]
The best way to do this would be via jspm 0.17 beta. See https://github.com/systemjs/plugin-babel#custom-presets-and-transforms for more info.
