### ISSUE TITLE
Relative imports goes to dependencies?

### ISSUE THREAD

**Issue by nicklasb** [systemjs/systemjs#1335]
Hi,
I am trying to import a specific file "hooks.ts" using ```import './hooks.ts'```.
It is my understanding that such a reference should mean that SystemJS loads that specific file.

However, it seems that instead, a hooks-file from one of the dependencies is loaded?

Have I misunderstood the behaviour?

**Comment by nicklasb** [comment]
Aww f*ck. I saw the bug now. The slash is not a slash. :-)

**Comment by nicklasb** [comment]
So I was wrong to close this. The above doesn't work.

**Comment by guybedford** [comment]
The above is certainly right. You can test normalization through `System.normalizeSync('./hooks.ts', System.normalizeSync('parent-module-name'))`. Normalization is entirely a function of SystemJS configuration, which it may help to look at if you can isolate the issue happening through the above.

**Comment by nicklasb** [comment]
Thanks, the issue seems to rather be with the / path not being set to using the .ts-suffice, because it resolved to ./hooks.js.ts, which didn't match and then obviously it went about looking in the dependencies. 
However I can not test properly until monday.

**Comment by aluanhaddad** [comment]
@nicklasb please do not use `import './hooks.ts'` this is a terrible idea in any scenario where build files would have a different extension. It will make interrupt extremely difficult especially if certain developers work in different workflows on the same project. 
Please prefer `import './hooks'` using the explicit file extension in typescript is a really really bad idea.

**Comment by nicklasb** [comment]
@aluanhaddad 

That depends completely on how you build files, and if you build them at all.
I, for example, build the application dynamically, and include plugins in runtime.
I see basically no reason to build, the performance impact on loading the app is about one second, and you lose all the dynamic.

So I do not agree, there are huge number of use cases for this usage. I'd rather say that it is the future.
