### ISSUE TITLE
Wildcards disappear in browserConfig on JSPM install

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#1337]
This might be an issue with JSPM, but you might have an explanation why if this is the right behavior.

I have an Aurelia-project with this browserConfig containing wildcards (*):

```js
browserConfig: {
    "baseURL": "/",
    "paths": {
      "app/": "app/",
      "*": "app/*" // Here
    }
  },
```

When running ```jspm install``` in the latest beta (0.17.0-beta.22) the wildcards disappear and my site stops working due to the impact on path resolution.

I have also put the path in "paths" in the config, but the same thing happens there. The wildcards get stripped away.

Is this a bug, or am I doing wrong? What is the alternative to make paths resolve correctly?

The app is entirely loaded and transpiled with SystemJS, TypeScript and Babel (for async in ES5).

**Comment by guybedford** [comment]
Thanks, this is a known upgrade path bug and was fixed in https://github.com/jspm/jspm-cli/commit/2a978827fb26cb73f91fa17a1bafd816457c9006 pending release I believe.

That wildcard should be kept, although base-level wildcards are not encouarged in jspm.

**Comment by robertsundstrom** [comment]
@guybedford OK. Thanks. I'll check it out.
