### ISSUE TITLE
Breakpoints not working when hot reloading scripts

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1338]
When reloading a script in chrome (at least) using `eval` on code with an existing sourceURL, there's a bug where breakpoints act funny. This means that using something like systemjs-hot-reloader is not the experience it could be. I've opened an issue in chrome's bug tracker, in the meantime I'm thinking on how to work around the issue. I can see two options:

1. Having a different sourceURL for each reload. I tried adding:
```
',' + new Date().toISOString().substr(11, 8) // HH-MM-SS date
```
To every sourceURL in `getSource` after `!transpiled` and it works well, though I still have to open each file by its "new" name (hence having the time as the "hash", so I can track it better).
2. leave it as is and use `debugger`.

Is #1 something you would consider supporting behind a flag perhaps? (or providing some kind of API to implement it with).

**Comment by guybedford** [comment]
This is really a SystemJS hot reloader feature, so I'd suggest posting an issue there. Perhaps a custom locate hook that adds a query parameter would be enough to handle both cache busting and ensuring these sources show up uniquely in the dev tools? If this mechanism is not enough though, we can certainly look at ways to make this easier within SystemJS itself.

Ideally dev tools would provide its own API to flush the sources when hot reloading.

**Comment by Mosho1** [comment]
There are downsides to what I suggested that make it unattractive, so I think I'll wait for the chromium team to fix it or come up with a better idea. Closing for now.

**Comment by Mosho1** [comment]
This should now be fixed. https://bugs.chromium.org/p/chromium/issues/detail?id=623150#c10
