### ISSUE TITLE
A hook after a script file was loaded and converted to JS object

### ISSUE THREAD

**Issue by rzvpopescu** [systemjs/systemjs#1339]
Can you please tell me if there is a hook that will provide me the JS object loaded from a file/module ?
I'm using SystemJs with typescript trying to create a DI/IOC mechanism and I want to inject the dependencies trough constructor, by setting some static properties on those objects.

So I need to hook to some method after the JS file is imported automatically.
```
import {Inject} from './Injector';
import {DependencyClass} from './Dependency1';

@Inject(DependencyClass)
export class Service{
constructor(dep:any) {
            
    }
}
```
Using `System.import` doesn't help, because the modules are imported without my control.

Thanks

**Comment by guybedford** [comment]
Unfortunately such a hook does not exist in the loader specification at all.

This is something that would definitely be worth chasing up with the loader specification work.. I've created https://github.com/whatwg/loader/issues/146.
