### ISSUE TITLE
Loading sourcemaps from commonjs with Meta throws 'require' is undefined

### ISSUE THREAD

**Issue by acostaf** [systemjs/systemjs#1340]
Hi Team

trying to load my sourcemaps using scriptLoad from code using commonjs throws  **'require' is undefined** and then crashes the whole app removing the line **meta: { 'app/*.js': { scriptLoad: true } },** fixes the error but cannot find a single way to load the maps

```
    var config = {
        meta: { 'app/*.js': { scriptLoad: true } },
        map: map,
        packages: packages
    };
```

**Comment by guybedford** [comment]
The reason for this is that scriptLoad does not support loading CommonJS - only the wrapped formats that can work in script execution - System.register, System.registerDynamic, AMD and globals when export names are known.

**Comment by acostaf** [comment]
Hi Guy

I am writing angular2 in TypeScript using Visualstudio 2013 so changing ts file will produce the js and load the sourcemap on the browser and the IDE so using module:system works fine but changing it to commonjs breaks the flow.

any idea when this may be fix (implemented)?

**Comment by guybedford** [comment]
Does it definitely not work in Chrome? Perhaps you can share the structure of the output file source map to better understand why it's not loading correctly without scriptLoad?

**Comment by acostaf** [comment]
Cannot use Chrome so cannot test it, it is also broken in Firefox and IE11

**Comment by aluanhaddad** [comment]
@acostaf I recommend configuring inline source maps with the TypeScript compiler. This will produce fewer files, fewer http requests and is just generally easier to manage.

**Comment by guybedford** [comment]
Just let me know if I can help further here at all.
