### ISSUE TITLE
Loading SystemJS dynamically in IE fails

### ISSUE THREAD

**Issue by Aedaeum** [systemjs/systemjs#1341]
Here's my original issue: http://stackoverflow.com/questions/38064851/ie-11-will-not-load-systemjs

All other scripts work using the logic described in that issue.

**Comment by guybedford** [comment]
Have you definitely got a Promise polyfill present in the browser at the time of loading SystemJS?

**Comment by Aedaeum** [comment]
Ah, that would be it.

I completely forgot about IE not supporting promises...at least <edge

Thanks.
