### ISSUE TITLE
How to use SystemJS dynamic import in package consumed via browser and Node.js

### ISSUE THREAD

**Issue by glen-84** [systemjs/systemjs#1343]
I asked this question [here](http://stackoverflow.com/questions/38055417/how-to-use-systemjs-dynamic-import-in-package-consumed-via-browser-and-node-js), but it seems unlikely that I'll get a response.

Is there any chance that you could add a very basic example package that makes use of a dynamic `SystemJs.import()` and can be installed and used by both the browser (probably with jspm) *and* a Node.js application?

I really want to avoid some hack with eval and XMLHttpRequest for loading "modules" dynamically (on-demand), but I'm not sure how to set this all up.

I'm happy to make another small donation, as this is really blocking me at the moment.

**Comment by adamburgess** [comment]
try npm:glen-84-1343

@guybedford Is there any non-hackish way of doing a local import from a package, other than this:

```js
// first we have to find where we are
import pkgJson from './package.json!'
const location = 'npm:' + pkgJson.name + '@' + pkgJson.version + '/';

// and then we can locate our files
export default id => System.import(location + id + '.js');
```

**Comment by glen-84** [comment]
How would you use that in a Node.js app? I tried a few things but couldn't get it to work.

**Comment by adamburgess** [comment]
well, if you're using jspm, it's just the standard way

app.js:
```js
import x from 'glen-84-1343'
x('cjs-export').then(y => console.log(y));
```

`jspm install npm:glen-84-1343 && jspm run app.js`
should print 'hi this is cjs'

**Comment by glen-84** [comment]
Is jspm required when using it from Node.js?

**Comment by guybedford** [comment]
@glen-84 to get this workflow to work consistently does require support for `System.import` in the Node environment, so it does restrict the options to webpack, jspm or an alternative top-level SystemJS node loader then. This story will be improving over time though.

**Comment by glen-84** [comment]
If I'm not mistaken, something like this:

```js
if (NODE) {
    require("x");
} else {
    SystemJs.import("x");
}
```

Wouldn't work, because jspm would see the `require`s and try to load them up front. Is there any way to prevent that? Maybe a comment like `// jspm:ignore` above the require().

My primary goal is to get dynamic loading working in the browser, but it would be nice to have something generic that works in both environments.

**Comment by guybedford** [comment]
```javascript
if (NODE) {
    require("" + "x");
} else {
    SystemJS.import("x");
}
```

would work as it would avoid the require tracing system.

But yes this is the limitation of the SystemJS CommonJS approach.

**Comment by glen-84** [comment]
Thanks, that is useful. =)

**Comment by guybedford** [comment]
Just let me know if you still need any help here at all.

**Comment by glen-84** [comment]
@guybedford Are there any issues, here or external/spec, that I can follow that will make this type of thing easier/cleaner?

@adamburgess Thanks for your help, it is much appreciated.

**Comment by guybedford** [comment]
The way this plays out is it just is a messy boundary case right now
between Node dynamic require convention and the SystemJS one.

The convergence will be when the dynamic require in ES modules is fully
standard syntax (loader.import or something) but that spec is still being
confirmed. Until then messiness is the game unfortunately.

**Comment by glen-84** [comment]
@guybedford,

> The convergence will be when the dynamic require in ES modules is fully standard syntax

I guess this is getting closer now, with `import()`?

Will (or has) systemjs implemented a polyfill for this?

Will it be possible to handle this scenario (of dynamic loading in both the browser and Node) in a uniform manner within the short to medium term?

**Comment by guybedford** [comment]
The dynamic `import()` is supported in SystemJS when using Babel through the Babel plugin. If using the Babel plugin, the `syntax-dynamic-import` plugin needs to be added as well for the support. Supporting this was one of the features of SystemJS 0.20.

**Comment by glen-84** [comment]
I don't use Babel anymore. 😞 

I'm using gulp-typescript.

**Comment by guybedford** [comment]
@glen-84 good point! I'd suggest following the TypeScript issue at https://github.com/Microsoft/TypeScript/issues/14495 then.

**Comment by glen-84** [comment]
@guybedford Thanks for the link. (=
