### ISSUE TITLE
Conditional Mapping for plugins

### ISSUE THREAD

**Issue by casperlamboo** [systemjs/systemjs#1345]
I'm working on a plugin where I want to use different scripts for development and production. (the [plugin](https://github.com/casperlamboo/plugin-worker) I'm referring to)

My `main.js` file looks like this
```javascript
// map is set to load plugin-dev in development and plugin-production in production
var plugin = require('./plugin.js');

// because it doesn't seem possible to conditionally load either the
// production or development code as the entry point (main in package.json)
// we had to add this in between step.
if (plugin.locate !== undefined) exports.locate = plugin.locate;
if (plugin.fetch !== undefined) exports.fetch = plugin.fetch;
if (plugin.translate !== undefined) exports.translate = plugin.translate;
if (plugin.instantiate !== undefined) exports.instantiate = plugin.instantiate;
```
In my config I have mapped `node` to `plugin-productions.js` and `browser` to `plugin-dev.js`
```javascript
{
  "jspm": {
    "map": {
      "./plugin.js": {
        "node": "./plugin-production.js",
        "browser": "./plugin-dev.js"
      }
    }
}
```
This works but I believe this is not how conditional loading is intended (I use node for production and browser for development). In the [jspm 0.17-beta docs](http://jspm.io/0.17-beta-guide/conditional-loading.html) this example is given
```javascript
      "map": {
        "./text.js": {
          "~production": "./text-dev.js"
        }
```
Using this example I've changed my `package.json` to
```javascript
{
  "jspm": {
    "map": {
      "./plugin.js": {
        "production": "./plugin-production.js",
        "dev": "./plugin-dev.js"
      }
    }
}
```
But when I want to make a production bundle using `jspm build index.js dist/app.js --minify` I receive the following error
```
(SystemJS) /Users/casper/MAMP/plugin-worker/example/jspm_packages/local/plugin-worker@0.0.1/plugin-dev.js:3
```
Notice how it's trying to load `plugin-dev.js`. Using this package configuration the development version in browser works seamlessly.

I've also tried working with `~production` (NOT production) and `production`. In this case the behaviour is exactly the same. The production still tries to load the plugin-dev and again the development version in browser works great.

It should also be possible to map the entry point. I've tried configuring my `package.json` as such
```javascript
{
  "jspm": {
    "main": {
      "node": "./plugin-production.js",
      "browser": "./plugin-dev.js"
    }
  }
}
```
The development version (again) work correctly but when I try to bundle for production I receive the following error.
```
err  Error: Unable to trace worker.js!local:plugin-worker@0.0.1/#:./@main - building package environment mappings of plugins is not currently supported.
```

(I'm using JSPM version `0.17.0-beta.22`)

**Comment by guybedford** [comment]
Sorry for the long delay here, I've been travelling quite a bit recently. This is a very specific bug actually, that by doing a main forwarding module we don't need to handle this exact case in the builder.

If you configure your plugin to load via meta configuration:

```javascript
System.config({
  meta: {
    "path/to/file.js": { "loader": "worker" }
  }
});
```


Instead of using the `!worker` syntax then this should work.

Supporting the plugin syntax normalization against conditionals is simply a TODO in https://github.com/systemjs/builder/issues/651.

**Comment by guybedford** [comment]
(I've created https://github.com/systemjs/builder/issues/651 to track)

**Comment by guybedford** [comment]
For the first conditional builder issue you mentioned here, are you definitely running beta.22 for jspm? The builder environment should by default do a production build, otherwise you can add `jspm build --production` flag but that shouldn't be necessary. This may be a bug as it's supposed to do what you describe.

**Comment by casperlamboo** [comment]
> If you configure your plugin to load via meta configuration: Instead of using the !worker syntax then this should work.

Are you perhaps referring to  issue #1347?

**Comment by guybedford** [comment]
I was referring to the conditional builds problem itself - conditional loads with plugin syntax may not be completely supported in bundling due to issues like https://github.com/systemjs/builder/issues/651.

**Comment by guybedford** [comment]
I believe this is being tracked in the issues above now? But let me know if I've missed something.
