### ISSUE TITLE
function addToError swallows error message in system.src.js line 108

### ISSUE THREAD

**Issue by pikeymick** [systemjs/systemjs#1346]
When an error is passed to:

```
function addToError(err, msg) {
    // parse the stack removing loader code lines for simplification
    if (!err.originalErr) {
      var stack = (err.stack || err.message || err).toString().split('\n');
      var newStack = [];
      for (var i = 0; i < stack.length; i++) {
        if (typeof $__curScript == 'undefined' || stack[i].indexOf($__curScript.src) == -1)
          newStack.push(stack[i]);
      }
   }
```

If the error exists on error.message, but error.stack is also present the message is swallowed, and it takes a lot of work to trace the issue back to this line. Please provide the user the ability to see the .stack, and .message if both are present.

**Comment by pikeymick** [comment]
Specifically this occurs in Safari when loading a module with unsupported JS: Unexpected keyword 'const'. Const declarations are not supported in strict mode."

It's very difficult to track this down.

**Comment by guybedford** [comment]
This is a standard technique in JS for creating new error stacks, which is effectively what we're providing.

The original error is available at `e.originalErr` where the original stack can be inspected.

**Comment by pikeymick** [comment]
This block only reports the stack trace if a stack trace is present, thereby swallowing any available error message as you can see in the attached message. This is easily reproduced by running an Angular 2 rc2 || rc3 app in Safari with es6 set. The app fails without telling the user why, and only shows the stack trace which is usually irrelevant to browser level (native code) issues.

**Comment by guybedford** [comment]
Is this a Safari-specific issue? Have you compared the error in Chrome?

I think the only reasonable alternative approach would be to throw two errors - the original error, and then the modified error. The issue with that is that it stops the user from being able to handle all errors.

You can achieve this behaviour yourself via:

```javascript
System.import('main')
.catch(function(e) {
  if (e.originalErr)
    console.error(e.originalErr);
  console.error(e);
});
```

I definitely agree this should be well-documented.

In terms of alternative approaches, the only alternative would be to return an unmodified error stack. Perhaps we could introduce a flag for this sort of behaviour as well.

**Comment by pikeymick** [comment]
The underlying behavior depends on the browser. Chrome doesn't enforce this particular issue "Unexpected keyword 'const'" when 'use strict' is set. 

Is there an added benefit to modifying the original stack? Perhaps I'm misunderstanding the block of code, it reads to me as though the block is there to create brevity in the stack?

**Comment by guybedford** [comment]
@pikeymick this is about how we handle all errors in SystemJS. And because SystemJS needs to provide additional stack information, we need to modify the error message to add that. We used to mutate the error message itself, but there were complaints that this wasn't good to mutate an error object. So the approach taken is to create a new error containing the previous error information (we copy the stack and message) and then provide a link to the original error object as `e.originalErr`. This is the same sort of approach taken by many projects I believe, although if there are better ways of copying the original info to the new object I'm always open to suggestions.

**Comment by guybedford** [comment]
This was fixed in https://github.com/systemjs/systemjs/issues/1374.
