### ISSUE TITLE
Config defined loader overrules inline defined plugin?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#1347]
In the SystemJS used by JSPM 0.17, shouldn't an inline defined plugin in the import statement overrule the loader defined in meta configuration? 
The docs doesn't actually state which way overrules the other, so maybe it's a wrong assumption. 

While working with web workers we noticed that our plugin / loader wasn't used when explicitly putting `!worker` in the import statement;

``` javascript
import Worker from 'test.js!worker';
```

It looked like the `*.js` meta config overruled this. The plugin isn't used. 

``` javascript
      "meta": {
        "*.js": {
          "loader": "plugin-babel",
          "babelOptions": {
            "stage1": true,
            "plugins": [
              "babel-plugin-transform-react-jsx"
            ]
          }
        },
```

When defining a `.worker` rule and renaming our file it did use our worker. 

``` javascript
      "meta": {
        "*.worker": {
          "loader": "worker"
        }
      }
```

**Comment by guybedford** [comment]
Thanks, yes this is a bug.

**Comment by casperlamboo** [comment]
in #1345 you suggested I'd use the meta configuration to load worker files
```javascript
System.config({
  meta: {
    "path/to/file.js": { "loader": "worker" }
  }
});
```
This doesn't completely work as expected. Inside the worker the target file is still configured to be loaded via the plugin. When loading this file it doesn't use babel but instead the worker-plugin.

**Comment by guybedford** [comment]
@casperlamboo that is actually strictly correct though, in terms of the behaviour of SystemJS itself, just that the worker environment would need a different configuration. This could be reconfigured in the worker with a custom config call potentially.
