### ISSUE TITLE
Path normalization in v0.19.29-31 

### ISSUE THREAD

**Issue by rosendi** [systemjs/systemjs#1348]
I have a few stylesheets:

component.css:

```
.h1 {
  composes: primaryText from "./colors.css";
}
```

colors.css:

```
.primaryText {
  color: #0d7689;
}
```

When I import `component.css` SystemJS v0.19.29-31 fails:

```
System.import('app/client/components/component.css!css.js').then(r => console.log(r));

// Error loading http://0.0.0.0:7070/http:/0.0.0.0:7070/app/client/components/colors.css!http://0.0.0.0:7070/css.js
```
The problem is here `http://0.0.0.0:7070/http:/0.0.0.0:7070/`. SystemJS v0.19.28 works fine. My `config.js` is default. Is it a bug?

**Comment by guybedford** [comment]
What CSS plugin are you using here?

**Comment by rosendi** [comment]
@guybedford [jspm-loader-css](https://github.com/geelen/jspm-loader-css) with a custom config: 
```
import { CSSLoader, Plugins } from 'jspm-loader-css';

import postcssAutoreset from 'postcss-autoreset';
import postcssColorFunction from 'postcss-color-function';
import postcssNested from 'postcss-nested';

const { fetch, bundle } = new CSSLoader([
  postcssAutoreset,
  postcssColorFunction,
  postcssNested,
  Plugins.values,
  Plugins.localByDefault,
  Plugins.extractImports,
  Plugins.scope,
  Plugins.autoprefixer(),
], __moduleName);

export { fetch, bundle };
```

**Comment by guybedford** [comment]
@rosendi right, yes I think jspm-loader-css may have some bugs here unfortunately. I'd suggest either posting an issue there or investigating other css plugins. You can also run a separate compilation before loading css through jspm too.

**Comment by rosendi** [comment]
[This demo](https://github.com/css-modules/jspm-demo) also fails with latest SystemJS.

**Comment by rosendi** [comment]
@guybedford OK, I'll post this issue there. I'm closing it for now.

**Comment by rosendi** [comment]
@guybedford What do you mean here?

>You can also run a separate compilation before loading css through jspm too.

**Comment by guybedford** [comment]
I mean you could use a custom build process through another system before providing the generated css to SystemJS as well.
