### ISSUE TITLE
Globals in meta configuration not present inside function

### ISSUE THREAD

**Issue by nojaf** [systemjs/systemjs#1349]
I have a configuration where I use a global inside my own script, the global is there when the script loads but not when I execute a function of the script.

I've created a repo where it can be reproduced: https://github.com/nojaf/systemjs-global-in-function
Is this expected behavior? Any workarounds?

**Comment by guybedford** [comment]
I'd suggest removing the `encapsulateGlobal` configuration and instead using CommonJS by writing viewmodel.js as:

```javascript
console.log("ko should be defined", ko);

module.exports = function(){
	console.log("ko is undefined", ko);
	var self = this;
	self.title = ko.observable("title");
}
```

CommonJS will provide globals by doing a scope wrapper. Global modules provide globals by setting the global for only the synchronous execution context - this allows globals to be loaded with script tags for CSP support.

We could potentially support globals via wrappers, but it becomes a tradeoff with CSP support handling.

**Comment by guybedford** [comment]
Marking as a documentation issue for now...
