### ISSUE TITLE
In IE11: "(SystemJS) TypeError: Unable to get property 'lastIndexOf' of undefined or null reference

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#1350]
I have a project with JSPM (version 0.17.0-beta.18) that has to target Internet Explorer (IE) 11.

When running in IE11 I get this error:

How do I solve this?

```
"(SystemJS) TypeError: Unable to get property 'lastIndexOf' of undefined or null reference
	   at F (http://localhost:2208/jspm_packages/system-polyfills.js:4:7471)
	   at H (http://localhost:2208/jspm_packages/system-polyfills.js:4:7058)
	Error loading http://localhost:2208/dist/app/startup.js"
```

**Comment by robertsundstrom** [comment]
Has anyone any idea on how to solve this?

**Comment by guybedford** [comment]
@robertsundstrom the polyfills file being referred to there means the bug is in the promise chain itself. So it could actually come from any code. I don't think this is in SystemJS itself so I'd suggest standard debugging techniques to track down the right line.
