### ISSUE TITLE
System vs SystemJS ambiguity?

### ISSUE THREAD

**Issue by mkastner** [systemjs/systemjs#1351]
What is the variable that should be used with system.js?

Here

[https://github.com/systemjs/systemjs/blob/master/docs/overview.md#map-config](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#map-config)

```
<script src="system.js"></script>
<script>
  // loads relative to the current page URL
  System.import('./local-module.js'); 

  // load from an absolute URL directly
  System.import('https://code.jquery.com/jquery.js');
</script>
```

the variable name is "System".

But here

[https://github.com/systemjs/systemjs#browser](https://github.com/systemjs/systemjs#browser)

```
<script src="system.js"></script>
<script>
  // set our baseURL reference path
  SystemJS.config({
    baseURL: '/js'
  });

  // loads /js/main.js
  SystemJS.import('main.js');
</script>
```

it's "SystemJS".

Which one is the right one?

**Comment by guybedford** [comment]
SystemJS is encouraged because System is a spec object and in future `System.import` will be deprecated for `SystemJS.import`. But we have a little while still...

**Comment by mkastner** [comment]
Thank you for the clarification.
