### ISSUE TITLE
Errors with Edge browser but Chrome is fine

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#1352]
Please browse to this URL http://familytreeweb20160702.azurewebsites.net/ in Microsoft Edge and Google Chrome browsers.

If you check the **console windows** in the Dev Tools, you will find that there are FORBIDDEN errors in Edge. There are no errors in Google Chrome.

There is an error thrown from **system.src.js**, so wondering is it a CORS issue that systemJS does not handle.

![edge](https://cloud.githubusercontent.com/assets/12233474/16571300/f725ed0c-421e-11e6-8f42-4a6856db9689.PNG)

**Comment by AStoker** [comment]
I believe it's related to this: https://github.com/systemjs/systemjs/issues/450
It's having trouble loading up source maps

**Comment by guybedford** [comment]
Yes this does seem like it is trying to load source maps. Perhaps disable CSS source maps for this application?
