### ISSUE TITLE
Importing ES6 modules in workers in safari fails

### ISSUE THREAD

**Issue by casperlamboo** [systemjs/systemjs#1353]
I was having trouble getting my [worker-plugin](https://github.com/systemjs/systemjs/issues/1330) to work in safari. I kept getting this error.
```
(SystemJS) 
  eval code
  eval@[native code]
  promiseReactionJob@[native code]
  Evaluating http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.12/plugin-babel.js
  Error loading http://localhost:3000/jspm_packages/npm/systemjs-plugin-babel@0.0.12/plugin-babel.js
  Error loading http://localhost:3000/src/worker.js
```
I was uncertain what caused the error so I started a [new project with only the bare minimum to import workers](https://github.com/casperlamboo/JSPM-worker-error) and I still got this error.

We get this error no matter what the content is of the javascript file that is loaded with SystemJS inside the worker, when empty, when containing regular js code or es2015 code. 

After overriding the System.normalize and System.locate we also noticed that in Chrome the `metadata.format` was set to `register` but in Safari it said `esm`. (This is kind of hard to debug because console.log's don't work from Web workers in Safari)

We are using jspm version `0.17.0-beta.21` with `SystemJS v0.19.31`

**Comment by guybedford** [comment]
I just tried your demo project in Safari and it seemed to work ok for me? (jspm 0.17.0-beta.22)

**Comment by guybedford** [comment]
Let me know if you still need help with this.... and thanks for your patience on these issues.

**Comment by casperlamboo** [comment]
Sorry for the delay.

I updated my jspm version to `0.17.0-beta.24` and I still got this error. I tested it on my device running safari version `9.0.1` and I tested it on a college's device running safari version `9.1.2`, both running mac OS.

I modified my code a little bit, instead of logging the `messageEvent` it logs the `data` property of the `messageEvent`. It should say "test" but in safari it gives a long error message (logging the catch in https://github.com/casperlamboo/JSPM-worker-error/blob/master/src/workerLoader.js#L8)

**Comment by guybedford** [comment]
I've had a deeper look into this, and tracked it down to this bug in Safari - https://bugs.webkit.org/show_bug.cgi?id=119472.

I've added a workaround for it to SystemJS builder in https://github.com/systemjs/builder/commit/7a3ddbf7c9c327dea5b35e209ff5589b42cd670b and posted a new release of the Babel plugin 0.0.13 with the fix.

Thanks for posting this one.

**Comment by casperlamboo** [comment]
@guybedford tested it and it works! thanks!!
