### ISSUE TITLE
Using es6-promise as a polyfill not working

### ISSUE THREAD

**Issue by ilbmiller** [systemjs/systemjs#1355]
The systemjs reamdme says that it supports the es6-promise polyfill:

> For the best performance in IE and older browsers, it is advisable to load a polyfill like [Bluebird](https://github.com/petkaantonov/bluebird) or [es6-promise](https://github.com/stefanpenner/es6-promise) before SystemJS.

However, when I locally install es6-promise via:
`jspm install npm:es6-promise`

and then try to load it in index.html before the systemjs loading:
` <script src="jspm_packages/npm/es6-promise@3.2.1/dist/es6-promise.js"></script>`
I get the following error:
```
SCRIPT5009: 'require' is undefined
File: es6-promise.js, Line: 3, Column: 2
```
which isn't surprising, as the es6-promise.js file requires that the common js module system loaded (which implements 'require(...)'):
```
/* */ 
"format cjs";
(function(process) {

...

    lib$es6$promise$polyfill$$default();
  }).call(this);
})(require('process'));

```

Obviously I'm not using systemjs to load the es6-promise (as it is a pre-requisite to loading systemjs) - I'm just trying to load it natively via &lt;script> in the index.html.  If systemjs says it supports es6-promise as a polyfill, how do I load it in my index.html as a pre-req to installing systemjs?

There is a workaround: I can use an 'npm install es6-promise', and then in the index.html load it via:
` <script src="node_modules/es6-promise/dist/es6-promise.js"></script>`
This works! 

 However, it forces me to use both npm install and jspm install to load the application's third party dependencies.  I'd like to consolidate the application's third-party installation to solely use jspm install - is there a way to use the 'jspm install' version of es6-promise?  Or a way to configure 'jspm install' for es6-promise to install the 'raw npm install' version of es6-promise?

Thanks,
Brad

**Comment by guybedford** [comment]
It is advisable to still use jspm and npm together for the different node / browser workflows.
