### ISSUE TITLE
system.js dist files have invalid source maps

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1357]
The comment at the top invalidates the source map, since line numbers no longer match:
```
/*
 * SystemJS v0.19.31
*/
```
https://sourcemaps.io/validate?url=https%3A%2F%2Fcdn.rawgit.com%2Fsystemjs%2Fsystemjs%2Fmaster%2Fdist%2Fsystem.js

Once the header is removed the source map becomes valid again: https://sourcemaps.io/validate?url=https%3A%2F%2Fcdn.rawgit.com%2Fasapach%2Fsystemjs%2Fmaster%2Fdist%2Fsystem.js

Same is true for other dist files: https://sourcemaps.io/validate?url=https%3A%2F%2Fcdn.rawgit.com%2Fsystemjs%2Fsystemjs%2Fmaster%2Fdist%2Fsystem-polyfills.js

**Comment by guybedford** [comment]
Thanks, yes this is a bug!

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/857c0ef8d97f3c4907e8d2eb4a5a732b93fc16c7.

**Comment by guybedford** [comment]
Released in 0.19.34.
