### ISSUE TITLE
Provide source maps encoding in Node

### ISSUE THREAD

**Issue by mavericken** [systemjs/systemjs#1359]
System.js currently relies on the existance of btoa for building sourcemap urls.  Most environments have it: [http://caniuse.com/#feat=atob-btoa]

It is not available on node.js, sadly, and I had a heck of a time realizing this was the reason why a very complicated sourcemap situation was not working.  The function is not found in system-polyfills, though I never expected system-polyfills to be necessary in Node anyways.  Now that I know the problem, I shimmed it into my crude loader script and I don't expect it will bother me again:
`global.btoa = global.btoa || function (str) {return new Buffer(str).toString('base64');};`

However, I wasted a bunch of time on this, and surely someone else will end up with this same problem and have to figure out what is wrong all over again.  How can we make it so nobody else has to waste time coming to this realization?  (Would be nice if we could just build the solution right in so it that it just works.)

**Comment by guybedford** [comment]
@mavericken are you saying that the btoa source maps approach actually works in Node now!? If so, I can mark this as a feature to support source map encoding in Node.

**Comment by mavericken** [comment]
It "worked for me".  My test project has a loader with the btoa global shim, and uses beta dependencies.   Also I have only seen it work with node - inspector so far, vs code still doesn't like it.
https://github.com/mavericken/jspm-node-typescript-vscode

**Comment by guybedford** [comment]
Awesome, I've added this in https://github.com/systemjs/systemjs/commit/e03812ce3285270c8bad5a4e0350bab514eb6ad7.

**Comment by guybedford** [comment]
Released in 0.19.34.
