### ISSUE TITLE
[question] Circular imports from TypeScript to Commonjs Failing

### ISSUE THREAD

**Issue by cthrax** [systemjs/systemjs#1360]
This is very likely a misuse or misunderstanding on my part, but I've encountered a scenario I thought should work with SystemJS but doesn't.

A plnkr demonstrating the issue can be found here https://plnkr.co/edit/uJiprk7lRhVyA97TOvrU?p=preview

If you look at the index.ts, there are two exports that are coming from a parent and dependency. The parent, depends on dep, which it tries to import from index.ts, which is loaded after the export from parent in index.ts. If this order is switched, everything works fine, but in this order, dep is always undefined when attempting to import in parent.

My mental model has the flow going "import parent from index"-> "import parent from parent" -> "import dep from index" -> "dep does not exist, parent fails to load" -> "import dep from dep" -> "parent is undefined, but dep exists". Which is understandable, but I thought SystemJS handled these sort of circles as per the FAQ on the main page. I have attempted typescript module formats of commonjs and system, both without luck.

Thanks for looking!

**Comment by guybedford** [comment]
The only bindings that support this in ES modules are exported functions (`export function x() {}`) which  can be defined before execution of the code. All other bindings depend on execution order in order to not be undefined.
