### ISSUE TITLE
Configuring baseURL when physical and virtual paths differ

### ISSUE THREAD

**Issue by stonebraker** [systemjs/systemjs#1361]
I am attempting to utilize jspm and systemjs in a grails application. Due to the way grails manages assets, the physical directory structure differs from the virtual directory structure.

The physical path to a hypothetical app.js javascript asset from the project's root directory would be:
./grails-app/assets/javascripts/app.js

Likewise, packages would be installed via jspm to:
./grails-app/assets/javascripts/jspm_packages

The virtual path for app.js and jspm_packages would be these respectively:
http://localhost:8080/assets/app.js
http://localhost:8080/assets/jspm_packages

The configs currently looks like this:
package.json
```
"jspm": {
    "directories": {
      "packages": "grails-app/assets/javascripts/jspm_packages"
    },
    "configFile": "grails-app/assets/javascripts/systemjs-config.js",
    ...
}
```

systemjs-config.js
```
System.config({
     baseURL: "/assets",
     ...
  },
  paths: {
    "github:*": "grails-app/assets/javascripts/jspm_packages/github/*",
    "npm:*": "grails-app/assets/javascripts/jspm_packages/npm/*"
  }
  ...
}
```

When accessing app.js via an index file like so:
```
<asset:javascript src="jspm_packages/system.js"/>
<asset:javascript src="systemjs-config.js"/>
<script type="text/javascript">
    SystemJS.load("assets/app.js");
</script>
```

SystemJS fails to retrieve babel attempting to load the file from a concatenated path:
http://localhost:8080/assets/grails-app/assets/javascripts/jspm_packages/npm/babel-core@5.8.38.js

Rather than the virtual path:
http://localhost:8080/assets/jspm_packages/npm/babel-core@5.8.38.js

Is there a way to better configure SystemJS to load from a rather distinct virtual path? The virtual path to application assets is a convention of the grails asset pipeline and is pretty well baked in. Any help is appreciated.

**Comment by stonebraker** [comment]
Not surprisingly, the act of writing it out organized the issue and led me to the answer:

```
paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
```

The babel dependency now loads as expected. Of course, if this is not the intended use, please advise.

Thanks for the work you're doing!

**Comment by guybedford** [comment]
Glad to hear you worked it out, yes this is the right approach.
