### ISSUE TITLE
Bundled Typescript library import error

### ISSUE THREAD

**Issue by bogdanmanate** [systemjs/systemjs#1362]
I'm developing a library using Typescript and I want to use that code inside an Angular 2 application. The normal workflow, at least from what I've read from a online resources, ist to create a single bundle file and to use a module loader to load your modules. Since Angular 2 seed is already using SystemJS, I decided to export the modules using system format.

I've created a gist with a test structure https://gist.github.com/bogdanmanate/87c0beb55ac8677510e3eb17092aa5d1

I can't figure it out how can I use the code from those bundled modules.

``` javascript
SystemJS.config({
        baseURL: '/lib',
       defaultJSExtensions: true,
            bundles: {
        'module-test': ['mainModule', 'moduleA', 'moduleB']
    }
    });
    SystemJS.import('module-test').then( function(module){
           var person = new Person();
           console.log(person.greetFriend())
        } ).
        catch(function (err){
            console.log(err)
        });
```

I've tried the above example, but unfortunately it seems that the class Person is not defined. What am I missing ?

**Comment by guybedford** [comment]
You want to import the `mainModule`, which should then load from the bundle. If you still see a separate request for `lib/mainModule.js` then the names in the bundle aren't matching up with the bundles configuration correctly.

**Comment by bogdanmanate** [comment]
Yes, I still see a separate request for `lib/mainModule.js`. What am I doing wrong in the bundles configuration? This is my exported bundle https://gist.github.com/bogdanmanate/87c0beb55ac8677510e3eb17092aa5d1#file-module-test-js

**Comment by guybedford** [comment]
Is the bundle loading automatiaclly when you just import `mainModule` directly? If not then perhaps try adding the `.js` extension in the bundles list. If the bundle is loading but then it's still sending a separate request, then you can check `Object.keys(System.defined)` to see what names are being defined as and why they aren't matching up.

**Comment by bogdanmanate** [comment]
I don't think that works, because my bundle file is called module-test.js. There is no way for SystemJS.import to know from where to download the mainModule. What is the correct definition for that bundle ?   bundles: {'module-test': ['mainModule', 'moduleA', 'moduleB']} and than SystemJS.import(mainModule) or 'bundles: {'mainModule': [ 'moduleA', 'moduleB']}' and than SystemJS.import('mainModule'). 
Thank you very much for taking your time to answer my questions.

**Comment by guybedford** [comment]
`bundles: { 'module-test': ['mainModule', ...] }` tells SystemJS that `System.import('mainModule')` should load it from `System.import(module-test)` so it will load the bundle file first automatically.

**Comment by guybedford** [comment]
I would suggest checking the js extensions...

**Comment by bogdanmanate** [comment]
You were totally right. The missing extensions was the problem. Oh, I hate when such a small detail makes me spend a couple of hours debugging. 
The modules are loaded, but the function start and the classes Greeter and Person are still not available. Do I have to use a prefix or something ?
Thank you very much once again.

**Comment by guybedford** [comment]
Sure. It looks like mainModule would need to re-export them to make them available.

**Comment by bogdanmanate** [comment]
Thank your three times. 
I saw many issues regarding Typescript and SystemJS, maybe the documentation should be a bit more explanatory regarding this workflow.
