### ISSUE TITLE
rewrite of SystemJS

### ISSUE THREAD

**Issue by chpio** [systemjs/systemjs#1365]
Hi,

would you accept a rewrite of SystemJS? @guybedford
i thought about these changes:
- es6 syntax (compiled with babel to es5) but without the use of es6 specific functions (eg Array#find) so there is no need for polyfills/babel-runtime
  - use of es6 modules so we could use rollup with tree-shaking for custom builds
  - i don't know about *class*es. But they wouldn't need babel-runtime [if compiled in loose mode](https://babeljs.io/repl/#?evaluate=true&lineWrap=true&presets=es2015%2Ces2015-loose&code=class%20Test%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20this.var%20%3D%201%3B%0A%20%20%7D%0A%20%20%0A%20%20foo()%20%7B%0A%20%20%20%20this.bar()%3B%0A%20%20%7D%0A%7D%0A%0Aclass%20Test2%20extends%20Test%20%7B%0A%20%20constructor()%20%7B%0A%20%20%20%20super()%3B%0A%20%20%20%20this.var%20%3D%202%3B%0A%20%20%7D%0A%20%20%0A%20%20bar()%20%7B%0A%20%20%20%20this.foo()%3B%0A%20%20%7D%0A%7D) (edit: nope, extended classes do need a helpers)
- rewrite the *hook*s to pipelines (a simple array which we could iterate over)
  - would allow us to define them in one place and a defined order of the handlers
- maybe more things i haven't thought about

ps: sorry for my bad english :|
pps: is there a purpose for the builds to be in the git repo? Isn't it complicating the dev process (merges) and cluttering the repo with non source code? Edit: if they are really needed (bower?) we could put them in to a second repo.

**Comment by guybedford** [comment]
> rewrite the hooks to pipelines (a simple array which we could iterate over) would allow us to define them in one place and a defined order of the handlers

Can you share the model you're thinking of here? I was doing some testing on this recently, and was thinking of creating a core extensible hook system, but in my initial benchmark tests, looping an array of handlers was much slower than the current method of hooking the functions.

**Comment by chpio** [comment]
i thought about doing nearly the same you are doing now:

```javascript
'use strict';

function constructA(next) {
	return function a(input) {
		console.log('a: before');
		const ret = next(input);
		console.log('a: after');
		return ret;
	};
}

function constructB(next) {
	return function b(input) {
		console.log('b: before');
		const ret = next(input);
		console.log('b: after');
		return ret;
	};
}

function makeHandlerChain(handlers, lastHandler) {
	let handler = lastHandler; // or a noop function
	for (let i = handlers.length - 1; 0 <= i; i -= 1) {
		handler = handlers[i](handler);
	}
	return handler;
}

const chain = makeHandlerChain(
	[
		constructA,
		constructB,
	],
	(input) => {
		console.log(input);
		return 'bar';
	}
);

console.log(chain('foo'));
```
