### ISSUE TITLE
normalizeSync during bundling is using file://, which breaks later on

### ISSUE THREAD

**Issue by davis** [systemjs/systemjs#1368]
I've written a [Handlebars plugin](https://github.com/davis/plugin-hbs) which basically looks like this:

```js
'use strict';

import Handlebars from 'handlebars';

const handlebarsRuntimePath = System.normalizeSync('handlebars/handlebars.runtime', __moduleName);

export function translate(load) {
  var precompiled = Handlebars.precompile(load.source);
  load.source = `module.exports = require('${handlebarsRuntimePath}').template(${precompiled});`;
}
```

but handlebarsRuntimePath ends up being a file:// path, which causes errors when i try to run the bundle built with jspm 0.17.0-beta.22:

```sh
jspm bundle -wid searcher-fe
```

![screen shot 2016-07-15 at 8 57 56 pm](https://cloud.githubusercontent.com/assets/4855619/16892641/d97a9830-4ace-11e6-9223-7ed8c9e1f7e8.png)

Am I doing something wrong in my plugin? Please advise, thanks!

**Comment by guybedford** [comment]
It all looks good - just make sure to use the canonical name when compiling in a build. See https://github.com/systemjs/plugin-babel/blob/master/plugin-babel.js#L23 for how this is done.

**Comment by davis** [comment]
so i can check if `System.getCanonicalName` exists to know whether it is being compiled in a build?

**Comment by guybedford** [comment]
Yes exactly, or just check System.builder if you prefer.

**Comment by davis** [comment]
awesome, i'll give that a shot. thanks!
