### ISSUE TITLE
System.loads doesnt output all keys with Object.keys.forEach

### ISSUE THREAD

**Issue by el-davo** [systemjs/systemjs#1369]
Im probably missing something really simple but this is what i am seeing when i try to get the entire list of dependencies from Systemjs with System.loads.

`console.log(System.loads)`

outputs

![image](https://cloud.githubusercontent.com/assets/11195158/16902169/ae6b18a0-4c4e-11e6-8759-cd4d627552ef.png)

However if i try to loop over the keys like so 

`Object.keys(System.loads).forEach((moduleName) => {
      console.log(moduleName);
});`

I dont get the entire list.

I get this

![image](https://cloud.githubusercontent.com/assets/11195158/16902178/f9405ae8-4c4e-11e6-9743-6788c2f32a35.png)

As you can see it isnt outputting things like "http://localhost:8000/app/build/build-editor.ts"

If i try and access the key directly with 

`console.log(System.loads['http://localhost:8000/app/build/build-editor.ts'])`

I get undefined

Any help appreciated

**Comment by guybedford** [comment]
I don't think this is possible for an object to be logged and display a value and then not provide that same value on property lookup! Are you sure you're writing all this code synchronously in the same state?

I take it you are running with `System.trace = true` here right?

**Comment by el-davo** [comment]
Hi Guy

Yes i have System.trace = true. I thought it was a strange thing to happen and i have never seen it happen before.

I initally ran into this issue while trying to look into this issue https://github.com/capaj/systemjs-hot-reloader/issues/49

This line here is where i put the logging - https://github.com/capaj/systemjs-hot-reloader/blob/master/hot-reloader.js#L82 which i believe is meant to create a map of importers from child to parent. However this doesnt seem to be happening on initial load and the importers property on each object is not initially set until you modify a parent and then due to the update the mapping occurs again.

**Comment by guybedford** [comment]
@el-davo perhaps this is due to later mutation? At the time of logging, they were objects, that were then cleared later perhaps?

**Comment by el-davo** [comment]
Hi Guy. Ill dig a little deeper when tonight hopefully and get back to you.
