### ISSUE TITLE
Feature Request: Wildcard in bundles

### ISSUE THREAD

**Issue by justinbmeyer** [systemjs/systemjs#137]
It would be nice to include a bundle of everything in something like jQueryUI without having to specify every single module.  For example:

```js
System.bundles["jqueryui.all"] = ["jqueryui/*"]
```

Any "jqueryui/*" module would be directed to load "jqueryui.all"

```js
System.import("jqueryui/autocomplete");
```

**Comment by milesj** [comment]
`System.paths` do the same thing, no?

https://github.com/systemjs/systemjs/wiki/Basic-Use

**Comment by jpsfs** [comment]
+1 for this feature!

I have the following use case:

```
--| project1
     --| components
         --| component1
              component1.js
     --| stores
         --| store1.js
```

In the end we have a bundle named **project1.js** that has all the components and stores. We need to be able to do something like:

```
import {Component1} from "project1/components/component1/component1"
```

Right now we have to manually add all components and stores to the bundle in order for this to work. Wildcards would be trully great!

Please let me know if there something I can do to help.
Cheers!

**Comment by guybedford** [comment]
The new package configuration feature makes this no longer necessary - when a file in a package is in a bundle, all other requires in that package will wait for the bundle to finish loading, effectively having a similar outcome.

**Comment by guybedford** [comment]
Finally implemented in https://github.com/systemjs/systemjs/commit/b141c9620749817bb999c008b66d33646d9e5678. Despite package config, this can be useful. Note wildcards are not deep in this implementation to ensure specificity.
