### ISSUE TITLE
How To use SystemJs inside NPM package to load it's own dependencies

### ISSUE THREAD

**Issue by jbeckton** [systemjs/systemjs#1370]
We are building a large Angular 2 SPA which will use many Angular 2 Component libraries packaged with NPM. When we load a library into our SPA app we are also required to add configuration for all the dependencies of that component library to our SPA's SystemJs.config. 

Is it possible to keep the SystemJs config inside each NPM packages so that the component library can be responsible for loading it's own dependencies?

**Comment by jbeckton** [comment]
Maybe this is what I am looking for?

https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages

**Comment by guybedford** [comment]
Shared configuration for SystemJS is the problem jspm is attempting to solve, exactly using the above feature.
