### ISSUE TITLE
System.delete System.import not working in Chrome 52.

### ISSUE THREAD

**Issue by ashubham** [systemjs/systemjs#1372]
In jasmine unit tests we do something like a `freshImport`. In the `beforeEach` block we have something like:

```
beforeEach(function(done) {
  freshImport(moduleName).then((m) => {
    // Do something with m;
    done();
  }, (err) => {console.error(err));
})
```
The definition of freshImport is:
```
function freshImport(name) {
  System.delete(System.normalizeSync(name));
  return System.import(name);
}
 ```

This used to work up until Chrome 51. But after upgrading to Chrome 52, the promise
returned from `freshImport` is never resolved, it is always pending. Not even an `err`.
Still works fine in Firefox. I tried in the dev console, basically doing a multiple delete/import cycle seems to be not working for latest Chrome.

An ugly hack which works fine is using a setTimeout(0) between the delete/import.

Any help would be appreciated.

**Comment by guybedford** [comment]
@ashubham perhaps try using a freshImport like this:

```javascript
function freshImport(name) {
  var normalized = System.normalizeSync(name);
  if (System.has(normalized)
    System.delete(normalized);
  return System.import(name);
}
```

there may be some subtle internal race conditions which are affected by subtle engine timing differences due to in-progress loads, although it's difficult to speculate without a reproduction.

**Comment by ashubham** [comment]
@guybedford I was actually able to have consistent reproduction of the issue. Running the following inside the chrome dev console:

```javascript
var f = freshImport.bind('/some/module/path');
f()
  .then(() => {console.log(1); return f();})
  .then(() => {console.log(2); return f();})
  .then(() => {console.log(3); return f();})
```
This outputs only : 
```
1
```
And, I am only seeing two requests being made for the `module` requested (the 2nd request resolves, the promise does not). With the change suggested, it does not even print `1`.

**Comment by guybedford** [comment]
@ashubham I just tested out the suggested:

```javascript
function freshImport(name) {
  var normalized = System.normalizeSync(name);
  if (System.has(normalized))
    System.delete(normalized);
  return System.import(name);
}
```

And it worked fine for me against a module load of a CommonJS module.

Can you perhaps clarify the case that isn't working:

* What module format are you loading?
* Does it have dependencies
* Does the module load correctly, or are there any loading or execution errors?

**Comment by ashubham** [comment]
@guybedford Thanks for testing this out.

- I am using system module format, transpiled from Typescript.
- I tried with both no dependencies and dependencies and the result is the same.
- Yes, just running `f()` multiple times manually works fine. The module loads.

Just to make sure, I am running `Chrome 52.0.2743.82 (64-bit)`.

**Comment by guybedford** [comment]
I just tested this again and it definitely works fine for me.

Perhaps this is an issue with promises.... ensure you're running:

```javascript
var f = freshImport.bind(null, '/some/module/path');
f().then(() => {console.log(1); return f();})
f().then(() => {console.log(2); return f();})
f().then(() => {console.log(3); return f();})
```
