### ISSUE TITLE
build only the changed module and not all 

### ISSUE THREAD

**Issue by Berg-it** [systemjs/systemjs#1373]
Hi, I use (gulp, jspm, systemjs and babel) with ES6 in project Angularjs. the problem that when I change a file I have to gulp task to launch command` jspm bundle-sfx app/bootstrap app/bootstrap.bundle.js ` to create each time the bundle where take few seconde. There's any solution to resolve this kind of problem?

**Comment by guybedford** [comment]
Answered in https://github.com/jspm/jspm-cli/issues/1996.
