### ISSUE TITLE
Bundle loading performance issue on Adnroid

### ISSUE THREAD

**Issue by SergeRNR** [systemjs/systemjs#1375]
Hello,

I see noticeable performance issues on Android Chrome while loaded bundle registers the modules it contains. The bundle contains main "app.js" file with 1000 modules imported. Each module contains simple object literal with single string property. So no there is no complex script execution inside modules.
On desktop the script is evaluated ~500 ms.
In Chrome on Android the script is evaluated ~2.2-2.5 s.

Is there a way to speed up parsing ?

**Comment by guybedford** [comment]
1000 modules is a lot. Performance improvements will be coming in subsequent versions, but until then I'd suggest using SFX bundles to minimize the public registry overhead.

**Comment by SergeRNR** [comment]
SFX bundles give a performance boost. 800-1000 ms for evaluating is much better (vs 2200).
