### ISSUE TITLE
require does not work with TypeScript transpiler

### ISSUE THREAD

**Issue by httpdigest** [systemjs/systemjs#1376]
I have the following minimal Angular 2 application. The result is the error `zone.js:323 Error: (SystemJS) ReferenceError: require is not defined(…)`:
**app.ts**:
```JavaScript
import { bootstrap } from "@angular/platform-browser-dynamic";
import { Component } from '@angular/core';
@Component({
  selector: 'my-app',
  template: require('template.html')
})
export class AppComponent {}
bootstrap(AppComponent, []);
```
**systemjs.config.js**:
```JavaScript
(function () {
  const conf = {
    typescriptOptions: {
      module: "system",
      target: "es2015",
      emitDecoratorMetadata: true,
      experimentalDecorators: true
    },
    map: {
      '@angular': '../node_modules/@angular',
      'rxjs':     '../node_modules/rxjs'
    },
    transpiler: 'typescript',
    packages: {
      'rxjs': {defaultExtension: 'js'},
      '@angular/platform-browser-dynamic': { main: 'index.js', defaultExtension: 'js'},
      '@angular/common': { main: 'index.js', defaultExtension: 'js'},
      '@angular/core': { main: 'index.js', defaultExtension: 'js'},
      '@angular/compiler': { main: 'index.js', defaultExtension: 'js'},
      '@angular/platform-browser': { main: 'index.js', defaultExtension: 'js'},
      '@angular/platform-browser-dynamic': { main: 'index.js', defaultExtension: 'js'}
    }
  };
  System.config(conf);
})();
```
**index.html**:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="node_modules/zone.js/dist/zone.js"></script>
  <script src="node_modules/reflect-metadata/Reflect.js"></script>
  <script src="node_modules/systemjs/dist/system.js"></script>
  <script src="node_modules/typescript/lib/typescript.js"></script>
  <script src="systemjs.config.js"></script>
  <script>
    System.import('main.ts').then(null, console.error.bind(console));
  </script>
</head>
  <body>
    <my-app>Loading...</my-app>
  </body>
</html>
```
When I change the `require('template.html')` to a simple `'<h3>It works!</h3>'`, then everything works correctly.

I am using TypeScript 2.0.0. Could it be that `require` does not work when using the TypeScript transpiler? My question is, because when I use `require` with a JavaScript application, then everything works fine (although not an Angular 2 application).

Any help is greatly appreciated!

**Comment by guybedford** [comment]
Yes the Node require is not defined inside of ES modules because SystemJS treats every module as a single module format, and does not support two-phase linking.

**Comment by httpdigest** [comment]
Thanks for your quick reply! But why does a single `require` work when I use a simple JavaScript file?

**Comment by guybedford** [comment]
It will work if you're not using ES module syntax so SystemJS can just treat it as CommonJS.

**Comment by httpdigest** [comment]
I'm not quite sure that I fully understand. (I have very little experience with TypeScript and ES modules and CommonJS modules). But how I understand it is that the TypeScript transpiler can be configured to produce output in a certain module format. And I also set it to "system", which as I thought meant "systemjs". So it should have been compatible with how systemjs works.
However, if I configure the transpiler to output "commonjs" format, then it also does not work with "require". Do you have any information regarding this behaviour?

**Comment by httpdigest** [comment]
Closing this because it is not relevant to me anymore (switched to Webpack).
