### ISSUE TITLE
Checking for buffer causes a break on caught exceptions during debugging.

### ISSUE THREAD

**Issue by EricABC** [systemjs/systemjs#1381]
On [this](https://github.com/systemjs/systemjs/blob/3d097d90485a3ceaf5751b5b2709ab7606502105/lib/global-eval.js#L9) line.

Changing to
```js
if (hasBuffer && new Buffer('a').toString('base64') != 'YQ==')
```
would solve it.

**Comment by guybedford** [comment]
Sure, no problem, I've included that.

**Comment by EricABC** [comment]
Thanks!
