### ISSUE TITLE
Unable to load bundled builds from a remote package

### ISSUE THREAD

**Issue by thekhoi** [systemjs/systemjs#1382]
I'm trying to load an angular package from a remote CDN URL. The angular assets are compiled w/ the angular CLI using the -prod flag.  This will generate named modules:

`System.register("main.js",[],function(a,b){...});`

The following is from the system-config file in the host application (http://localhost:4200).

```
{
  map: {'sharedcomponent':'http://mycdn.com/shared-component'}
  packages: {
    "http://mycdn.com/shared-component": {
      "main": "main.js",
      "meta": {
        "*": {
          "format": "system",
          "scriptLoad": true
      }
    }
  }
```
The host application is later importing the component returns an empty object.

```
System.import('sharedcomponent')
  .then(function(comp){
    console.log(comp); //outputs {}
  });
```

When inspecting SystemJS.defined in the console, I can see all the bundled modules loaded under the 'localhost:4200' domain rather than the CDN domain.

However if I deploy a non bundled build with anonymous modules, every thing loads correctly.

Can anyone provide any insight? Is this an issue w/ the systemjs or the angular CLI?

**Comment by thekhoi** [comment]
An update with additional information. There is a name 'collision' for 'main.js' in the host application and the remote package.

If i remove the collision, the remote package loads correctly.

**Comment by guybedford** [comment]
Sounds like you've sorted out the issue? Does the fox make sense to you
here?

**Comment by thekhoi** [comment]
> Sounds like you've sorted out the issue? Does the fox make sense to you
here?

No, I deleted my earlier comment because I mistakenly copied over the un-bundled instead of the bundled file.

It's still an issue.

**Comment by guybedford** [comment]
You'd want the register statements to look like:

```javascript
System.register("shared-component/main.js",[],function(a,b){...});
```

Then the pathing should work out ok.

**Comment by thekhoi** [comment]
The angular CLI does output in that format. Debugging through the code, url resolution using the baseURIObject when the module is registered and pushed to the queue.

I think url resolution should happen in the reduce step since you have access to the requested module address.

**Comment by guybedford** [comment]
You need to import the modules by the same name that they are registered as. So if it is `System.register('angular/x')` then you need to import by that name (`System.import('angular/x')`) after loading the bundle into SystemJS.

**Comment by thekhoi** [comment]
Well this is a problem then. This would mean you have to namespace everything that needs to be shared. You wouldn't be able to import using relative paths even in the same package if you intend to load the package from a remote host.

Is this why the angular team stopped hosting angular builds on code.angularjs.org when they started using relative paths?

**Comment by thekhoi** [comment]
> You'd want the register statements to look like:
>
> System.register("shared-component/main.js",[],function(a,b){...});
> Then the pathing should work out ok.

Is there a switch in systemjs builder to do this?

**Comment by thekhoi** [comment]
OK i have a work around for this issue.

After systemjs loads, I overwrote the System.register function so that it doesn't decanonicalize the name.

```
    System.register = function(name, deps, declare) {
      if (typeof name != 'string') {
        declare = deps; deps = name; name = null;
      }

      if (typeof declare == 'boolean')
        return this.registerDynamic.apply(this, arguments);

      this.pushRegister_({
        amd: false,
        entry: {
          name: name,
          deps: deps,
          declare: declare,
          declarative: true,
          executingRequire: false,
          esmExports: false,
          evaluated: false,
          originalIndices: null,
          execute: null,
          normalizedDeps: null,
          groupIndex: null,
          module: null,
          esModule: null
        }
      });
    };
```

I then overwrote the reduceRegister_ function to look for a metadata flag to determine if the decanonicalize method should be used to resolve the module name.

If it is set to false, I simply resolve the name using the load.address vs. the base URL object.
```
    System.reduceRegister_ = function(load, register){
      if (register) {
        let entry = register && register.entry;
        entry.name = (load.metadata && load.metadata.decanonicalize === false) ?
          new URL(entry.name, load.address).href.replace(/%05/g, '#') :
          this.decanonicalize(entry.name, load.address);
      }
      this.__proto__.reduceRegister_.call(this, load, register);
    }
```

The package configuration is here:

```
{
  map: {'sharedcomponent':'http://mycdn.com/shared-component'}
  packages: {
    "http://mycdn.com/shared-component": {
      "main": "main.js",
      "meta": {
        "*": {
          "format": "system",
          "scriptLoad": true,
          **"decanonicalize":false**
      }
    }
  }
```
