### ISSUE TITLE
Is there an api method to normalize paths to sub-dependencies

### ISSUE THREAD

**Issue by npbenjohnson** [systemjs/systemjs#1384]
I need this to write an import path-resolver for a sass builder. Example would be:
```
{
  map: {
    "mysassmodule": "repo:mysassmodule@1.0.0",
    "repo:mysassmodule@1.0.0": {
       "thirdpartysasslib": "repo:thirdpartysasslib@0.1.0"
    }
  }
}
```

Is there any way to get thirdpartysasslib to resolve to a folder (with a normalize call or otherwise) without making it a direct dependency of this project?

**Comment by guybedford** [comment]
I'm not sure I follow the context here. You want System.normalize to do
this for you, which you are configuring to be used by a sass resolver?

If so you could just have thirdpartysasslib at the base level as well.

map: {
thirdpartysasslib: x
}

**Comment by npbenjohnson** [comment]
That is how I'm doing it now, but it partially defeats the purpose of having sass compose its own dependency tree if you have to manually manage the dependencies at the base level, so I was just hoping maybe something exists that can look up references in the sub-dependencies.

I do have an idea for a workaround which would involve re-loading systemjs against whichever package is currently being scanned, but I don't have the time to try that out right now. Here's the relevant code, it runs as a node-sass resolver:

``` js
	_resolveSystemJsPath(filePath) {
		// Replace jspm:
		filePath = filePath.replace(/^sys:/, '');
		// normalize systemjs file:// value and return
		return SystemJs.normalize(filePath)
			.then(fileUrl => decodeURIComponent(url.parse(fileUrl).pathname.replace(/\.js$|\.ts$/, '')).replace('/', path.sep))
			.then(filePath => /^win/.test(process.platform) ? filePath.slice(1) : filePath)
	}

	// This is a resolver in the format lib-sass excepts to resolve imports
	// turns @import 'sys:[insert jspm reference here]' into a file path
	_sassImportResolve(current, previous, done) {
		const self = this;
		let promise = null
		if(/^sys:/.test(current))
			promise = this._resolveSystemJsPath(current) // Resolve systemjs
		else if(!/http[s]?:\/\//.test(current))
			promise = Promise.resolve(path.resolve(path.dirname(previous), current)) // Resolve filesystem
		else
			return done(console.warn('No path handler for file, letting sass-importer handle', current))

		promise.then(file => self._findMatchingFile(file))
			.then(foundFile => {
				if(foundFile)
					return fs.readFile(foundFile, 'utf8').then(contents => ({
						file: foundFile,
						contents: contents
					}))
				console.warn('File not found, letting sass-importer handle', current)
			})
			.then(result => done(result))
			.catch(err => done(new Error(err)))
	}
```

**Comment by guybedford** [comment]
For the subdependencies case you just want to pass two arguments to `System.normalize` I think? `System.normalize(filePath, pathToFileUrl(parentPath))`. A resolver is always composed of these two arguments, although let me know if I'm missing anything here.
