### ISSUE TITLE
Promise polyfill not as good as native for chrome debugging

### ISSUE THREAD

**Issue by mavericken** [systemjs/systemjs#1388]
The system-polyfills.js overwrites Promise always.  I have read this is because some browsers have poor native implementations.  However, when debugging with chrome, the native Promise has superior debugging capabilities, including sourcemapped async stack traces (whereas the polyfill Promise doesn't appear to look at sourcemaps).

I believe that (at least when production flag is false), system-polyfills.js should use the native promise available, so that developers automatically get the full native promise debugging capabilities afforded to them without having to figure this out themselves.

**Comment by guybedford** [comment]
If you want to use native promises, then skip including the system-polyfills.js file altogether. This file will be removed in the next major, to assume manual management of the Promise global.
