### ISSUE TITLE
file paths all getting prepended with undefined

### ISSUE THREAD

**Issue by oppianmatt** [systemjs/systemjs#1390]
By that I mean chrome dev tools thinks the files I load with systemjs have undefined as part of the name, but they still work:

![image](https://cloud.githubusercontent.com/assets/48596/17327748/b4d5a10a-58b1-11e6-9cd1-ba5b2c99d277.png)

For example I load a main like so:

```
<script>SystemJS.import('/static/js/main-search.f89ebe387b74.js');</script>
```

It fetches the right file:

![image](https://cloud.githubusercontent.com/assets/48596/17327782/e77d9f04-58b1-11e6-85d1-6756b128a8e9.png)

But then chrome thinks the name is main-search.f89ebe387b74.jsundefined: 
![image](https://cloud.githubusercontent.com/assets/48596/17327811/107a29d6-58b2-11e6-8924-aa6fe85d3fa8.png)

Which would be ok to ignore, except it breaks the javascript error reporting.

**Comment by oppianmatt** [comment]
SystemJS v0.19.33

**Comment by guybedford** [comment]
Which version of SystemJS are you using here? Make sure you're running the latest.

**Comment by oppianmatt** [comment]
I don't use a baseurl, all modules are configured to direct paths using map. No transpiling. Mix of AMD format and globals (with some libraries UMD).

**Comment by guybedford** [comment]
Make sure to use SystemJS 0.19.36.

**Comment by oppianmatt** [comment]
looks like that fixes it, thanks!

**Comment by guybedford** [comment]
Sure!
