### ISSUE TITLE
Mocha 3.0.0: "child_process" module is not available in the browser

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#1393]
I am using the latest version of jspm `0.17.0-beta.25` and installed `npm:mocha@^3.0.0` in my project. At runtime I see following error in my Browser console:

```
system.js:4 Uncaught (in promise) Error: (SystemJS) The NodeJS "child_process" module is not available in the browser.
	Error: The NodeJS "child_process" module is not available in the browser.
	    at eval (http://localhost:7357/jspm_packages/github/jspm/nodelibs-child_process@0.2.0-alpha/child_process.js:1:7)
	    at Object.eval (http://localhost:7357/jspm_packages/npm/growl@1.9.2/lib/growl.js:7:36)
	    at eval (http://localhost:7357/jspm_packages/npm/growl@1.9.2/lib/growl.js:292:4)
	    at eval (http://localhost:7357/jspm_packages/npm/growl@1.9.2/lib/growl.js:293:3)
	Evaluating http://localhost:7357/jspm_packages/github/jspm/nodelibs-child_process@0.2.0-alpha/child_process.js
	Evaluating http://localhost:7357/jspm_packages/npm/growl@1.9.2/lib/growl.js
	Error loading http://localhost:7357/src/index.js
```

With Mocha `v2.5.3` everything works fine.

**Comment by screendriver** [comment]
Update: with Mocha `v2.5.3` it doesn't work. The error message above disappears but I can't call any functions like `mocha.setup()` or `mocha.run()`. Could it be that Mocha will be installed like an Node.js package and not a Browser package so it can't run in the Browser?

**Comment by guybedford** [comment]
The override for Mocha 3 was added in https://github.com/jspm/registry/commit/08ba220bfdbf80006214c011c55ff9c9bbc50289.

Note that in jspm 0.17 we return the `Mocha` class as that is a much better approach than to have a mutable instance module.

**Comment by screendriver** [comment]
Thank you.

Ah ok I understand. Then I have to do a

```js
const mocha = new Mocha({
  ui: 'bdd'
});
mocha.run();
```

and everything works 👍 But one little question: how do I import `describe` and `it` and so on? A `import { describe, it } from 'mocha'` does not work (`undefined`). If I write `describe` as before without imports (as globals) it complains that it can not find it.

**Comment by guybedford** [comment]
@screendriver perhaps have a look at the BDD section in http://guybedford.com/systemjs-mocha-istanbul.

**Comment by screendriver** [comment]
Hmm ok. That's not working as well 😕  I tried a

```js
runner.suite.emit('pre-require', global, 'global-mocha-context', runner);
```

but where does the variable `global` came from? My browser tells me that it can not find it (`global is not defined`).

**Comment by guybedford** [comment]
Replace that with `window` in the browser.

**Comment by screendriver** [comment]
Thank you very much. It's working now! All of this should definitively be added somewhere in the docs 😉 Especially things like that one

> Note that in jspm 0.17 we return the Mocha class as that is a much better approach than to have a mutable instance module.
