### ISSUE TITLE
System.set not working in my unit tests

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#1395]
I am using the latest jspm beta `0.17.0-beta.25`. With the latest stable `0.16` everything works.
I wrote some unit tests and mock some of the module dependencies with [Sinon.js](http://sinonjs.org). My tests look like this:

#### index.js

```js
import { bar } from '@me/foo-package';

export function doIt() {
  if (bar.something()) {
    // ...
  }
}
```

#### index-test.js

```js
describe('index-test', () => {
  let index;

  before(async () => {
    System.set(System.normalizeSync('@me/foo-package'), System.newModule({
      bar: {
        something: sinon.stub().returns(false)
      },
    }));
    index = await System.import('src/index');
  });

  after(() => {
    // Delete package so that other tests don't load this mock
    System.delete(System.normalizeSync('@me/foo-package'));
  });

  it('should do anything', () => {
    // ...
  });
});
```

With this code I can mock `@me/foo-package` and can change the behaviour of the code to test. With jspm `0.16` this worked fine for me all the time. But with `0.17-beta` the package `@me/foo-package` gets loaded like any other usual dependency. Thus it doesn't load my mock module that I set with `System.set()`.

**Comment by guybedford** [comment]
To check you're normalizing correctly, it may help to inspect the registry via `Object.keys(System._loader.modules)` to see why the naming isn't matching up. I expect you'll see two entries containing the name `@me/foo-package`.

**Comment by screendriver** [comment]
`Object.keys(System._loader.modules)` results in

```
http://localhost:3000/jspm_packages/npm/@me/foo-package@1.2.0
http://localhost:3000/jspm_packages/npm/@me/foo-package@1.2.0.json
http://localhost:3000/jspm_packages/npm/@me/foo-package@1.2.0/index.js
```

**Comment by guybedford** [comment]
So try `System.set(System.normalizeSync('@me/foo-package/index.js')`.

**Comment by screendriver** [comment]
Ok, it works. Cool. But now I have to rewrite *all* of my unit tests. Are there any plans to change this behaviour?

**Comment by guybedford** [comment]
Better is to use `System.normalize` over `System.normalizeSync`... because `normalizeSync` can't load package configurations.

**Comment by guybedford** [comment]
OR ensure the package configurations have already loaded before mocking.

**Comment by screendriver** [comment]
When I do a

```js
System.set(System.normalize('@me/foo-package'), System.newModule({
  bar: {
    something: sinon.stub().returns(false)
  },
}));
```

it does not work anymore. Same with `System.normalize('@me/foo-package/index.js')`. It only works when I use `System.normalizeSync`.

Package configuration is already loaded before.

<details>
```html
<!doctype html>
  <script src="jspm_packages/system.src.js"></script>
  <script src="jspm.config.js"></script>
  <div id="mocha"></div>
  <script>
    SystemJS.import('./test-runner.js');
  </script>
```
</details>

**Comment by guybedford** [comment]
`System.normalize` returns a promise.

**Comment by screendriver** [comment]
Hmm ok. It's getting complicated for such a simple task like mocking dependencies for every test. The solution for all other readers:

```js
before(async () => {
  System.set(await System.normalize('@me/foo-package'), System.newModule({
    something: sinon.stub().returns(false)
  }));
  this.awesomeFunc = (await System.import('@me/testme')).awesomeFunc;
});
```

**Comment by screendriver** [comment]
By the way: if you want help when you write docs about that I would help you.
