### ISSUE TITLE
dist/system-register-only.js does not include config api

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1398]
I wanted to test and see if `system-register-only.js` build is any faster, but it turns out it does not include `System.config()` api (`lib/core.js` I assume). Is this by design? What's the scenario in which this can be used?

**Comment by guybedford** [comment]
Originally this build was meant as something closer to the simplest possible production workflow on top of the es6 module loader polyfill project. It could well be worth adding to the features to get something closer to a minimal SystemJS build, although System CSP production is currently pretty close to that.

**Comment by laurentgoudet** [comment]
I'd be personally interested by a `System.register`-only variant of the System CSP build, as I can't use the later as part of our stack still uses RequireJS (which the System CSP build interferes with), while the former is too limited (no `System.config`)

**Comment by guybedford** [comment]
Yes, perhaps we do need a full-config system-register CSP build.

It would be straightforward to adjust the makefile to provide this. But there are loading edge cases that may need to be considered carefully.
