### ISSUE TITLE
Intercept module import

### ISSUE THREAD

**Issue by ZoolWay** [systemjs/systemjs#1401]
I would like to intercept with the module loading and already have created a StackOverflow question worth some bounty. As there are no approaches there yet I would like to hear if anyone here might have an idea?

http://stackoverflow.com/questions/38766824/javascript-intercept-module-import

> I have a SPA (in Aurelia / TypeScript but that should not matter) which uses SystemJS. Let's say it runs at `http://spa:5000/app`.
> 
> It sometimes loads JavaScript modules like `waterservice/external.js` on demand from an external URL like `http://otherhost:5002/fetchmodule?moduleId=waterservice.external.js`. I use `SystemJS.import(url)` to do this and it works fine.
> 
> But when this external module wants to import another module with a simple `import { OtherClass } from './other-class';` this (comprehensiblely) does not work. When loaded by the SPA it looks at `http://spa:5000/app/other-class.js`. In this case I have to intercept the path/location to redirect it to `http://otherhost:5002/fetchmodule?moduleId=other-class.js`.
> 
> Note: The Typescript compilation for `waterservice/external.ts` works find because the typescript compiler can find `./other-class.ts` easily. Obviously I cannot use an absolute URL for the import.
> 
> How can I intercept the module loading inside a module I am importing with SystemJS?
> 
> One approach I already tested is to add a mapping in the SystemJS configuration. If I import it like `import { OtherClass } from 'other-class';` and add a mapping like `"other-class": "http://otherhost:5002/fetchmodule?moduleId=other-class"` it works. But if this approach is good, how can I add mapping dynamically at runtime?
> 
> Other approaches like a generic load url interception are welcome too.

**Comment by ZoolWay** [comment]
Still a support question. On the StackOverflow question I updated with some insights like multiple calls to `SystemJS.config()` are possible.

But trying to intercept `SystemJS.normalize` with just logging and calling the default implementation results in *Uncaught (in promise) TypeError: this.has is not a function* inside `system.js`.

Code would be
```
var systemLoader = SystemJS;
var defaultNormalize = systemLoader.normalize;
systemLoader.normalize = function(name, parentName) {
    console.error("Intercepting", name, parentName);
    return defaultNormalize(name, parentName);
}
```

**Comment by asapach** [comment]
Try instead of:
```js
return defaultNormalize(name, parentName);
```
do this:
```js
return defaultNormalize.call(systemLoader, name, parentName);
```

**Comment by ZoolWay** [comment]
@asapach Works, thanks!
