### ISSUE TITLE
Add support for the new rc.5 angular2 lazy loading with hot-reload...

### ISSUE THREAD

**Issue by born2net** [systemjs/systemjs#1402]
Angular2 released this week new support for lazy loading and modules.
https://angular.io/docs/ts/latest/guide/ngmodule.html

And while it does work well with systemjs, it does not support lazy loading with hot-reload!
So if you make a change in a lazy loaded module, hot-reload does not reload the module nor the component that the change was made in...

I think all it would take is just to recognize that a component is part of the build process even though it's not in the source code.  What angular2 does is use the router to load a component via a string, such as 

```
const appRoutes: Routes = [{
    path: '',
    component: EntryPanel
}, {   path: 'LazyLoad',
        loadChildren: 'src/comps/app1/lazyone/LazyOneModule'
    }, {
```

notice that LazyOneModule is referenced simply as a string, and so obviosuly if a change was made, the local server does not know it needs to reload the related component... 
A solution would be to somehow parse the router or to somehow via a "hack" let the local server and thus hot-reload force a reload of related component tree. 

Regards,

Sean - http://DigitalSignage.com

**Comment by guybedford** [comment]
Thanks for following this use case. I guess we need to hook into the module
reload event from the angular side then? This is something that could
probably use the help of contributions to work out the best integration
path forward. If you have any ideas I'd be interested to hear.

**Comment by born2net** [comment]
while I am not an expert in the internals of systemjs I would be happy to contribute time in testing whatever solution you guys come up with. And Hot-reload is the "killer app" for systemjs so I hope we can have a solution to test soon, as ngModules now play a MAJOR role in Angular 2 (all components now load through ngModules)

regards

**Comment by guybedford** [comment]
@born2net unfortunately I won't personally be working on this anytime soon and I'm not sure I know of anyone who is.

**Comment by jcmoore0** [comment]
@born2net - I am successfully using hot reloader with lazy loaded modules. 
If I make a change to an html file used in a lazy loaded module, it refreshes in <1 second.


**app.routing.ts**
export const routes: Routes = [
   { path: '', redirectTo: 'home', pathMatch: 'full'},
   { path:'examples', loadChildren:'app/examples/examples.module#ExamplesModule'}
];


**main.ts**
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule);

// Hot Reloader
window['hr'] && window['hr'].on('change', (fileName) => {
    if (fileName.indexOf('html') !== -1) {
        var newBody = document.createElement('body')
        newBody.appendChild(document.createElement('my-app'))
        document.body = newBody;
        platformBrowserDynamic().bootstrapModule(AppModule);
    }
})

**Comment by born2net** [comment]
yes but try and modify a component file, works?
this is my code

```
}
platformBrowserDynamic().bootstrapModule(App, modules).then((appRef: NgModuleRef<any>) => {
    appInjService(appRef.injector);
});

window['hr'] && window['hr'].on('change', (fileName) => {
    if (fileName.indexOf('html') !== -1) {
        var newBody = document.createElement('body')
        newBody.appendChild(document.createElement('app'))
        document.body = newBody;
        platformBrowserDynamic().bootstrapModule(App, modules).then((appRef: NgModuleRef<any>) => {
            appInjService(appRef.injector);
        });
    }
})
```
