### ISSUE TITLE
CORS request with systemjs not sending OPTIONS request

### ISSUE THREAD

**Issue by Andrewsturick** [systemjs/systemjs#1403]
Hello,

I am trying to import angular2 app code with system.import from crossDomain CDN

We are pointing to correct CDN endpoint as console is showing error : 

XMLHttpRequest cannot load ... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin.... is therefore not allowed access.

zone.js:323 Error: Error: XHR error loading ......

Our network tab shows that request is being made without   OPTIONS request happening first, and it is my understanding that we need for this OPTIONS request to take place first so that we can receive proper headers from server to send with our request...

I have also tried setting scriptLoad in meta object of config object.

Thanks for your help in advance, have been struggling with this for 2 days now and we cannot understand why OPTIONS request seems to  be skipped by browser from systemjs XHR request...

Cheers!
Andrew

**Comment by asapach** [comment]
There's no need to send `OPTIONS` for a simple `GET` request: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests
Your CDN probably simply doesn't have CORS enabled, or they might be white-listing the origins it's enabled for.

**Comment by Andrewsturick** [comment]
var   meta = {  
              app : {
                  "scriptLoad": true,
                  "format"       : "global",
                  "exports"      : "app"
              }
        };



    var  map = {
                   'app'          : ' https://mycdn.com/app'
           };
    
    var packages = {
        'app'           :         {main: 'main.js'}
    };

**Comment by Andrewsturick** [comment]
sorry can you clarify, what do you mean by may be white listing the origins it's enabled for?

**Comment by Andrewsturick** [comment]
Also worth noting, our CDN is serving all of our other resources just fine, for example our es6 shim and zone.js are being served from our same CDN successfully

The issue is only the request for app code made through systemjs..

Doesn't this mean that our CDN is allowing CORS since other requests from same url are working as long as they are not made by systemjs?

**Comment by asapach** [comment]
How are you loading the other resources? `<script>` tags don't require CORS. XHR does.

**Comment by Andrewsturick** [comment]
yes other resources are loaded through <script> tags

can you see my above posted meta information to see if I can modify that so systemjs performs request with script tag?

Seems my configuration above is still sending XHR requests

**Comment by asapach** [comment]
As for white-listing, the server can either respond with `Access-Control-Allow-Origin: *` to enable CORS for all origins, or `Access-Control-Allow-Origin: http://foo.example` for a specific origin, or omit the header, thus disabling CORS.

**Comment by Andrewsturick** [comment]
yes other resources are loaded through <script> tags

can you see my above posted meta information to see if I can modify that so systemjs performs request with script tag?

Seems my configuration above is still sending XHR requests

**Comment by Andrewsturick** [comment]
yes other resources are loaded through script tags

can you see my above posted meta information to see if I can modify that so systemjs performs request with script tag?

Seems my configuration above is still sending XHR requests

**Comment by asapach** [comment]
I see you have `scriptLoad` meta enabled for your app - this allows `register` and `amd` format modules to be loaded as `<script>` tags, but it doesn't work for `cjs` and `global` format. You need XHR to load those.

**Comment by Andrewsturick** [comment]
Sorry I don't quite understand the global format, "app" just bootstraps my angular2 app, can I change the global format to register?

**Comment by asapach** [comment]
Please read this first: https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md

**Comment by Andrewsturick** [comment]
Sorry, so just to clarify on the above reading material, if my main.js uses System.register to load dependencies, should I declare the format as register?

I'm still not entirely sure I understand...I first tried removing format property and letting default regex methods do their work, but is still performing XHR request....

I also just set format to "register" as our main.js has System.register in first line and is still performing XHR request

**Comment by Andrewsturick** [comment]
so if it is defaulting to global format, and our CDN has for white listed our url (other requests from our URL are working fine) got any other ideas?

**Comment by Andrewsturick** [comment]
I also removed the export property, as my main.js is not exporting a module

**Comment by Andrewsturick** [comment]
my main.js looks as follows: 

import angular from 'angular;
import 'uiBootstrap';

........

var requires = [....]
angular.module('myApp', requires)

angular.bootstrap(document.body , ['myApp'])

export default app;


Do these import exports done with ES6 default the format to ES? Is this why our requests are XHR though scriptLoad is true?

**Comment by Andrewsturick** [comment]
and if so, is there a workaround to perform scriptLoad requests?

**Comment by asapach** [comment]
To make it work you need to transpile your code into `register` format, e.g. using [`transform-es2015-modules-systemjs`](https://babeljs.io/docs/plugins/transform-es2015-modules-systemjs/) for babel. If you really want to use it in production and deploy it to a CDN you should bundle your code using e.g. [`jspm bundle --inject`](http://jspm.io/docs/production-workflows.html).
Then you need to configure SystemJS to load your modules/bundles using `<script>` tags:
```js
System.config({
  packages: {
    "app": {
      "meta": {
        "*.js": {
          "format": "register",
          "scriptLoad": true
        }
      }
    }
  });
```

**Comment by guybedford** [comment]
I think you can get SystemJS to send the preflight CORS request when using
xhr with the metadata:

System.config({
meta: {
'*': {
authorization: true
}
}
})

If that doesn't work though just let me know.
