### ISSUE TITLE
Problem with template literals

### ISSUE THREAD

**Issue by Thomas-P** [systemjs/systemjs#1404]
Hi,

it themes that there is a problem with using template literals with SystemJS. 

```javascript
"use strict";
/**
 * Created by Thomas-P on 14.08.2016.
 */
const x = 2;
function test() {
    return `test ${x}`;
}
exports.test = test;
```
will become

```javascript
(function(System, SystemJS) {(function(require, exports, module, __filename, __dirname, global, GLOBAL) {"use strict";
/**
 * Created by Thomas-P on 14.08.2016.
 */
var x = 2;
function test() {
    return `test ${ + x;
}
exports.test = test;

}).apply(__cjsWrapper.exports, __cjsWrapper.args);
})(System, System);
```

It looks like System will convert the template literals to string, but forget to replace the backticks and the replacement of '${' and also '}' with a string delimiter.
So it will also convert:
```javascript
`test ${x} test 2`;
```
to a not parseable version:
```javascript
return `test ${ + x + } test 2`;
```

**Comment by guybedford** [comment]
Thanks for posting. Which version of systemjs builder are you using here?
