### ISSUE TITLE
Failed to import 'lazy.js'

### ISSUE THREAD

**Issue by GiedriusGrabauskas** [systemjs/systemjs#1406]
Cannot import `lazy.js` package with original name.

SystemJS version: `v0.19.36`
Jspm version: `v0.17.0-beta.25`
Package: https://www.npmjs.com/package/lazy.js

package.json:
```json
{
   "jspm": {
      "dependencies": {
         "lazy.js": "npm:lazy.js@^0.4.2"
      }
   }
}
```
Script:
```ts
System.import("lazy.js").then((r)=> {
  console.log(r);
}).catch(e => {
  console.log(e);
});
```
Error:
```cmd
Error: (SystemJS) Invalid JSON file http://127.0.0.1/jspm_packages/npm/lazy.js@0.4.2.js.json
	Error: Invalid JSON file http://127.0.0.1/jspm_packages/npm/lazy.js@0.4.2.js.json
	Error loading http://127.0.0.1/jspm_packages/npm/lazy.js@0.4.2.js.json
```

**Comment by guybedford** [comment]
This sounds like a jspm issue with a corrupted install if `http://127.0.0.1/jspm_packages/npm/lazy.js@0.4.2.js.json` is not valid JSON. Perhaps try `jspm install npm:lazy.js -f`

**Comment by GiedriusGrabauskas** [comment]
`DefaultJsExtension: true` add `.js` extension after version:
```
lazy.js@0.4.2.js.json
              ^^
```
And this is not jspm issue with install, because file exist with name `lazy.js@0.4.2.json`
So, the solution is to use `DefaultExtension: 'js'`.

**Comment by guybedford** [comment]
@GiedriusGrabauskas are you using `defaultExtension: 'js'` or `defaultJSExtensions: true` somewhere here then?

**Comment by GiedriusGrabauskas** [comment]
I get this error with `defaultJsExtensions: true`.

**Comment by guybedford** [comment]
@GiedriusGrabauskas `defaultJSExtensions: true` is not supported in jspm 0.17.
