### ISSUE TITLE
Accessing build-specific configuration in code?

### ISSUE THREAD

**Issue by skorlir** [systemjs/systemjs#1407]
Hey @guybedford, trying to set up a "stage" variable in our SystemJS + JSPM project for configuring what deployed stage of our API we want the Angular app to send its requests to. We would like to use 

```js
System.config({ stage: 'test' })
```

But we can't figure out how to access this variable in our own code. I had hoped, at first, that we might be able to

```js
import * as env from '@system-env'
```

But this only contains flags for node vs. browser, dev vs. production.

How can we import and access build-specific configuration variables in our code?

I tried to read the docs, but failed to find an answer.

Thanks in advance!

**Comment by guybedford** [comment]
You could try something like -

```javascript
System.set('@custom-env', System.newModule({
  stage: 'test'
});
```

With `import {stage} from '@custom-env'`.

**Comment by skorlir** [comment]
We'll try that - thanks!
