### ISSUE TITLE
The Regex which is used to detect "import"-statements will detect import-statements within multiline-comments

### ISSUE THREAD

**Issue by tobias74** [systemjs/systemjs#1408]
`  var esmRegEx = /(^\s*|[}\);\n]\s*)(import\s*(['"]|(\*\s+as\s+)?[^"'\(\)\n;]+\s*from\s*['"]|\{)|export\s+\*\s+from\s+["']|export\s*(\{|default|function|class|var|const|let|async\s+function))/;
`

This regex will detect statements like:
`import { SomeThing } from "./myfile"`

even in case they are wihtin a multiline-comment-block

/*
import { Something } from "./myfile"
*/

This behaviour can lead to very-hard-to-debug errors like these documented on Stackoverflow:

[http://stackoverflow.com/questions/37179236/angular2-error-at-startup-of-the-app-http-localhost3000-traceur-404-not-fo/37181985#37181985](http://stackoverflow.com/questions/37179236/angular2-error-at-startup-of-the-app-http-localhost3000-traceur-404-not-fo/37181985#37181985)

and

[http://stackoverflow.com/questions/37022526/angular-2-404-traceur-not-found](http://stackoverflow.com/questions/37022526/angular-2-404-traceur-not-found)

EDIT:
Here a short description how this causes errors:

While working on a typescript-file wihtin an angular-project I commented out some lines of import-statements. The typescript-compiler then just copied these multiline-comments into the compiled js-files. When loading the app in the browser, systemjs would identify these import-statements in those comment-blocks and try to act on them. This leads to a hard-to-understand error-message: "404 traceur not found"

**Comment by guybedford** [comment]
Yes this is the way module format detection works in SystemJS. I've added a more useful error message here in https://github.com/systemjs/systemjs/commit/bac2cc52bef77c2e38a831e726fe644e625ec524.

**Comment by RohitRane** [comment]
I am getting this error in the browser : 
Unable to load transpiler to transpile http://localhost:8080/LKMonitoring/node_modules/@angular/http/index.js

But I don't see any block comments or import statements in this file!
Above all this is not even my code but core angular 2 library code.

How do I resolve this?

**Comment by fictitious** [comment]
@RohitRane but there is `export` statement in that file, so it still needs to be transpiled. You probably need to use angular bundle for their http module which is in node_modules/@angular/http/bundles/http.umd.js

**Comment by zapping** [comment]
I faced a similar issue with comments on the import section. 
http://stackoverflow.com/questions/40677324/comments-in-angular2
https://github.com/angular/angular/issues/12967

**Comment by guybedford** [comment]
PRs are welcome to handle these edge cases better. Note that explicitly defining the module format for folders by meta configuration is encouraged as well.
