### ISSUE TITLE
SystemJS prepends current directory to absolute path (Win32 Node.js)

### ISSUE THREAD

**Issue by Symbitic** [systemjs/systemjs#1409]
When running on Node.js, SystemJS appears to prepend the current directory to the filename argument in `System.import`, even if an absolute path was given.

This appears to be Windows specific, as the exact same code worked fine on Linux (absolute paths were constructed using path.join).

Example: `System.import('C:\Users\Example\Downloads\Repo\plugins\test.js')` results in:
```bash
(SystemJS) ENOENT: no such file or directory, open 'C:\Users\Example\Downloads\Repo\C:\Users\Example\Downloads\Repo\plugins\test.js'
```

Notes: I am using <https://github.com/systemjs/plugin-babel> as the transpiler. Not sure if that is related or not.

**Comment by guybedford** [comment]
Try `System.import('file:///c:/Users/...')` here instead. The loader works in the file URL space, not paths, so it is a coincidence that this works in Unix and not Windows.

The next version of SystemJS has an exception to deal with this case more easily.
