### ISSUE TITLE
Can´t find 'default' module inside a bundle for lazy load in angular 2

### ISSUE THREAD

**Issue by davidanaya** [systemjs/systemjs#1410]
Hi!

I'm trying to reference a module inside a js bundle built with systemjs with the lazy load funcionality from angular 2 RC5 and I'm getting an error.

My bundle insides look like this:

```
System.registerDynamic("app/components/test/test.component.js", ["@angular/core", "@angular/router"], true, function($__require, exports, module) {
...
});

System.registerDynamic("app/components/test/test.routing.js", ["@angular/router", "."], true, function($__require, exports, module) {
...
});

System.registerDynamic("app/components/test/test.module.js", ["@angular/core", "./test.routing", "."], true, function($__require, exports, module) {
...
  exports.default = TestModule;
  return module.exports;
});
```

and my routing file like this:

```
import { Routes, RouterModule } from '@angular/router';
const routes: Routes = [
  { 
    path: '', 
    redirectTo: 'main', 
    pathMatch: 'full'
  },
  {
    path: 'test',
    loadChildren: 'test.bundle.js'
  }
];
export const routing = RouterModule.forRoot(routes);
```

So in this case I get 
Error: Cannot find 'default' in 'test.bundle.js'

In case I use 
`loadChildren: 'test.bundle.js#TestModule'`
I get an "Error: Cannot find 'TestModule' in 'test.bundle.js'", so it seems the module is not recognized inside the bundle.

Any idea on what I might be doing wrong? Or maybe is only that this can´t be achieved at the moment?

**Comment by davidanaya** [comment]
Ok, the issue was that I was missing the bundle option in my systemjs.config.

If I use 
```
var config = {
    bundles: {
      'test.bundle.js': ['app/components/test/test.module.js']
    },
...
};
```

then I can use
```
{
    path: 'test',
    loadChildren: 'app/components/test/test.module#TestModule'
}
```
in my routing and everything works fine.

**Comment by bjorkblom** [comment]
@davidanaya How did you bundle your test.bundle.js file?
