### ISSUE TITLE
Wiki: How should a module look like?

### ISSUE THREAD

**Issue by bennyn** [systemjs/systemjs#1414]
Hello, I am testing SystemJS and found much documentation about which module systems are supported. Unfortunately, I did not find much information on how a module should look like.

I started with this test code:

**js/Person.js**

```
function Person(name) {
  this.name = name;
}

Person.prototype.greet = function() {
  return "Hello, my name is " + this.name + ".";
};
```

**index.html**

```html
SystemJS.import('js/Person.js').then(function(Person) {
  var homer = new Person('Homer');
  var greeting = homer.greet();
  document.write(greeting);
});
```

This code was working just fine and I got "Hello, my name is Homer." written to my page. Now I wanted to test the same with TypeScript (which has `system` module support).

I wrote the following:

```typescript
namespace World {
  export class Person {
    private name: string;

    constructor(name: string) {
      this.name = name;
    }

    public greet(): string {
      return `Hello, my name is ${this.name}.`;
    }
  }
}
```

Which compiled to:

**js/World.js**

```javascript
var World;
(function(World) {
  var Person = (function() {
    function Person(name) {
      this.name = name;
    }

    Person.prototype.greet = function() {
      return "Hello, my name is " + this.name + ".";
    };
    return Person;
  }());
  World.Person = Person;
})(World || (World = {}));
```

So I was hoping to be able to do this:

```html
SystemJS.import('js/World.js').then(function(World) {
  var homer = new World.Person('Homer');
  var greeting = homer.greet();
  document.write(greeting);
});
```

Sadly, I only receive an empty object (`Object {}`) from `SystemJS.import`. So there must be something about the `World.js` file which it doesn't like and I am trying to figure out what. Maybe you can help me?

I also noticed that if I change my TypeScript code a little:

```typescript
export namespace World {
  export class Person {
    private name: string;

    constructor(name: string) {
      this.name = name;
    }

    public greet(): string {
      return `Hello, my name is ${this.name}.`;
    }
  }
}
```

I am getting this:

```javascript
System.register("World", [], function(exports_1, context_1) {
  "use strict";
  var __moduleName = context_1 && context_1.id;
  var World;
  return {
    setters: [],
    execute: function() {
      (function(World) {
        var Person = (function() {
          function Person(name) {
            this.name = name;
          }

          Person.prototype.greet = function() {
            return "Hello, my name is " + this.name + ".";
          };
          return Person;
        }());
        World.Person = Person;
      })(World = World || (World = {}));
      exports_1("World", World);
    }
  }
});
```

This time it does a `System.register`, which looks totally different from the compiled output from before. Can you tell me which is the preferred way?

**Comment by fictitious** [comment]
You might find this question amusing: http://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules

The most popular answer concludes that namespaces should not be used at all.

**Comment by probins** [comment]
modules export values which other modules import. Your first example does not export anything, so there is nothing to import. See https://github.com/systemjs/systemjs/blob/master/docs/es6-modules-overview.md (and numerous other tutorials around the web) for example ES6 module syntax.

See https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Namespaces%20and%20Modules.md for info on namespaces. I'd agree that you should be using modules not namespaces.

**Comment by bennyn** [comment]
@fictitious: Thanks for sharing this question. With all these chocolate bars it's actually quite amusing. :grinning: 

@probins: That's exactly what I find confusing... My first example (`js/Person.js`) doesn't make any use of the `exports.method = function() {}` pattern, but it works! I can import the `Person` prototype just fine.

What I want to achieve is, that my TypeScript code compiles to ES5 JavaScript (with `system` modules), so I can import my code with `SystemJS` on a HTML5 website (supporting ES5).

**Comment by bennyn** [comment]
@fictitious: Following the answer on "[How do I use namespaces with TypeScript external modules?](http://stackoverflow.com/questions/30357634/how-do-i-use-namespaces-with-typescript-external-modules)", I went for the following TypeScript code (without declaring a `namespace`):

```typescript
export class Person {
  private name: string;

  constructor(name: string) {
    this.name = name;
  }

  public greet(): string {
    return `Hello, my name is ${this.name}.`;
  }
}
```

This transpiles to:

```javascript
System.register("Person", [], function(exports_1, context_1) {
  "use strict";
  var __moduleName = context_1 && context_1.id;
  var Person;
  return {
    setters: [],
    execute: function() {
      Person = (function() {
        function Person(name) {
          this.name = name;
        }

        Person.prototype.greet = function() {
          return "Hello, my name is " + this.name + ".";
        };
        return Person;
      }());
      exports_1("Person", Person);
    }
  }
});
```

I was able to import the `Person` module by declaring the following:

```html
<script src="lib/system.js"></script>
<script src="js/PersonModule.js"></script>
```

```javascript
SystemJS.import('Person').then(function(PersonModule) {
  var homer = new PersonModule.Person('Homer');
  var greeting = homer.greet();
  document.write(greeting);
});
```

The downside is now that I need to declare `<script src="js/PersonBundle.js"></script>`. I would prefer that SystemJS goes and fetches the file for me when it's needed. And I want to avoid the `PersonModule.Person` syntax, but I don't know how I can convince TypeScript to not wrap my `Person` class. :cry: 

This is my `tsconfig.json`:

```json
{
  "compilerOptions": {
    "module": "system",
    "outFile": "js/PersonModule.js",
    "rootDir": "src/ts",
    "sourceMap": false,
    "target": "es5"
  }
}
```

**Comment by probins** [comment]
Person.js:
```js
export function Person(name) {
  this.name = name;
}
Person.prototype.greet = function() {
  return "Hello, my name is " + this.name + ".";
};
```
transpile to System.register, say `PersonR.js`

homer.js:
``` js
import {Person} from './PersonR.js';

var homer = new Person('Homer');
var greeting = homer.greet();
document.write(greeting);
```
transpile that to System.register, say `homerR.js`

html:
```
SystemJS.import('./homerR.js');
```

`import {Person}` binds the Person variable to the exported Person value. `import()` returns the module
 (or to be more precise a Promise which resolves to the module), so you have to refer to that in the `then` clause: `...then(function(m) {var Person = m.Person; var homer = new Person('Homer');`

I believe initial module support was included in the recent Win 10 update. If you have that and enable experimental JS in Edge, you should be able to use ES6 format with `<script type="module" src="./homer.js">` without any transpiling (except from Typescript, of course, if you're using that). This will be the normal way of kick-starting module loading. `import()` would normally only be used for dynamic loading, such as loading page 2 in an SPA.

**Comment by bennyn** [comment]
Thanks @probins. Your ideas have made me to revise my example. Now I am on the right track. It looks like TypeScript handles a `module` with seperate classes better than one namespaced class. I got now what I wanted to achieve, which is:

```javascript
SystemJS.import('World').then(function(World) {
  var homer = new World.Human('Homer');
  console.log(homer.sayHello()); // Hello, my name is Homer.

  var simon = new World.Animal('Simon', 'Meow');
  console.log(simon.makeNoise()); // Meow!
});
```

Here is the whole example:

**src/ts/Animal.ts**

```typescript
module World {
  export class Animal {
    private name: string;
    private sound: string;

    constructor(name: string, sound: string) {
      this.name = name;
      this.sound = sound;
    }

    public makeNoise(): string {
      return `${this.sound}!`;
    }
  }
}
```

**src/ts/Human.ts**

```typescript
module World {
  export class Human {
    private name: string;

    constructor(name: string) {
      this.name = name;
    }

    public sayHello(): string {
      return `Hello, my name is ${this.name}.`;
    }
  }
}
```

**tsconfig.json**

```json
{
  "compilerOptions": {
    "module": "system",
    "outFile": "app/js/World.js",
    "rootDir": "src/ts",
    "sourceMap": false,
    "target": "es5"
  }
}
```

**app/js/World.js**

```javascript
var World;
(function(World) {
  var Animal = (function() {
    function Animal(name, sound) {
      this.name = name;
      this.sound = sound;
    }

    Animal.prototype.makeNoise = function() {
      return this.sound + "!";
    };
    return Animal;
  }());
  World.Animal = Animal;
})(World || (World = {}));
var World;
(function(World) {
  var Human = (function() {
    function Human(name) {
      this.name = name;
    }

    Human.prototype.sayHello = function() {
      return "Hello, my name is " + this.name + ".";
    };
    return Human;
  }());
  World.Human = Human;
})(World || (World = {}));
```

**app/index.html**

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test</title>
    <script src="lib/system.js"></script>
  </head>
  <body>
    <script>
      System.config({
        map: {
          "World": "js/World.js"
        }
      });

      SystemJS.import('World').then(function(World) {
        var homer = new World.Human('Homer');
        console.log(homer.sayHello()); // Hello, my name is Homer.

        var simon = new World.Animal('Simon', 'Meow');
        console.log(simon.makeNoise()); // Meow!
      });
    </script>
  </body>
</html>
```

I was expecting TypeScript to transpile something like:
```javascript
System.register("World", ["Human", "Animal"], function(...) {
  ...
}
```
But I am also fine with the solution I got now. :smiley: 

Thanks a lot!

**Comment by bennyn** [comment]
I got my question answered. Here is the Q&A for reference:
http://stackoverflow.com/questions/39120576/how-to-export-a-typescript-module-for-systemjs
