### ISSUE TITLE
How to define a dependency from the "window" namespace?

### ISSUE THREAD

**Issue by bennyn** [systemjs/systemjs#1415]
I have a module (`CryptoboxRepository`) which is registered like that:

```javascript
System.register(["proteus", "bazinga64"], function(exports_1, context_1) {
  "use strict";
  ...
});
```

The `bazinga64` dependency can be received just fine (because it's already in a SystemJS format) but `proteus` makes trouble. Luckily, `proteus` is available from the global namespace (`window.Proteus`) in my website. 

Is there a funcationality, to tell SystemJS that it can get `proteus` from the global namespace?

I already tried this:

```js
SystemJS.config({
  baseURL: '/public',
  map: {
    'CryptoboxRepository': 'js/CryptoboxRepository.js',
    'bazinga64': 'dependencies/bazinga64/bazinga64.js'
  },
  meta: {
    'CryptoboxRepository': {
      deps: {
        'proteus': 'dependencies/cryptobox/cryptobox.js'
      }
    }
  }
});
```

Unfortunately, I am getting this error:

> Uncaught (in promise) Error: (SystemJS) e.lastIndexOf is not a function
	TypeError: e.lastIndexOf is not a function

The file `cryptobox.js` specifies multiple packages for the global namespace. So I was wondering if I can force SystemJS to just accept `window.Proteus` for being the module `proteus`?

**Comment by guybedford** [comment]
Try - 

```javascript
meta: {
  'dependencies/cryptobox/cryptobox.js': {
    format: 'global',
    exports: 'Proteus'
  },
  'CryptoboxRepository': {
    // ...
  }
```

**Comment by bennyn** [comment]
Thanks for your support, @guybedford.

I changed it this way:

```js
...
meta: {
  'dependencies/cryptobox/cryptobox.js': {
    format: 'global',
    exports: 'proteus'
  },
  'CryptoboxRepository': {
    deps: {
      'proteus': 'dependencies/cryptobox/cryptobox.js'
    }
  }
}
```

But I still get:

> Uncaught (in promise) Error: (SystemJS) e.lastIndexOf is not a function

The dependency in my module is called `proteus` (small "p" in the beginnig) and `cryptobox.js` declares (along others): `window.Proteus   = __webpack_require__(/*! proteus */ 21);`.

So I have the difficault task to tell SystemJS that it should import a Node.js module which was exported for the Browser with WebPack.

**Comment by guybedford** [comment]
I would suggest stepping back and just focusing on getting `System.import('cryptobox')` to return the correct module value here.

That means adding the shim with a `exports: 'Proteus'` as that is what is defined to the cryptobox file, and setting the format as a `global`. The fact that it contains webpack require statements in the bundled format is irrelevant.

If you can share the full error message stack though that would be interesting to see as that is an awful error for SystemJS to spit out.

**Comment by bennyn** [comment]
Ok, I will try to extract `proteus` from the `cryptobox.js` file. 

Unfortunately there is no error stack but here is a screenshot of what I am getting (using `system.src.js` v0.19.36):

![screenshot](https://cloud.githubusercontent.com/assets/469989/17854008/25b71a16-6870-11e6-9269-6584f5067760.PNG)

So the error must be somewhere here:

![sub-buzz-18360-1470833128-1](https://cloud.githubusercontent.com/assets/469989/17854054/53a5b284-6870-11e6-9d70-73078ff71bff.png)

**Comment by bennyn** [comment]
@guybedford I just got this again:

> system.js:4 Uncaught (in promise) Error: (SystemJS) Cannot read property 'lastIndexOf' of null

It came up when using this module:

```js
define("proteus", [null], function(__WEBPACK_EXTERNAL_MODULE_44__) { });
```
I think that SystemJS doesn't like the `null` within my module's dependency list. Am I correct?
