### ISSUE TITLE
Error: XHR error (404 Not Found) loading http://localhost:51886/app/main.ts.js

### ISSUE THREAD

**Issue by j-nord** [systemjs/systemjs#1418]
From one day to another the import function will load the startup file "main.ts.js":

Error: XHR error (404 Not Found) loading http://localhost:51886/app/main.ts.js

Why the start program is now with ending: "ts.js" ? What's wrong?

We writing the program in typescript (for angular2) and compile js-files in the target app folder (with map-file) 

**start command in systemjs:**
    System.import('app').catch(function(err){ console.error(err); });

**Start program:
'app':                          { main: 'main', defaultExtension: 'js' },**

**systemjs.config.js:**
`(function (global) {

    // map tells the System loader where to look for things
    var map = {
        'app': './app', // 'dist',
        'rxjs': 'node_modules/rxjs',
        'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
        '@angular': 'node_modules/@angular'
    };

    // packages tells the System loader how to load when no filename and/or no extension
    var packages = {
        'app':                          { main: 'main', defaultExtension: 'js' },
        'rxjs':                         { defaultExtension: 'js' },
        'angular2-in-memory-web-api':   { defaultExtension: 'js' },
    };

    var packageNames = [
      '@angular/common',
      '@angular/compiler',
      '@angular/core',
      '@angular/forms',
      '@angular/http',
      '@angular/platform-browser',
      '@angular/platform-browser-dynamic',
      '@angular/router',
      '@angular/router-deprecated',
      '@angular/testing',
      '@angular/upgrade',
    ];

    // add package entries for angular packages in the form '@angular/common': { main: 'index.js', defaultExtension: 'js' }
    packageNames.forEach(function (pkgName) {
        packages[pkgName] = { main: 'index.js', defaultExtension: 'js' };
    });

    var config = {
        map: map,
        packages: packages
    }

    // filterSystemConfig - index.html's chance to modify config before we register it.
    if (global.filterSystemConfig) { global.filterSystemConfig(config); }

    System.config(config);

})(this);`

**package.json :**

{
  "version": "1.0.0",
  "name": "asp.net",
  "private": true,
  "scripts": {
    "postinstall": "typings install",
    "typings": "typings"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "3.3.7",
    "core-js": "^2.4.0",
    "jquery": "2.1.4",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "typescript": "^1.8.10",
    "gulp": "^3.9.1",
    "path": "^0.12.7",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.0",
    "gulp-typescript": "^2.13.6",
    "gulp-cssmin": "0.1.7",
    "gulp-uglify": "2.0.0",
    "typings": "1.3.2",
    "gulp-tsc": "^1.2.0"
  }
}

**Comment by fictitious** [comment]
That looks very similar to angular quickstart tutorial, which works fine for me when I run it with

    npm start

The only difference that I see is that I have `main: 'index.js'` in angular2-in-memory-web-api package config

            'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },

but it does not make any difference if I remove `main` there.

Hard to tell what's going wrong in your case without more information.
