### ISSUE TITLE
load module from s3

### ISSUE THREAD

**Issue by tomdavidson** [systemjs/systemjs#1419]
Suggestions on loading a module from s3?

**Comment by guybedford** [comment]
Did you try importing from the URL directly?

**Comment by tomdavidson** [comment]
For my case s3 native rather than s3 website is critical.

I didn't find docs or plugin claiming support for s3 so no I did not try
and assumed I would need to contrib the enhancement.

**Comment by asapach** [comment]
S3 bucket is just an HTTP URL, so it would work like any other CDN.

**Comment by tomdavidson** [comment]
There is the S3 interface, the REST API, and the website publishing option. The module to load will have configuration info, including secrets - publishing the module vs HTTP is not an option. I would like to use S3 so we can leverage network ACL in fetching the secured and private object rather than have REST credentials in the app which would defeat this particular purpose.

**Comment by tomdavidson** [comment]
Only [standard urls](https://github.com/systemjs/systemjs/blob/9ae1527ed9df717889609623be9d04cf7f0b95d6/docs/overview.md#loading-modules) are supported, but a plugin can [overide fetch](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md#creating-a-plugin). Any pointers or feedback on created a plugin that would allow fetching from s3://bucket-name/key style urls - using the AWS SDK?
