### ISSUE TITLE
Q: Multiple transpilers?

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1421]
I'd like to use TS transpiler alongside Babel in one of my projects. The `transpiler` option seems to be global and not package-specific. Will `loader` meta option work for this scenario, or should I transpile to `esm` first?
I'm mostly interested in Builder rather than in-browser compilation.

**Comment by fictitious** [comment]
Yes it's possible with plugin-typescript. I have example project where transpiler global option is not set, so it uses default transpiler for everything except the parts that have loader set to that plugin:

```
  paths: { 
    "plugin-typescript/": "../lib/plugin-typescript/lib/",
    "typescript/": "../lib/typescript/"
  },

  packages: {
    "plugin-typescript": {
      "main": "plugin.js",
      "meta": { "*.js": { "typings": true } }
    },
    "typescript": {
      "main": "lib/typescript.js",
      "meta": {
        "lib/typescript.js": {
          "exports": "ts",
          "typings": true
        }
      }

    },

   "the-package-that-uses-typescript": {
        defaultExtension: "ts",
        meta: {
            "*.ts": {loader: "plugin-typescript"}
        }
    }
},

```
