### ISSUE TITLE
Error: XHR error (404 Not Found) loading http://localhost:3000/apollo-client/index.js

### ISSUE THREAD

**Issue by kesemdavid** [systemjs/systemjs#1422]
Ive been reading all day and tried everything, im new to SystemJS and just started writing a new app yesterday, please tell me what am i doing wrong.
I followed the angular2 quick start and adjusted it to mine.. maybe ive done something wrong

both package.json and systemjs.config:

![files](https://cloud.githubusercontent.com/assets/21152044/18027867/7063379c-6c77-11e6-8375-d2c8c9bea371.png)

errors i get: 
![error](https://cloud.githubusercontent.com/assets/21152044/18027873/a0edb8b0-6c77-11e6-86f2-d5c65e6303b8.png)

**Comment by fictitious** [comment]
First thing that I see is you need to add paths to angular2-apollo and apollo-client to `var map = {` dictionary at the top of systemjs.config.js
