### ISSUE TITLE
Different behaviour when importing with SystemJS.config

### ISSUE THREAD

**Issue by bennyn** [systemjs/systemjs#1423]
I have a module stored in the path "`js/MyFancyModule.js`" and I thought that these import variants would do the same:

**No. 1**

```js
SystemJS.import('js/MyFancyModule.js').then(function(MyFancyModule) {
   ...
});
```

**No. 2**

```js
SystemJS.config({map: {MyFancyModule: 'js/MyFancyModule.js'}});

SystemJS.import('MyFancyModule').then(function(MyFancyModule) {
  ...
});
```

Surprisingly, only the second variant (calling `SystemJS.config` before importing) works. Can you tell me why?

Here is the module I used:

```js
System.register("MyFancyModule", [], function(exports_1, context_1) {
  "use strict";
  var __moduleName = context_1 && context_1.id;
  var MyFancyClass;
  return {
    setters: [],
    execute: function() {
      MyFancyClass = (function() {
        function MyFancyClass(text) {
          this.text = text;
        }

        return MyFancyClass;
      }());
      exports_1("MyFancyClass", MyFancyClass);
    }
  }
});
```

I also created a sample application, where you can see the behaviour:
- https://github.com/bennyn/systemjs-example/blob/master/dist/working.html
- https://github.com/bennyn/systemjs-example/blob/master/dist/not-working.html

**Comment by guybedford** [comment]
I think you'll find case 2 works here even without the configuration call.

Basically you need to ensure the registered name matches the imported name. That can be difficult to know how the configuration applies here I know, so to help it can be worth logging `Object.keys(System.defined)` to see the list of registrations. Then to test normalization try `System.normalizeSync('x')` to see what it is fully normalized.

I think the fix you need though is just to import `System.import('MyFancyModule')` in the first case or have a bundle of `System.register('js/MyFancyModule.js')`.

**Comment by fictitious** [comment]
> Basically you need to ensure the registered name matches the imported name.

The javascript module in question was generated by typescript compiler, and the behavior of the import in the non-working case is that the module is found, loaded, but `import` returns an empty object.

This leads to puzzling failures, unless one happens to always remember that requirement and knows how to fix it either on the typescript side or in config.js.

Maybe it's asking too much, but the question, as I understand it, goes a little bit further: why it fails in such a strange way, and why SystemJS has that requirement.

**Comment by guybedford** [comment]
@fictitious a bundle loaded through SystemJS is itself then a module. The value of a bundle module is thus the empty module, while it can define any number of other modules into the registry.

Because bundles can define multiple named modules, the bundle itself does not by default take the value of one of the modules as that would have to be an arbitrary decision to allow a bundle to take the module value of the first or last named module it defines say, which may lead to even more confusion when it isn't providing the correct module value.

If you only have a single module in a file, make it an anonymous System.register statement:

```javascript
System.register([], function(exports_1, context_1) {
  "use strict";
  var __moduleName = context_1 && context_1.id;
  var MyFancyClass;
  return {
    setters: [],
    execute: function() {
      MyFancyClass = (function() {
        function MyFancyClass(text) {
          this.text = text;
        }

        return MyFancyClass;
      }());
      exports_1("MyFancyClass", MyFancyClass);
    }
  }
});
```

**Comment by fictitious** [comment]
I think now it's clear where the confusion comes from.

Typescript compiler, when `outFile` is set in `tsconfig.json`, generates a bundle which will contain all the modules.

A bundle with a single module is still a bundle, not a module.

Thank you @guybedford !
