### ISSUE TITLE
load jquery module which depends on window.jQuery

### ISSUE THREAD

**Issue by pcompassion** [systemjs/systemjs#1425]
I'm trying to use https://github.com/luis-almeida/unveil

which looks like
```

;(function($) {

  $.fn.unveil = function(opts) {

    return this;

  };

})(window.jQuery || window.Zepto);
```

And I use the library as the following. 
```
import $ from 'jquery';  // I guess the jquery imported here is different from window.jQuery above.
import _jqueryUnveil from 'jquery.unveil';

$(selector).unveil();
```

I get an error,
$.unveil is not a function 

I tried putting this under meta
```

"jquery.unveil": {
        "deps": [
          "jquery"
        ]
       }
```

and 

```
"jquery.unveil": {
   globals: {
           'jquery': 'jquery' 
       }
}
```

**Comment by fictitious** [comment]
Works for me - I just tried

     npm install jspm
     ./node_modules/.bin/jspm install jquery
     ./node_modules/.bin/jspm install github:luis-almeida/unveil

and, without any furhter configuration (no `deps`, no `globals`):

```
import $ from 'jquery';  

console.log($ === window.jQuery);  // true

import _jqueryUnveil from 'luis-almeida/unveil';

console.log(typeof $); // function
console.log(typeof $.fn.unveil);  // function

$('.u').unveil();  // no error

```

**Comment by pcompassion** [comment]
I had bower installed unveil. I guess it's different when you install it from jspm.  
I'll try

Is there a way to alias `luis-almeida/unveil` to `jquery.unveil` ?

**Comment by fictitious** [comment]
Yes,  jspm-generated config.js has this line in the `map:`

       "luis-almeida/unveil": "github:luis-almeida/unveil@1.3.0",

You just need to add or replace it with

       "jquery.unveil": "github:luis-almeida/unveil@1.3.0",

**Comment by pcompassion** [comment]
oh shoot ; Thank you!
