### ISSUE TITLE
Handling of direct and transitive dependencies for web components

### ISSUE THREAD

**Issue by oleersoy** [systemjs/systemjs#1426]
Hi - please let me know if there is a better place to ask about this concept.  I have documented it on SO here: http://stackoverflow.com/questions/39196542/web-component-peer-dependencies-with-jspm

I also have a related Polymer issue [Rapid prototyping with transitive NPM dependency element resolution](https://github.com/Polymer/polymer/issues/3875) that systemjs and jspm seems to be a good fit for.  I would love to get your input on this.

**Comment by guybedford** [comment]
Yes jspm is exactly designed to handle these version resolutions in a flat folder structure through a managed SystemJS configuration file. In the peer dependencies case, peer dependencies by definition means using a single version of that dependency only in the entire application. Normal dependencies allow multi-version encapsulation just like npm.

**Comment by oleersoy** [comment]
@guybedford thank you I really appreciate your input on this!  I'll start prototyping this out more so that I can solidify the workflow concept a little better.  I'm assuming then that `Polymer` would be declared as a peer dependency, since all app components should use a compatible version, whereas `moment.js` would be declared as a normal dependency, and if a common version can be found, then jspm uses one version, but if not then it installs both?

**Comment by oleersoy** [comment]
Created a simpler scenario with a question about ES6 modules alone.  I would like these to be loaded in unbundled format using HTTP2.  I've scanned through most of the tutorials and documentation but how to accomplish loading two versions of momentjs and ensuring that the right module gets the right version is still escaping me.  Is there a test case that I could study that shows how to do this?

http://stackoverflow.com/questions/39212020/loading-two-separate-versions-of-moment-js-using-systemjs-and-jspm

**Comment by guybedford** [comment]
In SystemJS the above is handled through package configuration:

```javascript
System.config({
  packages: {
    'path/to/packageA': {
      main: 'packageAmain.js',
      map: {  moment: 'path/to/moment-1.x.js' }
    },
    'path/to/packageB': {
      main: 'packageBmain.js',
      map: {  moment: 'path/to/moment-2.x.js' }
    }
  }
});
```

Where `System.import('path/to/packageA')` will then load `path/to/packageA/packageAmain.js`.

Packages do need to be folders typically, but packages as modules does work too I believe.

**Comment by oleersoy** [comment]
OK - Great - Thanks!  Just want to make sure I understand correctly before I update my SO post.  So even though there are two versions of moment, both can be imported within `packageA` and `packageB` using the same statement:

`import moment from 'moment';`

Because the configuration takes care of mapping each package to the correct `moment` dependency?

**Comment by oleersoy** [comment]
Incidentally - wanted to get your opinion on a request to move Polymer packages to NPM.  

https://github.com/Polymer/polymer/issues/326

IIUC the main objective of the individuals requesting this was to get dependency management and repository management capabilities from one source (NPM).  The Polymer team is working on tooling that will keep the Polymer and NPM packages synchronized and up to date, but it seems to me like they would get all of that and more (Flat multi versioned dependency tree, http2 ready cache, etc.) if they just make the github repositories JSPM friendly?  WDYT?

**Comment by guybedford** [comment]
Yes the previous comment is correct. Most projects are moving to npm - so jspm will be adapting to that.

**Comment by oleersoy** [comment]
Great - really appreciate your input and all the fantastic work being done on JSPM.
