### ISSUE TITLE
speed up bundling process

### ISSUE THREAD

**Issue by pcompassion** [systemjs/systemjs#1427]
I have about 30 apps which has about 50 dependencies (after excluding shared dependencies)

Bundle process takes about 10 min with systemjs which were like 1 min with requirejs with similar bundling strategy.

I wonder if there's a way to speed up bundling 
For example, is there a way to bundle changed apps only?

**Comment by guybedford** [comment]
Is this with minification enabled or disabled? Perhaps check the numbers with it turned off.

**Comment by pcompassion** [comment]
I looked at the requirejs bundling code, it was only bundling about 10 apps. so the time I mentioned is way off. I didn't time it with a watch, I was just frustrated with the speed. I'll update with more precise  timing if problem persists.
