### ISSUE TITLE
Downloading same js file twice.

### ISSUE THREAD

**Issue by pcompassion** [systemjs/systemjs#1430]
![screen shot 2016-08-31 at 10 16 59 am](https://cloud.githubusercontent.com/assets/84749/18112660/3362a5d6-6f64-11e6-8c61-01a443bc09e7.png)

I see main-app.js (which is jspm-bundle) gets downloaded twice. (all the time)

I'm including it as below....
` <script type="text/javascript" src="/static/apps/main-app.js"></script>`

**Comment by fictitious** [comment]
Do you happen to have `import('main-app.js')` or similar statement somewhere?

Bundle can be loaded either with a script tag, or with explicit `import('bundle-name')` call. Either way, all the `SystemJS.register('module-name')` statements inside the bundle are executed,  and each module becomes available for `import` statement which should not cause any more loads (if all the dependencies are in the bundle).

**Comment by pcompassion** [comment]
when I search import('main-app.js'), the only place it appears is inside the bundle that I created for the app.

I'm suprised to see the two downloads even if I had to imports.

**Comment by guybedford** [comment]
Have a look at the registry at `Object.keys(System._loader.modules)` to see how name duplication might be happening in the registry. Note that the loader is case sensitive.
