### ISSUE TITLE
Load from string

### ISSUE THREAD

**Issue by pocesar** [systemjs/systemjs#1431]
I'm using greasemonkey, and I'm not being able to System.import directly because of CSP. So I'm using the `@resource` for downloading a remote script locally, then trying to load it using `GM_getResourceText('resource')` (returns the script as text).

The docs are pretty lackluster when it comes to examples, and I could not find anywhere how I can create an "anonymous" load from this script, like:

```js
Promise.all([
  System.import(GM_getResourceText('resource')) // fails
]).then(imports) {
})
```

tried using `System.set('resource', System.newModule(GM_getResourceText('resource')))` but fails with "expected object"

**Comment by fictitious** [comment]
One possible way is to write a plugin (see https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md) that will override `fetch` (see https://github.com/ModuleLoader/es-module-loader/blob/v0.17.0/docs/loader-extensions.md)

**Comment by guybedford** [comment]
The best thing to do here is to execute code containing `System.register` statements in the environment, just like loading a bundle.

**Comment by pocesar** [comment]
weirdly enough, I manage to do this using

```js
System.define(System.normalizeSync('diacritic'), GM_getResourceText('diacritic'))
System.define(System.normalizeSync('jquery'), GM_getResourceText('jquery'))
System.define(System.normalizeSync('bluebird'), GM_getResourceText('bluebird'))
System.define(System.normalizeSync('valid-url'), GM_getResourceText('valid-url'))

Promise.all([
  System.import('diacritic'),
  System.import('jquery'),
  System.import('bluebird'),
  System.import('valid-url'),
])
```

it was a lot of trial and error though.
