### ISSUE TITLE
should I inject core dependency for production or not?

### ISSUE THREAD

**Issue by pcompassion** [systemjs/systemjs#1432]
I find when I inject it, it get's downloaded via ajax. 

Or I could just do regular `<script>` import for the core dependency. 

question 1
If I do `<script>` way, 
I expected if 'jquery' is in core.js and app.js does `import $ from jquery`, it downloads the `core.js` not the `jquery.js` but I see `jquery.js` gets downloaded via ajax.
Simple stuff, but I don't find docs for this. 

question 2
Which one is prefered for production considering performance?

I see core.js takes long time to load with ajax.. 

![screen shot 2016-09-01 at 5 26 55 pm](https://cloud.githubusercontent.com/assets/84749/18160618/3eed2240-7069-11e6-8aa5-ab66cfd6c898.png)

**Comment by guybedford** [comment]
You can also make it load with script by:

```javascript
System.config({
  meta: {
    'path/to/bundle.js': { scriptLoad: true }
  }
});
```

**Comment by guybedford** [comment]
But including a manual script tag is recommended for scripts that will load with the page (obviously not blocking the main body HTML though too)
