### ISSUE TITLE
Bundle file load is not triggered when package maps to root directory

### ISSUE THREAD

**Issue by katrotz** [systemjs/systemjs#1434]
If a package is defined in JSPM config, mapped to "/", the application bundle fails to load.
When the package is mapped to a subfolder, so that the bundle file is outside of the package, the bundle loads ok.

Please find below the scenario where the bundle is not loaded

The setup

```
SystemJS v0.19.37
JSPM 0.17.0-beta.281
```

The configuration

```
SystemJS.config({
   ...
   paths: {
        ...
        "myPackageName/": "/"
    },
   packages: {
    "myPackageName": {
      "main": "scripts/index.js",
      "format": "esm",
      "meta": {
        ...
      }
    }
  },
   browserConfig: {
        ...
        "bundles": {
            "build.js": {
                "scripts/index.js",
                ...
            }
        }
    }
   ...
})
```

The import

```
System.import("myPackageName/scripts/index.js")
```

**Comment by dinoboff** [comment]
It's difference between how path are handled in node and the browser.Jspm used to create a config like that:
```
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    my-package/": "src/"
  },
  browserConfig: {
    "baseURL": "/"
  }
});
```

Now it look likes that:
```
SystemJS.config({
  browserConfig: {
    "paths": {
      "npm:": "/jspm_packages/npm/",
      "github:": "/jspm_packages/github/",
      "my-package/": "/src/"
    }
  },
  nodeConfig: {
    "paths": {
      "npm:": "jspm_packages/npm/",
      "github:": "jspm_packages/github/",
      "my-package/": "src/"
    }
  }
});
```

**Comment by katrotz** [comment]
@dinoboff Not sure I can follow the connection as the config was generated using the 0.17 jspm. 
I sense that the problem lies in the fact that the bundle file "build.js" is part of the package path, whose files it contains, hence creating kind of a circular dependency. Will try to do more tests/debugging this week. If I find the root cause will post it here. Meanwhile closing the ticket

**Comment by dinoboff** [comment]
@katrotz sorry, I thought the problem was with `"myPackageName/": "/"`.
