### ISSUE TITLE
Exceptions in Promises are absorbed

### ISSUE THREAD

**Issue by sebastien** [systemjs/systemjs#1437]
Whenever code is executed within the context of a promise, SystemJS seems to absorb the reporting of the exception:

```javascript
SystemJS.import("extend").then(function(){throw new Exception("Error")})
```

will leave the console desperately silent, while

```javascript
SystemJS.import("extend").then(function(){window.setTimeout(function(){throw new Exception("Error")},0)})
```
will properly notify of the error. I am loading modules dynamically and then executing actions that might fail, and would like to avoid having to do the `setTimeout` trick, if possible to help debugging.

Thanks!

**Comment by asapach** [comment]
Try this: http://www.2ality.com/2016/04/unhandled-rejections.html
If you're using `system-polyfills.js` you can use `window.addEventListener("unhandledRejection", ...)` - notice that the event name is case-sensitive (and doesn't follow the spec).

**Comment by sebastien** [comment]
Oh, thanks! I am not very familiar with the Promise API, so this is not an
issue with SystemJS then.

Le mar. 6 sept. 2016 18:52, Aliaksei Sapach <notifications@github.com> a
écrit :
