### ISSUE TITLE
Support for marking a module as no-op

### ISSUE THREAD

**Issue by wrl** [systemjs/systemjs#1439]
We have an application which we deploy both in the browser and as a Node module. When run as a Node module, we `require()` a number of native modules which are, naturally, not available in the browser. Nonetheless, when we distribute the main module as AMD, System.js helpfully tries to load these modules.

We could distribute stub modules, but it would be preferable to be able to specify in the System.js configuration that a particular module is non-existent or otherwise shouldn't be loaded.

**Comment by asapach** [comment]
Try mapping it to `'@empty'` - it's designed specifically for this scenario.

**Comment by wrl** [comment]
Is this behaviour documented anywhere?

**Comment by wrl** [comment]
Ah, unfortunately mapping the module to '@empty' results in an empty object being passed to the AMD module instead of `undefined` or `null`, which is what my code expects. Is this part of the module specification or a specific System.js behaviour?

**Comment by asapach** [comment]
It's systemjs-specific.

**Comment by fictitious** [comment]
@wrl Here is what I came up with after looking a little bit at systemjs sources:

        var nullModule = {'default': 'null'};
        Object.defineProperty(nullModule, '__useDefault', {
            value: true
        });
        SystemJS.set('@null', SystemJS.newModule(nullModule));

and then mapping modules to `@null` to stub them.

I'm sure there is a better way, but this works for me at the moment.
