### ISSUE TITLE
Is the import statement asynchronous?

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#1441]
This is a support request and even then perhaps a silly one...

Does the import statements load in parallel or sequentially? Can I imports a second item that relies on the first? For example, will this always work?
```
import css; //Assume, this is a very large file 
import 'path/to/file.css!';
```

**Comment by guybedford** [comment]
Imports load in parallel but are supposed to execute one after another according to the spec. SystemJS doesn't currently strictly provide this as it is still implemented to the older specification.
