### ISSUE TITLE
Am i doing something wrong ?

### ISSUE THREAD

**Issue by shivkoirala** [systemjs/systemjs#1442]
I am very new to systemJS and trying to explore it. Cant we call require like this below. The Require function works inside JS files but not in HTML files. Below is the SystemJS code on my HTML

```
 System.config({
map: {
Customerx: 'Customer.js'
}
 });
        
SystemJS.import('Customerx').then(function (m) {
            var x = require("Customerx"); //<-- this works inside JS files but not here why
 });

```

**Comment by learnjsf** [comment]
Closing this as the require() is not scoped on window.

**Comment by shivkoirala** [comment]
Closing this issue as require is not scoped on the window.
