### ISSUE TITLE
Importing does not wait for dependencies to complete

### ISSUE THREAD

**Issue by ZoolWay** [systemjs/systemjs#1444]
I am having problems with an Aurelia application which uses JSPM and TypeScript. While unbundled everything works fine I run into module loading problems when using the bundled file.

It looks like the imports are sometimes undefined when module is loaded and this of course breaks things.

Let's say I have a `main-service`:

```
import { GoodService } from 'core/good-service';
import { GateService } from 'core/gate-service';

console.log('GoodService:', GoodService, 'GateService', GateService);

export class  MainService ...
```

Here the browser will show me than there is an import for `GoodService` but none for the `GateService` - although `main-service.js` has `core/gate-service` as a dependency (`depCache`).

To find I more I tried to intercept the module loading like this:

```
            var systemLoader = System;
            var defaultImport = systemLoader.import;
            systemLoader.import = function(moduleName, normalizedParentName) {
                console.warn('Intercepting', moduleName, normalizedParentName);
                var r = defaultImport.call(systemLoader, moduleName, normalizedParentName);
                var r2 = r.then((i) => {
                    console.warn('Got something for', moduleName, i);
                    return Promise.resolve(i);
                }).catch((err) => {
                    console.error('Error when intercepted', moduleName, err);
                    throw err;
                });
                return r2;
            };
```

I can see that it starts to load `gate-service` before `main-service` but it loads `main-service` before there is a _Got something for gate-service_ message.

What is going wrong? What can I do to find out more?

JSPM is 0.16.45, SystemJS is 0.19.38

**Comment by ZoolWay** [comment]
I just found out while trying things that this might also happen when unbundled, so it more looks like a race condition in module loading.

**Comment by passerdev** [comment]
+1

**Comment by guybedford** [comment]
Do you perhaps have a circular dependency of gate-service back on main-service?
