### ISSUE TITLE
Arithmetic globs with plugins. (Doc?)

### ISSUE THREAD

**Issue by JSlain** [systemjs/systemjs#1445]
I'm using JSPM, but since the issue is with arithmetic (which is in systemjs), i'll fill it here.

I try to bundle my entire app in a bundle, not bundling dependencies so they can get **lazy loaded**, using **depCache**.

Now here's the way I finally got it, but it seems weird to me i have to do this.

1. Build the dependencies bundle
2. Build my app, with arithmetic '*- dep.bundle*'
3. Delete my dependencies bundle

Let say my app root is *app/app.js*, and the remaining of the app is also in *app/*
To build my false dependencies bundle, here's what i thought would do the trick (took that somewhere)

`jspm bundle app/app.js - [app/**/*] dep.bundle.js`

At first sight it seems correct, however if I inspect the result dep.bundle.js, only my app javascript files have been excluded from the bundle using this arithmetic. I have some **html templates** which didn't get included, as well as some **css** and **scss**. The cause is they are loaded using plugins (plugin-text, plugin-css, plugin-sass).

I started looking at the arithmetic source code, seeing that there was something special about plugins (since there was something special about the '*!*' keyword at some places)

I tried this, with still no success:
`jspm bundle app/app.js - [app/**/*] - [app/**/*!*]`

Here's what finally did the trick:
`jspm bundle app/app.js - [app/**/*] - [app/**/*!text] - [app/**/*!css] - [app/**/*!scss]`

I have a few questions:

- Is there a simpler way to make a bundle that contains ONLY my app, without building a temporary bundle containing **everything i don't want**?
- Let say I wanted to really keep this dependencies bundle, is there a simple way to say: `[app/**/*] really means everything in my app codebase, regardless of the plugin used to load it`?
- Does a documentation exists on the arithmetic part of systemjs? I had to dive into the sources to figure out how to make it work.

**Comment by guybedford** [comment]
This is the simplest way unfortunately, unless you define your plugins using `meta` configuration in SystemJS instead of using the `!plugin` syntax.

Note that brackets are supported for operation grouping as well so that can be used to avoid having to generate intermediate bundles.

I'm not sure how a `app/**/*!*` could work though, since the space of plugins is potentially infinite.

**Comment by JSlain** [comment]
Ok thanks, that works!

For future reference:
`jspm bundle app/app.js - (app/app.js - [app/**/*] - [app/**/*!text] - [app/**/*!css] - [app/**/*!scss])`

There's effectively no need to have an intermediate bundle.
