### ISSUE TITLE
Q: import execution order

### ISSUE THREAD

**Issue by asapach** [systemjs/systemjs#1446]
Is there a spec that defines the execution order of imported modules? I.e. is it guaranteed that imports declared first will be executed first, given that there are no other dependencies between modules (cyclic or otherwise)?
[The modules spec](http://www.ecma-international.org/ecma-262/6.0/#sec-modules) is kind of ambiguous in this regard. Does the new loader spec say something about this?
The reason I'm asking is that I'm seeing discrepancies in how modules are executed when imported using the full SystemJS runtime, SFX runtime and rollup. I wanted to make sure that this is something I should not rely on before I submit an issue. I'll create a repro case otherwise.

**Comment by guybedford** [comment]
Yes the new loader specification ensures execution order is well-defined for a given tree being executed. The old spec didn't provide this behaviour though so we aren't supporting this in SystemJS until the next major is released.

**Comment by asapach** [comment]
Thanks. By the next major you mean v0.20 or v1.0? And what are the release plans?

**Comment by guybedford** [comment]
We may well be able to make the next version 1.0. No definite plans as yet.
