### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by oehm-smith** [systemjs/systemjs#1447]
https://github.com/GeoscienceAustralia/gnss-site-manager/commit/6ab4dd5c704315af3fe35e3d96d2612e7c870e96

    npm install
    npm test

Fails to run with this abreviated output:

    [12:49:43] Starting 'karma.run'...

    START:
    15 09 2016 12:49:44.765:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
    15 09 2016 12:49:44.769:INFO [launcher]: Starting browser Firefox
    [12:49:44] copy.js.local normal files 0 items
    [12:49:44] copy.js.local service worker files 0 items
    15 09 2016 12:49:46.655:INFO [Firefox 48.0.0 (Mac OS X 10.10.0)]: Connected on socket /#xD4dsV2g9l8qc5YPAAAA with id 41478984
    15 09 2016 12:49:47.263:WARN [web-server]: 404: /node_modules/ng2-bootstrap/package.json
    Firefox 48.0.0 (Mac OS X 10.10.0) ERROR: Error{stack: null, originalErr: Error{}}
      About component
        ✔ should work
      About component 2
        ✔ should work
        ✔ should work

    Finished in 0.23 secs / 0.278 secs

    SUMMARY:
    ✔ 3 tests completed

There are many more tests that aren't even executed.

When I add the following to `system.src.js` function `addToError(err, msg)`:

     109         console.log('systemjs addToError - msg:'+msg+', err: ', err);

The output includes:

    Firefox 48.0.0 (Mac OS X 10.10.0) LOG: 'systemjs addToError - msg:Error loading http://localhost:9876/node_modules/ng2-bootstrap/package.json, err: ', Error{}
    Firefox 48.0.0 (Mac OS X 10.10.0) ERROR: Error{stack: null, originalErr: Error{}}
    LOG: 'systemjs addToError - msg:Evaluating http://localhost:9876/base/dist/dev/app/shared/jsonix/jsonix.service.js, err: ', ReferenceError{}

And that helped me track down where the error lies.  I haven't yet worked out what is causing the problem.  

This issue is a request to fix / improve the logging so you see something meaningful such as what can be seen by my change.

**Comment by guybedford** [comment]
Which version of SystemJS are you using here? The error may be slightly clearer in the latest version.

**Comment by oehm-smith** [comment]
I was using 0.19.27 and upgraded to 0.19.38, the most current version at this time.  It shows more detail but still doesn't highlight the problem.  It shows:

    16 09 2016 10:40:07.476:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
    16 09 2016 10:40:07.480:INFO [launcher]: Starting browser Chrome
    [10:40:07] copy.js.local normal files 0 items
    [10:40:07] copy.js.local service worker files 0 items
    16 09 2016 10:40:08.463:INFO [Chrome 52.0.2743 (Mac OS X 10.10.5)]: Connected on socket /#pLWbdBIaZDzTHuE0AAAA with id 17240373
    16 09 2016 10:40:09.155:WARN [web-server]: 404: /node_modules/ng2-bootstrap/package.json
    Chrome 52.0.2743 (Mac OS X 10.10.5) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
        Error: XHR error (404 Not Found) loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:636:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:225:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:125:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:293:33)
        Error loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
        Error loading http://localhost:9876/base/dist/dev/app/shared/shared.module.js as "../shared/shared.module" from http://localhost:9876/base/dist/dev/app/home/home.module.js'
      About component
        ✔ should work

    Finished in 0.072 secs / 0.152 secs

If I add the console.out line back into `addToError(err, msg)` it shows more information that helped us solve the problem (which was: 1) the jsonix.service's node_module dependencies needed to be added to the `karma Files[]`, and 2) the bg2-bootstrap and moment needed to be added as a map in the `karma test-config.js`):

    16 09 2016 10:42:46.750:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
    16 09 2016 10:42:46.754:INFO [launcher]: Starting browser Chrome
    [10:42:46] copy.js.local normal files 0 items
    [10:42:46] copy.js.local service worker files 0 items
    16 09 2016 10:42:47.739:INFO [Chrome 52.0.2743 (Mac OS X 10.10.5)]: Connected on socket /#bBBDHRZVX3EPu-OTAAAA with id 57081853
    16 09 2016 10:42:48.652:WARN [web-server]: 404: /node_modules/ng2-bootstrap/package.json
    Chrome 52.0.2743 (Mac OS X 10.10.5) LOG: 'system.js - addToError - msg: Error loading http://localhost:9876/node_modules/ng2-bootstrap/package.json, err: ', Error{}
    Chrome 52.0.2743 (Mac OS X 10.10.5) LOG: 'system.js - addToError - msg: Error loading http://localhost:9876/base/dist/dev/app/shared/shared.module.js as "../shared/shared.module" from http://localhost:9876/base/dist/dev/app/home/home.module.js, err: ', Error{originalErr: Error{}}
    Chrome 52.0.2743 (Mac OS X 10.10.5) LOG: 'system.js - addToError - msg: Error loading http://localhost:9876/base/dist/dev/app/shared/shared.module.js as "../shared/shared.module" from http://localhost:9876/base/dist/dev/app/select-site/select-site.module.js, err: ', Error{originalErr: Error{}}
    Chrome 52.0.2743 (Mac OS X 10.10.5) ERROR: '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
        Error: XHR error (404 Not Found) loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
            at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:636:29)
            at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:225:37)
            at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:125:47)
            at XMLHttpRequest.ZoneTask.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?f8afdc0a1fd11e453f00ee26da18050645299a9a:293:33)
        Error loading http://localhost:9876/node_modules/ng2-bootstrap/package.json
        Error loading http://localhost:9876/base/dist/dev/app/shared/shared.module.js as "../shared/shared.module" from http://localhost:9876/base/dist/dev/app/home/home.module.js'
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/shared/jsonix/jsonix.service.js, err: ', ReferenceError{}
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/shared/cors-site/cors-site.service.js, err: ', Error{originalErr: ReferenceError{}}
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/shared/cors-site/index.js, err: ', Error{originalErr: ReferenceError{}}
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/shared/index.js, err: ', Error{originalErr: ReferenceError{}}
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/app.component.js, err: ', Error{originalErr: ReferenceError{}}
    LOG: 'system.js - addToError - msg: Evaluating http://localhost:9876/base/dist/dev/app/app.component.spec.js, err: ', Error{originalErr: ReferenceError{}}
    LOG: 'system.js - addToError - msg: Error loading http://localhost:9876/base/dist/dev/app/app.component.spec.js, err: ', Error{originalErr: ReferenceError{}}
      About component
        ✔ should work

**Comment by guybedford** [comment]
Great to hear you were able to resolve the issue.
