### ISSUE TITLE
Loading ASP.Net MVC action result via SystemJS

### ISSUE THREAD

**Issue by abhiphirke** [systemjs/systemjs#1448]
Hi... I want to load the ASP.Net MVC response via SystemJS. My MVC action URL is /HOME/Loader. My config looks like this:

```
(function (global) {
    System.config({
        baseURL: 'http://localhost:53330/',
        defaultJSExtensions: false,
        paths: {
        },
        map: {
            app: '',
        },
        packages: {
            app: {
                main: 'Home/Loader',
            }
        }
    });
})(this);
```

While loading this resource, SystemJS is still appending default exception '.js' to URL, that is, it trying to load http://localhost:53330/Home/Loader.js which of course does not exist.

How can I have SystemJS not add default exception '.js' to URL? Any help is much appreciated.

**_UPDATE:_**
While I further stepped through code, I found out that the addDefaultExtension function is not really making any user of defaultJSExtensions config setting before setting the '.js' extension. Is this not a bug? Also, the function has a comment:
`// NB reconsider if default should really be ".js"?`
I am using SystemJS v0.19.27. Is this resolved in newer versions?

**Comment by aluanhaddad** [comment]
Try adding `"defaultExtension": false` to `packages.app`. You should upgrade to 0.19.39 though
