### ISSUE TITLE
Question: possible to load node module but not look for .map files

### ISSUE THREAD

**Issue by johntzan** [systemjs/systemjs#1449]
I am building an angular2 app, the app works fine except when loading a node module dependency i get 404 errors in my server console for all of its .js files looking for the .map files. And this node module did not come with .map files but does reference them in all js files with //sourceMappingURL. 

The module loads and works fine within the app, but when pushed to heroku, the 404 errors getting those map files causes errors and the app does not load. How can i point systemjs to not look for those map files?

**Comment by fictitious** [comment]
It's not SystemJS that requests these files, it's the browser. I think the only way to stop it is to remove any references to source maps from .js files.

**Comment by johntzan** [comment]
@fictitious Are you sure? the error comes up on the servers log and Systemjs errors. Removing the references to source maps means directly changing a node_module, and then I would have to check that specific module into git and push it to heroku.
