### ISSUE TITLE
Allow the use of regexp/glob in map to specify modules to load

### ISSUE THREAD

**Issue by mtpc** [systemjs/systemjs#1450]
Currently the only way to specify which loader to use for a specific file extension is by using a wildcard:
```javascript
System.config({
  ...,
  meta: {
    '*.js': {
      ...
    }
  }
})
```
Ideally, you'd use something like that:
```javascript
System.config({
  ...,
  meta: {
    // regexp
    '\\.(jpg|png|txt)$': {
      ...
    },
    // glob
    '!(*.jpg|*.txt)': { }
  }
})
```

**Comment by guybedford** [comment]
Yeah minimatch would be nice but isn't really suitable for this browser use case which needs to be small enough to fit into the loader and fast as well.
