### ISSUE TITLE
Error : Unable to load transpiler to transpile http://localhost:8080/LKMonitoring/node_modules/@angular/http/index.js

### ISSUE THREAD

**Issue by RohitRane** [systemjs/systemjs#1452]
You have mentioned in issue number 1408 that this error arises from comment block wrapping import statements.

But I don't see any such statements. But the angular 2 library do have such statements. 

Here is the stack trace of my error : 
**Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:8080/MyProject/traceur
	patchProperty/desc.set/wrapFn@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:636:26
	ZoneDelegate.prototype.invokeTask@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:225:23
	Zone.prototype.runTask@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:125:28
	ZoneTask/this.invoke@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:293:28
	
	Error loading http://localhost:8080/MyProject/traceur
	Unable to load transpiler to transpile http://localhost:8080/MyProject/node_modules/@angular/http/index.js
	Error loading http://localhost:8080/MyProject/node_modules/@angular/http/index.js as "@angular/http" from http://localhost:8080/MyProject/app/boot.js
Stack trace:
(SystemJS) XHR error (404 Not Found) loading http://localhost:8080/MyProject/traceur
	patchProperty/desc.set/wrapFn@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:636:26
	ZoneDelegate.prototype.invokeTask@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:225:23
	Zone.prototype.runTask@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:125:28
	ZoneTask/this.invoke@http://localhost:8080/MyProject/node_modules/zone.js/dist/zone.js:293:28
	
	Error loading http://localhost:8080/MyProject/traceur
	Unable to load transpiler to transpile http://localhost:8080/MyProject/node_modules/@angular/http/index.js
	Error loading http://localhost:8080/MyProject/node_modules/@angular/http/index.js as "@angular/http" from http://localhost:8080/MyProject/app/boot.jsMyProject:27:49
<anonymous>MyProject:27
ZoneDelegate.prototype.invoke()zone.js:192
Zone.prototype.run()zone.js:85
scheduleResolveOrReject/<()zone.js:451
ZoneDelegate.prototype.invokeTask()zone.js:225
Zone.prototype.runTask()zone.js:125
drainMicroTaskQueue()zone.js:357
ZoneTask/this.invoke()zone.js:297**
        
I am not great at reading stack traces. Is there a way to tell from this stack trace as to which file I need to look for the erroneous code?

Please guide as I am not able to get up application up running at all and all development is blocked due to this bug.

**Comment by guybedford** [comment]
You can try enforcing the module format via configuration like:

```javascript
System.config({
  meta: {
    'LKMonitoring/node_modules/@angular/*.js': {
      format: 'cjs'
    }
  }
});
```

But it may be best to try and follow an existing boilerplate for this workflow. @born2net may be able to advise here with their work on Angular2 support in https://github.com/jspm/jspm-cli/issues/2079.

**Comment by born2net** [comment]
this project works GREAT with jspm and hrm, so follow its setup.

- no babel or tracer or any unneeded libs, just pure TypeScript
- supports HRM
- support production and dev modes
- support TypeScript path mapping so you DON'T need libs in both node_modules and jspm_packages, essentially allowing to move all to jspm

it's all here: https://github.com/born2net/studioDashboard

Regards,

Sean

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

Sean

**Comment by RohitRane** [comment]
I haven't found a permanent solution for this issue, but deleting and reinstalling the tomcat7 server used in my projects seems to be solving the issue for a few builds
