### ISSUE TITLE
Some requires are not detected // require('x' + '')

### ISSUE THREAD

**Issue by andreas-wagner** [systemjs/systemjs#1453]
Hi,

i noticed when trying to use bunyan in a node app that I start with jspm run.

bunyan.js seems to test for availability of mv and dtrace-provider modules with require('mv' + '') or require('dtrace-provider' + '') respectively.

This seems to be fruitless and results in ignored/unresolved requires.
Is there a way to fix/circumvent this other than editing foreign code, like force + '' detection for example?

**Comment by andreas-wagner** [comment]
This may also be the reason why sequelize does not work with jspm / SystemJS, as sequelize tries to load the correct modules (maybe with require('mysql' + '')) for the specified database.

**Comment by guybedford** [comment]
Yes this is a limitation of SystemJS resolution.

Dependencies like this can be provided via meta configuration:

```javascript
System.config({
  meta: {
    'path/to/some/cjs/file.js': { deps: ['dtrace-provider', 'mv'] }
  }
});
```

**Comment by andreas-wagner** [comment]
Looks like it did not help:

`System.config({
  meta: {
    'bunyan': { deps: ['dtrace-provider', 'mv'] }
  }
});

import Bunyan from 'bunyan';

let myLogger = Bunyan.createLogger({
  name: 'default',
  streams: [{
    type: 'rotating-file',
    path: './log/test.log',
    level: 'debug',
    period: '1d',
    count: 14
  }]
});`

That produces:

`err  (SystemJS) "rotating-file" stream type is not supported: missing "mv" module
  AssertionError: "rotating-file" stream type is not supported: missing "mv" module
      at Logger.addStream (C:/code/logger/jspm_packages/npm/bunyan@1.8.1/lib/bunyan.js:606:16)
      at C:/code/logger/jspm_packages/npm/bunyan@1.8.1/lib/bunyan.js:469:18
      at Array.forEach (native)
      at new Logger (C:/code/logger/jspm_packages/npm/bunyan@1.8.1/lib/bunyan.js:468:25)
      at Function.createLogger (C:/code/logger/jspm_packages/npm/bunyan@1.8.1/lib/bunyan.js:1549:12)
      at execute (C:/code/logger/index.js!transpiled:179:24)
  Error loading C:/code/logger/index.js`

**Comment by andreas-wagner** [comment]
I forgot to mention that I use jspm v0.17.0-beta.28.

My package.json:

`{
  "jspm": {
    "name": "logger",
    "main": "index.js",
    "dependencies": {
      "bunyan": "npm:bunyan@^1.8.1"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.15"
    },
    "peerDependencies": {
      "assert": "github:jspm/nodelibs-assert@^0.2.0-alpha",
      "buffer": "github:jspm/nodelibs-buffer@^0.2.0-alpha",
      "child_process": "github:jspm/nodelibs-child_process@^0.2.0-alpha",
      "constants": "github:jspm/nodelibs-constants@^0.2.0-alpha",
      "crypto": "github:jspm/nodelibs-crypto@^0.2.0-alpha",
      "dtrace-provider": "npm:dtrace-provider@~0.6",
      "events": "github:jspm/nodelibs-events@^0.2.0-alpha",
      "fs": "github:jspm/nodelibs-fs@^0.2.0-alpha",
      "moment": "npm:moment@^2.10.6",
      "mv": "npm:mv@~2",
      "os": "github:jspm/nodelibs-os@^0.2.0-alpha",
      "path": "github:jspm/nodelibs-path@^0.2.0-alpha",
      "process": "github:jspm/nodelibs-process@^0.2.0-alpha",
      "safe-json-stringify": "npm:safe-json-stringify@~1",
      "stream": "github:jspm/nodelibs-stream@^0.2.0-alpha",
      "string_decoder": "github:jspm/nodelibs-string_decoder@^0.2.0-alpha",
      "util": "github:jspm/nodelibs-util@^0.2.0-alpha",
      "vm": "github:jspm/nodelibs-vm@^0.2.0-alpha"
    },
    "overrides": {
      "npm:inherits@2.0.3": {
        "ignore": [
          "test.js"
        ]
      },
      "npm:moment@2.15.1": {
        "jspmNodeConversion": false
      }
    }
  }
}`

As you can see 'mv' is there as well as 'dtrace-provider'.

My jspm.config.js is pretty long, but there is nothing special in there (untouched after `jspm init` and `jspm install npm:bunyan`.

Oh I also use `jspm run index.js` to start the app.

**Comment by guybedford** [comment]
@andreas-wagner run `System.normalizeSync('bunyan')` in the browser, and use that name in the meta configuration rather. Mains are not applied in meta normalization (https://github.com/systemjs/systemjs/issues/1331).

**Comment by andreas-wagner** [comment]
I am using this as a node app with jspm run instead of in the browser. I tried it but it still doesn't help. I also tried importing the packages manually before importing bunyan:

`import 'mv';
import 'dtrace-provider';
System.normalizeSync('bunyan');
System.config({
  meta: {
    'bunyan': { deps: ['dtrace-provider', 'mv'] },
    'bunyan/lib/bunyan.js': { deps: ['dtrace-provider', 'mv'] }
  }
});
import Bunyan from 'bunyan';
...`

The error still remains, meaning that this does not work somehow:

`try {
    var mv = require('mv' + '');
} catch (e) {
    mv = null;
}
assert.ok(mv, '"rotating-file" stream type is not supported: missing "mv" module');`

:-(

**Comment by guybedford** [comment]
You need to run `System.config` in a separate script to the `import` script:

```javascript
System.config({
  meta: {
    'bunyan/lib/bunyan.js': { deps: ['dtrace-rovider', 'mv'] }
  }
});
System.import('bunyan');
```

**Comment by andreas-wagner** [comment]
Thank you very much, the following worked:

```
System.config({
  meta: {
    'bunyan/lib/bunyan.js': { deps: ['dtrace-provider', 'mv'] }
  }
});

System.import('bunyan').then((Bunyan) => {
  let myLogger = Bunyan.createLogger({
    name: 'default',
    streams: [{
      type: 'rotating-file',
      path: './log/test.log',
      level: 'debug',
      period: '1d',
      count: 14
    }]
  });
  myLogger.info('w00t');
}, (error) => {
  console.log(error);
}).catch((error) => {
  console.log(error);
});
```

Is there a way to use a working normal import statement like `import Bunyan from 'bunyan'`?

**Comment by andreas-wagner** [comment]
Adding this block to `jspm.config.js` solved it:
```
SystemJS.config({
  "meta": {
    "bunyan/lib/bunyan.js": {
      "deps": ["dtrace-provider", "mv"]
    }
  }
});
```

Now I can normally import bunyan without any code-side 'workarounds';

I fully support 'Apply package main to meta' ([#1331](https://github.com/systemjs/systemjs/issues/1331)) btw, because I would have to know the main for every single package I figure out a workaround for.

As packages are being updated that package main may change. Updating an older project may yield  strange errors and it will take quite some time to remember what the fix was, especially since the fix is seemingly still there (but the main changed and maybe it has to be "bunyan/lib/index.js" instead of "bunyan/lib/bunyan.js" now)...

Anyway thank you very much for your help, you are top-notch, fast and reliable. Thumbs up :-)

**Comment by andreas-wagner** [comment]
@guybedford I tried to turn this fix into an override but it does not seem to work.

`jspm install npm:bunyan -o "{meta: {'bunyan/lib/bunyan.js': {'deps': ['dtrace-provider', 'mv']}}}"`

Can you tell me why?

**Comment by andreas-wagner** [comment]
I figured it out, in the override it should not be `bunyan/lib/bunyan.js` but of course be `./lib/bunyan.js` instead.

Respecting the full meta (as SystemJS does not mangle it, but completely replace it) it becomes:
`jspm install npm:bunyan -o "{'meta': {'*': {'globals': {'process': 'process'}}, '*.json': {'format': 'json'}, 'lib/*': {'globals': {'Buffer': 'buffer/global'}}, './lib/bunyan.js': {'deps': ['dtrace-provider', 'mv']}}}"`
