### ISSUE TITLE
Package Relative Map Issues - Multiple Node/CJS Path Styles In Same Package

### ISSUE THREAD

**Issue by RyanThomas73** [systemjs/systemjs#1455]
I was hoping to use SystemJS Builder to compile my react-native app for the browser using react-native-web. I'm still unable to get it to properly handle module resolution. Below is roughly the config that I would need to handle module resolution within the react-native-web package that I'm using.

```
System.config({
	defaultJSExtensions: true,
	map: {
		'react-native': 'react-native-web'
	},
	packages: {
		'react-native': {
			defaultExtension: false,
			main: 'dist/index.js',
			map: {
				// If I'm using defaultJSExtensions it can resolve paths like
				// ./dist/modules/injectResponderEventPlugin.js without problem
				// but it fails to resolve the modules like this ./dist/modules/*/index.js

				// If I turn off default extension and map ./dist/* to ./dist/*/index.js
				// then it fails to resolve the files that aren't in a named folder.

				// I'm trying to achieve support for node module resolution for both
				// since this package (and potentially others) mixes path styles

				// something like this is what I was hoping would work but the .js
				// after the wildcard is completely ignored
				'./dist/*': ['./dist/*.js', './dist/*/index.js']
			}
		}
	},
	packageConfigPaths: ['*/package.json'],
	paths: {
		'*': 'node_modules/*',
		'typescript_bin/*': 'typescript_bin/*'
	}
});
```

**Comment by guybedford** [comment]
I would suggest turning off `defaultJSExtensions` entirely as that will be deprecated.

Then try something like:

```javascript
packages: {
'react-native': {
            defaultExtension: 'js',
            main: 'dist/index.js',
            map: {
                // wildcard map isn't supported so you have to
                // individually create this for each "x" that gives issues
                './dist/x': './dist/x/index.js' 
            }
        }
}
```

It may also be worth trying out jspm 0.17 and running `jspm install npm:react-native && cat jspm_packages/npm/react-native@x.y.z.json` to see how jspm generates the correct SystemJS configuration for react native as well.

**Comment by RyanThomas73** [comment]
@guybedford 

Thank you for the suggestions. I have no desire to manually define every path for all of the npm dependencies that my project uses. I attempted to use jspm has you suggested. Unfortunately the generated .json file is not complete and does not correctly resolve all of the paths per the npm path resolution. I would have to add potentially more than 500 additional path mappings to the below generated .json file in order to allow the react-native-web package paths to resolve. This in addition to all the other packages that I will need to define would be prohibitively time consuming.

`jspm install npm:react-native-web && cat jspm_packages/npm/react-native-web@0.0.45.json`
**Below is the generated .json file**

"main": "dist/index.js",
  "format": "cjs",
  "meta": {
    "*": {
      "globals": {
        "process": "process"
      }
    },
    "*.json": {
      "format": "json"
    }
  },
  "map": {
    "./dist": "./dist/index.js",
    "./dist/apis/Animated": "./dist/apis/Animated/index.js",
    "./dist/apis/AppRegistry": "./dist/apis/AppRegistry/index.js",
    "./dist/apis/AppState": "./dist/apis/AppState/index.js",
    "./dist/apis/AsyncStorage": "./dist/apis/AsyncStorage/index.js",
    "./dist/apis/Dimensions": "./dist/apis/Dimensions/index.js",
    "./dist/apis/I18nManager": "./dist/apis/I18nManager/index.js",
    "./dist/apis/InteractionManager": "./dist/apis/InteractionManager/index.js",
    "./dist/apis/NetInfo": "./dist/apis/NetInfo/index.js",
    "./dist/apis/PanResponder": "./dist/apis/PanResponder/index.js",
    "./dist/apis/PixelRatio": "./dist/apis/PixelRatio/index.js",
    "./dist/apis/Platform": "./dist/apis/Platform/index.js",
    "./dist/apis/StyleSheet": "./dist/apis/StyleSheet/index.js",
    "./dist/apis/UIManager": "./dist/apis/UIManager/index.js",
    "./dist/apis/Vibration": "./dist/apis/Vibration/index.js",
    "./dist/components/ActivityIndicator": "./dist/components/ActivityIndicator/index.js",
    "./dist/components/Image": "./dist/components/Image/index.js",
    "./dist/components/ListView": "./dist/components/ListView/index.js",
    "./dist/components/ProgressBar": "./dist/components/ProgressBar/index.js",
    "./dist/components/ScrollView": "./dist/components/ScrollView/index.js",
    "./dist/components/StaticContainer": "./dist/components/StaticContainer/index.js",
    "./dist/components/StaticRenderer": "./dist/components/StaticRenderer/index.js",
    "./dist/components/Switch": "./dist/components/Switch/index.js",
    "./dist/components/Text": "./dist/components/Text/index.js",
    "./dist/components/TextInput": "./dist/components/TextInput/index.js",
    "./dist/components/View": "./dist/components/View/index.js",
    "./dist/modules/NativeMethodsMixin": "./dist/modules/NativeMethodsMixin/index.js",
    "./dist/modules/NativeModules": "./dist/modules/NativeModules/index.js",
    "./dist/modules/ReactNativePropRegistry": "./dist/modules/ReactNativePropRegistry/index.js",
    "./dist/modules/ScrollResponder": "./dist/modules/ScrollResponder/index.js",
    "./dist/modules/applyLayout": "./dist/modules/applyLayout/index.js",
    "./dist/modules/applyNativeMethods": "./dist/modules/applyNativeMethods/index.js",
    "./dist/modules/createDOMElement": "./dist/modules/createDOMElement/index.js",
    "./dist/modules/dismissKeyboard": "./dist/modules/dismissKeyboard/index.js",
    "./dist/modules/findNodeHandle": "./dist/modules/findNodeHandle/index.js",
    "./dist/modules/flattenStyle": "./dist/modules/flattenStyle/index.js",
    "./dist/modules/merge": "./dist/modules/merge/index.js",
    "./dist/modules/multiplyStyleLengthValue": "./dist/modules/multiplyStyleLengthValue/index.js",
    "./dist/modules/normalizeColor": "./dist/modules/normalizeColor/index.js"
  }

**Comment by RyanThomas73** [comment]
Since systemjs cannot resolve the paths automatically and there does not seem to be a viable solution to auto generate the necessary mappings I attempted to resolve the problem by using a custom loader plugin.

First I attempted to use the locate function like so to handle the resolution.
```
exports.locate = function(locateOptions) {
	var loader = this;

	var path = locateOptions.name;
	var needsFilePrefix = false;
	if(path.startsWith('file:///')) {
		path = path.substring(8);
		needsFilePrefix = true;
	}

	var resolvedPath = loader._nodeRequire.resolve(path);

	if(needsFilePrefix && !resolvedPath.startsWith('file:///'))
	{
		resolvedPath = 'file:///' + resolvedPath;
	}

	//console.log('Located: ' + resolvedPath + '\n');
	return resolvedPath;
}
```

This however prevented a problem because systemjs does not currently support hooking into the loader normalize method. When the above locate logic resolves a path like below:

`require('modules/applyLayout')` resolves to `'modules/applyLayout/index.js'`

The normalized parentName for for the above would still be `'modules/applyLayout'` which causes the corresponding dependencies to fail to resolve.

I tried adding a tenative patch to allow me to hook into the normalize logic like so:

```
function getPackageName(loader, normalizedName) {
  	// use most specific package
  	var currentPackage;
  	var currentPackageLength = 0;
  	var packageLength;

  	for (var nextPackage in loader.packages) {
  		if (normalizedName.substr(0, nextPackage.length) === nextPackage && (normalizedName.length === nextPackage.length || normalizedName[nextPackage.length] === '/')) {
  			packageLength = nextPackage.split('/').length;

  			if (packageLength > currentPackageLength) {
  				currentPackage = nextPackage;
  				currentPackageLength = packageLength;
  			}
  		}
  	}

  	return currentPackage;
  }

function getMetadataObject(loader, metadataConfig, load)
{
	var name = load.name;

	// apply wildcard metas
	var bestDepth = 0;
	var wildcardIndex;
	for (var module in metadataConfig) {
		wildcardIndex = module.indexOf('*');
		if (wildcardIndex === -1) {
			// we don't have a wildcard for this config element so continue
			continue;
	  	}

		if (module.substr(0, wildcardIndex) === name.substr(0, wildcardIndex)
			&& module.substr(wildcardIndex + 1) === name.substr(name.length - module.length + wildcardIndex + 1)) {

			var depth = module.split('/').length;
			if (depth > bestDepth) {
				bestDepth = depth;
			}

			extendMeta(load.metadata, metadataConfig[module], bestDepth != depth);
		}
	}

	// apply exact meta
	if (metadataConfig[name]) {
		extendMeta(load.metadata, metadataConfig[name]);
	}

	if(load.metadata.loader && load.name == load.metadata.loader) {
		load.metadata = {};
		return Promise.resolve('');
	}

	return loader.locate(load);
}


hook('normalize', function(normalize) {
	return function(name, parentName, isPlugin) {
		var loader = this;

		parentName = getParentName(this, parentName);

		var packageName = getPackageName(loader, name);
		if(!packageName && parentName) {
			packageName = getPackageName(loader, parentName);
		}

		var debugOutput = false;
		if(name.endsWith('Image')) {
			console.log('\nNORMALIZING');
			console.log('\tName: ' + name);
			console.log('\tParent Name: ' + parentName);
			debugOutput = true;
		}

		if(packageName) {
			if(debugOutput) {
				console.log('\tPackage Name: ' + packageName);
			}

			var loaderPackage = loader.packages[packageName];

			if(debugOutput) {
				console.log('\tMeta Config: ')
				console.log(loaderPackage.meta);
			}

			if(loaderPackage.meta) {
				var load = {};
				load.name = name;
				load.metadata = {};
				load._debugOutput = debugOutput;

				if(debugOutput) {
					console.log('\tGetting Metadata Object...');
				}

				var metadataObject = getMetadataObject(loader, loaderPackage.meta, load);

				if(debugOutput) {
					console.log('\tName Check: ' + name);
					console.log('\tWaiting For Promise Resolution...');
				}

				return metadataObject.then(function (metadataPromiseResult) {
					if(load.metadata.loaderModule && load.metadata.loaderModule.normalize) {
						return load.metadata.loaderModule.normalize.call(loader, name, parentName);
					}

					return normalize.call(loader, name, parentName, isPlugin);
				});
			}
		}

      var parsed = parsePlugin(loader, name);

      if (!parsed)
        return normalize.call(loader, name, parentName, isPlugin);

      return Promise.all([
        loader.normalize(parsed.argument, parentName, true),
        loader.normalize(parsed.plugin, parentName, false)
      ])
      .then(function(normalized) {
        return combinePluginParts(loader, normalized[0], normalized[1], checkDefaultExtension(loader, parsed.argument));
      });
    }
  });

```

This however resulted in an error about the plugin attempting to load itself. At this point I'm unable to proceed further with investigating; the code isn't really self documenting enough for me to resolve further issues without starting at the entry point and stepping through the entire library's source code.

If you could provide me with assistance in determining what it would require for me to proceed forward with a plugin like this then I could investigate further.

I appreciate if you can help me in determining if this would be a potential resolution. If not I'll accept that systemjs doesn't have the capabilities to handle node modules at this time and investigate some other libraries that our out there.

Thanks much for any assistance.

**Comment by guybedford** [comment]
I'm not sure I understand how jspm 0.17 didn't cover this for you?

If I run `jspm install npm:react-native-web && jspm run react-native-web` the execution of the library seems to run fine in jspm.

I would not advise using SystemJS on its own at all here though.

**Comment by winpzs** [comment]
If I had thousands of JS.....

**Comment by RyanThomas73** [comment]
@guybedford 

Using jspm 0.17 + builder does work for me.

My comment about it not working was in reference to your suggestion of using jspm to generate a package config so I could see how a correct/complete config for the react-native-web package. The generated package config would not work directly because of the differences between how jspm and npm handle the proverbially 'dependency hell'.

I did not want to try using jspm directly because as far as I can tell I would then need to maintain all of the dependencies twice:

- As npm dependencies for the react-native cli to resolve them when building for android and ios.
- As jspm dependencies for the jspm builder to resolve them when building against react-native-web for the browser.

Since a jspm setup does work I'll go ahead and close this issue.
