### ISSUE TITLE
Potentially unhandled rejection

### ISSUE THREAD

**Issue by super2457** [systemjs/systemjs#1456]
Hello! ie browser appear “Potentially unhandled rejection [2] (SystemJS)", How to solve this error, Thank you.

**Comment by super2457** [comment]
![qq 20160927174324](https://cloud.githubusercontent.com/assets/9149356/18868235/02d80e2a-84da-11e6-8c57-7b5c5a6c84b7.jpg)

**Comment by guybedford** [comment]
Make sure to add a catch handler to your promise - `System.import('x').catch(function (e) {...})`.
