### ISSUE TITLE
node-postgres native always loaded

### ISSUE THREAD

**Issue by andreas-wagner** [systemjs/systemjs#1458]
If I install node-postgres (`jspm install npm:pg`) and just do `System.import('pg')` SystemJS tries to load `.../jspm_packages/npm/pg@6.1.0/lib/native/index.js`.

This is however a optional require (taken from `.../jspm_packages/npm/pg@6.1.0/lib/index.js`):
```
if(typeof process.env.NODE_PG_FORCE_NATIVE != 'undefined') {
  module.exports = new PG(require('./native'));
}
```

I tried to prevent loading it by doing
```
System.config({
  map: {
    "pg/lib/index.js": {
      "./lib/native/index.js": "@empty"
    }
});
```
which seems to get me one step further (complains about `pg-types` not being there, solved by installing it), only to result in the same error again.
That means somehow it did not work 100%, as commenting out the require line in `pg@6.1.0\lib\index.js` solves all problems.

Is there anything else I could try?

**Comment by andreas-wagner** [comment]
I tried modifying the `jspm_packages/npm/pg@6.1.0.json` file and replaced
```
"map": {
    "./lib": "./lib/index.js",
    "./lib/native": "./lib/native/index.js"
  }
```
with
```
"map": {
    "./lib": "./lib/index.js",
    "./lib/native": "@empty"
  }
```
and it worked.

I am not into the SystemJS depths, but find it strange that this works, whereas my workaround above (using `System.config`) does not.

Can you explain that to me?

And can you tell me how to achieve the same result with `System.config` if possible?
If not then I need to use an override I guess, I've never done that, so I would need some help with that as well.

Thank you very much in advance :-)

**Comment by guybedford** [comment]
The method that you found is exactly the correct way to do this. It probably would have worked via `System.config` too if you'd used the `"./lib/native": "@empty"` map instead of `"./lib/native/index.js": "@empty"`. The reason being that package map configuration isn't transitive - it only applies once.

**Comment by andreas-wagner** [comment]
I tried the `"./lib/native": "@empty"` map as well, but that did not work at all.

Solved it by installing it with the override:
`jspm install npm:pg -o "{map: {'./lib/native': '@empty'}}"`

`npm:pg-types` has to be installed as well as it is a dependency that is not automatically installed by jspm.

**Comment by andreas-wagner** [comment]
Something I just noticed:

Installing it with the override removes all other maps.

with override:
```
"map": {
    "./lib/native": "@empty"
  }
```
without override:
```
"map": {
    "./lib": "./lib/index.js",
    "./lib/native": "./lib/native/index.js"
  }
```

I actually wanted to override just `"./lib/native": "@empty"`, can it be done without specifying everything (`jspm install npm:pg -o "{map: {'./lib': './lib/index.js', './lib/native': '@empty'}}"`)?

**Comment by andreas-wagner** [comment]
Found out how to include the dep for `npm:pg-types`:
`jspm install npm:pg -o "{map: {'./lib': './lib/index.js', './lib/native': '@empty'}, deps: ['npm:pg-types']}"`

The question still remains:
Is there a way to only change a single map entry?

**Comment by guybedford** [comment]
No, the map is either manual or automatically handled... there isn't an in-between mode.

**Comment by andreas-wagner** [comment]
Sad thing, but I'm still happy that it works now, thank you :-)
