### ISSUE TITLE
Minimal transpilation: transpile import / export statements exclusively

### ISSUE THREAD

**Issue by barneycarroll** [systemjs/systemjs#1459]
I want to import raw ES6 modules in the browser, but don't want to transpile anything of the runtime code - in other words I only want transpilation inasmuch as `import` & `export` are concerned. What's the best out-of-the-box option to provide to `SystemJS.config`'s `transpiler` to avoid transpiling runtime code?

**Comment by guybedford** [comment]
Just a straightforward Babel transform of the modules, with only the `babel-plugin-transform-es2015-modules-systemjs` transform applied to each module.

**Comment by barneycarroll** [comment]
Thanks! Given that the SystemJS plugin [`plugin-babel`](https://github.com/systemjs/plugin-babel) comes with stage 1 & 2 baked in, how would I invoke the Babel plugin [`plugin-transform-es2015-modules-systemjs`](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-systemjs) without those?

Could you show me what the `SystemJS.config` object would look like please?

**Comment by guybedford** [comment]
You should be able to just use:

```javascript
SystemJS.config({
  meta: {
    '*.js': {
      babelOptions: {
        es2015: false,
        stage2: false,
        stage3: false
      }
    }
  }
});
```

**Comment by barneycarroll** [comment]
Thanks Guy. For anyone else looking, here's the full config for a standalone setup with out of the box tooling that doesn't require custom build only transforms import / export statements:

```javascript
SystemJS.config( {
  map : {
    'plugin-babel'         : 'https://cdn.rawgit.com/systemjs/plugin-babel/master/plugin-babel.js',
    'systemjs-babel-build' : 'https://cdn.rawgit.com/systemjs/plugin-babel/master/systemjs-babel-browser.js'
  },
      
  transpiler: 'plugin-babel',
  
  meta: {
    '*.js' : {
      babelOptions : {
        es2015 : false,
        stage2 : false,
        stage3 : false
      }
    }
  }
} )
```

Now I'm struggling to see how your earlier allusion to `babel-plugin-transform-es2015-modules-systemjs` would fit into a SystemJS codebase in practice. Reading between the lines, I assume either:

1. Roll your own SystemJS Babel plugin that invokes Babel without any presets, and register the aforementioned plugin in the SystemJS Babel config
2. Run Babel with SystemJS transform plugin ahead of time, and import those files from the SystemJS without running any transforms.

Number 2 seems unlikely - [the docs for the `transpiler` field](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#transpiler) imply that SystemJS *needs* to transpile according to one of baked-in presets. I suppose I'm asking what extra tooling I'd need to develop in order to avoid downloading a full ES6 transpiler, when I'm only interested in making es2015 modules play nice with SystemJS.

**Comment by guybedford** [comment]
Precompiling for SystemJS as in (2) is an advisable workflow and will always give the best performance as well.
