### ISSUE TITLE
IE11: Potentially unhandled rejection [8] (SystemJS) Unable to get the property "lastIndexOf" link, which is not defined or is NULL

### ISSUE THREAD

**Issue by believer-ufa** [systemjs/systemjs#1464]
I have this error message on my project which working on jspm@beta.

In browser console i see what error occurs in `/jspm_packages/system.src.js:4758:5`.

Its a `booleanConditional` function. Internet Explorer not always gets in first parameter a `string` variable. Source code of this function [here](https://github.com/systemjs/systemjs/blob/master/lib/conditionals.js#L126-L147).

I added small check in this function:

``` js
function booleanConditional(name, parentName) {

    // In some situations in IE we get not String in this var and we need to resolve it..
    if (typeof name !== 'string') {
      name = ''
    }

    // ...
}
```

And now my IE11 browser works fine. What about solve this issue with this or other approaches?

P.S. Please take into consideration: this problem is floating and does not occur every time.

**Comment by guybedford** [comment]
This would happen if you call `System.normalize()` without any arguments. Perhaps try throwing to see who the caller is in this scenario?

**Comment by believer-ufa** [comment]
I will try to create a small copy of our project which show this problem and give you access to Cloud9 virtual machine with this code. I working on it now.

**Comment by believer-ufa** [comment]
I still trying to determine error and today i decided to add `console.log()` command in `buildGroups` functions. With it i understood how modules throws an errors. This is modules what depends from jQuery:

![image](https://cloud.githubusercontent.com/assets/801727/19058519/6f617466-89f1-11e6-881e-6d63f924310d.png)

![image](https://cloud.githubusercontent.com/assets/801727/19058531/85fd8f98-89f1-11e6-85ef-8f549d72e023.png)

![image](https://cloud.githubusercontent.com/assets/801727/19058541/9206fc70-89f1-11e6-9d90-996dad12d8d6.png)

I still dont know why this error occurs from time to time in IE11. And what is even more depressing - is that an error occurs in about 10-20% of launches IE11.

**Comment by believer-ufa** [comment]
If adding in `console.log` whole object, we can see his properties:

![image](https://cloud.githubusercontent.com/assets/801727/19058974/411fed72-89f5-11e6-80c7-71d0b3c452ce.png)

During start-up with no errors, we can see what `normalizedDeps` property have correct empty `array` value.

![image](https://cloud.githubusercontent.com/assets/801727/19059023/c0f7d910-89f5-11e6-9b68-9164cf7bd136.png)

**Comment by believer-ufa** [comment]
Just one thing what i understood in my analyse is what in Error-case runs IE11 trying to load my modules many-many times instead one time. Please, check this screenshot:

![image](https://cloud.githubusercontent.com/assets/801727/19059096/7f55ab12-89f6-11e6-9151-5be2e3dda1c7.png)

**Comment by guybedford** [comment]
If you're able to provide any replication here that would help a lot to investigate further.
