### ISSUE TITLE
Minified version of system.js has incorrectly used default word that is keyword in IE8

### ISSUE THREAD

**Issue by karol1990** [systemjs/systemjs#1467]
Guys,

It seems that your minified version of system.js uses default word (that is often property of an object) incorrectly (without quotes) that makes application inconsistent with IE8 browser to which it's an keyword.
It doesn't happen in system.src.js so there is probably sth in your minification tool.

**Comment by guybedford** [comment]
Thanks. Yes, it seems like the minifier is removing this.

A custom regex replacement to replace `/\.default[^\w]/` with `["default"]$1` as part of the makefile can likely fix this, any PR help adding in a script like that is welcome.

**Comment by asapach** [comment]
My guess is that it would be `screw-ie8` option in uglifyjs, but it should be off by default in that particular version.

**Comment by MikeBKemp** [comment]
Not sure if this helps, but if I build from source the default keyword is correctly quoted in the minified file. As mentioned above, adding `screw-ie8` replicates the issue.

**Comment by guybedford** [comment]
A PR here is welcome. Perhaps a recent version of UgilfyJS made screw-ie8 the default and we need to switch it back? That's the best I can think of.

**Comment by MikeBKemp** [comment]
It looks like `screw-ie8` is the default in uglify-js 2.7.0, where you can use `support-ie8` to switch it back. I'm happy to submit a PR adding that flag, but I'm a little unsure why the flag would be necessary, as the version here is ~2.4.23?

**Comment by guybedford** [comment]
@MikeBKemp thanks my local version may have got out of sync somehow then. Will sort this for the next release then.

**Comment by guybedford** [comment]
This should be fixed in 0.19.42, but let me know if it is still an issue at all.
