### ISSUE TITLE
Dynamic systemjs loading does not work on IE

### ISSUE THREAD

**Issue by mariosant** [systemjs/systemjs#1468]
I have to load systemjs dynamically (yes, the actual library). This works perfectly on Google Chrome, Edge and Firefox latest versions, it does work on Internet Explorer (tested 11, 10 and 9).

I have set this jsfiddle for an example reference.
https://jsbin.com/julomuc/edit?js,console

Console Outputs:
```
Chrome, Edge and Firefox:
SystemJS is object

Internet Explorer:
SystemJS is undefined
```

**Comment by guybedford** [comment]
Make sure to include a promise polyfill before loading SystemJS in IE.

**Comment by mariosant** [comment]
@guybedford thank you, I will try that and let you guys know.

**Comment by mariosant** [comment]
@guybedford this solved the issue, indeed. I have updated [jsbin bucket](https://jsbin.com/julomuc/edit?js,console) for anyone encounters the same issue.
