### ISSUE TITLE
CommonJS format doesn't cover module.parent

### ISSUE THREAD

**Issue by diagramatics** [systemjs/systemjs#1470]
Trying to load bayorigin/uniqid but because of https://github.com/bayorigin/uniqid/blob/master/index.js#L33 that uses `module.parent` to check for a debug flag set on the parent module, building just breaks entirely with `parent` being undefined.

Can we cover this in `cjs.js`? It's specifically just a Node thing though.

**Comment by joeldenning** [comment]
@diagramatics for the uniqid package, specifically, https://github.com/bayorigin/uniqid/issues/9 will potentially fix this problem, if it's merged and published. In the meantime, though, you can do a `jspm install npm:uniqid@4.0.0 && jspm resolve --only npm:uniqid@4.0.0` to fix your problems.  I experienced this same problem and actually reverted all the way back to uniqid@1.0.0 to get things working for me, but it looks like [everything before uniqid@4.1.0](https://github.com/bayorigin/uniqid/commit/e61a84e0039f94e20bb8b61ebc43d379f6f3bfbf#diff-168726dbe96b3ce427e7fedce31bb0bcR33) would work.

Regarding the larger issue of whether to add support into systemjs for module.parent, I can't really speak to that. You can see some discussion about it at https://github.com/jspm/jspm-cli/issues/2134

**Comment by guybedford** [comment]
Closing as a wont fix.
