### ISSUE TITLE
Who has Systemjs Material UI React typescript example

### ISSUE THREAD

**Issue by neechange** [systemjs/systemjs#1471]
`System.define(System.normalizeSync('MUIApp'),`
import MUI from 'materialUI';
MUI;
`);

System.import('MUIApp').then(value => { }).catch(err => { console.error(err); });`

`system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/BottomNavigation/BottomNavigationItem net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
VM18649:110 Error: (SystemJS) (…)(anonymous function) @ VM18649:110
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Card/CardActions net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Card/CardHeader net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Card/CardMedia net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Card/CardTitle net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Card/CardText net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/GridList/GridTile net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/List/ListItem net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/List/makeSelectable net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/styles/MuiThemeProvider net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/RadioButton/RadioButtonGroup net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Stepper/Step net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Stepper/StepButton net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Stepper/StepContent net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Stepper/StepLabel net::ERR_FILE_NOT_FOUNDfetchTextFromURL @ system.src.js:1051(anonymous function) @ system.src.js:1781(anonymous function) @ system.src.js:1780(anonymous function) @ system.src.js:2809(anonymous function) @ system.src.js:3387(anonymous function) @ system.src.js:3701(anonymous function) @ system.src.js:4093(anonymous function) @ system.src.js:4556(anonymous function) @ system.src.js:4825(anonymous function) @ system.src.js:407
system.src.js:1051 GET file:///D:/WWW/node_modules/material-ui/Stepper/Stepper net::ERR_FILE_NOT_FOUND`

**Comment by guybedford** [comment]
Perhaps try jspm for these sorts of use cases.
