### ISSUE TITLE
incorrect configuration order. the baseurl must be configured with the first systemjs.config call

### ISSUE THREAD

**Issue by zeeshanjan82** [systemjs/systemjs#1473]
I am getting the following error after I build my jspm + systemjs project:
![error](https://cloud.githubusercontent.com/assets/8342604/19714500/6c675474-9b6c-11e6-94ea-b8d385fdc0cd.png)

I am using jspm version: 0.16.47

**Comment by guybedford** [comment]
You do need to make sure that `System.config({ baseURL: 'x' })` is provided along with or before any `System.config({ map: {...}, paths: {...} })`.

**Comment by guybedford** [comment]
Basically to replicate on a fresh app just run:

```javascript
System.config({ map: { x: 'y' } });
System.config({ baseURL: 'z' });
```

So make sure you're not doing that.
