### ISSUE TITLE
Multiple Default Extensions

### ISSUE THREAD

**Issue by mavericken** [systemjs/systemjs#1474]
I have been struggling with the TypeScript 2.0 release because of the removal of extensions in imports.
https://github.com/frankwallis/plugin-typescript/issues/162

I do not feel the current defaultExtension feature is a good enough solution to the problem.  With only a single default extension for a directory, we have file extension dictating our directory structure.  We should be able to keep TS, TSX, JS, JSX files together when it makes sense to do so.

My proposal is to enable support for multiple default extensions.  For instance, we would be able to specify that the default extensions are ["ts","tsx"].  So, when systemjs is looking "./localimportfile", it would first check for "./localimportfile.ts", and if it does not find it, it would check for "./localimportfile.tsx".

Of course this proposal comes with the obvious implications that we would potentially be doing many unnecessary HTTP requests for files that do not exist.  I feel this would be an acceptable cost for the feature, considering that when performance is a concern, we make bundles instead anyways.  Also the feature shouldn't negatively impact people who stick with a single default extension, nor would it impact files that have the first extension on the list.

**Comment by guybedford** [comment]
These are all valid points, but starts to reach the limits of the goals of the SystemJS project. Rather other tools should handle this kind of transpilation and output a module tree that SystemJS can then load natively, just like we would with ES modules in the browser in future. The development and transpile workflows in SystemJS have been necessary to support legacy formats and modules, but in future these features will be removed as well.

**Comment by mavericken** [comment]
@guybedford, I suppose with the existing plugin capabilities, it should be possible to make a plugin that adds support for multiple defaults, by taking an unused extension like ".multipleDefaultExtensions", make that the default extension, and use the locate hook to figure out which extension is the valid extension we want to use.  Are there any better ways of doing this that jump out at you?

**Comment by guybedford** [comment]
As mentioned, plugins in SystemJS have limitations that shouldn't necessarily be solved with SystemJS.

**Comment by mavericken** [comment]
I actually resolved the issue I was having with the System.loads entry not matching when using a locate hook to find a different file.  The solution was to just accept that that address and module name don't have to match, so it was the hot-reloader which needed to be changed.

https://github.com/alexisvincent/systemjs-hmr/pull/4

So yes, turns out nothing in SystemJS needs to change for this feature.  It just required some improvements to the plugins.
