### ISSUE TITLE
System JS not working in IE11

### ISSUE THREAD

**Issue by ssashok10** [systemjs/systemjs#1475]
I am using Angular2 application and it works well with Chrome and Firefox. However, when i run the same application in IE 11, i am getting the below error,

Error:
0x800a1391 - JavaScript runtime error: 'System' is undefined   

Below are the polly fills that i am using to run the AngularJS application. I am posting this issue here as its related to SystemJS.

```
<script src="node_modules/core-js/client/shim.min.js"></script>

<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>
<script src="node_modules/systemjs/dist/system.src.js"></script>

<!-- 2. Configure SystemJS -->
<script src="systemjs.config.js"></script>
<script>
    System.import('app').catch(function(err){ console.error(err); });
</script>
```

**Comment by guybedford** [comment]
Perhaps check you are including the promises polyfill before SystemJS?

**Comment by DavidGangel** [comment]
@guybedford which promises polyfill exactly you mean?

**Comment by ssashok10** [comment]
Here is the IE polyfill that i am including before SystemJS,

`"<script src="node_modules/core-js/client/shim.min.js"></script>"`

**Comment by asapach** [comment]
There's one bundled with SystemJS: https://github.com/systemjs/systemjs#promise-polyfill
