### ISSUE TITLE
Warn the circular dependency

### ISSUE THREAD

**Issue by giuseppe-santoro** [systemjs/systemjs#1477]
Scenario (https://plnkr.co/edit/waMErcMwqd7a3hzLgKaU?p=preview):

day.js

```
const night = require('night.js');

exports.name = 'Day';

console.log('When I end, the ' + night.name + ' starts.');
```

night.js

```
const day = require('day.js');

exports.name = 'Night';

console.log('When I end, the ' + day.name + ' starts.');
```

Output

```
When I end, the undefined starts.
When I end, the Night starts.
```

The problem is caused by the circular dependency between the two files.
day.js requires night.js and night.js requires day.js.
When night.js is executed, day.js is not completely loaded.

I know that it has been discussed already [here](https://github.com/systemjs/systemjs/issues/136), I'm not proposing to change the behaviour, I just suggest to warn it.
The circular dependency is not always bad but it is potentially dangerous and a warning can help the developer to handle potential problems.

What do you think?

**Comment by guybedford** [comment]
The following case works fine and is a common pattern:

day.js
```javascript
const night = require('night.js');

exports.name = 'Day';

console.log('When I end, the ' + night.name + ' starts.');
```

night.js
```javascript
exports.name = 'Night';

const day = require('day.js');

console.log('When I end, the ' + day.name + ' starts.');
```

The catching of circular dependencies is a problem for development tooling in the IDE itself.
