### ISSUE TITLE
Have SystemJS fire an event when it's available

### ISSUE THREAD

**Issue by rolfen** [systemjs/systemjs#1483]
(Feature proposal)

As I include SystemJS in my project, I realise that there is no way to know when it's ready, if I'm loading in asynchronously (using the async attribute in the script tag).
In line with the widely used event model, it would be nice to have an even fired so that I can do this in a head script section:

```
window.addEventListener("SystemJsReady", function(eReady){
	SystemJS.import('main.js');
});
```

It might help with loading scripts without blocking rendering (although I'm not 100% sure about this point).

**Comment by EricSimons** [comment]
Why not just hook into [the promise that `System.import` provides](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemimportmodulename--normalizedparentname---promisemodule) once the module is fully loaded?

**Comment by guybedford** [comment]
If loading SystemJS itself asynchronously, use a similarly loaded asynchronous script that runs after SystemJS to do the importing.

**Comment by rolfen** [comment]
Thank you @EricSimons
But IE does not support Promises, as far as I know. 
But I see that I was wrong to assume that there is no way of knowing when SystemJS is ready.

**Comment by rolfen** [comment]
@guybedford Thank you for your suggestion. This seems to unreliable in Chrome -  I have performed some tests.
Following a research, I could not get a definitive answer to confirm that the scripts will be loaded in this order. Async scripts should be loaded in "parallel", which seems to be understood as "no order guaranteed". But the spec is complicated so I cannot be sure. As as I'm concerned this is unreliable.
