### ISSUE TITLE
Syntax error in IE11

### ISSUE THREAD

**Issue by AScripnic** [systemjs/systemjs#1486]
Hello,

I'm trying to run for the first time my big application on IE11 and it fails with error:

```
(SystemJS) Syntax error
    SyntaxError: Syntax error
       at F (https://myurl/js/lib/system-polyfills.js:413:19)
       at H (https://myurl/js/lib/system-polyfills.js:391:17)
       at q.prototype.when (https://myurl/js/lib/system-polyfills.js:528:17)
    Evaluating https://myurl/path/to/fileName.js
    Error loading https://myurl/path/to/file/fileName.js as "./fileName" from https://myurl/path/to/file/that/includes/fileName.js
```
I'm including `system.js` like this:

```html
        <script src="/js/lib/system-polyfills.js"></script>
        <script src="/js/lib/system.js"></script>
```
I can't understand why I'm getting this error because it work perfect in FF/Chrome/Safari.

Could you please give me a hint how to debug this?

**Comment by AScripnic** [comment]
Found the problem, I had to getters with the same name.

**Comment by buddyp450** [comment]
Could you please elaborate on how you went through debugging this? How did you locate the duplicate getters?
