### ISSUE TITLE
Api docs for babelOptions should also link to presets docs

### ISSUE THREAD

**Issue by togakangaroo** [systemjs/systemjs#1487]
The [babelOptions doc](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#babeloptions) says the following with a link

> A list of options is available in the [Babel project documentation.](https://babeljs.io/docs/usage/options/)

I would argue that 80% of the time someone lands here they are looking for docs on modifying presets (which is the accompanying sample) and this info is difficult to find in the linked doc as its actually another link deep.

I recommend adding an additional link. Something like

> See [this document for a list of babel presets](https://babeljs.io/docs/plugins/#presets)

**Comment by guybedford** [comment]
That makes sense. A documentation PR is welcome if you want to make this adjustment.

Note that the babelOptions through SystemJS itself are deprecated - the SystemJS Babel plugin is the recommended approach here.

**Comment by togakangaroo** [comment]
So I would give a PR, but now that I'm digging into it, even what is there doesn't make sense.

For example the default `babelOptions` as generated by jspm init is configured with

```
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
  },
```

but `optional` is not listed as a valid key in the linked docs. And when I add to that 

      "presets": ["es2016"]

I get an error `Unknown option: direct.presets(…)`

So...I'm not even sure how this is supposed to work.

**Comment by togakangaroo** [comment]
Just to be clear - in my specific case, I only need to support chrome latest - to make debugging easier, I simply want to remove transpilation of everything and keep *only* modules themselves.

I've been really struggling to figure out how to do this.

**Comment by guybedford** [comment]
@togakangaroo see https://github.com/systemjs/plugin-babel#es-features for conditionally using features.
