### ISSUE TITLE
Use System JS to load ES6 modules without transpiling them to ES5 ?

### ISSUE THREAD

**Issue by misterfresh** [systemjs/systemjs#1489]
Transpiling is SLOW. With webpack, 40 to 60 seconds initial build, then 5-10 seconds for each incremental build. It adds up and becomes more and more annoying as the project becomes larger.

I'm trying to think of the most lightweight workflow and tooling to develop front-end JS.

So far I found this : http://jamesknelson.com/learn-raw-react-no-jsx-flux-es6-webpack/
and this : https://shinglyu.github.io/web/2016/04/06/minimal_react.html

I'm willing to give up ES6 to skip the build step, even though it should not be necessary as current browsers support all the features except ES6 module loading. 

My only problem is module loading. This looked promising : https://github.com/ModuleLoader/browser-es-module-loader/tree/master/src  . But it seems to be loading full babel which I am trying to avoid.

**I would like to use System JS for module loading only, without transpiling. Is it possible?**

I set 
````
System.config({ 
    meta: {
         './module/path.js': {
              format: 'esm'
           }
    },
    transpiler: false 
});
System.import('src/app.js');
````

but I am getting the error: 

> "TypeError: Unable to dynamically transpile ES module as SystemJS.transpiler set to false"

 . Well yes, I set transpile to false because I do not wish to transpile !

Thanks.

**Comment by misterfresh** [comment]
````
<script charset="utf-8">
          // loads relative to the current page URL
          SystemJS.config( {
              map : {
                'plugin-babel'         : 'assets/js/loader/plugin-babel.js',
                'systemjs-babel-build' : 'assets/js/loader/systemjs-babel-browser.js',
                'react' : 'node_modules/react/dist/react.js',
                'react-dom' : 'node_modules/react-dom/dist/react-dom.js'
              },

              transpiler: 'plugin-babel',

              meta: {
                '*.js' : {
                  babelOptions : {
                    es2015 : false,
                    stage2 : false,
                    stage3 : false
                  }
                }
              }
          })
          System.import('src/app.js'); 
         
        </script>
````
this seems to work but uses Babel... I'll have to see how fast it is on a large project

**Comment by guybedford** [comment]
@misterfresh it is fine not to transpile, but then the modules should already be converted by another tool like Gulp into System.register modules via Babel.

**Comment by ricardobrandao** [comment]
@guybedford considering that recent browsers are already ES2015 compliant, wouldn't be best to allow SystemJS to work without transpiling the source? For instance, webpack [does that](https://webpack.js.org/guides/get-started/#using-es2015-modules-with-webpack):

> Note that webpack will not touch your code other than import/export. In case you are using other ES2015 features, make sure to use a transpiler such as Babel or Bublé.

**Comment by guybedford** [comment]
@ricardobrandao you can certainly just transpile the module syntax by disabling the other transforms in the transpiler plugin. For example, in plugin-babel this is explained here - https://github.com/systemjs/plugin-babel#es-features.

**Comment by ricardobrandao** [comment]
Hi @guybedford, thanks for the quick response.

I've tried that but it is throwing me an exception - ```[BABEL] ... Unknown option: direct.es2015```. Furthermore, I can't find that option in the [babel's api documentation](https://developit.github.io/babel-legacy-docs//docs/usage/options/).

**Comment by RonNewcomb** [comment]
I think transpiler option should be set to null, not to false?

**Comment by ricardobrandao** [comment]
@RonNewcomb that didn't work either. Which version of babel are you using?

**Comment by RonNewcomb** [comment]
I'm not using babel. Most of my systemjs.configs don't even mention the transpiler option at all.

I do use Typescript, but my systemjs is completely ignorant of that.  I don't use systemjs.builder anymore, either

**Comment by ricardobrandao** [comment]
Ok, thanks. On a project I'm still using babel 5 but I'll try to move to babel 6 in the next couple of weeks and then I'll give it another shot.

**Comment by nimo23** [comment]
Why not allowing to use the configs from official babel within the property "babel" of system.js:
```

System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ],
    "presets": [
        [
          "env",
          {
            "loose": false,
            "modules": false
          }
        ],
        "react"
      ]
  },
```

Actually, "babelOptions" does not handle official babel options from **.babelrc** (https://babeljs.io/docs/usage/babelrc/). Please provide this.
