### ISSUE TITLE
registerDynamic broken if CJS module defines a top-level variable called "module"

### ISSUE THREAD

**Issue by adelespinasse** [systemjs/systemjs#1490]
If a CJS module doesn't refer to the loader-provided `module` variable, but defines its own top-level variable called `module`, this normally doesn't necessarily break anything. But when it's included in a build bundle by wrapping it in `registerDynamic`, it breaks, because the `return module.exports` that gets added at the end now refers to the module's `module` variable instead of the actual module. There probably needs to be some renaming in this situation.

Details below in the original description (written when I didn't know what was really going on).

------  Original description below  ------

I'm using jspm@0.17.0-beta.32 to build a standalone bundle with `jspm build` and the `--node` flag. Package npm:iconv-lite loads its own encodings dynamically using:

```
iconv.encodings = require("../encodings"); // Lazy load all encoding definitions.
```

which works fine when running the non-bundled app with `jspm run`, but returns `undefined` in the bundled app.  The `encodings` module of iconv-lite ([source here](https://github.com/ashtuchkin/iconv-lite/blob/5a9206dfa8aabb845cf8ae258e7fdf2bc0253e2c/encodings/index.js)) gets transpiled to this within build.js:

```
$__System.registerDynamic("217", ["207", "208", "209", "20a", "20b", "20c", "20d", "216", "4"], true, function ($__require, exports, module) {
    "use strict";

    // Update this array if you add/rename/remove files in this directory.
    // We support Browserify by skipping automatic module discovery and requiring modules directly.

    var process = $__require("4");
    var define,
        global = this || self,
        GLOBAL = global;
    var modules = [$__require("207"), $__require("208"), $__require("209"), $__require("20a"), $__require("20b"), $__require("20c"), $__require("20d"), $__require("216")];

    // Put all encoding/alias/codec definitions to single object and export it. 
    for (var i = 0; i < modules.length; i++) {
        var module = modules[i];
        for (var enc in module) if (Object.prototype.hasOwnProperty.call(module, enc)) exports[enc] = module[enc];
    }
    return module.exports;
});
```

The problem, as far as I can tell, is that when the above code is run, `module.exports` is undefined at the beginning, and is never set before it's returned at the end. The relevant exported values are only added to `exports`, which is not the same as `module.exports`. If I directly modify the above code (after creating the bundle) to return `exports` instead of `module.exports`, it seems to work correctly.

No doubt I'm doing something wrong, but this seems like a bug to me, either in SystemJS or some other part of the tool chain (I still don't understand how the pieces fit together).

`iconv-lite` is in this case required by the `body-parser` module from ExpressJS.

**Comment by adelespinasse** [comment]
Oh duh. `module.exports` is actually the same as `exports` at the beginning of the transpiled code, but before the end, there's the `var module = modules[i];` declaration inside the loop, which is still in scope at the end because it's a `var` instead of a `let`. So at that point `module.exports` is undefined.

Transpilation bug, so is it actually a bug in Babel?

**Comment by asapach** [comment]
I'd suggest moving this to [systemjs/babel-plugin-transform-cjs-system-wrapper](https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper)

/CC @jrauschenbusch

**Comment by guybedford** [comment]
Thanks @asapach yes exactly this is a problem with the registerDynamic transformer, which should be handling these conflicts. Posted https://github.com/systemjs/babel-plugin-transform-cjs-system-wrapper/issues/9.

**Comment by guybedford** [comment]
This should be fixed in the latest releases of SystemJS Builder.
