### ISSUE TITLE
Angular2.12 - '(SystemJS) XHR error (404 Not Found) loading http://localhost:9876/@angular/core/testing

### ISSUE THREAD

**Issue by seanrkerr** [systemjs/systemjs#1492]
Hi There,

I'm receiving this error when I try to run karma test runner with systemjs. The app runs fine when running from the server. It's only when I try to run the karma test runner I receive the error. 

jspm version: 0.16.48
node version: v6.9.1
systemjs version: v0.19.41

system config:

 paths: {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },

**Comment by asapach** [comment]
Karma uses `/base/` as the `baseUrl`, so you probably need to set that in the config:
```js
System.config({
	baseURL: 'base'
})
```

**Comment by seanrkerr** [comment]
mmm. Ok It's set to baseUrl: '.',

**Comment by seanrkerr** [comment]
@asapach thanks I'll do some more digging. Closing this as it's not a specific systemjs issue.
