### ISSUE TITLE
Create bundle from ES2015 modules fails with traceur-runtime error

### ISSUE THREAD

**Issue by SamVerschueren** [systemjs/systemjs#1494]
Hi

First of all, I'm not a SystemJS expert at all, so if I say something that doesn't make sense, forgive me :).

I'm trying to build my Angular2 application with treeshaking. If I understand correctly, rollup is integrated in SystemJS? Does this mean that if build a bundle from ES2015 modules, it should treeshake it automatically? And this way we don't have to run rollup ourselves?

If that is correct, this means that I have to transpile my TypeScript project to the `es2015` target because that's how Rollup works. After that, I try to build my bundle but I get this error

<img width="1013" alt="screen shot 2016-11-16 at 22 59 54" src="https://cloud.githubusercontent.com/assets/1913805/20368055/a2f39592-ac52-11e6-90f8-f79bc0ae068d.png">

> Note: I receive the same error when I try to build a bundle from an AoT commonjs compiled Angular2 project

I'm using the `builder.bundle` because I use lazy loading, not sure if this could cause the issue?

**Comment by SamVerschueren** [comment]
After digging a little bit deeper, it doesn't look like I'm using the right approach here. These are my steps.

1. Compile TypeScript files to `ES2015` modules
2. Build a bundle with SystemJS

I was assuming that SystemJS transpiled the `ES2015` bundles at build time to `ES5`. But that doesn't seem to be the case which is probably the cause of the issue. Although, if you bundle ESM with Rollup directly (to `commonjs`), everything seems to work just fine.

This makes me wonder, how can we use tree shaking AND SystemJS bundling together? Because in order to treeshake, you need `ES2015` modules. But if I use ESM, something goes wrong and I get the `traceur-runtime` bug.

Not sure what I'm doing wrong here.

**Comment by SamVerschueren** [comment]
The problem seems to be that in some cases, my bundle references `$traceurRuntime` which is causing this bug. When I simply compile my app with the TypeScript compiler (`tsc`) to the `commonjs` target, I can bundle it without `$traceurRuntime`. When I use the AoT compiler (`ngc`) which also transpiles to the `commonjs` format, I end up with `$traceurRuntime` in my code.

**Comment by asapach** [comment]
@SamVerschueren, I would suggest moving this issue to [systemjs/builder](https://github.com/systemjs/builder).
Rollup only works with `builder.buildStatic()` and doesn't support CJS. I would also commend using [systemjs/plugin-babel](https://github.com/systemjs/plugin-babel).

**Comment by guybedford** [comment]
@SamVerschueren try adding `System.config({ transpiler: false })` to your configuration in the browser before loading the bundle.
