### ISSUE TITLE
How to disable catching the error and display custom erro messages

### ISSUE THREAD

**Issue by Rohith47** [systemjs/systemjs#1495]
We have a situation where we want to use our own custom error handler, when some thing goes wrong, like function undefined. We tried window.onerror and looks like, its not executing and SystemJS is handling the error.

Is there a way to register our custom error handler, so that we can handle the error, when we want to ?

**Comment by asapach** [comment]
See #1437. `window.onerror` doesn't work for Promises. You need to either add `.catch()` at the end of your promise chain, or use `"unhandledRejection"` event.

**Comment by Rohith47** [comment]
@asapach thanks for your response. But I'm not trying to load any modules dynamically using system.import here. I'm just using import statement and then converting that to JS using systemJs build.

I tried attaching "unhandledRejection" event to window, but its not executing it. 
To be more specific with my issue, In one of my typescript file, I'm calling a function, which is not defined and the error is getting catch in systemJS. I want to have handler for this error.

**Comment by guybedford** [comment]
@Rohith47 top-level execution errors in SystemJS are not caught by window.onerror because they aren't script errors, but eval errors. We could look at potentially calling `window.onerror` if it exists.

**Comment by Rohith47** [comment]
@guybedford Thanks.
