### ISSUE TITLE
Check whether the module is loaded or not

### ISSUE THREAD

**Issue by Rohith47** [systemjs/systemjs#1499]
How to check whether the module is loaded or not with systemjs?

I tried using _System.has_ method. But this method requires the complete url of the module, from where it is downloaded. 
For example, if I load the module **backbone** from "_http://zyz.com/backbone.js_", SystemJs is registering with "_http://zyz.com/backbone.js_" instead to "backbone.js"  in _loader object.
Is there any way I can check like System.has('Backbone') ?

**Comment by mikecaines** [comment]
```if (System.normalizeSync('backbone.js') in System.defined) alert('it is loaded')```
