### ISSUE TITLE
not call System.register - Unable to load Google Maps js file 

### ISSUE THREAD

**Issue by sreyan32** [systemjs/systemjs#1501]
I am using the systemjs-csp-production plugin to load the google maps js file. My config is as follows-:

```
map: {
'google-maps':               'https://maps.googleapis.com/maps/api/js?key=API_KEY'
},
meta: {
'./app/js/smgc.body.js': {
             deps: ['google-maps']
         },
'google-maps' : {
            exports: 'google',
            format: 'global'
          }
}
```

smgc.body.js is just a file that depends on google maps.

Now the error I am getting is -:

`not call System.register or AMD define. If loading a global module configure the global name via the meta exports property for script injection support.`

What am I doing wrong ? I am using SystemJS for an angular application.

And is the exports really required when using a global module ?

**Comment by guybedford** [comment]
Better late than never - with the CSP build, the exports is required yes. The above looks correct to me, perhaps try it with the normal SystemJS build?
