### ISSUE TITLE
Inter format dependency import not working

### ISSUE THREAD

**Issue by SamVerschueren** [systemjs/systemjs#1502]
I'm working on an Angular2 application and was using the `import * as x from 'x';` format to import NPM dependencies. That worked, but it failed when I wanted to use Rollup to treeshake my bundle. So I had to switch to `import x from 'x';`. That works when I produce my production bundle. But when I want to start my devserver, it fails because it can't find `x.default`.

So I dived into that and came across this https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies. This means it should be perfectly possible to do that right?

This is a stripped down version of my systemjs config

```json
{
  "defaultJSExtensions": true,
  "packageConfigPaths": [
    "/node_modules/@angular/*/package.json"
  ],
  "paths": {
    "app/*": "/app/*",
    "@angular/common": "node_modules/@angular/common/bundles/common.umd.js",
    "@angular/compiler": "node_modules/@angular/compiler/bundles/compiler.umd.js",
    "@angular/core": "node_modules/@angular/core/bundles/core.umd.js",
    "@angular/forms": "node_modules/@angular/forms/bundles/forms.umd.js",
    "@angular/http": "node_modules/@angular/http/bundles/http.umd.js",
    "@angular/platform-browser": "node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
    "@angular/platform-browser-dynamic": "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
    "@angular/router": "node_modules/@angular/router/bundles/router.umd.js",
    "@angular/common/testing": "node_modules/@angular/common/bundles/common-testing.umd.js",
    "@angular/compiler/testing": "node_modules/@angular/compiler/bundles/compiler-testing.umd.js",
    "@angular/core/testing": "node_modules/@angular/core/bundles/core-testing.umd.js",
    "@angular/http/testing": "node_modules/@angular/http/bundles/http-testing.umd.js",
    "@angular/platform-browser/testing": "node_modules/@angular/platform-browser/bundles/platform-browser-testing.umd.js",
    "@angular/platform-browser-dynamic/testing": "node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic-testing.umd.js",
    "@angular/router/testing": "node_modules/@angular/router/bundles/router-testing.umd.js",
    "*": "node_modules/*"
  },
  "packages": {
    "rxjs": {
      "defaultExtension": "js"
    },
    "pify": {
      "main": "index.js",
      "format": "cjs"
    }
}
```

As you can see, I define `pify` as a CommonJS package. Because they are interoperable, I should be able to write `import pify from 'pify';` instead of `import * as pify from 'pify';`? But I always get the error that `pify.default` is undefined.

Does anyone have an idea why it's not working?

**Comment by SamVerschueren** [comment]
Also if I look to my network tab, to the requested file for `pify`, it's not changed. It's not wrapped into something SystemJS specific (not sure if it should though).

**Comment by guybedford** [comment]
@SamVerschueren `import x from 'x'` is definitely the right approach, if that is working unbundled but breaking in the build with rollup then that may be a build bug. Does it work when you disable Rollup optimizations in SystemJS Builder?

**Comment by SamVerschueren** [comment]
Thanks for your response! The thing is that it's not working unbundled. It works with Rollup.

So I started with using `import * as x from 'x'` in my Angular 2 application. Then I wanted to add treeshaking with Rollup so I implemented that but with rollup, those statements do not work. So I had to change it to `import x from 'x'` and enable `allowSyntheticDefaultImports`.

When I now run my development script, the typescript is being compiled to CommonJS (something like this).

```js
var pify_1 = require('pify');

// ...

// Notice that it adds `default` here, but that should work right?
pify_1.default(fn)().then(function () {
    console.log('hello world');
});
```

My app is being bootstrapped with `System.import()` so it should "hijack" the `require` function?

**Comment by guybedford** [comment]
Ok, try compiling to the 'System' output format rather.

**Comment by SamVerschueren** [comment]
Tried that before but it always throws the following error.

![screen shot 2016-11-25 at 14 50 42](https://cloud.githubusercontent.com/assets/1913805/20627169/a28b8114-b31e-11e6-8912-66da6163ab05.png)

But this seems to be Angular specific so I don't expect you to debug that :). I will try to create a minimal setup first to see if that works.

I should use `target: es5` and `module: system` in my `tsconfig.json` right?

**Comment by SamVerschueren** [comment]
I found out why it fails like that.

If I define a component with a `templateUrl` like this

```js
@Component({
    moduleId: module.id,
    templateUrl: 'foo.component.html'
})
class FooComponent { }
```

Then it fails. When I open up my network tab and look at the response of that request, it just returns the contents of my `index.html` file, not the contents of `foo.component.html`. The same thing happens for the CSS file.

Anything I can do to fix this easily? I can also use a gulp task to inline the templates and css as a build step though.

**Comment by asapach** [comment]
Try `__moduleName` instead of `module.id`.

**Comment by SamVerschueren** [comment]
`__moduleName` seems to fix it. Makes me wonder why it's not `module.id` though? Any reason this is different?

**Comment by asapach** [comment]
`module.id` is for CommonJS, and `__moduleName` is for `system`.

**Comment by SamVerschueren** [comment]
Makes it more difficult to switch between those two. There will probably be a good reason for that, I just wonder why :)?

Thanks @guybedford and @asapach for helping me out on this :)!

**Comment by SamVerschueren** [comment]
Also, `__moduleName` is not recognised by TypeScript. Shouldn't it be added to the SystemJS type definitions?

```
declare var __moduleName: string;
```
