### ISSUE TITLE
Allow configuration of script to load from package.json when using packageConfigPaths

### ISSUE THREAD

**Issue by Roaders** [systemjs/systemjs#1504]
When using `systemjs` with `node_modules` I sue this setup to configure it:

```
Sytem.JS.config({
    paths:{
        '*': 'node_modules/*'
    },
    packageConfigPaths: ['./node_modules/*/package.json']
});
```

This is great as systemjs loads my package.json and picks out the `main` script and then loads that.

However, I have a package that has both node.js and browser packages. In package.json `main` points to the node scripts. `browser` points to scripts for the browser.

I would like to configure what property in the package.json is loaded by sytemjs.

**Comment by guybedford** [comment]
I'd suggest looking at jspm for these sorts of use cases as it will configure SystemJS correctly for loading from Node.
