### ISSUE TITLE
baseUrl not allowed when using <base href>

### ISSUE THREAD

**Issue by RyanQuackenbush** [systemjs/systemjs#1507]
SystemJS#0.19.41

If I have a `<base href="/app">` for an html5 mode based app it doesn't seem like I'm allowed to override the baseUrl via the System.config call. 

`System.config({
  baseUrl: '/'
});`

all paths have `/app/` prepended.  I don't want to remove the base href since all app anchor / location href's would point to the wrong app urls (Unless I prefix /app to all of them). I also do not want to make all my paths in the map config absolute due to the bundling task which would search from the root of the drive instead of the baseUrl set during bundling.

Is there a way to override this base href behavior?

On a side note I couldn't use paths either:

`System.config({
  paths: {
    '/app/*': "../*"
  }
});`

(Hopefully doing the paths right there, the docs are scarce are that).

Thanks

**Comment by guybedford** [comment]
Use `baseURL` not `baseUrl`.

**Comment by RyanQuackenbush** [comment]
Ah, simple one. Appreciate it.
