### ISSUE TITLE
How to configure that a global is already loaded?

### ISSUE THREAD

**Issue by billti** [systemjs/systemjs#1510]
I've tried a number of techniques here with no luck, and searched the issues and web, so apologies if I've missed something obvious.

How do you configure that a global is already available? (i.e. via an earlier script tag). In my case, React is already included earlier on the page (prior to SystemJS) direct from the CDN. When I try to use the global/exports properties on `System.config`, I see it trying to load the script again when the first dependency needs it. I want to be able to configure that this is already present (e.g. any dependency on `import React from "react"` should be satisfied by the already present `React` global).

Looking at the SystemJS API I can see this could perhaps be possible via methods such as `registerDynamic` or `set`. I can play around with these if this is not possible via the `config` call.

**Comment by asapach** [comment]
I don't think this can be done using config only. The simplest way to achieve this would be to map `"react"` to a shim module that essentially looks like this:
```js
module.exports = React;
```

**Comment by billti** [comment]
Thanks. I did a few searches on 'registerDynamic' and looked through the source, and the below seems to be working for me in testing. I'm not seeing any additional network calls to try and load React, and the global React is being used fine to satisfy the `import React from "react";` dependencies in my code.

```javascript
    System.registerDynamic("react", [], false, function(require, exports, module) {
        module.exports = React; // Set the existing React global as the default export
    });
```

I'll use this after the call to `config` has made the other settings

**Comment by DanielRosenwasser** [comment]
From looking at [this](http://stackoverflow.com/questions/27711088/global-libraries-with-system-js), maybe you could write something like

```ts
let externals = {
    "react": "React"
};
for (const m in externals) {
    System.set(m, eval(externals[m]);
}
```

**Comment by alexnofoget** [comment]
How to provide it with 6.1.4 version of SystemJS?

**Comment by joeldenning** [comment]
I think this will work for systemjs@6

```js
System.set(System.resolve('react'), window.React)
```

**Comment by zjhou** [comment]
> I think this will work for systemjs@6
> 
> ```js
> System.set(System.resolve('react'), window.React)
> ```

This will cause exception:
```
Unable to resolve bare specifier 'react'
```

My systemjs version is `^6.8.0`

**Comment by joeldenning** [comment]
@zjhou react must be in your import map in order for System.resolve to work.

```html
<script type="systemjs-importmap">
{
  "imports": {
    "react": "/react.js"
  }
}
</script>
<script src="system.js"></script>
<script>
System.set(System.resolve('react'), window.React)
</script>
```

**Comment by zjhou** [comment]
> not by specifier.



> @zjhou react must be in your import map in order for System.resolve to work. Modules are always identified by full URL, not by specifier.
> 
> ```
> <script type="systemjs-importmap">
> {
>   "imports": {
>     "react": "/react.js"
>   }
> }
> </script>
> <script src="system.js"></script>
> <script>
> System.set(System.resolve('react'), window.React)
> </script>
> ```

Thanks a ton.
