### ISSUE TITLE
How to `System.import` a module from a CDN without importing multiple copies of React peerDependency

### ISSUE THREAD

**Issue by gnestor** [systemjs/systemjs#1511]
I have a jspm project with default config and react and react-dom installed. I want to be able to dynamically import modules from a CDN (React components) and it's already working for some components, but for others I get the following error: 

```
Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```

I'd like to config SystemJS to not import react or react-dom as a dependency (or peerDependency) for any modules imported at runtime. I have tried the following with no luck:

```js
import React from 'react';
import ReactDOM from 'react-dom';

const module = 'react-json-tree'; 

System.defaultJSExtensions = true;
System.config({
  paths: {
    // import the React component module from npm
    [module]: `https://npm.jspm.io/${module}`,
    [`npm:${module}`]: `https://npm.jspm.io/${module}`,
    [`npm:${module}*`]: `https://npm.jspm.io/${module}*`
  },
  packages: {
    [module]: {
      map: {
        // import react and react-dom from jspm_packages
        'npm:react.js': 'jspm_packages/npm/react@15.4.1/react.js',
        'npm:react-dom.js': 'jspm_packages/npm/react-dom@15.4.1/index.js',
        // import everything else from npm/github
        'npm:*': 'https://npm.jspm.io/*',
        'github:*': 'https://github.jspm.io/*',
        '*': 'https://npm.jspm.io/*'
      }
    }
  }
});
System.import(`npm:${module}`)...
```

`paths` config is working because I'm getting 404 errors for the module's dependencies: `GET http://127.0.0.1:8080/npm:react.js 404 (Not Found)`

But `packages[module]` config doesn't seem to be working because it should be rewriting `npm:react.js` to `jspm_packages/npm/react@15.4.1/react.js`. 

I'm sure there is a relatively simple way to accomplish this and I've spent over a day in pursuit of the perfect configuration, so I'd appreciate some direction.

**Comment by gnestor** [comment]
Here's an example of a package.json of is throwing the _multiple copies of React_ error: https://github.com/reactjs/react-chartjs/blob/master/package.json

```js
"peerDependencies": {
    "react": "*",
    "react-dom": "*",
    "chart.js": "^1.1.1"
  },
```

And here's an example of one that isn't: https://github.com/alexkuz/react-json-tree/blob/master/package.json

```js
"peerDependencies": {
    "react": "^0.14.0 || ^15.0.0-0"
  },
```

**Comment by guybedford** [comment]
For a delayed response, there is a description of CDN workflows for jspm at http://jspm.io/0.17-beta-guide/loading-libraries-from-cdn.html, although this is getting out of date now.
