### ISSUE TITLE
loading esri

### ISSUE THREAD

**Issue by Robophil** [systemjs/systemjs#1515]
Hi, am working with `esri` library in my `angular2` project and have had no luck so far, successfully loading the library.
i'll want to be able to do something like
```javascript
import arcgisUtils = require('esri/arcgis/utils');
```

**Comment by asapach** [comment]
The syntax is invalid - it's either:
```js
import arcgisUtils from 'esri/arcgis/utils';
```
or
```js
var arcgisUtils = require('esri/arcgis/utils');
```

**Comment by Robophil** [comment]
ok. `Import` would also work, as long as there is an export from that module.
This is what i've noticed so far.
In my browser when i log the module,
```javascript
var arcgisUtils = require('esri/arcgis/utils');
console.dir(arcgisUtils)
```
i see this..
```javascript
_checkUrl: function ba(a){}
_createMap: function Ka(b,c,d,e,f,g){}
.........
```
![image](https://cloud.githubusercontent.com/assets/6032018/20805116/c725ce0e-b7f5-11e6-911c-2d409cd2a3dd.png)

but when i try to access `createMap` of my service, i keep seeing that this is not a function. Which obviously exists when from the log above. Its a bit of a headache ;)

**Comment by asapach** [comment]
If the code has been transpiled using babel then you need to use `arcgisUtils.default`, or the `import` syntax I've mentioned above.

**Comment by asapach** [comment]
... babel or typescript for that matter.

**Comment by Robophil** [comment]
Thanks. Let me give it a try

**Comment by Robophil** [comment]
Thanks @asapach, It works fine now. The typings seems to be what has been putting me off.

```javascript
declare module "esri/arcgis/utils" {
  /** Utility methods to work with content from ArcGIS.com. */
  var utils: {
    /** Specify the domain where the map associated with the webmap id is located. */
    arcgisUrl: string;
    /**
     * Create a map using information from an ArcGIS.com item.
     * @param itemIdOrItemInfo An itemId for an ArcGIS.com item or the response object obtained from calling the arcgisUtils.getItem method.
     * @param mapDiv Container ID for referencing map.
     * @param options Optional parameters that define the map functionality.
     */
    createMap(itemIdOrItemInfo: string | any, mapDiv: string, options?: any): any;
    /**
     * Get details about the input ArcGIS.com item.
     * @param itemId The itemId for a publicly shared ArcGIS.com item.
     */
    getItem(itemId: string): any;
    /**
     * Can be used with LayerList widget to get the layers list to be passed into the constructor.
     * @param createMapResponse The object created from the resolved promise returned by createMap().
     */
    getLayerList(createMapResponse: any): any[];
    /**
     * Can be used with esri.dijit.Legend to get the layerInfos list to be passed into the Legend constructor.
     * @param createMapResponse Object returned by .createMap() in the .then() callback.
     */
    getLegendLayers(createMapResponse: any): any[];
  };
  export = utils;
}
```

so when i do`import arcgisUtils from 'esri/arcgis/utils';`, i get this warning from vscode

**Module '"esri/arcgis/utils"' has no default export.**

so i thought it was wrong when the alternative which i tried above seems to work with no error from vscode

**Comment by Robophil** [comment]
Adding this,
```javascript
"allowSyntheticDefaultImports": true
```
to your `tsconfig.json` fixed this issue.
