### ISSUE TITLE
Minified and bundled error - Can't find variable: System

### ISSUE THREAD

**Issue by AmitM30** [systemjs/systemjs#1516]
Hi,

I am using SystemJS (and Aurelia) as module loader, building a production system. This is how I have setup my scripts loader:
```
<script src="//assets.wadi-uat.com/small/dist/app-init.js"></script>
<script src="/config.js"></script>
<script src="//assets.wadi-uat.com/small/dist/aurelia.js"></script>
<script src="//assets.wadi-uat.com/small/dist/app-build.js"></script>
```
app-init.js - is minified -> webcomponents-lite.js, system.src.js

Recently while testing across browsers, faced a few issues even on latest browsers saying:
```
UncaughtException: Uncaught ReferenceError: System is not defined
Browser	iPhone Safari 10.0.3
User agent	Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A551 Safari/602.1
Stack trace
    ReferenceError: Can't find variable: System
        at /config.js:1:7
```

Also, on Android Android Browser 5.1, Android Chrome 54 (where I assumed we should have no issue). The error is not consistent even on those browsers, so difficult to trace.

P.S.: I am not sure this is github thing or stackoverflow, so apologies if spamming

**Comment by guybedford** [comment]
Do you still need help here?
