### ISSUE TITLE
SystemJS wraps sourceMappingURL and prevents sourceMaps from working properly

### ISSUE THREAD

**Issue by lu4** [systemjs/systemjs#1518]
I'm using SystemJS as a nodejs transpiler backend, however I'm not able to debug my applications because SystemJS wraps `# sourceMappingURL=...` with it's service code.

Here how it looks in my browser:
http://imgur.com/jZif4EG

Question: Is there a quick fix for this problem? 

Thank you in advance,
Denis

**Comment by guybedford** [comment]
Can you clarify what you mean that it wraps `sourceMappingURL`? sourceMappingURL should still work even if it is wrapped in a function closure, so this may just be the fact that NodeJS as limited source map support.

Perhaps have a look at https://github.com/ModuleLoader/node-es-module-loader for a NodeJS loader that carefully includes source maps support.

**Comment by asapach** [comment]
@guybedford, should it? The [spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx) says:

> The generated code may include a line at the end of the source, with the following form:
> `//# sourceMappingURL=<url>`

My interpretation is that `sourceMappingURL` needs to be on the last line.

**Comment by lu4** [comment]
Ok, I had problem with Google Chrome refusing to show typescript untranspiled files, I thought that the reason for that is due to sourceMappingUrl is not showing on the last line. However I've found out that if you add folder to workspace like this [http://i.imgur.com/p722X9x.png](http://i.imgur.com/p722X9x.png) it starts to behave properly. So I'm not sure whether this is still a bug or rather Google Chrome is smart enough to take sourceMappingUrl from a line other than last one.
