### ISSUE TITLE
include map to Config.js

### ISSUE THREAD

**Issue by bes1002t** [systemjs/systemjs#1519]
Is it possible to outsource the map part of Config.js to another file? Something like:
`System.config({
    defaultJSExtensions: true,
    transpiler: "-a",
    map: "./maps.js"
});`

The problem is that the config has to be commitet, but the maps content is changing permanently and I don't want to commit that stuff everytime. So it would be cool if the config.js is never changing but the map file could be added to gitignore.

**Comment by asapach** [comment]
You can have multiple `System.config()` calls in different files. So you could move the map config elsewhere, call `System.config()` and gitignore the file.
