### ISSUE TITLE
Unable to import dist version of `xlsx` because of require script

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1521]
I'm trying to import this: https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.js

There is this snippet in the beginning of the file:

```
if(typeof module !== "undefined" && typeof require !== 'undefined') {
	if(typeof cptable === 'undefined') cptable = require('./dist/cpexcel');
	current_cptable = cptable[current_codepage];
}
```

Which I see gets detected and SystemJS tries to fetch it (as https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/dist/cpexcel.js ) and fails. The package works without it. Is there a way to have SystemJS ignore this?

**Comment by asapach** [comment]
See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md
Try setting `format` as `global` explicitly.

**Comment by Mosho1** [comment]
Tried that first, doesn't do the trick, I assume the specific way that module is `require`d is causing this. I'm trying to use `packages` -> `map` config next.

**Comment by Mosho1** [comment]
This worked:

```
"packages": {
        "https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx": {
            "map": {
                "./dist/cpexcel.js": "@empty"
            }
        }
    }
```

However, using `"xlsx"` as the package name doesn't work because it gets mapped to `"https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.8.0/xlsx.js"` (with the extension) in the final packages config, while the normalized module loses the extension for some reason, in `getPackage` (system.src.js#L2201).

**Comment by Mosho1** [comment]
I tried that as well, didn't work. I'll investigate further soon.

**Comment by guybedford** [comment]
Let me know if you still need help here.

**Comment by Mosho1** [comment]
Whoops, forgot about this. This worked in the end (I believe I tried it first and something else was wrong, but I can't recall):

````
meta: {
    xlsx: {
        format: "global",
        deps: ["jszip"]
    }
}
```
