### ISSUE TITLE
core.js prepareBaseURL invalid URLs on IE11

### ISSUE THREAD

**Issue by zacateras** [systemjs/systemjs#1524]
On IE11 and earlier custom URLPolyfill is used instead of Mozilla/Chrome [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) objects. However URLPolyfill implementation, originally pulled from [here](https://gist.github.com/Yaffle/1088850), was changed slightly. Usages of [string.charAt](https://developer.mozilla.org/pl/docs/Web/JavaScript/Referencje/Obiekty/String/charAt) method was replaced with string[number] selector. This seems to not work for browsers like IE11, since square brackets selector always returns undefined value.

This results in constructing URLs with double trailing slashes (as a result of [this](https://github.com/systemjs/systemjs/blob/master/lib/core.js#L27)) and missing slashes between host:port and path URL parts (as a result of [this](https://github.com/systemjs/systemjs/blob/master/lib/url-polyfill.js#L36)).

**Comment by guybedford** [comment]
@zacateras thanks for reporting this.

Numeric string indices definitely work in IE11, perhaps just not on Object strings.

Perhaps try removing the `String(url)` and replacing this with just `url` in https://github.com/systemjs/systemjs/blob/master/lib/url-polyfill.js#L6 - does that work as alternative fix for you?

**Comment by zacateras** [comment]
After further research I discovered that IE was automatically switched to IE7 (!) compatibility mode due to corporate domain policies. Other compatibility mode could be enforced by adding appropriate meta headers.

Closing #1524 and #1526.
