### ISSUE TITLE
Use System JS to load  to ES5  modules directly

### ISSUE THREAD

**Issue by jithinoj** [systemjs/systemjs#1525]
We are created an aurelia application. We have using typescript 2.1. We are configured the compiler target option to ES5. We need to load the ES5 modules directly.

tsconfig.json

`{
  "compilerOptions": {
    "module": "system",
    "experimentalDecorators": true,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "lib": [
      "es2015",
      "es5",
      "dom"
    ]
  }
 
}`

**Comment by aluanhaddad** [comment]
There is no such thing as ES5 modules per se and you are in fact trying to use CommonJS modules. Are you using plugin-typescript? What does your `(system|jspm)config.js` look like?
