### ISSUE TITLE
Config fetch override exists but has no access to original fetch

### ISSUE THREAD

**Issue by mavericken** [systemjs/systemjs#1527]
This does not work:
```
SystemJS.config({
  fetch: function(load, fetch) {
    return fetch.call(this, load)
  }
})
```
fetch is undefined.  I feel the feature is not very useful without exposing the original fetch function.  Interestingly this config option is also consumed by SystemJS builder.

I'm on SystemJS v0.19.40 in case that matters.

**Comment by guybedford** [comment]
The way to do a fetch hook override is via:

```javascript
var oldSystemFetch = System.fetch;
System.fetch = function (load) {
  // custom fetch function here
};
```

**Comment by mavericken** [comment]
So then, what I felt was a broken feature is actually a consequence of the code seen here:
https://github.com/systemjs/systemjs/blob/ab749f32a7c969686ae929f42518a925e8d9799b/dist/system.src.js#L2069
```
      loader[c] = loader[c] || {};
```

I still have a use case that isn't solved by the oldSystemFetch strategy, but I'll leave it out of this issue as it has already become too muddy with the initial misconception.
