### ISSUE TITLE
Not working with `browser-env`

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1528]
SystemJS: 0.19.41
browser-env: 2.0.16

I'm using `browser-env` to simulate browser environment to run `ava` tests.
`systemjs` throws `error at https://github.com/systemjs/systemjs/blob/ab749f32a7c969686ae929f42518a925e8d9799b/dist/system.src.js#L5114

because there is no script tag at all in `document`, thus (`$__curScript` is `undefined`).

Should this scenario be supported? If it does, I'm happy to help submitting a PR. 🌷 

I'm writing a plugin loader and planning to use `systemjs` to do the lifting.

I'm not 100% sure if this is a sound idea so here is my idea. It would be great if Guy Sensei can provide some insight. 🙇 

First, designate a `<pluginFolder>` for plugin modules (e.g. `./plugins` or `./node_modules` for any npm packages)

```ts
// Load `systemjs.config.json` using JSON plugin
const pluginConfigJson = await System.import('<pluginFolder>/<pluginName>/systemjs.config.json')

// Clone systemjs so dependencies can be load deparately from main code
const clonedSystemJS = new System.constructor()

// Config the cloned SystemJS using the plugin config.
clonedSystemJS.config(pluginConfigJson)

// Load the plugin main export
const mainExport = clonedSystemJS.import('<pluginFolder>/<pluginName>/index.js') 
// or also read `package.json` to get `main` field first
const mainExport = clonedSystemJS.import('<pluginFolder>/<pluginName>/<main>') 
```

**Comment by guybedford** [comment]
Perhaps try SystemJS 0.20 here, I don't think it wil have this same currentScript bug.

Please do suggest a PR though if you think there is something better we can do for this workflow here.

**Comment by unional** [comment]
Thanks! 

Do you have any command on this workflow? Do you spot anything that may concern you?

**Comment by guybedford** [comment]
It's difficult to comment on the workflow without having the same grasp as you of the problem you're trying to solve. But let me know if I can help.

**Comment by unional** [comment]
Run with 0.20.5 and the currentScript bug is gone.
However, when loading `browser-env` or `jsdomify` before `systemjs`, the following error is thrown:

```sh
Error: relUrl is not defined
  Resolving npm-module
  Loading npm-module
    throwResolveError (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:7:48)
    resolveIfNotPlain (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:52:9)
    SystemJSLoader$1.coreResolve (node_modules/systemjs/src/resolve.js:195:26)
    node_modules/systemjs/src/resolve.js:268:34
```

The issue can be reproduced at:
https://github.com/unional/some-issues/tree/systemjs-jsdomify
