### ISSUE TITLE
The "loader" option issue

### ISSUE THREAD

**Issue by gig177** [systemjs/systemjs#1530]
```bash
$ jspm -v
0.16.48
$ head -n 2 jspm_packages/system.js
/*
 * SystemJS v0.19.41
```
I can't figure out why this meta field doesn't work:
```javascript
  meta: {
    "*.txt": {
      "loader": "text"
    }
  },
```
Systemjs try to load `/static/hello.txt.js` (instead of `/static/hello.txt`) file.
Full sample source code available on this [repo](/gig177/systemjs_plugin_loader_issue)

**Comment by asapach** [comment]
https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use
> Note that if using the `defaultJSExtensions` compatibility feature, plugins for resources with custom extensions will only work by using the package configuration `defaultExtension: false` option to override this for specific packages.

**Comment by aluanhaddad** [comment]
@gig as noted by @asapach you need to use
```js
 meta: {
    "*.txt": {
      "loader": "text",
      "defaultExtension": false
    }
  },
```

**Comment by gig177** [comment]
Thanks for your help.
