### ISSUE TITLE
(0.20.0-alpha.1) Uncaught ReferenceError: warn is not defined

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#1531]
in 0.20.0 alpha, I get this error. Inspecting `system.src.js` I see that the function supposed to be called is named `warn$1`, so it looks like a fluke in the build.

**Comment by guybedford** [comment]
Thanks I believe this is fixed in master, for the coming beta.

**Comment by guybedford** [comment]
I mean on the 0.20 branch.
