### ISSUE TITLE
defaultExtension not recognizing js extension

### ISSUE THREAD

**Issue by lastmjs** [systemjs/systemjs#1532]
Here is my config:

```
System.config({
    packages: {
        '': {
            defaultExtension: 'ts'
        }
    }
});
```

Here is the import that might be misbehaving:
```
import {createStore} from './node_modules/redux/dist/redux.min.js';
```

I would expect `redux.min.js` to be requested from the browser, because the `.js` extension is already there. But my browser is requesting `redux.min.js.ts`. I thought that the extra `.` in the import name might be causing the issue, but doing:
```
import {createStore} from './node_modules/redux/dist/redux.js';
```
results in the browser requesting `redux.js.ts`. Is this the expected behavior? I've been searching through other issues, and nothing I'm coming across is fixing my issue. I'm also a little confused with the `defaultJSExtensions` property, though I have tried using that in my config as well. I'm not sure where to go from here.

**Comment by guybedford** [comment]
`defaultExtension` will enforce the default extension for all matching packages.

If you want to opt-out you can use meta configuration, but it is advisable to use defaultExtension configuration as narrowly as possible otherwise.

```javascript
System.config({
  packages: {
    './app': { defaultExtension: 'ts' },

    // this is only necessary if you really want to keep a `'': { defaultExtension: false }`
    './node_modules': { defaultExtension: false }
  }
});
```
