### ISSUE TITLE
Regex for migrating from defaultJSextensions true -> false

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/systemjs#1535]
@guybedford 
Not sure where this would best be shown. But I wrote a small regex to help with migration from defaultJSextensions true -> false.

Just going to leave it here. If its useful let me know where I can make a PR. If not, feel free to close.

replace
`from (['"])(\.?\.\/(?!.*\.['"]).*)(['"])` (es6) or `require\((['"])(\.?\.\/(?!.*\.['"]).*)(['"])\)` (cjs)
with
`from $1$2.js$3` (es6) or `require($1$2.js$3)` (cjs)

Might need minor modification depending on editor.

**Comment by guybedford** [comment]
Thanks for sharing @alexisvincent will close for now, but this will at least come up in search results.
