### ISSUE TITLE
typescript definition file (suggestion)

### ISSUE THREAD

**Issue by BBGONE** [systemjs/systemjs#1536]
Hello, why don't you write all system.js in typescript?
Then it would be easy to get the compiled code in any ES style - ES5, ES6 ...
Also static type checking on compilation is very helpful.
I submitted this because i need typescript type definition file for system.js.
Because you evolve the system.js - the definition files needs to be constantly updated.
Typescript generates them automatically,

**Comment by asapach** [comment]
Similar discussion was in #1505

**Comment by BBGONE** [comment]
yes, similar but different. Of course my suggestion is a bit more radical - to write it full in typescript and later compile to any ES standard, but it pays in the end.

**Comment by guybedford** [comment]
There are no plans to write SystemJS in TypeScript anytime soon.
