### ISSUE TITLE
toUrl method

### ISSUE THREAD

**Issue by BBGONE** [systemjs/systemjs#1537]
Hello, currently i use requirejs and it has toUrl method used like require.toUrl(modulename);
It returns full url to the module name passed in its parameter.
I looked in SystemJS API it seems it has no such method. Is there a way to get URL by the module name in SystemJS?
P.S. Looks like (by looking into CSS plugin) it has none of it, and plugin needs to reimplement calculation of the url from which to download the asset.

**Comment by asapach** [comment]
There's `SystemJS.normalize()`/`normalizeSync()` - it's poorly documented, but it should do what you need.

**Comment by BBGONE** [comment]
Thanks very much. That's good news :)
