### ISSUE TITLE
clearLoadErrors is not called on some syntax errors

### ISSUE THREAD

**Issue by JensLincke** [systemjs/systemjs#1538]
Working module code:
```
export function hello() {
  return "Hello "  + new Date() ;
}
```
Then doing a System.registry.delete() and again a System.import with:
```
XXXexport function hello() {
  return "Hello "  + new Date() ;
}
```
Produces a proper load error.

After fixing the error and doing a System.registry.delete() and again a System.import the module loads properly. 

When doing a different change:

```
export function hello() {
  return "Hello XXX  + new Date() ;
}
```

The module stays unloadable after fixing the error and doing a System.registry.delete() and System.import().

Debugging into the problem showed that in the first case, clearLoadErrors cleared registerRegistry property and in the second case the half loaded module stayed in there and blocked proper future loading. 

In the second case the error seemed to be inside babel:

```
lively-container.js:229 Error: https://lively-kernel.org/lively4/lively4-jens/demos/mymodule.js: Unterminated string constant (5:9)
  3 | 
  4 | export function hello() {
> 5 |   return "X World! Today is the  + new Date() ;
    |          ^
  6 | }
  7 | 
  Instantiating https://lively-kernel.org/lively4/lively4-jens/demos/mymodule.js
  Loading https://lively-kernel.org/lively4/lively4-jens/demos/mymodule.js
    at b.ja.raise (systemjs-babel-browser.js:17)
    at b.a.readString (systemjs-babel-browser.js:16)
    at b.a.getTokenFromCode (systemjs-babel-browser.js:15)
    at b.a.readToken (systemjs-babel-browser.js:15)
    at b.a.nextToken (systemjs-babel-browser.js:15)
    at b.a.next (systemjs-babel-browser.js:15)
    at b.aa.parseReturnStatement (systemjs-babel-browser.js:16)
    at b.aa.parseStatement (systemjs-babel-browser.js:16)
    at b.aa.parseBlockBody (systemjs-babel-browser.js:16)
    at b.aa.parseBlock (systemjs-babel-browser.js:16)
```

Our system js setup uses 0.20.x and the babel plugin to live develop on a website.

**Comment by guybedford** [comment]
Thanks for the feedback on 0.20 :) I've just added a test for this case in https://github.com/systemjs/systemjs/commit/2d865855a50243275a4c695280a219024aa9e7f3, and it appears to be working ok for me. If you're able to suggest any changes to that further to replicate please let me know.

**Comment by guybedford** [comment]
Do let me know if you're still seeing this at all?
