### ISSUE TITLE
System.import('app') : cannot resolve file 'app' ?

### ISSUE THREAD

**Issue by erwin16** [systemjs/systemjs#1539]
I am trying to follow the latest Angular2 tutorial ( no modified..) , I'm using Webstorm IDE (2016.3) to manage the Quickstart project /
'quickstart' is running fine , however my editor shows an error in the index.html file 👍 

`<head>
    <script src="systemjs.config.js"></script>
    <script >
      System.import('app').catch(function(err){ console.error(err); });
    </script>
</head>`

Cannot resolve file 'app'. Reports unresolved fiel references in Javascript files, including CommonJS and AMD modules references.

Is it related to the editor or do I need to modify the Angular2 tutorial systemjs.config.js ?

thanks for any feedback

**Comment by asapach** [comment]
Did you check out their live example?
https://cdn.rawgit.com/angular/angular.io/b3c65a9/public/docs/_examples/_boilerplate/systemjs.config.web.js

This piece in particular:
```
packages: {
  app: {
    main: './main.ts',
    defaultExtension: 'ts'
  }
}
```
