### ISSUE TITLE
Question: What are the consequences if one uses 'commonjs' in the browser instead of 'system' module format

### ISSUE THREAD

**Issue by jp7677** [systemjs/systemjs#1540]
Hi there,

I have a question regarding the module loader capabilities of systemjs. My bottom line question is: Are there any negative consequences when I'm using commonjs modules (generated from typescript using `"compilerOptions": { "target": "es5", "module": "commonjs" }`) instead of system modules loaded by systemjs in the browser?

Some more background: I had a rather standard setup for my (Aurelia) web application:
- Typescript for writing my own logic
- Compile the ts files using `"compilerOptions": { "target": "es5", "module": "system" }`
- Jspm for installing 3th party modules
- Gulp and Aurelia-bundler (which uses Systemjs-builder underneath) for bundling
- Loading Systemjs and the jspm config in the browser and importing everything using systemjs loader.

Once I decided to look into end-2-end tests I realized that I would need different typescript compiler options since protector tests run within node and not in the browser. Using commonjs in the typescript compiler options was obviously fine for nodejs/protractor. Much to my surprise my web application still kept working when using commonjs there as well (ok, had to slightly adjust some import statements)!  I guess that is some of the magic of systemjs being a universal loader. My question now is, should I just stick with commonjs as module format or should I introduce different typescript compile options for my web app and for protractor tests in nodejs? E.g. I read something about commonjs not being async, but can't find the answer if this is still a consequence when loading commonjs modules via systemjs.

Thanks for your thoughts!

**Comment by jp7677** [comment]
Doe someone has an idea if there are any sideeffects when using commonjs instead of system?

**Comment by asapach** [comment]
To me the biggest concern when switching between CJS and ESM/SystemJS modules is semantics: how and in which order the modules are resolved and instantiated, how import/export binding work, how circular references are handled, etc. Babel for example tries its best to mimic the module semantics, but there are still edge cases you can run into. Not sure about TypeScript. If you're careful and have full control of your dependencies, you might never run into those edge cases.

**Comment by jp7677** [comment]
Hi @asapach thanks for your response. I'm not sure if I understand your answer completely. So you are saying that I'm fine if module resolution between my own modules works? There are no difference regarding peformance, async etc when systemjs tries to load system or commonjs modules?

**Comment by asapach** [comment]
Depending on how you load and bundle you modules there may be a performance difference, for example you can use [`scriptLoad`](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta) to load `system` modules in the browser faster, but it doesn't work with [`cjs`](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#commonjs), because they need fetched using XHR, transformed and evaluated on the fly.
