### ISSUE TITLE
RC.4 treats module as if it has a default export when it doesn't

### ISSUE THREAD

**Issue by jdanyow** [systemjs/systemjs#1542]
This gist uses SystemJS 0.19.41 and works: https://gist.run/?id=8ca9d440877529f854382cde83c5c02d

If you edit the script tag in the `index.html` to use 0.20.0-rc.4 the gist breaks because DOM and FEATURE are undefined when imported via `import {DOM, FEATURE} from 'aurelia-pal';`. 

Here's the difference in behavior:

0.19.41 ✔️ 
![0.19.41 debugger](http://i.imgur.com/UmVQTgH.png)

0.20.0-rc.4 ❌ 
![0.20.0-rc.4 debugger](http://i.imgur.com/HL3xOGf.png)

**Comment by guybedford** [comment]
@jdanyow sure, it sounds like this is happening when importing `_aureliaPal` which itself was transpiled from ES modules into CommonJS or UMD? I've added a fix for this case in https://github.com/systemjs/systemjs/commit/5ca9e2674f233ce8b7cba232f887e2c6b8635b64, which should help here. Will post a release out shortly.

**Comment by guybedford** [comment]
Released in 0.20.0-rc.5.

**Comment by guybedford** [comment]
Included another correction in 0.20.0-rc.6.

**Comment by jdanyow** [comment]
@guybedford I'm still seeing the same issue with rc.5 and rc.6.  Here's a gist using rc.6 that shows the issue:

https://gist.run/?id=d54bc15e61e2b0c6d95878ff54b7f4aa

If you change the system.js script version to 0.19 in the index.html, it works.

**Comment by guybedford** [comment]
@jdanyow posted 0.20.0-rc.7.

**Comment by jdanyow** [comment]
that works! thanks!
