### ISSUE TITLE
System.fetch deprecated in 0.20

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#1543]
I've noticed that on SystemJS 0.20 branch `System.fetch` is gone.

My concern is that previously I was redefining `System.fetch` to overcome the fact systemjs currently does not support fetching module from http(s):// urls when it is runned by nodejs (see https://github.com/systemjs/systemjs/blob/0.20/dist/system.src.js#L1465)

I saw it's related to simplification of loader as discussed here : https://github.com/whatwg/loader/issues/147.

I'm worried that I will not be able to upgrade from 0.19 to 0.20 if I cannot fetch http urls inside nodejs.
Is there any (ideally robust) way to achieve what I was doing with 0.19 using 0.20 ?

**Comment by guybedford** [comment]
@dmail could you share some more background on the use case perhaps? The worry with http / https loading in NodeJS is the lack of caching. Does this not affect you?

**Comment by dmail** [comment]
@guybedford With pleasure. I want to publish an article (and certainly more) shortly. Until then let me try to explain the use case as briefly as possible.

I have a project, currently in a very messy state due to active research, called @jsenv.
It claims to give you a command able to run a JavaScript files inside NodeJS or the browser with many different options to match your needs. For example :

- `jsenv file.js`: run the file using NodeJS
- `jsenv file.js -monitor`: run the file keeping terminal opened watching file.js and dependency in order to rerun
- `jsenv file.js -monitor -platform=firefox`: same as above running file.js content using firefox

As you may guess one of the feature is hot module replacement. In order to have a uniform solution, I've made NodeJS fetch its modules from a server like a browser would.  

Concerning the lack of cache inside NodeJS I got an http client module which behaves like a browser and, consequently, support caching. It will be part of the jsenv codebase but is not visible/usable yet.

**Comment by guybedford** [comment]
@dmail the alternative in the new release is to hook the `instantiate` hook (`System[System.constructor.instantiate]`). See https://github.com/ModuleLoader/es-module-loader#instantiate-hook for the structure of this.

**Comment by dmail** [comment]
@guybedford Thank you for the hint, I'll try with this new instantiate hook.  

There is a code snippet below that illustrates my current understanding of the instantiate hook and how we can override module source fetching using it.
I have not runned it but can you spot if I'm wrong or not ?

```javascript
require('systemjs');

var oldInstantiate = System[System.constructor.instantiate];
System[System.constructor.instantiate] = function(key, processAnonRegister) {
    if (overrideDefaultInstantiate(key) === false) {
        return oldInstantiate.apply(this, arguments);
    }
    getSource(key).then(transpile).then(function(code) {
        eval(code);
        processAnonRegister();
    });
};
System.import('foo').then(function(exports) {
    exports.default; // 42
});

function overrideDefaultInstantiate(key) {
    return true;
}
function getSource(key) {
    return Promise.resolve('export default 42');
}
function transpile(code) {
    return Promise.resolve(`
        System.register([], function (_export, _context) {
            return {
                setters: [],
                execute: function () {
                    _export("default", 42);
                }
            };
        });
    `);
}
```

**Comment by guybedford** [comment]
Sure I can't confirm if it will run perfectly, but yes, the principle there looks exactly right!

**Comment by dmail** [comment]
@guybedford Thank you very much. I've made a small donation because I think this project deserves it.

To me, this issue is resolved so I close it. When my project will be using 0.20 with the instantiate hook I'll come back here to let you know if it went well.

**Comment by gkovacs** [comment]
@dmail did you end up figuring out how to override just the fetch portion while retaining the default SystemJS logic for the transpile stage? In particular, the ability to use packageConfigPaths seems non-trivial to replicate. I have the logic below which mostly works for importing CommonJS modules and dependencies, but was wondering if you ended up figuring out how to just use SystemJS's logic for it.

```javascript
  var oldInstantiate = SystemJS[SystemJS.constructor.instantiate]
  var getSourceAndTranspile = cfy(function*(key) {
    var code;
    var package_name;
    var requires_list = [];
    if (key.endsWith('.json')) {
      var jsonspec = yield localget_json(key);
      var package_name = key.replace(/\.json$/, '')
      var mainpath = package_name + '/' + jsonspec.main;
      code = yield localget(mainpath);
      requires_list = list_requires_multi(code).require;
      var fix_requires_list = function (requires_list) {
        var output = []
        for (let x of list_requires_multi(code).require) {
          if (SystemJS.getConfig().packages[package_name].map[x]) {
            output.push(SystemJS.getConfig().packages[package_name].map[x]);
          } else {
            output.push(x);
          }
        }
        return output;
      }
      requires_list = fix_requires_list(requires_list);
    } else {
      code = yield localget(key);
      requires_list = list_requires_multi(code).require;
    }
    return `
      var somefunc = new Function('require', 'exports', 'module', \`${code}\`)
      System.registerDynamic(${JSON.stringify(requires_list)}, true, somefunc)
    `;
  })
  SystemJS[SystemJS.constructor.instantiate] = function(key, processAnonRegister) {
    return getSourceAndTranspile(key).then(function(code) {
        eval(code);
        processAnonRegister();
    });
  };
```

**Comment by gkovacs** [comment]
I ended up resolving the issue of overriding the fetch implementation just by modifying SystemJS itself to check for window.systemjs_fetch and using it if available, my modified version is at https://github.com/gkovacs/systemjs the relevant code change is  https://github.com/gkovacs/systemjs/commit/6f2f0181d2f8d30b82645d1906d8e681aeae07cc
