### ISSUE TITLE
Is there any way to specify globals for the loaded script?

### ISSUE THREAD

**Issue by maximusk** [systemjs/systemjs#1544]
I have a module `a.js`, inside of which I want to use global variable `thisIsGlobal`, so it look like this:
```
console.log(thisIsGlobal);
```
I load that module like this:
```
SystemJS.import('a.js')
```
Is there any reason to specify globals for the loaded script, something like that:
```
SystemJS.import('a.js'. {globals: {thisIsGlobal: 3}})
```
I've seen that SystemJS wraps every module it loads with:

```
(function (System, SystemJS) {
    (function (require, exports, module, __filename, __dirname, global, GLOBAL) {
        module.exports = function a() {
            require('b.js');
        };
    }).apply(__cjsWrapper.exports, __cjsWrapper.args);
})(System, System);

```
and there's `global` and `GLOBAL`, so I thought maybe I could specify globals for each loaded script?

**Comment by guybedford** [comment]
@maximusk this can be done in SystemJS with:

```javascript
System.set('customglobal', System.newModule({ __useDefault: true, default: 3 }));
System.config({
  meta: {
    'a.js': {
      format: 'global',
      globals: {
        thisIsGlobal: 'customglobal'
      }
    }
  }
});
```

**Comment by maximusk** [comment]
thanks a lot for the solution! can you please tell me if it's possible to update `config` with modules and set globals values if System has already loaded some modules? The `globals` are not available before some modules are loaded, so is it possible to load some module, get values it exports and set globals based on it?

**Comment by maximusk** [comment]
@guybedford , thanks, but with this configuration, the `a.js` module is executed in the global context and is not wrapped inside `(function (System, SystemJS) {`. Can I get globals but have the script executed as a module?
