### ISSUE TITLE
Promise polyfill no longer loaded since 0.19.42

### ISSUE THREAD

**Issue by davidpronk** [systemjs/systemjs#1545]
After https://github.com/systemjs/systemjs/commit/afdeb3b693f6c43715932c8c30dac4d07ccf30df#diff-aee44e374b3a8148407e287f2eae402b the Promise polyfill is no longer loaded by SystemJS. This appears to be a breaking change since we use a dependency on ~0.19.26

I relied on the polyfill being loaded by SystemJS as found in the documentation:
"Otherwise, when Promise is not available, SystemJS will attempt to load the system-polyfills.js file located in the dist folder which contains the when.js Promise polyfill."

There is a basic example on our server at:
http://files.vpro.nl/frontend/systemjs-test/test/

In IE11 this page throws the following error:
```
SCRIPT5009: 'Promise' is undefined
File: system.js, Line: 4, Column: 15849
```

**Comment by guybedford** [comment]
Thanks, I've posted a 0.19.43 with the fix.

**Comment by marknach** [comment]
I'm seeing this same issue now on version 20.19

after https://github.com/systemjs/systemjs/commit/f9bf5fc20721b98cb9ad670e110c4f0b34df15ad ?

**Comment by Craig939393** [comment]
someone should open this again
