### ISSUE TITLE
Difference between 'System.import' and 'SystemJS.import'?

### ISSUE THREAD

**Issue by draptik** [systemjs/systemjs#1547]
Sorry if this is obvious to every one else but me: 
Is there a difference between using 

`System.import(...)` 

and 

`SystemJS.import(...)`?

**Comment by guybedford** [comment]
They are identical, `SystemJS` is used because the loader spec uses `System` which may be a conflicting namespace in future. For now though both are still safe to use.

**Comment by draptik** [comment]
@guybedford  Thanks for clarifying!
