### ISSUE TITLE
Support normalize functions in { map }

### ISSUE THREAD

**Issue by alexisvincent** [systemjs/systemjs#1548]
@guybedford I would like to propose that SystemJS support hooking into the normalization step of the resolve function via a normalize function inside map. I'm aware that some of the semantics around resolving modules has changed recently, so please forgive misuse of names.

In short, I want to be able to
```js
SystemJS.config({
  map: {
     'foo': (moduleName, parentName, parentAddress) => moduleName + parentName,
     'bar/*.js': (moduleName, parentName, parentAddress) => moduleName + '.old.js'
  }
})
```

This would give folks would have a more powerful, cleaner mechanism for doing custom module resolution and wouldn't have to resort to monkey patching System.normalize.

**Comment by lll000111** [comment]
In the meantime, while I wait for this little option, how do I "hack" this? I don't need this for production, I only need a quick hack for the tests - I have (calcualtions-only, non-GUI) code that runs on both node.js and browser but some very few modules like crypto are different. I want to test everything using the same tests, and when run the tests in the browser I want to load other "helper" modules (e.g. for SHA-256) without changing the (test) code. I could import dynamically, but that would mean to change all tests. A quick hack that exchanges the imports seems much cleaner to me! So simple, five lines of code in the test caller, just exchange the "-nodejs" string in imports for "-browser".

I tried intercepting functions, identifying the module-name string parameter, changing the string, calling the original SystemJS function. No luck.

First, I tried `normaliize[Sync]` and that doesn't even get called, so what's it for?

But anyway, I found that `SystemJS.constructor.prototype.resolve` is called, but I can't intercept it. I use `return resolveOrig.apply(SystemJS, args);` to call the original but end up with 

    Error: CreateListFromArrayLike called on non-object

How do I call the original method correctly? Is `resolve` the best function to intercept anyway?

In any case, the feature suggested here would put an end to all of this and it seems to me to be a pretty simple and clean solution too.

**Comment by guybedford** [comment]
Custom resolver hooks are still the recommended way of handling this:

```javascript
let resolve = System[System.constructor.resolve];
System[System.constructor.resolve] = function (key, parentKey) {
  if (key.startsWith('bar/'))
    return key + '.asdf.js';
  return resolve.call(this, key, parentKey);
};
```

I'm not sure it's an API we should try to make "easier" as custom hooks should feel like custom hooks.

**Comment by lll000111** [comment]
My main problem was I had to do a lot of source code reading and even more trial and error to find out simple things like this, other stuff too. I must admit I don't understand the first line in that code, why is the right side the way it is?

**Comment by guybedford** [comment]
`System.constructor.resolve` is a symbol, because the resolve function is not publicly exposed. This is a common pattern for private class variables in JavaScript.

**Comment by lll000111** [comment]
I didn't know it was a symbol and wondered why there is a function.

**Comment by ArmorDarks** [comment]
As I've said in this somehow related issue https://github.com/systemjs/systemjs/issues/1643, I'm quite upset that SystemJS encourages such monkey patching patterns...
