### ISSUE TITLE
version 2.0, "wilcards are being deprecated"

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1549]
So, I wanted to try v2.0, and I turned warnings on. The only one I got happens when I run jspm bundle.

> Paths  configuration "babel-runtime/*" -> "file:///home/asdf/node_modules/babel-runtime/*.js" 
> uses wildcards which are being deprecated for just leaving a trailing "/" to indicate folder paths.

Thing is, I havent configured babel runtime anywhere since I used jspm v0.16 a year ago.

**Comment by guybedford** [comment]
@amenadiel thanks, this isn't anything to worry about, but I've added a fix for this in https://github.com/systemjs/systemjs/commit/b097fb885bdd1fdcacae174908574d466fb58ff8, for a 0.19 patch release.

**Comment by guybedford** [comment]
Released in 0.19.45.
