### ISSUE TITLE
Warning: { name: module.id } is deprecated, tip to replace it

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1551]
Got this warning, which I knew I had coming.

My project was full if

```js
System.import('mymodule', {
    name: module.id
});
```

So, in sublimetext, I did a replacement in the whole project using the regex tool (Alt+R)

Find:
```js
{\n\t+name: module\.id\n\t+}
```
Replace with
Find:
```js
module.id
```

You might have to change the \t for \s if your indent with spaces.

**Comment by guybedford** [comment]
Thanks, closing but this should be available in the search for others.
