### ISSUE TITLE
Broken external import if build consists of at least one non-ESM module

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#1553]
It's broken both on SystemJS 0.19 and 0.20. The build is being done like this:
`jspm build appBroken.js out.js --externals dynamic --format cjs`

```js
// foo.js
module.exports = 'foo';
```

```js
// appBroken.js
import { getCounter } from 'dynamic';

import foo from 'foo'; // depending on this import, the build either works or not

setInterval(() => {
  console.log('Counter', getCounter());
}, 100);
```

See this repo for demonstration:
https://github.com/Rush/systemjs-bug-broken-external-import

Instructions on how to reproduce the bug:
```sh
git clone https://github.com/Rush/systemjs-bug-broken-external-import.git
cd systemjs-bug-broken-external-import
npm install
node_modules/.bin/jspm install
./runGood.sh # open browser at suggested URL and see that it works
# ctrl+c now
./runBroken.sh # open browser at suggested URL and see that it's broken
```

Thank you so much in advance if this can be looked at.

@guybedford @joeldenning

**Comment by guybedford** [comment]
@Rush I've included a fix for this in https://github.com/systemjs/builder/commit/5750842af6d15602b01e4a34641d212641696cf1. Note though that the live exports feature of the es module is no longer supported once it is an external of the SFX bundle unfortunately. I'm working on approaches in future to remedy this though.

**Comment by guybedford** [comment]
Released in latest SystemJS and builder.

**Comment by Rush** [comment]
@guybedford thanks, I'll be testing this over the next days. Idea - maybe we could convert non-ESM modules to ESM modules in order for rollup to pick them up and to have cleaner built files?

**Comment by asapach** [comment]
That won't work because CJS modules can call `require()` at any point in the execution, whereas ESM modules imports need to be statically analizable.

**Comment by Rush** [comment]
I see, but weren't there some recent spec updates to allow ESM modules dynamic imports?

**Comment by asapach** [comment]
`require()` is sync, whereas `import()` is async.

**Comment by Rush** [comment]
> I'm working on approaches in future to remedy this though.

Could you point me to an issue that tracks this feature? I unfortunately relied on it until I noticed that it breaks when my SFX had to include a cjs module as shown in this issue.

**Comment by guybedford** [comment]
@Rush nothing to show yet unfortunately, but I'll post out any updates in the gitter chat when the time comes.
