### ISSUE TITLE
No SystemJSLoader.locate/translate  in 0.20 - builder.compile is faulty

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#1554]
I was relying on this here: 

https://github.com/virtkick/node-serve-jspm/blob/master/src/serve-jspm.js#L28

serve-jspm in an Express middleware to pre-load and transpile modules on the server side.

**Comment by guybedford** [comment]
The approach here can be replaced by a `builder.compile` server, as in https://github.com/Munter/express-systemjs-translate/blob/master/lib/index.js#L347.

**Comment by Rush** [comment]
I'll do production testing later but so far appears to work fine. Thank you.

**Comment by Rush** [comment]
Actually I encounter some problem:
```js
// fullDir = /home/rush/code/frontend/javascripts/jspm_packages/github/angular/bower-angular@1.6.0.json
builder.compile(fullDir, {});
```
and getting:
```
Error: (SystemJS) ENOENT: no such file or directory, open '/home/rush/code/frontend/javascripts/jspm_packages/github/angular/bower-angular@1.6.0.json.json'
```

The example you posted is not resolving any paths - should I preprocess the path?

**Comment by Rush** [comment]
@guybedford this should reproduce the problem. Furthermore it appears that compiling `system.js` file itself will wrap it in a global wrapper, same for loading `jspm.config.js`. It was now the case with previous approach.

http://x.rushbase.net/1defe4c468d7a64b4b21050bf7e0668e6f39974b/systemjs-compile-bug.zip

```js
// test.js
let Builder = require('jspm').Builder;
let builder = new Builder();

builder.compile('jspm_packages/github/angular/bower-angular@1.6.1.json').then(console.log).catch(console.error);⏎                                                                                                                                            
```

package.json
```
{
  "jspm": {
    "name": "app",
    "main": "app.js",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.6.1"
    },
    "devDependencies": {
      "plugin-babel": "npm:systemjs-plugin-babel@^0.0.20"
    },
    "overrides": {
      "github:angular/bower-angular@1.6.1": {
        "main": "angular",
        "meta": {
          "angular.js": {
            "exports": "angular",
            "format": "global"
          }
        }
      }
    }
  },
  "devDependencies": {
    "jspm": "^0.17.0-beta.36"
  }
}
```

jspm.config.js
```js
SystemJS.config({
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "app/": "src/"
  },
  browserConfig: {
    "baseURL": "/"
  },
  devConfig: {
    "map": {
      "plugin-babel": "npm:systemjs-plugin-babel@0.0.20"
    }
  },
  transpiler: "plugin-babel",
  packages: {
    "app": {
      "main": "app.js",
      "meta": {
        "*.js": {
          "loader": "plugin-babel"
        }
      }
    }
  }
});

SystemJS.config({
  packageConfigPaths: [
    "npm:@*/*.json",
    "npm:*.json",
    "github:*/*.json"
  ],
  map: {
    "angular": "github:angular/bower-angular@1.6.1"
  },
  packages: {}
});
```

```sh
rush@rushpod: ~/c/systemjs-compile-bug » node test.js
{ (SystemJS) ENOENT: no such file or directory, open '/home/rush/code/systemjs-compile-bug/jspm_packages/github/angular/bower-angular@1.6.1.json.json'
        Error: ENOENT: no such file or directory, open '/home/rush/code/systemjs-compile-bug/jspm_packages/github/angular/bower-angular@1.6.1.json.json'
            at Error (native)
        Error loading /home/rush/code/systemjs-compile-bug/jspm_packages/github/angular/bower-angular@1.6.1.json.json
  originalErr: 
   { Error: ENOENT: no such file or directory, open '/home/rush/code/systemjs-compile-bug/jspm_packages/github/angular/bower-angular@1.6.1.json.json'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/home/rush/code/systemjs-compile-bug/jspm_packages/github/angular/bower-angular@1.6.1.json.json' } }
```

**Comment by guybedford** [comment]
@Rush yes this is a known issue with the compile approach unfortunately.

I hate to recommend it, but it may just be better to stick with SystemJS 0.15 for this compile server itself to use the hooks as before, while using SystemJS 0.16 in the browser.

**Comment by guybedford** [comment]
(this is exactly what SystemJS builder 0.16 is doing as well)

**Comment by Rush** [comment]
Unfortunately it's not really working.


```js
import {Loader, Builder} from 'jspm'; // jspm 0.17.0-beta.36

const jspmLoader = new Loader;
const config = jspmLoader.getConfig();

const loader = require('systemjs'); // 0.19.46
loader.config(config);

// workaround for: https://github.com/jspm/jspm-cli/issues/2202
const SystemJSBuilder = require('systemjs-builder'); // ^0.16.1
loader.getCanonicalName = (new SystemJSBuilder).getCanonicalName;

```

and while running my tests I get:
```
(SystemJS) EISDIR: illegal operation on a directory, read
        Error: EISDIR: illegal operation on a directory, read
            at Error (native)
        Error loading /home/rush/code/serve-jspm/tests/jsx-loader/jspm_packages/github/floatdrop/plugin-jsx@1.2.1
```

Not sure what I'm doing wrong or maybe this is not a good approach after all? Should I simply lock in to `beta.32` and wait for appropriate fixes in `systemjs` loader/builder? How can I help?

**Comment by guybedford** [comment]
@Rush this would require using SystemJS Builder 0.15 to do the compilation process I believe.

I'm not really sure what might be best for you here though. It's difficult to focus on these cases with SystemJS 0.20 because the focus is on building a really good browser loader, as opposed to something that can be used as "middleware" in tooling. Rather, static build approaches are better for this middleware over inlining SystemJS builds.

It would be a builder issue to fix the problem in https://github.com/systemjs/systemjs/issues/1554#issuecomment-276133001, which we can gladly pick up in the builder issue queue and look at approaches forward. Last time I looked at this problem properly I remember thinking it was a tricky one to solve, but perhaps if you're willing to assist we may make more progress on it this time too.

**Comment by Rush** [comment]
@guybedford What I don't quite get is why I necessarily need the builder. After all what I'm after is simulating the same code transformation a browser SystemJS would do, such as passing the code through plugin-babel/plugin-jsx. In my original serve-jspm version I was not using the builder at all, just the loader. https://github.com/virtkick/node-serve-jspm/blob/8e0cf28df63f835449f05a07c482ded2c9bab3c1/src/serve-jspm.js#L35 - cannot such API be added to the newest rewritten SystemJS?

**Comment by Rush** [comment]
Or maybe I should just call the same code in serve-jspm as you do in here? https://github.com/ModuleLoader/browser-es-module-loader/blob/master/src/browser-es-module-loader.js#L133

I cannot wrap my head around the new SystemJS, no idea where plugins are handled. :)

**Comment by guybedford** [comment]
@Rush the builder is designed to provide the identical transform ability between browser and server, and you can hook the loader hooks in the builder, but not the SystemJS loader. I think that's the distinction that may help you understand the change here.

**Comment by Rush** [comment]
@guybedford:

`.compile` seems to be using `browserConfig` - how can I differentiate between `.compile` and actual browser? 
```
  browserConfig: {
    "baseURL": "/js",
    "map": {
      "pug": "pug-browser.js"
    }
  },
```

My `pug-browser.js` is simply:
```js
export function locate(load) {
  return Promise.resolve(load.name + '.js');
};
```
I want to handle such requests with a real `pug.js` plugin on the server. Letting the browser load the plugin means many many many more requests and slowdowns.

**Comment by Rush** [comment]
@guybedford I was able to use the previous approach like so:

```js
const builder = new Builder;
const loader = builder.loader;

// workaround for: https://github.com/jspm/jspm-cli/issues/2202
loader.getCanonicalName = builder.getCanonicalName;
```

This works because like you said the builder in JSPM is usign an older SystemJS so getting the load from the builder works around the SystemJS 0.20. Am I safe to use this approach for now?

To be honest, trying to make it work is like going down the rabbit hole. :-)

**Comment by guybedford** [comment]
@Rush that looks good to me, and SystemJS builder won't be removing this support. It is a complex edge I know.

**Comment by Rush** [comment]
Thanks, closing until next time. :)
