### ISSUE TITLE
Memory leak during lazy module import & delete (v0.19.45, v0.20.4)

### ISSUE THREAD

**Issue by PavelPZ** [systemjs/systemjs#1555]
I have two ES6 modules: library.js and lazy.js. 
library.js is loaded once during app start, lazy.js is loaded x unloaded many times during interaction with app.
I am using Typescript 2.1.5. ES6 => ES5 transpiler from VS.NET IDE.

**library.js**
```
export const libFunction = () => alert('libFunction');
```

**lazy.js**
```
import { libFunction } from 'library';
libFunction();
```

**App start phase:**
```
System.import ('library.js').then…
```

**Lazy loading (only lazy.js is fetched):**
```
System.import ('lazy.js').then(…
```

**Lazy unloading:**
```
System .delete(System.normalizeSync('lazy.js'));
```

## Error:
Lazy.js is still loaded on Chrome heap, as I can see in Chrome Developer Tools => Profiles => Heap snapshot => (compiled code).
If I load x unload lazy.js many times, there are more instances of lazy.js compiled code on Chrome heap.

## Workaround:
If I don't preload library.js during App start and delete it during lazy unloading, all is OK:

**Lazy loading (both lazy.js and library.js are fetched):** 
```
System.import ('lazy.js').then(…
```

**Lazy unloading (both library.js and lazy.js are unloaded from Chrome heap as I can see in Heap snapshot => (compiled code))**
```
System .delete(System.normalizeSync('library.js'));
System .delete(System.normalizeSync('lazy.js'));
```

**Comment by PavelPZ** [comment]
Transpiled code:

**library.js**
```
System.register([], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var libFunction;
    return {
        setters: [],
        execute: function () {
            exports_1("libFunction", libFunction = function () { return alert('libFunction'); });
        }
    };
});
```

**lazy.js**
```
System.register(["library"], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var library_1;
    return {
        setters: [
            function (library_1_1) {
                library_1 = library_1_1;
            }
        ],
        execute: function () {
            library_1.libFunction();
        }
    };
});
```

**Comment by guybedford** [comment]
@PavelPZ thanks for posting the detailed report here, memory leaks are great to catch! Have you tried this with SystemJS 0.20 though? That may correct the issue, although the upgrade path isn't necessarily trivial I know.

**Comment by PavelPZ** [comment]
@guybedford, I am sorry, SystemJS 0.20 does not work for me (I am waiting for Typescript fix https://github.com/Microsoft/TypeScript/issues/13709).

**Comment by guybedford** [comment]
@PavelPZ the plugin-typescript master may have some fixes here to help as well?

**Comment by PavelPZ** [comment]
@guybedford, thanks a lot, I will try it.

Anyway, is there any official recommendation for lazy loading x unloading ES6 modules, bundles etc.?
In React world, there is common pattern to have single JSX file for every web page, product catalogue page etc. As a result, you could have thousands of independent JS files (some of them with dependencies), proceed them with caution is important. I cannot find any official strategy for such use case.

I use this code to recognize all lazy loaded dependencies:

**Before loading:**
```
oldInstantiate = System.instantiate;
let lazyLoaded = [];
System.instantiate = function (obj) {
  lazyLoaded[obj.name] = true; //register module, loaded in bundle
  return oldInstantiate.apply(this, arguments);
};
System.import('xxx').then (m => System.instantiate = oldInstantiate;)
```
**Release after using...:**
```
lazyLoaded.forEach(name => System.delete(name));
```

I know limitations of such solution, but I cannot find better one. 

Sorry for maybe stupid question...

**Comment by guybedford** [comment]
SystemJS enables lazy loading workflows, but doesn't prescribe exact workflows here too much. When it comes to bundling it is really up to you how you want to structure the loading of modules. Workflows around SystemJS that provide exact optimisations is an area ripe for new projects and contributions.

**Comment by PavelPZ** [comment]
@guybedford, situation with **v0.20.4** is even worse. When I remove library.js dependency from lazy.js, this code
```
await System.import ('lazy.js'); System.delete(System.normalizeSync('lazy.js'));
```
leaves lazy.js in memory (this code works well in v0.19.45).

If I repeat this code many times, e.g.
```
await System.import ('lazy.js'); System.delete(System.normalizeSync('lazy.js'));
await System.import ('lazy.js'); System.delete(System.normalizeSync('lazy.js'));
```
only one copy of lazy.js remains in memory.

**lazy.js with dependency in v0.19.45**
When I repeat import & delete many times, more copies of lazy.js remain in memory.

**Comment by PavelPZ** [comment]
@guybedford, you can see 
- working example at https://pavelpz.github.io/systemjs-memory-leak/. There you can try both correct and wrong behavior.
- source at https://github.com/PavelPZ/systemjs-memory-leak

The only difference between wrong and correct lazy-*-lib.js is:
- wrong version (lazy-with-lib.js) depends on library.js
- correct version (lazy-without-lib.js) has no dependency

Code for infinite IMPORT - DELETE loop:
```
const loadLazies = (withLibrary: boolean) => {
  //load and delete: 
  // - or lazy-with-lib.js (which depends on library.js) 
  // - or lazy-without-lib (without any dependency)
  let id = withLibrary ? 'lazy-with-lib' : 'lazy-without-lib';
  id = id + '.js?' + count.toString();

  //infinite loop: import and delete lazy??.js 
  System.import(id).then(m => {
    m.init(count++);
    System.delete(System.normalizeSync(id));
    setTimeout(() => loadLazies(withLibrary), 1);
  });
};
```

**Comment by PavelPZ** [comment]
In another version of test, I included two other options:
- meta: { '*': { scriptLoad: true } }
- System.delete('library.js')

**Results:**
- Chrome : both ```scriptLoad: true``` and System.delete('library.js') solves problem
- Chrome : only problem is ```With dependency, scriptLoad=false, delete library=false```
- IE 10: ```scriptLoad: true``` increases the number of successful import-delete cycles but do not solve it
- IE 10: System.delete('library.js') solves problem
- Firefox: all six cases work well

**Hypothesis:**
- when ```System.delete('library.js')``` sometimes helps, part of the problem could be in SystemJS
- when ```scriptLoad: true``` sometimes helps, eval([fetched JS witch dependency]) is not correct (in SystemJS or in browser)
- IE10 has its own problems

**Warning:**
Maybe my test or my conclusion is not correct

**Comment by guybedford** [comment]
@PavelPZ thanks so much for your investigation work here. I'm going to look into these cases and results as soon as I have a moment and get back on this soon.

**Comment by guybedford** [comment]
I've addressed these in https://github.com/ModuleLoader/es-module-loader/commit/64c0b583f914d3d32184c37adf96af2b737a3df7 and https://github.com/systemjs/systemjs/commit/19f854de638044e50e1367b02bea2ab16d268aa0, which will be released in the next patch shortly. Thanks for posting your investigation here.

**Comment by PavelPZ** [comment]
Thanks a lot. 
I can see v0.20.9 - does it contain your patch? 
I need patch for v0.19, I can see v0.19.46 in 0.19 branch but it is too old to have your fix.

**Comment by guybedford** [comment]
Ah, yes 0.19 is no longer being developed, and would be a completely different case as well as it is an entirely different codebase.

**Comment by PavelPZ** [comment]
Ok, thank you.
