### ISSUE TITLE
Fetch error: 404 Not Found

### ISSUE THREAD

**Issue by bennyn** [systemjs/systemjs#1556]
I tried to load a CommonJS module using SystemJS. The example which I used is very simple. It looks like this:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <script src="../bower_components/system.js/dist/system.js" />
    <script>
      SystemJS.config({
        map: {
          'wire': '../src/main/js/index.js'
        },
        packages: {
          'wire': {format: 'cjs'}
        }
      });
    </script>
  </head>
  <body>
    <script>
      SystemJS.import('wire').then(function(wire) {
        console.log('Module', wire);
      });
    </script>
  </body>
</html>
```

And here is the **index.js** of my module (`wire`):

```javascript
module.exports = {
  User: require('./user/User')
};
```

Unfortunately, I am always getting this error: 

> Failed to load resource: the server responded with a status of 404 (Not Found)
index.html:1 Uncaught (in promise) Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3636/demo/wire
  Loading wire
    at system.js:4

Why does SystemJS tries to load `wire` from `http://localhost:3636/demo/wire`? Because with `SystemJS.config` I specified to lookup `../src/main/js/index.js`.

I am using "SystemJS v0.20.3 Dev".

**Comment by atrauzzi** [comment]
Not sure if it's related, but I'm having a heck of a time with an import right now as well: https://github.com/jspm/jspm-cli/issues/2228

**Comment by guybedford** [comment]
This may be related to a pathing regression in https://github.com/systemjs/builder/issues/766. I've just released a fix in SystemJS 0.20.4, let me know if that helps.

**Comment by bennyn** [comment]
@guybedford I am sorry, but it does not work with v0.20.4.

My code sample is here: https://github.com/wireapp/wire-webapp-core/commit/a8330bb7884bc0d3d7a236bb02e2dc5a403eeb87

**Comment by ghempton** [comment]
FWIW–probably not related–I was seeing some issues with cjs modules not being mapped correctly after upgrading to 0.20. In this case (since we are using jspm), swapping the order of including `jspm.dev.js` followed by `jspm.config.js` to instead be  `jspm.config.js` followed by `jspm.dev.js` fixed the issue. Not sure what the underlying cause was, but might have been due to configuring a `map` before `packageConfigPaths` or `paths` was configured.

**Comment by guybedford** [comment]
@bennyn I added a test for this in https://github.com/systemjs/systemjs/commit/197b6f048aa1b365a7f00dd2d88cb7880a0972a2 and can't get the failing case. Can you help me replicate it there?

**Comment by fixl** [comment]
@bennyn I had the same issue, and the following solved it for me:
```javascript
SystemJS.config({
    map: {
        'wire': '../src/main/js'
    },
    packages: {
        'wire': {
            main: './index.js'
        }
    }
});
```
