### ISSUE TITLE
Production loader broken with global modules

### ISSUE THREAD

**Issue by ghempton** [systemjs/systemjs#1558]
Not sure if this is an issue here or should be in https://github.com/systemjs/babel-plugin-transform-global-system-wrapper.

Modules compiled with `format: global` include the following logic:

```javascript
System.registerDynamic("github:components/handlebars.js@1.3.0/handlebars.js", [], false, function ($__require, $__exports, $__module) {
  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, "Handlebars", null);
```

Two problems are encountered when trying to use `system-production.js`:

1.  `System.get` is not defined. Instead it should be `System.registry.get`.
2. `@@global-helpers` doesn't exist as a module

Is there a way around this?

**Comment by guybedford** [comment]
Getting these build outputs to be compatible with the production loader is currently not supported, but it is definitely a direction we should be aiming for.

I've updated the transform to use `System.registry.get` in the 0.4.0 version.

I've also posted an issue at https://github.com/systemjs/babel-plugin-transform-global-system-wrapper/issues/1 to track removing the global helpers entirely.

In the mean time the global helpers can be enabled for the production loader by including the `System.registry.set` call from https://github.com/systemjs/systemjs/blob/master/src/format-helpers.js#L10 into the production build file before loading the modules.
