### ISSUE TITLE
20.x branch cannot fetch secured script

### ISSUE THREAD

**Issue by umphy** [systemjs/systemjs#1560]
I noticed in my app when I upgraded to 20.x (tried x=0-4), the script loading breaks due to the resource being secured.

Looking at the requests, here are the main differences:

1. 19.x the request type is ```xhr```, whereas 20.x is ```fetch```
2. 19.x has ```Cookie``` in the request header, whereas 20.x does not

I suspect it's because of 2. that my app breaks because without the Cookie in the header, the app does not allow the fetching of the secured resource.

**Comment by guybedford** [comment]
Try using the following meta configuration here:

```javascript
System.config({
  meta: {
    'https://resource-path/*': { authorisation: true }
  }
});
```

I'll note this as a breaking 0.20 change.

**Comment by umphy** [comment]
Yup that did the trick. Thanks @guybedford :)
