### ISSUE TITLE
Error: Module https://cdn.rawgit.com/mochajs/mocha/v3.2.0/mocha.js detected as amd but didn't execute correctly.

### ISSUE THREAD

**Issue by WhyEvenTry** [systemjs/systemjs#1562]
This is more a request for free and unpaid support rather than a ticket I guess... on the other hand, at the very least I would like to have a better error message. This is way too fuzzy. What is "didn't execute correctly"?

**EDIT:** I think System.js mis-detects the module type? It says "amd", but it seems to me it's CommonJS.

**EDIT^2:**  Adding

```javascript
        meta: {
            'https://cdn.rawgit.com/mochajs/mocha/v3.2.0/mocha.js': {
                format: 'cjs'
            }
        },
```

to the system.js config loads mocha.js.

<br>

<hr>

<br>

I'm following the instructions on http://staxmanade.com/2015/09/browser-only-mochajs-tests-using-systemjs/ to run my tests in the browser (thus far everything ran in node - but it's mostly system independent code that could run anywhere).

`index.html` and `testInit.js` file are mostly just copied from http://plnkr.co/edit/LLQQqg?p=preview (the code for the blog post above). It's all pretty simple - a tiny HTML file and a small JS file. My HTML file is only slightly different, I configures system.js to get mocha from github:

I changed the ES 2015 style `import` statement in the JS file (see the plnkr link) to `const mocha = require('mocha');` - I'm not using Babel, just the ES 2015 that the browser understands anyway.

```javascript
    SystemJS.config({
        baseURL: 'build',
        map: {
            mocha: 'https://cdn.rawgit.com/mochajs/mocha/v3.2.0/mocha.js',
            test: '/One/test',
            chai: '../node_modules/chai/chai.js',
            'chai-as-promised': '../node_modules/chai-as-promised/lib/chai-as-promised.js',
            sinon: '../node_modules/sinon/lib/sinon.js',
            'js-sha256': '../node_modules/js-sha256/build/sha256.min.js'
        }
    });
```

The maps work. the file is loaded, but I get

```
Error: Module https://cdn.rawgit.com/mochajs/mocha/v3.2.0/mocha.js detected as amd but didn't execute correctly.
  Instantiating https://cdn.rawgit.com/mochajs/mocha/v3.2.0/mocha.js
  Loading http://localhost:63342/One/test/testInit.js
  Loading ./testInit.js
    at system.js:5
```

But nothing else. Googling the error message yields zero matches.

I don't want to install mocha locally because there is a bug in WebStorm (that has been open for a looong time), with `mocha` installed in the project directory WebStorm picks up a lot of its type inferences and auto-complete suggestions from mocha even in the non-test code. I'm not even sure if it would even improve anything if I loaded it _exactly_ like in the example, I might still have this problem here...

**Comment by asapach** [comment]
My guess is that it erroneously detects mocha as `amd` format, because there are a couple of `define()` statements, but it's actually a `global`. Try setting the format explicitly: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta

**Comment by WhyEvenTry** [comment]
Well, see my EDIT... yes that was it.

Now I have the problem that everything loaded from that file is loaded from my local system instead of from the CDN. It almost looks like the whole thing is impossible? I cannot load mocha from the CDN using system.js? Because there is no simple map entry, I would have to specify each and every file mocha loads individually.

**Comment by asapach** [comment]
As I said, try `global`. I don't think it's meant to be loaded as `cjs` in the browser.

**Comment by WhyEvenTry** [comment]
I _did_ set the format and loaded it, that's why my follow-up question? Was the reference to `global` about something else?
