### ISSUE TITLE
404 Error: Angular 2 Router Lazy Loading

### ISSUE THREAD

**Issue by udos86** [systemjs/systemjs#1565]
Hi,

we're experiencing a weird bug when working with the lastest SystemJS version while using Angular 2's lazy loading routing feature: the first character of the NgModule path is stripped resulting in an automatic 404 GET error.

This is our sample route configuration:
```
{
    path: 'experimental',
    loadChildren: './components/experimental/experimental.module#ExperimentalModule'
}
```

However at run time SystemJS tries to load the NgModule from the following URL:  `//omponents/experimental/experimental.module#ExperimentalModule`

When downgrading to an earlier version of SystemJS everything seems to work fine again.

**Comment by guybedford** [comment]
@udos86 check you're definitely using the latest patch version of SystemJS (0.20.5), and if so, would it be possible to share a full replication so I can look into this further?

**Comment by udos86** [comment]
@guybedford Thanks for your answer! After some further research we're pretty sure that this is not related to an error in the latest versions of SystemJS. We will let you know!
