### ISSUE TITLE
Promise polyfill

### ISSUE THREAD

**Issue by nazjunaid** [systemjs/systemjs#1566]
Hi we updated systemjs/jspm and started having issues in IE 

'Promise' is undefined

I noticed the system-polyfills.js is no longer included. Is there something we need to do to get systemjs working in IE/older browsers?

**Comment by amenadiel** [comment]
I'll answer the same as in  [jspm-cli#2227](https://github.com/jspm/jspm-cli/issues/2227): use a promise library via a script tag 

```html
    <script src="https://cdn.jsdelivr.net/bluebird/3.4.3/bluebird.min.js"></script>
```

before loading system.js

**Comment by nazjunaid** [comment]
Thanks that sorted the issue
