### ISSUE TITLE
Fetching lazily from mixed ESM/UMD results in CPU peak

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1567]
My main entrypoint is an ESM module which has several dependencies, some of which are AMD (like jQuery).

When I lazy load the main package as

```html
<script src="/jspm.config.js"></script>
<script >
	System.import('my_app');
</script>
```

I can see a `fetch` request to the main file inside `my_app` but then nothing else happens, and CPU peaks to 100%.

This is happening since SystemJS 0.20.0 and is still happening on 0.20.5. 

My best guess is that one or more non ESM dependencies are causing SystemJS to get stuck on a path resolution loop. However, no error is seen in the console, so maybe there should be a maximum level of recursion after which SystemJS would throw a resolution error.

PD: probably meaningless, but `fetch.js` shows up as loading from `/src/fetch.js`, but there is no such folder.

**Comment by guybedford** [comment]
@amenadiel can you perhaps share the contents of the file being loaded that peaks the CPU here? Also does it help if you add a meta configuration to set the module format of that file explicitly? Is it an ES module that is being transformed in the browser?

**Comment by amenadiel** [comment]
@guybedford I was trying to build a minimal, functional example of my issue. The simplest example didn't freeze, so I kept adding more and more parts of my app to the example until it froze.

It turns out I'm using json plugin to load some locales, so I had

```js
 "*.json": {
      "defaultExtension": false,
      "loader": "json"
 }
```

in my meta. Not a package meta, but the root meta property. Removing that part from my config (and temporarily disabling localization) did the trick.
