### ISSUE TITLE
Error: undefined is not a valid transpiler plugin (0.20.0)

### ISSUE THREAD

**Issue by josh-sachs** [systemjs/systemjs#1572]
Can we get some additional information on what this means?

"Default transpiler loading is removed. It is no longer possible to transpile sources without configuring one of the transpiler plugins."

Simply using System.config({transpiler: 'plugin-typescript'}) doesn't seem to work in 0.20.0 whereas it did in previous releases.

**Comment by kudoz83** [comment]
This is related to 1573... the undefined is due to a typo in the system.src.js source code.  That said, Fuck knows why plugin-typescript isn't a valid plugin.  I've opened an issue for that in the plugin-typescript repo (#190)
