### ISSUE TITLE
Paths and systemjs 0.20.5

### ISSUE THREAD

**Issue by msmolka** [systemjs/systemjs#1575]
I'm using version 0.20.5
in pre 0.20 version I have following config for kendo:
[http://docs.telerik.com/kendo-ui/third-party/systemjs](http://docs.telerik.com/kendo-ui/third-party/systemjs)

```json
 System.config({         
          paths: {
            'kendo.*': "lib/kendo/kendo.*.js"
          }
        })
```

and when I imported 
```js
System.register(["jquery", "app", "kendo.dropdownlist.min"], function
```

all worked and `kendo.dropdownlist.min` was searched in proper folder.

now it searched in root.

**Comment by guybedford** [comment]
Wildcard paths were deprecated in SystemJS 0.20. Unfortunately this dynamic paths approach is no longer supported, instead you would need to use a separator:

```javascript
System.config({
  paths: {
    'kendo/': 'lib/kendo/'
  }
});
```

with `System.register(['kendo/kendo.dropdownlist.min.js'])`.

**Comment by msmolka** [comment]
Thanks for answer, that will require quite a lot of modules to change for me. It's a pity that useful feature was deprecated.

**Comment by msmolka** [comment]
I wonder if it would be possible to workaround the issue by overwriting locate function.

**Comment by MaximBalaganskiy** [comment]
I keep my code on a separate `src` folder under `baseURL` and in 0.20 will be forced to always use `src` in imports... Prior I could do this
`
"paths": {
      "*": "src/*"
}
`

**Comment by CxRes** [comment]
Continuing on the above theme:
I was using the form 
```
paths:{
  "components/*":"app/components/*/index"
}
```

Now if I am to follow the systemjs 0.20 method, it seems I will have to declare 
```
paths:{
  "components/":"app/components/"
}
```

and either rewrite all imports which previously were
```
import 'component/thing'
```
as
```
import 'component/thing/index.js'
```
or 
create a file `component/thing.js` which just the line 
``` 
import `component/thing/index.js`
```

**Is there a better way to deal with this?**

**Comment by owlcode** [comment]
I'm also dealing with almost identical problem. Did you solve it?

**Comment by msmolka** [comment]
for me solution was "simple" map every file in config. It is aout 100 lines but works.
