### ISSUE TITLE
Resolve issue with packageConfigPaths

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1577]
using `systemjs`: 0.20.5

I'm working on a plugin system that based on `systemjs`. 
I'm loading the packages in `node_modules`.
I'm able to load package and scoped package (yey! :smile:)

with the following code: 

```ts
test.only('npm-module', async t => {
  const pluginName = 'npm-module'
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: `plugins/${pluginName}/node_modules`,
    map: {
      [pluginName]: './plugins/' + pluginName
    },
    packageConfigPaths: [
      './plugins/*/package.json',
      '*/package.json',
      '*/*/package.json'  // this enable loading scoped package.
    ]
  })
  await sys.import('nop')  // this is a dependency of `npm-module` and is loading fine
  await sys.import(pluginName) // this loads but throws an error
})
```

The error is:
```sh
Error: ENOENT: no such file or directory, open 'E:\hwong\panda\module-loader\fixtures\npm-module\node_modules\aurelia-logging-color\dist\package.json'
    Instantiating E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/package.json
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/package.json
    Unable to fetch package configuration file E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/package.json
    Resolving ./ColorAppender to E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/index.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/index.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/@pan/logging/dist/es5/index.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/dist/es5/printLog.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/dist/es5/index.js
    Loading npm-module
```

The situation is this:
The `npm-module` using a dependency called `@pan/logging`. It is a scoped package and it is load loading fine (as seen in `Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/@pan/logging/dist/es5/index.js`, which is its main js file)

`@pan/logging` in turns depends on [`aurelia-logging-color`](https://github.com/unional/aurelia-logging-color) and that is also loading, and resolving that package's `./ColorAppender` (the `Resolving ...` line).

However it then tries to load `aurelia-logging-color/dist/package.json` which is wrong. It should be `aurelia-logging-color/package.json`.

Seem like it only go up once to the parent folder (`aurelia-logging-color/dist` from `aurelia-logging-color/dist/es5`).

Since `aurelia-logging-color` is loading, it should already have the right path.

**Comment by guybedford** [comment]
Try using the following for scoped loading - `'@*/*/package.json'`, so that it doesn't match `aurelia-logging-color/dist/`.

**Comment by guybedford** [comment]
To be clear:

```javascript
packageConfigPaths: [
      './plugins/*/package.json',
      '*/package.json',
      '@*/*/package.json'  // this enable loading scoped package.
    ]
```

**Comment by unional** [comment]
Nice! That resolves this issue.
It then have a different issue, but will first see if I can find the answer first. 😄 

It's related to 'browser' field.

**Comment by unional** [comment]
And big thanks! Sensei 🌷 😛
