### ISSUE TITLE
Supporting browser field spec

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1578]
I encountered this after https://github.com/systemjs/systemjs/issues/1577 is resolved.

To recap:
I'm working on a plugin system that based on `systemjs`.
I'm loading the packages in `node_modules`.
The plugin (`npm-module`) uses `@pan/logging` which in turns uses `aurelia-logging-color`.

`aurelia-logging-color` uses the [package browser field spec](https://github.com/defunctzombie/package-browser-field-spec) to conditionally uses a different file in browser environment:

```js
// `aurelia-logging-color` package.json
{
  "main": "dist/es5/index.js",
  "browser": {
    "./dist/es5/environment.js": "./dist/es5/environments-browser.js"
  }
}
```

According to [this](https://github.com/jspm/jspm-cli/issues/1675#issuecomment-215733908)
I tried to change it to:

```js
// `aurelia-logging-color` package.json
{
  "main": "dist/es5/index.js",
  "browser": {
    "./dist/es5/environments.js": "./dist/es5/environments-browser.js"
  },
  "map": {
    "./environments": {
      "browser": "./dist/es5/environments-browser.js"
    }
  },
```
I also tried `./environment.js`, `./dist/es5/environments`, `./dist/es5/environments.js` but all doesn't seems to pick up by `systemjs`.

Is that the right file to change?

**Comment by guybedford** [comment]
Try using:

```json
{
  "map: {
    "./dist/es5/environments.js": {
      "browser": "./dist/es5/environments-browser.js"
    }
  }
}
```

that should work.

**Comment by unional** [comment]
Tried that, doesn't work.

I'm editing `plugins/npm-modules/node_modules/aurelia-logging-color/package.json`. Is this correct?

I wrote that myself so it is possible to make that change (properly in the actual code and release a new version).
However, if I was relying on a 3rd party library, then I would be out of luck?
Is it possible to do it inside `SystemJS.config()`?

**Comment by guybedford** [comment]
@unional the `package.json` file is the correct place for this yes.

What is the exact path is it requesting `./environments` from?

**Comment by unional** [comment]
This is the file requesting it:
https://github.com/unional/aurelia-logging-color/blob/master/src/createBrush.ts
So it is `aurelia-logging-color/dist/es5/createBrush.js`:

```js
"use strict";
var environments_1 = require("./environments"); // here
var Ansi16mBrush_1 = require("./Ansi16mBrush");
var AnsiBrush_1 = require("./AnsiBrush");
var CSSBrush_1 = require("./CSSBrush");

...
```

**Comment by guybedford** [comment]
```json
{
  "map": {
    "./dist/es5/environments": {
      "browser": "./dist/es5/environments-browser.js"
    }
  }
}
```

should definitely work in that case.

There are tests for this exactly as in https://github.com/systemjs/systemjs/blob/master/test/tests/testpkg/system.json#L18.

**Comment by unional** [comment]
...um... then it is weird. Still not working.
I also tried to simplify the scenario by `npm-module` importing `aurelia-logging-color` directly. But the browser field still not loaded:

```sh
  Error: ENOENT: no such file or directory, open 'E:\hwong\panda\module-loader\fixtures\npm-module\node_modules\os\package.json'
    Instantiating E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/os/package.json
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/os/package.json
    Unable to fetch package configuration file E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/os/package.json
    Resolving os to E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/environments.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/environments.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/createBrush.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/ColorAppender.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/node_modules/aurelia-logging-color/dist/es5/index.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/dist/es5/printLog.js
    Loading E:/hwong/panda/module-loader/fixtures/npm-module/dist/es5/index.js
    Loading npm-module
```

I'll create a github repo to demo and test this. 🌷

**Comment by unional** [comment]
Created https://github.com/unional/some-issues/tree/systemjs-browser-field for this issue. 🌷

**Comment by unional** [comment]
I have updated `aurelia-logging-color` to include the `"map": { ... }` already.

**Comment by guybedford** [comment]
@unional it works if you change `browser` to `node`... so the problem here is that because your test is running in Node it is following the node path.

**Comment by unional** [comment]
Sorry, the midnight effect got me. 😛 
I forgot to turn on `jsdomify` when I move the test to the repo. Updated the test.

Or could it be `jsdomify` still not sufficient to make `systemjs` to consider it is in browser?

This test will pass: `isBrowser = typeof window !== 'undefined' && typeof document !== 'undefined';`

Here is the updated code for easy reference:

```ts
import test from 'ava'
import * as SystemJS from 'systemjs'
import jsdomify from 'jsdomify'

test.before(() => {
  jsdomify.create()
})

test.after(() => {
  jsdomify.desctroy()
})

test('npm-module', async _t => {
  console.log('isBrowser', typeof window !== 'undefined' && typeof document !== 'undefined')
  const pluginName = 'npm-module'
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: `plugins/${pluginName}/node_modules`,
    map: {
      [pluginName]: './plugins/' + pluginName
    },
    packageConfigPaths: [
      './plugins/*/package.json',
      '*/package.json',
      '@*/*/package.json'
    ]
  })
  console.log(sys.getConfig())
  await sys.import('npm-module')
})
```

Here is the output:
```sh
isBrowser true
{ baseURL: 'file:///Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/',
  map: { 'npm-module': 'file:///Users/hwong/github/unional/some-issues/plugins/npm-module' },
  paths: {},
  packages: {},
  packageConfigPaths:
   [ 'file:///Users/hwong/github/unional/some-issues/plugins/*/package.json',
     'file:///Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/*/package.json',
     'file:///Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/@*/*/package.json' ],
  depCache: {},
  meta: {},
  bundles: {},
  warnings: false,
  pluginFirst: false,
  production: false,
  wasm: false }

  1 failed

  npm-module

  Error: ENOENT: no such file or directory, open '/Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/os/package.json'
    Instantiating /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/os/package.json
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/os/package.json
    Unable to fetch package configuration file /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/os/package.json
    Resolving os to /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/aurelia-logging-color/dist/es5/environments.js
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/aurelia-logging-color/dist/es5/environments.js
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/aurelia-logging-color/dist/es5/createBrush.js
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/aurelia-logging-color/dist/es5/ColorAppender.js
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/node_modules/aurelia-logging-color/dist/es5/index.js
    Loading /Users/hwong/github/unional/some-issues/plugins/npm-module/src/index.js
    Loading npm-module
```

**Comment by guybedford** [comment]
@unional the browser condition is checked when SystemJS itself is loaded, so you would need to ensure the browser condition is set before even initiating SystemJS.

**Comment by unional** [comment]
Argh, you are right. I tested it by creating an actual `index.html` and it is working.

On the other hand, seems like still some work need to be done to make `browser-env` or `jsdomify` work correctly with `systemjs`, reference: https://github.com/systemjs/systemjs/issues/1528

I loaded `jsdomify` before `system.js` and `Error: relUrl is not defined` is thrown:

```sh
Error: relUrl is not defined
  Resolving npm-module
  Loading npm-module
    throwResolveError (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:7:48)
    resolveIfNotPlain (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:52:9)
    SystemJSLoader$1.coreResolve (node_modules/systemjs/src/resolve.js:195:26)
    node_modules/systemjs/src/resolve.js:268:34
```

Will close this and discuss the `jsdomify` issue at #1528.

Thanks again. 🌷 
Don't overwork. 😛

**Comment by guybedford** [comment]
This is an error message error - the error here is supposed to be: `Unable to resolve "/./plugins/npm-module/node_modules//./plugins/npm-module" to /`.

The problem being that the resolver is somehow getting the wrong baseURI / baseURL values. This may itself be a bug with this method of adjusting the SystemJS browser environment, meaning these may need to be fixed where they are set in the `common.js` source.

Hopefully that helps to track down further.

**Comment by guybedford** [comment]
(fixed the error message bug in https://github.com/ModuleLoader/es-module-loader/commit/2e44cef516c9317d19c072e18e016649a3c4d4b6, thanks)

**Comment by unional** [comment]
Yes indeed. For the record, here is the error:

```sh
Error: Unable to resolve "/./fixtures/npm-module/node_modules/nop/package.json" to /
  Resolving /./fixtures/npm-module/node_modules/nop/package.json
  Loading /./fixtures/npm-module/node_modules/nop/package.json
  Unable to fetch package configuration file /./fixtures/npm-module/node_modules/nop/package.json
  Resolving nop
  Loading nop
    throwResolveError (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:7:9)
    resolveIfNotPlain (node_modules/systemjs/node_modules/es-module-loader/core/resolve.js:52:9)
    SystemJSLoader$1.coreResolve (node_modules/systemjs/src/resolve.js:182:26)
    node_modules/systemjs/src/resolve.js:268:34
```
