### ISSUE TITLE
Version 0.19.46 to 0.20.7

### ISSUE THREAD

**Issue by Eagle94T** [systemjs/systemjs#1579]
Some changes since Version 0.20.0 broke down something that [this plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview) wan't work anymore.
This means, since Version 0.20.0 it's not possible to run AngularJS 2 anymore.

**Comment by kudoz83** [comment]
When I run that plunker I see "Hello Angular 2"

I'm interested in this because I've been struggling to get around this breaking change with my ng2 project...

> Default transpiler loading is removed. It is no longer possible to transpile sources without configuring one of the transpiler plugins.

**Comment by Eagle94T** [comment]
@kudoz83 You should see "Hello Angular 2" but if you change the version of systemjs to 0.20.7 or something between 0.20.0 and 0.20.7 and run it again, you will not see "Hello Angular 2" anymore but loading. This because it will not find main.ts anymore (but I don't know why, I'm new to angular 2)

**Comment by unional** [comment]
Have you tried to configure the transpiler? Check out `jspm` on how to do that?

**Comment by pumano** [comment]
I have same issue. Systemjs 0.19.46 works perfect when I provide node_modules as static and load them as:

`'@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js'`

but in 0.20.7 it's not working and platform-browser-dynamic return 404 error. 
When I investigate this, I found wrong path to module. '@' sign is absent in path
