### ISSUE TITLE
Support for IE11

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1580]
Reading the breaking changes in System 0.20, I see that "scriptLoad is only available for IE11".

However, I don't see any mention to the fact that we're now using fetch instead of xhr, whereas (according to CanIUse), IE11 doesn't support fetch.

Is there a feature detection logic somewhere that uses fetch only if supported?

**Comment by unional** [comment]
Based on the error message I got from #1581 , it seems like it will just fallback to xhr?

```sh
loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Instantiating file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Loading file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
  Unable to fetch package configuration file file:///Users/hwong/github/unional/some-issues/plugins/npm-module/package.json
```

**Comment by guybedford** [comment]
Yes exactly, XHR remains the fallback in https://github.com/systemjs/systemjs/blob/master/src/fetch.js#L131.

@amenadiel perhaps you can share the exact issue you're having here?

**Comment by amenadiel** [comment]
No issue at all, I asked out of curiosity. Haven't used IE since 2011, and even then it was only to check a broken layout.
