### ISSUE TITLE
Is it possible to load AMD via scriptLoad with v0.20+

### ISSUE THREAD

**Issue by mikecaines** [systemjs/systemjs#1583]
I have set `window.define = System.amdDefine`, and `scriptLoad:true` and `format:'amd'` in `meta`, however when `import()` is called, the module always resolves to an empty Object (not `undefined`, but `{}`). 

The modules themselves are AMD in the form of:
```
define(
  'some-name', 
  ['dep1', 'depN'], 
  function (Dep1, DepN) {
    return function MyConstructor() {};
  }
);
```
I essentially want the exact same behaviour as `system-csp-production.js` from v0.19.

**Comment by guybedford** [comment]
@mikecaines this may be an issue with the module names not lining up correctly. It's safer to load anonymous AMD - `define(['dep1', 'depN'], ...`. Otherwise the module name has to exactly match the loaded name when run through the resolver, which can be hard to always get right and maintain.

**Comment by mikecaines** [comment]
Thanks, that was indeed the source of the issue.
