### ISSUE TITLE
Format discovery regex does not support comments

### ISSUE THREAD

**Issue by EricABC** [systemjs/systemjs#1585]
This is a relatively minor issue that is resolved by providing the format, and is perhaps beyond the scope of module type detection.  I discovered this by using systemjs-builder on the latest @angular/angular 4.0.0-beta.7 .js source.  In @angular/forms/src/directives/error_samples.js:
```js
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */
/**
 * @license
 * Copyright Google Inc. All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://angular.io/license
 */ export var /** @type {?} */ FormErrorExamples = {
```
esmRegex does not match due to the comment end prior to the export.

The output is not likely as intended on the angular side (duplicate license comment), nonetheless I believe it is technically legal.

**Comment by guybedford** [comment]
Exactly, this is beyond the scope of detecting in SystemJS. Unfortunate
that this is in the Angular build though.

**Comment by EricABC** [comment]
I pulled npm fresh and it wasn't there anymore... either that or somehow I hit some accidental keystroke while I had it open.  Either way, specifying the module types to remove ambiguity seems like good practice anyway.

**Comment by guybedford** [comment]
Great, thanks for the update.
