### ISSUE TITLE
Aurelia import undefined after upgrade to 0.20

### ISSUE THREAD

**Issue by MaximBalaganskiy** [systemjs/systemjs#1588]
After upgrading to SystemJS 0.20 some imports coming from Aurelia modules are undefined. Exactly the same project works fine with 0.19. Here is a console output from the project

```
import {ValidationRules} from "aurelia-validation";
import * as v from "aurelia-validation";

export class App {
	constructor() {
		console.log(ValidationRules, v);
	}
}
```

![image](https://cloud.githubusercontent.com/assets/3712700/23050636/bca8cb70-f517-11e6-9f52-22e36e3cc371.png)

As far as I can judge, all exports are now chucked under `default` property.

The repro can be found here https://github.com/MaximBalaganskiy/systemjs_issue
To make the project work you will need to apply 2 patches
https://github.com/aurelia/loader-default/commit/a4607b97bfc2016e6feced5c04eb8259504b2efe
https://github.com/systemjs/systemjs/commit/5687daca61b7a4ec4e3134be132d03f05100d8ff#diff-f64cf64b83a0176d3c8ac2cc0963e63aR1112

**Comment by guybedford** [comment]
This change was in the release notes for SystemJS 0.20 and is exactly as you describe a correction to the NodeJS interop.

Use `import ValidationRules from 'aurelia-validation'` or use the following meta configuration to use the old behaviour:

```javascript
System.config({
  meta: {
    'npm:aurelia-validation@1.0.0-beta.1.0.1/aurelia-validation.js': { esModule: true }
  }
});
```

See the release notes for 0.20 for more info.

**Comment by MaximBalaganskiy** [comment]
Thanks. Both approaches work good with es6. With TS the first option does not work well. The reason is I use a "root" module which reexports all aurelia modules for import convenience. With 0.20 I have to now re-export variables and TS does not like this at all - cannot use those variables for declarations.

Second option works fine though even with TS.

**Comment by MaximBalaganskiy** [comment]
I was a bit too fast closing it :) Having implemented the second option with `meta` declaration I'm seeing the same problem in bundled application. Could you please advise?
