### ISSUE TITLE
depCache with css loader (0.20.8)

### ISSUE THREAD

**Issue by sgilligan** [systemjs/systemjs#1590]
Hi, 
I've migrated from 0.19.46 to 0.20.8 and found that previously depCache would work with css files configured to load via a css loader plugin. With 0.20.8 I'm finding the load no longer works. Is this because of the bug fix '.. depCache now uses link preloading instead of partial execution ..' and this can no longer be done? Or am I missing something?
Cheers

**Comment by guybedford** [comment]
Yes this support isn't yet covered in the 0.20 version. Let me see what we can do here.

**Comment by guybedford** [comment]
It might help as well if you could you perhaps describe how this is affecting your bootstrap process? Is it not adequate to have CSS load after execution of the initial scripts? Is CSS preloading as "executing" the CSS before the JS really still preloading?

**Comment by sgilligan** [comment]
Yes, perhaps I've been abusing depCache. I was using it to trigger the load of the related css module to a js module (ie importing the js component triggers the css import). I release this isn't really about load caching/optimisation. I've shifted the modules to a meta.dep and everything is now working.

Will close this as resolved! Thanks.
