### ISSUE TITLE
SystemJS 0.19.44 has hardcoded "scriptLoaded = false"

### ISSUE THREAD

**Issue by manishgarg1** [systemjs/systemjs#1592]
It seems like SystemJS 0.19.44 has hardcoded scriptLoad = "false". For our project we use scriptLoad as the default loading strategy. Is this by choice or a mistake ? If this is by choice, what is the reasoning behind it ?

  hook('fetch', function(fetch) {
    return function(load) {
      var loader = this;
      if (load.metadata.loaderModule && load.metadata.format != 'defined') {
        if (typeof load.metadata.loaderModule === 'function' || load.metadata.loaderModule instanceof Module && typeof load.metadata.loaderModule.default === 'function')
          return '';
        **load.metadata.scriptLoad = false;**
        if (load.metadata.loaderModule.fetch)
          return load.metadata.loaderModule.fetch.call(loader, load, function(load) {
            return fetch.call(loader, load);
          });
      }
      return fetch.call(loader, load);
    };
  });

**Comment by guybedford** [comment]
@manishgarg1 the above code only disables script load specifically for plugins. That shouldn't be breaking the script loading for non-plugins?
