### ISSUE TITLE
A light version of systemJS?

### ISSUE THREAD

**Issue by fchristant** [systemjs/systemjs#1593]
First, compliments to this library, it is fantastic and works very well.

However, I'm a performance tuning maniac, and noticed that the minified file is 46KB. I'm only using System.config (with base urls and paths) and calls to System.Import.

With those limited needs, would it be possible to have a lighter library? Or would it not make much of a difference?

**Comment by asapach** [comment]
Have you tried `system-production.js`? https://github.com/systemjs/systemjs#browser-production

**Comment by fchristant** [comment]
@asapach I did not know it existed until now. Nice, almost 3 times smaller and works fine. Thanks a lot!
