### ISSUE TITLE
registerDynamic() API doc is outdated

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1594]
https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjsregisterdynamicname--deps-declare
https://github.com/ModuleLoader/es-module-loader/blob/master/docs/system-register-dynamic.md#systemregisterdynamic

**Comment by guybedford** [comment]
Thanks I've updated the SystemJS docs.

**Comment by unional** [comment]
Is it possible to use `registerDynamic()` to force load a module in "global" format?

I have a case that my file is detected as AMD while it is actually global.

I want to do:
```ts
function importGlobal(identifier) {
  systemjs.registerDynamic(identifier, [identifier], true, (require, _exports, module) => {
    module.exports = require(identifier);
  })

  // these still load the file instead from registerDynamic above.
  return systemjs.import(identifier)
  return systemjs.import(systemjs.resolveSync(identifier)

  // these returns undefined
  return systemjs.get(identifier)
  return systemjs.get(systemjs.resolveSync(identifier)
```

**Comment by guybedford** [comment]
It would have to be `registerDynamic(systemjs.resolveSync(identifier), ...` then `System.import('identifier')` which should work then. But this wrapper approach can work equally well with a custom `System.set` and `System.newModule`

**Comment by unional** [comment]
Tried to use `systemjs.resolveSync(identifier)` but it seems like the `require()` does not read global namespace file as in `SystemJS.import()`.

```ts
const normalizedId = systemjs.resolveSync(identifier)
systemjs.registerDynamic(normalizedId, [normalizedId], true, (require, _exports, module) => {
  console.log(normalizedId) // prints 'file:///Users/.../<target.js>'
  console.log(require(normalizedId)) // prints '{}'
  module.exports = require(normalizedId)
})
```

The target.js is a global file, such as:

```js
window.My = { product: {} };

(function (ns) {
  ns.Component = { a: 1 }
})(window.My.product)
```

**Comment by guybedford** [comment]
If you configure the global with:

```javascript
System.config({
  meta: {
    'path/to/target.js': { exports: 'window.My.product' }
  }
});
```

Then you should get the populated value. newModule should also work.
