### ISSUE TITLE
Problems with modules which have NO default export (like immutable.js, moment.js)

### ISSUE THREAD

**Issue by lexon0011** [systemjs/systemjs#1597]
I have problems using modules which have no default exports (like immutable.js, moment.js, ...). In case of Moment I import Moment in my typescript project with the following statement: 
`import moment from "moment";`

Additionally I add the following config to the systemjs config:
```
"paths": {
   'moment': 'node_modules/moment/moment.js',
}
```
In fact the typescript compiler produces the following code : `moment_1.default`

- moment_1: contains the moment function, which was exported with module.exports = function () ...
- moment_1.default: is undefined, because no default export is specified in the moment.js 

Is it possible with systemjs to convert non es6 modules to es6 modules with exports.default equal to module.exports?

I tried the following additional configuration, but I doesn't change anything:
```
meta: {
    'node_modules/moment/moment.js': {
      format: 'esm', 
      esModule: true
}
```

**Comment by guybedford** [comment]
Are you running the TypeScript compile with the `allowSyntheticDefaultExports` option?

**Comment by lexon0011** [comment]
Yes I add the option `allowSyntheticDefaultExports`. I also asked the question to stackoverflow and now I have a working workaround: Look [here ](http://stackoverflow.com/questions/42267240/angular-aot-rollup-with-modules-which-have-no-default-export-like-immutable-js)
