### ISSUE TITLE
Public contributors from supporterhq

### ISSUE THREAD

**Issue by blittle** [systemjs/systemjs#1600]
Does SystemJS or jspm have some sort of public contributors page like [Webpack](https://opencollective.com/webpack?utm_campaign=webpack&utm_medium=github&utm_source=opencollective#contributors)? I'm willing to bet I could get my company to help sponsor SystemJS if it could be publicized.

**Comment by guybedford** [comment]
@blittle thanks for the consideration... we could definitely include a mention of primary sponsors in the readme. Would the existing donation mechanism work for you or would you need a tax invoice as well?

**Comment by blittle** [comment]
@guybedford I think it should be fine. I'll get back to you soon.
