### ISSUE TITLE
Illegal operation on a directory when loading module with no main in package.json

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1603]
Repro:
https://github.com/unional/issues/tree/systemjs-no-main

```sh
npm install make-error
```

```js
  const sys = new SystemJS.constructor()
  sys.config({
    baseURL: 'node_modules',
    packageConfigPaths: [
      '*/package.json',
      '@*/*/package.json'
    ]
  })
  await sys.import('make-error')
```

The `make-error` package.json does not specify 'main': https://github.com/JsCommunity/make-error/blob/master/package.json

When I trace it in `system.src.js: 3900`:

```js
SystemJSLoader$1.prototype.import = function () {
  console.log('importing', arguments)
  return RegisterLoader$1.prototype.import.apply(this, arguments)
  .then(function (m) {
    return m.__useDefault ? m.default: m;
  });
};
```

it prints:
```sh
importing { '0': 'make-error' }
importing { '0': 'file:///E:/.../node_modules/make-error/package.json' }
```

I notice the code in `system.src.js:2108`:

```js
    if (pkg.main)
      subPath = pkg.main.substr(0, 2) === './' ? pkg.main.substr(2) : pkg.main;
    // also no submap if key is package itself (import 'pkg' -> 'path/to/pkg.js')
    else
      // NB can add a default package main convention here
      // if it becomes internal to the package then it would no longer be an exit path
      return Promise.resolve(pkgKey);
```

Where the `pkgKey` is the path to the `make-error`, thus the error.

Should `subPath` default to `index` instead?

Or is there a way to specify that generically using `meta`? Something like

```js
sys.config({
  ...,
  meta: {
    '*': {
      main: 'index'
    }
  }
})
```

Or `packages`:
```js
sys.config({
  ...,
  packages: {
    '*': {
      main: 'index'
    }
  }
})
```

**Comment by unional** [comment]
I need to figure out a way to do this generically because I'm working on a plugin system so there is no way to know all dependent packages ahead of time and specify this for the package:

```js
sys.config({
  packages: {
    'make-error': {
      main: 'index'
    }
  }
}
```

In fact, I discover this issue when I was importing another package of mine and `make-error` is a two levels deep dependency.

**Comment by guybedford** [comment]
Yes there is no way to configure a default main rule. SystemJS is not going to grow into a full-featured Node loader - it's a browser loader first and foremost. Rather configuration techniques for SystemJS are where the focus should be I think.

**Comment by unional** [comment]
Is it possible to print out a nicer error message? I was away from this for 2 weeks and now when I come back to it, it takes me 2 hours to realize I got hit with the same issue again. 😛

**Comment by unional** [comment]
Also, noticed that this error is a "run-away" error:

```js
system.import('...').then(
  () => { console.log('then') },
  () => { console.log('other') }
)
```

no log is printed when this code is executed.

repro here: https://github.com/unional/domture/tree/ran-away-error

**Comment by unional** [comment]
Sorry, last comment is noise. It is an issue with jsdom.
I have commented about this on another thread: https://github.com/tmpvar/jsdom/issues/1579

**Comment by unional** [comment]
FYI, `make-error` has fixed this issue. To repro, try `ascii-table`
