### ISSUE TITLE
production distribution with defaultExtension

### ISSUE THREAD

**Issue by mpfau** [systemjs/systemjs#1606]
We are using the following system configuration during build and when bundling with systemjs-builder:
``` js
{
  "packages": {"./src": {"defaultExtension": "js"}},
}
```
However, the packages configuration is not supported by the production dist of systemjs. How can we use the production dist with defaultExtension? 

Alternatively: Is there a way to tell the builder during bundling to append the defaultExtension to all paths?

**Comment by guybedford** [comment]
@mpfau seamless tooling around the production loader is a work in progress, for now custom solutions are the best approach still unfortunately (or just explicitly specifying the extension).

**Comment by mpfau** [comment]
@guybedford ok, thanks for confirming!

I think we will start with system.js and switch to system-production.js at a later time.
