### ISSUE TITLE
CSS requires not loaded in order

### ISSUE THREAD

**Issue by JeffBaumgardt** [systemjs/systemjs#1607]
Hi guys (Guy) I'm having a small issue since 17 beta 33 - 40. I have a styles.js file which requires several css files to be loaded. In my case I load jqueryUI styles and then my template file. But what I am seeing is that the order does not matter when loading these files the template always is loaded before the base so I lose all my custom templates.

This worked in beta 32 with no issues ever since beta 33 it has stopped working

```js
// Group 1: Normalization
require('normalize.css/normalize.css!')
// Group 2: Libraries
require('font-awesome/css/font-awesome.css!')
require('jquery-ui/themes/base/jquery-ui.css!')
// Group 3: App Base
require('./jquery-ui-theme.css')
require('./app.css')
```

I know requires technically do not expect order but can anyone see why it would load in an incorrect order when added to the document?

**Comment by guybedford** [comment]
@JeffBaumgardt if you want to investigate further it should be possible to track this from within the CSS plugin hooks at https://github.com/systemjs/plugin-css/blob/master/css.js#L84 to ensure that the fetch calls are being called in order. It may be something we can correct in either the plugin or the loader, unfortunately it's difficult for me to allocate resources into looking into this right now.

**Comment by JeffBaumgardt** [comment]
It is indeed loading out of order.

In the load it is pulling the first relative path first vs the package css files as shown above.

In my group 3 which should be loaded last is loaded first. I can only assume that it's because all the files here are relatively pathed. If I randomize the requires all the relative paths still load first before package files.

The problem is that with load order out of order the overrides in our custom jqueryui theme get overridden by the lib. 

I'm sorry I don't much about css loader very much and the call stack ends with the export so I don't have any more details.

**Comment by guybedford** [comment]
I have created https://github.com/systemjs/plugin-css/issues/128 with a possible approach towards implementing this. I don't have time to work on it, but if anyone else does, or wants to sponsor it please just let me know.
