### ISSUE TITLE
Errror installing systemjs with Angular

### ISSUE THREAD

**Issue by jrmcdona** [systemjs/systemjs#1608]
Hello!  I am getting dependency errors. See the screenshot.

What I am trying to do i use System.Config in a karma shim JS file.  Is there anyway to import the SystemJS directly into the file instead of installing using npm since I am have dependency errors?  Thanks

![image](https://cloud.githubusercontent.com/assets/4327773/23532979/65f21d1a-ff74-11e6-98ed-7a3411b98ea0.png)

**Comment by michaelsanford** [comment]
angular2, rxjs and zone [are not peer dependencies of systemjs](https://github.com/systemjs/systemjs/blob/master/package.json), so you probably have a `package.json` file in that folder which specifies some other packages who have those as peer dependencies.

Reproducing in a completely blank folder, after `npm init` ed with all default values:

```
λ npm i systemjs
system@1.0.0 \test\system
`-- systemjs@0.20.9

npm WARN system@1.0.0 No description
npm WARN system@1.0.0 No repository field.
```
No such warning.

**Comment by jrmcdona** [comment]
Thanks
