### ISSUE TITLE
__moduleName in bundles

### ISSUE THREAD

**Issue by soulcorrosion** [systemjs/systemjs#1612]
Hello, I'm using systemjs 0.19.46.
I have the following config for a bundle.

```javascript
System.config({
   packages : {
        'node_modules': {
                format: 'register',
               defaultExtension: 'js'
         }
   } ,
   bundles : {
          "node_modules/company/src/bundle.js" : ["company/src/component1/component1",                "company/src/component2/component2"]
    }
});
```
If I try to get the "__moduleName" var to do relative paths on Angular2, I get "http://localhost:8001/company/src/component/component" without the "node_modules". Without "node_modules" I won't have a valid path for getting an angular component view (html) or css.

Is there some config I'm missing?

**Comment by guybedford** [comment]
Perhaps try the following configuration in the browser:

```javascript
System.config({
  paths: {
    'company/': 'node_modules/company/'
  }
  bundles: {
    'company/src/bundle.js': ['company/src/component1/component1']
  }
});
```

The reason being that the `__moduleName` is relative to the module it is contained in - `company/src/component1/component1`, so we need to ensure the name in the bundle resolves to the correct URL for dynamic loading.

**Comment by winpzs** [comment]
System.config({
  paths: {
    'company/': 'node_modules/company/'
  }
  bundles: {
    'company/src/user-bundle.js': ['company/src/user/**']
  }
});
工程文件超多，可以这样用吗？

**Comment by soulcorrosion** [comment]
@guybedford thanks for the answer, however I couldn't get it to work. The paths config takes over and I get requests for indivisual files instead of the bundle.
I tried using a wilcard, like "company/src/component1/*" instead of the whole module name and in this case I got the bundle but then all individual files were requested as well.

**Comment by guybedford** [comment]
To match up the names of the modules in the bundle, ensure that `System.resolveSync('name-defined-in-bundle')` matches `System.resolveSync('name-defined-in-bundles')` (`bundles: { 'x': ['name-defined-in-bundles] }`).
