### ISSUE TITLE
registry is undefined in System.registry.get("@@global-helpers")

### ISSUE THREAD

**Issue by mkariti** [systemjs/systemjs#1613]
Hi there,
Ive compiled my angular2 app via gulp and I get the following error:
(SystemJS) Cannot read property 'get' of undefined
For some reason the .registry is undefined .
Any idea?

**Comment by guybedford** [comment]
SystemJS 0.20 uses the `System.registry.get` API, while 0.19 used `System.get`. If you're using SystemJS builder, make sure you're using version 0.16 for SystemJS 0.20, and version 0.15 for SystemJS 0.19.

**Comment by mkariti** [comment]
work like a charm! Thank you.
However, now im facing the following error:
EXCEPTION: Error in :0:0 caused by: The selector "myapp-app" did not match any elements
Will appreciate any input on this one as well.
