### ISSUE TITLE
Error: Module ....  detected as amd but didn't execute correctly.

### ISSUE THREAD

**Issue by RoyiNamir** [systemjs/systemjs#1615]
I have a very simple basic code .

When using System.js v 0.19.31  ( plunker : http://plnkr.co/edit/aKMjhaDS76ULtbOp8kws?p=preview)

It seems that things are working fine.

However , moving towards the latest version of system.js :  ( and here is the plunker : http://plnkr.co/edit/rkHlRcUTVsQjkYC0to6g?p=preview) - shows an werror  

Error Image : 

https://i.imgur.com/7Yj7w4g.jpg

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/issues/1587#issuecomment-287013920.
