### ISSUE TITLE
Trying override locate for cache busting and solve issue

### ISSUE THREAD

**Issue by msmolka** [systemjs/systemjs#1616]
Hello
I'm still on version 0.19. I cannot migrate to version 0.20 because of issue #1575.
I tried to not use paths for that, but overriding locate function

```javascript

var systemLocate = System.locate;

        System.locate = function (load) {
            return Promise.resolve(systemLocate.call(this, load)
                .then((url): string => {                 
                    if (url.indexOf("/kendo.culture.") > 0) {
                        url = url.replace("/kendo.culture.", "/lib/kendo/cultures/kendo.culture.")                    
                        return (`${url}.js?ver=${self.versionNumber}`);
                    } else if (url.indexOf("/kendo.") > 0) {
                        url = url.replace("/kendo.", "/lib/kendo/kendo.")                      
                        return (`${url}.js?ver=${self.versionNumber}`);
                    } else {
                        return (`${url}?ver=${self.versionNumber}`);
                    }

                }));
        };

```
Hover I've notice after update version this method is not called any more. So How can I cache bust in version 0.20 and override locate function?

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/issues/172#issuecomment-278565952 for a SystemJS 0.20 approach. If this doesn't work for you just let me know.

**Comment by msmolka** [comment]
@guybedford when I add:

```javascript
        let resolve = System[System.constructor.resolve];

        System[System.constructor.resolve] = function (key:string, parentKey:string) {
            return resolve.call(this, key, parentKey).then(function (url: string) {
                console.log(url);
                return url;
            });
        };
```
All is working
However after adding:
```javascript
return url + '?cache';
```
I have error
```
Error: metadata is undefined
  Instantiating http://localhost:55876/js/login.js?cache
  Loading login
  system.src.js:3239
```

**Comment by guybedford** [comment]
Ahh, yes that would be an issue. I'm not sure what we can do to make this work then actually...

**Comment by msmolka** [comment]
Implement maybe Cache Busting internally like advised in #172 (comment) ?

**Comment by msmolka** [comment]
@guybedford I've tried to solve issue. And at this moment the only thing working is add custom code inside `fetchFetch` function just before return. So allowing override that would solve cache busting and custom resolve while path wildcards are no longer possible.

```javascript
  console.log(url);
    if (url.indexOf("/kendo.culture.") >= 0) {
        url = url.replace("/kendo.culture.", "/lib/kendo/cultures/kendo.culture.") + ".js";
    } else if (url.indexOf("/kendo.") >= 0) {
        url = url.replace("/kendo.", "/lib/kendo/kendo.") + ".js";
    }
    console.log(url);

```

**Comment by guybedford** [comment]
Someone reported that the following code can work here:

```javascript

var buildNo = "build=" + Date.now().toString(36);
//SystemJSLoader$1 -> RegisterLoader$1 -> Loader
var Loader = System.__proto__.__proto__.__proto__.constructor;
var loaderResolve = Loader.prototype.resolve;
 
function augment(key) {
    if (key.indexOf(buildNo) > 0) {
        //key already augmented.
        return key;
    }
 
    var hI = key.indexOf("#"), qI = key.lastIndexOf("?", hI < 0 ? undefined : hI);
    if (qI > 0) {
        if (hI > 0) {
            //? and # found: put build between ? and #
            key = key.slice(0, hI) + "&" + buildNo + key.slice(hI);
        } else {
            //? found: put build at end
            key += "&" + buildNo;
        }
    } else {
        //no ? nor #
        key += "?" + buildNo;
    }
    return key;
}
 
var metadataSymbol;
function getMetadataSymbol(loader, mustFindKey) {
    if (metadataSymbol) {
        return metadataSymbol;
    }
    if (loader["@@metadata"]) {
        //some browsers dont support Symbol()
        return metadataSymbol = "@@metadata";
    }
    var symbols = Object.getOwnPropertySymbols(loader);
    for (var i = 0; i < symbols.length; i++) {
        var s = symbols[i], lov = loader[s];
        if (lov && typeof lov === 'object' && lov[mustFindKey]) {
            return metadataSymbol = s;
        }
    }
    throw new Error("I tried.");
}
 
Loader.prototype.resolve = function hackedLoaderResolve() {
    var loader = this;
    return Promise
            .resolve(loaderResolve.apply(loader, arguments))
            .then(function (key) {
                var newKey = augment(key);
                if (newKey !== key) {
                    var metaSymbol = getMetadataSymbol(loader, key);
                    var metadata = loader[metaSymbol];
                    var moveMe = metadata[key];
 
                    if (moveMe) {
                        delete metadata[key];
                        metadata[newKey] = moveMe;
                    }
                }
                return newKey;
            });
};/**/
```

It's a little sad the code requires such a hack though. The above also needs another hack for plugins to work as well.

Ideally this should definitely be easier to implement.

**Comment by ViceIce** [comment]
My solution is to use a custom loader:
```typescript
function locate(load) {
  return load.address + "?ctag=" + VO.Context.clientTag;
}
System.registry.set("vo-loader", System.newModule({ locate: locate }));
System.config({
  meta: {
    "VO*": {
      format: "amd",
      loader: "vo-loader"
    }
}
```

**Comment by errorx666** [comment]
@ViceIce That's the most elegant solution I've seen so far.

**Comment by errorx666** [comment]
@guybedford I ended up using this hack, but I'm worried that it's going to break because it's not using public APIs.

**Comment by sod** [comment]
As this issue is still open I'd like to add my horrible sledgehammer solution

```javascript
var version = 1;

window.fetch && (window.fetch = (function(fetch) {
    return function (url, options) {
        return fetch.call(this, url + '?version=' + version, options);
    }
}(window.fetch)));
```

**Comment by errorx666** [comment]
@sod This affects all AJAX calls with fetch, not just System, and breaks on URLs that already have query strings.

**Comment by mreiche** [comment]
@ViceIce That doesn't work for me anymore. 

```
Uncaught TypeError: Cannot read property 'set' of undefined
```

**Comment by ViceIce** [comment]
@mreiche Did you load systemjs? You have to load it before.

**Comment by msmolka** [comment]
I think, it is easy solvable inside SystemJS itself, but quite difficult outside. It should be build in. 
I'm using @guybedford solution, and it is working very well for me, but looks verbose, to simply add busting suffix.

**Comment by mreiche** [comment]
@msmolka Me too. His solution for SystemJS 0.20 works well for SystemJS 0.19 too.

**Comment by msmolka** [comment]
@guybedford I believe this is closed because of SystemJS 2.0 but is ti supported there?

**Comment by guybedford** [comment]
@msmolka yes, resolve hooking is much simpler now:

```js
const systemResolve = System.resolve;
System.resolve = async function (id, parent) {
  const resolved = await systemResolve.call(this, id, parent);
  return resolved + '?cache=' + Date.now();
};
```

(note, as usual untested outline approach :P)

This could be easily packaged up into a "drop-in" extra if anyone wants to provide that and list it in the readme.

**Comment by vitorhsb** [comment]
> Someone reported that the following code can work here:
> 
> ```js
> var buildNo = "build=" + Date.now().toString(36);
> //SystemJSLoader$1 -> RegisterLoader$1 -> Loader
> var Loader = System.__proto__.__proto__.__proto__.constructor;
> var loaderResolve = Loader.prototype.resolve;
>  
> function augment(key) {
>     if (key.indexOf(buildNo) > 0) {
>         //key already augmented.
>         return key;
>     }
>  
>     var hI = key.indexOf("#"), qI = key.lastIndexOf("?", hI < 0 ? undefined : hI);
>     if (qI > 0) {
>         if (hI > 0) {
>             //? and # found: put build between ? and #
>             key = key.slice(0, hI) + "&" + buildNo + key.slice(hI);
>         } else {
>             //? found: put build at end
>             key += "&" + buildNo;
>         }
>     } else {
>         //no ? nor #
>         key += "?" + buildNo;
>     }
>     return key;
> }
>  
> var metadataSymbol;
> function getMetadataSymbol(loader, mustFindKey) {
>     if (metadataSymbol) {
>         return metadataSymbol;
>     }
>     if (loader["@@metadata"]) {
>         //some browsers dont support Symbol()
>         return metadataSymbol = "@@metadata";
>     }
>     var symbols = Object.getOwnPropertySymbols(loader);
>     for (var i = 0; i < symbols.length; i++) {
>         var s = symbols[i], lov = loader[s];
>         if (lov && typeof lov === 'object' && lov[mustFindKey]) {
>             return metadataSymbol = s;
>         }
>     }
>     throw new Error("I tried.");
> }
>  
> Loader.prototype.resolve = function hackedLoaderResolve() {
>     var loader = this;
>     return Promise
>             .resolve(loaderResolve.apply(loader, arguments))
>             .then(function (key) {
>                 var newKey = augment(key);
>                 if (newKey !== key) {
>                     var metaSymbol = getMetadataSymbol(loader, key);
>                     var metadata = loader[metaSymbol];
>                     var moveMe = metadata[key];
>  
>                     if (moveMe) {
>                         delete metadata[key];
>                         metadata[newKey] = moveMe;
>                     }
>                 }
>                 return newKey;
>             });
> };/**/
> ```
> 
> It's a little sad the code requires such a hack though. The above also needs another hack for plugins to work as well.
> 
> Ideally this should definitely be easier to implement.

Tried to use @guybedford hack code above but it was not working for me, bundles from jspm.config were not correctly loaded and in the end an error was thrown.

Did a little digging and finally got it working by ignoring files in bundles or special keys from systemjs itself. Leaving the modified code below for others with the same issue.

```
function isBundled(key) {
    var bundles = System.getConfig().bundles || [];

    for (var i = 0 in bundles) {
        var b = bundles[i];
        if (b.indexOf(key) > -1) {
            return true;
        }
    }

    return false;
}

var ignoreLoaderResolveKeys = ['@system-env', '@empty'];
function shouldIgnoreCustomResolver(key) {
    return ignoreLoaderResolveKeys.indexOf(key) > -1;
}

function augment(key) {
    if (key.indexOf(buildNo) > 0 || isBundled(key) || shouldIgnoreCustomResolver(key)) {
        // key already augmented or should be ignored.
        return key;
    }

    ...
}
```
