### ISSUE TITLE
Dependencies not loaded before the requested module

### ISSUE THREAD

**Issue by martinsik** [systemjs/systemjs#1617]
I have a single file with a couple of `amd` modules:

```
define("partA", ["require", "exports"], function (require, exports) {
    ...
});
define("partB", ["require", "exports"], function (require, exports) {
    ...
});
define("partC", ["require", "exports"], function (require, exports) {
    ...
});
define("bundle", ["require", "exports", "partA", "partB", "partC"], function (require, exports, partA_1, partB_1, partC_1) {
    "use strict";
    console.log('bundle loaded');
    exports.partA = partA_1.partA;
    exports.partB = partB_1.partB;
    exports.PartC = partC_1.PartC;
});
```

The config description says https://github.com/systemjs/systemjs/blob/master/docs/config-api.md:

> `deps`: Dependencies to load before this module. Goes through regular paths and map normalization. Only supported for the `cjs`, `amd` and `global` formats.

So I thought I can import for example `partA` as follows:

```
SystemJS.config({
  meta: {
    'partA': {
      deps: [ 'bundle' ],
    }
  },
  map: {
    'bundle': 'bundle.js',
  }
});

SystemJS.import('partA').then(function(m) {
  console.log(m);
});
```

But this doesn't work because SystemJS tries to load `partA` instead of loading `deps` first.

However I can manually specify to load `bundle` fist and then `partA` that works as should:

```
SystemJS.import('bundle').then(function(m) {
   SystemJS.import('partA').then(function(m) {
     m.partAFunc();
  });
});
```

Demo: http://plnkr.co/edit/gUAtqbmCZarFjVzfPgRG

**Comment by guybedford** [comment]
Try using the following configuration here:

```javascript
SystemJS.config({
  meta: {
    'partA': {
      deps: [ 'bundle' ],
    }
  },
  map: {
    'bundle': 'bundle.js',
  },
  bundles: {
    'bundle.js': ['partA']
  }
});

SystemJS.import('partA').then(function(m) {
  console.log(m);
});
```

That achieves the same thing as your custom System.import nesting.

**Comment by martinsik** [comment]
You're right, it didn't occur to me that I can use AMD modules for `bundles` from the description in the documentation.

**Comment by ArtixZ** [comment]
It's really confusing. Why we need to config deps and bundles twice for the same purpose.
