### ISSUE TITLE
Docs missing description for 'production'

### ISSUE THREAD

**Issue by bulldetektor** [systemjs/systemjs#1618]
There's a link to [production](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#production) in the Configuration API, but the section is missing. What does the 'production' property actually do?

**Comment by guybedford** [comment]
Thanks I've removed the link now. This feature is slowly being deprecated.

This provides two features in SystemJS - conditional loading and also the ability to have production specific configs that get turned on in the production mode.
