### ISSUE TITLE
getConfig() from system-production.js

### ISSUE THREAD

**Issue by mpfau** [systemjs/systemjs#1619]
@guybedford `getConfig()` is currently not available for the production build of systemjs (commented out). Is there any special reason for this?

We need the configuration to pass it on to a worker which should behave the same as the main process...

**Comment by guybedford** [comment]
I guess I was trying to keep the production loader size overhead down, but agreed this is a good feature to keep. Uncommented in https://github.com/systemjs/systemjs/commit/2f9583fb29b544552e2b559511865e410f4453b6.

**Comment by guybedford** [comment]
Released in 0.20.10.

**Comment by mpfau** [comment]
@guybedford the production loader in 0.20.10 does not work anymore because cloneArrays is undefined (https://github.com/systemjs/systemjs/blob/2f9583fb29b544552e2b559511865e410f4453b6/src/systemjs-production-loader.js#L196).

**Comment by guybedford** [comment]
Ah, I've added a fix in https://github.com/systemjs/systemjs/commit/7b1807560e401fb1d5a2e18dd777ede95c242ad9 for the next release.

**Comment by mpfau** [comment]
Thanks! :-)
