### ISSUE TITLE
@empty resolves to absolute url with system-production.js

### ISSUE THREAD

**Issue by mpfau** [systemjs/systemjs#1620]
With the production loader, `System.resolve("@empty")` resolves to an absolute url (e.g. http://localhost:9000/beta/client/@empty).

The dev distribution (`system.js`) resolves to @empty, as expected.

**Comment by guybedford** [comment]
Great catch, I've fixed this in https://github.com/systemjs/systemjs/commit/234f92006104f07775e7d8db51c6a4039e58fbe3.

**Comment by guybedford** [comment]
Released in 0.20.10.
