### ISSUE TITLE
@node import fails in electron app when baseURL/path contains spaces

### ISSUE THREAD

**Issue by timfish** [systemjs/systemjs#1621]
I changed my `require()` references to `@node` imports in my electron app and now it's failing to load them when the app is located in `Program Files`. When I change them back to `require()` the issue is resolved. 

I had assumed `@node` references would simply call `require`, but there is something about the permissions in `Program Files` and electron which is stopping this from working.

There are no issues with both test and production builds until they're located in `c:\Program Files` on Windows 10, when it fails with:

```
(SystemJS) Cannot find module 'serialport'
	Error: Cannot find module 'serialport'
	    at Module._resolveFilename (module.js:455:15)
	    at Function.Module._resolveFilename (C:\Program Files\Company Name\AppName\resources\electron.asar\common\reset-search-paths.js:35:12)
	    at Function.Module._load (module.js:403:25)
	    at Module.require (module.js:483:17)
	Error loading file:///C:/Program%20Files/Company%20Name/AppName/resources/app.asar/dist/devices/dal/serial/node-serial.js as "./dal/serial/node-serial" from file:///C:/Program%20Files/Company%20Name/AppName/resources/app.asar/dist/devices/device-manager.js
```

If I take my working build output directory and copy it into `C:\Program Files\Company Name\AppName\`, I get the above error too so I know its not an installer issue.

I also tried disabling `asar` packing to see if that was the cause. Again the app works correctly until it's located within the `Program Files` directory.

Any ideas how I can resolve this without reverting to using `require` for all my native references?

**Comment by guybedford** [comment]
Where is the `serialport` module located?

The process SystemJS is using to load the modules is the following:

```javascript
// (if necessary - var require = System._nodeRequire)
var Module = require('module');
var base = System.baseURL.substr(isWindows ? 8 : 7);
var parentModuleContext = new Module(base);
parentModuleContext.paths = Module._nodeModulePaths(base);
parentModuleContext.require(key);
```

You can perhaps try that manually in your source - perhaps the `parentModuleContext.paths` assignment isn't detecting the location that contains `serialport`. Let me know how it goes.

**Comment by timfish** [comment]
Thanks Guy, I'll dig a bit deeper and see what I find..

 `serialport` is in `node_modules` at 
`C:/Program Files/Company Name/AppName/resources/app.asar/node_modules`

**Comment by guybedford** [comment]
Did you make any progress here?

**Comment by timfish** [comment]
I'll have another look today. I did notice that when I tried SystemJS in the main node process `@node/x` worked as its supposed to, so this appears to only be an issue in the render process.

**Comment by timfish** [comment]
That code fails too when under `Program Files` 

So, the following code:
```typescript
var Module = require('module');
var base = System.baseURL.substr(8);
console.log(base);
var parentModuleContext = new Module(base);
parentModuleContext.paths = Module._nodeModulePaths(base);
console.log(parentModuleContext.paths);
var sp = parentModuleContext.require('serialport');
console.log(sp);
```

Outputs the following in my Documents:
```
C:/Users/tim/Documents/Repos/app-workingcopy/releases/win-unpacked/resources/app.asar/
[
    "C:\Users\tim\Documents\Repos\app-workingcopy\r…ases\win-unpacked\resources\app.asar\node_modules", 
    "C:\Users\tim\Documents\Repos\app-workingcopy\releases\win-unpacked\resources\node_modules"
]
function SerialPort(path, options, callback) {
```

Outputs the following when under `Program Files`:
```
C:/Program%20Files/Company%20Name/win-unpacked/resources/app.asar/
[
    "C:\Program%20Files\Company%20Name\win-unpacked\resources\app.asar\node_modules",     
    "C:\Program%20Files\Company%20Name\win-unpacked\resources\node_modules", 
    "C:\Program%20Files\Company%20Name\win-unpacked\node_modules", 
    "C:\Program%20Files\Company%20Name\node_modules",
    "C:\Program%20Files\node_modules", 
    "C:\node_modules"
]
Error: (SystemJS) Cannot find module 'serialport'(…)
```

In both cases, the `serialport` module should be found in `app.asar\node_modules`

**Comment by timfish** [comment]
I have noticed that the `Program Files` one has escaped spaces in the paths whereas the one in my documents does not.

**Comment by guybedford** [comment]
Ah, thanks for hunting this down further! So I guess we should be using:

```javascript
var Module = require('module');
var base = decodeURI(System.baseURL.substr(8));
console.log(base);
var parentModuleContext = new Module(base);
parentModuleContext.paths = Module._nodeModulePaths(base);
console.log(parentModuleContext.paths);
var sp = parentModuleContext.require('serialport');
console.log(sp);
```

here rather. I've added a patch in 846535858 along these lines... will catch this in the next cycle next week after some more testing.

**Comment by scse972** [comment]
It's a problem of http in windows, not a bug in fact. You have to manage le name of directory when a page is loaded with space by replacing them with %20 value: for example: 

win.loadFile(path.join(__dirname,'/src/index.html')) doesn't work if __dirname contain space because in http space is %20

you have to use:
win.loadFile(path.join(__dirname.replaceAll(' ','%20'),'/src/index.html')) if you want to  load a page
