### ISSUE TITLE
0.19 => 0.20 Breaking Change and SEMVER

### ISSUE THREAD

**Issue by Izzmo** [systemjs/systemjs#1623]
Anyone have a reason why the update from 0.19 to 0.20 was a breaking change and the minor revision was changed instead of the major? This seems to be a total lack of foresight and breaks implementations.

_I don't think the beta moniker applies, either._

**Comment by guybedford** [comment]
For semver versions with a major version zero, breaking changes are permitted. The release notes document the changes at https://github.com/systemjs/systemjs/releases/tag/0.20.0. Note that if your package.json dependency contains `systemjs: "^0.19.0"` then you won't be opted into the upgrade through the package manager.

**Comment by Izzmo** [comment]
@guybedford thanks for the quick reply!

We are using bower with `"system.js": "^0.19.38"` but is still updating it to 0.20.x anyways. Could this be an issue with bower possibly?

**Comment by guybedford** [comment]
Yes that's an incorrect implementation of the `^` version constraint.

**Comment by Izzmo** [comment]
@guybedford hmm interesting. Maybe it's a sign to kick bower to curb, too :P

Thanks again.
