### ISSUE TITLE
Unify `browserConfig` and `nodeConfig` paths resolving

### ISSUE THREAD

**Issue by ArmorDarks** [systemjs/systemjs#1624]
Hello

Recently we've found, that `browserConfig` and `nodeConfig` paths resolving works completely differently, and it is very confusing.

For instance, in this example it is completely unobvious that paths will resolve in same way, as for `nodeConfig`.

```js
SystemJS.config({
  baseURL: "source/scripts",
  paths: {
    "npm:": "jspm_packages/npm/",
    "github:": "jspm_packages/github/",
    "app/": "source/scripts/"
  },
  ...
```

In next instance, it is also unclear, that due to introduced `browserConfig` path resolution will work _once again_ completely different, not to mention that we have confusing format differences: for `baseUrl` we don't use any leading `/` to define a root, but for `browserConfig` paths we do:

```js
SystemJS.config({
  baseURL: "source/scripts",
  browserConfig: {
    paths: {
      "npm:": "/jspm_packages/npm/",
      "github:": "/jspm_packages/github/",
      "app/": "/source/scripts/"
    },
  },
  ...
```

This leads to often situation when you have to repeat almost similar configs only to fix those path resolving differences:

![sublime_text_2017-03-18_22-32-09](https://cloud.githubusercontent.com/assets/4460311/24075790/c7c6098a-0c2a-11e7-9f63-c681962eef87.png)

I think this could be improved by following this clear pattern in _all_ cases:

1. All paths without leading `/` should resolve relatively to `baseUrl`
2. All relative paths like `./` or `../` should try to resolve relatively to `baseUrl`.

   This is the only difference between Node and Browser configs — for Node it will try to resolve infinitely until root of the project, but for Browser it can't go upper than location root.

3. All absolute paths with leading `/` or `<rootDir>/` should resolve to root, ignoring `baseUrl`

This will allow to write much cleaner configs without need to repeat paths. For example, right now due to path resolving differences you can be more flexible in `browserConfig`, but not in `nodeConfig`:

```js
SystemJS.config({
  baseURL: "source/scripts",
  browserConfig: {
    paths: {
      "npm:": "/jspm_packages/npm/",
      "github:": "/jspm_packages/github/",
      "app/": "" // we don't need to repeat `baseURL` value here, it will resolve relatively
    },
  },
  nodeConfig: {
    paths: {
      "npm:": "jspm_packages/npm/", // it isn't clear that it won't resolve relatively...
      "github:": "jspm_packages/github/",
      "app/": "source/scripts" // we have to repeat `basUrl` here, because we don't have relative resolving
    },
  },
  ...
```

I think that `browserConfig` and `nodeConfig` should be leaved exclusively for cases, when you need to declare really different paths for specific packages, but not to solve shown above paths resolving ambiguity.

So ideally, we'd want to write configs like so:

```js
SystemJS.config({
  baseURL: "source/scripts",
  paths: {
    "npm:": "/jspm_packages/npm",
    "github:": "/jspm_packages/github",
    "app/": "myScripts"
  },
  browserConfig: {
    paths: {
      "app/": "specifcScripts" // this is intentional override for browsers environment
    },
  },
  ...
```

**Comment by ArmorDarks** [comment]
I also think that in context of this proposal it worth to change `baseUrl` to `root` or `rootDir`m since it very misleading when used in context of Node.

And finally, it worth to make it part of `paths` object.

It will produce very fluent and easy to read configs:

```js
SystemJS.config({
  paths: {
    "root": "source/scripts",
    "npm:": "/jspm_packages/npm", // this and all others are relative to `paths.root`
    "github:": "/jspm_packages/github",
    "app/": "myScripts"
  },
  browserConfig: {
    paths: {
      "root": "assets", // we decided to override root for browsers
      "app/": "specifcScripts" // this is intentional override for browsers environment
    },
  },
  ...
```

**Comment by guybedford** [comment]
> All paths without leading / should resolve relatively to baseUrl

This is already the case.

> All relative paths like ./ or ../ should try to resolve relatively to baseUrl.

Due to compatibility with browser modules, relative paths at the top-level always resolve relative to the baseURI, which is environment specific and different to the baseURL. This distinction can be confusing I know, but the baseURL is the ability to set a custom path for "plain names". Perhaps baseURL should be aliased plainBaseURL...

> All absolute paths with leading / or <rootDir>/ should resolve to root, ignoring baseUrl

Again these resolve relative to baseURI, just like ./-style paths.

The trailing slash on paths is necessary to indicate folder paths over file paths. Also in the `npm:` case this provides an indicator that we should not add a trailing slash to the resolution process to get `npm:/`.

Perhaps if baseURL were instead called `plainBase` or similar it would also make more sense in the package.json context, I agree this is confusing, it just has direct lineage from requireJS and the loader spec, so kept the name.
