### ISSUE TITLE
0.20.10 not honoring package.json defaultExtension

### ISSUE THREAD

**Issue by AlbertWillemsen-Centric** [systemjs/systemjs#1625]
Trying to load an external package with defaultExtension in jspm object set to "ts".
Still tries to load everything with .js extension.

**Comment by AlbertWillemsen-Centric** [comment]
Under Node it seems packageConfigPaths is broken. In getPackageConfigMatch the normalized name is the full path of the package: C:/package/ instead of "local:package.json". This will never be matched an so the package.json will never be loaded. So main, format and defaultExtension are ignored.

**Comment by AlbertWillemsen-Centric** [comment]
changing line 1734 from:
relativeResolved = resolveIfNotPlain(key, baseURI);
to
return relativeResolved = resolveIfNotPlain(key, baseURI);
gives the desired effect, but it wil not load the package.json as a json file.

**Comment by AlbertWillemsen-Centric** [comment]
If I add 	
```
packageConfigPaths: [
		"jspm_packages/github/*/*.json",
		"jspm_packages/npm/@*/*.json",
		"jspm_packages/npm/*.json",
		"jspm_packages/local/*.json"
]
```
to the node config it seems to work.
also because of this it wil not resolve the packages object.
for example:
```
  packages: {
    "npm:typescript@2.2.1": {
      "map": {
        "source-map-support": "npm:source-map-support@0.4.14"
      }
    },
    "npm:source-map-support@0.4.14": {
      "map": {
        "source-map": "npm:source-map@0.5.6"
      }
    },
```
if i add them to map:
```
map: {
    "plugin-typescript": "github:frankwallis/plugin-typescript@7.0.5",
    "typescript": "npm:typescript@2.2.1",
	"source-map-support": "npm:source-map-support@0.4.14",
	"source-map": "npm:source-map@0.5.6"
```
they are found.

This doesn't seem correct.

**Comment by guybedford** [comment]
Package configuration is normalized to URLs by the configuration call. This can be checked by looking at the values in `System.getConfig()`. Normalized names are normalized URLs internally. Perhaps that will help to debug this further?

**Comment by AlbertWillemsen-Centric** [comment]
latest 0.20.18 version seems to fix this issue.
