### ISSUE TITLE
Sporadic `Cannot read property 'linkRecord' of undefined` errors when nesting System.import

### ISSUE THREAD

**Issue by ghempton** [systemjs/systemjs#1626]
In our automated test suite using System.js 0.20.10 we see this error very sporadically. We were able to work around it by ensuring that there are no nested System.import calls. E.g:

```
// a.js
System.import('b');
```

```
// b.js
System.import('c');
```

In the above setup, calling `System.import('a')` might sporadically trigger the error. Our workaround was to move the second `System.import` into a `setTimeout`:

```
// b.js
setTimeout(() => System.import('c'));
```

Our actually setup is much more complex, but the core of our workaround is this. Seems like there is a race condition somewhere.

**Comment by ghempton** [comment]
FWIW, we see this same issue (even more frequently) when using `0.19`

**Comment by lddubeau** [comment]
Can you point to the line in the source where the error is raised? I've been sitting on a race condition that happens sporadically for about a week now and I'm wondering whether your issue and mine are related, but I cannot tell without more information.

**Comment by ghempton** [comment]
I am collecting these logs from our integration server and for whatever reason I am having trouble getting the exact stack trace. Will post here once I do.

**Comment by guybedford** [comment]
If anyone has any replication at all here to share, I'll look into it carefully, but it is tricky without anything to work with. No matter how complicated the case it is fine, and if you need to share it privately that is fine too.

**Comment by ghempton** [comment]
In our case, the line of the error is here: https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L399

Also, want to note that the `setTimeout` workaround above has not completely solved the issue (just made it more infrequent).

**Comment by guybedford** [comment]
Unfortunately a line number doesn't help without a full replication.

If that is going to be a problem, I could potentially put together a debug build with enough assertions to understand further deduction from the assertion logs, but a shared replication would still be ideal.

**Comment by ghempton** [comment]
The reproduction is quite involved and requires our production codebase inside our CI environment. I have been using my own trivial debug build to debug this anyway and would be happy to use a different build.

**Comment by ghempton** [comment]
FWIW, with a little more tracing it seems like in all cases of this error on that line `dependencies` has one more entry than `dependencyInstantiations`. The actual `key` corresponding to the error is different every time: sometimes a module in our code and sometimes a module in a dependency such as `React`.

**Comment by guybedford** [comment]
@ghempton if that is the case it may be worth adding an assertion just before this line - https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L218 to check that `link.dependencies` is undefined at the time of being set there. Knowing that may get us one step closer to the cause.

**Comment by ghempton** [comment]
I added some tracing there and, interestingly enough, it is always undefined. Seems odd since at face value I can't see any code path which would cause `dependencyInstantiations` to not match up with `dependencies`...

**Comment by guybedford** [comment]
Thanks, this remote debugging seems to be making some progress! :)

Ok, here's another thing that might be useful to try then - adding a line like this:

```js
Object.defineProperty(link.dependencies, link.dependencies.length, { set() { throw new Error('Set dependency value over length.') } });
```

To just after that same line again, to see if we can catch any invalid mutations.

**Comment by guybedford** [comment]
It also may be worth trying a similar approach on `dependencyInstantiations` - first checking it isn't being overwritten, and then checking for any `undefined` writes. If `dependencyInstantiations.length` is definitely one less than `dependencies.length` and doesn't have its last item of undefined then not that last check though.

**Comment by ghempton** [comment]
This is truly baffling. I have wrapped both `link.dependencyInstantiations` and `link.dependencies` in `Proxy` objects which log all mutation. Neither of them are mutated. Furthermore, see the following tracing logic:

```javascript
function instantiateDeps (loader, load, link, registry, state, seen) {
  var beforeLength;
  return (link.depsInstantiatePromise || (link.depsInstantiatePromise = Promise.resolve()
  .then(function () {
    var depsInstantiatePromises = Array(link.dependencies.length);

    for (var i = 0; i < link.dependencies.length; i++)
      depsInstantiatePromises[i] = resolveInstantiateDep(loader, link.dependencies[i], load.key, registry, state, loader.trace && link.depMap || (link.depMap = {}));

    beforeLength = depsInstantiatePromises.length;
    return Promise.all(depsInstantiatePromises);
  })
  .then(function (dependencyInstantiations) {
    if(dependencyInstantiations.length !== link.dependencies.length) {
      // XXX: amazingly this matches up with `link.dependencies.length`
      console.error("Before length is: " + beforeLength);
    }
    link.dependencyInstantiations = dependencyInstantiations;

    // run setters to set up bindings to instantiated dependencies
    if (link.setters) {
      for (var i = 0; i < dependencyInstantiations.length; i++) {
        var setter = link.setters[i];
        if (setter) {
          var instantiation = dependencyInstantiations[i];

          if (instantiation instanceof ModuleNamespace) {
            setter(instantiation);
          }
          else {
            setter(instantiation.module || instantiation.linkRecord.moduleObj);
            // this applies to both es and dynamic registrations
            if (instantiation.importerSetters)
              instantiation.importerSetters.push(setter);
          }
        }
      }
    }
  })))
```

**Comment by ghempton** [comment]
Unless I am missing something, it appears that `Promise.all(depsInstantiatePromises)` is resolving to an array of a smaller size. Not sure how this is possible, but I can repeatedly get this behavior about 1/1000 of the time our app boots (as seen by our automated integration test suite).

**Comment by lddubeau** [comment]
@ghempton I'm still unclear as to whether you and I are facing different symptoms of the same issue. I've filed an issue (#1640) with a case that reproduces the problem I ran into, which I thought might be related to yours.

**Comment by ghempton** [comment]
Different error, but definitely seems similar. Sometimes the error moves around for us but is always related to `dependencyInstantations`. In our case, we are actually working with a bundle containing all of the modules. I wonder if we were to load the modules individually if we would hit the issue more often.

**Comment by ghempton** [comment]
So far I have not been able to repro this after upgrading our integration environment from Chrome 54 to 57. I will close this issue once it continues to not be an issue.

**Comment by guybedford** [comment]
There was a linking bug recently caught in https://github.com/systemjs/systemjs/issues/1640. It may or may not be related, but would be worth checking when the update is released shortly.

**Comment by ghempton** [comment]
So far, we haven't seen this issue crop up again.
