### ISSUE TITLE
SystemJS eats some errors making them hard to debug

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#1627]
![screenshot](https://cloud.githubusercontent.com/assets/115926/24217564/4df43c26-0f0e-11e7-8678-8baaad49ed93.png)

If I add a `console.error(childErr.stack)` I can see what's actually going on:

![screenshot](https://cloud.githubusercontent.com/assets/115926/24217673/a6469d1a-0f0e-11e7-8f2e-5503aae9128b.png)

![screenshot](https://cloud.githubusercontent.com/assets/115926/24217711/c53144fa-0f0e-11e7-9efe-6fa32c70c289.png)

**Comment by guybedford** [comment]
If you want access to this original stack, use `System.import('x').catch(err => console.error(err.originalErr.stack))`.

**Comment by amenadiel** [comment]
Is there a way to set that as a default handler?  My stacks are just pointind to bluebird rejections.

**Comment by Rush** [comment]
@guybedford maybe the original stacktrace should become part of the message?  Or maybe you should re-throw the original error modifying its message only?

**Comment by guybedford** [comment]
Originally in SystemJS we did exactly the above - we modified the error message itself, while retaining the same error object and stack. The issue with this approach is that mutating an error just isn't a good idea as there inevitably comes along a user who doesn't like their errrors being mutated!

I know what we have now isn't perfectly ideal, but it's the best win-win I can find.

**Comment by guybedford** [comment]
(The original stacktrace does get copied into the error at https://github.com/ModuleLoader/es-module-loader/blob/master/core/common.js#L90, it just doesn't get all the data due to the limitations of JS errors being generally awful.

**Comment by mk-pmb** [comment]
How about a reference to the original error in a property of the new error?

**Comment by guybedford** [comment]
@mk-pmb that's what we have - `err.originalErr`. Better documentation on this welcome :)
