### ISSUE TITLE
Dependencies are resolved (?) in bad order when mixed esm/amd used

### ISSUE THREAD

**Issue by yurydelendik** [systemjs/systemjs#1630]
I'm trying to move PDF.js to ES6 modules. Currently it's using UMD headers (and systemjs attempts to use AMD style?). So by introducing esm-type module, all dependencies order breaks, e.g. STR

1. Clone at setup pdf.js modified version:
```
git clone --depth=1 --branch=babel-next https://github.com/yurydelendik/pdf.js.git pdfjs-systemjs-babel
cd pdfjs-systemjs-babel
npm install
gulp server
```
2. Open browser at "http://localhost:8888/web/viewer.html"

It fails with "TypeError: RenderingStates is undefined" after I introduce https://github.com/yurydelendik/pdf.js/commit/8ef5ddab655ce77e620fd575528719d298fdca20 .

Works fine when the same code is compiled with webpack (`gulp generic` and opening at http://localhost:8888/build/generic/web/viewer.html)

Is it possible to mix esm and amd modules in the systemjs?

**Comment by guybedford** [comment]
The fix here is to add the following to the SystemJS meta configuration:

```javascript
    meta: {
      '*': {
        scriptLoad: false
      },
      'pdfjs-web/*': {
        esModule: true
      }
    },
```

The reason for this is from the SystemJS 0.20 release, which altered the module format interop such that only `import x from 'asdf'` style imports are supported for loading from legacy module formats. The reason for this is to align with the way NodeJS will handle interop with CommonJS (which won't allow named exports either).

It's a catch certainly, it could well be worth thinking of better ways to warn about this behaviour in the logs.

**Comment by yurydelendik** [comment]
`esModule: true` fixed it. Thank you for help. Closing
