### ISSUE TITLE
How to manually instantiate a registered module? something strange about System.register() a named module.

### ISSUE THREAD

**Issue by billshooting** [systemjs/systemjs#1631]
Hi,
I am using Typescript build a application and Systemjs as module loader. Here is the problem I encountered.
Suppose I have two files(modules),
`module depA` `depA.ts`
``` javascript
export default function depA () {
    // do something
};
```
`entry module` `app.ts`
``` javascript
import depA from 'depA';
depA();
//do something else
```
in `tsconfig.json`, set `module: "system"`, and **NOT** set the `outfile` option, the tsc will generate two **anonymous** systemjs moudles:
`depA.js`
``` javascript
System.register([], function(export_1, context_1){
//code generated
});
```
`app.js`
``` javascript
System.register(['depA'], function(export_2, context_2){
//code generated
});
```
In this case, `System.import('app.js')` works well. Everything is OK.

However, when I try to bundle the project files and set the `tsconfig.json` option: `outfile: 'bundle.js'`, things are different. the tsc will generate two **named** systemjs modules in one file:
`bundle.js` ---named module
``` javascript
System.register('depA', [], function(export_1, context_1){
//code generated
});

System.register('app', ['depA'], function(export_2, context_2){
//code generated
});
```
This time, `System.import('bundle.js')` will not work. The code inside the `function(export, context)` seems not to be excuted.
The interesting thing is if I manually delete the module name, it works. as below is the changed code:
`bundle.js` ---manually changed
``` javascript
System.register('depA', [], function(export_1, context_1){
//code generated
});

System.register(['depA'], function(export_2, context_2){ // change the entry module to anonymous
//code generated
});
```

Manully changing the code generated by tsc --`bundle.js` is not a perfect solution. So I wonder if there is a way to intantiate a **named** entry module?

**Comment by guybedford** [comment]
You need to do something like:

```javascript
System.import('bundle.js').then(function () {
  System.import('app').then(function (app) {
  });
});
```

Alternatively you can configure the above with bundles configuration via:

```javascript
System.config({
  bundles: {
    'bundle.js': ['app']
  }
});

System.import('app').then(function (app) {
  // ...
});
```

**Comment by billshooting** [comment]
Thank you, it help me a lot.

**Comment by mk-pmb** [comment]
Sounds like this issue is solved?

**Comment by billshooting** [comment]
Sorry, I forgot to colse this issue.
