### ISSUE TITLE
SystemJS loading dependent module by local folder not resolving

### ISSUE THREAD

**Issue by eanders-MS** [systemjs/systemjs#1636]
Hello,

I'm trying to load a node module called `radium` using SystemJS. Its main file is `lib/index.js`. I'm able to resolve this using a package entry, like this:
```javascript
packages: {
    'radium': {
        main: 'lib/index.js'
    }
}
```
`radium`'s `lib/index.js` loads an internal module called `'./plugins'`, which is a folder. It should resolve to `lib/plugins/index.js`, but SystemJS is instead trying to resolve it to `lib/plugins.js`. How do I hint SystemJS to do the right thing here?

Thanks.

**Comment by eanders-MS** [comment]
Would be great to be able to say to SystemJS: "If it is a folder, look for index.js in the folder".

**Comment by eanders-MS** [comment]
(but I know that isn't so simple, given it's a url, not a local path)

**Comment by guybedford** [comment]
In SystemJS this can be configured with the package configuration:

```javascript
System.config({
  packages: {
    'radium': {
      main: 'lib/index.js',
      map: {
        './lib/plugins.js': './lib/plugins/index.js'
      }
    }
  }
});
```

I know it's not ideal having to configure these module resolutions, but that is the nature of the browser loading problem.

**Comment by eanders-MS** [comment]
Worked like a charm, thanks!
