### ISSUE TITLE
Where have the 0.20.* versions gone on NPM

### ISSUE THREAD

**Issue by getu-lar** [systemjs/systemjs#1638]
I have an NPM based project with systemjs at version 0.20.9 that was created some weeks ago, but on Monday when I tried to set up a new project that also uses SystemJS, it only gave me 0.19.47 . The NPM package page (https://www.npmjs.com/package/systemjs) says that 0.19.47 is the "latest" version, but since I have a project that says otherwise and 0.20.0 has been released a while ago I am left to wonder: Where have the newer versions gone on NPM?

**Comment by ViceIce** [comment]
It seems that the lastest tag was overwritten by 0.19.47 release. It should point to 0.20.10 which is was released before 0.19.47.

**Comment by getu-lar** [comment]
Interesting... Is this because an NPM package can only have one "latest" release and whatever version is published last, will become the latest version? I realized that it is still possible to get newer versions if I adjust the version in my package.json file manually.

**Comment by ViceIce** [comment]
Yes. It can have multiple tags but one tag can only point to one version.

**Comment by guybedford** [comment]
Thanks, I've fixed this now. It's a footgun in npm that you have to manually run `npm dist-tag add systemjs@0.20.10 latest` to keep the latest at the semver latest when publishing out of order...
