### ISSUE TITLE
Cannot add dependency between AngularJS and jQuery [SystemJS 0.19.22]

### ISSUE THREAD

**Issue by jrabbe** [systemjs/systemjs#1644]
We recently discovered, by doing slight changes to our bundling, that the dependency we thought we had in place between AngularJS and jQuery was not there, and the order of library loading so far was down to dumb luck.

Both AngularJS and jQuery are installed using JSPM. They are installed as the following packages:

- AngularJS: `github:angular/bower-angular@1.5.8`
- jQuery: `npm:jquery@3.1.1`

From reading the docs and various articles, it seemed all I needed to do was add a `meta` object to the config with the following content.

```
  meta: {
    "angular": {
      deps: [
        "jquery"
      ]
    }
  }
```

However, this did nothing. I tried various variations including substituting the full package for "angular" and for "jquery" to no effect.

The jQuery package doesn't contain any SystemJS configuration, but it seems like it's installed as an AMD package, at least jQuery has support for that.

The metadata at the top of the AngularJS library file is

```
/* */ 
"format global";
"exports angular";
```

In a desperate attempt I added `"deps jquery";` below the last of those lines to the AngularJS library file and ran the build. This proved successful and solved the dependency problem.

Is my `meta` object configuration wrong, or do I have to do something else to get SystemJS to pick it up? 

At this point, even "upgrade SystemJS" is a valid response, although I would prefer to find out why something that is fairly well documented, and seems to work for other people, does not work in our setup.

**Comment by guybedford** [comment]
Upgrade SystemJS may well work here :)

But I think the issue is that meta configuration in SystemJS 0.19 doesn't necessarily run through the map configuration, so it should work to write:

```javascript
System.config({
  meta: {
    'github:angular/bower-angular@1.5.8/angular.js': { deps: ['jquery'] }
  }
});
```

Just let me know if that still gives you any issues though.

**Comment by jrabbe** [comment]
Using the full "path" to the JS file worked. Thank you.
