### ISSUE TITLE
0.20.11 breaks import

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1645]
Repro here: https://github.com/unional/domture/tree/break-import

This code works fine in 0.20.10

key points:

```ts
// @unional/logging, written in ts, transpile to es5
export * from 'aurelia-logging'  // aurelia-logging is cjs

// getLogger.ts test file
import { getLogger } from '@unional/logging'
import L = require('@unional/logging')

console.log(getLogger) // undefined
console.log(L) // { default: [Getter], __useDefault: [Getter] }
```

`@unional/logging` is transpiled to es5 thus it is in cjs format.
This means all cjs usage is broken if I'm not mistaken.

It seems to be introduced by `es-module-loader@2.1.4`

**Comment by unional** [comment]
The line `import { getLogger } from '@unional/logging'` not working is very problematic for TypeScript.

All TypeScript nowaday are written in ES6 format whenever possible.
But for compatibility (and other reasons), it is mostly transpile down to ES5.

This mean, in the eye of `systemjs`, it is a cjs module and per latest discussion, this syntax `import { getLogger } from '@unional/logging'` is prohibited.

That means either: Most TypeScript code will stop working, or they have to abandon esm syntax and go back to `import x = require('x')` syntax.

**Comment by unional** [comment]
Of course, this ties to 
#1587 
https://github.com/Microsoft/TypeScript/issues/8687

**Comment by unional** [comment]
cc @frankwallis

**Comment by guybedford** [comment]
ES modules transpiled to CJS without an `__esModule` flag will always have this behaviour yes. Either transpile to the system output format, or alter your imports to be CJS-like.

This sucks, yes. We can only do what is correct though.

**Comment by unional** [comment]
Do you mean the importing module (in this case `@unional/logging`)?  

It does have the flag thou. 

https://github.com/unional/logging/blob/master/dist/unional-logging.es5.js

The above link shows the bundles code from the es5 code being used.

**Comment by guybedford** [comment]
The main module code at https://github.com/unional/logging/blob/master/dist/unional-logging.es5.js#L1748 doesn't seem to export __esModule. Try for example adding `exports.__esModule = true` at line 1760 to see what I mean?

**Comment by unional** [comment]
Thanks! I didn't realize it does not have `__esModule` defined because that project was using TS@2.1, updating to 2.2 fixed this problem.

**Comment by unional** [comment]
Referencing the change made on TS side: https://github.com/Microsoft/TypeScript/issues/13709
