### ISSUE TITLE
Support question - examples for bundling core/npm modules

### ISSUE THREAD

**Issue by ORESoftware** [systemjs/systemjs#1646]
I am looking to bundle Node.js core modules as well as NPM modules for use in the browser.

1) Surely someone out there has a project with core modules pre-bundled? Does this exist? Maybe a command line app, where you pass the names of the core modules you want and the NPM modules you want bundled and then it generates them for you? That would be cool...know of anything?

2) I hate to ask this, but I am a little lost - how can I use SystemJS like Browserify - if I wanted to do (1) myself, how would I go about doing this with SystemJS? I cannot figure out how to bundle NPM modules with SystemJS like you would with Webpack or Browserify.

**Comment by ORESoftware** [comment]
Should I use this?

https://www.npmjs.com/package/systemjs-builder

**Comment by guybedford** [comment]
Still working on getting something here.
