### ISSUE TITLE
Error resolving .js files from filesystem

### ISSUE THREAD

**Issue by ORESoftware** [systemjs/systemjs#1647]
I have the following build script:

```js
let path = require('path');
let Builder = require('systemjs-builder');

const pkg = require('./package.json');
const deps = pkg.dependencies;

function getPaths(){
  return Object.map(deps, function(k,v){
      return require.resolve(k);
  });
}


let builder = new Builder(__dirname, {
  paths: getPaths()
});

let src = path.resolve(__dirname + '/browser-polyfills/dest/all-core-and-npm.js');
let dest = path.resolve(__dirname + '/dist/outfile.js');

builder
.bundle(src, dest)
.then(function () {
  console.log('Build complete');
})
.catch(function (err) {
  console.log('Build error');
  console.log(err);
});

```

I get this error:

```
Build error
{ Error on fetch for node_modules/ascii-table/ascii-table at file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table
        Loading ascii-table
        Loading browser-polyfills/dest/all-core-and-npm.js
        Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table'
    at Error (native)
  originalErr: 
   { Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table' } }

```

I confirmed that `require.resolve()` will always return a .js file, even for ascii-table, and this file exists on my filesystem. It seems clear that SystemJS should be looking for:

`/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table.js`

but instead, SystemJS is erroneously looking for:

`/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table`

It's looking for a file _**without**_ the .js extension...

this is such a fundamental problem (I have seen the same with RequireJS), why does this happen?

**Comment by guybedford** [comment]
SystemJS is the same as RequireJS in that it is a browser-based loader, that does not add extensions automatically. Running SystemJS in Node is designed to mimic the resolution in the browser, using the same resolution algorithm.

Tooling around SystemJS (like jspm) can help SystemJS to load Node modules correctly. It really depends on what you're trying to accomplish.

**Comment by unional** [comment]
I'm not familiar with the build code, but for `systemjs` itself, that's when you need to do:

```js
SystemJS.config({
  ...
  packages: {
     'yourPackage': {
        defaultExtension: 'js'
     }
  }
})
```

**Comment by unional** [comment]
For this error, it is likely due to `ascii-table` does not have `package.json/main` specified.
https://github.com/unional/domture#usage

Try to do the following:
```js
 packages: {
        // This is need for some packages due to https://github.com/systemjs/systemjs/issues/1603
        'make-error': {
          main: 'index'
        }
      }
```
https://github.com/systemjs/systemjs/issues/1603

**Comment by ORESoftware** [comment]
@unional, do you mean this in my case:

```
 packages: {
        // This is need for some packages due to https://github.com/systemjs/systemjs/issues/1603
        'ascii-table': {
          main: 'index'
        }
      }
```

@guybedford I have no idea what to do with the info you gave me - as far as I know there is no such thing as "browser resolution" - the browser can't really talk directly to the filesystem, like Node.js can. The browser can send a server an arbitrary path, and the server sends you a response, sometimes a file. I am not sure why the extension is omitted with SystemJS, seems wrong to me.

I hope @unional's solution works, because otherwise I don't know what to do.

**Comment by ORESoftware** [comment]
nope, it did something, but it didn't work

I have:

```js
let builder = new Builder(__dirname, {
  paths: getPaths(),
  packages: {
    'ascii-table': {
      main: 'index'
    }
  }
});

```
And now I get:

```
$ node systemjs-builder.js 
Build error
{ Error on fetch for node_modules/ascii-table/index.js/index.js at file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/index.js/index.js
        Loading browser-polyfills/dest/all-core-and-npm.js
        Error: ENOTDIR: not a directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/index.js/index.js'
    at Error (native)
  originalErr: 
   { Error: ENOTDIR: not a directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/index.js/index.js'
       at Error (native)
     errno: -20,
     code: 'ENOTDIR',
     syscall: 'open',
     path: '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/index.js/index.js' } }

```

jesus christ. something is wrong @guybedford

**Comment by unional** [comment]
`node_modules/ascii-table/index.js/index.js` doesn't look right. 😄 

Check where `ascii-table` on where it actually place its main.
Probably need a deeper dive into `system.src.js` 😛

**Comment by ORESoftware** [comment]
yeah, turns `ascii-table` has "main" defined, and it's:  "main": "index.js",

**Comment by unional** [comment]
Then it seems like is these two line causing the problem:

```sh
        Loading browser-polyfills/dest/all-core-and-npm.js
        Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/ascii-table/ascii-table'

```
Check the browser field in `ascii-table` package.json

**Comment by ORESoftware** [comment]
"browser" filed in acsii-table?

If I leave out the "main": "index", then it seems to work:

```
let builder = new Builder(__dirname, {
  paths: getPaths(),
  packages: {
    'ascii-table': {}
  }
});
```

**Comment by unional** [comment]
That sounds like a resolution issue then, @guybedford what do you think?

**Comment by ORESoftware** [comment]
Yeah I have tried a few things, not sure what's up. If "main" doesn't exist in a package.json file then SystemJS should look for index.js (right?). But that's actually not the problem here. The problem might be much worse.

**Comment by ORESoftware** [comment]
In the meantime, I am going to go cry for awhile LOL

**Comment by guybedford** [comment]
@ORESoftware I think you're just after `main: "ascii-table.js"`, or just use something like:

```javascript
{
  map: {
    'ascii-table': 'node_modules/ascii-table.js' // (node_modules may or may not be needed depending on your baseURL config)
  }
}
```

**Comment by ORESoftware** [comment]
@guybedford you have a major problem here, the map value for ascii-table works

but now I have this error:

<img width="1387" alt="screenshot 2017-04-09 13 04 40" src="https://cloud.githubusercontent.com/assets/11139560/24840635/584ded32-1d25-11e7-9682-cc9b0b557260.png">


I cannot patch *everything* and manually map everything myself, something is wrong

Is there some other configuration value I can add so that '.js' is used to resolve modules on the filesystem.

this is driving me insane.

**Comment by ORESoftware** [comment]
To explain the screenshot - you can see that ./node_modules/colors/lib/extendStringPrototype.js exists. But then I get this error:
```

Build error
{ Error on fetch for node_modules/colors/lib/extendStringPrototype at file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype
        Loading colors
        Loading node_modules/suman-browser-polyfills/modules/all-core-and-npm.js
        Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype'
    at Error (native)
  originalErr: 
   { Error: ENOENT: no such file or directory, open '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype'
       at Error (native)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype' } }
```



This has nothing to do with anything but the fact that SystemJS is not looking for 'x.js' but is instead just looking for 'x'. What is up with that?

Is there a configuration option I can add to SystemJS to say "looking for .js files"?

**Comment by ORESoftware** [comment]
There seems to be little mystery as to what the problem is here:

SystemJS should be looking for this:

`file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype.js`

instead it's looking for

`file:///Users/alexamil/WebstormProjects/oresoftware/sumanjs/suman/node_modules/colors/lib/extendStringPrototype`

**Comment by ORESoftware** [comment]
I am not sure if this will help, but I successfully have done what I wanted to do with Webpack. However, SystemJS and RequireJS can a few things that Webpack cannot - one thing is dynamic path resolution, which is important for me for my project here!

Here is my Webpack config which works:

```js

const path = require('path');

module.exports = {

  entry: ['babel-polyfill', './lib/index.js'],

  output: {
    path: path.resolve(__dirname + '/dist'),
    filename: 'suman.js'
  },

  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: ['latest'],
          plugins: ['transform-runtime']
        }
      },
      {
        test: /(\/lib\/init\/|cli.js$)/,
        loader: 'ignore-loader'
      }
    ]
  },

  resolve: {
    alias: {
      fs: require.resolve('suman-browser-polyfills/modules/fs'),
      assert: require.resolve('suman-browser-polyfills/modules/assert'),
      process: require.resolve('suman-browser-polyfills/modules/process'),
    },
    extensions: ['.js']
  },

  // packages: {
  //   'ascii-table': {
  //     main: 'index'
  //   }
  // },

  node: {
    // assert: true,
    buffer: true,
    child_process: 'empty',
    cluster: 'empty',
    console: true,
    constants: true,
    crypto: 'empty',
    dgram: 'empty',
    dns: 'mock',
    domain: true,
    events: true,
    // fs: 'empty',
    http: true,
    https: true,
    module: 'empty',
    net: 'mock',
    os: true,
    path: true,
    process: false,
    punycode: true,
    querystring: true,
    readline: 'empty',
    repl: 'empty',
    stream: true,
    string_decoder: true,
    timers: true,
    tls: 'mock',
    tty: true,
    url: true,
    util: true,
    v8: 'mock',
    vm: true,
    zlib: 'empty',
  }
};

```

all I am trying to do is the same thing, but with SystemJS instead of Webpack.

**Comment by ORESoftware** [comment]
@jrburke @guybedford 

RequireJS and SystemJS maestros - I want to use your tools - I do not want to use Webpack.  There is no reason why they shouldn't work. But I am really struggling to get them to work. It seems that both RequireJS and SystemJS suffer from the same problem where they search for files on the filesystem but with no extension (without '.js'). 

Why is that? It literally makes zero sense. I want to be able to use r.js and systemjs-builder to create bundles for the browser, but they are both letting me down. I have Webpack working for my use case, so this is not for want of trying or lack of will. 

I tried doing this with r.js and I failed, so I came to SystemJS, and I have the same problem. The problem is clear if you read this thread.

**Comment by guybedford** [comment]
@ORESoftware better build tooling for SystemJS (and node_modules support) is under development... in the mean time I wouldn't suggest holding your breath though :)

**Comment by ArmorDarks** [comment]
@guybedford We will eventually get `node_modules` support? That would be super cool!

**Comment by ORESoftware** [comment]
@guybedford

Thanks, it seems that SystemJS has the same problems that RequireJS has, that's unfortunate. It's not because it cannot be done, it's because it hasnt been implemented yet, as far as I can tell :)

On the other hand, I do believe that TypeScript/tsc can generate SystemJS and AMD bundles that include node_modules etc,  so that is where I will have to focus my effort here I guess.
