### ISSUE TITLE
Systemjs loads some modules differently to Node

### ISSUE THREAD

**Issue by JustASquid** [systemjs/systemjs#1652]
Since moving to es6 modules for systemjs, I've been running into errors importing certain libraries. I'm using typescript, which can generate either es6 or commonjs imports. 

Importing the simple package [email-validator](https://www.npmjs.com/package/email-validator), for example, will compile correctly for Typescript (no matter which output module system is chosen) and will run fine on Node.

This is not the only package for which I've run into this issue.

[Here is a simple project showing the issue](https://github.com/JustASquid/systemjs-es6-module-issue).

If you change the tsconfig to generate commonjs modules, and run src/main.js through node, you will see that it works fine and imports the package correctly. However, using es6 modules and running main.js in a browser using systemjs to do the imports will fail:

![fail](https://i.gyazo.com/6dae3f9eb61e1eb73ff596d9d9f0d761.png)

**Comment by guybedford** [comment]
@JustASquid which version of TypeScript are you using here? Did you try 2.2?

**Comment by JustASquid** [comment]
@guybedford Using 2.2.2. If you're interested, here are the compiled files:

Using es6 modules:

    "use strict";
    import * as EmailValidator from "email-validator";
    console.log(EmailValidator.validate("test"));
    console.log(EmailValidator.validate("test@test.com"));
    //# sourceMappingURL=main.js.map

Using commonjs modules:

    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    const EmailValidator = require("email-validator");
    console.log(EmailValidator.validate("test"));
    console.log(EmailValidator.validate("test@test.com"));
    //# sourceMappingURL=main.js.map

**Comment by guybedford** [comment]
Ah, you should probably be using `import EmailValidator from 'email-validator'` here then, as this is a CommonJS module. This is the recommended import pattern for loading untranspiled CommonJS.

**Comment by JustASquid** [comment]
Ah right - that *did* trigger a compilation error, but I guess I just needed to turn on `--allowSyntheticDefaultImports`.

Sorry about that.

**Comment by guybedford** [comment]
Thanks for the update, glad it's working.

**Comment by JustASquid** [comment]
@guybedford Ugh, sorry to open this up again - but basically, doing the import statement as you suggested brings up another problem (which might not actually have anything to do with how systemjs handles things) - I'm using shared code on both the client/server. If I use 

`import EmailValidator from 'email-validator'`

And TS commonjs module export, the TS compiler doesn't complain thanks to `allowSyntheticDefaultImports` but running the script through Node doesn't work: 

`TypeError: Cannot read property 'validate' of undefined`

So it seems like I need to use one form of import for the server side and one form for the client, which is definitely not idea.

I do apologize if this is outside of the scope of systemjs - but if you know off the top of your head somewhere else to take this issue I definitely will!

**Comment by guybedford** [comment]
@JustASquid again, this sounds like it is probably TypeScript specific to me? For example Babel will do an __esModule check on imports when running in Node through it's CommonJS output - https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=&browsers=&builtIns=false&code=import%20EmailValidator%20from%20'email-validator'.

**Comment by JustASquid** [comment]
@guybedford I just tried with Babel, and it appears that Babel works with both `import EmailValidator from 'email-validator'` and `import * as EmailValidator from 'email-validator'`. 

Anyway, I've asked a [question on stackoverflow](http://stackoverflow.com/questions/43374160/typescript-correct-way-to-import-commonjs-modules-for-commonjs-output), hopefully I can sort out what to do here!
