### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ghempton** [systemjs/systemjs#1656]
Another sporadic issue that we are seeing in our CI test suite using 0.20.12 . In this case, the error is much more common than #1626. This only seems to happen for us when we are loading our application from multiple bundles (rather than a single bundle).

The error happens here: https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L583. There seems to be a race condition where sometimes `doEvaluate` is called in a state were `link.dependencies` is set, but `link.dependencyInstantiations` is `undefined`.

Will spend more time digging into this in the next few days.

**Comment by guybedford** [comment]
If you can catch the state in a debugger, it would be interesting to log the value of `link.depsInstantiatePromise` to see if it exists and is resolved or not (which can only be indicated in the console log).

**Comment by ghempton** [comment]
`link.depsInstantiatePromise` is definitely instantiated (as determined by a trace statement). Unfortunately, this error is still quite sporadic and I can only reproduce it in our CI environment. Each build has a few of these failures spread out sporadically (out of hundreds of feature tests).

**Comment by ghempton** [comment]
Spent some time on this, but cannot seem to make any progress. A lot of the dependencies seem to hit `instantiateDeps` multiple times and it feels somehow related to the fact that each time we do a deep instantiation. If I move this parentheses https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L397 to instead include the population of `deepDepsInstantiatePromises` (so as to include it in the `link.depsInstantiatePromise`) I see the same error more frequently. I am still not fully grokking the scenario where we need to do the deep traversal multiple times, perhaps you could point me in the right direction?

**Comment by guybedford** [comment]
@ghempton apologies for the delay, please do let me know if you are you still seeing this. If so, it could help to know if you are using the `System.registry.set` or `System.registry.delete` registry API here within the loads, or if the erroring module is just a normal dependency load, circular dependency, primary dependency or plugin dependency.

**Comment by ghempton** [comment]
We are still seeing this and is effectively blocking us from splitting our large application up into multiple bundles. We are not doing any registry mutation such as `System.registry.set` or `System.register.delete` (although we do `System.register.get`). The actual dependency that hits this moves around a bit and we do have some circular dependencies. What is the difference between a normal dependency and a primary dependency?

**Comment by guybedford** [comment]
@ghempton is there no way we can arrange for me to look into the codebase? Or even to copy the codebase, remove all code related to the application while retaining the bug, and share the replication? Happy to sign an NDA etc if necessary too if that's what it takes to get to the bottom of this!

**Comment by ghempton** [comment]
@guybedford appreciate the willingness to dig so deep! I can probably arrange this. I will shoot you an email.

**Comment by recaro** [comment]
This error still happens for us with 0.20.14 after it was reported fixed in #1640

**Comment by lddubeau** [comment]
I managed to miss this report when I filed #1700. That issue report has a case that reproduce the issue reliably and an explanation of why the code change in #1640 did not fix it.

**Comment by guybedford** [comment]
This has been fixed in the next release, and is tracking at #1700. @ghempton this does seem like exactly the issue you were having so do try out the next release and I'm sure it will fix your loading issues.
