### ISSUE TITLE
path and baseURL don't produce expected url ?

### ISSUE THREAD

**Issue by epitka** [systemjs/systemjs#1657]
Trying this with aurelia so I have default config file, but I am trying to set the base url to 
http://locahhost/sav3

Config is like this

"System.config({
  defaultJSExtensions: true,
  transpiler: "typescript",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  baseURL:'http://localhost/sav3',
  map: {
  "npm:aurelia-bootstrapper@2.1.1": {
      "aurelia-event-aggregator": "npm:aurelia-event-aggregator@1.0.1",
      "aurelia-framework": "npm:aurelia-framework@1.1.2",
      "aurelia-history": "npm:aurelia-history@1.0.0",
      "aurelia-history-browser": "npm:aurelia-history-browser@1.0.0",
      "aurelia-loader-default": "npm:aurelia-loader-default@1.0.2",
      "aurelia-logging-console": "npm:aurelia-logging-console@1.0.0",
      "aurelia-pal": "npm:aurelia-pal@1.3.0",
      "aurelia-pal-browser": "npm:aurelia-pal-browser@1.2.1",
      "aurelia-polyfills": "npm:aurelia-polyfills@1.2.1",
      "aurelia-router": "npm:aurelia-router@1.3.0",
      "aurelia-templating": "npm:aurelia-templating@1.4.1",
      "aurelia-templating-binding": "npm:aurelia-templating-binding@1.3.0",
      "aurelia-templating-resources": "npm:aurelia-templating-resources@1.4.0",
      "aurelia-templating-router": "npm:aurelia-templating-router@1.1.0"
    }
}"

This tries to load script from 

http://localhost/sav3/aurelia-pal-browser.js

instead from

http://localhost/sav3/jspm_packages/npm/aurelia-pal-browser.js

**Comment by guybedford** [comment]
I wonder where the `.js` extension is coming from? If you do `System.import('aurelia-pal-browser')` the configuration would definitely apply, and if it was failing you'd get a request to `http://localhost/sav3/aurelia-pal-browser`, not `aurelia-pal-browser.js`. So perhaps there's an import to `aurelia-pal-browser.js` somewhere instead?
