### ISSUE TITLE
CORS via scriptload giving ReferenceError: module is not defined

### ISSUE THREAD

**Issue by gajewsk2** [systemjs/systemjs#1659]
Trying to load scripts over cors using the same format as I'm using for my same-domain site. I'm using 
```
meta: {
    "npm:jquery@2.1.0": {
      "format": "global"
    }, 
    "*.js": {
              format: 'system',
          "scriptLoad": true,
    }
  }
```

```
'use strict';

System.register(['penpal', 'jquery'], function (_export, _context) {
  "use strict";

  var Penpal, $, connection;
  return {
    setters: [function (_penpal) {
      Penpal = _penpal.default;
    }, function (_jquery) {
      $ = _jquery.default;
    }],
    execute: function () {
      console.log($);
     
      console.log(Penpal);
    }
  };
});

//# sourceMappingURL=index.es6.js.map
```

I see CJS loading is disabled with scriptLoad, so how do you get around using the index files which throw: `Uncaught ReferenceError: module is not defined`
`module.exports = require("npm:penpal@2.5.0/lib/index.js");`

**Comment by asapach** [comment]
Evidently you're trying to load CJS modules as scripts tags, which is what `scriptLoad` does. And it obviously doesn't work. Try setting `authorization: true` instead.

**Comment by gajewsk2** [comment]
Yeah, there's some confusion on my part. I'm using `transform-es2015-modules-systemjs` to transform the code, which i thought put it in `format:system`. However, even with this systemjs is looking at the cjs indexes. The rest of my modules aren't in cjs, just those indexes that jspm generates.

**Comment by asapach** [comment]
You should upgrade to jspm 0.17 - it replaced those CJS placeholders with JSON files, so it shouldn't be a problem anymore.

**Comment by gajewsk2** [comment]
I was waiting until it was released from beta. Any ETA on that? Is jspm 0.17 ok for production yet?

**Comment by asapach** [comment]
@guybedford

**Comment by guybedford** [comment]
jspm 0.17 is in many ways more stable than jspm 0.16, so can be worth using. Note that the `0` in the major version number indicates the jspm project stability overall though...

**Comment by gajewsk2** [comment]
Awesome. Is there any timeline to move it officially out of beta?
