### ISSUE TITLE
Import promise never resolves when specifying bundle

### ISSUE THREAD

**Issue by michaelfranzl** [systemjs/systemjs#1662]
Using systemjs 0.20.12 Dev running the following simple and self-contained example in the browser, the `console.log("... this never happens.");` never is called beause the promise never resolves, and even no request is made.

The "bundles" configuration tells systemjs that `local:module@0.0.1.json` is to be found in the file `jspm_packages/local/module@0.0.1/module.js`.

Any other path other than what is configured as registry paths works, for example `Xspm_packages/local/module@0.0.1/module.js` works (notice the X).

But I do want the bundled module to be in exactly that location, under `jspm_packages/local/module@0.0.1`.

Is this a bug, or do I want to do something that should not be done?

```
<!DOCTYPE html>
<html>
  <head>
  </head>
  
  <body>
  
    <script src="system.js"></script>
    
    <script>
      SystemJS.config({
        paths: {
          "npm:": "jspm_packages/npm/",
          "local:": "jspm_packages/local/",
          "github:": "jspm_packages/github/",
        },
        browserConfig: {
          "baseURL": "/",
          "bundles": {
            "jspm_packages/local/module@0.0.1/bundle.js": [
              "local:module@0.0.1.json",
            ]
          }
        },
      });

      SystemJS.config({
        packageConfigPaths: [
          "npm:@*/*.json",
          "npm:*.json",
          "local:*.json",
          "github:*/*.json"
        ],
        map: {
          "module": "local:module@0.0.1",
        },
      });
      
      console.log("I want a module, but...");
      
      System.import('module').then(function(mod) {
        console.log("... this never happens.");
      });
      
    </script>
    
  </body>
</html>
```

**Comment by michaelfranzl** [comment]
Skipping over the mappings and directly requesting the wanted file ...

... this promise never resolves:

    System.resolve('jspm_packages/local/module@0.0.1/module.js')
    --> Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}

... but the Sync version works:

    System.resolveSync('jspm_packages/local/module@0.0.1/module.js')
    --> "file:///jspm_packages/local/module@0.0.1/module.js"

Result is the same when not using file:// but served via http server.

**Comment by michaelfranzl** [comment]
To give my rationale as to why I want `bundle.js` to reside within the path `jspm_packages/local/module@0.0.1`: It has to do with deployment to a production server. Specifically, the URL to `bundle.js` would be versioned this way, acting as a cache-buster when upgrading just this module.

Now, as a work-around I could put the version in the file name and store `bundle.js` in the root path of the web server, but there is also the following to consider:

Say that `bundle.js` was created according to [systemjs/builder](https://github.com/systemjs/builder).  It has inlined CSS created by [systemjs/plugin-css](https://github.com/systemjs/plugin-css). The original CSS file contained `background-image: url('image.jpg')` which in the bundle is correctly translated to `background-image: url('jspm_packages/local/module@0.0.1/image.jpg')`.

To serve this image file, I already need to have the directory `jspm_packages/local/module@0.0.1`, so it would be logical to put `bundle.js` (and all other assets belonging to it) there also, so that the version string doesn't have to be coded twice.

In all video presentations I have seen on YouTube, you put the bundled file directly in the root directory, but that would be losing the versioned URL that is otherwise there without bundles. Any general hints about not just production workflow, but deployment workflow, would be appreciated.

**Comment by manuellp12** [comment]
Hello I confirm the issue. However in version 0.19.41 this case is working properly.

**Comment by michaelfranzl** [comment]
This issue is still present in version 0.20.15. It would be nice if this could be confirmed as a bug, and if a fix is planned for the future.

**Comment by elliot-xu** [comment]
I may be meeting the similar problem here. I'm testing angular5 code which uses `SystemJs.import()` to load bundle files.
In my unit test, I expect to do some check when view is stable `whenStable().then( my check here... )`, 
but `SystemJs.import(bundle)` hasn't resolved yet since `my check here...` already started. 
Which was not expected, because `NgZone`(zone.js) will and would register a `Promise` and its callback as tasks,  when all the tasks finished, `whenStable()` will be fired, so I can do some check then. It worked well when systemjs was on 0.19.41. 
Could this dead lock thing may be the reason why `NgZone` thinks that there are no more tasks should invoke?
