### ISSUE TITLE
user my javascript file in Angular 2

### ISSUE THREAD

**Issue by karangoswami31** [systemjs/systemjs#1663]
HI I  have created Simple java script file ,, 
just take example  Webflow.require('ix').init([]);
 or 
or my file general.js 
=?   $(document).ready(function () {
        if ($(".threeblockslider").length) {
            var owl = $(".threeblockslider");
			owl.owlCarousel(threeblockSliderOption);
        }
});
how it work in Angualr2

**Comment by constgen** [comment]
Is question related some how to SystemJS? If not it is better to close this issue and ask the question in developers forums and chats, e,g, Stackoverflow.

**Comment by karangoswami31** [comment]
How to Access Javascipt object In ANgular 4.0
