### ISSUE TITLE
Support require json files

### ISSUE THREAD

**Issue by mk-pmb** [systemjs/systemjs#1666]
Thanks for this great project! Out of the box it almost loaded my node module, until the line where that node module `require()`s a JSON file. There I get: `Error: missing ; before statement`.
If I prepend `module.exports = ` to the JSON file, it works with systemjs, but fails in other contexts where real JSON is expected.
For my current use case it would suffice to detect JSON files that hold an object or an array.
Ignoring possible UTF-8 BOM is appreciated.

**Comment by ArmorDarks** [comment]
You can use already existing plugin for it: https://www.npmjs.com/package/systemjs-plugin-json

**Comment by mk-pmb** [comment]
Oh, thanks! I'll PR a hint in the docs.
