### ISSUE TITLE
Allow plugins to intercept format guessing

### ISSUE THREAD

**Issue by mk-pmb** [systemjs/systemjs#1667]
In the [docs/module-formats.md § module-format-detection](
https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection), it sounds to me like the list is hard-coded. Would it seem feasible to allow configuring a list of module identifiers to help guessing?

The modules could export a structure that contains an oracle function and some meta data like plugin APO version,
The oracle function could work on a conjecture object which holds
* the format identifier of the current best guess
* the mystery file's URL
* the mystery file's full file content
* the position of the first character that's neither whitespace nor a JS comment; or the remaining file content starting at that character.
* a dictionary object of formats that have been disproven, e.g. `conjecture.maybe = { cjs: false, system: false }`
  * Possible read-only use case: "If it can't be `cjs`, don't bother checking whether it's my special variation `cjs-with-magic-comments`."
  * Possible modifying use case: "If it has `/\.jsm($|\?)/` in it's URL, it cannot be `global` format."

The oracle function could return its opinion as a non-empty string, or return a false-y value if it has no idea.

I'll defer thinking about priority issues until I see whether it's feasible at all.
The plugin's meta data could contain default transpiler info for the formats it knows about.
I'll also defer thinking about how we could best support to put transpiler functions in the same module as the oracle function.

**Comment by guybedford** [comment]
This could definitely be a useful feature, but the goals of the SystemJS project are to improve alignment with specs over time, not to introduce more custom functionality.

**Comment by mk-pmb** [comment]
Sounds like it's off-topic here then, and should be requested in one of the specs projects listed in [es-module-loader](https://github.com/ModuleLoader/es-module-loader) once I or someone else finds the time. I'll leave up to you whether and when to close it.
