### ISSUE TITLE
Self-mapped bundles cause promise deadlock

### ISSUE THREAD

**Issue by EricABC** [systemjs/systemjs#1669]
If I map a bundle to a path that coincidentally includes itself as a mapping, a deadlock occurs.
```json
{
  ...
  "bundles": {
    "rxjs/MyRxBuild.js": [
      "rxjs",
      "rxjs/*",
      "rxjs/operator/*"
      ...
    ]
  }
}
```

```loadBundlesAndDepCache``` will run system.import [here](https://github.com/systemjs/systemjs/blob/13df95c4823c860bf4967326339dc9de617b1b0a/src/instantiate.js#L141) when ```key``` is its own normalized import.

If there was a way to retain that the load is within a bundle context, rather than just check for a match with its own normalized form, it might also fix possible (however obscure) cyclical bundle cases.

**Comment by michaelfranzl** [comment]
I ran into the same issue a couple of days ago: https://github.com/systemjs/systemjs/issues/1662

**Comment by EricABC** [comment]
Ah I see, sorry for the dupe.
