### ISSUE TITLE
Loaded modules get empty dependencies

### ISSUE THREAD

**Issue by ZoolWay** [systemjs/systemjs#1673]
Hello,

It is a bit tricky to describe my problem. It started occuring when my project grow to a certain size. I will appreciate anything helping me finding the issue.

This happens using SystemJS 0.19.46 and 0.19.47:
Some of my own modules get imported empty - but only when using a bundle, not when running unbundled.

An example from an affected module inside a bundle. The generated code looks like this:
```
define("core/client-storage-service.js", ["require", "exports", "aurelia-framework", "core/api-caller", "core/state", "lib/unique-tools", "lib/enum-ex", "core/memory-appender"], function(require, exports, aurelia_framework_1, api_caller_1, state_1, unique_tools_1, enum_ex_1, memory_appender_1) {
  "use strict";
  Object.defineProperty(exports, "__esModule", {value: true});
  ...
```

When I put a break point at the `Object.defineProperty`-line, I find out:
The values for `aurelia_framework_1`, `unique_tools_1`, `enum_ex_1` and `memory_appender_1` look good.
But `api_caller_1` and `state_1` are just an empty object.
When I run `SystemJS.has('.../core/state')` (using fully qualified name) at this point it return `false`. When I run it after continuing the breakpoint and having my application failed because of this, the same command return `true`. So it feels like when loading that module _core/client-storage-service_ it has not loaded _core/state_ although its a dependency. Later it has loaded _core/state_.

The module _core/api-caller_ is quite complex while _core/state_ is more a simple shared object. Also I must again state that unbundled the very same code runs.

I also tried to hint the dependency in the configuration with no luck:
```
  meta: {
    "core/client-storage-service": {
      "deps": [
        "core/state"
      ]
    }
  },
```

I activated the warnings but they all go about the wildcards in the _paths_ which I need at this moment (and are reason to stick to 0.19) and about _defaultJSExtensions_.

When I revert to code to 2 weeks ago it works. There was no change in any library versions, just changed and added more user code - like it got more modules during this time.

What else can I do to find the source of the problem?

**Comment by guybedford** [comment]
@ZoolWay this sounds like it might be a circular reference was inadvertently introduced into the codebase altering the execution order resulting in undefined exports at the time of execution. I'd suggest looking closely at the dependency tree of the module loading the undefined exports, and seeing if you can trace down the loop.

**Comment by ZoolWay** [comment]
@guybedford Thanks. Is there any kind of debug option I can turn on to get more out of it?

**Comment by ZoolWay** [comment]
Okay, thanks to [madge](https://github.com/pahen/madge) I was able to find the circular dependency and resolved it. The problem vanished.

```
madge --circular .
```

Still would be nice to get some more information out of SystemJS in these cases.
