### ISSUE TITLE
`require()` analysis issue with CJS

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1677]
`systemjs` has problem loading `axios` library directly due to its `require()` analysis

The error message is: `Error: ENOENT: no such file or directory, open '/Users/hwong/github/unional/some-issues/node_modules/https/package.json'`

The problem is cause by these lines: https://github.com/mzabriskie/axios/blob/master/lib/defaults.js#L16-L26

```js
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```

When `systemjs` tries to load this file, it statically picked out `require('./adapters/http')` which cause it to load https://github.com/mzabriskie/axios/blob/master/lib/adapters/http.js which should be loaded only in node environment. That file contains `require('http')`.

If I change the code to:
```js
function getDefaultAdapter() {
  var adapterPath;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapterPath = './adapters/xhr';
  } else if (typeof process !== 'undefined') {
    // For node use HTTP adapter
    adapterPath = './adapters/http';
  }

  return adapterPath ? require(adapterPath) : undefined;
}
```

it fails with:

```sh
Error: Module ./adapters/xhr not declared as a System.registerDynamic dependency of
file:///Users/hwong/github/unional/some-issues/node_modules/axios/lib/defaults.js
```

So seems like dynamic relative path resolution is not working.

repro: https://github.com/unional/issues/tree/systemjs-require-analysis

In the repro it demonstrates the first issue. To see the second issue, you need to manually change the code in `node_modules/axios/lib/defaults.js`

🌷

**Comment by guybedford** [comment]
The best way to handle this sort of a case is just to map to `@empty` the module path you don't want.

Something like:

```js
System.config({
  map: {
    'path/to/axios/lib/defaults.js': '@empty'
  }
});
```

If the above is configured as a package, it may be worth using a package map config for the above - `'./lib/defaults.js': '@empty'` sort of thing.

**Comment by unional** [comment]
Thank! I have tried many possible ways and only these two works:

```js
System.config({
  packages: {
    axios: {
      main: 'dist/axios.min.js' // `axios` actually distribute bundled version
      map: {
        // notice it has to be adjusted relative to the package root instead of `./adapters/http`
        './lib/adapters/http': '@empty'
      }
    }
  }
}
````

For reference, none of the following works:

```js
System.config({
  map: {
    'node_modules/axios/lib/adapters/http.js': '@empty',
    './node_modules/axios/lib/adapters/http.js': '@empty',
    'C:\<path to project>\node_modules\axios\lib\adapters\http.js': '@empty'
  },
  packages: {
    'axios': {
      map: {
            './adapters/xhr': 'lib/adapters/xhr.js',
            './adapters/http': '@empty',
            './adapters/http.js': '@empty',
            'lib/adapters/http': '@empty',
            'lib/adapters/http.js': '@empty',
            './lib/adapters/http': '@empty',
            'C:\<path to project>\node_modules\axios\lib\adapters\http.js': '@empty'
      }
    }
  }
}
```
