### ISSUE TITLE
Adding an app build version resolution to each request

### ISSUE THREAD

**Issue by mlc-mlapis** [systemjs/systemjs#1682]
Can anybody explain the situation how to correctly add a version to each request to eliminate caching when sources have changed?

I temporarily use just a trivial source hack as:
```
function fetchFetch (url, authorization, integrity, asBuffer) {
  if (_build_version) {
    url = url + '?v=' + _build_version;
  }
  ...
}
```
I can not understand why so simple thing is not officially enabled and supported when anybody needs it.

**Comment by mlc-mlapis** [comment]
Any reaction?

**Comment by guybedford** [comment]
This has been resisted for some time because the idea has been that modules won't have this in the browser.

But we're running a custom resolver and it's a convenience that would help a lot of people.

I'll see if I can play around with this old one for the next release.

**Comment by guybedford** [comment]
I guess it would help here to understand the workflows this applies to.

In my mind one only needs a force cache clear when working in local development, but then you can use the disable cache in the network tools like you would need to do for other resources anyway.

Once in production, everyone should be using hashed or versioned URLs in their builds. What keeps me away from this is encouraging bad practise. If someone can help me see the argument for how this can be a good practise in a build that might help.

**Comment by asapach** [comment]
@guybedford, one workflow I found this useful is Karma: it has a built-in web server that caches files based on their hash. So if you request `/file` you get a response without any caching headers, but when you request `/file?hash` you get `ETag` and `Last-Modified` headers which help speed things up when you make multiple requests for the same files. I was using `locate` hook in v0.19 for that.

**Comment by mlc-mlapis** [comment]
@guybedford ... there are many different scenarios how the process could be set ... local dev -> **test version** -> production version. There could be also different time requirements on each phase ... to make dev process as fast as possible where each second is counted ...

But still the main reason is simplicity. If you take `locate` hook from  v0.19 and compare it to any custom builds (able to generate hashed or versioned URLs) then `locate` is by far the easiest.

And I don't understand also why are you talking about bad practise in this case ... it is totally optional and it is working by the same principle as hashed or versioned URLs produced by more complicated build systems.
