### ISSUE TITLE
Errors not log to console in Micrsooft Edge and IE11

### ISSUE THREAD

**Issue by xwisdom** [systemjs/systemjs#1683]
Hello,

While testing a script in Microsoft Edge and IE11 I noticed that exceptions were not logged to the console. Is this a bug in SystemJS?

Tested using SystemJS 0.20.13

Here's the sample script:

```
<script>
System.register("moduleA", [], function (_export, _context) {
  "use strict";

  return {
	setters: [],
	execute: function () {
	  _export("default", function (arr) {
		  var txt = "Hello";
		  throw new Error('Error on page!'); // throw exception
		  return txt;
	  });
	}
  };
});

System.import('moduleA').then(function(v) {
	console.log(v.default());
})
</script>
```

**Comment by guybedford** [comment]
Try `System.import('moduleA').then(function(v) {
	console.log(v.default());
}, function (err) { console.log(err) });`?

**Comment by xwisdom** [comment]
Hi Guy,

Many thanks. I'll give it a try.

**Comment by xwisdom** [comment]
It's working! I got it to log the error to the console.

Many thanks for your help
