### ISSUE TITLE
defaultExtension seems not to work when using absolute path for modules

### ISSUE THREAD

**Issue by pushist1y** [systemjs/systemjs#1684]
I'm using following configuration

`SystemJS.config({
                baseURL: Consanta.baseUrl + "/ts",
                packages: {
                    "*/ts": {
                        defaultExtension: "js"
                    }
                }
            });`

I don't want to use relative paths as base url as I want to import modules from different pages of MVC app. But i can't figure how to make SystemJS to add default "js" extension for all my modules. Currently it tries to access correct url for imports except for extensions. 

I've tried to specify packages mask as: `"."`, `"/ts"`, `Consanta.baseUrl + "/ts"`, `"*"`.

I just want to make it add .js extension for every module. How can i achieve that?

**Comment by guybedford** [comment]
`packages: { "/ts": { defaultExtension: 'js' }}` should work here actually.

**Comment by pushist1y** [comment]
As i mentioned, i'm using MVC. I have pages with urls like:
`http://myhostname/controllername/actionname/parameter`

If i'm using an import on that page and the config with relative path as the one you provided it tries to load file like:
`http://myhostname/controller/ts/myscript.js`

While i want it to go for:
`http://myhostname/ts/myscript.ts`

Using MVC I may have pages with really long parametrized urls but i still want modules to be loaded from single directory.

**Comment by guybedford** [comment]
@pushist1y to try and understand - your import might be `import 'myscript'` within a parent module at `http://myhostname/controllername/actionname/parameter`, which you then want to resolve to `http://myhostname/ts/myscript.ts`? In that case `baseURL: '/ts', packages: { '/ts': { defaultExtension: 'ts' } }` sounds exactly right.

**Comment by pushist1y** [comment]
Thank you! That really works. I can't tell why i thought it didn't earlier...

But now i have another problem.
For now i have following code:
```<script type="text/javascript" src="~/ts/Auth/Register.js" asp-append-version="true"></script>
<script type="text/javascript">
    $(function () {
        SystemJS.import('Auth/Register').then(function (m) {
            m.initRegister();
        });
    });
</script>```

This code includes file with my module statically and then the import call accesses already loaded module and calls an initialize function from it. That works fine.


I'm trying to change this to following:
```<script type="text/javascript">
    $(function () {

        SystemJS.config({
            baseURL: "/ts",
            packages: {
                "/ts": { defaultExtension: "js" }
            }
        });

        SystemJS.import('Auth/Register').then(function (m) {
            m.initRegister();
        });
    });
</script>```

This time i have no static link to js module file, SystemJS acquires it itself (it get's the file from proper url of http://host/ts/auth/register.js, i can tell that viewing Network tab in chrome debug) but this time the module does not have "initRegister" function and i'm getting an exception. 

The file i'm importing: [link](http://static.terribles.ru/files/2017-08-21--13-38-28-Register.js)

This file contains multiple modules (the target module and all modules required by it are compiled into single file via typescript).

**Comment by guybedford** [comment]
It sounds like the issue here is getting the bundle module names to match up with the imported module names.

The way to check this is to look at `[...System.registry.keys()]` finding what `Auth/Register` becomes (it should be `https://site.../ts/Auth/Register.ts` with this config). If it's not that, I suspect the reason would be that you need to include your SystemJS configuration before loading the bundle to ensure the normalization of the bundle names is correct.

**Comment by pushist1y** [comment]
When loading js-file manually i'm getting following keys
Before import: ```["@empty", "@system-env", "@@cjs-helpers", "@@global-helpers"]```
After import: ```["@empty", "@system-env", "@@cjs-helpers", "@@global-helpers", "http://localhost:56496/auth/Modules/CommonFunctions", "http://localhost:56496/auth/Modules/BaseUrl", "http://localhost:56496/auth/Common/UserDto", "http://localhost:56496/auth/Auth/Register"]```


When i'm trying to import via SystemJS
Before import: ```["@empty", "@system-env", "@@cjs-helpers", "@@global-helpers"]```
After import: ```["@empty", "@system-env", "@@cjs-helpers", "@@global-helpers", "http://localhost:56496/ts/Auth/Register.js"]```

It finds the source file properly but somehow doesn't load it's contents. The ```Auth/Register``` module is registered with dependencies:
```System.register("Auth/Register", ["Modules/CommonFunctions", "Modules/BaseUrl", "Common/UserDto"], function (exports_4, context_4)...)```

But it does not attempt to resolve them - browser doesn't try to load corresponding files

**Comment by guybedford** [comment]
@pushist1y the mismatch there is then exactly the issue - `/ts/Auth/Register.js` as created by the bundle is not matching up with `/auth/Auth/Register` as expected. There seem to be two issues - (1) that the `baseURL` is not matching between these, and (2) that the default js extension is not included in the bundle. (1) can be fixed by altering the `baseURL` in production to `/auth`, or explicitly having the bundle define `/auth/...`. (2) can be fixed by having the bundle include the `.js` extension, or by using a package configuration to add it via `packages: { '/auth': { defaultExtension: 'js' } }`.

**Comment by pushist1y** [comment]
Ok, i can confirm that configuration from your first answer works: `SystemJS.config({
                    baseURL: Consanta.baseUrl + "/ts",
                    packages: { "/ts": { defaultExtension: 'js' } }
                });  `

I've reconfigured our project from scratch and somehow it works and pulls all the necessary modules itself. I can't tell what I did wrong before but thank you for your answers anyway.
