### ISSUE TITLE
After updating to 0.20.13, template imports come in as "true"

### ISSUE THREAD

**Issue by httpete** [systemjs/systemjs#1685]
Only in built version does it do this. I import templates like:

import * as template from './template.html';

When I revert to 0.20.12 it works fine.

**Comment by guybedford** [comment]
Which plugin are you using here?

**Comment by httpete** [comment]
text plugin I have it configured to field all .html

**Comment by guybedford** [comment]
I've published a 0.0.10 of the text plugin with a fix. Let me know if that works for you.
