### ISSUE TITLE
After upgrade to 0.20.13 I get "true" instead of the module I want

### ISSUE THREAD

**Issue by lll000111** [systemjs/systemjs#1686]
For running tests for JS code that runs on node, browser, react-native I have a special `index.html` file which loads SystemJS from `./node_modules/` using a `<script>` tag. In order to let code that has a `require('systemjs') run using the SystemJS that the page has already loaded

    SystemJS.registry.set('systemjs', SystemJS.newModule({default: SystemJS, __useDefault: true}));

Inside modules that used `const SystemJS = require('systemjs')` this gave me SystemJS. As of 0.20.13 I only get `true`! The last working version is 0.20.12.

Related to https://github.com/systemjs/systemjs/issues/1685 "After updating to 0.20.13, template imports come in as "true""?

**Comment by guybedford** [comment]
The __useDefault value was changed to be the actual module value in this
contract to support default exports with the __esModule flag. Try:

__useDefault: SystemJS

**Comment by lll000111** [comment]
Works, thanks!
