### ISSUE TITLE
Live bindings does not seems to work

### ISSUE THREAD

**Issue by chabb** [systemjs/systemjs#1687]
I am using typescript with systemJS as the module loader. I am using the D3.js library to do some charting.

The D3 library exports an 'event' field, that is supposed to be a live binding. It's used by some event listeners. Sadly, the binding is not live, as the value of the imported export is always null.

Is there a way to come across that, or to tell SystemJS that this binding should be live ?

**Comment by asapach** [comment]
Are you importing the ES modules or the compiled UMD bundle?

**Comment by chabb** [comment]
I am importing the ES modules,  I have a typescript file that export what i need from d3. 

`
export * from 'd3-axis';
export * from 'd3-format';
export * from 'd3-interpolate';
export * from 'd3-scale'
export * from 'd3-array';
export * from 'd3-shape';
export * from 'd3-sankey';
export * from 'd3-zoom';
export * from 'd3-drag';
`
Then in another typescript file, i do an import of this file
`
import * as d3 from '../../../../custom-d3';
`

One interesting point is that i needed to upgrade SystemJS to the latest version,  for the d3.event ( d3.event is exposed in the d3-selection module, which is used by other d3 modules, d3 is a collection of submodules) to work in d3 submodules ( => that means the d3.event was not correctly exported in d3 submodules when i was using an older version of SystemJS). Now it's working fine inside d3 code, but my code is not able to see the d3.event 'live', it is still null

**Comment by asapach** [comment]
The next question is: are `d3-selection` and other d3 imports ES modules or UMD bundles? Are you installing them using JSPM? Does it respect `jsnext:main` or `module` fields in `package.json` rather than `main`?

**Comment by chabb** [comment]
I installed those d3-modules via npm.. they are ES modules. 
They have a jsnext:main field, but it does not seem to be used, the main field is used.

E.g, the d3-axis has this package.json :

```
"homepage": "https://d3js.org/d3-axis/",
  "jsnext:main": "index",
  "main": "build/d3-axis.js",
  "module": "index",
  "name": "d3-axis",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/d3/d3-axis.git"
  }
```
When my app is packaged, the module is loaded via build/d3-axis.js, index.js is not used

**Comment by asapach** [comment]
> they are ES modules

Apparently not. Looks like in this case UMD bundles will be used.

**Comment by chabb** [comment]
Yes, you are right.

**Comment by chabb** [comment]
Is there a way to tell SystemJS/Typescript to use the jsnext:main field ? Apparently, is this field is respected, things should work as expected.

**Comment by chabb** [comment]
I found a way to make it work, but i had to tweak to source-code. Basically i tell systemJS to use the js:next field, if available, and then i use the babel transpiler. This ensures that the d3 modules and my module are in the same layer, so live bindings are working correctly. So now the question is : how to do it without tweaking the source code ?

**Comment by guybedford** [comment]
@chabb instead of tweaking the source code this could be provided with a packages configuration instead, which will take preference over the package.json loaded through package config paths.

**Comment by aendrew** [comment]
I ran into this today with my project ft-interactive/d3-bootloader. Using the UMD bundle and importing using `import d3 from 'd3'` (i.e., default export instead of gathering all named exports via `*`) seems to have fixed it? That may be due to [this here](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies):

> When loading CommonJS, AMD or Global modules from within ES6, the full module is available at the default export which can be loaded with the default import syntax.

Weird, man. Weeeeeird.
