### ISSUE TITLE
react-redux loading issue

### ISSUE THREAD

**Issue by pirovorster** [systemjs/systemjs#1689]
A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
  Instantiating https://localhost:8746/lib/react-redux/dist/react-redux.js

![image](https://user-images.githubusercontent.com/6638988/27263773-cd98d4e4-5470-11e7-83bf-dcbcbc872559.png)

However react-redux does not require any transpilation?

**Comment by SerkanSipahi** [comment]
@pirovorster 
do you use SystemJS for loading of components,libs? If it is so, then set `SystemJS.config({ transpiler: false })` , i think default is true!

**Comment by guybedford** [comment]
@pirovorster just let me know if you still need assistance with this.

**Comment by chinfeng** [comment]
I got the same issue.

[src/instantiate.js#L417](https://github.com/systemjs/systemjs/blob/9e87f004339b3ee60dc8bec8750957bf5d9266a2/src/instantiate.js#L417)

It just cannot detect react-redux.js. When i change to react-redux.min.js, it works find.

**Comment by guybedford** [comment]
@chinfeng the fix for this is to set the module format explicitly through meta configuration.

**Comment by SerkanSipahi** [comment]
@chinfeng see https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta
