### ISSUE TITLE
Can I load an AMD module with system-production.js?

### ISSUE THREAD

**Issue by xwisdom** [systemjs/systemjs#1692]
Hello,

Is it possible to dynamically load an AMD module using system-production.js?

When I tried loading the AMD module I get the following error:

> Uncaught (in promise) Error: Module instantiation did not call an anonymous or correctly named System.register.

**Comment by guybedford** [comment]
No, the production build only supports System.register and System.registerDynamic modules. The SystemJS builder project enables building into these formats from AMD, which itself uses the Babel transformers listed under `babel-plugin-transform-...` in https://github.com/systemjs.

**Comment by xwisdom** [comment]
Thanks for the feedback
