### ISSUE TITLE
Object literal shorthand not working?

### ISSUE THREAD

**Issue by nonsensecreativity** [systemjs/systemjs#1698]
fileA.tsx

`export const someVar = 'string';`

fileB.tsx

```
import {someVar} from './fileA';

const newVar = {
   someVar
}
```

then I got "Error: someVar is not defined"

this will work without shorthand

```
const newVar = {
  someVar: someVar
}

```
is it plugin-typescript issue? or SystemJS?

my package:
- JSPM: ^0.17.0-beta.41
- SystemJS: SystemJS v0.20.14
- plugin-typescript: @7.0.6

**Comment by SerkanSipahi** [comment]
@nonsensecreativity im have no idea of typescript but i guess your plugin(plugin-typescript: @7.0.6) has no support `Object literal shorthand`.

**Comment by nonsensecreativity** [comment]
just found out today that I need to specified the typescript compiler options 'target' for 'es5'
