### ISSUE TITLE
Be able to undef a module after an error?

### ISSUE THREAD

**Issue by cristiano-belloni** [systemjs/systemjs#17]
(I'm talking about the dynamic require case here)
With requirejs, this was my errback function:

```
var failedId = err.requireModules && err.requireModules[0];
requirejs.undef(failedId);
```

What's the workflow when you get an error loading a module with the jspm loader? Do one has to undefine it somehow?

**Comment by mc007** [comment]
just a question, is undef still in place, and does it work for all modules? Sorry, I can't find it in the code rightnow ;-)

**Comment by guybedford** [comment]
`System.delete`, `System.set` and `System.get` are all supported.

**Comment by mc007** [comment]
awesome! thank you, again :-)
