### ISSUE TITLE
 Error: (SystemJS) XHR error (404 Not Found) loading localhost:3000/three

### ISSUE THREAD

**Issue by sancelot** [systemjs/systemjs#1701]
Hi guys !

I started using angular, and faced the next message , once trying using three.js api :

 Error: (SystemJS) XHR error (404 Not Found) loading localhost:3000/three

After some researchs , I found many people facing similar problems with other apis ....but without success...

finally somebody told me that was "because of" systemjs , he was using webpack.

Do you think it is valuable in professional developing environments to display a poor non sense message in console log when something goes wrong ????? 

Dring, dring !!!! I think you should awake.

Regards.
S.Ancelot

**Comment by SerkanSipahi** [comment]
Can you see the problem? Its try to load three and not three.js ! I think this is more than `valuable in professional`
```js
Error: (SystemJS) XHR error (404 Not Found) loading localhost:3000/three
```

Systemjs is an universal loader. It can load .ts .js, es6 and so on. I think its default behavior has not file extension.

you can configer it in your Systemjs config:
```js
SystemJS.config({
    packages: {
        "src": {
            "defaultExtension": "js"
        },
        "test": {
            "defaultExtension": "js"
        },
        "node_modules": {
            "defaultExtension": "js"
        }
    }
});

```

**Comment by sancelot** [comment]
I will have a look at it. for you the problem resolution seems an evidence ...
The major problem today, is that some people may develop very good backend , but nobody will use them since the user frontend is a sucking one.  
"loading: can not found three file ...". But we may not live in same world. Regards
