### ISSUE TITLE
Matching the standard

### ISSUE THREAD

**Issue by PFight** [systemjs/systemjs#1702]
Hello, looks like dynamic import going to be implemented in Chrome, already works in Safary TP, and nice to Firefox and Edge teams.

https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/wRLMM5-kpCY/Y0be_ASaAwAJ

![image](https://user-images.githubusercontent.com/198847/27908957-0ccc05e8-6257-11e7-9721-4d3a8431e03f.png)

What about compability with this implementation?

**Comment by guybedford** [comment]
Dynamic import is supported in SystemJS, through both the TypeScript and Babel transformers.
