### ISSUE TITLE
Loading dependency module

### ISSUE THREAD

**Issue by hanh090** [systemjs/systemjs#1704]
I have module A which already declare in System.config, something like that
```javascript
SystemJS.config({
    meta: {
        'A.js': {
        }
});
```
then in module B, I need using module A as my dependency. How can I do that?

**Comment by SerkanSipahi** [comment]
// you can just import it in file B.js 
import a form 'A';

**Comment by hanh090** [comment]
Your solution will load only file `B.js` not module `B.js` which have some dependencies

**Comment by hanh090** [comment]
@guybedford I still do not know answer yet :sweat:

**Comment by guybedford** [comment]
@hanh090 the method described in https://github.com/systemjs/systemjs/issues/1704#issuecomment-313662210 sounds right to me. It will load `B.js` as a module including its dependencies before executing `A.js`.

**Comment by hanh090** [comment]
I tried that but no success. I declare dependencies of `B.js` by SystemJS via config like this:
```javascript
// B.js module
SystemJS.config({
	baseURL: base_path,
	map: {
		"dependency": "dependency_path",
		"b_module": "b_module_path",
	},
	meta: {
		'b_module/b_module.js': {
			"deps": [
				"dependency/dependency.js"
                         ]
                }
       }
})
```
And `A.js` module:
```javascript
// A.js module
SystemJS.config({
	baseURL: base_path,
	map: {
               "a_module": "a_module_path",
		"b_module": "b_module_path",
	},
	meta: {
		'a_module/a_module.js': {
			"deps": [
				"b_module/b_module.js"
                         ]
                }
       }
})
```

**Comment by guybedford** [comment]
The configuration above should all be in a single file that is loaded before loading any modules. Then the modules should just include code and no configuration. Let me know if that makes sense.

**Comment by hanh090** [comment]
Sorry for my late comment
for my business I need separated these config to separated files and it fail whenever I import by your mentioned way. I have a workaround is using Promise.all to load all config file
