### ISSUE TITLE
System-Production-Loader not supporting `packages` configuration option

### ISSUE THREAD

**Issue by joeljeske** [systemjs/systemjs#1705]
I am confused why the production loader does not support the `packages` configuration option. Currently, I am transpiling my source with builder.compile() to create a 1-to-1 source-to-output build. 
In development, I have configuration like 
```
SystemJS.config({
    ...
    packages: {
            app: {
                main: './main.ts',
                defaultExtension: 'ts'
            }
        }
});
```

In production, I need something like 
```
SystemJS.config({
    ...
    packages: {
            app: {
                main: './main.js', // Note use .JS instead of .TS
                defaultExtension: 'js'
            }
        }
});
```

My output built files all contain the appropriate `System.register` calls that are supported by system-production-loader but I cannot figure out how to tell SystemJS the primary entry point to my module and then the file-extension of its other dependencies. 

Possible Solutions: 

1. Using `packages` or another configuration option to tell the loader where to find my files
2. Supplementing the full path information in the compiled files such they contain enough information to find its dependencies at production runtime.

**Comment by guybedford** [comment]
The production loader removes a lot of the features of SystemJS, and build workflows for it are still somewhat experimental.

Basically, the idea is that resolutions should be inlined as far as possible for production, but support for this in SystemJS builder is pending.

**Comment by fahadash** [comment]
Any update on this?
