### ISSUE TITLE
Import/require package with local module dependency

### ISSUE THREAD

**Issue by bitstrider** [systemjs/systemjs#1707]
So in my example, I'm using [`getlibs`](https://github.com/activewidgets/getlibs) to import/require [`cwise-compiler`](https://github.com/scijs/cwise-compiler), but when it encounters a [local module dependency](https://github.com/scijs/cwise-compiler/blob/master/compiler.js#L3) within that module's source...

```
var createThunk = require("./lib/thunk.js")
```

...`systemjs` trys to resolve it as if it were a module from npm:

```
system.src.js:80 Uncaught (in promise) Error: Fetch error: 404 
  Instantiating https://unpkg.com/lib/thunk.js
  Loading https://unpkg.com/cwise-compiler
```
see: activewidgets/getlibs#4

**Comment by bitstrider** [comment]
Still, it would be better if relative imports could be automatically recognized and mapped accordingly, so that we don't have to manually config based on trial-and-error.

Relative imports start with `./` so wouldn't that be enough to trigger an auto-mapping? Or would there be some side-effects?

**Comment by amenadiel** [comment]
It doesn't sound like a SystemJS issue.

You should request for a new custom config for cwise-compiler as the ones seen on https://github.com/activewidgets/getlibs/tree/master/config

While getlibs is based on SystemJS, and allows to use SystemJS methods to a certain extent, it isn't SystemJS purpose to deal with inner getlibs logic.

**Comment by guybedford** [comment]
Yes, SystemJS allows flexible resolution rules, but it is about how this fits with what getlibs is doing.
