### ISSUE TITLE
Module prefetching causes failure on conditional module loading

### ISSUE THREAD

**Issue by SaschaNaz** [systemjs/systemjs#1710]
http://plnkr.co/edit/pl7MH1jPzuL8jEAWcd1P?p=preview

```js
if (node) { // if node
  const mz = require("mz");
  // use the loaded module
}
else { // browser
  // do something for browser
}
```

This causes total failure on non-production mode SystemJS because it tries fetching "mz" first before actually executing the script. I hope prefetching won't breakdown everything.

**Comment by guybedford** [comment]
This is how the CommonJS loading in SystemJS works. You can use map configuration to disable requires - 

```js
System.config({
  map: {
    'mz': '@empty'
  }
});
```

**Comment by SaschaNaz** [comment]
That way my library will force users to set it manually every time. Can't SystemJS be more generous so that it can prevent throwing on prefetching step?

**Comment by guybedford** [comment]
You could make the require undetectable to SystemJS in the code with a variation like:

```js
const mz = require("mz" || null);
```

**Comment by SaschaNaz** [comment]
I did ``require(`mz${""}`)`` but as a workaround.
