### ISSUE TITLE
__dirname is broken when page URL starts with `file:///`

### ISSUE THREAD

**Issue by saschanaz** [systemjs/systemjs#1711]
SystemJS in local environment fails to get correct __dirname. It becomes `/C:/...` when it should be `file:///C:/...` (absolute) or just `/` (relative).

On MSEdge:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <script src="https://rawgit.com/systemjs/systemjs/master/dist/system.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", async () => {
            const __dirname = await System.import("systemjsrepro.js");
            h2.textContent = `__dirname: ${__dirname}`
        });
    </script>
</head>

<body>
    <h2 id="h2">__dirname?</h2>
</body>

</html>
```

```js
// systemjsrepro.js
module.exports = __dirname;
```

**Comment by guybedford** [comment]
`file://C:/...` is not a valid file URL - it should be `file:///C:/..`.

Try loading that URL and let me know if that works ok?

**Comment by SaschaNaz** [comment]
@guybedford Ah yes, it actually was `file:///C:/...`. It still gives a wrong value.

**Comment by guybedford** [comment]
I'm not sure I follow how that could be possible. The code at https://github.com/systemjs/systemjs/blob/master/src/format-helpers.js#L166 is designed to strip the `file:///` part correctly in windows leaving a `c:/...` path. Perhaps you can help get a replication here.

**Comment by SaschaNaz** [comment]
It seems the wrong `isWindows` value is the problem. This works: `(typeof process !== 'undefined' && typeof process.platform === 'string' && process.platform.match(/^win/)) || (typeof navigator !== "undefined" && typeof navigator.platform === "string" && navigator.platform.match(/^Win/))`

**Comment by guybedford** [comment]
Thanks for spotting that and the PR. Rather than changing the `isWindows` code to detect the browser environment I think it would be better to alter the `stripOrigin` function to work with both path styles based on detecting `/^file:///[a-z]\:/i`.

**Comment by SaschaNaz** [comment]
I think the detection itself is robust, the problem is the current `stripOrigin` function gets wrong `isWindows` value so it creates Linux-style path. (`/dev/...`)

**Comment by guybedford** [comment]
@SaschaNaz I understand, but I don't want to be doing OS environment in the browser at all in SystemJS.

**Comment by guybedford** [comment]
(Hence, why I'm suggesting a more flexible approach with the regex)
