### ISSUE TITLE
js extension missing

### ISSUE THREAD

**Issue by MovGP0** [systemjs/systemjs#1712]
I have the following configuration: 

**systemjs.config.js**
```javascript
(function(global) {
    System.config({
        baseURL: '/', 
        defaultJSExtensions: true,
        paths: {
            // paths serve as alias
            '@angular': 'node_modules/@angular', 
            'npm:': "node_modules/", 
            "*": "*.js",
        },
        map: {
            '@angular/core': '@angular/core/bundles/core.umd.js',
            '@angular/common': '@angular/common/bundles/common.umd.js',
            '@angular/compiler': '@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': '@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': '@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': '@angular/http/bundles/http.umd.js',
            '@angular/router': '@angular/router/bundles/router.umd.js',
            '@angular/forms': '@angular/forms/bundles/forms.umd.js',
            'rxjs': 'npm:rxjs'
        },
        packages:  {
            rxjs: {
                defaultExtension: 'js'
            }, 
            main : {
                defaultExtension: 'js'
            }
        }
    });
})(this);
```
because of the `defaultJSExtensions: true` and the ` "*": "*.js"` path I expect that everything that cannot be found gets an .js attached and tried again. unfortunately this doesn't seem to be the case. 

When executing `System.import("main");` I get an 404 when SystemJS tries to `GET https://localhost:443/main` instead of  `GET https://localhost:443/main.js`. 

I am wondering if this is a bug or a faulty configuration.

**Comment by guybedford** [comment]
If you define your baseURL as a package with `defaultExtension: 'js'` then you can still get this support.

`defaultJSExtensions` and a `*: *.js` path are no longer supported as of SystemJS 0.20. The intention is that extensions should be included, just like it is necessary for module scripts in browsers.
