### ISSUE TITLE
Network load order

### ISSUE THREAD

**Issue by archpollux** [systemjs/systemjs#1715]
Why does SystemJS always load the requested dependency on import **first** and then its dependencies? With `scriptLoad: true` this fails, plus this is a deviation from how RequireJS works and I don't see the use. After name resolution, why can't SystemJS look at the `meta`, check `deps` and follow the tree right down to the leaves and then load in reverse order?

Before you ask, I'm using `scriptLoad: true` here because I am trying to get around a server that does not have CORS enabled and that I do not control.

**Comment by asapach** [comment]
@archpollux are you using [`depCache`](https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#depcache)? If not, it has no options other than walking the dependency tree.

**Comment by archpollux** [comment]
I just tried using that too, does not seem to change anything about load order.

**Comment by guybedford** [comment]
@archpollux dependencies need to be discovered to be loaded normally. `depCache` will allow parallel loading, but naming has to be done carefully using normalized names as keys to ensure it applies properly.

**Comment by guybedford** [comment]
Just let me know if you need further assistance here.
