### ISSUE TITLE
What happened to `dist/system.js` in 0.20.16?

### ISSUE THREAD

**Issue by mlc-mlapis** [systemjs/systemjs#1716]
I can't find any explanation why `dist/system.js` in 0.20.16 is not in a compressed format and its size is ~68kB while the same file 0.20.15 is just ~47 kB.

**Comment by guybedford** [comment]
Thanks, I've released a 0.20.17 with a fix.

**Comment by mlc-mlapis** [comment]
@guybedford 👍
