### ISSUE TITLE
Relative paths: SystemJS.import() vs SystemJS.register()

### ISSUE THREAD

**Issue by DavidKDeutsch** [systemjs/systemjs#1717]
When I call `SystemJS.import('./myFile')` from a module, the file is loaded from the baseUrl instead of relative to my module's location, which I have read is by design(?). However in the `register` call I use to define that module, dependencies declared in the same way (i.e. "./myFile") are indeed loaded relative to the module's location. Is there any way to tell SystemJS to use the same logic for `import()`? FWIW, I am dynamically loading modules at runtime, which is why I am using `import` instead of `register`.

**Comment by guybedford** [comment]
Try using `import()` instead of `SystemJS.import` within the ES module for the dynamic require, that will ensure that it is contextual to the module, as `SystemJS.import` is a top-level import function only.

**Comment by DavidKDeutsch** [comment]
Hmm.. I'm actually using TypeScript with moduleKind set to "system," and the compiler has been giving me problems because I am trying to import a JSON file with a plugin, i.e. I _was_ using `SystemJS.import('./myFile.json!json')`, and I changing that to use various combinations of `import('./myFile.json')`, and the TypeScript compiler could not resolve it.

Putting the compile-issue aside, the JS code generated by the TypeScript compiler was along the lines of: 

    System.register(["dependency1", "./dependency2"], function (exports_1, context_1) {
       context_1.import('./myFile.json!json');
    }

However, `context_1.import` is not defined. Anything obvious that I am doing incorrectly?

**Comment by guybedford** [comment]
@DavidKDeutsch which version of SystemJS are you using? If `context_1.import` is not defined that may be an older version of SystemJS.

**Comment by DavidKDeutsch** [comment]
Ah, looking at the SystemJS repo history, that seems to be exactly the case; I am using version 0.19.46, as that is what the latest (non-beta) version of JSPM (0.16.53) depends on. Given how new I am to the whole SystemJS/JSPM ecosystem, I'm probably going to wait until 0.17 is stable (it has been in beta for over 7 months, so hopefully that is soon!). Thanks for solving the mystery!
