### ISSUE TITLE
[Help] System JS is not loading a module from NodeJs

### ISSUE THREAD

**Issue by minuz** [systemjs/systemjs#1718]
Hi All, 

I'm trying to use the URL module from NodeJs - https://nodejs.org/dist/latest-v8.x/docs/api/url.html
and SystemJs is not able to load it.

Not sure what am I doing wrong.

Within my Angular component, I tried to load as 
`import * as url from 'url'`

The `@types/node` seems to accept that and I get no compilation errors. However, when trying to execute, it throws:

> 1:313 Error: Unexpected token <
  Evaluating http://localhost:5000/Ng/Index/url
  Evaluating http://localhost:5000/ng/documentAnalysis/extracted-matches/dashboard.component.js
  Evaluating http://localhost:5000/ng/documentAnalysis/extracted-matches/extracted.matches.module.js
  Evaluating http://localhost:5000/ng/documentAnalysis/document.analysis.module.js
  Evaluating http://localhost:5000/ng/caseManagement/case.management.module.js
  Evaluating http://localhost:5000/ng/app.module.js
  Evaluating http://localhost:5000/ng/main.js
  Loading ng/main.js
    at eval (<anonymous>)
    at evaluate (system.src.js:2822)
    at system.src.js:3621
    at dynamicExecute (system.src.js:1145)
    at doEvaluate (system.src.js:1092)
    at ensureEvaluate (system.src.js:1000)
    at system.src.js:1018
    at Object.eval (dashboard.component.ts:4)
    at eval (dashboard.component.ts:12)
    at eval (dashboard.component.ts:12)

I did a simple test using Angular-cli which uses Webpack, the same code works absolutely fine.
Unfortunately I cannot switch to the angular-cli at this stage and I need to rely on SystemJs for dev mode.

Any ideas?

**Comment by guybedford** [comment]
Try loading `@node/url` instead here.
