### ISSUE TITLE
SystemJS@0.20 fails to load lodash/defaults. Requiring a module which exports undefined.

### ISSUE THREAD

**Issue by AlbertWillemsen-Centric** [systemjs/systemjs#1719]
This used to work in 0.19.

First of, I load bluebird as Promise polyfill before systemjs.

Because of bluebird the `module.exports` is set to `undefined` in `./_Promise.js` which is expected.
So the result of the `require("./_Promise")` is also expected to be `undefined`.

But instead the output of this require call is:
```
l {Symbol(): Object}
	default: (...)
	__useDefault: (...)
	Symbol(): Object
	get default: function ()
	get __useDefault: function ()
	__proto__: Module
```

**Comment by guybedford** [comment]
@AlbertWillemsen-Centric could you share a test case here for me to look into further? Ideal is a plunkr, followed by a git repo or zip file that doesn't require an npm install.

**Comment by AlbertWillemsen-Centric** [comment]
Hi @guybedford ,

thanks for that tip.
I'm trying to isolate the problem.
When I strip my project to the bare essentials of the bug, it doesn't seem to occur.
So I'm still looking into it.

**Comment by AlbertWillemsen-Centric** [comment]
latest 0.20.18 version seems to fix this issue.
