### ISSUE TITLE
Cache Busting Extension

### ISSUE THREAD

**Issue by justinbmeyer** [systemjs/systemjs#172]
Related from https://github.com/bitovi/steal/issues/129, would you consider adding a cache-busting extension to SystemJS?  This would allow someone to specify a build number and every URL would include a  `?buildNumber=123123` to make sure nothing would be cached.

**Comment by amcdnl** [comment]
@guybedford I noticed when you use this with plugins it appends `.js` to the end.  For example when used with the json plugin I get:

     GET http://localhost:9000/dist/app/routes.json.js?bust=3 404 (Not Found)

    es6-module-loader.src.js:139 Potentially unhandled rejection [3] Error loading "app/routes.json!bower_components/plugin-json/json" at http://localhost:9000/dist/app/routes.json.js?bust=3
    Error loading "app/routes.json!bower_components/plugin-json/json" from "app/app" at http://localhost:9000/dist/app/app.js?bust=3434
    Not Found: http://localhost:9000/dist/app/routes.json.js?bust=3 (WARNING: non-Error used)

**Comment by guybedford** [comment]
Perhaps just add path exceptions to the rule? If the extension is json don't add a cache bust parameter?

**Comment by guybedford** [comment]
I've moved this to a loader extension example at https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader#custom-extension-example---cache-busting-extension.

**Comment by amcdnl** [comment]
Heres what I ended up implementing:  https://github.com/amcdnl/systemjs-test/blob/master/index.html#L40

Its not the most ideal but works for now.

**Comment by AlexKey** [comment]
+1

**Comment by lookfirst** [comment]
I agree with what @amcdnl came up with, but I really think this should be part of SystemJS. It is one of those things that would be really nice to have as part of using this library and not have to worry about maintaining a separate extension for it.

**Comment by guybedford** [comment]
We could potentially still do this with extension in the next SystemJS that would allow querystrings to be defined through meta configuration:

```javascript
System.config({
  modules: {
    '*': {
      suffix: '?cache-bust'
    },
    'some/package': {
      suffix: '-f89sd8ds8g'
    }
  }
});
```

The first case would work for query strings, the second for files that were renamed with hashes.

**Comment by djindjic** [comment]
I have had some research about cache busing few months ago and just want to add something I haven't seen in discussion above.
It's better to hash-rename file instead of adding query string because some proxy servers don't cache querystring urls
Here is an blog post with example:
http://www.stevesouders.com/blog/2008/08/23/revving-filenames-dont-use-querystring/

**Comment by amcdnl** [comment]
@guybedford I like the suffix approach :+1:

**Comment by lookfirst** [comment]
@djindjic That is terribly old advice, proxy servers pay attention to HTTP headers.

Myself and @stickfigure had a good discussion on this thread over on the requirejs issue tracker a few years ago: https://github.com/jrburke/requirejs/issues/376 I must admit, it really sucks having to maintain a fork of requirejs.

**Comment by lookfirst** [comment]
@guybedford Looks good.

**Comment by lookfirst** [comment]
@guybedford reopen this issue?

**Comment by whitecolor** [comment]
```javascript
System.config({
  modules: {
    '*': {
      suffix: '?cache-bust'
    },
    'some/package': {
      suffix: '-f89sd8ds8g'
    }
  }
});
```

in this case `?cache-bust` should be added after file extension,and `f89sd8ds8g` before it. This probably could be useful. This maybe usefull. Better to implement cache-busting extension as a plugin to systemjs-builder that will add needed config while/after build process.

**Comment by carlosagsmendes** [comment]
Are there similar hooks in the bundling process? I'm considering applying hashes to bundles (by generating a hash for each bundle file), and then create a map from the original name to the (bundle) name with the hash.

Thanks

**Comment by whitecolor** [comment]
@carlosagsmendes after build there is bundle data in memory, though there is no `css` bundle data.

**Comment by carlosagsmendes** [comment]
Thanks. But aren't the files (including css) bundled together?

**Comment by whitecolor** [comment]
@carlosagsmendes
you can separate css https://github.com/systemjs/plugin-css#build-example

**Comment by guybedford** [comment]
@carlosagsmendes it's advisable to run SystemJS builder manually in cases like this and injecting your own bundle config. The `trace` API is easy to inject into a bundle. That is in https://github.com/jspm/jspm-cli/blob/master/lib/bundle.js#L127.

**Comment by szepeviktor** [comment]
Please avoid GET parameters, use `javascript.min.012.js`
```apache
    # filename revisioning
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.+)\.(\d\d+)\.(js|css|png|jpg|gif)$ $1.$3 [L]
```

**Comment by carlosagsmendes** [comment]
@guybedford could you please further explain the latest release notes for the builder? I'm sorry, but I can't grasp the following phrases:

All bundles now contain fully-normalized dependencies. 

This restricts production-time mappings, but means that map config is not needed at all in production unless dynamic normalization and loading scenarios are required. 

Thanks in advance

**Comment by OliverJAsh** [comment]
Related requirement: https://github.com/jspm/jspm-cli/issues/412#issuecomment-93704188

**Comment by szepeviktor** [comment]
@OliverJAsh Isn't rewriting a good practice?
https://github.com/systemjs/systemjs/issues/172#issuecomment-91930901

**Comment by oricalvo** [comment]
I created a small gulp task + SystemJS extension that may help with correcty reload module files that were changed without totally disabling browser cache. The gulp task calculates the hash value for each file and the extension is responsible for adding the hash value into each SystemJS loader request. Take a look at https://github.com/oricalvo/systemjs-cachebuster

**Comment by stajs** [comment]
So what is the best way to cache bust? It seems like the [proposed solution](https://github.com/systemjs/systemjs/issues/172#issuecomment-75236888) was never implemented and the issue is closed now.

For others looking for a solution, [this way](http://vadosware.com/2015/05/17/cache-busting-with-systemjsaurelia/) worked for me:

```javascript
var systemLocate = System.locate;
System.locate = function (load) {
	var System = this;
	return Promise.resolve(systemLocate.call(this, load)).then(function (address) {
		return address + System.cacheBust;
	});
};
System.cacheBust = '?v=' + version;
```

**Comment by oricalvo** [comment]
The problem with above solution is that each module has the same version number. This means that all modules are reloaded each time there is a new change in a single module. My proposed solution is to calculate the hash for each module separately (quite standard solution) and then attach it to the appropriate module. In a way, my solution is quite the same as above but a bit more accurate.

**Comment by stajs** [comment]
@oricalvo Yes, totally agree with you: hashes are a better solution overall. It's just an alternative for others who aren't using gulp. It could be extended to use hashes, and for my case a system wide version is okay for now.

**Comment by szepeviktor** [comment]
You can put version number/hash in three places

1. file name
2. dir name
3. GET parameter

3. is not CDN friendly, 1. is complicated.
2. is used at companies like Google.

Actually 1. also: https://www.google.com/images/nav_logo242.png

**Comment by OliverJAsh** [comment]
@oricalvo I did what you were saying using the API here: https://github.com/jspm/jspm-cli/issues/412#issuecomment-93995362

**Comment by mbrowne** [comment]
For those who are just looking for an easy way to prevent caching in development, I recommend using [lite-server](https://github.com/johnpapa/lite-server). By default, it will serve JS files with `Cache-control` `max-age=0` so that you don't need to do any additional cache-busting unless you need it in production for some reason. Note that `lite-server` will also automatically reload your browser when you make code changes.

Tip: By default, lite-server looks for changes to any .JS files in your project, which might cause your browser to reload twice anytime you make changes if SystemJS is configured to create any bundles in development. To avoid this, you can tell lite-server to monitor only the bundle file by using a line like this in lite-server's config file: `"files": ["build.js"]`. I'm sure there are plenty of other ways to achieve a similar development workflow, but lite-server worked for me easily so I thought I'd share this.

**Comment by Clay-Ferguson** [comment]
Can some one please say what the final disposition of this was? I need to do the cache busting. I tried this:

   ```
 var systemLocate = System.locate;
    System.locate = function(load) {
          return Promise.resolve(systemLocate.call(this, load)).then(function(address) {
    return address + '?bust=...';
  });
}
```
and it doesn't have any effect at runtime. Is there some special way to turn on the 'locating' thing?

**Comment by guybedford** [comment]
In SystemJS 0.20 this can be handled via:

```javascript
let resolve = System[System.constructor.resolve];

System[System.constructor.resolve] = function (key, parentKey) {
  return resolve.call(this, key, parentKey).then(function (resolved) {
    return resolved + '?cache';
  });
};
```

**Comment by jjtron** [comment]
I tried the above, but I must be doing something wrong. Does the code go in the 'systemjs.config.js' file? Or right before 'System.import'? Or somewhere else?

**Comment by Clay-Ferguson** [comment]
@jjtron I haven't tried Guy's code above yet (from 2 days ago), but what I had already gotten done is I just hack the SystemJS source file to read a global variable 'systemJsCacheBuster'.  Arguably ugly but works.

```js
function fetchFetch(...
....
if (systemJsCacheBuster) {
	  url += systemJsCacheBuster;
  }
```

This issue is an extremely important thing for SystemJS to solve and as i just showed the solution doesn't have to be difficult. I hope Guy changes his mind and makes this a 'feature'. IMO 99% of developers are going to need this, for actual production use.

**Comment by CNSKnight** [comment]
I did just try @guybedford resolve override, but System.JS chokes silently after returning the first `+='cache'` resolved path. Returning undecorated path from the same then() works just fine.

**Comment by guybedford** [comment]
@CNSKnight the approach has been explored a bit more in https://github.com/systemjs/systemjs/issues/1616, and there are some issues with it in SystemJS 0.20 unfortunately. There's an approach at https://github.com/systemjs/systemjs/issues/1616#issuecomment-289268010 which may work here as an alternative.

**Comment by ryanrain** [comment]
after trying a few of the approaches above, i found that by far the simplest way to cache bust an "older" angular 2 app was to simply add version info to the folder name.
