### ISSUE TITLE
SystemJS interprets Flow "import type" comments (should ignore them)

### ISSUE THREAD

**Issue by lll000111** [systemjs/systemjs#1721]
SystemJS 0.20.17

In a test file I have [Flow type annotations using comments](https://flow.org/en/docs/types/comments/) (a Flow feature for files that I don't want to have to transpile), and one comment is a type import:

```
/*::
import type {KeyValueMapObj} from '../lib/object-recipes.js.flow';
 */
```

Unfortunately SystemJS interprets this as an ES6 import and complains that there is no transpiler plugin configured - which is not actually needed.

Since SystemJS seems to interpret the same comment syntax, at least it should ignore `import type` import statements - they are for Flow types, not for modules.

**Comment by guybedford** [comment]
Sure thanks for posting, I've updated the regex in https://github.com/systemjs/systemjs/commit/eacc8c809b195acbe349023a3ce4c4d78bc1d2b1.
