### ISSUE TITLE
Apply to MOSS financial support for ASM implementation

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1723]
Webpack has been [awarded USD 125.000 from MOSS foundation](https://medium.com/webpack/webpack-awarded-125-000-from-moss-program-f63eeaaf4e15) to implement ASM modules.

SystemJS already has experimental support for these modules. @guybedford have you considered [applying for this financial support](https://www.mozilla.org/en-US/moss/)? I feel this project, along with JSPM were pioneers in ASM support and therefore deserve this endorsement and support way more than webpack does.

Also any endorsement from MOSS will contribute bringing more awareness of these amazing tools.

**Comment by ArmorDarks** [comment]
I don't know how others, but I'd be happy to make small donations each month to sustain focused development and maybe bring some additional talented helping hands to project. Unfortunately, there seems to be no Patron account or anything like that...

I dunno, Kickstarter?

**Comment by guybedford** [comment]
@amenadiel I'm certainly be considering applying for this grant or running an open collective or both, although want to reach certain milestones first.
