### ISSUE TITLE
I set a path defaultExtension with 'js',but when load 'abc.css' the SystemJs try load to 'abc.css.js',it caused 'abc.css' not found.

### ISSUE THREAD

**Issue by mokeyish** [systemjs/systemjs#1726]

**Comment by AlbertWillemsen-Centric** [comment]
Did you install the css loader and add:
```
SystemJS.config({
...
	meta: {
...
		"*.css": {
			"loader": "css",
			"defaultExtension": false
		},
...
```
to your jspm.config.js?

**Comment by mokeyish** [comment]
@AlbertWillemsen-Centric Thinkyou for your answer,I think I lost the 'defaultExtension:false',I thought there was regular expression path to configure the default extensions,but I found nothing help in the document.I'll try as you said later.

**Comment by AlbertWillemsen-Centric** [comment]
This is how i use it, so it should work.
