### ISSUE TITLE
Various documentation problems

### ISSUE THREAD

**Issue by drjayvee** [systemjs/systemjs#1728]
I started learning and toying with SystemJS but ran into various problems which caused huge headaches. I got extremely frustrated after two days of trying to build even a very simple repo with just two tiny modules.

I decided to write a ticket to detail my experience in the hopes that it may help improving the documentation. I'd be glad to write PRs if we can agree on which bits of doc might use some changes or additions.

## defaultExtension ##
The first issue was `.js` extensions for modules. I was trying to convert [my experiment project](https://github.com/drjayvee/es6-util/tree/systemjs) from build-compiled using babel to SystemJS. I was using modules names _without_ extensions.

After a bit of reading, I saw the `packages` configuration allows specifying a `defaultExtension`. Adding that made everything work in dev - great!

Next I wanted to try and create a build. The build proces itself (using systemjs-builder) was easy enough to understand (but I ran into huge problems later). However, when I tried to use the same `System.config` together with `system-production.js`, I got an error:
`TypeError: The SystemJS production build does not support the "packages" configuration option.`
Well that's unexpected! Maybe the Builder adds `.js` to every module name? But how am I supposed to use the same initialization (`System.import('main');`) in dev and production in files that don't get built?

Looking at a bundle, it seems the Builder also didn't think it through entirely:
`System.register("js/widgetParent.js", ["js/oop", "js/widget"], ...`
So the module name includes the extension, but the dependencies don't?

[This tutorial](https://superdevelopment.com/2016/03/16/a-dive-into-systemjs-part-1/) taught me about normalized names, but the [SystemJS.register](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemjsregistername--deps-declare) and [es-module-loader](https://github.com/ModuleLoader/es-module-loader/blob/v0.17.0/docs/system-register.md) documentation are inconsistent about normalized names vs names. Even the [Loading Bundles](https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#loading-bundles) doc is inconsistent (or at the least very confusing) about extensions in module names.

Oh well, let's add `.js` for now.

## Build - which transpiler? ##
Now I'm creating a distribution build like so ([full source](https://github.com/drjayvee/es6-util/blob/systemjs/build.js)):
```js
var builder = new Builder({
  map: {
    'plugin-babel':          'node_modules/systemjs-plugin-babel/plugin-babel.js',
    'systemjs-babel-build':  'node_modules/systemjs-plugin-babel/systemjs-babel-browser.js'
  },
  baseURL: path.resolve('src')
});
```
Now I get a new Error in the browser:
`Error: $traceurRuntime is not defined`
Where did that come from? Why does SystemJS need traceur runtime when transpiling using babel?

Turns out the default is traceur (?), even though this same configuration uses `plugin-babel` in dev. The [SystemJS Builder documentation](https://github.com/systemjs/builder#basic-use) doesn't provide a hint, and even mentions that `babel-core` needs to be installed separately. Finally, even [plugin-babel](https://github.com/systemjs/plugin-babel/blob/master/README.md#building-and-bundling) doesn't tell me that I need to explicitly specify `transpiler: "babel"` in the configuration.

This alone cost me hours of searching for solutions. :( I did find several issues on GitHub and StackOverflow that pointed me in the right direction, but this was highly confusing.

## Babel building ##
So now I try again with
```js
builder.config({
  transpiler: 'babel',
  map: {
    'systemjs-babel-build': 'node_modules/systemjs-plugin-babel/systemjs-babel-node.js'
  },
  baseURL: path.resolve('src')
});

Promise.all([
  builder.bundle('js/* - [js/tabView.js]', 'dist/js/common.js', bundleOptions),
  builder.bundle('[js/tabView.js]', 'dist/js/tabView.js', bundleOptions),
  builder.bundle('[main.js]', 'dist/main.js', bundleOptions)
]).then(...)
```
I get this error:
```
Error on translate for js/main.js at file:///home/jay/public_html/systemjs-tehst/src/js/main.js
        (SystemJS) ENOENT: no such file or directory, open '/home/jay/public_html/systemjs-tehst/src/babel'
        Error: ENOENT: no such file or directory, open '/home/jay/public_html/systemjs-tehst/src/babel'
            at Error (native)
        Error loading /home/jay/public_html/systemjs-tehst/src/babel
        Unable to load transpiler to transpile /home/jay/public_html/systemjs-tehst/src/js/main.js]
```
Why is the builder trying to find `src/babel`?

I've actually tried lots of stuff, and another error I got regularly was
```
Build error
{ [Error: Error on translate for js/main.js at file:///home/jay/public_html/systemjs-tehst/src/js/main.js
        (SystemJS) exports is not defined
        ReferenceError: exports is not defined
            at /home/jay/public_html/systemjs-tehst/node_modules/babel-core/lib/api/node.js:3:1
            at Object.exports.runInThisContext (vm.js:54:17)
        Evaluating /home/jay/public_html/systemjs-tehst/node_modules/babel-core/lib/api/node.js
        Error loading /home/jay/public_html/systemjs-tehst/node_modules/babel-core/lib/api/node.js
        Unable to load transpiler to transpile /home/jay/public_html/systemjs-tehst/src/js/main.js] originalErr: [ReferenceError: exports is not defined] }
```

I've also tried building with jspm CLI but can't get it to find modules, probably because it's not using a baseURL or something. I've tried and tried but the error messages don't help to fix the problem. I was already really frustrated and so I didn't spend too much trying to get this to work.

## Conclusion ##
SystemJS looks like a fantastic solution. It's modern (based on the ES6 module loader spec), supports both bundling and async loading, and doesn't even need watcher builds in dev. Really good stuff.

Unfortunately, in my humble opinion, the build&bundle documentation is a little bare bones and sometimes really confusing or inconsistent. As I said above, I'd be glad to help to straighten this out!

If you want to give it a go, [clone this repo](https://github.com/drjayvee/es6-util/tree/systemjs) (checkout the systemjs branch) and run `npm install && node build`.

**Comment by guybedford** [comment]
Thanks for sharing your experience. It really helps to hear, and assistance in smoothing the documentation of these workflows to make life easier getting started would be amazing. My own priority is to the continual convergence of the project, over ensuring the best possible user experience for the project as it sits today, at least until it is finished. SystemJS has been an evolving project over a long time, so techniques have changed and moved based on the constraints the project has had to deal with, while the workflows are still themselves converging. I think some of the new builder work coming towards the end of this year should make the new vision clearer, but in the transition right now certainly it might be tricky to understand how it all fits together.

> Looking at a bundle, it seems the Builder also didn't think it through entirely:
> System.register("js/widgetParent.js", ["js/oop", "js/widget"], ...
> So the module name includes the extension, but the dependencies don't?

In this case, you can set `normalize: true` as a build option to get what you were expecting. The tricky thing here from an architecture point of view is that what most users would want s partial normalization - that is certain things fully normalized, but things that are dynamic in production remaining unnormalized. Working out this boundary is not straightforward... but new techniques are acoming.

> Build - which transpiler?

We should probably deprecate Traceur entirely as it is long past its support window. Babel or Typescript would be the answer!

> Babel building

The setup to follow for Babel is exactly the readme steps here - https://github.com/systemjs/plugin-babel#usage.

Let me know if that answers some of your questions, and suggestions welcome on how things could be more clearly presented.

**Comment by drjayvee** [comment]
Thank you for taking the time to respond!

I very much agree that the priority should be getting the project ready for production use, and worry about guides and documentation later.

If you want, send me a message once you want to tackle documentation. I'd very much like to contribute to this project and might be the target audience (familiar with ES2015 modules, synchronous and asychronous loading; but not with differences between transpilers or their internals).

I've given building another shot. This configuration:
```js
builder.config({
  transpiler: 'plugin-babel',
  map: {
    'plugin-babel': path.resolve('node_modules/systemjs-plugin-babel/plugin-babel.js'),
    'systemjs-babel-build': path.resolve('node_modules/systemjs-plugin-babel/systemjs-babel-browser.js')
  },
  baseURL: path.resolve('src')
});
```
leads to this error:
```
{ [Error: Error on translate for js/oop.js at file:///home/jay/public_html/es6-playground/src/js/oop.js
        (SystemJS) Unable to calculate canonical name to bundle /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/babel-helpers/. Ensure that this module sits within the baseURL or a wildcard path config.
        Error: Unable to calculate canonical name to bundle /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/babel-helpers/. Ensure that this module sits within the baseURL or a wildcard path config.
            at getCanonicalNamePlain (/home/jay/public_html/es6-playground/node_modules/systemjs-builder/lib/utils.js:227:13)
            at getCanonicalName (/home/jay/public_html/es6-playground/node_modules/systemjs-builder/lib/utils.js:150:19)
            at Object.<anonymous> (/home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/plugin-babel.js:25:31)
            at /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/plugin-babel.js:224:4
            at /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/plugin-babel.js:225:3
            at Object.exports.runInThisContext (vm.js:54:17)
        Evaluating /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/plugin-babel.js
        Error loading /home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/plugin-babel.js
        Unable to load transpiler to transpile /home/jay/public_html/es6-playground/src/js/oop.js]
  originalErr: [Error: Unable to calculate canonical name to bundle file:///home/jay/public_html/es6-playground/node_modules/systemjs-plugin-babel/babel-helpers/. Ensure that this module sits within the baseURL or a wildcard path config.] }
```
I have no idea how to configure `map` or `path` (or anything else) in such a way that `system-babel-build` can find its dependencies (which is what I think the problem is here).
