### ISSUE TITLE
Get module names from a bundle

### ISSUE THREAD

**Issue by mciureanu** [systemjs/systemjs#1730]
Sorry, this is more like a question than an issue. I can't find a way to get the module names from a bundle file. What I try to achieve is to load a bundle file dynamically, and to list all modules from that bundle, because based on some convention I could load the "root" module.  I thought that maybe noticing what modules have been added from the load call might be a way to solve this, but I couldn't figure out how to do that either.

**Comment by guybedford** [comment]
There isn't any way to do this as the bundle name definitions aren't related to their parent bundle internally. Perhaps try using the `bundles` configuration with a dynamic import that loads a specific module from the bundle. Trying to think in terms of importing modules, not bundles.
