### ISSUE TITLE
Same domain (native) fetch requests don't send cookies

### ISSUE THREAD

**Issue by frenkie** [systemjs/systemjs#1731]
In SystemJS@0.20 the native fetch method is preferred over XMLHttpRequest when available.
A difference between the two is that XMLHttpRequest always sends cookies on same domain requests. For the fetch method this has to be [explicitly configured as an option](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included). Currently, SystemJS only sets a value for this option for authorization requests, but a default value allowing only 'same-origin' is needed I think.

We currently have issues with using SystemJS in an admin environment with cookie authentication which is redirecting all our SystemJS requests to a login page.

**Comment by guybedford** [comment]
We're aiming to follow the browser loader defaults here, which I don't believe includes credentials by default for `<script type="module">` in browsers, so we should do the same.

Can you not get the correct behaviour here to work through `meta` configuration such as `meta: { '*': { authorization: true } }`? If not, perhaps we can extend the meta configuration to handle this case properly.
