### ISSUE TITLE
ESM __useDefault with Proxy objects broken?

### ISSUE THREAD

**Issue by felixrabe** [systemjs/systemjs#1732]
Hi there

I've been puzzled by the `System.import()` behavior (0.20.18) when using a Proxy object as an ESM module's __useDefault.

I've put up a minimal example at https://github.com/felixrabe/e-112-systemjs-proxy/ that contrasts the behavior with other similar types of `import` and the actual / expected output.

Did I find a bug or is there something I do not understand about using SystemJS with proxies?

**Comment by felixrabe** [comment]
Excerpt from the example: (see linked repo for full code)

    Promise.resolve()

      .then(() => SystemJS.import('./src/object'))
      .then(x => console.log('object:', x.default.hello))

      .then(() => SystemJS.import('./src/objectUseDefault'))
      .then(x => console.log('objectUseDefault:', x.hello))

      .then(() => SystemJS.import('./src/wrappedProxy'))
      .then(x => console.log('wrappedProxy:', x.default.x.hello))

      .then(() => SystemJS.import('./src/wrappedProxyUseDefault'))
      .then(x => console.log('wrappedProxyUseDefault:', x.x.hello))

      .then(() => SystemJS.import('./src/proxy'))
      .then(x => console.log('proxy:', x.default.hello))

      .then(() => SystemJS.import('./src/proxyUseDefault'))
      .then(x => console.log('proxyUseDefault:', x.hello))

      .catch(err => console.error(err))

Actual output:

    $ ./index.js
    object: world
    objectUseDefault: world
    wrappedProxy: world
    wrappedProxyUseDefault: world
    proxy: world
    TypeError: undefined property 'then'
        at Object.get (.../112-systemjs-proxy/src/proxyHandler.js!transpiled:12:19)
        at <anonymous>

Expected output:

    $ ./index.js
    object: world
    objectUseDefault: world
    wrappedProxy: world
    wrappedProxyUseDefault: world
    proxy: world
    proxyUseDefault: world

**Comment by felixrabe** [comment]
The only other dependency in the example is `systemjs-plugin-babel`. I've tested this on OS X 10.9 with node 8.4.0.

**Comment by felixrabe** [comment]
I've updated the [repository](https://github.com/felixrabe/e-112-systemjs-proxy) with sample code that gets the expected result in two ways:

-   By patching `SystemJS.import` (indexWithImportWorkaround.js, [importWorkaround.js](https://github.com/felixrabe/e-112-systemjs-proxy/blob/93fd12af97a0b3a317095985e14919a896dd3299/importWorkaround.js))

-   By adding a `then` property to the proxied object (indexWithProxyFix.js, [proxyUseDefaultWithFix.js](https://github.com/felixrabe/e-112-systemjs-proxy/blob/93fd12af97a0b3a317095985e14919a896dd3299/src/proxyUseDefaultWithFix.js))

**Comment by felixrabe** [comment]
I suspect this is rather an issue of using Proxies together with Promises.

**Comment by felixrabe** [comment]
In the project I'm working on, I'm now using a Proxy handler that special-cases 'then':

    const handler = {
      get: (t, n, p) => {
        if (n in t) {
          return t[n]
        } else if (n === 'then') {
          return undefined
        } else {
          throw new TypeError(`undefined action "${n}"`)
        }
      },
    }

    const actions = new Proxy({}, handler)

(This is for use with Redux actions.)

**Comment by guybedford** [comment]
It does sound like this might be the interaction with `then`. Promises do this - see https://github.com/tc39/proposal-dynamic-import/issues/48 for recent spec discussion here too.
