### ISSUE TITLE
Revisit esmRegEx for new export proposals / dynamic import

### ISSUE THREAD

**Issue by typhonrt** [systemjs/systemjs#1733]
@guybedford perhaps it is time to revisit the [esmRegEx](https://github.com/systemjs/systemjs/blob/9e87f004339b3ee60dc8bec8750957bf5d9266a2/src/instantiate.js#L418) to add support for these two proposals: [proposal-export-default-from](https://github.com/tc39/proposal-export-default-from) and [proposal-export-ns-from](https://github.com/tc39/proposal-export-ns-from) as these are being used now via babel transforms and are stage 1 & 2 respectively. While at it perhaps supporting dynamic imports would be useful to add to the regex as well.

I too use the esm regex in my complexity analysis module ([typhonjs-escomplex](https://github.com/typhonjs-node-escomplex/typhonjs-escomplex)) and documentation tool ([TJSDoc](https://github.com/typhonjs-node-tjsdoc/tjsdoc)) and grabbed an earlier version of the SystemJS esmRegEx to detect ES Modules to set the Babylon sourceType parameter when parsing AST. 

An issue was filed against typhonjs-escomplex recently regarding multi-line detection (but the regex just doesn't cover it): https://github.com/typhonjs-node-escomplex/typhonjs-escomplex/issues/7

I setup two regex101 test cases for the old syntax (snagged from SystemJS over a year ago):
https://regex101.com/r/dp5qhA/3/

and the current SystemJS syntax:
https://regex101.com/r/OtEEhg/1/

Several test cases are included in the tester including the new proposals and dynamic imports none of which are detected by the current regex.

It should be noted that the current SystemJS syntax has a regression for compound imports like: `import v, { x, y as w } from "mod";` This seems to be due to location of `space` changes:
`[^"'\(\)\n; ]` (addition of ' ' in character set) and removal of space between `\s*` & `(` in the following segment `export\s*(\{|default|function|class|var|const|let|async\s+function))`.

It's possible to add naive support for dynamic imports by adding `\(` to the first character set after import: `(import\s*([\('"]`. This will match any line starting with `import(` but doesn't work when the statement is later in the line such as `const myModule = await import('...');` or in a Promise on the same line, etc.

I couldn't immediately find a basic NPM module that provides an ES Module regex test, so I might create one so that it can be versioned and unit tests provided as the language syntax moves forward.

I'd be glad to hear your thoughts especially on dynamic import support and I can perhaps continue working on the regex to add support for the new export proposals.

**Comment by guybedford** [comment]
@typhonrt definitely it would make sense to have a carefully maintained regex here with proper unit tests. Support for export default from and export namespaces proposals should definitely be included as it seems like those have the right momentum at this point. As for dynamic `import()` note that this is permitted in scripts as well as modules so shouldn't be part of this detection.

If you are interested in creating a repo like this with the regex updates, SystemJS would definitely move to inlining that regular expression as part of its build process through Rollup if it were as simple as a `module.exports = /regex/`.

Feel free to add me as a contributor as well and I will gladly help out too.

**Comment by typhonrt** [comment]
@guybedford I've posted an initial repo: [typhonjs-esmregex](https://github.com/typhonjs-node-utils/typhonjs-esmregex)

I started with the current SystemJS `esmRegEx` value, but reverted the space changes mentioned above as that removes two regressions in the tests. I have yet to add the new proposal changes which will be done soon along with as many negative tests that are useful. Could you perhaps comment on the negative lookahead `(?!type)` and the purpose for it being in the current SystemJS `esmRegEx` value? I'm not exactly sure why it is there and if there is a purpose I want to add tests, etc.

Thanks for the pointer that dynamic import can be used in scripts!

**Comment by guybedford** [comment]
@typhonrt the negative lookahead is to avoid Flow typings matching - see https://github.com/systemjs/systemjs/issues/1721.

**Comment by typhonrt** [comment]
Excellent. I figured it was probably Flow related as I didn't pick up on anything particular with [Typescript / modules](https://www.typescriptlang.org/docs/handbook/modules.html) and it helps to have a specific reference with test cases as I'm going to be annotating exactly what the regex covers in documentation, etc.

Almost there. I think the next update sometime this week may even properly work with multi-line import statements. I'll post a note back here when things are done.

**Comment by calebboyd** [comment]
@typhonrt any update? I have the same use case, but would definitely appreciate the broader use as part of SystemJS

**Comment by typhonrt** [comment]
I kind of stepped back from OSS efforts for a bit, but I'll see if I can finish up this weekend. I am trying to find a multi-line regex solution which is a bit trickier. I'm pretty sure `[\s\S.]*` may be what is needed.

**Comment by guybedford** [comment]
A regex approach is no longer used in SystemJS 2.0, as translation is fully outsourced to plugin systems.

**Comment by porsager** [comment]
Congrats on the 2.0 release 👍 

Are there any parts of the extras that tries to do esm identification, or is it now required to specify up front?

**Comment by guybedford** [comment]
@porsager thanks!

The default build will just load System.register, falling back to AMD and global loading.

There's a simple Babel transform available for ESM at https://github.com/systemjs/systemjs-transform-babel, which runs through the transform extra. This doesn't currently do format detection and just transforms everything, but a format filter like 0.21 could be added easily, using a similar regex approach.

Feel free to open an issue up on that project to discuss further what would work best here.
