### ISSUE TITLE
append `index.js` to everything in directory

### ISSUE THREAD

**Issue by dlants** [systemjs/systemjs#1735]
Hi there!

I'm trying to use SystemJS to load my Purescript project... the project outputs a directory of CommonJS modules as follows:

```
output/
  App.Main/
    index.js
  App.View/
    index.js
  App.Events/
    index.js
```

What's more, all of the Purescript internal libraries are exposed the same way. The way these modules are then imported is by:

```
var App_Events = require("../App.Events");
var App_View = require("../App.View");
```

I would like to configure `SystemJS` so that every reference to the `output` folder is appended by `index.js`. This is possible in a per-package setting using `main`, but seeing as Purescript generates hundreds of such modules doing this is pretty impractical.

Is this something that's possible? What's your recommendation for dealing with a setup like this?

Thanks!

**Comment by guybedford** [comment]
If should be possible to do this with a custom resolver.
