### ISSUE TITLE
fetching not required file?

### ISSUE THREAD

**Issue by GongT** [systemjs/systemjs#1736]
I suddenly got an error: (I think I do not modify anything, include any dependency)
```
System.import('application/includes/dom.js')
->
Uncaught (in promise) Error: Fetch error: 404 Not Found
  Instantiating http://accounts.localhost.vm:3012/public/application/includes.js
  Loading application/includes
    at system.js:4
    at <anonymous>
```

there is no any `require` in `dom.js`      
why it try to load `includes.js`?

```js
System.version = "0.20.18 Dev"
System.getConfig().packages["http://accounts.localhost.vm:3012/public/application"] = {
  "defaultExtension": "js",
  "main": "index",
  "configured": false
}
System.getConfig().baseURL = "//accounts.localhost.vm:3012/public/"
System.getConfig().paths["application/"] = "application/"
```

```
# jspm depcache application/includes/dom.js
     Injecting the traced dependency tree for application/includes/dom.js...
     
       application/includes/dom.js
     
ok   Dependency tree injected
```

**Comment by GongT** [comment]
when I rename folder `includes` to `include`, problem resolved !

is `includes` something special?

**Comment by guybedford** [comment]
`includes` is on the `Array.prototype`, so this definitely sounds like a but that we're susceptible to that. What is the straightforward replication here? Just loading a module from a folder called `includes`, or is there some combination of dependency loading and configuration that makes this happen? Help replicating would be great.
