### ISSUE TITLE
support to use an Object to be a loader

### ISSUE THREAD

**Issue by lovetingyuan** [systemjs/systemjs#1738]
support use an object like `{ locate, fetch, translate, instantiate  }` as a loader? not just a string

**Comment by guybedford** [comment]
You can set a custom loader directly into the registry with:

```js
System.registry.set('my-loader', System.newModule({
  fetch: ...
}));
```

Let me know if that works for you?

**Comment by lovetingyuan** [comment]
thanks! It works! (I use v0.19.39, and I use `System.set`)
Systemjs is quiet interesting😁
