### ISSUE TITLE
"Cannot read property 'forRoot' of undefined" with many npm packages

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#1739]
I use **angular 4 + SystemJS + [ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap)** and things were fine until version **0.19.16**. After I upgraded **SystemJS** to **0.20.19**, I'm getting the following error in the line ```NgbModule.forRoot()```

> Cannot read property 'forRoot' of undefined

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppRoutingModule } from 'app/app-routing.module';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { App } from 'app/app';

@NgModule({
    imports: [
        BrowserModule,
        AppRoutingModule,
        NgbModule.forRoot(),
        StoreDevtoolsModule.instrument({ maxAge: 5})
    ],
    declarations: [App],
    bootstrap: [App],
})
export class AppModule
{
    constructor()
    {
    }
}
```

I tried many configurations in ```system.config``` like ```map``` and ```package``` thinking it is a module locating error. But keeps getting the same error.

Something has changed between the version **0.19.16 and 0.20.00** is causing this error. Or it may be that these third party packages is using **webpack** to generate **CJS** module that is not compatible with **systemjs** anymore. May be a breaking change as described in the [blog](http://guybedford.com/systemjs-alignment) and [spec meeting](https://github.com/nodejs/CTC/pull/60/files#diff-2b572743d67d8a47685ae4bcb9bec651R217).

Many packages that has the ```forRoot``` module importing pattern are broken currently. My conversation with the ```ng-bootstrap``` team shows some frustration with the **SystemJS** [in this ticket](https://github.com/ng-bootstrap/ng-bootstrap/issues/1858).

What is the solution to this issue? 

1. Should these packages (ng-bootstrap, ng2-bootstrap) be bundled with **SystemJS** builder, so it will have the right exports?
2. Is there any new **SystemJS** configuration which will solve the issue?
3. Shouldn't the ```forRoot``` be used at all, but import individual module from these packages?

**Comment by guybedford** [comment]
You can configure SystemJS to load these modules with named exports support via the `esModule: true` meta configuration:

```js
System.config({
  meta: { '*': { esModule: true } }
});
```

**Comment by varghesep** [comment]
I entered a bug in the [angular repo](https://github.com/angular/angular/issues/19313) regarding a dependency resolution problem.

I don't know whether it is related to ```SystemJS``` not loading the dependencies correctly in order, or the ```angular``` is failing to do that. The app works perfectly fine in the JIT mode.
