### ISSUE TITLE
meta > deps > .css neither confirms nor denies?

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#1740]

**Comment by CNSKnight** [comment]
I've not seen this specifically in existing issues:
Given:
```
meta: {
            'datatables-materialize': {
                deps: [
                    '/lib/datatables/media/css/dataTables.material.min.css',
                    'datatables.net'
                ]
            },
...
}
```

1. will ignore .min.css and not load datatables.net
2. if deps order flipped, will load datatables.net but yet ignore .min.css

Perhaps it is expected behavior that the loader will never receive non .js resolvables?

**Comment by guybedford** [comment]
What is the module format of "datatables-materialize" here? It does affect how the deps get interpreted, as deps will follow the loading method of the module format of the module loading it.

When you say it doesn't load, you mean there is not even a network request at all?
