### ISSUE TITLE
Plugin loader locate method is not called for all dependent files

### ISSUE THREAD

**Issue by Genata** [systemjs/systemjs#1741]
Hi, 

I'm trying to create plugin with locate method which should be called for each loaded file. This way I want to implement cache busting mechanizm for my application. 

I'm currently using system.js v0.20.16.

This is my plugin code (lib/cache-buster.js):
```javascript
(function(){
	function locate(load) {
		return load.address + "?ctag=12345";
	}
	
	exports.locate = locate;
})();
```

This is my configuration:
```javascript
meta: {
	"dist/*.js": {
		loader: "cacheBuster"
	}
},
map: {
	"cacheBuster": "lib/cache-buster.js",
}
```

I have this file called "dist/main.js": 
```javascript
define([
	'dist/myFolder/myFile1.js',
	'dist/myAnotherFolder/myFile2.js',
	'dist/myFolder/myFile3.js'
], function(){...});
```

If I run **System.import("dist/main.js").then(...)**, my plugin will get called for **"dist/main.js"**, but it is **NOT** called for **'dist/myFolder/myFile1.js'**, **'dist/myAnotherFolder/myFile2.js'** and **'dist/myFolder/myFile3.js'**. 

Could you please explain me, am I missing something, or this is a bug in System.js?

Thanks!

**Comment by AlbertWillemsen-Centric** [comment]
try removing `dist/` from you define in main or replace it by `./`

**Comment by guybedford** [comment]
The resolve hook should be a more reliable approach here in 2.0.
