### ISSUE TITLE
Can't load node core modules

### ISSUE THREAD

**Issue by hochopepa-codes** [systemjs/systemjs#1742]
I`m using Angular 4 with SystemJS. Seems that I can't load node core modules.

`import * as path from 'path';`

 or syntax with require does not work.

This is the error I get. `GET http://localhost:3000/path 404 (Not Found)` 

The problem is that I can't map path to those modules (path, fs, etc) because they are included in node executable and not in node_modules. 

I don't have much experience with SystemJS, I googled for this but didn't find any solution. Probably missing something simple (or not?) so I would appreciate if you could show me the process of loading node core modules.

Thanks

**Comment by AlbertWillemsen-Centric** [comment]
Have you used: 
```
jspm install path
```
