### ISSUE TITLE
getting global namespace of a global script file

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1744]
Hi @guybedford,

Is there a way to get the global namespace of a global script file?
For example, when I load this file: 

```js
// https://github.com/unional/global-store/blob/master/dist/global-store.es5.js
var GlobalStore = { get: ... }
```
using `systemjs.import()`, I get the object `{ get: ... }`.
I also need to get the name `GlobalStore`.
Is there a way to do that?

I'm working on [`domture`](https://github.com/unional/domture) and it needs to reconstruct the global namespace. i.e.

```ts
const dom = new Domture()

// uses `systemjs.import()` internally
dom.import('./node_modules/global-store/dist/global-store.es5.js')

dom.window.GlobalStore // should be created
```

**Comment by unional** [comment]
🤣 It is actually working... I don't need to do anything. Sorry for the noise.

**Comment by unional** [comment]
It turns out that it works for some files and not others.
e.g. this file doesn't work: https://github.com/unional/color-map/blob/master/dist/color-map.es5.js

**Comment by unional** [comment]
I debug in and found that `cjsExportsRegEx.exec(source)` returns `["(module.exports,", "module.exports,", undefined, ".exports", ","]` when execute against https://github.com/unional/color-map/blob/master/dist/color-map.es5.js

It is defined here:
https://github.com/systemjs/systemjs/blob/9e87f004339b3ee60dc8bec8750957bf5d9266a2/src/instantiate.js#L432

**Comment by amenadiel** [comment]
You can specify the format using config's metadata, as seen in 
https://github.com/systemjs/systemjs/blob/9e87f004339b3ee60dc8bec8750957bf5d9266a2/src/instantiate.js#L273

**Comment by unional** [comment]
Do you know how to configure that? For example, I want to do `systemjs.import('./color-map.js')`, what is the config that will work?

```js
systemjs.config({
  meta: {
    "./color-map.js": {
      format: "global"
    }
  }
}
```
doesn't work.
Also tried: `app/color-map.js` (app maps to the base dir), `file:///Users/....../color-map.js`, `./path-from-base/color-map.js`

**Comment by unional** [comment]
Nevermind. Found it here: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta

For my case, it should be `app/color-map.js`

**Comment by unional** [comment]
Thanks @amenadiel ! 🌷
