### ISSUE TITLE
Ignore ES6 transpilers

### ISSUE THREAD

**Issue by caperavensoftware** [systemjs/systemjs#1745]
When setting transpiler to false and the module format is standard ES6 modules (import / export) we should no  longer need to have it automatically transpiled because there is sufficient support in node and browsers to not have ES6 modules transpiled.

**Comment by guybedford** [comment]
SystemJS does not build on top of ES modules in browsers - rather the goal for SystemJS is to use the production build as a polyfill-like workflow for publishing ES modules for modern browsers and System.register modules for older browsers with the exact same semantics. See http://guybedford.com/systemjs-alignment#isomorphic-browser-modules for more info on this approach, although the details are still being fleshed out somewhat.

**Comment by bobOnGitHub** [comment]
Here's a use case : 
I'm using Aurelia.io in the latest version of chrome. (trying it out)
Aurelia.io uses SystemJS. 
SystemJS insists on a transpiler (traceur)
But my browser supports ES6+ ( + being "and beyond").
My understanding is that even though I have an ES6+ compliant browser, my ES6+ code for which the engine is optimised will be transpiled down to ES5 _and_ I won't be able to see my original code in the debugger ).
Have I misunderstood ?
