### ISSUE TITLE
Can I implement custom loader to load nested dependencies from a module defined with `SystemJS.set`

### ISSUE THREAD

**Issue by maximusk** [systemjs/systemjs#1747]
Suppose I register a module like that:

```
SystemJS.set('@mynamespace/core-libs', SystemJS.newModule({foo: {bar: 3}}));
```

Now I want to return `{bar: 3}` when user requests:

```
import * from '@mynamespace/core-libs/foo'
```

As I understand I can write a loader to "intercept" the call and provide the logic to retrieve `{bar:3}`. Am I right? How can I do that?

**Comment by guybedford** [comment]
You could define another module that exports the nested object:

```js
import * as m from '@mynamespace/core-libs';
// note live bindings are lost by this!
export const foo = m.foo;
```

Which is probably the easiest approach (or by an explicit `SystemJS.set` as well).

It wouldn't be a plugin, but a loader extension to extend the loader to hook this case through the instantiate hook (https://github.com/ModuleLoader/es-module-loader#instantiate-hook).

**Comment by maximusk** [comment]
@guybedford ,

> You could define another module that exports the nested object

that's I what I currently do using explicit `SystemJS.set` approach.

Thanks a lot for the reference, I'll take a look. If there's anything else I can study please post. Appreciate!
