### ISSUE TITLE
Comment parsing 

### ISSUE THREAD

**Issue by patrickinminneapolis** [systemjs/systemjs#1748]
The following comment is not parsed properly 

/* 
export const pipe = (...fns) => data => {
*/ 

This comment causes systemjs to try to transcompile when the expected behavior is that the comment be totally ignored.

**Comment by guybedford** [comment]
The format detection is not defined to be exact, see https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection for more info.

It is worth explicitly defining the module format through metadata for these cases.

**Comment by guybedford** [comment]
This regex approach is no longer used in 2.0.
