### ISSUE TITLE
How to use default export with `SystemJS.newModule` method

### ISSUE THREAD

**Issue by maximusk** [systemjs/systemjs#1749]
I have a function that I want to set as a default export:

```
function a() {}
```

`SystemJS.newModule` takes an object with bindings, so the following won't work:

```
SystemJS.set('@scoped', SystemJS.newModule(a));
```

By debugging sources I've found that I can use `__useDefault`:

```
SystemJS.set('@scoped', SystemJS.newModule({
    __useDefault: a
}));
```

However, this is not a public API. Is there a better more official way to set default export?

**Comment by guybedford** [comment]
`export default x` is identical to `SystemJS.newModule({ default: 'x' })`, but it sounds like you don't just want to set the ES module default, but the ES module interop default, which wouldn't be recommended as that is primarily meant for interop use cases. What you've found there with `__useDefault` is the only way to set that though here.
