### ISSUE TITLE
Multiple wildcards in path configs

### ISSUE THREAD

**Issue by robrbecker** [systemjs/systemjs#175]
It would be nice to simplify the config process by reducing the amount of very similar duplicated entries. I have a lot of lines that look like this:

```
System.config({
  paths: {
    'projectA/*': 'bower_components/projectA/dist/*.js',
    'projectB/*': 'bower_components/projectB/dist/*.js',
    ....
  }
});
```

I'd like to simplify this to just match and replace multiple wildcards like:

```
System.config({
  paths: {
    '*/*': 'bower_components/*/dist/*.js',
  }
});
```
- star matching on the left would have to stop at / breaks
- star replacement on the right side would have to be in order unless you used $1, $2 ..
  Thoughts?

**Comment by trusktr** [comment]
npm:glob or npm:globule, etc, might help

**Comment by leye0** [comment]
I don't understand. 

The alternative doesn't work for the OP. There would be no .js files in this (imaginary) bower_components directory if this is like the situation mentionned by @robrbecker.

All js are located at bower_components/componentA/dist/componentA.js, bower_components/componentB/dist/componentB.js.

Am I confused or it doesn't address the issue?
