### ISSUE TITLE
can't make systemjs and babel work together

### ISSUE THREAD

**Issue by mafar** [systemjs/systemjs#1750]
Hi,
I am new to systemJs and was thinking to switch from requirejs to it
I put up a basic example but can't seem to make it work.

**index.html**
```js
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8" />
    <title>Test</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.20.19/system.js"></script>
  </head>

  <body>
    <script>
      SystemJS.config({
        map: {
          'plugin-babel': 'https://raw.githubusercontent.com/systemjs/plugin-babel/master/plugin-babel.js',
          'systemjs-babel-build': ' https://raw.githubusercontent.com/systemjs/plugin-babel/master/systemjs-babel-browser.js'
        },
        transpiler: 'plugin-babel'
      });
      SystemJS.import('main.js').then(function (Rectangle) {
        const square = new Rectangle(10, 10);
        console.log(square.area); // 100
      });
    </script>
  </body>

</html>
```
**main.js**
```js
class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
  // Getter
  get area() {
    return this.calcArea();
  }
  // Method
  calcArea() {
    return this.height * this.width;
  }
}
```

**Comment by ArmorDarks** [comment]
What error do you get with your setup?

Note, that it is easier to do this with JSPM, which is a wrapper around SystemJS and a builder.

You can also refer to [Kotsu jspm.config.js](https://github.com/LotusTM/Kotsu/blob/master/jspm.config.js) as to one of working, proper examples. It should work for pure SystemJS, without JSPM, too.

**Comment by djangosdk** [comment]
for line 
```const square = new Rectangle(10, 10);```

Uncaught (in promise) TypeError: Rectangle is not a constructor

**Comment by ArmorDarks** [comment]
Ah. That's because you `main.js` does not export anything:

```js
export default class Rectangle {
  constructor(height, width) {
    this.height = height;
    this.width = width;
  }
  // Getter
  get area() {
    return this.calcArea();
  }
  // Method
  calcArea() {
    return this.height * this.width;
  }
}
```

**Comment by djangosdk** [comment]
still same error

**Comment by ArmorDarks** [comment]
I see. It happens, because SystemJS does not recognize module as esm-one.

You have to options:

1. To take a default exported value:

   ```js
   SystemJS.import('main.js').then(function (module) {
     Rectangle = module.default;
     const square = new Rectangle(10, 10);
     console.log(square.area); // 100
   });
   ```

2. To export in commonjs format:

   ```js
   module.exports = class Rectangle {
     constructor(height, width) {
       console.log(height)
       this.height = height;
       this.width = width;
     }
     // Getter
     get area() {
       return this.calcArea();
     }
     // Method
     calcArea() {
       return this.height * this.width;
     }
   }
   ```

   Then your original example will work without changes:

   ```js
   SystemJS.import('main.js').then(function (Rectangle) {
     const square = new Rectangle(10, 10);
     console.log(square.area); // 100
   });
   ```

3. To configurate meta with format to support esm

   ```js
   SystemJS.config({
     map: {
       'plugin-babel': 'https://raw.githubusercontent.com/systemjs/plugin-babel/master/plugin-babel.js',
       'systemjs-babel-build': ' https://raw.githubusercontent.com/systemjs/plugin-babel/master/systemjs-babel-browser.js'
     },
     transpiler: 'plugin-babel',
     meta: {
       '*.js': {
         'format': 'esm'
       }
     }
   });
   ```

   Well, strangly enough it does not work for some reason =\

**Comment by djangosdk** [comment]
@ArmorDarks  
thank you for ur feedback. 

1. Point-3 should work but it does not
1. For point-2 , I want to adopt to ES6 , so there is no way I am using commonJs syntax otherwise i would be using commonjs as loader

There is lot missing with systemJs docs and it is still not mature i think. I will stick with requireJs for now as I was able to up its example in minutes.

**Comment by ArmorDarks** [comment]
First example definately works, tested it locally. Didn't you forget to `export default` in `main.js`?

I really recommend to try JSPM. It is overly more finished and polished experience for SystemJS end users, and you will need to build for production anyway.

Try `0.17` beta branch, which is the last one as of right now. And here is [0.17 documentation](https://jspm.io/0.17-beta-guide/index.html)

**Comment by djangosdk** [comment]
@ArmorDarks Thankx. Will try it.
