### ISSUE TITLE
SystemJS parses `import` and `export` inside comments and throws `transpiler required` error

### ISSUE THREAD

**Issue by maximusk** [systemjs/systemjs#1752]
When I have commented `import` or `export` inside a module TypeScript compiler doesn't transpile it into `require` and `exports` calls. Hence I get the following files:

```
// import { ... } from ' ... ';
```

When SystemJS loads this file it detects `import` or `export` calls and throws an error about the need for transpiler.

**Comment by guybedford** [comment]
Yes this is a design limitation of the format detection process (see https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection). Setting the module format explicitly through metadata would be the fix here.

**Comment by limscoder** [comment]
I ran into this same issue:

SystemJS v 20.9 (using the version included with Grafana).

I have a UMD module that contains the following comment:

```javascript
/*

// usage

import StyleSheet from 'glamor/lib/sheet'
let styleSheet = new StyleSheet()

*/
```

SystemJS loads this UMD module properly when the comment is removed. When the comment is present, I get the following error. I suspect SystemJS is looking for `import` statements regardless of if they are in a comment or not.

```
Error: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })````

**Comment by amenadiel** [comment]
You can specify the module format in your config file. Not doing so will make SystemJS resort to autodetection, which is text based and, therefore, doesn't know if imports are commented out.

You should just do (in your jspm.config.js)

```js
packages: {
    "this_umd_module": {
      "format": "umd",
      "defaultExtension": "js",
      "main": "main.js"
    },
   ...
}
```
