### ISSUE TITLE
Issues with missing .defaults export with Vue.js 2.5 & TypeScript

### ISSUE THREAD

**Issue by ciddan** [systemjs/systemjs#1753]
See: https://github.com/vuejs/vue/issues/6815
I cannot figure out if this is an issue with:
1. My setup.
2. Vue.js. Or,
3. SystemJS.

**Comment by guybedford** [comment]
Sounds like this has been resolved from https://github.com/vuejs/vue/issues/6815#issuecomment-336723928. Just let me know if you need further assistance.

**Comment by viT-1** [comment]
Same question.
I have [working repo](https://github.com/viT-1/systemjs-ts-es6) with SystemJS 5.0
and extended [repo with Vue](https://github.com/viT-1/systemjs-ts-es6-vue).
I couldn't get to work Vue with SystemJS but with es-module-shims it's working!
