### ISSUE TITLE
Supporting redirected URL for dependency normalization

### ISSUE THREAD

**Issue by wmhilton** [systemjs/systemjs#1754]
So this works in the latest version of Chrome, which is freaking awesome:

```html
# index.html
<!DOCTYPE html>
<html>
  <head><title>import demo</title></head>
  <body>
    <script type="module" src="./app.js"></script>
  </body>
</html>
```
```js
# app.js
import { concat } from 'https://unpkg.com/lodash-es'
console.log('lodash =', concat([1,2,],3,4))
```

Chrome has no tree-shaking and downloads 300+ dependencies (one for every function exported from lodash)... but it works.

Here is what I have for a SystemJS equivalent:
```html
# index.html
<!DOCTYPE html>
<html>
  <head><title>import demo</title></head>
  <body>
    <script src="https://unpkg.com/systemjs/dist/system.js"></script>
    <script>
      SystemJS.config({
        map: {
          'systemjs-babel-build': 'https://unpkg.com/systemjs-plugin-babel/systemjs-babel-browser'
        },
        transpiler: 'https://unpkg.com/systemjs-plugin-babel'
      })
      SystemJS.import('./app.js')
    </script>
  </body>
</html>
```
```js
# app.js
import { concat } from 'https://unpkg.com/lodash-es'
console.log('lodash =', concat([1,2,],3,4))
```
And it has the 302 redirect resolution issue explained in https://github.com/ModuleLoader/es-module-loader/issues/538

At the moment, I'm "solving" this by manually mapping module identifiers to their final URL, which basically means adding a line of config for every deep dependency in my project. (And that became so burdensome I started using the UMD builds of my dependencies instead of their native ES6 source code.) I'm building a client-side IDE so I need to be able to dynamically load npm modules, which is why I'm not just using Webpack or something.

Any idea how I can get around this? Is there a hook where I could mangle the resolving algorithm in SystemJS to use the post-302 location?

**Comment by guybedford** [comment]
Ok, so the reason for this is we don't support "catching" redirects in the fetch component of SystemJS.

Supporting this is important for spec alignment so let's aim to get this feature in soon.

Basically we'd need something along the following lines:

* During `fetch`, detect a redirect, and return the redirect URL along with the source
* If using `scriptLoad` then unfortunately we don't have this information so this would have to be for the fetch mode only.
* This data can be stored as `meta.redirectURL` or similar on the load record.
* When resolving dependencies, we'd need to then use the redirectURL over the standard URL as the parent in normalization.

This should be relatively straightforward to implement, so I will aim to get to this, although it won't be very soon unfortunately.

**Comment by unional** [comment]
#1772 needs the same functionality when resolving dependencies. The difference is that the "redirectURL" is returned during the plugin's `locate` call.

**Comment by guybedford** [comment]
This is still a tricky one to support in SystemJS 2.0. Leaving open, but its nature is a wontfix.

**Comment by guybedford** [comment]
(although I'm always open to bright ideas too)

**Comment by guybedford** [comment]
It should be possible to support with the translate loader though, just not the script loader.

Removing the wontfix label for the translate loader support.

**Comment by guybedford** [comment]
I implemented this in es-module-shims in https://github.com/guybedford/es-module-shims/commit/a811843f6a2a1cbc7504971ba572a314f96f1e9b and it was pretty straightforward.

The hardest part is just figuring out how to pipe this information in the System loader internals.

**Comment by guybedford** [comment]
So it turns out the translate loader is not really being focused on. Given this I think we can go back to the wontfix scenario here.
