### ISSUE TITLE
paths under 0.20.x

### ISSUE THREAD

**Issue by rj33** [systemjs/systemjs#1755]
Under 0.19 I was using this path transform in builder config:
"modules/*.css": "dist/modules/*.css"

I'm trying to upgrade to 0.20, so need to find an alternative without wildcards, but I'm not sure what this would be. Usually you can do:
"modules" : "dist/modules/"

but I only want the path change for css files not js files.

The case I'm dealing with here is that I have the css transformed from scss into my build directory (dist). So when the css plugin is processing the css imports it needs to look for them in dist/ not in the same path as the *.js module they are imported in, as that path only has the untransformed .scss file. I'd prefer to keep my current scss processing path, rather than another plugin, and so continue to import .css using the css plugin if possible, but I'm not clear on how to get the path transform I need now that wildcards are no longer supported.

**Comment by amenadiel** [comment]
I would rather have everything in `.scss` in each module/script, and let the `scss` plugin deal with them during the build stage.

However, you could use a different strategy. Let's say your folder structure is something like

```
- root
  - modules
    - app.js
  - styles
    - style1.scss
    - style2.scss
  - dist
    - modules
      - app.built.js
      - style1.css
      - style2.css
```

So when you do (from `modules/app.js`)

```js
import 'modules/style1.css';
```

You want it to behave as if you did

```js
import 'dist/modules/style1.css';
```

Why don't you precompile your `scss` files into their own folder (instead of putting them in `dist/modules` along your `.js` files?. So your layout could instead look like:

```
- root
  - modules
    - app.js
  - styles
    - style1.scss
    - style2.scss
  - dist
    - modules
      - app.built.js
    - styles
      - style1.css
      - style2.css
```

Then, a `path` definition such as

```js
paths: {
  "modules/styles/" : "dist/styles",
  ...
}
```

would turn 

```js
import 'modules/styles/style1.css';
```

into

```js
import 'dist/styles/style1.css';
```

**Comment by rj33** [comment]
Thanks, those are both decent suggestions, and I may go with the second if I can't get something else working.

I was avoiding plugin-scss because it wasn't a drop in replacement for plugin-css, and so required a few more changes to the existing workflow than I was happy with , also I preferred to stick with plugin-css as it is maintained within the systemjs/* project and so seemed more likely to be working with future versions (plugin-scss hasn't seen changes for nearly 18 months).

I also like my scss and js in the same directory, just for convenience, as I'm often editing both at the same time, but I can live without that if I have to, so your suggestion on a separate directly to allow a non-wildcard path statement might be the easiest way to go.

Another option that looks like a possibility is to override the builder fetch, according to this page:
http://www.oss.io/p/systemjs/builder

I can do something like this:
var mySource = 'import * from foo; var foo = "bar";'; // get source as a string
builder.bundle('foo.js', {
  fetch: function (load, fetch) {
    if (load.name.indexOf('foo.js') !== -1) {
      return mySource;
    } else {
      // fall back to the normal fetch method
      return fetch(load);
    }
  }
});

I assume I could do the same thing the pre 0.20 path transform was doing in .a fetch override. This isn't ideal as I'm using a grunt plugin to fire off the build tasks rather than my own builder.bundle calls, so If I want to keep that, I'll need to hack the grunt plugin's code directly.

I looked at trying to find .a way of hacking the plugin-css code to provide an equivalent to the path transform, but it seems the transform needs to happen higher up, as there is a fetch that seems to occur well before the plugin code is entered, so any hack would have to occur outside of the css plugin's code based on my reading so far.

Thanks again for the suggestions, they have given me a few more options to play with.

**Comment by davismj** [comment]
I've got an entire built application. I'm testing upgrading to 0.20 because it looks great. Like every web application ever, I have a src/ folder that builds into a dist/ folder, and my imports look like this:

**main.js**

```javascript
import { Dependency } from "./dep.js";
```

I can't find any tools SystemJS provides me for saying "local files are in the 'dist/' folder." I used to do this in SystemJS 0.19 with:

```javascript
System.config({
  baseURL: ".",
  paths: {
    "*": "dist/*"
  }
});
```

This doesn't work anymore. I've tried changing `maps`, `paths`, `packages`, but nothing seems to work. What's the new way of handling the dist folder?

**Comment by guybedford** [comment]
@davismj wildcard paths were deprecated quite a while back for straightforward directory paths:

```js
System.config({
  paths: {
    'x/': 'path/'
  }
})
```

The `*` path is exactly just the baseURL though, and doesn't have a representation in paths.

**Comment by davismj** [comment]
@guybedford Thanks! Problem is that the `*` path and the baseURL were doing two different things for me. `*` was shorthand for a local package, as it would handle cases where I request `./main.js`, where baseURL was the base of my directory, and was important for things like where `node_modules` was located.

I might have done it wrong, but as a result, in my node config, when bundling, the bundler has a hard time tracing down my dependencies when i set my baseURL to `dist`. I then set my `node_modules` to `./../node_modules` or `../node_modules`, and for some reason it starts looking in `../../node_modules`. If i set it to `./node_modules` or `node_modules`, it looks in `dist/node_modules`.

Maybe this is a totally separate bug and I'm trying to solve the wrong problem.

**Comment by guybedford** [comment]
The suggested workflow is to refer to local paths by the name of the local
package - ‘myapp/x’ instead of ‘./x’.

Jspm provides the prompts to set this up exactly that way for the app name
on init.

**Comment by davismj** [comment]
I'm tracking, but what if I change the name of my local package? I have to change hundreds of import statements across the application? But the modules are always local. Making a local, relative paths a first-class citizen seems like a big win.

**Comment by guybedford** [comment]
@davismj you can always configure this custom map name such that it doesn't have to match the same external name of the package. `./x` isn't easy to reference in internal imports - the plain solution also solves the problem of internal requires without backtracking which I think is important to solve here too.

**Comment by davismj** [comment]
> you can always configure this custom map name such that it doesn't have to match the same external name of the package

Interesting. I'll give this a try. Thanks for your support, Guy!

> the plain solution also solves the problem of internal requires without backtracking

You lost me here, so I'll take your word for it.
