### ISSUE TITLE
Uncaught (in promise) Error: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.

### ISSUE THREAD

**Issue by lastmjs** [systemjs/systemjs#1757]
I'm getting this error when trying to import a simple wasm binary:

```
Uncaught (in promise) Error: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.
```

Compiled from:

```
#include <stdio.h>

int main(int argc, char** argv) {
    int hello = 5;
    int monkey = 15;

    printf("The answer is: %d", hello + monkey);
}
```

I've seen this problem on my own, and I think `WebAssembly.instantiate` just needs to be used instead.

**Comment by guybedford** [comment]
Unfortunately SystemJS can't support the async form of WebAssembly.instantiate due to the fact that that requires making the execution function of ES modules asynchronous.

I take it this buffer size is referring to the size of the wasm binary? If so this may be worth escalating.

**Comment by guybedford** [comment]
Instantiate happens here - https://github.com/systemjs/systemjs/blob/master/src/common.js#L67, where synchronous execution is a requirement.

**Comment by guybedford** [comment]
It would still be good to tackle this approach properly. @xtuc would value your thoughts if you know if there is a way to do this yet?

**Comment by guybedford** [comment]
> Using W.compileStreaming + W.instantiateStreaming; will trigger the download and compilation twice, but we can hope that some caching is involved (at least for the download).

This may well be an option actually. Double compilation doesn't sound too bad in the face of not being able to execute code at all. I'm tempted to write this in as the default.

Thanks so much @xtuc for the summary. it would help a lot to have this use case acknowledged from the Web Assembly side ideally given the impassable roadblocks here.

**Comment by guybedford** [comment]
@xtuc thanks so much for the feedback on this so far.

I've just had a look further into the implementation details on this:

1. I think when we previously discussed this, the issue we noticed was that the response stream is being "used" by the `compileStreaming` call. It seems like this could be resolved by calling `res.tee()` although this wouldn't be supported in Safari. Perhaps that would be ok.
2. More seriously, `instantiateStreaming` seems like it will throw a LinkError and therefore not return the module info if the importObject is incorrect, meaning we'd need to provide a Proxy to this object that can dynamically return "nonsense" modules. It seems like there might still be an issue with that if we return an unexpected type. If you know what would happen in such cases do share as that sounds like the absolute make or break on this to me.

It feels like a minefield there, but perhaps we can wade through it in the ugly name of compatibility.

The ideal fix would be an async WebAssembly.instantiate function I think that could work with compileStreaming.

**Comment by xtuc** [comment]
> 1. [...]

it didn't know about `ReadableStream.tee`, but to start the stream decoding (via `instantiateStreaming`) we need to pass the `ImportObject`, which isn't possible at that point.

> 2. [...]

IRC getters were called, maybe that a Proxy would work too, that would be great (even for Webpack). Note that the type doesn't matter, it's more like a cast than a contract. 

> @xtuc also, do you happen to know if Safari is one of the browsers that enforces the 4Kb limit?

I think they agreed on that, but someone from Apple will probably be at the meeting, I can ask.

**Comment by guybedford** [comment]
> it didn't know about ReadableStream.tee, but to start the stream decoding (via instantiateStreaming) we need to pass the ImportObject, which isn't possible at that point.

> IRC getters were called, maybe that a Proxy would work too, that would be great (even for Webpack). Note that the type doesn't matter, it's more like a cast than a contract.

Ok it seems like an experiment needs to be done with this approach then to see if it can work! Good news on the types, although it might still result a top-level execution failure or not?

> I think they agreed on that, but someone from Apple will probably be at the meeting, I can ask.

This still seems like a blocking issue if they have implemented it already without stream tee being supported.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/pull/1857.

The trick was to use the SystemJS top-level await support.

**Comment by guybedford** [comment]
(released in 2.0.2)

**Comment by lukewagner** [comment]
FWIW, the best-performing option I can think of is:
* first [clone](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone) the Respose produced by `fetch()`
* feed the original `Response` into `WebAssembly.compileStreaming`
* get a readable stream out of the second `Response` and use a mini-wasm-decoder to decode just enough to get the import strings out of the imports section (which should be a tiny amount of code), closing/canceling the stream as soon as that is decoded
* as soon as the imports are decoded, recursively issues module instantiations, and as soon as *those* resolve to export values, issue the async `WebAssembly.instantiate`.

If an engine does the expensive compilation during `compileStreaming`, this will be nearly-ideal performance.  If the engine does expensive compilation during `instantiate`, this will unfortunately serialize compilation, so to improve things we could standardize the extension to `instantiate` that allows it to take promises for its imports, allowing all `instantiate`s to be issue much more eagerly above.

**Comment by xtuc** [comment]
@lukewagner 

I played with that idea and it seems to work great!

We can't read from an already opened stream (I don't remember the exact message), something like just adding a consumed to the initial stream is not possible. 

So I created a new stream consuming the initial one and passed the new to instantiateStreaming. Also that allows me to buffer until the import section is fully decided. 

Note that WebAssemblyjs already has a small decoder. I'll see if I can find the time to continue that.

**Comment by guybedford** [comment]
Thanks for the updates here. I also went down this route initially here, but eventually settled on compileStreaming + WebAssembly.instantiate in SystemJS (https://github.com/systemjs/systemjs/blob/master/src/features/wasm-load.js#L16). I'd be interested to know how the performance compares.

Strictly speaking, neither of the above implement spec semantics though, which is my greatest concern currently, since in theory:

```js
import 'esm1';
import 'wasm';
import 'esm2';
```

should execute `esm1`, `wasm` then `esm2` synchronously in graph execution order, while due to the async instantiate as a single phase we have an unnecessary ticks between `wasm` and `esm2`. It may seem subtle, but execution semantics matter at this level to ensure startup consistency.

**Comment by lukewagner** [comment]
> We can't read from an already opened stream (I don't remember the exact message)

In case it helps: there is a spec-defined notion of a Response being "used" (reflected in `Response.bodyUsed`) and a Response can only be used once (and `Response.arrayBuffer()` and `Response.body.getReader().read()` both set this).  To get around this you have to explicitly `Response.clone()`.

**Comment by xtuc** [comment]
@lukewagner that's great, but I went with a wrapper because we don't want the decoder to be racing with the instantiation, that's why i'm buffering until the `importObject` is ready.
