### ISSUE TITLE
env and global requests for wasm import

### ISSUE THREAD

**Issue by lastmjs** [systemjs/systemjs#1758]
I'm importing a simple wasm file, and I'm getting http requests for a `env` and `global` file. What are these files? Why are they being requested? Is there any documentation for the use of `wasm` with SystemJS that I could reference?

**Comment by guybedford** [comment]
You can map these names with a custom map config in SystemJS, then you just need to ensure the right functions are exported there. Preparing the `env` module usually means building stdlib files into an env module. Then there is memory wiring to think about as well. If you are interested, perhaps have a look at my wasm introduction here - https://egghead.io/courses/get-started-using-webassembly-wasm.
