### ISSUE TITLE
Suggestion: expose the method for combining two configuration objects

### ISSUE THREAD

**Issue by benstevens48** [systemjs/systemjs#1761]
Hi,
Apologies in advance for the long post. Currently I'm using SystemJS as a module loader with npm for installing client-side packages and gulp for build tasks. Perhaps I could use jspm (and perhaps I should) but I like the control this setup gives me and also the fact that I can use the same structure with webpack and there are various other reasons for it.

I've set it up so that it will work without a build setup (which is one of the things I like about SystemJS over webpack because I find this conceptually simpler), but I do have a build setup which does a couple of things (well at least a couple of things). Firstly, I actually have a core `systemjs.config.js` file and a production version and development version `systemjs-prd.config.js` and `systemjs-dev.config.js` to allow overwriting certain things like the map config - e.g. VueJS has different versions for dev and production. Secondly, I use the builder to create some bundles, using a list of module names because I like to have control over what goes into the bundle and am also loading some on demand.

So during my build step, (using JavaScript run by node e.g. in a gulp 4 task), I want to be able to read the config object from my core config file and the dev or production one, combine them, pass that to the builder, build the bundles, and also write the bundles section of the config object (which I'm happy doing manually), then write the resulting config file to disk. This is actually possible using not too much code, but there are parts of it I'm not completely happy about. Here is the code.

```js
const path = require('path');
const gulp = require('gulp');
const del = require('del');
const extend = require('extend');
const fs = require('mz/fs');
const Builder = require('systemjs-builder');
const globby = require('globby');

gulp.task('systemjs:prd', async () => {
    let config = await readSystemJSConfig(['static/app/systemjs.config.js', 'static/app/systemjs-prd.config.js']);
    await createSystemJSBundles(config);
    await writeSystemJSConfig(config);
});

async function readSystemJSConfig(configPaths){
    let systemJS = {config: function(obj){extend(true, this.currentConfig, obj);}, currentConfig: {}};
    for(let p of configPaths){
        let src = await fs.readFile(p, 'utf-8');
        (new Function('SystemJS', src))(systemJS);
    }
    return systemJS.currentConfig;
}

async function writeSystemJSConfig(config){
    let content = 'SystemJS.config(' + JSON.stringify(config) + ');';
    await fs.writeFile('build/static/app/systemjs.config.js', content);
}

const systemJSBundles = {
    'vendor/vendor.bundle.js': ['node_modules/@angular/**/*.js', 'node_modules/rxjs/**/*.js',  '!node_modules/rxjs/add/**', '!node_modules/rxjs/bundles/**', '!node_modules/rxjs/src/**', '!node_modules/rxjs/testing/**'],
    'app/main.bundle.js': ['node_modules/systemjs-plugin-text/text.js', 'app/**/*.js', '!app/**/*.standalone.js', 'app/**/*.html']
};

async function createSystemJSBundles(config){
    let builder = new Builder('build/static');
    builder.config(Object.assign({}, config, {baseURL: 'build/static'}));
    let toDelete = [];
    for(let bundleName of Object.keys(systemJSBundles)){
        let globs = systemJSBundles[bundleName];
        let paths = await globby(globs, {cwd: 'build/static'});
        config.bundles = config.bundles || {};
        config.bundles[bundleName] = paths;
        await builder.bundle(paths, path.join('build/static', bundleName));
        toDelete = toDelete.concat(paths);
    }
    await del(toDelete, {cwd: 'build/static'});
}
```

(There may be a couple of missing bits).

What I am slightly unhappy about with this code is the following.

1. In order to combine SystemJS configs I am using a deep Object.assign (the extend package) but I don't think this is quite right - hence the request to be able to use the function that SystemJS uses to combine configs. 
2. Using evaluation of code to read the config - it would be better if this was part of the builder or SystemJS (which may do this internally).
3. Writing the config file with JS code as a string - very easy but again feels a bit wrong - would be  good if it was part of the builder.

Now you might think you could do 1 by using SystemJS in Node calling config() and getConfig(), but unfortunately it converts all the paths to file paths and also adds some extra stuff to the config which I don't really want. I realise that 2-3 are probably builder suggestions but also I think they are tied up with this issue of the config paths being converted to file paths. I realise that I could concatenate my base and prd/dev config files into one file instead of merging the config object, but this still leaves me with the issue of injecting the bundles config.

**Comment by guybedford** [comment]
I've personally written a method like this a couple of times and it is definitely a useful feature when creating these types of tools on top of the workflow.

The function for this is available at https://github.com/systemjs/systemjs/blob/master/src/config.js#L96.

It is probably easiest just top copy and modify it, as this API is now stable for 0.20 and won't be changing.

If anything a separate helper tool would be the place for this sort of stuff. If you do put something like that together let me know.

**Comment by benstevens48** [comment]
Thanks for the reply. I could probably write a helper once but then I wouldn't have time to maintain it. I could imagine something like a package called systemjs-merge (like webpack-merge but no need for any fancy features) which would export a function that behaved liked Object.assign modified to correspond nicely to multiple SystemJs.config() calls. 

Then for reading an writing config files I could imagine a package called something like systemjs-config-file-helper with a re-export of the merge function and two other functions - readConfig which would accept a file path or array of file paths and return a config object (merged for multiple files or if there are multiple SystemJS.config() calls in the same file), and writeConfig, which would take a config object (or maybe an array of objects to merge) and a file path and write the config to that path (or return a string if the file path is omitted). This could perhaps use the javascript-stringify package instead of JSON.stringify and have an option for nice spacing to make it more readable. Essentially I've already included these two functions in the code above and I'm sure they've been written multiple times by multiple people. I'd be happy to make this into a minimal package, but I think it needs the ability to merge configs first (at least to support multiple SystemJS.config() calls in one file).

Alternatively in a future release the first package could be part of SystemJS and the second part of the builder.

**Comment by guybedford** [comment]
Closing as SystemJS 2.0 no longer provides a configuration system.
