### ISSUE TITLE
System.js encodes '#' in url's with xfbml

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#1765]
`https://connect.facebook.net/en_US/sdk.js#fbml=1&version=v2.11&appId=54321...` becomes `https://connect.facebook.net/en_US/sdk.js%23xfbml=1&version=v2.11&appId=54321...` and causes fb to return 404

**Comment by guybedford** [comment]
Can you rather just import `https://connect.facebook.net/en_US/sdk.js` here as the `#` would be ignored anyway?
