### ISSUE TITLE
Second call to System.config with baseURL don't rebase previous items (packages,map etc.)

### ISSUE THREAD

**Issue by luboid** [systemjs/systemjs#1766]
If I have next config

```javascript
System.config({
  baseURL: './',
  packages: {
    theapp: {
      defaultExtension: 'ts',
      main: 'main'
    }
  },
  map: {
    theapp: ''
  }
});
```
Second call with 

```javascript
System.config({
  baseURL: './src'
});
```
don't relocate package at ./src

**Comment by madmed88** [comment]
I have the same problem. I used to override the baseUrl in order to run karma but when upgrading to 0.20 the only way I made it work is by re writing all the map config which is not ideal because I don't want to maintain two map configs.
