### ISSUE TITLE
Request for support of EcmaScript modules syntax out of the box

### ISSUE THREAD

**Issue by maximusk** [systemjs/systemjs#1767]
With the implementation by most browsers of EcmaScript modules and the recommendation by some libraries like Angular to package libraries in flat ESM I think it'd be great if SystemJS supported ESM syntax out of the box without the need for transpilers to commonjs syntax. Are there any plans like this or has it been already considered and rejected?

**Comment by guybedford** [comment]
See https://github.com/guybedford/es-module-shims if you are still interested in this.
