### ISSUE TITLE
plugin: locate does not adjust folder level

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#1772]
I created [systemjs-plugin-domture](https://github.com/unional/systemjs-plugin-domture) to make node resolution possible for [domture](https://github.com/unional/domture).

One issue I faced is that the folder level is not adjusted for `require('./subfolder')` syntax after I fix the address in the `locate()` hook.

The issue can be reproduced by this test: https://github.com/unional/domture/blob/locate-subfolder-adjust-folder-level/src/createDomture.spec.ts#L232

## The scenario

```js
// index.js
module.exports = require('./subfolder')

// subfolder/index.js
module.exports = require('./foo')

// subfolder/foo.js
module.exports = function foo() { ... }
```

In the plugin, I update `load.address` from `file:///.../subfolder` to `file:///.../subfolder/index.js`.
`systemjs` can then load `subfolder/index.js` but when it process `require('./foo')`, it tries to load from `file:///.../foo` instead of `file:///.../subfolder/foo`.

If I change the content of `index.js` to `module.exports = require('./sub-folder/index')`, it is working fine.

Is it ok to change `systemjs` so that it will adjust the current folder based on `load.address` after `locate` is called?

**Comment by unional** [comment]
I noticed `loader.registerDynamic()` is called in two flavors: `registerDynamic(name, deps, boolean (executingRequire), callback(execute))` and `registerDynamic(deps, boolean(executingRequire), callback(execute))`.

But looking at es-module-loader: https://github.com/ModuleLoader/es-module-loader/blob/master/core/register-loader.js#L463
it seems like the arguments are not adjusted for the two overloads.

Could this be part of the issue?

**Comment by guybedford** [comment]
I take it that https://github.com/systemjs/systemjs/issues/1754 was the final conclusion here?

**Comment by unional** [comment]
If I understand correctly, "This data can be stored as meta.redirectURL or similar on the load record." means `load.address` would be considered and/or the value returned by the `locate` hook would be involved in solving the location?
