### ISSUE TITLE
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:56536/src/fw/fw.module

### ISSUE THREAD

**Issue by ShaileshBhatNP** [systemjs/systemjs#1787]
I'm getting this error while running angular2 project in visual studio. In the project, fw is the module, which is inside _app folder of src_. What may be the reason..
![errorinconsole](https://user-images.githubusercontent.com/29448807/34766673-2f6611ae-f61b-11e7-9dc2-f8a396e43a4e.png)

**Comment by akaradi** [comment]
How did you resolve this?
