### ISSUE TITLE
SystemJS builds for Node instead of browser

### ISSUE THREAD

**Issue by pieterbeulque** [systemjs/systemjs#1792]
Hi

[Here's a ticket for context](https://github.com/visionmedia/superagent/issues/1331)

Superagent is an NPM package that has this in its `package.json`:

```.json
{
  "browser": {
    "./lib/node/index.js": "./lib/client.js",
    "./test/support/server.js": "./test/support/blank.js"
  },
  "main": "./lib/node/index.js"
}
```

In my `jspm_packages` folder it creates a `superagent@3.8.2.js` file that holds this:

```js
module.exports = require("npm:superagent@3.8.2/lib/node/index.js");
```

I believe this should honor the `browser` field from `package.json` and become:

```js
module.exports = require("npm:superagent@3.8.2/lib/client.js");
```

Is this an issue with JSPM / SystemJS or have I configured/installed something incorrectly?

JSPM version: JSPM 0.16.53

Thank you ✌️

**Comment by floydpink** [comment]
@pieterbeulque did you figure out any work around for this issue?

**Comment by pieterbeulque** [comment]
@floydpink - No, I'm absolutely clueless on how to fix this. I edit the wrong file manually 😁

**Comment by guybedford** [comment]
Perhaps try using jspm 0.17 here as it has better support for these kinds of conditional mappings.

**Comment by pieterbeulque** [comment]
We're stuck on 0.16 for legacy issues 😞

**Comment by guybedford** [comment]
What happens if you install and null out the main mapping with:

```
jspm install superagent -o "{ main: null }"
```

Alternatively, try setting the main directly to the desired value similarly.
