### ISSUE TITLE
Loader import method must be passed a module key string?

### ISSUE THREAD

**Issue by bariscanyilmaz** [systemjs/systemjs#1794]
![hata](https://user-images.githubusercontent.com/30300440/36147439-3ebd9a82-10c9-11e8-899f-e6996eed6cc9.PNG)

what is this error source. 
first I got the transpiler fault and now I get it

**Comment by guybedford** [comment]
It would help to know the content of `ng2-bs3-modal.js` here.

**Comment by amuvar** [comment]
HI how you guys resolved above screenshot error
