### ISSUE TITLE
Auto-load configuration

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#1796]
Hello!

I've like to use SystemJS in WordPress which is able output a `<script>` tag and a global. Something like

```js
SystemJSConfig = {
  map: {
    css: 'node_modules/systemjs-plugin-css/css.js'
  }
};
```

Would it be possible to auto-load configuration from a specially named global to prevent concatenation of `system.js` and `SystemJS.config(SystemJSConfig);`?

**Comment by szepeviktor** [comment]
@guybedford Could you please advise.

**Comment by guybedford** [comment]
SystemJS 2.0 supports package map configurations loaded through scripts now.
