### ISSUE TITLE
System.import('blah') does not attempt to fetch if it has failed previously

### ISSUE THREAD

**Issue by charliematters** [systemjs/systemjs#1799]
SystemJS 0.20.19

I can hopefully mock up an example of this later, but when fetching modules, SystemJS appears to cache failed fetches and will not attempt to fetch again, even after a `System.registry.remove('blah')` call.

The current symptoms appear when the module has an incorrect import statement (e.g. a typo). The `System.import('blah')` promise throws the same error as when it first fails, but makes no attempt to fetch the file.

Ideally, removing the offending import from the registry (or some similar method call) would allow SystemJS to forget about the error and try again in the same way as it does originally.

**Comment by guybedford** [comment]
This is the way module loading works in the browser module loader and so what SystemJS copies.

If you want to have something re-requested, run `System.registry.delete(System.resolveSync('blah'))` (and you can double-check it is working by seeing it return `true`.

**Comment by charliematters** [comment]
My issue is that `System.registry.delete(System.resolveSync('blah'))` doesn't seem to be working when child dependencies are failing. I don't know the best way to host a simple example, but here are some files that illustrate my issue:

dependency.js_valid
```javascript
module.exports = { result: 'good' }
```

dependency.js_invalid
```javascript
require('missing.js')
module.exports = { result: 'bad' }
```

main.js
```javascript
document.getElementById('fetch-button').onclick = () => {
  System.import('dependency.js').then(
    dep => console.log('Fetched dependency.js', dep),
    err => console.log('Did not fetch dependency.js', err)
  )
}

document.getElementById('forget-button').onclick = () => {
  console.log('Forgotten dependency.js', System.registry.delete(System.resolveSync('dependency.js')))
  console.log('Forgotten missing.js', System.registry.delete(System.resolveSync('missing.js')))
}
```

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <script src="/node_modules/systemjs/dist/system.js"></script>
    <script>
      System.import('/main.js')
    </script>
  </head>
  <body>
    <button id="fetch-button">Fetch dependency.js</button>
    <button id="forget-button">Forget dependency.js</button>
  </body>
</html>
```

Steps to reproduce:
1. Put the above files in a folder with an npm project which has SystemJS installed in node_modules
2. Host it locally (I used http-server)
3. Open it in a browser (I used Chrome 64)
4. Run `cp dependency.js_valid dependency.js` to copy the valid dependency into place
5. Press 'Fetch dependency.js' and the browser will fetch the dependency and print it in the console
6. Forget it and fetch it again, and the browser correctly re-fetches:

![image](https://user-images.githubusercontent.com/7063124/37301623-ffaba862-2620-11e8-8947-40ba8b84f660.png)

7. Click 'Forget dependency.js' (or refresh the browser)
8. run `cp dependency.js_invalid dependency.js` to copy the dependency with the invalid `require` into place
9. Click the button to fetch it again - as expected an error appears:

![image](https://user-images.githubusercontent.com/7063124/37301683-39fcc76c-2621-11e8-945f-8a32eab2f5e6.png)

10. Click the button to forget it
11. Copy the good dependency back again with `cp dependency.js_valid dependency.js`
12. Click the Fetch button

At this point I would expect that it would re-fetch dependency.js as it was never fully fetched in step 9. However, it has cached the dependencies for the invalid version of dependency.js and as we can see it's still trying to fetch missing.js:

![image](https://user-images.githubusercontent.com/7063124/37301907-e9d225e2-2621-11e8-940f-9f726b469968.png)

I notice that the call to forget 'dependency.js' returns false - I guess this is part of the problem, but ultimately It would be nice if there was a way of removing files from the registry completely without leaving cached bits behind.

Is this clear? If not I can try again!

**Comment by guybedford** [comment]
@charliematters yes you do need to manually clear all failed child error records. Failed records cache - this is the way modules work in browsers. It's possible to create a script to clear all dependency errors for a given module load using the tracing API - https://github.com/ModuleLoader/es-module-loader#tracing-api.

**Comment by charliematters** [comment]
The perfect link - thanks!

**Comment by charliematters** [comment]
Sorry to re-open, but I've been looking into using the `System.loads` object that is revealed when using the trace API.

When you load the incorrect dependency, the loads object remains empty.

Is `System.loads` the place to be looking? Can you give me some (_more!_) pointers on where to start?

**Comment by guybedford** [comment]
Right, so the error you are dealing with here is a fetch error?

In that case, yes records that don't complete fetch won't be traced unfortunately. We could potentially look at updating the trace API to support this use case.

**Comment by charliematters** [comment]
I guess it it is, yes - the 404 is the main source of the problem. 

It would be really useful to be able to use the trace API (or similar) to completely wipe any traces of problems, but I'm not good enough to make the changes myself!
