### ISSUE TITLE
meta > build option in config API is undocumented

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#1800]
As part of the config API: `build` option under the `meta` property is undocumented. 

The `build` option is documented in the systemjs/builder [docs](https://github.com/systemjs/builder/tree/0.15#ignore-resources) and seems to work as part of jspm/sjs 0.16/0.19 (I am guessing later versions as well).

Please Fix...

**Comment by guybedford** [comment]
The `build` option is not a SystemJS feature but a SystemJS builder feature, so that's why it's documented there.

**Comment by CxRes** [comment]
I strongly disagree with your stance! It may be a builder feature but it is a part of the SJS config. You should document it as such and then point users to builder docs for the options etc.
