### ISSUE TITLE
How to unload a module?

### ISSUE THREAD

**Issue by santoshppg** [systemjs/systemjs#1803]
Hello, I am having issues trying to unload a module loaded using System.Import function. Currently, I have this simple line of code inside my <script> tag: System.import('app').. I see SystemJS imports the module and I see the loaded module in the network tab of Google chrome. so, everything works fine until this point. However when I navigate to another page and come back, it doesn't re import the module and I don't see any changes to the module in the chrome's network tab. I have tried deleting the module before importing it by executing System.delete('app') but it doesn't seem to work. The only workaround I have found is to refresh the entire page which is not ideal. Is there a proper way of doing this or is this a bug? Could someone help here? 
Thanks,

**Comment by guybedford** [comment]
Perhaps try `System.delete(System.resolveSync('app'))` here.

**Comment by santoshppg** [comment]
Thanks guybedford, I get this error when I use System.resolveSync... "System.resolveSync is not a function".... But, I managed to find a solution to this problem: https://stackoverflow.com/questions/48274567/how-to-load-an-angular2-component-from-angularjs-more-than-one-time/49185911

**Comment by guybedford** [comment]
@santoshppg that may be due to an older version of SystemJS, but glad you found the fix there.
