### ISSUE TITLE
Why are named imports from JSON forbidden?

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#1804]
SystemJS 0.20 removes the ability to use named imports from non-ES modules for consistency with [NodeJS ES module directions](https://github.com/nodejs/CTC/pull/60/files#diff-2b572743d67d8a47685ae4bcb9bec651R217). 

This is done for the following reasons:
> V8 team has misgivings on this because it would require pessimistically guarding against all potential side effects for accessing all imported variables, including in ESM to ESM calls. For example, would mean none of those can be inlined.

and

>**Temporal Dead Zone Problem**: Exported names from CJS modules are not definitively known till after the CJS module is evaluated, not at parse time.  
ES spec guarantees that exported names are definitively known at parse time, prior to evaluation. For example, ES specifies throwing an error at parse time if an undefined name from an imported module is used, but for CJS modules whether that name is defined or not cannot be absolutely determined till after evaluation.

None of this concerns importing from a JSON file! Therefore, I would like to understand why named imports have been excluded for JSON in SJS 0.20?

**Comment by guybedford** [comment]
If you try running the latest version of NodeJS with `node --experimental-modules a.mjs` where `a.mjs` contains `import * as m from './b.json'`, you will notice that named exports are not supported and the JSON is only available as the default.

If you want to change this, post an issue to Node, and may the debate ensue.

SystemJS is just trying to move to a compatibility place where it can roughly match what things will actually be like in Node.

**Comment by CxRes** [comment]
Done! Please do share your 2 cents on nodejs/node#19306
