### ISSUE TITLE
SystemJS swallows a part of the error stack

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#1805]
*Occurs both on 0.19 and 0.20 but with slightly different error messages*

Lets say we have a file `src/index.js` which loads `src/app.js` 

Now `src/app.js` imports an external dependency, lets call that `dep`
```js
// src/app.js
import dep from 'dep';
dep();
```

Now, main in `dep` has a function that expects a `String`. Lets take `@node/path`:
```js
// dep/main.js
import path from '@node/path';

function doSomething(foo) {
    let bar = path.join('xyz', foo);  // Error
    ...
}

export default doSomething;
```

The error message looks like the one below:
```
Error: Path must be a string. Received undefined
  Evaluating chrome-extension://ckdfecgjleemcjkaocabhlfniljklfic/src/app.js
  Evaluating chrome-extension://ckdfecgjleemcjkaocabhlfniljklfic/src/bootstrap.js
  Loading src/bootstrap.js
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
```

For some inexplicable reason there is no mention of `dep` in the error message, where the error actually occurs. I am presuming this to be a bug...

**Comment by guybedford** [comment]
Is that the full error stack here? Is there not more below the `Object.resolve` line?

**Comment by CxRes** [comment]
Absolutely Nothing!!!!

**Comment by guybedford** [comment]
Interesting, it does sound like there should be an Evaluating line for the dep.js.

Any chance you could try putting this together as a test case PR here?

**Comment by CxRes** [comment]
I wouldn't know where to begin with writing a test case but if you can point me to an example I'll try to take a stab at it this weekend.

**Comment by guybedford** [comment]
SystemJS 2.0 no longer mutates error stacks.
