### ISSUE TITLE
Sporadically get error only in iFrame: Main.js Interpreted as amd module format, but called System.register.

### ISSUE THREAD

**Issue by juminoz** [systemjs/systemjs#1808]
This seems to be the same issue as the one that was closed a couple years ago, but for this case it only happens in an iframe.

https://github.com/systemjs/systemjs/issues/970

It happens consistently in Safari, but sporadically in Chrome. The issue only started last week with no code change so I'm at a lost on what could have gone wrong.

system.src.js:3054 Uncaught Error: Module https://d1jbmqjs327xbn.cloudfront.net/_ra/spaces-developer.pxand/assets/js/framework/builder/builder-client.js interpreted as amd module format, but called System.register.
    at a.<anonymous> (system.src.js:3054)
    at a.<anonymous> (system.src.js:3773)
    at a.reduceRegister_ (system.src.js:4268)
    at HTMLScriptElement.m (system.src.js:2851)

@guybedford You mentioned that this could happen for many reasons, do you mind listing them out so I can try to figure out what case this is.

**Comment by guybedford** [comment]
@juminoz which version of SystemJS are you running here?

**Comment by juminoz** [comment]
0.19.41

I found a workaround for this particular case. The issue was jQuery UI. I had to switch to an older version that doesn't support AMD. I'm still not sure how it happened all the sudden, but at least I found a workaround.

**Comment by guybedford** [comment]
Thanks for the update here. Will close for now, but if you want a follow up please share the replication info.
