### ISSUE TITLE
How do I find out what SystemJS is doing?

### ISSUE THREAD

**Issue by lll000111** [systemjs/systemjs#1811]
I have a line

```js
require('../tools/communication-server.js');
```

And no matter how I configure the map nothing works:

```js
    SystemJS.config({
        baseURL: '..',
        map: {
            'chai': '../node_modules/chai/chai.js',
            'chai-as-promised': '../node_modules/chai-as-promised/lib/chai-as-promised.js',
            // dependency of chai-as-promised
            'check-error': '../node_modules/check-error/check-error.js',
            'js-sha256': '../node_modules/js-sha256/build/sha256.min.js',
            '.../tools/': '@empty',
            '../tools/communication-server.js': '@empty',
            './tools/communication-server.js': '@empty',
            'tools/communication-server.js': '@empty',
            'communication-server.js': '@empty',
            'websocket': '../lib/system/websocket.js',
            'ws': '@empty'
        }
    });
```

I don't want to load that module in the browser environment, but it is always loaded!

Same with a request for `websocket`, for which I cannot find a `require` anywhere (the ".js" is missing but there is not a single require statement left in the code that attempts to load that module without "js" ending).

How do I find out what on earth SystemJS is doing???

The rest of the map stuff works, for example "ws" is not loaded as configured.

I cannot find any information on how to debug this apart from editing SystemJS sources and adding console.log statements there. Why does it not work in the first place? "map" from x => y should be simple, no?

I also tried with "path" (set to nowhere, just to see what happens):

```js
        paths: {
            '../tools/': 'https://code.mycdn.com/app-1.2.3/'
        }
```

but this does nothing at all either.

What is the MAGIC needed for all those configuration options to actually DO SOMETHING? How do I find out WHY they don't do anything? As far as I can see from reading the little documentation there is it *should* do *something* (even if it's not correct), but nothing at all happens.

The docs for "map" say its for plain names - but "/" are allowed. Since I also tried "path" because this is a relative path I'm not sure what else is left.

**Comment by lll000111** [comment]
Okay useless, who cares.

**Comment by ArmorDarks** [comment]
Seems like you need JSPM (check ^0.17 beta)
