### ISSUE TITLE
[question] is systemjs the right solution for what I'm doing?

### ISSUE THREAD

**Issue by choucalate** [systemjs/systemjs#1812]
I have a dumb question.
I’m trying to load arbitrary react components/packages on the fly and render them in my application.
Ideally, these arbitrary independent components can be hosted on a cdn somewhere, and I want to be able to load them dynamically.
Is SystemJS the right solution to use in this?  If I’m using web pack, can System JS reference the React/ReactDOM references I’m using within web pack and supply them to these components that do not have React bundled inside them?

I'd prefer to use SystemJS over RequireJS because of the wide amount of module formats that I can provide and use instead.

**Comment by guybedford** [comment]
This is exactly the sort of use case SystemJS is built for. You may want to look into the SystemJS production loader for this if you are just loading UMD, globals, AMD and System.register modules. If you need CommonJS then you'll want to use the dev loader though, which is a lot bigger and more heavy weight.

**Comment by dreamflow** [comment]
from reading the [mainpage](https://github.com/systemjs/systemjs) my impression was so far
that the SystemJS-production-loader can only load the
System format directly .
good to hear that it can load more formats .

i suggest adding the info what formats the SystemJS-
production-loader can directly load to the [mainpage](https://github.com/systemjs/systemjs) \:
System, AMD, UMD, globals, Web Assembly

the [docs/production-build.md](https://github.com/systemjs/systemjs/blob/master/docs/production-build.md) page does not mention
that the SystemJS-production-loader can load UMD .

**Comment by choucalate** [comment]
@guybedford How do we consume the dev loader on the browser side with a webpack bundler if it uses the nodeRequire? Do you have an example? https://github.com/systemjs/systemjs/blob/6fdd0a95dc5a6a33920e571a1d1890430853da70/src/instantiate.js#L10
