### ISSUE TITLE
Starting from 0.21.1, SystemJS leaks strict mode to loaded modules (Breaking Change)

### ISSUE THREAD

**Issue by stefanocke** [systemjs/systemjs#1815]
Starting with 0.21.1 we get errors, when loading modules that are not yet written in "strict mode".
(In our case, it was CKEditor 4, which uses for example "arguments.callee", which ist forbidden in strict mode).

Debugging into SystemJS, we found the reason:

Before 0.21.1:
https://github.com/systemjs/systemjs/blob/2d40444a3779d4e7f60fe0abcffed45c6767adaa/dist/system.src.js#L2805

Starting with 0.21.1:
https://github.com/systemjs/systemjs/blob/b2dba015c4f30eca8602feab2d341cd7f135387b/dist/system.src.js#L2802

As you can see, before 0.21.0, the code has been evaluated with "(0, eval)". Starting with 0.21.1, it is evaluated with (eval).
The first does not 'leak' strict mode, but the second does. (See also https://stackoverflow.com/questions/19357978/indirect-eval-call-in-strict-mode)

It seems, the code change came from the update of the rollup plugin and / or the rollup configuration.
(BTW:  rollup has some warnings regarding eval ... https://github.com/rollup/rollup/wiki/Troubleshooting#avoiding-eval)

**Comment by guybedford** [comment]
Thanks, yes this is a build bug - I've just published a 0.21.3 with the fix.
