### ISSUE TITLE
Angular 6 Support

### ISSUE THREAD

**Issue by rbmanian75** [systemjs/systemjs#1822]
We see that angular 6 is dependent on rxjs 6.

We are getting the following errors

![image](https://user-images.githubusercontent.com/1324600/40318959-57e5c772-5d1e-11e8-986d-ec31ab5896ad.png)

Is there anyway to fix this isssue?

**Comment by Ks89** [comment]
same issue

**Comment by rbmanian75** [comment]
I have solved it by adding this to paths of system.config

        "rxjs/internal-compatibility": "../../../../node_modules/rxjs/internal-compatibility/index.js",
        "rxjs/testing": "../../../../node_modules/rxjs/testing/index.js",
        "rxjs/ajax": "../../../../node_modules/rxjs/ajax/index.js",
        "rxjs/operators": "../../../../node_modules/rxjs/operators/index.js",
        "rxjs/webSocket": "../../../../node_modules/rxjs/webSocket/index.js"

and to the packages
        "rxjs/internal-compatibility": { main: "index.js", defaultExtension: "js" },
        "rxjs/ajax": { main: "index.js", defaultExtension: "js" },
        "rxjs/operators": { main: "index.js", defaultExtension: "js" },
        "rxjs/testing": { main: "index.js", defaultExtension: "js" },
        "rxjs/webSocket": { main: "index.js", defaultExtension: "js" },
        "rxjs": { main: "index.js", defaultExtension: "js" },
