### ISSUE TITLE
version 0.19 vs 0.20 

### ISSUE THREAD

**Issue by PrimeTime416** [systemjs/systemjs#1823]
I was trying to use the systemjs model with a CDN via codepen, I as able to get it to work with version 0.19 but none of the version 0.20 work? The error message I am getting is:

`  <script  src="https://unpkg.com/systemjs@0.20.0/dist/system.js"></script>
  <script src="/scripts/config.js"></script>`

![image](https://user-images.githubusercontent.com/20260606/40392307-2ce7fb00-5de9-11e8-954a-2bb61cae6b7a.png)

*** and this works now problem,  I know things changed between versions but this is really broken?
` <script  src="https://unpkg.com/systemjs@0.19.31/dist/system.js"></script>
  <script src="/scripts/config.js"></script>`

![image](https://user-images.githubusercontent.com/20260606/40392390-6d29a0ba-5de9-11e8-841f-5c7bb9c32e87.png)

**Comment by amenadiel** [comment]
The config file and deoendencies packages definition are different between both versions. You should upgrade jspm locally, then follow the upgrade steps to transform your config.js to jspm.config.js, then reinstall the loader and dependencies.

If you want to try it live on codepen, you would at least need to provide it with a valid config file.
