### ISSUE TITLE
RxJS 6

### ISSUE THREAD

**Issue by dinony** [systemjs/systemjs#1825]
Hi,

I'm using [systemjs](https://github.com/dinony/od-virtualscroll/blob/a64656a6dc2b30d3f4e2b2ea771e1a49a24a3fd5/package.json#L92) for a small demo in an angular lib. 
I've tried to adapt the [config](https://github.com/dinony/od-virtualscroll/blob/feature/upgrade/demo/systemjs.config.js) to use rxjs6. The actual import statements are [here](https://github.com/dinony/od-virtualscroll/blob/a64656a6dc2b30d3f4e2b2ea771e1a49a24a3fd5/demo/src/app.component.ts#L3-L4).
With the current config file the following mapping does apply (correct me if I'm wrong):

```
// node_modules/rxjs/index.js
import {Observable} from 'rxjs' 

// nodule_modules/rxjs/operators/index.js
import {reduce} from 'rxjs/operators' 
```

With this setup, rxjs internally requires:

```
var reduce_1 = require("../internal/operators/reduce");
exports.reduce = reduce_1.reduce;
```

and this results in a 404 for `http://localhost:3000/node_modules/rxjs/internal/operators/reduce`.

How can I apply a file extension or what is the recommended setup in this case? 

Thanks a lot!!

**Comment by strpipe** [comment]
Take a look here: https://github.com/ReactiveX/rxjs/blob/master/integration/systemjs/systemjs-compatibility-spec.js 
Does this do the trick?

**Comment by dinony** [comment]
Yeah awesome, thanks! Didn't know about the integration file in the rxjs repo.
