### ISSUE TITLE
SystemJS 2.0 ideas

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1833]
It would be nice to start working towards a SystemJS 2.0.

The basic principle would be to provide the absolute smallest kernel of a loader, then go back to enabling separate "plugins" that can be added to provide different functionality.

The kernel would effectively be the register loader (https://github.com/ModuleLoader/system-register-loader), including WASM and native ES module loading support.

Then plugins could include:

* Global modules
* AMD modules
* CommonJS modules
* SystemJS dev loader and plugin system
* Depcache
* Map config
* Package maps (TODO)

**Comment by cxq** [comment]
Hi @guybedford,

Thanks for all your effort. I'm implementing SystemJS at the moment for large scale applications.
What I'd like to have is:

- The possibility to create an extendable system.config, like the way we do to extend eslint, stylelint rules.
- Stop relying only on JSPM to install packages?

Thanks a lot.
Xiu

**Comment by guybedford** [comment]
SystemJS 2.0 has been released now.

@cxq see Rollup code splitting workflows for a SystemJS workflow without jspm. jspm 2.0 should follow soon though.
