### ISSUE TITLE
defaultExtension not applied on all pages

### ISSUE THREAD

**Issue by ataraxis** [systemjs/systemjs#1835]
I'm using `defaultExtension` to apply the `js` extension to modules imported from Typescript. This works fine if the containing html page has a structure like `http://domain.com/page`, but when the url is something like `http://domain.com/page/more` then `defaultExtension` is no longer applied.

I'm able to change the url of the page from `/page/more` to `/page` using `history.pushState` before SystemJS loads and `defaultExtension` will then work. However i don't want to have to manipulate my urls in this way.

Here's a minimal config that reproduces the issue:

```javascript
    System.config({
        map: {
            'app': 'assets/javascripts',
        },
        packages: {
            'app': {
                defaultExtension: 'js',
            },
        },
    });
```

So if i have `import thing from './module'` in my Typescript, then when the url of the containing page is `/page`, the browser loads `/assets/javascripts/module.js`. But if the url of the containing page is `/page/more`, the browser attempts to load `/assets/javascript/module` instead.

**Comment by fahadash** [comment]
@guybedford Seems like this issue came back with 2.0. There is no way to define defaultExtension anymore. I have checked the docs and there is nothing in there about this.

**Comment by guybedford** [comment]
@fahadash in 2.0 defaultExtensions are not supported by design (unless through plain package maps), just like they are not supported in the browser module loader.
