### ISSUE TITLE
Load chunks

### ISSUE THREAD

**Issue by mitkaaa** [systemjs/systemjs#1838]
Hi!

There are two modules **A** and **B**. **A** the parent of the **B** child.

- A
-- index.js
- B
-- index.js
-- 0.index.js

**B** has a dependency on the chunks, which are loaded asynchronously.

Modules build a webpack. SystemJS only uses for loading modules like AMD.

How to get inside the module **B** it's own URL?

**Comment by guybedford** [comment]
This is what `System.register('name', ...` does - defines modules inside chunks. Can SystemJS builder was designed to support these outputs.

The entire approach is now deprected for Rollup code splitting workflows though, which provide superior optimization using ES module semantics.
