### ISSUE TITLE
esModule, TypeScript and the mystery of .default

### ISSUE THREAD

**Issue by ciddan** [systemjs/systemjs#1840]
Hey SystemJS peeps,

I've run in to this issue so many times now - I'd just like to finally understand the issue and know if I can fully fix it somehow. 

I've got my TypeScript project configured to compile to the SystemJS module format. Mostly everything works great. There is however one issue that crops up from time to time that I've found I can't get around: namely when I import some external packages, they may generate `blabla is not a function` errors at runtime. Invariably it is because my TS => JS compiled output is `foo_bar_1.function()` while, at runtime, the correct thing should be `foo_bar_1.default.function()`.

I've put together the following example for a more real-world scenario to illustrate. If needed I'd more then happily set up a reproduction repository.

``` JavaScript
// JS module I'm trying to import. This is source from a module in node_modules
var index = {
  createLocalVue: createLocalVue,
  createWrapper: createWrapper,
  config: config,
  mount: mount,
  shallow: shallow,
  shallowMount: shallowMount,
  TransitionStub: TransitionStub,
  TransitionGroupStub: TransitionGroupStub,
  RouterLinkStub: RouterLinkStub,
  Wrapper: Wrapper,
  WrapperArray: WrapperArray
}

module.exports = index; // no default export defined here!

/* -------------------------------------- */

// my ts source
import {createLocalVue} from "@vue/test-utils";
createLocalVue();

// compiled js
test_utils_1.createLocalVue(); // not a function

/* -------------------------------------- */
// alternate ts source
import testUtils from "@vue/test-utils";
testUtils.createLocalVue();

// compiled js
test_utils_1.default.createLocalVue(); // works!
```

It is my understanding, from the documentation, that adding
```JavaScript
meta: {
    "node_modules/@vue/test-utils/vue-test-utils.js": {
        esModule: true
    }
}
```
would fix scenario 1, i.e. that I could use the named imports that are _actually_ exported from the module. But I **can not** get that to work. No matter what I do, all functions exported from `@vue/test-utils` are only available under the .default property.

**Comment by guybedford** [comment]
Should the meta path here not be `node_modules/@vue/test-utils/dist/vue-test-utils.js`? Matching the path exactly is usually the issue here. A nice way to verify it is also to ensure that `System.resolveSync('node_modules/@vue/test-utils/dist/vue-test-utils.js')` exactly matches the path in the registry (`System.resolve('@vue/test-utils')`).
