### ISSUE TITLE
module is not provided as a parameter in function if define.amd is present in the code

### ISSUE THREAD

**Issue by surgicaI** [systemjs/systemjs#1843]
- We were trying to use following library with out typescript code:
   https://github.com/davidchambers/string-format
- But it was giving following error:
   "module detected as amd but didn't execute correctly"
- While investigating we found out that *module* is undefined in index.js file of string-format lib.
- After removing following line from code things started working:
else if (typeof define === 'function' && define.amd) 
- We are using latest version(0.21.4) of systemJs

**Comment by guybedford** [comment]
This sounds like the format detection of SystemJS. Explicitly setting the format was the recommended pattern here, although that is no longer necessary in SystemJS 2.0.
