### ISSUE TITLE
System.locate modification for cache-busting isn't working with SystemJS 0.21.4

### ISSUE THREAD

**Issue by fahadash** [systemjs/systemjs#1849]
I am using SystemJS 0.21.4 I got this from npm. I realized that this version doesn't work with the cache-busting technique which requires `System.locate` to be "overridden".

Here is one
https://www.unitydatasystems.com/blog/2015/12/15/angular-2-systemjs-cache-busting/

Here is a full on SystemJS plugin that doesn't work anymore.
https://github.com/oricalvo/systemjs-cachebuster#systemjs-cache-buster

Is there any alternate method to get cache-busting?

**Comment by guybedford** [comment]
See previous issues for help - https://github.com/systemjs/systemjs/issues/172, https://github.com/systemjs/systemjs/issues/1616.

If you come up with an approach please do share your solution.
