### ISSUE TITLE
SystemJS 2.0 doesn't work with CommonJS, AMD, UMD packages, there is no more defaultExtension in packages, and even "system" module doesn't work

### ISSUE THREAD

**Issue by fahadash** [systemjs/systemjs#1850]
2.0 Release broke my code that was transpiling modules in CommonJS format. I started getting "ReferenceError: exports is not defined".

I changed the module format to AMD and got "define is not defined"

I changed the format to "system", it seems to work but it is ignoring my `defaultExtension` and trying to load 

/path/to/mymoduleclassB

for the following

```ts
import {MyModuleClassB} from "./mymoduleclassB"
```

I am not sure if 2.0 will work with Angular, an example would be great.

**Comment by guybedford** [comment]
@fahadash thanks for trying out SystemJS 2.0, but do carefully read the deprecation notes in the release post as it is a major breaking upgrade path. As mentioned in the release post - there is no pressure to upgrade here either.

For AMD support in SystemJS 2.0 you need to add the "AMD extra" available here - https://github.com/systemjs/systemjs/tree/master/dist/extras.

SystemJS 2.0 provides no configuration at all apart from package maps currently, so yes defaultExtension isn't possible.

**Comment by fahadash** [comment]
I tried with package maps too. I will share my config json. Currently on phone.

**Comment by fahadash** [comment]
By the way, if 2.0 makes the breaking changes, which latest version will be most aligned with 0.21.*?

**Comment by guybedford** [comment]
@fahadash `npm install systemjs@0.21.5` is the latest 0.21 branch release.

**Comment by fahadash** [comment]
@guybedford  I was hoping there were some later alpha releases (like 1.0.0) that would allow me to have package maps and default Extensions and would allow CommonJS modules without installing any plugin.

**Comment by guybedford** [comment]
@fahadash a commonjs extra can definitely be useful, and could work as a
drop in for 2.0.0.

**Comment by amenadiel** [comment]
> there is no pressure to upgrade here either.

He he, there's no pression from your part, but I feel I must try it. ASAP. I skipped alpha due to lack of spare time, I can't skip this one.
