### ISSUE TITLE
README still refers to @alpha (and several questions)

### ISSUE THREAD

**Issue by amenadiel** [systemjs/systemjs#1851]
README.md should be updated. It still says `npm install systemjs@alpha`. 

Now, I have so many questions

-  don't get how are we supposed to load it. Should we copy it from  `node_modules` folder to our `public` folder? 
- JSPM will still load older versions of SystemJS, so 2.0 will pass unnoticed to everyone using `jspm dl-loader` in their workflow. I get it, if it weren't so things would break, but there should be a new jspm version to load 2.0 version.
- Will the old loaders (json, less, css, handlebars) work with minor adjustments to hooks?
- The `package name maps` does mean `jspm.config.js` and `jspm.browser.js` will be deprecated?
- If our document root is the public folder, and `node_modules` is not public, this means package maps won't see referred packages, so we will need to move `node_modules` into public folder, therefore move tools referencing node modules to public too (e.g. karma.conf.js)?
- Will a future version of JSPM update the package name maps for us or will we have to do this every time we add a package?

**Comment by guybedford** [comment]
Thanks, I've updated that reference. Glad to answer questions on it, sure.

> don't get how are we supposed to load it. Should we copy it from node_modules folder to our public folder?

I guess so, or use the jsdelivr CDN version or just reference node_modules directly.

> JSPM will still load older versions of SystemJS, so 2.0 will pass unnoticed to everyone using jspm dl-loader in their workflow. I get it, if it weren't so things would break, but there should be a new jspm version to load 2.0 version.

Yes exactly, this is coming. jspm 2.0 is currently in beta. Sign up for an invite here - https://docs.google.com/forms/d/e/1FAIpQLSenR5AjHN2_Ks1pWxaw7YPak4quhHLIrM9Bx3XON4WvaMD9RA/viewform

> Will the old loaders (json, less, css, handlebars) work with minor adjustments to hooks?

Yes this should be very straightforward. A compatibility layer could even be created, but it would probably be easier to just update them. See for example the Babel transformer.

Note that there is no "plugin selection system" anymore (either via `plugin` config or `!plugin` syntax). The suggestion here would be for transformers to basically do transformation based on file extensions so they can all just chain together without any configuration necessary apart from their own compilation options. A pattern for piping in those compilation options is also yet to be determined.

> The package name maps does mean jspm.config.js and jspm.browser.js will be deprecated?

Yes, instead a package name map is now generated by jspm.

> If our document root is the public folder, and node_modules is not public, this means package maps won't see referred packages, so we will need to move node_modules into public folder, therefore move tools referencing node modules to public too (e.g. karma.conf.js)?

Yes, unless using jspm.

> Will a future version of JSPM update the package name maps for us or will we have to do this every time we add a package?

As above, yes via `jspm map`.

**Comment by guybedford** [comment]
@amenadiel thanks again for the feedback, will close this for now, but further feedback discussion very welcome. If there are missing features to implement I am all ears, and have already added named register support in a custom extra by demand.
