### ISSUE TITLE
Adding global property to Package Name Map

### ISSUE THREAD

**Issue by xwisdom** [systemjs/systemjs#1852]
Hello,

Thanks for the work that you have done on SystemJS 2.0.

I have just one question for you. Wouldn't it be easier to add a global property to the package name map format rather than trying to always auto detect the last defined global?

I think the auto-detection feature is great but there are times when it might not work as intended.

<script type="systemjs-packagemap">
{
  "packages": {
    "jquery": {
      "main": "jquery.min.js",
      "path": "/path/to/jquery",
      "global": "jQuery"
    }
  }
}
</script>

**Comment by guybedford** [comment]
Sure!

Do you have a specific example of something that isn't working through the global loader?

I want to try and stay as close to spec as possible so only add fixes / escape hatches where absolutely necessary.

Note also that another way to load a global would be the following:

jquery-module.js
```js
import 'jquery.min.js';
export default window.$;
```

So that I think that would be the idea escape hatch if things don't work correctly rather than changing the behaviour of package maps.

Let me know if that can work for you.

**Comment by xwisdom** [comment]
Thanks for the workaround but this would require an additional import file for each external library or global object.

Here's an example where systemjs failed to detect the jQuery global:


```html
<script type="systemjs-packagemap"> 
{
   "packages": { "jquery": { "main": "jquery.min.js", "path": "assets/jslibs/jquery" } } 
} 
</script>
<script src="/path/to/system.js" ></script>
<script src="/path/to/jquery.js" ></script> <!--preload jquery lib for faster load time -->
<script>
    System.import('jquery').then(e => console.log(e.default)) //output: undefined
</script>
```


The auto-detection will also fail in cases where multiple global objects are defined within a single file or external library bundle.

If this change requires a lot of modification to the core, then is it possible to create a plugin to add this feature to SystemJS library?

**Comment by guybedford** [comment]
@xwisdom when running a build that wrapper would be inlined into the main file so that shouldn't be a problem.

If preloading jQuery for faster load time, rather preload it with a `System.import` in such a scenario.

The core is completely hackable yes, you are free to modify it as you wish.

**Comment by guybedford** [comment]
Sure, just let me know if I can help further at all.
