### ISSUE TITLE
CrossOrgin attribute set to 'anonymous' in SystemJS 2.0.1

### ISSUE THREAD

**Issue by xwisdom** [systemjs/systemjs#1859]
Hello,

The crossorigin was added in 2.0.1, but can you please explain why this attribute was added and its value hard-coded? 

I've noticed that in version 0.21 the crossorigin attribute was optional and the value could be set by the developer.

Here's a discussion in 2016 about setting a default value for crossorigin: https://github.com/systemjs/systemjs/issues/1156

**Comment by guybedford** [comment]
@xwisdom thanks for asking - this was changed in the HTML specification recently, so SystemJS has followed the same direction.

The issue at https://github.com/systemjs/systemjs/issues/1847 is tracking ways to do custom credentials, would value your feedback there.

I'm currently wondering if we might need to support something like:

```html
<script type="system-module" src="https://site.com" crossorigin="use-credentials">
```

**Comment by xwisdom** [comment]
Thanks for the quick reply.

I'll post my feedback on the new configuration.

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by guybedford** [comment]
Let's continue tracking this in #1847.
