### ISSUE TITLE
Requesting a method to set Package Map from JavaScript

### ISSUE THREAD

**Issue by xwisdom** [systemjs/systemjs#1860]
Hello,

I'm recommending a new method be added to the library to allow developers to set the package map from within JavaScript. This method will be useful in cases where we need to generate a package map dynamically.

Example:
```javascript
System.setPackageMap(jsonString);
// or 
System.setPackageMap(packageMapObject);
```

What do you think about this idea?

**Comment by PixleProgrambetaxl** [comment]
+1

**Comment by guybedford** [comment]
@xwisdom would the following work for you here:

```html
<script>
const packageMap = generatePacakgeMap();
const script = document.createElement('script');
script.type = 'system-packagemap';
script.innerHTML = JSON.stringify(packageMap, null, 2);
document.head.appendChild(script);
</script>
<script src="system.js"></script>
```

If there are any bugs on the above workflow we can certainly look into them.

**Comment by xwisdom** [comment]
@guybedford this will work if you're generating the package map before loading systemjs, but what if you want to generate it after loading systemjs?

**Comment by guybedford** [comment]
@xwisdom the current plan is for package name maps not to support being loaded after the first module has been loaded I believe. But we could consider deviating from this yes.

**Comment by xwisdom** [comment]
@guybedford thanks a lot for considering this option.

**Comment by guybedford** [comment]
This could certainly also be a justification for a System.config function, with a packageMap option as an alternative configuration.

As much as possible we should stick to what browsers will do, but it isn't at all clear what the dynamic package map story will be at this point.

**Comment by xwisdom** [comment]
@guybedford I don't think we need a System.config function since package map is ideal for most use cases.

**Comment by blittle** [comment]
The spec recommends appending a new package map to the DOM: https://github.com/domenic/import-maps#dynamic-import-map-example

It looks like SystemJS doesn't take into account multiple package maps on the DOM: https://github.com/systemjs/systemjs/blob/a0b95a50830ff97b58b29f19b885a058605fbe4c/src/features/package-name-map.js#L8

@guybedford would you be apposed with me sending an PR that changes SystemJS to handle multiple package maps?

**Comment by blittle** [comment]
@guybedford I'm looking at the specification, and it isn't clear to me how the package maps should merge when there are multiple. For example, inside the tests there is the map:

```json
{
   "packages":{
      "x":"/y",
      "p":{
         "path":"t"
      },
      "m":{
         "main":"index.js"
      }
   },
   "scopes":{
      "/scope":{
         "packages":{
            "x":"/y"
         }
      }
   }
}
```

Clearly, the package `x` will be overridden if another map is subsequently loaded that has:

```json
{
   "packages":{
      "x":"/y2"
    }
}
```

But what should happen if the following map is loaded?
```json
{
   "packages":{
      "x":"/y",
      "p":{
         "main":"file.js"
      }
   }
}
```
Should the `main` property get merged in with the `path` property of the previous map? Or should it completely override the previous?

Related, what should happen with merging `scopes`?  Would the following merge in a new module `z` inside `/scope` while also introducing the new `/scope2`?
```
{
   "scopes":{
      "/scope":{
         "packages":{
            "z":"/t"
         }
      },
      "/scope2":{
         "packages":{
            "h":"/j"
         }
      }
   }
}
```

**Comment by guybedford** [comment]
I would suggest we start off being cautious by actually throwing when packages collide in scopes or at the base level. so - `Error: package "p" has already been defined.

We can relax this constraint if the spec were to allow it in future.

For scopes I think we should merge them always, so that the new scope is defined as well as the new package in the old scope in your example.

**Comment by guybedford** [comment]
It seems this feature is being explicitly blocked. Tracking in https://github.com/domenic/import-maps/issues/92. Please do voice your support there if you care about this. //cc @blittle.

**Comment by blittle** [comment]
@guybedford I have an implementation that would work with the specification as thus defined, where multiple maps could get processed and override eachother, but only happen _once_ before any resolutions have taken place.

**Comment by blittle** [comment]
Or in other words, the implementation would not allow subsequent dynamically defined maps to be processed. Only once up front.

**Comment by guybedford** [comment]
Ahh, great, that would be good to include. See also https://github.com/systemjs/systemjs/pull/1893.

**Comment by frehner** [comment]
Hey @blittle, is there anything blocking you from submitting your work as a PR? Or is it pushed up somewhere where someone can look at it/continue the work? 

Would love to have multiple package maps support. :)

**Comment by joeldenning** [comment]
I too am interested in this

**Comment by dmail** [comment]
Would be usefull when systemjs is used on node (like I do).

**Comment by guybedford** [comment]
Let's move this to https://github.com/systemjs/systemjs/issues/1993.

**Comment by berif92** [comment]
coin,snapshot height,amount
ETH,-,64

coin,Type,Network,Snapshot Height,address,amount,message,signature1,signature2,redeem script/public key,EOA1,EOA2
ETH,Non Staking,ETH,20914735,0x0cdcdb19a857c2ac24818ca4fdfe38cce071483e,0.058959708849230328,I am an OKX address,0x07f19879aa28d51c97cddfdfecffe7ed96525545d041aee4f4386b0bf4c1a26924b637fb02ccbb97305c13daa51a0f50b8896fb25ecbaf60020cde920d227a221b,,,,
ETH,Native ETH Staking,ETH,20914735,0xabababababababababababababababababababababababababababababababababababababababababababababababab,32,I am an OKX address,0x07f19879aa28d51c97cddfdfecffe7ed96525545d041aee4f4386b0bf4c1a26924b637fb02ccbb97305c13daa51a0f50b8896fb25ecbaf60020cde920d227a221b,,,0x0cdcdb19a857c2ac24818ca4fdfe38cce071483e,
ETH,Eigenlayer Staking,ETH,20914735,0xcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcdcd,32,I am an OKX address,0x07f19879aa28d51c97cddfdfecffe7ed96525545d041aee4f4386b0bf4c1a26924b637fb02ccbb97305c13daa51a0f50b8896fb25ecbaf60020cde920d227a221b,0xf6e60fd5d2692eaf813cbb38369c160781a063e39dbadde9a88998a4c8019e08488f83a6e7ee5e5b3fbdd50f25db631150070e8bb470d1474eb0e6d9a1fd0c561c,,0x0cdcdb19a857c2ac24818ca4fdfe38cce071483e,0x16f01cfc16b0b8c3400fb8e5099b0974fcc9fc12
