### ISSUE TITLE
How is systemjs's browser compatibility?

### ISSUE THREAD

**Issue by xdlrt** [systemjs/systemjs#1861]
I can't find a lot information about browser compatibility, I want to know if I can use this lib in IE9+ with promise and fetch polyfills.I hope you can help me, thanks.

**Comment by guybedford** [comment]
@xdlrt SystemJS 0.21 has been tested for IE9, yes. SystemJS 2.0 works only in IE11+.

**Comment by xdlrt** [comment]
thx,I will try 0.21
