### ISSUE TITLE
Is there support for JWT and / or custom Authorization headers?

### ISSUE THREAD

**Issue by edisontrent1337** [systemjs/systemjs#1862]
Is it possible to import modules that are secured via http basic?
I need to fetch a module from a different origin that is secured via http basic, and I couldn't figure out how to do it without disabling http basic auth for certain endpoints of my application.

**Comment by guybedford** [comment]
Did you try using inline authentication (`https://x:a@site.com/...`)? Or has that been disabled in browsers now?

**Comment by edisontrent1337** [comment]
I am sorry, I totally missed the point in my question. The resource in question is not secured via http basic, its like this: I need to send a JSON Web Token to access the endpoint with the resource. Is there a way to add Authorization Headers to the request that SystemJS does? 
Thank you for your help!

**Comment by guybedford** [comment]
Right, in SystemJS 0.21 this is provided via a configuration option if you're using SystemJS 0.21.

As for SystemJS 2.0, just like scripts and other web resources, there is no way to configure the authorization header. But this could be implemented as an extra to SystemJS 2.0, happy to advise re implementation.

**Comment by edisontrent1337** [comment]
I did not see the documentation in the 0.21 branch. Sorry to bother you and thanks!
