### ISSUE TITLE
`<script type="system-module">` support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1864]
With this we can then support the integrity and cross-origin attributes.

**Comment by Hypercubed** [comment]
In this case, would the content be ES module or System.register format?

**Comment by guybedford** [comment]
This would be for System.register module loading.

Supporting ES modules in this project is an interesting concept, but gets tricky where ES modules load other ES modules, because we can no longer control the resolver.

For that reason I usually like for this project to remain an isolated graph, and instead use ES module shims to load ES modules, but there could certainly be value in supporting native loading bridges.

It might get far with these use cases just to do something like `const nativeModule = await import('native-module'); System.set('native-module', nativeModule);` since that also allows conditionally checking for existence of the native loader (eg `if (hasDynamicImport)` branches in code etc).

**Comment by guybedford** [comment]
I'm referring to this project btw - http://npmjs.org/package/es-module-shims.

**Comment by guybedford** [comment]
Implemented in https://github.com/systemjs/systemjs/pull/2015.
