### ISSUE TITLE
Package map doesn't add ".js"?

### ISSUE THREAD

**Issue by KonradHoeffner** [systemjs/systemjs#1865]
I am unable to load core-js modules using systemjs 2.0.1 in Firefox 49 (to test the transpiled code). It seems as if systemjs forgets to add the ".js" at the end of "web.dom.iterable".

main.js:
```

"use strict";

System.register(["core-js/modules/web.dom.iterable", "core-js/modules/es6.set",...
```
The package map and dependency loading:

	<script type="systemjs-packagemap">
	{
  	"packages": {
    	"core-js": {"core-js": "./node_modules/core-js/x.js"}
  	}
	</script>
	<script src="node_modules/systemjs/dist/s.min.js"></script>
	<script src="node_modules/systemjs/dist/system.min.js"></script>

The error:

```
Unhandled promise rejection Error: Error loading file:///.../myproject/node_modules/core-js/modules/web.dom.iterable from file:///.../myproject/target/main.js
Stack trace:
h.instantiate/</<@file:///.../myproject/node_modules/systemjs/dist/system.min.js:4:4817
core.min.js
```

**Comment by guybedford** [comment]
Yes, file extensions are necessary in these build outputs. If you simply amend the JS extensions into the build output that should get you closer. Which build tool are you using here?

**Comment by KonradHoeffner** [comment]
I was using no build tool at the time, just babel with npm. Adding the .js extension at the end didn't fix the problem unfortunately, so I switched to Babel with Webpack now without SystemJS.

**Comment by guybedford** [comment]
Perfect, glad you are sorted out!
