### ISSUE TITLE
Sending a Bearer Authorization Header in SystemJS 0.21.5

### ISSUE THREAD

**Issue by edisontrent1337** [systemjs/systemjs#1867]
How do I exactly have to specify the meta configuration in order for SystemJS to send XHR requests?
I would like to send a JSON Web Token to access a bundle.js file cross origin.

**Comment by guybedford** [comment]
Yes we still need to add this and it can be done quite easily, we just need to decide on an approach here.

Currently tracking in https://github.com/systemjs/systemjs/issues/1863.

I'm still also not sure if we want to have a configuration system in core or what type of configuration pattern to use for extensions.

Could be something like:

```js
System.config({
  authentication: {
    'https://domain.com': 'authentication-header'
  }
});
```

or more property-based:

```js
System.authentication['https://domain.com'] = 'authentication-header''
```

**Comment by guybedford** [comment]
Let's continue tracking in #1863 though.
