### ISSUE TITLE
Loading esm and cjs for development workflow

### ISSUE THREAD

**Issue by mpfau** [systemjs/systemjs#1868]
Our current workflow consists of two steps:
* **Development:** Loading esm or cjs modules directly from the src tree of the project and replace modules whenever they are changed on the disk (hot reloading)
* **Bundling:** Use systemjs-builder to create bundles in System.register format (final distribution)

While the bundling part is supported by the new rollup code splitting, I quite don't get how we can implement the development step with systemjs 2.0.

I guess that we are expected to use rollup at development time, too. However, directly working on the src tree has the following advantages:
* No source maps are needed and debugging works perfectly
* The code parts to implement hot reloading (state management) could be removed from the final dist build (via rollup)

I would therefore propose to add support for loading esm and cjs modules to systemjs 2.0.

**Comment by mpfau** [comment]
cjs is already tracked with #1854

**Comment by guybedford** [comment]
@mpfau did you mean to reopen this?

**Comment by mpfau** [comment]
@guybedford Sorry, closed it by accident when I saw that there is already a ticket for cjs support. But I have found nothing about esm and hot reloading with system js 2.0.

What is your take on that?

**Comment by guybedford** [comment]
@mpfau the SystemJS 2.0 loader is designed to support hot-reloading, just the same as the previous version but with a slightly different API. It would be possible to upgrade https://github.com/alexisvincent/systemjs-hot-reloader to work with SystemJS 2.0 probably quite easily, but I personally am not taking this on right now.

**Comment by mpfau** [comment]
@guybedford As SystemJS 2.0 currently only supports loading the System.register format, we need to use Rollup. Unfortunately, after bundling with rollup, the information about the modules is lost and we end up with a single bundle. But we need that information to reload the module and all transitive dependencies. Or did I get something wrong?

**Comment by guybedford** [comment]
@mpfau did you take a look at the `experimentalCodeSplitting` feature in Rollup?

**Comment by mpfau** [comment]
@guybedford sure, but when I use it, no information about the modules is preserved...

**Comment by mpfau** [comment]
Yes, I am talking about hot reloading workflows for a single page webapp. I end up with one bundle that has been created from multiple esm modules. And ideally I would like to reload a single module and its dependencies. Hot the module context is lost during bundling with rollup.

That is fine for the distribution but I would like to be able to reload esm modules at development time...

**Comment by guybedford** [comment]
I see, yes these workflows are still being somewhat worked out. There was this project which implements hot module wrapping for Rollup - https://github.com/PepsRyuu/nollup.

**Comment by guybedford** [comment]
A systemJS approach for this in Rollup could well be useful, using the named system.register form.

**Comment by mpfau** [comment]
Thanks, nollup is an interesting reference! But why not load cjs/esm modules directly during development? That would be the simplest approach and wouldn't need any transpilation/bundling...

**Comment by guybedford** [comment]
Yes, that is what I am working on in jspm 2 beta. If you would like to join the private beta just let me know.

**Comment by jbadeau** [comment]
I’m also interested in jspm 2
