### ISSUE TITLE
Can't resolve modules with dependencies using the named-register extra

### ISSUE THREAD

**Issue by yuloh** [systemjs/systemjs#1871]
Hello,

I am creating a bundle with the typescript compiler which still uses the `System.register('name', ...)` format to register modules.  I saw that this is no longer supported in SystemJS 2.0 and I need to use the named-register extension.

With the extension registered I am able to resolve a module that doesn't depend on any other modules correctly.  However, I can't resolve a module that depends on other modules.  This seems to be because it tries to resolve the module name without the `bundle:` prefix.

The bundle generated by the typescript compiler looks like this:

```js
System.register("greeter", [], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    function greeter(person) {
        return "Hello, " + person;
    }
    exports_1("default", greeter);
    return {
        setters: [],
        execute: function () {
        }
    };
});
System.register("main", ["greeter"], function (exports_2, context_2) {
    "use strict";
    var greeter_1, user;
    var __moduleName = context_2 && context_2.id;
    return {
        setters: [
            function (greeter_1_1) {
                greeter_1 = greeter_1_1;
            }
        ],
        execute: function () {
            user = "Jane User";
            document.body.innerHTML = greeter_1.default(user);
        }
    };
});
```

And I'm resolving the module like this:

```
System.import('bundle:main');
```

...which results in the error `Unable to resolve bare specifier "greeter" from bundle:main`.

Is there any way to resolve named modules or will I need to wait for a fix in the typescript compiler?

**Comment by smialy** [comment]
Maybe this way:
```html
<script type="systemjs-packagemap">
{
    "packages": {
        "greeter": "bundle:greeter",
        "main": "bundle:main"
    }
}
</script>
<script>
    System.import('main');
</script>
```

**Comment by guybedford** [comment]
One thing we could even consider here is to alter the named register to register into the plain names directly without the `bundle:` prefix.

That would involve adding a check for all plain names to see if they are in the registry already before applying the package name map, but that is exactly what was done in previous SystemJS versions.

Let me see if I can update the extra, it may be a short enough release time that this can be done as an update to the named register extension despite being breaking.

**Comment by guybedford** [comment]
I've implemented and released the fix to no longer use the `bundle:` scheme in 2.1.0.

**Comment by guybedford** [comment]
(Let me know if that works out for you here please!)

**Comment by guybedford** [comment]
Thanks for the update.

**Comment by yuloh** [comment]
Wow, don't know how I typed @ myself 🤦‍♂️.  Glad you saw the notification anyway.
