### ISSUE TITLE
AMD aliasing

### ISSUE THREAD

**Issue by hirokiosame** [systemjs/systemjs#1872]
Aliasing a package and going into that package doesn't seem to work for me. For example:

Config
```
{
  "packages": {
    "lodash": "//unpkg.com/lodash@4.17.11/"
  }
}
```

```
define(
  'demo',
  ['lodash/union'],
  function (union) {
    console.log(union);
  }
);

System.import('demo');
```

Reproduction: http://jsfiddle.net/hirokiosame/wd7L3cp2/10/

By looking at the Network tab, it seems like it's requesting `http://fiddle.jshell.net/hirokiosame/wd7L3cp2/10/show/lodash/union`

**Comment by guybedford** [comment]
Try the path form here in the package map rather:

```js
{
  "packages": {
    "lodash": {
    	"path": "//unpkg.com/lodash@4.17.11/"
    }
  }
}
```

You probably want to be using an AMD / UMD build of lodash here too.

**Comment by hirokiosame** [comment]
Ahh, thank you!
