### ISSUE TITLE
How to use SystemJs.import?

### ISSUE THREAD

**Issue by juansaintclair** [systemjs/systemjs#1880]
I'm trying to use SystemJs.Import in a certain contexto: 
declareChildApplication('angularjs', () => SystemJS.import('http://10.189.2.42/angularjs.app.js'), pathPrefix('/angularjs'));

I`ve installed via yarn add systemjs and calling it in index:
<script src="node_modules/systemjs/dist/system.js"></script>

But I still getting this error: Uncaught ReferenceError: 'angularjs' died in status LOADING_SOURCE_CODE: SystemJS is not defined

What is happening? How to use SystemJs.import?

**Comment by TrySound** [comment]
>  envGlobal.System = new SystemJS();

**Comment by guybedford** [comment]
@juansaintclair the previous version of SystemJS used both `System` and `SystemJS` globals to avoid conflicts, which the current v2.0 no longer does as there are no active `System` global specs for the browser than I am aware of.

The fix would be `SystemJS = System` I think.

I'm open to realiasing the `SystemJS` global, but this needs to be undertaken as a serious deprecation path if done, and I'd need a really good reason to make that change all through the project.
