### ISSUE TITLE
Create bundle in nodejs

### ISSUE THREAD

**Issue by javadbat** [systemjs/systemjs#1881]
before systemjs2.0 released I use the jspm bundle to create a custom bundle for our app and bundle the following dependency in one file to reduce load time and transpile time in our production app.
```
    jspmVendorPackages: [
        "babel",
        "babel-runtime",
        "core-js",
        "css",
        "mobx",
        "mobx-react",
        "react",
        "react-dom",
    ],
```
in systemjs2, doc said its deprecated  and introduce rollup but don't explain how exactly we can do it .
can anyone publish a good Doc  in Medium aboute how we create bundle that registered by `System.registerDynamic ` in systemjs2.0?
and how we can transpile our individual non-bundle js file in node for production use . so that systemjs just load transpiled minified file when needed to speed up a load time in production ?

**Comment by guybedford** [comment]
See the Rollup code splitting documentation for workflows here.

Note that there is no pressure to upgrade to SystemJS 2.0, this isn't a straightforward upgrade path certainly.

**Comment by javadbat** [comment]
@guybedford SystemJS is great work and I can call it JS piece of Artwork but the lack of good site and documentation and some sponsorship, keeping it small and don't let it grow like webpack. I hope you can take care of this problem with your special talent  🥇 👍

**Comment by guybedford** [comment]
Thanks for the support @javadbat.
