### ISSUE TITLE
Features and extensions implementation in SystemJS 2.0 makes core less hackable itself

### ISSUE THREAD

**Issue by InvictusMB** [systemjs/systemjs#1882]
I had 2 issues while playing around with SystemJS 2.0:
1. Package name map state and implementation is hidden inside closure, is a singleton and `createPackageMap` is not exposed anywhere. So there is no way to customize or extend it's behavior without copy pasting the thing entirely.

2. I wanted to have a `system.js` + AMD setup and it worked. But `system.js` already contains `global` extra which executes before AMD detection. So `lodash` for example is resolved twice. First with global definition extra and then with AMD. I can't imagine any practical side effects of this but it is not very clean. 
I would expect globals detection to be the last fallback. But there is no way I can set it up myself. I cannot control how AMD plugin instantiates itself and I cannot run it before globals plugin that is bundled with  `system.js`. And I cannot just run `s.js` + AMD + globals because package name map is not available as a pluggable extra.

I want to build Stackblitz like experience with SystemJS 2.0. So I mainly need a run time representation of `package.json`'s dependencies section and a way to transform it into a package name map in a dynamic manner.
I've figured so far that just exposing `createPackageMap` utility and having a guarantee that the `json` instance I pass to it will be used as a source of truth for the resolver (as in current implementation) should be sufficient for my use case.

So my main question is: What is the preferred way to make extras/features further extensible? And more specifically: What is the preferred way to expose package name map things from SystemJS? Should I expose `createPackageMap` or should I expose the json object I pass to it on SystemJS instance?

And a less urgent question: Shouldn't the bundled extras/features be less invasive? I mean I want to have more control on when they are executed and which SystemJS instances they apply to. For example instead of amending the prototype on script load, plugin could add itself to `System.prototype.plugins` and then wait for `System.activatePlugin`/`activatePlugins` call on an instance.

**Comment by guybedford** [comment]
> Package name map state and implementation is hidden inside closure, is a singleton and createPackageMap is not exposed anywhere. So there is no way to customize or extend it's behavior without copy pasting the thing entirely.

This is the nature of fixed specifications. Hooking points aren't really supposed to exist. There is nothing wrong with copying this code verbatim into a custom resolver.

The only concern at that point is repeating code in the core, in which case building your loader on top of s.js may be a better approach as that is the base hookable loader.

> I wanted to have a system.js + AMD setup and it worked. But system.js already contains global extra which executes before AMD detection. So lodash for example is resolved twice. First with global definition extra and then with AMD. I can't imagine any practical side effects of this but it is not very clean.

The extras apply one after another, with the first one catching. For example a System.register will beat an AMD define will beat a global detection. So there shouldn't be any duplication here, it's just fallback detections. How is this affecting things for you?

> I want to build Stackblitz like experience with SystemJS 2.0. 

Stackblitz was originally built with SystemJS, always glad to contribute to sandbox development :P

> For example instead of amending the prototype on script load, plugin could add itself to System.prototype.plugins and then wait for System.activatePlugin/activatePlugins call on an instance.

A primary priority was to keep the footprint down, so having a more complex plugin system was avoided here. The only issues may arise if attempting multiple loaders in the page, but even then global load order can be manipulated to get things to work out as desired. The idea was that one would just concat the loader and extras together which effectively acts like a single unit of code.

Happy to help where you are having issues, but most of the above sound like architectural questions / curiosities over real pain points to me?

In terms of generating package maps, you are hitting a fundamental problem here with dynamic package maps which won't work on the web :)

In terms of supporting this in SystemJS though I'm open to the following:

1. Supporting multiple "system-packagemap" entries
2. Supporting dynamically injected <script type="system-packagemap"> by listening to the dom mutation event or similar.

This could be in core or even an extra if we can come up with a way to compose it with the base loader.

**Comment by sberney** [comment]
Or maybe, having a special build of SystemJS internals that you can import into your own project? Instead of copying and pasting the code you're interested in, maybe there is a way to export that code from systemjs as modules themselves? Does the `s.js` build not suffice then?

**Comment by abhishiv** [comment]
I would like to add that I also have a stackblitz kind of dev env built on 0.20. I was able to find a workaround to [#1860 Requesting a method to set Package Map from JavaScript](https://github.com/systemjs/systemjs/issues/1860)by having a custom build of system.js, and overloading `System.resolve`. 

1) However not having [#1854 CommonJS loading extra](https://github.com/systemjs/systemjs/issues/1854) means I'm unable to load most modules from cdn since they [often use](https://cdn.jsdelivr.net/npm/react@16.4.2/index.js) `module.exports`.

2) Also I think we need a way to set globals like `process`, `Buffer` etc.

**Comment by guybedford** [comment]
@abhishiv would you be interested in porting the CommonJS from 0.21 into SystemJS 2.0? If anyone would like to sponsor this work as well I'd certainly be open to that too, it shouldn't be a day of work I just don't have a reason to prioritise it myself currently.

Re process and Buffer globals, those could be handled in such a CommonJS extra as part of the wrapper.

**Comment by guybedford** [comment]
> It haven't affected me yet other than I was very confused when debugging the registrations. Yes, System.register and AMD defines catch but global definition falls through. I was expecting global detection to happen last and only in the case when the rest have failed.

@InvictusMB this is exactly as the behaviour is supposed to work. If you were seeing anything different here that sounds like a bug that would be great to know about.

Here are some action items from this issue thread, let me know if I'm missing anything:

* CommonJS extra (https://github.com/systemjs/systemjs/issues/1854)
* Separate library internals from loader?

**Comment by guybedford** [comment]
Closing this issue to track separate action items. If there is anything more to be added from this, please let me know. Expanding hooks, extras and conventions over time is a priority that is driven by user feedback, so don't hesitate to share thoughts.
