### ISSUE TITLE
AMD loader incompatible with webpack AMD output

### ISSUE THREAD

**Issue by JounQin** [systemjs/systemjs#1883]
```js
const content = {}
export default content
```

It will output something like following with webpack:
```js
// just for DEMO
define(function() {
  return {
    default: {},
    __esModule: true,
    [Symbol.toStringTag]: "Module"
  }
})
```

And then `SystemJS` AMD loader will wrap into an object with `default` key again:
```js
{
  default: {
    default: {},
    __esModule: true,
    [Symbol.toStringTag]: "Module"
  },
  [Symbol.toStringTag]: "Module"
}
```

So we have to call `System.import(mod).then(module => module.default.default)` to get the correct `content`.

Maybe #1848 related

**Comment by guybedford** [comment]
We could look at implementing the __esModule flag just for AMD. But if this were CommonJS this is actually correct behaviour!

**Comment by JounQin** [comment]
@guybedford `module.default` is correct behavior for CommonJS, not `module.default.default`.

**Comment by guybedford** [comment]
That is ‘right’ but not ‘correct’ :p
