### ISSUE TITLE
SystemJS 0.21: Instantiate watches the wrong key to determine if scriptLoad is possible or not

### ISSUE THREAD

**Issue by zenorbi** [systemjs/systemjs#1888]
SystemJS tries to load URL's with plugin key parts as simple script tags.

In these places:
https://github.com/systemjs/systemjs/blob/fe02b0ec628821ebd7ace2d0d96f701ed9dd153a/src/instantiate.js#L45
https://github.com/systemjs/systemjs/blob/fe02b0ec628821ebd7ace2d0d96f701ed9dd153a/src/instantiate.js#L50
SystemJS checks `metadata.load.pluginKey` to check if scriptLoad is possible as it isn't when using plugins. However the `pluginKey` is actually at `metadata.pluginKey` not under the `load` as can be seen here:

https://github.com/systemjs/systemjs/blob/fe02b0ec628821ebd7ace2d0d96f701ed9dd153a/src/resolve.js#L9
https://github.com/systemjs/systemjs/blob/fe02b0ec628821ebd7ace2d0d96f701ed9dd153a/src/resolve.js#L106

and many other lines in this file.

**Comment by guybedford** [comment]
@zenorbi thanks for sharing. Would you like to look into a fix here?
