### ISSUE TITLE
Can we use the Systemjs in react native

### ISSUE THREAD

**Issue by jaiminp21** [systemjs/systemjs#1889]
Hi Team,

Can we use the systemjs in react native application for loading component  from remote server ?

Thank you !

**Comment by guybedford** [comment]
I'd be glad to work on any changes necessary to ensure SystemJS can be supported in react native.

Did you try this? Is there anything we can address here?

**Comment by guybedford** [comment]
In theory all that is needed is `fetch` support, but if there is anything specific in the environment that is not working or that we can add I'd be glad to. We'd need more info from testers here first though. Closing in the mean time.
