### ISSUE TITLE
Babel, JSX, and import in browser?

### ISSUE THREAD

**Issue by spiderworm** [systemjs/systemjs#1890]
For the moment, I'm trying to get React, JSX, Babel, and native modules all working together seamlessly in the browser. I got babel standalone with react and client-side JSX transforms working pretty easily:

```
<script crossorigin src="https://unpkg.com/babel-standalone@6.26.0/babel.min.js"></script>
<script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
<script type="text/jsx" src="..."></script>
```

The only thing that doesn't work is import statements within my JSX files. Apparently I need to add SystemJS to the mix somehow to get imports working? What's the trick to getting this working?

**Comment by guybedford** [comment]
Easy workflows for doing this sort of thing are not currently a priority in SystemJS 2.0 (as they were in SystemJS 0.21 and before).

Perhaps have a look at this project instead - https://github.com/guybedford/es-module-shims.

**Comment by guybedford** [comment]
And note that the Babel plugin could certainly be improved to provide these easy workflows if someone is interested in working on that, it is just not a priority for me personally these days given es-module-shims provides that use case now.

**Comment by zerkotin** [comment]
I think this is a big mistake to leave it out as it provides many platforms the ability to work on react apps without node and without a bundler.
My self i use the iPad as development on the go, and i am using systems 0.2 to do that with react babel and jsx. All attempts to reach the same goal using the latest systemjs failed.

Systemjs 0.2 was the only good solution for doing that, and it would be wonderful if you could still support it, it is crucial for mobile environment.

Thank you.

**Comment by guybedford** [comment]
@zerkotin did you try the transform extra with Babel (https://github.com/systemjs/systemjs-transform-babel) here? These workflows haven't been heavily optimized as you are one of the first to demand this in the issue queue. You can make things better if you like!

**Comment by zerkotin** [comment]
```<!doctype` html>
<html>
  <head>
    <title>systemjs + react + jsx</title>
    
    <script src="https://unpkg.com/systemjs@3.1.6/dist/system.js"></script>
    <script src="https://unpkg.com/systemjs@3.1.6/dist/extras/transform.js"></script>
    <script src="https://unpkg.com/systemjs-transform-babel@0.1.2/dist/babel-transform.js"></script>
    
    
	<script type="systemjs-importmap">
	{
	  "imports": {
	    "react": "https://unpkg.com/react@16/umd/react.production.min.js",
	    "react-dom": "https://unpkg.com/react-dom@16/umd/react-dom.production.min.js",
	    "prop-types": "https://unpkg.com/prop-types@15.7.2/prop-types.min.js"
	  }
	}
	</script>
    <script>
      System.import('./main.js')
    </script>
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>
```

This is my setup and it does not work, maybe im doing something wrong i don’t know, I’ve been playing around with that for 2 weeks now and cant figure it out.

**Comment by guybedford** [comment]
@zerkotin it's not your fault - these workflows haven't been worked out before and require someone to develop them. They are simple to do, but I am personally not interested in their development so haven't worked on this. I'm happy to accept PRs or sponsorship for these types of things. And if I get the time I might try to provide a nice easy solution. But it's just very difficult to prioritize.

**Comment by guybedford** [comment]
Also there is nothing wrong with sticking to SystemJS 0.20 if that is working for you!

**Comment by zerkotin** [comment]
i would have done that, it sounds easy enough, but im not familiar with the code.
I just through that its always a good idea to keep sync with the latest version (for future proofing).
Also the latest version are far simpler to configure.

Perhaps a transform that injects all the imports as text/jsx (just an idea)

Anyway thank you for answering.
Also maybe you can point me in the right direction of where to look i might do it myself.

**Comment by stunaz** [comment]
maybe reopen!
