### ISSUE TITLE
Support import-maps fallback

### ISSUE THREAD

**Issue by isidrok** [systemjs/systemjs#1891]
Since the addition of fallbacks to the import-maps spec (https://github.com/domenic/import-maps#fallback-examples) I think support could be added here as well.

I can open a PR if the change seems interesting.

**Comment by guybedford** [comment]
Yes we should definitely implement the fallbacks.

There are still a few questions around the implementation there, so I would prefer to wait until it is clearer what it will look like, or at least for there to be a reference implementation / spec.

**Comment by guybedford** [comment]
Note that fallbacks aren't currently designed to support fetch failure fallbacks, and only standard module fallbacks in the browser. As such, this likely won't be on the roadmap for a while, or at least until that changes.

**Comment by guybedford** [comment]
Actually, one thing we could do here is support fallbacks where we simply ignore unknown URL protocols: `x: ["std:x", "https://..."]` will always fall through the unknown protocol.

Reopening this as a feature to be developed, and PRs are very welcome.

**Comment by isidrok** [comment]
So this would be somehow in preparation for the  early standard lib proposal, right?

Regarding the implementation:

- Unknown URL protocols would never be attempted to be fetched therefore resulting in no errors.

- Fetch error fallbacks would not be supported yet.

**Comment by guybedford** [comment]
Yes exactly, it wouldn't actually be useful at all for anything I guess, but would be a form we could support.

It wouldn't skip fetching unknown URL protocols, it would just fall-through those import maps fallbacks by default in the resolver.

**Comment by guybedford** [comment]
I'm going to close this actually, as currently no use cases for fallbacks in SystemJS have been discovered. If something comes up we can reopen.

**Comment by joeldenning** [comment]
Talking with a user of single-spa, they’re very interested in fallback URLs to handle the case where a CDN is unavailable.

See https://github.com/WICG/import-maps/blob/master/README.md#for-user-supplied-packages

I’m reopening

**Comment by guybedford** [comment]
Fallbacks have been removed from import maps. SystemJS should follow the specs so for now we can close this, but reopen if / when the picture changes again.
