### ISSUE TITLE
SystemJS 2.0 AMD "exports is not defined"

### ISSUE THREAD

**Issue by DrGonzo84** [systemjs/systemjs#1892]
I can try configure angular project with SystemJS 2.0 + Typescript.
Now, I admit my not totally understanding about module loader. However, this is my file:

**PACKAGE.JSON**
`{
  "name": "client",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "build": "tsc -w",
    "start": "live-server",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "^7.2.0",
    "@angular/compiler": "^7.2.0",
    "@angular/core": "^7.2.0",
    "@angular/platform-browser": "^7.2.0",
    "@angular/platform-browser-dynamic": "^7.2.0",
    "core-js": "^2.6.2",
    "rxjs": "^6.3.3",
    "systemjs": "^2.1.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "live-server": "^1.2.1",
    "typescript": "^3.2.2"
  },
  "description": ""
}`

**TSCONFIG.JSON**
`{ 
  "compilerOptions": { 
    "outDir": "dist", 
    "sourceMap": true,
    "declaration": true,
    "module": "amd",
    "moduleResolution": "node", 
    "experimentalDecorators": true, 
    "emitDecoratorMetadata": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [ 
      "dom",
      "es2017" 
    ] 
  } 
} `

**SystemJS-config.json**
`{
    "packages": {
        "@angular/core": "/node_modules/@angular/core/bundles/core.umd.js",
        "@angular/common": "/node_modules/@angular/common/bundles/common.umd.js",
        "@angular/common/http": "/node_modules/@angular/common/bundles/common-http.umd.js",
        "@angular/compiler": "/node_modules/@angular/compiler/bundles/compiler.umd.js",
        "@angular/platform-browser": "/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
        "@angular/platform-browser-dynamic": "/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
        "@angular/http": "/node_modules/@angular/http/bundles/http.umd.js",
        "@angular/router": "/node_modules/@angular/router/bundles/router.umd.js",
        "@angular/forms": "/node_modules/@angular/forms/bundles/forms.umd.js",
        "@angular/animations": "/node_modules/@angular/animations/bundles/animations.umd.min.js",
        "@angular/animations/browser": "/node_modules/@angular/animations/bundles/animations-browser.umd.js",
        "@angular/platform-browser/animations": "/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js",
        "angular-l10n": "/node_modules/angular-l10n/bundles/angular-l10n.umd.js",
        "angular-in-memory-web-api": "/node_modules/angular-in-memory-web-api/index.js",
        "tslib": "/node_modules/tslib/tslib.js",
        "rxjs": "/node_modules/rxjs/bundles/rxjs.umd.min.js",
        "rxjs/operators": "/node_modules/rxjs/operators/index.js",
        "ts-md5": "/node_modules/ts-md5/dist/md5.js",
        "primeng": "/node_modules/primeng/primeng.js"
    }
}`

**INDEX.HTML**

    <script type="systemjs-packagemap" src="SystemJS-config.json"></script>
    <script src="node_modules/systemjs/dist/system.js"></script>
    <script src="node_modules/systemjs/dist/extras/amd.js"></script>
    <script src="node_modules/systemjs/dist/extras/named-register.js"></script>
    <script> 
      System.import('./dist/main.js').catch(function (err) { 
          console.error(err); 
      });
    </script>

Now, to summarize. 

I added:
- SystemJS NPM
- Link in my index.html system.js and extra AMD
- Setup Typescript to compile in AMD module
- SystemJS mapping

Then launch:
- "npm build" = tsc -w
- "npm start" = live-server

**SHOW MY APP!!!!!**

Unfortunately this not working. On the start of application browser console show me this error:

> ReferenceError: exports is not defined

Why? What am I missing?

Thanks

**EDIT**
I investigated and i found some information about my problem. Error throw on loading of "rxjs/opreator". This is my package map of this module:

> "rxjs/operators": "/node_modules/rxjs/operators/index.js",

Problem is that there isn't relative UMD bundle of this module. How i can resolve this problem?

Thank you

**Comment by guybedford** [comment]
The packages configuration is specific to SystemJS 0.21. You can find that branch here - https://github.com/systemjs/systemjs/tree/0.21.
