### ISSUE TITLE
registerDynamic in 2.0/3.0

### ISSUE THREAD

**Issue by puopg** [systemjs/systemjs#1896]
registerDynamic seems to have been deprecated from 1.0. 

Is there an equivalent or has this functionality been integrated into the new format for System.register? 

I used this method to register dependencies like 'react' so as to hoist them across our monorepo. sorta like

```
function registerDep(name, requirer) {
  SystemJS.registerDynamic(name, [], false, function(_r, _e, _m) {
    _m.exports = requirer()
  })
}

registerDep('react', () => require('react'));
registerDep('react-16.6.0', () => require('react-16.6.0'));
registerDep('react-router-dom', () => require('react-router-dom'));
registerDep('react-dom', () => require('react-dom'));
```

Thanks for any support!

**Comment by guybedford** [comment]
I've created https://github.com/systemjs/systemjs/pull/1899.

**Comment by guybedford** [comment]
#1899 has been merged.

**Comment by joyfulelement** [comment]
hi @guybedford : 

Could you help elaborate the usage of new `System.set()` that is equivalent to the `SystemJS.registerDynamic()` example that @puopg had at the top? 

I have been looking for some migration guide about it, but couldn't find any. So any thought on this would be much appreciated!

**Comment by guybedford** [comment]
@joyfulelement if you have many CommonJS modules you are trying to support, I would suggest building them together with another tool like Webpack or Rollup as the alternative to registerDynamic.

**Comment by Fucks** [comment]
> @joyfulelement if you have many CommonJS modules you are trying to support, I would suggest building them together with another tool like Webpack or Rollup as the alternative to registerDynamic.

@guybedford do you have any example of this?
