### ISSUE TITLE
Unable to delete or overwrite a module that previously failed to instantiate (3.0)

### ISSUE THREAD

**Issue by mike-starr** [systemjs/systemjs#1902]
If `System.instantiate` rejects, the module is left in a state where calls to `System.delete` won't find or delete it, but `System.import` will still return it - making it impossible to reload.

**Comment by guybedford** [comment]
Thanks for posting, this is an important bug to fix. I'm looking into a test case and fix and will report back.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/cdd355152704e6507216ae1c84928e27b50d43af.

**Comment by guybedford** [comment]
Released in 3.0.1.
