### ISSUE TITLE
System.resolve API sometimes returns string, sometimes promise

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1909]
System.resolve sometimes returns a string, and sometimes a promise. Note that this is inconsistent with the documentation, which [says that it returns a promise](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemresolveid--parenturl---promisestring).

### Situations where it returns a string
- [basic resolve](https://github.com/systemjs/systemjs/blob/master/src/features/basic-resolve.js#L10) used in s.js
- [importmap resolve with inline importmap](https://github.com/systemjs/systemjs/blob/master/src/features/import-map.js#L48) used in system.js

### Situations where it returns a promise
- [importmap resolve with `<script type="systemjs-importmap" src="">`](https://github.com/systemjs/systemjs/blob/master/src/features/import-map.js#L43)

This is confusing as a user, especially when switching from inline import map to src="" import map. Would ideal behavior be to always return a Promise? Update the documentation to clarify when it returns a string or a promise?

**Comment by joeldenning** [comment]
I think that any change to the return value (such as always returning a Promise) would technically be a breaking change for anyone who's systemjs@3 code assumes that it returns a string instead of a promise.

**Comment by frehner** [comment]
As I was looking into possibly making a PR for SystemJS loading multiple import maps, I think it would be beneficial to standardize this as well. 

It would be confusing/difficult if a page had BOTH an `src` and inline import map and then trying to use this API.

**Comment by guybedford** [comment]
Always returning a Promise seems the way this needs to go, especially with the new import maps approach.

**Comment by DmitryBrus** [comment]
Documentation states that System.resolve returns string, but it is not aligned with this merge

https://github.com/systemjs/systemjs/blob/master/docs/api.md

Where I can open issue on documentation or might be I'm missing something?

**Comment by joeldenning** [comment]
| SystemJS Version | System.resolve() return value |
| ------------------ | ----------------------------- |
| system.js 5 | Promise |
| s.js 5 | string |
| system.js 6 | string |
| s.js 6 | string |

See related https://github.com/systemjs/systemjs/releases/tag/6.0.0. It sounds like you might be using an older version of systemjs. Try upgrading to systemjs@6?
