### ISSUE TITLE
Temporal dead zone violation in src/system-core.js

### ISSUE THREAD

**Issue by eemeli** [systemjs/systemjs#1910]
Specifically, this part: https://github.com/systemjs/systemjs/blob/836db7bca7416287d1a815f60b30dbf2d9d48d97/src/system-core.js#L18-L28

Line 18 exports `const` variables before they're declared on lines 22 & 28. This does not seem to cause an issue with Rollup and its transpiled output, but it's still incorrect. That should cause a `ReferenceError`, right?

**Comment by guybedford** [comment]
I've commented on the PR.
