### ISSUE TITLE
Module load error handling

### ISSUE THREAD

**Issue by hirokiosame** [systemjs/systemjs#1913]
Looking for a way to handle 404s on modules. If I could catch this in a transform hook or something, that would be great.

**Comment by guybedford** [comment]
Errors can be caught by the trace API `onload` hook - https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#onloadurl-error-sync.

**Comment by hirokiosame** [comment]
@guybedford 
Ah nice, thank you.

With the onload hook, how can I provide an alternative URL given a failed request?

**Comment by guybedford** [comment]
There is no way to provide a failure fallback, without manually modifying `System.import` with a custom extension.

**Comment by hirokiosame** [comment]
Thanks for explaining @guybedford 
Can I repurpose this ticket to be a feature request?

**Comment by guybedford** [comment]
@hirokiosame I would suggest trying the custom interception first - 

```js
const systemImport = System.import;
System.import = function (name) {
  return systemImport.call(this, name)
  .catch(async err => {
    const resolved = await System.resolve(name);
    System.delete(resolved);
    throw err;
  });
};
```

sort of thing...

As much as possible we should investigate workflows in userland, before considering core integrations.
