### ISSUE TITLE
Invalid script breaks SystemJS

### ISSUE THREAD

**Issue by fenderil** [systemjs/systemjs#1914]
Hi there.

I'm trying to load different scripts with SystemJS.import and amd extra. Some scripts can be too old and don't have AMD wrapper. If this script had been loaded, script puts his error to SystemJS registry and all next imports will get same error. Same issue for scripts with wrong syntax, or scripts simply include only `throw new Error('I'm broken script')`.

Using onload hook to catch error and delete broken module is useless. In this hook module is still not defined in system.

**Comment by guybedford** [comment]
Thanks for posting an issue. So this seems very much like the test case we have in https://github.com/systemjs/systemjs/blob/master/test/fixtures/browser/eval-err.js.

Could you share what the exact problem is with new imports here? That test runs before further `System.import` calls load other files just fine.

Note that if you are loading a module which loads any module which loads the errored module, then yes you will continue to get the error and there is no way to resolve that as errors cache in the module registry - this is just like the browser loader works.

It is possible to clear the cached error with `System.delete` though for SystemJS.

If it's something else though a detailed replication would help a lot.

**Comment by fenderil** [comment]
Thx for quick answer.

Here it is: https://github.com/fenderil/systemjs-issue

I have some separated js-flows (apps) in same page, which working with same system.js instance. Possibly, I had not understood error handling and I should use different system.js instances for different apps.

**Comment by guybedford** [comment]
Thanks so much for the replication here! Fixed in https://github.com/systemjs/systemjs/commit/56d515a2885ebce6b8ac8c46850706b98e5408a5 and published in 3.1.0.
