### ISSUE TITLE
Supporting late import maps

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1916]
We could include support to:

- [ ] Allow for import maps to be added to the DOM after SystemJS executes. See https://github.com/systemjs/systemjs/blob/52a38c11cbe98522c6813f353cf026af322843ba/src/features/import-map.js#L22
- [ ] Allow for import maps to be added to the DOM all the way until the first System.import. See [acquiring import maps boolean explanation](https://github.com/WICG/import-maps/blob/master/spec.md#when-import-maps-can-be-encountered).

This could be done by moving import maps processing to the `System.resolve` handler.

**Comment by guybedford** [comment]
I think allowing import maps after SystemJS executes would only really be a requirement if we want to land https://github.com/systemjs/systemjs/issues/1864 as that would ideally follow the same processing model as import maps and module scripts then.

But without having an actual `<script type="systemjs-module">` treating the cutoff as the SystemJS init script itself seems quite adequate to me.

**Comment by joeldenning** [comment]
Here are a couple reasons I want the feature, all of which are unrelated to `<script type="systemjs-module">`:

1) Spec compliance. https://github.com/WICG/import-maps/blob/master/spec.md#when-import-maps-can-be-encountered
2) The following code doesn't work, and the reason why is not clear at all to the user.
```html
<html>
  <head>
    <script src="https://unpkg.com/systemjs"></script>
    <script type="systemjs-importmap">
      {
        "imports": {
          "lodash": "https://unppkg.com/lodash"
        }
      }
    </script>
    <script>
       System.import('lodash')
    </script>
  </head>
</html>
```
3) Dynamic, inline import maps often get injected after initial load/parse, but systemjs gets loaded as part of initial load/parse. I'm talking about situations where client-side javascript creates a dynamic import, and it may not always be able to do so synchronously

**Comment by joeldenning** [comment]
Here's a proposed implementation (not working or fleshed out or anything yet):

```js
let acquiringImportMaps = true, importMapPromise

if (typeof document !== 'undefined') {
  document.querySelectorAll('script[type="systemjs-importmap"][src]').forEach(function (script) {
    script._fetchPromise = fetch(script.src);
  });
}

function retrieveImportMaps() {
  const scripts = document.querySelectorAll('script[type="systemjs-importmap"]')
  for (let i=0; i<scripts.length; i++) {
    const script = scripts[i];
    if (script.src && script._fetchPromise) {
      // use _fetchPromise
      importMapPromise = importMapPromise.then(() => {
        ...
        delete script._fetchPromise;
      });
    } else if (script.src) {
      // fetch
    } else {
      // parse inline map
    }
  }
}

systemPrototype.resolve = function(id) {
  if (acquiringImportMaps) {
    retrieveImportMaps()
    acquiringImportMaps = false;
  }

  return importMapPromise.then(map => ...)
}
```

**Comment by guybedford** [comment]
Right, so you still want the import maps to be processed as of the first `System.resolve` call instead of any earlier. I can see the reasoning for that.

**Comment by joeldenning** [comment]
Yeah exactly — not sure if there are situations where System.resolve is called where we don’t want to set acquiringImportMaps to be false, but I think that it would be a pretty easy implementation to just do it in System.resolve

**Comment by guybedford** [comment]
I've renamed this issue to reflect the above.

**Comment by viT-1** [comment]
Why unpkg and not other cdns (for example jdelivr)?

**Comment by joeldenning** [comment]
> Why unpkg and not other cdns (for example jdelivr)?

There is no reason. You're referring to example code in an issue. You can use jsdelivr or any other cdn of your choice. Doesn't matter which one.
