### ISSUE TITLE
Chaining cycle in promise with async execute

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#1921]
I'm using systemjs to have top level await in the browser.
However there is a `promise cannot resolve with itself` error, you can reproduce with a simple fiddle like this one: https://jsfiddle.net/9odyajcw/.

Is there a way to make it work ?

**Comment by dmail** [comment]
When you're inside the fiddle, open the browser console to see logs.
You should see 42 being logged and after that an error about promise cycle.

**Comment by guybedford** [comment]
Thanks for the report! Will aim to take a look soon at the case and fix.

**Comment by guybedford** [comment]
So this was a bug specifically with s.js, not found in system.js. I've fixed this up in https://github.com/systemjs/systemjs/commit/cc44badb9545182b1d121dd5c06f50ccd3079e23 - thanks so much for the clear replication.

**Comment by dmail** [comment]
Amazing thank you very much for the fast response and fix. That will help me to finish my project relying on your work on systemjs.

**Comment by guybedford** [comment]
Released in 3.1.1.

**Comment by guybedford** [comment]
Glad to help.
