### ISSUE TITLE
Importing a module manually placed into the registry with `System.set` fails unless the module is also specified in the import map

### ISSUE THREAD

**Issue by TheMcMurder** [systemjs/systemjs#1927]
I recreated the issue here: https://gitlab.com/TheMcMurder/systemjs-3 (Note this doesn't render anything it just logs to the console)

This issue could be a misunderstanding on how I'm supposed to interact with SystemJS.

I'm migrating a project that used `registerDynamic` so I've switched to start using `System.set` and it works great to put items in the registry but when I try to get those items using `System.import` it always fails.

I have a WIP solution to the problem that I've been experimenting with and I'll PR that after submitting this issue.

```html
<script type="systemjs-importmap">
    {
      "imports": {
        "mod1": "/mod1.js",
      }
    }
 </script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/system.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/amd.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/named-exports.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/named-register.js'></script>
  <script>
    // This is where I'm manually setting something into the registry
    System.set('test', {thing: 'thing'})
    System.import('/index.js')
  </script>
```

```js
// index.js
System.import('test').then(test => console.log('from test', test.thing))
```

As far as I can tell because `test` isn't in the import map it's failing here: https://github.com/systemjs/systemjs/blob/master/src/common.js#L171 and never being resolved.

Is this behavior expected? Am I breaking the patterns of interaction with SystemJS or is this an actual bug where Import doesn't support items that have been `set` into the registry?

My solution to fix this problem is on import check if something is already in the registry via `System.has` then if nothing is defined continue on the old path otherwise resolve with the id. See

**Comment by guybedford** [comment]
Currently SystemJS is defined to always resolve all specifiers to full URLs in the resolve operation.

The registry is only checked after applying the resolve operation.

So if you want to support names like this, you would need to hook the resolver as well to support them manually:

```js
const systemResolve = System.resolve;
System.resolve = function (name, parent) {
  if (name === 'test') return name;
  return systemResolve.call(this, name, parent);
};
```

SystemJS previously always would check the registry twice - once before resolution and once after resolution, just like your PR provides. But I am hesitant to implement this again now that URLs are the standard registry key. Rather I think a custom resolver hook can support this if needed.

Note the other alternative is just to make sure you always define URLs:

```js
System.set(new URL('test', base).href, { thing: 'thing' });
```

**Comment by TheMcMurder** [comment]
I'm closing this issue based on the updates above.

The two solutions proposed both work without changes to SystemJS. Thank you.

Same example working with using a URL as the key.
```html
<script type="systemjs-importmap">
    {
      "imports": {
        "mod1": "/mod1.js",
      }
    }
 </script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/system.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/amd.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/named-exports.js'></script>
  <script src='https://unpkg.com/systemjs@3.1.1/dist/extras/named-register.js'></script>
  <script>
    const url = new URL('test', window.location.origin)
    System.set(url, { thing: 'thing' });

    System.import('/index.js')
  </script>
```

```js
// index.js
SystemJS.import(`${window.location.origin}/test`).then(test => console.log('from test', test.thing))
```
