### ISSUE TITLE
Script error in IE 11

### ISSUE THREAD

**Issue by soulwu** [systemjs/systemjs#1931]
https://github.com/systemjs/systemjs/blob/63c5a289465aeeaecdc6b121bcd5feea4b37ad23/dist/system.js#L778

This line use `Object Property Value Shorthand` which not support in IE11

**Comment by guybedford** [comment]
Thanks so much, I've included the fix in https://github.com/systemjs/systemjs/commit/551b2e8ec7bda18ba6454a6e30f83fe8d04ebaaf.

**Comment by guybedford** [comment]
Released in 3.1.3.

**Comment by joeldenning** [comment]
See related https://github.com/systemjs/systemjs/issues/1935
