### ISSUE TITLE
__useDefault interop patterns

### ISSUE THREAD

**Issue by frehner** [systemjs/systemjs#1933]
When I have an AMD bundle that tries to import a System.register named export, the AMD bundle gets the error
```
Uncaught (in promise) TypeError: Cannot read property 'thisIsFalse' of undefined
    at Object.<anonymous> (app-1.js:3)
    at Object.execute (amd.js:56)
    at Object.declaration.execute (named-exports.js:38)
    at doExec (system.js:433)
    at postOrderExec (system.js:429)
    at system.js:380
```

However, I have found that the following works: 

1. AMD importing from AMD
1. System importing from System
1. System importing from AMD

So it appears to only affect AMD importing from System.

Here is a small reproduction repo to see the error: https://github.com/frehner/systemjs-amd-register-bug

Here's a screenshot of the error, along with a `System.import` to show that it looks ok when not being using in the AMD bundle. <img width="595" alt="Screen Shot 2019-04-17 at 6 37 52 PM" src="https://user-images.githubusercontent.com/3054066/56329613-8db92380-6141-11e9-9f08-0cc20a534cb5.png">

**Comment by joeldenning** [comment]
This line of code appears to be the problem, from what I can tell. https://github.com/systemjs/systemjs/blob/master/src/extras/amd.js#L42.

My perspective is that this is a bug in SystemJS -- I think AMD modules should be able to fully interoperate with System.register modules. And that `depModules[idx] = ns.default;` should be replaced with just `depModules[idx] = ns;`

Changing how AMD modules are fed dependencies could potentially break things. But I believe that assuming that AMD modules always want the default export is just as arbitrary of an assumption as saying that they don't. And that at least the latter allows the AMD module to have **all** of the module and do whatever interop with it that they can.

For AMD modules created by rollup, they appear do not do any special interop with the injected dependencies. But I know that webpack AMD modules do special interop where they check an injected dependency for an `__esModule` property and then handle named and default exports accordingly. If we want AMD modules created  by those two bundlers to interoperate with System.register modules, I think we should  get rid of the `ns.default` and also add in a `__esModule` property to all SystemJS modules.

**Comment by frehner** [comment]
Joel helped walk me through his thoughts, and for what it's worth, changing that line did make my example repo code work :)

**Comment by guybedford** [comment]
So the driving motivation here was that `default` can be any value, while the full ES module can only ever be an object.

So say you have an AMD module, that expects a function value for one of its dependencies - then that dependency cannot be represented as an ES module ever.

The mindset in the above is kind of based on having an unchanged AMD dependency where one of its dependencies in turn is upgraded to an ES module.

Does the above capture your use case as well here? Understanding the use case / scenario would help a lot to know what we can do here.

I am also hesitant to implement __esModule here, despite being the original creator of that proposal :P

**Comment by guybedford** [comment]
Also worth noting here that CommonJS modules are only represented as a `default` export to ES modules in the Node.js --experimental-modules implementation.

**Comment by frehner** [comment]
>Does the above capture your use case as well here? Understanding the use case / scenario would help a lot to know what we can do here.

To be honest, I'm not sure I fully understand what you're saying :D 
Sorry.

My use case is that I have SystemJS loading a variety of modules; some are AMD format (because webpack at the time didn't have system format support, and these modules are older), and some are System format (because these modules are newer and were built with Rollup). 

This issue is preventing me from importing values in my older AMD modules from my newer System modules -- in other words, if I want to be able to use my newer modules with my older modules, I currently have to make _everything_ AMD format otherwise some imports just flat out break as shown above.

Hopefully that helps explain my use case?

**Comment by frehner** [comment]
To be clear, now that webpack now supports system format I don't really have an issue with upgrading all my modules to be system format. But I did want to at least report this issue

**Comment by guybedford** [comment]
Thanks for the update. One thing that might help to know - are the ES modules libraries you are loading? Or your own modules?

**Comment by frehner** [comment]
Good point -- the modules I build could be upgraded, but external modules that I don't control (e.g. React) would still have to be AMD until a time that they consider releasing a system format bundle.

So upgrading all my modules to System wouldn't work.

**Comment by guybedford** [comment]
Ok I see, that makes sense. It does seem it's either __esModule or nothing here (default -> breaks your case, all exports -> breaks eg an AMD dependency depending on another AMD dependency). I'm very hesitant to implement __esModule in this project though as I say.

Marking this issue as __esModule interop, and will see how further feedback goes on this topic.

**Comment by guybedford** [comment]
The logic I used to use here was to have a `__defaultOnly` flag only set by the AMD / global layer itself. This would act as a kind of reverse interop case as __esModule and worked well.

Perhaps we could bring this back rather.

**Comment by joeldenning** [comment]
Could you explain what you mean by the `__defaultOnly` flag wet on the AMD layer? Would this be something like this?

```js
System.__defaultOnly = true?
```

Or something set on a per-amd module basis somehow, via `define()`?

Also I'm curious why you're hesitant to reintroduce __esModule.

**Comment by guybedford** [comment]
@joeldenning `__defaultOnly` gets set on the ES module namespace itself when that namespace corresponds to a module that was executed via AMD / global etc. Instead of AMD always doing `ns.default` it would then do `ns.__useDefault ? ns.default : ns`. In this way AMD - AMD compatibility is maintained, while ensuring the correct ESM -> AMD, and AMD -> ESM interop.

**Comment by joeldenning** [comment]
Let me see if I'm understanding correctly -- the AMD module itself would export a field called `__useDefault` whenever it wanted only the default value?

```js
define('a', function() {
  return {
    __useDefault: true,
    default: function doSomething() {},
  }
})

define(['a', function(deps) {
  const a = deps[0]
  // a is the doSomething function, since it specified __useDefault
  a()
})
```

^^ This would make sense to me and would solve the problem described in the issue rather well. Would technically be a breaking change though for people depending on the current behavior of always returning the default for AMD modules.

```

**Comment by guybedford** [comment]
@joeldenning I was thinking more having this "automatically" in the AMD layer itself, where it sets `__useDefault` on all AMD module namespaces when they are created, and then checks it on all dependencies.

**Comment by guybedford** [comment]
Yes, it's a breaking change because it changes the way ES modules are interpreted by default in AMD. We would bump the major for this.

**Comment by joeldenning** [comment]
Ah I see, so the code changes would only be in `amd.js`, and the user of SystemJS wouldn't have to know that it was happening, since the amd extra is doing all the work for them. I like it.

**Comment by guybedford** [comment]
Ok I've gone ahead and implemented this in https://github.com/systemjs/systemjs/pull/1941.

Since it is in theory a breaking major release I won't rush the merge :)

**Comment by guybedford** [comment]
(and quick - if you can think of any other major changes to add now's our chance...)

**Comment by joeldenning** [comment]
I can't think of any changes to add to a major version. Any plans to release #1941?
