### ISSUE TITLE
Document web worker workflows

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1934]
Currently only SystemJS supports web workers. Perhaps we should just include this in s.js as well.

Then we should document how to build workflows around this.

**Comment by pigcan** [comment]
Any news?

**Comment by guybedford** [comment]
I haven't worked further on these workflows, but would gladly if people are interested.

**Comment by guybedford** [comment]
Rather than documenting what we have, I think we should continue to work to improve these use cases. Tracking in https://github.com/systemjs/systemjs/issues/2256.
