### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by kouts** [systemjs/systemjs#1935]
This line here https://github.com/systemjs/systemjs/blob/0ec9da6b46d38da3813357124202b4c43da729d6/dist/system.js#L788 breaks compatibility with IE11.
I think Symbol.iterator is[ not supported at all in IE11](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator#Browser_compatibility).

**Comment by joeldenning** [comment]
Could you share a stacktrace? The [check here](https://github.com/systemjs/systemjs/blob/0ec9da6b46d38da3813357124202b4c43da729d6/dist/system.js#L772) is intended to prevent any errors from occurring in IE11 -- the intended behavior is that in IE11 the iterator just wouldn't be defined.

**Comment by joeldenning** [comment]
Oh wait, maybe it's the [computed property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Syntax) that's breaking IE11, not the Symbol.

**Comment by kouts** [comment]
Ahh yes it's an ES6 feature.
