### ISSUE TITLE
Can we still use SystemJS with JSPM? (Using latest version for both)

### ISSUE THREAD

**Issue by thatguyjono94** [systemjs/systemjs#1938]
Hi guys, I'm just really confused at the moment as about 7 months ago I used SystemJS with JSPM 0.17 to run my (ReactJS + JSX + ES6) code locally without the bundling step. It seems now with the new versions for both SystemJS and JSPM, the documentation looks mutually exclusive.

It is still possible to use AMD module, import url mappings, and also babel transformers (that have support for JSX). Basically the ability to run modern React builds without the bundling step (for local env only).

Without the `SystemJS.Config` I don't see how we can define imports and specify which babel transformers we should be using etc.

Thanks

**Comment by guybedford** [comment]
@thatguyjono94 the Babel workflows for SystemJS 2.0 are still available, but yes we don't yet have a full story on the configuration mechanism. As mentioned in the SystemJS 2.0 release post, the features that get prioritized are the ones users ask for, so thanks for posting the issue.

The issue for the Babel configuration is tracking in https://github.com/systemjs/systemjs-transform-babel/issues/2. Let's move that discussion there, and I'd be glad to discuss further and implement some approaches.

As for the jspm 2.0 integration - yes SystemJS transforms are no longer supported in jspm. The reason for this is that the previous browser loader supported transforms, but the new browser ES module loader does not support transforms. So instead the jspm workflows recommend separate Babel compilation approaches, as discussed here - https://jspm.org/docs/integrations#babel.

The nice think about precompilation approaches is their incremental caching benefits as well - it is more similar to the C++ -> Object file -> linking type builds as opposed to the current monolithic JS builds we do which are terribly slow and suffer from caching issues.

**Comment by thatguyjono94** [comment]
@guybedford thanks for your response.

I agree with the approach, but I had a feature built (like JSFiddle) where users can effectively use a code sandbox. It has ES6 import statements from either third party packages or local user generated JS files. I am right in saying that SystemJS/JSPM is moving away from this direction (exclude the bundling step)?

I'm not fully across the different module standards, and am a little confused at the moment, but would like to do some research and contribute to SystemJS.

Could you point me in the right direction? Thanks

**Comment by guybedford** [comment]
I see. Yes SystemJS will continue to support these sandbox use cases, but jspm won't. Happy to discuss the configuration approach and work on something in the linked discussion on the transform repo. These workflows just won't transfer seamlessly into jspm workflows like SystemJS did previously, which shouldn't be a problem for sandbox cases, right?

As for the module standards, I'd love to know how these can be communicated better in the SystemJS and jspm documentation. What topics would you like to see explained better?

**Comment by thatguyjono94** [comment]
@guybedford I think the biggest difference for the code sandbox cases is that I had the JSPM registry to pull packages from. SystemJS does have import mappings, but just the ease of pulling a JSPM package and mapping it to a ES6 import. I could virtually run any build I wanted, like proper Vue/React builds using babel presets (even had support for typescript). It was like magic having such a thing working without any form of back-end compiling. 

And in regards to the documentation, I think just a section on why the shift. As previous users of the package like myself may be interested in mutual exclusiveness of the two packages considering they both went together.

**Comment by guybedford** [comment]
> I had the jspm registry to pull packages from

Am I understanding correctly that you mean the registry doesn’t work the
same for you under jspm 2.0? What about the jspm.io / jspm 2.0
jspm_packages workflow do you find incompatible with this? They are very
much designed for this. See the sandbox on the site.

> I could run virtually any build I wanted, like proper Vue/React builds
using Babel presets

Again what about the current setup explicitly restricts this? This should
all still be supported with System.transform and we can refine these
workflows in the Babel loader issue. It just seems like polish mainly
needed to me? Or is there more?

The shift is that the project, as it always has done, aims to align with
the native module future in browsers. The browser loader used to have a
translate hook, now it doesn’t. So publishing packages that utilize
translate is no longer a goal. And for performance makes sense too -
packages should be optimized for publish. That gets us to the native module
CDN suitable ecosystem that will fit the decentralized web so well.

**Comment by thatguyjono94** [comment]
@guybedford I think I may have confused myself. If I understand correctly, the same on the fly transpiling can be achieved with JSPM 2.0. 

Previously, this was my process:

1) Include system.js library 
2) use `System.JS.config` to map urls/npm packages
3) use `System.import` to include index.js file.

Looking at the jspm.io examples, I could run local react/jsx builds like I did in my previous workflow.

And from my understanding, SystemJS is for backwards compatibility with the latest ES Module.

As a side note I did try the SystemJS example on the main page:

`<script src="system.js"></script>
<script type="systemjs-importmap">
{
  "imports": {
    "lodash": "https://unpkg.com/lodash@4.17.10/lodash.js"
  }
}
</script>

<script>
  System.import('/js/main.js');
</script>`

main.js

`import _ from 'lodash';

console.log(_);`

And I get undefined in my browser, have I missed a step to get this working?

**Comment by thatguyjono94** [comment]
Have I missed a step above? Just not sure if I'm using the library correctly. I would find an example useful @guybedford .

**Comment by thatguyjono94** [comment]
Will be closing this issue as I don't think it's relevant.

**Comment by guybedford** [comment]
@thatguyjono94 if there's anything I can clarify further to do with these workflows just let me know.

**Comment by guybedford** [comment]
You could even try something like - 

```html
<script src="system.js"></script>
<script type="systemjs-importmap">
{
  "imports": {
    "lodash": "https://system-dev.jspm.io/npm:lodash@4.17.10/lodash.js"
  }
}
</script>
<script>
  System.import('/js/main.js');
</script>
```
