### ISSUE TITLE
Load css modules without exclamation mark in the name

### ISSUE THREAD

**Issue by wclr** [systemjs/systemjs#194]
Is it possible to make systemjs load css files using css plugin if css moudules come without exclamation mark in the end? This is a special use case where it is impossible to put exclamation mark in the end of css module name.

``` javascript
require([...., 'styles/styles.css'], ...) 
```

can not have:

``` javascript
require([...., 'styles/styles.css!'], ...) 
```

(because files are also used with another loader that does not support !):

Maybe override some internal loader function to add exclamation mark for css names prior import or some other way.

**Comment by victorwpbastos** [comment]
:+1:

**Comment by timbur** [comment]
I must be an idiot because I can never get this to work reliably, even when following [the docs](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use) exactly.

**Comment by timbur** [comment]
My problem seems to be relying on `jspm-cli` too heavily, I guess.  It ends up being easier to just manually update `package.json` and `config.js`.
