### ISSUE TITLE
document how to import babel-transform

### ISSUE THREAD

**Issue by javadbat** [systemjs/systemjs#1943]
in the jspm2 doc, we see script tag that used to import babel-transform but u don't explain how to install and implement and integrate it to load react and another es module.
for example, one step is to run:
`npm i systemjs-transform-babel`
to add transform library to systemjs folder

**Comment by guybedford** [comment]
The babel-transform isn't mentioned in the jspm 2 documentation. Seamless jspm 2 workflows with SystemJS don't currently exist, rather these are designed for es-module-shims only, with SystemJS as a build target.

I'm happy to discuss approaches here further though - and enabling the easy Babel transform could be a possibility, I guess I just haven't seen a need for this myself so haven't focused on it.

**Comment by javadbat** [comment]
the first need is for running a react app on the fly so we could have lazy load and other stuff. the life cycle of jspm 0.16 and systemjs1 was good but too many deprecated libraries and change of Babel ecosystem is its weak point. another weak of systemjs 1 is no dynamic import support. your vision for jspm 2 is about the future that we stop using current frameworks and use a native and pure rich feature of js and  HTML but we are really far from that future and we need reach or any other Bible transform as we had before.

**Comment by guybedford** [comment]
What Babel transforms are you after for CRA workflows? JSX?

The unbuilt workflow is just for development, so Babel env etc should all be applied for production processing.

We could certainly look at getting some easy workflows going around eg JSX loading though.

**Comment by javadbat** [comment]
my use case is unbuilt for development and separate build per page and component for production use and import every page and component on demand. I even build a custom router for that  case that load every page with system js on user demand. 
![ss (1)](https://user-images.githubusercontent.com/11534875/58004554-b9d91300-7af8-11e9-9282-ad53be271524.PNG)
![ss (2)](https://user-images.githubusercontent.com/11534875/58004566-c2c9e480-7af8-11e9-92b6-a9af43e0de87.PNG)

as you can see in the above picture I have a react component for product page and I load it with [ jb-router ](https://github.com/javadbat/jb-router) when user clicks on the product page link.
![image](https://user-images.githubusercontent.com/11534875/58004882-85b22200-7af9-11e9-9c0d-18b6511ac682.png)
and config the router like above picture

**Comment by javadbat** [comment]
I don't create a bundle for my whole app and I just bundle react and mobx and every single page of my app download and fetched from a different js file.
that's why systemjs is a very useful tool for me and let me control my own application and using babel with just simple config in systemjs like below:
![image](https://user-images.githubusercontent.com/11534875/58005345-b3e43180-7afa-11e9-9485-6f111d557e93.png)

**Comment by javadbat** [comment]
if you think this system is stupid and systemjs 2.0.0 has a different way to do the job. I have to remove system js and work with a rollup and watch all my file for change and transpile them on change. then use ES10 browser import function. that makes me do the lots of work to define watches and files and change all imports but worth because I don't want to let webpack control my application.

**Comment by guybedford** [comment]
It seems like you are using decorators and JSX mainly that would need to be supported here.

In some places I couldn't see that you were using exact file extensions, which may require changing your code to work, but apart from that everything seems like it could be fine with this workflow to me.

A simple Babel transform in the browser to support these two features could give you a the SystemJS 1 style workflow you are after, yes.

To work out what you'd need further here - 

* Are all files in your app ES modules? Or do you also load CJS / AMD / global modules?
* Are you using this workflow just for development (modern browsers), or did you want this workflow to work on older browsers as well?

**Comment by javadbat** [comment]
1- all my project module is an ES module but some external module from npm is CJS like react
2- I use this workflow for both productions  and development but I have publish script that could transfer them to more compatible format for production use
this is my code :
![image](https://user-images.githubusercontent.com/11534875/58076259-fec77d00-7bbe-11e9-9da1-3e50e66f63c4.png)


and the bable option:
![image](https://user-images.githubusercontent.com/11534875/58076155-c4f67680-7bbe-11e9-8542-d9343a1cf5dc.png)

**Comment by javadbat** [comment]
the best scenario is I can add babel hook  to systemjs like below:
`System.Hooks.push((filesrc)=>{babelTransform(filesrc,babelOptions).then((transpiledCode)=>{resolve(transpiledCode)})})`

**Comment by javadbat** [comment]
@guybedford  any news for this issue?

**Comment by javadbat** [comment]
@guybedford
