### ISSUE TITLE
Am I bound to System.register?

### ISSUE THREAD

**Issue by Univream** [systemjs/systemjs#1947]
The [docs](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md):

> System.register can be considered as a new module format designed to support the exact semantics of ES6 modules within ES5.

So using ES6 syntax like `export` / `import` would also be possible to register an export or import of a dependency.

**Comment by guybedford** [comment]
SystemJS supports `System.register`, AMD modules and global modules.

To use native ES modules, you need to use browsers that directly support the syntax.
