### ISSUE TITLE
Support JSON files as valid ESM modules.

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1949]
As of https://github.com/whatwg/html/pull/4407, JSON files are valid ESM modules that can be loaded via `import json from './file.json'` and `import('./file.json').then(m => console.log(m.default))`

It would be awesome if SystemJS supported JSON modules. Regarding implementation, the tricky part will be knowing whether to script tag the module or XHR + JSON.parse it. I propose that we use a not-quite-spec-compliant simplification in SystemJS, which is to check if the normalized module url ends with `.json`. So urls that don't end in `.json` would get the normal `<script>` tag treatment, whereas urls that do end in `.json` would be XHR + JSON.parse()'ed.

@guybedford what are your thoughts?

**Comment by guybedford** [comment]
The approach implemented there seems ideal to me.
