### ISSUE TITLE
SystemJS with Node-style path resolution

### ISSUE THREAD

**Issue by briandipalma** [systemjs/systemjs#195]
Hi,

I'm playing around with using unbuilt ES6 modules instead of ES6 modules compiled to CJS in node.
This is fine as long as you are working within one package but once you start using ES6 packages from other ES6 packages it gets a bit more painful. I know I've asked these sort of questions before and the answer was JSPM. The issue is that I'm now working on a server side/CLI tool and I'd prefer to stick to `npm` in that realm.

I agree that JSPM would make sense on the client as it deals with all the module wiring configuration for you and there is no other good solution available. In node land though `npm` and node's resolution algorithm is perfectly adequate.

[This is the package I wish to import](https://github.com/briandipalma/global-compiler) there are a few ES6 modules in `src` which are exported by `index.js` in the root. Testing is fine with `SystemJS` as it's all local and simple so I don't need to configure `SystemJS`. So the tests are able [find all the CJS modules required by the ES6 module](https://github.com/briandipalma/global-compiler/blob/master/src/flatten.js).

The problem arises when I import this package from another package and I need to configure `SystemJS`,

```javascript
System.config({
	map: {
		'global-compiler': 'node_modules/global-compiler/index'
	}
});
```

This means I then need to configure all the CJS packages that `globaal-compiler` requires eventhough I didn't need to do that before. In essence one you load a package with `SystemJS` it takes over all loading of that package's dependencies eventhough node could do that job just fine.

Would it make sense to add some configuration option to only load ES6 packages with `SystemJS` for node server side use?

**Comment by matthewp** [comment]
There is https://github.com/bitovi/system-npm which implement's the Node algorithm for anyone needing this feature.

**Comment by guybedford** [comment]
Closing as it's really not a SystemJS concern.
