### ISSUE TITLE
Is there anyway to install systemjs by npm and setup by webpack

### ISSUE THREAD

**Issue by tomzaku** [systemjs/systemjs#1952]
React + SystemJs
===
After install it by
```
npm install systemjs
```

My webpack config
```
const webpackAppConfig = {
  entry: {
    common: './src/common-deps.js',
  },
  output: {
    filename: appConfig.outputFiles.js,
    path: appConfig.rootBuildPath,
  },
  node: {
    fs: 'empty',
  },
  resolve: {
    modules: [
      __dirname,
      'node_modules',
    ],
  },
  module: {
    rules: [
      {
        exclude,
        include,
        test: /\.(js|jsx|mjs)$/,
        // use: ['babel-loader', 'source-map-loader'],
        use: [
          {
            loader: 'babel-loader',
          }
        ]
      }
    ]
  },
  devServer: {
    port: appConfig.port,
  },
  module: {
    rules: [
      {parser: {System: false}},
    ]
  }
}
```
src/common-deps.js
```
const systemJs = require('systemjs')
systemJs

window.SystemJS = window.System
if (SystemJS._nodeRequire) {
  // Fixes https://github.com/systemjs/systemjs/issues/1817
  // SystemJS basically will try to detect if it should use NodeJS's built-in
  // require to load things if it can, but because Webpack (sometimes, depending
  // on the settings/target I think?) defines `require`, SystemJS can get
  // confused. When it gets confused, it tries to use Webpack's require (which
  // then complains since the things we're trying to load dynamically weren't
  // loaded by Webpack). This is our hack to un-confuse SystemJS.
  console.warn("Monkey-patchings SystemJS._nodeRequire to undefined.");
  SystemJS._nodeRequire = undefined;
}

```

After that I import this file to index.html.

index.html
```
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width" />
	<title></title>
	<script src="https://cdn.polyfill.io/v2/polyfill.min.js"></script>
</head>

<body>

	<script type="systemjs-importmap">
		 {
        "imports": {
					react: 'https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.production.min.js',
					'react-dom': 'https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js',
					'react-dom/server': 'https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom-server.browser.production.min.js',
					'single-spa': 'https://unpkg.com/single-spa@4.3.2/lib/umd/single-spa.min.js',
					lodash: 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js',
					rxjs: 'https://unpkg.com/rxjs@6.4.0/bundles/rxjs.umd.min.js',
        }
      }
	</script>
	<script src="./common/common.js"></script>

	<script src="./main.js"></script>

	<!-- Static navbar -->
	<link rel="stylesheet" href="./style.css">

	<div class="navbar">
		<ul>
			<a href="#/app1">
				<li>
					#app1
				</li>
			</a>
			<a href="#/appTs">
				<li>
					#appTs
				</li>
			</a>
		</ul>
	</div>
</body>

</html>

```

Did I doing wrong way. Cuz it will throw this problem

```
Uncaught SyntaxError: Unexpected token <
    at eval (<anonymous>)
    at evaluate (evaluate.js?f634:106)
    at eval (instantiate.js?60f9:359)
    at doEvaluateDynamic (register-loader.js?344b:685)
    at eval (register-loader.js?344b:545)
    at doEvaluateDynamic (register-loader.js?344b:682)
    at ensureEvaluate (register-loader.js?344b:520)
    at eval (register-loader.js?344b:139)
    at ZoneDelegate.invoke (zone.js?91f6:388)
    at Zone.run (zone.js?91f6:138)
```
![image](https://user-images.githubusercontent.com/19413272/59153894-88b48880-8a8f-11e9-9bca-999f396c16f2.png)

**Comment by joeldenning** [comment]
To make sure I understand your question, you're asking if you can embed systemjs into a webpack bundle instead of loading it from CDN?

Yes, you can. Your code looks fine, I don't see any obvious problems. The ZoneJS stuff is irrelevant to the error -- only reason it's in the stacktrace is because ZoneJS monkey patches literally every global javascript feature it can get its hands on. But it wasn't the initiator of the error.

The error message that you're getting, `Unexpected token <`, indicates that one of the network requests is returning HTML (a file that starts with the `<` character) instead of javascript. This often happens when your web server is in SPA mode and is configured to return the index.html file whenever it cannot find the actual js file that was requested.

The next step I would take to debug is look through your network requests and find the one that should be a js file but is actually returning HTML. Is probably a file that is System.import()'ed inside of main.js. After you find which network request is problematic, figure out why that file doesn't exist and fix that.

**Comment by tomzaku** [comment]
Thanks @joeldenning 
I debugged the network and found the error when fetching the file 'react' & 'react-dom'.
I was surprised that It didn't fetch 'react' & 'react-dom' files from cdn. 
```
 "imports": {
					react: 'https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.production.min.js',
					'react-dom': 'https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom.production.min.js',
					'react-dom/server': 'https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.8.6/umd/react-dom-server.browser.production.min.js',
					'single-spa': 'https://unpkg.com/single-spa@4.3.2/lib/umd/single-spa.min.js',
					lodash: 'https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.min.js',
					rxjs: 'https://unpkg.com/rxjs@6.4.0/bundles/rxjs.umd.min.js',
        }
```
Instead of that, It fetched files from `http://localhost:9200/react` and `http://localhost:9200/react-dom`.
And of course, it will return html file instead of javascript file.
![image](https://user-images.githubusercontent.com/19413272/59156049-4b67ef00-8abf-11e9-9f80-0a5b1b9193c6.png)

Do you have any suggestions?

**Comment by tomzaku** [comment]
Could I do something like that
```
"imports": {

	react: '../node_modules/react/react.production.min.js',
	'react-dom': '../node_modules/react-dom/16.8.6/umd/react-dom.production.min.js',

	'single-spa': '../node_modules/single-spa@4.3.2/lib/umd/single-spa.min.js',
	lodash: '../node_modules/ajax/libs/lodash.js/4.17.11/lodash.min.js',
	rxjs: '../node_modules/rxjs@6.4.0/bundles/rxjs.umd.min.js',

}
```
Means import node_modules instead from cdn

**Comment by joeldenning** [comment]
> Instead of that, It fetched files from http://localhost:9200/react and http://localhost:9200/react-dom.

That would seem to indicate that systemjs hasn't processed the import map at the time that it is trying to load react and react dom. Would be good to double check that systemjs is the initiator of the network request to `localhost:9200/react` and not webpack. You can do that by adding the "Initiator" column to your Network tab in Chrome devtools, then clicking on the initiator for the react network request and seeing if it's systemjs or not. My guess is that it is, but if it's webpack or something else initiating the request then that's the issue.

Next step I'd take to debug is check which code is triggering the download of react and react-dom. And see if that's happening before SystemJS is loaded. If so, that would explain the issue. If not, I'd put a break point on https://github.com/systemjs/systemjs/blob/3616ff8d24be85a1fe10d3f34add3c78e8695f7a/src/features/import-map.js#L22 and see if that line of code is getting executed before the request the code triggers a download of react. If not, then that's the problem. If so, then it's a bit deeper. You'd want to put a breakpoint [here](https://github.com/systemjs/systemjs/blob/master/src/features/import-map.js#L43) and see what the resolve function is returning for `react`.

**Comment by tomzaku** [comment]
Thanks for your information.
>That would seem to indicate that systemjs hasn't processed the import map at the time that it is trying to load react and react dom. Would be good to double check that systemjs is the initiator of the network request to localhost:9200/react and not webpack. You can do that by adding the "Initiator" column to your Network tab in Chrome devtools, then clicking on the initiator for the react network request and seeing if it's systemjs or not. My guess is that it is, but if it's webpack or something else initiating the request then that's the issue.
As you guess, Systemjs's  still there.
![image](https://user-images.githubusercontent.com/19413272/59156435-79e8c880-8ac5-11e9-8327-59ef85058b99.png)
> You'd want to put a breakpoint here and see what the resolve function is returning for react.
I looked up node_modules/systemjs/dist/system.src.js and search 'acquiringImportMaps' but it doesn't found any result.
![image](https://user-images.githubusercontent.com/19413272/59156529-2e371e80-8ac7-11e9-8069-cb47df422e1c.png)

**Comment by joeldenning** [comment]
Ah maybe you're on an old version of SystemJS that doesn't support import maps? Are you on systemjs@0.21 instead of v3?

**Comment by tomzaku** [comment]
I checked the version of systemJs by package.json and it shows me like that:
"systemjs": "^3.1.6",

**Comment by tomzaku** [comment]
But when I check by this line
```
cat node_modules/systemjs/package.json| grep version
  "version": "0.21.5",
```

**Comment by tomzaku** [comment]
Look like something wrong when install

**Comment by joeldenning** [comment]
Something is missing because version 3.1.6 does not have system-production.js. See https://unpkg.com/systemjs@3.1.6/dist/. Only 0.21 does. https://unpkg.com/systemjs@0.21.6/dist/

Looks like you're using 0.21 somehow. Might be that another package in your bundle has a downstream dependency of systemjs@0.21? I know that Angular does some stuff with 0.21, and it seems like you might be doing some angular stuff since you've got ZoneJS going.

**Comment by tomzaku** [comment]
![image](https://user-images.githubusercontent.com/19413272/59156710-fbdaf080-8ac9-11e9-9963-1a40b0f3e60b.png)
When I update the version from 0.21 to 3.1.6 and still didn't see 'acquiringImportMaps' word by searching. It could be complied and changed the name

**Comment by joeldenning** [comment]
It's there if you use `system.js` instead of `system.min.js`. See https://unpkg.com/systemjs@3.1.6/dist/system.js which has acquiringImportMaps right in it.

Upgrading to version 3 will likely change everything though -- are you still getting a similar error? Or what's your new error?

**Comment by tomzaku** [comment]
Similar errors
Instead GET return 200, now is 304
![image](https://user-images.githubusercontent.com/19413272/59157227-490e9080-8ad1-11e9-95ef-1b41be84406a.png)

**Comment by joeldenning** [comment]
Next step would be go back to my comment that had instructions that assumed you were on systemjs@3?

**Comment by tomzaku** [comment]
Thanks Joel,

When I updated to v3 it will throw the error " Can't resolve 'systemjs' in common-deps.js"
When I looked up package.json in systemJs v3, it's mentioned 'main'
```
"files": [
    "dist"
  ],
```
That why I write this line it will throw error

```
const systemJs = require('systemjs')
systemJs
```
The reason I wrote this line is to make sure `common-deps` will include systemJs.

**Comment by tomzaku** [comment]
I tried to do something like this but still not work
```
import systemJs from 'systemjs//dist/system'
import amd from 'systemjs//dist/extras/amd'
import nameExport from 'systemjs//dist/extras/named-exports'

window.SystemJS = window.System

export {
  systemJs,
  amd,
  nameExport
}
```

When I import directly from unpkg like this, it will work perfectly.
```
		<script src='https://unpkg.com/systemjs@3.1.2/dist/system.js'></script>
		<script src='https://unpkg.com/systemjs@3.1.2/dist/extras/amd.js'></script>
		<script src='https://unpkg.com/systemjs@3.1.2/dist/extras/named-exports.js'></script>

```

**Comment by joeldenning** [comment]
Your errors might be too specific to your exact code to help you further. Couple last things I'll comment on: 1) if you can't `require('systemjs')` then your node_modules, package.json, or webpack config are messed up. Figure that out first. 2) don't put in two slashes into your import statements. `systemjs//dist` is wrong. Instead, do `systemjs/dist`.

**Comment by JerryBerry12** [comment]
#2388 can you help me?
