### ISSUE TITLE
base uri not taken into account

### ISSUE THREAD

**Issue by LarsDenBakker** [systemjs/systemjs#1956]
Given a page:

```
<html>
  <head>
    <base href="/foo/">
  </head>
  <script src="./s.min.js"></script>
  
  <script type="module src="./my-esm.js"></script>

  <script>
    System.import('./my-system-module.js');
  </script>
</html>
```

If the browser path is `/foo/`, the browser will request `./foo/my-esm.js` and `./foo/my-system-module.js`.

If the browser path is `/foo/bar/`, the browser will request `./foo/my-esm.js` and `./foo/bar/my-system-module.js`.

This is unexpected, I would expect systemjs to respect the `<base>` element and request `./foo/my-system-module.js`. This is also the behavior of native es modules, images, style links etc.

This pattern is very common with SPA routing, where URLs change through javascript without going back to the server.

The problem is that the baseUrl is calculated only from the window location here: https://github.com/systemjs/systemjs/blob/master/src/common.js#L8

Normally you could use Node.baseURI for this, which takes the base element into account or otherwise falls back to the window location. Unfortunately this is not supported on IE11: https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI

**Comment by guybedford** [comment]
@LarsDenBakker we could add support for the `<base>` tag in SystemJS via checking the `<head>` for the tag explicitly in the initial determination.

I'd be happy to accept a PR along these lines - although note that keeping the character count down is important.
