### ISSUE TITLE
Documentation Missing for Browser Usage

### ISSUE THREAD

**Issue by ThoughtDrive** [systemjs/systemjs#1958]
There is a [Pluralsight video](https://www.pluralsight.com/courses/javascript-module-fundamentals) that shows how to use SystemJS in a browser, but it's for the older 0.19 version. I'm having difficulty finding anything in the documentation on how to use SystemJS in a browser for the latest version. I would like to request that a simple setup (this is already in the documentation, but it would be nice to expand on it a bit) and usage section be added to the documentation so people that are new to SystemJS will be able to follow the instructions and get up and running quickly without the need for external npm packages (if that's even possible with the latest version). If you like, I am willing to help with that effort. I already have a working demo for version 0.19 that shows how to set up SystemJS and imports a module. If I could get the project to work with version 3.1.6, I could make documentation and send that your way for approval. Either way, I'm stuck using version 0.19 until I can find documentation on how use the latest version.

**Comment by viT-1** [comment]
My [example repo](https://github.com/viT-1/systemjs-ts-es6-vue) on 5.0 (with dev version for ES-modules for modern browsers)

**Comment by joeldenning** [comment]
Here's an intro video: https://www.youtube.com/watch?v=AmdKF2UhFzw

And here's a repo of examples: https://github.com/systemjs/systemjs-examples

**Comment by kouts** [comment]
@joeldenning thank you for your work.
