### ISSUE TITLE
parallel imports could breaks each other

### ISSUE THREAD

**Issue by Pashokus** [systemjs/systemjs#1960]
If you are loading a bunch of modules and one of them will throw an error during executing some async code, System.import call will be rejected for another module with this error. 

I am using imports-map and amd extra.

**Comment by guybedford** [comment]
This could be a bug with the AMD extra, although it may well be browser-specific too.

Any chance you could share the replication? Which browser is this happening with?

**Comment by Pashokus** [comment]
Thanks for the quick response!
You can clone this repo https://github.com/Pashokus/systemjs-issue and follow steps in the README file

**Comment by Pashokus** [comment]
if you can't reproduce the issue using these steps, try to change timeout in the file 2.js from 100 to different value, like 200, 300 and back

**Comment by joeldenning** [comment]
I just pulled cloned the repo and was able to replicate the issue. I also PR'ed the issue repo to make it easier for others to replicate it. https://github.com/Pashokus/systemjs-issue/pull/1

**Comment by joeldenning** [comment]
I replicated the issue in Firefox. It is not Chrome-specific

**Comment by joeldenning** [comment]
Fix released in 4.0.1. See https://github.com/systemjs/systemjs/blob/master/CHANGELOG.md
