### ISSUE TITLE
use-default extra not working with module's deps?

### ISSUE THREAD

**Issue by frehner** [systemjs/systemjs#1977]
In an attempt to upgrade from 3.1 to 4.1, I discovered that my app doesn't work even with the `use-default` extra. What I _think_ is happening is that the `use-default` extra works for anything that you call `System.import` on, but _doesn't_ work if you need `use-default` to work on a module's dependencies.

@joeldenning

**Comment by joeldenning** [comment]
# Details about the issue

See these lines of code, which are why this isn't working:

https://github.com/systemjs/systemjs/blob/d615254e2145dea7ed637f9c017b166b0c7938e3/src/system-core.js#L101
https://github.com/systemjs/systemjs/blob/d615254e2145dea7ed637f9c017b166b0c7938e3/src/system-core.js#L135

I looked at system-core.js and don't see a way of a systemjs extra being able to hook into that functionality to modify it.

# A proposed solution

We add a new hook to systemjs named something like `System.prototype.prepareModule`. It would be called whenever passing a `ns`/module object to external code. The out-of-the-box implementation is just this:

```js
// out-of-the-box
System.prototype.prepareModule = function(ns) { return ns };
```

The use default extra would then patch that function like so:
```js
System.prototype.prepareModule = function(ns) { return ns.__useDefault ? ns.default : ns }
```

@guybedford can you think of a different solution to this? What do you think of the proposed solution?

**Comment by guybedford** [comment]
@frehner this is what the named exports extra is for, have you tried that here?

**Comment by frehner** [comment]
Yeah, I have that extra as well. Didn’t fix it

**Comment by guybedford** [comment]
@frehner it definitely should work, so could well be a bug. Could you perhaps share an exact replication case of how named exports isn't applying here?

**Comment by guybedford** [comment]
Also make sure to apply the named exports extra **after** the AMD extra.

**Comment by frehner** [comment]
Yup, I’ll see if I can make a example tomorrow. For the moment I’ll just add that I had SystemJS 3.1 with AMD and named exports extras.

After the upgrade to 4.1 with AMD, named exports, and use default extras my app broke.

**Comment by guybedford** [comment]
That was exactly the breaking upgrade path of 3 -> 4... that when importing an ES module from AMD, the `default` is not read automatically, but only for modules exporting `__useDefault`.

**Comment by frehner** [comment]
I was under the impression that the use default extra would be the way to have v4 act the same way it did as v3. Am I incorrect in that thought then?

**Comment by guybedford** [comment]
Yes, the default extra only applies to System.import. Note the main break is that when importing an ESM module from AMD, eg `export var p = 5; export default 42;`, before you would get `define(['./esmdep.js'], function (esm) { esm === 42 })` and now it is `esm === { p: 5, default: 42 }`.

If the issue you are hitting is on the other side though - getting the wrong thing when importing AMD from ESM or AMD from AMD, then that is a bug with the named exports extra under this new model, but I'd need to see a replication.

**Comment by frehner** [comment]
Yeah I think the issue I was seeing was the the imported ESM module only had a default property and no named properties at all. I’ll get a reproduction repo setup tomorrow to make sure I’m saying this all correctly though haha

Thanks for your help

**Comment by guybedford** [comment]
@frehner if you had an ESM being imported that had a default export, then yes that is exactly the change to your codebase needed for the SystemJS 4.x upgrade path - making the `.default` explicit! Neither the named exports nor use default extras will fix this for you, they handle the other cases.

If you really really really want it to work as before you can do `export const __useDefault = true` but that is strongly not recommended... rather correct at the importer side to access the `.default`.

**Comment by frehner** [comment]
I just double checked and my ESModule doesn’t have a default, just named exports.

**Comment by frehner** [comment]
But let me double check everything again, my memory is poor haha

**Comment by frehner** [comment]
ok, here's a repo to look at:

https://github.com/frehner/systemjs-amd-register-bug

(ignore the name, it was used to report a previous bug :D )

`app-2` is a ["system" bundle](https://github.com/frehner/systemjs-amd-register-bug/blob/master/src/app-2/rollup.config.js#L5), and `app-1` is an [AMD bundle](https://github.com/frehner/systemjs-amd-register-bug/blob/master/src/app-1/rollup.config.js#L5). 

SystemJS has the [`amd`, `named-exports`, and `use-default` extras](https://github.com/frehner/systemjs-amd-register-bug/blob/master/index.html#L20)

`app-1` only has [one named export](https://github.com/frehner/systemjs-amd-register-bug/blob/master/src/app-1/app-1.js) and nothing else in it. 

`app-2` imports [both a default and a named export from app1](https://github.com/frehner/systemjs-amd-register-bug/blob/master/src/app-2/app-2.js), just to see what's happening. 

Here's what's logged when you run the project:

![Screen Shot 2019-07-30 at 10 56 43 AM](https://user-images.githubusercontent.com/3054066/62149614-59fda600-b2b9-11e9-8acd-87d03f69150e.png)

So I guess for clarity's sake -- is this what is supposed to be happening?

**Comment by guybedford** [comment]
Thanks for the test case, yes it turns out this was a bug with the named exports extra. Fixed in https://github.com/systemjs/systemjs/pull/1978.

**Comment by guybedford** [comment]
Released in 4.1.1.

**Comment by frehner** [comment]
speedy fast! thank you for your patience with me, too :)

**Comment by joeldenning** [comment]
ha wow i was way off on this one i forgot what the named exports extra does. Will look at that one again 😄
