### ISSUE TITLE
How to connect dependencies (not from node_modules)

### ISSUE THREAD

**Issue by mg901** [systemjs/systemjs#1979]
How to connect dependencies (not from node_modules) to the System module.

**Comment by joeldenning** [comment]
Hi @mg901, I’m not sure exactly what your question is asking, could you help me understand?

In general, there are two ways of telling systemjs about modules:

1. An import map. See https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md
2. System.set. See https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemsetid-module---module

Once you do that, you are able to do a System.import() to load the module. Other modules are able to depend on those modules by specifying them as “externals” in their webpack/rollup config

**Comment by mg901** [comment]
Hi, @joeldenning . Thank you. `System.set` what you need.
