### ISSUE TITLE
[help] how to use systemjs in a commonjs way?

### ISSUE THREAD

**Issue by houyaowei** [systemjs/systemjs#1981]
[install] 
     I installed systemjs with npm install systemjs
[question]
    so , I want to execute the `import systemjs from "systemjs"`, finally, I
    get a error "Cannot resolve dependency 'systemjs'"

can I use it in this way? thx

**Comment by joeldenning** [comment]
My understanding is that systemjs does not currently support being executed in Node. See https://github.com/systemjs/systemjs/pull/1897.

If you're trying to bundle this into the browser, you should be able to do this:

```js
import 'systemjs/dist/system.js'

window.System.import()
```

**Comment by houyaowei** [comment]
@joeldenning  thanks for your answer.  

how about systemjs at version 0.21.5?
 https://www.npmjs.com/package/systemjs/v/0.21.5
whether it can be used in node?

**Comment by joeldenning** [comment]
systemjs@0.21 works in Node.

**Comment by guybedford** [comment]
Updated support for `require('systemjs')` in Node.js could be useful and wouldn't be too much work, I just haven't got around to it as the use cases don't seem that compelling! But the tracking issue can be found here - https://github.com/systemjs/systemjs/issues/1873.
