### ISSUE TITLE
Cannot import multiple modules that share the same name

### ISSUE THREAD

**Issue by ZachJW34** [systemjs/systemjs#1982]
Currently using SystemJS(5.0.0) in a single-spa like Angular application. We dynamically load multiple applications that all share the same default export of `AppModule`. The first application can load fine since their is no `AppModule` to begin with on the window and the [getGlobalProp]()https://github.com/systemjs/systemjs/blob/a8d4dc57dacae6e33e3c9967b9919c8f1afa1d76/dist/system.js#L554 function can successfully find the last global prop added. When the second application loads, rather than being added as the last global prop, it will replace the existing `AppModule` on the window and cause the `getGlobalProp` function to not find the new module.

After SystemJS has processed the import, should it not remove the global? I'm currently accomplishing this with:
```
(function() {
  const systemPrototype = System.constructor.prototype;
  const originalImport = systemPrototype.import;
  systemPrototype.import = function () {
    return originalImport.apply(this, arguments).then(function (ns) {
      delete window['AppModule']
      return ns
    });
  };
})();
```

**Comment by joeldenning** [comment]
Hmm you shouldn't need to create global variables at all. Here's a good example of single-spa + angular + systemjs working together. https://github.com/joeldenning/coexisting-angular-microfrontends

What are you trying to accomplish with the global variables?

**Comment by ZachJW34** [comment]
I do not need the globals, I just need the module in the registry. I believe the global is a result of our bundling our applications as `umd` bundles, and 
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
------> else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(window, function() {
```
the later else block being executed after the script is injected, adding the module to the window.

**Comment by joeldenning** [comment]
For UMD bundles, you should use the AMD, named export, and use default extras. The AMD extra will create a `window.define` function. So in the code snippet that you shared, it will call `define()` instead of creating the global variable.

See https://github.com/systemjs/systemjs#extras and http://single-spa-playground.org/playground/html-file.

**Comment by ZachJW34** [comment]
Ah I see. Thanks for all the help!
