### ISSUE TITLE
Change System.resolve to always be sync

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#1985]
See related #1939 for why System.resolve returning a promise is problematic for webpack users. Also note that the import specs themselves are moving towards a synchronous `import.meta.resolve()`.

Proposed implementation:
1. Modify [this line](https://github.com/systemjs/systemjs/blob/a8d4dc57dacae6e33e3c9967b9919c8f1afa1d76/src/system-core.js#L31) inside of System.import to call a function on the System.prototype called `acquireImportMaps`. Wait for the promise that it returns before proceeding to `resolve`
2. Modify [this line](https://github.com/systemjs/systemjs/blob/a8d4dc57dacae6e33e3c9967b9919c8f1afa1d76/src/features/import-map.js#L40) so that `acquireImportMaps` is patched and does the waiting there. Keep patching `systemjsPrototype.resolve`, but have it return synchronously.

```js
// rough draft of changes to system-core.js
systemJSPrototype.acquireImportMaps = function() {};

systemJSPrototype.import = function (id, parentUrl) {
  const loader = this;
  return Promise.resolve(systemJSPrototype.acquireImportMaps())
  .then(function() {
    return loader.resolve(id, parentUrl));
  })
  .then(function (id) {
    const load = getOrCreateLoad(loader, id);
    return load.C || topLevelLoad(loader, load);
  });
};
```

```js
// Rough draft of changes to import-maps.js
let finalMap;

systemJSPrototype.acquireImportMaps = function () {
  if (acquiringImportMaps) {
    acquiringImportMaps = false;
    Array.prototype.forEach.call(document.querySelectorAll('script[type="systemjs-importmap"]'), function (script) {
      importMapPromise = importMapPromise.then(function (map) {
        return (script._j || script.src && fetch(script.src).then(function (resp) {return resp.json()}) || Promise.resolve(JSON.parse(script.innerHTML)))
        .then(function (json) {
          return mergeImportMap(map, parseImportMap(json, script.src || baseUrl));
        })
      });
    });

    return importMapPromise.then(function(map) {
      finalMap = map;
    });
  }
};

systemJSPrototype.resolve = function(id, parentUrl) {
  parentUrl = parentUrl || baseUrl;
  resolveImportMap(id, parentUrl, finalMap);
};
```

@guybedford thoughts?

**Comment by qlqllu** [comment]
@guybedford any plan on this?

**Comment by guybedford** [comment]
I agree with the implementation approach here, and would gladly accept a PR along these lines.

Perhaps let's call the `acquireImportMaps` hook an async `beforeImport` or `prepareImport` hook or something suitably general so it might be used in other ways too.

**Comment by qlqllu** [comment]
It's great if you can push this update to NPM!

**Comment by joeldenning** [comment]
@qlqllu Since this is a breaking change, it will be part of systemjs@6.0.0. We're working on finalizing some changes for 6.0.0 on the [6.x branch](https://github.com/systemjs/systemjs/tree/6.x).

I'll see if we can maybe publish systemjs@6 under the npm `beta` tag. But for now, here's how you can use the code immediately:

```sh
npm install https://github.com/systemjs/systemjs.git#6.x
```

Note that systemjs doesn't currently work in NodeJS, though, and is best used via `<script>` tag. Also, bundling it via webpack is not recommended.

**Comment by qlqllu** [comment]
@joeldenning Thanks for the detail information!

I am trying to upgrade the 0.x version to the latest version. As you said, if the latest version does not work in NodeJS, I think I'd better wait for some time, because our app needs to support SSR.

What's the plan to support NodeJS?

**Comment by joeldenning** [comment]
See https://github.com/systemjs/systemjs/issues/1873 for the tracking issue for Node support.
