### ISSUE TITLE
Using mutation observers for dynamic import map support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#1995]
In theory the current approach is not spec compatible as we follow DOM order over dynamic injection order of import maps.

It should be possible to be fully in-line with the spec by using mutation observers.

The benefits of this approach are:

1. In theory slightly better performance as we immediately load import maps as they are added to the DOM.
2. It opens the door to loading import maps after the first module load, which would just work out naturally from there (each injection simply chains the existing `acquiringImportMapsPromise`).

(2) is not currently a feature of the spec, but I think it would be useful to be able to prototype this in SystemJS so that can inform the spec process (sometimes the tail has to wag the dog!).

Ideally we could make it an extra though to be clear about the spec situation.

If we were to separate it into an extra, that could be achieved by perhaps something as simple as a boolean flag on the System instance - `System.experimentalDynamicImportMaps = true` or similar.

**Comment by orbachar** [comment]
any updates on this?

**Comment by guybedford** [comment]
This is currently being discussed again in https://github.com/systemjs/systemjs/issues/2211.

**Comment by guybedford** [comment]
Implemented in the new dynamic import maps extra 6.4.0 thanks to @stevenvachon.
