### ISSUE TITLE
import: URL support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#2002]
Whether SystemJS would support internal `import:` URLs is still uncertain, but if it does, it would likely be a `if (url.startsWith('import:')) url = url.slice(7);` sort of approach.

The spec issue tracking this is https://github.com/WICG/import-maps/issues/149.

**Comment by viT-1** [comment]
It would be nice (for Vue/Angular templates) to include support of html-files (to do this without bundlers I had to use gulp-html-to-js),
because of plugin-text [is not working](https://github.com/systemjs/plugin-text/issues/52).

**Comment by joeldenning** [comment]
@viT-1 could you help me understand what you mean by "support of html files"? Are you talking about being able to do `<script type="systemjs-module" src="import:name-of-module">` inside of the root html file?

Or are you talking about SystemJS being able to load an html file as a module (see https://github.com/systemjs/systemjs/issues/1992)?

**Comment by guybedford** [comment]
An initial implementation of `import:` URLs has landed in https://github.com/systemjs/systemjs/pull/2015.

**Comment by viT-1** [comment]
> @viT-1 could you help me understand what you mean by "support of html files"?
> Or are you talking about SystemJS being able to load an html file as a module (see #1992)?
Yes, able to load html as a module.

**Comment by joeldenning** [comment]
@viT-1 you are in the wrong issue then. See https://github.com/systemjs/systemjs/issues/1992

**Comment by viT-1** [comment]
@joeldenning Ok
