### ISSUE TITLE
Select module type by mime-type

### ISSUE THREAD

**Issue by justinfagnani** [systemjs/systemjs#2005]
Matching the spec here will help head off potential errors that could be caused by misconfigured servers or server-side transforms that expect spec compliance.

Consider a server-side transform that UA-sniffs to detect JSON module support, and if the browser doesn't support them transforms `foo.json` to a JS module. The transform cannot rename the file, but it can set the mime-type.

I saw the explanation for selecting based on file-extension, but I wonder if inject script tags is really necessary. Could scripts not be executed by using fetch + a wrapped + eval? The wrapper can put the script in strict mode and ensure that top-level `this` is undefined, and even make top-level await work.

**Comment by dmail** [comment]
How using script makes it csp compatible while eval would not?

**Comment by LarsDenBakker** [comment]
We're migrating a large codebase from HTML Imports to es modules, and use a server-side transform to es module / systemjs. So we're serving .html files with mimetype text/javascript.

If I'm not mistaken, `fetch` is already use for file extensions other than `.js`? Then you could maybe special-case `.js`, and still use mine-type checking for rest which uses fetch.

**Comment by LarsDenBakker** [comment]
Yes that's what I mean. The use case of transforming .js into something else is a lot less, I think.

**Comment by guybedford** [comment]
The eval fallback approach has been released in 6.0.0.
