### ISSUE TITLE
Consider unbundling global extra from system.js by default

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#2008]
It may be worth removing the global extra from being included in SystemJS by default such that it only loads System.register modules or the CSS / JSON / Wasm modules.

Manually adding the global extra when needed doesn't seem such a pain, and would allow users to easily choose between AMD or global support for UMD patterns.

I would really value feedback here further to know if this makes sense.

**Comment by thiscantbeserious** [comment]
I can second that we're just bundling everything together to AMD, UMD or (our prefered way in combination with Rollup for now) to System.register format. 

I do however support less global scope pollution :hear_no_evil:, looking at what we try to aim with modules to begin with this seems counterproductive to begin with in a way and should be only applied when it's really needed (knowing that it's ugly).

So I'd support in making optional by default in my opinion.

**Comment by guybedford** [comment]
I don't think we should do this, at least not yet.
