### ISSUE TITLE
AMD extension that does not run js to get dependencies.

### ISSUE THREAD

**Issue by justinbmeyer** [systemjs/systemjs#201]
Related to: https://github.com/bitovi/steal-tools/issues/81

Would you consider changing the AMD plugin to work more like CJS so that it parses the dependencies instead of running the JS file to trap the "define" call?  Thanks!

**Comment by justinbmeyer** [comment]
@guybedford Most UMD style modules break in this way.  jQuery, Q, etc.  Anything like:

```
document.SOMETHING
if(define){
  define("d3", d3)
} else {
  window.d3 = d3
}
```

I created https://github.com/bitovi/system-parse-amd - an extension that does this.  The trick to it is that it runs the code only once when execute is called: https://github.com/bitovi/system-parse-amd/blob/master/system-parse-amd.js#L296

However, it fails System's tests as described here:

https://groups.google.com/forum/#!topic/systemjs/UWJhzvyirpc

I think that it's in SystemJS's best interests to avoid execution of code in instantiate across all formats.  Anything that wants to hook into it, like our trace, will have problems.

**Comment by guybedford** [comment]
@justinbmeyer the above style shouldn't break SystemJS. If you set the meta value to treat it as AMD surely it works fine? I'd be really interested to hear about it as I believe we can make that work 100%.

As for the issue you're having, I can't see which test you are referring to - can you point me to the test case code?
