### ISSUE TITLE
TypeError: registration[1] is not a function

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2016]
Migrating from 5.0 to 6.0
You can check it on this [pet project](https://github.com/viT-1/systemjs-ts-es6-vue) (5.0 actual).

Steps to reproduce:
- change package.json SystemJs to 6.0
- npm i
- npm run deploy
- npm run www
- localhost:3000

**Comment by guybedford** [comment]
I ran the steps but wasn't able to replicate this - the correct logs show up in the console in SystemJS 6 for me.

Also note that usually replications should be absolutely minimal - running custom install and build commands is not something maintainers should be expected to do, especially given the security risks.

**Comment by viT-1** [comment]
6.1.1 still have that strange error

**Comment by guybedford** [comment]
As mentioned I tried the replication previously but it was working fine for me, should I try it again?

If you are able to update / simplify the replication that would help a lot.

**Comment by viT-1** [comment]
@guybedford I would appreciate if you try to change 5.0 to 6.0 with my repository again.
I don't have so much time to prepare new (simplier) codebase.

**Comment by viT-1** [comment]
I just checked same error from IE11 and got another description about this situation:
`Unhandled rejection Error: Unable to resolve specifier './IamHeader.html' from src/common.blocks/IamHeader/IamHeader.conf`
You can try my repository:

- npm run deploy
- check dist/bundle.js file

**Comment by guybedford** [comment]
@viT-1 if you're still getting this, could you run with SystemJS unminified, and let me know which line is giving the error? It should be an easy fix if you could point me to that.

**Comment by viT-1** [comment]
I'm not using minified versions of SystemJS.
With 5.0 i have not errors, but with 6.1.4 i have (my proj [now](https://github.com/viT-1/systemjs-ts-es6-vue/tree/f52864a37917f0bb4f0deb1fb1c253fb42c7519b)):

```
(index):31 SystemJs bundle is loaded!
system.js:529 Uncaught (in promise) Error: Unable to resolve specifier './IamHeader.html' from src/common.blocks/IamHeader/IamHeader.conf
    at throwUnresolved (system.js:529)
    at SystemJS.systemJSPrototype.resolve (system.js:525)
    at SystemJS.systemJSPrototype.resolve (named-register.js:46)
    at system.js:325
    at Array.map (<anonymous>)
    at system.js:323
throwUnresolved @ system.js:529
systemJSPrototype.resolve @ system.js:525
systemJSPrototype.resolve @ named-register.js:46
(anonymous) @ system.js:325
(anonymous) @ system.js:323
load (async)
(anonymous) @ system.js:561
systemJSPrototype.instantiate @ system.js:543
systemJSPrototype.instantiate @ system.js:764
systemJSPrototype.instantiate @ named-register.js:54
(anonymous) @ system.js:278
Promise.then (async)
getOrCreateLoad @ system.js:277
(anonymous) @ system.js:229
Promise.then (async)
systemJSPrototype.import @ system.js:228
systemJSPrototype.import @ system.js:665
(anonymous) @ (index):29
```

**Comment by guybedford** [comment]
I was referring to the title bug being easy to resolve if the line from the source is known (running against unminified SystemJS). But this error seems to keep changing 🤔

**Comment by ricochet1k** [comment]
I'm seeing the same bug as the title. I'm seeing it on like 307, that looks like this: 
```js
const declared = registration[1](_export, registration[1].length === 2 ? {
```
In the debugger, `registration` looks like `['app', ['./asset.js']]` where `app` is the default export and `./asset.js` is one of the asset bundles Rollup generated.

**Comment by guybedford** [comment]
@ricochet1k that is due to using named register when SystemJS does not support named registration by default unless using the named register extra.

You should probably disable the named register output from the compiler providing the SystemJS output (so you get `System.register([deps], ...)` instead of `System.register('name', ...`).

If you really do want named registrations then add the extra.

**Comment by ricochet1k** [comment]
I don't understand, Rollup doesn't seem to have any options related to named registrations? It looks like Rollup is outputting for SystemJS 2.0, maybe I just need to use that version.

**Comment by guybedford** [comment]
Try setting ‘name’ to null or undefined in the Rollup configuration.

**Comment by ricochet1k** [comment]
Ah, just found that. Thanks.

**Comment by guybedford** [comment]
@ricochet1k it would help if you could let me know what workflow you were following here to get this issue. Did you have an explicit `name` in the configuration, or did you need to actually set it to null?

**Comment by ricochet1k** [comment]
I started my project from here: https://github.com/rixo/svelte-template-hot
I then wanted to have multiple entry points, with code splitting and bundle sharing as necessary, so I started following this: https://rollupjs.org/guide/en/#code-splitting skipping to the bottom of that section where it talks about SystemJS. 

The template had `name: "app"` by default, all I had to do was delete that line.

**Comment by guybedford** [comment]
I've added a readme edit in https://github.com/systemjs/systemjs/commit/e5730dfe2709a41a927d175c6b0637483719a452 to try and clarify this. The Rollup docs and code splitting workflow themselves don't have this case but it's definitely an easy catch yes.

**Comment by viT-1** [comment]
Trying v6.1.9

Got error with generated code
```
System.register("src/common.blocks/IamHeader/IamHeader.html", [], function (exports_1, context_1)
...
System.register("src/common.blocks/IamHeader/IamHeader.conf", ["./IamHeader.html"], function (exports_12, context_12)
...
```

One module can't resolve another, which generated from neighbor file in same folder =(
```
system.js:533 Uncaught (in promise) Error: Unable to resolve specifier './IamHeader.html' from src/common.blocks/IamHeader/IamHeader.conf
    at throwUnresolved (system.js:533)
    at SystemJS.systemJSPrototype.resolve (system.js:529)
    at SystemJS.systemJSPrototype.resolve (named-register.js:46)
    at system.js:329
    at Array.map (<anonymous>)
    at system.js:327
```

**Comment by jwsimms** [comment]
I have been working with SystemJS for sometime without any issues. Our project does not make use of a framework such as Vue, React, or Angular. It is strictly typescript. Recently, we are in the process to import other libraries, and I took the opportunity to update SystemJS to the latest version or adjust our software to reflect current practices.

After downloading 6.3.1 our project and using mapping the modules, I received two different errors.

- “Unable to resolve bare specifier”
- “registration[1] is not a function”

`
<script type="systemjs-importmap">
        {
           "imports": {
             "uniFormUI": "./uniFormUI.js"                       
           }
        }
        </script>
        
 <script type="systemjs-module" src="import:uniFormUI"></script>   
 <script src="./node_modules/systemjs/dist/system.js"></script>    
 <script src="./node_modules/systemjs/dist/extras/named-register.js"></script>

`

After days of fiddling with it, I was able to get the import map working, but I used version 6.3.1 of System.js and 6.1.2  of named-register.js.  It was a partial success. Weird! It intermittently worked on my home computer upon startup, generating a promise error attempting to instantiate a class that inherited another. However, my work computer is liking it as I write the description. I don’t get a warm fuzzy feeling with my solution.

To resolve that issue at home, I resorted back by importing my library from the <script> tags, and removing the systemjs-importmap settings. I think the library might not have been loaded before accessing the class, but I am guessing. It would definitely fail more often than succeed.

If I do not use systemjs-importmap, and install 6.2.5 of systemJS, it works perfectly. However, things go off the rails starting from 6.2.6.

`
system.js:533 Uncaught (in promise) Error: Unable to resolve specifier 'uniFormUI' from http://localhost:8080/uniWS/
    at throwUnresolved (system.js:533)
    at SystemJS.systemJSPrototype.resolve (system.js:529)
    at system.js:226

system.js:311 Uncaught (in promise) TypeError: registration[1] is not a function
    at system.js:311
`

Any suggestions would be greatly appreciated as I am running out of ideas. I don't want to mix systemJS versions, and don't want to remain at 6.2.5

**Comment by joeldenning** [comment]
Hi @jwsimms, could you please create a new Github issue for this? The Github issue template has a link in it to a code sandbox template that you can use to demonstrate the issue you're having - doing that is the best way for us to be able to diagnose this.

**Comment by jwsimms** [comment]
Is the sandbox private or public?

**Comment by jwsimms** [comment]
Thanks Joel for replying!

Since the project contains company proprietary code, I am unable to post it
in a public forum. I will attempt to reduce the project to a simplistic
structure and see if the issue remains. I suspect it will disappear. Only
one way to find out. If the error is not reproducible in this manner, are
there other options?

**Comment by joeldenning** [comment]
> If the error is not reproducible in this manner, are there other options?

Sure, it would just take more time and be harder to diagnose. Without a demonstration of the issue, I would just ask some questions and then ask some more after you respond. A few round of back and forth and I bet we'd be able to find it. However, if you can create a codesandbox from [this template](https://github.com/systemjs/systemjs/issues/new?template=bug.md) that shows it, I bet we'd be able to immediately identify and fix any issues.

**Comment by joeldenning** [comment]
If you're unable to create the code sandbox to demonstrate this, perhaps consider opening up a new issue using the "Question" template? It has some preliminary info that will help me diagnose.

https://github.com/systemjs/systemjs/issues/new?template=question.md

**Comment by guybedford** [comment]
Let's track this in https://github.com/systemjs/systemjs/issues/2185, it seems to come up every now and then but lets move the single issue there.

**Comment by izancalderaro** [comment]
> I have been working with SystemJS for sometime without any issues. Our project does not make use of a framework such as Vue, React, or Angular. It is strictly typescript. Recently, we are in the process of importing other libraries, and I took the opportunity to update SystemJS to the latest version and adjust our software to reflect current practices.
> 
> After downloading 6.3.1 and modifying our project to use importmap, I received two different errors.
> 
> * “Unable to resolve bare specifier”
> * “registration[1] is not a function”
> 
> ```
> <script type="systemjs-importmap">
>        {
>            "imports": {
>              "uniFormUI": "./uniFormUI.js"                       
>            }
>         }
>         </script>
>         
>  <script type="systemjs-module" src="import:uniFormUI"></script>   
>  <script src="./node_modules/systemjs/dist/system.js"></script>    
>  <script src="./node_modules/systemjs/dist/extras/named-register.js"></script>
> ```
> 
> After days of fiddling with it, I was able to get the import map working, but I used version 6.3.1 of System.js and 6.1.2 of named-register.js. It was a partial success. Weird! It intermittently worked on my home computer upon startup, generating a promise error attempting to instantiate a class that inherited another. However, my work computer is liking it as I write the description. I don’t get a warm fuzzy feeling with my solution.
> 
> To resolve that issue at home, I resorted back by importing my library from the <script> tags, and removing the systemjs-importmap settings. I think the library might not have been loaded before accessing the class, but I am guessing. It would definitely fail more often than succeed.
> 
> If I do not use systemjs-importmap, and install 6.2.5 of systemJS, it works perfectly. However, things go off the rails starting from 6.2.6.
> 
> ```
> system.js:533 Uncaught (in promise) Error: Unable to resolve specifier 'uniFormUI' from http://localhost:8080/uniWS/
>     at throwUnresolved (system.js:533)
>     at SystemJS.systemJSPrototype.resolve (system.js:529)
>     at system.js:226
> 
> system.js:311 Uncaught (in promise) TypeError: registration[1] is not a function
>     at system.js:311
> ```
> 
> Any suggestions would be greatly appreciated as I am running out of ideas. I don't want to mix systemJS versions, and don't want to remain at 6.2.5

Save my life! thx
