### ISSUE TITLE
Cannot read property 'default' of undefined. Importmap for node_modules used

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2018]
Smth strange (using SystemJS 5.0). I can turn on vue with vue-class-component on [sandbox project](https://github.com/viT-1/systemjs-ts-es6-vue),
but on internal project I can't turn it on with importmap for vue as external source.

```
// bundle.js
...
System.register("src/VueApp.init", ["vue", "src/VueApp.conf"], function (exports_15, context_15) {
    "use strict";
    var vue_5, VueApp_conf_1;
    var __moduleName = context_15 && context_15.id;
    return {
        setters: [
            function (vue_5_1) {
                vue_5 = vue_5_1;
            },
            function (VueApp_conf_1_1) {
                VueApp_conf_1 = VueApp_conf_1_1;
            }
        ],
        execute: function () {
            vue_5.default.config.productionTip = false;
            window.addEventListener('load', function () {
                new vue_5.default({
                    el: VueApp_conf_1.el,
                    components: VueApp_conf_1.components
                });
            });
        }
    };
});
```
Got error on first line of execute function
vue_5.default

Why vue_5_1 can be undefined? May be I need to "init/load/import" external node_modules?

```
// importmap
<script type="systemjs-importmap">
{
	"imports": {
		"vue": "https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"
	}
}
</script>
```

**Comment by joeldenning** [comment]
Which [systemjs extras](https://github.com/systemjs/systemjs#extras) are you using with systemjs? What order are you loading the extras in? I'd recommend using the AMD extra, named exports extra, and maybe the use default extra.

**Comment by viT-1** [comment]
Before tsc-transpiling my code was:
```
// VueApp.init.ts
import Vue from 'vue';
import { components, el } from './VueApp.conf';

Vue.config.productionTip = false;

window.addEventListener('load', () => {
	new Vue({
		el,
		components
	});
});
```

**Comment by joeldenning** [comment]
You should be able to use both the named extra and the AMD extra with vue. The file you linked to is in UMD format, which works great with those extras.

**Comment by viT-1** [comment]
Where I can find usage example?

**Comment by joeldenning** [comment]
Here's a decent example: https://github.com/joeldenning/coexisting-vue-microfrontends/blob/master/root-html-file/index.html.

**Comment by guybedford** [comment]
@viT-1 something strange is happening indeed. `vue_5` not being defined sounds like you may have some invalid System.register modules there.

Did you try adding a logger to:

```js
function (vue_5_1) {
                vue_5 = vue_5_1;
            },
```

to see if `vue_5_1` is defined, or that the setter is executing at all?

**Comment by viT-1** [comment]
I try it vue_5_1 was (and still) undefined

@joeldenning Your example use link with preload vue it is [not supported by IE11](https://caniuse.com/#feat=link-rel-preload) (for me SystemJS over ES modules advantages only for bundling modules for legacy browsers).
I added to the index.html use-default.min.js (besides which there is still system.min.js & named-exports.min.js)
and added System.import('vue') to the init script:

```
// index.html
<script>
	// fix vue-class-component.esm.js
	// https://github.com/vuejs/vue-class-component/issues/356
	window.process = { env: { NODE_ENV: 'production' } };
</script>
<script type="systemjs-importmap">...</script>
<script src="vue.js"></script><!-- Double initiated (importmap and script) vue was my issue! -->
<script src="system.js"></script>
<script src="named-register.js"></script>
<script src="use-default.js"></script>
<script src="bundle.js"></script>
<script>
System.import('vue')
	.then(function () {
		System.import('./bundle.js')
			.then(function () {
				System.import('src/VueApp.init') //according to System.register name
					.then(function () {
						console.log('bundle is activated!');
					});
			});
	});
</script>
```

and I had no success. But when I wrote this comment (and combine code together), suddenly realized that vue is initialized twice! It was my problem. Anyway thanks! And may be this issue will be helpfull for someone with same error.

**Comment by viT-1** [comment]
Note: after commented out `<!--<script src=".../vue.min.js">-->` my code (with importmap link to vue) working without `System.import('vue')`.
