### ISSUE TITLE
Is there a timeout option or cancel function for System.import?

### ISSUE THREAD

**Issue by ywmail** [systemjs/systemjs#2021]
I use System.js to load async components.  When the current route changes, I need to cancel loading the current component before loading another component.

**Comment by joeldenning** [comment]
SystemJS is a polyfill of browser specs, and afaik no browser spec currently supports the canceling of dynamic `import()`.

Here's some code you could use to implement cancellation with abort controllers. There might be an easier/more elegant way, but i think this would work.

```js
const abortController = new AbortController()
loadModule('foo', abortController).then(() => {
  console.log('only if not canceled')
})

// later on, cancel it
abortController.abort()

function loadModule(name, abortController) {
  let isCanceled = false
  abortController.addEventListener('abort', () => {
    isCanceled = true
  })

  return new Promise((resolve, reject) => {
    SystemJS.import(name).then(data => {
      if (!isCanceled) {
        resolve(data)
      }
    }).catch(err => {
      if (!isCanceled) {
        reject(err)
      }
    })
  })
}
```
