### ISSUE TITLE
named-export extra cannot handle co-existence of export { } & export default

### ISSUE THREAD

**Issue by shrinktofit** [systemjs/systemjs#2031]
```js
// a.js
const o = { p: 0 };
export { o };
export default o;
```

```js
// b.js
import { o } from './a';
```

These two modules are transformed as umd format using babel. And I setup systemjs with:
```js
import 'systemjs/dist/system';
import 'systemjs/dist/extras/amd';
import 'systemjs/dist/extras/named-exports'
```

At runtime, the `o` is not exported. When I trace into the debugger, the imported module `./a.js` is just the `o` itself.

**Comment by guybedford** [comment]
Can you confirm what version you are using here? This was actually fixed in
a recent release.

**Comment by shrinktofit** [comment]
v3.1.6...

Let me try the lastest...

**Comment by shrinktofit** [comment]
I have confirmed that it has been fixed..
