### ISSUE TITLE
IE, polyfill.io for Promise & fetch

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2037]
I couldn't [make to work](https://github.com/viT-1/systemjs-ts-es6-vue) SystemJs 5.0 with
`https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch,Promise`
If I replace bluebird & fetch links to polyfill.io IE11 raised error:
`Uncaught (in promise) TypeError`
but it's all ok with
`https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.5.5/bluebird.min.js`
&
`https://cdn.jsdelivr.net/npm/whatwg-fetch@3.0.0/dist/fetch.umd.js`

**Comment by joeldenning** [comment]
This sounds like a problem related to polyfill.io, not to systemjs. Are you reporting a bug with SystemJS?

I'm closing this since it doesn't seem related to systemjs, but feel free to comment further if I'm missing something.

**Comment by viT-1** [comment]
> I'm closing this since it doesn't seem related to systemjs, but feel free to comment further if I'm missing something.
Are you trying to test my issue?

**Comment by viT-1** [comment]
Stack trace is all about SystemJS:
```
Uncaught (in promise) TypeError: Не удалось получить свойство "default" ссылки, значение которой не определено или является NULL
   at execute (http://localhost:3000/bundle.js:438:13)
   at doExec (http://localhost:3000/systemjs/system.js:439:9)
   at postOrderExec (http://localhost:3000/systemjs/system.js:435:5)
   at Anonymous function (http://localhost:3000/systemjs/system.js:416:11)
   at postOrderExec (http://localhost:3000/systemjs/system.js:413:5)
   at Anonymous function (http://localhost:3000/systemjs/system.js:416:11)
   at postOrderExec (http://localhost:3000/systemjs/system.js:413:5)
   at Anonymous function (http://localhost:3000/systemjs/system.js:416:11)
   at postOrderExec (http://localhost:3000/systemjs/system.js:413:5)
   at Anonymous function (http://localhost:3000/systemjs/system.js:416:11)
```

**Comment by viT-1** [comment]
On stack trace on bundle.js:438:13 we have vue_class_component_1.default
[Related issue](https://github.com/vuejs/vue-class-component/issues/357) on vue-class-component

**Comment by joeldenning** [comment]
@viT-1 your comments after I closed the issue seem completely unrelated to your original comment. Your original issue is about polyfill.io, but your follow up comments are not related to polyfills at all.

I don't understand what issue you're trying to report.

**Comment by viT-1** [comment]
@joeldenning I'm trying to understand which package brings problem. Original issue and follow up comments all about IE + polyfill.io + SystemJs. Stack trace by [last commit](https://github.com/viT-1/systemjs-ts-es6-vue/commit/357000a9c509a57150f9291dee395f3fc8fad386) showed that vue-class-component.default is not related to original issue.

**Comment by viT-1** [comment]
@joeldenning error (bundle.js transpiled from [VueApp.ts](https://github.com/viT-1/systemjs-ts-es6-vue/blob/357000a9c509a57150f9291dee395f3fc8fad386/src/VueApp/VueApp.ts#L7)) is about resolving vue through [importmap](https://github.com/viT-1/systemjs-ts-es6-vue/blob/357000a9c509a57150f9291dee395f3fc8fad386/src/importmap.json)

```
System.register("src/VueApp/VueApp", ["vue", "src/VueApp/VueApp.conf"], function (exports_9, context_9) {
    "use strict";
    var vue_2, VueApp_conf_1, VueApp;
    var __moduleName = context_9 && context_9.id;
    return {
        setters: [
            function (vue_2_1) {
                vue_2 = vue_2_1;
            },
            function (VueApp_conf_1_1) {
                VueApp_conf_1 = VueApp_conf_1_1;
            }
        ],
        execute: function () {
            VueApp = /** @class */ (function () {
                function VueApp() {
                }
                VueApp.init = function () {
                    vue_2.default.config.devtools = false;
                    vue_2.default.config.productionTip = false;
                    // @link: no-new https://gitlab.com/gitlab-org/gitlab-ce/issues/42783
                    /* eslint-disable no-new */
                    new vue_2.default({
                        el: VueApp_conf_1.selector,
                        components: VueApp_conf_1.components,
                    });
                };
                return VueApp;
            }());
            exports_9("default", VueApp);
        }
    };
});
```

vue_2 is undefined =(

**Comment by viT-1** [comment]
In case of bluebird & whatwg-fetch all setters are initiated, but with polyfill.io this function is not run
```
function (vue_2_1) {
  vue_2 = vue_2_1;
},
```

**Comment by viT-1** [comment]
It is polyfill.io feature.
I can make it work with
`https://cdn.polyfill.io/v3/polyfill.min.js?flags=always`
&
`https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.5.5/bluebird.min.js`
+
`https://cdn.jsdelivr.net/npm/whatwg-fetch@3.0.0/dist/fetch.umd.js`

**Comment by joeldenning** [comment]
👍 glad to hear you got it working.

**Comment by viT-1** [comment]
@joeldenning Not so happy =) because 'always' flag force to implement polyfills to other browsers too. Moreover, legacy project has compatibility with polyfill.io v2 but not v3.

On the other hand this investigation show us the cause of problem, and it is not a SystemJS.

**Comment by tomzaku** [comment]
For me. It's just one simple line
```
    <script src="https://polyfill.io/v3/polyfill.min.js?features=fetch%2CPromise%2CURL"></script>
```
