### ISSUE TITLE
import.meta.resolve ?

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#2047]
I am currently experimenting around `import.meta.resolve`.
To do that I have a systemjs fork where I put

```js
resolve: (id) => loader.resolve(id, parentId),
```

Into

https://github.com/systemjs/systemjs/blob/2839f30af8804c5b7db3f9e8bb55b445f1f90bc2/src/system-core.js#L45-L49

Would you agree to make this part of systemjs ?

**Comment by dmail** [comment]
My suggestion is not fully working because doing
```js
module.context.resolve('foo')
```

with an importMap like 

```json
{
  "imports": {
    "/foo": "/bar.js"
  }
}
```

Is throwing Unable to resolve specifier.

This is because [resolveImportMap](https://github.com/systemjs/systemjs/blob/2839f30af8804c5b7db3f9e8bb55b445f1f90bc2/src/common.js#L179) is called with

```js
(importMap, "foo", parentUrl)
```

While I would expect it to be called with

```js
(importMap, `http://127.0.0.1:8080/foo`, parentUrl)
```

(Assuming my window.origin is `http://127.0.0.1:8080`

**Comment by joeldenning** [comment]
Why not just use [System.resolve](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemresolveid--parenturl---promisestring)?

`import.meta` is part of [this spec](https://github.com/tc39/proposal-import-meta). My preference would be to following the standards laid out in that spec for the systemjs `meta` object. Looks like [someone casually recommended import.meta.resolve](https://github.com/tc39/proposal-import-meta/issues/9#issuecomment-329252608) in a discussion a few years ago, but there doesn't appear to be any real proposal for it.

**Comment by guybedford** [comment]
`import.meta.resolve` likely will be specified at some point, we just have to be careful not to jump the gun here.

**Comment by dmail** [comment]
> Why not just use System.resolve?

Are you wondering why am I not using directly System.resolve in my code ?
If that was your question it is because the code is converted to systemjs, commonjs or an iife. I would like to use import.mea.resolve as an abstraction to convert into something compatible the formats mentionned.

> we just have to be careful not to jump the gun here.

I understand, I can see your will to stick to the spec through latest changes in systemjs. (which I salute by the way).
I can maintain a fork of systemjs until the behavior and need for import.meta.resolve becomes concrete.

Have you any advice to fix the `Unable to resolve specifier` error when doing `module.context.resolve('foo')` ?

**Comment by dmail** [comment]
I just looked at import-maps reference implementation, specifically on [parseFromString](https://github.com/WICG/import-maps/blob/eacf4eabfde2e98cc813e57b6b180296148df640/reference-implementation/lib/parser.js#L5).

According to my tests, the following:

```js
const importMap = parseFromString(
  `{
  "imports": {
    "foo": "./bar"
  },
  "scopes": {}
}`,
  "http://domain.dom",
)
console.log(JSON.stringify(importMap, null, '  '))
```

Logs
```console
{
  "imports": {
    "foo": "http://domain.dom/bar"
  },
  "scopes": {}
}
```

But using systemjs

```js
const importMap = resolveAndComposeImportMap(
  {
    imports: {
      foo: "./bar",
    },
    scopes: {},
  },
  "http://domain.dom",
  { imports: {}, scopes: {} },
)
console.log(JSON.stringify(importMap, null, "  "))
```

Logs

```console
{
  "imports": {
    "http://foo": "http://bar"
  },
  "scopes": {}
}
```

**Comment by guybedford** [comment]
`resolveIfNotPlainOrUrl` very specifically does not resolve `resolveIfNotPlainOrUrl("foo", "http://127.0.0.1:8080/")` into `"http://127.0.0.1:8080/foo"`, but rather returns `undefined`. This is then used to construct the `resolveAndComposeImportMap` implementation where the LHS in imports is resolved via `resolveIfNotPlainOrUrl(name) || name` exactly to get the expected `"imports": { "foo": "http://domain.com/bar" }` in your second example.

We have comprehensive tests on these cases so I suspect you were editing the source and mistakenly thought this was a SystemJS bug, but if not please do post a test case here further.

**Comment by dmail** [comment]
Yes indeed, sorry for the noise here.
I'm going to post a recap here when I'm done testing systemjs + import map resolution but I already realized the error is on my side.

**Comment by dmail** [comment]
I wanted to remap `"foo"` to `"bar.js"` but my import map was incorrect

```json
{
  "imports": {
    "/foo": "/bar.js"
  }
}
```

Should have been

```json
{
  "imports": {
    "foo": "./bar.js"
  }
}
```

So not a systemjs issue here.

About my experiment around import.meta.resolve I'll use the following snippet:

```html
<script src="system.js"></script>
<script>
  window.System = new window.System.constructor()
  window.System.createContext = (parentId) => {
    return {
      url: parentId,
      resolve: (id) => System.resolve(id, parentId),
    }
  }
</script>
<script>
  widnow.System.import('./index.js')
</script>
```
