### ISSUE TITLE
resolveIfNotPlainOrUrl can be wrong if parentUrl has no slash

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#2049]
**Steps to reproduce**

```js
resolveIfNotPlainOrUrl('/foo', 'http://domain.com')
```

**Expected return value**

```js
"http://domain.com/foo"
```

**Actual return value**

```
"http://foo"
```

Maybe that's not really an issue because `parentUrl` will never be just an origin without slash.
You will know better than me.

**Comment by joeldenning** [comment]
I'm not 100% sure on this one - will defer to @guybedford on it. Below is my understanding of this.

> Maybe that's not really an issue because parentUrl will never be just an origin without slash.

Yes, I think that that is the case. My understanding is that resolveIfNotPlainOrUrl should be called with a parentUrl that is a directory. Normally it is only called with the `baseUrl`, as calculated via the `<base>` element or `location.href`.

I know that `location.href` is guaranteed to always have a trailing `/` after the origin. And my understanding of `<base href>` is that the href should end in a `/` in order for requests to be made relative to that directory.

**Comment by guybedford** [comment]
Yes, `resolveIfNotPlainOrUrl` should strictly support this case, BUT this function is a specially designed resolver that is optimized to be fast (faster than new URL) and small and without unnecessary logic. The assumption is that the parent URL will always be a valid normalized URL. If you do eg `new URL('http://domain.com').href` you will see the trailing slash is strictly supposed to be included.

When writing an `import.meta.resolve` implementation, it should be using `import.meta.url` as the parent (`this.url` from within the resolve function) which will always be a valid URL, so you should be able to workaround this @dmail without needing a fix.

**Comment by dmail** [comment]
I confirm `resolveIfNotPlainOrUrl` behaviour is correct regarding parentUrl because it will always have a trailing slash.
Thanks for your response.
