### ISSUE TITLE
Race condition linking dependencies

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2051]
To reproduce: 

Go to https://openmrs-spa.org/openmrs/spa/login and open up console. Refresh the page several times. You'll see a variety of errors related to linked dependencies not being provided to modules correctly, on a race condition / random basis.

Not sure root cause yet. I have verified the errors occur with systemjs@6.0.0 and systemjs@6.1.3. Don't know about other versions.

Going to look into this more, and hopefully find root cause.

**Comment by guybedford** [comment]
Just took a quick look but with minified sources of SystemJS and dependencies it's a bit tricky. Typically don't want to debug these issues with source maps. Yeah I would suggest getting this isolated to a test server, switching to unminified SystemJS, then slowly cutting out dependencies until you get something close to isolateable.

**Comment by joeldenning** [comment]
I fixed this in https://github.com/openmrs/openmrs-esm-root-config/pull/30. The cause was that `System.getRegister()` would sometimes return the wrong registration for react-dom because `System.register()` was being called manually inside of a different module.

**Comment by guybedford** [comment]
It is a requirement that `getRegister` is called synchronously directly after the `System.register` call. So yes that sounds like it would cause a race condition otherwise.
