### ISSUE TITLE
Load a module via a pre-obtained string containing the module code?

### ISSUE THREAD

**Issue by sdegutis** [systemjs/systemjs#2053]
I have a file at ./foo.js that contains the typical System.register(...) top-level call. But sometimes I have the text contents of this file ahead of time, without needing to go over the network to get it. Is it possible to register this module into SystemJS using this string, instead of going over the network? I can't really figure out how to use SystemJS's low-level API to accomplish this.

**Comment by sdegutis** [comment]
Thanks for getting back to me about this. It's a clever solution.

One thing though, it messes with SystemJS's relative import resolution. So if my string is a pre-fetched copy of "./foo.js" which tries to import "./bar.js", then calling `System.eval(fooSource)` throws `Error loading [eval]:bar.js`, because the prefix of the eval plugin's string is interpreted as the relative base, because the "./" from "./foo.js" is lost.

Ultimately I'd like an API like this:

```javascript
System.preload('./foo.js', fooSource);
System.preload('./bar.js', barSource);

System.import('./foo.js').then(/* ... */);
```

And I think your eval idea inspired a way I could do this:

1. In preload, resolve the path using `System.resolve(path)`
2. Store the source code in `sourceMap[resolvedPath] = source`
3. Override instantiate to try this map and eval/delete if found

This should preserve all path information. It should also allow preloading multiple modules up front. Since I'm rendering all of this from the server, I can then try to provide any cached modules to the client as an optimization.

Just tested it and it works. Here's what I came up with:

```javascript
(function (global) {

  const System = global.System;

  const preloads = Object.create(null);

  System.preload = function (name, code) {
    const url = System.resolve(name);
    preloads[url] = code;
  };

  const systemInstantiate = System.instantiate;
  System.instantiate = function (url) {
    const code = preloads[url];
    if (code) {
      delete preloads[url];
      (0, eval)(code);
      return System.getRegister();
    }
    return systemInstantiate.call(this, url);
  };

})(typeof self !== 'undefined' ? self : global);
```

Thanks for your help coming up with this. I was on the wrong path at first, trying to use System.set to accomplish this. But overriding instantiate was the way to go.

On a related note, it may be neat to have a plugin that caches modules for you after loading them (whether from preload or over the network) as long as its url conforms to a given function. Maybe something like `System.shouldPreload = (urlBeforeResolve) => urlBeforeResolve.test(/^\.\//)`. Just an idea.

**Comment by guybedford** [comment]
Right, what I usually do is make the `url` an optional second argument to the eval function, as it is not always the case that one wants to enforce the registry URL - 

```js
 System.eval = function (source, url = '[eval]:' + ++evalId) {
```

Note that `System.preload` is exactly what named System.register is for though - 

```js
System.register('https://path/to/module.js', [...deps...], function () {
});
```

Although usually if you find yourself populating these it means you are doing bundling the old AMD way which is generally not considered a good idea anymore!

**Comment by sdegutis** [comment]
I'm not sure whether my use-case is doing things the wrong way. It may very well be so, and I'm open to suggestions.

Ultimately I need the client-side to be able to load modules from the server that I sometimes have available ahead of time in the client (hence this issue) and sometimes don't.

They're dynamically created by the server at runtime, so I can't do traditional static bundling e.g. using webpack (or at least not in the traditional way).

**Comment by guybedford** [comment]
If the module is actually being created / compiled in the client then that is exactly a valid use case for this.

**Comment by guybedford** [comment]
And you'd probably be better off using the named register extension for this directly - https://github.com/systemjs/systemjs/blob/master/src/extras/named-register.js.

**Comment by sdegutis** [comment]
I think when I tried the named-register approach a bit ago using bare import specifiers, it had the same relative-address-resolution issue described above. And I don't think that plugin can be used with relative specifiers due to line 45.

**Comment by guybedford** [comment]
You probably want to use the named register extension with full URLs, the
approach if you look at it is entirely equivalent to a named veal like this
code sample.
