### ISSUE TITLE
Problem with System.set()

### ISSUE THREAD

**Issue by alexnofoget** [systemjs/systemjs#2062]
I have some plugin with this code:
```
import React from "react";

export const Hello = () => {
  console.log("react in plugin", React);
  return <span>hello world</span>;
};
```
I build it with webpack as amd, and setup react as extenral dependency.
Then I want to import this module dynamically from remote url (for example from localhost:8236/index.js) inside of my main application.

```
function App() {
  const [Component, setComponent] = useState(null);

  window.System.import("http://localhost:8236/index.js").then(module => {
    console.log("component", module.Hello);
    setComponent(module);
  });

  console.log("on render", Component);

  return (
    <div className="App">
      <Plugin />
      {Component && <Component.Hello />}
    </div>
  );
}

export default App;
```
If I use `systemjs-importmap` and react from cdn 
```
<script type="systemjs-importmap">
      {
        "imports": {
          "react": "https://cdnjs.cloudflare.com/ajax/libs/react/16.8.6/umd/react.development.js"
        }
      }
</script>
```
then everything works well, but react inside my app and inside plugin works from different instances. Therefore I cant use hooks and context inside plugin.

I tried to use `System.set('react', React)`, where React from `import React from 'react'`. But my plugin doesnt define react then. 
![image](https://user-images.githubusercontent.com/1737309/67979901-47836780-fc2e-11e9-8f30-25ef02f0b254.png)
Can anyone help me to solve this issue?

**Comment by guybedford** [comment]
You probably want to define `react` as an external of your Webpack AMD bundle, so that it contains something like this - `define(['react'], ...`. That way SystemJS can pass the correct React instance to the bundle when it loads it.

**Comment by alexnofoget** [comment]
> You probably want to define `react` as an external of your Webpack AMD bundle, so that it contains something like this - `define(['react'], ...`. That way SystemJS can pass the correct React instance to the bundle when it loads it.

Webpack did it 
![image](https://user-images.githubusercontent.com/1737309/67980873-64209f00-fc30-11e9-82c6-18beb38cac54.png)
The problem is how to set react dependency from current instance of my main app through Systemjs

**Comment by guybedford** [comment]
Note you probably want anonymous defines as well (no `define("firstplugin", ...`, just `define(['react'], ...`).

I'm confused then as to which module is not getting the same react instance If two modules have `define(['react']`, and you import both, then they have the same react.

**Comment by alexnofoget** [comment]
> I'm confused then as to which module is not getting the same react instance. If two modules have `define(['react']`, and you import both, then they have the same react.

Not if one react from current app and another from cdn.

**Comment by alexnofoget** [comment]
I tried to fix define and nothing changed:
![image](https://user-images.githubusercontent.com/1737309/67981723-4f450b00-fc32-11e9-9a49-a1f0e975df25.png)

**Comment by guybedford** [comment]
Ah, that would be the problem then indeed, exactly using import maps you can make sure they point to the same thing. But that does require SystemJS to be in charge of loading the AMD via `System.import('./webpack-chunk.js')` and also removing the named define.

**Comment by alexnofoget** [comment]
I meen this code with error:
```
function App() {
  const [Component, setComponent] = useState(null);

  window.System.set('react', React);
  setTimeout(
    () =>
      window.System.import('http://localhost:8236/index.js').then((res) => {
        console.log('import', res);
        setComp(res);
      }),
    2000,
  );

  console.log("on render", Component);

  return (
    <div className="App">
      <Plugin />
      {Component && <Component.Hello />}
    </div>
  );
}
```

**Comment by guybedford** [comment]
Don't use System.set. If you have to use it, you are already doing something wrong.

**Comment by alexnofoget** [comment]
If I setup react as external dependency for my main app and load it with Systemjs, then I`ll get errors with other packages which depend on react inside my app. Should I load all of them with Systemjs?

**Comment by alexnofoget** [comment]
Is any way to provide 'react' from current instance `React`?

**Comment by guybedford** [comment]
I see. Yes this path is trouble all the way!

If you must use System.set, use a URL for `'react'` - `System.set('app:react', { default: React, __useDefault: true })`, and remember it's an object with a default export. Where the import map points to `app:react` as well. Resolution always resolves into URLs.

But there will likely be further state issues...

Ideally you want a SystemJS module graph for your app that is well-defined in terms of where the instances are of everything.

**Comment by alexnofoget** [comment]
> If you must use System.set, use a URL for `'react'` - `System.set('app:react', { default: React, __useDefault: true })`, and remember it's an object with a default export. Where the import map points to `app:react` as well. Resolution always resolves into URLs.

I tried it, but nothing changed again :weary:
![image](https://user-images.githubusercontent.com/1737309/67987739-3c850300-fc3f-11e9-8fa3-3a29863da8e0.png)

**Comment by guybedford** [comment]
Did you use an import map to point `"react": "app:react"`?

**Comment by alexnofoget** [comment]
> "react": "app:react"

Oh, I see. Did you mean this?
```
<script type="systemjs-importmap">
      {
        "imports": {
          "react": "app:react"
        }
      }
</script>
```
I got empty react module inside my plugin

**Comment by guybedford** [comment]
Sorry I can't assist you further in your debugging process. I've given you some ideas hopefully you can work with, but open source can't, systematically, go further than that.

**Comment by joeldenning** [comment]
I've set up many systemjs@6 + react applications before. One key to making it work is to use the `named-exports` extra in addition to the `amd` extra.

You can see react working as an AMD module from CDN at the following url: https://openmrs-spa.org/openmrs/spa/login

**Comment by alexnofoget** [comment]
> I've set up many systemjs@6 + react applications before. One key to making it work is to use the `named-exports` extra in addition to the `amd` extra.
> 
> You can see react working as an AMD module from CDN at the following url: https://openmrs-spa.org/openmrs/spa/login

From CDN for me it is working too. But how to register module with set from app instance?

**Comment by joeldenning** [comment]
See https://github.com/systemjs/systemjs/issues/1510#issuecomment-548593606. I didn't read through all the back and forth with you and Guy Bedford, but I believe that you can do this:

```js
System.set(System.resolve('react'), window.React)
```

However, I'd recommend not doing this. Instead, load it from a CDN. The reason is that `System.set` is not a browser specification like import maps are. Right now the browser standards only support "one in-browser module per network request" and it's easiest just to stick to that methodology. Calling System.set() works but you have to know what you're doing (there are some nuanced things that happen with it). If the above code doesn't work, I have no interest in helping you debug your specific situation 😄.

**Comment by alexnofoget** [comment]
@guybedford I used your suggestion

```System.set('app:react', { default: React, __useDefault: true })```.
but faced with further problem: 
https://user-images.githubusercontent.com/1737309/67988412-eca73b80-fc40-11e9-8ddd-b3b448bac176.png 

After several hours of debugging I figured out that everything works just fine if I remove this check:
```
if(depLoad.h || !depLoad.I)
```
Could you tell me how to bypass this condition check?
I don't want to fork systemsjs just to remove this single line with unclear consequences.

**Comment by guybedford** [comment]
@alexnofoget is the `depLoad` in the above the `depLoad.id === 'app:react'` that you need to skip the check for?

Note that `System.set` explicitl will set `depLoad.I` to `undefined` so that the `if` statement will always be true in that case.

If it is not, perhaps check you are running the latest version, or confirm the exact situation that is applying here in the above (the `depLoad.id` value).

**Comment by alexnofoget** [comment]
I`m sorry for wainting. I have created a demo project. Here it is https://github.com/alexnofoget/system-demo
In `public/index.html` you can change source of systejs:
```
<!-- <script src="%PUBLIC_URL%/js/system.js"></script> -->
<script src="https://unpkg.com/systemjs@6.1.4/dist/system.js"></script>
```
By default it is system from CDN latest version and `System.set('app:react', { default: React, __useDefault: true })` will not work. 
But you can use local version with commented this line https://github.com/alexnofoget/system-demo/blob/master/public/js/system.js#L335 and then `System.set('app:react', { default: React, __useDefault: true })` works well.

**Comment by shrinktofit** [comment]
Hey you can try this: 

`System.register("react", [], /* Normal part that export react instance, see System.register module format */)`

However you should enable named-register on

**Comment by joeldenning** [comment]
See #2106 which explains how to use System.set.
