### ISSUE TITLE
Add live web demos

### ISSUE THREAD

**Issue by mk-pmb** [systemjs/systemjs#2063]
Hi!
Could you please add some web demos into `docs/examples/` that demonstrate how to use systemjs, live on the web, "try it yourself"? (Using the master branch as Github Pages root.)
There are some code examples in the readme already for Import Maps, but it would be nice to be able to see the available features in action and study their behavior without having to set them up on your own webspace first.

**Comment by guybedford** [comment]
//cc @joeldenning was doing some work like this in https://github.com/systemjs/systemjs-examples.

Definitely need to get these going I agree. Further input / ideas welcome.

**Comment by joeldenning** [comment]
yeah also we have plans to work on a documentation website for systemjs, too.

**Comment by mk-pmb** [comment]
I do hope we can get the examples good enough that 98+% of users won't need the docs website. :D

**Comment by joeldenning** [comment]
There are five examples pending code review at https://github.com/systemjs/systemjs-examples/pulls.
