### ISSUE TITLE
How do I have to import rxjs/operators in Systemjs 5.0.0?

### ISSUE THREAD

**Issue by danyjaen** [systemjs/systemjs#2066]
Hello and **thanks** for your work, 
I have an issue with an angular 8 application, I'm trying to import @angular/core and rxjs 6 with systemjs but I receive the following error:
![image](https://user-images.githubusercontent.com/29709790/68797590-2884cc80-0655-11ea-9a8a-fb8fd5955f4f.png)

I tried to import rxjs/operators from rxjs/operators/index.js but it doesn't work
`{
  "imports": {
    "monitoring": "http://localhost:4201/main.js",
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@4.3.7/lib/system/single-spa.min.js",
    "@angular/core": "https://unpkg.com/@angular/core@8.0.0/bundles/core.umd.js",
    "rxjs": "node_modules/rxjs/bundles/rxjs.umd.min.js"
  }
}`

and also tried 
`{
  "imports": {
    "monitoring": "http://localhost:4201/main.js",
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@4.3.7/lib/system/single-spa.min.js",
    "@angular/core": "https://unpkg.com/@angular/core@8.0.0/bundles/core.umd.js",
    "rxjs": "node_modules/rxjs/bundles/rxjs.umd.min.js",
    "rxjs/operators": "node_modules/rxjs/operators/index.js"
  }
}`

**Comment by joeldenning** [comment]
Hi @danyjaen -- I've done this exact  thing before with the following code:

https://github.com/openmrs/openmrs-esm-root-config/blob/43252e76f792ad95b173cf4f47b10833bf09884d/src/rxjs-compat/rxjs-modules.js#L1

Check out that whole file. The root of the problem here is that browser standards call for "one network request per module," but that the rxjs bundles published to npm do not have a separate bundle for the operators.

One thing I'd suggest is to use [`System.set()`](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemsetid-module---module) instead of System.register for the operators. I think you'll still need to patch System.resolve like is shown in the file I linked to. The reason I suggest that is that I actually had to rollback the code I linked you to because it was causing the bug described in https://github.com/systemjs/systemjs/issues/2051. Using System.set() would change that, though.

**Comment by danyjaen** [comment]
Helo @joeldenning!
Thanks for your answer, is it possible to use this file with import-maps? Because I'm trying to do

importmap.json
```
{
  "imports": {
    "monitoring": "http://localhost:4201/main.js",
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@4.3.7/lib/system/single-spa.min.js",
    "@angular/core": "https://unpkg.com/@angular/core@8.0.0/bundles/core.umd.min.js",
    "rxjs": "/node_modules/rxjs/bundles/rxjs.umd.min.js",
    "rxjs/operators": "/node_modules/rxjs/index"
  }
}
```

index.html:

```
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Your application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="importmap-type" content="systemjs-importmap" />
    <script type="systemjs-importmap" src="/importmap.json"></script>
    <link
      rel="preload"
      href="https://cdn.jsdelivr.net/npm/single-spa@4.3.7/lib/system/single-spa.min.js"
      as="script"
      crossorigin="anonymous"
    />
    <script src="https://unpkg.com/core-js-bundle@3.1.4/minified.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/zone.js/dist/zone.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/import-map-overrides@1.8.0/dist/import-map-overrides.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/5.0.0/system.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/5.0.0/extras/amd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/5.0.0/extras/named-exports.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/5.0.0/extras/named-register.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/5.0.0/extras/use-default.min.js"></script>
  </head>
  <body>
    <script>
      const originalResolve = System.resolve;
      System.resolve = function(name) {
        if (name === 'rxjs/operators') {
          return '/rxjs-operators.js';
        } else {
          return originalResolve.apply(this, arguments);
        }
      };      System.set('/rxjs-operators.js', [], _export => {
        _export(rxjs.operators);
        return {};
      });
      System.import('single-spa').then(function(singleSpa) {
        singleSpa.registerApplication(
          'monitoring',
          function() {
            return System.import('monitoring');
          },
          function(location) {
            return location.pathname.includes('/');
          }
        );
        singleSpa.start();
      });
    </script>
    <import-map-overrides-full show-when-local-storage="overrides-ui"></import-map-overrides-full>
  </body>
</html>

```

But is not working,
![image](https://user-images.githubusercontent.com/29709790/68839345-d2e60980-06c0-11ea-85ee-e30e9100cff7.png)


 I tried also with the importmaps.json:

```
{
  "imports": {
    "monitoring": "http://localhost:4201/main.js",
    "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@4.3.7/lib/system/single-spa.min.js",
    "@angular/core": "https://unpkg.com/@angular/core@8.0.0/bundles/core.umd.min.js",
    "rxjs": "/node_modules/rxjs/index"
  }
}
```

But also didn't work
![image](https://user-images.githubusercontent.com/29709790/68839388-eabd8d80-06c0-11ea-8e4f-9f3b6236291e.png)


Thanks!!

**Comment by joeldenning** [comment]
> Thanks for your answer, is it possible to use this file with import-maps?

I don't think so. Like I said in my previous comment:

> The root of the problem here is that browser standards call for "one network request per module," but that the rxjs bundles published to npm do not have a separate bundle for the operators.

In other words, the rxjs project itself is not set up properly for it to work with import maps.

**Comment by danyjaen** [comment]
I think I have it!

   ```
 <script>
      const originalResolve = System.resolve;
      var rxjs = '';
      System.import('rxjs').then(function(rxjsa) {
        rxjs = rxjsa;

        System.register('/rxjs-operators.js', [], _export => {
          _export(rxjsa.operators);
          return {};
        });


        System.import('single-spa').then(function(singleSpa) {
          singleSpa.registerApplication(
            'monitoring',
            function() {
              return System.import('monitoring');
            },
            function(location) {
              return location.pathname.includes('/');
            }
          );
          singleSpa.start();
        });
      });

      System.resolve = function(name) {
        if (name === 'rxjs/operators') {
          return '/rxjs-operators.js';
        } else {
          return originalResolve.apply(this, arguments);
        }
      };
    </script>
```

Now it loads! Tnaks for your help!!

**Comment by joeldenning** [comment]
Update - here's a published version of rxjs that is in System.register format https://github.com/esm-bundle/rxjs

**Comment by mdgeek** [comment]
I know this is an old post, but I was struggling with this problem as well.  Here is what I came up with:

I created an AMD module for each deep import.  Here is the operators.js file for the import `rxjs/operators`:

    define('rxjs/operators', ['rxjs'], rxjs => rxjs.operators);

Here is my import map:


    {
      "imports": {
        "rxjs": "dist/rxjs.umd.js",
        "rxjs/": "dist/"
      }
    }
