### ISSUE TITLE
CJS plugins are bonk?!

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#2069]
I'm not seeing a clear upgrade path to v6 et al, so just bumped to 0.21.6 but eg plugin-text throws `exports is not defined`. 
Do I need to now transpile these w/babel? or am I missing something?

**Comment by joeldenning** [comment]
Duplicate of https://github.com/systemjs/systemjs/issues/1854. Also see related https://github.com/systemjs/systemjs/issues/2055 and https://github.com/systemjs/systemjs/pull/1901
