### ISSUE TITLE
Update to use classes

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#207]
Have each extension as a class extending the previous extension.

Then use an ES6 module build to connect them together into a single file.

Then work out how to remap the base class in another build for system-CSP so we can inject the script loader extension first.

**Comment by matthewp** [comment]
Can we still do this? I'd be happy to take it on if so. Not sure with the new W3 Loader if this will be possible or not.

**Comment by guybedford** [comment]
Closing - as discussed with @matthewp, we'd like to move to a simple extension stamping into an array:

```javascript
System._extensions = [register, core, cjs]; // etc.
```

**Comment by matthewp** [comment]
Hey @guybedford I'm happy to do it either way.  I wonder if classes provide a more elegant way to write extensions though. 

```js
var SystemLoader = System.constructor;

class SystemWithMap extends SystemLoader {
  normalize(name, parentName, parentAddress) {
    // do stuff
    return super(name, parentName, parentAddress);
  }
}

global.System = SystemWithMap;
```

I think you're concern was that we will have a deep nested prototype but I don't think this is necessarily a bad thing, as far as performance. It might aid in debugging as it will be easier to know which normalize you're inside of (debuggers will show `this` as being an instance of that class). 

I can implement the `System._extensions` like we discussed, it's a smaller change, but I'd like to still consider the class approach for in the future.

**Comment by chpio** [comment]
is this an allowed way to extend Systemjs?

```javascript
import {constructor as System} from 'systemjs';

export class MySystem extends System {
  normalize(name, parentName, parentAddr) {
    // my mapping
  }
}

export default new MySystem();
```

it's loading the files from my mapped URLs, but after that it crashes. I think the error is here: https://github.com/systemjs/systemjs/blob/f94507b22bc5aff669e9d404d43a6bd6e60fcf42/lib/register.js#L595

`loader.normalize` seems to be the original *normalize* not the extended one. I just don't know where the error is exactly.

**Comment by guybedford** [comment]
@chpio yes the above should be supported.

It just takes one class method to not scope the `this` properly and use an implicit binding, so it's possible there's a bug somewhere causing this.

If you're able to track it down further at all do let me know, it would just be about verifying the `this` value up the stack.

**Comment by chpio** [comment]
ok, it was my fault. it used the argument definition from this doc: https://github.com/ModuleLoader/es6-module-loader/blob/1530db0bf18adb7f58c8471228fefe75b925cc92/docs/loader-extensions.md

but i don't really get what the 3. argument is doing, the 1. is the current name 2. is the parent name.
