### ISSUE TITLE
es5 build

### ISSUE THREAD

**Issue by LarsDenBakker** [systemjs/systemjs#2071]
The systemjs `dist` runs fine on IE11 but it uses `let` and `const` which are not es5. This means it doesn't work on browsers which only support es5.

As far as I can tell that's the only blocker, is this something you guys think is worth it?

**Comment by joeldenning** [comment]
IE11 is supported but IE<=10 are not. Supporting those browsers comes with challenges and I'd prefer not to support them. We've already broken IE11 several times on accident in PRs and it would be a pain to have to test everything out in <=IE10 vms, too

**Comment by LarsDenBakker** [comment]
My use case specifically was older safari versions and chrome 41.

**Comment by guybedford** [comment]
If switching let and const to var is all it takes to support those versions, and it matters to you that much, then a PR here can be accepted sure. But if it is much more than just that then as @joeldenning says that falls outside the scope of the project.

**Comment by LarsDenBakker** [comment]
Thanks, I'll check if that's the only change necessary. I'll also double check if anyone is still testing Chrome 41, since googlebot uses evergreen chrome nowadays. IE10 isn't really a target.
