### ISSUE TITLE
Uncaught Error: Module  detected as amd but didn't execute correctly.

### ISSUE THREAD

**Issue by kukuyu** [systemjs/systemjs#2072]
I use single-spa load app which entry is singleSpaEntry.js:

![image](https://user-images.githubusercontent.com/16571529/69242790-99d7f880-0bdc-11ea-8d0b-e32ac573c828.png)

When using System.js v0.21.4 -  Error:

![image](https://user-images.githubusercontent.com/16571529/69242671-4e254f00-0bdc-11ea-90f6-fd27648347ef.png)

**Comment by joeldenning** [comment]
Impossible to diagnose this without further information. Would need to see the `singleSpaEntry.js` bundle file to understand this better.

**Comment by kukuyu** [comment]
> Impossible to diagnose this without further information. Would need to see the `singleSpaEntry.js` bundle file to understand this better.

Actually, the first screenshot is the entire contents of the singleSpaEntry.js file, which comes from the official document of single-spa ：  https://single-spa.js.org/docs/getting-started-overview

**Comment by joeldenning** [comment]
I'm referring to the bundle file, not the source file. Are you using webpack? Can you paste the link to the contents of the output bundle?

**Comment by kukuyu** [comment]
> I'm referring to the bundle file, not the source file. Are you using webpack? Can you paste the link to the contents of the output bundle?

yes , I use webpack, but  I don't quite understand what you said 'paste the link to the contents of the output bundle'

**Comment by joeldenning** [comment]
When you run webpack, it takes the `singleSpaEntry.js` file and creates a separate, new file that is browser-ready. That separate new file is called a bundle. See https://webpack.js.org/guides/getting-started/#creating-a-bundle for more documentation

**Comment by kukuyu** [comment]
> When you run webpack, it takes the `singleSpaEntry.js` file and creates a separate, new file that is browser-ready. That separate new file is called a bundle. See https://webpack.js.org/guides/getting-started/#creating-a-bundle for more documentation

I probably understand what you mean, but the  singleSpaEntry.js file has no other dependencies

**Comment by kukuyu** [comment]
![image](https://user-images.githubusercontent.com/16571529/69314618-8de94680-0c6f-11ea-82fc-8c57c79108a1.png)

**Comment by joeldenning** [comment]
Are you saying that you are not bundling the file with webpack? The number of dependencies doesn't matter - what matters is whether the file is processed by webpack.

If the file is not processed by webpack, then that would explain the problem. SystemJS is interpreting the module as an AMD format, but it is not in AMD format. Modules that are in AMD format must call `define()` - your module does not.

**Comment by kukuyu** [comment]
> Are you saying that you are not bundling the file with webpack? The number of dependencies doesn't matter - what matters is whether the file is processed by webpack.
> 
> If the file is not processed by webpack, then that would explain the problem. SystemJS is interpreting the module as an AMD format, but it is not in AMD format. Modules that are in AMD format must call `define()` - your module does not.

I use webpack bundlilng the file: 
![image](https://user-images.githubusercontent.com/16571529/69405467-bf7b1400-0d3a-11ea-82b5-7e52b9a98ae9.png)

I suspect that the Systemjs  version is a problem， I will try it by change the version of Systemjs. thank you very much!

**Comment by joeldenning** [comment]
It looks like your webpack bundle has not correctly set webpack's `output.libraryTarget` option. It appears to be compiling it to webpack's default `iife` format, but should be either `system` or `amd`.

See https://github.com/systemjs/systemjs#compatibility-with-webpack and https://github.com/joeldenning/systemjs-webpack-interop for some more information

**Comment by kukuyu** [comment]
> It looks like your webpack bundle has not correctly set webpack's `output.libraryTarget` option. It appears to be compiling it to webpack's default `iife` format, but should be either `system` or `amd`.
> 
> See https://github.com/systemjs/systemjs#compatibility-with-webpack and https://github.com/joeldenning/systemjs-webpack-interop for some more information

Just add this configuration-“libraryTarget: 'system'”，thank you ！
