### ISSUE TITLE
Same module，different url，return a diffent result？

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2075]
i want to request a child module, avoid cache， i am add a time stamp，why different two request？ how to solve ？ 
![image](https://user-images.githubusercontent.com/22994293/69528614-8f857800-0fa9-11ea-8a3d-30651840cbfc.png)

**Comment by yuanman0109** [comment]
this is my Usage scenarios：
![image](https://user-images.githubusercontent.com/22994293/69536667-5e14a880-0fb9-11ea-91f2-93900b030c27.png)

**Comment by joeldenning** [comment]
[`System.delete`](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemdeleteid---boolean) the module and then the next time you System.import it, it will redownload it.

**Comment by yuanman0109** [comment]
Thank you for your reply，i am solved it after import 'systemjs/dist/extras/amd.min.js'；but now ，the ‘main.js’ contain ‘react’, i want to the 'main.js' can depend parent's ’react‘，find a webpack‘s externals prop can come true；my parent project how to setting use ’systemjs‘？

**Comment by joeldenning** [comment]
I'm not sure if I understand your question - are you asking how to set [webpack externals](https://webpack.js.org/configuration/externals/#root). Or how to use systemjs in general?

**Comment by yuanman0109** [comment]
yes，i hope use systemjs import  all child module dependent The framework js,，maybe，i don‘t know system Whether there is this function

**Comment by yuanman0109** [comment]
thank you for your answer
