### ISSUE TITLE
system.min.js bundle problem in IE11

### ISSUE THREAD

**Issue by NebSehemvi** [systemjs/systemjs#2076]
**Version**: systemjs "6.1.5", **system.min.js** from dist

Unfortunately, I can't provide some screenshots, but I will copy text/code.

I've faced some problems with SystemJS in IE11:

`SCRIPT1002: Syntax error`
`File: system.min.js, Line 4, Column: 9229`

IE points to Line 4, Column 9229, and after clicking it, caret is placed between '=' and '>' of an arrow function.
This arrow function is single for whole bundle:
`r.forEach(t=>{n.i.push(t),t(n.n)})`

If I replace it with `function(t)`, everything works perfect. If I don't, nothing works and modules in IE don't load at all.

I hope it would be possible to fix it.

**Comment by kouts** [comment]
I've made a pr for this https://github.com/systemjs/systemjs/pull/2077#issue-346808302

**Comment by NebSehemvi** [comment]
I've thought on doing it myself, but pr appeared surprisingly quick. Thanks!

**Comment by smff** [comment]
I want to offer my own decision: https://github.com/systemjs/systemjs/pull/2079 as it solves the whole problem

**Comment by NebSehemvi** [comment]
> I want to offer my own decision: #2079 as it solves the whole problem

Unfortunately, SystemJS 6.x.x do not support IE10 or lower. 

https://github.com/systemjs/systemjs/issues/2071
> IE11 is supported but IE<=10 are not. Supporting those browsers comes with challenges and I'd prefer not to support them. We've already broken IE11 several times on accident in PRs and it would be a pain to have to test everything out in <=IE10 vms, too

I guess that full transpiling for IE10 won't be accepted.

**Comment by smff** [comment]
Okay -) 
I mean, my solution gives a template for writing the source code the way you want to. The final assembling goes through babel. 
We'll just have to see what the system.js owner decides to do

**Comment by joeldenning** [comment]
Fixed in https://github.com/systemjs/systemjs/releases/tag/6.1.6. I accidentally published 6.1.6 incorrectly (wrong version number in banner comment!) so I also published 6.1.7 with a fix for that.

**Comment by nikolowry** [comment]
I'd really love a fix for `systemjs-transform-babel` and IE11, see https://github.com/systemjs/systemjs-transform-babel/issues/4
