### ISSUE TITLE
how to avoid webpack@4.39.3 rewrite System.import()?

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2078]
i'm already install systemjs-webpack-interop plugin ,but it is no work;
![image](https://user-images.githubusercontent.com/22994293/69843946-c1962300-12a4-11ea-944f-32ba4a997c2f.png)

**Comment by yuanman0109** [comment]
![image](https://user-images.githubusercontent.com/22994293/69843970-ec807700-12a4-11ea-99bc-d63a686a7f79.png)
![image](https://user-images.githubusercontent.com/22994293/69843989-1a65bb80-12a5-11ea-89d1-aa782c298841.png)

this's my code and webpack config；

**Comment by joeldenning** [comment]
Could you explain what is not working?

**Comment by yuanman0109** [comment]
> Could you explain what is not working?

The console .log output system's import function is different from first console

**Comment by joeldenning** [comment]
Why is the `console.log` being executed twice? I only see it once inside of componentWillMount?

**Comment by yuanman0109** [comment]
> Why is the `console.log` being executed twice? I only see it once inside of componentWillMount?

because i'm use react-router@4 :
![image](https://user-images.githubusercontent.com/22994293/69844672-3dde3580-12a8-11ea-95a1-3b662626e562.png);
change router path link to 'page2'

**Comment by yuanman0109** [comment]
> Why is the `console.log` being executed twice? I only see it once inside of componentWillMount?
this is my error，my child project import systemjs too,so window.system already change to child system; make a error; thank you for your help
