### ISSUE TITLE
Error in case of load 2 global modules on row.

### ISSUE THREAD

**Issue by AndreyLuzinov** [systemjs/systemjs#2084]
You have code in systemjs/src/extras/global.js

function getGlobalProp () {
    ...
    if (lastProp !== lastGlobalProp)
      return lastProp;
  }

But if you load two global modules one by one then first module adds "window.default" property and second just override same "window.default" property.

This cause to (lastProp !== lastGlobalProp) return false and no actual result returned.

**Comment by AndreyLuzinov** [comment]
I have an additional question: Why can't we just reference "window.default" prop instead for diffing properties? For me it's not quite reliable solution. I had some cases when module.default was value "true" instead referencing to my default component in module.

**Comment by guybedford** [comment]
The expectation is that globals are legacy scripts that set their own name on the global object. Such as `window.$`.

Setting a generic global like `default` is not a good pattern for a portable module format, rather use a wrapped format like AMD or System.register.

**Comment by AndreyLuzinov** [comment]
Thanks for explanation.

**Comment by AndreyLuzinov** [comment]
However I trying to load UMD library modules generated with webpack and they work through window.[libraryName]. Can you explain why they don't register module name?

**Comment by joeldenning** [comment]
UMD bundles can work either as global variables or as AMD modules. If you don't want them to work as global variables, use the [AMD extra](https://github.com/systemjs/systemjs#extras)
