### ISSUE TITLE
module-types check does not account for hash and query params

### ISSUE THREAD

**Issue by LarsDenBakker** [systemjs/systemjs#2087]
The module types file extension check in https://github.com/systemjs/systemjs/blob/master/src/extras/module-types.js#L11 is done based on the full url, including hashes and query params. 

This creates problems for example when there are filenames in query parameters.

**Comment by joeldenning** [comment]
Thanks for the clear description on this. Would you be willing to submit a pull request that fixes this? Something like this, perhaps:

```js
const ext = url.slice(url.lastIndexOf('.'), url.indexOf('?') >= 0 ? url.indexOf('?') : url.length);
```

**Comment by LarsDenBakker** [comment]
I do have filenames in the query parameter, but I don't need systemjs to read them it just needs to read them. I can prepare a PR for this.

**Comment by joeldenning** [comment]
Released in https://github.com/systemjs/systemjs/releases/tag/6.1.9

**Comment by LarsDenBakker** [comment]
Thanks!
