### ISSUE TITLE
[question] why iframe.src and iframe.srcdoc has different result ?

### ISSUE THREAD

**Issue by shaoahs** [systemjs/systemjs#2089]
if use iframe.srcdoc has warning message  !!
```
Package target bare specifier did not resolve, resolving target '/dependence/pixi/pixi.min.4.8.8.js' for pixi
Package target bare specifier did not resolve, resolving target '/project/group/sample/debug/main.1.0.0.d6f1b1660fbdb1e5.js' for slot-sample
```

if use following raw data 
- iframe.srcdoc can't  run! 
- iframe.src is normal !
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>sample</title>
  <script type="systemjs-importmap">
    {
      "imports": {
        "pixi": "/dependence/pixi/pixi.min.4.8.8.js",
        "group/sample": "/project/group/sample/debug/main.1.0.0.d6f1b1660fbdb1e5.js"
      }
    }
  </script>
  <script type="systemjs-module" src="import:group/sample"></script>
</head>
<body id="sample">
<script src="/systemjs/6/system.js" crossorigin></script>
</body>
</html>
```
if use following raw data 
- iframe.srcdoc is normal ! 
- iframe.src is normal ! 
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>sample</title>
  <script type="systemjs-importmap">
    {
      "imports": {
        "pixi": "http://127.0.0.1:3000/dependence/pixi/pixi.min.4.8.8.js",
        "group/sample": "http://127.0.0.1:3000/project/group/sample/debug/main.1.0.0.d6f1b1660fbdb1e5.js"
      }
    }
  </script>
  <script type="systemjs-module" src="import:group/sample"></script>
</head>
<body id="sample">
<script src="/systemjs/6/system.js" crossorigin></script>
</body>
</html>
```

**Comment by joeldenning** [comment]
Iframes with `srcdoc` **have an unusual** [`window.location.href`](https://developer.mozilla.org/en-US/docs/Web/API/Location), where it is set to `about:srcdoc`. See [this codepen](https://codepen.io/joeldenning/pen/OJPzaZN?editors=1000) (check the browser console) which demonstrates this. In order for SystemJS to work, you must have a valid `baseUrl`, which is used for resolving urls.

See this code below from SystemJS - note how either a `<base>` element or `window.location.href` is needed for the systemjs baseUrl to work:

https://github.com/systemjs/systemjs/blob/958aa919aa8dabe6cdbbc8b7da7e9d5366ded4bd/src/common.js#L8-L21

The easiest way to solve your problem might be to insert a `<base>` element into your HTML page. That way, the unusual `location.href` won't matter.

```html
<html>
  <head>
    <base href="/">
  </head>
</html>
```

Alternatively, we could explore what the baseUrl should be in situations where location.href is "unusual"

**Comment by shaoahs** [comment]
thanks you very much !

**Comment by joeldenning** [comment]
Did that work for you? I'll close this issue since it appeared that your problem is now solved.
