### ISSUE TITLE
question: why not strict mode in compiled output?

### ISSUE THREAD

**Issue by frehner** [systemjs/systemjs#2098]
Not really an issue, more of a question:

is there a reason that strict mode is explicitly turned off in the compiled output? 

https://github.com/systemjs/systemjs/blob/master/rollup.config.js#L11

I just tested it with strict mode on, and all the tests continue to pass. So it doesn't appear (on the surface) to have to do with features you're building or anything. 

Anyway, just curious.

**Comment by joeldenning** [comment]
I’m not sure if it’s about saving the bytes for `”use strict”;` or if there were/are features of javascript that are being used that strict mode removes. I would be in favor of changing to strict mode if it doesn’t break things.

@guybedford do you have thoughts?

**Comment by guybedford** [comment]
Yes exactly those bytes are deemed unnecessary :)

**Comment by joeldenning** [comment]
@frehner could you explain how strict mode / not strict mode impacts things and how you even noticed?

**Comment by frehner** [comment]
>@frehner could you explain how strict mode / not strict mode impacts things and how you even noticed?

I came across it as I was debugging something else. In the end, it turned out that it was because my code wasn't being executed in strict mode.

However, I think there may still be some value in having systemjs itself execute in strict mode: when it's in non-strict mode (aka sloppy mode) there is the extremely small but still possible chance that there's an error in SystemJS. And since it's in sloppy mode, it would fail silently. 

Those types of situations would be extremely hard for users of SystemJS to debug properly.

**Comment by joeldenning** [comment]
I support turning on strict mode - I think a better error message (that only rarely shows) is worth the 10 bytes.

**Comment by guybedford** [comment]
SystemJS itself not running in strict mode doesn't affect code it evaluates executing in strict mode.

Whenever converting modules to SystemJS module format, the `'use strict` string should be present in the function wrapper for compatibility.

If that is missing, that is a bug in the transpiler outputting the System format.

**Comment by frehner** [comment]
From my testing, I think systemjs bring in strict mode does actually affect things.  But I could be wrong here. I even wrote a little bit about it here https://dev.to/frehner/exploring-javascript-s-strict-mode-8ip

The section on functions is probably most relevant to this discussion 

again, I could be wrong. But executing the code in those examples I believe shows how systemjs being in sloppy mode could affect things

**Comment by frehner** [comment]
updated the above comment now that I'm at a computer.

**Comment by frehner** [comment]
Just had a report that systemjs fails to work in older versions of chrome (v45) due to this. The error:

`Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by guybedford** [comment]
@frehner can you share your SystemJS module output here? It should look like - 

```js
System.register([..], function (...) {
  'use strict';
});
```

if the `'use strict'` is missing then you might get an error like this.

Alternatively if using AMD or globals you would also get an error like this.

**Comment by frehner** [comment]
It may have actually been an issue in single-spa itself. We just corrected it in this PR https://github.com/single-spa/single-spa/pull/507#event-3200299896

**Comment by joeldenning** [comment]
It's true that single-spa was not in strict mode, but that would not cause the error `Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`. Single-spa does not have any `let` or `const` variables in its output, due to the browserslist that has been set. See https://unpkg.com/single-spa@5.3.1/lib/umd/single-spa.min.js - there are no `let` or `const` variables in there.

I think that this is a problem with SystemJS - that's what the person reporting the issue indicated. SystemJS currently doesn't work in certain older versions of Chrome due to its use of `const` and `let` outside of strict mode. See https://unpkg.com/systemjs@6.2.6/dist/system.min.js

I think the fix is to enable strict mode, even though it incurs about 10 bytes to the bundles.

**Comment by guybedford** [comment]
Ahh I didn't realise `const` and `let` were an issue in Chrome 45 - I'd be happy to just go back to `var` everywhere to avoid this.

**Comment by guybedford** [comment]
(kind of odd to have IE11 support but not Chrome 45!)

**Comment by guybedford** [comment]
This was resolved in #2162.
