### ISSUE TITLE
Cannot set existing module with API

### ISSUE THREAD

**Issue by newmanw** [systemjs/systemjs#2100]
In version 0.21.x docs you could use the set method as follows:

> SystemJS.set(moduleName, Module)
> Type: Function
> 
> Sets a module into the registry directly and synchronously.
> 
> Typically used along with SystemJS.newModule to create a valid Module object:
> 
> SystemJS.set('custom-module', SystemJS.newModule({ prop: 'value' }));

The following works great in version 0.21.x
```
import * as angularCore from '@angular/core';
SystemJS.set('@angular/core', SystemJS.newModule(angularCore));
```

However it looks like System.newModule has since been removed.  According to the API documentation:

> System.set(id, module) -> Module
> Type: Function
> 
> Sets a module in the registry by ID.
> 
> System.set('http://site.com/normalized/module/name.js', {
>   exportedFunction: value
> });

The following does not seem to work in 6.x.  
```
import * as angularCore from '@angular/core';
System.set('@angular/core', angularCore);
```

If this is not a bug and I am using the new API incorrectly it would be helpful in the 6.x API docs to provide an example.

**Comment by joeldenning** [comment]
Can you clarify what isn't working for you? I have noticed that `System.set()` doesn't fail, but that you can't do `System.import()` to get that module unless you set the module as a URL.

See related issue https://github.com/systemjs/systemjs/issues/2062 which explains this more.

**Comment by newmanw** [comment]
@joeldenning yes, sorry about that.

`System.set('@angular/core', angularCore);
`

Works just fine, at least as far as not throwing an error.  However When I use System.import(url), systemjs tries to got out and find @angular/core. I am trying to prevent systemjs from looking externally for @angular/core.  In version .021.x  this worked.

**Comment by joeldenning** [comment]
Follow the instructions in this comment and the few after them - https://github.com/systemjs/systemjs/issues/2062#issuecomment-548556303.

```html
<script type="systemjs-importmap">
  {
    "@angular/core": "app:angular-core"
  }
</script>
<script>
  System.set('app:angular-core', angularCoreObj);
</script>
```

**Comment by newmanw** [comment]
@joeldenning thanks. I will give that a go.  Assuming that this means if you use System.set(...), you will always need to define an importmap?  If that is indeed true it would be help to add that to the System.API documentation for set().

**Comment by joeldenning** [comment]
First check if it works, then we can talk about documentation. I agree that System.set has gotten a lot less usable, but there are also some decent reasons for it. It used to allow for arbitrary module specifiers back in 0.21, but now it must be a full URL.

**Comment by newmanw** [comment]
@joeldenning no luck there either.  No errors, just @angluar/core used in the umd file loaded by systemjs is not resolved.  If it helps here is what angular's compiler generated:

```
(function (global, factory) {
	typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('@angular/core')) :
	typeof define === 'function' && define.amd ? define('image', ['exports', '@angular/core'], factory) :
	(global = global || self, factory(global.image = {}, global.ng.core));
}(this, (function (exports, core) { 'use strict';
```

With "core" being undefined.

**Comment by joeldenning** [comment]
I tried out the System.set approach locally and it worked for me with a different module besides angular core. Be sure to use the amd extra, and then it should work.

**Comment by newmanw** [comment]
@joeldenning thanks for all your help.  The amd extra did get me a bit farther.  At that point NgModule was undefined.  Adding the named-exports extra got me past that.  At this point there is an error being thrown by the angular JIT compiler that I don't fully understand.

Without knowing where to dig now, can you think of other difference between 0.21.x and 6.x that would be causing problems with how @angular is loading within SystemJS?

**Comment by newmanw** [comment]
@joeldenning, yup works. Thanks for all your help!

Docs are a bit lacking here, not sure I would have gone down this path w/o your guidance.  Even if there was just a guide to help migrate from 0.21.x to 2.x - 6.x as that seems to be where things diverged.  Lots of stuff surrounding using SystemJS for loading external JS modules at runtime for "plugin" type architectures, everything I found including very recent blogs and SO posts are still using 0.21.x

**Comment by joeldenning** [comment]
I agree that the docs could be improved overall. We have discussed creating a full documentation site that goes into more depth. It's pretty tricky since the variety of use cases and tools used in conjunction with SystemJS is really high. However, it would be good to have it.

In the meantime, I've created #2106 which clarifies in the documentation.
