### ISSUE TITLE
RxJS issues with SystemJS 6

### ISSUE THREAD

**Issue by frehner** [systemjs/systemjs#2103]
I've created an example repo to demonstrate https://gitlab.com/frehner/sys-rxjs

But here are the issues I've found and documented -- however, I think there's a chance that they all stem from a single issue that appears to be some sort of race condition in SystemJS. I'm not sure though.

## Errors received
There are several different errors that can be received, and none of them consistently. Sometimes both `finalize`s are called, sometimes only one is called, and sometimes there's an error and the code isn't even executed.

1. `TypeError: Object(...) is not a function`.
    * Can be found in Firefox v72 on MacOS, and more rarely in Chrome 80 on MacOS
    * Points to this line `Object(rxjs_operators__WEBPACK_IMPORTED_MODULE_1__["tap"])((x) => console.log('module', x)),`
1. Mod1 `finalize` is not called
    * Can be found in Firefox v72 on MacOS with `Disable Cache` **unchecked**
    * Can be found in Chrome 80 on MacOS with `Disable Cache` **checked**
    * Can be found in Safari 13.0.4 in both cache situations
1. `Uncaught (in promise) TypeError: rxjs.interval is not a function at (index):46`
    * Can be found in Chrome 80 on MacOS with `Disable Cache` **unchecked**

**Comment by frehner** [comment]
As a means of debugging, here's a version of that same repo but with RxJS built locally using webpack. Note that there are separate builds of RxJS and the Operators. https://gitlab.com/frehner/sys-rxjs/tree/with-rxjs-built

**Comment by joeldenning** [comment]
After some debugging of this, I've identified two separate issues. See #2107 for an explanation.

My vote is that we track the AMD `System.import() twice` scenario in this issue, and track the other problems in #2108. The `System.import() twice` scenario is fixed in #2104, and a good demonstration of the problem can be found at https://codesandbox.io/s/nifty-waterfall-rsifl.

**Comment by joeldenning** [comment]
Alternative - here's a published version of rxjs that is in System.register format https://github.com/esm-bundle/rxjs

**Comment by patrickmichalina** [comment]
@joeldenning wow! Thanks for publishing these, total lifesaver :)
