### ISSUE TITLE
Collision between named modules and import map

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2107]
When using the named-register extra, registering a module with the same name as a module in the import map results in some broken behaviors. Specifically, the module will get executed two times instead of one, which is problematic. The table below shows how this issue relates to #2104 and #2103:

Scenario | Module Type | Works in 6.1.9 | Works after #2104
------------ | ------------- | ----------- | ---------
System.import() twice | System.register | ❌ | ❌ 
System.import() twice | AMD | ❌ | ✅ 
System.import() once, as linked dep once | System.register | ❌ | ❌ 
System.import() once, as linked dep once | AMD | ❌ | ❌ 

Demo of problem:

See https://codesandbox.io/s/zealous-feynman-n5eqw. This demonstrates the `System.import() once, as linked dep once, with System.register format` scenario. Note in browser console how the `a` module is being executed twice.

**Comment by joeldenning** [comment]
When a module is registered manually with a name and is also within the import map, we need to decide how to handle that. 6.1.9 will use the module id from the import map for the first import, but the module id from the registerRegistry for the second import. This is what results in the behavior.

#### Option 1
**Import Map wins** - if a module is defined in both, the import map takes priority over the named register (registerRegistry). This is my preferred solution.

#### Option 2
**named register (registerRegistry) wins**. This is the current behavior. The problem is that sometimes you have to load the code from the url in the import map for the named register to even occur. #2103 is an example of that situation, and in that situation you get the weird behavior described in my original comment.

**Comment by guybedford** [comment]
Named System.register is deprecated.

Perhaps we should look at supporting named AMD without supporting named System register?

**Comment by guybedford** [comment]
Ideally I would move named System.register to a third party extension at this point.

**Comment by joeldenning** [comment]
Why is named system.register deprecated? I am not aware of any browser specs similar to named system register, but also wasn't aware that you consider it deprecated.

**Comment by guybedford** [comment]
It's exactly deprecated because there is nothing in the browser semantics that resembles it. We shouldn't be encouraging build patterns that are dead ends.

Then in build tools like Babel and TypeScript and Rollup I would want to ensure that naming the System.register format is never done by default to discourage the pattern entirely.

Do you think it can work to remove it as an extra, making the AMD extra independent?

**Comment by joeldenning** [comment]
Hmm I think a fair amount of people accidentally use named System register via named AMD or through build tools that add in the library name.

Aren't `System.set()`, `System.get()`, `System.has()`, and `System.entries()` all in the same situation, though, of no browser proposals / standards? Where do we draw the line on where to deviate from the standards vs stick to them?

**Comment by guybedford** [comment]
> Hmm I think a fair amount of people accidentally use named System register via named AMD or through build tools that add in the library name. From what I have seen, fewer people use it intentionally.

The only valid usage of named register is legacy apps that need AMD bundle support. For single modules with `define('asdf', ...)` they are effectively just almost-anonymous modules in AMD (is this why we had double execution as there is one one for the bundle and one for the name, or is that a separate thing?).

Even in those legacy app cases, the fact that `System.register('name')` is supported is then an anti pattern as users might think this is the correct way to use System.register, when in fact we do want this to throw typically still. Hence my suggestion re the separation.

For the registry operations, Node.js is currently looking to add some registry APIs itself likely quite similar ones. The use cases for the registry APIs are for mocking, testing, reloading, etc. These are not recommended as bundling or normal runtime features. They are for instrumentation.

**Comment by joeldenning** [comment]
> is this why we had double execution as there is one one for the bundle and one for the name, or is that a separate thing?

Yes, this is why there was double execution

> For the registry operations, Node.js is currently looking to add some registry APIs itself likely quite similar ones.

👍 cool

Overall, I think I'm okay with deprecating / removing named register from a future version of systemjs. The main thing I've seen it used for are the use cases that are also covered by System.set.
