### ISSUE TITLE
NodeJS support

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2109]
The single-spa community has some interest in supporting server rendering (https://github.com/single-spa/single-spa/issues/103). Much, but not all, of the single-spa community uses SystemJS, so getting systemjs working in node is becoming a priority for us.

First question to think about, I think, is whether to do fetch + eval on the server or not. Alternative would perhaps be something with cjs / esm that is in the node_modules. My concern with fetch + eval is security of executing arbitrary code from remote servers. But other options don't really seem to be systemjs at all.

@guybedford thoughts?

**Comment by guybedford** [comment]
If we get https://github.com/systemjs/systemjs/pull/2058 merged, the implementation here simplifies to just creating a custom fetch hook for Node.js I believe.

I think that may well be the missing piece to make maintaining this straightforward.

**Comment by guybedford** [comment]
(and yes I'm all for the feature, it's just been for lack of effort!)

**Comment by guybedford** [comment]
Note, this is a duplicate of https://github.com/systemjs/systemjs/issues/1873.

**Comment by joeldenning** [comment]
Oh I'll close in favor of #1873
