### ISSUE TITLE
SystemJs not working in IE11/W10 when Authorization is required

### ISSUE THREAD

**Issue by simon-sharp** [systemjs/systemjs#2110]
Hi

I have been experiencing difficulties to load my app in IE11 (but only in Windows 10, Windows 7 works fine) when loading a website that is secured by htaccess password protection. The page loads correctly but everything that is loaded by System.import('url/loader.js') results in a 404 Unauthorized Error. Reason is that in the HTTP Request Header does not send the Authorized Attribute.

Are there more People experiencing this behaviour and is any workaround known?

I thank you very much for your answer.

Best regards,
Simon

**Comment by joeldenning** [comment]
Why does the authorization header only impact Windows 10? And why only IE11. That is unusual.

The issue you've described is similar to the one described in https://github.com/systemjs/systemjs/issues/1863. SystemJS loads code by default via `<script>` element, which means you cannot control the headers very easily. Also see related https://github.com/systemjs/systemjs/pull/2058 where new hooks are being proposed that would faciliate customizing how the HTTP request is sent.

**Comment by simon-sharp** [comment]
I would assume that it is a IE11 Bug or Security feature they have built in for some reason. I asked primarily to see if someone already has a solution for the issue.

What I will do now is to go and check if some CSP settings could solve the issue.

**Comment by joeldenning** [comment]
Sounds good - hope you find it. I am closing this since it doesn't appear to be an issue with SystemJS itself.
