### ISSUE TITLE
The result of import multiple amd module  is uncertain

### ISSUE THREAD

**Issue by FreezeSoul** [systemjs/systemjs#2111]
When update to 6.1.10, i got a problem,but the 6.1.9 is ok. 

I import more than one amd module,but the result is uncertain. 

When i refresh the following page,the console output moudles: jquery,jquery,jquery,or other. Evertime is not same. 

I want to get moudles : jquery,lodash,sockjs,stomp .

```
<!DOCTYPE html>
<html lang="en-US">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Basic Webpack SystemJS Example</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="systemjs-importmap">
    {
  	"imports": {
		"jquery": "./library/jquery/jquery.min.js",
		"lodash": "./library/lodash/lodash.min.js",
		"sockjs": "./library/sockjs/sockjs.min.js",
		"stompjs": "./library/stompjs/stomp.min.js"   
	  }
	}
  </script>
  <script src="dist/system.js"></script>
  <script src="dist/extras/amd.js"></script>
  <script src="dist/extras/use-default.js"></script>
  <script src="dist/extras/module-types.js"></script>
  <script src="dist/extras/named-exports.js"></script>
  <script src="dist/extras/named-register.js"></script>
</head>
<body>
	<script>
		function importsMore(argumentList){
			let promiseList = [];
			for (let i = 0; i < argumentList.length; i++) {
			let arg = argumentList[i];
			promiseList.push(
			  new Promise(resolve => {
				System.import(arg).then((o) => {
				  console.log(o);
				  resolve(o);
				});
			  })
			);
			}
			return Promise.all(promiseList);
		}
		
		importsMore(["jquery", "lodash", "sockjs", "stompjs"]).then((libs) => {
			console.log(libs)
      	      	});
		// when i import by the following code , it got same module sometimes
		/*
		System.import("jquery").then((o) => {
		  console.log(o);
		});
		System.import("lodash").then((o) => {
		  console.log(o);
		});
		System.import("sockjs").then((o) => {
		  console.log(o);
		});
		System.import("stompjs").then((o) => {
		  console.log(o);
		});
		*/
	</script>
</body>
</html>
```

Thanks your working.

**Comment by joeldenning** [comment]
Perhaps the most helpful thing would be to create a Code Sandbox that shows the problem - [here is a code sandbox template](https://codesandbox.io/s/frosty-swanson-jx68v) you can start with. Can you show the problem there as a starting place for me to debug this?

**Comment by FreezeSoul** [comment]
You can try on : https://codesandbox.io/s/relaxed-hill-ozorh

**Comment by joeldenning** [comment]
I am able to see the issue - will take a look at this later today. Thank you for putting together the code sandbox to demonstrate this

**Comment by joeldenning** [comment]
I've discovered that this is being caused by the recent changes to the named-register extra. See https://codesandbox.io/s/serverless-fast-rltnf, https://github.com/systemjs/systemjs/pull/2108, and https://github.com/systemjs/systemjs/pull/2105

**Comment by joeldenning** [comment]
After further debugging, it is definitely related to https://github.com/systemjs/systemjs/pull/2104. It's a problem with the AMD extra, but the problem only surfaces when you're also using the named-register extra.

**Comment by FreezeSoul** [comment]
Thank you for your working ,waiting for new release!

**Comment by joeldenning** [comment]
I've created https://github.com/systemjs/systemjs/pull/2114 to fix this. If you want to try it out in your full application, you can copy/paste the amd and named-register extra into your project and script tag the new versions instead of the 6.1.10 versions to test it out.

**Comment by joeldenning** [comment]
Released in https://github.com/systemjs/systemjs/releases/tag/6.2.0
