### ISSUE TITLE
cdn modules loading queue

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2112]
v 5.0

Just found floating error with direct-vuex package: https://github.com/paleo/direct-vuex/issues/32 which depends on vuex module.

Q: how SystemJS resolves node modules from importmap if they have dependencies?
How to make no doubt about app loading without errors?

**Comment by joeldenning** [comment]
> how SystemJS resolves node modules from importmap if they have dependencies?

Modules indicate they have dependencies by calling `System.register(['dep1'], ['dep2'], ...)` or by calling `define(['dep1', 'dep2'], ...)`.

CommonJS modules (cjs) are not supported by systemjs.

>  How to make no doubt about app loading without errors?

Could you explain what you mean by this?

**Comment by viT-1** [comment]
> CommonJS modules (cjs) are not supported by systemjs.

In issues I say nothing about CommonJS, only [about importmap](https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md).

> Could you explain what you mean by this?
direct-vuex has vuex dependency, how can I be sure about proper module loading?

**Comment by joeldenning** [comment]
> In issues I say nothing about CommonJS, only about importmap.

You mentioned node_modules, which often have CommonJS modules in them. I brought up CommonJS for that reason

> direct-vuex has vuex dependency, how can I be sure about proper module loading?

Place `vuex` into the import map

**Comment by viT-1** [comment]
> Place vuex into the import map
It's a pitty that you think like that. Of course [I did it](https://github.com/viT-1/direct-vuex-systemjs/blob/master/src/importmap.system.json)! =(

**Comment by joeldenning** [comment]
"How can I be sure about proper module loading" is not specific enough for me to understand what you mean. What does "being sure" mean?

I am closing this issue since you gave my comment a thumbs down and are unable to explain the issue.

**Comment by viT-1** [comment]
All explained in first comment & related =(

**Comment by joeldenning** [comment]
I have read your original comment many times. I do not understand it. Please explain it more clearly

**Comment by viT-1** [comment]
> It is floating error... After page reloading issue is gone.
When importmap modules cached all is ok, but if direct-vuex is loaded first I have an error about undefined Vuex.

**Comment by joeldenning** [comment]
> When importmap modules cached all is ok, but if direct-vuex is loaded first I have an error about undefined Vuex.

That is helpful information that was not provided in the original comment. Thanks for a bit more detail.

To help me diagnose the problem, please provide a code sandbox so that I can take a look at this. Template repo at https://codesandbox.io/s/throbbing-mountain-bep07

**Comment by viT-1** [comment]
I [have an repo](url) where is ok with loading direct-vuex & vuex through importmap.
But in another bigger project have that issue with module loading.

**Comment by joeldenning** [comment]
As I commented [here](https://github.com/systemjs/systemjs/issues/2113#issuecomment-580773215), I already pulled that repo and did not see any problems with it.

Please provide a code sandbox like I instructed.

**Comment by viT-1** [comment]
@joeldenning, please reopen an issue

**Comment by viT-1** [comment]
@guybedford Please reopen this issue.

**Comment by joeldenning** [comment]
As [explained here](https://github.com/systemjs/systemjs/issues/2113#issuecomment-580794189), I am closing and locking these issues.
