### ISSUE TITLE
5.0: Cannot read property 'length' of undefined when setup has named-exports script

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2113]
Some umd modules have not default export (for example I need to use [debounce dorator](https://cdn.jsdelivr.net/npm/debounce-decorator-ts@1.0.4/dist/debounce-decorator-ts.umd.js)).
My previous setup for default import was ok (has no errors):
```
/systemjs@5.0.0/dist/system.js
/systemjs@5.0.0/dist/extras/named-register.min.js
~/js/importmap.system.json
~/js/app-bundle.system.js // from tsc with tsconfig "module": "system" & outFile
~/js/app-init.system.js
```

Now I want to add extra named-exports.min.js after named-register:
```
/systemjs@5.0.0/dist/extras/named-register.min.js
/systemjs@5.0.0/dist/extras/named-exports.min.js
~/js/importmap.system.json
```

[importmap.system.json](https://github.com/viT-1/direct-vuex-systemjs/blob/master/src/importmap.system.json) (for example)

catch error:
```
system.js:287 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at system.js:287
```

What am I doing wrong?

**Comment by viT-1** [comment]
Related https://github.com/paleo/direct-vuex/issues/14#issuecomment-568918493

**Comment by joeldenning** [comment]
I cloned [this repo](https://github.com/viT-1/direct-vuex-systemjs/blob/master/src/importmap.system.json) and added `named-exports.min.js` to the HTML file. Then I ran `npm run deploy` and `npm run postdeploy`. I did not get the error that was reported.

Could you please provide a minimal example showing this in Code Sandbox?

Here is a template sandbox: https://codesandbox.io/s/throbbing-mountain-bep07

**Comment by viT-1** [comment]
Strange. Yes this issue about another bigger repo.

**Comment by viT-1** [comment]
@joeldenning  You need not only add script but import named export in [L4](https://github.com/viT-1/direct-vuex-systemjs/blob/aa789daabe5b0e7d3480383e031437c50e559af0/src/VueApp.ts#L4)
`{ createDirectStore } from 'direct-vuex'`
and change L16

**Comment by joeldenning** [comment]
Since you have been rather rude to me in https://github.com/systemjs/systemjs/issues/2112, I am not going to prioritize looking at this.

If anyone else wants to jump in on this issue, or if you are able to find the problem, feel free to pull request any changes.

**Comment by viT-1** [comment]
:astonished:

**Comment by viT-1** [comment]
It's a pitty to get such response about issues misunderstanding.

**Comment by joeldenning** [comment]
I maintain a few dozen open source projects and interact with over a hundred open source developers every month. Even when there is a language barrier, respectful communication can occur. I am unpaid for my maintenance of systemjs and am a skilled developer - I do not owe you my time. It is reasonable for me to expect you to provide a code example through code sandbox.

I am closing and locking this issue due to this and several issues over the last few months where you have not been able to engage in issues in a respectful way.
