### ISSUE TITLE
define with systemjs get unexpected problems

### ISSUE THREAD

**Issue by FreezeSoul** [systemjs/systemjs#2115]
systemjs version 6.2.0
I found several problems with current version of systemjs work with define.
1. define a module make import failed，the demo is here [problem1](https://bdiy1.csb.app/problem1-with-systemjs6.2.0.html). I also compare with 6.1.9 is ok : [here](https://bdiy1.csb.app/problem1-with-systemjs6.1.9.html)
2. define a module invoke twice, the demo is here [problem2](https://bdiy1.csb.app/problem2-with-systemjs6.2.0.html),The 6.1.9 version is here : [here](https://bdiy1.csb.app/problem2-with-systemjs6.1.9.html)

The codesandbox is here : https://codesandbox.io/s/magical-snow-bdiy1

It looks like there are some problems with define work on current version

I don't know if it was my fault, but i think there is some thing wrong.

**Comment by joeldenning** [comment]
Taking a look at this now

**Comment by joeldenning** [comment]
I have found a fix for Problem 1 -- see my fork of your code sandbox at https://codesandbox.io/s/frosty-feynman-nruri

**Comment by joeldenning** [comment]
The same change also fixes Problem 2. I will submit a PR with the fix.

**Comment by joeldenning** [comment]
Fixed in https://github.com/systemjs/systemjs/pull/2116

**Comment by FreezeSoul** [comment]
I will try on my proj,thk. @joeldenning

**Comment by joeldenning** [comment]
Released in https://github.com/systemjs/systemjs/releases/tag/6.2.1
