### ISSUE TITLE
AMD module detection reg ex does not work for correct AMD syntax (define is not a function)

### ISSUE THREAD

**Issue by dprokop** [systemjs/systemjs#2117]
Hi, I've encountered an issue with SystemJS 0.20.19 having problems with resolving AMD module. 

Looked into your code a bit and it seems like the `amdRegEx` (https://github.com/systemjs/systemjs/blob/0.21/src/instantiate.js#L432) does not work for correct AMD  code. 

Here's the example of the failing regex- module is not detected as AMD when loaded, define is not a function is thrown:
https://regexr.com/4tl9s

The problem is that the module function is wrapped in `()` which is not respected by the reg ex. The code snippet is minimised by Terser.

Here is the same code that's formatted and the reg ex works as expected:
https://regexr.com/4tlcd

**Comment by joeldenning** [comment]
Want to send in a PR for this? I actively maintain systemjs@6, and used to use systemjs@0.21. However, I normally don't dive far into the systemjs@0.21 code for fixes as much anymore.
