### ISSUE TITLE
Expose resolved import map for use in extras

### ISSUE THREAD

**Issue by joeljeske** [systemjs/systemjs#2120]
It would be helpful if the resolved final import map was available for use in user-provided extras. I would like to build on top of the System resolution process and need access to the import map to do so. Likely this would need to be behind a promise since the resolution is async.

**Comment by joeldenning** [comment]
The [resolve hook](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#resolveid-parenturl---string) is exposed as a way to modify url resolution. A lot of extra behavior can be implemented with it without directly exposing the import map.

What specific behavior would your extra implement? Is it possible to do with the resolve hook?

**Comment by joeljeske** [comment]
My plan was to leverage the existing resolution and composition of import-maps and provide additional data such as fallbacks that did not make it into the initial spec. After reading more of your source however, the code is pretty explicit about what how it will merge import maps. 

It seems like I might have to implement my own similar pipeline for resolving and composing metadata maps to be used in the resolve/instantiate hooks.

**Comment by joeldenning** [comment]
Hmm yeah fallback resolution would be a cool thing to add - the instantiate hook is another hook to look into that could be useful for that. Ultimately, though, you are right that a feature like that couldn't be implemented without full control over import map resolution.
