### ISSUE TITLE
Provide ES module output

### ISSUE THREAD

**Issue by Jack-Works** [systemjs/systemjs#2123]
I want to add ES module support in https://github.com/DimensionDev/webextension-polyfill and I need to use SystemJS as an imported module instead of a global name.

```ts
import { System } from 'systemjs'

// My code
class ExtensionFileLoader extends System {
// hooks overwrited
}
loadExtension(new ExtensionFileLoader)

window.System // should be undefined
```

**Comment by guybedford** [comment]
Unfortunately `window.System` needs to be defined for the module format itself to work since `System.register` assumes `window.System.register` exists.

SystemJS should support being imported as a module fine through `import 'systemjs'` just not with any exports.

**Comment by Jack-Works** [comment]
Now I have to import systemjs then delete it from window... That's not so good

**Comment by joeldenning** [comment]
Like Guy said, deleting systemjs from the window will cause all [`System.register`](https://github.com/systemjs/systemjs/blob/master/docs/system-register.md) modules to fail, as they assume that `System` is available as a global variable. SystemJS is the only global variable an application would need, but it does need to be a global variable.

**Comment by Jack-Works** [comment]
Yes, but I'm pre-processing all SystemJS module by wrapping them from

```js
System.register(...)
```

to

```js
(function () {
    arguments[0].register(...)
})
```

And pass my non-global System object in.

**Comment by joeldenning** [comment]
Since you're already deviating from the documented/ecnouraged workflow, I think it's reasonable to expect you to add one more line of code (`delete window.System`) to support that workflow.
