### ISSUE TITLE
System.delete does not delete entry from registerRegistry

### ISSUE THREAD

**Issue by k-j-kim** [systemjs/systemjs#2124]
Hi all,

I'm curious if this is expected behavior:

```
    it('Calling System.delete cleans registerRegistry', async function () {
        loader.instantiate = x => {
            loader.register('myModule', [], _export => ({ execute() { _export('y', 42) } }));
            return loader.getRegister();
        };

        await loader.import('myModule');

        assert.equal(loader.get('myModule').y, 42);

        loader.delete('myModule');

        assert.equal(await loader.get('myModule'), undefined); // passes
        assert.equal(loader.registerRegistry['myModule'], undefined); // fails
    });
```

**Comment by guybedford** [comment]
The act of a module being loaded from the register registry should delete the entry in the register registry as it uses it. That it isn't seems like a bug to me yes, and rather than patching the delete function, a PR to the named register extension to delete the entries as it uses them would be great.

**Comment by k-j-kim** [comment]
@guybedford quick question,

[even though `registerRegistry` is used in instantiating](https://github.com/systemjs/systemjs/blob/dc9a1dad19d29c1252b322d6d15c543901dd1dbe/src/extras/named-register.js#L54-L55), and the module is added to the registry, it is [still used in subsequent calls to resolve](https://github.com/systemjs/systemjs/blob/dc9a1dad19d29c1252b322d6d15c543901dd1dbe/src/extras/named-register.js#L43-L49).

So if we delete the entry on instantiate, subsequent resolve calls will fail on import. Am I missing something here?

**Comment by guybedford** [comment]
Yeah that's a problem... I'm open to suggestions then.

It's worth noting that named registration is considered a deprecated feature.

**Comment by k-j-kim** [comment]
I've made a small PR here: https://github.com/systemjs/systemjs/pull/2125. Open to alternative solutions as well.

> It's worth noting that named registration is considered a deprecated feature.

What is the reason for this? Is it because it is not in the native spec?

Also, should it be removed from the doc like the other deprecated features (e.g., https://github.com/systemjs/systemjs/pull/2052)?
