### ISSUE TITLE
ERROR: TS2306 ... is not a module for type definitions SystemJS 6.1 

### ISSUE THREAD

**Issue by OZ79** [systemjs/systemjs#2127]
Hi,
I would like to use SystemJS 6.1.0 with TypeScript. Type definitions for SystemJS 6.1 was added.  
In my .tsx: `import * as System from "systemjs";`
Error happened during compilation:
```
ERROR in ... .tsx
Module not found: Error: Can't resolve 'systemjs' in 
...
ERROR in ... .tsx(5,25)
      TS2306: File .../node_modules/@types/systemjs/index.d.ts' is not a module.
ℹ ｢wdm｣: Failed to compile.
```

Seems like lack of this one or something like that in node_modules/@types/systemjs/index.d.ts:
```
export = System;
export as namespace System;
```

**Comment by guybedford** [comment]
Thanks for posting, does that simple correction you included fix the issue?

If you'd like to make that PR to type types that would be great.

**Comment by OZ79** [comment]
If I add:
```
export = System;
export as namespace System;
```
Unfortunately there is still error:
```
ERROR in ... .tsx
Module not found: Error: Can't resolve 'systemjs' in ...
ℹ ｢wdm｣: Failed to compile.
```

**Comment by joeldenning** [comment]
> In my .tsx: `import * as System from "systemjs";`

SystemJS@6 does not yet support use within NodeJS (See https://github.com/systemjs/systemjs/issues/1873). The typescript definitions in DefinitelyTyped create a **global variable** called `System` - they do not allow for usage as an imported module since that is not yet supported.

Closing this because I don't think there's a bug here. If I'm missing or if there's more to discuss, feel free to comment further or reopen.

**Comment by stevenvachon** [comment]
You can't `import 'systemjs'` because there is neither an _index.js_ file in the project root nor a `main` in the published _package.json_ file.

**Comment by joeldenning** [comment]
@stevenvachon that is correct. But will soon change with #2150, which adds a server-side implementation of systemjs

**Comment by stevenvachon** [comment]
@joeldenning I'm not sure how that will solve TypeScript issues for browser builds.

**Comment by joeldenning** [comment]
It won't - was just sharing informationally that soon systemjs will support nodejs usage, and we'll need to update the types to account for that.
