### ISSUE TITLE
AMD modules cannot return falsy values

### ISSUE THREAD

**Issue by lpomerleau** [systemjs/systemjs#2129]
Hi systemjs team,

If I create AMD modules such as these:
```
define([], function () {
  return false;
});

define([], function () {
  return '';
});
```
when they're imported, the default export is an empty object instead of `false` or `''`.

The values are thrown out here:
https://github.com/systemjs/systemjs/blob/6caaee592172954bbf65bd8490212286f6e38754/src/extras/amd.js#L58

I'll submit a PR with a fix for your approval: #2130

**Comment by joeldenning** [comment]
Fix released in https://github.com/systemjs/systemjs/releases/tag/6.2.5
