### ISSUE TITLE
How i'can upgrade systemjs@0.21.6 to 6.2.5

### ISSUE THREAD

**Issue by zornic84** [systemjs/systemjs#2137]
Hi Guys,

i can't find a solution or example for an Visual Studio ASP-MVC 5 with angular 7/8/9 with systemjs 2-6.
I hope you can help me. The example on 

here is my current solution:

`<script src="~/node_modules/core-js/client/shim.min.js"></script>
    <script src="~/node_modules/zone.js/dist/zone.js"></script>
    <script src="~/node_modules/systemjs/dist/system.src.js"></script>
    <script src="~/CientApp/systemjs.config.js"></script>
    <script>
        System.import('CientApp/main.js').catch(function (err) { console.error(err); });
    </script>`

systemjs.config.js:

`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.appVersion = '1.0.0';
    System.config({
        transpiler: 'typescript',
        typescriptOptions: {
            "target": "es5",
            "module": "commonjs",
            "moduleResolution": "node",
            "sourceMap": true,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true
        },
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'CientApp/app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js?v=' + System.appVersion,
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js?v=' + System.appVersion,
            '@angular/common/http': 'npm:@angular/common/bundles/common-http.umd.js?v=' + System.appVersion,
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js?v=' + System.appVersion,
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js?v=' + System.appVersion,
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js?v=' + System.appVersion,
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js?v=' + System.appVersion,
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js?v=' + System.appVersion,
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js?v=' + System.appVersion,

            '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js?v=' + System.appVersion,
            '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js?v=' + System.appVersion,
            '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js?v=' + System.appVersion,

            '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js?v=' + System.appVersion,
            '@angular/cdk/a11y': 'npm:/@angular/cdk/bundles/cdk-a11y.umd.js?v=' + System.appVersion,
            '@angular/cdk/bidi': 'npm:/@angular/cdk/bundles/cdk-bidi.umd.js?v=' + System.appVersion,
            '@angular/cdk/observers': 'npm:/@angular/cdk/bundles/cdk-observers.umd.js?v=' + System.appVersion,
            '@angular/cdk/overlay': 'npm:/@angular/cdk/bundles/cdk-overlay.umd.js?v=' + System.appVersion,
            '@angular/cdk/portal': 'npm:/@angular/cdk/bundles/cdk-portal.umd.js?v=' + System.appVersion,
            '@angular/cdk/scrolling': 'npm:/@angular/cdk/bundles/cdk-scrolling.umd.js?v=' + System.appVersion,
            '@angular/cdk/platform': 'npm:/@angular/cdk/bundles/cdk-platform.umd.js?v=' + System.appVersion,
            '@angular/cdk/keycodes': 'npm:/@angular/cdk/bundles/cdk-keycodes.umd.js?v=' + System.appVersion,
            '@angular/cdk/coercion': 'npm:/@angular/cdk/bundles/cdk-coercion.umd.js?v=' + System.appVersion,
            '@angular/cdk/collections': 'npm:/@angular/cdk/bundles/cdk-collections.umd.js?v=' + System.appVersion,
            '@angular/cdk/rxjs': 'npm:/@angular/cdk/bundles/cdk-rxjs.umd.js?v=' + System.appVersion,
            '@angular/cdk/table': 'npm:/@angular/cdk/bundles/cdk-table.umd.js?v=' + System.appVersion,

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'CientApp/systemjs-angular-loader.js'
                    }
                }
            },
            'rxjs': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/ajax': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/operators': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/testing': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
            'rxjs/webSocket': { main: 'index', defaultExtension: 'js?v=' + System.appVersion },
        }
    });
})(this);`

**Comment by joeldenning** [comment]
It looks like you're doing the following?

1. In-browser Typescript compilation
2. In-browser CommonJS modules
3. Custom versioning with `v` query param
4. UMD modules for core angular

^ Is that correct?

> 1. In-browser Typescript compilation

No systemjs@6 plugin exists for typescript, but in-browser compilation can be solved the following ways:

a) [System.shouldFetch](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#shouldfetchurl---boolean) and [System.fetch](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#fetchurl---promise) hooks. You can implement your own fetch that runs typescript.
b) (Alternative) [System.transform](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#transformurl-source---promise) hook. Run typescript inside of it.

> 2. In-browser CommonJS modules

See https://github.com/systemjs/systemjs/issues/1854

> 3. Custom versioning with `v` query param

Create an [import map](https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md) with the mapping of specifier to urls

> 4. UMD modules for core angular

Use the AMD extra. You also might want the named-exports and use-default extras for better interop. See https://github.com/systemjs/systemjs#extras

I imagine it'll be fairly hard to upgrade. Let us know if you have any questions.

**Comment by zornic84** [comment]
I've created an import map, but, angular will not loaded. Here my Code:

index.html:
`<script src="~/node_modules/systemjs/dist/system.js"></script>
    <script src="~/node_modules/systemjs/dist/extras/amd.min.js"></script>
    <script src="~/node_modules/systemjs/dist/extras/named-exports.js"></script>
    <script src="~/node_modules/systemjs/dist/extras/named-register.min.js"></script>
    <script>System.import('./CientApp/main.js')</script>
    <script type="systemjs-importmap" src="~/CientApp/bundle.json"></script>`

bundle.json:
`{
    "imports": {

        "app": "CientApp/app",

        "moment": "/node_modules/moment/src/moment.js",
        "moment/": "/node_modules/moment/src/",

        "@angular/core": "/node_modules/@angular/core/bundles/core.umd.js",
        "@angular/common": "/node_modules/@angular/common/bundles/common.umd.js",
        "@angular/common/http": "/node_modules/@angular/common/bundles/common-http.umd.js",
        "@angular/compiler": "/node_modules/@angular/compiler/bundles/compiler.umd.js",
        "@angular/platform-browser": "/node_modules/@angular/platform-browser/bundles/platform-browser.umd.js",
        "@angular/platform-browser-dynamic": "/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js",
        "@angular/http": "/node_modules/@angular/http/bundles/http.umd.js",
        "@angular/router": "/node_modules/@angular/router/bundles/router.umd.js",
        "@angular/forms": "/node_modules/@angular/forms/bundles/forms.umd.js",

        "@angular/animations": "/node_modules/@angular/animations/bundles/animations.umd.js",
        "@angular/animations/browser": "/node_modules/@angular/animations/bundles/animations-browser.umd.js",
        "@angular/platform-browser/animations": "/node_modules/@angular/platform-browser/bundles/platform-browser-animations.umd.js",

        "@angular/cdk": "/node_modules/@angular/cdk/bundles/cdk.umd.js",
        "@angular/cdk/a11y": "/node_modules//@angular/cdk/bundles/cdk-a11y.umd.js",
        "@angular/cdk/bidi": "/node_modules//@angular/cdk/bundles/cdk-bidi.umd.js",
        "@angular/cdk/observers": "/node_modules//@angular/cdk/bundles/cdk-observers.umd.js",
        "@angular/cdk/overlay": "/node_modules//@angular/cdk/bundles/cdk-overlay.umd.js",
        "@angular/cdk/portal": "/node_modules//@angular/cdk/bundles/cdk-portal.umd.js",
        "@angular/cdk/scrolling": "/node_modules//@angular/cdk/bundles/cdk-scrolling.umd.js",
        "@angular/cdk/platform": "/node_modules//@angular/cdk/bundles/cdk-platform.umd.js",
        "@angular/cdk/keycodes": "/node_modules//@angular/cdk/bundles/cdk-keycodes.umd.js",
        "@angular/cdk/coercion": "/node_modules//@angular/cdk/bundles/cdk-coercion.umd.js",
        "@angular/cdk/collections": "/node_modules//@angular/cdk/bundles/cdk-collections.umd.js",
        "@angular/cdk/rxjs": "/node_modules//@angular/cdk/bundles/cdk-rxjs.umd.js",
        "@angular/cdk/table": "/node_modules//@angular/cdk/bundles/cdk-table.umd.js",


        "rxjs": "/node_modules/rxjs",
        "angular-in-memory-web-api": "/node_modules/angular-in-memory-web-api/bundles/in-memory-web-api.umd.js",

        "primeng-lts": "/node_modules/primeng-lts"
    }
}`

I am currently getting the following errors when I start my project.:

> Uncaught ReferenceError: exports is not defined at main.js:2
> Uncaught (in promise) ReferenceError: exports is not defined at main.js:2

**Comment by joeldenning** [comment]
That's not enough information diagnose the problem. Even if enough information was provided, I will not be able to help you diagnose each error along the way. At first glance it looks like you might be trying to load some CommonJS modules, which are not currently supported as explained above.

I have outlined the process for upgrading to the latest systemjs above, so I'm closing this issue. Feel free to comment further. Perhaps other community members can jump in on this one to provide in depth debugging help.

**Comment by zornic84** [comment]
Hello joeldenning,

I created a small test program and uploaded it to my OneDrive. I hope you can help me like this. I find the examples very poorly documented,

Link: https://1drv.ms/u/s!AnUmEVMpERKrn48-w9Mwul4lVFRxvw?e=6L2J5W
