### ISSUE TITLE
6.2.5 Named register problem is still on FireFox

### ISSUE THREAD

**Issue by shrinktofit** [systemjs/systemjs#2138]
![image](https://user-images.githubusercontent.com/28807867/75949968-d78a3400-5ee2-11ea-95de-3b8384c1a317.png)

The call sequence is:
- Register some named registers, through `System.register(name, ...)`;
- Do `System.import('cc')` where `'cc'` is a module resolved from import map;

Result:
- When instantiating `'cc'`, the `getRegister()` returns the first named register, instead of what `'cc'` ifself should be.

The problem can only be reproduced in Firefox(71.0). It's unstable reproduced. I reproduce it through many time page-refresh. I guess it's because `setTimeout` here:
https://github.com/systemjs/systemjs/blob/10fae8c5801289bd4a4ecdc5be3d6b6c070f403d/src/extras/named-register.js#L34-L36

Code:
[web-desktop.zip](https://github.com/systemjs/systemjs/files/4291090/web-desktop.zip)

How to run:
```bash
> http-server .
```

**Comment by joeldenning** [comment]
I have done >5 fixes for amd + named register. It is not an easy problem to solve. See the following, related, links:

- https://github.com/systemjs/systemjs/issues/2139
- https://github.com/systemjs/systemjs/pull/2121
- https://github.com/systemjs/systemjs/pull/2116
- https://github.com/systemjs/systemjs/pull/2114
- https://github.com/systemjs/systemjs/pull/2108
- https://github.com/systemjs/systemjs/pull/2104

I think that to properly fix the issue we'd have to refactor the amd extra substantially such that it no longer returns the first named amd module from each file, but instead returns the last amd module in each file. If we change that behavior and do a significant refactor of the AMD module, I think it might solve the issue. If you have other ideas on how to fix it, I'm open to it.

**Comment by joeldenning** [comment]
I've created https://github.com/systemjs/systemjs/pull/2140 as a work-in-progress pull request to see if that might solve the problem.

**Comment by joeldenning** [comment]
Fix implemented in #2144 and released in https://github.com/systemjs/systemjs/releases/tag/6.2.6. Let us know if you still run into issues and we can revive #2140 as an alternative implementation/fix.
