### ISSUE TITLE
I have a plugin is React Flags Select usage

### ISSUE THREAD

**Issue by Sirajul-haq** [systemjs/systemjs#2143]
flags select box initial loading country flag didn't show . When I select one region, then the flag showed.

![Screenshot_2020-03-12 React App](https://user-images.githubusercontent.com/58596461/76595068-c82d6b00-6520-11ea-8496-607737b253e4.png)
```
import ReactFlagsSelect from 'react-flags-select';
import 'react-flags-select/scss/react-flags-select.scss';

const LocalSelect = () => {

return ( 

 <ReactFlagsSelect
  searchable={true}
  searchPlaceholder="Search"
  className="menu-flags"
  defaultCountry="US"
  showSelectedLabel={true} />     

 )
}
```

**Comment by joeldenning** [comment]
Hi @Sirajul-haq, this issue appears to be in the wrong github repository. If you are having an issue with react-flags-select, you can create an issue at https://github.com/ekwonye-richard/react-flags-select
