### ISSUE TITLE
`ns` prototype is null, but that breaks some things

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2147]
https://github.com/systemjs/systemjs/blob/0f1161d86e6d84642d2d94b3f686f0028959297b/src/system-core.js#L83

Some projects assume that their dependencies have the full object prototype available to them. For example, the popular [react-table](https://github.com/tannerlinsley/react-table) project does this (see [line 7 of react-table.development.js](https://unpkg.com/browse/react-table@7.0.0/dist/react-table.development.js))

This throws an Error when the dependency (in this case `react`) does not have the Object.prototype methods on it.

Is there any reason not to change that code to be `ns = {}`, so that the prototype is Object.prototype?

@guybedford thoughts?

**Comment by guybedford** [comment]
React isn't an ES module though so shouldn't be a namespace - rather it should be used via `import React from 'react'` as its own default export.

Is this because you are using the named exports extension?

It is very important not to change this - namespaces have an empty prototype by the ECMAScript specification.

**Comment by joeldenning** [comment]
Yes, I discovered this when talking with someone setting up single-spa. They are using the named-exports extra because that's the easiest way to be able to do `import { useState } from 'react';`

**Comment by guybedford** [comment]
I would suggest getting React table to fix this as a bug in that project then - that they are detecting a namespace using a technique that is not spec valid for namespaces.

**Comment by bartoszgolebiowski** [comment]
I had a serious problem with that
This is my dependency which I am using.
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react'], factory) :
  (global = global || self, factory(global.ReactQuery = {}, global.React));
}(this, (function (exports, React) { 'use strict';

  React = React && React.hasOwnProperty('default') ? React['default'] : React
```
The last line couse exception
```js
React variable is Module and does not have hasOwnProperty function.
```

This is caused because React variable is the module and does not have hasOwnProperty method

![image](https://user-images.githubusercontent.com/39523638/76617978-bac7af00-6527-11ea-9754-4fd9b46ba615.png)

**Comment by guybedford** [comment]
The problem is this bug in Rollup - https://github.com/rollup/rollup/pull/3420 which was released in 1.32.1 - when React table uses that build it will resolve the issue.

I would suggest posting an issue to React table to get a new build out with that release asap.

**Comment by joeldenning** [comment]
Good catch - I had just verified that rollup does this correctly now with [this repl example](http://rollupjs.org/repl/?version=2.1.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMFJlYWN0JTIwZnJvbSUyMCdyZWFjdCclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJ1bWQlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==). It looks react-table is on 1.32.1 - https://github.com/tannerlinsley/react-table/blob/master/yarn.lock#L6720. I'll create a pull request to upgrade this for them.

**Comment by joeldenning** [comment]
I have created https://github.com/tannerlinsley/react-table/pull/2021 to resolve this issue in react-table.
