### ISSUE TITLE
equivalent of inline module in HTML? Consider "System.execute" to register and execute immediately?

### ISSUE THREAD

**Issue by csr632** [systemjs/systemjs#2148]
I want to inline the first module in my html, to reduce loading time. So instead of this:
```html
<script src="system.js"></script>
<script>System.import('/js/main.js')</script>
```
I want to do something equivalent to this:
```html
<script type="module">
  // This is main.js module
  import {addTextToBody} from './utils.mjs';
  addTextToBody('Modules are pretty cool.');
</script>
```

> Update: Clarify: In this example, when I said `./utils.mjs`, I actually want to say `shared-utils`, which is an external dependency(matained and deployed by other team).

How to achieve this with systemjs module?

> Update: my proposol is in this comment: https://github.com/systemjs/systemjs/issues/2148#issuecomment-605415551

**Comment by joeldenning** [comment]
Could you help me understand exactly what performance you're wanting to optimize?

In your second example, the `utils.mjs` file has to be downloaded before the inline module is executed, which is pretty similar to having to download `/js/main.js` in the systemjs example. I don't see a performance gain in the second example.

Here are a few code samples that show different options within systemjs:

#### dynamic import
```html
<script>
  System.import('utils.js').then(utils => {
    utils.addTextToBody('Modules are pretty cool.');
  })
</script>
```

#### SystemJS equivalent of static import

```html
<script>
  // This has no perf benefit over the dynamic import, but I'm showing it for completeness
  // This solution also requires the named-register extension
  System.register('some-name', ['utils.js'], function (_export, _context) {
    let utils;
    return {
      setters: [m => utils = m],
      execute() {
        utils.addTextToBody('Modules are pretty cool.');
      }
    }
  })
  System.import('some-name');
</script>
```

#### `type="systemjs-module"`
```html
<!-- Only use this approach if you're not using any extras. Otherwise you'll run into the issue described in https://github.com/systemjs/systemjs/issues/2040 -->
<!-- This simply calls `System.import()`, but does so a bit earlier because it happens inside of the systemjs code itself instead of afterwards -->
<script src="/js/main.js" type="systemjs-module"></script>
<script src"system.js"></script>
```

**Comment by joeldenning** [comment]
Like I said in my comment above, I am not sure what performance gain you're hoping to see. However, here are a few performance tips that can benefit initial page load:

1. [Preload the scripts you know you're going to need](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content)
2. Use [depcache](https://github.com/systemjs/systemjs/pull/2134) to avoid "dependency waterfall" of network requests. This allows you to specify a module's dependencies upfront so that they are downloaded simultaneously instead of having to first download the module to discover what its dependencies are. This feature is not yet merged into systemjs, but if it interests you, you can voice your support in the PR

**Comment by csr632** [comment]
In this example:
```html
<script src="system.js"></script>
<script>System.import('/js/main.js')</script>
```
There will be 4 sequential request: load html -> load system.js -> load systemjs module `/js/main.js` -> load systemjs module `utils.js`
before my 'main.js' get executed.

But I want to inline `system.js` and `/js/main.js` into HTML so that 
there will be only 2 sequential request: load html(execute system.js, register systemjs module `/js/main.js`) -> load systemjs module `utils.js`
before my 'main.js' get executed.

Inline `system.js` is simple because it is already umd bundle. But I don't know how to inline the systemjs format `/js/main.js`.

**Comment by csr632** [comment]
Thanks for your advice! Your "dynamic import" solution can inline the `/js/main.js` into HTML but It is hard to be done by automatic tool.
The "named-register" solution seems doable. I can compile my main module into a systemjs module with named. And render this HTML template:
```html
<script>
  <%  main.js build output  %>
  System.import('some-name');
</script>
```

**Comment by csr632** [comment]
The "named-register" solution is not very ideal because I **have to give a name to every entry systemjs module I want to execute**.

I hope systemjs can provide a method like "System.execute". It is just like "System.register" but will trigger the execution without have to call System.import('module-url').

So that rollup can generate:
```js
System.execute(['shared-utils'], function (_export, _context) {
    let utils;
    return {
      setters: [m => utils = m],
      execute() {
        utils.addTextToBody('Modules are pretty cool.');
      }
    }
  })
```
I can embed System.execute module into HTML:
```html
<script>
  <%  system.js umd bundle  %>
  <%  main.js System.execute module  %>
  //  no need to call System.import('main-module'); manually!
</script>
```
And the resulte HTML will be **perfectly equivalent to native esModule** in browser: 
```html
<script type="module">
  import {addTextToBody} from 'shared-utils';
  addTextToBody('Modules are pretty cool.');
</script>
```

**Comment by joeldenning** [comment]
If implemented, System.execute would not have any performance benefit over `System.import('shared-utils').then(() => {})`. I think your best option is just the system import.

**Comment by csr632** [comment]
@joeldenning I am trying to avoid hand-writing "systemJS API" here. I always use esModule syntax in my source code and use rollup to build a systemjs bundle.

I just want my systemjs bundle can be inlined into HTML like ["iife" or "esm" output format](https://rollupjs.org/guide/en/#outputformat). 
I expect systemJs to provide exact same semantics with esModule. And rollup should be able to output both format with exact same semantics. So that I can switch to native esModule in the future(when the browser support is ready), without need to change any source code.

**Comment by joeldenning** [comment]
Rollup, Babel, typescript, and webpack do not support outputting to System.execute format (as far as I know). I don’t think adding System.execute would help you avoid doing some handwritten code. You can still compile ES modules with rollup to work with System.import().then by outputting to iife format and declaring shared-modules as an external.

**Comment by csr632** [comment]
[Webpack already support "amd-require"](https://webpack.js.org/configuration/output/#module-definition-systems). I hope this idea can be transplanted into the systemjs world!

> libraryTarget: 'amd-require' - This packages your output with an immediately-executed AMD require(dependencies, factory) wrapper.
> The 'amd-require' target allows for the use of AMD dependencies without needing a separate later invocation. As with the 'amd' target, this depends on the appropriate require function being available in the environment in which the webpack output is loaded.

**Comment by joeldenning** [comment]
I'm open to adding a new API if it adds value, but don't see what value `System.execute()` would have over `System.import().then()`

@guybedford could you comment here? Did previous versions of SystemJS have an API for inline execution of modules?

**Comment by guybedford** [comment]
The SystemJS module format cannot be inlined into HTML - note that HTML inlining is generally an anti-pattern from a long-term caching perspective. One depth latency to get to the HTML assets is fine, and the standard for mos loading. Any more than one to two depths of latency is not fine and should be solved, and hence why we have depcache.

**Comment by guybedford** [comment]
The only way to do this would be with the define extra, something like:

```html
<script src="system.js"></script>
<script src="named-define-extra.js"></script>
<script>
// System.register call, with named definition
System.register('app', [...deps], function () {
});
System.import('app');
</script>
```

**Comment by tmsns** [comment]
I had a similar issue, but with an external script. The script was an app, compiled to the systemjs format with Rollup. The idea here was to minimize the number of extra script tags, as other script tags were already on the page.

I started with:
```html
<script src="/s.min.js"></script>
<script src="/app.system.js"></script>
```

Of course, this didn't work, as nothing is imported.
My second try was to do an actual import instead:
```html
<script src="/s.min.js"></script>
<script>System.import("/app.system.js")</script>
```
This worked, but had two drawbacks:
- extra code is needed to bootstrap the bundle (´System.import´)
- the execution of the bundle code is delayed by the extra download and the module emulation

So, I continued by adding a script tag that would directly download the app:
```html
<script src="/s.min.js"></script>
<script src="/app.system.js"></script>
<script>System.import("/app.system.js")</script>
```
This worked as well, but downloaded the app two times, and added even more code.

After investigating the pluggable extra's, I came up with the following one: https://github.com/tmsns/systemjs/blob/feat/auto-import/src/extras/auto-import.js

This meant I could just do the following:
```html
<script src="/s.min.js"></script>
<script src="/auto-import.js"></script>
<script src="/app.system.js"></script>
```
and even bundle these 3 together in one file (eg.using Rollups iife), reducing the number of downloads to 1.
```html
<script src="/bundle.iife.js"></script>
```

I will send in the code as a PR. It might help other people as well. 😃

**Comment by guybedford** [comment]
The auto import feature as suggested by @tmsns has now been shipped in 6.4.0.

This allows eg:

```js
<script src="system-dep.js"></script>
<script src="system-module.js"></script>
```

where the module is immediately registered and imported, so it can work with the browser preloader.

Note that in the above where both modules are System.register modules, it is a requirement to ensure the script tags are in dependency post-order (dependencies first!), otherwise it will alter the execution ordering.

**Comment by dmail** [comment]
I think there is use case where it's important to execute js without an http request:
- js is inlined in the HTML file and is responsible to render the very first thing use sees and load my application

In that case it's crucial to keep the js inline, otherwise time to first frame is delayed by one http request. With a slow network it means user sees a blank page until http request resolves.

What do you think?

**Comment by dmail** [comment]
I can do a pull request
