### ISSUE TITLE
Is System.meta part of ES6 spec, or an addition?

### ISSUE THREAD

**Issue by trusktr** [systemjs/systemjs#215]
?

**Comment by trusktr** [comment]
@guybedford Is the `System` API going to be part of the API available in browsers when ES6 Modules finally land in browsers?

**Comment by trusktr** [comment]
@guybedford Is there a link to where the `System.import` API and friends are defined? An official spec?

**Comment by guybedford** [comment]
https://github.com/whatwg/loader
