### ISSUE TITLE
Interested by automatic report about files size into pull requests ?

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#2153]
Hello systemjs team :).

I have noticed it's important for your project to watch dist/* file sizes. In occured quite often in pull request. This comment from @joeldenning gave me an idea:

![image](https://user-images.githubusercontent.com/443639/78329973-33e48000-7583-11ea-90ad-9406c6687527.png)

I made a tool for this purpose, it comments pull request like this:

![image](https://user-images.githubusercontent.com/443639/78330171-a6556000-7583-11ea-8f81-1ddb3d2bd40a.png)

If you are interested let me know and I will open a pull request to integrate it into systemjs. 
The project is open source and can be seen at https://github.com/jsenv/jsenv-github-pull-request-filesize-impact.

**Comment by joeldenning** [comment]
Hi @dmail - yes that would be easier. Would gladly accept a PR for it.

**Comment by dmail** [comment]
Cool will do that soon then.

**Comment by dmail** [comment]
Done :)
