### ISSUE TITLE
content-type (mime type) application/javascript or text/javascript ?

### ISSUE THREAD

**Issue by shaoahs** [systemjs/systemjs#2176]
- SystemJS Version: 
- Which library are you using?
  - [X] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

## MDN Common MIME types

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types
use text/javascript

### systemJS  Invalid content-type header

https://github.com/systemjs/systemjs/blob/master/docs/errors.md#4
use application/javascript

### web server MIME type config

 use text/javascript  mjs js;
or
use  application/javascript  mjs js;

**Comment by joeldenning** [comment]
Hi @shaoahs, you are right that `text/javascript` is a valid mime type. SystemJS already supports `text/javascript`, although the documentation for the error code doesn't indicate that. See code below:

https://github.com/systemjs/systemjs/blob/953b0581969ddb37ad0e798c512a16ed2721563f/src/extras/module-types.js#L29

I have created #2177 to fix the documentation. For the error you are experiencing, can you confirm with the content-type response header is for the module that you're loading? If it's `text/javascript` and not working, that would be a problem. But the code seems to indicate that `text/javascript` is fine.

Also, what version of systemjs are you using? 6.3.0 had some issues where it would link to the wrong error codes.

**Comment by shaoahs** [comment]
use systemjs 6.2.6 ! is fine !
because some document say this (text/javascript) , some document say that (application/javascript)
let me confuse !

**Comment by joeldenning** [comment]
👍 thanks for reporting this
