### ISSUE TITLE
React16.9‘s project import  systemjs after The console prints waring 

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2178]
- SystemJS Version: 6.3.1
- Which library are you using?
  - [Y ] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [Y ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?
no
### Question
my app import react16.9 and systemjs，but my console log waring，if don't import systemjs ，no 
 happen ；look the picture：
![image](https://user-images.githubusercontent.com/22994293/79314102-e7f6eb00-7f33-11ea-975a-fa093bac87d3.png)
![image](https://user-images.githubusercontent.com/22994293/79314166-fd6c1500-7f33-11ea-9be1-4f7e1f8ceb5e.png)

**Comment by joeldenning** [comment]
Hi @yuanman0109 - we'd need further information to diagnose this. The error message suggests that you are spreading the global `System` object as props to a JSX element (`<img {...window.System} />`. The contents of your App component are important here for diagnosing further, as they likely show the problem.

**Comment by yuanman0109** [comment]
> Hi @yuanman0109 - we'd need further information to diagnose this. The error message suggests that you are spreading the global `System` object as props to a JSX element (`<img {...window.System} />`. The contents of your App component are important here for diagnosing further, as they likely show the problem.

thanks。I have solved the problem，I found a hint in the document；if i add the webpack rule，no waring now；I solved the problem, but I don't know why。my webpack version is ^4.42.1，Cause of ’import’ and system.import conflict？
![image](https://user-images.githubusercontent.com/22994293/79410342-acf7c480-7fd2-11ea-8ca4-7d19a80d4747.png)

**Comment by joeldenning** [comment]
Ah yes, you must set that rule in webpack so that `System.import()` is executed in the browser instead of interpreted at build-time by webpack to be a code split.

More details at https://github.com/systemjs/systemjs#compatibility-with-webpack
