### ISSUE TITLE
v6.3.1 have different performance with v6.2.6

### ISSUE THREAD

**Issue by SallyOne** [systemjs/systemjs#2183]
### Demonstration
In our company project, use system and webpack to lazyload angularjs module,such as:
```
  resolve: {
                loadModule: async ($q, $ocLazyLoad) => {
                    const deferred = $q.defer();
                    const module = await System.import(/* webpackChunkName:"dashboardChunk" */ './dashboard.module');
                    $ocLazyLoad.load(module.default);
                    deferred.resolve(module);
                    return deferred.promise;
                },
            },
```
v6.2.6 working use systemjs,but v6.3.1,report error: SyntaxError: Unexpected token 'import',I don't know reason and not very good to reproduce the problem, please have a look

**Comment by SallyOne** [comment]
resolved by locked version (6.2.6)

**Comment by SallyOne** [comment]
> ### Demonstration
> In our company project, use system and webpack to lazyload angularjs module,such as:
> 
> ```
>   resolve: {
>                 loadModule: async ($q, $ocLazyLoad) => {
>                     const deferred = $q.defer();
>                     const module = await System.import(/* webpackChunkName:"dashboardChunk" */ './dashboard.module');
>                     $ocLazyLoad.load(module.default);
>                     deferred.resolve(module);
>                     return deferred.promise;
>                 },
>             },
> ```
> 
> v6.2.6 working use systemjs,but v6.3.1,report error: SyntaxError: Unexpected token 'import',I don't know reason and not very good to reproduce the problem, please have a look

**Comment by joeldenning** [comment]
Hi @SallyOne - are you sure you are using SystemJS to load that chunk? `webpackChunkName` makes it look like it is Webpack, not SystemJS, that is loading the dashboard module.

Starting with Webpack 2, `System.import()` is interpreted as a **webpack codesplit** instead of a SystemJS module. This has since been deprecated, but it is still enabled by default. What this means is that the `System.import()` is compiled to a `__wepback_require__` by the time it hits the browser, and SystemJS is not involved at all when the file is actually loaded.

You can read more about this at https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import - search that page for `System.import` and you'll see how it referenced how webpack uses System.import as a code split.

You can turn off this behavior in webpack by setting parser.system to false in the webpack config. That is described [in these docs](https://github.com/systemjs/systemjs#compatibility-with-webpack):

```js
{
  module: {
    rules: [
      { parser: { system: false } }
    ]
  }
}
```

**Comment by joeldenning** [comment]
I do not know why changing your SystemJS version would have any impact on this - perhaps there is different code in your project that is loading SystemJS modules without it being a webpack code split?

**Comment by SallyOne** [comment]
```
import(/* webpackChunkName: "chunk1" */'@/components/chunk1.js')
```
only use webpack to lazyload is not working(https://github.com/webpack/webpack/issues/4861),

many people have this problem,such as:
![image](https://user-images.githubusercontent.com/12112235/80664897-93727480-8aca-11ea-9437-f6b7b3215c4a.png)

so i use system and webpack to lazyload module and js plugin,I sure that work fine,yesterday I started to report errors after upgrading yarn.lock dependencies，after locating the problem, it was found that the upgrade of systemjs to 6.3.1 caused an error,6.2.6 can work fine,
![image](https://user-images.githubusercontent.com/12112235/80665263-90c44f00-8acb-11ea-9b20-373a7f8eefa9.png)

**Comment by joeldenning** [comment]
Does your webpack config have the following?

```js
{
  module: {
    rules: [
      { parser: { system: false } }
    ]
  }
}
```

If not, then `System.import()` **does not use SystemJS**.

**Comment by SallyOne** [comment]
project have no this config, after I  add this config to webpack,I find lazyload not working,If it is lazy loading done by webpack, why is the version of system.js affecting the result of lazy loading, I am very confused

**Comment by joeldenning** [comment]
Are you  doing `import 'systemjs'` anywhere in your code?

If so, systemjs@6.3.0 introduced new fields to the package.json, which would impact webpack resolution of the file.

6.2.0:

https://github.com/systemjs/systemjs/blob/0f1161d86e6d84642d2d94b3f686f0028959297b/package.json#L3-L4

6.3.0:

https://github.com/systemjs/systemjs/blob/c977894618c83928c0b843bf998f97bf2e0ffb1c/package.json#L3-L12

**Comment by SallyOne** [comment]
I ’m sorry to reply so late because of the Labor Day holiday，you are right, this issue can close

**Comment by joeldenning** [comment]
Did you figure out why 6.3.0 had different behavior? If the package.json `exports` field is breaking things for people, we'd want to fix it.
