### ISSUE TITLE
not found in '../libs/system'

### ISSUE THREAD

**Issue by kukuyu** [systemjs/systemjs#2188]
I use systemjs like this:

`import * as SystemJS from '../libs/system';
`
but when i use webpack build  this index.js file,  it's waring:
![image](https://user-images.githubusercontent.com/16571529/81464268-8e13d900-91f2-11ea-8c72-8dc2c42e13c2.png)
There's no problem with the path： ‘../libs/system’。

**Comment by joeldenning** [comment]
Hi @kukuyu, good question. We generally discourage bundling systemjs with webpack, and instead encourage loading via script tag. If you'd like to bundle systemjs, you should note that it does not expose any ESM or CJS exports from its main file and so you should not do `import * as SystemJS from '../libs/system'`. Instead, try doing `import 'systemjs/dist/system.min.js';`.

The reason for this is that SystemJS creates the `window.System` global variable which is needed for loading System.register modules. That variable must be global to facilitate script loading.

**Comment by kukuyu** [comment]
> Hi @kukuyu, good question. We generally discourage bundling systemjs with webpack, and instead encourage loading via script tag. If you'd like to bundle systemjs, you should note that it does not expose any ESM or CJS exports from its main file and so you should not do `import * as SystemJS from '../libs/system'`. Instead, try doing `import 'systemjs/dist/system.min.js';`.
> 
> The reason for this is that SystemJS creates the `window.System` global variable which is needed for loading System.register modules. That variable must be global to facilitate script loading.

thank you !! get it ！
