### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by kukuyu** [systemjs/systemjs#2190]
when i use system :

![image](https://user-images.githubusercontent.com/16571529/81815246-57c0bb80-955c-11ea-8e2a-a6958ee9f9b6.png)

**Comment by joeldenning** [comment]
This error is described and documented in https://github.com/systemjs/systemjs/blob/master/docs/errors.md#3. What it means is that a network request to download a javascript module returned HTML instead of javascript. This commonly occurs when you’re running a webpack dev server that defaults to an html file for all unknown URLs, and usually means that the URL for the javascript file is incorrect. To diagnose, check the browser devtools network tab to see the http response body of the module. Until it returns javascript, things won’t work.

**Comment by kukuyu** [comment]
> This error is described and documented in https://github.com/systemjs/systemjs/blob/master/docs/errors.md#3. What it means is that a network request to download a javascript module returned HTML instead of javascript. This commonly occurs when you’re running a webpack dev server that defaults to an html file for all unknown URLs, and usually means that the URL for the javascript file is incorrect. To diagnose, check the browser devtools network tab to see the http response body of the module. Until it returns javascript, things won’t work.

yes, you are right!
I use the system to load the final package file. I used webpack-externals to exclude the package file, React and React-dom, and then there will be more network requests for react and react-dom, and the returned is html. How can I deal with this situation?
webpack.config.js:
`externals: {
        'react': 'React',
        'react-dom': 'ReactDOM'
    },`

**Comment by kukuyu** [comment]
I try like this:
`<script type="systemjs-importmap">
			{
			  "imports": {
				"react": "https://cdn.jsdelivr.net/npm/react@16.12.0/umd/react.production.min.js",
				"react-dom":"https://cdn.jsdelivr.net/npm/react-dom@16.12.0/umd/react-dom.production.min.js",
				"main": "./main.js"
			  }
			}
		</script>
		<script>
			System.import('main')
               </sccript>`
but failed:

![image](https://user-images.githubusercontent.com/16571529/81887040-e1aa6c00-95d0-11ea-8019-6d88b0cd19ad.png)

**Comment by joeldenning** [comment]
The values in your webpack external object should match the names in your import map:

```js
externals: { 'react': 'react', 'react-dom': 'react-dom' }
```

Additionally, I noticed in your second screenshot that the network request is for `main` instead of `main.js`. What version of systemjs are you using? You must use systemjs@>=2 in order for import maps to work.

**Comment by kukuyu** [comment]
> The values in your webpack external object should match the names in your import map:
> 
> ```js
> externals: { 'react': 'react', 'react-dom': 'react-dom' }
> ```
> 
> Additionally, I noticed in your second screenshot that the network request is for `main` instead of `main.js`. What version of systemjs are you using? You must use systemjs@>=2 in order for import maps to work. The latest version is systemjs@6.3.1

yes,    I use systemjs version is  SystemJS v0.20. ，  
When I upgrade the version to the latest SystemJS 6.3.1, I will get an error：
`Unhandled Promise rejection: Cannot find module '/baseComponent/store.js' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module '/baseComponent/store.js'
    at src lazy namespace object:5
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.invokeTask (zone.js:423)
    at Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)
    at ZoneTask.invokeTask [as invoke] (zone.js:502)
    at invokeTask (zone.js:1744)
    at HTMLDocument.globalZoneAwareCallback (zone.js:1770) Error: Cannot find module '/baseComponent/store.js'
    at http://localhost:9000/main.js:5928:11
    at ZoneDelegate.invoke (http://localhost:9000/main.js:2600:160)
    at Zone.run (http://localhost:9000/main.js:2327:37)
    at http://localhost:9000/main.js:3200:28
    at ZoneDelegate.invokeTask (http://localhost:9000/main.js:2631:173)
    at Zone.runTask (http://localhost:9000/main.js:2384:39)
    at drainMicroTaskQueue (http://localhost:9000/main.js:2837:25)
    at ZoneTask.invokeTask [as invoke] (http://localhost:9000/main.js:2720:13)
    at invokeTask (http://localhost:9000/main.js:4249:12)
    at HTMLDocument.globalZoneAwareCallback (http://localhost:9000/main.js:4280:11)`

**Comment by kukuyu** [comment]
> The values in your webpack external object should match the names in your import map:
> 
> ```js
> externals: { 'react': 'react', 'react-dom': 'react-dom' }
> ```
> 
> Additionally, I noticed in your second screenshot that the network request is for `main` instead of `main.js`. What version of systemjs are you using? You must use systemjs@>=2 in order for import maps to work. The latest version is systemjs@6.3.1

Yes, the version I am using is SystemJS v0.20.19 which can be loaded normally. If you upgrade to SystemJS 6.3.1, the following error will be reported：

![image](https://user-images.githubusercontent.com/16571529/82031228-2535d080-96cc-11ea-8124-c06c9d713502.png)

**Comment by joeldenning** [comment]
systemjs@0.20 does not have support for import maps. It's preferred to use systemjs@6 when possible. The error seems to indicate that the url for the base component store is incorrect.

**Comment by kukuyu** [comment]
The url address of the store is correct: store.js, which can be accessed separately in the browser .It can be loaded correctly with SystemJS v0.20.19, but after upgrading to SystemJS 6.3.1, an error is reported.

**Comment by joeldenning** [comment]
We would need more detail here to diagnose this. Here are the next steps to debug:

1. What is the full URL for `/baseComponent/store.js` that you are able to load in the browser?
2. What is the full URL that systemjs@6 tries to load

**Comment by kukuyu** [comment]
![image](https://user-images.githubusercontent.com/16571529/82277262-ff554800-99b9-11ea-8602-9271e3fd11e0.png)

**Comment by kukuyu** [comment]
I use webpack to start a local service: http: // localhost: 9000/#/app1/, and then in this application, use systemjs to load another application (also a local service：http://localhost:9006/).
Therefore, the address of the store in the code is: store: '/ baseComponent / store.js', and the address loaded in the browser is:

![image](https://user-images.githubusercontent.com/16571529/82277346-2c095f80-99ba-11ea-87e2-cf68efa93608.png)

Made a proxy with proxy in wepback：
![image](https://user-images.githubusercontent.com/16571529/82277435-6b37b080-99ba-11ea-85d6-2458a58e8e58.png)

So the actual loaded address should be：

![image](https://user-images.githubusercontent.com/16571529/82277493-93271400-99ba-11ea-9b90-8f7c13819665.png)

![image](https://user-images.githubusercontent.com/16571529/82277551-bb167780-99ba-11ea-9b2d-d9015a607aad.png)

**Comment by joeldenning** [comment]
You likely don't need a proxy for this. Here are a couple alternatives:

Option 1:
Set the webpack public path [on the fly](https://webpack.js.org/guides/public-path/#on-the-fly) and then use the public path to calculate the URL for the module.

```js
// Set the public path dynamically
__webpack_public_path__ = 'http://localhost:9006/';

// Load relative to the public path
System.import(__webpack_public_path__ + 'baseComponent/store.js';
```

Here's a project that helps you accomplish that: https://github.com/joeldenning/systemjs-webpack-interop

Option 2

Use webpack code splits to load chunks within the webpack project, instead of systemjs. To do that, you set the webpack public path dynamically and then use webpack's `import()` function to do code splits.

**Comment by kukuyu** [comment]
I use proxy to solve cross-domain access problems. Option 1: Still unable to access across domains，I tried to upload the resource to the CDN, and the request still reported an error. 

`zone.js:682 Unhandled Promise rejection: Cannot find module 'https://om.gtimg.cn/om/omadmin/xone/app1/store.js' ; Zone: <root> ; Task: Promise.then ; Value: Error: Cannot find module 'https://om.gtimg.cn/om/omadmin/xone/app1/store.js'
    at src lazy namespace object:5
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:150)
    at zone.js:889
    at ZoneDelegate.invokeTask (zone.js:423)
    at Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601) Error: Cannot find module 'https://om.gtimg.cn/om/omadmin/xone/app1/store.js'
    at http://localhost:9000/main.js:5928:11
    at ZoneDelegate.invoke (http://localhost:9000/main.js:2600:160)
    at Zone.run (http://localhost:9000/main.js:2327:37)
    at http://localhost:9000/main.js:3200:28
    at ZoneDelegate.invokeTask (http://localhost:9000/main.js:2631:173)
    at Zone.runTask (http://localhost:9000/main.js:2384:39)
    at drainMicroTaskQueue (http://localhost:9000/main.js:2837:25)`

**Comment by joeldenning** [comment]
This issue has deviated from the original question and I've given options to solve your current solution. I am closing this issue since there's no more action I can take. Feel free to comment further if you'd like, but we might be at the point where it's up to you.

**Comment by kukuyu** [comment]
> This issue has deviated from the original question and I've given options to solve your current problem. I am closing this issue since there's no more action I can take. Feel free to comment further if you'd like, but we might be at the point where it's up to you.

thank you！
