### ISSUE TITLE
Application 'xxx' died in status LOADING_SOURCE_CODE: Unable to resolve bare specifier 'React'

### ISSUE THREAD

**Issue by ooooevan** [systemjs/systemjs#2195]
- SystemJS Version: 6.3.2
- Which library are you using?
  - [x] SystemJS
- Which extras are you using?
  - [x] AMD extra
  - [x] Named Exports
### Question
I use systemjs in single-spa,all my micro app is umd library,and they work fine.

I use `system.js`,`amd.js`,`name-exports.js`to load micro app,if i remove each of them, i can't load the micro app.i am confused why i need `amd.js`, my micro app is umd mode.

When i externals `react`,`react-dom` in webpack,it doesn't work.
```js
// config-overrides.js
config.output.libraryTarget= 'umd',
config.externals = {
    ...config.externals,
    react: 'React',
    'react-dom': 'ReactDOM',
};
```
I got this error
![image](https://user-images.githubusercontent.com/25603236/83133225-1fe97480-a115-11ea-887a-63d367e44d28.png)

I can't find `React` variable in window. if i remove `amd.js`,it can't load each of micro app,but i can find `React` variable
![image](https://user-images.githubusercontent.com/25603236/83133074-e6b10480-a114-11ea-825e-fad339def305.png)

thank you very much

**Comment by ooooevan** [comment]
@joeldenning it works, thank you

**Comment by Hallelujah1** [comment]
<script type="systemjs-importmap" src="https://storage.googleapis.com/react.microfrontends.app/importmap.json"></script>
  <script type="systemjs-importmap">
    {
        "imports": {
          "single-spa": "https://cdn.jsdelivr.net/npm/single-spa@5.9.0/lib/system/single-spa.min.js",
          "react": "https://cdn.jsdelivr.net/npm/react@16.13.1/umd/react.production.min.js",
          "react-dom": "https://cdn.jsdelivr.net/npm/react-dom@16.13.1/umd/react-dom.production.min.js",
          "react-router-dom": "https://cdn.jsdelivr.net/npm/react-router-dom@5.2.0/umd/react-router-dom.min.js",
          "@alifd/next":"https://alifd.alicdn.com/npm/@alifd/next/1.22.26/next.min.js",
          "moment": "https://momentjs.com/downloads/moment.js",
        }
      }
  </script>

halo guys，Is still an error，"@types/systemjs": "^6.1.0","single-spa": "^5.8.2"。why? 

application '@study/todos' died in status LOADING_SOURCE_CODE: Unable to resolve bare specifier 'react-router-dom' from http://localhost:9002/study-todos.js

**Comment by joeldenning** [comment]
Please provide a code sandbox (you can use [this template](https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html)), and create a new issue for any new issues.
