### ISSUE TITLE
import extra amd.js,console log global variable( ex:  echart, katex, jquery) is undefined. 

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2201]
Hi @ooooevan, good question. This error is explained in detail in [these docs](https://github.com/systemjs/systemjs/blob/master/docs/errors.md#8). What it means is that `React` is not in your [import map](https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md).

To fix this, you need to add React to an import map on the page:

```html
<script type="systemjs-importmap">
  {
    "imports": {
      "react": "https://cdn.jsdelivr.net/npm/react@16.13.1/umd/react.production.min.js",
      "react-dom": "https://cdn.jsdelivr.net/npm/react-dom@16.13.1/umd/react-dom.production.min.js"
    }
  }
</script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/amd.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/named-exports.min.js"></script>
```

Also, you should not rename `react` to `React` inside of your webpack externals. `react` is the name of the module, whereas `React` is the name of the global variable when used as a global var. With SystemJS, you won't be using the React global variable but instead the systemjs module for react.

```js
// config-overrides.js
config.output.libraryTarget= 'umd'
config.externals = {
    ...config.externals,
    react: 'react',
    'react-dom': 'react-dom',
};
```

Using the amd + named-exports extra is a good way of loading react. It will prevent React from creating a global variable, but will register it as an AMD module that SystemJS can understand. You can see an example of this working at https://github.com/react-microfrontends/root-config/blob/master/src/index.ejs

_Originally posted by @joeldenning in https://github.com/systemjs/systemjs/issues/2195#issuecomment-635420934_

hi @joeldenning , i have the same problem，if i use System.import('echarts') do it this way is no problem, but my child app both use import echarts from 'echarts', don't in global variable，how to solve this problem at not use System.import?

**Comment by yuanman0109** [comment]
children app use import echarts from 'echarts' all the way, if change to system.import('echart') is difficult， because they  belong to different projects，The team will crazy；

**Comment by joeldenning** [comment]
Hi @yuanman0109, good question. You can use echarts from SystemJS without changing how your team does the import:

```js
import echarts from 'echarts';
```

The way to do so is to mark `echarts` as a [webpack external](https://webpack.js.org/configuration/externals/#root) in your webpack config, and then change the [libraryTarget](https://webpack.js.org/configuration/output/#outputlibrarytarget) to `"system"`.

Then add echarts to your import map and add the amd and named-exports extras.

Here is a [code sandbox](https://codesandbox.io/s/quirky-kare-ln53z?file=/index.html) showing that echarts can be successfully loaded by SystemJS. You can use the `import echarts from 'echarts'` syntax if you configure webpack properly.

**Comment by yuanman0109** [comment]
> Hi @yuanman0109, good question. You can use echarts from SystemJS without changing how your team does the import:
> 
> ```js
> import echarts from 'echarts';
> ```
> 
> The way to do so is to mark `echarts` as a [webpack external](https://webpack.js.org/configuration/externals/#root) in your webpack config, and then change the [libraryTarget](https://webpack.js.org/configuration/output/#outputlibrarytarget) to `"system"`.
> 
> Then add echarts to your import map and add the amd and named-exports extras.
> 
> Here is a [code sandbox](https://codesandbox.io/s/quirky-kare-ln53z?file=/index.html) showing that echarts can be successfully loaded by SystemJS. You can use the `import echarts from 'echarts'` syntax if you configure webpack properly.

Thank you very much for your reply. i'm try it and it worked In this way；but I got a problem，if i modify child app libraryTarget  to ‘system’, the webpack external both  from system import; However, my child app import react from root react；Lead to i must modify parent app react  import；my project have multiple child project，if modify parent app use system-import‘s’ react，other child app Can't use root app；What do I need to do？Here is my configuration：
parent app：
![image](https://user-images.githubusercontent.com/22994293/87401611-eef1d000-c5ec-11ea-8dc1-8279f55b6f32.png)
child app：
![image](https://user-images.githubusercontent.com/22994293/87401742-206a9b80-c5ed-11ea-90ea-577b8ea5564a.png)
now，An error has occurred at load child app ：
![image](https://user-images.githubusercontent.com/22994293/87401966-74758000-c5ed-11ea-8bb1-ddf8481908c5.png)

**Comment by joeldenning** [comment]
You must add all in-browser modules (including `react` and `react-dom`) to the import map. Then you can use them with the same import syntax as normal.

**Comment by yuanman0109** [comment]
> You must add all in-browser modules (including `react` and `react-dom`) to the import map. Then you can use them with the same import syntax as normal.

it's right, but if  add all cdn modules to the import map, i need delete the global module in order to reduce unnecessary  script tags， and parent app must to modify webpack librarytarget to 'system' to be able to work; if parent app use 'system' librarytarget , must add system module to 'index.html' script tag.   i expect use ‘’import systemjs from ‘xxx’ ‘’ the way；How to do

**Comment by joeldenning** [comment]
Hi @yuanman0109, could you clarify what you're asking? I do not think I fully understand. You can load global modules with SystemJS. Alternatively, you can use `System.set()` ([documentation](https://github.com/systemjs/systemjs/blob/master/docs/api.md#systemsetid-module---module)) to add modules to the SystemJS registry.

Regarding modifying the webpack libraryTarget, that is necessary when you want to inject SystemJS modules as externals into a webpack bundle. It doesn't have to be `system`, but can also be `amd`. However, in order to use SystemJS as a module loader, you will need to set it.

**Comment by yuanman0109** [comment]
hi @joeldenning ，I'm sorry I didn't describe it clearly；What I want it to look like ：parent app By script tag import react and react-dom module，Like this:
![image](https://user-images.githubusercontent.com/22994293/87848025-0db6d600-c90f-11ea-83aa-83bb4050396f.png)；（Note that there is no systemjs script tag）， my parent app enter file use import the way，like this：
![image](https://user-images.githubusercontent.com/22994293/87848148-fa583a80-c90f-11ea-8851-d3db0a77db75.png)
now，i hope child app dependent echart module use systemjs‘s import map，and react、react-dom use script tag‘s root variable，but，my child app‘s librarytarget is ‘system’，my import-map is no react、react-dom，so it don‘t work；if i add react、react-dom to import-map; like this:
![image](https://user-images.githubusercontent.com/22994293/87848266-19a39780-c911-11ea-8df0-087ea8d1e6c1.png)
child app can work normally；but my script tag import react、react-dom It seems redundant；I don't know if I have explained my needs clearly；

**Comment by joeldenning** [comment]
It is still difficult to diagnose this because the explanation is long and omits some important details. In particular, the method in which systemjs is being loaded and the entire contents of the html file would be needed. However, please do not share them here in the comment, as a big paste of code is not fun for me to have to sort through. Instead, could you create a code sandbox demonstrating the issue? You can paste the output bundle from webpack into the sandbox, which is probably easier than copying over your entire webpack config.

Here is a code sandbox template: https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html

**Comment by yuanman0109** [comment]
> It is still difficult to diagnose this because the explanation is long and omits some important details. In particular, the method in which systemjs is being loaded and the entire contents of the html file would be needed. However, please do not share them here in the comment, as a big paste of code is not fun for me to have to sort through. Instead, could you create a code sandbox demonstrating the issue? You can paste the output bundle from webpack into the sandbox, which is probably easier than copying over your entire webpack config.
> 
> Here is a code sandbox template: https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html

it'is my code https://codesandbox.io/s/morning-leftpad-f9uqi;

**Comment by joeldenning** [comment]
I read through your comment again and I think I understand now. I would recommend using `<link rel="preload">` to cause react/react-dom to be downloaded as soon as possible.

Here is a code sandbox that shows this: https://codesandbox.io/s/magical-fire-xz5sr?file=/index.html

More info about preloading is available at https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by guybedford** [comment]
@joeldenning do you think depcache would help here?

**Comment by joeldenning** [comment]
> do you think depcache would help here?

No. My understanding is that he's looking for a way to preload in the HTML. Depcache is slower than a `<link rel="preload">` since the browser won't start fetching during HTML parse.

**Comment by yuanman0109** [comment]
> I read through your comment again and I think I understand now. I would recommend using `<link rel="preload">` to cause react/react-dom to be downloaded as soon as possible.
> 
> Here is a code sandbox that shows this: https://codesandbox.io/s/magical-fire-xz5sr?file=/index.html
> 
> More info about preloading is available at https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

thank you，I've seen code sandbox，I'm still confused，i see you‘r index> I read through your comment again and I think I understand now. I would recommend using `<link rel="preload">` to cause react/react-dom to be downloaded as soon as possible.
> 
> Here is a code sandbox that shows this: https://codesandbox.io/s/magical-fire-xz5sr?file=/index.html
> 
> More info about preloading is available at https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

thank you，I've seen code sandbox，I'm still confused，i see you‘r index.html use systemjs import 'app.js', but my project is webpack HtmlWebpackPlugin generate script tag add to body tag，no use system。  Maybe I'd like to see webpack config，your code sandbox demo don‘t use webpack package and compile。

**Comment by joeldenning** [comment]
If you're using HTML webpack plugin, you'd do something like this:

```html
<script type="systemjs-importmap">
{
  "imports": {
    "app": "<%= htmlWebpackPlugin.files.js[0]%>"
  }
}
</script>
<script>System.import('app')</script>
```

More information at https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

**Comment by yuanman0109** [comment]
> If you're using HTML webpack plugin, you'd do something like this:
> 
> ```
> <script type="systemjs-importmap">
> {
>   "imports": {
>     "app": "<%= htmlWebpackPlugin.files.js[0]%>"
>   }
> }
> </script>
> <script>System.import('app')</script>
> ```
> 
> More information at https://github.com/jantimon/html-webpack-plugin#writing-your-own-templates

This is a very useful help, I will try
