### ISSUE TITLE
when  using   system.import(utl) method ,   can  we  load the url codes   through script tag  

### ISSUE THREAD

**Issue by duanbaosheng** [systemjs/systemjs#2202]
- SystemJS Version: 
- Which library are you using?
  - [ ] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

**Comment by joeldenning** [comment]
Hi @duanbaosheng, could you clarify what you mean by "can we load the url codes through script tag"? What do you mean by "url code"?

Code examples may help communicate, as well

**Comment by guybedford** [comment]
Closing as this is outdated, although you may want to check out the new auto import feature shipping in core.
