### ISSUE TITLE
Recommended polyfill for Firefox implementation of CSSStyleSheet

### ISSUE THREAD

**Issue by theurere2** [systemjs/systemjs#2207]
### Demonstration
Code Sandbox: https://codesandbox.io/s/serene-carson-vzt8r?file=/main.js

### Expected Behavior
Right now Firefox does not support `CSSStyleSheet`. What is a good work around for this as right now Firefox throws an error `TypeError: Illegal constructor.`?

**Comment by theurere2** [comment]
I ended up using https://www.npmjs.com/package/construct-style-sheets-polyfill to fix the problem in Firefox.

**Comment by joeldenning** [comment]
Yes that's a good polyfill to use - it's the one we use in the systemjs tests:

https://github.com/systemjs/systemjs/blob/5854c5e1708b4b22a3ab455bcbfac9fca8869c0e/package.json#L31
