### ISSUE TITLE
Using the imported CSS

### ISSUE THREAD

**Issue by theurere2** [systemjs/systemjs#2208]
- SystemJS Version: 6.3.3
- Which library are you using?
  - [x] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [x] AMD extra
  - [x] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
As demonstrated here: https://codesandbox.io/s/musing-wind-71p4v I am importing a CSS file. Unfortunately the CSS doesn't seem to be applied. Is there something that I have to do in order that the CSS be used? The h1 should be colored red after loading my file `test.css`

**Comment by theurere2** [comment]
Here is an example how to use the imported css: https://codesandbox.io/s/serene-carson-vzt8r?file=/main.js

**Comment by joeldenning** [comment]
Hi there - it's a good question and thanks for providing code sandboxes to help diagnose any issues. I took a  look at your second code sandbox and it shows how to do this correctly. The documentation for CSS modules is shown at https://github.com/systemjs/systemjs/blob/master/docs/module-types.md#css-modules
