### ISSUE TITLE
Dynamic import map updates

### ISSUE THREAD

**Issue by stevenvachon** [systemjs/systemjs#2211]
### Demonstration
https://codesandbox.io/s/systemjs-ignored-import-maps-j5xcl

### Expected Behavior
Be aware of updates to any import map for later use of `System.resolve()` (for `System.set()`).

### Actual Behavior
Only the first call to `System.prepareImport()` will parse import maps.

### Possible Solution
Use `MutationObserver` to pick up any changes to `script[type=systemjs-importmap]`, which might denecessitate `prepareImport()`.

**Comment by stevenvachon** [comment]
From Gitter:
> @guybedford 
Exactly - import maps spec is now frozen and doesn’t support updates
It does support dynamic injection before the first module load, but so does systemjs
After the first module load they are frozen
I’ve created http://github.com/guybedford/import-maps-extensions to get movement on new spec work for these sorts of cases
Will post to WICG when import maps unflag

**Comment by guybedford** [comment]
Currently this feature is only available to the Node.js build.

Yes a DOM mutation approach would allow this - I'd be open to it provided we can:

1. Implement it as a core extra
2. At the same time point to import-maps-extensions from SystemJS and the extra as possible standards directions for this while also noting that this is not currently part of any official spec

@stevenvachon if you feel like working on a PR, we could possibly add the necessary core hooks to support this? 

Here's an outline approach that might work:
* Have `prepareImport` mark which scripts have been processed
* Allow `prepareImport` to take a boolean argument which clears the `IMPORT_MAP_PROMISE` check
* Have an extra that uses dom mutators to determine when a new import map is injected, and then calls `System.prepareImport(true)` to trigger the updates.

Let me know if something like that might work, and no pressure of course re any PR work if you don't feel like it - happy to leave this issue open here as a feature too.

**Comment by stevenvachon** [comment]
Would it be acceptable to simplify it to a `clearCache` argument that simply reparses _all_ import maps?

**Comment by guybedford** [comment]
@stevenvachon the issue with that approach is that scripts could have been removed or reordered in the mean time and also there is a risk of refetching, so unfortunately not I don't think if we want to try and match what the spec would do as closely as possible.

What's the reason you don't like just marking scripts? I believe we already mark scripts in other places.

**Comment by joeldenning** [comment]
Jumping in a bit late here, but my understanding is that the import maps spec strictly forbids the behavior being discussed here. Dynamically adding an import map after loading the first module is disallowed.

From the spec:

> Because they affect all imports, any import maps must be present and successfully fetched before any module resolution is done. This means that module graph fetching is blocked on import map fetching.

https://github.com/WICG/import-maps#installation

Are we discussing an intentional deviation from the spec here?

**Comment by guybedford** [comment]
@joeldenning yes, I have a "spec intent" for this work at https://github.com/guybedford/import-maps-extensions.

**Comment by joeldenning** [comment]
Here's to hoping that the original import maps spec is adopted at all 😄. I am starting to have my doubts now that we're coming up on two years without a comment from Firefox/Safari

**Comment by guybedford** [comment]
Yes it's a dark ages for browser engagement right now... this is why to be perfectly honest we are the implementors who are most driving it right now.

I don't think they will be stalled indefinitely, but I do think they could be delayed by years. Which is why being able to address extensions in a standards space through import maps extensions is so important to continue to move forward.

In due course when I post this repo to WICG it would be huge to have some support there.

**Comment by guybedford** [comment]
Released in 6.4.0.
