### ISSUE TITLE
AMD modules cannot return undefined

### ISSUE THREAD

**Issue by eymorale** [systemjs/systemjs#2212]
### Demonstration

Code Sandbox: 

When creating an AMD module that returns undefined, i.e.
```
define([], function () {
  return undefined;
});
```

### Expected Behavior
The import should be undefined

### Actual Behavior
The import is an empty object `{}`

I will submit a PR with the fix shortly

**Comment by joeldenning** [comment]
I put together a code sandbox demonstrating the behavior, alongside with your proposed fix: https://codesandbox.io/s/unruffled-sutherland-mgbor?file=/index.html

I commented on your pull request with some hesitations about changing this. The AMD spec appears to indicate that falsy return values from AMD factory functions should be ignored and not made the export. See https://github.com/amdjs/amdjs-api/blob/master/AMD.md#factory-

> If the factory function returns a value (an object, function, or any value that coerces to true), then that value should be assigned as the exported value for the module.
