### ISSUE TITLE
Error when import  { Ng2GoogleRecaptchaModule } from 'ng2-google-recaptcha

### ISSUE THREAD

**Issue by 11LoneWolf11** [systemjs/systemjs#2213]
### Demonstration

Code Sandbox: 

### Expected Behavior
It should run without error.

### Actual Behavior
***as soon as I import  { Ng2GoogleRecaptchaModule } from 'ng2-google-recaptcha' in app.module.ts***

```import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { LoginComponent } from './boxLogin/login.component';

import { Ng2GoogleRecaptchaModule } from 'ng2-google-recaptcha';
@NgModule({
    imports: [BrowserModule, FormsModule, Ng2GoogleRecaptchaModule],
    declarations: [AppComponent, LoginComponent],
    bootstrap: [AppComponent]
})
export class AppModule { }```


it throws the following error
```
[object Error]: {description: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js", message: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js", originalErr: Error, stack: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js"}
description: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js"
message: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js"

originalErr: Error
stack: "(SystemJS) Syntax error SyntaxError: Syntax error at Anonymous function (eval code:15:1) at Anonymous function (eval code:1:31) at eval code (eval code:1:2) Evaluating http://localhost:25313/src/node_modules/ng2-google-recaptcha/index.js Evaluating http://localhost:25313/src/app/app.module.js Evaluating http://localhost:25313/src/main.js Error loading http://localhost:25313/src/main.js"

__proto__: Error```

systemjs.config.js

```/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': '/node_modules/'            
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            'app': 'app',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
            , 'ng2-google-recaptcha': 'node_modules/ng2-google-recaptcha'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {              
                defaultExtension: 'js',
                meta: {
                    './*.js': {
                        loader: 'systemjs-angular-loader.js'
                    }
                }
            },
            'ng2-google-recaptcha': { main: 'index.js', defaultExtension: 'js' },
            rxjs: {
                defaultExtension: 'js'
            }
        }
    });
})(this);
```

**Comment by joeldenning** [comment]
Hi @11LoneWolf11, it appears you're using SystemJS@0.21, since the `System.config()` api was removed in later versions of SystemJS.

I help maintain SystemJS, but know more about SystemJS@6 than 0.21, so I may not be able to help here. It appears that when SystemJS is attempting to eval the ng2-google-recaptcha  module, that the browser is throwing a syntax error. Providing which version of ng2-google-recaptcha you are using would likely be needed to diagnose this.

The best thing you can do to help diagnose this is to provide a code sandbox demonstrating the issue. The issue template you used has a code sandbox template in it - here's the link: https://codesandbox.io/s/quirky-antonelli-2kusz?file=/index.html. That template uses SystemJS@6, but can be modified for SystemJS@0.21

**Comment by 11LoneWolf11** [comment]
Joeldenning, I was working in .net 4.5.2 with angular2 configured to run from .net run button. I tried to upload on the sandbox however it has limit of 20 mbs only so I have posted the entire solution on git,  https://github.com/11LoneWolf11/BoxDome, please download and run the project to see error message in chrome console.

The project should run straight away to replicate the issue without any configuration.

requirement: windows 10 and Visual studio 2017.

**Comment by joeldenning** [comment]
I do not plan on diagnosing this, since I don't have Visual Studio, don't enjoy Angular, and don't enjoy Windows 😄. If anyone else would like to take a look at this, that would be helpful.
