### ISSUE TITLE
Cross-origin anonymous gives problems on Safari

### ISSUE THREAD

**Issue by LarsDenBakker** [systemjs/systemjs#2220]
Scripts are loaded using cross-origin anonymous to match module behavior: https://github.com/systemjs/systemjs/blob/master/src/features/script-load.js#L12

However, there is a bug in Safari where this causes same-origin requests to also be anonymous: https://bugs.webkit.org/show_bug.cgi?id=171566

It's fixed, but not released in any Safari version I think.

It can be fixed by using a custom `createScript` function, but this might cause bugs for people who need to rely on cookies for script requests.

**Comment by guybedford** [comment]
Thanks for posting I didn't know about this.... ok we should have a Safari-specific fix here then only on the needed versions ideally.

**Comment by guybedford** [comment]
Released in 6.4.1, thanks for the report here.
