### ISSUE TITLE
Low version browser use Systemjs@6.4.2 incompatible；

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2227]
- SystemJS Version: 6.4.2
- Which library are you using?
  - [y ] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ y] AMD extra
  - [y ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?
no
### Question
in my pad safari browser produced an error； because the version use ‘const‘ es6 grammar； https://github.com/cdnjs/cdnjs/blob/cac67d81e5b78625aedbf57b65a9b2d8f00ee35f/ajax/libs/systemjs/6.4.2/system.js#L624 ；
but systemjs version 6.3.3 is ok：https://github.com/cdnjs/cdnjs/blob/master/ajax/libs/systemjs/6.3.3/system.js；
why ？I can't use 6.4.2

**Comment by guybedford** [comment]
Thanks for reporting - I've released a fix in 6.4.3.
