### ISSUE TITLE
./node_modules/_systemjs@6.4.3@systemjs/dist/system-node.cjs Module not found: Can't resolve 'fs' in

### ISSUE THREAD

**Issue by xujinji93** [systemjs/systemjs#2231]
- SystemJS Version: 
- Which library are you using?
  - [ ] SystemJS
  - [ ] SJS
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

**Comment by joeldenning** [comment]
Hi @xujinji93, I tried out systemjs@6.4.3 locally and was unable to reproduce this issue when running system-node.cjs. What version of nodejs are you using? Could you share the code you're running that results in the issue?
