### ISSUE TITLE
How to properly use SystemJS + extras in node with typescript

### ISSUE THREAD

**Issue by Kepeters** [systemjs/systemjs#2236]
- SystemJS Version: 
- Which library are you using?
  - [x] system-node.cjs
- Which extras are you using?
  - [x] AMD extra

### Question
Hi everyone, I was wondering what the canonical way is to use SystemJS within a node typescript project using ts-node.
We would like to use SystemJS to validate external (AMD/UMD) modules (mostly frontend modules) by loading them into JSDom and checking if certain methods are available in them. For now I understand that I can use:
```
const systemJs = require('systemjs/dist/system-node.cjs');
```
to expose the ` systemJs.System.import` method to import modules.
However I can not properly import amd.js from the extras directory since it will throw an error: 
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ./node_modules/systemjs/dist/extras/amd.js
require() of ES modules is not supported.` 

This is true for all those import variants:
```
import "systemjs/dist/extras/amd";
import amd from "systemjs/dist/extras/amd.min"; 
import * as amd from "systemjs/dist/extras/amd";
const amd = require("systemjs/dist/extras/amd");
```
And even if that worked how would I connect that with SystemJS?

**Comment by joeldenning** [comment]
Use `import 'systemjs/dist/extras/amd.js'` instead of `require()` to load the extra. The extra doesn't export anything - it just patches the global `System` variable.
