### ISSUE TITLE
How the externals' map be shared from systemjs-importmap ?

### ISSUE THREAD

**Issue by shalldie** [systemjs/systemjs#2244]
- SystemJS Version: 
- Which library are you using?
  - [ ] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

https://github.com/systemjs/systemjs-examples/blob/master/loading-dependencies/webpack-externals/webpack.config.js#L14

webpack.config.js:
```js
externals: ['vue', 'vue-router']
```

index.html:
```html
  <script type="systemjs-importmap">
    {
      "imports": {
        "vue": "https://cdn.jsdelivr.net/npm/vue",
        "jupiter": "./dist/bundle.js"
      }
    }
  </script>
```
If the map has been defined in `systemjs-importmap` ，webpack will use `system.import` to load the module。

Who(webpack or systemjs) and how did this work?

I know it's not very suitable to ask the question here, but i'm curious very much! I've searched a lot of resposities but failed because of my poor knowledge.

**Comment by joeldenning** [comment]
Hi @shalldie, good question.

> If the map has been defined in systemjs-importmap ，webpack will use system.import to load the module。

This is almost true, but not quite. See the following code that shows that webpack specifies dependencies via `System.register()`. It does not use `System.import()`:

https://github.com/systemjs/systemjs-examples/blob/bf70097688e4c062683d31c9f58399aee6747a49/loading-dependencies/webpack-externals/dist/bundle.js#L1

https://github.com/systemjs/systemjs-examples/blob/bf70097688e4c062683d31c9f58399aee6747a49/loading-dependencies/webpack-externals/dist/bundle.js#L6

> Who(webpack or systemjs) and how did this work?

This was implemented in https://github.com/webpack/webpack/pull/8864. Webpack specifies dependencies by calling `System.register(deps, ...)`, and SystemJS provides the dependencies. You can read more about the System.register format at https://github.com/systemjs/systemjs/blob/master/docs/system-register.md

**Comment by shalldie** [comment]
@joeldenning 
Thanks for your patience!
I'll spend the afternoon looking at it
