### ISSUE TITLE
Loading external resource (CORS) error

### ISSUE THREAD

**Issue by wclr** [systemjs/systemjs#225]
Why when I try to load module (using `System.import`) from external source I've got an error:

```
XMLHttpRequest cannot load ... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ...  is therefore not allowed access. 
```

But this resource can be loaded with `<script>` tag or `jquery.getScript`. I'm I doing something wrong? Can this be handled?

**Comment by circlingthesun** [comment]
I've created a plugin that deals with this. https://github.com/circlingthesun/systemjs-script-plugin

**Comment by OliverJAsh** [comment]
Is there any way we can use https://github.com/systemjs/systemjs/blob/master/lib/extension-scriptLoader.js?

**Comment by guybedford** [comment]
Yes, this is used in the CSP build of SystemJS, which is exactly for this stricter Content Security Policy support.

**Comment by OliverJAsh** [comment]
How can I use that version instead of SystemJS? It's not downloaded with
`jspm dl-loader`.

**Comment by OliverJAsh** [comment]
I'm trying to use the CSP version like so:

```
<script src="/assets/jspm_packages/github/systemjs/systemjs@0.16.7/dist/system-csp.js"></script>
```

This doesn't work because SystemJS tries to request ES6 Module Loader from `/assets/jspm_packages/github/systemjs/systemjs@0.16.7/dist/es6-module-loader.js`.

**Comment by guybedford** [comment]
It's fine to manually include `es6-module-loader.js` with a script tag or concatenated with SystemJS in these cases.

**Comment by OliverJAsh** [comment]
Thanks. SystemJS will download using the type `script` by default, eventually?

**Comment by guybedford** [comment]
Yes, this will be in the 0.17 release.

**Comment by Ken-vdE** [comment]
+1 same problem. Tried importing google maps api. No luck

**Comment by circlingthesun** [comment]
@Ken-vdE, you should be using 0.17+. Then use:

```javascript
System.config({
  ...
  meta: {
    "ga": {
      "scriptLoad": true,
      "format": "global",
      "exports": "ga"
    }
  },
  map: {
    "ga": "//www.google-analytics.com/analytics.js"
  }
});

```
But with the google maps URL.

**Comment by Ken-vdE** [comment]
@circlingthesun still no luck: 
![image](https://cloud.githubusercontent.com/assets/15888558/13028615/2e19e8c4-d274-11e5-9456-4782fc2ff9ba.png)

**Comment by circlingthesun** [comment]
Replace, occurrences of `ga` with `GoogleMaps`.

**Comment by Ken-vdE** [comment]
@circlingthesun yes, i did that.

**Comment by circlingthesun** [comment]
In Main.js you should also be loading GoogleMaps via whatever module syntax you are using. So `var  GoogleMaps = require('GoogleMaps');` for CommonJs or  `import GoogleMaps from 'GoogleMaps';` for ES6.

**Comment by Ken-vdE** [comment]
@circlingthesun  Im doing that already.

**Comment by circlingthesun** [comment]
Mmm... I'm not sure whats going on then.

**Comment by Ken-vdE** [comment]
@circlingthesun Alright, thanks for the help anyway ;) Maybe you could try it yourself, see if it's a local problem or a sysjs problem?

**Comment by circlingthesun** [comment]
Here is a working example: http://plnkr.co/edit/uF6N79pLQCmTvjJxS7X9?p=preview

**Comment by Ken-vdE** [comment]
@circlingthesun Wow, thanks! Strange, the code is pretty much similar... Ill figure it out ;)

**Comment by circlingthesun** [comment]
:+1:

**Comment by Ken-vdE** [comment]
@circlingthesun Im using the angular2 framwork, and it just wont load... Getting the same error.

**Comment by circlingthesun** [comment]
I doubt that Angular has anything do with it not loading. What version of SystemJS are you using? It appears that 0.17.0 doesn't work. My example uses 0.19.0.

**Comment by Ken-vdE** [comment]
@circlingthesun Yes that wasn't my guess either. Im using 0.19.6.

**Comment by circlingthesun** [comment]
Well that doesn't seem to be the problem.

**Comment by Ken-vdE** [comment]
@circlingthesun strange thing is, the chrome network debugger shows the google file is loaded...

**Comment by Ken-vdE** [comment]
@circlingthesun I finally figured out the issue. Apparently I really dumb :) The naming is important, obviously; 'GoogleMaps' doen't exist, but 'google' does... Sorry for the trouble and thanks for all the efforts.

**Comment by circlingthesun** [comment]
No worries, glad you got that sorted :)

**Comment by Andrewsturick** [comment]
Quick question, does setting the meta property not work to set cross-domain requests to script requests?

I am trying to import my angular2 app code deployed to CDN, but keep getting the XHR request error:

XMLHttpRequest cannot load ... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin ...  is therefore not allowed access. 



My map object is obviously correctly pointing to the resource as we are at least getting CORS, and is called "app".

My meta is as such: 

meta = {
    "app" : {
          "scriptLoad": true,
           "format": "global",
           "exports": "app"
     }
}

I am including the meta in my config object with my map and packages objects.

I've been banging my head on this all day, any help would be GREATLY appreciated...

Cheers!

**Comment by fnlctrl** [comment]
I think I've found a way to bypass cors altogether.

1. Make sure`fetch loader` is not used (i.e. script loader is always used)
2. Simply add this snippets before loading modules:

```js
var createScript = System.constructor.prototype.createScript;
System.constructor.prototype.createScript = function (url) {
  return Promise.resolve(createScript.call(this, url))
    .then(function (script) { script.crossOrigin = undefined; });
};
```

### Why it works

The culprit is the "crossorigin" attribute, more detail: https://stackoverflow.com/a/41069421

Normally, `<script>` tags don't send "Origin" header when requesting script content and thus bypass CORS completely. 

However, by adding "crossorigin" - even with "anonymous", will lead to the browser sending the "Origin" header for `<script>` tags, and thus making them subject to CORS restrictions.

These lines

https://github.com/systemjs/systemjs/blob/main/src/features/script-load.js#L23-L24

will cause `crossOrigin` to be almost always added - (unless `.indexOf()` returns `0` which means script `url` begins with `location.origin`, i.e. your app domain is equal to your cdn domain)

By adding the above plugin, we always remove the "crossOrigin" attribute, and CORS is no more.

**Comment by joeldenning** [comment]
It's not possible to tell browsers to bypass cors. However, the way that cors works does change depending on the `crossOrigin` attribute (also the `credentials` attribute). In other words, the rules of CORS are complicated but are always followed.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
