### ISSUE TITLE
After import extra amd.js，window.wx is undefined? how to use?

### ISSUE THREAD

**Issue by yuanman0109** [systemjs/systemjs#2250]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
wx is by script tag download，my app need use window.wx setting,now, before i import amd.js, window.wx is undefined

**Comment by joeldenning** [comment]
Hi @yuanman0109 - the `wx` script is likely in UMD format, which behaves differently when amd.js is loaded. The amd.js extra creates the `window.define` global function, which changes the behavior of UMD scripts. UMD scripts call `define()` if `window.define` is available, and will create a global variable otherwise.

Here are some options for you to consider:

### Option 1

If you want don't need wx to be a SystemJS module, load it before amd.js is loaded:

```html
<!-- load wx before SystemJS -->
<script src="/wx.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/amd.js"></script>
```

### Option 2

Manually set the global variable:

```js
System.import('/wx.js').then(module => {
  window.wx = module
})
```

### Option 3

Temporarily remove the `window.define` variable while loading wx.js:

```html
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
<script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/amd.js"></script>
<script>
  const systemDefine = window.define;
  delete window.define;
  const wxScript = document.createElement('script')
  wxScript.src =  '/wx.js'
  wxScript.addEventListener('load', () => {
    window.define = systemDefine
  })
  document.head.appendChild(wxScript)
</script>
```

**Comment by yuanman0109** [comment]
> Hi @yuanman0109 - the `wx` script is likely in UMD format, which behaves differently when amd.js is loaded. The amd.js extra creates the `window.define` global function, which changes the behavior of UMD scripts. UMD scripts call `define()` if `window.define` is available, and will create a global variable otherwise.
> 
> Here are some options for you to consider:
> 
> ### Option 1
> If you want don't need wx to be a SystemJS module, load it before amd.js is loaded:
> 
> ```
> 
> <script src="/wx.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/amd.js"></script>
> ```
> 
> ### Option 2
> Manually set the global variable:
> 
> ```js
> System.import('/wx.js').then(module => {
>   window.wx = module
> })
> ```
> 
> ### Option 3
> Temporarily remove the `window.define` variable while loading wx.js:
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
> <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/extras/amd.js"></script>
> <script>
>   const systemDefine = window.define;
>   delete window.define;
>   const wxScript = document.createElement('script')
>   wxScript.src =  '/wx.js'
>   wxScript.addEventListener('load', () => {
>     window.define = systemDefine
>   })
>   document.head.appendChild(wxScript)
> </script>
> ```
Thank you very much for your answer, which will surely solve the problems I have encountered.But if a lot of my applications use global variables, it's going to take a lot of time to fix them，But if I don't import amd.js file, there will be some other errors。

**Comment by joeldenning** [comment]
> But if a lot of my applications use global variables, it's going to take a lot of time to fix them，But if I don't import amd.js file, there will be some other errors。

Yes unfortunately this is the current state of the JS ecosystem - lots of UMD builds that make assumptions about the runtime environment they will be run in.
