### ISSUE TITLE
Include named exports extra for AMD / globals by default

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#2263]
Now that Node.js has effectively implemented this pattern, I'm wondering if we do the same.

@joeldenning would this be useful?

**Comment by guybedford** [comment]
Added in https://github.com/systemjs/systemjs/pull/2264.

**Comment by joeldenning** [comment]
Excited to see this - I always encourage using the named-exports extra in the single-spa community, as many important libs don't work without it (react's umd build, vue's umd build, etc)

**Comment by guybedford** [comment]
Glad to hear. I believe there won't be any conflict if you happen to still include the extra - but it should never be necessary now too.

Please post if you hit any issues at all, but it should be perfectly compatible.

Will post the release now.
