### ISSUE TITLE
Graceful error handling for failing external import maps

### ISSUE THREAD

**Issue by naltatis** [systemjs/systemjs#2267]
I'm trying to build a micro frontends setup where different teams provide their own import map definitions. However, it seems that System.js completely aborts the import map resolution when one of the referenced import maps fail to load or contain invalid JSON data. This behaviour makes the great idea of import maps unusable from a reliablity standpoint.

Is there a ways to make the import map resolution process more graceful? I'm aware that using multiple import maps is considered experimental (https://github.com/systemjs/systemjs/issues/2095) right now. Nevertheless it would be a great feature if one failing import map wouldn't have negative effects on all the others.

I've already tried to work around this behaviour via [a hook for prepareImport](https://github.com/systemjs/systemjs/blob/master/docs/hooks.md#prepareimport---promise) but without success so far.
Am I missing something here?

### Demonstration

The example has two import map references (a and b). `import-map-a` points to a non existing target and is commented out for demonstration.

Code Sandbox: https://codesandbox.io/s/distracted-flower-hfbxn?file=/index.html

### Expected Behavior

Everything works fine if all external import maps work. H1 is replaced with "App B was loaded". I'd expect that this behaviour continues working even if you're adding an additional, broken import map definition (`import-map-a`).

### Actual Behavior

The complete import map resolution breaks. The H1 is not replaced any more, even though system b could work perfectly fine without system a.

\ Michael

**Comment by guybedford** [comment]
Thanks for posting the issue, this sounds like a sensible thing to do to me. We can add graceful failures as a feature certainly. If you're interested in making a PR I 'd be glad to add it, or you can wait until one of us gets to it.

I think we should still add an error handler to log errors to the console without throwing the `prepareImport` promise, then add a full error code as can be seen in the error message pattern here - https://github.com/systemjs/systemjs/blob/master/src/features/import-maps.js#L56, with the errors documented in https://github.com/systemjs/systemjs/blob/master/docs/errors.md.

**Comment by naltatis** [comment]
I'll give it a try 💪

**Comment by guybedford** [comment]
Released in 6.8.0.
