### ISSUE TITLE
Documentation for auto imports

### ISSUE THREAD

**Issue by joeldenning** [systemjs/systemjs#2268]
I tried auto imports out today for the first time, but was unable to find documentation. I don't have the time now to submit a documentation PR, but would be happy to later (if I remember to do so).

**Comment by guybedford** [comment]
I'm still a little unsure if I want to push auto imports as a loading technique more strongly. The main issue being that there is no ES module analog to what it is doing, and systemjs-module is probably still a better bet in most cases.

Primarily I've been interested in exploring it as an optimization technique. And it may make sense to even change it to be non-executing in future as a sort of preloading mechanism as an analog to modulepreload. Hence the lack of documentation.

**Comment by guybedford** [comment]
I'm also considering adding system-modulepreload and possibly even removing auto imports in a subsequent release.

For now I think leaving undocumented makes sense. If anything it may be time to redocument systemjs-module better.

**Comment by guybedford** [comment]
systemjs-module redocumented in https://github.com/systemjs/systemjs/pull/2278.
