### ISSUE TITLE
System.config is not a function in browser console

### ISSUE THREAD

**Issue by hefeng6500** [systemjs/systemjs#2269]
- SystemJS Version: v 6.7.1
- Which library are you using?
  - [ √] system.js
- Which extras are you using?
  - [ √] Global
  - [ √ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
no.

### Question

In my old project, use SystemJS api `SystemJS.config` at version v0.20.18. When I upgrade to new version 6.7.1, got an error in browser console, "  Uncaught TypeError: SystemJS.config is not a function ", what should I use instead of System.config?

**Comment by joeldenning** [comment]
Hi @hefeng6500. In SystemJS@>=2.0.0, you use Import Maps to control the behavior of your modules. Additionally, you may use [the new SystemJS registry API](https://github.com/systemjs/systemjs/blob/master/docs/api.md) to control the module registry. You can also use https://github.com/systemjs/systemjs-babel to compile modules in development. Is there specific functionality from `System.config()` that you are trying to find the equivalent for?

**Comment by chrys-exaucet** [comment]
Hello. I subscribe to the issue since it matches my concern. When using **System.config()** to map libraries in node_modules, I have the exact same error aforementionned. I switched to  this:
```js
   <script type="systemjs-importmap">
    {
      "imports": {
       "mylib": "/node_modules/mylib/dist/mylib-dev.js", 
              }
    }
```

Doing so yields 404 error :

````
Failed to load resource: the server responded with a status of 404 (Not Found)
Uncaught Error: Error loading http://localhost:<port>/node_modules/mylib/dist/mylib-dev.js (SystemJS Error#3 https://git.io/JvFET#3)
    at HTMLScriptElement.<anonymous> (script-load.js:69)
    at e.invokeTask (zone.min.js:13)
    at t.runTask (zone.min.js:13)
    at t.invokeTask [as invoke] (zone.min.js:13)
    at p (zone.min.js:43)
    at HTMLScriptElement.h (zone.min.js:43)
```

**Comment by joeldenning** [comment]
`System.config` is for SystemJS@<1. It was removed in systemjs@>=2

Your code and stacktrace do not show you using System.config, so I think you maybe posted this in the wrong place.

**Comment by chrys-exaucet** [comment]
Fair enough! Note: Having read the thread, I found no relevance pasting system.config stacktrace ( which doesn't working for v6.x as you said). Since, in your previous message, you ask what kind of functionality from System.config we wanted to find an equivalent for, I posted what I thought to be equivalent of ```js System.config( path:{ npm:'/node_modules/' }, packages: 'mylib': 'npm:mylib/dist/mylib/mylib-dev.js```.
