### ISSUE TITLE
ImportMaps and the waterfall problem

### ISSUE THREAD

**Issue by jonbjk** [systemjs/systemjs#2270]
Hi
We are using importMaps and SystemJs as a mechanism to allow breaking up a large web app into modules that can be deployed individually. The setup works well, but there is a waterfall problem that we would like to address.
There are some proposals https://github.com/WICG/import-maps/issues/209 to solve the problem.
I do understand that getting dependency caching into the standards proposal will take time, so I am contemplating to solving it by adding some hooks to SystemJs. Not sure whether this is a good idea or not though.
@guybedford Could you give some advice?

**Comment by guybedford** [comment]
@jonbjk firstly it is advisable to make sure that the packages you are serving are still individually optimized with eg RollupJS optimizations. No network optimization will replace the job of good code optimization. But it can be done at a fine-grained level.

For the latency waterfall, SystemJS does implement the "depcache" field exactly as described in that issue you found. It is still somewhat uncertain how much a performance benefit this can offer so I'm waiting on pushing this more to see if we can get benchmarks that demonstrate it works well (and in turn that would be useful to take back to the standards process).

In my own benchmarks so far I haven't found it to be that much of a performance improvement, but perhaps the implementation in SystemJS could be optimized further or it just needs the right type of application to apply to.

I'd suggest trying it out in your app, and if it seems to make a good improvement and you feel like sharing the numbers that would be a great help to hear too.

**Comment by jonbjk** [comment]
@guybedford Thank you for the prompt reply.
I did not realise that SystemJs already implemented the "depcache" field. That is good news.
We will try this approach and can share some numbers.
We have a lot of other things in the backlog so it might take some time before I can report back.

**Comment by guybedford** [comment]
@jonbjk please do share any results you come up with here, improving benchmarks is specifically tracking in https://github.com/systemjs/systemjs/issues/2022 as well.

For now I will close this, but I hope to get an update from you at some point!
