### ISSUE TITLE
Trigger error on currentScript when there is an error while fetching

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#2271]
### Description of Proposed Feature

Make systemjs dispatch an `error` event on `currentScript` when there is a fetch error.
An error is already thrown at https://github.com/systemjs/systemjs/blob/abccaf09a54b125150a8be663218d0ba08a5ce90/src/features/script-load.js#L68-L70

The idea would be to add something like the following:

```js
if (currentScript) {
  currentScript.dispatchEvent(new Event('error'))
}
```

### In what way would you use it?

I would like to catch 3 types of error that may happen while loading/parsing and executing the main script of my page. Doing nothing means the page display would be broken and I would have to open the DevTools to see the error. So I would like to detect them to display an error screen. Maybe one day I would also ping a server to track these errors.

<details>
  <summary>See steps to reproduce</summary>

An html file

```html
<script id="main-script" type="module" src="./main.js" />
<script type="text/javascript">
  const mainScript = document.querySelector('#main-script')
  mainScript.onerror = () => {
    alert('main script load error')
  }
  const errorEventCallback = () => {
    alert('main script syntax or runtime error')
  }
  window.addEventListener('error', errorEventCallback)
  window.mainScriptExecutionCompleted = () => {
    window.removeEventListener('error', errorEventCallback)
  }
</script>
```

And inside `main.js`

```js
window.mainScriptExecutionCompleted()
```

To trigger the different types of errors I do the following:

##### network error

```diff
- <script id="main-script" type="module" src="./main.js" />
+ <script id="main-script" type="module" src="./not-found.js" />
``` 

#### syntax error

```diff
- window.mainScriptExecutionCompleted()
+ a b
``` 

#### runtime error

```diff
- window.mainScriptExecutionCompleted()
+ throw new Error("foo")
```

</details>

In this context, when I switch to Systemjs:

```diff
- <script id="main-script" type="module" src="./main.js">
+ <script id="main-script">System.import("./main.js")</script>
```

If `main.js` contains a syntax error -> I do have `error` event on `window`
If `main.js` contains a runtime error -> I do have `error` event on `window`
If server fails to serve `main.js` (404, 500, timeout) -> There is no `error` event on `script#main-script`

**Comment by joeldenning** [comment]
Hi @dmail, thanks for the nice description here. One thing to note is that `currentScript` does not work in IE11, so an alternative would have to be found in order to support IE11.

Additionally, I'm unsure that `document.currentScript` would work here, since it changes after the synchronous execution of the script, and System.import() is asynchronous.

**Comment by dmail** [comment]
Hi @joeldenning,

I try to make good descriptions, I am glad you like this one :)

> One thing to note is that currentScript does not work in IE11,

I was thinking we could use `document.currentScript` when available and keep current behaviour for IE11.

> Additionally, I'm unsure that document.currentScript would work here, since it changes after the synchronous execution of the script, and System.import() is asynchronous.

The idea is to know which `script` tag eventually initiated the fetching of an url to be able to dispatch an error event on it. We need to read an eventual `document.currentScript` when `System.import` is called. Later when a script load error occurs it should be able to know if there is a script associated with it.

```js
System.import = function(specifier) {
  var currentScript = document.currentScript
  if (currentScript) {
    // there is a currentScript,
    // any network error while fetching specifier (or its dependencies)
    // should dispatch an error event on currentScript
  }
}
```

**Comment by joeldenning** [comment]
I see. Yes I think that storing the currentScript upfront, synchronously for later use would work.

I think my last question is whether this behavior makes sense in the context of `System.import()`, or whether it only makes sense with `<script type="systemjs-module">`.

[This code sandbox](https://codesandbox.io/s/throbbing-cdn-gkhmf?file=/index.html) shows that, for native modules, the script `error` event *does not fire for import()*, but only for `<script type="module" src="a.js">`. This makes sense, since the error for `import()` is asynchronous and wrapped in a promise. Because of this, I don't think it makes sense to fire an `error` event for scripts that call `System.import()`, but that it would make sense for `<script type="systemjs-module">`

**Comment by dmail** [comment]
Yes good point, only a fetch error during main file loading or static import loading should dispatch the `error` event on the script tag. As your codesanbox shows a dynamic import should not be considered.

I was suggesting to dispatch it for `System.import` because I am using a tool to transform my html scripts from

```html
<script type="module" src="a.js"></script>
```

To

```html
<script>System.import("./a.js")</script>
```

I forgot to consider `systemjs-module` and should certainly prefer the following output when transforming my html. 

```html
<script type="systemjs-module" src="a.js"></script>
```

**Comment by joeldenning** [comment]
The downside of `systemjs-module` is that imports can start happening before the systemjs extras have been installed, which results in some tricky behavior. But if you're not using extras, it should work fine.
