### ISSUE TITLE
Proper way to determine what to import?

### ISSUE THREAD

**Issue by armandn** [systemjs/systemjs#2287]
- SystemJS Version: 6.8.0
- Which library are you using?
  - [X] system.js
  - [X] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [X] Named Exports
  - [X] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

Let's say I have several "bundles" of modules generated by Typescript with `System.register("id", ["dep1", "dep2"...`
Each such bundle has a class that is its entry point.

I want a sort of generic script that can determine which bundle has been loaded / registered, and import the corresponding "Main". Some things, such as `System.entries()` or `System.has()` seem list entries only _after_ `System.import()`, so how can I do something like this:
```
    if (System.has('ModuleA'))
        System.import('ModuleA').then(function(m){new Class1()})
    else if (System.has('ModuleB'))
        System.import('ModuleB').then(function(m){new Class2()})
```

**Comment by joeldenning** [comment]
When using the named-register extra, you can access the named register modules via `System.registerRegistry`. See this for example:

```js
      for (let moduleName in System.registerRegistry) {
        console.log("importing", moduleName);
        System.import(moduleName).then((ns) => {
          console.log("imported", moduleName, ns);
        });
      }
```

Working example:

https://codesandbox.io/s/unruffled-glade-c6djx?file=/bundle.js
