### ISSUE TITLE
Question: Difference between SystemJS and Module Federation from webpack

### ISSUE THREAD

**Issue by dmail** [systemjs/systemjs#2292]
### Question

The recent addition of [Module Federation](https://webpack.js.org/concepts/module-federation/) in Webpack is being used by React to experiment promising stuff around [server components](https://reactjs.org/blog/2020/12/21/data-fetching-with-react-server-components.html).

In this context I got curious and wanted to know more about Module Federation. When I read the high level documentation on Module federation, I see common points with SystemJS (top level await, sharing module cross bundles, ...).

I am wondering what are the differences between Module federation and SystemJS? Could they have used SystemJS to achieve Module federation? If not, what are the things Module Federation have that SystemJS does not?

Module Federation and SystemJS are barely comparable as they don't share the same purpose. But if you have insight I would be curious to read them. 

Maybe it's not the correct place to ask this question. If that is so, sorry for the noise.

**Comment by joeldenning** [comment]
Module federation shares modules via the webpack module registry. As such, it's largely a webpack-specific technique, although there have been efforts to support it in rollup. Module Federation does not include a registry api or a global api for loading modules (`System.import()`). It generally uses global variables for each federated bundle to dynamically inject modules into the webpack registry, although this is configurable via webpack's `output.libraryTarget` config.

The approach with module federation is for each project to bundle all its dependencies, but then only load each dependency once. There is a "host" and a "remote", where the host is the main app for the page and the remote is a separately built app that you're pulling in some of the dependencies.

Another difference is that module federation is both a build-time and runtime tool, whereas SystemJS is only a runtime tool.

It is possible to use SystemJS and module federation together - systemjs to load the bundles, but module federation to track the shareable modules within those bundles.

**Comment by dmail** [comment]
I now have a better understanding of the differences between SystemJS and Module Federation. And how they can be used.
Thank you for taking the time to respond 👍
