### ISSUE TITLE
System JS Parallel Imports with Promise.All

### ISSUE THREAD

**Issue by p-michaels-20200** [systemjs/systemjs#2297]
### Question
Sorry if this has been brought up before but I cannot find an answer to it.  I have an angular app which uses system js.  It has multiple assets - e.g. vendor, main, runtime, polyfills & polyfills-es5.

I wanted to download these assets in parallel for performance reasons so I used Promise.All.  However I noticed Promise.All doesn't always wait until all the imports are finished and doesn't respect the order of execution.  This meant I would sometime see load errors because it tried to execute the main bundle before other assets like runtime/vendor were downloaded.

`Promise.all([
    System.import('runtime'),
    System.import('polyfills'),
    System.import('polyfills-es5'),
    System.import('vendor'),
    System.import('main')
  ])
  .then(function(modules) { ... })`

To get round this issue, I link preload all assets and it fixes the problem.  However link preloading isn't supported by all browsers - https://caniuse.com/link-rel-preload

Is there an alternative or recommended solution that I can use?  I cannot chain the imports as its a large app and chaining would impact performance. I feel like I'm missing something obvious.

**Comment by guybedford** [comment]
@p-michaels-20200 you can achieve this sort of flattening using the depcache feature of SystemJS. See https://github.com/systemjs/systemjs/blob/master/docs/import-maps.md#depcache for more info.

The gist of the approach is a configuration something like:

```js
{
  "depcache": {
    "/path/to/main.js": ["runtime", "polyfills", "polyfills-es5", "vendor"]
  }
}
```

`depcache` will load the flat module list whenever an import to `main` is triggered, and will not result in any change of evaluation ordering.

**Comment by guybedford** [comment]
Another feature in consideration is a `System.preload` function or `<link rel="system-preload">` tag support for preloading for SystemJS without altering execution order.

**Comment by p-michaels-20200** [comment]
@guybedford - thanks for the quick reply, this looks to be exactly what I need.  Closing this question out
