### ISSUE TITLE
loading dependences from import file don't add "js" extension

### ISSUE THREAD

**Issue by sergiot71** [systemjs/systemjs#2307]
- SystemJS Version:   6.8.3
 Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)? NO

### Question
we have a ES6 module (from typescript) loaded correctly with System.import('fpnet_test') by importmap:
<script type="systemjs-importmap">
    {
      "imports": {
        "fpnet_test": "./scripts-typescripts/controllers/sistema/fpnet-test.ctrl.js"
      }
    }
</script>
The script has a dependence: System.register(["./fpnet-test-interface"], ...
Systemjs try to load this file without ".js" extension and fails.
![image](https://user-images.githubusercontent.com/8170940/109955221-8c1b8900-7ce2-11eb-8192-4f44c048af44.png)

Can you help me, thanks.

Sergio

**Comment by joeldenning** [comment]
Hi @sergiot71, here's an example that shows how to do this: https://github.com/systemjs/systemjs-examples/tree/master/loading-code/typescript-default-extension

**Comment by sergiot71** [comment]
Hi @joeldenning, thank you very much! it's ok!!!
Sergio
