### ISSUE TITLE
Access webpack vendor chunks from System module

### ISSUE THREAD

**Issue by pavlovp** [systemjs/systemjs#2308]
- SystemJS Version: latest
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)? No

Hi, I'm aware that this question is related also to webpack,

[my repo](https://github.com/pavlovp/question-webpack-externals) represents simple case - a react app and a library exporting react component.
The app resolves the library in runtime - works great with System!

The problem is that React library gets duplicated. 
I followed the example from [webpack docs](https://v4.webpack.js.org/plugins/split-chunks-plugin/#split-chunks-example-2).
As you can see, in the 'dist' folder, separate chunk for React is created (when compiling app).

This chunk is JSONP webpack chunk.

Can such chunk be consumed by System.js - can we force Webpack to emit those chunks as System.js modules?

**Comment by joeldenning** [comment]
Hi @pavlovp, good question. Webpack chunks are not in System.register format (see https://github.com/webpack/webpack/issues/8833#issuecomment-468181544), so SystemJS is unaware of them.

Generally the best way to share React between projects is to mark `react` and `react-dom` as [webpack externals](https://webpack.js.org/configuration/externals/#root), and then add them to the systemjs import map.

**Comment by pavlovp** [comment]
Right, Thank you - repo updated according to your answer

**Comment by grvpanchal** [comment]
@joeldenning I have an issue with server-side rendering with chunks when the target is node. Is there a solution to server-side rendering for chunks?

**Comment by joeldenning** [comment]
Your question doesn't seem related to the original question and isn't specific enough for me to help with. Webpack chunks on the server side are generally loaded with `require()`. I haven't used webpack chunks + systemjs on the server side before.
