### ISSUE TITLE
SystemJS Bare Specifier Error Handling

### ISSUE THREAD

**Issue by stuartcargill** [systemjs/systemjs#2312]
Hi,

I have an app which gets quite a lot of traffic, sometimes I see issues with the import map being downloaded which results in a unable to resolve bare specifier error.  

Is there a way to retry if the import map fails to download? I tried adding the onerror event handler but this doesnt seem to work as the script type is not JavaScript:

`<script src="import-map.json" onerror="myFunction()" type="systemjs-importmap"></script>`

**Comment by guybedford** [comment]
@stuartcargill good suggestion - yes we could support a special `onerror` callback like this for handling fallbacks. I'd be more than happy to review a PR along those lines / leave this open to track.

**Comment by stuartcargill** [comment]
Thanks for the quick reply @guybedford  - I'll work on this and create a PR when it's ready.

**Comment by QWERTYail** [comment]
Y

**Comment by saak23** [comment]
@guybedford ,
Katie (@kykwak) sent the PR to implement "OnError" callback. Can you please review the request? Thanks
-Saikrishna

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/pull/2324.

**Comment by kykwak** [comment]
Hi @guybedford , was wondering how to get the minified version of the latest changes? Thanks
