### ISSUE TITLE
How to make self-bootstrapping s.js-enabled script that can also be XHR-loaded

### ISSUE THREAD

**Issue by joaotavora** [systemjs/systemjs#2316]
- SystemJS Version: 
- Which library are you using?
  - [ ] system.js
  - [x] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
No.

### Question

Hello.  The question's title may be confusing, but I tried for a while and couldn't find any better phrasings.

In short, my Rollup-based use case requires me to create a `mashup.js` (which is the main Rollup a "chunk" of many js modules), inject the contents of `s.min.js` into its beginning and load that from an `index.html` file.  It works fine, _as long_ as I load said chunk from a normal `<script src='mashup.js'></script>` tag.

However, in certain situations, I am also required to load `mashup.js` using a more rudimentary legacy technique of `XMLHttpRequest` and creating a `script` tag in that manual requests's `load` handler.  The `mashup.js` will load fine, but the main code won't actually be run, because `s.js` will check if `document.readyState` is `loading`, which is true when I load it as described in the previous paragraph, but false when the `script` tag is manually created.

I've looked at `System.import(file)` but it doesn't seem to work because Rollup seems to register that main module anonymously, with `System.register([], (function(e, t) {...}`

Also, I cannot control the contents of the `index.html` file, so I need something self-contained in a single `.js` file.

Hopefully I've explained myself.  What are my options?

Thank you in advance.

**Comment by joeldenning** [comment]
You're relying on the auto-import feature within script-load.js. It might be interesting to add support for auto-importing after the document is loaded, perhaps via an imperative api that turns on auto imports for any subsequent calls to System.register(). @guybedford thoughts on that?

@joaotavora, here's a workaround that you can try that doesn't require any changes to systemjs. It hooks `instantiate`, which is a bit unusual but entirely possible.

1. Add the following to your bundle. It needs to execute after s.js. It doesn't matter whether it executes before or after the `System.register()` created by rollup:

```js
const originalInstantiate = System.constructor.prototype.instantiate;

System.constructor.prototype.instantiate = () => {
  // The rollup bundle's registration object will be the last register that is returned by getRegister.
  const autoImportRegister = System.getRegister();

  // Only use this custom implementation of instantiate one-time immediately, after this script executes. Resume normal script loading behavior aftewards.
  System.constructor.prototype.instantiate = originalInstantiate;
  return autoImportRegister;
};
```

2. Add the following to your code that loads the mashup.js file:

```js
xhr.addEventListener('load', () => {
  const scriptEl = document.createElement('script');
  scriptEl.src = "mashup.js"
  scriptEl.addEventListener('load', () => {
    // Tell SystemJS to instantiate your module. This doesn't result in a network request because we hooked instantiate.
    System.import('mashup.js');
  })
})
```

Here's a code sandbox showing it working: https://codesandbox.io/s/intelligent-sky-rsloz?file=/bundle.js:23793-24063

**Comment by joaotavora** [comment]
> Add the following to your code that loads the mashup.js file:

Thanks!! I haven't tested it, but it seems a good start.  Unfortunately but I can't touch the `xhr` code that loads the `mashup.js` file because it lives in the `index.html`. It will sometimes load `s.el`-enabled `mashup.js` and other times load some pre-ESM dinossaur.

Isn't there some "run once" thing I can append to `mashup.js` that will do the same?  Maybe just adding `System.import('mashup.js')` to the end of `mashup.js` itself?

**Comment by joaotavora** [comment]
> Isn't there some "run once" thing I can append to mashup.js that will do the same? Maybe just adding System.import('mashup.js') to the end of mashup.js itself?

Seems  to work...

https://codesandbox.io/s/restless-dream-2jmhf?file=/bundle.js&resolutionWidth=320&resolutionHeight=675

Do you know of any subtle adverse side effects to this?

**Comment by joaotavora** [comment]
```js
System.constructor.prototype.instantiate = () => {
  // Only use this custom implementation of instantiate one-time immediately, after this script executes. Resume normal script loading behavior aftewards.
  System.constructor.prototype.instantiate = originalInstantiate;
  return System.getRegister();
};
```

**Comment by joeldenning** [comment]
> Isn't there some "run once" thing I can append to mashup.js that will do the same? Maybe just adding System.import('mashup.js') to the end of mashup.js itself?

Yes, that should work.

> Does System.getRegister rely on instantiate?

No. Your code snippet would work fine - no need to call getRegister before setting instantiate back to originalInstantiate.

**Comment by joaotavora** [comment]
> Yes, that should work.

Indeed it does. For future reference, I'm setting the path passed to the `xhr` in an attribute of the `<script>` element itself, then retrieving that path with `document.currentScript.getAttribute` and passing it to `System.import()`

Closing the issue, thanks.  Feel free to reopen if you think this merits more discussion.
