### ISSUE TITLE
how to use it /

### ISSUE THREAD

**Issue by lili21** [systemjs/systemjs#2318]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [x] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [x] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
No

### Question
any good resource about how to using this? I got a local es module, `./src/test.js`，how to load it in the browser without bundle?

**Comment by joeldenning** [comment]
Hi @lili21, here's a video that might help: https://www.youtube.com/watch?v=AmdKF2UhFzw

SystemJS doesn't load ES modules, but loads System.register, umd, amd, global, and wasm modules. You can read more at https://github.com/systemjs/systemjs/blob/master/docs/module-types.md
