### ISSUE TITLE
sebmck/6to5

### ISSUE THREAD

**Issue by djindjic** [systemjs/systemjs#232]
Hello,

Do you have a plan in the future to support 6to5 insted of traceur compiler?

**Comment by cesarandreu** [comment]
:+1: 

Any new info on this? Very excited about this.

**Comment by guybedford** [comment]
This is currently being tracked in https://github.com/ModuleLoader/es6-module-loader/pull/270.

**Comment by interactionist** [comment]
Thanks @guybedford , this looks pretty cool.

**Comment by guybedford** [comment]
This is already to go pending 6to5 3.0.0 in https://github.com/systemjs/systemjs/pull/333.

**Comment by sebmck** [comment]
Looking to release 3.0.0 tomorrow.

**Comment by douglasduteil** [comment]
Awesome guys :+1: 
Can't wait to try it. !

**Comment by douglasduteil** [comment]
OMG It's working !!! 
:heart:  http://plnkr.co/plARF6 :heart: 
Awesome work @guybedford @sebmck

**Comment by djindjic** [comment]
Rest of civilians are waitig for jspm update :-D

**Comment by interactionist** [comment]
@douglasduteil Looks great – noice mixin of es7. And now jspm …
True engineering @guybedford & @sebmck

**Comment by guybedford** [comment]
Thanks for patience, working on the jspm side of this for very soon.
