### ISSUE TITLE
how to load import-maps again after init??

### ISSUE THREAD

**Issue by SecretCastle** [systemjs/systemjs#2321]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [x] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

init 
```
<head>
   <script type="systemjs-import">
     {
         "imports": {
              "app1": "//localhost:8081/app,js"
         }
      }
   </script>
</head>
```

```
// index.js
// inject method which is rewrite script content and add app2 after app1
inject({
  'app2': '//localhost:8082/app.js'
})

Systemjs.prepareImport(true)
```

but it not work, i read source code 
https://github.com/systemjs/systemjs/blob/f9b43bcdb62b3ddb649dd81858bdc47228044f90/src/features/import-maps.js#L29
and  i found when i call `Systemjs.prepareImport(true)`,  `script.sp` was `true`, and return

how to do that???

**Comment by lili21** [comment]
You need to create a new script tag, with the `systemjs-import` type and the new `import-maps` content.

**Comment by SecretCastle** [comment]
@lili21  好吧，两中国人说啥英文😀
