### ISSUE TITLE
How to import a string as js module in systemjs like window.require can use window.require('blob:xxxx')? 

### ISSUE THREAD

**Issue by 1021683053** [systemjs/systemjs#2322]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Use Default
  - [ ] Transform
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
Global System.import() url or id  like window.require, but window.require can use window.require('blob:xxxx')

In requirejs 
```javascript
public async parseController(controllerCode?: string) {
    return new Promise((resolve, reject) => {
      if (controllerCode) {
        const blob = new Blob([controllerCode], { type: 'application/javascript' })
        const src = URL.createObjectURL(blob)
        window.require([src], (mod) => {
          try {
            const value = interopDefault(mod)
            resolve(value)
          } catch (e) {
            console.error('require controller error:', controllerCode)
            reject(e)
          }
        }, reject)
      } else {
        resolve(null)
      }
    })
  }
```
How to import a string as js module in systemjs?

**Comment by joeldenning** [comment]
Hi @1021683053, you can call `System.import(blobUrl)`. Here's a code sandbox demonstrating it: https://codesandbox.io/s/fragrant-frog-xdjd2?file=/index.html
