### ISSUE TITLE
System.registerDynamic interop / migration

### ISSUE THREAD

**Issue by anhallbe** [systemjs/systemjs#2327]
- SystemJS Version: 6.8.3
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [x] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
We are currently using SystemJS version 0.20.19. The project depends on loading external modules/bundles at runtime that are using the `System.registerDynamic` format. We would like to upgrade to a newer version of SystemJS, but since this format was deprecated and removed, we need a way to either:

1. Transform the modules before they are registered (a `fetch` hook?)
2. Add `registerDynamic` to the System object, and somehow map it to `register`

Question: Is there a recommended migration path for this scenario, or does anybody have any tips on how to implement this?
 
### More context / Current Setup

The dynamically loaded module:
```js
// Script located at https://example.com/a.js

"bundle";
(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    } else if ("function" === "function" && true) {
        System.registerDynamic("some-component.js", ["@angular/core"], false, function ($__require, $__exports, $__module) {
            if (typeof factory === "function") {
                return factory.call($__exports, $__require, $__exports, $__require("@angular/core"));
            } else {
                return factory;
            }
        });
    }
})(function (require, exports) {
    "use strict";

    Object.defineProperty(exports, "__esModule", { value: true });
    exports.SomeComponent = void 0;
    var core_1 = require("@angular/core");
    var SomeComponent = function () {
        function SomeComponent() {
        }
        SomeComponent = __decorate([core_1.Component({
            selector: "some-component",
            template: "the-template",
        })], SomeComponent);
        return SomeComponent;
    }();
    exports.SomeComponent = SomeComponent;
});

(function (factory) {
    if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(require, exports);
        if (v !== undefined) module.exports = v;
    } else if ("function" === "function" && true) {
        System.registerDynamic("some-module.js", ["@angular/common", "@angular/core" "some-component.js"], false, function ($__require, $__exports, $__module) {
            if (typeof factory === "function") {
                return factory.call($__exports, $__require, $__exports, $__require("@angular/common"), $__require("@angular/core"),  $__require("some-component.js");
            } else {
                return factory;
            }
        });
    }
})(function (require, exports) {
    "use strict";

    Object.defineProperty(exports, "__esModule", { value: true });
    exports.SomeModule = void 0;
    var common_1 = require("@angular/common");
    var core_1 = require("@angular/core");
    var some_component_1 = require("some-component.js");
    var SomeModule = function () {
        function SomeModule() {}
        SomeModule = __decorate([core_1.NgModule({
            imports: [common_1.CommonModule],
            declarations: [some_component_1.SomeComponent],
            entryComponents: [some_component_1.SomeComponent]
        })], SomeModule);
        return SomeModule;
    }();
    exports.SomeModule = SomeModule;
});
```

The project that imports the module:
```typescript
System.set("@angular/core", System.newModule(ImportedAngularCore));

function importTheThing(url: string) {
  System.import(url).then( ... )
}
importTheThing("https://example.com/a.js")
```

**Comment by anhallbe** [comment]
Update: I managed to get *some* of it working by adding a custom `registerDynamic`:

```typescript
const systemJsPrototype = System.constructor.prototype;
systemJsPrototype.registerDynamic = (moduleId: string, deps: string[], _requires: boolean, wrappedExecute: RegisterDynamicExecute) => {
	return System.register(deps, (exp, ctx) => {
		const module: System.Module = {};
		const resolvedDeps: Record<string, System.Module> = {};
		return {
			setters: deps.map(depName => depValue => resolvedDeps[depName] = depValue),
			execute: () => {
				const requireFn: (id: string) => System.Module = dep => resolvedDeps[dep];
				wrappedExecute(requireFn, module);
				exp(module);
			}
		}
	})
}
```
Also added import maps instead of the `System.set("dep", System.newModule(TheDep))` calls.

This works well when the imported script only has a single `registerDynamic` call., and the "moduleId" is ignored. However if I include the "moduleId" in the `System.register` call, and add the "named-register" extra (which I think is needed here), I'm getting the following error:

```
TypeError: registration[1] is not a function
```

I'm not sure where to go from here. It appears `arguments` is incorrect below in the named-register extra, where  `register` is called with arguments `"themodule", ["the", "deps"]` rather than `["the", "deps"], declareFn`.

![image](https://user-images.githubusercontent.com/4991954/116712599-4de5d180-a9d4-11eb-8e22-bc780b89ba46.png)

**Comment by anhallbe** [comment]
Another update:
I modified the `named-register.js` extra so that it strips the first argument when calling the original `register`:

```js
  systemJSPrototype.register = function (name, deps, declare) {
    if (typeof name !== 'string')
      return register.apply(this, arguments);
    var define = [deps, declare];
    this.registerRegistry[name] = define;
    if (!firstNamedDefine) {
      firstNamedDefine = define;
      Promise.resolve().then(function () {
        firstNamedDefine = null;
      });
    }
    return register.apply(this, [...arguments].slice(1));   //  <--- Changed
  };
```

With this, I'm not getting the `registration[1] is not a function` anymore and the module loads correctly. I'm not sure if this breaks anything else. But it seems to me like the first argument (module name) should always be stripped here since `register` will throw the error if it is included?

**Comment by joeldenning** [comment]
Hi @anhallbe, the recommended upgrade path is to modify how the modules are compiled so that they use System.register() rather than System.registerDynamic().

The named-register extra can be susceptible to race conditions (calls System.getRegister() in`<script>`'s `load` event, but clears the `lastRegister` inside of a `Promise.resolve()` in hopes that a microtick of the event loop coincides with the `load` event). SystemJS core does not support named registers, which is why the named register extra strips the name before forwarding it on to systemjs core. The named-register stores the names in System.registerRegistry. The error about registration[1] is one you can look up in the Github issues where you'll find lots of people reporting it and myself and others explaining various possible explanations for it.

It sounds like what you have is working for you, so if so there's maybe no need to modify it.

**Comment by anhallbe** [comment]
@joeldenning thanks for the input. Unfortunately we can't really make sure all the modules are re-compiled (backwards-compat mess), but the custom `registerDynamic` seems to work fine for now.

There's one thing I don't understand about the named-register extra, though:
The final line in the register method is:
```
return register.apply(this, arguments);
```
And unless I'm reading it wrong, won't `arguments` always (incorrectly) include the `name` as the first argument? I.e the `name` isn't stripped at all before sending it over to core, causing the error.

Maybe I'm missing something, because obviously the extra appears to work well for some people. And it works fine here: https://codesandbox.io/s/broken-sun-c3xjm?file=/index.html But I don't see how it could ever work?

Example from above link:
![image](https://user-images.githubusercontent.com/4991954/116975273-aad8d480-acbf-11eb-8ded-a5a19c29fafb.png)

**Comment by joeldenning** [comment]
> won't arguments always (incorrectly) include the name as the first argument? I.e the name isn't stripped at all before sending it over to core, causing the error.

Good point! That appears to be a bug. The reason why this doesn't totally break the tests or all use cases is that named-register overrides the `getRegister` hook to return from `registerRegistry`. However, that doesn't cover every circumstance. The fix will be helpful for a lot of people. I've put it together in #2329
