### ISSUE TITLE
SystemJS migrating from v5 to v6 with outFile

### ISSUE THREAD

**Issue by viT-1** [systemjs/systemjs#2336]
### Demonstration
Sorry but not Code Sandbox, only [github project](https://github.com/viT-1/systemjs-ts-es6-vue/tree/d1d72c72daacf8ff740539dcecad99bc66eb34e5) without workaround & problem with relative paths which are ok in v5.0
This project render relative paths for named modules such as
`System.register("common.blocks/IamHeader/IamHeader-conf", ["./IamHeader.html"], function (exports_7, context_7)`
When I try to upgrade to v6 has many errors.

Then I [prepare bundle](https://github.com/viT-1/systemjs-ts-es6-vue/commit/2ea1b0b9d9e0c1cecdb34dd248596fb287d94713#diff-c7aa789f4d6443b4ab1096cb8b13d6351936adc5e99fa8e813b9637fc9aca206R116) by string replacing outFile to absolute paths (it is working ok in v5 & v6).

After second try upgrading to v6 with [running script](https://github.com/viT-1/systemjs-ts-es6-vue/blob/2ea1b0b9d9e0c1cecdb34dd248596fb287d94713/src/index.htm#L27) from v5 I have double initiated entry point (main):
console logged 'SystemJs bundle is loaded!' twice.

For v6 I was forced to [change running script](https://github.com/viT-1/systemjs-ts-es6-vue/commit/49793d558b56779f0c4a380119a223f8b76a18ee#diff-dadd119dd17f99b336705b171f6504e2af781259be16b76414b46d932e52de96). Strange behaviour but it is working now!

### Expected Behavior
Relative paths of named modules should working as they do in 5.0
Activate entry point should be with different function name from [naming bundle file in importmap](https://github.com/viT-1/systemjs-ts-es6-vue/blob/49793d558b56779f0c4a380119a223f8b76a18ee/src/importmap.system.json#L3), not `System.import('main')`, may be `System.run('main')`, because of double activation entry point in v6 (import main & import bundle with main).

PS: May be my project with jest, vue2, decorators & esm deploy with shims for importmaps acceptable for [community projects](https://github.com/systemjs/systemjs#community-projects)? ;)

PPS: It's a pitty, but my project on IE11 have many errors with v5 & v6 (need to investigate) & not supported now =(

**Comment by joeldenning** [comment]
Your project and Github issue are complex and do not have clear steps to reproduce the issue. Please provide a minimal example and give a single set of instructions on how to reproduce the problem. The readme has many paragraphs, and the github issue links to many different commits. It is difficult to diagnose such issues.
