### ISSUE TITLE
module-types.js got error 

### ISSUE THREAD

**Issue by FreezeSoul** [systemjs/systemjs#2342]
if (!process.env.SYSTEM_BROWSER && !baseUrl && typeof process !== 'undefined') {
  var cwd = process.cwd();
  // TODO: encoding edge cases
  baseUrl = 'file://' + (cwd[0] === '/' ? '' : '/') + cwd.replace(/\\/g, '/') + '/';
}

need fix to =>>

if (typeof process !== 'undefined' && !process.env.SYSTEM_BROWSER && !baseUrl)

**Comment by guybedford** [comment]
Thanks, fix released in 6.10.1.
