### ISSUE TITLE
semantic-ui-react TypeError: a is not a function

### ISSUE THREAD

**Issue by Jarreddebeer** [systemjs/systemjs#2355]
- SystemJS Version: 6.10.1
- Which library are you using?
  - [x] system.js
  - [x] s.js (I tried both individually)
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)? N

Simple case: https://github.com/Jarreddebeer/semantic-ui-test

### Question

When I import from 'semantic-ui-react' from a bare-bones app it throws:
```
Uncaught (in promise) TypeError: a is not a function
    at _interopRequireWildcard (interopRequireWildcard.js? [sm]:22)
```

It appers to be from `@babel/runtime@7.15.3/helpers/interopRequireWildcard.js` line 22, which is:
```js
if (obj === null || _typeof(obj) !== "object" && typeof obj !== "function") {
```
Vaguely to me `_typeof`, `_typeof2` and `_typeof3` appear to be undefined, specifically:
```js
import * as _typeof3 from "@babel/runtime/helpers/typeof";

var _typeof2 = "default" in _typeof3 ? _typeof3.default : _typeof3;

var exports = {};
var _typeof = _typeof2["default"];
```

Where `@babel/runtime/helpers/typeof` is from: https://ga.system.jspm.io/npm:@babel/runtime@7.15.3/helpers/esm/typeof.js

I don't have the intuition to debug further. The import-map was created using the generator, and i'm able to get a fairly sized react based app running, just, if I import from semantic-ui-react this error is thrown.

**Comment by guybedford** [comment]
This is a JSPM bug, can you post a new JSPM issue on https://github.com/jspm/project/issues with the exact command used to generate the original import map? Specifically it's likely a conditional resolution generation issue.

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/project/issues/125.
