### ISSUE TITLE
System JS error in Safari Browser issue when trying to load Single-Spa library

### ISSUE THREAD

**Issue by asingh-sys** [systemjs/systemjs#2358]
- SystemJS Version: 6.3.3
- Which library are you using?
  - system.js

Hi, we have observed a recurring issue with Safari browsers (mainly mobile safari) when trying to load Single Spa library. For a lot of these customers, the file throws the following error:

`Error loading "/single-spa.5.8.0.min.js" from "/main.js" (**SystemJS Error#3 https://git.io/JvFET#3**)`

Main.js is our actual application bundle in which Single spa is added as an external module.

This does not happen for other browsers as much (85% Safari browsers). To remediate the issue we also tried to add a preload for the file as below, but it has not helped much.

`<link href="/single-spa.5.8.0.min.js" rel="preload" as="script">`

Any suggestions about what could be the problem between the Safari Browser and loading Single-Spa library?

Thanks!

PS: Same query raised under Single-spa : https://github.com/single-spa/single-spa/issues/883

**Comment by joeldenning** [comment]
Closing in favor of #883
