### ISSUE TITLE
System.prepareImport blocks until all importmap request are fulfilled

### ISSUE THREAD

**Issue by StanislavVoronov** [systemjs/systemjs#2368]
### Demonstration
I add importmap dynamically with System.createScript and add it with document.head.appendChild. 
Then I use System.prepareImport to fetch all importmap json files. There is a problem. If one of them is pending (with fiddle for example), prepare import blocks until all request will fulfilled, althrouth some importmap have already finished download

Code Sandbox: 

### Expected Behavior
System.prepareImport doesn't block

### Actual Behavior

**Comment by joeldenning** [comment]
SystemJS cannot load modules until it has downloaded all import maps because every import map can affect the resolution of bare specifiers to full URLs. For this reason, systemjs waits for all import maps to finish loading before proceeding to load modules.
