### ISSUE TITLE
Error Dynamic Import 

### ISSUE THREAD

**Issue by solangeDev** [systemjs/systemjs#2370]
I try implementing import dynamic but I have the next error

(property) Document.currentScript: HTMLOrSVGScriptElement | null
Returns the script element, or the SVG script element, that is currently executing, as long as the element represents a classic script. In the case of reentrant script execution, returns the one that most recently started executing amongst those that have not yet finished executing.

Returns null if the Document is not currently executing a script or SVG script element (e.g., because the running script is an event handler, or a timeout), or if the currently executing script or SVG script element represents a module script.

Object is possibly 'null'.ts(2531)

this is my function ======>
toggleButton(tag: string): void {
    const im = document.createElement('script');
    im.type = 'importmap';
    im.textContent = JSON.stringify({
      imports: {
        "reactwc": "./assets/direflowBundle.js"
      },
    });
    console.log(im);
    document.currentScript.after(im);
    // console.log('aqui', tag);
  }

**Comment by joeldenning** [comment]
There's no question or error report here, so I don't understand what you're looking for. I'm closing this since there's no action I can take, but feel free to comment further with a clear question and/or bug report.
