### ISSUE TITLE
How to re-export from current env ?

### ISSUE THREAD

**Issue by wenerme** [systemjs/systemjs#2371]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [x] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

I want to use the systemjs in bootstrap module, want to re-export the common module from bootstrap module, like

```js
import 'systemjs';
import 'systemjs/dist/extras/named-register';
import 'systemjs/dist/extras/named-exports';
import 'systemjs/dist/extras/module-types';
import 'systemjs/dist/extras/dynamic-import-maps';
import * as ReactModule from 'react';
import { jsxs, jsx, Fragment } from 'react/jsx-runtime.js';
export function useSystem() {
  System.register('react', [], (exports) => ({
    execute: () => {
      console.log('React', ReactModule);
      exports(ReactModule);
    },
  }));

  System.register('react/jsx-runtime', [], (exports) => ({
    execute: () => {
      exports({ jsxs, jsx, Fragment });
    },
  }));

  return System;
}
```

Use systemjs in bootstrap module makes dev easier, any suggest on how to do this properly ?

**Comment by joeldenning** [comment]
Using `System.set()` is the way I prefer to do it, but named registers can also work:

```html
<!-- The urls in the import map won't actually be downloaded if you call System.set() before loading those modules -->
<script type="systemjs-importmap">
{
  "imports": {
    "react": "/react.js",
    "react/jsx-runtime": "/react-jsx-runtime.js"
  }
}
</script>
```
```js
import * as React from 'react';
import * as jsxRuntime from 'react/jsx-runtime';

System.set(System.resolve('react'), React);
System.set(System.resolve('react/jsx-runtime'), jsxRuntime);
```

Closing because I think I've answered the question, but feel free to comment further or reopen.
