### ISSUE TITLE
Package.json main points to node version which messes up import on browser

### ISSUE THREAD

**Issue by northkode** [systemjs/systemjs#2373]
when I use SystemJS from npm install it defaults to the node version which breaks.

How do i import non node version?

**Comment by erikt9** [comment]
One of the files under `dist` (e.g., `import systemjs/dist/system.js`) is what you would use.

**Comment by joeldenning** [comment]
Thanks @erikt9, yes that import is the way to import the browser version of SystemJS. Closing this issue since the question has been answered.
