### ISSUE TITLE
Dynamic import only gets the first module

### ISSUE THREAD

**Issue by dsuryd** [systemjs/systemjs#2377]
I use `System.import` as shown below.  Only the first module gets loaded.  The network log only shows one fetch, and no exception is thrown.

index.html:
```html
    ...
    <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.js"></script>
    <script>
      System.import("/module1.js").then(m => (document.getElementById("mod1").innerText = m.default()));
      System.import("/module2.js").then(m => (document.getElementById("mod2").innerText = m.default()));
    </script>
  </head>
  <body>
    <div id="mod1"></div>
    <div id="mod2"></div>
  </body>
```

module&lt;x&gt;.js:
```ts
export default function() { return "MODULE <x>"; }
```

### Expected output:

MODULE 1
MODULE 2

### Actual:

MODULE1

https://github.com/dsuryd/systemjs-import-issue

**Comment by joeldenning** [comment]
This was caused by loading webpack UMD bundles without using SystemJS' amd.js extra. I've created the PR below that shows the fix

https://github.com/dsuryd/systemjs-import-issue/pull/1
