### ISSUE TITLE
System.import returns empty module

### ISSUE THREAD

**Issue by brandones** [systemjs/systemjs#2379]
- SystemJS Version: 6.11.0
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [x] AMD extra
  - [x] Named Exports
  - [x] Named Register
  - [ ] Transform
  - [x] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

This might be a bug, but I think I will need help debugging before I'd be able to produce a minimum reproduction.

#### Summary

When providing an import map override for a module using module federation and being served with webpack-dev-server, `System.import(thatModule)` always resolves to an empty object. This module has the same webpack configuration as other modules, which don't have the same problem.

#### Details

I have an application using [import-map-overrides](https://github.com/joeldenning/import-map-overrides). Using it, I create a new `systemjs-importmap` entry to add [@openmrs/esm-patient-chart-app](https://github.com/openmrs/openmrs-esm-patient-chart/tree/master/packages/esm-patient-chart-app) (and [@openmrs/esm-login-app](https://github.com/openmrs/openmrs-esm-core/tree/master/packages/apps/esm-login-app) just for comparison) running from webpack-dev-servers.

```html
<script type="systemjs-importmap" id="import-map-overrides" data-is-importmap-override="">{
  "imports": {
    "@openmrs/esm-patient-chart-app": "//localhost:8081/openmrs-esm-patient-chart-app.js",
    "@openmrs/esm-login-app": "//localhost:8082/openmrs-esm-login-app.js"
  },
  "scopes": {}
}</script>
```

both modules use the same [webpack configuration](https://github.com/openmrs/openmrs-esm-core/blob/master/packages/tooling/openmrs/default-webpack-config.js), which is using webpack module federation. Some key points of the webpack config, I think, include:

```js
    entry: {
      [name]: "systemjs-webpack-interop/auto-public-path",
    },
    output: {
      libraryTarget: "system",
      publicPath: "",
      path: resolve(root, outDir),
    },
    plugins: [
      new ModuleFederationPlugin({
        name,
        library: { type: "system", name },
        filename,
        exposes: {
          app: srcFile,
        },
        shared: Object.keys(peerDependencies).reduce((obj, depName) => {
          obj[depName] = {
            requiredVersion: peerDependencies[depName],
            singleton: true,
            import: depName,
            shareKey: depName,
            shareScope: "default",
          };
          return obj;
        }, {}),
      }),
```

The JS returned at `//localhost:8081/openmrs-esm-patient-chart-app.js` and `//localhost:8082/openmrs-esm-login-app.js` is approximately the same, and are here:

[openmrs-esm-patient-chart-app.js.txt](https://github.com/systemjs/systemjs/files/7866925/openmrs-esm-patient-chart-app.js.txt)
[openmrs-esm-login-app.js.txt](https://github.com/systemjs/systemjs/files/7866926/openmrs-esm-login-app.js.txt)

Both start with

```js
System.register("@openmrs/esm-patient-chart-app", [], function(__WEBPACK_DYNAMIC_EXPORT__, __system_context__) {
```

and eventually have something like

```js
/*!***********************!*\
  !*** container entry ***!
  \***********************/
/***/ ((__unused_webpack_module, exports, __webpack_require__) => {

"use strict";
var moduleMap = { ... };
var get = (module, getScope) => { ... };
var init = (shareScope, initScope) => { ... };

// This exports getters to disallow modifications
__webpack_require__.d(exports, {
	get: () => (get),
	init: () => (init)
});
```

Where `get` and `init` are familiar to me as the functions that I expect to be present on the object I receive from `System.import`.

In the browser console:

```
System.import("@openmrs/esm-login-app").then(n => console.log(n));
VM2467:1 Module {Symbol(Symbol.toStringTag): 'Module', get: ƒ, init: ƒ}
```

This module has the right functions on it.

```
System.import("@openmrs/esm-patient-chart-app").then(n => console.log(n));
VM2475:1 Module {Symbol(Symbol.toStringTag): 'Module'}
```

This module is empty. The import doesn't fail, but simply resolves to nothing.

The two overrides don't seem to interact with each other—`esm-patient-chart-app` always fails and `esm-login-app` always works, regardless of whether the other is there.

That's as far as I got with debugging. I figure the next step is to start instrumenting SystemJS. But I wanted to file this issue first in case there might be easier answers or things to check.

**Comment by joeldenning** [comment]
I'll read through the full details either later today or some other time, but my first impression is to just stop using named SystemJS registers. In other words, do `System.register([], ...) {` rather than `System.register("@openmrs/esm-patient-chart-app", [], ...) {`. This can be configured via the `library` option in webpack - you should unset that to be undefined and then webpack will generate a bundle that isn't named. See https://webpack.js.org/configuration/output/#outputlibraryname for details about this.

**Comment by joeldenning** [comment]
Okay I read through the issue in more detail, and there's not quite enough to fully diagnose things but my initial suggestion still  stands. A large portion of systemjs issues disappear entirely when not using named registers. The empty module is something I've seen before, but can be complicated to diagnose. A self contained example, or clear and easy instructions to demonstrate, would help in fully diagnosing this.

**Comment by brandones** [comment]
Okay, thank you @joeldenning , I'll give that a try!

**Comment by Paramesh-C** [comment]
Able to replicate the same issue with assets generated for Single-SPA. Possibly my comment won't have enough details (due to propriety code) to help you debug this further. 

   "core-js": "3.21.1",
    "single-spa": "5.8.0",
    "systemjs": "6.0.0",
    "zone.js": "0.11.4"

`
sspa-apps.js:2 single-spa minified message #37: See https://single-spa.js.org/error/?code=37&arg=application&arg=DemoMultipleSSPAApps&arg={} 
Module {Symbol(Symbol.toStringTag): 'Module'}
Symbol(Symbol.toStringTag): "Module"
`

**Comment by brandones** [comment]
So I spent a day or so trying to get rid of named registers and didn't get it. I think I have a fundamental conceptual gap: how is `foo` supposed to import `bar` if `bar` doesn't have a name? In our app, we go through each entry in the import map and call `System.import` for each one. Without named registers, `System.import` is apparently not available. How can my app shell import things from the importmap without named registers? Isn't the "key" of each module in an importmap the "name" by which it must be referred to?

**Comment by brandones** [comment]
I have, in any case, produced a minimal reproduction of the bug described by this issue.

https://github.com/brandones/systemjs-issue-2379-repro

**Comment by asika32764** [comment]
FYI 

I Just import axios and will reproduce same issue.

![screenshot 2022-04-18 下午4 15 12](https://user-images.githubusercontent.com/1639206/163779039-015d246c-82be-4678-af08-b63225fa76b3.jpg)

SystemJS@6.12.1

**Comment by Paramesh-C** [comment]
> So I spent a day or so trying to get rid of named registers and didn't get it. I think I have a fundamental conceptual gap: how is `foo` supposed to import `bar` if `bar` doesn't have a name? In our app, we go through each entry in the import map and call `System.import` for each one. Without named registers, `System.import` is apparently not available. How can my app shell import things from the importmap without named registers? Isn't the "key" of each module in an importmap the "name" by which it must be referred to?

In my implementation I avoid using import maps, rather use the actual URL of the system module js to be imported. System.import('system_module_url').

I had the same issue with using system imports for amd modules, I had to change webpack configuration and library target to **system** to make it work and on doing so the module will have empty unnamed register **System.register([], ...)** as mentioned on previous comment.

**Comment by Paramesh-C** [comment]
> I have, in any case, produced a minimal reproduction of the bug described by this issue.
> 
> https://github.com/brandones/systemjs-issue-2379-repro

I'm not entirely sure about webpack-interop module but my approach doesn't require import maps and uses the publicpath of the system js module to be imported. I made some changes to the project to make the imported setup function to work. 

1. Change module project's webpack config's entry to [name]: "./src/helloWorldPage.tsx", and remove **name** in output target.
2. Add @swc/cli and @swc/core in module package.json for transpiling.
3. In shell project, change Object.keys(importMap.imports) to Object.**values**(importMap.imports) in index.ts. This will use the url to import instead of mapped name. Imports amd, named-exports, named-register, use-default are not required.

I will leave it for @joeldenning to confirm the approach.

**Comment by brandones** [comment]
Got it, thank you @joeldenning . In actual OpenMRS modules' [webpack config](https://github.com/openmrs/openmrs-esm-core/blob/a214e7445f7b1c3ddd8ca39453a0316fefc5dd5b/packages/tooling/webpack-config/src/index.ts#L110) we have that entry line:

```js
    entry: {
      [name]: "systemjs-webpack-interop/auto-public-path",
    },
```

Oddly, it mostly seems to work. I have no idea how or why it works when it does. I don't know what constitutes a valid vs invalid usage of `"systemjs-webpack-interop/auto-public-path"`. However, when I replace it with 

```js
    entry: {
      [name]: srcFile,
    },
```

I start getting Module Federation errors:

> Failed to load module @openmrs/esm-patient-chart-app Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/@openmrs/esm-framework/@openmrs/esm-framework

Where `@openmrs/esm-framework` is "shared" via Module Federation between the [app shell](https://github.com/openmrs/openmrs-esm-core/blob/a214e7445f7b1c3ddd8ca39453a0316fefc5dd5b/packages/shell/esm-app-shell/webpack.config.js#L228) and [all modules](https://github.com/openmrs/openmrs-esm-core/blob/a214e7445f7b1c3ddd8ca39453a0316fefc5dd5b/packages/tooling/webpack-config/src/index.ts#L183). Associated with a network request for a non-existent file `vendors-openmrs-esm-core_node_modules_react_index_js.js`.

Anyway I suspect that this has nothing to do with SystemJS and is just a Module Federation configuration problem, and that this issue can be closed. Thanks very much for the help, @joeldenning and @Paramesh-C .

**Comment by Paramesh-C** [comment]
Thanks @joeldenning. In one of my project, I'm actually importing by URL instead of import maps. Since you are not recommending to use URL directly, is there any specific reason (like a vulnerability or performance degradation) on importing such way ?

**Comment by brandones** [comment]
@Paramesh-C I think that Joel was merely hypothesizing that the problem I was experiencing might have been caused by named-registers. Not that there is any particular problem with named registers generally. As explained above, it turned out that my problem was caused by a bad webpack configuration.
