### ISSUE TITLE
On-demand dynamic imports for SystemJS dependencies

### ISSUE THREAD

**Issue by anhallbe** [systemjs/systemjs#2380]
- SystemJS Version: 6.11.0
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [x] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?
No, but I'm looking to add/use one.

### Question
We have an Angular app that uses systemjs to dynamically load components from an external service. These components should re-use modules that are known by our app. Some modules are already imported with the app, e.g `"@angular/core"`, while some should be loaded "on-demand".

The modules can be imported in the application with a known path, e.g `const dynamicallyImported = await import("dep")`. But I'm trying to make sure that the `import("dep")` is only executed when "dep" is needed by one of the dynamic components.

Example:
```ts
// App code
const component = System.import("https://example.com/component.js");


// component.js
System.register("component", ["@angular/core", "on-demand"], (_export) => {
  let angularCore;
  let onDemand;

  return {
    setters: [
      value => angularCore = value,
      value => onDemand = value,
    ],
    execute () {
      // code that uses angularCore and onDemand
    }
  };
});
```

We are already able to get this to work when the dependencies are available when registering the modules, like so:
```ts
// App code
import * as angularCore from "@angular/core";

System.register("@angular/core", [], (_export) => {
  return {
    execute () {
      _export(angularCore);
    }
  };
});
```

However, I can't figure out how to get the dynamic import to work. I tried the following
```ts
// App code
System.register("on-demand", [], (_export) => {
  return {
    async execute () {
      const onDemand = await import("on-demand");
      _export(onDemand);
    }
  };
});
```

...expecting the async `execute()` to finnish before the component's `execute()` starts, but this does not seem to be the case.

**Question 1:** Am I missing something about the async execute that makes this not work?
**Question 2:** Is there another (better) way to hook into the internal imports?

**Comment by anhallbe** [comment]
Update:
I solved this using import maps and an `instantiate` hook instead which performs the import, instead of the named register. This seems to work fine for now, although I still don't understand why the async execute above wouldn't work.

**Comment by brandones** [comment]
Hi @anhallbe , can you elaborate a bit more on your solution, or link to some code? I'm trying to solve this exact same problem (which you've stated very nicely).
