### ISSUE TITLE
How to update systemjs from 0.20 to 6.x in vue project

### ISSUE THREAD

**Issue by huijie6** [systemjs/systemjs#2409]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [x] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

**Comment by huijie6** [comment]
With systemjs 0.20.18 in vue project, **SystemJS.import()** is effective.
But when I update it to 6.2.5, **System.import()** is invalid.
So I want to ask for help, what can I do to make it work?

**Comment by guybedford** [comment]
@huijie6 it may be advisable to first try the 0.21 upgrade, with the 0.21 release details here - https://github.com/systemjs/systemjs/releases/tag/0.21.0 specifically the AMD interop changed to use the `{ default: module }` form. Following the release notes for each major release you can see if breaking changes affected you. It's a big version difference certainly.

**Comment by huijie6** [comment]
Thank you. But the 0.21 is not in the preferred library of my company. I have to find a way to use the 6.x.

**Comment by guybedford** [comment]
@huijie6 yes you can upgrade to 6.x but for large major upgrades it can be recommended to do them incrementally by each major, carefully reading the major release notes, rather than all at once.

**Comment by huijie6** [comment]
Thank you very much. I will have a try.
