### ISSUE TITLE
[QUEST] Less Plugin

### ISSUE THREAD

**Issue by amcdnl** [systemjs/systemjs#241]
I see you have a CSS plugin ( https://github.com/systemjs/systemjs#plugins ) but do you plan on adding a LESS plugin too?

I know you maintain https://github.com/guybedford/require-less so seemed like a obvious plugin for system to have.

**Comment by guybedford** [comment]
Closing as this is a community task not a SystemJS one.

**Comment by amcdnl** [comment]
I took Justin's plugin and abstracted it from steal to a single plugin file and updated it for some of the newer LESS engine API.  Note: Still experimenting with builds for this.

https://gist.github.com/amcdnl/b5df9e02ef005fd9c047

**Comment by justinbmeyer** [comment]
@amcdnl We might extract our less into its own project system-less.  We have a need for some other features (like compiling every less in its own context) ... want to work together on it?
