### ISSUE TITLE
`/dist` files in git repo?

### ISSUE THREAD

**Issue by nilzona** [systemjs/systemjs#2417]
hey @guybedford 

I am curious to know why the files in the files `/dist`  are checked into the git repo.

It's especially curious because `dist` is present in the `.gitignore` file :)

When I work with the project (in a fork) I get conflicts on these files that I think are unnecessary.

**Comment by guybedford** [comment]
It's purely historical. Current pattern is to only build dist on release commits. Can definitely be changed in a major.
