### ISSUE TITLE
Chain of TLA dependencies does not run setter correctly

### ISSUE THREAD

**Issue by nilzona** [systemjs/systemjs#2423]
### Demonstration

When importing an async module that depends on and re-exports something from another async module the setters are never run and re-exporting does not work.

https://codesandbox.io/s/systemjs-async-race-condition-mxf6q8?file=/index.html

**Comment by guybedford** [comment]
Thanks for finding this case!  A good start may be to put together the test case explicitly as a PR to the repo, then hopefully someone can assist in trying to work on a fix.

**Comment by nilzona** [comment]
never mind ... I misspelled `setters` and `setter`  🙈
