### ISSUE TITLE
expose applyImportMap for system.js

### ISSUE THREAD

**Issue by wenerme** [systemjs/systemjs#2428]
### Description of Proposed Feature

system-node.js has a applyImportMap export, for program controlled import make, and api is easier that insert a tag and wait prepareImport 

### In what way would you use it?

like there is already systemJSPrototype.prepareImport, how about systemJSPrototype.applyImportMap=extendImportMap ?

**Comment by guybedford** [comment]
I'd be open to exposing this if you want to create a PR.
