### ISSUE TITLE
Issue utilizing SystemJS and import-maps

### ISSUE THREAD

**Issue by SomethingSexy** [systemjs/systemjs#2437]
Looking at this [sandbox example](https://jspm.org/sandbox#H4sIAAAAAAAAA51UXW/aMBR976+4y15AapKmXbeJBQSlrCqCqiOttj06iQG3/pJ9gaFp/32OE1DpWlXaQxLl+vr4nHOvb/quVAVuNYUlCt47SncfSsreEUAqKBIolsRYit1ghfPwc+AXkCGnvRklBUKGxCA1aVwH9/skEbQbrBndaGUwgEJJpNLhbFiJy25J16ygof85BiYZMsJDWxBOu4k7JY1rGmmuyq1HfReG7gMwzm6ncEUlNQSVgWtR4cOUaL86KhnC/WzScaJQ204cL3ap0YPVImIqfj89vVn+vLp4vBzpm7vh+Ww4PB9Phno8+X6tButRcTk9Sy5vv00H+dpul3YxGDjsMPQ0bGGYRqh86wZ2a5GKBxsyz0IQ7Q367akEddAGnSbgQqbyzAWCPTsS1SB7dlKLjk/rJ5+ikyiJmSzpL7cceJA/xzW4LZSmB9ivQz7Jcnkqf6AFhsRatpBvczlI73+Ikn8oOVJHu3f1pHFtUmVFUznIPPA460C20t4W4IqUTC5AqHLFqQVNzVwZQSTyresIIJxDbtTGUmMhJ8UjoILrUZJAq6SaSr9ZSeAsN8RswdbA7WeVsqboviFxV8b+xyg5dfJKZjG2kWCy0th7Sc+9LJQQrqH3yuCC5NQxplxtwAkBIp2KsFEAowymXijEcOeaJ6vZxa6ff4C7DbBR5nHu9kY7/tUx/yEizCse/ZPobK/kYOVQUnPY7ryvjjdSi87azqGPPV/iWmxUd3araed2hEsqWwK6veqaW8VpxNWiJdrtL6+0w8TVvjKIaO34wJw5XzaGoRsRVekdHjSXK2j6A3xvIKgV6hVCa80IzBTnK+2sjxvzn1rbfsnHZ9e2hg5qe2suz71J43oCuYHkx+NfkXMXnDYFAAA=) the script tag to load SystemJS 

```<script src="https://ga.system.jspm.io/npm:systemjs@6.12.1/dist/s.min.js"></script>``` 

is being wrapped with `System.Register`, which it fails to find `System` because that does not exist yet.

```
s.min.js:1 Uncaught ReferenceError: System is not defined
    at s.min.js:1:1
```

Did something change recently with how this is being loaded and returned?  This seemed to start failing a few hours ago.

**Comment by guybedford** [comment]
This was a CDN configuration issue due to switching to a new CDN on JSPM. Thanks for reporting, it should be working now.
