### ISSUE TITLE
Unable to resolve bare specifier '@ambevtech/wms-push-notification-react-client'

### ISSUE THREAD

**Issue by AlexandreAkao** [systemjs/systemjs#2441]
Hello guys
I'm facing this error:
![image](https://user-images.githubusercontent.com/40917812/197611523-961ad8d3-3f2e-43b9-990a-5d8554bd03ed.png)

But `@ambevtech/wms-push-notification-react-client` is only used in one micro frontend, I don't wanna share it with other micro frontends.

I know that probably will solve if I add this `@ambevtech/wms-push-notification-react-client` on import-map, but it is a private dependency that requires authentication.

This is my import-map:
![image](https://user-images.githubusercontent.com/40917812/197617357-36a7eb50-af4d-4960-bef4-d1f6db9c08fb.png)

Does anyone know how to solve this?

Thanks for the help :)

**Comment by nilzona** [comment]
My guess is that you're building `@ambevtech/wms-push-notification-react-client` with webpack and that you have declared every dependency starting with `@ambevtech/` as external with a regex in the `external` property of your webpack-config.js.

Anyhow .. this is not an issue with SystemJS and you're probably better off asking for help in the `single-spa` community.

**Comment by AlexandreAkao** [comment]
> My guess is that you're building `@ambevtech/wms-push-notification-react-client` with webpack and that you have declared every dependency starting with `@ambevtech/` as external with a regex in the `external` property of your `webpack-config.js` which means that they are expected to be in the import-map.
> 
> Anyhow .. this is not an issue with SystemJS and you're probably better off asking for help in the `single-spa` community.

Yeah you are right, tks for your support, helps a lot.
