### ISSUE TITLE
How to register a module by API

### ISSUE THREAD

**Issue by YangYongAn** [systemjs/systemjs#2459]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [x] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
In my project , I use `react/jsx-runtime` in webpack . but some component build with swc ,  I want want share my project's 'react/jsx-runtime' to outer build :
```js
import { jsx, jsxs } from 'react/jsx-runtime'

window.React = React;
(window as any).__ = {
  jsx,
  jsxs
}

```

and  how to register the 'react/jsx-runtime'  in my code use Systemjs API ?

I try to do like this but not working:

```js
System.set('react/jsx-runtime', {
  exportedFunction: __
});
```

and  

```js
System.register('react/jsx-runtime', [], function(_export, _context) {
  const jsx = __.jsx;
  const jsxs = __.jsxs;
  _export({ jsx, jsxs });
});
```

I just **DO NOT** want to creat a js file . Is that possible?

**Comment by YangYongAn** [comment]
I use this code is working:
```
System.addImportMap({
  "imports": {
    "react/jsx-runtime": "./static/systemjs/react/jsx-runtime.js",
  }
})
```

but I don't want to use js file .I want reg the module in my bundle

**Comment by tbrannam** [comment]
You are looking for this doc https://github.com/systemjs/systemjs/blob/main/docs/api.md#systemsetid-module---module

basically you must register a 'bare-specifier' to a app specific url- then you register the app specific url to an object that implements the interface.

**Comment by YangYongAn** [comment]
> You are looking for this doc https://github.com/systemjs/systemjs/blob/main/docs/api.md#systemsetid-module---module
> 
> basically you must register a 'bare-specifier' to a app specific url- then you register the app specific url to an object that implements the interface.

THX，I try to use `System.set` and `System.addImportMap` to resolve the module which in bundle like a 'bare-specifier', It's works well ！

```ts
import 'systemjs'

import * as React from 'react'
import * as ReactDOM from 'react-dom'
import * as classnames from 'classnames'
import * as reactRedux from 'react-redux'
import * as jsxRuntime from 'react/jsx-runtime'
import * as axios from 'axios'

import * as cards from '../card/shared'

vpa.__shared.cards = cards

const shredNS = 'vpa://'

vpa.__shared.NS = shredNS

const sharedMap = {
  react: React,
  'react-dom': ReactDOM,
  classnames,
  'react-redux': reactRedux,
  'react/jsx-runtime': jsxRuntime,
  axios,
  '@cards': cards
}

exposeModule(sharedMap, shredNS)

export function exposeModule (sharedMap, sharedNS) {
  const imports = {}

  for (const name in sharedMap) {
    imports[name] = `${shredNS}${name}`
    System.set(`${shredNS}${name}`, createMod(sharedMap[name]))
  }

  System.addImportMap({ imports })

  function createMod (mod) {
    return {
      default: mod,
      __useDefault: true,
      __esModule: true,
      ...mod
    }
  }
}
```
