### ISSUE TITLE
system.min.js doesn't include latest version

### ISSUE THREAD

**Issue by JennerChen** [systemjs/systemjs#2474]
@guybedford #2460   latest version 6.14.2 still not working.  maybe need release new one.
system.min.js  still use old one 
![image](https://github.com/systemjs/systemjs/assets/5472912/36a98aa2-c2ec-456a-959a-9a9c68983d5a)
https://g.alicdn.com/code/lib/systemjs/6.14.2/system.min.js

system.js is correct 
![image](https://github.com/systemjs/systemjs/assets/5472912/1b9854a1-2eb1-4fa5-9264-b145c93421c8)
https://g.alicdn.com/code/lib/systemjs/6.14.2/system.js

**Comment by guybedford** [comment]
Turns out this was a Terser optimization issue where it was converting the array into the string form as an unsafe optimization.

Fixed in 6.14.3, thanks.
