### ISSUE TITLE
Should consumers be aware of `process.env.SYSTEM_PRODUCTION` 

### ISSUE THREAD

**Issue by tbrannam** [systemjs/systemjs#2486]
- SystemJS Version: 
- Which library are you using?
  - [ ] system.js
  - [ ] s.js
  - [x] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question

In the distribution file `system-node.cjs` there exists references to the environment variable `process.env.SYSTEM_PRODUCTION` which triggers some conditional code.   

Should consumers be defining this value, at build time or runtime?

**Comment by internettrans** [comment]
I believe `SYSTEM_PRODUCTION` is removed via `@rollup/plugin-replace`

https://github.com/systemjs/systemjs/blob/9647576d43294e938ddae8fe231beb62255f4e46/chompfile.toml#L31
