### ISSUE TITLE
difference in phone

### ISSUE THREAD

**Issue by yinkeli** [systemjs/systemjs#2495]
- SystemJS Version: 
- Which library are you using?
  - [√ ] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [√ ] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
When I use systemjs(v6.12.1) to import a module, the module is imported normally on the Android phone, but not on the iOS device.

![image](https://github.com/user-attachments/assets/8f278503-77b0-416b-8a51-459deddee815)
![image](https://github.com/user-attachments/assets/3cb86e8d-afdf-4e2a-b6a9-68d899f6043a)

**Comment by internettrans** [comment]
The same issue was created twice, closing this one in favor of #2496
