### ISSUE TITLE
Please help analyze how this problem arises.

### ISSUE THREAD

**Issue by yinkeli** [systemjs/systemjs#2496]
- SystemJS Version: 
- Which library are you using?
  - [x] system.js
  - [ ] s.js
  - [ ] system-node.cjs
- Which extras are you using?
  - [ ] AMD extra
  - [ ] Named Exports
  - [ ] Named Register
  - [ ] Transform
  - [ ] Use Default
  - [ ] Global
  - [x] Dynamic Import Maps
- Are you using any [custom hooks](/docs/hooks.md)?

### Question
When I use systemjs(v6.12.1) to import a module, the module is imported normally on the Android phone, but not on the iOS device.Please help analyze how this problem arises.
![image](https://github.com/user-attachments/assets/ae2128ae-9069-4a1c-bef9-0987ce324d62)
![image](https://github.com/user-attachments/assets/3d064714-d8b1-44f7-abf8-f7b99344a87d)

**Comment by internettrans** [comment]
More information needed, or a way to reproduce the problem

**Comment by yinkeli** [comment]
> More information needed, or a way to reproduce the problem

hello,The following figure shows how to use the systemjs to import required modules in the vue2 project. The xDesignerRender module can be imported on both PCs and Android phones. However, the parameters in the callback function after the import on iOS devices are not expected.
![image](https://github.com/user-attachments/assets/4ef9a793-584d-4017-a11d-48e89a71e6aa)

**Comment by internettrans** [comment]
Please provide a way to replicate the issue - a code sandbox or repo or zip file

**Comment by yinkeli** [comment]
> Please provide a way to replicate the issue - a code sandbox or repo or zip file

This problem was found internally, it is difficult for me to provide a duplicate demo, but I try a lower version of systemsjs such as 0.21.6, which is different from v6.12.1, can I use a lower version of systemsjs but do not need amd module but global module?

**Comment by yinkeli** [comment]
> Please provide a way to replicate the issue - a code sandbox or repo or zip file

`System.config({
        map: {
          'vue': '@empty', 
            'Vue': '@empty'
        },
})`  
In addition to this configuration, what else needs to be configured to allow systemjsv0.21.6 to use the window.Vue object when loading components?

**Comment by internettrans** [comment]
>  can I use a lower version of systemsjs but do not need amd module but global module

SystemJS 0.21 is very different from SystemJS 6. I wouldn't expect the migration to be easy

**Comment by yinkeli** [comment]
> > can I use a lower version of systemsjs but do not need amd module but global module
> 
> SystemJS 0.21 is very different from SystemJS 6. I wouldn't expect the migration to be easy

Okay, thank you for your response. I don't have a reproducible demo here at the moment, but I have achieved the desired effect using the 0.21.6 version, although there may be some hidden issues.

**Comment by internettrans** [comment]
Is `x-designer-renderer.min` a publicly accessible javascript file or npm package? What module format is it in?

**Comment by yinkeli** [comment]
> Is `x-designer-renderer.min` a publicly accessible javascript file or npm package? What module format is it in?

This is our own component, which has been built and packed into a UMD module as a static resource on the server.

**Comment by internettrans** [comment]
Switching from UMD to System.register format might fix things for you. UMD format requires the amd.js systemjs extra and often leads to complications that are avoided with System.register format.
