### ISSUE TITLE
SystemJS sometimes fails to load Traceur before importing modules

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#254]
I am seeing a race condition whereby, sometimes, SystemJS does not load Traceur before it imports my ES6 module:

```
 Uncaught TypeError: undefined is not a function
thinking.html:715 Uncaught TypeError: Error loading "js/all" at http://www.uat.brightnorth.co.uk/js/all.js
Include Traceur for module syntax support
thinking.html:764 Uncaught TypeError: Error loading "js/thinking" at http://www.uat.brightnorth.co.uk/js/thinking.js
Include Traceur for module syntax support
```

This will happen the majority of the time when my browser cache is disabled.

I haven't yet been able to put together a test case. Do you have any guesses what might be the problem?

**Comment by guybedford** [comment]
Closing for now, but please report back if you see this again.
