### ISSUE TITLE
Automatically load Traceur runtime

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#258]
Just like we detect when we need Traceur, we can detect if we need Traceur runtime if the format is determined to be `register`, we run a regex to see if `$traceurRuntime` is present in the source and then load it.

**Comment by martinmicunda** [comment]
@guybedford `traceur-runtime` is auto loaded in development environment ok however when I am creating sfx bundle I am getting follow error

```js
Uncaught ReferenceError: $traceurRuntime is not defined
```

I have to manually add `traceur-runtime` when I am creating sfx bundle to fix this problem so it seems like when I am creating sfx bundle the `systemjs` doesn't automatically load `traceur-runtime`

> NOTE: I am using latest `systemjs` and `systemjs-builder`

**Comment by guybedford** [comment]
@martinmicunda thanks I've created an issue for this at https://github.com/systemjs/builder/issues/46.
