### ISSUE TITLE
Plugin in `path`

### ISSUE THREAD

**Issue by dtinth** [systemjs/systemjs#259]
So far my experience with jspm.io and SystemJS has been very pleasant, thanks for creating this project!

I found some unexpected behavior here: you can see that `components/*` has been mapped to `.jsx` path (to represent React components).

``` javascript
System.config({
  "paths": {
    "*": "app/lib/*.js",
    "app/*": "app/*.js",
    "components/*": "app/components/*.jsx!",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

The behavior I expect is that the `.jsx` file is loaded and preprocessed with `jsx` plugin. Instead, it tries to load the `.jsx!` file and results in 404.

**Comment by trusktr** [comment]
+1, would be nice and intuitive.
