### ISSUE TITLE
Allow SystemJS to load in the browser within NPM

### ISSUE THREAD

**Issue by justinbmeyer** [systemjs/systemjs#267]
After being inspired by RaveJS, I want to make an extension that makes it possible to load npm modules by reading package.json. I think there's a desire to do everything in node_modules because NPM is superior to bower in many ways.

But, I can't make this work because `system.js` doesn't work when loaded within `node_modules`.  This is because the path to es6ml is wrong.

Would you consider a fix that looked for es6-module-loader.js in the right place if `system.js` was loaded within node_modules?  Or is there an alternative solution that can make this work?  Thanks!

**Comment by matthewp** [comment]
It would be easy to get SystemJS to load from both node_modules and bower_components with 1 simple function added to polyfill-wrapper-end. Would be an easy win with little downside. Would be happy to submit a change if you're open to it.

**Comment by guybedford** [comment]
@matthewp sorry for the delay - I'd be interested to see what you mean here.

**Comment by guybedford** [comment]
@matthewp did you still want to follow up on this?

**Comment by matthewp** [comment]
Probably in the future, not at this time though.

**Comment by guybedford** [comment]
Sure - do let me know your ideas though especially coming up to this rewrite. The ideal discussion window is this next week.

**Comment by guybedford** [comment]
Let me know if you still want to discuss this at all.
