### ISSUE TITLE
traceur.options doesnt work !

### ISSUE THREAD

**Issue by SerkanSipahi** [systemjs/systemjs#268]
That doesnt work ! What is my false? 

``` html
<head>
        <script src="webcomponents-lite.js"></script>
        <script src="traceur-compiler/bin/traceur.js"></script>
        <script src="es6-module-loader/dist/es6-module-loader.js"></script>
        <script src="systemjs/dist/system.js"></script>
        <script>
             // > traceur.options.experimental = true; dont working, too !!!

             traceur.options.asyncFunctions = true;
             traceur.options.arrayComprehension = true;

             console.log(traceur.options.asyncFunctions); // > return false ?!?!?!
        </script>
</head>
```

**Comment by Bretto** [comment]
System.traceurOptions.asyncFunctions = true is not working in traceur@0.0.84

**Comment by guybedford** [comment]
We have a test of this here - https://github.com/systemjs/systemjs/blob/master/test/test.js#L517 and it is definitely passing?

**Comment by Bretto** [comment]
This is what I am trying, I was thinking the asyncFuntions was just an option of the experimental flag... I am trying to get arrayComprehension to work.

The experimental flag is not working in traceur@0.0.84
```
var metadata = {};
    metadata.traceurOptions = {
        experimental: true,
        arrayComprehension: true
    };
    System.import("src/bootstrap", {metadata: metadata}).catch(function(ex) {
        console.error('Internal Error ', ex.stack || ex);
    });
```

breaks on 
```
console.log([for (x of ['a','b','c']) for (y of [1,2,3]) (x+y)]);
```

**Comment by guybedford** [comment]
You need to set System.traceurOptions not through metadata. Let me know if
that works for you.

**Comment by Bretto** [comment]
System.traceurOptions.experimental = true;

System.traceurOptions
undefined

**Comment by guybedford** [comment]
`System.traceurOptions = { experimental: true }`

**Comment by Bretto** [comment]
Still breaking on 
```
console.log([for (x of ['a','b','c']) for (y of [1,2,3]) (x+y)]);
```

```
System.traceurOptions = { experimental: true };

    System.import("src/bootstrap").catch(function(ex) {
        console.error('Internal Error ', ex.stack || ex);
    });
```

**Comment by MajorBreakfast** [comment]
@Bretto BTW your error handler crashes if the promise rejects without an error (which is possible).

Instead use:
``` JavaScript
console.error('Internal Error ', ex && ex.stack || ex)
```

**Comment by Bretto** [comment]
Unfortunately System.traceurOptions should be removed.
https://github.com/google/traceur-compiler/issues/1666#issuecomment-76415917

The metadata is not working...

**Comment by guybedford** [comment]
The confusion here is that Traceur has it's own version of a `System` loader with a different API.

We don't support `traceurOptions` on metadata, only through the global `System.traceurOptions`, while Traceur does the opposite.
