### ISSUE TITLE
Asynchronous loading of systemjs causes errors when importing

### ISSUE THREAD

**Issue by nathanathan** [systemjs/systemjs#272]
I am asynchronously loading System.js so I can use it in a bookmarklet.

On line 2162 of system@0.9.3.src.js I'm getting this error when I try to import additional scripts in Chrome:

`Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

**Comment by gobengo** [comment]
I saw a similar error today, when async loading systemjs in an HTML file that was loaded via an HTML Import.

In that case, `window.document` refers to the already-loaded outer document that is doing the importing. `document.currentScript.ownerDocument` refers to the document that is being HTML-imported, and I believe the one that systemjs actually wants to write to.

So this patch of document.write worked in Chrome. I did this at the top of my HTML file being imported.

```javascript
  (function () {
    var topDocument = document;
    var currentScript = document.currentScript;
    var ownerDocument = currentScript.ownerDocument;
    // patch document.write
    document.write = (function (ogWrite) {
      return function (html) {
        if (document.currentScript.ownerDocument !== document) {
          return currentScript.insertAdjacentHTML('afterend', html);        
        }
        return ogWrite.apply(document, arguments);
      }
    }(document.write));
  }())
```

**Comment by guybedford** [comment]
@gobengo thanks for sharing - I do think the better way around this is to manually include `es6-module-loader.js` in scenarios where SystemJS isn't aware of how to do a `document.write` style injection.

**Comment by gobengo** [comment]
Yeah it turns out that didn't continue working very well. I think manually including the deps is the only way.

**Comment by tomchentw** [comment]
I've encounter the same error when I try to import [Google Maps JavaScript API v3]. Here's the [jsfiddle] and the screenshot:

<img width="1259" alt="screen shot 2015-08-09 at 11 34 00 am" src="https://cloud.githubusercontent.com/assets/922234/9153464/b4e1b1da-3e8a-11e5-866f-49b072bb5109.png">

Any thoughts?

Related to tomchentw/react-google-maps#92

[Google Maps JavaScript API v3]: https://developers.google.com/maps/documentation/javascript/tutorial
[jsfiddle]: https://jsfiddle.net/tomchentw/d3o1ys86/
