### ISSUE TITLE
Support loading System in System

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#276]
Because.

**Comment by matthewp** [comment]
What do you mean by this?

**Comment by guybedford** [comment]
It's a challenge to see if we can support loading a new `System` instance through `System.import` itself.

**Comment by matthewp** [comment]
Why load a new System and not just `var system = new System.constructor();`?

**Comment by guybedford** [comment]
This would allow jspm to self host - 'jspm install jspm'. At the moment
this is the bottleneck for that.

**Comment by matthewp** [comment]
Can you explain the use case for jspm self-hosting? I'm still not clear on what problem this would solve.

**Comment by guybedford** [comment]
Dogfooding mainly for fun. Self-updating could be useful though.

**Comment by matthewp** [comment]
Fair enough, this sounded like a "because we can" idea but I wasn't totally sure ;)

**Comment by matthewp** [comment]
Maybe I'm underestimating what is needed here, don't we just need to not set a global and then do some type of umd-ish export?

**Comment by guybedford** [comment]
Yeah I think the first thing is fixing the global collission of System with itself. After that it's mainly about handling the environment-specific behaviours like auto-loading the module loader, traceur etc.

**Comment by guybedford** [comment]
https://github.com/systemjs/systemjs/issues/349 is a first step on this.

**Comment by ohjames** [comment]
We're pre-compiling assets here in the build system for a very large project using incremental rebuilds that spit out a few very large bundled files together with source maps (the large amount of transpiling on each reload slows down testing too much without this). The vendor dependencies are put into a single file and since they rarely change this also saves a lot of time.

Ideally our intermediate build steps could also produce systemjs modules, currently they have to produce amd/common so that jspm can bundle in the final step. So even though this sounds kinda meta/fancy it has some pretty cool real world applications.

**Comment by guybedford** [comment]
@ohjames using bundles within bundle arithmetic is supported currently, so you should be able to do that today. This issue is specifically tracking `import System from 'systemjs'`.

**Comment by ohjames** [comment]
@guybedford currently when I try to `bundle` an ES5 package called `init` that uses the systemjs format I get the error:

```
TypeError: "init" was defined via a bundle, so can only be used for subtraction or union operations.
```

If I convert the same module to AMD then `jspm bundle` works.

**Comment by guybedford** [comment]
Sure I can see if we can support something like that - created a feature in https://github.com/systemjs/builder/issues/163.

**Comment by guybedford** [comment]
It almost works currently actually. Can debug driving this through the use case of actual jspm dogfooding in due course.

**Comment by ohjames** [comment]
Cool, the retranspilation on each page reload was killing me, but at least compiling to AMD server-side using multiple CPUs/Cores removes 99% of that burden on the CPU. I assume compiling direct to System format rather than AMD would only save a little more.

**Comment by ohjames** [comment]
Oops, wrong bug again, time to go back to bed.
