### ISSUE TITLE
A JSON format?

### ISSUE THREAD

**Issue by justinbmeyer** [systemjs/systemjs#277]
CJS allows one to load JSON files like:

```
var foo = require('something.json')
```

Would you consider a JSON format extension (similar to CJS / AMD) that enabled modules to import JSON without the need for ! plugins?

It could detect JSON simply by checking if the source starts with `/\s*\{/`.  Thanks!

**Comment by guybedford** [comment]
Closing as plugins will be possible to work just like formats soon.
