### ISSUE TITLE
[QUESTION] How the developer is supposed to load external modules?

### ISSUE THREAD

**Issue by ipeychev** [systemjs/systemjs#279]
Hello,

I would like to ask a question - how developer is supposed to load modules from external files? For example, let's suppose I want to load jQuery from their CDN. The code below throws exception - "invalid file name":

``` javascript
import {jquery} from 'https://code.jquery.com/jquery-2.1.3.min.js';
```

However, if written in this way:

``` javascript
System.load('https://code.jquery.com/jquery-2.1.3.min.js')
```

then SystemJS tries to make an AJAX request to the local server, like this:
GET https://code.jquery.com/jquery-2.1.3.min.js.js 

Of corse, this fails with the following error:
" XMLHttpRequest cannot load https://code.jquery.com/jquery-2.1.3.min.js.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. The response had HTTP status code 404."

Something similar happens in the following case:
1. We have a file on the local server, called "local-dep.js". The code below works fine:

``` javascript
import {test} from './local-dep';
```

However, specified in this way it is not being loaded - SystemJS raises exception that the module name is invalid.

``` javascript
import {test} from 'http://localhost:8081/app/local-dep.js';
```

Here are the questions summarized:
1. Why SystemJS behaves differently when module is being loaded via "import" and "System.import"?
2. How the developer is supposed to load modules from external files in ES6?

Thanks,

**Comment by IAMtheIAM** [comment]
2 years later, is it supported to load modules from external URL yet?

**Comment by asapach** [comment]
I believe yes: http://jspm.io/0.17-beta-guide/loading-libraries-from-cdn.html

**Comment by Sushil1091Jes** [comment]
System.import('http://path-to-js').then((modules){ }) is showing error

**Comment by joeldenning** [comment]
@Sushil1091Jes the problem you're experiencing should be in a separate github issue. And we'd need more information to be able to debug it, such as stacktrace and/or github repo that reproduces the problem.
