### ISSUE TITLE
Loads of traceur source map warnings

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#284]
With `jspm@0.10` and `system@0.11` I now get:
```
Source map http://localhost:8000/src/data/worker/searchIndices.js!eval points to the files missing from the workspace: [http://localhost:8000/src/data/worker/@traceur/generated/TemplateParser/20, http://localhost:8000/src/data/worker/@traceur/generated/TemplateParser/25, http://localhost:8000/src/data/worker/@traceur/generated/TemplateParser/22, …]
```

I'm using the `src/` directory as a workspace folder in chrome. I think the "!eval" part at the end of the file names messes this up.

I'm not totally sure if this is a jspm, systemJS or traceur issue. Any ideas?

**Comment by guybedford** [comment]
Closing as this is a Traceur bug, thanks for following up with Traceur.
