### ISSUE TITLE
Conditional proposal

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#285]
Here's a variation that captures the previous features of conditionals (https://github.com/systemjs/systemjs/pull/189, https://github.com/systemjs/systemjs/issues/126), but is much less verbose:

```javascript
System.sites = {
  // in this case the `./detect/browser/name.js` module has `export default browserName`
  // which is a string, that then gets used as a conditional wildcard in the mapping
  'browserName': './detect/browser/name.js',
  'browser/feature.js': '/some/package/#{browserName}/feature.js'
}
```

Conditionals would be equally possible to set through `paths` and `map`, and work in imports as they are the final normalize action before plugins.

The symbol is `#{...}` which acts by simple string replacement. Alternative suggestions to `#` welcome.

Please give feedback! This is the most terrifying API I've ever designed.

**Comment by guybedford** [comment]
Random aesthetic point - which seems better:

```javascript
import {feature} from 'feature-#{env}.js';
```

OR

```javascript
import {feature} from 'feature-#[env].js';
```

**Comment by guybedford** [comment]
I'm also tempted to leave out the boolean conditional, because it can always be substituted for the branch conditional, and I've yet to see a scenario that justifies it's use.


The biggest argument for the boolean conditional is probably polyfills, since the boolean conditional can only be used to load side effects (which in general are supposed to be restricted to application code in modular design).

But a polyfill should probably not rely on explicit global assumptions, and instead return the `Promise` binding for example, which would be wrapped in a polyfill package.

So the only use case left is side effects of application code which should only run in certain environments, what one would think of as code like:

app.js
```javascript
doStuff();
if (feature)
  doOtherStuff();
```

But the above can always be refactored into:

```javascript
app-env1.js
doStuff();
app-env2.js
doStuff();
doOtherStuff();
```

So I don't see a strong argument left for the boolean conditional.

**Comment by MajorBreakfast** [comment]
``` JavaScript
import {feature} from 'feature-#{env}.js'
```
I actually prefer the curlies, because it reminds me of ES6 string templates (with '#' instead of '$'). The hash sign is also a good choice because it can't pop up in an URL since the hash section is client-side.

No boolean condition is fine, I think.

**Comment by guybedford** [comment]
Thanks - great points. I can see curlies working.

**Comment by matthewp** [comment]
+1 to es6-like string interpolation.

**Comment by marcfallows** [comment]
This complicates things slightly (unless it was already planned), but it could also be useful to dig into the value if an object is exported.

``` javascript
System.sites = {
  'featureConfig': './detect/features.js',
  'animate.js': '/some/module/animations/#{featureConfig.animate}.js',
  'design.js': '/some/module/resolutions/#{featureConfig.design}.js'
}
```

``` javascript
// ./detect/features.js

// Would do feature detection here to choose appropriate config.
export var config = {
   animate: 'css',
   design: 'mobile'
}
```

**Comment by guybedford** [comment]
@marcfallows I have considered this actually, but one could just have a folder with separate modules:

```
features/animate.js
features/design.js
```

I'm not sure there is that much cost?

Note also that you can set features in a file too:

dev-environment.js
```javascript
System.set('/features/animate': System.newModule({ default: 'css' });
System.set('/features/design': SystemnewModule({ design: 'mobile' });
```

Perhaps we can create a shorthand for the above allowing for easier setting of conditions through configuration:

```javascript
System.config({
  conditions: {
    'features/animate': true
  }
});
```

Will just have to see how that works out with the normalization systems.

**Comment by marcfallows** [comment]
@guybedford My concern with folders with separate modules is that you would need conditional logic in each of the modules.

It would be more ideal if I could make all of the decisions in one module, and then use that information to load only the right modules. Or alternatively I would include Modernizr and then I could also do `import lib/flashcanvas#?{Modernizr.canvas}`.

Otherwise I have to start creating a lot of small modules which export a single Modernizr setting.

**Comment by speigg** [comment]
Isn't conditional loading handled by the programmatic api?

```javascript
if (Modernizr.canvas) {
   System.import('lib/flashcanvas')
}
```

It seems a bit silly to add extra syntax when the above is simple enough, but maybe I'm missing something?

**Comment by matthewp** [comment]
@speigg The problem is that your System.import means that `lib/flashcanvas` is not part of the module's dependency graph. This makes builds much more difficult.

**Comment by speigg** [comment]
@matthewp True. But for any of the dependencies, it is possible that `System.import` will be used to load something dynamically (it is, after all, part of the spec), so it seems like this is something that will have to be dealt with regardless (unless you are also the author of all your dependencies, which is unlikely, in which case you can be assured that `System.import` isn't used anywhere).

**Comment by speigg** [comment]
Again, maybe I'm missing something, but is it even possible to create a bundle that guarantees to contain all dependencies? I have the impression that when using a bundle, all dependencies will still have to be hosted (like in the development workflow) in order to ensure that everything continues to work, just in case _somewhere_ a dynamic `System.import` was used. 

Perhaps it just considered bad practice to use the dynamic `System.import` API anywhere but in the root html document, and I am unaware?

**Comment by matthewp** [comment]
@speigg As long as you create a bundle for every time you use the dynamic System.import you are fine. I use it all the time, for progressive loading. I just make sure that i have a bundle for the modules I am progressively loading.

**Comment by speigg** [comment]
But that's just for code you have control over. What about your dependencies? And if they are already doing as you described, then the solution I described above is compatible.

**Comment by guybedford** [comment]
@speigg the idea here is to build up a full _static conditional graph_ where we know what conditions lead to which modules, all in a properly portable / modular way.

System.import tracing is also something that can be done to build up a _dynamic loading graph_, but the conditional graph is the focus for now as these can always be added manually for tracing.

**Comment by justinbmeyer** [comment]
@guybedford I'm trying to understand this in the scope of language packs.  

Is "env" a module name in the following?

```
import {feature} from 'feature-#{env}.js';
```

Would "env" be loaded and the string return value used to load a specific "feature-X.js" file?

What if no file was needed?  Would env return "@empty" and presumably a "feature-empty.js" be defined? (gosh I hate the .js).

For language packs, I could do something like:

```
import date from 'dates-#{lang}.js'
```

**Comment by guybedford** [comment]
@justinbmeyer yes you are exactly right.

There was also a proposal for loading a single side-effect module based on a truth condition like for polyfills:

```javascript
  import 'es5-polyfill.js#?{notES5}'
```

But that was generally considered ugly and non-obvious.

**Comment by justinbmeyer** [comment]
@guybedford will these modules be identified in any way?  For example, the metadata of `dates-en.js` might have `load.metadata.conditionallyLoaded = true`.  

Also, the templated module name of  `load.metadata.conditionalTemplate = 'dates-#{lang}.js'` will be great and the name of the"case" module like `load.metadata.conditionalCase = 'lang'`

Also, I'd like to propose that "case" modules ("lang" in my `'dates-#{lang}.js'` example) conventionally provide an array of possible default export values.  For example:

```
var lang;
if( navigator.language.indexOf("gr") >= 0 ) lang = "gr"
else if( navigator.language.indexOf("en") >= 0 ) lang = "en"
else lang = "es"

export default lang
export var cases = ["gr","en","es"]
```

Why am I suggesting all of this?  Builds.

When analyzing the dependency graph, a build system will likely not want to bundle modules like 'dates-es.js'.  Instead it will want to make a bundle of all conditional modules for a specified case.

For example, I will want to bundle 'dates-es.js' and 'greetings-es.js' and every other module that loads when `lang="es"`

The best / easiest way to do this is to walk the dependency graph.  And instead of adding a "conditional" module to a bundle, get its "case" module and record its `conditionalTemplate`.  

Once all `conditionalTemplates` have been found, get all 'cases' and bundle all the modules that need to load for each case.

Thoughts?

**Comment by guybedford** [comment]
@justinbmeyer yes there would be some standard meta like this. The `conditionModule` (case) being set for example.

Yes exactly these types of analysis are the very point of this system. We initially based the system on enumerating the outcomes, but this quickly become very repetitive. Instead the benefit of this syntax is that we can simply glob the file system and discover the list of options at build time that way.

**Comment by justinbmeyer** [comment]
> Instead the benefit of this syntax is that we can simply glob the file system and discover the list of options at build time that way.

What if people have paths and such setup to move "foo-en" in a different folder than "foo-es"?

**Comment by justinbmeyer** [comment]
Also, when you say "we" ... does this mean that this is going to be part of some spec ... or that there's people working on this outside of this issue?

How are you planning on implementing it?  Similar to plugins?  Would the deps be "dates-#{lang}.js" or "dates-es.js"?

**Comment by guybedford** [comment]
This won't be in a spec at all, this is SystemJS API.

It will be an extension just like any other that normalizes `dates-#{lang}.js` into `dates-es.js`. It does enforce a certain file structure yes, as map config runs before the conditional replacement process.

**Comment by guybedford** [comment]
Still fleshing out the boolean conditional. Wondering if:

```javascript
import 'lib/flashcanvas|Modernizr/canvas';
```

May be preferable to:

```javascript
import 'lib/flashcanvas#?{Modernizr.canvas}';
```

**Comment by crisptrutski** [comment]
Syntax looks good to me, reminds me of guard notation for pattern matching in a bunch of languages. 

One thing to note is that pipe is not technically forbidden in URLs, it's just part of the inconsistently handled "unwise" set

**Comment by guybedford** [comment]
@crisptrutski thanks for the feedback. Perhaps `import 'lib/flashcanvas#|Modernizr/canvas'; for a full guard?

#### Conditional Adjustment Proposal

Instead of the condition being a module, have the condition as a member expression

For example:

```javascript
import {feature} from './browsers/#{./browser-impl.js}.js';
```

Might become:

```javascript
import {feature} from './browsers/#{browser.type}.js';
```

We thus restrict the use of `/` and `.` in the condition name itself, so that it has to be mapped (throwing an error for say `./browsers/#{browser/type}.js` or ./browsers/#{./browser.js}.js. This way we allow member expressions while keeping the syntax well-defined.

There's a slippery slope here when enabling more syntax, but I think member expressions may well make sense in order to avoid having too many disperate condition modules, which could be difficult to manage.

**Comment by guybedford** [comment]
Actually the syntax can easily be extended to become arbitrarily powerful via plugins:

```javascript
import 'q|#{process.env.X}=="Y"!eval'
```

The above would load the module `q` only if the `process` module had `env.X` matching the condition.

Where an eval plugin could be simply written:

```javascript
export function translate(load) {
  return 'export default load.name';
}
```

So we do have full flexibility with this syntax, only in a way that doesn't encourage it's abuse too easily!

**Comment by MajorBreakfast** [comment]
- I like the pipe (without prepended hash) for the conditional syntax. It reminds me of how the pipe is used in math.
  - `\|` can be used to escape it
- I don't like the member expression thing. Module paths are more flexible than access to globals.
```JS
System.map['isdev'] = `${process.env.NODE_ENV}=='development'!eval` // Template string
```

**Comment by guybedford** [comment]
We're weary to introduce a new character that would need to be escaped, instead we're looking at `#?` on its own again.

Current consensus implemented in the dev branch:

```javascript
import {feature} from './browsers/#{browser.type}.js';
import 'es5-shim#?~browser.es5';
```

**Comment by guybedford** [comment]
@MajorBreakfast note that the member expression feature is not global access - it is a member expression of a module name (the first part being the module name). Also plugin syntax is very much confirmed and has a long history at this point.

**Comment by guybedford** [comment]
Merged into master.

**Comment by martinmicunda** [comment]
Hi @guybedford

I have situation in my app where I want to use conditional for backend-less approach (e.g. use $httpBackend mock in angular) but only for test environment. 

```js
System.set('env', System.newModule({ 'test': true })); // this value is hardcoded
``` 

```js
import EmployeeResource from './employee.resource';
import employeeResourceMock from './employee.resource.mock.js#?env.test'; // this should be only load for test env
```

The problem is that I would like to set `env` value dynamically. For example when I am running command `ENV=test gulp serve` it would set `test` value to `true`

```bash
ENV=test gulp serve
```
```js
System.set('env', System.newModule({ 'test': process.env.ENV }));  // this will set to true
``` 

and if I don't pass any arguments it would set `test` to `false`

```bash
gulp serve
```
```js
System.set('env', System.newModule({ 'test': process.env.ENV }));  // this will set to false
```

**Comment by guybedford** [comment]
@martinmicunda yes this is completely possible in that latest SystemJS. It's just undocumented in the release to get testing feedback on it first.

**Comment by martinmicunda** [comment]
@guybedford could you point to right directions how to that as I been looking at test files but I could not figure out how to set env dynamically? Thanks

**Comment by guybedford** [comment]
What isn't working in your above example?

**Comment by martinmicunda** [comment]
@guybedford I am settings the environment in `config.js`

```
System.config({
  "baseURL": "./",
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});
System.set('env', System.newModule({ 'test': process.env.ENV }));
```
but I am getting follow error in browser `Error: process is not defined` which make sense as process doesn't exist in browser. So my question is how to set this value dynamically in config.js when I run 

```
ENV=test gulp serve

or 

gulp serve --env=test
```

**Comment by guybedford** [comment]
@martinmicunda it's up to your systems to set an environment global here to manage this. `window.env` should suffice.

**Comment by martinmicunda** [comment]
@guybedford ah got it... 

Just one more thing when I use follow code in `config.js`
```js
System.config({
  "baseURL": "./",
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});

System.set('env', System.newModule({ 'test': false })); // --> this cause error

System.config({
  "map": {}
})
```
and I run `jspm install` I am getting follow error (NOTE: if I add above System.set() line to my application code the `jspm install` works fine:

```bash
> jspm install


err  TypeError: undefined is not a function
         at Config.eval (eval at <anonymous> (/Users/martinmicunda/projects/groupon/projects/brands_ui-es6/node_modules/jspm/lib/config/loader.js:94:15), <anonymous>:16:26)
         at Config.read (/Users/martinmicunda/projects/groupon/projects/brands_ui-es6/node_modules/jspm/lib/config/loader.js:94:3)
         at /Users/martinmicunda/projects/groupon/projects/brands_ui-es6/node_modules/jspm/lib/config.js:94:26
         at runMicrotasksCallback (node.js:337:7)
         at process._tickCallback (node.js:355:11)
         at Function.Module.runMain (module.js:503:11)
         at startup (node.js:129:16)
         at node.js:814:3
```

**Comment by guybedford** [comment]
Yes System.config needs to contain config data only. Use a separate file for code execution.

**Comment by guybedford** [comment]
I mean jspm config.js...

**Comment by martinmicunda** [comment]
@guybedford ok I am passing variable through gulp-inject into html as set them as global.

```html
        <!-- build:remove -->
        <script src="jspm_packages/system.js"></script>
        <script src="jspm.conf.js"></script>
        <script>
            System.import('app/bootstrap').catch(console.error.bind(console)); // make sure any errors are print to console
        </script>
        <!-- endbuild -->

        <script type="text/javascript">
            window.ENV = {
                <!-- inject:env -->
                mock: true,
                environment: 'test'

                <!-- endinject -->
            };
            System.set('ENV', System.newModule({ 'default': window.ENV, __useDefault: true })); // it requires for conditional ES6 module loader
        </script>
```
app code
```js
import EmployeeResource from './employee.resource';
import employeeResourceMock from './employee.resource.mock.js#?ENV.mock';
```

and it works fine for my development flow however when I try use `systemjs-builder` in my production flow I am getting follow error:

```bash
Error: Error: ENOENT, open '/Users/martinmicunda/projects/groupon/projects/brands_ui-es6/ENV.js'
```

I am guessing that global variables are not available as I defined them in `html`. So my first question is if `systemjs-builder` support conditional import and if yes how do you pass variable through `systemjs-builder` to application? 

```js
    var Builder = require('systemjs-builder');
    var builder = new Builder();

    builder.loadConfig('./jspm.conf.js')
        .then(function() {
            builder.buildSFX('src/app/bootstrap', paths.tmp.scripts + 'build.js', { sourceMaps: true, config: {sourceRoot: paths.tmp.scripts} })
                .then(function() {
                    return cb();
                })
                .catch(function(ex) {
                    cb(new Error(ex));
                });
        });
```

**Comment by martinmicunda** [comment]
@guybedford did you have chance to look at this? Thanks

**Comment by guybedford** [comment]
There is no support yet for conditional builds, which is also one of the reasons conditionals aren't documented currently.

I'd suggest setting globals directly if you can for builds, although in effect this workflow may just end up being equivalent to having a variable map config anyway.

Sorry I can't be of more help than that right now.

**Comment by martinmicunda** [comment]
hmm that didn't work.. I found temporary solution for my production build (I am using coditional imports only in dev and test env). Basically I am using `gulp-preprocess` task before I build a bundle and preprocess task remove mock code from my files. It would be nice when  `systemjs-builder` will support conditional imports and also option to pass globals in the future but I understand this my take a while...

```js
//@exclude
import employeeResourceMock from './employee.resource.mock.js#?ENV.mock';
//@endexclude
```

**Comment by martinmicunda** [comment]
Hi @guybedford. Do yo know if there is plan to add support for conditional module syntax to `systemjs-builder` in near future? Thanks

**Comment by guybedford** [comment]
@martinmicunda this is certainly on the roadmap, but implementation is not currently being prioritised.

**Comment by omerts** [comment]
how do you load the conditional loader from a relative path?
using 
```javascript
import fetch from '#{./FetchSelector.js}';
```
throws:
```
Condition modules cannot contain . or / in the name.
```

**Comment by guybedford** [comment]
@omerts condition modules need to be mapped via map configuration so they don't have `.` or `/` in the name.

**Comment by omerts** [comment]
@guybedford  thank you :)
