### ISSUE TITLE
Minimal loader build

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#291]
It is possible to create a variation of SystemCSP without the format layers, and just the register extension. Even meta and plugins can be removed through precompilation.

Then a compiler can compile to this output, allowing for an incredibly lightweight production loader.

Goal is to have two loaders then - development and production.

**Comment by matthewp** [comment]
:+1: like the idea.

**Comment by iseulde** [comment]
So this version would not have the `es6-module-loader` dependency?

**Comment by guybedford** [comment]
Merged into master.
