### ISSUE TITLE
System.import doesn't resolve path of argument to match module path in bundle

### ISSUE THREAD

**Issue by theefer** [systemjs/systemjs#293]
Given the following config:

``` javascript
System.config({
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js",
    "app/*": "js/*.js"
  },
  "bundles": {
    "build": [
      "js/test"
    ]
  }
});
```

`System.import("js/test")` correctly loads the `build.js` bundle instead of the `js/test.js` file.

However, `System.import("app/test")` (using paths config) loads `js/test.js` instead of `build.js`.

**Comment by guybedford** [comment]
Try running `jspm bundle app/test` here so that the bundle matches the paths in the client.

**Comment by theefer** [comment]
Ah right that did the job, I guess that does make sense. Thanks!
