### ISSUE TITLE
Source maps option

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#295]
Source maps can be really annoying when you don't want them downloaded.

Perhaps a 

```javascript
  System.sourceMaps = false;
```

To automatically strip them from sources?

**Comment by theefer** [comment]
Can't you simply `--skip-source-maps` if you don't want them when bundling, or are you thinking of runtime skipping (do browsers even allow that?) ?

**Comment by guybedford** [comment]
This is specifically for the runtime. It would mean removing the `sourceMappingURL` in the translate hook.

**Comment by matthewp** [comment]
Why are they annoying? They can be disabled in the browser.

**Comment by guybedford** [comment]
If I have source maps in a production app, then as soon as I open the devtools console they are downloaded by default even if that is not wanted. Changing them through settings its easy to forget to switch them back on again.

It's only 1 MB of code typically, but it can also clutter network debugging etc.

I think it's nice to have source maps enabled in production as far as code is open source. View source is a nice feature, but it shouldn't degrade debugging experience of production apps.

**Comment by MajorBreakfast** [comment]
Chrome dev tools has a switch in the settings. Isn't using that easier than changing the source?

**Comment by theefer** [comment]
I also feel like I'd rather choose whether sourcemaps are downloaded or not, as a developer, rather than it being prescribed by the page, in which case it'd be more complicated to turn them back on when necessary.

**Comment by marcfallows** [comment]
As a dev debugging, I would like it to be my choice to switch on/off source maps - and I have that ability in the browser dev tools. Seems a bit strange to make this a choice by the loader.

**Comment by guybedford** [comment]
I've updated the issue title to reflect that when we introduce chained source maps for plugins, there are performance implications for this with in-browser compilation, so turning off source maps for that is useful.

Stripping source maps is something I would still like personally too, but I certainly agree with the arguments here as well.
