### ISSUE TITLE
Module not detected as CommonJS

### ISSUE THREAD

**Issue by Bubblyworld** [systemjs/systemjs#297]
The following code:

```javascript
Object.defineProperties(exports, {
  isServer: {get: function() {
      return isServer;
    }},
  __esModule: {value: true}
});
function isServer() {
  return typeof exports !== 'undefined' && this.exports !== exports;
}
```

Needs meta to be manually included otherwise `exports` is undefined.

**Comment by matthewp** [comment]
The presence of an `exports` isn't enough to declare a module to be CommonJS. I don't want to speak for @guybedford but I think it would be hard to capture this scenario with regex without creating false-positives elsewhere. Luckily it's very easy to fix any module that is detected as the wrong format; just put `"format cjs";` in the top of the file.

**Comment by guybedford** [comment]
@matthewp good point. This output should rather use a reference to `module.exports` if it wants to be detected as CommonJS.

This is Traceur's CommonJS output, so I will write a PR to change the above to `Object.defineProperties(module.exports`, when I can.

**Comment by guybedford** [comment]
I've posted the above PR to Traceur. That's the best possible fix for this.
