### ISSUE TITLE
Swapping modules - need to use normalized name

### ISSUE THREAD

**Issue by marcfallows** [systemjs/systemjs#298]
I'm having some trouble with a module that I want to swap out based on some config.

``` javascript
System.config({
   "versions": {
      "lib/sdk": "0.1.2"
   }
});
System.import('main');
```

There's a case I want everything which asks for `aModule` to give me `aMockModule`.

``` javascript
// main.js
require(['lib/sdk/aModule'], function(aModule) {
   // aModule should be aMockModule
});
```

``` javascript
// lib/sdk@0.1.2/utils/differentModule.js
require(['../aModule'], function(aModule) {
   // aModule should also be aMockModule
});
```

At this point I can only seem to get it to work if I do the following:
``` javascript
System.config({
   "paths": {
      "lib/sdk@0.1.2/aModule": "lib/sdk@0.1.2/aMockModule.js"
   }
});
```

This works, but if I upgrade versions of the sdk, then I need to change the config, which doesn't seem right. Also, I feel like it should be something I can do with `meta`, but I'm not sure how (and `meta` would need to include the normalized name with version... again, doesn't feel right).

Am I missing something in terms of the configuration options? Would there be a way to apply this regardless of version so the config does not need to be updated?

**Comment by guybedford** [comment]
You should be able to do this with map:

```javascript
System.config({
  map: {
    'lib/sdk/aModule': 'lib/sdk/aMockModule'
  }
});
```

**Comment by marcfallows** [comment]
If I do the map, as suggested, it does not seem to be working for relative lookups. I end up loading `aModule` in these cases, and `aMockModule` in the other cases (when listing `lib/sdk/aModule` as a dependency)

``` javascript
// lib/sdk@0.1.2/moduleAtSameLevel.js
require(['./aModule'], function(aModule) {
   // getting aModule, not aMockModule
});
```

**Comment by guybedford** [comment]
It should still work. Could you share a log of `Object.keys(System._loader.loads)` to see if there are different entries in the modules table?

**Comment by marcfallows** [comment]
@guybedford Unfortunately with versions it doesn't go so well. 

I've setup a simple repro of the issue here: https://9a8574b51086868b03d9802b27edbb303454dc76-www.googledrive.com/host/0BwYsSI4nLi9UUXRCS3U0Y2Qtd3c/ (Unfortunately my Plunker won't save with "@" character in the file names).

I would expect `bb` on the screen, but I get `ba`.

**Comment by marcfallows** [comment]
Further to this (although it could be a separate issue) I would expect to be able to do the following:

``` javascript
System.config({
    "meta": {
        "lib/angular/angular": {
            "exports": "angular"
        },
        "lib/angular/angular-resource": {
            "deps": ["lib/angular/angular"]
        }
    },
    "versions": {
        "lib/angular": "1.2.8"
    }
});
```

But actually, I have to do this (specifying the version number):
``` javascript
System.config({
    "meta": {
        "lib/angular@1.2.8/angular": {
            "exports": "angular"
        },
        "lib/angular@1.2.8/angular-resource": {
            "deps": ["lib/angular/angular"]
        }
    },
    "versions": {
        "lib/angular": "1.2.8"
    }
});
```

I have a few libraries where I need to do this and it is frustrating that I have to update the version numbers in several places. You can see where the frustration is amplified if you consider that I would likely be using `angular-resource`, `angular-cookies`, `angular-route`, `angular-animate` and `angular-sanitize` - all of which would have `deps` on `["lib/angular/angular"]`, and I would have to update the `meta` in each one when incrementing the version (the example above only shows one - `angular-resource`). 

angular will always export `angular` (and other libraries `meta` such as `exports` and `deps` probably won't change from version to version either). I expect to be able to update the `versions` and be able to leave the `meta` as is.

I really feel like I should be able to specify `meta` for *unversioned* library names. I should then be able to specify *versioned* `meta` to override if there is, say, a version specific dependency.

Thoughts?

**Comment by guybedford** [comment]
Yes setting meta can be tricky because you need to set the exact name in the format expected, which can be hard to know exactly.

In this coming release module names become URLs and meta will be possible to be unnormalized URLs making this stuff easier.

**Comment by marcfallows** [comment]
Ok, so sounds like that will address the `meta` issue. But there's still a `map` bug I repro'd https://github.com/systemjs/systemjs/issues/298#issuecomment-68872542. I'm not sure the module names being URLs will fix this.

**Comment by guybedford** [comment]
@marcfallows the versions extension is actually also being removed in the next version as well, see https://github.com/systemjs/systemjs/pull/282. In the mean time we can look at the bug though, PRs welcome too.

**Comment by marcfallows** [comment]
@guybedford Oh, I didn't realize you were removing `versions`. Would I then specify versions as a `map`? If so, don't I end up back in the situation of https://github.com/systemjs/systemjs/issues/298#issuecomment-68993289 where I have to specify meta with a version?

I'm happy to look into the bug, but it's a bit of an edge case - which has a workaround - to look into if `versions` is being dropped soon.

**Comment by guybedford** [comment]
Yes map would be the place to then specify exact versions, but you would end up needing to still include it with your meta actually, you're right.

The thing about meta is you do want it to apply to a specific version and not every version of that name though right?

**Comment by marcfallows** [comment]
I want to be able to specify that `"lib/angular/angular"` exports `angular`. And when I update the version of angular the `meta` won't change so I would hope I only have to update the `versions` or `map` and leave the `meta` keys as is (without the version number included).

If I specify the versions as `map` then I also have to update the `meta` key version.

Will the Wildcard meta (https://github.com/systemjs/systemjs/issues/217) solve this for me?

``` javascript
System.config({
    "map": {
        "lib/angular": "lib/angular@1.2.8"
    },
    "meta": {
        "lib/angular@*/angular": {
            "exports": "angular"
        }
    }
});
```

**Comment by guybedford** [comment]
Yes wildcard meta would solve this for you actually.

Are you running multiple versions of angular?

Another consideration might be to use `paths` config to set:

```javascript
System.config({
  "paths": {
    "angular": "lib/angular@1.2.8/angular"
  },
  "meta": {
    "angular": {
      "exports": "angular"
    }
  }
});
```

**Comment by marcfallows** [comment]
I'm not running multiple versions of angular, but regularly updating to try and stick with their releases. But, the wildcard meta approach could actually cope with multiple versions since I could specify an exact version if I needed different meta. That meta would be more specific, and hence prioritize over the generic angular meta.

`paths` wouldn't work unfortunately, since I have `"lib/*"` already as a path.

Seems like specifying the version numbers explicitly in the meta works for now, and then I can clean up the config once there is wildcard meta.

Can I help with that feature or is it well under way?

**Comment by marcfallows** [comment]
I just realized I have a slight issue. Say I want `"lib/angular"` to have a version, and want a `map` shorthand of `"angular"`. If `versions` is no longer available, I lose this ability since `map` is not recursive.

Say I wanted this:
``` javascript
System.config({
    "paths": {
        "lib/*": "http://some.cdn.com/lib/*.js"
    }
    "map": {
        "angular": "lib/angular/angular",
        "angularMock": "lib/angular/angular-mock"
        
        // Mapping the version wouldn't work if the dependency is "angular"
        // "lib/angular/": "lib/angular@1.2.8"
    },
    "meta": {
        "lib/angular/angular": {
            "exports": "angular"
        },
        "lib/angular/angular-mock": {
            "exports": "angular.mock"
        }
    },
    "versions": {
        "lib/angular": "1.2.8"
    }
});
```

If `versions` is ditched, I don't think there's any way of handling this without repeating the version number in the config - which doesn't seem great...

**Comment by matthewp** [comment]
I've been wondering if there was a reason map isn't recursive. Is there?

**Comment by guybedford** [comment]
Maps aren't recursive because the map `"jquery": "jquery/index"` would diverge if applied more than once.

**Comment by guybedford** [comment]
@marcfallows it's worth thinking carefully why you are using a version in the pathname here at all - are you running multiple versions of angular side-by-side in your application?

**Comment by marcfallows** [comment]
@guybedford I may be missing something crucial here because this isn't the first time you seemed surprised I'm using `verisons`.

Our CDN hosts several versions of angular. Our app has several versions, each version may use a different version of angular. (app 1.0.0 uses angular 1.2.8, app 2.0.0 uses angular 1.3.8). We don't bundle the libraries (host them externally to get CDN goodness). The config with `versions` lets SystemJS use the correct library version.

Would you handle this differently so there was no need for a version number? I'm not sure how you would do that.

**Comment by guybedford** [comment]
Ok. I would suggest using the map config here, and then ensuring you configure the specific version of angular when doing the meta config. It does mean changing the version requires altering it in two places. You can avoid that by using a path config for angular. Those are pretty much the two options I believe.

**Comment by marcfallows** [comment]
@guybedford As mentioned before, because I'm already using `paths` for the `"lib/"` using `paths` for `"angular"` doesn't work. This is where `versions` fit in nicely. When `versions` is removed I lose a level of configuration I needed. I start having to repeat things or process the config as part of the build.

**Comment by guybedford** [comment]
@marcfallows you're going to have to repeat yourself somewhere then.

**Comment by guybedford** [comment]
That is - either with paths including the lib, or with the map including the version.

**Comment by guybedford** [comment]
@marcfallows closing for now, sorry it isn't the elegant solution you may have hoped for. Please do let me know if you have further workflow questions at all.

**Comment by marcfallows** [comment]
@guybedford all good. Thanks for all of the responses and the great work you've been doing on this project.

I had thought about my own plugin or extension that would use the package.json version number and translate the path to include the version number (where applicable). Could you see this working? Or, do you think I would be better off sticking with a build step?

**Comment by guybedford** [comment]
@marcfallows sure! It could be worth exploring something along the lines of generating from the package.json certainly - either dynamically or in a build step.
