### ISSUE TITLE
[support question] traceur System.register and bundling

### ISSUE THREAD

**Issue by pkozlowski-opensource** [systemjs/systemjs#300]
I'm not sure this is the best place to ask support questions but I wasn't sure where I could reach out to project maintainers and clarify one thing before I start digging through the code. So I will take my chances here - feel free to close this issue if this is not an appropriate place.

So, I'm experimenting with traceur's `instantiate` module format (`System.register`) and SystemJS  with register extension. I got a basic setup working without problems but now I'm playing with a scenario where I would like to bundle some of the files together and pre-load them while allow dynamic loading for some other files. 

For example, assuming that my project consists of files: `foo.js`, `bar.js`, `baz.js` I would like to bundle `foo.js` and `bar.js` together and pre-load them while require `baz.js` as needed.

What I though will be enough is to bundle together `foo.js` and `bar.js` and include them in the HTML page like so:

```html
   <script src="lib/es6-module-loader-sans-promises.src.js"></script>
    <script src="lib/system.src.js"></script>
    <script src="lib/extension-register.js"></script>
    <script>
        register(System);
    </script>
    <script src="./bundled_foo_and_bar.js"></script>
    <script>
        System.import('./foo').then(function(m) {
            //foo should be pre-loaded from bundled_foo_and_bar.js so shouldn't trigger any XHR request
        });

       //later on
       System.import('./baz').then(function(m) {
            //baz wasn't preloaded so baz.js should be pre-loaded dynamically
        });
    </script>
```

Apparently I'm missing an important piece here, since calling `System.import('./foo')` triggers an XHR request, contrary to what I would expect.

Is such a combination of a static + dynamic workflow possible with traceur's output and SystemJS? If so, I would be grateful for pointing me to the missing pieces....

**Comment by guybedford** [comment]
Yes this workflow is entirely supported.

You need to ensure thought that the name you import `./foo` completely matches the name in the bundle file. For example, if your `System.register` calls in the bundle look like `System.register("foo", ...` then you need to directly have a `System.import('foo')` so the names match.

To test normalization you can do `System.normalize('./foo').then(function(normalized){ console.log(normalized) })` to see what the name is normalizing into and ensure that that matches what is in the bundle.

**Comment by pkozlowski-opensource** [comment]
Ah, I was missing the `moduleName` option to traceur! Your remark put me on the right track and now I've got it working. Perfect!

BTW, @guybedford, thank you very much for all your hard work on the loader-related projects for ES6. I fully realize how much work it represents and the whole community should be really grateful for this (I certainly am!). Open source at its best!

**Comment by guybedford** [comment]
Glad that has clarified. Sure, thanks!
