### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by arcanis** [systemjs/systemjs#303]
I don't really understand the windows compatibility and may use some additional infos :

  - Why does the path have to be prefixed by `file:` ? Can't SystemJS add them internally when needed? They break tools such as the `path` module, and are really weird on unix.

  - When I do something like `System.import('willikins/_run')`, I get the following error:

    ```
    Error loading "willikins/_run" at c:\Users\Mael\AppData\Roaming\npm\node_modules\willikins\sources/_run.js
    Only file URLs of the form file: allowed running in Node.
    ```

  - When I fix the import by adding the prefix (`System.import('file:willikins/_run')`), SystemJS is ignoring my path configuration:

    ```
    Error: Error loading "file:willikins/_run" at file:willikins/_run.js
ENOENT, open 'C:\Users\Mael\Downloads\LimitedSpoiler\server\willikins\_run.js'
    ```

    (notice how the loaded file has changed, but is now relative to my current directory, rather than the one I want it to load)

  - Finally, when adding the `file:` prefix to the path too, I get the same error as before (only file URLs ... allowed running in Node).

What I am missing ?

**Comment by guybedford** [comment]
The internal use of `file:` is identical to how you might expect file URLs to work in the browser. It's not a system that is compatible with `/` style URLs and you need conversions if you want it to be.

What is your baseURL?

**Comment by arcanis** [comment]
Ok, I have fixed this issue - I had to `file:`-prefix my path mapping, but not the key, the value. Ie

```
System.paths[ 'foo' ] = 'file:bar';
```

Rather than

```
System.paths[ 'file:foo' ] = 'bar';
```

However, I'm really not convinced by this 'fake protocol'. How is it that they are needed ? Will the standard have them too ?

**Comment by guybedford** [comment]
@arcanis great to hear that has worked it out. This is entirely for aligning with the standard. The use of a `file:` protocol has been a standard convention in browsers for many many years.
