### ISSUE TITLE
Import is broken in node.

### ISSUE THREAD

**Issue by briandipalma** [systemjs/systemjs#306]
I've tried reverting both https://github.com/systemjs/systemjs/commit/6beeaab3bf74ad18b524d89c8b12eb4f24f074c7 and https://github.com/systemjs/systemjs/commit/53338ccda10e18761d83d7587e75834840cf0bb1 but I'm still seeing errors when [running this](https://github.com/briandipalma/gc-cli/blob/master/bin/gc-cli-cli.js) command line tool with the latest SystemJS.

`Only file URLs of the form file: allowed running in Node.`

It's not clear to me what the source of that error is.

**Comment by briandipalma** [comment]
Reverting to 0.9.3 works.

**Comment by guybedford** [comment]
What's the value of the baseURL / address being loaded?

The `baseURL` should be `file:/absolute/path/to/folder/`, and the `address` trying to load should then be of a similar form.

**Comment by briandipalma** [comment]
And using 0.10.0 exact version breaks import.

**Comment by briandipalma** [comment]
It's hard coded in the CLI script

```javascript
System.config({
baseURL: __dirname.replace('bin', ''),
map: {
'global-compiler': 'node_modules/global-compiler/src'
}
});
```

The value of `__dirname` (before SystemJS is used to load anything) is `c:\Development\Github\gc-cli\bin` no indication of a `file:`, do I need to add it myself when using node? All my tests pass though and they use almost the same configuration. Umm I'll try and add `file:` in front of `baseURL`.

**Comment by briandipalma** [comment]
Yep adding `file:` before the `baseURL` fixed the issue. Can I add that to the node documentation?

**Comment by briandipalma** [comment]
Small documentation note added, I checked there before opening this issue.

**Comment by guybedford** [comment]
Right, thanks, the problem here is the `C:` part in windows specifically, because this is being seen as the protocol. Thus, instead of becoming `file:/c:/...` it is remaining `c:/...`.

This is a windows bug - I've noted this in https://github.com/systemjs/systemjs/issues/309.
