### ISSUE TITLE
register plugin?

### ISSUE THREAD

**Issue by forresto** [systemjs/systemjs#315]
Trying to get [plugin-coffee](https://github.com/forresto/plugin-coffee) to work. Do plugins need to be registered somehow to work? How does SystemJS know `x.coffee! -> plugin-coffee`? The docs don't specify how plugins should be installed to actually use them in a project.

**Comment by guybedford** [comment]
The plugin is just taken as the module name at the extension. So you can include:

```javascript
System.config({
  map: {
    coffee: "plugin-coffee"
  }
});
```

Or do:

```javascript
import 'x.coffee!path/to/plugin-coffee`
```

Or some variation of the above. Map configuration is probably the advised way though.

**Comment by forresto** [comment]
How is the plugin installed? `jspm install plugin-coffee`?

**Comment by guybedford** [comment]
If it's in the registry that will work, otherwise `jspm install github:forresto/plugin-coffee`.
