### ISSUE TITLE
loading jsx from .js filenames

### ISSUE THREAD

**Issue by cdetrio** [systemjs/systemjs#316]
I've been running into libraries that have JSX in .js files (most recently [react-d3](https://github.com/esbullington/react-d3/blob/master/src/barchart.js)). Without the .jsx extension, they don't get processed by plugin-jsx, resulting in "Unexpected token <" errors.

As a workaround, I've been renaming the files (and their require statements) to .jsx in my local jspm_packages directory. What's a better way to fix this? Could the jsx translator process files with `/** @jsx React.DOM */` at the top, instead of relying on the file extension?

**Comment by guybedford** [comment]
Firstly, rather use the version on npm - `jspm install npm:react-d3`.

Then you can set the plugin on importing with `import 'file.js!jsx'`.

**Comment by cdetrio** [comment]
Yeah, I did install react-d3 from npm using that command. Then I import it with  `import rd3 from 'react-d3'` in app/app.jsx.

The react-d3/src files have their import statements in [react-d3/src/index.js](https://github.com/esbullington/react-d3/blob/master/src/index.js). So even with `import 'file.js!jsx'`, the require statements there still have to be modified.

Using `file.js!jsx` is better than changing file extensions (thanks!). But how can I avoid altogether the need to change require statements inside another package's src files?

**Comment by guybedford** [comment]
It looks like this relies on Browserify transforms to work? https://github.com/esbullington/react-d3/blob/master/package.json#L55.

There is an issue tracking this at https://github.com/jspm/npm/issues/10.

Note the next version of SystemJS would allow package configuration to enable auto-applying the plugin to these files.

**Comment by cdetrio** [comment]
Ah, I see. I also tried using in-browser [JSXTransformer](http://fb.me/JSXTransformer-0.12.0-rc1.js), but that doesn't work because the files in question aren't loaded through browser script tags. They're loaded by system.js.

Thanks so much for your help!

**Comment by victorwpbastos** [comment]
> Note the next version of SystemJS would allow package configuration to enable auto-applying the plugin to these files.

I'm so excited for the next release!

**Comment by guybedford** [comment]
Closing for now, let me know if there is anything still unanswered here!

Yes hoping for the big new release in Feb, although have been hoping for it for over 6 months now! Doing my best to make it happen soon.
