### ISSUE TITLE
Handlebars issue?

### ISSUE THREAD

**Issue by Barguast** [systemjs/systemjs#318]
Hi. I'm very new to the SystemJS / JSPM ecosystem so apologies if this issue lies elsewhere.

Basically, I can't use the handlebars library at all. If get this through jspm:

    jspm install handlebars

And try to use it in my code, it looks like the library isn't being found:

    GET jspm_packages/github/components/handlebars.js@2.0.0/handlebars.js.js 404 (Not Found)

The cause seems to be in handlebars.js@2.0.0.js which reads:

    define(["github:components/handlebars.js@2.0.0/handlebars.js"], function(main) {
        return main;
    });

I think it's the file extension that is making it look in the wrong place. If I remove it, everything works again. This is a good enough workaround for me, but I suspect something, somewhere, is mishandling dots in the name?

Hope this was helpful.

**Comment by guybedford** [comment]
Thanks for posting. This is actually a jspm bug with working out the default main. I've added a fix in https://github.com/jspm/jspm-cli/commit/ec4dc7d570aa44695f60c7cfcfcaceeb25c54749, a release should follow soon.
