### ISSUE TITLE
New extension handling in CommonJS

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#319]
When we disable auto-adding the `.js` extension for modules, the question is how this passes down through into CommonJS.

A simple rule in the CommonJS layer that might be useful:

* When loading CommonJS with any extension present, load the filename directly  (`file.coffee` / `./file.js` / `some/package.extension`)
* When loading CommonJS without an extension, and the module is a relative require, use the same extension as the parent module (`./dep` -> `./dep.coffee` / `./dep.js`)
* When loading CommonJS without an extension, and the module is not a relative require, add ".js".

The same rule could apply for AMD then as well.

**Comment by victorwpbastos** [comment]
This would be great!

**Comment by Thecontrarian** [comment]
YES! any idea on the timeline to release?

**Comment by guybedford** [comment]
I've implemented a slightly different approach to the above. Will document on release.

**Comment by jimthedev** [comment]
@guybedford was this already released by chance?

**Comment by guybedford** [comment]
@jimthedev still working hard on it!

**Comment by jimthedev** [comment]
@guybedford awesome. Thanks for the update!

**Comment by subesokun** [comment]
Not sure if this is the right place to ask but my question is also related to the extension handling. While having a look on the new Angular2 npm package ([see here](https://www.npmjs.com/package/angular2)) I've noticed that they use the file extension `*.es6` for all their TS -> ES6 transpiled files.

My question is now if `angular2.es6` has relative imports like `import './di'`, will jspm load then the `di.es6` file or will it try to load the none existing `di.js` in case of a `import 'angular2/angular2.es6'`? Actually is this `*.es6` a new naming convention for ES6 files? I've never seen it before.

**Comment by forresto** [comment]
@guybedford did this get documented somewhere?

**Comment by guybedford** [comment]
@forresto what I've implemented for this use case is default extensions via package configuration in https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages. This is not currently compatible with the `defaultJSExtensions` backwards compatibility mode though.

**Comment by subesokun** [comment]
@guybedford this defaultExtension property per package solves also my question. Thanks for the link.
