### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by unsafecode** [systemjs/systemjs#321]
I'd like to have DefinitelyTyped definitions for System.js in TypeScript

https://github.com/DefinitelyTyped

I've made a very basic one myself, but it's surely limited to a basic usage. A better one will surely be helpful!

**Comment by Barguast** [comment]
I've been thinking of writing one, and have started piecing one together for my own use. So far I don't have much!

    interface ISystemStatic
    {
        import(name: string): any;
        defined: any;
    }

    declare var System: ISystemStatic;

I'd be very interested in doing this, particularly since I work heavily in TypeScript, but mainly to try and spread the word of this awesome project. 

Unfortunately I don't think I have a good enough grasp of the API - the above is literally all I've used so far! If someone can point me in the right direction (i.e. to the properties of the System object), I'd be happy to make a start on this.

**Comment by unsafecode** [comment]
Might be merged with mine:

```javascript
interface System {
    amdDefine: () => void;
    amdRequire: () => void;
    baseURL: string;
    paths: { [key: string]: string };
    meta: { [key: string]: Object };
} 

declare var System: System;
```

**Comment by guybedford** [comment]
This would be very welcome!

The loader API can be read from https://github.com/ModuleLoader/es6-module-loader/blob/master/src/loader.js#L919.

SystemJS-specific additions would be exactly as in the above, with a `config` function as well, and expanding to all the configuration options that are documented.

Just let me know if any further help with clarifying the above is needed at all.

**Comment by DeanB2015** [comment]
Is there still a need for a System.js DefinitelyTyped definition?

**Comment by aabluedragon** [comment]
@DeanB2015 Definitely.

**Comment by unsafecode** [comment]
@DeanB2015 Sure, otherwise a LOT of TypeScript code won't simply work with system.js as a loader.

**Comment by tinganho** [comment]
I also need to type definitions for SystemJS.

**Comment by jamiewinder** [comment]
For what it's worth, a few partial ones have popped up on various GitHub projects:
https://github.com/mgechev/angular2-seed/blob/master/typings/custom.system.d.ts

Though these refer back to this issue, so I think they're just merges of unsafecode and my declarations above. I doubt you'll need much more than this, but it can easily be extended if needed.

**Comment by milkshakeuk** [comment]
here is what I have needed so far:

```typescript
interface System {
    import: (name: string) => {
        then: (successCallback: Function, failCallback?: Function) => void;
    }
}

declare var System: System;
```

**Comment by tinganho** [comment]
Even though they are simple can someone put it up on DT?

**Comment by NathanWalker** [comment]
https://github.com/borisyankov/DefinitelyTyped/pull/5043

**Comment by guybedford** [comment]
Great, thanks for posting!
