### ISSUE TITLE
RactiveJS and SystemJS 0.11.2 - Module process not declared as a dependency

### ISSUE THREAD

**Issue by victorwpbastos** [systemjs/systemjs#322]
After the last update my app stop running:

![image](https://cloud.githubusercontent.com/assets/1017515/5781595/3e190d40-9d9b-11e4-8043-8cbf06ba249c.png)

When I downgrade to version 0.11.1 all back to normal.

**Comment by wildlyinaccurate** [comment]
Just stumbled across this error as well. Works fine with 0.11.1.

**Comment by guybedford** [comment]
Thanks, this is due to https://github.com/systemjs/systemjs/commit/3bfddd81d2f28b21ad9992cd6d7a3127244312c0.

@theefer it seems like reverting to tokenizing may be the way to go with the rules at this level as this is caused by string characters in regular expressions causing invalid string removal.

For now we should probably revert the change, and then work on a tokenizer for the next release.

**Comment by theefer** [comment]
Sounds fair. Regexp only get us so far.

Will the tokeniser run in all cases, or do you want to start the work to
pre process deps for all cases except dev?

**Comment by guybedford** [comment]
The tokenizer will just run in browser in dev, to avoid a full syntax parser. Builds use their own parsing process - https://github.com/systemjs/builder/blob/master/compilers/cjs.js.

**Comment by theefer** [comment]
OK. Are you thinking of using esprima, or another parser?

**Comment by guybedford** [comment]
I was thinking simple tokenizing like in https://github.com/systemjs/systemjs/blob/5f460116abcc25cad96373ccd186db71e5db735a/loader.js#L49.

**Comment by theefer** [comment]
Ah yes that'd work. Plus I realised today stable esprima doesn't support ES6 :-(

**Comment by guybedford** [comment]
An alternative would be to just use Traceur for CommonJS as well actually, but I'm hesitant.

**Comment by guybedford** [comment]
Fixed and published the reversion for this as 0.11.3.

**Comment by theefer** [comment]
Should the bug whose fix broke this and got reverted be reopened?

**Comment by guybedford** [comment]
@theefer yes, we can reopen the issue.

**Comment by theefer** [comment]
It's https://github.com/systemjs/systemjs/issues/311 but I don't have the rights to reopen.
