### ISSUE TITLE
Problem importing es6 from global

### ISSUE THREAD

**Issue by fairbanksg** [systemjs/systemjs#323]
I'm running into an issue with loading an ES6 format module from a global format module.

```
// a.js 
import './b';

// b.js 
window.foo = 'foo';

// c.js 
export default 'bar';

// index.html
System.import('a');
```

Built with this config:

```
System.config({
  meta: {
    b: { format: 'global', deps: ['c'] }
  }
});
```

This breaks because of a missing entry in the groups array while linking.

Repo demonstrating the issue: https://github.com/fairbanksg/systemjs-issue

**Comment by guybedford** [comment]
@fairbanksg ensure you are including the `config.js` file in with the built version, and running the latest versions of ES6 Module Loader and SystemJS.

If it's still not working, I will check this out first thing tomorrow.

**Comment by fairbanksg** [comment]
Oops, I didn't have the config included in the example repo. I added that in and pushed it to the repo, but still have the same problem. ES6 Module Loader, SystemJS, and SystemJS builder are all latest.

**Comment by guybedford** [comment]
Ok thanks, I think I might know what this is.

**Comment by guybedford** [comment]
Thanks, this has been fixed.

**Comment by fairbanksg** [comment]
I grabbed HEAD and tested with my example repo and my real project and this is working perfectly now.
Thanks!

**Comment by guybedford** [comment]
Sure!
