### ISSUE TITLE
browser = false resolves to @empty, fails import

### ISSUE THREAD

**Issue by AutoSponge** [systemjs/systemjs#325]
Documented example: [readable-stream](https://github.com/iojs/readable-stream/issues/88)

When package.json sets `browser: false` the dependency maps to `@empty` module.  This fails on load with an unknown module error.  Can this instead fail silently?  Or should we add `@empty` to our map?

**Comment by guybedford** [comment]
@AutoSponge thanks for reporting.

Can you clarify - are you loading in Node or the browser here?

Is this `jspm install stream` that you are referring to or something else?

Is the browser field `false` or `{ util: false }`? The `@empty` replacement is designed to optimize for the browser use case handling following Browserify rules.

**Comment by AutoSponge** [comment]
@guybedford, I'm loading in the browser.  The uncompiled version works fine but when building to a self-executing package, the reference to `util` is lost.  According to the stream team, the choice to exclude `util` from the package.json was intentional (`{util: false}`).

**Comment by guybedford** [comment]
@AutoSponge perhaps the issue here is that SFX bundles don't support `@empty`?

Try adding `System.register('@empty', [], false, function() {})` at the appropriate place in the sfx bundle and see if that helps?

**Comment by guybedford** [comment]
@AutoSponge see https://github.com/systemjs/builder/issues/49 and the associated commit and let me know if that helps.

**Comment by AutoSponge** [comment]
@guybedford, manually adding the `@empty` registration also works.  I also fixed the issue by adding an `empty.js` file to my project and adding `"@empty": "app/empty",` to my config.js map.  IMO, if that statement could be injected automatically in SFX bundles, it could better support production builds.

**Comment by guybedford** [comment]
Thanks for confirming! I've added https://github.com/systemjs/builder/commit/79efa573b4d364c62220a03bab80d12171e7acfb.

**Comment by guybedford** [comment]
Resolved in builder.
