### ISSUE TITLE
jspm bundle assertion error

### ISSUE THREAD

**Issue by benmonro** [systemjs/systemjs#328]
after running `jspm bundle app bundle.js`

I get the following:
```
     Building the bundle tree for app...

err  AssertionError: not already a dependency
         at Console.assert (console.js:106:23)
         at /Users/BenMonro/.nvm/v0.11.14/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:313:21
```

Not even sure what in my code is causing this...

**Comment by guybedford** [comment]
This could well be a loader bug. A test case or isolated example would be really great to figure it out.

**Comment by benmonro** [comment]
I put some console.logs in es-6-module-loader-sans-promises.src.js where it was crashing and was able to figure out which file of mine was causing it.  I removed the reference to that file and was able to move on.  That said, I'm still having a lot of trouble getting our bundle to work w/ jspm.  It has a TON of dependencies and its been slow going getting through each error message... :(

**Comment by guybedford** [comment]
@benmonro is this for code that works in the browser? What sort of issues are these?

If you can share the one you skipped it would help to fix it.

**Comment by benmonro** [comment]
I believe it was select2.  https://select2.github.io/
 
pretty sure we had a require('./select2') somewhere that i had to remove to get it to finally finish the bundle successfully.

**Comment by guybedford** [comment]
@benmonro thanks, it seems like select2 is using jquery, which isn't declared as a dependency which would cause the bundling issues. I added the dependency with:

```
jspm install select2 -o "{ shim: { select2: ['jquery'] }, dependencies: { jquery: '*' } }"
```

to make it work for me. Ideally this should be added to the registry as an override.

**Comment by guybedford** [comment]
Thanks again for letting me know, I've posted https://github.com/jspm/registry/issues/132 to track the override. Closing for now.

**Comment by benmonro** [comment]
looks like that works for me too @guybedford thanks!
