### ISSUE TITLE
Create a System.clone

### ISSUE THREAD

**Issue by matthewp** [systemjs/systemjs#331]
Will be:

1. Adding `loader._extensions = []` in core.
2. Each extension will push itself into `loader._extensions`.
3. Clone will do a each(loader._extensions, function(ext) { ext(newLoader); })

I'm working on getting this done.

**Comment by matthewp** [comment]
@guybedford I've been working on this, couple of things I've run into though. First, I had to move `core` into the first extension to be applied in the Makefile in order to have it create the `._extensions` property. Is this ok? Otherwise I'll have to find a different way to do it.

Second thing, I'm getting an error when trying to load an es6 file "Include Traceur for module syntax support". I am running the code to add the traceur paths to the cloned loader. Is there some other code that needs to be applied?

**Comment by guybedford** [comment]
@matthewp the second issue is probably because of changing the order of core. I would suggest moving the `_.extensions` creation into polyfill-wrapper-start perhaps?

**Comment by matthewp** [comment]
Yeah, I was thinking I might need to do that. It's nice to be able to define `._extensions` in core. Just for my knowledge, what is the reason why meta and register to be added first?

**Comment by guybedford** [comment]
Because core auto-loads Traceur, it needs to run after the register extension which does module loading. That in turn is dependent on meta to set custom formats inline.

**Comment by matthewp** [comment]
Ah, my problem was actually that the register extension has two `register` functions so when I try to push `register` into `loader._extensions` it is referencing the one within the closure. Hm, not sure I can fix this without renaming one of them.

**Comment by guybedford** [comment]
@matthewp I'm working on a PR right now to split up extension core. Will post it within the next 12 hours.

**Comment by guybedford** [comment]
@matthewp actually read this... can the stamping not be done automatically in the makefile itself?

**Comment by matthewp** [comment]
Yeah, it can, probably better to do it that way so that we don't have to worry about extensions being away of this api.

**Comment by matthewp** [comment]
Ok, updated again, let me know if there's anything else.
