### ISSUE TITLE
Named exports for non-ES6

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#334]
We can enable importing named exports for non-ES6 modules like:

```javascript
import { readFile } from 'fs';
```

To do this means making the module object look like:

```javascript
var mObj = { default: require('fs') };
// extend with named properties before defining the module
extend(mObj, mObj.default);
return System.newModule(mObj);
```

This is effectively what 6to5 does. It's just a one way road we should go down carefully...

**Comment by msegado** [comment]
Good timing - I actually just came here to see if there was something open on ES6/CJS interop.

The issue I ran into recently (which I think your proposal would fix) was that `System.import` behaves differently when loading CJS and ES6 modules. Example:
```javascript
System.import('es6module').then(function (m) {
    // here, m is the module, m.default is the default export
});
System.import('cjsmodule').then(function (m) {
    // here, m is the default export, m.default is an export named 'default'
});
```
...I discovered this when I tried transpiling some toy ES6 modules to CJS instead of System (using 6to5) and my async module load broke =)

I think your proposal above looks good, but it will take some thinking to handle the corner case in which a CJS module exports both an actual default and a named property called 'default':
```javascript
/* csjmodule.js */
exports = "foo";
exports.default = "bar";

/* main.js */
System.import('cjsmodule').then(function (m) {
    console.log(m.default); // umm...
});
```
Perhaps this is uncommon enough that you could just issue a warning for that case and put one of them in m.__conflicting_named_default or something, though that doesn't seem very standards-friendly.

Anyway, I see you're no stranger to discussion on these issues =) esnext/es6-module-transpiler#85

Also relevant: webpack/webpack#706

**Comment by guybedford** [comment]
@msegado the latest 6to5 3.0.0 will give a better behaviour here - the interop output went a bit off track a little at one point.

With the approach above, the `default` clashing is not a problem as we copy the exports out onto a module object with a default property.

**Comment by msegado** [comment]
@guybedford Oops; yes, I overlooked the fact that the named export would still be accessible as m.default.default...

```javascript
/* csjmodule.js */
exports = function foo() { return 'foo'; };
exports.default = function bar() { return 'bar'; };

/* main.js */
System.import('cjsmodule').then(function (m) {
    console.log(m.default()); // should print 'foo'
    console.log(m.default.default()); // should print 'bar'
});
```
Thanks for the heads up about 6to5 3.0.0!

**Comment by matthewp** [comment]
It seems dangerous to me to extend properties onto an object that were not already there. However... I cannot think of a downside off-hand.

**Comment by MajorBreakfast** [comment]
That's quite nice for modules like `path`, `lodash` and such.

I remember that traceur for node's `require()` had that behavior once. I think they removed it since.

**Comment by sebmck** [comment]
I'm a bit conflicted on the behaviour of 6to5. It doesn't really feel *right* to be able to use:

```javascript
import fs from "fs";
fs.readFile;
```
and

```javascript
import { readFile } from "fs";
readFile;
```

and have them work the same.

Unfortunately it seems to be the only way to get a good CommonJS interop that works well over named and default exports.

**Comment by MajorBreakfast** [comment]
@sebmck You're right. But at least I prefer that to not having the proper es6 way at all. Maybe an opt-out could be the solution?

The es6 way is:
``` JavaScript
import { readFile } from "fs"
// or
import * as fs from "fs"
```

**Comment by MajorBreakfast** [comment]
@guybedford (When) Will this feature land?

**Comment by sebmck** [comment]
@MajorBreakfast Hasn't even been implemented yet, this is a discussion issue to determine whether or not the tradeoffs are worth it.

**Comment by MajorBreakfast** [comment]
@sebmck It improves interop with cjs to make cleaner code possible. I really hope that this lands (soon :).

**Comment by sebmck** [comment]
@MajorBreakfast I know what it does :stuck_out_tongue_winking_eye: It's much more complicated than you'd think though such as how you'd handle namespaced/wildcard imports etc.

**Comment by TheFuzzball** [comment]
Bump?

Also, can we make this work with AMD modules that return an object?

e.g.

amd.js
```javascript
define(() => {
  return {
    foo() {
      return 'bar';
    }
  }
})
```

main.js
```javascript

import { foo } from 'amd';
console.log(foo()) // 'bar'

```

**Comment by matthewp** [comment]
@TheFuzzball why are you using amd if you have es6?

**Comment by TheFuzzball** [comment]
Interoperability with legacy code. I'd prefer not to have to go through existing code and convert it to ES6.
The way I see it SystemJS supports interperability with CommonJS and AMD modules, and it should be easy / nice to use with both.

**Comment by matthewp** [comment]
Does your code example work today?  I'd be a little surprised if it did.

**Comment by TheFuzzball** [comment]
Aside from the AMD code being ES6 instead of ES5 it works today, sure.

**Comment by patrickarlt** [comment]
Just as a note we are discussing this in https://github.com/Leaflet/Leaflet/issues/3229. This would be a great feature to have since we don't really want to rewrite everything to use ES6 modules and potentially impact downstream apps.

Glad to see this is getting worked on!

**Comment by guybedford** [comment]
Merged into master.

**Comment by jonaskello** [comment]
I'm a bit confused by this issue. As I understand it this issue states that I should be able to do named imports into an ES6 module from a commonjs module? However the [documentation](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#inter-format-dependencies) says:

>For convenience, named exports are also auto-populated but may not be correctly bound as expected, so use these carefully.

Also I cannot seem to get it working. Is it supposed to work?
