### ISSUE TITLE
Import CSS import not working for bundled modules

### ISSUE THREAD

**Issue by marjan-georgiev** [systemjs/systemjs#335]
I have a module that imports a CSS file using the `import 'file.css!'` syntax. After bundling the module during the build process, the CSS file is not loaded in the browser.

A test example is provided at https://github.com/amcdnl/systemjs-test/issues/2

If I use `System.import('file.css!')` instead of `import 'file.css'`, the file is loaded without a problem.

**Comment by guybedford** [comment]
Closing as I believe we worked this out this was because the css file was included in the bundle config.
