### ISSUE TITLE
Add __moduleName and __moduleAddress for anon System.register

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#340]
These should be added to the register extension handling of `System.register` anonymous output.

**Comment by guybedford** [comment]
Note that for CSP support, it is probably sensible to do this through second and third arguments being `__moduleName` and `__moduleAddress` rather than adding separate bindings.

**Comment by guybedford** [comment]
In addition, it will be possible to have the above `__moduleName` and `__moduleAddress` variables also populated by named System.register assuming that form.

**Comment by guybedford** [comment]
Effectively, the second argument of System.register can become the meta argument. Rather do this when the meta is worked out?

**Comment by MajorBreakfast** [comment]
Only two arguments sounds nicer.

`__moduleName` and `__moduleAddress` are private API of SystemJS, right? Is making them one day available via `import { moduleName, moduleAddress } of this module` currently under consideration?

**Comment by guybedford** [comment]
Yes exactly, it's private now, the issue here is to create that meta module so that System.register can fully support it. We just don't know what it will look like yet.

**Comment by olanod** [comment]
Will `__moduleName` and `__moduleAddress`  be variables in the scope of the file or can/will they be in the objects declared in that file?  
I was writing a decorator for a class and one thing I'd love to do is to know the path of the file of my decorated class. 
If I can do something like this without passing anything extra to the decorator it would be awesome.
```
import {withTemplate} from 'decorators';

@withTemplate
class MyElement {
}
```
```
export function withTemplate(target) {
    var path = getThePartOfThePathINeed(target.__moduleAddress);
    var defaultTemplate = `${path}/${classNameToFileName(target.name)}.html`;
    // ...
}
```

**Comment by guybedford** [comment]
You'd need to assign the `__moduleName` from the scope, potentially with the decorator as an expression:

```javascript
import {withTemplate} from 'decorators';

@withTemplate(__moduleName)
class MyElement {
}
```

**Comment by guybedford** [comment]
This issue is still blocked by being able to define metadata format in System.register.

**Comment by guybedford** [comment]
Will come naturally with the metadata system.
