### ISSUE TITLE
Loading es6 module loader with a different path

### ISSUE THREAD

**Issue by AlexKey** [systemjs/systemjs#341]
Is it possible to load the es6 module loader with a different path?

Our paths are determined with a cache busting hash, so even though systemjs and the es6 module loader are in the same physical path they won't be accessible in the same path.

e.g

/VersionedContent/BXCezsY6aYhgKzEvKK2evw/JS/Systemjs/system.js
/VersionedContent/AZCezsY6aYhgKz7899vw/JS/Systemjs/es6-module-loader.js

Is this something I can specify as a map? 

From what I can tell from looking at the code it creates a base path based upon it's current directory.

**Comment by guybedford** [comment]
The best way to do this is just to include it with a script tag before SystemJS.

**Comment by AlexKey** [comment]
Thanks @guybedford I took a slightly different approach an used a cache busting querystring with an incrementing number which we use elsewhere.

It'll de-cache it more often, but it's ok for the experiments.

If I put it in the script tags will that mean it'll be used even if it doesn't need to polyfil?

Or I'm guessing do all browsers need to be polyfilled at the moment?

**Comment by guybedford** [comment]
That can work too. But yes it always needs to be included anyway, the auto-loading is just a convenience.

**Comment by AlexKey** [comment]
Ah cool, I'll go with the two script tags :-)
