### ISSUE TITLE
[Question] How to make this kind of plugin

### ISSUE THREAD

**Issue by ocombe** [systemjs/systemjs#342]
Hey @guybedford, I have a question about a plugin that I'd like to write for SystemJS: I've developed an angularJS lib that let you lazy load any component (https://github.com/ocombe/ocLazyLoad) and I want to integrate it with SystemJS.

I want to know if it is possible to do this: When SystemJS loads a js file (or coffee, or typescript, or anything that will be compiled to js code), my plugin should: wait for the code to be executed (evaluated), but **before** the promise is resolved it should execute an action (in my case register any new angular component that could be defined in the source file) and resolve the promise at the end once it has been treated.
The detection of the components to register will be automatic when the code is evaluated, I don't need to parse the code to do that, but it is important that the promise isn't resolved until I've done my thing.
If the file doesn't contain any angular component, I'll resolve the promise immediately.

How would you write a plugin that could do that ?

**Comment by guybedford** [comment]
Awesome to hear you're checking it out. Will help where I can, feedback on areas where the docs are lacking is really welcome.

I would suggest doing this through the translate hook:

```javascript
export function translate(load) {
  if (!load.name.match(/\.customext$/))
    return load.source;
  return load.source + '  register('custom-module', ...)';
}
```

Let me know if that sounds sensible?

**Comment by ocombe** [comment]
Since this might happen on any kind of js file (it might be coffee or typescript, or even atscript), there might already be a translate plugin executed for this file. Is it possible to have more than one plugin for a file? We had this discussion in https://github.com/systemjs/systemjs/issues/287 and this might be one of these case where chaining plugins might be useful.

The doc mentions an "instantiate" plugin, but doesn't give any example of it. Wouldn't my plugin fall into this category?

It's important to notice that I will execute async treatments, but in the end I won't touch the source.

If I'm not mistaken your example won't work for me because the "register" fonction will be executed after the code has been evaluated (good), but it won't yield the resolve of the promise until the end of my async treatment (bad!).

```js
export function translate(load) {
  if (!load.name.match(/\.customext$/))
    return load.source;
  return load.source + '  register("custom-module", ...)';
}
```

should in fact be something like that:

```js
export function translate(load) {
  if (!load.name.match(/\.customext$/))
    return load.source;
  register("custom-module", ...).then(function() {
    return load.source;
  }
}
```

With the register function being a promise. Is this possible ?

**Comment by ocombe** [comment]
Ah I found an example that looks like what I might do (with the promise thing): https://github.com/systemjs/plugin-image/blob/master/image.js
I will return a promise like this but it will probably be in the translate function.
I just need to make sure that my plugin can be executed on any kind of js source code (+ coffee + typescript + ...) independently of any other plugin installed.

**Comment by guybedford** [comment]
@ocombe you want to be careful not to actually execute the code in translate as that will mess with circular references support. Happy to discuss the use case further if it helps.

**Comment by ocombe** [comment]
Yes, I don't want to execute the code myself, I want to execute my function once the code has been executed.
I've been looking at the source code of the es6-module-loader, and it looks like all the plugin are executed before the code evaluation.
Is there any chance that I could define a plugin that would be executed after the `__eval` function? Just after "// 15.2.4.5.3 InstantiateSucceeded" would be awesome. It would be some kind of "postEvaluated" plugin. Or maybe an "onLoad" plugin
Unfortunately I don't think that it is possible for now :(

**Comment by guybedford** [comment]
@ocombe perhaps explain exactly what you're trying to accomplish and I can see if I can suggest something?

**Comment by ocombe** [comment]
I don't know if you are familiar with Angular, but Angular 1.x doesn't offer the possibility to load a new component once the application has been bootstrapped.
You need to load all your source files at the beginning, otherwise Angular won't detect them. It won't throw an error, it will just ignore the new components.

My library (ocLazyLoad) plugs itself onto the Angular instantiation process and keeps a reference of all the providers. This way you can instantiate new angular component when you lazy load them.
Let's say that you need a new service that hasn't been loaded yet, you use my lib to load the file and it will return a promise. This promise is resolved once the service has been lazy loaded and instantiated with Angular.

To simplify the process, I'd like to use SystemJS for the imports.
You'd add an import for your service at the beginning of a file, SystemJS would load the file and execute the code, my plugin would know that a new service has been added (because it will override the angular.module('...').factory from angular), the plugin would make the instantiation of the new service, and SystemJS would resolve its promise.

Let's say that I'd do as you suggested and add a register function at the end of the source code: the code would be executed and my register function called. But this function is async, so SystemJS would resolve before I've had the chance to really register the new service.
The Angular code would try to use the new service, but since it doesn't know about it (because I haven't had the chance to register it yet) it would throw an error.

That's why my plugin needs to be executed after the code evaluation, but before SystemJS resolves its promise.

**Comment by guybedford** [comment]
@ocombe could you possibly wrap the `System.import` here - 

```javascript
function angularImport(name) {
  return System.import(name)
  .then(function(module) {
    return register(module);
  });
}
```

?

**Comment by guybedford** [comment]
Also, how does Angular itself deal with circular references for registrations?

**Comment by guybedford** [comment]
There are options here, but it depends on these edge cases. I can discuss on chat in a couple of hours too?

**Comment by ocombe** [comment]
Yes I could wrap `System.import` and it would work, but I was hoping to make something that use import so that users wouldn't have to learn a new syntax.
I need to list my use case to check how I would really use this.
I could also override the System.import function so that it would be the same name (kinda like what I do with the angular.module functions), but a plugin would be cleaner.

I think that Angular throws an error (Uncaught Error: [$injector:cdep]) if you try to do a circular reference.

I can discuss this on chat if you want too, in 2h. Gtalk (hangout) or skype?

**Comment by guybedford** [comment]
Sure, Skype in 2 hours (on the hour) would be good (better for my connection) - guy-bedford.
