### ISSUE TITLE
Access file in the mapped directory whose package.json doesn't have a main property

### ISSUE THREAD

**Issue by hgl** [systemjs/systemjs#345]
I'm trying to install [github:web-animations/web-animations-js](https://github.com/web-animations/web-animations-js), whose package.json doesn't have a `main` property. I try to import it like:

```js
import "web-animation-js/web-animations-next";
```

which supposedly should import `web-animations-next.js` in its package folder in `jspm_packages`, but jspm tries to open `web-animation-js/web-animations-next.js` from my project's root folder and throws `ENOENT` when bundling it.

Any way to make this work?

**Comment by guybedford** [comment]
It sounds like this is a jspm issue not a SystemJS issue.

Looking at the repo, you probably need to be requiring `web-animation-js/web-animations-next.min`.

**Comment by hgl** [comment]
Man, that was a quick reply! Thankk you. :)

I might debug into it, so was trying to import the unminified version.

Should I reopen this in jspm?

**Comment by guybedford** [comment]
Sure, issues for help getting libraries configured for jspm should be opened at https://github.com/jspm/registry/issues.

**Comment by hgl** [comment]
Overriding its `package.json` does sound like a solution, but isn't perfect IMHO. I wish jspm could make it work in the case where the main entry point is missing, but a specific importing file is provided by the author in the `import` clause.

**Comment by guybedford** [comment]
@hgl jspm does allow specific importing of the file in the import like you're doing - I think you were just referencing a path that didn't exist.

**Comment by hgl** [comment]
Oh, tou are right, I referenced an incorrect file, but change that doesn't fix the problem.

```js
import "web-animation-js/web-animations-next.dev";
```

```
$ jspm bundle move/main
Building the bundle tree for move/main...

err  Error: Error loading "web-animation-js/web-animations-next.dev" at file:/Users/hgl/dev/lab/jspm/web-animation-js/web-animations-next.dev.js
     Error loading "web-animation-js/web-animations-next.dev" from "move/main" at file:/Users/hgl/dev/lab/jspm/lib/main.js
     ENOENT, open '/Users/hgl/dev/lab/jspm/web-animation-js/web-animations-next.dev.js'
```

Clearly, jspm is trying to bundle the file from my project root folder.

I have tried another npm package where the main entry point exists, and I can import a specific file like `<pkgname>/<file>` with no problem, but no when the entry point is missing in `package.json`.

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/registry/issues/174.
