### ISSUE TITLE
Support SystemJS not loaded through a script tag in the browser

### ISSUE THREAD

**Issue by Bnaya** [systemjs/systemjs#349]
The js error i'm getting:
```
Uncaught TypeError: Cannot read property 'src' of undefined
```
On the var:
``
$__curScript
``
I've tried the csp version, i'm getting the same error.
Dose it suppose to work on this environment?

**Comment by guybedford** [comment]
I'd be happy to work towards supporting this environment. Currently SystemJS in the browser expects to be loaded through a script tag, and is failing when it tries to read its own tag here - https://github.com/systemjs/systemjs/blob/master/lib/polyfill-wrapper-end.js#L34. We should make this code fall back nicely if the script tag is not found.

**Comment by Bnaya** [comment]
The issue title is misleading imo.
I will explain. 
chrome content script (aka extension injected code) should be loaded via chrome.tabs.executeScript and not via DOM script tag.
Its a different animal. loading script via script tag will execute the code in the pade scope and not the extension scope.

To read more about it:
https://developer.chrome.com/extensions/content_scripts
search for chrome.tabs.executeScript(null, {file: "content_script.js"});

**Comment by guybedford** [comment]
Related -https://github.com/systemjs/systemjs/issues/272#issuecomment-74610328.

**Comment by guybedford** [comment]
Did you ensure you loaded `es6-module-loader.js` first before `system.js`?

**Comment by guybedford** [comment]
@Bnaya did you manage to get this to work?

**Comment by Bnaya** [comment]
No, but i have theoretical ugly solution 
this platform (chrome content scripts) is very problematic.
you don't have direct mechanism to load scripts.
You do have access to the DOM apis BUT when you load script file using script src it will run on the page scope and not in the content script scope.
You can load js files to the content script scope only via api that available only on the background page  of the chrome extension 
```js
chrome.tabs.executeScript(null, {file: "content_script.js"});
```
So in order to make it work you will need to add some code to the background page that listens for some event from content scripts and injects/evals the scripts on demand.
I guess that for this platform the best options is to work with build step that concats all the modules to single file also on development (eg browserify)

**Comment by guybedford** [comment]
@Bnaya you don't need to listen to events - just inject the module loader and system.js scripts and then use precompiled ES6. If you really want to use ES6 code directly (not advisable) then include Traceur as well. See https://github.com/systemjs/systemjs/blob/master/test/tests/worker.js for an example of this in web workers.

**Comment by Bnaya** [comment]
chrome content script is a different animal.
its just don't have any direct way to load scripts. that is the problem.

**Comment by guybedford** [comment]
Ok, it may make more sense to directly compile a bundle then, or just specify the js files individually in the manifest itself.

**Comment by guybedford** [comment]
@Bnaya if there's anything specific that can be done here do let me know. Otherwise closing for now.
