### ISSUE TITLE
6to5 has changed its name to BABEL

### ISSUE THREAD

**Issue by SerkanSipahi** [systemjs/systemjs#350]
see: https://github.com/6to5/6to5 redirect to https://github.com/babel/babel
todo: ?!? https://github.com/systemjs/systemjs/search?utf8=%E2%9C%93&q=6to5 ?!? change in babel?

**Comment by guybedford** [comment]
Renamed in https://github.com/systemjs/systemjs/commit/21cf5129da4788027a9f49de29579e9815cd9a30.
