### ISSUE TITLE
Supporting contextual AMD require

### ISSUE THREAD

**Issue by markstickley** [systemjs/systemjs#351]
Hi,

I'm seeing an issue when bundling with systemjs builder, although the issue comes when running the bundled code so I think I'm right in posting the issue here.

I have been using require.js until recently switching to system.js, but there are other clients for this library who still rely on require.js and so radically changing the source is not an easy solution...

The issue manifests when using the AMD pattern and you are a) handling circular dependencies or b) dynamically loading modules at run time. Using `require([module], callback)` in the body of a define block where `module` has not been specified as a dependency of the define block will give an error similar to this:

```
 Potentially unhandled rejection [2] TypeError: Error loading "module1" at http://spiritedaway.blinkbox.local:8080/module1.js
Module module3 not declared as a dependency.
    at http://spiritedaway.blinkbox.local:8080/system.js:1:6049
    at http://spiritedaway.blinkbox.local:8080/build/bundle0.js:13:5
    at http://spiritedaway.blinkbox.local:8080/build/bundle0.js:16:6
    at f (http://spiritedaway.blinkbox.local:8080/system.js:1:5933)
    at l (http://spiritedaway.blinkbox.local:8080/system.js:1:4623)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (http://spiritedaway.blinkbox.local:8080/system.js:1:8139)
    at o (http://spiritedaway.blinkbox.local:8080/es6-module-loader.js:7:17774)
    at p (http://spiritedaway.blinkbox.local:8080/es6-module-loader.js:7:18146)
    at j (http://spiritedaway.blinkbox.local:8080/es6-module-loader.js:7:15692)
    at k (http://spiritedaway.blinkbox.local:8080/es6-module-loader.js:7:16077)
```

This does not happen when using require.js and when using SystemJS with the unbundled code (so omitting these lines in config.js):

``` javascript
System.depCache['module1'] = ["module2"];
System.bundles['build/bundle0'] = ["module2","module1"];
```

I thought I might fix it by adding 'module3' to module1's depCache but that didn't do anything.

For a working example of the problem, please download this sample project and open index-system.html: http://www.markstickley.co.uk/system-require.zip

Am I doing something obviously wrong?

A use case for dynamically loading modules at run time is resolving circular dependencies predictably. If two modules depend on each other then depending on the entry point and its dependencies you may not be able to tell which will be loaded first and therefore which module will have one of its dependencies set to `undefined`. By removing the circular dependency from the define block and placing it in a require block inside the definition you only have to handle it once.

Another use case is when you get data back from a web service describing an object and you have to choose which module to load and instantiate based on the data received. Not knowing the data ahead of time you would have to depend on every single module which can lead to slow loading times so it's best to handle it at run-time. In our app the modules being loaded are bundled and referenced in `config.js` also.

Thanks!

**Comment by guybedford** [comment]
@markstickley the `require` object you are passing in is not a dynamic require, but the CommonJS-style require just like the AMD `define(function(require) {})` form. If you need a dynamic require like AMD, use the `System.amdRequire` as documented here - https://github.com/systemjs/systemjs/wiki/Module-Format-Support#requirejs-support.

**Comment by markstickley** [comment]
Thanks! I didn't think it was the same thing. However when I add the lines


in the `<head>` and remove the reference to `require` in the module I get a different error:

```
 Potentially unhandled rejection [2] TypeError: Error loading "module1" at http://localhost:8080/module1.js
undefined is not a function
    at http://localhost:8080/system.js:1:13224
    at Array.map (native)
    at a (http://localhost:8080/system.js:1:13190)
    at http://localhost:8080/build/bundle0.js:13:14
    at http://localhost:8080/build/bundle0.js:16:6
    at f (http://localhost:8080/system.js:1:5933)
    at l (http://localhost:8080/system.js:1:4623)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (http://localhost:8080/system.js:1:8139)
    at o (http://localhost:8080/es6-module-loader.js:7:17774)
    at p (http://localhost:8080/es6-module-loader.js:7:18146)
```

I also have concerns that if it was working it wouldn't handle the require call using paths relative to the module calling it since System.amdRequire is a global instance of require and not specific to a particular module.

**Comment by guybedford** [comment]
It would be interesting to know where in SystemJS that is breaking, by seeing the original source line of the error.

Yes relative requires this way are not supported. Rather use System.import for this - `System.import('./relmodule', { name: module.id }`, where `module` is the special module AMD dependency.

**Comment by markstickley** [comment]
It's line 1238:32 in system.src.js.

Is there likely to be support for relative requires in the future or is this a tactical decision that has been made? Making this code depend upon System would have a lot of knock-on effects and while we have a hacky workaround already it would of course be better if there was an officially supported solution!

Thanks :)

**Comment by guybedford** [comment]
We don't support importing the AMD-style contextual require. The way to do this would be with the `System.import` call as shown above. Perhaps have this in a conditional to support both environments, which would work fine.

This is certainly something we could support in the AMD layer, although I don't have the bandwidth myself to work on it myself right now. Feel free to make a PR, or let me know if you'd like to sponsor the feature.

**Comment by guybedford** [comment]
This is now supported.
