### ISSUE TITLE
Remove globals created by globals

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#352]
It may be worth considering having the global module format remove the globals defined by each module after execution.

This way, Angular would never define its global, so that users are always encouraged to import it, which in turn will remove possible build race conditions if angular isn't defined in time.

Global dependencies of other globals will still get those globals defined, just for their initial execution.

The case that is left out here though is if a global is accessed asynchronously in the code, instead of referenced during the initial execution (`var angular = window.angular`). But making this case throw would avoid multi-version errors as well.

Not completely sure which wins - the async issue or strictly encouraging modular code.

**Comment by MajorBreakfast** [comment]
I like the idea because it uncovers where import statements are missing.

However, globals are kind of useful when working on the console, e.g. `$('.use-jquery-to-select-stuff')` Maybe there's a way to keep the available there?

**Comment by guybedford** [comment]
Thinking about this further, unfortunately it is just an ideal. The reason being that most globals do access other globals in asynchronous global scope.

**Comment by MajorBreakfast** [comment]
@guybedford Yeah sure. Anyway, I really like that you try to discuss that kind of stuff in the open. That's BTW also the reason why I'm watching this project ;)
