### ISSUE TITLE
Passing text string vars into require

### ISSUE THREAD

**Issue by lmartins** [systemjs/systemjs#354]
Hi,

Not sure this a bug with the library or with my code, but here's what i've found:

In my project I load JS based on the site's current view, like this:
```
    var currentView = document.body.getAttribute('data-jscontroller');
    if ( currentView ) {
        var viewPath = './views/' + currentView;
        require( viewPath );
        App.Views[currentView].init();
    }
```

Unfortunately this returns an error:
```
es6-module-loader.js:7:26213
TypeError: Module ./views/home not declared as a dependency.
The contents of the file being required is a simple object that simply builds an object with event subscribers to the app functionality for the loaded view.
```

The weird thing about is that `viewPath` var as a value of `./views/home` and if I put that directly in the require it loads the JS without any issue.

Any tips?

**Comment by matthewp** [comment]
Use System.import when you need to do things like this. require is statically parsed.
