### ISSUE TITLE
__esModule should be picked up by SystemJS

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#359]
We should treat this as an ES6-style module.

**Comment by matthewp** [comment]
All that is old is new again? ;-)

**Comment by guybedford** [comment]
Yes, finally relevant again! Too lazy to link the old issues. Let's just pretend it hasn't already been discussed many times before :)

**Comment by MajorBreakfast** [comment]
``` JavaScript
module.exports = { default: 'hello', __esModule: true}
```
``` JavaScript
import hello from 'some-module' // hello === 'hello'
```
That it?

**Comment by guybedford** [comment]
Yes as well as named exports support.

**Comment by MajorBreakfast** [comment]
I'm still kinda liking https://github.com/systemjs/systemjs/issues/334 which would enable that for all modules without requiring code changes to them. `__esModule` could still exist and make things cleaner if it is set.
