### ISSUE TITLE
System loader as a separate instance (different context)

### ISSUE THREAD

**Issue by marcfallows** [systemjs/systemjs#360]
Is it possible to have a separate instance of System which runs a completely different config? 

I have my app using SystemJS, but I have a legacy application I'm porting in as sort of a "sub-app" which I want to use System, but requires a separate config, baseURL, etc.

So, I would need something like:

``` javascript
var someOtherSystem = new System();

// Does not clobber any previous calls to System.config();
someOtherSystem.config({
   baseURL: '/path/to/base/'
});
// Loaded based on the config above, not the global System config.
someOtherSystem.import('module');
```

I can't find anything in the docs which does this. But it seems it should be possible.

**Comment by MajorBreakfast** [comment]
I think it is done this way:
```
var someOtherSystem = new Loader(System);
```
Taken from https://github.com/systemjs/builder/blob/master/index.js#L46

**Comment by guybedford** [comment]
There is a `System.clone` function which was recently added to support this more easily.

**Comment by marcfallows** [comment]
Thanks!

@guybedford Are both valid? I'm currently using 0.11.2. Should I upgrade and use clone()? Or can I use @MajorBreakfast's suggestion?

**Comment by guybedford** [comment]
Both should work - note you do need to do more work with the other method setting things like `baseURL` manually, as in the SystemJS builder code.

**Comment by marcfallows** [comment]
Great, thank you for the help!

**Comment by MajorBreakfast** [comment]
@marcfallows Always upgrade :) Things tend to break only minimally and having new features available right away is awesome.
