### ISSUE TITLE
Importing polyfills

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#361]
I've come across a library that polyfills a function on the global `window` object like so:

``` js
(function() {
  'use strict';

  if (window.fetch) {
    return
  }

  window.fetch = function (){};
})();
```

https://github.com/github/fetch/blob/2f2ed4c171babfaa6b354b06083c5ebd4931066a/fetch.js#L5

In environments without `window.fetch`, importing this file will give us the `window.fetch` polyfilled function. In environments with `window.fetch`, importing this will give us an object.

How should SystemJS handle importing polyfills such as this? Is this an error in the polyfill script itself?

At the moment I am having to do this to workaround the issue:

``` js
import x from 'fetch';

var fetch = (typeof x === 'function') ? x : window.fetch;
```

**Comment by guybedford** [comment]
This is where it can be useful to set shim configuration - if you just set the shim in the override to define the `export` value as `fetch` then it should work out. It would be great to have that in the registry as well.

**Comment by MajorBreakfast** [comment]
@guybedford I think it doesn't work because the module conditionally sets `window.fetch`.

@OliverJAsh Why do you want to import `fetch` if the module already sets it on window?
```JavaScript
import 'fetch-polyfill'
```

**Comment by OliverJAsh** [comment]
@MajorBreakfast Good point!
