### ISSUE TITLE
Global module's dependencies not loaded correctly if module has init function

### ISSUE THREAD

**Issue by codazzo** [systemjs/systemjs#362]
I seem to have encountered an issue with the global module extension. I have two global modules and one of them has a dependency on the other. This is how I configure them:
```js
System.config({
  "meta": {
    "vendor/highcharts/js/highcharts.src": {
        "format": "global",
        exports: "Highcharts"
    },
    "vendor/highcharts/js/modules/exporting.src": {
      "format": "global",
      "deps": [
        "vendor/highcharts/js/highcharts.src"
      ]
    }
  }
});
```
I tried adding an `init()` function to the latter but this does not work at the moment. The problem seems to be that the module's dependencies are not passed to [`retrieveGlobals`](https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L67-L72) when it's being [instantiated](https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L141). An easy fix would be to add the `deps` parameter, which is missing. Another problem appears in that case though - when loading `vendor/arts/js/modules/exporting.src`, the dependency has not been fully loaded so it cannot be required in https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L70. One solution would be to let `retrieveGlobals` return a Promise and use `System.import` instead of `require`. What do you think @guybedford? I'm happy to issue a PR in that case. Still quite new to System.js so apologies if I'm getting something fundamentally wrong here.

**Comment by guybedford** [comment]
@codazzo the configuration used there looks right to me - it should be defining correctly. My guess is that if it isn't, the meta isn't actually being applied at all.

The thing to ensure with meta is that the module name used is fully normalized. One thing to test is that `System.normalize('vendor/highcharts/js/modules/exporting.src').then(console.log.bind(console))` and see that the name normalizes correctly to itself. Alternatively just double-check the meta is applying by changing the format to AMD or something that should in theory break and seeing that it breaks accordingly.

If the meta is really applying, then it looks like it could be a bug, but I doubt that there is a bug in the meta.

**Comment by guybedford** [comment]
Do let me know if you still need help with this at all.

**Comment by codazzo** [comment]
Hi @guybedford - thanks for replying, and apologies for the delay.
The meta is indeed applied correctly, but the problem only arises if you add an init function to the metadata. I'm getting an exception at https://github.com/systemjs/systemjs/blob/45c13842cf36998ee92797fd479f88be648c266f/lib/extension-global.js#L71 as `deps` is not defined - that seems to be the cause of the issue (the parameter is not passed to `retrieveGlobals`).

**Comment by guybedford** [comment]
Ahh right - this is https://github.com/systemjs/systemjs/issues/237 then.

**Comment by codazzo** [comment]
Ah, should have looked it up beforehand. Thanks for clarifying :+1:
