### ISSUE TITLE
`this` in AMD is `undefined` if it's imported after a strict mode script

### ISSUE THREAD

**Issue by hgl** [systemjs/systemjs#363]
index.js
```
import "./class";
import "./this";
```

class.js
```
export default class {}
```

this.js
```
define(function (require, exports, module) {});
console.log(this);
```

Importing `index.js` outputs `undefined`. By removing `import "./class";`, it outputs `window`.

**Comment by guybedford** [comment]
That's really odd. I can't see offhand why that would be happening at all. It's certainly a bug though.

**Comment by hgl** [comment]
From the generated script via bundle-sfx, it seems that AMD scripts have the converted `System.register()` calls wrapped in IIFEs, and since a previous script use `"use strict"` in the same lexical scope, that cause the IIFE to destroy the `this` value.

Commonjs scripts are not wrapped with such IIFEs.

**Comment by guybedford** [comment]
How is the `"use strict"` statement in the same lexical scope though? Surely the ES6 code should be surrounded in a function closure itself that uses `"use strict"`?

**Comment by hgl** [comment]
I get this (partial) generated code:

```js
"format register";
(function(global) { ... })(typeof window != 'undefined' ? window : global)
('index', function(System) {

"use strict";

System.register("class", ...);

(function() {
function define(){};  define.amd = {};
System.register("this", [], false, function(__require, __exports, __module) {
  return (function(require, exports, module) {}).call(__exports, __require, __exports, __module);
});
console.log(this);
})();

"use strict";

System.register("index", ["class", "this"], ...);
});
```

Clearly the first "use strict" isn't surrounded in its own closure.

**Comment by hgl** [comment]
BTW, if the solution is to simply wrap es6 code in a closure, are you saying that `this` in AMD is **supposed** to be `undefined`, where as in commonjs it should be the global object?

**Comment by guybedford** [comment]
Thanks, this is actually a Traceur bug that the `"use strict" is being leaked out of the `System.register` closure. I've posted https://github.com/google/traceur-compiler/pull/1782 as a fix.

**Comment by hgl** [comment]
Ah, thanks for fixing it quickly. But strangely, I was asking jspm to use babel, and babel seems to put `"use strict"` in `System.register()` correctly.

So no matter which transpiler I specified, jspm will use Traceur to transpile es6 modules?

**Comment by guybedford** [comment]
It sounds like the setting may not be passing through properly. Are you using SystemJS manually or through jspm? Double-check you're including the `transpiler` option.

**Comment by hgl** [comment]
I use systemjs through jspm, and just double checked, `transpiler` maps to `"babel"`.

Running `bundle-sfx` gives the incorrect `"use strict"` from Traceur (which I assume).

Here are the file contents:

package.json:

```json
{
  "jspm": {
    "directories": {
      "lib": ".",
      "packages": "jspm_packages"
    }
  }
}
```

config.js
```js
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "paths": {
    "*": "*.js"
  }
});
```

**Comment by guybedford** [comment]
It's definitely not running Traceur in my tests. Can you confirm your version of jspm / SystemJS builder?

**Comment by hgl** [comment]
`$ jspm -v`
```
0.14.0
Running against global jspm install.
```

and digging into the global jspm's `node_modules`, it's using version `0.9.0` of systemjs-builder

**Comment by guybedford** [comment]
Your config and version should be using Babel fine. The way to tell if it's Babel or Traceur is if the `System.register` output looks like:

```javascript
System.register("tests/jquery", ["github:components/jquery@2.1.3"], function (_export) {
```

Then it is Babel. If it looks like:

```javascript
System.register("tests/jquery", ["github:components/jquery@2.1.3"], function ($__export) {
```

then it is Traceur.

**Comment by hgl** [comment]
Ah, then it is using Babel, I have this:
```js
System.register("class", [], function (_export) {});
```
in `build.js`.

Is it because system 0.9.0 is using an older version of Babel? I manually transpile es6 with latest Babel with system format, and the generated code is correct.

**Comment by guybedford** [comment]
That could make sense if Babel has changed. Perhaps an npm update of jspm would help then.

**Comment by hgl** [comment]
Problem solved!! Thank you so much.

However, I was using `npm update -g jspm`, and if jspm's version is up-to-date, its dependencies won't be updated. uninstall & install jspm does the trick.

**Comment by guybedford** [comment]
Wow, I didn't know that... may be worth checking you're running an up-to-date npm (jspm update always verifies deep dependencies at latest, it's kind of the definition of updating).

**Comment by hgl** [comment]
Yes, you are right, I was using an older version of npm. Just updated, hope it won't bite me again. :)

Thanks again for all the helps.
