### ISSUE TITLE
[Web Workers] System.config() missing

### ISSUE THREAD

**Issue by stefanr** [systemjs/systemjs#364]
Is there a reason why the config method is missing inside a web worker? Setting the paths manually using `System.paths = {"*": "*.js", ...}` seems to work fine.

Allowing to import the auto generated config file would make sense. 

```js
importScripts("jspm_packages/system.js");
importScripts("config.js");

System.import("worker/test").then(function (module) {
  ...
});
```

**Comment by guybedford** [comment]
Are you saying `System.config` is not defined within a web worker context? This is certainly a bug if so. Are you sure you're looking at the right `System` global and not the one provided by Traceur perhaps? (the way to tell is by the properties).

**Comment by stefanr** [comment]
Yes it's the right `System` because `System.import` works as expected. `System.config` is not defined.

In general the `System` object is very different inside a web worker. It has a different prototype chain and is missing some properties like `config` or `register`.

Besides a `version` property would be helpful, as well as a property to determine if the script is running inside a web worker or not.

**Comment by MajorBreakfast** [comment]
I've been using SystemJS in a web worker for a few weeks now. Not sure what goes wrong here, though.

**Comment by guybedford** [comment]
@stefanr you are definitely seeing Traceur's `System` global there instead of SystemJS. Make sure you include Traceur first before SystemJS. See https://github.com/systemjs/systemjs/blob/master/test/tests/worker.js for an example.

**Comment by guybedford** [comment]
Let me know if you got it working ok. Closing for now.

**Comment by stefanr** [comment]
No it's not Traceur's `System`. In web workers `System` is an instance of `SystemLoader` whereas in the browser it's an instance of `Loader`. It seems that `System` is changed somewhere in `upgradeSystemLoader()` (haven't looked into it in detail) which is called after importing the module loader in browser mode. So the behavior is certainly different. Since it's called in the else branch I suppose it's save to call it inside a web worker.

@MajorBreakfast: So because of this I have no idea why this is working for you.

Suggestion for "fixing?" this in [polyfill-wrapper-end.js#L85](https://github.com/systemjs/systemjs/blob/master/lib/polyfill-wrapper-end.js#L85):

```js
else if(isWorker) {
    [...]
    if (!$__global.System || !$__global.LoaderPolyfill) {
      [...]
      importScripts(basePath + 'es6-module-loader.js');
      $__global.upgradeSystemLoader();
    } else {
      $__global.upgradeSystemLoader();
    }
  }
```

**Comment by guybedford** [comment]
@stefanr it sounds then like it's just es6-module-loader.js without system.js applied? You need to include es6-module-loader.js first then system.js to get the right System. The PR looks good for a fix though too.

**Comment by MajorBreakfast** [comment]
@stefanr I did it like in the unit test @guybedford mentioned.
