### ISSUE TITLE
How To Mock Dependencies For Testing?

### ISSUE THREAD

**Issue by micahasmith** [systemjs/systemjs#366]
I was wondering how to mock a module's dependency for a test?

For instance, let's say that I have a module A that references another module B, but for my unit test I want module B to be swapped out with a fake-- can I do that with systemjs? (esp with es6 modules)

Wasn't able to find any info online. Thanks!

**Comment by matthewp** [comment]
System.map["moduleB"] = "fake/moduleB";

**Comment by micahasmith** [comment]
sweet. so just do that before importing the module and its all good?

also, does it keep these fake dependencies within the scope of one test file? anything i should know about "resetting"/"clearing out" the fakes?

**Comment by guybedford** [comment]
You can "swap out" dependencies with something like:

```javascript
System.set('custom/module', System.newModule({ custom: 'module' }));
var tmp = System.get('custom/module');
System.set('custom/module', ...); // etc
```

**Comment by micahasmith** [comment]
Both of these means don't work for me:

https://github.com/micahasmith/babel-test/blob/master/test/app.test.js#L15-L47

**Comment by guybedford** [comment]
I take it you're swapping out dependencies of the module you're importing? If so note you need to System.delete the index.js module by exact name as well as both dependencies before re-importing to get the right effect.

**Comment by micahasmith** [comment]
thanks! going to test now

**Comment by micahasmith** [comment]
Doesn't work for me either:

https://github.com/micahasmith/babel-test/blob/master/test/app.test.js#L50-L96

Is there some other way devs are going about this now? (Am i using an antiquated solution to code isolation via dep swapping?)

**Comment by guybedford** [comment]
It could be worth ensuring the delete operation is returning true to indicate its actually doing something. Note you need to be using SystemJS 0.15 with the fix from https://github.com/ModuleLoader/es6-module-loader/issues/313.

**Comment by micahasmith** [comment]
its in there in both of the new tests, `System.delete("src/index");`

**Comment by guybedford** [comment]
Yes - but check it is returning `true` just like `var p = {a: 'value'} delete p.b` returns false unless p.b exists.

**Comment by guybedford** [comment]
Actually `delete` doesn't do that, but `System.delete` does...

**Comment by micahasmith** [comment]
Yep, returns `true`

**Comment by guybedford** [comment]
And you're definitely using SystemJS 0.15?

**Comment by micahasmith** [comment]
i npm installed jspm yesterday, it was version v0.14

it included systemjs v0.13.2

even if i upgrade and get this fixed though, it'll only lead into the problem that they systemjs loader is based on a global mutable singleton map of dependencies, which means i would have to enforce order/non-async execution of my tests in order to ensure that while i mutate the System.js config for one test its not trying to import/use that config in another test, correct?

or does System.js have a means to mutate within a sandbox/context?

**Comment by guybedford** [comment]
Right, the SystemJS update for jspm that will make this work is coming tomorrow or Friday (working on it).

If you want to create a custom version of SystemJS for testing, you can use `System.clone()` which will create a new loader for you. You still need to run config on it after cloning though.

**Comment by micahasmith** [comment]
Awesome. Well i'm super excited to try both after the release.

I'll check back in on this next week then. Thanks!

**Comment by onlywei** [comment]
After some trial and error, I finally got this working. I had to call `System.normalizeSync()` on all paths, otherwise they didn't work.

```js
let functionToTest;

beforeEach((done) => {
  System.delete(System.normalizeSync('foo/bar.js'));
  System.set(System.normalizeSync('foo/bar.js'), System.newModule({...});

  System.delete(System.normalizeSync('foo/functionToTest.js'));
  System.import('foo/functionToTest.js').then((imported) => {
    functionToTest = imported;
  }).then(done, fail);
});
```

I think it's kind of weird that I have to do this, because `System.normalizeSync()` is not an advertised method in any API docs. @guybedford I'm not sure if this is intentional. I think a sensible default for `System.delete()` might be to automatically call `System.normalizeSync()` internally if the initial attempt didn't delete anything? What do you think?

**Comment by guybedford** [comment]
@onlywei that is exactly correct.

**Comment by onlywei** [comment]
@guybedford should the `normalizeSync()` method be displayed in the System API docs, or do you have a vision to simplify this API for mocking?
