### ISSUE TITLE
Issue using the jspm cli to install Angular-Material

### ISSUE THREAD

**Issue by ThomasBurleson** [systemjs/systemjs#367]
I am using `jspm install angular-material`; Angular-Material a library that has registered dependencies upon Angular, Angular-Animate, and Angular-Aria. 

With the above commend, all libraries are downloaded and installed in `jspm_packages/angular` correctly.
Afterwards, I try do use an import in my `boot.js`:

```js
import angular from 'angular'
```

An error occurs in the dev console: `Error loading "angular" at http://localhost:8080/angular.js`. This is unexpected and confusing (IMHO). After some consideration, I finally realize that I must manually install these also with:

```console
jspm install angular
jspm install angular-aria
jspm install angular-animate
```

Questions:
*  Is this process correct; or am I missing a key install option ?
*  Any recommendations for an improved installation procedure ?

**Comment by guybedford** [comment]
You need to manually install anything you are going to require in your code regardless of whether it exists already as a third-party dependency. So in this case if you explicitly require angular, you need to install angular, but not the other libraries.

**Comment by ThomasBurleson** [comment]
@guybedford  - Good to know.  Yes, in this case I will need to require all 4 libraries... and thus will need to manually install each. 

> Wonder if this fact is in the docs anywhere? This scenarios will probably confront other developers similarly in the future.

BTW - jspm totally rocks!

**Comment by guybedford** [comment]
Thanks! Yes it would be worth mentioning along with the dependency handling somewhere in the wiki.
