### ISSUE TITLE
SystemJS with Babel on Node.js

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#372]
I have attempted to wire up a bootstraper with babel as the chosen transpiler. But the transpiler doesn't load.

Giving me the error "Unexpected reserved word" when trying to load the file ,/app in which a class is defined.

What am I missing? What dependencies have I missed?

    var System = require('systemjs');
    
    System.config({
      "baseURL": "./",
      "transpiler": "babel",
      "babelOptions": {
 	   "experimental": true
      },
      "paths": {
        "*": "*.js"
      }
    });
    
    System.import('./app').then(function (app) {
    	
    });

**Comment by guybedford** [comment]
Ensure that your app file is being detected as ES6. If its not importing or exporting anything it won't be detected and treated as a module. So either add module syntax or use meta - `"format es6"` at the top of the code for example.

**Comment by robertsundstrom** [comment]
@guybedford I solved it. 

I assume the that the problem was that SystemJS didn't find the babel-files before - as they were located in a sub-directory.

I now have a project consisting of the following files:
* bootstrap.js
* app.js

And of course:

* babel.js
* babel.js
* babel-polyfill.js
* babel-helpers.js

All files are located in the root.

bootstrap.js looks like this: 

    var System = require('systemjs');
    require("./babel-polyfill");
    
    System.transpiler = 'babel';
    System.babelOptions = {
	    experimental: true
    };

    System.import('./app').then(function(m) {
      console.log(m);
    });

Please tell me if something is wrong or unecessary!

**Comment by guybedford** [comment]
Out of interest is this code running in Node or the browser?

**Comment by robertsundstrom** [comment]
Ah! I forgot to mention that it is in Node.

**Comment by guybedford** [comment]
Ok that looks right then! If you want Babel in another path you can set:

```javascript
System.paths['@babel'] = 'path/to/babel.js';
```

I'm working on better auto-loading for the polyfill now as well. This workflow will be easier in the next release.

**Comment by robertsundstrom** [comment]
Alright. I'm hoping for better Node-support over all, both in SystemJS and JSPM. 

A colleague of mine noticed that babel-specific errors aren't emitted when loaded through the ES6 module-loader - what would be emitted when running the babel-node CLI.

Another peculiar behavior is that at least one "import * from" statement seems to be required in the initial module (the one loaded by System.import() ) or else babel will neither load or parse the file as ES6.

**Comment by guybedford** [comment]
@robertsundstrom are you adding a catch handler to the import promise? Could be worth checking that.

Yes - that catch should be better documented. Files without module syntax are not auto-detected as es6 and require manually indicating to SystemJS that they are ES6. One way to do this is to add `"format es6"` at the top of the file.

**Comment by robertsundstrom** [comment]
@guybedford Thank you very much! That made my colleague, who nearly lost his faith in this, very happy.

We also want to use JSPM in our project(s) - both in the front-end website (easy, when we follow the guides) and in the service back-end (pure Node, hard). The latter is tricky.

How do we do that the easiest way to get going? Are there any samples available for node projects?

BTW. With SystemJS only, we had an issue when referencing NPM-packages. The import-statement did not find the dependencies that we installed through NPM. We had to use require(..). How do you resolve that?

That needs to be documented and samples to be developed. I'm open for contributing to the effort.

**Comment by guybedford** [comment]
@robertsundstrom the backend support for jspm is limited, see https://github.com/jspm/jspm-cli/wiki/NodeJS-Usage. Basically we're waiting on the conditional loading feature of SystemJS before we can support code-splitting between server and client, and for now we always follow the "browser" path.

With the above, some Node packages will work on the server, but road blocks get hit quite quickly. I would advise running npm on the server until this feature is in.

**Comment by guybedford** [comment]
About resolving npm packages - jspm exactly sets up npm packages for resolution through SystemJS as it is a different resolution process.

**Comment by robertsundstrom** [comment]
OK. I understand that. Then we'll have to wait then. 

But I really like the idea of JSPM, especially that you can potentially get everything from various sources through one CLI and bundle dependencies to your product when releasing.

You've done a great job so far, btw!

**Comment by robertsundstrom** [comment]
Here's my new starter template:

https://github.com/robertsundstrom/SystemJS-Node-Starter-Template

Hope that this will be helpful to someone.

**Comment by guybedford** [comment]
It could be worth mentioning the above project on the group or in the Gitter room.

Thanks for the feedback.
