### ISSUE TITLE
Please Help with configuring load and test

### ISSUE THREAD

**Issue by kburson** [systemjs/systemjs#373]
Ok, I have been pounding my head against the desk for far too long, it is time to ask for help.
Maybe I am way off base, or I just cannot see the trees in the forest.  Please help.

I am trying to build an application using gulp, Angular 1.3+, ES6, traceur, SystemJS, es_module_loader and http-server.  I want to pre-transpile the ES6 and serve them as static ES5 files rather than have the browser compile the files at runtime...  I simply believe it will be more performant.

I have looked at several modules loaders, I like SystemJS, especially after watching Mr Bedford's presentation on JSPM, SystemJS and es6_module_loader given last year at jsconf, although I am considering browserify or webpack if I cannot get this to work.

So far the app is looking good, it compiles and hosts just fine from the compiled folder location, but I cannot get Karma to run a single test within my compiled project.

Here is my project structure:

```bash
gulpfile.js
client/
    - src
        - app/
            - bootstrap.js
            - system.config.js
            - index.html
            - modules/
                  - app.module.es6
                  - AppRouter.es6
                  - app.less
                  - common/
                       - common.module.es6
                       - masterTemplate/
                               - MasterTemplateController.es6
                               - MasterTemplateController.spec.es6
                               - masterTemplate.tpl
                               - masterTemplate.less
                  - home/
                      - home.module.es6
                      - home.less
                      - greeting/
                            - GreetingController.es6
                            - GreetingController.spec.es6
                            - greeting.less
                            - greeting.tpl
                    ...
                          
```

using gulp and traceur I am able to transpile all the es6 code to es5 modules with amd wrappers. 
The compiled artifacts are laid out in a build folder as such:

```bash
_build/
   - css/
   - fonts/
   - img/
   - js/
      - lib/...
      - modules/
         - common/...
         - home/
             - greeting/
                  - GreetingController.js
             - home.module.js
         - app.module.js
         - AppRouter.js
         - mock.app.module.js
      - bootstrap.js
      - system.config.js
   - index.html
   
```

The compiled layout is not identical to the source layout, but it is very close: 
 
* The vendor libs are in the `lib` folder and come from 3 different places (npm, bower and a custom download).  
* The `fonts`, `css` and `img` folders are collected from several sources.  
* The `_build/js` folder is nearly identical to the `client/src/app folder`, except the `index.html` file is one level up.
* The html template files (`*.tpl`) {some call these partials} are all compiled into a $templateCache module 
  saved under `_build/js/modules/common/templates/templates.module.js`

then I serve it up using http-server.  The `index.html` loads up the runtime infrastructure 
and finally the `bootstrap.js`, which uses SystemJs to bootstrap angular starting with the `/modules/`.
      
```html
<!doctype html>
<head>
    <title>App</title>
    
    <link rel="icon" type="image/png" href="/favicon.png">
    <link rel="stylesheet" href="/css/app.css">
    
    <script src="/js/lib/traceur-runtime.js"></script>
    <script src="/js/lib/system.js"></script>
    <script src="/js/system.config.js"></script>

</head>
<body>
<div ui-view="main" class="root-view"></div>
<script src="/js/bootstrap.js"></script>
</body>
</html>
```

This works great.  Everything loads and present as it should.

Now I go to test it...  Because I am using SystemJs to load all dependencies (identified using `import` in each module and subsequent src file) I need to use **karma-systemjs** to help karma find and load those same files.  
Here is my `karma.config.js`, which is stored at `client/src/tests/karma/karma.config.js`

```js
module.exports = function (config) {
  config.set({
    basePath: '../../../../,
    urlRoot: '',
    hostname: 'localhost',
    frameworks: [ 'systemjs','mocha','chai','chai-as-promised','sinon-chai'],
    plugins: [
      'karma-mocha',
      'karma-chai',
      'karma-chai-plugins',
      'karma-systemjs',
      'karma-traceur-preprocessor',
      'karma-chrome-launcher',
      'karma-firefox-launcher',
      'karma-spec-reporter',
      'karma-junit-reporter',
      'karma-failed-reporter'
    ],
    systemjs: {
      configFile: '_build/js/system.config.js',
      files: [
        '_build/js/lib/*.js',
        '_build/js/modules/**/*.js',
        'client/src/app/**/*Spec.es6'
      ],
      config: {
        transpiler: 'traceur',
        paths: {
          'angular':           '_build/js/lib/angular.min.js',
          'angular-animate':   '_build/js/lib/angular-animate.min.js',
          'angular-messages':  '_build/js/lib/angular-messages.min.js',
          'angular-aria':      '_build/js/lib/angular-aria.min.js',
          'angular-resource':  '_build/js/lib/angular-resource.min.js',
          'angular-cookies':   '_build/js/lib/angular-cookies.min.js',
          'angular-storage':   '_build/js/lib/angular-storage.min.js',
          'angular-material':  '_build/js/lib/angular-material.min.js',
          'angular-mocks':     '_build/js/lib/angular-mocks.js',
          'angular-ui-router': '_build/js/lib/angular-ui-router.min.js',
          'statehelper':       '_build/js/lib/statehelper.min.js',
        }
      },
      testFileSuffix: '.spec.js'
    },
    preprocessors: {
      'client/src/app/**/*.spec.es6': ['traceur']  // pre-compile tests
    },
    traceurPreprocessor: {
      options: {
        modules: 'amd',
      },
    },
    client: {
      mocha: {
        reporter: 'html',
        ui: 'bdd'
      }
    },
    reporters: ['junit', 'spec', 'failed'],
    reportSlowerThan: 1000,
    junitReporter: {
      outputFile: 'reports/unit-test-results.xml',
      suite: ''
    },
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: [
       'Chrome'
    ],
    captureTimeout: 10000,
    port: 9876,
    runnerPort: 9100,
    singleRun: true,
    background: false
  });
};

```

after I build the app and run `gulp karma` I get this incredibly useful error message:

```bash
ERROR [karma]: Uncaught TypeError: Illegal module name "/base/client/src/app/modules/home/greeting/GreetingController.spec"
at http://localhost:9876/base/node_modules/es6-module-loader/dist/es6-module-loader.src.js?3aac9167d6f21486de90ab673ff41c414843e2b4:2667

Chrome 41.0.2272 (Mac OS X 10.10.2): Executed 0 of 0 ERROR (0.399 secs / 0 secs)


[02:17:59] 'karma' errored after 1.81 s
[02:17:59] Error: 1
    at formatError (/Users/kpburson/.nvm/versions/node/v0.12.0/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/kpburson/.nvm/versions/node/v0.12.0/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/kpburson/projects/ver-client/node_modules/orchestrator/index.js:264:8)
    at /Users/kpburson/projects/ver-client/node_modules/orchestrator/index.js:275:23
    at finish (/Users/kpburson/projects/ver-client/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/kpburson/projects/ver-client/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/kpburson/projects/ver-client/node_modules/karma/lib/server.js:220:7)
    at Server.<anonymous> (/Users/kpburson/projects/ver-client/node_modules/karma/lib/server.js:231:9)
    at Server.g (events.js:199:16)
```

The `system.config.js` file is:

```js
System.config({
  baseURL: '/js/', 
  paths: {
    'angular':          '/js/lib/angular.js',
    'angular-animate':  '/js/lib/angular-animate.js',
    'angular-aria':     '/js/lib/angular-aria.js',
    'angular-cookies':  '/js/lib/angular-cookies.js',
    'angular-material': '/js/lib/angular-material.js',
    'angular-messages': '/js/lib/angular-messages.js',
    'angular-mocks':    '/js/lib/angular-mocks.js',
    'angular-resource': '/js/lib/angular-resource.js',
    'angular-storage':  '/js/lib/angular-storage.js',
    'angular-ui-router':'/js/lib/angular-ui-router.js',
    'statehelper':      '/js/lib/statehelper.js'
  },
  meta: {
    'angular': {format: 'global', exports: 'angular'},
    'angular-ui-router': {format: 'global', deps: ['angular']},
    'statehelper': {format: 'global', deps: ['angular', 'angular-ui-router']}
  }
});
```

and the `bootstrap.js` file is:

```js
System.import('app.module').then(
  function (a) {
    angular.element(document).ready(
      function () {
        angular.bootstrap(document, ['app']);
      }
    );
  },
  function (a, b, c) {
    console.out('\na:', a, '\nb:', b, '\nc:', c);
  }
);

```

I am at my wits end. Please help me figure out how to get the tests from the `client/src` folder 
to compile in memory and execute against the pre-compiled code in `_build/js`.

**Comment by guybedford** [comment]
I'm not personally familiar with Karma-SystemJS, perhaps post this issue there?

Karma always uses the `/base/` folder in the URL, so you may need to change the baseURL to `/base/` and then have the other paths change accordingly though. Check that the URLs exist if you navigate to them in the browser - a 404 should be pretty clear in the console.

Note also that `/base/client/src/app/modules/home/greeting/GreetingController.spec` is an illegal module name in SystemJS - module names shouldn't start with `/`, they should always be relative to the baseURL. Not sure where that is being loaded from though.

As a side note - I would advise for later on to compile using the `modules: 'instantiate'` option in Traceur. This is a native module format for ES6 that will ensure exact compatibility, which is a better target than AMD.

The testing workflows are very much left to be handled by third-party projects. See how the support is there. If you're still banging your head against it my apologies - it can always be worth using another solution that has better community support then in the mean time. I will aim to reach out wider and support these areas over time, but for now am very much focusing on the core project.

**Comment by douglasduteil** [comment]
Hi @guybedford 
Is there a way to mock imports in SystemJS ?
Can we "deregister" or remap at the execution moment a file path to another file ?

**Comment by guybedford** [comment]
@douglasduteil to mock an import you can use map config, but then you'd need a new loader via `System.clone()` each test. It is also possible to use the `delete`, `get` and `set` methods of the registry to swap out modules. You do need to know the exact name of the module through `System.normalize('name')` here though. See which approach works best for you.

**Comment by douglasduteil** [comment]
Alright thanks @guybedford

**Comment by guybedford** [comment]
@kburson did you manage to make progress here?

**Comment by rolaveric** [comment]
We've moved the thread over to karma-systemjs so you can close this issue off.
https://github.com/rolaveric/karma-systemjs/issues/7
https://github.com/rolaveric/karma-systemjs/issues/9

**Comment by kburson** [comment]
I will try the 'instantiate' format. Thanks, I did not know which format was best out of { amd, register, commons, instantiate }, so I chose amd. Systemjs works beautifully to host my app, loading my modules as needed.  

I love not having to list all the dependencies in specific order in my index.html, just the root module and let systemjs walk the dependency graph, it is beautiful.  My only problem was getting karma to work with precompiled files while systemjs would load compiled files from a different location, but still allow me to keep my import statements normalized to short relative paths.

Yes, rolaveric is helping me with his plugin. I have great hope to get this all working the way I envision it.

On that note I would love to have a discussion with people about project layout, specifically for an angular project using es6 module loader (systemjs) in both a loose-leaf (for Dev) and bundled format (for prod, bundled by systemjs-builder).  Where do I take such a discussion?

**Comment by guybedford** [comment]
@kburson in terms of the workflow discussions - there are a number of angular starters available - there is a small list at https://github.com/systemjs/systemjs/wiki/Community-Projects although I know there are more than are listed there too. Perhaps reach out to some people there or start a discussion on the group or Gitter room.

**Comment by guybedford** [comment]
Closing for now, I realise there is a gap between what is offered here and the full support needed. Perhaps posting in the Google Group or Gitter chat room may work better. If you have any suggestions for how we can make this better please do post back here.
