### ISSUE TITLE
Unable to use babel-runtime out-of-the-box

### ISSUE THREAD

**Issue by cmaher** [systemjs/systemjs#374]
When using the Babel option 'runtime', Babel loads helper functions as separate files instead of inlining them in every file. This option can be enabled with:

```js
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  }
```

This configuration causes babel to load helper functions from files that look like:
```js
// babe-runtime/helpers/create-class.js
exports["default"] = (function () {
  return function () {
    // ...
  };
})();

exports.__esModule = true;
```

When this file is loaded, it's interpreted as the object
```js
var _createClass = { 
  default: function () { /* the create-class function */ }, 
  __esModule: true}`
}
```
But babel calls it as a method: `_createClass(/*...*/)`, which fails, because _createClass is an object, and not a function.

I'm working around this with the following configuration:
```js
var systemInstantiate = System.instantiate;
System.instantiate = function (load) {
  if (~load.name.indexOf('babel-runtime')) {
    load.source = load.source + '\n;module.exports = module.exports["default"];';
  }
  return systemInstantiate.call(this, load);
};
```
using System.instantiate instead of a plugin, since I can't change Babel's loading of `babel-runtime` (side note: path-based plugins rather than just extension-based plugins would be awesome).

 I'm not sure if this is a problem with System.js or Babel, but I can imagine other people running into this problem since `babel-runtime` really helps shrink the code size.

This issue seems very similar to #304, but I don't think it's an exact duplicate (in fact, changing the helper code to use `export default` fixes the problem as well).  A possible workaround is to do something similar to https://github.com/systemjs/systemjs/blob/master/lib/extension-core.js#L11, but using '__esModule' instead of '__useDefault', but this might be considered (1) breaking and (2) undesirable.

If you think this is actually an issue with babel, I'll take it there.

**Comment by guybedford** [comment]
Thanks for the detailed info. This might be a Babel issue actually - if the helper is meant to be interpreted as a single export style module, then it shouldn't have the `__esModule` flag set.

**Comment by guybedford** [comment]
@cmaher I just checked the output and Babel is definitely accessing the default property of the helpers in the latest version. It may be worth checking your version of the helpers is matching the version of Babel doing the transpiling.

**Comment by cmaher** [comment]
Yep. I've been using the latest babel (4.7.12) and the latest System (or at least the latest one included in jspm). I thought that I was using the wrong version too (especially in relation to the issue you opened: https://github.com/babel/babel/issues/774). It seems that, for instance, babel-runtime/regenerato/runtime.js are properly referencing `default`, but the individual helper functions do not behave correctly when loaded individually.

I'll open this issue against Babel. thanks for your help.

**Comment by cmaher** [comment]
And @sebmck thinks this is a System.js issue since the default is being loaded.  Posted a sample project for getting to the bottom of this: https://github.com/cmaher/systemjs-babel-runtime

**Comment by cmaher** [comment]
So I'm now convinced that jspm is downloading incompatible versions of SystemJS and Babel. Sorry for the run-around (again).
