### ISSUE TITLE
Support System.delete for register pipeline

### ISSUE THREAD

**Issue by jbe456** [systemjs/systemjs#375]
In `System`, there is already a `moduleRecords` variable which is accessible through :
```
System._loader.moduleRecords
``` 

But in `extension-register.js`, you use a custom local `moduleRecords` variable:
```
  // module binding records
  var moduleRecords = {};
  function getOrCreateModuleRecord(name) {
    return moduleRecords[name] || (moduleRecords[name] = {
      name: name,
      dependencies: [],
      exports: {}, // start from an empty module and extend
      importers: []
    })
  }
```

Versus you should do the same as in `es6-module-loader`:
```
  // custom module records for binding graph
  // store linking module records in a separate table
  function getOrCreateModuleRecord(name, loader) {
    var moduleRecords = loader.moduleRecords;
    return moduleRecords[name] || (moduleRecords[name] = {
      name: name,
      dependencies: [],
      module: new Module(), // start from an empty module and extend
      importers: []
    });
  }
```

Otherwise it breaks the `delete` for example:
```
// 26.3.3.3
    'delete': function(name) {
      var loader = this._loader;
      delete loader.importPromises[name];
      delete loader.moduleRecords[name];
      return loader.modules[name] ? delete loader.modules[name] : false;
    }
```

**Comment by guybedford** [comment]
@jbe456 the reason for this is that when modules are compiled into System.register, they are no longer ES6, but need to behave the same way as ES6 modules when loaded along with other formats. The way this is replicated is by creating a linking pipeline in the register extension which is identical to the linking pipeline in the module loader itself. It's a subtlety of the implementation!

**Comment by jbe456** [comment]
Ok. I tried to replace your internal structure by the one from the main loader and did not observe any issue. Where should I observe issues in this case?

According to your last comment then, shouldn't you extend the delete method to delete also the module from your internal structure ?

Anyway my issue is slightly different. I am manipulating the loader `moduleRecords` to implement a rollback method on `System` (in order to undo all modifications since a point of time, for test purpose: ie unload all loaded module during a unit test) but it doesn't work because of this hidden structure I can't access. What would you suggest?

**Comment by guybedford** [comment]
If delete is not deleting then yes that is a bug. We should allow the internal registry to be refreshed when a module has been deleted. Can you share a specific example here of what isn't working?

An alternative in tests is to use `System.clone` to create multiple loaders so you don't need to clear the registry.

**Comment by guybedford** [comment]
@jbe456 this may well be a bug, do let me know if you're still having issues with it.

**Comment by timbur** [comment]
I probably should have commented here instead of ModuleLoader/es6-module-loader#203.  Does the `delete` method reload all affected `importers`?  Or is there some other way that SystemJS ensures  references to the deleted module are removed/updated?  I'm not seeing any logic in the source that resembles this functionality, but I could be overlooking something.

**Comment by guybedford** [comment]
This should work now in the latest release.
