### ISSUE TITLE
Error while testing with Karma

### ISSUE THREAD

**Issue by VictorQueiroz** [systemjs/systemjs#376]
I really need Karma and all those plugins to test using es6 module loader and systemjs? I'm getting this error on: https://github.com/VictorQueiroz/angular-boilerplate-es6
```
INFO [launcher]: Trying to start Chrome again (1/2).
INFO [Chrome 41.0.2272 (Linux)]: Connected on socket lQWDVBn0TM8inmr_Rzvo with id 77222430
Chrome 41.0.2272 (Linux) ERROR
  TypeError: Illegal module name "/base/app/scripts/app_test"
  Hint: Is the working directory different when you run karma?
  You may need to change the baseURL of your SystemJS config inside your karma config.
  It's currently checking "/base/scripts"
  Note: "/base/" is where karma serves files from.
```

Can someone help me? I really don't know what to do. And if someone can show me a better workaround for Karma, will be helpful too. Anyway, thank you. Waiting for an answer!

**Comment by kburson** [comment]
Take a look at the issues in karma-systemjs, I have been dealing with much the same thing. Rolaveric, the author, has been discussing various strategies with me.

https://github.com/rolaveric/karma-systemjs

**Comment by guybedford** [comment]
Karma support is not provided in this repo unfortunately. Perhaps ask on the Group or gitter room if you need further help.
