### ISSUE TITLE
Possible race condition in register extension

### ISSUE THREAD

**Issue by matthewp** [systemjs/systemjs#377]
Hey @guybedford, I'm seeing a problem where buildGroups is being called on an entry before `normalizedDeps` has been set.  It happens when the entry is part of a bundle, haven't seen it happen otherwise, if that helps clue you in.  I'll keep digging, thought I'd create the issue in case you knew of a scenario where this could happen.

**Comment by matthewp** [comment]
The problem seems to be that a parent is executed before a child module is instantiated, still digging.

**Comment by guybedford** [comment]
Closing for now, but let me know if you manage to track this down.
