### ISSUE TITLE
Issues using alongside curl (AMD loader)

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#378]
We are trying to port part of our application to use the jspm/SystemJS ecosystem.

``` html
<head>
    <script src="/jspm_packages/system.js"></script>
    <script src="/config.js"></script>
    <script>
        System.import('app')
            .catch(function (error) {
                setTimeout(function () {
                    console.error(error);
                });
            });
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/curl/0.7.3/curl-for-jQuery/curl.js"></script>
</head>
<body></body>
```

This fails with:

```
TypeError: Error loading "app" at http://0.0.0.0:8080/app.js
Include Traceur or Babel for module syntax support.
Include Traceur or Babel for module syntax support.
```

Removing curl fixes the error, but of course we want curl on the page to load our non-ported AMD app. I played around a bit and discovered I could get it work by forcing Babel to load synchronously after SystemJS:

``` html
<head>
    <script src="/jspm_packages/system.js"></script>
    <script src="/jspm_packages/babel.js"></script>
    <script src="/config.js"></script>
    <script>
        System.import('app')
            .catch(function (error) {
                setTimeout(function () {
                    console.error(error);
                });
            });
    </script>
    <script>
        window.define2 = window.define;
    </script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/curl/0.7.3/curl-for-jQuery/curl.js"></script>
    <script>
        window.define === window.define2;
        // => false
    </script>
</head>
<body></body>
```

This suggests the problem arises because of a conflict with Babel/SystemJS and curl both trying to define and use `window.define`. If curl overrides `window.define`, it could cause problems for SystemJS—and vice versa. Do you have any ideas how we can proceed?

/cc @sndrs @rich-nguyen @theefer

**Comment by MajorBreakfast** [comment]
An idea: You could try to load curl as a module in the global format.

**Comment by guybedford** [comment]
Curl setting `window.define` shouldn't affect SystemJS module loading. But it does affect the loading of Traceur and Babel as they are then being triggered into AMD mode through curl.

Loading the transpiler like you are doing early sounds like the sensible fix here, and I don't think you'll get more problems than that. You shouldn't need to get and set `window.define` at all though if Babel is already loaded.

**Comment by guybedford** [comment]
Let me know if the above method works ok for you. Happy to discuss further if the explanation isn't clear.

**Comment by OliverJAsh** [comment]
Thanks, that works!
