### ISSUE TITLE
Multiple Imports withing the same import()

### ISSUE THREAD

**Issue by AlessandroEmm** [systemjs/systemjs#38]
Hey Guy

Just started to give JSPM a try. :-)

Is it possible to import multiple libraries at the same time sort of like

jspm.import(['this', 'andthis', 'andthis'] function(th, tha, tha2) { 
  // work it
  } )

I'd like to use it this way then pass them to the Polymer constructor so the libraries can be used in the ShadowDOM scope.

Thanks again
Alessandro

**Comment by robdodson** [comment]
@guybedford is this still supported? I was looking to do the same thing this weekend but wasn't sure how to make the jspm object available on my page

**Comment by MajorBreakfast** [comment]
I use this in my app:
``` JavaScript
Promise.all([
    System.import('command-worker/RequestResponseHandler'),
    System.import(commandsModuleName)
  ])
  .then(function(modules) { ... })
```

**Comment by robdodson** [comment]
@MajorBreakfast yeah I wrote something similar, was just curious if there some way to not have to do all the boilerplate myself. I think (but I may be mistaken) that System usually wants there to just be 1 call to import (like for a main.js file) and so maybe this is outside normal usage. @guybedford is that accurate?

**Comment by guybedford** [comment]
@robdodson I don't know of any plans for an array require, but it could be worth bringing up as a spec issue. I do like the perspective of having a single entry point though, as you then need all dynamic calls to be full modules themselves, which works well with bundling. We will have `<script type="module">` to make the inline case easier anyway in future.

**Comment by robdodson** [comment]
@guybedford yeah I'm specifically looking at it from the case of Web Components where it's harder to have one entry point if you're using HTML Imports. I'm not a fan of the current approach in https://github.com/ModuleLoader/es6-module-loader/issues/95 with htmlimport-esmodule, I'd love to just System.import whatever I need in my script tags vs having to include an HTML Import and then an import statement which references the url for the import. That approach just feels cumbersome to me.

**Comment by guybedford** [comment]
@robdodson Erik's proposal is out of date, I've updated https://github.com/ModuleLoader/es6-module-loader/issues/95 to reflect the latest information. It's worth thinking in terms of module tags first, then working backwards to System.import.

**Comment by chrismbeckett** [comment]
+1 @guybedford @robdodson Array support for System.import would be convenient when combining SystemJS and Web Components.

**Comment by bennyn** [comment]
I tried to use it this way:

```javascript
System.import(['dexie', 'proteus'])
.then(function(dexie, proteus) {
  console.log('dexie', dexie);
  console.log('proteus', proteus);
});
```

But all I'm getting is:

> system.src.js:1226 Uncaught (in promise) TypeError: e.match is not a function(…)
