### ISSUE TITLE
Loading multiple resources

### ISSUE THREAD

**Issue by brettz9** [systemjs/systemjs#383]
Hi,

I'd like to avoid the need for:

```js
Promise.all(['module1', 'module2'].map(function (url) { 
    return System['import'](url);
)).then(function (modules) {
    var m1 = modules[0];
    var m2 = modules[1];

});
```

...with something like this:

```js
System.loadAll(['module1', 'module2']).done(function (m1, m2) {

});
```

...or at least like this:

```js
System.loadAll(['module1', 'module2']).then(function (modules) {
    var m1 = modules[0];
    var m2 = modules[1];

});
```

In proposing to WhatWG to just allow this pattern, I was told to start a library for it and see if it becomes popular.

Would you suggest I simply make a light wrapper for your library and distribute it with your library as a dependency, or do you see a place for it in your library itself? I'm not interested in a whole other library like RequireJS, just adding this light layer...

**Comment by guybedford** [comment]
You could write this as an extension:

```javascript
function loadAll(loader) {
  loader._extensions = loader._extensions || [];
  loader._extensions.push(loadAll);
  loader.loadAll = ...;
}
loadAll(System);
```

Then that can be concatenated with SystemJS or added as a separate <script> tag as a custom extension.

**Comment by MajorBreakfast** [comment]
@brettz9 You should call it "importAll(...)".

**Comment by guybedford** [comment]
Careful this doesn't get confused with https://github.com/whatwg/loader/issues/36#issuecomment-79407109.

**Comment by brettz9** [comment]
Thanks, Guy. Will report back if and when I get to making the extension.

**Comment by krnlde** [comment]
Unfortunately there is a limitation in the `Promise.resolve()` [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.resolve) which only allows to pass one parameter.
But as quoted [here](http://stackoverflow.com/a/31525452/622041) you could append your own spread wrapper to the `.then()` method or simply use es6 destructuring.

**Comment by dashng** [comment]
Hard week for me. I am find a way to compress all js amd files together when deliver. 
Is there any solution for system js like requirejs r.js to compress all files together.
