### ISSUE TITLE
Remote resource imports

### ISSUE THREAD

**Issue by brettz9** [systemjs/systemjs#384]
I presume the spec allows for remote resource imports? (e.g., `System.import('http://example.com')`)

Can support for this be added? And if so, would CORS be required, or could things work as with script tag insertion?

**Comment by circlingthesun** [comment]
I've just created a plugin that lets you load external resources via script tags. https://github.com/circlingthesun/systemjs-script-plugin

**Comment by brettz9** [comment]
Great to see the plugin and know it can be done, thanks. As far as the spec allowing for this, I've asked at whatwg/loader#43

**Comment by guybedford** [comment]
Remote resource imports will be supported in the next version of SystemJS.

**Comment by amio** [comment]
What about Node.js? I got the error message: "Only file URLs of the form / allowed running in Node."

**Comment by guybedford** [comment]
@amio that will come in 1.0 I expect.

**Comment by amio** [comment]
@guybedford Thanks

Is there a roadmap or schedule for 1.0 release?
