### ISSUE TITLE
Keep original source code in dev tools resource panel after transformation

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#385]
I made a simple jsx plugin using Babel.  (Serious kudos to everyone who made this so incredibly easy!)

`jsx.js`:
```js
'use strict';

var babel = require('babel');

exports.translate = function (load) {
    var output = babel.transform(load.source, {sourceMap: true});
    load.source = output.code;
    load.metadata.sourceMap = output.map;
};
```

I'm creating a dev tools extension for Chrome (and hopefully eventually Firefox) which hot reloads modules upon updates from within the inspector's native code editor.  The code shown in the source panel is the transformed code, but it needs to show the original ES6 + JSX code.

What's the best way to approach fixing this?

**Comment by guybedford** [comment]
The source maps are a little annoying in that we get original sources with line-by-line debugging but only for the original name within sources panel (`file.js`), not the one that comes up in the console (ending in `file.js!eval`).

Let me know if that makes some sense? Are you seeing both versions?

**Comment by timbur** [comment]
I'm only seeing `file.js` in my sources panel and its code is transformed.

I'm looking at `lib/polyfill-wrapper-end.js` and `lib/extension-register.js`.  Your comment helped point me in the right direction.  `//# sourceURL` plus `//# sourceMappingURL` is pretty neat.  I've managed to show both the original source and the transformed source, although the structure isn't how I would like.

This is what I have currently, and it results in essentially `file.js` and `file.js!source` (backwards from your `file.js!eval`.)  

`jsx.js`:
```js
'use strict';

var babel = require('babel');

exports.translate = function (load) {

    var split = load.address.split('/');
    var filename = split.pop();
    var options = {};
    var output;

    options.filename = filename;
    options.sourceMap = 'both';
    options.sourceFileName = filename+'!source';

    output = babel.transform(load.source, options);
    load.source = output.code;

};
```

Ideally I want something which would put all of the transformed (evaluated) code into its own `eval` subdirectory and leave the original source filename intact (without `!source.js`), but it doesn't look to me like the loader is currently designed to allow changes to `load.address`.  It would be preferable to modify or specify the sourceURL address from within the `jsx.js` plugin.

**Comment by timbur** [comment]
I figured out that relative URLs can be used for the `sourceFileName`, so since I was unable to set the `sourceURL` for the output from within the plugin (without digging too deep into the SystemJS source), I did the following:

1. Added an extra route to the server to allow `components/eval/*.jsx` to act as an alias for `components/*.jsx`.
2. For `System.config`, I added `"components/*.jsx"  : "components/eval/*.jsx"`.
3. Updated `jsx.js` to use a relative URL to place the sourceFileName up one directory:
```js
'use strict';

var babel = require('babel');

exports.translate = function (load) {

    var split = load.address.split('/');
    var filename = split.pop();
    var options = {};
    var output;

    options.filename = filename;
    options.sourceMap = 'inline';
    if (split[split.length - 1] === 'eval') {
        options.sourceFileName = '../'+filename;
    } else {
        options.sourceFileName = filename+'!source';
    }

    output = babel.transform(load.source, options);
    load.source = output.code;

};
```

So now the dev tools sources panel looks exactly like I wanted:
![sources-panel](https://cloud.githubusercontent.com/assets/7020411/6936989/f0715014-d825-11e4-8595-da715b9ed493.png)

**Comment by guybedford** [comment]
Nice. The sourceURL should have just been `load.address.substr('file:'.length)` though? 

It's an annoying solution needing a server path. This naming issue with source maps affects us all the way down in the module loader as well - needing to add these special `!eval` indicators. I wish someone could tell me there was a way to do this stuff properly.

If you're able to generalize it, it would be great if you can share your plugin as well.

**Comment by timbur** [comment]
Where is `file:` coming from?  Either we're thinking about two different things or I'm completely overlooking something.  I'll explain how I reached my conclusion.

Suppose we're importing some ES6+JSX module:
`import ExampleApp from 'components/ExampleApp.jsx!jsx';`

In the `jsx.js` plugin (as seen in my previous comment) which transforms the source of imported JSX files using Babel, there is of course `load.address` within the `exports.translate` method.  Ideally, within `exports.translate`, I would be able to simply change `load.address` to `http://localhost:8080/components/eval/ExampleApp.jsx` so that it uses this as the `//# sourceURL` of the transformed code, but that doesn't work because `__eval` in `polyfill-wrapper-end.js` uses an old reference to `load.address`.  A solution here might be to pass the `load` object to `__eval` instead of `source`, `address`, and `sourceMap`, but I was afraid to take a stab at this myself, so I came up with the workaround.

Beyond that, we specify `options.filename` (e.g., `ExampleApp.jsx`) and `options.sourceFileName` (e.g., `../ExampleApp.jsx`) to be passed to `babel.transform`.  In the dev tools sources panel, the original ES6+JSX source is eventually represented via `options.sourceFileName`.  And since I couldn't change `load.address` to be represented as `http://localhost:8080/components/eval/ExampleApp.jsx`, I had to make it the actual address.  So to make the original ES6+JSX source show up in the dev tools sources panel as its real URL of `http://localhost:8080/components/ExampleApp.jsx`, `options.sourceFileName` is `../ExampleApp.jsx` to move it up one directory (above the `eval` directory).  This keeps all of the transformed files out of sight within the `eval` directory, since when we're editing modules from within the sources panel, we only care about the ES6+JSX code.

I am planning on releasing all of this as part of an ES6+JSX development toolkit, but I'm not sure how much sense it would make to share a generalized version of this by itself since it currently depends on that extra bit of routing on the server.  It would make a lot more sense if we were able to change the `sourceURL` via `load.address` from within plugins, and in which case would only take 30 seconds to put together a generalized version.

**Comment by guybedford** [comment]
@timbur we could certainly look at changing the `load.address` value of the plugin to be `http://localhost:8080/components/eval/ExampleApp.jsx!`, which would then become the evaluated sourceURL. Would that help here? It's a very small change to make in SystemJS, I can do it in 10 mins.

**Comment by timbur** [comment]
That would be fantastic.  It'd eliminate the need for this extra server route workaround.

**Comment by guybedford** [comment]
Sure I've created this at https://github.com/systemjs/systemjs/pull/389. Perhaps try that out and let me know if it works ok for you?
