### ISSUE TITLE
System.define not using appropriate plugins?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#386]
Does `System.define('components/SomeComponent.jsx!', source)` not work similarly to `System.import`?  It doesn't seem to be applying the jsx transformations.  Do I need to specify some option(s) to make this work?

**Comment by timbur** [comment]
I couldn't find any documentation on what exactly is expected to be passed into the `options` argument for `System.define`, so I took a guess and it seems to work.

In my case, I'm redefining the module for a bit of hot reloading, so first I set `System.trace = true` and upon checking `System.loads`, it turns out I needed to set the module path to `components/SomeComponent.jsx!jsx` instead of just `components/SomeComponent.jsx!`, which I'll probably do everywhere from now on for clarity.  Then all I had to do was copy a couple of key options from the old module to be passed to the `options` argument of `System.define`.

The result ended up being along these lines:
```js
var dir = 'components';
var name = 'SomeComponent';
var extension = 'jsx';
var path = dir+'/'+name+'.'+extension+'!'+extension;
var oldOptions = System.loads[path];
var options = {};

if (oldOptions) {
    options.address = oldOptions.address;
    options.metadata = {};
    options.metadata.plugin = oldOptions.metadata.plugin;
}

System.delete(path);
System.define(path, code, options).then(function () {
   // successfully reloaded module
   // save changes, etc.
});
```

**Comment by guybedford** [comment]
Nice, a hot-reloading tool for SystemJS is something very much needed. Could you not just `delete` and then `import` again for hot reloading?

**Comment by timbur** [comment]
I tried to `delete` and `import` but for some reason `import` never executed the new code.  Plus, `define` is more ideal anyway since we already have the updated source from the dev tools sources panel.  It doesn't make sense to request the updated source from the server.

And to take it a step further, regarding some other plans, I want developers to be able to work on apps together in real-time.  Suppose a developer makes a change, we'd use diff-match-patch to replicate the change as a patch to the other developers, and it would be applied using `delete` and `define`, which of course would be much more efficient than each developer redownloading the entire module each time.

**Comment by timbur** [comment]
Also, I'll see about putting together a standalone hot loader for SystemJS when I get a chance.  But if someone else wants to give it a shot based on what I've outlined in this thread, it should be relatively straightforward.  :)

**Comment by guybedford** [comment]
The delete issue is probably due to https://github.com/systemjs/systemjs/issues/375 here. I can prioritise the fix if it would help, although it's fine this way too.
