### ISSUE TITLE
I cannot use an inline script as a module.

### ISSUE THREAD

**Issue by kapitancho** [systemjs/systemjs#387]
Hello,
I have a working jspm+systemjs+es6 loader+babel environment which works fine - I am able to load import and execute ES6 scripts without any problem. 
Unfortunately - I am not able to perform a very simple task - register an inline script as a module.
Since there is no function documentation available I had to inspect and play with the core code but after 4 hours of debugging I could say that I am stuck. Based on some code fragments copy/paste I was able to "almost load" a module but that is not a solution.

Is there a way to do this?
It is as simple as this:
var es6module = 'some nice es6 code';
System.????transpileAndUseTheCodeAsModule (es6module);

If you need any additional information I could provide it.

Thank you in advance!

**Comment by guybedford** [comment]
`System.module` can be used here. See https://github.com/ModuleLoader/es6-module-loader/blob/master/src/system.js#L300 which is the code for the module tag.

**Comment by guybedford** [comment]
Note the above will execute the module anonymously. If you want to create a named module you have to use System.define. See https://github.com/systemjs/systemjs/issues/386.

**Comment by kapitancho** [comment]
Thank you :)
A combination of System.define + System.import did the trick since I wanted to get this module auto-executed.
Thank you for the quick reaction!

**Comment by lastmjs** [comment]
@kapitancho How did you do it? I'm having trouble defining and using a module inline.

**Comment by lastmjs** [comment]
@guybedford Is System.module in use anymore? Where can I find documentation on it?

**Comment by lastmjs** [comment]
It looks like System.define and System.module require the source code to be passed in as a string...it would be nice to define the module with JavaScript code (not a string). I think System.register will allow me to define a module in code, correct?

**Comment by lastmjs** [comment]
System.define allows you to pass in a string as the second argument.
