### ISSUE TITLE
Loading JSON implicitly (without .json extension)

### ISSUE THREAD

**Issue by geelen** [systemjs/systemjs#388]
I'm trying to write an autoprefixer loader, just sort of getting the hang of it, and I've come across a behaviour I vaguely knew about node that I'd never really made use of - requiring JSON files without an extension:

```js
var data = require('./data')
# Looks first for ./data.js, then ./data.json
```

To me, this is dumb, but autoprefixer depends on caniuse-db which uses it in a bunch of places. But googling around, I couldn't figure out if this problem had been hit on SystemJS before. I did come across this in Browserify's readme:

> opts.extensions is an array of optional extra extensions for the module lookup machinery to use when the extension has not been specified. By default browserify considers only .js and .json files in such cases.

Theoretically, a 404 on `data.js` could trigger a retry against `data.json` using the JSON plugin but it feels... not great. Anyway, wanted to discuss :)

**Comment by guybedford** [comment]
SystemJS doesn't support loading JSON, but when installing npm packages in jspm, it will automatically detect JSON requires and rewrite them to use the JSON plugin.

If the jspm npm install isn't working for this case though, then that could be a bug in jspm-npm.

**Comment by geelen** [comment]
Right, ok cool. I'm running against JSPM 0.15.1, and this was one of the lines causing an error: https://github.com/postcss/autoprefixer-core/blob/master/data/prefixes.coffee#L42

Changing that to `caniuse-db/features-json/border-radius.json` didn't help, it was still looking for `border-radius.json.js`. I had to use `caniuse-db/features-json/border-radius.json!json` and `jspm install json` for this to work.

**Comment by guybedford** [comment]
How did you install postcss?

**Comment by geelen** [comment]
Actually just using autoprefixer for the moment, but:

`jspm install npm:autoprefixer-core`

This is my plugin at the moment:

```js
import insertCss from 'insert-css'
import Autoprefixer from 'autoprefixer-core'
let autoprefixer = Autoprefixer('last 2 versions')

export var translate = (load) => {
  insertCss(autoprefixer.process(load.source).css)
  load.source = ''
}
```

**Comment by guybedford** [comment]
Ok, yes that is a limitation in jspm-npm currently. I've proposed a fix for this at https://github.com/jspm/npm/issues/52.

In the next config update for jspm this will be possible to fix with an override as well.

**Comment by guybedford** [comment]
Closing as we're tracking on the npm project. Sorry for the delay on this, it's a tricky one.
