### ISSUE TITLE
Associate plugin with file extension without "!"?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#391]
For example, it would be nice to automatically use the `jsx` plugin for `.jsx` imports without having to explicitly append `!` or `!jsx` to the  path when importing.  I would assume this is easily doable but I couldn't find it anywhere upon skimming through everything.

**Comment by matthewp** [comment]
There's a proposal for that here: https://github.com/systemjs/systemjs/issues/287

**Comment by timbur** [comment]
Thanks!  I'm guessing this functionality does not yet exist?  Would I be wasting my time if I implemented it?

Side note:  This is of course just like, my opinion, man, but automatically appending `.js` to paths seems like a poor design decision, making things more confusing and troublesome than should ever be necessary.  I "fixed" this (made it more sensible) for my own projects via `System.config`'s `paths`, which is easy enough so I guess it's not a big deal.

**Comment by matthewp** [comment]
Not sure, SystemJS is currently based on the slightly older spec which specified adding `.js`, the new spec does not. So whenever the new spec is implemented.

**Comment by guybedford** [comment]
The new release with this functionality should be coming very soon. The branch is mostly complete, just doing final testing.
