### ISSUE TITLE
newModule Enumerability

### ISSUE THREAD

**Issue by u9520107** [systemjs/systemjs#393]
ok.. got a weird error that's breaking my setup down completely.
For convenience I transpile all my tools into commonjs modules using babel@4.7.16.
Then on the browser, I use System.import to load these modules to run in the client.
I have a module named store-base, which is used quite often. I noticed that during most requires, the loader logic runs through getModule function, and would get something in via system.src.js:624
```
var entry = loader.defined[name]; //name is 'dist/store-base'
```
But at some point, this line would return nothing. Tracing the code in chrome reveals that loader.defined is still an mapping with all the modules names intact, but all the properties became undefined.
At this point, systemjs loader seems to attempt to load the module differently, giving back an object y, with the desired module as y.default. However, it strips the __esModule property, which causes babel's interopRequire unable to return the default. Then the script crashes.

Any insights?

**Comment by u9520107** [comment]
more details..
So on the browser I import a module called the client-app-driver via System.import, then in the client-app-driver it would call System.import again to load applications.
```
System.import('dist/client-app-driver').then(function (m) {
    new m('server/app');
});
```
Somewhere in client-app-driver
```
   var app = System.import(src);
```
At this point, loader.defined seems to have lost its information.

**Comment by guybedford** [comment]
@u9520107 `System.defined` is just the bundle registry, which is cleared as soon as bundles are defined into the loader registry.

Try changing line https://github.com/systemjs/systemjs/blob/master/lib/extension-register.js#L347 from:

```javascript
    if ((!entry || entry.declarative) && exports && exports.__useDefault)
      return exports['default'];
```

to:

```javascript
    if ((!entry || entry.declarative) && exports && !exports.__esModule && exports.__useDefault)
      return exports['default'];
```

**Comment by guybedford** [comment]
I'm really struggling to understand exactly how the stripping of the `__esModule` could be happening. If there is any way you can post a test case that would be really great to see.

**Comment by u9520107** [comment]
I'd love to help. But I am racing a project deadline. So it might take some time to test again. I found that reverting back to jspm 0.14.0 fixes the issue. Not exactly sure why. Perhaps I can find some time during this weekend to investigate further.





        Jack Tzu-Chieh Huang
Web Developer @ Meepshop




On Wed, Apr 8, 2015 at 4:44 AM -0700, "Guy Bedford" <notifications@github.com> wrote:












I'm really struggling to understand exactly how the stripping of the __esModule could be happening. If there is any way you can post a test case that would be really great to see.

**Comment by guybedford** [comment]
@u9520107 I can pretty much guarantee that the change that caused this is https://github.com/systemjs/systemjs/commit/04383f5e4c044f7e2d67c46aed5c1c5560235733, but that is a very important feature which should be backwards-compatible.

If you can track this down, or offer any sharable case at all, that would be a really great help here.

**Comment by u9520107** [comment]
@guybedford yes.. i'd want to help. Turns out 0.14.0 somehow dies on firefox.. so I have to bump versions sooner or later. I need to run some design demo on Monday Taipei time, so I probably won't have time to look into this before then...

https://github.com/meepshop/meepworks
this is the core library we're trying to work things out. Just run 'npm install' and then 'gulp watch' to start the server off. Preferably on iojs >=1.3.0 or node >= 0.12.0.
As long as I upgrade jspm to 0.15.xx it breaks down. While on 0.14.xx would work for webkit and ie>=9.
But the last time I checked on jspm 0.15.3, the error message wasn't the same. Feel free to check it out before I can investigate further.

**Comment by guybedford** [comment]
@u9520107 you seem to have a lot of unnecessary dependencies in your install. For example SystemJS builder isn't intended to be installed with jspm itself. Are you sure all these dependencies are supposed to be there?

**Comment by u9520107** [comment]
@guybedford Dunno. For building isomorphic apps, if you load css via js, the server rendered html will not have proper styling before js files are loaded. Tracing the source code and served those css files via html head seems to be the right way to avoid this issue. Are there any other way to trace the source codes for css imports?

**Comment by u9520107** [comment]
@guybedford Cool, it seems I really don't need systemjs-builder as jspm dependency, and only install it for server-side.

**Comment by guybedford** [comment]
@u9520107 did you have further progress here? Closing for now, but happy to discuss further.

**Comment by u9520107** [comment]
@guybedford sorry, was away from my post for quite a while.
I realized that jspm is now at 0.15.4, and is using the latest babel. For that I want to move my projects to use the latest babel as well. But I am bumping into some bugs, presumably with babel. I'll probably have to deal with that first before I can jump back into this issue.

**Comment by u9520107** [comment]
@guybedford ok.. I made some modifications to use the latest babel.js. However, I can still see some modules being loaded wrong. I've pushed the current changes to my repo on branch "babel5". Currently tested with latest iojs and jspm 0.15.4.
I'll trace the commit you mentioned and see what I can find.

**Comment by u9520107** [comment]
I check the linkDeclarativeModule function mentioned in the commit, my trace doesn't seem to hit that section of the code at all. 
On the other hand, I tried the change you suggested above to add !exports.esModule to the export check. The error still persists. Using a conditional breakpoint with name.indexOf('store-base') > -1. The first hits have __esModule correctly set to true, and the code runs fine. Util one hit that looks different. The object still put the wanted module at "default", but does not have __useDefault nor __esModule set to true. Hence breaking both jspm and _interopeRequire's ability to return default.

**Comment by u9520107** [comment]
Firefox issue fixed... turns out that i mistakenly used el.innerText instead of el.innerHTML in one of the modules, which isn't supported by firefox. The stacktrace didn't leave the scope of es6-module-loader, so I thought the error was originated there.

**Comment by u9520107** [comment]
@guybedford For the first few imports for StoreBase, loader.defined contains a reference to the module, so the getModule function returns the reference.
When it breaks, loader.defined's reference to  storebase became undefined, getModule calls loader.get(name) to fetch the module from the registery. The get function would find the module in _loader.modules[name], and return _loader.module[name].module. The returned object is an instance of the Module prototype, which contains no flag for __esModule nor __useDefault, hence breaking the detection to use the default property as the module itself. Hence the changes you wanted to make to  https://github.com/systemjs/systemjs/blob/master/lib/extension-register.js#L347  wasn't sufficient to mend the problem.

I am not sure when the module is packages into a Module object, but perhaps it's the packaging that lost the __useDefault flag or the __esModule flag that results in this issue?

**Comment by u9520107** [comment]
@guybedford In es6-module-loader.src.js line 2326, the module loader creates an instance of Module, and copies the keys in the obj to the Module instance, this Module instance is then passed to the getModule function of system.js.
What I realized is that __esModule property is set to be not enumerable. Therefore, the for in loop fails to copy the flag to the Module object... Therefore, __esModule flag is lost during the process, and babel's _interopRequire helper function fails to use the default prop because of that.

**Comment by u9520107** [comment]
@guybedford Things work as intended if I added the following code to line 2339 of es6-module-loader.src.js:
```
      if(obj['__esModule']) {
          m.__esModule = true;
      }
```
Which basically allow Module object to have __esModule flag.
This however, is against the spec you mentioned in https://github.com/ModuleLoader/es6-module-loader/pull/162.
What would the impact to adding __esModule flag into Module object be?

**Comment by guybedford** [comment]
Thanks so so much for digging into this, I never would have seen that!

Basically this is entirely because Babel defines `__esModule` as non-enumerable, and when casting into a Module object we need to still be keeping that property.

I've updated the code in ESML to handle enumerability here - https://github.com/ModuleLoader/es6-module-loader/commit/57675e9a06d48b33cd2f4524fab52924aeff668c.

**Comment by matthewp** [comment]
Crazily I just happened upon this same bug. Glad to see someone fixed it ;)
