### ISSUE TITLE
Transpiler should be optional

### ISSUE THREAD

**Issue by milesj** [systemjs/systemjs#396]
Right now SystemJS requires me to set the transpiler to babel or traceur. This should really be optional, as I'm running into situations where ES6 was already transpiled in the pipeline before it reaches SystemJS.

**Comment by guybedford** [comment]
@milesj the transpiler is optional. If it's being used when it shouldn't that means that sources are being detected as ES6 when they are not. What module format are you transpiling into?

**Comment by milesj** [comment]
There are a few problems I was having, the first being with Karma. Karma has it's own [transpiler layer](https://babeljs.io/docs/using-babel/#karma), which would then by piped to the browser, and in the browser I would use SystemJS to load the transpiled modules to run unit tests. I would set `System.transpiler` to null/empty and it would error out an unknown/invalid module "".

Another instance I tried using the SystemJS builder to bundle files, but the files were already transpiled via Babel as I need to run other transformations on them. Got a similar error above.

I may just be using it incorrectly, as the tools for ES6 are still a bit new.

**Comment by guybedford** [comment]
The main thing to watch out for is that bundle files should look something like:

```javascript
System.register("moduleA", ...);

System.register("moduleB", ...);
```

The names also need to match what is expected in SystemJS, so typically bundles like the above are only supported via SystemJS builder builds.

If building files separately you want to ensure that the bundle files have one System.register each and that there is no name:

moduleA.js
```javascript
System.register([], ...);
```

moduleB.js
```javascript
System.register([], ...);
```

Hope that helps somewhat. 

This post is old now, but may still be useful here - http://guybedford.com/practical-workflows-for-es6-modules.

**Comment by milesj** [comment]
Thanks for this, I'll give it another shot.

**Comment by guybedford** [comment]
Sure, just let me know if you still need any help here.
