### ISSUE TITLE
Loading es6-module-loader with doc.write

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#397]
Is it unpossible to load es6-module-loader as a module? Or by `document.createElement('script');`?

https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L2288-L2290

**Comment by szepeviktor** [comment]
I am coming from curl.js, an AMd resource loader.
Do you suggest to move to System.js?

**Comment by MajorBreakfast** [comment]
@szepeviktor SystemJS is a collection of extensions to the module loader. The module loader cannot load itself. However, the `document.write()` code can certainly be replace with a `document.createElement()` call.

> I am coming from curl.js, an AMD module and resource loader.

I personally enjoy using SystemJS. Guy Bedford is very quick to resolve issues and SystemJS seems to me to be more powerful then many other loaders. However, the downside is that SystemJS is a moving target. It's not stable. Some things might get renamed or replaced by a different approach. Stagnation is the biggest selling point and also the biggest caveat of many other loaders (I've never used curl.js specifically).

**Comment by szepeviktor** [comment]
@MajorBreakfast Thank you for your answer.
Now I do propose to avoid `document.write()`.

**Comment by szepeviktor** [comment]
@MajorBreakfast Maybe loading `es6-module-loader.js` as an AMD module? AMD module loading is available without `es6-module-loader.js`, isn't it.

**Comment by probins** [comment]
@szepeviktor I think you're missing the point. ES6/ES2015 modules are the future. AMD isn't. The loader isn't a module, so why load it as one? It's there to use until the loader object is implemented in browsers. If you want to avoid `document.write`, just load the loader in a script tag before SystemJS.

**Comment by szepeviktor** [comment]
I was taught to avoid `doc.write()` at all costs.
I know AMD is deprecated in favour of ES6 but I am used to AMD loaders.

**Comment by szepeviktor** [comment]
Can I concatenate `es6-module-loader` and System.js?

**Comment by MajorBreakfast** [comment]
@szepeviktor AMD loading is provided by SystemJS's AMD extension + the module loader.

Anyway, the future is bright, because there will come a time when the loader is part of the browser.

The use of a single `document.write()` at startup costs almost nothing. You can run into problems if you're using it constantly, though. What's far more costly is that SystemJS can only trigger the download of the module loader after it was downloaded. But as said you can easily avoid that if you specify two script tags.

**Comment by szepeviktor** [comment]
PageSpees 100 score requires you to avoid external script in the HTML.

**Comment by MajorBreakfast** [comment]
@szepeviktor Take a look at sfx-bundles. It's probably what you want.

**Comment by guybedford** [comment]
If you want to avoid the call to `document.write` then include `es6-module-loader.js` directly with a script tag before SystemJS or concatentate it together before the SystemJS source. That should give the compliance you're looking for.

**Comment by szepeviktor** [comment]
Thank you.
