### ISSUE TITLE
Avoid loading es6-module-loader

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#398]
Is there a way use System.js for only resource and AMD loading?
I would use only global scripts and AMD modules.

**Comment by szepeviktor** [comment]
@guybedford Could please advise.

**Comment by guybedford** [comment]
You're welcome to use SystemJS just for these use cases. The SystemCSP build would be good for this as it is designed to always use script tag injection for these cases.

**Comment by guybedford** [comment]
Just let me know if you have any further questions on this at all.
