### ISSUE TITLE
Possible to import all files with regular expression?

### ISSUE THREAD

**Issue by jonricaurte** [systemjs/systemjs#400]
Right now in my application_test file I have to import all my files in my app with _spec.es6. Is there a way where I can import all files with a certain regular expression?

Thanks.

**Comment by matthewp** [comment]
No, there's not.  SystemJS runs from the browser, it doesn't glob the filesystem.

**Comment by MajorBreakfast** [comment]
However you can write a grunt task that generates application_test.js with all the imports

**Comment by NicholasGW** [comment]
I'm trying to figure out how to do something similar(#402) without bundling to make my app highly pluggable. I managed it with RequireJS so I'm sure it's possible with SystemJS but I can't get it to work just yet...

**Comment by guybedford** [comment]
Yes the best option here is to generate the list of imports and use dynamic import - `Promise.all(importList.map(System.import.bind(System))).then((modules) => {})`
