### ISSUE TITLE
Latest version doesn't work with PhantomJs using Karma

### ISSUE THREAD

**Issue by jonricaurte** [systemjs/systemjs#401]
Saw in the newest one bind was removed, however, my tests keep giving ERROR. When I switch to Chrome, all the tests run. Karma debug level does not really give anything more than that.

**Comment by guybedford** [comment]
I don't think there's anything in this codebase that would cause this - it runs completely in IE8, so I struggle to see how it would fail in PhantomJS.

Can you confirm if this is still happening with the latest patch release?

**Comment by matthewp** [comment]
Phantom < 2 did not (fully) support getter/setters which Traceur produced. That could be the cause.

**Comment by guybedford** [comment]
There's definitely nothing in SystemJS itself that isn't supporting the environment. As @matthewp says note that ES6 compilation outputs may use unsupported syntax.
