### ISSUE TITLE
Use a plugin to make loading of runtime determined React components?

### ISSUE THREAD

**Issue by NicholasGW** [systemjs/systemjs#402]
Hoping for some comments/ideas about how best to do this with SystemJS. Recently, I was tasked with making a highly pluggable UI, and was able to do something like this with RequireJS:

ComponentA has children of a certain type which are pluggable, meaning there can be any number, we don't know until runtime (bundling is impossible due to the server nature).

ComponentA would use a RequireJS plugin to load all existing components.

The plugin would query an endpoint, get the names of all the component files, load them into an object keyed by name (the components have methods to expose their own name) and then it would finally "return" and let ComponentA know the dependencies had been loaded via the onload() function.

ComponentA could then render any of the children components by name. like so:

    var Children = require("bundleLoader!children");
    
    ...
     
    React.render(Children["child1"], myDiv);

It seems this should even easier with SystemJS + ES6, perhaps by making a plugin and overriding some of the ES6 Module Loader hooks, but I thought I'd post and see if that's the right approach first!

Thanks all

**Comment by guybedford** [comment]
I'm not quite sure why you specifically need to run this via a plugin instead of the plain dynamic require API?

For example you could do:

```javascript
getComponentList.then(function(componentNames) {
  return Promise.all(componentNames.map(System.import.bind(System)));
})
.then(function(components) {
});
```

Let me know if that roughly sounds like the right idea or not?

**Comment by NicholasGW** [comment]
Thanks for the response! That method makes total sense to me in a normal context but I got confused how to integrate this into a React component in a react/flux way. Specifically, say if I want to use one of these components I retrieve in the render function of my React Component, I don't think it makes sense to put the Async call in the Render function.

I'm unsure how I can make sure I have all these modules loaded before React tries to render anything, short of loading them all in the top-most component, but then I would have to pass down references.

I realize I may be missing something here...:P.

**Comment by guybedford** [comment]
I'm not a React expert at all, but I believe it's generally ok to pass references down in React as the top-down information flow is the recommended pattern. That is have the System.imports made before calling React.render. Also surely these should just be children then, which means they are passed in anyway?

**Comment by NicholasGW** [comment]
I think passing down could work... I guess part of my confusion is most examples + the React team generally use CJS/Browserify, which makes it much more straightforward to write stuff like this:

    var ChildComponent = require("myComponent");

    var ParentComponent = React.createClass({....

    render: function() {

    return ( <div> <ChildComponent /> </div> )

    });

    module.exports = ParentComponent


  And sort of lends itself well to the hierarchical way you build up UIs. There's not much guidance on what the sensible way to async load components that are used in other components. I guess loading all the ones at runtime once they are known and passing that in as a property is the sensible way to go.

**Comment by guybedford** [comment]
As mentioned, I'm not a React developer by any means, but I think dynamic import at the top would look something like:

```javascript
import AppComponent from 'app-component';

getChildren().then(function(childComponents) {

  var children = childComponents.map(function(Child) {
    return <Child data="value" />;
  });

  React.render(<AppComponent>{children}</AppComponent>, container);
});
```

Mapping the children with the right data is a little intricate, but should be fairly straightforward.

**Comment by guybedford** [comment]
Happy to discuss further, closing for now.
