### ISSUE TITLE
Overlapping bundles results in extraneous HTTP request

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#403]
``` js
// config.js
{
    "bundles": {
        "bar": ["a", "c"],
        "foo": ["a", "b"]
    }
}
```

``` js
// b.js
import a from 'a';
```

``` js
// c.js
import a from 'a';
```

``` js
// app
System.import('b')
```

I have two bundles that have overlap in their transitive dependencies.

When I import `b`, SystemJS appears to retrieve the dependency `a` from the `bar` bundle, even though it was already downloaded from the bundle `foo`. This means we have an extraneous HTTP request for a bundle that shouldn't be needed.

**Comment by OliverJAsh** [comment]
If I reverse the order of the bundles in the config, `a` is retrieved from `foo`, removing the extraneous request.

``` js
// config.js
{
    "bundles": {
        "foo": ["a", "b"],
        "bar": ["a", "c"]
    }
}
```

**Comment by guybedford** [comment]
Right this is a bug - we should be storing the list of bundles currently loading and giving those preference when doing bundle matching.

**Comment by guybedford** [comment]
Is the reordering enough for now or would it help to get this patch out sooner?

**Comment by OliverJAsh** [comment]
It would really help if we had this fixed soon. We're porting the whole of
the Guardian over to use SystemJS. I can look into this if you don't get
the chance.

It's odd that re-ordering fixed the issue. I thought JS objects don't
respect order.

**Comment by guybedford** [comment]
Sure will aim to get a patch out asap.

**Comment by guybedford** [comment]
I've just been looking into this and am trying to come up with a test case.

Am I right in thinking this comes up when you have a dynamic import requesting A, and a dynamic import requesting B just after?

**Comment by guybedford** [comment]
Struggling to get the right simple scenario going - help would be appreciated. Have a patch in https://github.com/systemjs/systemjs/commit/5806665b374c096e61cac533709981d0eac39cbb, would just be nice to match it to a test case.

**Comment by OliverJAsh** [comment]
`a` is a dependency of `b`, which I am `System.import`ing. I am never `System.import`ing `c`, so theoretically I should never see the `bar` bundle downloaded. The `foo` bundle should suffice. The bug seems to be that SystemJS wants to load the transitive dependency, `a`, from the `bar` bundle, when it should in fact already be registered from the `foo` bundle.

**Comment by guybedford** [comment]
I don't think this case should currently result in two loads though. Are you sure the names in the bundle match up with the imported name?

The reason is that by the time SystemJS knows that a b depends on a, it has already got "a" declared in its local bundle store as the bundle has been executed already. That is why I say I can only see it being the dynamic case which would cause this.

Will do some more testing here as well.

**Comment by OliverJAsh** [comment]
``` html
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>
    System.import('c');
</script>
```

``` js
System.config({
  "baseURL": "/",
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js"
  },
  "bundles": {
    "bundle1": [
      "a",
      "b"
    ],
    "bundle2": [
      "a",
      "c"
    ]
  }
});

System.config({
  "map": {
    "traceur": "github:jmcriffey/bower-traceur@0.0.87",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.87"
  }
});
```

```
$ jspm bundle --inject b bundle1.js
$ jspm bundle --inject c bundle2.js
```

This example results in:

![image](https://cloud.githubusercontent.com/assets/921609/7217444/858e8ada-e623-11e4-8cf9-b01d0727a341.png)

**Comment by guybedford** [comment]
Thanks so much for clarifying! I'll test this out again tomorrow.

**Comment by guybedford** [comment]
Just tested it out in full and the fix above has definitely resolved this!
