### ISSUE TITLE
Support async `require` inside of AMD module

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#404]
I have an AMD module that looks like this:

``` js
define(function () {
    require('foo', function () {});
});
```

The AMD module is executed successfully, but fails when it evaluates `require`: `require is not defined`.

**Comment by guybedford** [comment]
This should work with:

```javascript
define(function(require) {
  require('foo');
});
```

Async require would only apply for `require(['foo'])` though right?

**Comment by OliverJAsh** [comment]
How does this work if the original define already has dependencies?

``` js
define(['bar'], function (bar) {
    require('foo', function () {});
});
```

**Comment by guybedford** [comment]
`require`, `exports` and `module` are all special AMD requires:

```javascript
define(['bar', 'require'], function(bar, require) {
  require('foo', function () {});
});
```

**Comment by OliverJAsh** [comment]
Ta!

**Comment by OliverJAsh** [comment]
When I bundle this AMD module, the nested `require` doesn't work:

```
Uncaught TypeError: Module foo not declared as a dependency.
```

**Comment by guybedford** [comment]
Yes - `foo` needs to be a dependency as well as it is being loaded synchonously there.

The async alternative would be `require(['foo'])` via `window.require = System.amdRequire`.

**Comment by OliverJAsh** [comment]
Can you elaborate? I'm a bit confused about what exactly `System.amdRequire` is. How is it different to `System.import`?

**Comment by guybedford** [comment]
Sure - `System.amdRequire` is designed to be the same as eg RequireJS require - it isn't Promise-based and takes a callback.

**Comment by OliverJAsh** [comment]
We're aiming to bundle the same dependency graph with RequireJS *and* SystemJS, so we can run them in parallel and slowly release the SystemJS version to our users, to make sure there are no problems.

``` js
define(['bar'], function (bar) {
    require('foo', function () {});
});
```

Originally with RequireJS, `require` here would be async. I can achieve similar behaviour using `System.amdRequire`, as you pointed out, but then this breaks the build for RequireJS.

Do you have any ideas how I might make the original code work for SystemJS?

**Comment by guybedford** [comment]
I wasn't aware this dynamic require form was supported in RequireJS - we can definitely add support for it.

**Comment by OliverJAsh** [comment]
When I bundle a module that contains an aync require, I get the following error when I execute the bundled module:

Code:
``` js
require(['bootstraps/facia'], function(facia) {
```

Error:
```
TypeError: Module bootstraps/facia not declared as a dependency.
```

**Comment by guybedford** [comment]
The only require that follows the above syntax is `window.require = System.amdRequire`, and not the `define(['require'], function(require) {})` currently. Supporting this local dynamic contextual require is a feature tracked at https://github.com/systemjs/systemjs/issues/351.

**Comment by OliverJAsh** [comment]
I'm not entirely clear what that means. My goal is:

```
define(function () { require(['foo'], function () {}) });
```

To work when unbundled and bundled.

**Comment by guybedford** [comment]
@OliverJAsh I see what you mean. I've added this in https://github.com/systemjs/systemjs/commit/f80b43c5b73d6ca164dc9a2ccd8e50d294aefe9e, let me know if that helps?

**Comment by OliverJAsh** [comment]
Thanks @guybedford. That works, but not when you use `require` asynchronously:

``` js
define(['bar'], function (bar) {
    setTimeout(function () {
        require('foo', function () {});
        // window.required is undefined
    }, 500);
});
```

**Comment by guybedford** [comment]
@OliverJAsh sure I've included that as well. On jspm you can `dl-loader --edge` to test the functionality.

**Comment by OliverJAsh** [comment]
Hey @guybedford,

Code:
``` js
define(['require'], function (require) {
    require(['bootstraps/facia'], function(facia) {}
});
```

This works when unbundled. When bundled I get the following error:

Error:
```
TypeError: Module bootstraps/facia not declared as a dependency.
```

I thought this was fixed in https://github.com/systemjs/systemjs/commit/f80b43c5b73d6ca164dc9a2ccd8e50d294aefe9e?

/cc @rich-nyugen

**Comment by guybedford** [comment]
Yes dynamic requires are never detected as dependencies.

**Comment by guybedford** [comment]
Can you share the bundle output? Are you using an SFX bundle or normal bundle?

**Comment by rich-nguyen** [comment]
Yep, it's here http://aws-frontend-static.s3.amazonaws.com/CODE/frontend-static/bundles/app/abf45373d76dfcb57fecf6c7c25bf85f/app.js
if you search for the term '.boot', you can see the dynamic require.

**Comment by guybedford** [comment]
@rich-nguyen you mean the `require(["js!foresee"])`?

**Comment by rich-nguyen** [comment]
I meant this one: `require([i],function(i){i.boot(t,e,n,o)})` where the `i` is typically `http://interactive.guim.co.uk/2015/apr/krugman-3/boot.js`, a dependency that isn't known at bundle time.

**Comment by guybedford** [comment]
Right - yes we need to include support for the contextual require in SystemJS builder. I've created an issue for that at https://github.com/systemjs/builder/issues/164.
