### ISSUE TITLE
AMD with empty dependency list is not recognised

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#405]
``` js
define([''], function () {});
```

This module will not be recognised as AMD. If you remove the empty dependency list, it will be recognised as AMD:

``` js
define(function () {});
```

**Comment by guybedford** [comment]
What would be the intention of a `''` module? Is that valid code?

**Comment by OliverJAsh** [comment]
I'm not sure if it is a valid AMD module? If not we don't need to worry, but it came up in the codebase I'm converting.

**Comment by guybedford** [comment]
It would probably throw anyway if detected as AMD.

**Comment by guybedford** [comment]
One can define an empty module though - `System.set('', System.newModule({}))` so perhaps strictly it could be allowed if it was really needed. Just let me know.

**Comment by OliverJAsh** [comment]
Not really a big issue!
