### ISSUE TITLE
global extension safari bug

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#406]
SystemJS's global extension uses `getOwnProperty` on `loader.global`. The method throws an error if called inside a web worker inside safari (iOS 8.3 and desktop version 8.0.2). If I replace the condition in [this code](https://github.com/systemjs/systemjs/blob/98c3de60be24b119f8ca38b1c446ea1b0c74927b/lib/extension-global.js#L53) with a simple `true` it works. That's super strange...

error.stack:
```
hasOwnProperty@[native code]
prepareGlobal@http://192.168.0.10:8080/packages/system.src.js:1020:62
...
```

error:
```
TypeError: ...
Error loading "github:jmcriffey/bower-traceur@0.0.87" at http://192.168.0.10:8080/packages/github/jmcriffey/bower-traceur@0.0.87.js
Error evaluating http://192.168.0.10:8080/packages/github/jmcriffey/bower-traceur@0.0.87.js
undefined is not an object (evaluating 'loader.global.hasOwnProperty(g)')
```

I did some research on the internet and this bug appears in other projects as well. https://github.com/facebook/regenerator/issues/183 They fix it by using `getOwnPropertyNames()` instead which is just ES5.1 but for some reason works.

Possible fixes:
- Drop hasOwnProperty check entirely
- Use hybrid approach. Web workers aren't present on ES3 browsers.
- Use `getOwnrPropertyNames` and expect ES5.1 (Probably not so great for some people)

**Comment by MajorBreakfast** [comment]
I just realized why this bug appears now and didn't before: I have no global modules in my web worker script. However what has changes is that traceur is now loaded as a global module. So, the problem existed before, I just didn't encounter it.

**Comment by guybedford** [comment]
Thanks so much for the detailed report!

I've included a fix in master as above, will test on IE8 etc when running the release soon.

**Comment by MajorBreakfast** [comment]
@guybedford You're welcome. I made some comments in [the commit](https://github.com/systemjs/systemjs/commit/fc12514b2d5dcc5cdef48bf04176baf59608fb97).

**Comment by MajorBreakfast** [comment]
My implementation of `forEachGlobal`.
```JS
function forEachGlobal(callback) {
  function handle(key) {
    if (indexOf.call(ignoredGlobalProps, key) != -1) { return; }

    var value;
    try { value = loader.global[key]; }
    catch (e) { ignoredGlobalProps.push(key); }

    if (value === loader.global) { return; }

    callback(key, value);
  }

  if (Object.keys) {
    Object.keys(loader.global).map(handle);
  } else {
    for (var key in loader.global) {
      if (loader.global.hasOwnProperty(key)) { handle(key); }
    }
  }
}
```

- Merges the two methods
- Some vars are renamed
- Moved `hasOwnProperty` into the `for ... in` loop

**Comment by guybedford** [comment]
Thanks, I've updated the commit above.

**Comment by MajorBreakfast** [comment]
- I really liked your`Object.keys()` approach: It and `for ... in`+`hasOwnProperty` both list enumerable own properties. It'd be good if the search was always limited to own properties for consistency.
- Also, some renaming ideas:
  - g, curGlobal -> key, value
  - curGlobalObj -> globalSnapshot
  - multipleExports -> hasMultipleExports

**Comment by guybedford** [comment]
Good naming suggestions! Object.keys doesn't add anything though, apart from more code.

**Comment by MajorBreakfast** [comment]
It gets the job done without crashing in safari

**Comment by guybedford** [comment]
The current fix works fine though?

**Comment by MajorBreakfast** [comment]
Didn't test it but It has to.
It's essentially the same as my current dirty fix: `self.hasOwnProperty = function() { return true }` :)

I'd prefer adding the `Object.keys` workaround which lets both branches behave identically.

**Comment by guybedford** [comment]
@MajorBreakfast I finally implemented these suggestions in https://github.com/systemjs/systemjs/commit/9d477f9bfdde8e5d0b6921bd5715c23e76b73f42.

**Comment by MajorBreakfast** [comment]
Nice!

One last suggestion:
`iterateGlobals` -> `forEachGlobal`
`forEachGlobal` -> `forEachNotIgnoredGlobal`
because the current names are synonymous.
