### ISSUE TITLE
CSP SystemJS: Babel not downloaded

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#407]
When I use the CSP version of SystemJS, ES6 detection seems to fail and thus Babel is not downloaded, resulting in:

```
Uncaught SyntaxError: Unexpected reserved word
13987:751 Uncaught Error loading "es6/bootstraps/app" at http://localhost:9000/assets/javascripts/es6/bootstraps/app.js
http://localhost:9000/assets/javascripts/es6/bootstraps/app.js did not call System.register or AMD define
```

**Comment by MajorBreakfast** [comment]
The csp version prevents issues with the **c**ontent **s**ecurity **p**olicy of runtime environments like chrome web apps. Instead of using `eval` the code is downloaded and executed using a script tag. This unfortunately means that no transpilation can be applied.

**Comment by OliverJAsh** [comment]
Cheers @MajorBreakfast

**Comment by guybedford** [comment]
@OliverJAsh a good workflow here is to compile modules from ES6 into System.register with a watcher, and then they will be CSP-compatible in the browser. But loading CommonJS won't work this way yet unfortunately, although it is planned. If you want further help with these workflows at all, I'd be happy to discuss the use case in more detail anytime.

**Comment by OliverJAsh** [comment]
@MajorBreakfast Your description of the CSP version of SystemJS was spot on. Could we add this to the documentation/wiki?

**Comment by OliverJAsh** [comment]
@MajorBreakfast Your description of the CSP version of SystemJS was spot on. Could we add this to the documentation/wiki?

**Comment by OliverJAsh** [comment]
| Script | XHR
--- | --- | ---
Eval | x | ✓
Same origin policy | x | ✓

Transpiling is only supported via eval, thus only via XHR loads.

Is this correct?

**Comment by guybedford** [comment]
Yes!
