### ISSUE TITLE
Web worker detection fails on iOS 7

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#409]
I just discovered that the web worker detections fails in iOS 7 Safari because the `WorkerGlobalScope` doesn't exist there.

iOS 7 Safari has (in alphabetical order, tl;dr `WorkerGlobalScope` is missing):
```
Array, ArrayBuffer, Blob, Boolean, DataView, Date, Error, EvalError, EventSource, FileReader, FileReaderSync, Float32Array, Float64Array, Function, Infinity, Int16Array, Int32Array, Int8Array, JSON, Math, MessageChannel, MessageEvent, NaN, Number, Object, RangeError, ReferenceError, RegExp, String, SyntaxError, TypeError, URIError, URL, Uint16Array, Uint32Array, Uint8Array, Uint8ClampedArray, WebSocket, WorkerLocation, XMLHttpRequest, __defineGetter__, __defineSetter__, __lookupGetter__, __lookupSetter__, __proto__, addEventListener, clearInterval, clearTimeout, close, console, constructor, decodeURI, decodeURIComponent, dispatchEvent, encodeURI, encodeURIComponent, escape, eval, getAllProperties, hasOwnProperty, importScripts, isFinite, isNaN, isPrototypeOf, location, navigator, onerror, onmessage, openDatabase, openDatabaseSync, parseFloat, parseInt, postMessage, propertyIsEnumerable, removeEventListener, self, setInterval, setTimeout, toLocaleString, toString, undefined, unescape, valueOf, webkitURL
```

It'd be nice if SystemJS's environment checks were centralized, e.g. introduce some a vars like `isNode`, `isBrowser`, `isBrowserDocument`, `isBrowerWebWorker` for use in its extensions and computed in `polyfill-wrapper-start.js`. For this we need to list all checks that are used in the various extensions first of course.

**Comment by guybedford** [comment]
@MajorBreakfast see the commit above. Let me know if that works better for you, I will be doing the testing myself with the release cycle shortly.

**Comment by guybedford** [comment]
(btw yes detections are more central in the next major change)

**Comment by guybedford** [comment]
This should be working now in the next patch release, let me know if you notice any further issues.
