### ISSUE TITLE
Issue with Flux when not bundling

### ISSUE THREAD

**Issue by NicholasGW** [systemjs/systemjs#411]
Hey all,

Perhaps this problem is me not understanding fully how SystemJS is handling loading CJS modules in the browser, but I appear to have a problem:

In a flux/React app, I have multiple CJS modules that require use of the Dispatcher, and load it like so:

    var AppDispatcher = require('js/dispatchers/app-dispatcher');

app-dispatcher is like so:

    var Dispatcher = require('flux').Dispatcher;

    module.exports = new Dispatcher();

Rather than bundle-like behaviour in which the dispatcher only gets loaded once, it appears that it's being loaded for each require. This has the unfortunate effect of when my Store requires it and registers callbacks, when the next component requires it a new instance is instantiated and the previous callbacks are lost.

Am I missing something or is this the intended behaviour and I should be bundling?

**Comment by MajorBreakfast** [comment]
Can you double check this by inserting a `console.log` into the source?

**Comment by NicholasGW** [comment]
Sure thing...for the record I'm also seeing this with other modules, for example my settingsStore:

![image](https://cloud.githubusercontent.com/assets/6642497/7235936/ec0bccce-e767-11e4-934b-b927e6f9fa97.png)

**Comment by NicholasGW** [comment]
I threw in some console.logs just after the require(app-dispatcher) code, which shows that the callbacks registered in settingsStore are no longer present when app-actions requires Dispatcher. Hope it's just something silly...thanks for your help!

![image](https://cloud.githubusercontent.com/assets/6642497/7236181/af1ef9a6-e769-11e4-9f56-2e475e15a545.png)

**Comment by MajorBreakfast** [comment]
Next thing I would do is try to replicate this in a test project with as few files as possible. If you can replicate it, then upload the test project to github.

I have several modules that I use in multiple places in my app. Their code is executed just once each - as it should. I'm using the es6 format. What you're describing should not happen. There must be an explanation for it.

**Comment by NicholasGW** [comment]
Thanks for the response...I actually just did as you suggested and was unable to replicate it, so it might be something odd with my full app. I'll keep digging!

**Comment by NicholasGW** [comment]
I have discovered and fixed the issue! It seems it had to do with the fact that for one require, I was using the filename without an extension, and for another require I had filename + extension, plus a plugin. This was a from a previous version in which I was experimenting with the JSX plugin and just converted everything over. Although this didn't make much sense now, I'm not sure it should have cause a problem, so I will show how to reproduce:  
  
If loading app-dispatcher.js as shown above, one module would have this:

    var AppDispatcher = require('app-dispatcher');

and another module would have this:

    var AppDispatcher = require('app-dispatcher.js!jsx');

It will load app-dispatcher.js twice. Given, typing the above like that is likely erroneous as I can't imagine a scenario where you only need/want to use a plugin to load a module SOME of the time, but just thought I'd mention it anyway. Example is here:

https://github.com/NicholasGW/systemjsexample

Cheers!

**Comment by MajorBreakfast** [comment]
Ah that makes sense. @guybedford has a new plugin system in the works that makes this simpler.

**Comment by NicholasGW** [comment]
Perfect! Thanks for the help @MajorBreakfast. Closing this down.
