### ISSUE TITLE
Remove `babel` handling, to always use `babel-core`

### ISSUE THREAD

**Issue by crisptrutski** [systemjs/systemjs#413]
Relevant modules are picked up from `babel-core`, but not from `babel-cli` (ie. `npm install babel`)

See https://github.com/systemjs/builder/issues/148

**Comment by guybedford** [comment]
`babel` no longer contains `browser.js` so we can remove the `babel` handling entirely.

**Comment by crisptrutski** [comment]
:+1:

**Comment by crisptrutski** [comment]
Remove obsolete mappings here de1f7ee999cacb6866fff91291fac4d062109c91
