### ISSUE TITLE
System.register doese not work under node.js 

### ISSUE THREAD

**Issue by PinkaminaDianePie** [systemjs/systemjs#415]
under node.js compiled code throw this error:

```javascript
throw new TypeError('Multiple anonymous System.register calls in the same module file.');
```
but in my module System.register called only once:

```javascript
require("source-map-support").install();require("babel/polyfill");var System = require("systemjs");System.register(['chai', '../../lib/active-record/active-record', '../../lib/errors'], function (_export) {
	var chai, ActiveRecord, _this, _classCallCheck, _get, _inherits, should;

	return {
```

**Comment by guybedford** [comment]
The problem most likely comes from mixing `System.register` alongside `require` calls, which SystemJS will attempt to manage as well in modules you load through SystemJS.

**Comment by PinkaminaDianePie** [comment]
but how should i do in this case? i dont load anything via SystemJS, i only compilled my code in system format, and dont use System.import() anywhere.

**Comment by PinkaminaDianePie** [comment]
i have tried to switched to commonjs format, but my code doese not work well with it - seems to SystemJS polute global scope, used by babel polyfills or smth. for example this code works well:
```javascript
A.get({}).get('123').get('123', '456'); //returns Promise
```
but this code
```javascript
try{
	let a = await A.get({}).get('123').get('123', '456'); //es7 async function, works with promises
	done();
}catch(e){
	done(e);
}
```
fails with error:
```bash
node_modules/es6-module-loader/dist/es6-module-loader.src.js:1185
				next.become(new Rejected(e));
        ^
TypeError: Cannot read property 'become' of undefined
```
Both snippets works well without SystemJS, but when i include it (just include, without any System.import calls), second snippet crashes with error.

**Comment by guybedford** [comment]
@PinkaminaDianePie code compiled for the System format can only run in SystemJS itself, or via a self-executing bundle. If you're looking to compile ES6 into CommonJS for use in Node directly, just use Babel via Gulp with the CommonJS output.

**Comment by PinkaminaDianePie** [comment]
@guybedford i was used it this way before, but now i need to load some modules in runtime. ES6 modules can not ne loaded anywhere except top of the file, so i need to load it with System.import(). So i can't use SystemJS for this and must create own polyfill based on promises and node's require()?

**Comment by guybedford** [comment]
@PinkaminaDianePie runtime loading of ES6 means using a loader like SystemJS. Unfortunately it does mean using `System.import` to load everything then.

**Comment by PinkaminaDianePie** [comment]
@guybedford i dont need resolve circular dependencies or smth, just runtime load. I can just use require() in node, but i want to use only es6 syntax and tools. So i think it will be easier to write own polyfill which did not fit full spec, but acceptable in one simple use case.

**Comment by guybedford** [comment]
Closing, but if you have any further questions please feel free to ask.
