### ISSUE TITLE
Plugin load address missing file extension

### ISSUE THREAD

**Issue by phamann** [systemjs/systemjs#416]
I have a path `//connect.facebook.net/en_US/all.js` but when this has reached my plugin (i.e. the path has been resolved) it is missing the `.js` file extension inside the `address` key in the load object passed to my plugins fetch method.

![google chrome](https://cloud.githubusercontent.com/assets/80089/7256714/b360e21a-e848-11e4-9c20-a9989d7c1331.png)

**Comment by OliverJAsh** [comment]
Could it be to do with this, @guybedford? https://github.com/systemjs/systemjs/blob/master/lib/extension-plugins.js#L89-L98

**Comment by phamann** [comment]
So if we update the plugin to expose a proper `locate` method, we can handle this...

**Comment by OliverJAsh** [comment]
From my testing, it looks like you just need to provide a `locate` method that returns the default:

``` js
exports.locate = function(load) {
    return System.locate(load);
};
```

If you don't provide this, SystemJS will remove the `.js`: https://github.com/systemjs/systemjs/blob/master/lib/extension-plugins.js#L89-L98

Is this correct behaviour @guybedford?

**Comment by matthewp** [comment]
Plugins don't go through the normal locate unless you explicitly tell them to, otherwise this would fail:

```js
import "foo.css!css"
```

because it would try to load `foo.css.js`.  So yes, if you are writing a plugin that expects JavaScript-by-default then calling the loader's locate is the way to go.

**Comment by OliverJAsh** [comment]
@phamann We should contribute our fixes upstream to the plugin.

**Comment by guybedford** [comment]
Yes we had to use a heuristic to make the case @matthewp shows work, and as a result we get this edge case.

It is really due to the bad design of paths automatically adding js extensions, which is changing in the next release.

I'm not sure there's anything better we can do in SystemJS itself for now.

**Comment by guybedford** [comment]
Closing as there's nothing nice we can really do here. This gets better in the next major release though.
