### ISSUE TITLE
JSPM CDN treats es6 module on Github as cjs

### ISSUE THREAD

**Issue by edrex** [systemjs/systemjs#417]
It seems that es6 modules don't work properly when fetched from the jspm CDN and transpiled with Babel.

I have an example consisting of a [main project](https://github.com/edrex/hello-systemjs-example) and an external [Hello](https://github.com/edrex/hello-component) module. It works fine when the module is installed locally, but breaks with `setmode remote`. I put up a [live copy](https://edrex.github.io/hello-systemjs-example/) set to load from the CDN, so you can see the breakage.

If I set the Chrome debugger immediately after the line in `main.js` that includes the module (with source map support turned on),

```javascript
import Hello from 'hello';
```

and run `Hello = Hello['default']`, then the demo works correctly.

The module seems to initially be doubly-nested in `default`.

Are the contents of my module's [package.json](https://github.com/edrex/hello-component/blob/master/package.json) incorrect?

**Comment by edrex** [comment]
I dug into this a little further (getting to know the tool chain) and the difference seems to be that

https://github.jspm.io/edrex/hello-component@0.1.1.js

is coming back as commonjs, while the local package, http://localhost:3000/jspm_packages/github/edrex/hello-component@0.1.1.js, is es6:

```javascript
export * from "github:edrex/hello-component@0.1.1/index";
```

I guess that makes this a... jspm/registry issue? I'm not sure where the code running the CDN lives (is it public?)

**Comment by guybedford** [comment]
Thanks for letting me know - I've fixed this on the server now!

**Comment by edrex** [comment]
awesome, thanks @guybedford.

https://github.jspm.io/edrex/hello-component@0.1.5.js comes back in es6 format now, so great!

In my poking around I noticed that 

https://github.jspm.io/edrex/hello-component.js

returns a pointer to the latest version. That's still coming back cjs.

**Comment by guybedford** [comment]
Sure! That could be a cache issue - try clearing your browser cache, the headers can be pretty brutal although that request isn't supposed to be heavily cached. Alternatively ensure that it's mapping to a version that definitely has ES6.

**Comment by edrex** [comment]
It doesn't seem to be a local cache issue (used chrome incognito, curl).

**Comment by guybedford** [comment]
Right, jspm internally caches the format, but this isn't being properly flushed when the package is updated. I've flushed that one for now, and I've made a note of that at https://github.com/jspm/project/issues/26, but can't guarantee I'll get to it soon.

**Comment by guybedford** [comment]
Actually sorry the format cache wasn't being populated correctly - I've fixed this now.
