### ISSUE TITLE
__filename and __dirname not to use protocol paths where possible

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#419]
This is done in browserify so that path can work against them: `/path/to/file.js` over `https://site.com/path/to/file.js`.

**Comment by u9520107** [comment]
@guybedford for the line
```
var curOrigin = location.origin;
```
IE doesn't support location.origin. Might need an alternative solution in this case. (tested on IE 11)
Project spartan on the other hand does support this though.

**Comment by guybedford** [comment]
Thanks so much for posting - I've included https://github.com/systemjs/systemjs/commit/8b841dcde4b68175cbaa5ff6f9391f719332018f.
