### ISSUE TITLE
Support global script-loading subset

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#420]
When loading a global script that has:

* `metadata.exports` set
* No `metadata.globals` provided
* No `metadata.deps` provided

We can support automatically loading that global via script tag injection.

**Comment by guybedford** [comment]
The reason we need to have `metadata.exports` set is because the current expectation is that a global without exports will provide automatic global detection, which would break down if we suddenly add this by default.

**Comment by MajorBreakfast** [comment]
- What if the module has no exports like some polyfill?
- Are two strategies sensible? Explicitly opting in to script tag injection by using system-csp has its benefits.

**Comment by guybedford** [comment]
We could support a special `exports: false` value for the no exports case - the important point is we need to know about that to know it's possible to work.

It will still be possible to opt-in to script loading via `System.meta = { '*': { scriptLoad: true } }`.

**Comment by guybedford** [comment]
Merged into master.
