### ISSUE TITLE
Potential circular dependency issue

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/systemjs#422]
I'm not sure if this should work or not? I have a circular dependency between two modules which doesn't appear to be working. This code is written in TypeScript, and I'm using CommonJS as the output format (I can post the produced JS too, if needed):

mod-a.ts:
```typescript
import { ClassB } from './mod-b';

export class ClassA
{
  constructor()
  {
  }

  public isB(): boolean
  {
    return this instanceof ClassB;
  }
}
```

mod-b.ts:
```typescript
import { ClassA } from './mod-a';

export class ClassB extends ClassA
{
  constructor()
  {
    super();
  }
}
```

index.ts
```typescript
import { ClassA } from './mod-a';
import { ClassB } from './mod-b';

var a = new ClassA();
var b = new ClassB();

window.alert(a.isB());
window.alert(b.isB());
```

The result is an error within the TypeScript-injected __extends function in mod-a.ts where it attempts to set the prototype of the class to that of the base constructor. It's because the base constructor is undefined. 

Honestly not sure if this is a problem in TypeScript, in SystemJS, or if it's simply because I'm using the CommonJS output format, and only the register output can handle circular references?

**Comment by MajorBreakfast** [comment]
Circular dependencies work with the es6 and the register format. CommonJS doesn't support them.

**Comment by jamiewinder** [comment]
I thought that might be it. There is a PR in TypeScript for adding register support, so hopefully that'll do the trick. Thanks.
