### ISSUE TITLE
Issue loading baobab: 'Uncaught TypeError: helpers.inherits is not a function'

### ISSUE THREAD

**Issue by frankwallis** [systemjs/systemjs#425]
I am running into this issue when trying to load baobab - it seems like the modules are not being loaded correctly, but it's a bit odd. 

I have created a little test project which demonstrates the issue [here](https://github.com/frankwallis/baobab-jspm-test)

What I am seeing:
1) When bundling in the browser it fails with the above message
2) Doing an SFX bundle and running from that works ok

I have tried:
1) Installing from Github
2) Adding registry='npm' override
3) Adding format='cjs' override

but no luck

**Comment by MajorBreakfast** [comment]
Can you log the helpers module? Just inject a `console.log` after where it's imported.

**Comment by frankwallis** [comment]
It's an empty object {}

**Comment by frankwallis** [comment]
It also looks like this module has quite a lot of circular references:

helpers -> type -> facet -> type

and

helpers -> type -> facet -> cursor -> helpers

**Comment by MajorBreakfast** [comment]
That is probably the issue then. Next, you should probably insert some `console.log`s to exactly determine the order in which your modules get executed.

**Comment by frankwallis** [comment]
ok so I put in some logging:

working (when bundled):
```
in baobab
in cursor
in helpers
in type
running type
running helpers
loading cursor
in facet
running facet
in update
running update
in merge
running merge
running baobab
```

not working (browser loading):
```
in baobab
in cursor
in helpers
in type
running type
in facet
running facet
```

so after running 'type' it should continue executing 'helpers', but instead it fails to load 'facet'. It looks as though this is because 'type' requires 'facet' inside a function:

[type.js](https://github.com/Yomguithereal/baobab/blob/master/src/type.js#L113)
```
type.FacetFacets = function(value) {
  if (!type.Object(value))
    return false;
  return Object.keys(value).every(function(k) {
    var v = value[k];
    return typeof v === 'string' || v instanceof require("./facet");
  });
};
module.exports = type;
```

I can keep investigating, but is this a bug or just unsupported behaviour?

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/npm/issues/62.

**Comment by guybedford** [comment]
Yes this is a SystemJS issue - created https://github.com/systemjs/systemjs/issues/426.
