### ISSUE TITLE
Circular reference issue

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#426]
In https://github.com/systemjs/systemjs/commit/1ffea562e13c15c999367a465e05fe144111030f, this has stopped the correct interpretations of circular references now.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/a69f38369c0013936c767b8346c0154e83e05036.

**Comment by matthewp** [comment]
Was this not breaking the circular ref tests?

**Comment by guybedford** [comment]
Apparently not.
