### ISSUE TITLE
To get around adding Javascript function to HTML

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#427]
I use WordPress that has a nice function `wp_localize_script()` to output a global **before** the script.
How should I *autostart* my main module?

Now I append this to system.js:
```js
// SystemJsConfig is the name of the global
System.config(SystemJsConfig);
System.import('js/main');
```

curl.js was able to autoconfig and autostart from a global called `curl`.

**Comment by szepeviktor** [comment]
I think the base URL can be provided: `System.baseURL = originalSystem.baseURL;`
But haven't found anything else.

**Comment by szepeviktor** [comment]
It would be nice to have
```html
<script type="text/javascript" data-systemjs-run="bundle.js,run.js" src="system.src.js"></script>
```

**Comment by guybedford** [comment]
I'm weary of tying in an API that's just going to need to be deprecated in future.

It's easy to handle this stuff manually.

**Comment by MajorBreakfast** [comment]
I agree. No need to add sugar on top of something that is already nice to use. Too much sugar and it gets all sticky xD (or hard to remember/maintain)
