### ISSUE TITLE
Plugin location

### ISSUE THREAD

**Issue by szepeviktor** [systemjs/systemjs#428]
I am searching for documentation :) but all I've found is code:
`return Promise.resolve(loaderNormalize.call(loader, name, parentName, parentAddress))`

Must plugins be located in `baseURL` and cannot be relocated by `paths`?

**Comment by guybedford** [comment]
Plugins run through the standard locate hook by default, so will have paths configuration apply.

**Comment by szepeviktor** [comment]
Sorry.
You are right. I must have been lost in the parameters.
