### ISSUE TITLE
SFX error messages

### ISSUE THREAD

**Issue by subesokun** [systemjs/systemjs#430]
Would it be possible to print an extra console error in case SystemJS failed to load the dependencies? In my case I was using bundle-sfx of jspm and in the error console I was seeing an error but accidentally misinterpreted it (I didn't have a close look on the stack trace) and thought everything went fine with loading the dependencies. So it took me a while until I've noticed that this error was preventing SystemJS to load all dependencies and I was debugging into the wrong direction. Sadly my application is also loading stuff without jspm so the app started half way hence it was not obvious to me that something went wrong with loading the dependencies.

I think adding a console error like `Failed to import dependencies due to an uncaught exception`, `Failed to import module endp:xyz`, ... or similar would help making clear that not all dependencies have been loaded and you should better have a look on it. Does this makes sense?

**Comment by MajorBreakfast** [comment]
Have you something like this in use?
```HTML
<script>
  System.import('lib/main')
    .catch(function(e) { console.error(e && e.stack || e)})
</script>
```

If one of my files is not found I get something like this:
```
Error loading "lib/router" at http://localhost:8080/lib/router.js
Error loading "lib/router" from "lib/main" at http://localhost:8080/lib/main.js
Not Found: http://localhost:8080/lib/router.js
```
In the above example it clearly says that `router.js` is not found.

**Comment by subesokun** [comment]
Sadly this doesn't work in case you're using `bundle-sfx` of jspm as then you won't have the `System.import` call. You only include the bundled JS file via the `<script>` tag, that's all.

**Comment by MajorBreakfast** [comment]
Ah kay. Sorry that I didn't catch that part. You should probably move that issue into systemjs/builder. The sfx bundle logic lives in [this file](https://github.com/systemjs/builder/blob/fb59e1490d620c8081ab946774d78cf4b2998fb0/lib/templates/sfx-core.js). AFAIK in case of sfx bundles the real SystemJS is only used for building the sfx-bundle. At runtime you only get this minimal loading mechanism.

**Comment by guybedford** [comment]
@subesokun so are you saying just an extra message reading: `System SFX bundle import of xyz failed` at the top of the error stack would have helped?

**Comment by subesokun** [comment]
@guybedford Seeing a message telling that the import has failed would have helped definitely. But when adding this error on top of the stack you'd need to expand the error stack to see the root cause or? Maybe then a error message like `System SFX bundle import of xyz failed. See error stack for root cause.` would be helpful not that people will overlook the error that caused the import to fail.

I'm wondering if in general (not only bundle sfx) such bundle import error would be helpful in case you don't have added the `catch` statement when calling `System.import`.

**Comment by guybedford** [comment]
SFX is a target that is optimized for file size. As such, it doesn't have the same useful debugging traces etc, we get from SystemJS builder.

For full debugging information, users should use a normal bundle against SystemJS, or unbundled. That is the "development" environment.

When using SFX builds, the only thing we can do extra is to mention that it's an SFX build failure. But that will be obvious because there will be an error inside the SFX js file.

So I'm not actually even sure what value an extra message would provide here.

**Comment by subesokun** [comment]
@guybedford What do you mean exactly with SFX build failure? In my case the issues was caused when trying to load a given module which then tried to access a property that hasn't been defined yet. But the actual SFX build was successful.

Normally I develop against the unbundled source but there is a little demo app which just consumes the pre-build SFX bundle so that it doesn't depend on any tool to make the demo as simple as possible and independent from external resources/servers. As this is a corner case it'd be also ok for me to close this issue.

Generally, is it now recommended to add the `catch` statement as mentioned by @MajorBreakfast ? I remember some discussion regarding that and removed then as recommended back then the `catch` statement. So that's why I was wondering if such import error message would have made sense also for the normal development using unbundled sources.

**Comment by guybedford** [comment]
I mean exactly when there is an error in module code exected within an SFX bundle, not creating the SFX bundle. I think we can close this as I don't want to bloat SFX bundles with debugging information as mentioned above.

**Comment by subesokun** [comment]
Ok no problem, so I'll close this issue.

**Comment by guybedford** [comment]
Thanks!
