### ISSUE TITLE
Emit Traceur / Babel runtime as a dependency

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#431]
I just noticed during a quick test that this is the case.
During my development I usually use `jspm bundle --inject ...` and `jspm unbundle` and this feature eliminates the requirement for any code changes to `index.html`. It's awesome :) Doesn't work with System CSP, though. `$traceurRuntime is not defined`

**Comment by guybedford** [comment]
Yes - it can't detect the use of Traceur runtime as it can't parse the source.

**Comment by MajorBreakfast** [comment]
Traceur runtime should be listed as a dependency, I think. That's what it is after all. What do you think?

**Comment by guybedford** [comment]
I did prototype that previously actually, but the dependency syntax would have also had to be parsed anyway (`"deps traceur"`). Otherwise it needs to be a dependency of every module in the bundle! Note that modular Babel runtime works like this though.

**Comment by MajorBreakfast** [comment]
I mean like this:
```JS
System.register("my-module", ["traceur-runtime"], function($__export) {
  ...
  return {
    setters: [...],
    execute: function() { ... }
  };
});
```

**Comment by guybedford** [comment]
Yes it would have to be done for every module that depends on Traceur runtime.

The question is what if the user doesn't want to load Traceur runtime as a module, and are using a script tag? (backwards-compatibility)

**Comment by MajorBreakfast** [comment]
SystemJS isn't the most backwards compatible project around :) I think, modules all the way is the way to go.

The bundle could (and probably should) include the runtime by default. If somebody doesn't want that, he/she could simply do:
`jspm bundle my-module - traceur-runtime`

**Comment by Hypercubed** [comment]
Sorry guys the github issues were leading me in circles.  Is this still open?  I had no trouble bundling with babel but when using traceur runtime is missing.

**Comment by guybedford** [comment]
Yes Traceur runtime needs to be included manually unless making an SFX bundle.

**Comment by lucalenardi** [comment]
I'm getting an `Uncaught ReferenceError: $traceurRuntime is not defined` even with `bundle-sfx`with jspm@0.16.10. 

Traceur is added in the map part of the config.js file and is in the package.json dev dependencies. No error in the bulding process, but still, no runtime.

Is there something to verify?

**Comment by guybedford** [comment]
@lucalenardi thanks this was a regression I've fixed in https://github.com/systemjs/builder/commit/8013581a9b6397f3a522b029a6519c36ca75b15a.

**Comment by guybedford** [comment]
This has been implemented in https://github.com/systemjs/plugin-babel/blob/master/babel.js#L47, so will apply when using external plugins for transpilation, the workflow we are moving towards here.

**Comment by guybedford** [comment]
(note that the above is not yet released)
