### ISSUE TITLE
Help - "Multiple defines for anonymous module"

### ISSUE THREAD

**Issue by nalbion** [systemjs/systemjs#433]
I'm working on a "Hello World" app using Angular 2.0 & TypeScript with asynchronous modules.  

I've based my work on the Angular Quick Start guide: https://github.com/angular/ts-quickstart.git

I can build my multi-module app (on [GitHub](https://github.com/nalbion/angular2-ts-demo)) and as long as `MyAppComponent` is located in `_main.ts` everything works okay - but ideally, I'd be using the compile-time modules to have `MyAppComponent` (and all of the other components) moved into its own subdirectory & file.  However, as soon as I do that, SystemJS throws an exception:  ***"Multiple defines for anonymous module"***  (See [this branch](https://github.com/nalbion/angular2-ts-demo/tree/feature/relocated-my-app-component))

When I comment out the call to the external module the relocated `MyAppComponent` works without error (See [this branch](https://github.com/nalbion/angular2-ts-demo/tree/feature/relocated-my-app-without-initExtras)) - but what do I need to do to get both working together?

...Obviously I'm very new to TypeScript, SystemJS & Angular 2.0 and my code may be a bit naive at the moment (I'm not even sure why I'm using SystemJS through jspm.io - I'm just expanding on ts-quickstart).  If you can help me fix it up a bit hopefully this demo will help others get up to speed more quickly.

Thanks!

**Comment by nalbion** [comment]
My app is running here: http://nalbion.github.io/angular2-ts-demo/dist/

**Comment by gdi2290** [comment]
the problem was the build system which was combining multiple `amd` files that SystemJS did not like. The solution was compile the TypeScript to ES6 for SystemJS builder to compile the files with `System.register` wrappers

**Comment by jiaweihli** [comment]
@guybedford Is there a way to avoid this issue?  I'm currently compiling TypeScript (with some other Coffeescript) using browserify into commonjs, and was hoping to load the resulting output into systemjs to avoid the traditional circular dependency pitfall.  I got the same error: `Uncaught TypeError: Multiple defines for anonymous module` while systemjs was loading backbone.

**Comment by guybedford** [comment]
@jiaweihli you can set the module format as `register` via meta config to fix this - `System.config({ 'path/to/file': { format: 'register' } })`.

**Comment by jiaweihli** [comment]
I've tried this:

```html
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.js"></script>
    <script>
      System.config({
        baseURL: '/',
        'js/dashboard.js': {
          format: 'register'
        }
      });

      System.import('js/dashboard.js');
```

but I'm running into the same error.

**Comment by jiaweihli** [comment]
Ah, I think:

> For comprehensive handling of NodeJS modules, a conversion process is needed to make them SystemJS-compatible, such as the one used by jspm.

from https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#commonjs is the issue.
