### ISSUE TITLE
Can't load angular-file-upload

### ISSUE THREAD

**Issue by togakangaroo** [systemjs/systemjs#438]
Very likely that I'm missing something here but I *think* that this might be a bug. 

I'm using systemjs via jspm pulling in [angular-file-upload](https://github.com/nervgh/angular-file-upload). It's serving [this file](https://github.com/nervgh/angular-file-upload/blob/master/angular-file-upload.js).

No matter what I do I keep getting errors when I 

    import 'nervgh/angular-file-upload'

Here is my configuration (the meta configuration for this module is toward the bottom)

```
System.config({
  "baseURL": "/Scripts",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.3.15",
    "babel": "npm:babel-core@5.1.13",
    "babel-runtime": "npm:babel-runtime@5.1.13",
    "core-js": "npm:core-js@0.9.5",
    "lodash": "npm:lodash@3.7.0",
    "nervgh/angular-file-upload": "github:nervgh/angular-file-upload@1.1.5",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:core-js@0.9.5": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:lodash@3.7.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});

System.meta['github:nervgh/angular-file-upload@1.1.5'] = { 
  format: 'global', // options: amd, cjs, es6, global, register
  // exports: 'angular', // if format === 'global', the name of the global
  deps: ['angular']
}
```

Whenever I run this I get an error that "define is not a function". I've tried turning the format to 'amd' as angular-file-upload.js **does** have a umd on it. This gives me

```
Potentially unhandled rejection [2] Error: Error loading "github:nervgh/angular-file-upload@1.1.5" at http://localhost:59006/Scripts/jspm_packages/github/nervgh/angular-file-upload@1.1.5.js
Error loading "github:nervgh/angular-file-upload@1.1.5" from "aboutSurge" at http://localhost:59006/Scripts/aboutSurge.js
Unable to load dependency github:nervgh/angular-file-upload@1.1.5/angular-file-upload.
    at c (http://localhost:59006/Scripts/jspm_packages/system.js:1:5640)
    at http://localhost:59006/Scripts/jspm_packages/system.js:1:6055
    at $__global.upgradeSystemLoader.c.execute (http://localhost:59006/Scripts/jspm_packages/system.js:1:14500)
    at f (http://localhost:59006/Scripts/jspm_packages/system.js:1:5970)
    at l (http://localhost:59006/Scripts/jspm_packages/system.js:1:4597)
    at Object.$__global.upgradeSystemLoader.e.instantiate.Promise.all.then.execute (http://localhost:59006/Scripts/jspm_packages/system.js:1:8278)
    at o (http://localhost:59006/Scripts/jspm_packages/es6-module-loader.js:7:18496)
    at p (http://localhost:59006/Scripts/jspm_packages/es6-module-loader.js:7:18868)
    at j (http://localhost:59006/Scripts/jspm_packages/es6-module-loader.js:7:16406)
    at k (http://localhost:59006/Scripts/jspm_packages/es6-module-loader.js:7:16791)
```

This is really confusing as I don't see any error message I can act on. In fact, this is the same error it gives as if I have no meta configuration at all or if I omit the `format` key.

In what way is it failing? I have no idea. I tried replacing `angular` in the deps with the full `github:angular/bower-angular@1.3.15` but to no avail an in fact, it must be having some success since replacing the dep with `'dfjadkjf'` gives a completely different (and clearer) error message.

What's going on? Is this a bug? Am I doing something wrong?

**Comment by MajorBreakfast** [comment]
`System.meta['github:nervgh/angular-file-upload@1.1.5']` seems strange. After `paths` is applied this becomes likely `jspm_packages/github/nervgh/angular-file-upload@1.1.5.js`. You likely meant to set the meta data for `github:nervgh/angular-file-upload@1.1.5/angular-file-upload` (The package's main module).

**Comment by togakangaroo** [comment]
Thanks that worked
