### ISSUE TITLE
Module Mocking Support

### ISSUE THREAD

**Issue by dchambers** [systemjs/systemjs#444]
I'm trying to move the [BRJS](https://github.com/BladeRunnerJS/brjs) implementation of CommonJS to SystemJS, but one of the features we need to be able to support is the ability to mock arbitrary modules within tests. We currently do this using a feature called [sub-realms](https://github.com/BladeRunnerJS/browser-modules#sub-realms), that allows us to replace certain modules for the duration of the test, but where all previously defined modules are re-created, in case they depended on any of the modules that are being mocked.

I'm currently trying to see if we can provide a similar features using the primitives made available within SystemJS at present. For example, I tried writing some code like this: 

```js
<script src="lib/system.src.js"></script>
<script>
System.register("foo", [], function(_export) {
	var __moduleName = "foo";
	
	function foo(str) {
		return str + '!';
	}
	return {
		setters: [function (m) {
		}],
		execute: function () {
			_export("default", foo);
		}
	};
});

function _bar(_export) {
	"use strict";

	var __moduleName = "bar";

	var foo;
	function bar() {
		return foo("foobar");
	}
	return {
		setters: [function (m) {
			foo = m.default;
		}],
		execute: function () {
			_export("bar", bar);
		}
	};
}

System.register("bar", ["foo"], _bar);

System.import('bar').then(function(module) {
	var bar = module.bar;
	console.log(bar()); // Note: displays 'foobar!'
	doFooReplacementTest();
});

function doFooReplacementTest() {
	// replace 'foo' and verify it's been replaced
	System.set('foo', System.newModule({default: function foo(str) {
		return str + '?';
	}}));
	
	System.import('foo').then(function(module) {
		var foo = module.default;
		console.log(foo('hello')); // Note: displays 'hello?'
	});
	
	
	// replace 'bar' and verify that it uses the new 'foo'
	System.set('bar', System.newModule(System.get('bar')));
	
	System.import('bar').then(function(module) {
		var bar = module.bar;
		console.log(bar()); // Note: displays 'foobar!' rather than 'foobar?' as desired
	});
}
</script>
```

but using `set()` doesn't cause dependent modules to have their bindings updated, even if I also use `delete()` or if I try to re-construct the module from scratch like this:

```js
System.set('bar', System.newModule({bar: System.get('bar').bar}));
```

Finally, even using `System.register` a second time like this has no effect:

```js
System.register('bar', ['foo'], _bar);
```

plus, if I `delete()` the module first before re-registering then I get this error:

```
GET http://localhost:8080/bar.js 404 (Not Found)f @ es6-module-loader.src.js:2602$__Object$defineProperty.value @ es6-module-loader.src.js:2777c @ es6-module-loader.src.js:377b @ es6-module-loader.src.js:365$__Object$defineProperty.value @ es6-module-loader.src.js:2776$__global.upgradeSystemLoader.loader.fetch @ system.src.js:739$__global.upgradeSystemLoader.loader.fetch @ system.src.js:1806$__global.upgradeSystemLoader.loader.fetch @ system.src.js:1921(anonymous function) @ es6-module-loader.src.js:1525O @ es6-module-loader.src.js:1183K @ es6-module-loader.src.js:11427.y.when @ es6-module-loader.src.js:9307.v.run @ es6-module-loader.src.js:8213.a._drain @ es6-module-loader.src.js:973.a.drain @ es6-module-loader.src.js:62b @ es6-module-loader.src.js:268
es6-module-loader.src.js:140Potentially unhandled rejection [3] Error loading "bar" at http://localhost:8080/bar.js
Not Found: http://localhost:8080/bar.js (WARNING: non-Error used)
```

So ..., what are my options here, or is this something that is intentionally not allowed. Or, would I be better of using the branch of SystemJS (can't find it at the mo though!) that is tracking the new [whatwg loader spec](https://github.com/whatwg/loader)?

Thanks in advance, Dominic.

**Comment by matthewp** [comment]
When you delete a module you need to delete all of its parents and then later re-import them (after you've set your mocked version). To do this you need to maintain your own reverse-lookup of modules to its parents so you know which to delete.  You can do this in normalize, I use this technique in a hot-swapping extension, you can use as a reference: https://github.com/stealjs/live-reload/blob/master/live.js#L120

**Comment by dchambers** [comment]
Hi @matthewp,

Thanks for providing this helpful information, and making me aware of StealJS, which I'll need to look into also.

I've taken a look at the source code, and AFAICT you are just invoking `delete()` on the module being reloaded, plus all of the modules that transitively depend on that module? Then, you are invoking `import()` on these same set of modules, so that they are reloaded from the server?

I've changed my example to try and do something similar, but where I'm re-invoking `register()` instead of `import()`, since the code is already on the client:

```js
function _foo(_export) {
	var __moduleName = 'foo';
	
	function foo(str) {
		return str + '!';
	}
	return {
		setters: [function (m) {
		}],
		execute: function () {
			_export('default', foo);
		}
	};
}

function _bar(_export) {
	'use strict';

	var __moduleName = 'bar';

	var foo;
	function bar() {
		return foo('foobar');
	}
	return {
		setters: [function (m) {
			foo = m.default;
		}],
		execute: function () {
			_export('bar', bar);
		}
	};
}

// Register modules for the first time
System.register('foo', [], _foo);
System.register('bar', ['foo'], _bar);

// import 'bar'
System.import('bar').then(function(module) {
	console.log(module.bar());
	
	// delete all modules
	System.delete('foo');
	System.delete('bar');
	
	// Register exactly the same modules a subsequent time
	System.register('foo', [], _foo);
	System.register('bar', ['foo'], _bar);
	
	// import 'bar' again (ERROR!)
	System.import('bar').then(function(module) {
		console.log(module.bar());
	});
});
```

Unfortunately this fails on the second `import()` since SystemJS subsequently tries to retrieve the module from the server, rather than using the registered module. I'm guessing that this is now a separate bug; that SystemJS doesn't use locally held modules if these were ever deleted in the past?

**Comment by matthewp** [comment]
That's not a bug, when you delete a module it's gone.  If you want to re-execute the module without having them retrieved from the server you'll need to keep their source (probably in a hook on `instantiate`) and then use `System.define(name, source)` after you've deleted them.  Then when you re-import it will use that source and not go back to the server. Hope this helps.

**Comment by dchambers** [comment]
`System.define()`, right! I'd incorrectly assumed that I was reading out of date documentation (e.g. [here](https://gist.github.com/dherman/7568080)) and that that was just the old name for `System.register()`!

So, the `source` parameter that this method requires is the transpiled source code as a string rather than the `module` function used by `System.register()`? And, it's best to store this within the `instantiate` hook so I can be sure I have the transpiled source?

**Comment by matthewp** [comment]
I thought there was a form of System.register that allowed you to provide a source string but I cannot find the docs on that.  If that exists it would be safer to use than System.define which has a few issues.

**Comment by guybedford** [comment]
@dchambers thanks for the detailed investigations - to explain a few of the things you're noticing:

* Yes `System.set` does not update bindings - you need to manually delete and re-set all importing modules of the changed module as well. I did try and discuss at some length in the spec issue queue if we could look to support such a feature at https://github.com/whatwg/loader/issues/30, but in the end it doesn't really make sense.
* The next issue you're hitting here when using `System.delete` is that the `System.register` implementation in SystemJS does not currently support being run multiple times. I've added an adjustment in https://github.com/systemjs/systemjs/commit/23dfb22aa7ea87c4d941b1bcd67a5ad3946d43a1 to make this possible. The workaround would be to run `delete System.defined['foo']` as well as `System.delete('foo')`.

Let me know if that workaround helps.

**Comment by dchambers** [comment]
Hi @guybedford,

Thanks so much for providing 23dfb22 to hopefully make this do-able &mdash; having to use `System.register()` the first time, but `System.define()` subsequently sounded awkward. I'll give this a try on Monday and let you know how it worked for me.

**Comment by dchambers** [comment]
Okay, I've finally had a chance to look at this again, and I can confirm that @guybedford's patch (23dfb22) in combination with @matthewp's recommendation (to delete and re-create all modules that transitively depend on the module being replaced) works, and allows me to do exactly what I want.

Thanks everyone :+1:

**Comment by guybedford** [comment]
@dchambers thanks for the follow-up. Note I actually had to alter the solution in https://github.com/systemjs/systemjs/commit/e2b9440ec5fea93fe267a699ccb41b2675ce9f2f today as there was a reason we needed the registered module to be a constant, but it should still work fine as a fix in your examples.

**Comment by dchambers** [comment]
Yep, e2b9440 also works. Thanks again.

**Comment by mKoder** [comment]
@dchambers - could you please post an example of what the final solution for this testing method is? 

Thanks very much, I'm stuck with the same problem and cant quite seem to get it right

**Comment by dchambers** [comment]
Hi @mKoder, I'm really sorry for the snail-mail paced response. I was away on holiday when I received notification of your message, then managed to forget about it by the time I got back to work.

So far, I've created the following two repositories:

  * [sync-import](https://github.com/dchambers/sync-import) (working library with real code)
  * [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) (a design only at this point with no working code)

The [sync-import](https://github.com/dchambers/sync-import) import library has only been implemented so we could de-risk the idea and make sure it's do-able, but we probably won't need  [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) for a few more months yet, so this has been parked for the time being.

In addition to [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) I'm anticipating the need for another library with an easier to use API &mdash; [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) merely apes the SystemJS API since I'm not sure what the best mocking API will end up looking like.

Hope that helps...

**Comment by mKoder** [comment]
No problem, thanks very much for the info :)

On Mon, Sep 14, 2015 at 5:38 PM, Dominic Chambers <notifications@github.com>
wrote:

> Hi @mKoder <https://github.com/mKoder>, I'm really sorry for the
> snail-mail paced response. I was away on holiday when I received
> notification of your message, then managed to forget about it by the time I
> got back to work.
>
> So far, I've created the following two repositories:
>
>    - sync-import <https://github.com/dchambers/sync-import> (working
>    library with real code)
>    - MockableSystemJS <https://github.com/dchambers/MockableSystemJS> (a
>    design only at this point with no working code)
>
> The sync-import <https://github.com/dchambers/sync-import> import library
> has only been implemented so we could de-risk the idea and make sure it's
> do-able, but we probably won't need MockableSystemJS
> <https://github.com/dchambers/MockableSystemJS> for a few more months
> yet, so this has been parked for the time being.
>
> In addition to MockableSystemJS
> <https://github.com/dchambers/MockableSystemJS> I'm anticipating the need
> for another library with an easier to use API — MockableSystemJS
> <https://github.com/dchambers/MockableSystemJS> merely apes the SystemJS
> API since I'm not sure what the best mocking API will end up looking like.
>
> Hope that helps...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/systemjs/systemjs/issues/444#issuecomment-140138409>.
>



-- 
Regards

Edward Lynn
Developer / Director
DevHaus Creative
07951 697471
