### ISSUE TITLE
Keep RequireJS API on window?

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#445]
We are following the advice [in the wiki to add a RequireJS-like API](https://github.com/systemjs/systemjs/wiki/Module-Format-Support#requirejs-support):

``` js
window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;
```

This works well, but after executing some(?) modules, SystemJS appears to remove these from the window, breaking the API.

**Comment by guybedford** [comment]
Thanks I'll look to see where this might be happening.

**Comment by guybedford** [comment]
The only places in the code where we overwrite `require` or `define` are:

* https://github.com/systemjs/systemjs/blob/master/lib/extension-amd.js#L177
* https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L147
* https://github.com/systemjs/systemjs/blob/master/lib/extension-cjs.js#L82

In all the above cases we store the old value and revert it after execution.

Are you sure this isn't third-party code that you are loading that is altering these globals?

**Comment by OliverJAsh** [comment]
Hmm, when we load http://visuals.guim.co.uk/2015/05/results-interactive/1431098468790/main.js (bundled), `window.define` is `undefined` afterwards. Sorry that's not very helpful.

**Comment by guybedford** [comment]
@OliverJAsh I just tried running that and I get that `define` is undefined specifically while executing the bundle. That is by design when running modules as global modules - the AMD define will be removed for the initial execution to ensure it doesn't trigger any AMD detection paths in the code.

**Comment by OliverJAsh** [comment]
Can you share the LOC that does that specific work?

**Comment by guybedford** [comment]
That would be https://github.com/systemjs/systemjs/blob/master/lib/extension-global.js#L147. All defines in the bundle should be converted into System.register. If you want an AMD bundle, the module format needs to be set to AMD.

**Comment by OliverJAsh** [comment]
Got it, thanks!
