### ISSUE TITLE
Exceptions should point to source file rather than !eval version

### ISSUE THREAD

**Issue by edrex** [systemjs/systemjs#448]
If I throw an exception in a module (es6, babel transpiler):

```
throw new Error("Something bad happened.")
```

I see something like this in the chrome console:

```
Potentially unhandled rejection [2] Error: Something bad happened.
    at System.register.execute (http://localhost:3000/app/main.js!eval:10:13)
    at g (https://jspm.io/es6-module-loader@0.16.5.js:1:20468)
    at w (https://jspm.io/es6-module-loader@0.16.5.js:1:20850)
    ...
```

Ideally these traces would use source maps to show the source file line number: http://localhost:3000/app/main.js:3:13.

Is there a current issue to track this gap? Is there some detail of my configuration which is preventing it from working? I understand that source maps are really tricky and support for them is spotty and full of caveats, so assuming that it's just not viable to support right now. Thanks!

**Comment by guybedford** [comment]
This is tracked in https://github.com/ModuleLoader/es6-module-loader/issues/293, and is a quirk of source maps - we want the `sourceURL` to be the correct file, but then the source map has to give the original ES6 source a different name hence the !eval bit. I'm not sure what the suggested way around this this is in browsers - ideas and suggestions (and testing) welcome. Feel free to continue discussion there.
