### ISSUE TITLE
Executing SFX bundle on a page that already has System

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#449]
When executing SFX bundle on a page that already has System, `window.System` is overridden.

Could the SFX bundle check for the existence of `window.System` and only set it if it does not already exist?

/cc @mattosborn

**Comment by guybedford** [comment]
@OliverJAsh SFX don't touch `window.System` at all, and only use a locally scoped System variable. Perhaps you can share the sfx bundle for me to try it here?

**Comment by OliverJAsh** [comment]
Here is the SFX bundle http://visuals.guim.co.uk/2015/05/results-interactive/main.js

**Comment by guybedford** [comment]
The System defined there is not the SFX system. This may be from Traceur runtime. Note I've created an issue asking Traceur not to clobber System in https://github.com/google/traceur-compiler/issues/1911.

**Comment by guybedford** [comment]
I've created https://github.com/systemjs/builder/issues/169, I think that might be the issue.

**Comment by OliverJAsh** [comment]
It looks like SystemJS:

``` js
Object.keys(System)
// => ["register", "registerModule", "get", "set", "normalize"]
```

**Comment by guybedford** [comment]
Traceur creates its own version of System. We don't define a `registerModule` method.

**Comment by guybedford** [comment]
Tracking at https://github.com/systemjs/builder/issues/169.
