### ISSUE TITLE
Error when trying to import react component

### ISSUE THREAD

**Issue by omerts** [systemjs/systemjs#453]
Hello,

When trying to load react component I get the following error:
```
Potentially unhandled rejection [3] Error: Error loading "react" at file: path/to/src/react.js
Error loading "react" from "client/pages/todos.react" at file: path/to/src/client/pages/todos.react.js
ENOENT, open 'path\to\src\react.js'
```

**Comment by guybedford** [comment]
@omerts you need to ensure you have React installed into your application at a name that can be loaded. Have you located react into your project?

**Comment by omerts** [comment]
@guybedford  Thanks for the reply.
I am using react all throughout the app, and it was working, when switching to systemjs, I began encountering the above error.

**Comment by guybedford** [comment]
@omerts your first step will be to get `System.import('react')` to work then - ensure you can get that to resolve to the correct file and format, and then start loading the components after that.

**Comment by omerts** [comment]
@guybedford Thanks for your help, the error was because I didn't add react to the System.paths. Sorry for the newbie error, I am new to systemjs.
