### ISSUE TITLE
Plugin parent module argument

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#455]
Perhaps a last argument to the plugin can be the parent plugin module itself.

This would allow parent helpers to be passed to the child resource.

**Comment by guybedford** [comment]
@geelen would be good to discuss this API further to implement something here.

**Comment by geelen** [comment]
What do you mean "argument to the plugin"? I'm currently having a problem where *I wish* I could pass arguments to plugins, and I didn't think it was possible :)

**Comment by guybedford** [comment]
Sorry will clarify!

```javascript
export function fetch(load, fetch, plugin) {
}
```

Adding the plugin as an argument itself to maintain a reference when extending plugins. Although maybe we just need to work on ensuring the class extension for plugins can work properly. 

I guess my point is simply - I think we can improve this API, and think we should chat about it again...!

As for arguments to plugins, metadata is a good option for this, have you tried using that?

Again, this is probably something we should optimize the experience around - is it `System.config({ meta: { 'plugin/path': {...} } })` or `System.config({ meta: { 'plugin/path!plugin': {...} } })`?

**Comment by guybedford** [comment]
I'm wondering if we should just ensure the meta should work via:

```javascript
System.config({
  meta: {
    'plugin/path': {...}
  }
});
```

Even when loading arbitrary `plugin/path!plugin`.

**Comment by guybedford** [comment]
Doesn't seem like this is needed for now.
