### ISSUE TITLE
`import "./foo"` loads installed package even if "./foo.js" exists

### ISSUE THREAD

**Issue by hgl** [systemjs/systemjs#456]
```js
import "./foo";
```

This seems to favor installed `foo` over `./foo.js` file.

**Comment by guybedford** [comment]
@hgl if `bar.js` is in the baseURL, then I understand this happening, but do you mean this is even if the file doing the importing is within a subfolder?

**Comment by hgl** [comment]
No, in my case the importing file is in the `baseURL` as you said. So this is planned? Why would that be the case since `./` exists to denote a file and not a package?

**Comment by guybedford** [comment]
It is by design in the current version. This is actually one of the changes made in the upcoming version of SystemJS to behave like you'd expect though.

**Comment by guybedford** [comment]
(although it still needs to go through a deprecation phase first unfortunately for backwards compat, so is effectively two majors away)

**Comment by hgl** [comment]
Great. Thanks for the heads up. I will close this.
