### ISSUE TITLE
System.register not used as export

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#458]
``` js
System.normalize = function interactives(name) {
    var regExp = /(^http[s]?:\/\/)(.*)/.exec(name);
    if (regExp) {
        return 'interactive/' + regExp[2] + '.js';
    } else {
        return name;
    }
};
System.paths['interactive/*'] = '//*';
System.import('http://visuals.guim.co.uk/2015/05/results-interactive-test/1432207400012/main').then(function(main) {
    console.log(main);
    // => {}
});
```

The imported module contains a `System.register('main', …)`, but the export is an empty object. Why is this?

**Comment by guybedford** [comment]
This is because that is a named module - `main`, which is effectively a bundle at this point.

Only if the name in SystemJS entirely matches the name in the bundle will it give you the right object (`System.paths['main'] = '...'; System.import('main'`).

This is still not advisable though - just use anonymous System.register that doesn't give a name and load it as an anonymous module for portability.

**Comment by OliverJAsh** [comment]
> This is still not advisable though - just use anonymous System.register that doesn't give a name and load it as an anonymous module for portability.

How would you do that?

**Comment by guybedford** [comment]
`System.register([], function() { ... }` with no name. There's an option when creating a compile in Babel or Traceur to leave out the module name.

**Comment by guybedford** [comment]
Note that you can only have a single definition in a file then though.

Just let me know if you need further help at all.

**Comment by OliverJAsh** [comment]
> This is still not advisable though - just use anonymous System.register that doesn't give a name and load it as an anonymous module for portability.

How can you make this behaviour the default for bundle?

**Comment by OliverJAsh** [comment]
> There's an option when creating a compile in Babel or Traceur to leave out the module name.

Is this possible to configure via `jspm bundle`?

**Comment by guybedford** [comment]
`jspm bundle` is only for bundles. Bundle config is designed exactly for this use case:

```javascript
System.bundles['http://visuals.guim.co.uk/2015/05/results-interactive-test/1432207400012/main'] = ['main', ...];
```

**Comment by guybedford** [comment]
If you have more than one `System.register` call then it is a bundle and not an anonymous module, and my point about removing the name doesn't apply.

**Comment by OliverJAsh** [comment]
OK thanks.
