### ISSUE TITLE
System.clone and async System.register

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#460]
When cloning System, we're having to temporarily swap the variable at `window.System` to use the cloned loader, so that any asynchronous `System.register` calls will be called against the cloned loader and not the original.

``` js
var originalSystem = window.System;
var newSystem = originalSystem.clone();
newSystem.baseURL = '/foo';
window.System = newSystem;
System.import('main').then(function () {
    window.System = originalSystem;
});
```

This could cause problems. What if other `System.register`s occur before the correct loader is restored?

**Comment by guybedford** [comment]
@OliverJAsh I preemptively created https://github.com/systemjs/systemjs/pull/459 for this when you posted the first one, but still not sure how this aligns with the spec so weary of promising that contract.

**Comment by guybedford** [comment]
Merged and fixed in https://github.com/systemjs/systemjs/commit/e5644a7d14e12b7730199fca9be31d4c4a7e8c52.

**Comment by OliverJAsh** [comment]
Cheers! :smile:

**Comment by guybedford** [comment]
Note System.clone has been deprecated for standard class extension. See https://github.com/systemjs/builder/blob/master/lib/builder.js#L61 for an example.
