### ISSUE TITLE
AMD env breaks node env detection

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#461]
I have the following code:

``` js
// Setup AMD env
window.require = System.amdRequire.bind(System);
window.define = System.amdDefine.bind(System);
var newSystem = System.clone();
```

When I try to import something that depends on [`jspm/nodelibs-process`](https://github.com/jspm/nodelibs-process/blob/2dd9498d7e5ce134e4ff9dd41319cda4e31f993c/index.js#L1) using `newSystem`, I get an error:

```
process is not defined
```

I believe this is due to this line: https://github.com/systemjs/systemjs/blob/749c7c86c69b99ae8be83bb7a6878e50c276fbf8/dist/system.src.js#L2463.

Could we use a better heuristic for detecting node envs?

**Comment by guybedford** [comment]
Any suggestions what might be a better way here? We need to get access to the underlying CommonJS  `require` regardless though.

**Comment by guybedford** [comment]
Also what environment are you running to have both `window` and Node?

**Comment by OliverJAsh** [comment]
`var isNode = !! global.process`

?

**Comment by guybedford** [comment]
It's not just `isNode`, it's specifically knowing the global require.

**Comment by OliverJAsh** [comment]
I'm just running in the browser, but System's Node detection just looks for `window.require`, which I am setting.

**Comment by guybedford** [comment]
Ahh right I see - yes we can fix that with a better Node check.

**Comment by guybedford** [comment]
Sure, I've added https://github.com/systemjs/systemjs/commit/71c5bdc39f475a60e8dd166e7a5700c6c65b07a0.

**Comment by OliverJAsh** [comment]
Thanks!

**Comment by OliverJAsh** [comment]
When testing jspm@0.16.0-beta, I'm seeing network error messages for `process` now:

![image](https://cloud.githubusercontent.com/assets/921609/8033365/ba0c05ba-0dd5-11e5-85ff-1a676fc2e708.png)

**Comment by guybedford** [comment]
Is the `System._nodeRequire` not set now though? So is it then unrelated to that?

**Comment by OliverJAsh** [comment]
Yes, it must be unrelated.

**Comment by guybedford** [comment]
So nodelibs-process is supposed to depend on npm:process so that `require('process')` within nodelibs-process directs to that. Can you see this set up in the map configuration?

**Comment by OliverJAsh** [comment]
I can see that:

``` json
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
```

Not sure what else is requesting process.

**Comment by OliverJAsh** [comment]
`jspm install npm:lodash@~2.4.1` wraps the Lodash files in:

``` js
/* */ 
"format cjs";
(function(process) {
// …
})(require("process"));
```

`process` is not actually used anywhere inside of Lodash—how come jspm is doing this?

Whatsmore, `process` is not defined in the System config as a dependency for Lodash.

**Comment by guybedford** [comment]
Yes the wrapping is unavoidable pending https://github.com/jspm/npm/issues/55 unfortunately.

There must be another bug interaction that is stopping process from working though.

Can you share your value of `System.packages` from the environment? It's just debugging at this point - is there anyway you can share a test case?

**Comment by OliverJAsh** [comment]
I have managed to isolate the bug: https://github.com/systemjs/systemjs/issues/514
