### ISSUE TITLE
IE10 & 11 issue bringing down system.js

### ISSUE THREAD

**Issue by wesleycho** [systemjs/systemjs#463]
I am observing an issue where IE10 & 11 are broken at [this line](https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L1333) - the error is `Object doesn't support this action`.

**Comment by guybedford** [comment]
Thanks for posting, yes the master branch has yet to undergo IE testing.

**Comment by robwormald** [comment]
looks like it's the `new URL(...` call throwing in all versions of IE.

**Comment by lucasstrange** [comment]
If you use system.dev.js and change this line it will work in IE.  The native URL object does not match the expected signature.

            //var URL = __global.URL || URLPolyfill;
            var URL =  URLPolyfill;

**Comment by lstefano71** [comment]
To support both Chrome and IE:
```
  //var URL = __global.URL || URLPolyfill;
  var URL;
	try {
		URL = URLPolyfill;
	} catch(e) {
		URL = __global.URL;
	};
```

I know it's horrendous but it gets the job done while waiting for a proper fix.

**Comment by SerkanSipahi** [comment]
@lstefano71 its doesnt work in IE10. What im doing wrong? Nothing changed. The same error is displayed:

```error
Object doesnt support this action
```

**Comment by SerkanSipahi** [comment]
i believe i need systemjs/dist/system-polyfills.src.js! will check this out

**Comment by SerkanSipahi** [comment]
Thanks, its works but now i geht an another error:

@lstefano71 @guybedford @lucasstrange 
Object doesnt support property or method 'Register' line https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L1984

Whats going wrong here?

**Comment by guybedford** [comment]
@SerkanSipahi it sounds like you are running the unreleased version of SystemJS on master, which is still being environment tested. I'd suggest using the version from 0.16.11 at https://github.com/systemjs/systemjs/tree/0.16.11.

**Comment by SerkanSipahi** [comment]
@guybedford any release date from master there?

**Comment by SerkanSipahi** [comment]
@guybedford : `Object doesnt support property or method 'Register' line`,  come from our Application, it fixed :)

Feedback: systemjs#master, builder#master, moduleLoader#master works in Chrome, Firefox, Safari(7,8), Internet-Explorer(9,10,11) :)

**Comment by SerkanSipahi** [comment]
@guybedford Hello again :) do you have any new release date? Please see ticket: https://github.com/babel/babel/issues/1660 , thank you.

**Comment by guybedford** [comment]
The new release is out - just let me know if you're still having issues here.

**Comment by SerkanSipahi** [comment]
@guybedford : thanks it works :)
