### ISSUE TITLE
Automatically assign cjs/amd module to global variable?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#465]
This is probably a really stupid question, but if I have some `cjs` module (e.g., https://github.com/feross/buffer) and I want to assign it to the global (window) `Buffer` variable, how do I do this without explicitly setting `window.Buffer`?  Is there a way to tell SystemJS to automatically assign the `cjs` module to a global variable without setting the `globals` or `deps` metadata on every other module that depends on it?  Surely there's a quick and easy way to do this that I just haven't found.  I saw `scriptLoad` mentioned somewhere but couldn't really find anything on it.

**Comment by guybedford** [comment]
@timbur it sounds like you're wanting to create CommonJS compatibility? The npm endpoint does this automatically when you install something from npm.

Shimming globals to module values is a feature coming in the upcoming SystemJS release though.

**Comment by timbur** [comment]
Dang.  Everything I need is in the next release.  XD

I did actually install `buffer` through npm using `jspm install npm:buffer` but there are `require` statements in the main file that result in an error when I make force the `global` format on the `buffer` module.

Is there a shortcut to basically tell SystemJS to do this (but asynchronously along with whatever other modules are loading within the same scope)?
```js
System.import('buffer').then(function (Buffer) {
  window.Buffer = Buffer;
});
```

**Comment by guybedford** [comment]
@timbur if you want to run on edge SystemJS you can try that here - `jspm dl-loader --edge`. Then in your configuration you can add `System.config({ meta: { 'some/module': { globals: { 'Buffer': 'npm:buffer' } } } });`

**Comment by timbur** [comment]
> edge SystemJS

Hmm... I just tried it and it didn't load my main module.

> System.config({ meta: { 'some/module': { globals: { 'Buffer': 'npm:buffer' } } } });

Just out of curiosity, how will this work for production builds?

**Comment by timbur** [comment]
For now I suppose I can bundle the `buffer` module manually and assign it to `window` before anything else loads.

**Comment by guybedford** [comment]
The latest release is out, if you need further help with this just let me know.
