### ISSUE TITLE
Conformity with WHATWG Loader specification 

### ISSUE THREAD

**Issue by 39dotyt** [systemjs/systemjs#466]
Does this module conforms with WHATWG loader specification? I think, this should be mention in the README.

**Comment by guybedford** [comment]
This is described in the readme at https://github.com/ModuleLoader/es6-module-loader:

> This project implements dynamic module loading through System exactly to the previous ES6-specified loader API at 2014-08-24 ES6 Specification Draft Rev 27, Section 15. The new loader implementing the WhatWG loader spec is pending alpha release on the 1.0 branch.

We'll be switching to the WhatWG branch as soon as enough details are confirmed.

**Comment by 39dotyt** [comment]
@guybedford, it's about es6-module-loader, not about Systemjs. Am I mistaken?

**Comment by guybedford** [comment]
SystemJS is built on top of es6-module-loader.

**Comment by 39dotyt** [comment]
Okay. Thank you. This makes sense.
