### ISSUE TITLE
Unable to load plugins if absolute path

### ISSUE THREAD

**Issue by schinckel** [systemjs/systemjs#467]
I'm serving all CSS+JS under `/static/`, including SystemJS plugins.

When I attempt to load a plugin, I am informed that this is an `illegal module name`.

I've tracked it down to the `SystemLoader.prototype.normalize`, which rejects those with a leading slash.

I'm not exactly sure how to load a plugin with it this way.

**Comment by guybedford** [comment]
SystemJS is currently based on the `baseURL` concept that all modules must existing as subpaths to a single baseURL. As such, arbitrary URLs cannot be requested - rather you should use a lower baseURL.

The next release coming soon will allow arbitrary URLs though, with a new concept of package existing as exceptions within the URL space.

**Comment by schinckel** [comment]
Hi Guy. Thanks for the response.

I'm using Django, and using the normal static files handling process there. It's built with the facility to have static files anywhere, and automatically generates the paths correctly: including if they are on a different server. It also means I can't use a lower baseURL, as that value is not necessarily known at the time the template is written, only rendered.

As it turns out, it's possible to override System.normalize (and is indeed documented).

      var STATIC_ROOT = new RegExp('^{% static "" %}');
      var systemNormalize = System.normalize;
      System.normalize = function(name, parentName, parentAddress) {
        if (name.match(STATIC_ROOT)) {
          return name;
        }
        return systemNormalize.call(this, name, parentName, parentAddress);
      }
