### ISSUE TITLE
System.delete throws "loader is not defined"

### ISSUE THREAD

**Issue by geelen** [systemjs/systemjs#468]
For `jspm-server`, I delete modules to force a reload. This is throwing an error for my project, here's the info:

![image](https://cloud.githubusercontent.com/assets/23264/7806866/36fffc96-03c9-11e5-8d7d-6425433ebf4b.png)
![image](https://cloud.githubusercontent.com/assets/23264/7806869/3f1bc2f2-03c9-11e5-994b-b93309f17ad3.png)

**Comment by guybedford** [comment]
Thanks - this should be fixed in https://github.com/systemjs/systemjs/commit/d99facc2e7313767381e797a4eea6bc2b5012c0e now.
