### ISSUE TITLE
Synchronous import or synchronous instantiation of pre-registered modules?

### ISSUE THREAD

**Issue by dchambers** [systemjs/systemjs#469]
Hi, I'd like to know whether there is a way to get SystemJS to synchronously instantiate modules I've registered with `System.register()`? I've seen two issues related to synchronous import (#191 & #261) were created in the past, but in both cases the reporters found ways to work around there issues that I'm not sure are available to us, hence why I've created a new issue.

Doing this would make it possible for code external to a bundle to synchronously `require()` (or `System.get()`) the modules it needed. This wouldn't be such a big deal if it weren't for the fact that we're looking to [convert BRJS to use SystemJS](https://github.com/BladeRunnerJS/brjs/issues/1389), yet BRJS has a large number of apps that depend on it, and so backwards compatibility is critically important.

Without something like this, we'd end up with with the following problems:

  1. Code within script tags (within aspect and workbench pages) that isn't part of the bundle, would cease to work since `require()` invocations and global references would no longer work.
  2. Tests within BRJS aren't currently bundled either, and so all tests would fail since `require()` invocations and global references would no longer work (we could possibly work around this one, though it wouldn't be easy given the nature of [js-test-driver](https://code.google.com/p/js-test-driver/)).
  3. Even if tests were bundled, our plan to use [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) for mocking relies on us being able to re-register modules dynamically, yet this would again mean that we would subsequently need to asynchronously import modules, but this would require people to convert their synchronous tests to asynchronous tests, which  would be a huge undertaking, and would lead to slower, less reliable, more complex tests.

These problems could be solved if there was a synchronous way to load all modules, for example:

```js
System.instantiateRegisteredModules();
```

or alternatively, there could be a method that we could repeatedly invoke for each pre-registered module, for example:

```js
// this would throw if the module had not been pre-registered
System.instantiate('the-module');
```

Any ideas would be much appreciated, and if need be we could look at forking SystemJS with your guidance?

**Comment by guybedford** [comment]
@dchambers I'd strongly suggest using a `System.set` / `System.delete` etc style test API here along with the tracing system if you need something synchronous. Module loading itself is always an asynchronous operation, even subsets of it like using System.register.

**Comment by dchambers** [comment]
Hi @guybedford, I did try experimenting with a `System.set` / `System.delete` approach at the beginning, but couldn't get it to work as the thing being set is the exported module, which means that I would need to store the actual module that was registered via `System.register()`, then pass a `require`, `exports` and `module` into to it so I can get a new module with updated dependencies, which in turn would require that I create the dependencies in the right order so that everything hooks up correctly, at which point I've re-written SystemJS :-)

**Comment by dchambers** [comment]
Of course, the live binding feature you previously mentioned (whatwg/loader#30) would have made it possible for a `System.set` / `System.delete` approach to work without the need to replicate parts of what SystemJS already does. Perhaps though, replicating just the module bootstrapping part of the code is not too difficult? Is it just a question of repeatedly iterating for modules whose dependencies have been met until all modules have been created, or will there be lots of other gotchas (like zebra striping?) for which SystemJS already has the smarts in-built?

**Comment by guybedford** [comment]
@dchambers you're right, that update feature I suggested would have helped here. Best to move on though as that was very much not a possibility in the spec.

So unfortunately yes you would need to rebuild these elements of the pipeline synchronously to achieve what you're after. The pieces here are basically the register extension in SystemJS - https://github.com/systemjs/systemjs/blob/master/lib/register.js which has also been extracted out into https://github.com/systemjs/builder/blob/master/templates/sfx-core.js.

It ends up being quite common to reuse this code in lots of places - so I'm tempted to see at some point if we can abstract it better into some kind of core pipeline API, but for now I just don't have the time to work on such a thing unfortunately

**Comment by guybedford** [comment]
The only possible (and terribly bad) workaround I can think of would be to override the Promise implementation in SystemJS (the master version uses environment promises making it possible to override), to provide a synchronous `Promise.resolve()`, and then immediately revert the promise implementation synchronously not to pollute the environment.

**Comment by dchambers** [comment]
Funny that you should mention that as that's exactly what I've been trying so far this morning. Although bad from a hacky point of view, when contrasted with the benefits that moving to SystemJS is going to give us then I think it's more than justified.

**Comment by dchambers** [comment]
> So unfortunately yes you would need to rebuild these elements of the pipeline synchronously to achieve what you're after. The pieces here are basically the register extension in SystemJS - https://github.com/systemjs/systemjs/blob/master/lib/register.js which has also been extracted out into https://github.com/systemjs/builder/blob/master/templates/sfx-core.js.

Okay, this is really good to know. I'm going to go with the _bad_hack first, as even this will be acceptable to us, then look at looping back later to fix the technical debt I'm planning to introduce now...

**Comment by dchambers** [comment]
@guybedford, the _terrible hack_ works! I had to hack [Bluebird](https://github.com/petkaantonov/bluebird) to get it to work even though they supposedly support [synchronous-inspection](https://github.com/petkaantonov/bluebird/blob/master/API.md#synchronous-inspection), but will also [re-try broody-promises](https://github.com/gobwas/broody-promises/issues/1), a library designed specifically with this one goal in mind, once I get back from lunch...

**Comment by dchambers** [comment]
Okay, in case anybody else needs to do this in the future, I paired these scripts:

  1. [bluebird.js](https://cdn.jsdelivr.net/bluebird/latest/bluebird.js)
  1. [es6-module-loader-sans-promises.js](https://github.com/ModuleLoader/es6-module-loader/blob/v0.16.6/dist/es6-module-loader-sans-promises.src.js)
  1. [system.js](https://github.com/systemjs/systemjs/blob/0.16.11/dist/system.src.js)

with the following function loaded at the end:

```js
System.syncImport = function(name) {
	var scheduledFuncs = [];
	var origScheduler = Promise.setScheduler(function(fn) {
		scheduledFuncs.push(fn);
	});
	
	try {
		var promise = this.import(name);
		
		for(var fn of scheduledFuncs) {
			fn();
		}
		
		var value = promise.value();
	}
	finally {
		Promise.setScheduler(origScheduler);
	}
	
	return value;
};
```

and was then able to write code like this:

```js
var myModule = System.syncImport('my-module');
```

Just to be clear, this only works in my case because all of the modules I need have been pre-bundled.

**Comment by matthewp** [comment]
Cool, why not package that up as an extension?

**Comment by dchambers** [comment]
Yeah, that probably makes sense, especially given that [MockableSystemJS](https://github.com/dchambers/MockableSystemJS) is going to need something like `syncImport()` to make it workable. I think I'll leave for a bit though in case I invest the time to do this in a cleaner way in the meantime.

**Comment by matthewp** [comment]
There was some discussion about making imports synchronous in Node, this could be useful for that.

**Comment by dchambers** [comment]
@matthewp, are you able to provide a link please? This isn't something I have any knowledge of.

**Comment by guybedford** [comment]
Please take such terrible discussions elsewhere :)
