### ISSUE TITLE
writing a handlebars plugin and then a wild React appears

### ISSUE THREAD

**Issue by davis** [systemjs/systemjs#470]
here is my plug:

`hbs.js`
```javascript
'use strict';
export function translate(load) {
  return `import h from 'handlebars'\n\nexport default h.compile(${load.source})`;
}
```

then i get the following error:
![screen shot 2015-05-27 at 7 08 55 pm](https://cloud.githubusercontent.com/assets/4855619/7851392/d87b9dde-04a3-11e5-88b9-e56758deb08b.png)

![screen shot 2015-05-27 at 7 09 28 pm](https://cloud.githubusercontent.com/assets/4855619/7851397/ec81c4fc-04a3-11e5-8e0c-7729c4e80e08.png)

my project does not use React. why does it appear here?

**Comment by davis** [comment]
i got my plug in working with the following code

```javascript
'use strict';

export function translate(load) {
  return `import Handlebars from 'handlebars';

export default Handlebars.compile('${load.source}')`;
}
```

i'm still wondering where React came from

**Comment by guybedford** [comment]
This is likely due to inadvertently triggering JSX syntax.

**Comment by guybedford** [comment]
It sounds like you need to look at your string escaping here.

**Comment by guybedford** [comment]
Just let me know if you need help with this.

**Comment by davis** [comment]
In jspm@beta (0.16.0) i am running into React again

plugin code:
```
export function translate(load) {
  load.source = "export default 'hello';";
}
```

![screen shot 2015-06-05 at 1 58 37 pm](https://cloud.githubusercontent.com/assets/4855619/8015130/fc95cd82-0b8a-11e5-9a5a-9ab98cfdae65.png)

**Comment by davis** [comment]
changed my plugin code to 
```
export function translate(load) {
  load.source = "module.exports = 'hello';";
}
```

and now it works :(
