### ISSUE TITLE
Loading dependencies using relative paths

### ISSUE THREAD

**Issue by niemyjski** [systemjs/systemjs#473]
First, I must say that my example is for local purposes only...

I have an example folder for one of my js projects and I wanted to load my module from the dist folder but I haven't been able to make this happen without copying it locally..

folder structure is something like this: `/dist/exceptionless.js` and `/example/systemjs/index.html`.
I tried creating a new source of `"local:*.js": "../../dist/*.js"` and doing `System.import("local:exceptionless");` without luck..

Is there a good way to accomplish this? I get that most people pull dependencies from npm / github.. But in my case I want the file to always be the local source because it's consumed for dev / testing / educational purposes.

Please note that I'm loading the `index.html` file directly into safari without a web server... I also get that you can't access resources outside of the root... but in this case I want to :hammer:

**Comment by guybedford** [comment]
I'd suggest setting the path to `/dist/*.js`.

Working on making paths a bit more intuitive for the coming release.

**Comment by niemyjski** [comment]
Thanks, I try that but I can't seem to load up a directory from my base path. Is this a known limitation?

**Comment by guybedford** [comment]
That should work, but if not I'd suggest setting the baseURL to `/` and then configuring paths as needed rather.

**Comment by guybedford** [comment]
(in the process of deprecating baseURL actually here)

**Comment by niemyjski** [comment]
I guess I'll have to put together a small sample for a test and send it your way as I can't get it to work.

**Comment by niemyjski** [comment]
pretty new to this (just picked it up today but it's been on my radar. If I get some time.. I'll try digging into it more).

**Comment by guybedford** [comment]
The point to note here is that paths targets are normalized relative the baseURL itself. So `../../` in your example above will be taken relative to `System.baseURL`.

**Comment by niemyjski** [comment]
yeah, this is not what I'm seeing over here. What I'm seeing is that it's eating the leading ../ parts of the path.. Could this be safari doing this?

**Comment by marcog83** [comment]
Hi,
i've updated to jspm and 'jspm dl-loader'
and when i refreshed the browser an error occurred.

Before updating, SystemJS worked. I think it was 0.12.
I read that there are some breaking changes in jspm 0.15, 
and I wondered how I can upgrate my code.

Just few info about project configuration, maybe i'm missing something.

baseURL is set as "/",
and config-dev.js is my entry point script

this is my console 
![error](https://cloud.githubusercontent.com/assets/4071265/7903027/b408a364-07cf-11e5-81d4-748632af2396.png)

here is my filesystem
![filesystem](https://cloud.githubusercontent.com/assets/4071265/7903028/d2fee5bc-07cf-11e5-9d0b-e58cce8114cd.png)


and this is how I import scripts in html page

![html](https://cloud.githubusercontent.com/assets/4071265/7903031/e4a788be-07cf-11e5-9970-0028b7295a6f.png)

thanks a lot
marco

**Comment by NathanielInman** [comment]
@marcog83 I had a similar issue and this is how I solved it.. it's likely not ideal though

I have a simple ES6 class that babel attempts to compile. It loads two helper modules, which call another module that requires a relative url '../core-js/object/define-property.js' and it the server returns a 404 because the file extension wasn't appended.

![screen shot 2015-06-02 at 12 25 10 pm](https://cloud.githubusercontent.com/assets/460990/7942235/7daa23a2-0922-11e5-86d2-db00ea3e5baa.png)

I was able to solve it by changing the normalize hook in system.js by adding +'.js' as below
![screen shot 2015-06-02 at 12 29 27 pm](https://cloud.githubusercontent.com/assets/460990/7942309/0ebae930-0923-11e5-85f3-4b6c395a0258.png)

**Comment by guybedford** [comment]
This issue is due to running jspm on master - use `npm install -g jspm` to run on stable and extensions should then be handled properly here.

**Comment by NathanielInman** [comment]
Running on stable fixed everything for me. Thanks!
