### ISSUE TITLE
Module is loading twice from different alias paths.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/systemjs#476]
Originally I thought this was an Aurelia issue so I posted over there https://github.com/aurelia/dependency-injection/issues/34.  However, I was told that this is actually a SystemJS issue.  Unfortunately, I don't understand Aurelia's dependency injection system or SystemJS's module loading system well enough to understand how to reproduce this in just SystemJS (without Aurelia).  Here is the original issue, please let me know if there is anything I can do to help narrow things down!

The `IMPORTANT` bit at the bottom is more SystemJS specific.

----

I have two view models and one service that is dependency injected into each of the models.

ModelA
```js
import { inject } from 'aurelia-dependency-injection';
import { Foo } from 'foo';
@inject(Foo)
export class ModelA {
	constructor(foo) {
		this.foo = foo;
	}
}
```
ModelB
```js
import { inject } from 'aurelia-dependency-injection';
import { Foo } from 'services/foo';
@inject(Foo)
export class ModelB {
	constructor(foo) {
		this.foo = foo;
	}
}
```
Foo
```js
export class Foo {
}
```

In this scenario, `ModelA` and `ModelB` will get different instances of `Foo`.  This is because they import from different paths.

***IMPORTANT***: Both paths resolve to the same location at runtime!  In `config.js` (for SystemJS) there are the following mappings:
```
"paths": {
	"*": "*.js",
}
"map": {
	"Foo": "services/Foo.js"
}
```

The expectation here would be that both models would get the same instance since they are reading the same class file off disk.

**Comment by matthewp** [comment]
You can think of map as like aliasing a module's name.  So what you really want is:

"map": {
  "foo": "services/foo"
}

This means that importing "foo" will give you "services/foo".

**Comment by Zoltu** [comment]
In my snippet, both (correctly) resolve to the same file on disk.  My expectation is that the module will be loaded only once, not twice, because it is the same file on disk.

For my immediate issue I have already worked around it by just having both imports look the same, but this was after a couple of hours of bashing my head against the wall trying to figure out what was going wrong.  This bug is to fix the problem for future users and me in 2 weeks when I forget about this bug.

I believe that it is *wrong* to load the same module twice since loading a module in JavaScript (I believe) can have side effects (as seen here).

**Comment by matthewp** [comment]
> My expectation is that the module will be loaded only once, not twice, because it is the same file on disk.

This expectation is wrong, modules are not files on disks, they are keys in a database.  Fixing your map (as I showed above) will make them resolve to the same key, and therefore only load once.

**Comment by guybedford** [comment]
@matthewp this is exactly the sort of reason for making URLs the primary unit of the registry.

**Comment by matthewp** [comment]
@guybedford Making URLs the primary unit of the registry doesn't change the fact that there are non-files in the registry.  It is just ignoring the elephant in the room.  The solution is that tooling should hide the need for maps for all but advanced usage.

Regardless, `foo` and `services/foo` should not resolve to the same url.  If they are it's because something else is going on that's not shown in this example.

**Comment by Zoltu** [comment]
In my naivete I cleaned up my `System.config` call a bit to simplify it.  Perhaps I oversimplified it since I was operating under incorrect assumptions:

```js
System.config({
	"paths": {
		"*": "output/*.js",
		"local-services:*": "output/services/*.js"
	},
	"map": {
		"OAuth": "local-services:OAuth"
	}
});
```

The following two imports resolve to different modules.
```
import { OAuth1 } from 'OAuth';
import { OAuth2 } from 'services/OAuth';
```

**Comment by Zoltu** [comment]
Note: the reason I am not using 'OAuth' everywhere is because TypeScript doesn't support any kind of file mapping yet https://github.com/Microsoft/TypeScript/issues/2338.  Once TypeScript supports a mapping similar to SystemJS (fingers crossed) then I believe the right answer for *me* is to use `import from 'OAuth'` everywhere.

----

Am I correct in understanding that the keys into the database that you referred to @matthewp in my example are `OAuth` and `services/OAuth` because those are the imports I have?  Or are the keys in the database `OAuth` and `local-services:OAuth`, indicating that the map is just a way to alias one key to another?

**Comment by guybedford** [comment]
@Zoltu the way to check this is to check `Object.keys(System._loader.modules)` and see if `Foo` is represented twice. It should then be clear how it has been named separately.

**Comment by guybedford** [comment]
Let me know if you still have any more questions here.
