### ISSUE TITLE
Issue with loading none TypeScript modules from a TypeScript module

### ISSUE THREAD

**Issue by subesokun** [systemjs/systemjs#477]
While playing around with TypeScript I came across a tricky use-case (using `plugin-typescript` from @frankwallis)

```typescript
/* lib/main.ts */
/// <reference path="../typings/somemod/somemod.d.ts" />
import 'somemod/somemod';
```
```typescript
/* typings/somemod/somemod.d.ts */
declare module "somemod/somemod" { }
```
Normally everything would work as expected in case the `somemod` package contains a file named `somemod.ts` but in case the module ships e.g. only transpiled cjs files you run into the issue that `import 'somemod/somemod'` should load the file `somemod.js` instead of the `somemod.ts` file.

Just writing `import 'somemod'` would solve that issue as then somehow the cjs loader gets used instead of the typescript loader but then the TS compiler will throw an error as it can't find the external module definition for `somemod` :( Writing `import 'somemod/somemod.js'` won't work either as this will also raise the same TS compiler error. Sadly the definition file is not under my control so I can't change it to `declare module "somemod"`.

What confuses me a little bit is that `import 'somemod'` will use the cjs loader but `import 'somemod/somemod'` will use the typescript loader to fetch the file.

Any ideas? Maybe this issue is somewhat related to #319

(using SystemJS that comes along with jspm@0.15.6)

**Comment by guybedford** [comment]
I must admit I haven't been following the TypeScript support that closely. Does this gets easier when extensions are not assumed? Perhaps it is worth discussing with @frankwallis?

**Comment by frankwallis** [comment]
This is a known limitation in plugin-typescript, see https://github.com/frankwallis/plugin-typescript/blob/master/lib/fix-requires.js#L39

It should get fixed very soon, but until then you will need to workaround it by using ```import 'somemod/somemod.js'``` and ```declare module 'somemod/somemod.js'```.

**Comment by subesokun** [comment]
@frankwallis, thanks for the pointer. Looking forward to the fix. 

Something that makes me wonder is why `import 'somemod'` correctly uses the cjs loader but `import 'somemod/somemod'` will use the ts loader. I'm not so deep into this topic but maybe it'd help that in case a require is not relative and no extension is present, that by default the loader associated with the package gets used. So if `somemod` defines as `format: 'cjs'` and you try to import `somemod/somemod` it should call the cjs loader over the ts loader. Then this loader could decide whether to append a `.js` extension or a different one. But in the end this would also mean that each loader has to define it's own format... like `format: 'ts'`. Not sure if that would have negative consequences or gives `format` a different semantic though.

**Comment by subesokun** [comment]
Just read about this new [plugin loaders](https://github.com/systemjs/systemjs/blob/0.17.0/docs/overview.md#basic-use) shipping with SystemJS 0.17.0. Could a `package.json` contain also this `meta` property so that you can define `meta: { '*': { loader: 'ts' }}` that by default all files from that package are getting loaded via the `ts` loader?

**Comment by guybedford** [comment]
@subesokun note that CommonJS is not a loader in SystemJS. It's a module format - which means it is either detected automatically from the source after the loader has done translation, or via metadata on the load record itself. So having TypeScript working as CommonJS requires the same detection rules as CommonJS normally.

For the loader metadata option, yes this is in the new release, but the ".js" extensions are still added automatically for the time being unfortunately.

**Comment by subesokun** [comment]
Ok, I think for now it'll be best to wait for the fix from @frankwallis and see if it solves my issue. Thanks for the clarification regarding the module format, I had there some misunderstandings.
