### ISSUE TITLE
Make System.register lazy

### ISSUE THREAD

**Issue by MajorBreakfast** [systemjs/systemjs#479]
In my app there are modules that are needed both in the worker and the main thread. Currently I can't create a shared bundle that contains all files. It's because all functions provided to the `System.register()`s are called, not just the ones for modules that are actually needed. Some of my modules can't run inside a worker (e.g. modules that need `document`) and the consequently crash.

So, can we make the execution lazy? I don't need this immediately because creating two bundles is easy. However, I think it would be a nice feature.

**Comment by guybedford** [comment]
Execution is actually already lazy - System.register just sets `System.defined[name]` which in turn is only executed when imported.

Perhaps you have AMD or something that isn't masking the code? This may improve in the latest builder updates.

**Comment by MajorBreakfast** [comment]
Okay. I'll investigate it further. Anyway, thanks for clearing this up.
