### ISSUE TITLE
export * exports __useDefault and __esModule incorrectly

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#487]
These special properties don't make sense to export with export *.

**Comment by guybedford** [comment]
The fix for this will actually come from the bulk export function implementation in https://github.com/ModuleLoader/es6-module-loader/issues/386.

**Comment by guybedford** [comment]
Actually the way to do this is to make __useDefault and __esModule non-enumerable.

**Comment by guybedford** [comment]
This should now be resolved in https://github.com/systemjs/systemjs/commit/b5146b37dbf4b502ac67243dd90c1340cb848068.

**Comment by guybedford** [comment]
Released in SystemJS 0.18.

**Comment by geelen** [comment]
Should `__hotReload` be non-enumerable as well then?

**Comment by guybedford** [comment]
@geelen unfortunately this trick won't apply in the spec, so it's not advisable to assume it can work that way.
