### ISSUE TITLE
How do I print TypeScript errors?

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#488]
How do I print TypeScript errors in the browser console?

Shouldn't type-check errors be caught and presented when hooking up .catch(..) like with babel?

**Comment by mhegazy** [comment]
@robertsundstrom only syntax errors are reported. A full typecheck is not possible in transpile scenarios, as the compiler does not have access to all your modules, .d.ts, references, etc.. transpiling is a simple string->string transformation; other than errors, this produces the same JS output as building from the commandline as all type-check errors in TypeScript do not change emit,.

For the full errors I would use a TypeScript plugin in your editor, this way you can get all errors at design time without having to do a separate build step.

**Comment by vladima** [comment]
@robertsundstrom I've responded in #489, JIC copying my answer here:
>complete typechecking in transpile scenarios is not really possible: TypeScript compiler deliberately works within given file without attempting to resolve tripleslash references/external modules and even standard library. In this circumstances it cannot build the full set of types that will be available in the program and will report lots of errors which are in fact false positives. If you want to have full-fledged editing experience with correct errors - you should use editor with TypeScript support i.e. VSCode, Sublime, Visual Studio, Atom etc. Support to compile isolated modules can be seen as merely a shortcut to avoid explicit compilation step but not the replacement for full program analysis which can be done i.e. in the editor or the compiling the whole program.

we probably can consider reporting syntax errors, they will be reasonably precise.

**Comment by robertsundstrom** [comment]
@mhegazy @vladima Ah! OK. That totally makes sense then. Thanks.
