### ISSUE TITLE
default extension when importing TypeScript files, question about sourceMaps

### ISSUE THREAD

**Issue by maryo** [systemjs/systemjs#489]
Hi. I tried the new typescript support. Just the development workflow yet with a simple Hello World code.
http://maryo.chytrak.cz/jspm/

I've installed the jspm using `npm install -g jspm@beta`

1) I had to change the value of typescript key in System.config map `"github:mhegazy/typescript@v1.5-beta2"` to `"github:mhegazy/typescript@v1.5-beta2/bin/typescript.js"`. Is it a bug or did I just misunderstood something?

2) I've set `"defaultJSExtensions"` to false, but then the `.ts` extension needs to be present when importing. Is it possible to import the TypeScript files without specifying the `.ts` extension?
I think it would be good if the default extension was `.ts` when importing from `.ts` file and `.js` otherwise.

3) I've intentionally left `undefinedFunctionCall();` in `bootstrap.ts` at line 16 and got this in recent Chrome
`Uncaught (in promise) Error: undefinedFunctionCall is not defined
	Error loading http://maryo.chytrak.cz/jspm/app.ts
    at Object.bootstrap (http://maryo.chytrak.cz/jspm/bootstrap.ts!transpiled:6:9)...`.

Could sourceMaps help here so i could see the call is from line 16 of `bootstrap.ts`?

Thanks for this awesome project and any answer.

**Comment by guybedford** [comment]
The `defaultJSExtensions` option needs to be set to true in this version of jspm unfortunately. I've updated the release notes at https://github.com/jspm/jspm-cli/releases/tag/0.16.0-beta.

If (1) is still happening with this enabled that is a bug, but it was working fine for me.

**Comment by johnjelinek** [comment]
I'm having to name all of my ts files `*.js.ts`, is that expected?

Here's my `config.js`:
```
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "paths": {
    "github:*": "jspm_packages/github/*",
    "app/*": "app/*.ts"
  }
});

System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2"
  }
});
```

`index.html`:
```
<!doctype html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script src="jspm_packages/system.js"></script>
    <script src="config.js"></script>
    <script>
      System.import("app/main")
        .catch(function (e) {
          console.error(e, "Report this error to @johnjelinek");
        });
    </script>
  </body>
</html>
```

`app/main.js.ts` (note: the transpiler doesn't launch unless I import it here):
```
import * from "typescript";
import { Person } from "app/models/person";

class Main {
  constructor(message: string) {
    var h1 = document.createElement("h1");
    h1.innerText = message;
    document.body.appendChild(h1);

    var h2 = document.createElement("h2"),
        person = new Person("John", "Jelinek");

    h2.innerText = person.fullname;
    document.body.appendChild(h2);
  }
}

new Main("Hello World");
```

`app/models/person.js.ts`:
```
export class Person {
  fullname: string;
  constructor(public firstname: string, public lastname: string) {
    this.fullname = `${firstname} ${lastname}`;
  }
}
```

**Comment by johnjelinek** [comment]
as an aside: the typing features aren't really working. For example, if I pass a non-string as the args for `Person` (ie: `new Person(1,2)`) there are no complaints.

**Comment by maryo** [comment]
OK. Thanks.

1 & 2: How will the `.ts` extension be handled in the future? Using the map like @johnjelinek did? `"app/*": "app/*.ts"`. Will it be enough?

3: The source maps.

I've tried to manually transpile some code using eval with inline source maps enabled without SystemJS. I had to add the code to the source map too (because it comes from the textarea) and it works perfectly in Chrome - `textarea content:10 Uncaught ReferenceError: undefinedFunctionCall is not defined`

http://maryo.chytrak.cz/jspm/source-map-test.html

But using SystemJS... `jspm-ts-angular.dev/:1 Uncaught (in promise) Error: undefinedFunctionCall is not defined`
http://maryo.chytrak.cz/jspm/index.html

Also I've noticed i can't just `System.import('./greeter.ts')`. Looks like the TypeScript transpiler is not invoked. Is this intentionally? Is it needed to have a top-level JS file with TS file import?
http://maryo.chytrak.cz/jspm/single-file.html (with `System.import('./greeter.ts')` -> `Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`)

http://maryo.chytrak.cz/jspm/index.html (with `System.import('./app.ts')` which contains `import {bootstrap} from './bootstrap.ts';` -> works... just the source maps)

**Comment by johnjelinek** [comment]
I had to do `import * from "typescript"` to invoke the transpiler.

**Comment by vladima** [comment]
@maryo re. 1 there is an initial version of TypeScript/JSPM sample [here](https://github.com/Microsoft/TypeScriptSamples/tree/jspm/jspm) nothing needs to be changed in default module paths

@johnjelinek complete typechecking in transpile scenarios is not really possible: TypeScript compiler deliberately works within given file without attempting to resolve tripleslash references/external modules and even standard library. In this circumstances it cannot build the full set of types that will be available in the program and will report lots of errors which are in fact false positive. If you want to have full-fledged editing experience with correct errors - you should use editor with TypeScript support i.e. VSCode, Sublime, Visual Studio, Atom etc. Support to compile isolated modules can be seen as merely a shortcut to avoid explicit compilation step but not the replacement for full program analysis which can be done i.e. in the editor or the compiling the whole program.

**Comment by maryo** [comment]
@vladima Great. Even the sourcemaps work well in your example.

Here are steps for reproducing the problem in your example.
1) append `undefinedFunctionCall();` to the end of the body of the exported main function inside `app.ts`. Sourcemaps work nicely `app.ts:6 Uncaught (in promise) ReferenceError: undefinedFunctionCall is not defined` - Great

2) Remove the `then` call after `System.import('app')` so it's just
```
//System.config({......
System.import('app');
    </script>

And also replace the exported main function with it's body, just replace the passed el argument with hardcoded `document.getElementById`

so the contents of `app.ts` is now
```
import { Greeter } from 'greeter'

let greeter = new Greeter(document.getElementById("content"));
greeter.start();
undefinedFunctionCall();
```

The program still works, but the sourcemaps are now broken:
`jspm.dev/:1 Uncaught (in promise) Error: undefinedFunctionCall is not defined` - It doesn't tell you anything about `app.ts`.

3) Now replace the whole contents of the app.ts to just simple Hello world console.log with defined empty class so the contents of the `app.ts` is now:
```
import { Greeter } from 'greeter'
class Test {} // This is test of the transpilation
console.log('Hello world');
```
It works, it prints `Hello world` to the console.

4) Now remove the first line - `import { Greeter } from 'greeter'` and you will get
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by frankwallis** [comment]
I think that there may be an issue with new ```defaultJSExtensions``` configuration property, even when it is set to true systemjs behaviour is significantly different to how it was in the previous release, it is not backwards compatible. [This](https://github.com/frankwallis/source-map-test) is an example project I created a few weeks ago using the new typescript support, but I am now unable to get it working with jspm 0.16-beta because of issues with file extensions. Originally there was a paths mapping '*' -> '*.ts' which defaulted all the files to the correct extensions but this path mapping does not work any more.

In the example project provided by @vladima there are explicit mappings for app.js -> app.ts and greeter.js -> greeter.ts (ie every typescript file has a mapping) and greeter is imported as an ambient module ```import {Greeter} from 'greeter'``` when it would normally be imported as a relative module. When I change it to use the relative path ```import {Greeter} from './greeter'``` it then becomes impossible for me to create a mapping which makes the system load greeter.ts.

It seems that the logic for resolving file paths using map entries in config.paths and adding js extensions is happening quite differently.

**Comment by guybedford** [comment]
@frankwallis good point - I've added an experimental change into SystemJS to try to correct for this at https://github.com/systemjs/systemjs/commit/b00b8a5d36b8fe8f661af20c219393144a607ea5. Let me know if that helps.

**Comment by guybedford** [comment]
I've been thinking about this some more, and while it would be great to cater to the use case, it is a breaking change at this point in SystemJS to apply defaultJSExtensions after paths instead of before. For this reason I'm reverting that fix and going to have to leave this as a point of contention unfortunately.

**Comment by frankwallis** [comment]
ok but unless it is possible to map ```import "./greeter"``` to ```"http:/greeter.ts"``` then it won't be possible to build any existing TypeScript projects. That used to be possible in 0.15 using a path entry of ```"*":"*.ts"``` but in 0.16 it does not seem to be possible.

**Comment by guybedford** [comment]
@frankwallis the alternative here is to post a SystemJS 0.18 with the new paths behaviour for this scenario. Are you sure this is the only option?

**Comment by maryo** [comment]
The extension handling is one problem. But even if i use `.js` extension instead of `.ts` one, i still get
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` when
index.html: `<script>System.import('app')</script>`
app.js:
```js
class Test {}
console.log('test');
```

We should probably split this issue.

**Comment by frankwallis** [comment]
The best I have managed to come up with is this workaround which means that you can use relative imports in typescript source files:

```
      // workaround for https://github.com/systemjs/systemjs/issues/489
      var systemNormalize = System.normalize;
      System.normalize = function(dep, parent) {
         var System = this; // its good to ensure exact instance-binding
         console.log('normalizing ' + parent + ' -> ' + dep);
         return systemNormalize.call(this, dep, parent)
            .then(function(normalized) {
               // only modify relative imports from typescript files
               if ((parent && (parent.slice(-3) == '.ts')) && (dep[0] == ".")) {
                  var depname = dep.slice(dep.lastIndexOf("/"));

                  // if no file extension ensure it gets a .ts extension                  
                  if (depname.indexOf('.') < 0)
                        normalized = normalized + '.ts';
               }               
             
               // and fix up any double extensions
               if ((normalized.slice(-6) == '.ts.js') || (normalized.slice(-6) == '.js.ts'))
                  normalized = normalized.slice(0, normalized.length -6) + ".ts";
                  
               console.log('normalized ' + normalized + ' (' + parent + ' -> ' + dep + ')');
               return normalized;
            });
      }
```

I should be able to integrate this into plugin-typescript, but if users are not using the plugin then they will need to inject it themselves.

**Comment by guybedford** [comment]
@frankwallis yes that's unacceptable - let's continue the discussion in https://github.com/systemjs/systemjs/issues/506.

**Comment by vilic** [comment]
@vladima Sad to say that the jspm demo fails in August.

**Comment by guybedford** [comment]
@vilic which demo are you referring to?

**Comment by vilic** [comment]
@guybedford https://github.com/Microsoft/TypeScriptSamples/tree/jspm/jspm

**Comment by mhegazy** [comment]
@vilic https://github.com/Microsoft/TypeScriptSamples/tree/master/jspm is now working with latest JSPM.

**Comment by vilic** [comment]
@mhegazy @vladima Thanks!
