### ISSUE TITLE
defaultJSExtensions, import files with different extension

### ISSUE THREAD

**Issue by DatenMetzgerX** [systemjs/systemjs#490]
As mentioned in the release notes of 17.0, the new default will be `defaultJSExtensions:  false`. I'm creating a new project, so I would like to go with the new default and avoid using any features that might be deprecated in the near future. 

In my setup I will use the new Typescript support. So my configuration looks like this

```js
System.config({
  "baseURL": "/",
  "defaultJSExtensions": false,
  "transpiler": "typescript",
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});
```
Loading typescript will now fail because of the missing `.js` extension. So I configured the default extension for the typescript package:

```js
"packages": {
    "github:mhegazy/typescript@v1.5-beta2": {
         "defaultExtension": "js"
    }
    ....
}
```

ans also changed the mapping for typescript (added js extension):
```js
System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2.js",
});
```

This configuration works fine for all packages where we do not have mixed content. If a package contains js and css resources, the resolution will fail for all css resources (because of the added .js extension to the package path). E.g. `http://localhost:3000/jspm_packages/github/angular/bower-material@0.9.7.js/angular-material.css`

So how would a correct configuration with `defaultJSExtensions` looks like? 

If I have to use `defaultJSExtensions` for the moment, then how can I use `.ts` files? The problem is, if we use `defaultJSExtensions: true`, then an extension will be appended even if the filename of an import statement already contains an extension. 

```js
System.import('app/main.ts');
```
resolves in an import of `app/main.ts.js`... 

My last try was to use the `paths` configuration and map all files in `app/**/*` to `app/**/*.ts`, but with a similar result as with the previous configuration:

```js
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
      "app/*": "app/*.ts"
  }
});
```

```js
System.import('app/main');
```

Results in `/app/main.js.ts``

So it's kind of impossible to get rid of the default extension if another extension should be used.
May you provide an example for using a different extension when `defaultJSExtensions: true` is set (what needs to be for backward compatibility?). 

Thanks!
Micha

**Comment by guybedford** [comment]
The `defaultJSExtensions: true` mode has to be used in jspm currently. Only plain SystemJS projects can take advantage of the new mode for now. I've updated the release notes to mention this.

I should have learned from the past that users really hate seeing the future but being held back from it. Sorry!

**Comment by DatenMetzgerX** [comment]
Thanks for your fast replay. 

First, I think I'm just using plain System.js because I'm not using jspm to bundle any resources. I'm just executing the page in the browser.

It's ok for me if I have to use the option. But what looks wrong for me is, that  `defaultJSExtensions` also adds the extension if an extension is already included in the import statement. I figured out how I can use the typescript support at the moment. I have to use 

```js
System.import("main.ts!typescript")
```

But if this notation is used in typescript, then IDE support is broken because the import can not be resolved by the IDE (it tries to resolve the file including `!typescript`).

I would expect that `defaultJSExtensions: true` only appends the `.js` extension if no extension is present. Also because we can now define loaders for file endings like *.css. This functionality is useless when the loader needs to be specified explicit to avoid appending the .js extension.

Or do I mix different concepts? I'm still new to SystemJS, JSPM...

**Comment by guybedford** [comment]
@DatenMetzgerX the `defaultJSExtensions` is a backwards-compatibility mode with the previous behaviour. There is real code that expects things like `import 'file.main'` to work with js extension adding so we need to cater to this.

The `defaultJSExtensions` breaks jspm's lookup system at the moment, which is probably why you needed to alter the path to TypeScript for example.

**Comment by mikehaas763** [comment]
> The defaultJSExtensions: true mode has to be used in jspm currently.

Is the technical reason for this because jspm currently depends on an older version of systemjs that itself does not support false mode?

**Comment by guybedford** [comment]
Yes, jspm 0.17 will contain the update to the new SystemJS configuration, as part of a two-phase SystemJS upgrade in jspm.
