### ISSUE TITLE
17.x not working in IE?

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/systemjs#493]
For some reason, the following doesn't appear to be working in IE 11 (in both Edge and 10 modes). Works fine in Chrome, Firefox.
```html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <script src="lib/es6-module-loader.js"></script>
    <script src="lib/system.js"></script>
    <script>
        System.config({
            baseURL: "src"
        });
        System.defaultJSExtensions = true;
        System.import("app").then(function (app) {
            app.init();
        });
    </script>
</head>
</html>
```
The referenced scripts are the current versions of system.js and es6-module-loader.js (from the dist folders). The error I get is on the System.config line:

    Object doesn't support property or method 'config'

Interestingly, if I don't include the script tag for es6-module-loader script (which I usually don't) then window.System is also undefined.

If I downgrade to the 16.x versions, it works.

**Comment by guybedford** [comment]
Note that SystemJS not longer requires es6-module-loader.js to be included in the browser at all as it is now a complete build of the loader itself.

In IE10 SystemJS will try to load `system-polyfills.js` though, which needs to be present in the `lib` folder. Have you got this in the environment?

**Comment by jamiewinder** [comment]
Nope! Included it (and removed es6-module-loader) and now it's all working. My fault. Thanks!
