### ISSUE TITLE
import error when module  without export

### ISSUE THREAD

**Issue by reutopiaer** [systemjs/systemjs#496]
```
//load.js
var System = require('systemjs');
System.import('./test1').then(function(m) {
  console.log(m);
});
System.import('./test2').then(function(m) {
  console.log(m);
});
````
```
//test1.js
var fs = require('fs');
console.log('test1 typeof fs ' + typeof fs);
export function M() {};
```

````
//test2.js
var fs = require('fs');
console.log('test2 typeof fs ' + typeof fs);
//export function M() {};
```

$ iojs load.js
Potentially unhandled rejection [3] Error: Error loading "fs" at file:e:/fs.js
Error loading "fs" from "test2" at file:e:/test2.js
ENOENT: no such file or directory, open 'e:\fs.js'
    at Error (native)
test1 typeof fs object
{ M: [Function: M] }

**Comment by guybedford** [comment]
What is your `System.baseURL` value here? It should be requesting fs relative to the process directory.

Note that SystemJS doesn't provide the Node-lookup. That is `require('fs')` will look for a file called fs.js in the current directory. This is where configuration comes in to set the loading path to fs.

**Comment by reutopiaer** [comment]
@guybedford  thanks for your reply. 
```System.baseURL``` is default ```console.log(System.baseURL); // file:e:/ ```

I want use nodejs's buildin module(such as 'fs' 'http' ...) in the module that import by SystemJS.
Right now I just add ```export function M() {}; ```to the modle file.It's work,but I need a better way to import.

**Comment by guybedford** [comment]
Importing Node builtins it not a feature supported natively in SystemJS. If you need access to these, rather look at jspm or access `System._nodeRequire` directly.
