### ISSUE TITLE
Systemjs is unable to resolve correct path

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#500]
This used to work. What is wrong? I updated the dependencies. A bug in SystemJS?

Repository: https://github.com/robertsundstrom/knockoutjs-express-es6 (not updated)

## Error ##

GET http://localhost:3000/text.js 404 (Not Found)D @ system.src.js:3580o.fetch @ system.src.js:3580o.fetch @ system.src.js:3580p @ system.src.js:3580(anonymous function) @ system.src.js:3580r @ system.src.js:3580r @ system.src.js:3580n @ system.src.js:3580(anonymous function) @ system.src.js:3580(anonymous function) @ system.src.js:3580(anonymous function) @ system.src.js:3580
localhost/:1 Uncaught (in promise) Not Found: http://localhost:3000/text.js
	Error loading http://localhost:3000/text.js
	Error loading http://localhost:3000/pages/home/home.html!http://localhost:3000/text.js

## config.js ##

System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "stage": 0,
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "text": "jspm_packages/github/systemjs/plugin-text@0.0.2.js",
    "css": "jspm_packages/github/systemjs/plugin-css@0.1.10.js",
    "knockout-projections": "./js/knockout/knockout-projections.min.js",
    "modules": "modules",
    "utils": "../modules/utils.js",
    "services": "services",
    "components": "components"
  }
});

...

**Comment by guybedford** [comment]
@robertsundstrom no bugs here. Just the interaction with `defaultJSExtensions` meaning the paths config needs to be updated to `"paths": { "text.js": "..." }` etc etc.

**Comment by robertsundstrom** [comment]
@guybedford. Thank you! Got a bit worried.

You can close this issue now.

**Comment by guybedford** [comment]
This is difficult to know though - I've added a change in https://github.com/systemjs/systemjs/commit/b00b8a5d36b8fe8f661af20c219393144a607ea5 to make this work as expected actually. A patch may well follow soon.

**Comment by guybedford** [comment]
After further thought I've decided to stick with the existing behaviour as it does make sense and would be breaking to change at this point, even though it may be a little inconvenient.
