### ISSUE TITLE
Deprecate System.map?

### ISSUE THREAD

**Issue by probins** [systemjs/systemjs#501]
es6-module-loader implements paths and not map, and site mappings in the new spec seems to match paths, but https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#paths recommends using map over paths. This seems contradictory and likely to confuse newbies. I'm thinking it might be better to concentrate on paths/sites and deprecate map.

**Comment by guybedford** [comment]
Map is far more powerful than paths, and I'd always suggest it over paths. Map allows mapping a name into a package, which is not possible via paths.

**Comment by probins** [comment]
perhaps what's needed then is some more/better examples of when you would use each. The first example in map/paths docs is identical. If systemjs is simply using es6-module-loader's implementation, then perhaps change systemjs docs to a link to es6-module-loader's docs, and give examples for those features of map that paths doesn't provide.

**Comment by guybedford** [comment]
Documentation PRs are always welcome.
