### ISSUE TITLE
require.toUrl

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#504]
Do you have any intentions to implement `require.toUrl`, which is [part of the AMD specification for the `require` function](https://github.com/amdjs/amdjs-api/wiki/require#requiretourlstring-)?

I ask because we noticed a lot of our consumers are relying on this function (available with curl/RequireJS, our current module loaders).

Let me know how I can help if so!

/cc @rich-nguyen @Rich-Harris

**Comment by guybedford** [comment]
Sure, I've added this in https://github.com/systemjs/systemjs/commit/1417f90dc7a87d32e1ec06560ac93e07e825090e.

**Comment by rich-nguyen** [comment]
Brilliant, thanks for the speedy change, @guybedford ! We will test this and get back to you

**Comment by Rich-Harris** [comment]
Oh man, this is such great news to wake up to. @guybedford: what a hero. This could save us a lot of uncertain work. @OliverJAsh thanks for digging up the spec and raising this :+1:

**Comment by OliverJAsh** [comment]
:smile:

@guybedford I presume this will make SystemJS fully AMD compliant?

**Comment by guybedford** [comment]
I guess so! Just AMD-style plugins then that we don't support. Thanks for pushing on all these to get to this point.

**Comment by guybedford** [comment]
Released in SystemJS 0.18.

**Comment by OliverJAsh** [comment]
Thanks for releasing this!

Should `require.toUrl('./foo')` return with or without `.js`? curl returns without the extension, but we seem to return with it. `foo` could be a directory?

**Comment by Rich-Harris** [comment]
Ah, good catch @OliverJAsh, this would have caused our modules to fail! [requirejs](https://github.com/jrburke/requirejs/blob/master/tests/toUrl/toUrl-tests.js) is ambiguous on the subject (all the tests have `.js` extensions), but curl [states](https://github.com/cujojs/curl/blob/master/src/curl.js#L329-L334) that an extension shouldn't be added (albeit because there might already be one, rather than because it might be a directory). The spec says 

> require.toUrl resolves the module ID part of the string using its normal module ID-to-path resolution rules, except it does not resolve to a path with a ".js" extension. Then, the '.extension' part is then added to that resolved path

which I read as saying 'if there's no extension, don't add one'.

**Comment by guybedford** [comment]
Thanks - I've added this in https://github.com/systemjs/systemjs/commit/da93c0cc86f2238f1fcb96649f6a56f1fa0051c8.

**Comment by OliverJAsh** [comment]
Thanks @guybedford. Is there any way I can start using this right now, without waiting for a release? `jspm dl-loader --source|--edge` only seem to use the `dist` folder in this repo, not the actual source.

**Comment by guybedford** [comment]
@OliverJAsh sure I've pushed up a build.

**Comment by OliverJAsh** [comment]
Unfortunately I found a bug: https://github.com/systemjs/systemjs/pull/530
