### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by maryo** [systemjs/systemjs#505]
I get
`Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` when
config.js:
```js
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "paths": {
    "github:*": "jspm_packages/github/*"
  }
});

System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2"
  }
});
```
index.html:
```html
<script src="jspm_packages/system.js"></script>
<script src="config.js"></script>
<script>System.import('app')</script>
```
app.js:
```js
class Test {}
console.log('test');
```

It works when i prepend redundant import `import notExistingFile from 'whatever';` to `app.js`

**Comment by vladima** [comment]
seems that this source code does not match `[esmRegex](https://github.com/systemjs/systemjs/blob/master/lib/esm.js#L6)` and so transpiler is never called

**Comment by guybedford** [comment]
Thanks @vladima for catching that. Should have noticed that one myself!

@maryo you can use meta configuration to ensure the format is detected as ES6. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md. Just let me know if you have any further questions.

**Comment by maryo** [comment]
Thanks a lot. It helped. I missed it :innocent:. Nevertheless the regexp could be modified to catch more things not present in ES5, not only export/import. Or is it a bad idea?

**Comment by guybedford** [comment]
The internal layer is only for the ES6 module format. Not the ES6 script format. This distinction will be clearer in future.
