### ISSUE TITLE
Consider paths over map in package config

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#507]
Within package config, it may be nicer to use wildcard paths over map as it offers more flexibility than map rules.

For example with map we have issues like:

```javascript
map: {
  './jquery': './jquery/index.js'
}
```

Then `System.import('pkg/jquery/test')` will now require `pkg/jquery/index.js/test`!

Paths may well make a lot more sense here.

**Comment by probins** [comment]
brings me back to my question on whether it wouldn't be better to deprecate map :-)

**Comment by guybedford** [comment]
We can't deprecate map if we want to allow `import 'jquery'`. map -> packages -> paths.

**Comment by guybedford** [comment]
The more I think about this though the more I like it. It does effectively deprecate contextual map, paths makes more sense here as we are at the end of the pipeline anyway. Map is always an early aliasing.

**Comment by guybedford** [comment]
Implemented in https://github.com/systemjs/systemjs/pull/510.

**Comment by guybedford** [comment]
Reverted this in the end for two reasons:

1. Paths apply before js extension adding, while we do need a mechanism that can apply flexibly with the js extension process.
2. The cost of having map also map subpaths is not that great to warrant separating out the feature. The major cost is that `./jquery.js/y` also gets mapped when we just wanted to map `jquery.js`. If this really is an issue a new map can be created for `./jquery.js/y` into itself to take preference. It's mainly an issue for when extensions are not used, and the general best practice is for extensions to be used.
3. We lose the ability to map from internal to external with paths, which is useful for replacing internal implementations with any custom external implementation
4. Much better to see this as a single concept instead of two for simplicity anyway.

At least we've been down the road, and have some experience to hold this to now.

**Comment by guybedford** [comment]
The other killer here worth mentioning was that wildcard paths didn't transfer as neatly as hoped.

The issue being that wildcard paths in URL space get tricky. For example `paths['*'] = 'lib/*'` in a package would be circular in its dependencies becoming `lib/lib/dep` etc. Similarly for extension adding.
