### ISSUE TITLE
Sourcemaps not correct when Error is not inside exported function

### ISSUE THREAD

**Issue by maryo** [systemjs/systemjs#511]
Sorry for flooding with issues, I've closed the original one - https://github.com/systemjs/systemjs/issues/489
I am not sure if this is a bug or just a limitation. I've tested it using both Babel and TypeScript as a transpiler and the result was the same.

Let's say i have a file `app.js` and `index.html`.

**A SCENARIO WHERE IT WORKS AS EXPECTED**
`app.js`
```js
export function bootstrap() {
	unknown_function_call('sourcemaps are OK'); // app.js:2 Uncaught (in promise) ReferenceError: unknown_function_call is not defined
}
```
`index.html`
```html
<script>
	System.import('app').then(function(app) {
		app.bootstrap();
	});
</script>
```

**A SCENARIO WHERE IT DOES NOT**
`app.js`
```js
unknown_function_call('sourcemaps are WRONG'); // jspm-sourcemaps-test.dev/:1 Uncaught (in promise) Error: unknown_function_call is not defined
```
```html
<script>System.import('app')</script>
```

I'd expect here it tells me the error comes from from app.js:1, not from the root.

**Comment by guybedford** [comment]
This is a browser limitation - browser do not handle source maps in the synchronous execution scope.

**Comment by maryo** [comment]
I was afraid it's something like that :-/. But I'm still not sure i understood the difference between the second scenario and this one.
http://maryo.chytrak.cz/source-map-test/

**Comment by guybedford** [comment]
The difference is if its within the initial execution thread, or after the event loop has run.

**Comment by maryo** [comment]
I'm so sorry but U still don't understand it.

```js
	var System = {
		register: function register(dependencies, createModule) {
			createModule().execute();
		}
	};

	var transpiled = `
		var __moduleName = 'http://jspm.dev/app/index.ts';System.register([], function(exports_1) {
			return {
				setters:[],
				execute: function() {
					unknown_function_call('sourcemaps are OK');
				}
			}
		});
		//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJpbmRleC50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7O1lBQUEscUJBQXFCLENBQUMsc0JBQXNCLENBQUMsQ0FBQzs7OztBQUM5QyxzQkFBc0IifQ==
		//# sourceURL=http://jspm.dev/app/index.ts!transpiled
	`;

	var head = document.head || document.body || document.documentElement;
	var script = document.createElement('script');
	script.text = transpiled;
	head.appendChild(script);
```
I was trying to understand it by reproducing the issue in the simplest scenario but this still works.
Could you or someone else describe it by breaking sourcemaps in this code if it's simple?

**Comment by guybedford** [comment]
The way to test this is simply: `eval('some code //#sourceMappingURL=data:[some source map]')` if the code has an error in it, the source map will not apply. Only if the code ticks the even loop via a non-sync callback, will the source map have applied.

**Comment by maryo** [comment]
This works for me in Chrome.

eval('undefinedFunctionCall(); //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbInRlc3QudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUEscUJBQXFCLEVBQUUsQ0FBQyJ9');


test.ts:1 Uncaught ReferenceError: undefinedFunctionCall is not defined

**Comment by guybedford** [comment]
Interesting. It's worth investigating.

**Comment by guybedford** [comment]
I've adjusted the source maps error test to be treated as an ES module instead of global in https://github.com/systemjs/systemjs/commit/a47af63986b60daf83a7e654b1e69506831b4dc0. It gives me the right debugging source map fine here. I think the issue may be related to the size of the module being loaded - if it takes longer than a certain amount of time to process the source map it seems Chrome may ignore it to provide the error? That's the best I can think of currently here. Closing as it seems like a Chrome internal, and not really something we have control over here.

**Comment by guybedford** [comment]
Argh, actually I reverted the change - the test is testing exactly the thing that you say doesn't work originally, and it works fine for me! I even changed the contents of `error.js` to your example and the source map works fine here. Perhaps Chrome sorted this out recently.

**Comment by maryo** [comment]
Does it realy works fine for you? You mean the scenario in the first comment titled "A SCENARIO WHERE IT DOES NOT"? It's still the same for me.

You can try it here.
http://maryo.chytrak.cz/jspm-source-maps/

My Chrome version is 43.0.2357.134 m and I am using Windows8, SystemJS version is 0.18.4

![chrome console output](http://maryo.chytrak.cz/jspm-source-maps/chrome-console-output.png)

**Comment by guybedford** [comment]
I think this is actually just the TypeScript transpiler not linking up source maps correctly.

**Comment by guybedford** [comment]
As mentioned, I have tested your scenario that doesn't work in Traceur, and it worked fine. If this is TypeScript specific, then that would be useful to know.

**Comment by maryo** [comment]
I've tested the same using Traceur and then Babel with the same result as before.

http://maryo.chytrak.cz/jspm-source-maps-traceur/

There has to be a difference if your test is successfull.

**Comment by guybedford** [comment]
I get the following stack trace in Chrome:

```
Uncaught (in promise) Error: unknown_function_call is not defined
	Error loading http://maryo.chytrak.cz/jspm-source-maps-traceur/app/index.js
    at execute (http://maryo.chytrak.cz/jspm-source-maps-traceur/app/index.js!transpiled:6:7)
    at ensureEvaluated (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:2007:26)
    at Object.Promise.all.then.execute (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:2137:13)
    at doDynamicExecute (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:688:25)
    at link (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:883:20)
    at doLink (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:555:7)
    at updateLinkSetOnLoad (http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:603:18)
    at http://maryo.chytrak.cz/jspm-source-maps-traceur/jspm_packages/system.src.js:424:11
```

The third line above is exactly the correct line.

**Comment by maryo** [comment]
Yes, I get the same. "index.js!transpiled:6:7" is correct? It points to the transpiled filed, not to the original one which is first line of index.js.

**Comment by guybedford** [comment]
@maryo yes I'm not sure why this seems to vary. I guess syntax errors are treated differently to runtime errors as well here. It could be worth investigating further - perhaps syntax errors give a link to the original source, while runtime errors link to the transpiled source?

Note that it is wired correctly though - if you add a debugging breakpoint to the original source for a runtime error it will debug the original source file fine.

**Comment by jjrv** [comment]
I managed to get SystemJS to wrap soon to be loaded code in a function and `eval()` it in the `instantiate` hook, then call that function when importing (so it doesn't run synchronously inside the same eval that contains the source map). **It did not help.**

This far easier solution fixed everything for me:

```JavaScript
var oldInstantiate = System.instantiate;

System.instantiate = function(load) {
	return(oldInstantiate.call(this, load).then(function(result) {
		if(!load.metadata.bundle && load.metadata.format.match(/^(amd|cjs)$/)) {
			load.source = 'try {' + load.source + '\n} catch(err) {console.error(err.stack);}';
		}

		return(result);
	}));
}
```

Errors encountered during a synchronous import now show the correct line of code according to the source map.

**Comment by guybedford** [comment]
@jjrv if you're able to share a test case that this solved for you, that would be really interesting to investigate further. Obviously relying on a fix like the above just to get good source maps is not ideal!

**Comment by jjrv** [comment]
@guybedford here: https://github.com/charto/charto-map-frontend/commit/b9fec718306c08bcb2bccb1548b0530a32e9b690

It's currently just a template combining TypeScript, [`cbuild`](https://github.com/charto/cbuild) and [`systemjs-hot-reloader`](https://github.com/capaj/systemjs-hot-reloader). Putting any gibberish in the compiled `dist/app.js` like a function call `undefinedFunctionCall();` gives a nice stack trace in my  Chrome 49.0.2623.110 (stuck in this version due to old OS X). If you remove the `System.instantiate` kludge from `index.html`, the stack trace printed to the browser's console will no longer consider the source map in its output.

I don't think there's anything special about my project and any use of SystemJS in this browser would probably work in the same way. There's currently a single fork of my project and its maintainer also running on OS X (not sure what version) is having the same experience.

**Comment by guybedford** [comment]
@jjrv when I run this I get:

```
Error on fetch for debug.js at file:///Users/guybedford/Projects/test/charto-map-frontend/debug.js
  Loading node_modules/systemjs-hot-reloader/hot-reloader.js
```

With the source maps stuff, are you definitely expanding the `...` in the error message in Chrome?

**Comment by jjrv** [comment]
@guybedford I've now changed `app.ts` contents to:

```TypeScript
import * as React from 'react';

console.log('Hello, World!');
console.log(React);

declare var unknownFunctionName: any;

unknownFunctionName();
```

The import and `console.log` ensure that SystemJS detects the module type. Then I ran:

```bash
npm install
npm start
```

Opening [http://localhost:6630/](http://localhost:6630/) in Chrome shows this in the debug console:

<img width="677" alt="screen shot 2016-04-22 at 3 54 00 am" src="https://cloud.githubusercontent.com/assets/778781/14728514/31295d42-083e-11e6-8cea-c9efc6b09a95.png">

Then I removed the kludge, specifically [these lines](https://github.com/charto/charto-map-frontend/blob/b9fec718306c08bcb2bccb1548b0530a32e9b690/index.html#L23-L36) from `index.html`, reloaded and pressed `...` and then the down arrow as well. Now debug console shows:

<img width="692" alt="screen shot 2016-04-22 at 3 55 53 am" src="https://cloud.githubusercontent.com/assets/778781/14728527/5726b940-083e-11e6-8f68-a27a040fcecb.png">

**Comment by guybedford** [comment]
This seems like a Chrome-specific debugging optimization. Perhaps we have to choose between being able to add extra information to the error message and having the error message show the right source maps.

As an alternative, perhaps try:

```javascript
System.import('x')
.catch(function(e) {
  if (e.originalErr)
    throw e.originalErr;
  throw e;
});
```

I suspect throwing the `e.originalErr` should give the same source maps result you're aiming for with your extension here. If so, perhaps we can just document this as an alternative workflow for source maps.

**Comment by jjrv** [comment]
@guybedford it works, thank you! Much cleaner than patching the imported source. The down arrow now gives lines translated using source maps, while `...` doesn't. This is fine.

**Comment by guybedford** [comment]
@jjrv thanks for the confirmation, I've created a documentation issue in https://github.com/systemjs/systemjs/issues/1236.
