### ISSUE TITLE
Improve stacktrace for failed dependency loading

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#512]
This is what the errors looks like when a dependency fails to load:

```
Potentially unhandled rejection [3] Internal Server Error: <dependency>
	Error loading <dependency> from <requester>
	Error loading <dependency> (WARNING: non-Error used)
```

Sometimes `dependency` is a nested dependency of a dependency of `requester`, e.g. `requester -> foo -> bar -> dependency`. Is it possible to show the immediate requester (`bar`)?

**Comment by guybedford** [comment]
Sure, we can look at this - moved to https://github.com/ModuleLoader/es6-module-loader/issues/397.
