### ISSUE TITLE
system.import('app') does not load app.js

### ISSUE THREAD

**Issue by rolandjitsu** [systemjs/systemjs#513]
After I have updated to version `0.17.x`, it cannot load the files anymore. I used to use the `extension-register.js` together with:
```js
register(System)
```
somewhere in the `index.html`. And a simple:
```js
System
    .import('app')
    .catch(
        console.error.bind(console)
    );
```
But right now, you have removed `extension-register.js` (or renamed it to `register.js`) which no longer works as it used to. So I have switched to the full `system.js` file, but it keeps asking for `app` instead of `app.js`. If I turn on the `defaultJSExtensions`, then it breaks angular 2 (I am using that) because it adds those `.js` extensions to everything.

I've also tried including `es-module-loader,js`, but no changes (as expected since you mentioned is no longer necessary to include).

So I am a bit stuck and I am unsure what to do :| I transpile all my ES6 files before hand into ES5 in `register` or `commonjs` (tried both, same result) format so I avoid using runtime compilation with babel, traceur or typescript (I use gulp-typescript to compile instead).

I have a setup [here](https://github.com/rolandjitsu/ng2-play) which uses the version before `0.17.x` if you want to check it out and see how I've set it up.

**Comment by guybedford** [comment]
For the simple register build you can use the `system-register-only.js` build.

For the full SystemJS, yes `defaultJSExtensions is the option to use here. We're working on a patch to allow it to play well with custom extensions in https://github.com/systemjs/systemjs/issues/506.

**Comment by rolandjitsu** [comment]
@guybedford alright, but if I turn the `defaultJSExtensions` option on, how do I make the rest of the things behave (like angular 2 which doesn't have the extensions since it's all in one file)?

**Comment by guybedford** [comment]
Wait for the patch later today.

**Comment by rolandjitsu** [comment]
@guybedford awesome, that would be great. Just to have an idea, how will it work after the patch? I will set:
```js
System.config({
    defaultJSExtensions: true
});
System
    .import('app/bootstrap')
    .catch(
        console.error.bind(console)
    );
```
And then how will I tell System to not add any extension to angular? Something like the following?
```js
System.config({
    defaultJSExtensions: true,
    package: {
        'angular/*': {
            defaultJSExtension: false
        }
    }
});
```

**Comment by rolandjitsu** [comment]
Also, how about globbing patterns? I seem to only be able to do `app/*` and not `app/**/*.js`, and I have a deep tree, about 3 levels deep right now. Or is `app/*` supposed to work with any path that comes? Because it seems it does not.

**Comment by guybedford** [comment]
The plan will be something like:

```javascript
System.config({
  defaultJSExtensions: true,
  packages: {
    'path/to/angular': {
      defaultExtension: 'es6'
    }
  }
});
```

That said, Angular is quickly moving over to use js extensions anyway at this point!

**Comment by PinkaminaDianePie** [comment]
but what is default behavior in standart? should i append .js to all my module names or it will be ok to use defaultJSExtensions? will it work with native ```System``` object?
