### ISSUE TITLE
Changing baseURL after creating configs breaks config

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#514]
Given:

```
├── assets
│   ├── config.js
│   └── jspm_packages
├── index.html
├── node_modules
│   └── jspm
├── package.json
└── start.sh
```

(Contents at https://gist.github.com/OliverJAsh/418007daa5f61eb89c2a)

When I call `System.config` for [*the second time*](https://gist.github.com/OliverJAsh/418007daa5f61eb89c2a) to set `baseURL`, dependency mapping breaks:

```
Uncaught (in promise) Not Found: http://127.0.0.1:7000/assets/process.js
	Error loading http://127.0.0.1:7000/assets/process.js from http://127.0.0.1:7000/assets/jspm_packages/npm/lodash@2.4.1.js
	Error loading http://127.0.0.1:7000/assets/process.js
```

**Comment by guybedford** [comment]
Yes this is true. `baseURL` needs to be set before loading the configuration file as the configuration is normalized based on the baseURL. This is catch that needs to be documented. What I'll do is try and throw a useful error message if changing the baseURL too late.

**Comment by OliverJAsh** [comment]
Thanks!

**Comment by guybedford** [comment]
I've included this baseURL warning in https://github.com/systemjs/systemjs/commit/036ae527fca24a5c121b7482854419d6cd6dd1db.
