### ISSUE TITLE
Custom file extension

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#515]
``` js
System.config({
  "defaultJSExtensions": true,
  "paths": {
    "svgs/*": "inline-svgs/*.svg"
```

This used to work, but now all paths have `.svg` appended. Is there a new way to do this?

**Comment by guybedford** [comment]
Yes this is a known issue - in the process of providing a patch for it in https://github.com/systemjs/systemjs/issues/506.
