### ISSUE TITLE
systemjs, jspm, typescript, es6, sass and gulp

### ISSUE THREAD

**Issue by dsebastien** [systemjs/systemjs#516]
Hey there,

This isn't an issue for systemjs but rather a question about how to use systemjs in combination with n other 'things'. Having seen your Package Management for ES6 Modules talk (thanks!), I'm pretty much sold on the idea that systemjs & jspm are the way to go, but I'm having a hard time figuring out to best approach the transition from what I currently do to what I should be doing.

In my project, I'm using NPM for dependencies, a set of gulp tasks, TypeScript, SASS and AngularJS.

So far, I've developed the following build: https://github.com/dsebastien/midnightLightV2/blob/master/gulpfile.babel.js

My current build workflow is as follows:
* DEV
  * transpile TS code to ES5 towards a temp folder (w/ sourcemaps)
  * same for JS code (ES6 -> ES5 transpilation step using babel) (w/sourcemaps)
  * import the generated files through script tags (very painful)
* PROD
  * take all the generated ES5 code in the temp folder and create two minified bundles: vendor.min.js & bundle.min.js

Next to that, I use gulp-sass to translate my SASS code to CSS; note that I use a single sass file that imports additional sass partials. I also plan to have per-component sass files (together with Angular 2 components)

For vendor code/css, I simply refer to 'node_modules' in dev and copy files around for pro. Finally, in my TypeScript code, I use modules and imports. I already have an entrypoint but it currently only bootstraps Angular.

So that is what I am with today. I use script tags and feel the pain. Your talk makes me want to change my approach to be able to leverage both jspm & systemjs but I need a bit of help :)

As you've said in your talk, HTTP2 isn't quite there yet, thus for production I'd like to keep at most two bundles per file type (js & vendor js + css & vendor css) so as to limit the number of HTTP requests.

Preferably, I'd also like to avoid in-browser transpilation in all cases unless that would make sense for dev somehow? I also want to keep sourcemaps as they're very useful.

So far, I have done the following in order to switch:
* installed jspm
* added the dependencies I need using jspm (angular2, normalize.css, etc)
* loaded system.js & jspm.conf.js in my index.html
* modified the import for nomalize.css in my main SASS file
  * but I don't like the fact that I have to specify the version due to the folder structure under jspm_packages..

Would it make sense to:
- keep transpiling TS code to ES5 using gulp-typescript
- keep transpiling ES6 code to ES5 using gulp-babel
- use systemjs builder just after these two to create a bundle?

What would you recommend me as dev/prod workflow?

**Comment by martinmicunda** [comment]
@dsebastien check out this [repo]( https://github.com/martinmicunda/employee-scheduling-ui) for dev/prod workflow

**Comment by guybedford** [comment]
Yes it could be advisable to stick with your existing gulp tasks for transpiling, as it will offer the quickest build work flow, with SystemJS builder to create a bundle at the end. Be sure you are compiling into the `system` module format though for the best compatibility with SystemJS (supported in Babel and coming in TypeScript 1.5).

**Comment by dsebastien** [comment]
Thanks for your feedback! I'm still struggling to get the bundle I want but thanks to @martinmicunda I better understand how to do what I want.

I'm currently blocked with the TypeScript part as the currently available package doesn't support transpiling with the System module format and I'm not willing to build TypeScript on my machine, I've got enough bleeding edges around ;-)
