### ISSUE TITLE
AMD/global not downloading via script tag

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#517]
From https://github.com/systemjs/systemjs/releases/tag/0.17.0:

> SystemJS will now automatically load with a script tag for maximum CSP-compatibility when loading AMD, System.register or globals without custom shim options set.

Given:

``` js
// main.js
define(function () {
    return "main";
});
```

And

``` html
<script src="jspm_packages/system.src.js"></script>
<script src="config.js"></script>
<script>
    System.import('main');
</script>
```

`main.js` is downloaded using XHR. Shouldn't it be downloaded using script tags (thus avoiding eval) for maximum CSP compatibility? The same happens when the module is a global.

If I try using the CSP version:

``` html
<script src="jspm_packages/system.csp-production.src.js"></script>
<script src="config.js"></script>
<script>
    System.import('main');
</script>
```

I get an error:

```
Uncaught (in promise) http://127.0.0.1:7000/main.js did not call System.register or AMD define
	Error loading http://127.0.0.1:7000/main.js
```

**Comment by guybedford** [comment]
Thanks, that's a bug in the CSP build.

For the normal build, SystemJS needs to know the module format in advance to know to use script tag injection. For globals, it also needs to know the exports in order to use a script tag.

That is - 

```javascript
  System,config({ 
    meta: {
      'main.js': { format: 'amd' },
      'global-file.js': { format: 'global', exports: 'globalName' }
    }
  }0;
```

**Comment by OliverJAsh** [comment]
Thanks!

**Comment by OliverJAsh** [comment]
It's me again! If I specify the format is AMD, this works, but it doesn't seem to work for `format: register`—these are still downloaded as XHRs.

**Comment by guybedford** [comment]
Which module format is this for? You're definitely running the latest version? If so then maybe.

**Comment by OliverJAsh** [comment]
Both AMD and register. Yes, I am definitely running the latest version. Will try to repro is an isolated test case.

**Comment by guybedford** [comment]
Interesting, are you sure you're specifying the meta correctly? Note that if it is a package, you have to refer to the main itself and not just the package name when doing the meta. If you can share the config, I can try suggest why it's not applying.

**Comment by OliverJAsh** [comment]
If I specify the format as AMD, System downloads via XHR but then throws an error because the contents of the file are System.register. So, I know it is honouring the format.

**Comment by guybedford** [comment]
Strange, is this even on a simple model test case? I did a test earlier and it was definitely script-loading for me. Perhaps can you share a repo?

**Comment by OliverJAsh** [comment]
Could it be because my file, `core`, is being mapped to a bundle?

**Comment by guybedford** [comment]
Ah, then you need to declare the bundle module is a bundle - configuring the meta for the bundle to set `bundle: true` or setting the `format: 'register'` should work. Try the first one first though. Bundles when known to be bundles should have this automatically though certainly.

**Comment by OliverJAsh** [comment]
Thank you!

**Comment by davidecantoni** [comment]
Is the bug in the CSP build fixed?
If i run systemjs with the CSP version on IE9 i get the same error that @OliverJAsh had.
Thanks for your feedback.

**Comment by guybedford** [comment]
@davidecantoni System-CSP should definitely be working. Are you just getting this error in IE9? Further info here would be appreciated.

**Comment by davidecantoni** [comment]
@guybedford i am using SystemJS v0.18.17

The first problem i am facing is that systemjs is undefined if i load a single compressed file including:
- csp-production.js
- config.js
- main-bundle.js // not --injected
- init.js // where i execute System['import']("js/src/main.js"); from the main-bundle.js

Note: This is happen in all IE versions.
system-polyfill.js is in the same directory and it get's fetched by the library.
The problem is, i think, related to the issue mentioned here #770 

Now back to the csp-production problem i am facing:
```
Potentially unhandled rejection [13] http://demo.localhost/js/dist/bundle-user-box.min.js did not call System.register or AMD define
	Error loading http://demo.localhost/js/dist/bundle-user-box.min.js
	Error loading http://demo.localhost/js/src/modules/user-box.js (WARNING: non-Error used) 
Potentially unhandled rejection [14] http://demo.localhost/js/dist/bundle-google-maps.min.js did not call System.register or AMD define
	Error loading http://demo.localhost/js/dist/bundle-google-maps.min.js
	Error loading http://demo.localhost/js/src/modules/google-maps.js (WARNING: non-Error used) 
```

This is my config file:
```
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "github:*": "jspm_packages/github/*",
    "bower/*": "bower_components/*",
    "modules/*": "js/src/modules/*",
    "plugins/*": "js/src/plugins/*",
    "vendor/*": "js/src/vendor_local/*"
  },
  bundles: {
    "js/dist/bundle-detail-page.min.js": [
      "modules/detail-page",
      "plugins/pf-report-property",
      "plugins/slideshow",
      "bower/slick.js/slick/slick"
    ],
    "js/dist/bundle-google-maps.min.js": [
      "modules/google-maps",
      "plugins/pf-google-maps"
    ],
    "js/dist/bundle-user-box.min.js": [
      "modules/user-box",
      "plugins/pf-authentication",
      "plugins/pf-userbox",
      "bower/ractive/ractive-legacy"
    ]
  },

  map: {
    "blazy": "bower/blazy/blazy.js",
    "bloodhound": "vendor/bloodhound.js",
    "cookie": "bower/jquery.cookie/jquery.cookie.js",
    "detectmobile": "vendor/detectmobilebrowsers.js",
    "form": "vendor/jquery.form.js",
    "format": "bower/number-format.js/lib/format.min.js",
    "h5validate": "bower/h5validate/h5validate.js",
    "hoverIntent": "bower/jquery-hoverintent/jquery.hoverIntent.js",
    "jquery": "vendor/jquery-global.js",
    "mediator": "modules/mediator.js",
    "mediatorlib": "bower/mediator/mediator.min.js",
    "money": "bower/money.js/money.js",
    "ractive": "bower/ractive/ractive-legacy",
    "readmore": "vendor/readmore.js",
    "replace": "plugins/pf-replace-options",
    "slick": "bower/slick.js/slick/slick.js",
    "smartbanner": "bower/jquery.smartbanner/jquery.smartbanner.js",
    "sticky": "vendor/jquery.sticky.js",
    "tooltipster": "bower/tooltipster/js/jquery.tooltipster.js",
    "typeahead": "vendor/typeahead.jquery.js",
    "underscore": "bower/underscore/underscore.js"
  }
});
```

Please let me know in case you need more information.

**Comment by guybedford** [comment]
@davidecantoni yes this would happen - the reason is that SystemJS will not define itself until the URL and Promise polyfills have been loaded first, so that in your bundle the `config.js` part is failing because Systemj is not yet defined.

To make this work, try including URL and Promise with script tags for IE cases rather.

**Comment by davidecantoni** [comment]
@guybedford i changed the implementation like this:

```html
    <script src="system-polyfills.src.js"></script>
    <script src="system-csp-production.src.js"></script>
    <script src="config.js"></script>
    <script src="js/dist/bundle-main.min.js"></script>
    <script>
        System['import']('//code.jquery.com/jquery-1.11.3.min.js').then(function() {
            executePF();
        }, function(error) {
            console.log(error);
            // fallback to local jquery version
            System['import']('js/src/vendor_local/jquery.min.js').then(function() {
                executePF();
            })
        });
    </script>
```

the problem is happening here:
https://github.com/systemjs/systemjs/blob/master/dist/system-csp-production.src.js#L2014-L2015

If i log the value of ```load.metadata.registered``` on not IE it prints true for loaded files which is fine.
On IE it is printing false for the bundled files and jQuery (//code.jquery.com/jquery-1.11.3.min.js) which are lazy loaded.
This is throwing the error ...did not call System.register or AMD define
Do i have to add a meta config for the bundle files and the external one (//code.jquery.com/jquery-1.11.3.min.js)?

**Comment by guybedford** [comment]
@davidecantoni I've added this test in https://github.com/systemjs/systemjs/commit/f670e8b7ccbec2a9356003331e1a8315d377008c and it's definitely working fine for me in IE11. If you're able to share a simple replication for this that would be really useful here, as it would be great to track down and ensure this isn't a bug.

**Comment by davidecantoni** [comment]
Hello @guybedford 

Please check this comment: #770 

And pay attention on this implementation with single files:
https://github.com/davidecantoni/systemjs-ie/blob/master/public/index.html#L33-L48

and the one with a single file:
https://github.com/davidecantoni/systemjs-ie/blob/master/public/index.html#L51

Only concern to add is that ```[OK] lazy init``` gets triggered twice.

**Comment by guybedford** [comment]
@davidecantoni is this the same question answered in https://github.com/systemjs/systemjs/issues/770#issuecomment-141966612?

**Comment by davidecantoni** [comment]
@guybedford yes, thanks for answering

**Comment by cdll** [comment]
marked~
