### ISSUE TITLE
Invalid paths when requiring module loaded from Github

### ISSUE THREAD

**Issue by lyptt** [systemjs/systemjs#520]
I have the following two dependencies in my System.config map:

```json
    "auth0/angular-jwt": "github:auth0/angular-jwt@0.0.9",
    "auth0/angular-storage": "github:auth0/angular-storage@0.0.11"
```

Neither of these dependencies load correctly. They both end up appending an extra '.js' on the end of the filename when they're imported. I've tried every combination I can possibly think of but nothing seems to stop that extra '.js' being appended.

I'm using JSPM so I'm not sure how that effects things. I can't seem to find any info on this one, nor even what version of SystemJS I'm using. Some assistance with this would be very helpful.

**Comment by guybedford** [comment]
Make sure you use jspm 0.15 against SystemJS 0.16 and jspm 0.16 beta against SystemJS 0.17.

Also if you've upgraded to jspm 0.16 beta, make sure you run `jspm init` to upgrade your config file.

**Comment by lyptt** [comment]
How would I go about verifying my version of SystemJS? I'm on v0.15.7 of JSPM, but I have no idea how to check my SystemJS version.

**Comment by guybedford** [comment]
Ok sure, that isn't the issue then. Do the requires within those projects have existing `.js` extensions? Automatic js extension adding is in jspm 0.15, upgrading to 0.16 beta may help.

**Comment by lyptt** [comment]
I don't think it's even hitting the script unfortunately. The directory structure looks like this:

```
auth0/
    angular-storage@0.0.11/
        dist/
            angular-storage.js
    angular-storage@0.0.11.js
```

The file in dist has no requires whatsoever, and the file outside of dist has the following as its contents:

```javascript
module.exports = require("github:auth0/angular-storage@0.0.11/index");
```

**Comment by guybedford** [comment]
Right - this is just standard jspm configuration then. The package.json file declares the main as `index.js` which is what jspm is using (https://github.com/auth0/angular-storage/blob/master/package.json#L4).

You need to override this with the correct main then - `jspm install github:auth0/angular-storage -o "{main:'angular-storage.js'}"`.

**Comment by lyptt** [comment]
I've installed again using your specified command and I still get a 404. It appears to not even be attempting to load from JSPM now:

```
GET http://127.0.0.1:1337/js/auth0/angular-storage.js.js 404 (Not Found)
```

My import statement is as follows:

```javascript
import _dep_AngularStorage from 'auth0/angular-storage';
```

And the JSPM line remains the same after this change: 

```json
"auth0/angular-storage": "github:auth0/angular-storage@0.0.11"
```

**Comment by guybedford** [comment]
Did you ever upgrade to the jspm beta? Note that your config would have been changed in the process.

One way to check is if you have `*: *.js` in your paths then you're on 0.15, if you have `defaultJSExtensions: true` then you're on the 0.16 beta. If you have both, then you're in a bad place :)

**Comment by lyptt** [comment]
No I don't think so. I've got ```"*": "*.js"``` in my paths, and no ```defaultJSExtensions``` at all.

Here's my complete config.js:

```javascript
System.config({
  "baseURL": "/js",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "es6.spec.blockScoping",
      "es6.spec.symbols",
      "es6.spec.templateLiterals",
      "asyncToGenerator",
      "minification.memberExpressionLiterals",
      "minification.propertyLiterals",
      "spec.undefinedToVoid",
      "validation.undeclaredVariableCheck"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.4.0",
    "angular-mocks": "github:angular/bower-angular-mocks@1.4.0",
    "angular-ui-router": "github:angular-ui/ui-router@0.2.15",
    "auth0/angular-jwt": "github:auth0/angular-jwt@0.0.9",
    "auth0/angular-storage": "github:auth0/angular-storage@0.0.11",
    "babel": "npm:babel-core@5.5.8",
    "babel-runtime": "npm:babel-runtime@5.5.8",
    "chieffancypants/angular-loading-bar": "github:chieffancypants/angular-loading-bar@0.7.1",
    "core-js": "npm:core-js@0.9.17",
    "dwmkerr/angular-modal-service": "github:dwmkerr/angular-modal-service@0.6.6",
    "ivpusic/angular-cookie": "github:ivpusic/angular-cookie@4.0.6",
    "jquery": "github:components/jquery@2.1.4",
    "lodash": "npm:lodash@3.9.3",
    "moment": "github:moment/moment@2.10.3",
    "stealjs/system-json": "github:stealjs/system-json@0.0.3",
    "systemjs/plugin-json": "github:systemjs/plugin-json@0.1.0",
    "wildlyinaccurate/angular-readable-time": "github:wildlyinaccurate/angular-readable-time@0.1.1",
    "github:angular-ui/ui-router@0.2.15": {
      "angular": "github:angular/bower-angular@1.4.0"
    },
    "github:angular/bower-angular-mocks@1.4.0": {
      "angular": "github:angular/bower-angular@1.4.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.5.8": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.17": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:lodash@3.9.3": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});


```

**Comment by guybedford** [comment]
Did you really try the override I suggested?

If you look at the main it contains a ".js" require, which would exactly cause your issue - https://github.com/auth0/angular-storage/blob/master/index.js.

This is all part of the process of moving to full modularity. It does take some effort to dive in though.

**Comment by guybedford** [comment]
Note that in the new beta, extensions can be "optional", which will make this more flexible in future.

**Comment by lyptt** [comment]
I absolutely did. My package.json got updated with the following:

```json
"jspm": {
    "directories": {},
    "configFile": "jspm-config.js",
    "dependencies": {
      "angular": "github:angular/bower-angular@^1.4.0",
      "angular-mocks": "github:angular/bower-angular-mocks@^1.4.0",
      "angular-ui-router": "github:angular-ui/ui-router@^0.2.15",
      "auth0/angular-jwt": "github:auth0/angular-jwt@^0.0.9",
      "auth0/angular-storage": "github:auth0/angular-storage@^0.0.11",
      "chieffancypants/angular-loading-bar": "github:chieffancypants/angular-loading-bar@^0.7.1",
      "dwmkerr/angular-modal-service": "github:dwmkerr/angular-modal-service@^0.6.6",
      "ivpusic/angular-cookie": "github:ivpusic/angular-cookie@^4.0.6",
      "jquery": "github:components/jquery@^2.1.4",
      "lodash": "npm:lodash@^3.9.3",
      "moment": "github:moment/moment@^2.10.3",
      "stealjs/system-json": "github:stealjs/system-json@^0.0.3",
      "systemjs/plugin-json": "github:systemjs/plugin-json@^0.1.0",
      "wildlyinaccurate/angular-readable-time": "github:wildlyinaccurate/angular-readable-time@^0.1.1"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    },
    "overrides": {
      "github:auth0/angular-storage@0.0.11": {
        "main": "angular-storage.js"
      }
    }
  }
```

**Comment by guybedford** [comment]
I guess the main isn't `angular-storage.js` though? It should probaby be `dist/angular-storage.js`.

**Comment by lyptt** [comment]
That did the trick, thanks. Will this change at all for 0.16, or can I safely continue using overrides to fix this situation?

**Comment by guybedford** [comment]
The override will be fine to use.

**Comment by lyptt** [comment]
Cool, thanks for the help!
