### ISSUE TITLE
Get module location synchronously

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#521]
Is this possible?  Right now I'm doing the following to set `ace`'s `basePath`, for example:

```js
var ace = require('ace/ace');

var defined = System.defined;
var aceTest = /\/ace(|\.js)$/;
var aceName = null;

for (var key in defined) {
  if (aceTest.test(key)) {
    aceName = key;
    break;
  }
}

if (!aceName) {
  throw new Error('Ace not defined?');
}

System.locate({name: aceName, metadata: {}}).then(function (aceLocation) {
  // point ace to the proper directory for its files
  aceLocation = aceLocation.replace(window.location.origin, '');
  aceLocation = aceLocation.replace('/ace.js', '');
  ace.config.set('basePath', aceLocation);
});
```

As you can see, it's pretty ugly.  Plus I'm running into problems with `ace` attempting to retrieve themes/extensions/etc. before the `basePath` is actually set, so if this can be done synchronously somehow, it would solve that problem.

**Comment by guybedford** [comment]
This is `__filename` in CommonJS.

**Comment by timbur** [comment]
That's only for `ace`'s scope though right?

I just tried this and console logs `undefined`:
```js
var ace = require('ace/ace');
console.log(ace.__filename);
```

**Comment by guybedford** [comment]
Right. In the latest SystemJS (0.17) this is possible via `System.normalizeSync('ace')` although this isn't officially an API that will necessarily stick around.

**Comment by timbur** [comment]
Sweet.  I saw `normalizeSync` earlier today but didn't consider using it.  I think I tried v0.16's `normalize` yesterday and it wasn't giving me the full URL (just `github:ajaxorg/ace-builds@^1.1.9` I believe)?  In any case, thanks a ton.  What are your thoughts on offering `*Sync` versions of methods where possible?  I think it might simplify/solve problems for certain use-cases like the example I've provided.

**Comment by timbur** [comment]
How can I make `normalizeSync` (or something equivalent) work when `ace` (for example) is a dependency of a dependency?

**Comment by guybedford** [comment]
@timbur `System.normalizeSync('ace', System.normalizeSync('dependency-parent-of-ace'))`

**Comment by timbur** [comment]
AWESOME.  Thanks!

**Comment by timbur** [comment]
I feel like I'm losing my friggin' mind.  This is no longer working for me.

Within my top package's `config.js`, I have `web-tedit` clearly mapped along with it's `ace` dependency:
```js
System.config({
  "map": {
    ...
    "web-tedit": "github:loggur/web-tedit@master",
    ...
    "github:loggur/web-tedit@master": {
      "ace": "github:ajaxorg/ace-builds@1.2.0",
      ...
    }
});
```

When `web-tedit` initializes `ace`, it does the following:
```js
var ace = require('ace');
var acePath = System.normalizeSync('ace', System.normalizeSync('web-tedit'));

// Set ace's basePath
acePath = acePath
  .replace(window.location.origin, '')
  .replace(/\.js$/, '');
ace.config.set('basePath', acePath);
```

`web-tedit` resolves fine but `ace` does not.  I don't understand how this could be happening when everything is clearly mapped within `config.js`.

**Comment by timbur** [comment]
In the mean time, this seems to work reliably:
```js
var teditPath = System.normalizeSync('web-tedit')
  .replace(/\.js$/, '');

var acePath = System.normalizeSync(System.packages[teditPath].map['ace'])
  .replace(window.location.origin, '')
  .replace(/\.js$/, '');
```

**Comment by guybedford** [comment]
@timbur yes this isn't working - I've created https://github.com/systemjs/systemjs/issues/585. There were some adjustments around normalization that altered this within normalizeSync. Will aim to get it back in.

**Comment by timbur** [comment]
Thanks.  I'm probably still losing my mind but glad to know I'm not losing it completely lol.

**Comment by guybedford** [comment]
@timbur it may be best just to use `System.normalize` here instead of `System.normalizeSync` if you can. normalizeSync is a private API currently, and including package map in normalizeSync has some detailed implications that need to be carefully weighed up.

**Comment by timbur** [comment]
I will say, being able to normalize some module name synchronously is really convenient and makes  things easier in terms of not having to worry about the order of events, but I can understand normalization needing to be asynchronous in many cases.

There are a few other things I've run into when extending `System` and creating plugins that I also feel could be easier, as I know that information is already there within the internals of `systemjs` and it feels silly to "re-extract" it.  For instance, it would be really helpful in some cases to quickly know the context of some `load` within a plugin or patch.  (If there's already a way to quickly get the context from within a plugin, I guess I'm just being blind and dumb again lol.)  If you want, I'd be glad to make a note of some things that I think would be really helpful in allowing people to extend `systemjs` functionality.

**Comment by guybedford** [comment]
What sort of extra information are you looking for within a plugin? The plugin hooks have all the load metadata on the `load` object passed to the plugin.

**Comment by timbur** [comment]
The stuff I've run into might be more specific to my particular use-case, which sort of revolves around the ability to configure `systemjs` on-the-fly - e.g., add and remove modules and packages dynamically in a live editing environment.  For most projects this extra information would probably be useless.  But for instance, yesterday I remember thinking it would be useful to know within `System.fetch` which module was fetching the module.  I don't remember the use-case exactly, but it was along the lines of one module importing another module that did not yet exist, and so it needed to possibly be mapped to the contextual module's config before continuing (maybe via some user prompt or something).

That is of course just a single (probably silly) example, but I have run into a handful of things like this.  I can get by one way or another, and I'm definitely not trying to volunteer you for anymore work, but I'd be glad to make a note of things like this as I go along and share them with you if you think it might be beneficial to other plugin authors.

Also, there was another issue quickly closed recently that I think I did a bad job of explaining, and it was in the same vein.  I'll comment on it again with hopefully a better explanation.
