### ISSUE TITLE
Mapping overrides default extension

### ISSUE THREAD

**Issue by anzeo** [systemjs/systemjs#524]
I'm trying to get System.js to play along with Angular2 and the new typescript transpiler option (introduced in 0.17). However I can't seem to get the mapping correctly.

I have angular2 installed under my `node_modules`, while I have my sources under `src`. This is my System.js configuration:

```javascript
System.config({
    transpiler: 'typescript',
    packages: {
        '/src': {
            main: 'app',
            defaultExtension: 'ts'
        },
        '/node_modules/angular2': {
            main: 'angular2',
            defaultExtension: 'js',
            map: {
                'rx': './node_modules/rx/index.js'
            }
        }
    },
    map: {
        // Added a path for ng2 because internal they require modules as 'angular2/src/...'
        angular2: '/node_modules/angular2/',
        typescript: '/lib/typescript@v1.5-beta2/bin/typescript.js'
    }
});
```

As you can see I'm trying to make use of the new packgaes configuration to set the default extension per package. This works great, except for one issue: somewhere in the code the `rx` is required by Angular2. Without the mapping configuration, System.js tries to resolve the Rx package on the path

    localhost/rx

Which is obviously wrong. With the mapping in place, the package is correctly located, but `require`s are no longer automatically postfixed with my default extension. So I get a bunch of 404s regarding the requires in the Rx package.

Am I doing anything wrong here? You can find the code on [this Github repository of mine](https://github.com/anzeo/Typsy)

**Comment by guybedford** [comment]
You'll need to separately add the `defaultExtension` option to the rx package here.

**Comment by anzeo** [comment]
Thanks for your fast reply. I tried this, by updating my config to:

```javascript
System.config({
    transpiler: 'typescript',
    packages: {
        '/src': {
            main: 'app',
            defaultExtension: 'ts'
        },
        '/node_modules/angular2/node_modules/rx': {
            main: 'index',
            defaultExtension: 'js'
        },
        '/node_modules/angular2': {
            main: 'angular2',
            defaultExtension: 'js',
            map: {
                'rx': './node_modules/rx'
            }
        }
    },
    map: {
        // Added a path for ng2 because internal they require modules as 'angular2/src/...'
        angular2: '/node_modules/angular2/',
        typescript: '/lib/typescript@v1.5-beta2/bin/typescript.js'
    }
});
``` 

I can correctly target the Rx package now (thank you for that!). However, all `require`s from there on are still not resolved with the default extension.

If I update the default extension to `foo` I correctly get a 404 for

    localhost/node_modules/angular2/node_modules/rx/index.foo

**Comment by guybedford** [comment]
Can you share a test case here?

**Comment by anzeo** [comment]
Working on it!

If you have time, you could already verify the issue by cloning my repo, running npm install and then just open up the index file. I don't have a lot of time left today, so might be postponed to tomorrow. Thanks for the quick assistance.

**Comment by guybedford** [comment]
Let me know if you need any further assistance here.
