### ISSUE TITLE
SystemJS not treating file as ES6 code with System.import

### ISSUE THREAD

**Issue by lyptt** [systemjs/systemjs#526]
I'm at the stage where I'm moving my Jasmine tests over to ES6, but it seems like SystemJS is refusing to treat the code as ES6.

I'm making use of the karma-jspm plugin to integrate JSPM into Karma, and Babel for transpiling my code to ES5.

With the following spec file:
```javascript
import Application from '../app';
import angular from 'angular';
import 'angular-mocks';

describe('Something here', function() {
	
});

export default {};
```

I get the error `Line 5: Reference to undeclared variable "describe"`. If I swap out all of the import statements for `require`s this error goes away, but then complications arise in mixing the two module loading formats. 

All of my other code now uses ES6, so it causes issues when attempting to require ES6 modules as it seems that these modules return object wrappers instead of the actual exported object.

I'm using the approach of loading my spec files directly, and serving the core application code along with any other dependent resources. I've noticed that the karma-jspm plugin attempts to go through every directly loaded file and `System.import` it, so I'm not sure if there's something around that causing the issue.

I've noticed that stripping out the imports completely and simply attempting to use any ES6 feature like arrow functions for example throws up syntax errors, so it does seem like my tests aren't being passed through Babel at all.

**Comment by guybedford** [comment]
The issue here is rather that `describe` is not being declared as a global it seems. I guess this has to do with the execution profile of ES6 against CommonJS perhaps.

I suppose this is specific to the way describe is defined by the testing system.

When using no module syntax it is exactly right that code is not transpiled - transpilation support is only provided for the Module entry point and not Script currently.

**Comment by lyptt** [comment]
Interestingly enough though, when running under Karma's debug mode I am able to access describe as a global variable. 

It only seems to be within the context of SystemJS that I do not have access to it. I've even verified that just before my tests are loaded by SystemJS, describe is available as a global variable, so I'm not sure it's that simple.

**Comment by guybedford** [comment]
@lyptt perhaps look into if it is always defined or only defined synchronously for tests.

**Comment by milkshakeuk** [comment]
@lyptt have a look at how I am running my unit tests using systemjs without a karma adapter https://github.com/milkshakeuk/tsdemo/tree/jspm?files=1

**Comment by guybedford** [comment]
Closing as a support issue, but let me know if I can help further.
