### ISSUE TITLE
Plugin removes .js

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#528]
``` js
System.paths['googletag'] = "//www.googletagservices.com/tag/js/gpt.js";
System.import('googletag!system-script');
```

`googletag` will resolve to `http://www.googletagservices.com/tag/js/gpt`. Shouldn't it resolve to `http://www.googletagservices.com/tag/js/gpt.js`?

**Comment by guybedford** [comment]
I'm really not sure how to tackle this one actually.

It's really a backwards-compatibility issue for something that's always been awful - paths adding .js extensions, and the plugin system removing them by default.

The plugin system has no way of knowing if the js extension was added intentionally by the path or defaultJSExtensions.

I'd suggest the workaround of importing `googletag.js` and setting a path for that.

This issue doesn't happen with `defaultJSExtensions` disabled, so at least it's a pain point that is going away.

May have to mark this as a wontfix / cantfix!

**Comment by guybedford** [comment]
Going to have to do the wontfix here unfortunately...
