### ISSUE TITLE
Clone with same map config

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#529]
I want to create a new System (aka clone, `new System.constructor()`).

I want it to share the same config as my old System.

`newSystem.config({ map: oldSystem.map })` will not suffice, because `map` is transformed by System.

Could we add a way to read out the original config? Or should I do this another way?

**Comment by guybedford** [comment]
I guess keeping your initial config around to use again would be the suggested way to do this.

**Comment by OliverJAsh** [comment]
Ah, just realised I can do `newSystem.config({ packages: oldSystem.packages })`
