### ISSUE TITLE
Bower install

### ISSUE THREAD

**Issue by kokujin** [systemjs/systemjs#53]
On the "Getting started" page:
https://github.com/systemjs/systemjs#getting-started

It states:
"Download es6-module-loader.js and traceur.js from the ES6-loader polyfill and locate them in the same folder as system.js from this repo.
Then include dist/system.js with a script tag in the page:"
1. The traceur.js resolves into a 404 and does not exist physically in the repo.
2. Would'nt it be better just to "bower install system.js" and be done?

Thanks

**Comment by brettz9** [comment]
Might not `es6-module-loader.js` be added as a dependency and moved during installation into the dist folder for convenient one-command-install and single-script-HTML-inclusion?

**Comment by Waog** [comment]
+1
