### ISSUE TITLE
CSP: support transpiling in eval environments

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#531]
Chrome Extensions allow you to modify CSP to allow usage of `eval` (`script-src 'self' 'unsafe-eval'`), but not inline scripts (`unsafe-inline`). This means that, unless you're not transpiling and using the CSP version, you must bundle.

Could SystemJS optionally use `eval` instead of [injecting transpiled code using an inline script tag](https://github.com/systemjs/systemjs/blob/15cb1e2f82c0ca541213fbcfe07fbe81e2ee2588/lib/global-eval.js#L38-L55)? Perhaps there is a reason we are using inline script tags over `eval`? Could `eval` be supported behind an option, for the sake of enabling a nice "refresh to reload" workflow when working in environments such as Chrome Extensions?

**Comment by guybedford** [comment]
Certainly we can support this by passing through to this conditional - https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L60.

It's just about coming up with an adequate feature detection that will work in this scenario.

The reason we use `<script>` injection is to preserve maximum global compatibility for global assignments via `var global = 'val'`.

**Comment by OliverJAsh** [comment]
How about `window.chrome && window.chrome.extension`?

**Comment by guybedford** [comment]
Also relevant - https://github.com/systemjs/systemjs/issues/421#issuecomment-114055907.

**Comment by guybedford** [comment]
Added https://github.com/systemjs/systemjs/commit/be2db270a3701ea034bf52b83ca757d57ed95a54. This does need much more testing though. Feedback very welcome.

**Comment by OliverJAsh** [comment]
I will test this when it's available in the dist folder.

**Comment by guybedford** [comment]
Thanks, that would be great - I've finished for the day here and hoping to release soon, so consider the dist build on master the release candidate.

**Comment by guybedford** [comment]
Released in 0.18.2.

**Comment by OliverJAsh** [comment]
This works perfectly. Thank you.

**Comment by guybedford** [comment]
Awesome, thanks for the quick feedback!

**Comment by jaysonminard** [comment]
So, can get a quick usage description?  This is for the non CSP version, it now auto-detects if in chrome extension environment and uses eval to load.  Correct?

**Comment by jaysonminard** [comment]
Ok, seems like I don't need the description.  I tried the system.js from 0.18.2 in my content script of a chrome plugin, and it worked fine.  First load didn't complete in time for chrome to abandon the content script, but cached load did.  Will check that is what I think it is and confirm...

**Comment by jaysonminard** [comment]
see #421 for more info, but working fine in all aspects of a chrome extension, that rocks!
