### ISSUE TITLE
Updated to JSPM, complains about multiple system.register calls in a module file, but there is only 1

### ISSUE THREAD

**Issue by robertbaker** [systemjs/systemjs#532]
https://github.com/robertbaker/ng-next-gen

This is a fork, only changes was setting transpiler to typescript and installing jspm@beta and the dl-loader.

```
jspm@beta - Uncaught TypeError: Multiple anonymous System.register calls in the same module file.
localhost/:1 Uncaught (in promise) Uncaught TypeError: Multiple anonymous System.register calls in the same module file.
Evaluating http://localhost:9238/app/attributes/drop-action.js
Error loading http://localhost:9238/app/boot.js
```

js:
```
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
    switch (arguments.length) {
        case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
        case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
        case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
    }
};System.register(['ng-decorate'], function(exports_1) {
    var ng_decorate_1;
    var VM;
    return {
        setters:[
            function (_ng_decorate_1) {
                ng_decorate_1 = _ng_decorate_1;
            }],
        execute: function() {
            VM = (function () {
                function VM() {
                }
                VM.link = function (scope, $element) {
                    var element = $element[0];
                    var statement = VM.$parse(element.getAttribute('drop-action'));
                    element.addEventListener('dragover', function (event) {
                        event.preventDefault();
                        element.classList.add('dragover');
                    });
                    element.addEventListener('dragleave', function () {
                        element.classList.remove('dragover');
                    });
                    element.addEventListener('drop', function (event) {
                        element.classList.remove('dragover');
                        statement(scope, {
                            $event: event,
                            $data: event.dataTransfer.getData('any')
                        });
                        scope.$applyAsync();
                    });
                };
                __decorate([
                    ng_decorate_1.autoinject
                ], VM, "$parse");
                VM = __decorate([
                    ng_decorate_1.Attribute({
                        selector: '[drop-action]'
                    })
                ], VM);
                return VM;
            })();
        }
    }
});
```

**Comment by robwormald** [comment]
@robertbaker this is a known issue (and I probably should have mentioned in the angular2 note i made) - TypeScript doesn't yet support System.register *bundling* - that is, you can transpile it on the fly, or server side, but bundling all that into a single module is not yet supported.

It's on the TS roadmap for version 1.6, so it's coming - in the interim, if you really want to build a bundle, I've been outputting ES6 from TS, and then using the bundler + babel or traceur to build the bundle. Bit of a faff, but it works.

Check out my gulpfile for some hints on that https://github.com/robwormald/ng2-jspm-seed/blob/master/gulpfile.js

**Comment by robertbaker** [comment]
I'm not doing a bundle build and I'm still using 1.4. It seems my mistake
is using the ts transpiler in the system.config.

I'll take a look at your seed more, looks like you output ts to es6. Then
I'm guessing systemjs transpiles that to es5?

Wouldn't it be better to just have ts output to es5 and use no transpiler
for systemjs?

**Comment by robwormald** [comment]
Yeah, i'm transforming from TS -> ES6. My reasoning there is given everything else is going be bundled via traceur or babel, I'd rather start from as close-to-source as possible - TS -> ES6 does the least amount of transformation. Ymmv.

**Comment by robwormald** [comment]
Clarification: there are basically two uses cases in play here - during development, I just load Typescript files directly off disk via the SystemJS loader (which uses TS 1.5beta2 iirc). Thats pretty seamless, its just the bundle step that's a bit of a faff.

**Comment by robertbaker** [comment]
Wouldn't converting TS to JS in the browser be slower?

**Comment by guybedford** [comment]
Did you manage to make progress here?

**Comment by robertbaker** [comment]
@guybedford I did. I have JSPM working, minus the bundling part. So many things changed, couldn't tell you what the solution was. But I ended up changing my config and gulp tasks.
