### ISSUE TITLE
System._extensions

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#533]
``` js
System.normalize = function {
    // …
};
System._extensions.push(function(loader) {
    loader.normalize = System.normalize;
});
```

`System._extensions` is no longer available in 0.18.

Is there an alternative? I've looked in the source, but to no avail.

I do this before using the Node API to bundle.

**Comment by OliverJAsh** [comment]
Previously, I had to do this to get module IDs containing plugins don't seem to route through my normalize function.

**Comment by guybedford** [comment]
Yes this was deprecated for standard class extensions.

You can directly modify the prototype of SystemJS, but that probably isn't advisable. I've created https://github.com/systemjs/builder/issues/207.

**Comment by OliverJAsh** [comment]
`extensions` are not on the prototype?

Happy to use a hack for now until we have something proper!

**Comment by guybedford** [comment]
Yes they happen in the constructor, so you add an extension by extending `System.constructor` then extending the normalize instance within the new constructor. Basically the constructor is the new extension function. Once you've initialized a new extended constructor, it can be passed to `builder.reset(newSystemInstance)`. We should be able to handle this use case better though.

**Comment by OliverJAsh** [comment]
OK, here's what I've got:

``` js
/*eslint-env node*/
'use strict';

var path = require('path');

var System = require('jspm/node_modules/systemjs');

var PatchedSystem = function (oldSystem) {
    oldSystem.constructor.call(this);
    this.config({
        baseURL: oldSystem.baseURL,
        paths: { '*': 'javascripts/*' }
    });
    this.normalize = function () {
        console.log('normalize');
        return 'foo';
    };
};
PatchedSystem.prototype = Object.create(System);

var jspm = require('jspm');
var builder = new jspm.Builder();
var newSystem = new PatchedSystem(builder.loader);
builder.reset(newSystem);
builder.build('core', null)
    .then(function (output) {
        console.log(output);
    })
    .catch(function (error) {
        console.error(error.stack);
    });
```

Unfortunately this won't work because `builder.reset` doesn't copy across `paths` or `normalize`, only `baseURL`:

https://github.com/systemjs/builder/blob/7a71fdb39a98adc219fc7daa5d7a14ce190e3aa1/lib/builder.js#L72

**Comment by OliverJAsh** [comment]
I hacked this in the end by setting `new jspm.Builder().loader.normalize = function () {}`.

**Comment by OrKoN** [comment]
@guybedford @OliverJAsh what's the right way to override normalize hook in 0.16.0? I need to extend it and call the default normalize hook.

**Comment by OrKoN** [comment]
Did like @OliverJAsh suggested:

```js
gulp.task('jspm', function() {
  var builder = new jspm.Builder();

  function productionVersions(builder) {
    var systemNormalize = builder.loader.normalize;
    builder.loader.normalize = function(name, parentName, parentAddress) {
      if (name === 'ember') {
        name = 'ember/ember.prod';
      }

      if (name === './env.dev') {
        name = './env.prod';
      }

      return systemNormalize.call(this, name, parentName, parentAddress);
    };
  }

  productionVersions(builder);

  return builder.loadConfig('./system.config.js')
    .then(function() {
      return builder.buildSFX('.tmp/boot', 'dist/app.min.js', { sourceMaps: false, minify: true, mangle: true});
    });
});
```
