### ISSUE TITLE
Code style?

### ISSUE THREAD

**Issue by nyarly** [systemjs/systemjs#537]
This is intended much more as a discussion point than a real issue but:

There are some stylistic idiosyncrasies across the systemjs project that give me (and JSHint) pause. Notably, (aside from occasional semicolon omissions), there's {}-less ifs. My experience has been that both omissions tend to be error-prone, and I wanted to check in to see if there was a strong feeling about keeping them.

**Comment by guybedford** [comment]
Yes development is not done against JSHint which can cause editor issues. The style is roughly captured in https://github.com/jspm/jspm-cli/blob/master/.jshintrc although it won't match exactly.

Note that static analysis of the code files will always error though as we are concatenating sources for building so static analysis breaks down (free globals will be incorrectly detected).

In terms of the general style though, it is pretty set.

**Comment by guybedford** [comment]
Closing, but let me know if you'd like to contribute.
