### ISSUE TITLE
Including same modules in two other modules fails

### ISSUE THREAD

**Issue by TitanNano** [systemjs/systemjs#541]
I'm sorry if the title isn't very descriptive, but it's hard to explain the issue in short.
What I'm doing:

module_a.js includes module_b.js
module_c.js includes also module_b.js, but also module_a.js

I'm doing this because B provides functions A and C need. But I always get an error.
```
TypeError: Multiple anonymous System.register calls in the same module file.
```
As soon as I remove the import of B in C it works properly.

All modules are already transpiled by Bable into the SystemJS format.

**Comment by TitanNano** [comment]
UPDATE: It works fine in Chrome. The issue only occurs in Firefox.

**Comment by guybedford** [comment]
@TitanNano thanks, are you able to provide a test case for this at all?

**Comment by TitanNano** [comment]
yes I have a local repo where I test my modules. I will push it to GitHub.

**Comment by TitanNano** [comment]
okay, here is the source I'm experiencing the issue with. 
https://github.com/TitanNanoDE/ApplicationFrameTests/ (it also gives a short description on how to set everything up)

I include 
`af/util/make.js` in `scripts/main.js`, 
`util/make.js`     in `af/af.js` and 
`af/af.js`            in `scripts/main.js`

**Comment by guybedford** [comment]
I tested it out but am not able to reproduce any issue in Chrome or Firefox at all - do I need to change something?

**Comment by TitanNano** [comment]
you build with grunt?
I'm on Firefox 40.0a2, but I just tried to run it in Firefox 39.0 as well as in 41.0a1 and it works fine too. 

So I have a mis configuration in my Firefox? Is there anything that could cause such an error?

**Comment by guybedford** [comment]
I'm not sure - if it's specifically in Firefox 40.0a2 could it be a browser bug?

**Comment by TitanNano** [comment]
yes I don't really know. Maybe I need to wait until they move to the next version.
