### ISSUE TITLE
URLPolyfill is not defined with nodejs

### ISSUE THREAD

**Issue by jbe456** [systemjs/systemjs#543]
Using `system-register-only.src.js` version 0.17.1, 0.18.1 or 0.18.2, I run into the following issue when the code run with nodejs:

```
ReferenceError: URLPolyfill is not defined
```

Looking at the latest code:
```
  var URL = __global.URL;
  try {
    new URL('test:///').protocol == 'test:';
  }
  catch(e) {
    URL = URLPolyfill;
  }
```

It cannot run under nodejs because `URL` is undefined. Am I missing something?

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs#polyfills.

**Comment by jbe456** [comment]
Thanks, I loaded the polyfill and at least I have a different issue now ;-)
