### ISSUE TITLE
Root scope globals

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#545]
We have some third party code on our site:

``` js
function foo() {};
window.foo();
```

When loading via XHR, this works. When bundling, however:

``` js
(function () {
    function foo() {};
    window.foo(); // fails
})();
```

Because `foo` is no longer defined in the root scope, it is not added to `window`, so the `window.foo` call fails.

Is there any way to support code such as this when bundling? Shouldn't the two environments (bundling and non-bundling) be identical?

**Comment by guybedford** [comment]
Thanks. The builder detects globals from parse tree analysis. I've created https://github.com/systemjs/builder/issues/211 to ensure the parse tree analysis catches these cases. Will continue to track there.
