### ISSUE TITLE
Load with JSX extension

### ISSUE THREAD

**Issue by silvenon** [systemjs/systemjs#547]
I'm using jspm with babel and I can't seem to figure out how to load `app.jsx`. If I use `System.import('app')`, it's looking for `app.js`, if I try `System.import('app.jsx')`, it's looking for `app.jsx.js`. I can load `app.js` with JSX inside just fine.

I tried adding:

```js
"extensions": [".jsx", ".js"]
```

to `babelOptions` in `config.js`, but it didn't help.

**Comment by guybedford** [comment]
Yes you need to use the latest SystemJS with `defaultJSextensions` not set to load a custom extension. Otherwise use a package configuration in the latest SystemJS to override the defaultJSExtensions behaviour through the package configuration defaultExtension. Adding the js extension used to be the only behaviour, so this backwards-compatibility option is a little painful.

**Comment by silvenon** [comment]
jspm seems to depend on `v0.16.x`, how do I update?

**Comment by guybedford** [comment]
`npm install -g jspm@beta`

**Comment by guybedford** [comment]
The upgrade guide is at https://github.com/jspm/jspm-cli/releases/tag/0.16.0-beta.

**Comment by silvenon** [comment]
Thanks, it works.

**Comment by dmason30** [comment]
@silvenon @guybedford 

Sorry I don't get it:
`
        SystemJS.config({
            meta: {
                '*.jsx': {
                    'loader': 'plugin-babel',
                    'format': 'cjs',
                    'babelOptions': {
                        'modularRuntime': false,
                        stage1: true,
                        presets: ['babel-preset-react']
                    }
                }
            },
        });

        var App = SystemJS.import('assets/js/LogOutButton.jsx').then(LogOutButton => {
            ReactDOM.render(<LogOutButton />, document.getElementById('renderTarget'));
        });
`

![image](https://cloud.githubusercontent.com/assets/20278756/26252054/140b57bc-3ca7-11e7-9740-996d071710ce.png)

Is trying to add '.js' to the imported file, if I add 'defaultJSExtensions ' to the System.config then none of the jspm libraries are able to load as the js extension is not being included in the url:

`
        SystemJS.config({
            meta: {
                defaultJSExtensions: false,
                '*.jsx': {
                    'loader': 'plugin-babel',
                    'format': 'cjs',
                    'babelOptions': {
                        'modularRuntime': false,
                        stage1: true,
                        presets: ['babel-preset-react']
                    }
                }
            },
        });

        var App = SystemJS.import('assets/js/LogOutButton.jsx').then(LogOutButton => {
            ReactDOM.render(<LogOutButton />, document.getElementById('renderTarget'));
        });
`

![image](https://cloud.githubusercontent.com/assets/20278756/26252118/4b716e08-3ca7-11e7-88ce-388d6dc3d0ea.png)
