### ISSUE TITLE
iOS/Mobile Safari 7 trouble with URL constructor

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#548]
In iOS Safari 7 (iOS 7), `window.URL` is available, but it does not return a fully qualified `URLUtils` object:

``` js
new URL('http://foo.com/bar').href
// => undefined
```

According to MDN, `href` is not supported by some browsers, even though they do support the `URL` constructor. https://developer.mozilla.org/en-US/docs/Web/API/URLUtils/href

Should we be [polyfilling](https://github.com/systemjs/systemjs/blob/f2d9db7088d09df2c1bb37f977303236efcafb67/dist/system.src.js#L98) these browsers?

Because of this, `System.normalize` fails.

**Comment by guybedford** [comment]
Make sure you're running on the latest SystemJS - we run a full feature test on URL to ensure it is compatible in https://github.com/systemjs/systemjs/blob/master/lib/wrapper-end.js#L5.

When compatibility fails for `URL` or `Promise` we load the `system-polyfills.js` file automatically. This was badly documented in the update though - it's mentioned at https://github.com/systemjs/systemjs#polyfills, basically it is just like we used to load `es6-module-loader.js` before but for these polyfills.

**Comment by OliverJAsh** [comment]
Unfortunately I am running the latest SystemJS.

`new URL('test:///').protocol == 'test:';` will return `undefined` instead of throwing an exception, so we will [never set `URL = URLPolyfill`](https://github.com/systemjs/systemjs/blob/f2d9db7088d09df2c1bb37f977303236efcafb67/dist/system.src.js#L98) for these devices.

**Comment by guybedford** [comment]
Oh man. Ok I've pushed up https://github.com/ModuleLoader/es6-module-loader/commit/1e961e14b7869430f539909a5d0b164198b101b1, will post out a release in the next few hours with some other small tweaks then.

**Comment by OliverJAsh** [comment]
Perfect. Thank you so much!

**Comment by guybedford** [comment]
Released in 0.18.3.
