### ISSUE TITLE
AMD loader plugin compliance

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#549]
The specification for AMD loader plugins is here:

https://github.com/amdjs/amdjs-api/blob/master/LoaderPlugins.md

It specifies:

> A plugin dependency is a dependency expressed in AMD that is intended to be loaded by a loader plugin. It has the form:
>
> `[Plugin Module ID]![resource ID]`

SystemJS works in reverse, however:

`[resource ID]![Plugin Module ID]`

Switching from RequireJS to SystemJS, this has become a problem for us. We load some third party code on our site. Our contract with them is we will load any code that is AMD compliant. SystemJS does not comply with the specification for AMD loader plugins.

Could we consider making SystemJS fully AMD compliant, perhaps behind an option?

**Comment by guybedford** [comment]
This can certainly be considered as a meta configuration to use an AMD-compatible mode.

**Comment by OliverJAsh** [comment]
It's worth nothing that loader plugins are not actually part of the AMD spec:

> This repo holds the API specifications for AMD and *some APIs that are strongly related to AMD.*

https://github.com/amdjs/amdjs-api

**Comment by Munter** [comment]
I'm runnig into this problem in our migration now as well. Allthough I'm completely ok with not having SystemJS interpret requirejs plugins, but providing my own systemjs compatible plugins under the same name.

However, is there a way I can make SystemJS treat the AMD plugin order of `[Plugin Module ID]![resource ID]` correctly? I just need something to tell it to flip the order around while I'm running in compatibility mode

**Comment by OliverJAsh** [comment]
Hey Peter, on my phone right now but we worked around this using
System.normalize. Search for system normalise in the Guardian/frontend repo

**Comment by Munter** [comment]
Great! That looks easily implementable. Is there a way I can make this only affect amd modules? As soon as I start using cjs or es6 I'd prefer to be on the standard track for systemjs. Incidentally all my legacy plugin using code is amd

**Comment by Munter** [comment]
For anyone looking up this issue later, I enabled amd module loader reversal with this:
```js
(function () {
  var systemnormalize = System.normalize;
  var blacklist = ['systemjs-json'];

  function shouldReverse(parts) {
    return parts.every(function (part) {
      return blacklist.indexOf(part) === -1;
    });
  }

  System.normalize = function (name, parentName) {
    var parts = name.split('!');

    if (parts.length > 1 && shouldReverse(parts)) {
      name = parts.reverse().join('!');
    }

    return systemnormalize.call(this, name, parentName);
  };
})();
```

This script goes after `system.js` and before `config.js`

**Comment by matthewbauer** [comment]
Does this break anything if we put it as a normalize hook in amd.js?

Even though this isn't part of the AMD spec- it is pretty much standard in most AMD modules outside of SystemJS stuff.

**Comment by gig177** [comment]
How to use this patch at bundling environment?

**Comment by guybedford** [comment]
Thanks to @matthewbauer this is now possible via the `System.pluginFirst` switch.

**Comment by matthewp** [comment]
> How to use this patch at bundling environment?

You can't, the SystemJS Builder doesn't support custom extensions, and last I checked cannot, as an implementation choice.
