### ISSUE TITLE
Babel/ES6 source maps off by one line

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#550]
If I transpile the following code in my browser:

``` js
"format es6";
const foo = 'bar';
debugger;
foo;
```

The mapping of the source to the transpiled code appears to be off by one line:

![image](https://cloud.githubusercontent.com/assets/921609/8352272/cc762466-1b2b-11e5-9ea1-240668c15b5a.png)

Using `jspm@0.16.0-beta.3`.

**Comment by guybedford** [comment]
Strange it seems to be working ok for me actually. Could you share a test case?

**Comment by guybedford** [comment]
(I did try your exact case, not being lazy honest!)

**Comment by OliverJAsh** [comment]
Can no longer reproduce. Will keep testing!
