### ISSUE TITLE
Dependencies not loaded when plugin outputs source in system.register format

### ISSUE THREAD

**Issue by frankwallis** [systemjs/systemjs#551]
I have updated [plugin-typescript](https://github.com/frankwallis/plugin-typescript) to be compatible with SystemJS 0.18 and TypeScript 1.5. TypeScript now supports outputting in the System.register format and so I am using that and setting ```load.metadata.format = "register"```. 

This was working fine in 0.18.1, but since updating to 0.18.2 and 0.18.3 it has stopped working. The first typescript file is loaded, but after that its relative imports do not get loaded. There are no errors displayed or exceptions thrown.

You can see the issue in the example project contained within plugin-typescript. Swapping back to SystemJS 0.18.1 fixes everything. Any ideas?

**Comment by guybedford** [comment]
I can't think of any changes between SystemJS 0.18.1 and 0.18.2 that would have affected this. Are you sure that simple upgrade path causes the issue?

If so the only thing I can think of would be the normalization changes in https://github.com/systemjs/systemjs/commit/e30ab5f7f903745937efd643a61826d02aad4131 or https://github.com/systemjs/systemjs/commit/974e6e0d8a73c70e165157e6f5624a1e513dbb20. But that still doesn't seem like it.

Are you seeing network requests to the other files? Does TypeScript give error message for compile errors at all currently? If not then it may be that?

**Comment by frankwallis** [comment]
Yes I was completely wrong about this, sorry, it works the same with all versions. What was happening was the module was being registered as a named module, when I change it to be an anonymous module everything starts working ok.

The relevant code is in the System.register instantiate hook:

```
      // named bundles are just an empty module
      if (!entry)
        entry = {
          declarative: false,
          deps: load.metadata.deps,
          execute: function() {
            return loader.newModule({});
          }
        };
```

I don't really understand when modules should be named and when they should be anonymous?

**Comment by guybedford** [comment]
@frankwallis modules should usually be anonymous unless they are part of a bundle. Bundles should typically only be made though when moving from development to production and not as a distribution format, unless using SFX bundles. Let me know if that clarifies things?

**Comment by frankwallis** [comment]
Yes thanks, that implies that the plugin should produce named modules when called from systemjs-builder. Is there a flag or setting I should use to find out if it is being called from the builder or as part of a live-load?

**Comment by guybedford** [comment]
@frankwallis the plugin can return normal anonymous System.register calls and these will be converted to named calls by the builder. It's only if you set the format to 'defined' and implement the bundle hook to manage this process that you would do this yourself.

**Comment by frankwallis** [comment]
great, thanks
