### ISSUE TITLE
Having problems testing when using SystemJS for module control

### ISSUE THREAD

**Issue by buddyp450** [systemjs/systemjs#552]
Please see the issue here for details: https://github.com/facebook/jest/issues/367

Can anyone point me in the right direction as far as setting up SystemJS for server-side testing configurations using node/iojs? I feel like SystemJS doesn't really fit for this but I'm unsure of what else to do when all of my modules depend on SystemJS for their mapped module loading.

**Comment by guybedford** [comment]
So it sounds like jest assumes that your modules resolve based on the Node resolution algorithm.

Unfortunately this isn't compatible with SystemJS's resolution algorithm.

If there was a way in jest to set a "custom resolver" algorithm through an API then we could plug jspm into jest, but I'm not sure if this is currently possible.

**Comment by yoavniran** [comment]
I recently started using Jest and was surprised there wasnt a solution out there already to get Jest to play nice with my JSPM-based app.

fortunately, it gave me a nice excuse to write my first Gulp plugin: [gulp-jest-jspm](https://www.npmjs.com/package/gulp-jest-jspm).
to use it, you dont even have to be using Gulp, you can simply use its _getJestConfig()_ method to generate the config for you before you run Jest.
