### ISSUE TITLE
Plugin that gets applied to every import?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#553]
I tried monkey-patching `System.fetch` to do this, but I'm running into issues with `load.metadata.deps` not being set properly, so I figure the proper way to go about this is probably to just make it a plugin that gets applied to every import.  Is there a way to do this?

**Comment by timbur** [comment]
Am I being dumb or is there not an easy way to do this?

**Comment by guybedford** [comment]
This is not advisable for plugins as it won't apply to normal plugins?

You could do a wildcard loader:

```javascript
System.config({
  meta: {
    '*': { loader: 'customLoader' }
  }
});
```

But extending the loader sounds like a better option here to me.

What exactly are you trying to do, and what issues did you set extending fetch?

**Comment by timbur** [comment]
Thanks!  I'll try that in a bit.  I tried that previously, with an older version of `systemjs`, but since it didn't work back then I dismissed it this time.

I have an in-browser workspace using `web-tedit` (which you probably remember) and git repos are able to be cloned/stored within the browser (IndexedDB, WebSQL, etc.), and so I need for `systemjs` to grab files from said in-browser repo.

The issue I had with monkey-patching fetch was basically this:
```js
System.config({
  "map": {
    "test": "github:timbur/test"
  }
});
/* also tried:
System.config({
  "packages": {
    "test": {
      "main": "main.js",
      "defaultExtension": "js",
      "meta": {
        "*.css": {
          "loader": "css"
        },
        "*.json": {
          "loader": "json"
        },
        "*.jsx": {
          "loader": "jsx"
        }
      }
    }
  }
});
*/

System.import('test');
```
```js
// test/main.js
import { mount } from './app.jsx';
mount(document.getElementById('root'));
```
For some reason it's looking for `app.jsx` at the site root, not within `test`.

**Comment by guybedford** [comment]
I'm not sure I understand how monkey patching fetch could have altered your dependency resolution. If that's the problem I can look into it, but please confirm first.

**Comment by timbur** [comment]
I figured out the problem, but I'm not entirely sure of the best way to solve it.  Rather than describing the problem, I'll describe what I'm doing and both the problem and solution will probably be immediately obvious to you @guybedford.

Basically:
* Within the browser, users (developers) can load any project/repo without any CLI installation - e.g., npm, jspm, etc.
* There are of course configurations (typically package.json and config.js) associated with each project/repo.
* It would seem that my problem stems from the fact that said config files need to be automatically (as much as possible, at least) generated and updated on-the-fly, such that loading projects automatically determines the proper config if it doesn't exist, and adding or removing modules/dependencies will be immediately reflected within the config files, so that everything loads correctly and reliably (or at least as far as it can be taken with minimal human intervention).

Would it be at all feasible for me to pull the relevant logic from `jspm-cli` into the browser?

**Comment by timbur** [comment]
Also, as for how this is related to the `System.fetch` override, every module is (or should be) available as a git repo within the browser stored within IndexedDB (or WebSQL), and so their files can be retrieved/traversed similarly to however `jspm-cli` does it when installing modules server-side.

**Comment by guybedford** [comment]
@timbur the next release of jspm (0.17) will have a new piece of logic in SystemJS to dynamically load package configurations as JSON files before loading modules from the package. Perhaps that would help you with your problem? This logic would actually go as a post-normalize or locate hook I think.

**Comment by timbur** [comment]
Interesting.  I suppose I'll wait for it and see if I can work on something else in the mean time.  Thanks!  Feel free to close this if you don't think there's anymore discussion to be had.  :)

**Comment by guybedford** [comment]
Sure, but note it will be a little while unfortunately. If you want to implement something similar in the mean time that may well be useful.
