### ISSUE TITLE
meta configuration for plugin loader fails with relative paths in import

### ISSUE THREAD

**Issue by pgbross** [systemjs/systemjs#554]
Using "Plugin syntax" I can load an html template like:

```javascript
import instructionsTextOnly from './instructions-text-only.html!text'
```
On switching to using a meta configuration like:
```javascript
System.config({
  map: {
    'text': 'js/text.js'
  },
  meta: {
    '*.html': {
      loader: 'text'
    }
  }
})
```
the import fails with this statement (by fail I mean the text loader plugin is not invoked)

```javascript
import instructionsTextOnly from './instructions-text-only.html'
```
but works with this (ie. no relative path)

```javascript
import instructionsTextOnly from 'instructions-text-only.html'
```

Sometimes the .html files I wish to include are not in the same location as the importing .js file, but I can't find a meta configuration that will allow this. Do I need a different regex in the meta configuration somehow, or is the presence of a relative path not supported for plugin loaders?

--philip

**Comment by guybedford** [comment]
This is working fine for me. Note that `*.html` means all `.html` files within the baseURL. Perhaps check this is holding in your example.

**Comment by pgbross** [comment]
Ah I think that will be the problem as my sources are two or three folders below the baseURL. Is there a wildcard syntax (glob or regex?) that I can put in a map entry that means all .html files in any folder below the baseURL? Or is the preferred configuration to name each folder path explicitly?

**Comment by guybedford** [comment]
You should be able to use the wildcard with backtracking -

"../../*.html": {
loader: 'text'
}

Let me know if that works out for you.

**Comment by pgbross** [comment]
That looks like it should be good for my needs. I will test and let you know how it behaves (it may be 10 days before i am back in the office).

**Comment by pgbross** [comment]
Just to confirm now that I am back at work today (sorry for the delay) - using wildcard with backtracking is working for me.
