### ISSUE TITLE
AMD module reporting incorrect dependencies

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#555]
We are using RequireJS to create a bundle that contains backbone:

``` js
// main.js
define([ "require" ], function(require) {
    var req = function() {
        var requirejs, require, define;
        return
            // …
            // define("underscore", …),
            // define("jquery", …),
            function(t) {
                var e = "object" == typeof self && self.self == self && self || "object" == typeof global && global.global == global && global;
                if ("function" == typeof define && define.amd) define("backbone", [ "underscore", "jquery", "exports" ], function(n, r, i) {
                    e.Backbone = t(e, i, n, r);
                }); else if ("undefined" != typeof exports) {
                    var n, r = require("underscore");
                    try {
                        n = require("jquery");
                    } catch (i) {}
                    t(e, exports, r, n);
                } else e.Backbone = t(e, {}, e._, e.jQuery || e.Zepto || e.ender || e.$);
            }(function(t, e, n, r) {})
            // …
    }();
    return req;
});
```

(for full code, see http://interactive.guim.co.uk/2015/05/witness-petition/assets-1432824663727/js/main.js)

SystemJS seems to extract the following `metadata` from this module:

```
deps: ["underscore", "jquery"],
format: "amd"
```

Which means SystemJS will try and download `"underscore"` and `"jquery"`.

In this case, the modules are *not* dependencies of the `main` module. They are referenced as dependencies of another module (`backbone`) contained in the bundle. Are we doing some kind of static analysis that is incorrectly reading these as dependencies of `main`?

**Comment by guybedford** [comment]
The static analysis is exactly picking up the `require("underscore")` and `require("jquery")` statements.

It's the same problem as having a CommonJS file loaded by SystemJS with requires inside conditionals that aren't hit.

The way to work around this is to map the modules to empty or the correct module they should be, or alternatively alter the format interpretation.

**Comment by guybedford** [comment]
Closing, but let me know if you have further questions here at all.
