### ISSUE TITLE
Path to file that has no extension

### ISSUE THREAD

**Issue by robertsundstrom** [systemjs/systemjs#557]
I have the path ~/signalr/js. I try to load it from Systemjs but the loader adds .js to the end, producing: ~/signalr/js.js - that doesn't exist (as a route).

Can I make an exception for this path in some way, so that ".js" isn't added? 

I can't make a redirect route in ASP.NET. If I could then then it would have been solved by now.

**Comment by guybedford** [comment]
@robertsundstrom which version of SystemJS are you using? If using 0.17 and below, this can be done via a custom path config, and above by a custom package config.

**Comment by guybedford** [comment]
Sorry I mean 0.16 and below.

**Comment by robertsundstrom** [comment]
I'm using 0.18. What would that package config look like then?

**Comment by guybedford** [comment]
Are you using the `defaultJSExtensions: true` option?

**Comment by robertsundstrom** [comment]
Yes. I am.

**Comment by guybedford** [comment]
Ok sure. So if you use the packages configuration from https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages to define the `~/signalr` as a package, then you can alter the default extension for that package via `defaultExtension: ''`.

I actually just realised this won't work - have added a fix in https://github.com/systemjs/systemjs/commit/1b4acc582d23e28e66394cb9568cfb17be48196b, and pushed the build up as well which should allow this workflow.

**Comment by robertsundstrom** [comment]
Alright. Thanks. 

I discovered packages a couple of days ago when playing with the TypeScript support. I understand why the use in that context: enabling the .ts extension.

How do I update systemjs itself?

**Comment by guybedford** [comment]
Sure, you can update the system.js file from the dist of this repo or using jspm use `jspm dl-loader --edge`. Just let me know if you have further questions at all.

**Comment by robertsundstrom** [comment]
Aha. OK. I have wondered if that was the command for that.

Is this rights?

    "packages": {
        "signalr": {
            "main": 'js',
            "defaultExtension": ""
        }
    }

I can't seem to get this to work. The result should map to signalr/js (without extension).

By the way...

I can't express how much I like SystemJS. I can't live without it. It makes my life so much easier - with Babel and TypeScript.

**Comment by robertsundstrom** [comment]
I solved it:

    "packages": {
        "signalr": {
            "defaultExtension": "",
            "map": {
                "./hubs": "signalr/js"
            }
        }
    }

I'm using ASP.NET as a backend, for Web API, and SignalR for real-time communication.

**Comment by guybedford** [comment]
Thanks, it really means a lot to hear you're enjoying the project.

I'm wondering if we shouldn't make the convention here `defaultExtension: false` rather than empty string? It may well make more sense to strictly do this at a sematic level.

**Comment by robertsundstrom** [comment]
I like that, It makes it clearer - compared to just using empty string literals.

**Comment by guybedford** [comment]
Sure, thanks, I've updated this in the latest build.

**Comment by guybedford** [comment]
This has been released in 0.18.4
