### ISSUE TITLE
Pulling System.js from github

### ISSUE THREAD

**Issue by Chocoloper** [systemjs/systemjs#558]
Hello!

I'm developing a website and wanted to use angularjs 2.0. I found some tutorial which included a system.js script in the header and used "System.import('app.js')" to bootstrap the angular script.
The system.js was loaded like this:
`<script src="https://jspm.io/system@0.16.js"></script>`
I never had the chance to check this file in the last two days until it broke today. So searching for another source of the script I found this repository and added the system.js like this
`<script src="https://rawgit.com/systemjs/systemjs/master/dist/system.src.js"></script>`
Using that I get the following error:
````
GET http://192.168.0.10:8080/rx.js 404 (Not Found)
fetchTextFromURL @ system.src.js:1021
SystemLoader.fetch @ system.src.js:1054
lib$es6$promise$$internal$$initializePromise @ angular2.dev.js:1385
lib$es6$promise$promise$$Promise @ angular2.dev.js:1676
SystemLoader.fetch @ system.src.js:1053
calledRegister @ system.src.js:1523
(anonymous function) @ system.src.js:2026
loader @ system.src.js:2257
loader @ system.src.js:2794
loader @ system.src.js:3295
hookConstructor.meta @ system.src.js:3362
(anonymous function) @ system.src.js:3580
(anonymous function) @ system.src.js:320
run @ angular2.dev.js:115
zoneBoundFn @ angular2.dev.js:88
lib$es6$promise$$internal$$tryCatch @ angular2.dev.js:1338
lib$es6$promise$$internal$$invokeCallback @ angular2.dev.js:1350
lib$es6$promise$$internal$$publish @ angular2.dev.js:1321
(anonymous function) @ angular2.dev.js:166
run @ angular2.dev.js:115
zoneBoundFn @ angular2.dev.js:88
lib$es6$promise$asap$$flush @ angular2.dev.js:1132
```
So it seems that the script want to pull the rx.js from my local server but it's not there! Also I would propose that it is not a good idea to assume that everyone serves this library file from the same server instance. Adding the rx.js from another source like in the following line didn't solved the problem:
`<script src="https://rawgit.com/Reactive-Extensions/RxJS/master/dist/rx.js"></script>`

**Comment by probins** [comment]
The version of system.js on jspm.io adds some default mappings to load modules/packages from jspm.io. This is a convenience for jspm.io users. The default loader does not have these mappings, so if you want to load an external package/module you have to tell the loader where it should fetch it from, by setting paths or maps with System.config. See the config-api in docs/

**Comment by Chocoloper** [comment]
Following your advice and dding following script to my script solved the issue:
´´´
<script>
    System.config({
      map: {
        rx: 'https://rawgit.com/Reactive-Extensions/RxJS/master/dist/rx.js'
      }
    });
...bootstrap...
</script>
´´´
Got a new problem now: property Observable (from rx) is undefined. But that's another story!
Thank you very much!

**Comment by guybedford** [comment]
The exact configuration that the jspm on the server adds is actually:

```javascript
System.config({
  paths: {
    '*': 'https://registry.jspm.io/*.js',
    'github:*': 'https://github.jspm.io/*.js',
    'npm:*': 'https://npm.jspm.io/*.js'
  }
});
```
