### ISSUE TITLE
URL encoding issue in SystemLoader

### ISSUE THREAD

**Issue by abhishiv** [systemjs/systemjs#559]
Using SystemJS v0.18.3 on the browser

In this function, https://github.com/systemjs/systemjs/blob/9bdd29ea48cb72795e54e06bc542fe81b3882c1e/dist/system.src.js#L974

Sometimes I see request fail because they look like following:

```
https://github.jspm.io/jspm/nodelibs-process@%5E0.1.0.js
https://npm.jspm.io/inherits@%5E2.0.1.js 
```

It seems to be because of  `^` in  `npm:process@^0.10.0`

I was able to fix it by doing the following:

```
      if (isBrowser) {
	      url = url.replace(/#/g, '%23');
	      url = url.replace(/%5E/g, '');
      }
```

My config looks like this

```
System.config({
	"defaultJSExtensions": true,
  "paths": {
    "*": "*.js",
    "github:*": "https://github.jspm.io/*.js",
    "npm:*": "https://npm.jspm.io/*.js"
  },
  map: {
    "traceur": "jspm_packages/traceur",
    "process": "jspm_packages/nodelibs-process/index"
  }
});
```

You can reproduce  this by trying to install `npm:parse`

Edit:

Also noticed that this also happens for `~` in `https://npm.jspm.io/inherits@~2.0.1.js ` while importing `npm:pouchdb`

**Comment by guybedford** [comment]
This issue is actually because jspm is not currently compatible with the
latest SystemJS, only version 0.16.

The update for this will be coming soon.

**Comment by guybedford** [comment]
Closing, but let me know if you have further questions on this.
