### ISSUE TITLE
systemjs no conflict

### ISSUE THREAD

**Issue by yoavniran** [systemjs/systemjs#561]
Hi,
Im considering using SystemJS with a new project im beginning soon.

This new project will be bundled and then delivered to the browser by another script that is embedded in the customer's website (ala Google Analytics).

As far as I can tell, it wont be a problem to bundle everything into one file (system js + my code).

I am however worried about conflicting instances of System JS (not very likely but still) one being already on the page and one that will be downloaded for my code since System is a global object.

Is there a way now or that can be added to provide for this (albeit edgy) scenario?

thanks!
Yoav

**Comment by yoavniran** [comment]
just saw the documentation part about SFX bundles. I guess that answers the question. right? :)

**Comment by guybedford** [comment]
@yoavniran yes SFX bundles will not conflict with anything else on the page.
