### ISSUE TITLE
Bad GIT habit - forced update on public branch

### ISSUE THREAD

**Issue by markokr** [systemjs/systemjs#562]
I'm tracking systemjs development via git repo, no local commits.
Periodically I need to clean stuff like this after 'git pull':
```
~/src/js/systemjs (master)$ git pull
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 183 (delta 94), reused 88 (delta 88), pack-reused 80
Receiving objects: 100% (183/183), 324.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (129/129), completed with 28 local objects.
From https://github.com/systemjs/systemjs
 + 922bebf...9bdd29e master     -> origin/master  (forced update)
 * [new tag]         0.18.0     -> 0.18.0
 * [new tag]         0.18.1     -> 0.18.1
 * [new tag]         0.18.2     -> 0.18.2
Auto-merging dist/system.src.js
CONFLICT (content): Merge conflict in dist/system.src.js
Auto-merging dist/system.js.map
CONFLICT (content): Merge conflict in dist/system.js.map
Auto-merging dist/system.js
CONFLICT (content): Merge conflict in dist/system.js
Auto-merging dist/system-register-only.src.js
CONFLICT (content): Merge conflict in dist/system-register-only.src.js
Auto-merging dist/system-register-only.js.map
CONFLICT (content): Merge conflict in dist/system-register-only.js.map
Auto-merging dist/system-register-only.js
CONFLICT (content): Merge conflict in dist/system-register-only.js
Auto-merging dist/system-csp-production.src.js
CONFLICT (content): Merge conflict in dist/system-csp-production.src.js
Auto-merging dist/system-csp-production.js.map
CONFLICT (content): Merge conflict in dist/system-csp-production.js.map
Auto-merging dist/system-csp-production.js
CONFLICT (content): Merge conflict in dist/system-csp-production.js
Automatic merge failed; fix conflicts and then commit the result.
~/src/js/systemjs (master|MERGING)$ 
```

Please don't do it.  It's especially bad for anyone who tries to develop anything against
your branches.

**Comment by guybedford** [comment]
These merge conflicts are meaningless as these are the build files. It's a line between making the build files available to users so that they can use stuff on edge, but also not having builds as every second commit to pollute the commit history. This will become less frequent naturally as the project stabilizes anyway.

**Comment by markokr** [comment]
But this makes repo unusable...

Normal way to do it would be to just build (and test) and commit build files together with changes.
Then if you want to see real change then just do "git log -p lib/".

Another way would be to commit build files on minor releases, and do those as ofter as needed.

Current way just discourages cloning our repo :(

**Comment by guybedford** [comment]
Yes the points are very much taken here I know it's not ideal at all.

Aiming to stick with a release workflow going forward.
