### ISSUE TITLE
Javascript errors don't link to original source?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#563]
When using SystemJS javascript errors aren't linked to their place in the original source?

Example:
`npm install babel-core es6-module-loader systemjs`
index.html:
``` html
<!doctype html>
<html>
  <head>
    <title></title>
    <script type="text/javascript" src="node_modules/babel-core/browser.js"></script>
    <script type="text/javascript" src="node_modules/es6-module-loader/dist/es6-module-loader-dev.js"></script>
    <!--<script type="text/javascript" src="node_modules/systemjs/dist/system.js"></script>-->
    <script type="text/javascript">
      System.transpiler = 'babel';
      System.import('mymodule.js');
    </script>
  </head>
  <body>

  </body>
</html>
```
mymodule.js:
```
export class Q {
  constructor () {
    var world = 'earth';
    console.log(`Hello ${world}`);
    this.walk();
  }
}
var q = new Q();
```
**Using es6-module-loader**
When using the *es6-module-loader*, errors in the Chrome console link to the original file and the *Sources* panel display an error on the line (in the original source). See: 
![es6-module-loader-chrome-error](https://cloud.githubusercontent.com/assets/523210/8433204/a7bd8b42-1f44-11e5-88d1-7702481691ad.png)

**Using SystemJS**
But when I switch to using *SystemJS* (see the commented script tag in html file), with the same source, it doesn't link to the original source anymore: 
![systemjs-chrome-error](https://cloud.githubusercontent.com/assets/523210/8433254/f359372c-1f44-11e5-9ec7-0e9ca35b63b0.png)

I noticed a small difference in how the file was transpiled. The es6-module-loader encapsulated the entire module (inc the sourceMappingURL comment) between:
```
(function() {
...
})
```

I'm using using: 
```
├── babel-core@5.6.15
├── es6-module-loader@0.17.3
└── systemjs@0.18.4
```

**Comment by peteruithoven** [comment]
The following pull request seems relevant:
https://github.com/ModuleLoader/es6-module-loader/pull/383
https://github.com/systemjs/systemjs/issues/450#issuecomment-106772331

**Comment by peteruithoven** [comment]
If there is anything I can check or change please let me know.

**Comment by peteruithoven** [comment]
Problem might be caused by executing code directly in the imported module.

**Comment by peteruithoven** [comment]
Similar issue: https://github.com/systemjs/systemjs/issues/511

Another valid approach seems including a main javascript file using a <script> tag, with a System.import. Example: 
``` js
System.import('helloworld').then(function(m) {  
  var HelloWorld = m.default
  var helloWorld = new HelloWorld();
})
```

**Comment by milkshakeuk** [comment]
From what I can see in your module 

```javascript
export class Q {
  constructor () {
    var world = 'earth';
    console.log(`Hello ${world}`);
    this.walk();
  }
}
var q = new Q();
```

The method for walk does not exist,  and thats exactly what the screen shots of the console error show.

**Comment by peteruithoven** [comment]
The [JSPM CLI Getting started](https://github.com/jspm/jspm-cli/wiki/Getting-Started) example also has this issue. When one makes a mistake `bootstrap.js`'s `bootstrap` function Chrome displays that the error comes from `es6-module-loader.src.js:140`.

**Comment by peteruithoven** [comment]
Two ways to work around this:
- Bundle into sfx, then errors are shown and sourcemapped correctly in Chrome. 
- Delay the thrown error from the thing that's executed when the module is loaded (as explained by guy bedford  in #511), see example below. 

``` javascript
import _ from 'lodash-node/modern/lang/isEqual';
import $ from 'jquery';
import underscore from 'myname';

export function bootstrap() {
  // bootstrap code here
  setTimeout(function() {
    this.foo(); // should throw error
  },1000)
}
```

**Comment by peteruithoven** [comment]
Relevant issue: https://github.com/ModuleLoader/es6-module-loader/issues/397
Relevant pull request: https://github.com/ModuleLoader/es6-module-loader/pull/404

**Comment by peteruithoven** [comment]
I'm closing this for now. If the errors are improved, like mentioned in https://github.com/ModuleLoader/es6-module-loader/issues/397 and https://github.com/ModuleLoader/es6-module-loader/pull/404 this is all much less problematic. 

Although to be honest, I still don't understand how the es6-module-loader handles my first much better.
