### ISSUE TITLE
import failure with file protocol url

### ISSUE THREAD

**Issue by juvee** [systemjs/systemjs#564]
```js
System.import('some filepath').then(....)
```
Access to restricted URI denied Error loading file://........

but i can load it this way:
```js
$('<div>').load('some filepath', function(data) {
       console.log(data)
    });
```

**Comment by guybedford** [comment]
@juvee yes `System.import` resolved paths relative to the current URL, while `System.load` will assume your are passing in an absolute URL already. What exactly is the URL here?

**Comment by juvee** [comment]
with
```js
$('<div>').load
```
I meant Jquery load, not ``` System.load ``` , doesn't matter relative or absolute URL
apparently systemjs load content with ajax(xhr) that doesn't let CORS and file:// protocol load

but Jquery can load content with virtual DOM ``` $('<div>').load ```

**Comment by guybedford** [comment]
@juvee yes that is correct. I'd suggest running a local server or enabling file access flags. See https://github.com/systemjs/systemjs/blob/master/docs/overview.md#file-access-from-files.

**Comment by juvee** [comment]
yes, indeed, the solution to CORS and file:// protocol is access headers and local server.
but
i suggest implementing feature that intercept ajax loading same as [sass.js importer](https://github.com/medialize/sass.js#importer-callback-function)
that has these advantages:
* dynamic loading 
* modify path requests
* modify loading content

**Comment by guybedford** [comment]
Glad you've sorted this out. The loader hooks are documented at https://github.com/ModuleLoader/es6-module-loader/wiki/Extending-the-ES6-Loader#loader-hooks.

**Comment by juvee** [comment]
thank you very much!
