### ISSUE TITLE
Pls clarify bundle(s)

### ISSUE THREAD

**Issue by CNSKnight** [systemjs/systemjs#565]
```
System.config({
  bundles: {
    bundleA: ['dependencyA', 'dependencyB']
  }
});
```
>A built bundle file must contain the exact named defines or named System.register statements for the modules it contains.

My become:
>A *bundle must be built and a* built bundle file must contain the exact named defines or named System.register statements for the modules it contains.

Does bundleA == 'path/to/bundleFile'?
Can bundleA be described/referenced in *System.map*?

**Comment by guybedford** [comment]
Yes the bundle is a module path and will go through mapping rules.

Certainly can clarify along these lines.

**Comment by guybedford** [comment]
Added some clarifications in https://github.com/systemjs/systemjs/commit/e38356c5888757951a949ab3bd3c1085802911fb.
