### ISSUE TITLE
baseURL in config.js is set to a wrong directory every time I run "jspm install"

### ISSUE THREAD

**Issue by qt911025** [systemjs/systemjs#568]
my `package.json` setting is:
```json
"jspm": {
    "directories": {
      "baseURL": "browser"
    },
    "dependencies": {
      "lodash": "npm:lodash@^3.9.3",
      "pixi.js": "npm:pixi.js@^3.0.6"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.1.13",
      "babel-runtime": "npm:babel-runtime@^5.1.13",
      "core-js": "npm:core-js@^0.9.4"
    }
  }
```

and settings in `config.js` will be modified to 
```javascript
System.config({
  "baseURL": "/home/quentine/WorkSpace/electron/dots-and-boxes-game/node_modules/jspm/lib/config/",
  ...
});
```
automatically. But the right place is `browser`. How to fix that?

**Comment by guybedford** [comment]
You can edit the `baseURL` in the config.js file manually, and the value you set will not be altered by jspm. I'd be interested to hear what you did though to end up with that baseURL in your config file in the first place.

**Comment by qt911025** [comment]
Here is the project. I was just running `jspm install`.
https://github.com/qt911025/dots-and-boxes-game

**Comment by guybedford** [comment]
Right, that's exactly because it is evaluating the line https://github.com/qt911025/dots-and-boxes-game/blob/master/browser/config.js#L2 and storing it back into the config. It's best not to include code evaluations in the config file as it is only designed to work with static configurations.

**Comment by qt911025** [comment]
I know that, thx.
