### ISSUE TITLE
Improve story for non-.js source code.

### ISSUE THREAD

**Issue by Zoltu** [systemjs/systemjs#569]
I am writing a TypeScript application.  When a module lookup occurs, I want SystemJS to default to looking for a `.ts` file for my source code.

My first attempt looks something like this:
```js
System.config({
	"defaultExtension": "ts"
});
```

Unfortunately, this basically breaks all libraries brought in via `jspm install` since none of them are TS libraries.  This lead me to my second attempt:
```js
System.config({
	"defaultExtension": "ts",
	"packages": {
		"jspm_packages": {
			"defaultJSExtension": true
		}
	}
});
```

Unfortunately, this doesn't appear to actually do anything.  What I expected was for everything in the `jspm_packages` folder to behave as if the `defaultJSExtension` flag was enabled, allowing me to continue using all those packages as normal but all of my source code would be `ts`.  This lead to my next attempt, which included moving all of my source code to a subdirectory:
```js
System.config({
	"defaultJSExtension": true,
	"paths": {
		"*": "source/*"
	},
	"packages": {
		"source": {
			"defaultExtension": "ts"
		}
	}
});
```

My expectation was that anything looked up in the `source` folder would get the `ts` extension, the rest would follow the legacy rules.  Unfortunately (again) this didn't work.  While the `source/` is prepended correctly, the `ts` extension was not and instead a `js` extension was added.  This lead me to my final attempt:
```js
System.config({
	"defaultJSExtension": true,
	"packages": {
		"source": {
			"defaultExtension": "ts"
		}
	},
	"map": {
		"app": "source/app"
	}
});
```

This worked!  Unfortunately, it means that *every* time I create a new file or move a file I have to create a mapping for it.

I do not understand what the long-term strategy here is.  The `defaultJSExtensions` is meant to be a temporary flag according to the docs, but I do not see any path forward for removing it.  A few feeble attempts resulted in packages installed with JSPM not getting their loader file setup correctly.  Perhaps I am not understanding something?

Ideally, I would like to have my project be fully TypeScript yet still be able to use third party (non-typescript) libraries without having to do any setup beyond telling SystemJS that I want my source to be `ts` instead of `js`.  Alternatively, I would like either the second or third of my above attempts to have worked.  Both of them seem like bugs to me, though maybe they are intentional?

**Comment by Aedaeum** [comment]
:+1: 
This is useful for applications outside the scope of web development.

**Comment by milkshakeuk** [comment]
The way I got it to work was with this config:

```javascript
System.config({
  "baseURL": "/",
  "defaultJSExtensions": true,
  "transpiler": "typescript",
  "paths": {
    "github:*": "../jspm/github/*",
    "npm:*": "../jspm/npm/*"
  },
  "packages": {
    "js": {
      "main": "main.ts",
      "defaultExtension": "ts"
    }
  }
});
```

when the first ts file is loaded all its imports (which are also in sub folders of the js folder) are normalised to .ts and the ts transpiler sorts out the rest.

have a look at my jspm branch of my [tsdemo](https://github.com/milkshakeuk/tsdemo/tree/jspm)

**Comment by Zoltu** [comment]
I believe this solution is functionally the same as the third option I listed.  You have to either use relative paths (as you do) or you have to prepend everything with `js/`.

**Comment by guybedford** [comment]
The third option is exactly the suggested best-practice here. Do let me know if you have any further questions at all about the use cases.

**Comment by Zoltu** [comment]
@guybedford The third option doesn't work.  Only the fourth option works.  I suspect this is a bug?

Also, is there a technical reason why the second option can't work?  It seems like it should, and it would provide a better workflow.  If not, what is the correct process for submitting a feature request?

**Comment by guybedford** [comment]
Sorry I meant the fourth option. Paths apply at the very end of the pipeline, map at the very beginning.

The second option doesn't work because `defaultJSExtensions` is not a package configuration option, only a global compatibility option.
