### ISSUE TITLE
Register-only version calls normalizeSync but does not provide it

### ISSUE THREAD

**Issue by mkleehammer** [systemjs/systemjs#571]
I have a project compiled with Babel and with all source concatenated into one file.  I assume I want the register-only version for this and used the precompiled version from dist.  (I'm starting with the "src" to test.)  This generates a TypeError on doRegister line 1213 (0.18.4) because loader.normalizeSync is undefined.  I searched the "src" file and it does seem like there is no normalizeSync.

Am I using the correct file if I don't want dynamic loading?  Is one of the polyfills required?  (It didn't appear to be so.)

**Comment by guybedford** [comment]
Thanks, yes this is a bug.

**Comment by guybedford** [comment]
Fixed in 0.18.5.
