### ISSUE TITLE
Add `main` to `bower.json` and `package.json`?

### ISSUE THREAD

**Issue by al-the-x** [systemjs/systemjs#573]
I installed `systemjs` via `bower install systemjs/systemjs` (instead of just `systemjs`... separate issue, unrelated) and was warned that `bower.json` has no `main` defined, which means that tools like [`wiredep`](/taptapship/wiredep) and [`main-bower-files`](/ck86/main-bower-files) are fairly useless. The `main` entry is also a valuable piece of documentation for a package. Any reason for omitting it in both `package.json` and `bower.json`? If not, happy to open a PR to correct.

**Comment by guybedford** [comment]
Thanks, the bower.json is mainly there for tests over bower installs of the project. I was actually hoping to deprecate the bower.json at some point, so wouldn't want to guarantee this workflow if we're planning on taking it away? Let me know your thoughts.

**Comment by al-the-x** [comment]
Admittedly, it is a little counter-intuitive to use with a `bower`-based
workflow at the moment, so maybe not worth the effort. I was hoping to get
a simple `require` function out of the deal but ended up with another ball
of wax altogether... If I can get my dependencies -- which should be
AMD-compatible -- working with the `systemjs` module loader via Bower, I'll
submit a PR and some documentation. Until then, back to globals and
`wiredep`...!

**Comment by guybedford** [comment]
This is in the bower.json now.
