### ISSUE TITLE
Question | Why can't set baseURL twice?

### ISSUE THREAD

**Issue by omerts** [systemjs/systemjs#576]
Out of curiosity, why is the option to set baseURL, after it has been set, is now disabled?
Just in case someone in the future will search for it, the error message is:
```
baseURL should only be configured once and must be configured first
```

**Comment by guybedford** [comment]
Good question - because configuration is normalized into absolute URLs based on the value of the baseURL. Try logging `System.meta` or `System.packages` to see this.
