### ISSUE TITLE
system-csp-production.js gives: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by gavares** [systemjs/systemjs#577]
I have a very simple repro modeled after @guybedford example here: https://github.com/guybedford/jspm-lodash-test

My example works fine using just `system.js` but when I change to `system-csp-production.js` I get the error mentioned in the title. Sample code below:

index.html:
```html
<html>
  <head>
    <script src="jspm_packages/system-csp-production.js"></script>
    <script src="config.js"></script>
    <script>
      System.import('src/main.ts!typescript')
      .catch(function(err) {
        console.log('Error: ', err.stack);
      });
    </script>
  </head>
  <body>
  </body>
</html>
```

config.js:
```json
System.config({
  "baseURL": ".",
  "transpiler": "typescript",
  "defaultJSExtensions": true,
  "typescriptOptions": {
    "noImplicitAny": true,
    "typeCheck": true,
    "preserveConstEnums": true,
    "noLib": false,
    "suppressImplicitAnyIndexErrors": true,
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
});

System.config({
  "map": {
    "angular": "github:angular/bower-angular@1.4.2",
    "babel": "npm:babel-core@5.6.15",
    "babel-runtime": "npm:babel-runtime@5.6.15",
    "core-js": "npm:core-js@0.9.18",
    "jquery": "github:components/jquery@2.1.4",
    "lodash": "npm:lodash@3.10.0",
    "ts": "github:frankwallis/plugin-typescript@2.0.1",
    "typescript": "github:mhegazy/typescript@v1.5-beta2",
    "github:frankwallis/plugin-typescript@2.0.1": {
      "typescript": "github:mhegazy/typescript@v1.5-beta2"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.6.15": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:lodash@3.10.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
```

main.ts
```typescript
import * as _ from 'lodash';
import * as angular from 'angular';

vnApp = angular.module('vn',[]);
console.log(_);
console.log("vnApp initialized: " + vnApp);
```

causes the error mentioned in the title. 

jspm -v: `0.16.0-beta.3`
typescript: mhegazy's typescript 1.5-beta2

**Comment by guybedford** [comment]
Yes the CSP build is only possible to use when you've already bundled everything in your app or precompiled sources. It won't natively support transpilation or CommonJS loading (the likely cause of the error).

**Comment by gavares** [comment]
Thanks for the response. So it sounds like I need to bundle all my code and dependencies into a single outfile and load that all at once. 

I'm building a Chrome packaged app using Typescript and I'm wondering if the correct process would be to use the typescript compiler (ts) to create a single out file (ES5 + module = "system"? ES6?) and then process that single outfile with `jspm bundle` into a second single outfile?

If all my sources and dependencies are bundled into a single large outfile, what purpose is SystemJs serving in that scenario? Is it to manage runtime load/eval order?

**Comment by guybedford** [comment]
Certainly that might work. Are you loading other module formats or all ES6/TypeScript code? Support for TypeScript bundling in SystemJS will be coming soon, but we're not completely there yet I don't believe.

**Comment by gavares** [comment]
My app is written entirely in typescript but I rely on quite a few external js libraries (angular, postal, lodash etc.) which all have d.ts files defined.  

How far out is TypeScript support for SystemJS? Is it something I could do/contribute to help move that effort forward?

**Comment by guybedford** [comment]
It should work fine with this TypeScript plugin, you just need to build everything first with SystemJS builder.

**Comment by guybedford** [comment]
Let me know if you have any further questions here.
