### ISSUE TITLE
What's the best way to make imports from plugins/transpilers accessible?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#580]
There's probably a better way to do this, as I'm currently resorting to some pretty silly hacks.

I have [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx) which is of course a plugin for `systemjs` that uses `babel` for `jsx` transformation, and includes [`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) by default for hot reloading of React components.

[`babel-plugin-react-hot`](https://github.com/loggur/babel-plugin-react-hot) uses [`react-hot-api`](https://github.com/gaearon/react-hot-api) and so eventually that module has to be imported within the context of the transformed module.  The silly hack I've resorted to is monkey-patching `System.locate` and `System.fetch` to ensure `systemjs` knows where to look for certain modules, but surely there's a better way?  I suppose I could also just prepend a blob of code to the module as well, but there are some use cases where defining truly global modules would be really helpful.

**Comment by guybedford** [comment]
@timbur could the plugin not add an extra import to the top of the module to load the api it needs:

plugin-babel-jsx.js
```javascript
translate: function(load) {
  return 'import {reload} from 'react-hot-api';\n' + load.source;
}
```

Or have I misunderstood the issue?

**Comment by timbur** [comment]
@guybedford The location of `react-hot-api` is only configured within the Babel plugin, so when this gets added to the transformed source of modules and nested dependencies, those modules have no way to know where `react-hot-api` is.  I need to know the best way to ensure this.

I guess maybe I could make the transformer add `System.configure({"map": {"react-hot-api": reactHotApiLocation}})` to every module?  Would that be the best way?  I don't really like it but if you think that would work reliably and there isn't a better way I suppose I'll go that route.

**Comment by guybedford** [comment]
@timbur you can do normalization here via something like:

```javascript
export function translate(load) {
  return System.normalize('react-hot-api', __moduleName)
  .then(function(hotNormalized) {
      return `import {reload} from "${hotNormalized}";
                 ${load.source}`;
  });
}
```

If using CommonJS for the plugin, this would be `module.id` in place of `__moduleName` I think.

**Comment by timbur** [comment]
Nice!  I think I could get something like that to work within the Babel plugin.  I'll try in a bit.

**Comment by guybedford** [comment]
Great, just let me know if you need further assistance here.

**Comment by timbur** [comment]
Haven't had a chance to get back to this since I got stuck on those other things.  :(

I'll let you know how it goes.

**Comment by timbur** [comment]
I ended up prefixing `__dirname` to the import path and it seems to work.  :)

**Comment by davis** [comment]
this seems to build the right code, but i'm running into chrome not serving things from file:// is there anyway to get around this?
