### ISSUE TITLE
Transpiling of `cjs` modules synchronous while `es6` modules asynchronous?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#582]
In the live editing environment I'm working on, I'm loading basic templates on-the-fly for certain file extensions if the requested module doesn't exist so that everything can continue (re)loading with graceful error handling.

Suppose `some-decorator` is not yet mapped within the following module:
```js
import SomeDecorator from 'some-decorator';

@SomeDecorator
export default class Foo {
  // etc.
}
```

When `systemjs` looks for `some-decorator` and doesn't find it, it will default to:
```js
export default function SomeDecorator () {
}
```

But there appears to be a race condition where `SomeDecorator.default` is undefined.

However, if I use `cjs` for the template instead, there's no race condition:
```js
module.exports = function SomeDecorator () {}
```

I would very much prefer to use `es6` though, so what can I do?

**Comment by guybedford** [comment]
Have you got a circular reference here? That's the only way an export will be undefined during initial execution.

**Comment by timbur** [comment]
There doesn't appear to be any circular reference.  The example code is basically all there is when I'm testing this.  If you're absolutely certain that a circular reference is the only thing that would cause this, then it must be caused by my `System.locate` and `System.fetch` monkey-patches.  But that still wouldn't explain why the `cjs` export is defined while the `es6` export is not.

**Comment by guybedford** [comment]
Can you clarify:

> When systemjs looks for some-decorator and doesn't find it, it will default to:

It sounds like this is a defaulting mechanism you've patched in somehow?

**Comment by timbur** [comment]
Yeah I'll try to come up with a way for you to reproduce the issue.

**Comment by timbur** [comment]
Alright it took a bit of effort to reproduce but you can see it here: https://github.com/timbur/systemjs-automatic-cjs-vs-es6

With a really basic templating system, it worked fine.  But when applying some default template to an [undefined module within a transpiled `jsx` file](https://github.com/timbur/systemjs-automatic-cjs-vs-es6/blob/master/foo.jsx#L2), only `cjs` works.  The `jsx` transpilation happens via [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx), which of course uses Babel to support `stage 0` stuff.

**Comment by guybedford** [comment]
Yeah it's the jsx plugin - the plugin should be setting `options.modules = 'system'` when doing the transpilation.

**Comment by timbur** [comment]
Interesting.  What does that do?

**Comment by timbur** [comment]
Herp derp I should have probably at least googled it before asking lol.  Thanks once again for the help!

**Comment by guybedford** [comment]
It's not actually obvious at all - this is due to a double-interop problem (`import test from 'test'; test.default`)! The short answer is don't load ES6 from ES6 transpiled into CommonJS though.

**Comment by timbur** [comment]
@guybedford When I "hot reload" some module, I get the following error:
```
Uncaught TypeError: Multiple anonymous System.register calls in the same module file.
```

I call `System.delete` before the reload, but I'm guessing I need to ensure the module name passed to `System.delete` matches the module name passed to `System.register`?  Or am I misunderstanding the error?  Btw the `System.register` call originates from setting Babel `options.modules = 'system'` as you described within this issue.

**Comment by timbur** [comment]
Never mind.  Finally figured out that I should just use `System.import` now instead of `System.define` within the module reloader when reloading modules that depend on the module being reloaded.

`R E L O A D C E P T I O N` <sup><sup><sup>bom bommm</sup></sup></sup> <sup><sup><sup>bom bommm</sup></sup></sup> <sup><sup><sup>bom bommmmmmmmmmmm</sup></sup></sup>

Everything seems to work beautifully now.  :)

**Comment by guybedford** [comment]
@timbur if you wanted to use named system.register then yes the name should match the System.delete name. If you're able to share your work please do!

**Comment by timbur** [comment]
> If you're able to share your work please do!

For sure!  Where's the best place to share?  I was planning on maybe submitting a PR or something to the jspm registry for [`plugin-babel-jsx`](https://github.com/loggur/plugin-babel-jsx).  The default template stuff is part of something else though, which I will share when it's more complete (although it is already [on github](https://github.com/loggur/web-tedit)).

**Comment by guybedford** [comment]
The current `jsx` entry in the registry is outdated, so it would be great to replace it with your plugin!

Also to add build support for source maps, instead of using the `inline` option, extract the source map and set it as `load.metadata.sourceMap = JSON.stringify(sourceMap)`.

**Comment by timbur** [comment]
Sweet!  I'll do that in a bit.
