### ISSUE TITLE
What's the best way to extract source (npm, github, etc.), user/repo, branch (version), and file for some `load` within a plugin/monkey-patch?

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#584]
Sorry for all the issues lately.  Once I determine the best way to do these last few things I should be out of your hair for a while.  :)

I'm monkey-patching `System.fetch` and I currently manually extract the source, user/repo, branch, and file from the `load.address` or `load.name`, but surely there's some method to do this built into `systemjs`.  Or better yet maybe you could pass this info along to the `load` object?

Although, I'm kinda refactoring some of the code for the automatic package management I'm working on so... maybe this won't even be necessary.  I could see it possibly being pretty useful info to have though regardless.

**Comment by guybedford** [comment]
SystemJS has no knowledge of jspm's schema. The function to convert a URL into a schema module name is in SystemJS builder - https://github.com/systemjs/builder/blob/master/lib/builder.js#L60.

**Comment by timbur** [comment]
Okay cool.  Just making sure.  Thanks!  :)

**Comment by timbur** [comment]
I think I did a bad job of explaining this.  When `systemjs` normalizes some string like `github:timbur/some-module@master`, surely it separates each portion of that into basically:
```js
var params = {
  source: 'github',
  user: 'timbur',
  repo: 'some-module',
  branch: 'master'
};
```

And then of course uses `System.paths` and possibly `System.map` and others to create the URL - e.g., `http://localhost:8080/jspm_packages/github/timbur/some-module@master`.

For my particular use-cases, I need to basically recreate the above object within a plugin, and I currently do this through a pretty convoluted process that parses `(new URL(load.name)).pathname`.  This allows me to do stuff like load from alternative sources, find an existing version match, etc.

So I guess what I'm wondering is if there's a set of utility functions that `systemjs` uses internally that could be exposed.  Or maybe just pass as much of this info to the `load` object as possible so that it doesn't have to be recreated.

**Comment by guybedford** [comment]
SystemJS doesn't have any understanding of this level of information in the paths. It has no internal knowledge of what the `:` and `@` represent in jspm.

**Comment by timbur** [comment]
When I type this in my browser's console:
```
System.normalizeSync('github:does/not@exist');
```

How does it return this?
```
http://localhost:8000/jspm_packages/github/does/not@exist.js
```

**Comment by guybedford** [comment]
With one rule:

```javascript
System.config({
  'github:*': 'jspm_packages/github/*'
});
```

**Comment by timbur** [comment]
Ohhhhh, I see.  Alrighty then.  So I guess I have no choice but to parse `load.name` as I'm currently doing then eh?

**Comment by guybedford** [comment]
Yes exactly, SystemJS has none of jspm's assumptions coded in.
