### ISSUE TITLE
Starting without inline script?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#586]
In all the documentation I find on JSPM / SystemJS it starts with something like the following in a html file. 
``` html
<script type="text/javascript">
  System.import('app');
</script>
```
Or 
``` html
<script type="module">
  import app from './app';
</script>
```
The only exception seems to be when using a self-executing bundle.

Isn't there any way to include an script by url? Something like:
``` html
<script type="text/javascript" src="app"></script>
```
or 
``` html
<script type="module" src="app"></script>
```

**Comment by probins** [comment]
You can load a *script* with a script tag as always. `<module src="app.js">` is part of the [module tag spec] (https://github.com/dherman/module-tag/blob/master/explainer.md#external-module-scripts) but `<script type="module" src="app.js"></script>` is not currently supported by the polyfill (see https://github.com/ModuleLoader/es6-module-loader/blob/master/src/module-tag.js). It could I suppose be added, but I'm not sure what advantages this has over `<script>System.import('app')</script>` (which is marginally fewer characters to type :-) ).

**Comment by peteruithoven** [comment]
It's mostly different, unusual, something extra to remember. Especially for people coming from other module tools not using module tools at all. 
Also, when I want to switch to sfx bundles I need to change my html. 

You are right that I can simply use a script tag, but then it doesn't go through SystemJS's paths and map config? So we need to add `.js` manually. Maybe that makes sense because that's just how JavaScript ES6 will work?
```
 <script type="text/javascript" src="app.js"></script>
```
I can't get the <module> tag to work, should that work? Does that require an extra package? 

Maybe my bigger question is then, why is System.import used in almost every example? Is there a bigger benefit I'm missing?

**Comment by probins** [comment]
`<script>` is for loading scripts; `<module>` is for loading modules. `<script type="module">` is an interim thing until browsers support `<module>`. In future, when browsers support module syntax/loading, you can bootstrap with `<module>import 'app'</module>` (assuming default name-address mapping). In the meantime, with SystemJS you could do `<script type="module">import 'app'</script>` but then you would need a transpiler because current browsers don't know 'import'. So you can do `<script>System.import('app')</script>` instead. In future, modules will normally use `import` statements, and not refer to the `System` object. `System.import` will be for dynamic importing: onclick(System.import...).

Does that clarify things?

**Comment by peteruithoven** [comment]
It does, thanks! 

One thing that still confuses me though is that a script doesn't support importing, when import is used it's regarded as module? 
So using the following in html
``` html 
<script type="text/javascript" src="app.js"></script>
```
I can create an app.js with:
``` javascript
var world = 'earth';
console.log(`Hello ${world}`);
```
But when I use the following I get an `SyntaxError: modules are not implemented yet` error. 
``` javascript 
import SpaceShip from 'spaceship';
new SpaceShip();
```

**Comment by probins** [comment]
the error you get depends on which browser you are using. No current browser supports import/export (apart from some unstable code behind flags). But this is independent of `<script>` or `<module>`, which are HTML tags. These tags don't care what the content is; any valid script can be executed in a script tag. However, as the module tag spec explains, modules operate in a different context from scripts - they have their own scope and do not block rendering - so, whilst there isn't any rule at the moment that scripts can't import, it might well be that some future version of HTML will introduce a rule to limit import/export to module tags.

I'm assuming you're not using SystemJS when getting the error you mention; if you did, it would try and load a transpiler to deal with 'import'.

**Comment by peteruithoven** [comment]
I got that error in Firefox. In Chrome I get `Uncaught SyntaxError: Unexpected reserved word`. I understand almost no browser supports import/export, but that's why I'm using SystemJS and a transpiler right? 

I am actually using JSPM, with babel configured as transpiler. That's what makes my import work when I use `System.import()`. 

I'll try to better describe my test. 
**index.html**
``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <script src="jspm_packages/system.js" charset="utf-8"></script>
    <script src="config.js" charset="utf-8"></script>
    <script type="text/javascript" src="app.js"></script>
    <!--<script type="text/javascript">
      System.import('app');
    </script>-->
  </head>
  <body>
  </body>
</html>
```
**app.js**
``` javascript
var world = 'earth';
console.log(`Hello ${world}`);

// the following import gives an error when 
// not using System.import()
import SpaceShip from 'spaceship';
new SpaceShip();
```
**config.js*** (nothing customized)
``` javascript
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});

System.config({
  "map": {
    "babel": "npm:babel-core@5.6.20",
    "babel-runtime": "npm:babel-runtime@5.6.20",
    "core-js": "npm:core-js@0.9.18",
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:babel-runtime@5.6.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});
```

**Comment by probins** [comment]
the browser sees app.js as a normal script and runs it, finds 'import' and doesn't know what to do with it. As stated before, if that script tag is type="module", then the browser will leave it alone, and the loader polyfill will find it and load it as a module. However, the polyfill doesn't support src= with type="module" but only inline modules.

**Comment by peteruithoven** [comment]
Thanks for your patience, what I didn't get until now is that SystemJS or the es6-module-loader aren't involved at all with scripts loaded as src of a script tag. I was thinking they where because I could use ES6's template strings, but looking at the [compatibility table](https://kangax.github.io/compat-table/es6/) that's already supported natively. 

To summarize
The ES6-module-loader (and thus SystemJS) don't support transpiling javascript loaded through `script` tags with `src`. Like: 
``` html
<script type="text/javascript" src="app.js"></script>
<script type="module" src="app.js"></script>
```
It does provide a `System.import()` that can be used anywhere, to load script that can be transpiled. Like: 
``` html
<script type="text/javascript" src="bootstrap.js"></script> 
```
loading bootstrap.js with:
``` javascript 
System.import('app');
```
Or, what makes more sense, because you don't need that extra file:
``` html
<script type="text/javascript">
  System.import('app');
</script> 
```
**Inline ES6**
When you use a transpiler, an inline script with ES6 can be used to import: 
``` html
<script type="module">
  import 'app';
</script>
```
**Module tag**
The module tag is part of the [module tag spec](https://github.com/dherman/module-tag/blob/master/explainer.md#external-module-scripts) for using inline modules that browsers will probably implement in the future. 
``` html
<module>
  import 'app'
</module>
```

**Comment by probins** [comment]
The ES6-module-loader polyfills the `Loader` and `System` objects, as in the original spec; in the new spec it looks like these will be part of the `Reflect` object rather than separate globals. If the ES6-module-loader is loading an ES6 module, it will call the transpiler to transpile on the fly. This doesn't make sense in a production environment, so transpilation will generally be part of an offline build process.
