### ISSUE TITLE
Ignore default .js extension when there is a exention?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#590]
**Update: this describes using JSPM 0.15.x**
Currently the default configuration added by JSPM automatically adds the `.js` extension, unless another loader is specified with the `!`. See: 
``` 
  "paths": {
    "*": "*.js",
  },
```
But this means I can't add default loaders for .json files in a project? Because I understand when I add a `!` it uses the loader with the extension name. 

I have the following configuration to use the loader for json files in general.
``` js
  "packages": {
    "data": {
      "meta": {
        "*.json": {
          "loader": "json"
        }
      }
    }
  }
```
Currently the above configuration will result in SystemJS searching for `data/config.json.js` when using `import 'data/config.json'`.

I was hoping I could do
- `import 'app'` (not specifying `.js` when importing javascript files)
- `import 'data/config.json'` (Using the loader specified in config.json)

Is there a way to specify that I only want to add `.js` to path's without extension?

**Comment by guybedford** [comment]
Are you running the 0.15 jspm or 0.16 beta here?

**Comment by peteruithoven** [comment]
Apologies, I'll try to mention the version next time. I was slightly confused version wise because I did installed jspm a few folders higher by accident one time. The global / local message added to `jspm --version` was a great help though. 

I was using a 0.15 version. 

Using version `0.16.0-beta.3` now. 

No more more `"*": "*.js",` in paths, but a [defaultJSExtensions](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions) set to true: 
``` json
  "defaultJSExtensions": true,
```
Looking at the [defaultJSExtensions](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions) docs I understand this option will be deprecated in the future? What's the reason behind that? Adding `.js` is recommended now? Did the ES6 spec change on that? Checking the following page I see .js is always used for relative paths. 
https://whatwg.github.io/loader/#browser-resolve

**Comment by guybedford** [comment]
Yes exactly, the spec no longer assumes adding default js extensions. Current best-practices are to include extensions so module names are more similar to URLs with package rules as a subset, instead of their own entire custom naming system.

**Comment by peteruithoven** [comment]
Thanks for clearing that up, then this question becomes irrelevant.

**Comment by peteruithoven** [comment]
SystemJS's overview docs also contain a helpful explanation:
> Note that if using the `defaultJSExtensions` compatibility feature, plugins for resources with custom extensions will only work by using the [package configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) `defaultExtension: false` option to override this for specific packages.

From: https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use
