### ISSUE TITLE
Wrong bower package name

### ISSUE THREAD

**Issue by tristanlins** [systemjs/systemjs#594]
Your `bower.json` contains the name `systemjs`, but on bower.io this package is known as `system.js`.

**Comment by guybedford** [comment]
PRs welcome.

**Comment by guybedford** [comment]
Wait - the project name is `systemjs` not `system.js`. The bower registry entry is actually incorrect here unfortunately. I'd suggest posting the change there rather, although I know that can be a tricky process! Have they improved that yet? Alternatively posting a new entry? Or is SystemJS already taken?

**Comment by tristanlins** [comment]
The name `systemjs` seems to be taken:

```
$ bower install systemjs
bower systemjs#*            not-cached git://github.com/mrdoob/system.js.git#*
bower systemjs#*               resolve git://github.com/mrdoob/system.js.git#*
bower systemjs#*              checkout master
bower systemjs#*          invalid-meta systemjs is missing "main" entry in bower.json
bower systemjs#*          invalid-meta systemjs is missing "ignore" entry in bower.json
bower systemjs#*              resolved git://github.com/mrdoob/system.js.git#71090b45c1
bower systemjs#*               install systemjs#71090b45c1

systemjs#71090b45c1 bower_components/systemjs
```

**Comment by guybedford** [comment]
That one is actually a `system.js` - they should really be switched. Is there any chance of this now do you think?

**Comment by tristanlins** [comment]
Sry, I'm not so familiar with bower and renaming bower packages. But you're right, this is a naming clash and their should switch the name.
