### ISSUE TITLE
Module is loaded incorrectly if the very first statement of the module is not a `System.register` call

### ISSUE THREAD

**Issue by daniel-a-melo** [systemjs/systemjs#595]
The modules which first statement is not `System.register` are not loaded correctly. They are loaded with the value evaluated from this statement instead of function registered. 

**Steps to reproduce**

1 - `npm init`
2 - `npm install systemjs --save-dev` . Currently version v0.18.4 is installed

Result `package.json`

``` javascript
{
  "name": "systemjs-test",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "systemjs": "^0.18.4"
  }
}
```
3 - Create a module `main.js`

``` javascript
var x = 1;
System.register([], function(exports) {
    console.log('Registered main module');
    var ConsoleWriter;
    return {
        setters:[],
        execute: function() {
            ConsoleWriter = (function () {
                function ConsoleWriter() {
                }
                ConsoleWriter.prototype.sayHello = function () {
                  console.log('Hello!');
                };
                return ConsoleWriter;
            })();
            exports("ConsoleWriter", ConsoleWriter);
        }
    }
});
```
4 - Create an `index.html`

```html
 <!doctype html>
  <html>
  	<head>
       <script src="node_modules/systemjs/dist/system.js"></script>
       <title>System JS</title>
    </head>
    <body>
        <script>
          System.config({
            "baseURL": "./",
            "defaultJSExtensions": true
          });

          System.import('main').then(function(main) {
            console.log('Imported main');
            console.log(main); //Outputs 1
            console.log(typeof main); //Outputs number
            if (main.ConsoleWriter) {
              var writer = new main.ConsoleWriter();
              writer.sayHello();
            } else {
              console.log('Module was loaded incorrecly');
            }

          });
        </script>
    </body>
  </html>
```
List of files:

```
package.json
main.js
index.html
node_modules/systemjs/dist/system.js
```
The function registered on `main.js` is never executed. `System.import` completes the module loading providing the `number` 1 evaluated as the result of the first statement of `main.js`

If I remove the statement `var x = 1;` from `main.js` the module is loaded correctly. 

Tested under FireFox 39 and Chorme 34 on Ubuntu 12.10

This issue affects TypeScript classes that extends some class and transpilation module is set to `system`. TypeScript transpiler inserts the definition of function `__extends` before `System.register` and it prevents the module from being loaded correctly as shown in this bug report.

**Comment by guybedford** [comment]
Thanks, setting variables outside of the `System.register` function is actually not supported by the format. You can make it work via metadata to inform that the module format is register:

```javascript
System.config({
  meta: { main: { format: 'register' } }
});
```

But that will break down in other places too and is just a hotfix for the problem.

The problem is that TypeScript shouldn't be including code outside of the `System.register` function. Let me know if you'd like me to create an issue.

**Comment by daniel-a-melo** [comment]
Thanks @guybedford. I will open the issue for TypeScript. 

For information the workaround I took is telling TypeScript transpiler to not generate helper functions (such as `__extends` or `__decorate`) and I define them myself on another JavaScript file I load manually in the HTML page. 

The parameter `compilerOptions/noEmitHelpers` set to `true` on `tsconfig.json` prevents the TypeScript transpiler emitting those helpers before the `System.register` call

**Comment by guybedford** [comment]
Interesting, if we had a way of running the helpers via a global or require mechanism then it sounds like that would solve https://github.com/systemjs/builder/issues/178 and also fix this.

**Comment by daniel-a-melo** [comment]
Exactly, it seems it is on the pipeline for TypeScript 1.6 as per https://github.com/Microsoft/TypeScript/issues/3364

**Comment by daniel-a-melo** [comment]
@guybedford if I change the `compilerOptions/module` parameter to `amd` on `tsconfig.json` it does work. 

It intrigues me as I assumed that it failed because System.JS wasn't able to recognize module format due to the emitted helper function. 

In this case the transpiled code was:

```javascript
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
define(["require", "exports"], function (require, exports) {
    var SomeBaseClass = (function () {
        function SomeBaseClass() {
        }
        return SomeBaseClass;
    })();
    exports.SomeBaseClass = SomeBaseClass;
    var SomeClass = (function (_super) {
        __extends(SomeClass, _super);
        function SomeClass() {
            _super.apply(this, arguments);
        }
        SomeClass.prototype.doSomething = function () {
            console.log('did something');
        };
        return SomeClass;
    })(SomeBaseClass);
    exports.SomeClass = SomeClass;
});
```

and yet System.JS recognizes it as a AMD module and loads it correctly

**Comment by guybedford** [comment]
The `define` detection will check all the source so is more expensive than the `System.register` detection which only skips whitespace and comments, not code. The idea is that code using the System.register output gets cheaper format detection.

**Comment by jamiewinder** [comment]
I think I've just encountered this bug in the new TypeScript 1.5. Is there a way to force system.js to assume the format is 'register' for now (to save me putting "format register" everywhere?) :)

**Comment by guybedford** [comment]
@jamiewinder are you building a bundle, or loading separately compiled files? This config may help - https://github.com/systemjs/systemjs/issues/595#issuecomment-122259045.

**Comment by jamiewinder** [comment]
They're separate for now. I spotted that syntax after posting, and had just tried '
```
meta: { "*": { format: 'register' }}
```
Which, unforeseen consequences, breaks plugins (even if you try and override with the "register cjs" string). No problem though, I'll just workaround for now. Thanks.
