### ISSUE TITLE
Compose mapped module IDs

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#596]
I have installed `when`. I want to alias `Promise` to `when/es6-shim/Promise`.

Unfortunately you cannot do:

``` js
System.config({
  map: {
    "when": "github:cujojs/when@3.7.3",
    "Promise": "when/es6-shim/Promise"
  }
});
```

Is there any other way of achieving this?

**Comment by guybedford** [comment]
Package map will compose with global map I believe. So you could try having the `Promise` mapping as a package map and the `when` mapping as a global map.

**Comment by unional** [comment]
@guybedford , how to have Promise mapping as a package map for the whole system? Is it something like this?

````
System.config({
    "map": { "when": "github:cujojs/when@3.7.3" },
    "packages": {
        "*" : {
            "map": {
                  "Promise": "when/es6-shim/Promise"
            }
        }
    }
}
````
I tried `.`, `*`, `/`.

**Comment by guybedford** [comment]
@unional just use the global map - 

```javascript
System.config({
  map: {
    Promise: 'when/es6-shim/Promise'
  }
});
```

**Comment by unional** [comment]
@guybedford , the global map way is not working:

In development console:
> Promise.toString()
< "function Promise() { [native code] }"
> System.import("when/es6-shim/Promise").then(function(Promise) { console.log(Promise.toString())})
< Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
The global Promise is still native promise.

**Comment by unional** [comment]
Ok, I figured a way that will work.  Please let me know if this is the preferred way.

* Since `map` is not ordered, I can't do `Promise: "when/es6-shim/Promise"` as it depends on `when: "github:cujojs/when@3.7.3"`.  I have to do:
````
System.config({ map: { Promise: "github:cujojs/when@3.7.3/es6-shim/Promise"}});
````

* I have to load the Promise first:
````
System.config({
  meta: {
    "*": {
      deps: [ "Promise"]
    }
  }
}
````

**Comment by guybedford** [comment]
Note that metadata `deps` won't work for all formats in builds (specifically for ES modules, System.register modules and AMD modules). I've made an issue at https://github.com/systemjs/systemjs/issues/625 to track this. `deps` will also never ever work for ES modules.

It is probably advisable to explicitly import `Promise` into everything that requires it, although I know it an be very impractical, but that is the way full modularity should go. Or just use a good old script tag to load the promise library in the head. See also the globals configuration at https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#globals.

**Comment by OliverJAsh** [comment]
I can use the package map, but I want `Promise` to be available to all packages. If I try adding it to the global map, it brings me back to the original problem:

``` js
System.config({
  map: {
    "when": "github:cujojs/when@3.7.3",
    "Promise": "when/es6-shim/Promise"
  }
});
```

**Comment by guybedford** [comment]
Perhaps install `when` as `Promise` and set the main entry point to `es6-shim/Promise`?

**Comment by OliverJAsh** [comment]
To do that I would need to add an override?

**Comment by guybedford** [comment]
It's really about what is convenient for you here. I would have suggested a `<script>` tag.

I've been putting some thought to it though and it may actually be possible to enable `deps` metadata across all module formats. I've created https://github.com/systemjs/systemjs/issues/640.
