### ISSUE TITLE
amd commonjs require, module undefined

### ISSUE THREAD

**Issue by Munter** [systemjs/systemjs#599]
I'm getting an error thrown in my code base on this line: https://github.com/systemjs/systemjs/blob/6426fbb171acf41fcb908abd4ade0e92deb896e7/lib/amd-helpers.js#L67

`module` is undefined

**Comment by guybedford** [comment]
Can you share the code here? It sounds like CommonJS incorrectly detected as AMD to me. Sharing the scenario would help a lot to know what error to throw here.

**Comment by guybedford** [comment]
For interest, managed to track down the history of this line all the way back to https://github.com/systemjs/systemjs/blob/61446701bc37623353c031465a43fc7bf7649279/loader.js#L574. It seems it is entirely a vestige, and can probably be removed for a clear error message!

**Comment by guybedford** [comment]
Tempted to remove this line entirely for a better error. Do you remember how this worked out?

**Comment by Munter** [comment]
Think I ran into it at work. I'm on vacation right now, so if it's still an issue I'll run into it again in 10 days

**Comment by guybedford** [comment]
Thanks, no problem will leave this up until then.

**Comment by guybedford** [comment]
@Munter did you ever manage to replicate this again?

**Comment by guybedford** [comment]
The message at https://github.com/systemjs/systemjs/blob/master/lib/amd-helpers.js#L68 should catch the underlying issue here in future.
