### ISSUE TITLE
IE 8 support

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#603]
Currently this fails due to `Object.getOwnPropertyDescriptor`.

Would it be possible to get SystemJS working in IE 8? How big a piece of work would this be, to your knowledge?

**Comment by guybedford** [comment]
The `Object.getOwnPropertyDescriptor` check is supposed to work in IE8. Will look into this, it should be straightforward to fix.

**Comment by guybedford** [comment]
I'll do an IE8 test and aim to fix this along with the coming release I'm hoping to do this week. If you're able to look into it sooner let me know too.

**Comment by OliverJAsh** [comment]
This is a good example of why I would like to be able to lock the version of SystemJS, re. https://github.com/jspm/jspm-cli/issues/743. I could choose to use the version below which does not have this bug.

**Comment by guybedford** [comment]
@OliverJAsh this is fixed on master now, and I've pushed a build so `jspm dl-loader --edge` should now work here. It may well be worth allowing custom version flags for that command to avoid this sort of thing in future.

**Comment by guybedford** [comment]
Released in 0.18.5.
