### ISSUE TITLE
Improve packages wildcard support

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#606]
While this works:
"packages": {
    "abc/def-xyz": {...}
}

This does not:
"packages": {
   "abc/*-xyz": {...}
}

This support improvement would me me to gradually translate code from old javascript to new javascript using transpiler.

**Comment by guybedford** [comment]
Can you more clearly explain the use case here for why you would need this?

Is there a reason you can't make `abc` the package, and then use wildcard-meta to have `*-xyz` meta options?

**Comment by unional** [comment]
I was trying to setup a folder naming convention that when the folder is named in certain way to help me port code from JS to TS.  

There are several assumptions I made:
* `module` == `package`:  I want to create modules that can have their own dependency map.
* Using `defaultExtension` for `*.ts` in the package: This is basically what suggested by Frank https://github.com/frankwallis/plugin-typescript  
* `import` or `require` without extension: This one I'm still not quite sure about.  I saw there is a change in es6 module loader that it will not append `.js` by default.  Does it mean in the future we should reference module and *local dependency within module* using URL with full file name? Should it be `import X from 'lib/myModule'` or `import X from 'lib/myModule-main-file.js` or `import X from 'myCompany:myModule'` etc for module reference, and `import X from 'moduleLocalDir/component'` or `import X from 'moduleLocalDir/component.js'`?

With those assumption, I have the module folder structured like this:

````
+-- lib
	+-- myModuleA
	    +-- ts
	        +-- *.ts files
	    +-- *.js original files
	+-- myModuleB
	    +-- ts
	        +-- *.ts files
	    +-- *.js original files
````

With this structure, having a wildcard package definition would greatly simplify the configuration:

````
"packages": {
	"lib/*/ts": {
		"defaultExtension": "ts",
		"meta": {
			"*.ts": {
				"loader": "ts"
			}
		}
	}
}
````

**Comment by guybedford** [comment]
@unional if you want a map config for each package, then you'd need to declare them each separately anyway?

```javascript
"packages": {
  "lib/myModuleA": {
    "defaultExtension": "ts",
    "map": {...}
  },
  "lib/myModuleB": {
    "defaultExtension": "ts",
    "map": {...}
  }
}
```

You can reduce meta-duplication by using global meta:

```javascript
"meta": {
  "*.ts": { loader: "ts" }
}
```

I'd advise having each package entirely declared separately for maximum portability, or having the `lib` folder declared as a package of many modules.

If using `defaultExtension: 'ts'` you can write imports of the form `import './file'` and that will load `file.ts`. It is generally recommended to include the extension though as the best-practicee.

**Comment by unional** [comment]
@guybedford  thanks.  regarding `import './file'` vs `import './file.ts'`, does best practice suggest to do that only inside modules, or between modules? i.e., `import $ from 'jquery'` or `import $ from 'lib/jquery.js'`

For portability, would module or package based config be a viable option in the future? i.e.:

in `app/config.js`
````
"packages": {
    "lib/ModuleA": {
        "configFile": "config.js" // relative to lib/ModuleA/config.js
    }
}
`````

Similar to `jspm` in `package.json`

**Comment by guybedford** [comment]
It's not about whether it is inside the module or not, but when requesting a package by name that has a main entry point, or other configuration making it a defined package, that is the one case you can skip the extension. (`System.config({ packages: { 'lib/jquery': { main: 'jquery.js' } }, paths: { 'jquery-cdn': '//cdn.jquery.com/jquery.js' } })` cases).
