### ISSUE TITLE
code in multi-line comments parsed during import

### ISSUE THREAD

**Issue by DannyMeister** [systemjs/systemjs#607]
I broke during a live demo of our Angular2 app because commenting out my directive in the .ts still resulted in at least a partial evaluation of the commented out script.

Here's a plunk of a small repro with no dependencies other than SystemJS.
http://plnkr.co/edit/y32hgVjW9j6KPGEmzHgU?p=preview

**Comment by guybedford** [comment]
Yes module format detections are not designed to be accurate but performant and to handle the 99% use case. We don't remove comments when applying the regular expressions for ES6 module syntax detection for performance reasons.

If you want to be certain about the module format, use meta-configuration - 

```javascript
System.config({
  './*.js': { format: 'esm' }
});
```

**Comment by guybedford** [comment]
Let me know if you have any more questions on this at all.

**Comment by DannyMeister** [comment]
Thanks, with the meta configuration available, that kind of limitation is perfectly acceptable.
