### ISSUE TITLE
Execution order is not correct with depCache (0.18)

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#611]
I'm trying to use depCache to pre-fetch the files I needed instead of using `require(...)` directly in the code (for my own reason, namely ExtJS).
I notice the files are being loaded, but the execution follows the load order rather than the dependency order.

i.e., I have two files: `KitchenSink/app.js` and `KitchenSink/controller/MainFrame.js`. with:

````
depCache: {
    "KitchenSink/app": ["KitchenSink/controller/MainFrame"]
}
````

When the `KitchenSink/app.js` is loaded, it does trigger the loading of `KitchenSink/controller/MainFrame.js`.  But the `app.js` code is executed before the `MainFrame.js`, causing ExtJS couldn't find `KitchenSink.controller.MainFrame`.

**Comment by unional** [comment]
If I set deps in meta, the files are loading with the right order.

````
"meta": {
    "KitchenSink/app": { "deps": ["KitchenSink/controller/MainFrame"] }
}
````

Of course, this duplicates the dependency declaration.

**Comment by guybedford** [comment]
Execution happens in the order resources are available. So if A depends on B and D and C depends on B, then B may be executed before or after D. This has some benefits as the JS engine executes as soon as it can.

Note that the new WhatWG specification is carefully defining execution order so that this will be deterministic regardless of the network for predictability.

With the current implementation though, the only way to ensure execution order is to carefully define dependencies to know that something has executed by the execution of the parent.

**Comment by unional** [comment]
Thanks for the explanation. If on my A depends on B, would it be possible
that B could execute before A? This is what happen to me. I don't have
other code depend on B.

And when you talk about "depend", does it apply to `depCache` or `meta -
deps`?

Also, it might be a good idea to add this as a known issue

**Comment by guybedford** [comment]
The only way B would execute before A is if there is a circular reference in play.

**Comment by unional** [comment]
I don't think there is circular reference in place.  There is only two files there:

`KitchenSink/app.js`:
````
Ext.application({ name: "KitchenSink", controllers: ['MainFrame'] })
````
`KitchenSink/controller/MainFrame`:
````
Ext.define('KitchenSink.controller.MainFrame', { extend: 'Ext.app.Controller'});
````

With `depCache` only in `config.js`:
````
System.config({
  ...
  depCache: {
     'KitchenSink/app': [ 'KitchenSink/controller/MainFrame']
  }
});
````

**Comment by guybedford** [comment]
@unional `depCache` does not set execution order, it only informs SystemJS to load the modules in parallel. Setting up execution order should be done via `deps` meta or explicit imports.
