### ISSUE TITLE
entry property added to metadata results wrong behaviour

### ISSUE THREAD

**Issue by csbenjamin** [systemjs/systemjs#614]
I have a big app. Several modules are loaded asynchronously. In a module A I load facebook sdk. The facebook url is //connect.facebook.net/en_US/sdk.js. When the loading of facebook sdk is processing, a property `entry` is added to its metadata. In the entry object there are dependencies of other module B that has nothing to do with the module A. In these dependencies there is a dependence "../service". This results a attempting to load  //connect.facebook.net/service.js, that does not exist. This happens randomly. If the browser cache is on, it does not happen, otherwise it happens.

What the `entry` metada is for? Am I missing something?

PS 1: This is the facebook sdk metadata in my system config:

    "format": "global",
    "exports":"FB",
    "scriptLoad":true

PS 2: My english is not good. If my text is confuse, let me know and I will try to be clearer.

**Comment by csbenjamin** [comment]
PS 3: I'm using SystemJS v0.18.4

**Comment by guybedford** [comment]
Yes there shouldn't be an `entry` object added to the metadata. How are you checking this metadata?

How often does it try to load `service` from the wrong location? Wondering what type of race condition might lead to that.

Perhaps try upgrading to the latest SystemJS version from this master branch and see if that helps?

**Comment by csbenjamin** [comment]
@guybedford I did a simple case to reproduce the wrong behaviour. The error happens randomly. You will have to reload the page several times with the console opened.
Here is the simple case: http://systemjstest.vcsoft.com.br/
The source code of this case is here https://github.com/csbenjamin/systemjstest
If you want to reproduce the error locally you will need to setup a nginx server. In the repo there is a server.nginx file. I don't know how fast is your internet, but mine is slow and I can reproduce the error only locally.

PS: upgrading to the latest SystemJS version from this master branch didn't help. I checked the metadata in chrome debug mode. I added some console.log in system.src.js and now we can see the metadata.entry in the console. The service is loaded from the wrong location more than 50% of time running this simple case locally. Let me know if you could reproduce the error.

**Comment by csbenjamin** [comment]
Here is a screencast of error happening in my compurer. I'm running the simple case above locally.
https://www.youtube.com/watch?v=ophH7FuM8bM

[![bug systemjs](http://img.youtube.com/vi/ophH7FuM8bM/0.jpg)](http://www.youtube.com/watch?v=ophH7FuM8bM)

**Comment by guybedford** [comment]
Thanks for posting this detailed information. I was able to see it in your example, and believe I've tracked it down. I've posted a possible fix, you'll need to clone SystemJS, `npm install && make` to get the `system.src.js` file. Let me know if you can try that and see if it resolves the issue?

**Comment by csbenjamin** [comment]
Unfortunately the experimental fix didn't fix the issue. I have updated the https://github.com/csbenjamin/systemjstest and http://systemjstest.vcsoft.com.br/, so you can test yourself.

**Comment by guybedford** [comment]
@csbenjamin thanks for the quick feedback. I've attempted another fix. I don't have an easy install of nginx handy to test which makes it tricky to run the example. If this one doesn't sort it will devote more careful time to the issue.

**Comment by csbenjamin** [comment]
@guybedford It seems that the issue was resolved. Thanks for that. If you need, I have added a server.js file in my repo, so you don't need to use nginx anymore to reproduce the case locally. Also I have updated the example with the new system.src.js.
Feel free to close this issue.

**Comment by guybedford** [comment]
Excellent, thanks so much @csbenjamin for your help tracking this down.

**Comment by guybedford** [comment]
Released in 0.18.5.
