### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by photonstorm** [systemjs/systemjs#615]
Trying out the latest dist of SystemJS (v0.18.4) and I'm getting the error: Uncaught RangeError: Maximum call stack size exceeded. This is in a blank html file, nothing else at all included:

```
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>SystemJS</title>
        <script src="lib/system.src.js"></script>
    </head>
    <body>
    </body>
</html>
```

I've tried the system.src.js and system.js but they both do the same thing. This is in latest build of Canary (Version 46.0.2464.0 canary), but Chrome stable works fine - so either Canary has dropped a feature which SystemJS can't cope with or has a glitch for the moment. Figured I'd mention it either way.

**Comment by guybedford** [comment]
I just ran the test suite against that version of Canary and it definitely seems to run fine. Are you using the `dist/system.src.js` build on the current master?

**Comment by photonstorm** [comment]
Ok closing this one off - it was just Canary being it's usual flakey self. It fixed itself with an update to Version 46.0.2466.0.

**Comment by guybedford** [comment]
Sure, thanks for following up.

**Comment by photonstorm** [comment]
Is there a release that fixes the `webkitStorageInfo` and `webkitIndexDB` deprecation warnings that Canary throws?

**Comment by guybedford** [comment]
Thanks, I've added these in https://github.com/systemjs/systemjs/commit/05472da64fbdf8bd32423c4178522cd69683b203.
