### ISSUE TITLE
AMD/Squire-like mocking support for SystemJS ?

### ISSUE THREAD

**Issue by cyparu** [systemjs/systemjs#616]
Currently in all my [Karma](https://github.com/karma-runner/karma) & [Jasmine](http://jasmine.github.io/) mock-testing specs I'm using [Squire](https://github.com/iammerrick/Squire.js) for mocking the [AMD/RequireJS](http://requirejs.org/) modules that is working behind by creating new RequireJS contexts. 
Since I'm looking to migrate to a future-proof TypeScript/SystemJS **combo** for all my frontend developments I'm also looking for a Squire-like support testing infrastructure for SystemJS.

**Comment by guybedford** [comment]
There is the Karma-SystemJS project which may be suitable here. It is also possible with SystemJS to:
* Extend its constructor and create custom SystemJS instances for isolated loader tests in the same page
* Delete and remove modules from the registry for mocking - `System.set(System.normalizeSync('mocked/module'), System.newModule({ module: 'obj' })`

We definitely need to expand the docs / information available in this area. @OliverJAsh does the above cover some of the points of how you managed to replace your Squire-style testing for SystemJS here?

**Comment by OliverJAsh** [comment]
We were able to drop this is as a replacement for Squire. It might not work for all your needs:

``` js
export default class Injector {
   constructor() {
        this.loader = new System.constructor();
        this.loader.config({
            baseURL: System.baseURL,
            defaultJSExtensions: true,
            transpiler: System.transpiler,
            paths: System.paths,
            map: System.map,
            // Map is transformed to packages
            packages: System.packages
        });
        this.loader.normalize = System.normalize;
    }

    mock(mocks) {

        // Support alternative syntax
        if (typeof mocks === 'string') {
            mocks = { [mocks]: arguments[1] };
        }
        Object.keys(mocks).forEach(moduleId => {
            var mock = mocks[moduleId];
            var mappedModuleId = System.map[moduleId] || moduleId;
            this.loader.set(mappedModuleId, this.loader.newModule(mock));
        });
        return this;
    }

    test(dependencies, callback) {
        // Support alternative syntax
        if (typeof dependencies === 'string') {
            dependencies = [dependencies];
        }
        return Promise.all(dependencies.map(dep => this.loader.import(dep)))
            .then(args => callback(...args));
    }
}
```

**Comment by cyparu** [comment]
Great! @guybedford &  @OliverJAsh 10x for your tips! 
I'll try to wrap this as a helper/utility module that can be reused allover ... as a sort of **mini-squire**.
