### ISSUE TITLE
Module format es6 / esm?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#617]
The [module formats docs](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md) describe a `esm` format (which make more sense name wise than es6). It also says "previously referred to as es6", but what does that mean? Will using `es6` become deprecated or will both `esm` and `es6` work? 

Should I use `esm` in config API's [meta](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta) and [packages](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages)'s `format` options? 

Should I use `esm` in [package.json's format option](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#format)?

**Comment by guybedford** [comment]
`esm` is the configuration to use, `es6` is the previous naming for this. Thanks, I've created https://github.com/jspm/jspm-cli/issues/961 to track this update in jspm.

**Comment by peteruithoven** [comment]
So `esm` can be used everywhere? 
If so I'll try to do some docs pull requests.

**Comment by guybedford** [comment]
For SystemJS yes. Not in the jspm package.json currently.

**Comment by peteruithoven** [comment]
I've added a comment to *Configuring Packages for jspm*:
https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm/0b7151423fcf2ddc636c9f0600974c6f86bae625#format

**Comment by guybedford** [comment]
Thanks.
