### ISSUE TITLE
Folders named # in npm:es5-ext

### ISSUE THREAD

**Issue by WorldMaker** [systemjs/systemjs#621]
My ultimate goal is to load [CycleJS](http://cycle.js.org) via JSPM. It requires `virtual-dom` from NPM and on NPM `virtual-dom` eventually depends on (dependency of a dependency) [es5-ext](https://github.com/medikoo/es5-ext) from NPM. es5-ext dependencies don't want to load properly in my browser and the issue appears to be due to the fact that es5-ext has decided to name some of its folders `#`. When modules under the `#` folder do a relative require (such as `require('../../object/valid-value')`), the relative path is getting resolved based on URL rules (which makes sense to me) rather than with regards to the odd folder names. Is there some easy work around here? Is there some way to (that is worth the effort) to make the relative imports a little bit smarter here in the face of such a silly folder name?

Given that all of this stems from `virtual-dom` wanting a polyfill for ES6 Map, I'm almost inclined to just update the dependency in `virtual-dom` to a less odd polyfill and/or find a way with JSPM or SystemJS configuration to shim out the ES6 Map polyfill `virtual-dom` is requesting with the Babel implementation...

That said, given the `es5-ext` attitude that this "works in Browserify", it seemed reasonable to open an issue to track if this is something that SystemJS should fix or not. (My assumption is "not", at the moment, because seriously why would you name a folder `#` and expect it to work in browsers?)

**Comment by guybedford** [comment]
Ok thanks. It seems this is a side-effect of moving entirely to URL-based normalization where previously this might have worked correctly.

I think this may be best tackled in jspm itself, via a process of converting `#` into `%`. I've created an issue there to track this at https://github.com/jspm/npm/issues/84.

**Comment by WorldMaker** [comment]
That makes sense. Thanks!

**Comment by OliverJAsh** [comment]
I've just ran into this exact issue when trying to use CycleJS via jspm (and also https://github.com/jspm/jspm-cli/issues/988). @WorldMaker Did you work around it in the end?

**Comment by WorldMaker** [comment]
I was at GenCon this weekend. I plan to look into alternatives sometime later this week or at least this weekend.

**Comment by guybedford** [comment]
Ok I finally get this was working before but broke. Fixed in https://github.com/systemjs/systemjs/commit/627fee21da71274f738b1064fc12458355d5fa51.

**Comment by guybedford** [comment]
Fixed and released in 0.18.9.

**Comment by WorldMaker** [comment]
:ok_hand: It works for me with 0.18.9. Thanks!
