### ISSUE TITLE
IE8 breakage: Object.keys when re-exporting

### ISSUE THREAD

**Issue by mattfysh** [systemjs/systemjs#627]
Not sure which project to raise this. the following code processed by SystemJS builder
```
export * from './bar';
```
results in transpiled code which uses `Object.keys`, breaking IE8
```
setters: [function($__m) {
      Object.keys($__m).forEach(function(p) {
        if (p !== 'default' && !$__exportNames[p])
          $__export(p, $__m[p]);
      });
    }]
```
We could add the es5shim, but it would be nice if all of the ES6 module syntax transpiled to systemjs would work on ES3 systems. A couple of other questions
- should this syntax also re-export 'default'?
- where can I find the templates used for generating SystemJS modules to see if there are other non-ES3 constructs?

thanks!

**Comment by guybedford** [comment]
This is Traceur's output which is not compatible with IE8 - Traceur will only support IE9+ I believe. Most transpilers expect a full ES5 environment so the best thing to do is to add a custom step to include an ES5 shim for IE8, then carefully pick ES features that transpile and work on top of the shim layer.

**Comment by mattfysh** [comment]
thanks @guybedford, for some reason I assumed babel was the default but I've now switched to that and the output looks to be IE8-compatible. I remember reading that when babel transpiles to systemjs format, this will always be ES3-friendly, is that still the case... is the long term plan to continue to have babel's transpiler work with IE8? Cheers!

**Comment by guybedford** [comment]
Sure, no problem. Yes no transpilers support IE8 natively - it's really up to the transpilers to decide what they support. The shim workflows may work better with some transpilers than others, but ES5 shims are pretty reliable.
