### ISSUE TITLE
ES6 detection of tsc --t es6 output

### ISSUE THREAD

**Issue by nicklasb** [systemjs/systemjs#628]
Hi,
I am using the `tsc --t es6` and `--out app.js` options to emot a single es6 file output from the Typescript compiler. 
The generated code* looks like this: https://github.com/OptimalBPM/mbe-nodes/blob/master/example/static/scripts/app.js

It is ES6-code, it has class declarations and other features, however it seems like the ES6-detection doesn't react to it and treats it as a ES5-file, doesn't invoke traceur/babel and complains about the fat arrow syntax instead.

If I add `"format es6"` at the top, it is successfully recognized. But that should not be necessary, and also there seem to be no non buildscript-way of automating it. So it doesn't integrate well with my work flow. 

*I am in the middle of migrating from RequireJS, that is why it is all a mess, currently.

**Comment by guybedford** [comment]
Yes only ES6 modules are detected and transpiled automatically. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-formats for more info.

**Comment by nicklasb** [comment]
Ok, 
I have not found any way to force es6 transpilation in the System.import()-call. Is there some option anywhere for that?
If not, my options are:
1. Always build `"format es6";` on top of the typescript output.
2. Try to make the TypeScript crowd add some setting to tsc. Is `"format es6";` some kind of standard syntax that doesn't make something else fail? If so, that would make it easier.
3. Convince you to add more detection(I presume I will fail, though as that could be problematic)

**Comment by guybedford** [comment]
Meta configuration is the suggested way to handle this - 

```javascript
System.config({
  packages: {
    'path/to/app': {
      format: 'esm'
    }
  }
});
```

**Comment by guybedford** [comment]
(where `path/to/app` is the main code folder for your application modules)

**Comment by nicklasb** [comment]
Ok, thanks!

Closing!

**Comment by nicklasb** [comment]
Hi, 
I was a bit too quick closing there, I  tried the syntax you proposed before and I thought I saw an error in how I did it, but it didn't work.

Neither did(also mentioned in https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-formats):

    System.config({
      meta: {
        'path/to/app': {
          format: 'es6'
        }
      }
    });

However, this worked: 

    System.meta['scripts/app'] = {
        format: 'es6'
    };

Not sure why, I thought they would affect the same setting.

**Comment by guybedford** [comment]
Ok sure, yes that's the configuration for the 0.16 SystemJS version.

**Comment by nicklasb** [comment]
Ok, I see. So for posterity, the proper way of specifying the format of a .js file from 0.17 and onward is:

    System.meta['scripts/app'] = {
        format: 'es6'
    };

Closing.

**Comment by nicklasb** [comment]
So I am reopening again. :-)

After adding the setting above, the files are loading and everything seems ok, however, then jspm complains when I try to install a new package:

```bash
$ jspm install angular-ui-layout

err  TypeError: Cannot set property 'scripts/app' of undefined
         at Config.eval (eval at <anonymous> (/home/nibo/develop/mbe-nodes/node_modules/jspm/lib/config/loader.js:92:15), <anonymous>:80:28)
         at Config.read (/home/nibo/develop/mbe-nodes/node_modules/jspm/lib/config/loader.js:92:3)
         at Promise.resolve.then.then.then.then.then.config.loaded (/home/nibo/develop/mbe-nodes/node_modules/jspm/lib/config.js:94:26)
         at tryCatchReject (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at Pending.run (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:821:13)
         at Scheduler._drain (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/home/nibo/develop/mbe-nodes/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:415:13)

warn Installation changes not saved.
```

I am not sure if this is a jspm problem and if I should open it over there, but you are the same guy and all, and the problem may be in system.js.

**Comment by guybedford** [comment]
Yes, this is a jspm issue, but note that System config calls should always be via `System.config({ meta: { 'scripts/app': ... } })` and not `System.meta['scripts/app'] = ...`.

**Comment by nicklasb** [comment]
Ok. Note however that I used the example from the SystemJS docs, they'd need to be updated, then: 
https://github.com/systemjs/systemjs/wiki/Module-Format-Support#format-detection

Should I create a separate jspm issue?

**Comment by nicklasb** [comment]
But wait, using the System.config-approach didn't work (I just saw that I had already tried that above)

**Comment by nicklasb** [comment]
Either way, I should mention that I no longer compile this way(using --out), so the setting is not needed.
For posterity, I would say that using `--out` is not needed when having a working module import system in place.

**Comment by guybedford** [comment]
The SystemJS wiki is out of date (there is a note at the top mentioning this). Rather use the in-repo docs at https://github.com/systemjs/systemjs/tree/master/docs.

Sure, it sounds like a naming issue with the name of the bundle itself outputted by the builder. Names have to very carefully match up, that is why it is advisable to use SystemJS builder for bundling, and to not output names for single-file compiles.

Hope it's making some sense :)

**Comment by nicklasb** [comment]
Ok, not using it for building yet, but I am getting there.
Making sense is overrated. :-)
