### ISSUE TITLE
How to ignore css assets for a specific package?

### ISSUE THREAD

**Issue by ChrisPiechowicz** [systemjs/systemjs#632]
Is it possible to ignore package assets for a specific package?
I have separate SASS files but my stylesheets are overridden by original package assets.

package config:
    "github:chieffancypants/angular-loading-bar@0.8.0": {
      "angular": "github:angular/bower-angular@1.4.2",
      "css": "github:systemjs/plugin-css@0.1.13"
    },

the package js file contains this:
"deps ./loading-bar.css!";

I don't want to manually comment this line.

**Comment by guybedford** [comment]
This behaviour comes from the override created at https://github.com/jspm/registry/blob/master/package-overrides/github/chieffancypants/angular-loading-bar%400.8.0.json.

You can locally override this override with:

```
  jspm install github:chieffancypants/angular-loading-bar -o "{main:'build/loading-bar',dependencies:{angular:'*'},shim: {'build/loading-bar': deps:['angular']}}"
```
```

**Comment by ChrisPiechowicz** [comment]
Thanks, it works :)
