### ISSUE TITLE
JSPM Aurelia typescript with transpiler

### ISSUE THREAD

**Issue by aidesigner** [systemjs/systemjs#635]
My objective was to get the Aurelia navigation skeleton running using the setup below.  From my perspective this setup is the holy grail for a Visual Studio Azure user - JSPM with typescript (strongly typed) in a VS environment.  Primarily I have been struggling with systemjs and file extension ts and js (solved).  I am new to jspm and wonder if these features are not ready, or I am making fundamental errors.  Note: I ran "jspm dl-loader --edge" to get latest loader.

1) Most of the Chrome errors below show the ".js" extension is missing from the core-js package.  I tried using the "packages" section in config.js to tell systemjs to add extensions and specify the default entry point.  Is it expected to add "packages" config for each package?

2)  I have found type definitions for core-js (ie. core-js.d.ts).  Is this of any value to systemjs as core-js is a dependency of most Aurelia packages?

3)  Is there another approach to all this where jspm/systemjs bundles this all up and my problems go away?  I assume using Aurelia sources while in alpha is advisable.

**Chrome console Error:**
http://localhost:54179/jspm_packages/npm/core-js@0.9.18/modules/core.dict 404 (Not Found)
http://localhost:54179/jspm_packages/npm/core-js@0.9.18/modules/core.$for 404 (Not Found)
// Many errors of this sort

**Setup:**
-Visual Studio 2015 RTM, typescript
-JSPM, Systemjs (transpiler "typescript")

**package.json:**
  "jspm": {
    "directories": {
      "baseURL": "wwwroot"
    },
    "dependencies": {
      "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.14.0",
      "aurelia-framework": "github:aurelia/framework@^0.13.2",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@^0.9.0",
      ...
      "core-js": "npm:core-js@^0.9.18"
    },
    "devDependencies": {
      "typescript": "github:mhegazy/typescript@v1.5-beta2"
    },
    "overrides": {
      "npm:core-js@0.9.18": {
        "main": "client/shim.min"
      }
    }

**config.js:**
System.config({
  "baseURL": "/",
  "defaultJSExtensions": false,
  "transpiler": "typescript",
  "paths": {
    "npm:*": "jspm_packages/npm/*",
    "github:*": "jspm_packages/github/*"
  },
  "packages": {
    "npm:core-js@0.9.18": {
      main: "index.js",
      defaultExtension: "js"
    },
    "github:mhegazy/typescript@v1.5-beta2": {},
    "github:aurelia/bootstrapper@0.14.0": {
      "main": "index.js",
      "defaultExtension": "js"
    }
  }
});

**Actions:**
>jspm dl-loader --edge
>jspm cc

**Resources:**
https://github.com/systemjs/systemjs/issues/490
https://github.com/aurelia/bootstrapper/issues/10
https://github.com/frankwallis/plugin-typescript/issues/33
https://github.com/Microsoft/TypeScript/issues/3956

**Comment by aidesigner** [comment]
**Issue 1 solved:**  This somehow worked, but this level of intervention cannot be appropriate?
Before:  "packages": {  "npm:core-js@0.9.18": {...}   }
After:  "packages": {  "npm:core-js@0.9.18/modules": {...}   }

**Issue 3:** Still open.
**Issue 4:** Still open.

Getting JSPM, Systemjs, aurelia, and VS 2015 RTM to work together seems to be complicated.  Any comments about flaws in my approach are definitely welcome.  Especially if somewhat has this all working.  Hopefully I did not misuse this site as it all revolved around systemjs.

**Comment by guybedford** [comment]
This sounds like a jspm issue. Make sure you're using the 0.16 jspm version via `npm install jspm@beta` and then make sure to set `defaultJSExtensions: true`. jspm does not yet support the `defaultJSExtensions: false` option - that will be for 0.17.

**Comment by aidesigner** [comment]
Thanks, but I have the latest on everything including npu install jspm@beta.  While defaultJSExtensions: false is not officially supporting it does appear to prevent automatic js extension.  My basic issue is I have some JS files (Aurelia framework, core-js, etc) and also have some TS files (My Aurelia Views). 

**Problem:**
defaultJSExtension:true  lines like "aurelia.start().then(a => a.setRoot('src/app', document.body));" look for app.ts.js.
**Failed solutions:
-System.Config({"paths": {"app.js": "app.ts"}})
-Referencing app.ts like "app!typescript"
- Possibly try frankwallis/plugin-typescript plugin which has a way of rerouting and compiling all ts files itself.

As a secondary question am I crazy trying to transpiler my ts files with jspm/systemjs.  Due to performance I guess I should compile ts files locally with gulp. except for initial development/debug?

**Comment by guybedford** [comment]
I would strongly suggest going with the TypeScript plugin workflow here as the jspm TypeScript workflow is currently very experimental and not polished enough for real world projects yet. The plugin has got great support though and should be relatively straightforward to set up I believe.

**Comment by vladima** [comment]
@aidesigner I've made a few changes [here](https://github.com/aurelia/skeleton-navigation/compare/master...vladima:master) in original skeleton-navigation example to make it work with TypeScript as a transpiler

**Comment by aidesigner** [comment]
At the moment I am content with compiling typescript locally with Visual Studio (https://github.com/Microsoft/TypeScript/wiki/Using-TypeScript-With-ASP.NET-5) or Gulp (https://github.com/louislewis2/Aurelia-Demo).  Thank you for the link as it will benefit others.

I am now a little unclear as to the benefits of TypeScript transpiler.  It adds some workload to the browser and maybe inhibits bundling/minimization without any advantage.  The ts source maps can be delivered with the transformed js to the browser, which provides a good developer debug experience.  It what scenario would you recommend TypeScript transpiler?

**Comment by vladima** [comment]
@aidesigner I guess using in-browser transpile can be beneficial during the development, you can omit build step, just edit .ts file and hit F5 to refresh the page. For production scenarios local compilation is definitely preferable.
