### ISSUE TITLE
Converting between jspm and bower configs

### ISSUE THREAD

**Issue by MaluTom** [systemjs/systemjs#637]
Hello,

Where I work, we use a proxy with NTLM authentication for access to github. This makes using system js with jspm dependencies not possible since the http components within jspm doesn't seem to support proxy auth using NTLM (see here for more - https://github.com/jspm/github/issues/59). This unfortunately leaves me with using bower for downloading dependencies.

At the same time, I'm working with the aurelia framework which has a skeleton project built using jspm and using  config.js to load dependencies. However, I'm not exactly sure how to translate between a config.js file using jspm dependencies and a config.js file using bower dependencies. Are there any utils available that will help with this?

**Comment by matthewbauer** [comment]
Take a look at https://github.com/stealjs/system-bower

It may be what you're looking for.

**Comment by guybedford** [comment]
Proxies can be configured for jspm via the proxy environment variables - https://github.com/request/request#controlling-proxy-behaviour-using-environment-variables.

Closing as this is a jspm issue not a SystemJS one, but any trouble with the proxy configuration please do post another jspm issue and I will do what I can to help.
