### ISSUE TITLE
extended typescript classes will not load in system

### ISSUE THREAD

**Issue by lucasstrange** [systemjs/systemjs#641]
extended typescript (version 1.5) classes, compiled with the 'System' module option, will not load.

example:

export class foo {
}

export class bar extends foo {
}

throws error...  Uncaught TypeError: Multiple anonymous System.register calls in the same module file. 

javascript generated by the typescript compiler shown below...

var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};System.register([], function(exports_1) {
    var foo, bar;
    return {
        setters:[],
        execute: function() {
            foo = (function () {
                function foo() {
                }
                return foo;
            })();
            exports_1("foo", foo);
            bar = (function (_super) {
                __extends(bar, _super);
                function bar() {
                    _super.apply(this, arguments);
                }
                return bar;
            })(foo);
            exports_1("bar", bar);
        }
    }
});
//# sourceMappingURL=foobar.js.map

**Comment by guybedford** [comment]
This has been fixed in TypeScript in https://github.com/Microsoft/TypeScript/pull/4111.

For now, you need to manually add `"format register"` to the top of the source. Or use meta configuration:

```javascript
System.config({
  meta: {
    'path/to/app/*': { format: 'register' }
  }
});
```

**Comment by lucasstrange** [comment]
Thanks.  System with typescript has really made writing javascript fun.
