### ISSUE TITLE
Require node modules with NodeJS

### ISSUE THREAD

**Issue by Tiinusen** [systemjs/systemjs#642]
What is the correct method to require global modules?

require('path') as example, which is a global node package
or if I have installed packages locally such as express which included with require('express').

So what is the proper way to include global or local npm packages in node?

Is there a way to make SystemJS quite seamlessly with NodeJS require path

**Comment by matthewbauer** [comment]
I think you'll want to use jspm: http://jspm.io/

It will manage your config.js and with:

```
jspm init
jspm install path
```

You should be able to require('path') in SystemJS after you've required the config.js file generated by jspm.

If you don't want to use jspm, you can use:
```js
path = System._nodeRequire('path');
```

To get path directly from node. Of course, remember that this code will only work in Node environments.

**Comment by robertsundstrom** [comment]
Is there really no straightforward way to import Node modules without having to treat in-built Node modules as some special kind?

If no, is this something that will be addressed in the future? Or, will we have to wait for Node.js to implement this?

**Comment by guybedford** [comment]
SystemJS is a browser loader first and foremost. jspm then provides compatibility for Node/npm modules via SystemJS's resolution system and makes that work in Node as well. A NodeJS-first module loader like SystemJS that implements the Node module resolution algorithm is something that someone could make certainly.
