### ISSUE TITLE
Can't find any information with respect to dynamic imports and self executing bundles..

### ISSUE THREAD

**Issue by buddyp450** [systemjs/systemjs#643]
I get the very clear error message in my self-executing bundle that my code fails at ```return System.import(path)``` because "Dynamic System.import calls are not supported for SFX bundles. Rather use a named bundle."

It's unclear to me what a "named" bundle is, how to make one, or why dynamic import calls fail at all.

Could someone please elaborate on the steps I need to take in order to make dynamic import calls work? Do I just need to bundle normally? (Non self-executing?) I was using a self-executing bundle as a way around another issue so I'd like to continue using it as such.

**Comment by matthewbauer** [comment]
I agree that the documentation and error messages need to be improved.

However, for your situation in particular, I think you're going to need to include SystemJS in your runtime for System.import to work.

**Comment by buddyp450** [comment]
When I include SystemJS individually it requires a huge tree of dependencies that I have to make available via my server mostly all underneath ```jspm_modules```. Any way around this? I'd like to not have to expose that entire tree. Unfortunately with the server architecture I'm working with it doesn't allow catch-alls like exposing ```/jspm_modules/*```.

**Comment by guybedford** [comment]
@buddyp450 you only need to serve `system-polyfills.js` and `system.js` to use a normal bundle.

**Comment by guybedford** [comment]
Just let me know if you still have any questions here.
