### ISSUE TITLE
TypeScript calls to super methods are broken with external ES6 modules

### ISSUE THREAD

**Issue by aphex** [systemjs/systemjs#647]
When setting up some basic inheritance with TypeScript I am seeing that super method calls are not being transpiled properly. This could likely be an issue for tsc but I am wondering if any ordering comes from systemjs.

I am using System JS 0.18.4 and a simplified version of the jspm sample. 

*index.html*
```
<html>
<head>
    <title>Jspm sample</title>
    <script src="jspm_packages/system.src.js"></script>
    <script src="config.js"></script>
</head>
<body>
    <div id="content"></div>
    <script>
        System.import('app');
    </script>
</body>
</html>
```

*config.js*
```
System.config({
  "baseURL": "/",
  "defaultJSExtensions": false,
  "transpiler": "typescript",
  "paths": {
    "*": "*.ts",
    "github:*": "jspm_packages/github/*.js"
  }
});

System.config({
  "map": {
    "typescript": "github:mhegazy/typescript@v1.5-beta2"
  }
});
```

*app.ts*
```
import { Greeter } from 'greeter'
let greeter = new Greeter();
```

*greeter.ts*
```
import { Base } from 'base'

export class Greeter extends Base {
    constructor () {
        super();
        this.run();
    }

    run() {
        console.log('Greeter is running');
        super.run();
    }
}
```

*base.ts*
```
export class Base {
  run() {
    console.log('Base is running');
  }
}
```

The problem is with the second super call, within the run method. It is being transpiled to
```
Greeter.prototype.run = function () {
    console.log('Greeter is running');
    _super.run.call(this);
};
```

When it should be
```
Greeter.prototype.run = function () {
    console.log('Greeter is running');
    _super.prototype.run.call(this);
};
```

The issue is coming from typescript.js (https://github.com/mhegazy/TypeScript/tree/master/bin) line 25322, where the compiler is looking to see if the node has already been processed, if so it will use prototype otherwise just super. 
```
function emitSuper(node) {
                if (languageVersion >= 2 /* ES6 */) {
                    write("super");
                }
                else {
                    var flags = resolver.getNodeCheckFlags(node);
                    if (flags & 16 /* SuperInstance */) {
                        write("_super.prototype");
                    }
                    else {
                        write("_super");
                    }
                }
            }
```

This is due to the order in which nodes are being processed. I am seeing *app.ts* then *greeter.ts* and finally *base.ts*. This needs to change so that all dependencies of *greeter.ts* are processed first, or at least dependencies that are then used in class inheritance.

**Comment by aphex** [comment]
The more I am looking into this the more I think it is all tsc but only in the browser with ES6 Modules. When I run tsc with node everything is transpiled correctly. I am going to open an issue there unless you have any other thoughts on this it can be closed here. 

https://github.com/Microsoft/TypeScript/issues/4118

**Comment by guybedford** [comment]
Thanks for reporting there, yes this sounds like an output issue. Will continue to track there.
