### ISSUE TITLE
system.import does not execute named system.registers

### ISSUE THREAD

**Issue by rkirov** [systemjs/systemjs#648]
Consider:

index.html
```html
<!doctype html>
<html>
  <head>
    <script src="https://jspm.io/system.js"></script>
  </head>
  <body>
    <script>
      System.config({
        paths: {
          '*': '*.js'
        }
      });
      System.import('test');
    </script>
  </body>
</html>
```

test.js
```javascript
System.register("test.js", [], function($__export) {
  "use strict";
  var __moduleName = "test.js";
  return {
    setters: [],
    execute: function() {
      console.log('execed');
    }
  };
});
```

However, removing `test.js` i.e. turning the registration into anonymous executes the module.

**Comment by guybedford** [comment]
Single-file compilation should usually use anonymous module output, because having the module names match up is necessary otherwise to have the bundle work correctly, which will usually not be right.

That is the output should be:

```javascript
System.register([], function($__export) {
  "use strict";
  var __moduleName = "test.js";
  return {
    setters: [],
    execute: function() {
      console.log('execed');
    }
  };
});
```

Note that the above would work with an output of `System.register("test"...` but it is still not advisable to do that.

**Comment by guybedford** [comment]
In Traceur you should be able to set the `moduleName: false` option here?

**Comment by rkirov** [comment]
I see your point why anonymous registration is preferable for single-file compilation. Thanks for the traceur option tip, is should get us unblocked on the plunkr issue.

However, what about bundles? My test below shows the same behavior, System.import xhrs the file but does not execute the module I asked to import.

Assuming I can't change the generated code, is it a bug or a feature that named registered modules do not execute after the System.import call?

(the synthetic `bundle` file I am testing with)
```javascript
System.register("test.js", [], function($__export) {
  "use strict";
  var __moduleName = "test.js";
  return {
    setters: [],
    execute: function() {
      console.log('execed');
    }
  };
});

System.register("test2.js", [], function($__export) {
  "use strict";
  var __moduleName = "test2.js";
  return {
    setters: [],
    execute: function() {
      console.log('execed2');
    }
  };
});
```

**Comment by guybedford** [comment]
If you're using SystemJS 0.16 here, note the correct naming would be `test` not `test.js`. In SystemJS 0.18 the above bundle would load fine though.

**Comment by rkirov** [comment]
Got it, that explains a lot. My mental model was the following for System.import(module_name):

* map module_name using config.paths and config.map to final_module_name 
* XHR localhost/final_module_name 
* eval localhost/final_module_name (which populates System's module cache)
* fetch final_module_name from the cache and call its execute function.

Sounds like in System 0.16 the last step is:

* fetch original module_name for the cache and call its execute function.

While we are here, is __moduleName used or plan to be used in any step of the process above?

**Comment by guybedford** [comment]
Glad you worked it out. Yes exactly, the only change in the mental model between SystemJS 0.16 and SystemJS 0.17+ is that the extension is considered part of the `final_module_name`, while before it wasn't. It's part of the move to making URL's first-class module names.

`__moduleName` is entirely a SystemJS construct, the spec will have something here, we're just waiting for it to be written down. In the mean time we will continue to support `__moduleName` in SystemJS and SystemJS builder.

Just let me know if you have any further questions on this stuff at all.
