### ISSUE TITLE
Unable to run the imported method.

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#650]
I have a **main.ts** file which gets compiled to system module format as below. In the **main.ts** file, I import the module and call the **run** method. My expectation was that the **run** would run. But nothing happens if you look at the compiled code.

I have the following in the index file:

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.js"></script>
<script src="~/js/app/main.js"></script>
```

**main.ts**:

``` javascript
/// <reference path="./systemjs.d.ts" />

System.config({
    baseURL: "/js/app/"
});

import { run } from 'hello-world-internal-module-client';

run();
```

to 

**main.js**

``` javascript
/// <reference path="./systemjs.d.ts" />
System.register(['hello-world-internal-module-client'], function(exports_1) {
    var hello_world_internal_module_client_1;
    return {
        setters:[
            function (_hello_world_internal_module_client_1) {
                hello_world_internal_module_client_1 = _hello_world_internal_module_client_1;
            }],
        execute: function() {
            System.config({
                baseURL: "/js/app/"
            });
            hello_world_internal_module_client_1.run();
        }
    }
});
```

This is how I compile the **ts** files to **js**:

**gulpfile.js**:

``` javascript
var ts = require("gulp-typescript"),

var tsProject = ts.createProject({
    declarationFiles: true,
    noExternalResolve: true,
    removeComments: true,
    module: 'system'
});

gulp.task('ts-compile', function () {
    var tsResult = gulp.src(paths.tsSource)
                    .pipe(ts(tsProject));

    return merge([tsResult.js.pipe(gulp.dest(paths.tsOutput))
    ]);
});
```

**Comment by guybedford** [comment]
Note that `~/js/app/main.js` seems like an invalid URL. Your index file would need to look like:

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.js"></script>
<script>
  System.config({
    baseURL: "/js/app/"
  });
  System.import('main.js');
</script>
```

That is the top-level import must be a dynamic `System.import` call as modules aren't supported loading through script tags. Also the `System.config()` call can't be in a module itself as that is too late to configure the baseURL.

**Comment by varghesep** [comment]
Thank you for that information. Now I get another 404 error saying 
   Request URL: http://localhost:5000/js/app/hello-world-internal-module-client can't be loaded. As you may notice the module name does not have JS file extension. I added .JS file but gives me other errors.

**Comment by guybedford** [comment]
Yes you would need to include the file extension here. Babel and Traceur are only needed when transpiling in the browser (which it doesn't look like you are here).

**Comment by varghesep** [comment]
I added the .ts as well as .js file extension to the module reference in **main.ts**. When I try to compile via gulp task, I get the error:

Could not find module ''hello-world-internal-module-client.ts''

However, I don't get any error if I don't use the extension. But I get the 404 when I load the site in browser.
 
``` javascript
/// <reference path="./systemjs.d.ts" />

import { run } from 'hello-world-internal-module-client.ts';

run();
```

**Comment by guybedford** [comment]
Right, try using the TypeScript `transpile` API instead that runs modules as isolated compiles. Then you just need to ensure the extensions match up in the references in the transpiled files. These workflows aren't very polished at the moment, so it can be a tough path to work out.

**Comment by varghesep** [comment]
I see that it is working after I made the change. I included **es6-module-loader** as well as used the JavaScript transpiler as you suggested.

``` html
        <script src="https://cdnjs.cloudflare.com/ajax/libs/typescript/1.0.0/typescript.js"></script>
        <script src="~/lib/es6-module-loader/dist/es6-module-loader.js"></script>
        <script src="~/lib/es6-module-loader/dist/es6-module-loader.src.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.18.4/system.js"></script>
        <script src="~/js/app/main.js"></script>
```

``` javascript
System.config({
    baseURL: "/js/app/",
    transpiler: 'typescript'
});
System.import('hello-world-internal-module-client.js').then(function (m) {
    new m.run();
});
```
Do you think I'm following the right pattern?

Do you mind explaining a little the role of the typescript (babel or traceur) transpiler here? I already use a package called **gulp-typescript** to compile the TS files to JS, so the transpiler is being used already. Why should I specify it again during the run time?

**Comment by guybedford** [comment]
This looks like the right general direction to be taking. Note you don't need to include `typescript.js` or `es6-module-loader.src.js` or `es6-module-loader.js` int he above app.

It isn't necessary to specify the transpiler for runtime here, the workflow of pre-compiling means skipping the internal SystemJS transpilation layer, which is advised as the internal TypeScript transpilation support is very limited.
