### ISSUE TITLE
Regular expression performance

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#653]
We need to investigate the performance of the regular expression changes, it sounds like there may be an issue here - https://github.com/systemjs/systemjs/commit/7ab76a4b1e76f2c03e189336646f256fe4e25adb#commitcomment-12516620.

**Comment by guybedford** [comment]
@m4r71n is there anyway you can share a sample of your codebase that has these performance issues? I'm still unable to find any test that can capture this regression.

**Comment by m4r71n** [comment]
@guybedford yes try `https://github.com/m4r71n/systemjs-performance.git` with 0.18.6 and 0.18.4

**Comment by guybedford** [comment]
Awesome, thanks so much, yes that is a really bad regression. Resolved in https://github.com/systemjs/systemjs/commit/fa4f8dca04302a390d27d59c69eda703790087a6.

**Comment by guybedford** [comment]
Released in 0.18.8.
