### ISSUE TITLE
CommonJS only detects require() statements used in assignments

### ISSUE THREAD

**Issue by lizardruss** [systemjs/systemjs#654]
Thanks for the great work on SystemJS!

I have an edge case that's probably rare, but it would be nice if SystemJS could support it. Consider the following code where a module is required but not assigned.
```javascript
require('myModule').myMethod();
```

It seems that SystemJS doesn't recognize `myModule` as a dependency, so I get the error "Module myModule not declared as a dependency."

If I change this code to use an assignment, it works correctly.
```javascript
var myModule = require('myModule');
myModule.myMethod();
```

**Comment by guybedford** [comment]
This definitely works fine for me if I write a file containing those exact contents and import it. Are you sure that's all that is needed to replicate?

**Comment by lizardruss** [comment]
This is definitely due to how I'm using it, and probably not related to normal usage. I'll close this since testing the regex in isolation works.
