### ISSUE TITLE
Error when using depCache: TypeError: Cannot read property 'done' of undefined

### ISSUE THREAD

**Issue by lizardruss** [systemjs/systemjs#656]
I'm seeing a runtime error on this line: https://github.com/systemjs/systemjs/blob/381491ace80b190e3f496d329447237cfd6fef09/dist/system.src.js#L470

After debugging with devtools, `existingLoad.linkSets` is an empty array.

I used the `jspm depcache` command to set up the depCache SystemJS configuration. Let me know if there's any other details needed. Thanks!

**Comment by guybedford** [comment]
Thanks, do you have an example project test case for this at all you can share? Help replicating would be really appreciated.

**Comment by lizardruss** [comment]
Had a hard time reproducing this one, but finally got an example put together:
https://github.com/lizardruss/systemjs_example

The example is pretty contrived, but the `tests` module is dynamic in that it can be based off of runtime input. I also need SystemJS to analyze it for dependencies. This is why I've overridden `System.fetch`. If there's a better way to accomplish that, please advise. I tried using `System.module(source, options)`, but could not figure out a way to create a named module named with that method.

Without the depcache, this works fine, but with the depcache configured, I get the error mentioned.

**Comment by lizardruss** [comment]
I updated the example to remove the overridden `System.fetch`, and generated a depcache entry for tests.js, and the error still occurs.

**Comment by guybedford** [comment]
Amazing thank you so much for taking the time to put this together!

I've included a fix at https://github.com/ModuleLoader/es6-module-loader/commit/c518b8c4d23d7699062e036f8fea64a4a9575d4c, will post the release as soon as I can.

**Comment by guybedford** [comment]
Released in 0.18.8.
