### ISSUE TITLE
Map configuration cannot go 'above' baseURL?

### ISSUE THREAD

**Issue by jamiewinder** [systemjs/systemjs#661]
I have a project using SystemJS which stores all of its modules in a folder called 'src'. It also has some external libraries, including SystemJS loaders, in a sibling folder called 'lib'. So:
```
/src/
    config.js
    startup.js
/lib/
    moment.js
    systemjs/plugin-css.js
    systemjs/plugin-text.js
```
To support this, I tried to use the following config:
```javascript
System.config({
    baseURL: "src",
    map: {        
        "lib": "../lib",
        "css": "../lib/systemjs/plugin-css",
        "text": "../lib/systemjs/plugin-text"
    }
});
```
But this doesn't appear to work. For example, when it tries to load the CSS loader, it appears to look for 'src/lib/systemjs/plugin-css.js'. It looks like I'm being prevented from going 'above' the baseURL which sort-of makes sense, but is a bit prohibitive in this case.

**Comment by guybedford** [comment]
Yes this is by design. For other custom paths, use the paths configuration instead of map configuration.

**Comment by jamiewinder** [comment]
Thanks Guy. I tried this with paths also, but didn't have much luck. Are the kind of mappings I'm trying to make even feasible? i.e.:
```
lib/moment > lib/moment.js (starts with 'lib', so not under baseURL of 'src')
app/app > src/app/app.js (doesn't start with lib, so assume it's under the baseURL)
app/app.css! > src/app/app.css (and loaded with lib/systemjs/plugin-css.js)
```
Seems like I need to specify a default path of 'src', but only if no other matching paths are found (i.e. 'css', 'text', or starts with 'lib/'). I'll try to figure it out, but if you can give me any insight it'd be appreciated. I'll update if I figure it out! :)

**Comment by guybedford** [comment]
```javascript
    paths: {        
        "lib": "./lib",
        "css": "./lib/systemjs/plugin-css",
        "text": "./lib/systemjs/plugin-text"
    }
```

Should just work here.

**Comment by jamiewinder** [comment]
Great thanks. Not sure what I was doing wrong, but using your example seemed to do the trick. 

Thanks again.
