### ISSUE TITLE
Use map in other map?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#662]
Using not quite modular projects like *Three.js* you sometimes need to use other files from packages. It would be nice if it was possible to create maps to these files using a map to the general project. 
Would something like this work: 
```
System.config({
  "map": {
    "three.js": "github:mrdoob/three.js@master",
    "three.js/loaders/STLLoader": "three.js/examples/js/loaders/STLLoader.js",
  }
});
```
To clarify, I'd like to use both `three.js` and `three.js/loaders/STLLoader` in my project. 
Basically my question is; can mappings build on other mappings? 

There is a lot of overlap with https://github.com/systemjs/systemjs/issues/596 but that issue didn't really answer my question.

**Comment by guybedford** [comment]
Yes, you can do this via internal package map configuration:

```javascript
System.config({
  packages: {
    'three.js': {
      map: {
         './loaders/STLLoader': './examples/js/loaders/STLLoader.js'
      }
    }
  }
});
```

**Comment by peteruithoven** [comment]
Alright but, that would enable importing `./loaders/STLLoader` in the `three.js` package alone. I'd like to import both `three.js` and `three.js/loaders/STLLoader` in my main application. So if I understand SystemJS's configuration correctly I'd need them both globally.

**Comment by guybedford** [comment]
No it would apply to external imports as well.

**Comment by peteruithoven** [comment]
I apologize, I don't fully understand the packages configuration. I'm confused by the following line:
> In addition packages allow for setting contextual map configuration which only applies within the package itself.

How can configuration be applied only within specific packages but also influence "the global scope"? 

In the [Configuration API: packages docs](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) the following example is used: 
``` javascript
System.config({
  packages: {
    // meaning [baseURL]/local/package when no other rules are present
    // path is normalized using map and paths configuration
    'local/package': {
      main: 'index.js',
      format: 'cjs',
      defaultExtension: 'js',
      map: {
        // use local jquery for all jquery requires in this package
        'jquery': './vendor/local-jquery.js'

        // import '/local/package/custom-import' should route to '/local/package/local/import/file.js'
        './custom-import': './local/import/file.js'
      }
      meta: {
        // set meta for loading the local vendor files
        'vendor/*': {
          'format': 'global'
        }
      }
    }
  }
});
```
This also uses a map in a package configuration, does this also add a map for the "global scope"?

**Comment by peteruithoven** [comment]
When using the following configuration `three.js/loaders/STLLoader` is normalized into `http://localhost:3000/jspm_packages/github/mrdoob/three.js@master/loaders/STLLoader.js`
```javascript
System.config({
  'map': {
    'three.js': 'github:mrdoob/three.js@master',
  }
  'packages': {
    'three.js': {
      map: {
        './loaders/STLLoader': './examples/js/loaders/STLLoader.js'
      }
    },
  }
});
```
Which is the result as when that packages configuration doesn't exist.

The following configuration works: 
``` javascript
System.config({
  'map': {
    'three.js': 'github:mrdoob/three.js@master',
    'three.js/loaders/STLLoader': 'github:mrdoob/three.js@master/examples/js/loaders/STLLoader.js'
  }
});
```
This normalizes `three.js/loaders/STLLoader` into 
`jspm_packages/github/mrdoob/three.js@master/examples/js/loaders/STLLoader.js`.
But I'd like to shorten it to: 
``` javascript
System.config({
  'map': {
    'three.js': 'github:mrdoob/three.js@master',
    'three.js/loaders/STLLoader': 'three.js/examples/js/loaders/STLLoader.js'
  }
});
```

But maybe I should simply do something like the following?
``` javascript 
var threejsMap = 'github:mrdoob/three.js@master';
System.config({
  'map': {
    'three.js': threejsMap,
    'three.js/loaders/STLLoader': threejsMap+'/js/examples/js/loaders/STLLoader.js'
  }
});
```

**Comment by peteruithoven** [comment]
If I can figure out https://github.com/systemjs/systemjs/issues/669, I could probably figure this one out myself.

**Comment by guybedford** [comment]
I'm still not sure why you don't just use

```javascript
System.config({
  packages: {
    'three.js': {
      map: {
         './loaders/STLLoader': './examples/js/loaders/STLLoader.js'
      }
    }
  }
});
```

here. It is exactly designed for the `System.import('three.js/loaders/STLLoader')` use case.

**Comment by peteruithoven** [comment]
You where right, I just don't understand the packages section.
I've added an example to a new config playground: 
http://codepen.io/peteruithoven/pen/LVqqQQ?editors=001

**Comment by peteruithoven** [comment]
An example repository where this is working: 
https://github.com/Doodle3D/jspm-threejs-using-examples

**Comment by peteruithoven** [comment]
Actually, scratch that, that example doesn't work. 
I still had a `"three.js/loaders/STLLoader": "github:mrdoob/three.js@master/examples/js/loaders/STLLoader.js",` mapping, after removing that it fails. 
https://github.com/Doodle3D/jspm-threejs-using-examples

The packages > three.js > map configuration seems okay:
```
System.packages['http://localhost:3000/jspm_packages/github/mrdoob/three.js@master.js'].map
> 
Object {./loaders/STLLoader: "./examples/js/loaders/STLLoader.js"}
```

**Comment by guybedford** [comment]
@peteruithoven thanks, this is actually an issue in jspm that the map config does not apply before the meta config - if it did this configuration would work for you fine.

If you rather use the full mapped name in the package config then instead:

```javascript
System.config({
  "meta": {
    "github:danialfarid/ng-file-upload-bower@6.0.4/ng-file-upload.js": {
      "deps": [
        "ng-file-upload-shim"
      ]
    }
  }
});
```

**Comment by guybedford** [comment]
There is actually a PR to fix this at https://github.com/jspm/jspm-cli/pull/965.

**Comment by peteruithoven** [comment]
But this is about adding an extra map through a `packages` config. Do you mean this issue for `meta` also applies on `packages`?

**Comment by guybedford** [comment]
Yes exactly - I meant to include the `packages` example above with the full name used.

**Comment by peteruithoven** [comment]
So I understand the fix is merged, released as beta-6. I've done `npm install -g jspm@beta` which installed that version and then I did a `jspm install` in the example above. I see it has combined all the config, it put meta en packages above map. 
But the normalization still fails to use that packages configuration.

**Comment by guybedford** [comment]
This particular example is actually an edge case with defaultJSExtensions and `three.js` ending in js! If you install it aliased to `three` instead of `three.js` it will work though. This was an edge case we had to introduce to make the upgrade path bearable.

**Comment by peteruithoven** [comment]
Ah... interesting. Even though in never versions it didn't seem to add .js behind imports that already ended with .js?
I can confirm that removing the `.js` fixes the `three/loaders/STLLoader`! 
Example:
```
System.config({
  ...
  map: {
    ...
    "three": "github:mrdoob/three.js@master",
    ...
  },
  packages: {
    "three": {
      "map": {
        "./loaders/STLLoader": "./examples/js/loaders/STLLoader.js"
      }
    }
  },
});
```

But, then the `meta` config isn't picked up, in the following config I've included 3 ways of describing the meta. The `meta` config is picked up when I enable the `"three/loaders/STLLoader": "github:mrdoob/three.js@master/examples/js/loaders/STLLoader.js",` map. 
``` javascript 
System.config({
  ...
  map: {
    ...
    "three": "github:mrdoob/three.js@master",
    //"three/loaders/STLLoader": "github:mrdoob/three.js@master/examples/js/loaders/STLLoader.js",
    ...
  },
  packages: {
    "three": {
      "map": {
        "./loaders/STLLoader": "./examples/js/loaders/STLLoader.js"
      },
      meta: {
        "./loaders/STLLoader": {
          "deps": [
            "three"
          ],
          "globals": {
            "THREE": "three"
          },
          "exports": "THREE.STLLoader",
          "format": "global"
        },
        "three/loaders/STLLoader": {
          "deps": [
            "three"
          ],
          "globals": {
            "THREE": "three"
          },
          "exports": "THREE.STLLoader",
          "format": "global"
        }
      }
    }
  },
  meta: {
    "three/loaders/STLLoader": {
      "deps": [
        "three"
      ],
      "globals": {
        "THREE": "three"
      },
      "exports": "THREE.STLLoader",
      "format": "global"
    }
  }
});
```

System.meta has the incorrect address: `http://localhost:3000/jspm_packages/github/mrdoob/three.js@master/loaders/STLLoader.js`
`System.packages['http://localhost:3000/jspm_packages/github/mrdoob/three.js@master'].meta` contains the following two incorrect paths `./loaders/STLLoader` and `three/loaders/STLLoader`.

Could it be that the packages config isn't loaded before the meta config?

**Comment by guybedford** [comment]
The meta value in the package needs to be the mapped name of `examples/js/loaders/STLLoader.js`.

**Comment by guybedford** [comment]
We could potentially look at supporting package maps for package meta though.

**Comment by peteruithoven** [comment]
Ah so package meta paths are an exception, in that it doesn't go through the regular normalization proces? Or is it that it only doesn't support using the map described in packages config?

**Comment by guybedford** [comment]
Yes, sort of, we don't do any operations to package meta, although we only put configuration through global map (not package map) and global paths, neither of which apply to meta so it would be equivalent to doing nothing even if we did.

**Comment by peteruithoven** [comment]
You're contradicting yourself? It doesn't do any operations on the package meta path or it does, but only using the global `map` and `paths`?

Why wouldn't these global configs apply to meta?

**Comment by guybedford** [comment]
To clarify - base-level meta goes through map and paths (but not package map), package meta goes through nothing, which is equivalent anyway to as if it went through global map and paths.

**Comment by peteruithoven** [comment]
Thanks for clearing up the first part. 

> which is equivalent anyway

Because it's relative from the packages path? And because the `map` and `paths` rarely influences the last part of a path? If that's true, that sounds like an okay assumption, but it's still an assumption.

**Comment by guybedford** [comment]
Yes, relative paths never go through map and paths because they are URL-relative at that point. Only plain names like `jquery` or `pkg/path` go through map and paths.
