### ISSUE TITLE
Meta paths normalized?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#664]
The current [Configuration API:meta docs](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta) don't really mention whether the meta paths are normalized using the `map` and `paths` config. 
Can I for example do the following? 
```
System.config({
  "map": {
    "three.js": "github:mrdoob/three.js@master",
  }
  "meta": {
    "three.js": { // referring to mapped three.js
      format: 'global',
      exports: 'jQuery'
    }
  }
});
```

**Comment by peteruithoven** [comment]
Same goes for the [packages configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages).

**Comment by guybedford** [comment]
Yes both are normalized. This is definitely worth fixing in the documentation.

**Comment by peteruithoven** [comment]
Thanks for the quick reply, I created a pull request with an doc clarification attempt.
