### ISSUE TITLE
Config playground

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#669]
Since I'm really struggling with understanding SystemJS's configuration I started thinking on ways that could clarify it, besides more documentation. 
One idea is creating a little playground, where one can play around with config and try normalizing different path's. 
But I'm missing some SystemJS API info to make it useful. 
I'm hoping there for example is a sync normalize function available that I can just pass path and it returns a normalized path. But it isn't mentioned in the current [System API](https://github.com/systemjs/systemjs/blob/master/docs/system-api.md). 
I'm also hoping to use System.get() to retrieve meta information on paths. 

Current version: 
http://codepen.io/peteruithoven/pen/OVdxYJ?editors=001

**Comment by peteruithoven** [comment]
I've come a lot further. I'm now working with promises everywhere. I found most of the docs I needed with the es6-module-loader, which makes sense in hindsight. 
http://codepen.io/peteruithoven/pen/OVdxYJ?editors=001

I am struggling with only having access to an older SystemJS version (https://jspm.io/system.js). 
There isn't any way I could get the latest beta online? 
Using something like: `https://jspm.io/system@beta.js`

I still haven't figured out how to retrieve meta data. Relevant for issues like: https://github.com/systemjs/systemjs/issues/666

**Comment by peteruithoven** [comment]
For now I'm using the latest system.js from github using: 
`https://raw.githubusercontent.com/systemjs/systemjs/master/dist/system.js`

**Comment by guybedford** [comment]
Glad to hear you're making sense of the normalization. I did plan on writing a document that detailed the exact normalization flow, but haven't got around to that yet. Package and plugin normalization does make it a little more complex. Also the `defaultJSExtensions` stuff complicates it far more than it should be, which will come away in future luckily.

The simple normalization code flow is:

1. Contextual (internal) package map (module names not starting in `./` in package map) (https://github.com/systemjs/systemjs/blob/master/lib/package.js#L130-L145)
2. Global map config (https://github.com/systemjs/systemjs/blob/master/lib/map.js#L24)
3. URL normalization for relative paths to parent or baseURI (https://github.com/systemjs/systemjs/blob/master/lib/core.js#L60)
4. Check if the module is already in the registry (eg `@empty` doesn't URL-normalize), then final paths and URL normalization against baseURL or baseURI (`./x` means baseURI-relative, `x` means baseURL-relative) (https://github.com/systemjs/systemjs/blob/master/lib/paths.js#L12)
5. Internal package map (`./` package map names, and other things) (https://github.com/systemjs/systemjs/blob/master/lib/package.js#L153-L204)

The super simple concept is `map -> URL-normalize to parent if relative -> paths if not relative -> URL normalize to baseURI if not absolute`.

The package map then sort of wraps the above simple process. Then we wrap that with plugin normalization applying first (https://github.com/systemjs/systemjs/blob/master/lib/plugins.js#L12) as well.

**Comment by peteruithoven** [comment]
Thanks for that explanation, that would definitely deserve it's own doc page. 

The problems stays that SystemJS is quite a blackbox. I see some similarities with the issues with App Cache, to use it you have to understand a very big spec. I've been struggling with meta configuration for almost 2 days and I'm still quite lost. 
I personally feel we need ways to more easily check the effects configuration has and be able to play with it. 
This is quite simple with the normalization process, but when it comes to meta and packages configuration I'd like to see for example:
- globally 
  - added globals 
  - formats used for packages
- package specific (through `packages` configuration)
  - added globals 
  - formats used for packages
  - alterations in normalizations
- package specific (through `meta` configuration)
  - deps
  - successfully loaded deps
etc etc.

I now understand I can check System.meta en System.packages for example to verify if configuration was normalized correctly, but this only gives me a small part of the info. 

This also regularly requires the actual packages, which means I can't turn it into a codepen like example. 

Possible solutions: 
- More (info on) functions on System to retrieve the effects.
- Using something like the [debug module](https://www.npmjs.org/package/debug) to conditionally show what's happening. 

I'm curious what you think.

**Comment by guybedford** [comment]
Interesting, so you want to be able to play around with how the inputs affect the outputs? You could probably write extensions to the loader to be able to inspect the meta for a module and its dependencies etc.

For example, an instantiate hook like:

```javascript
var systemInstantiate = System.instantiate;
System.instantiate = function(load) {
  var instantiateResult;
  return systemInstantiate.call(this, load)
  .then(function(result) {
    instantiateResult = result;
    return Promise.all(result.deps.map(function(dep) {
      return System.normalize(dep, load.name);
    });
  })
  .then(function(normalizedDeps) {
    var loadInfo = {
      name: load.name,
      deps: normalizedDeps,
      meta: load.metadata
    };
    console.log(loadInfo);
    return result;
  });
};
```

You could even give dummy hooks to turn it into a toy loader and just get the metadata information out you wanted.

More examples is definitely a great point as well. Perhaps a common configurations guide that lists scenarios.

**Comment by peteruithoven** [comment]
I've created a new playground with a more per config type examples approach:
http://codepen.io/peteruithoven/pen/LVqqQQ?editors=001

**Comment by peteruithoven** [comment]
I created a separate debugger issue: https://github.com/systemjs/systemjs/issues/678
