### ISSUE TITLE
Docs: normalization page

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#675]
As discussed in #669 it would be helpful to have a import path normalization specific documentation page. 
It could elaborate on the following explanation:
https://github.com/systemjs/systemjs/issues/669#issuecomment-128421919
It could link to a playground so people can easily experiment: 
http://codepen.io/peteruithoven/pen/LVqqQQ?editors=001

**Comment by peteruithoven** [comment]
We could link to it from all the places that allow normalized paths.

**Comment by guybedford** [comment]
:+1:

**Comment by peteruithoven** [comment]
We could add a short chapter on the packages > meta path, explaining that those don't go through the regular map and paths normalization. If there are more exceptions this could be a more general exceptions chapter. 
A link could be added to this info in the Configuration API page's packages meta documentation.

**Comment by DavidKDeutsch** [comment]
So I see that this (and #707) is closed; is the documentation written? I'm having a hell of a time following the normalization flow between paths, map, meta, packages, baseUri vs baseUrl, etc...
