### ISSUE TITLE
Configuration validation?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#677]
Would it be an idea to validate what configuration is given? This could prevent mistakes like putting `globals` in the `packages` instead of the `meta` configuration, like:
https://github.com/systemjs/systemjs/issues/666#issuecomment-128413473

**Comment by peteruithoven** [comment]
I'm not sure if this could be a part of a validation step, but I could really use some warnings/errors on why specified globals are not created.

**Comment by guybedford** [comment]
@peteruithoven good idea - I've added this in https://github.com/systemjs/systemjs/commit/def97e2c6b10bafdf2f8c11c7d9fa5f169b3bfdf.
