### ISSUE TITLE
SystemJS debugger

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#678]
Like I've mentioned in #669 I was missing information from SystemJS, how it used my config while importing modules. 
With the [tip on using instantiate](https://github.com/systemjs/systemjs/issues/669#issuecomment-128468777) I was able to create a simple script that could output more information. 
When adding the following script in front of the first `System.import()` you'll get info on all the loaded modules. 
``` javascript
"use strict"
var imports = {};
var systemNormalize = System.normalize;
System.normalize = function(path, importFrom) {
  var promise = systemNormalize.apply(this, arguments)
  promise.then(function(normalizedPath) {
    imports[normalizedPath] = {
      importPath: path,
      path: normalizedPath,
      from: importFrom,
      deps: []
    };
  });
  return promise;
}
var systemInstantiate = System.instantiate;
System.instantiate = function(load) {
  var instantiateResult;
  return systemInstantiate.call(this, load)
    .then(function(result) {
      var importData = imports[load.name];
      importData.metadata = load.metadata;
      var fromData = imports[importData.from];
      if(fromData) {
        fromData.deps.push(importData);
      }
      return result;
    });
};
function logImport(importData) {
  console.groupCollapsed(importData.importPath);
  console.log('path: ', importData.path);
  var metadata = importData.metadata;
  for(let metaKey in metadata) {
    if(metaKey == 'deps') continue;
    var metaValue =  metadata[metaKey];
    if(metaValue !== undefined) {
      console.log(metaKey+': ',metaValue)
    }
  }
  console.groupCollapsed('  deps : ',importData.deps.length);
  for(let depData of importData.deps) {
    logImport(depData);
  }
  console.groupEnd();
  console.groupEnd();
}
function logImports() {
  console.group("Imports");
  for(let index in imports) {
    var importData = imports[index];
    // root imports?
    if(importData.from === undefined) {
      logImport(importData);
    }
  }
  console.groupEnd();
}
```
Example usage: 
``` javascript
System.import('app.js').then(function() {
  logImports(); // log imports after import
});
```
Example result:
![screen shot 2015-08-14 at 02 52 44](https://cloud.githubusercontent.com/assets/523210/9277133/72268d1c-42a8-11e5-8b56-3719b78eb561.png)

This is a start, but I'd like to improve this further with:
- [x] Also showing the path that was used to import the module, currently I only have the normalized path. 
- [x] Finding a way to turn this into a tree, following the dependency structure. 
- [x] Turn this into something that can easily be installed, maybe a loader plugin?
- [ ] Find a way to list unused configuration, since this could more easily indicate typo's in path's. 
- [x] Find an easy way to enable / disable it.

**Comment by guybedford** [comment]
Sure! Intercepting `System.normalize` in the same way would allow building up a table to track which module names normalize into a given module at instantiate.

Similarly a table keyed by normalized module name would allow dependency analysis.

In terms of easily enabling it, I guess it's just a script tag to include after SystemJS, or one could set up a sample page that already has it enabled with nice looking outputs etc, not sure what the best experience there would be.

**Comment by peteruithoven** [comment]
Small update; I'm displaying the paths how they where imported and I'm logging imports as a three.

**Comment by peteruithoven** [comment]
For making this easier to install, maintain and share I'd like to turn this into a package that can easily be installed. Possible solutions: 
- [Extend the ES6 Loader](https://github.com/ModuleLoader/es6-module-loader/blob/v0.17.0/docs/loader-extensions.md) and have users import it through an extra `script` tag. 
- [Extend the ES6 Loader](https://github.com/ModuleLoader/es6-module-loader/blob/v0.17.0/docs/loader-extensions.md) and have users import it using `System.import()`
- [Create a SystemJS plugin](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md). 

Using a script tag would require users to enter quite a long complicated url, which changes when an other version is installed. Something like:
``` html
<script src="jspm_packages/github/peteruithoven/systemjs-debugger@0.0.1.js" charset="utf-8"></script>
```
Is there any way around this complicated url? 

Using `System.import()` requires it to be imported the user's main class, which is not very convenient. That would look something like: 
``` javascript
System.import('sytemjs-debugger').then(function() {
  System.import('app.js').then(function() {
    logImports(); // log imports after import
  });
});
```

Creating a SystemJS plugin seems the cleanest solution, but it I'm afraid this requires extra configuration, if it's even possible. This might require enabling multiple loader plugins, which I'm not sure is possible?

**Comment by peteruithoven** [comment]
I've opted for the second option and released it:
https://github.com/peteruithoven/systemjs-debugger
