### ISSUE TITLE
`js` default extension for packages does not work on IE 8

### ISSUE THREAD

**Issue by cadorn** [systemjs/systemjs#680]
````
{"packages": {
    "resources/layer": {
      "format": "cjs",
      "defaultExtension": "js"
}}}
````

Will make a request to server without appending `.js`. Works on google chrome.

**Comment by guybedford** [comment]
Are you definitely running the latest patch of SystemJS? The test at https://github.com/systemjs/systemjs/blob/master/test/test.js#L874 is definitely working fine in IE8 for me. Any help replicating appreciated.

**Comment by guybedford** [comment]
Please do let me know if you have any further information here still.

**Comment by cadorn** [comment]
Will do; just have to get back to this.

**Comment by guybedford** [comment]
This may have been fixed in https://github.com/systemjs/systemjs/commit/f4a18506fc57c5ec3fd9042db1eaaf9eb22a9331. Try the latest release and let me know if that helps.

**Comment by guybedford** [comment]
Closing for now, but please let me know if you're still seeing this.
