### ISSUE TITLE
Add option for seperate map file

### ISSUE THREAD

**Issue by dpsthree** [systemjs/systemjs#681]
I have several lengthy, unaltered "map" objects in a few projects. I tend to avoid checking in auto-generated code/configuration so I strip config.js of anything that is non-essential. For example I leave the transpiler options and delete the map section, this creates a much smaller and easier to understand config.js. It would be nice if there were an option to generate the map content in a different file to prevent source control from seeing this constant change. It may be possible to have systemjs look for this file automatically when calling System.config from config.js. Alternatively, if someone chooses to use this option it may be acceptable to add an additional script tag to fetch it.

**Comment by guybedford** [comment]
If you want to skip version control of `config.js` then it may be better to create a separate config.js file that you do put in version control with your own changes, and then include it separately in the browser and for builds. Note that having `config.js` in version control is encouraged though as it is the version lock.
