### ISSUE TITLE
System.get(...).retrieveGlobal is not a function

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#683]
I'm getting this error in this line which appears in a few places in my **bundled** code:

     return System.get("@@global-helpers").retrieveGlobal(__module.id, false);

There is also a `prepareGlobal` that gets called, and upon inspection the `@@global-helpers` module indeed has it, but not the former.

This code was bundled with a previous (0.16) version of SystemJS successfully.

**Comment by Mosho1** [comment]
Turns out I Didn't update my systemjs-builder module

**Comment by kresli** [comment]
I get same error here. Im using systemjs 0.18 and system-builder 0.13.1. @Mosho1 how did you resolve it?
