### ISSUE TITLE
Can't override System.config paths

### ISSUE THREAD

**Issue by topheman** [systemjs/systemjs#684]
Hie,

I'm trying to override System.config paths in order to inject stubs for unit tests.

I first tried adding a second block specifying my modules on which my unit tests are based like that:

```html
<script src="jspm_packages/system.js"></script>
<script src="jspm.config.js"></script>
<!-- config to override geolocation service with proper stub -->
<script>
System.config({
  "paths":{
    "app/services/geolocation/geolocation.js":"test/unit/stubs/services/geolocation/geolocation.js"
  }
});
</script>
````

Then, I tried to inject it directly in `jspm.config.js` file. The paths part would look like that:

```json
"paths": {
  "app/services/geolocation/geolocation.js": "test/unit/stubs/services/geolocation/geolocation.js",
  "github:*": "jspm_packages/github/*",
  "npm:*": "jspm_packages/npm/*"
}
````

I tried everything: declaring after, before, changing the paths ...

I can see ithe path I declared in the console when I access to `System.paths` but it doesn't have any effects.

Am I doing something wrong ? Is this not the way to override module for such a use case ?

Tophe

Note:

In my `jspm.config.js`, I have `baseUrl = './'`

I require my module that way : `import geoip from '../../services/geolocation/geolocation.js';`

I also tried to import it that way : `import geoip from '/app/services/geolocation/geolocation.js';` it didn't change anything, it was still the original, not the stub.

Made with jspm `0.16.0-beta.3`

**Comment by guybedford** [comment]
The way to debug this is to check if the `System.paths` entry contains the correct normalized path mapping you expect. Perhaps log that and see what it is?

**Comment by topheman** [comment]
@guybedford It does contain the correct path.

I pushed my code in a branch on https://github.com/topheman/vanilla-es6-jspm/tree/feature/override-systemjs-paths

```shell
$ git clone https://github.com/topheman/vanilla-es6-jspm.git
$ cd vanilla-es6-jspm
$ git checkout feature/override-systemjs-paths
$ npm install
$ gulp serve:test
```

I'm injecting the override of System.paths via browserSync, you'll see confirmation via a console log, before all the calls to the assets (if you view source the page, you can see the `System.config()` call).

Still, when you click on the red button, it's making an xhr (the `app/services/geolocation/geolocation.js` file is still loaded, not the one specified in the config override, which sould be : `test/unit/stubs/services/geolocation/geolocation.js`)

**Comment by topheman** [comment]
@guybedford I loaded `system.src.js` to debug, which led me to understand my mistake :

`paths` aren't meant to be used with relative paths like when I was doing `import geoip from '../../services/geolocation/geolocation.js';`

Now I have the following paths configuration in my `jspm.config.js` :

```json
  "paths": {
    "services/*": "src/app/services/*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  }
```

And I require the service like this : `import geoip from 'services/geolocation/geolocation.js';`

Then, when I'm in unit-test mode (to retrieve the stub version of this service), I inject the following config which now correctly overrides :

```json
{
  "paths": {
    "services/geolocation/geolocation.js": "test/unit/stubs/services/geolocation/geolocation.js"
  }
}
```

Can you confirm this is the right way to do it ?

You can check the code out (same repo / same branch as I mentionned above).

**Comment by guybedford** [comment]
That looks great to me - yes you can't apply paths to URLs, they must apply in plain name space (the part before URL normalization), which you've converted to exactly right. You could actually use aliases to achieve this:

```javascript
System.config({
  meta: {
    'app/services/geolocation/geolocation.js': {
      'alias': 'test/unit/stubs/services/geolocation/geolocation.js'
    }
  }
});
```

Note that this is an undocumented feature and is still being considered if it will remain in this form.

**Comment by topheman** [comment]
Thanks @guybedford 

I managed to to share a `jspm.override.json` file between the `gulp serve:test` task and my `karma.conf.js` so my tests now pass perfect and DO use the overridden files, just by using a little config ... :+1: 

Tophe
