### ISSUE TITLE
Dependencies loads globally

### ISSUE THREAD

**Issue by samouss** [systemjs/systemjs#685]
Hello,

I have some trouble with SystemJS for loads external dependencies.

I installed Moment.js through JSPM via the registry. When I load it in the browser via ES6 `import`, it'll be loaded globally.

But when I install it through NPM, it'll only load in my module scope and not as global.

I try to override configuration at installation but it doesn't change anything.

Any ideas ?

Thanks.

**Comment by peteruithoven** [comment]
Difference might be caused by these overrides: https://github.com/jspm/registry/tree/master/package-overrides/github/moment

**Comment by samouss** [comment]
These overrides are for these versions `2.10.3`, `2.4.0` and `2.8.0`, but I use the latest version `2.10.6`.

So, I don't think that comes from here.

**Comment by samouss** [comment]
I try again the installation override from github and it works.

Thanks for your time.
