### ISSUE TITLE
Documenting import

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#686]
https://github.com/systemjs/systemjs provides two examples of importing modules:

* Browser:
```` System.import('main.js'); ````

* Nodejs:
```` System.import('./app').then(function(m) {
  console.log(m);
}); ````

https://github.com/systemjs/systemjs/blob/master/docs/overview.md offers other examples:

* Browser:
````System.import('./local-module.js');  ````

* ES6:
```` System.import('./app/es6-file.js').then(function(m) {
  console.log(new m.q().es6); // yay
}); ````

In both browser examples, the module seems to be imported anonymously. This provides no handle for the module. The Nodejs and ES6 examples both use promises which provide handles to the modules.

It might be helpful to add a browser example like this:
````
Promise.all([
  System.import('jquery')
  , System.import('bootstrap')
]).then(function(modules){
  (function($, bs){
    // ...module code goes here...
  }).apply(null, modules);
});
````

Or document some better technique to provide module aliases in the browser.

**Comment by WorldMaker** [comment]
One partial reason for the terseness of the browser examples is that outside of the "top-level" import to kick off the show in your index page what you really want is your module format to the leg work on imports, whether that is AMD, CommonJS, or (IMHO the nicest, modern option) ES6.

```js
// ** AMD **
define(['jquery', 'bootstrap'], function ($, bs) {
  // Your module
});

// ** ES6 **
import jquery from 'jquery';
import bootstrap from 'bootstrap';

// Your module
```

I use [JSPM](http://jspm.io/) with SystemJS and for the most part all of my uses of `System` directly are in the auto-generated JSPM config file and simple bootstrapping head matter that JSPM provides:

```html
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('lib/main');
  </script>
```

Which may seem strange, but really that is just about all I need as once in `lib/main` or whatever I call my entry point I stick to the module system from there on out. (The remaining interactions with `System` directly are in loader plugins and one case where I'm doing "dynamic" imports for reasons.)

Hope that clarifies things a bit.

**Comment by smcmurray** [comment]
@WorldMaker , your response reads to me as "You don't want to use Systemjs for importing."

Your preferred solution is to use ES6 imports. Unfortunately, ES6 imports cannot import on demand and cannot do dynamic importing. For instance, I have an app with 100s of modules. I don't want to load them all up-front just in case I ever need them. I usually only need a handful of them, but I don't know ahead of time which ones I will need.

AMD defines mix importing and exporting. I want Systemjs to do the importing and dependency management. I prefer promises over callbacks.

CJS requires are synchronous. I prefer Systemjs async loading with promises.

So, for the moment (I'm still just getting my feet wet with Systemjs) I have been using CJS exports like so:
```` module.exports = Promise.all([System.import('a'), System,import('b')]).then(function(modules){...}); ````

I'm hopeful that something like PR #695 will simplify that slightly to:
```` module.exports = System.import(['a', 'b']).then(function(modules){...}); ````

So, the bottom line is that Systemjs appeals to me as a module loader. So of course I want to use it  instead of AMD or CJS to load my modules. I don't want to use CJS requires and AMD requires and Systemjs imports. I want to use just one of those. I choose Systemjs imports.

**Comment by WorldMaker** [comment]
ES6 modules (and their import/export statements) are more like AMD defines than they appear. It is a much nicer alternative than CommonJS-style exports. The ES6 loader (or SystemJS in its role as polyfill) loads things asynchronously and on demand for you (akin to AMD) without you having to manually handle the promises, in most cases. The export syntax is as expressive as CJS (versus AMD) and IMO easier to use than either CJS or AMD.

Of course, I don't know the specifics of your dynamic importing needs, but I would encourage you to maybe explore using more ES6-style modules. They are the future after all, and the great thing about SystemJS here is that the future is today.

**Comment by smcmurray** [comment]
I like the ES6 syntax for import/export. I'm still not clear on how to polyfill that without transpiling.

I also need to be able to do things like:

````
some_element.addEventHandler('click', function(){
  import api from some_element.getAttribute('data-api');
  api(some_element.getAttribute('data-uuid'))
  .then(function(controller){
    // do something with the controller
  });
});
````

There are some obvious problems with the import statement above, inluding:
* It is not invoked as a top-level statement
* I want `api` to be function-scoped
* the module source is determined dynamically

I need to learn how to do the above in a way that makes sense.

Also, I don't understand how "The ES6 loader (or SystemJS in its role as polyfill) loads things asynchronously and on demand for you (akin to AMD) without you having to manually handle the promises." In the example above, import does not appear to be async at all. System.import clearly is async.

**Comment by WorldMaker** [comment]
SystemJS supports transpilers and detects if a module needs transpilation, loading the transpiler and performing the transpilation only when/if needed.

Import doesn't appear to be async, but like I said it is intended to always be async in the same way that AMD modules are async, which is part of why they have the restriction that imports need to be top level in that module. When an AMD is loaded, the listed dependencies in the `define([...deps], fn)` are asynchronously (and often/hopefully in parallel) loaded before the callback function that makes up the "body" of the define is ever ran. This is the same for ES6 modules: imports are loaded asynchronously (and often/hopefully in parallel) before the module's code is ever actually ran. Essentially there is a hidden, but implied `.then` between the module imports and the module body. (That's a bit of an over-simplification, but maybe descriptive enough to help.) So all of these are roughly the same effective loading pattern:

```js
// Your example above:
module.exports = Promise.all([System.import('a'), System,import('b')]).then(function(modules){
   var a = modules[0];
   var b = modules[1];
   /* Module Body */
}); 

// AMD
define(['a', 'b'], function (a, b) {
  /* Module Body */
});

// ES2015 (ES6)
import a from 'a';
import b from 'b';

/* Module Body */
```

The ES2015 is deceptively simple compared to the other two, but gets you to roughly the same place. 

Your event handler example does seem like a valid case to use `System.import()`. As written your example seems to me to be very strongly coupled and in an application under my own control I might try to refactor it to need less of a closure on such a large amount of state information, but that's my two sense and everyone has different preferences. I'm also not sure I'd do a dynamic load in something as possibly common as a click handler, but again that's probably as much a matter of personal taste. Also, I've come to prefer the behavior of bundlers like the SystemJS bundler when it can most easily do a static analysis of every possible import from a given starting point, so I tend to factor out dynamic imports more often than not these days.

Anyway, all of this is just my two cents on the matter. Hopefully some of it may help as you try to learn and come up with an approach that fits yourself and your applications.

**Comment by probins** [comment]
`import` is not anonymous; the module is added to the registry. This used to use the name, but is now the normalised url; you can find it in `System._loader.modules`, and access it with `System.get()`, though this is not normally needed in user code. `System.import()` returns a thenable which you can use for dynamic loading or whatever you like; https://github.com/ModuleLoader/es6-module-loader/blob/master/demo/index.html provides an example.

The loader details are all subject to change until the spec is finalised, but the basic principles will remain the same.

**Comment by probins** [comment]
I use `System.import` a lot for the sort of incremental loading you're talking about. The initial bootstrap is small, and the user is presented with a lot of buttons that say 'I want to do x', and x is only loaded when the user clicks on that button. If it helps, my standard click listener looks like:
```
var listener = function() {
  // component name is button id minus 'button'
  var me = this.getAttribute('id').replace('button', '');
  System.import('components/' + me);
  // hide button and remove listener
  this.style.display = 'none';
  this.removeEventListener('click', listener);
};
```

**Comment by smcmurray** [comment]
@probins , does that listener actually work?

Shouldn't SystemJS try to load ('components/'+me) at the same time it loads the listener definition and fail?

**Comment by probins** [comment]
no, `System` is a global object like any other, and its properties/methods, like `import()`, behave like any other, so is executed when the listener is executed. (Of course, I missed out the bit that says `button.addEventListener('click', listener)`). Don't confuse this with the `import` statement. Broadly speaking, `import` establishes the dependencies; it goes in modules, and each dependency is loaded/executed by the module loader the first time the loader encounters it, so if several modules import 'a', 'a' is only loaded/executed the first time. `System.import` goes in script, and is executed like other functions, calling the module loader to load/execute the module if it's not already loaded. You can have it on its own for a bootstrap
```
<script>System.import('myBootstrap');</script>
```
(in practice, you'll probably need some config in there as well to tell it where to find the module), or in a listener or other delayed function for dynamic loading, as in my example.
