### ISSUE TITLE
domReady

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#687]
In the browser, can imported modules load and run before the DOM is set?
If so, is there a documented technique to prevent this? Something like domReady?

**Comment by guybedford** [comment]
A domready plugin for SystemJS could certainly be made to handle this use case. I don't know of any plugins that do this yet. If you're interested in making one or need any guidance just let me know.

**Comment by smcmurray** [comment]
Here's a stab at it. Completely untested.

https://github.com/smcmurray/systemjs-domReady

**Comment by guybedford** [comment]
That's the right idea, but would need to be implemented into the plugin interface via something like:

```javascript
exports.instantiate = function(load) {
  return promiseForDomReady();
};
```

**Comment by smcmurray** [comment]
@guybedford , My idea was that it doesn't need to be a plugin. Just importing it provides a promise that the DOM is ready.

Is there some advantage to being a plugin?

**Comment by guybedford** [comment]
@smcmurray yes I agree it probably does make the most sense just to import your domready function and add a callback to it within your module:

```javascript
import domready from 'domready';
domready(function() {
  // ... etc ...
});
```

A plugin would allow the ability to abstract the above to work without a wrapper being necessary that is all.

**Comment by guybedford** [comment]
Let me know if you have any further questions here at all.
