### ISSUE TITLE
How do I request ES6 transpile for my Loader Plugin?

### ISSUE THREAD

**Issue by WorldMaker** [systemjs/systemjs#690]
I've written a couple of plugins and think I've now debugged their translation output. The plugins are written in ES6, so I assumed that if SystemJS was transpiling the plugins it would automatically transpile the translated output of the loader as well. That doesn't seem to be the case as the browser seems to be complaining about parsing issue with the ES6 output of my loader plugin. Is there something I missed in my plugin to let SystemJS know that the translation will be in ES6?

The plugins I'm working on are: [system-jade-virtualdom](http://github.com/WorldMaker/system-jade-virtualdom) and [turtle-factory](http://github.com/WorldMaker/turtle-factory).

Thanks, Max

**Comment by guybedford** [comment]
@WorldMaker the plugin transpile method can return any module format, just like loading a normal module. Note that if the output is ES6, just like a normal module it needs to have module syntax present to be detected. To enforce detection as ES6 the plugin can impose the module format via `load.metadata.format = 'esm'`, but the most flexible is to allow any module format to be loaded. Just let me know if you're having any more issues with this.

**Comment by WorldMaker** [comment]
Interesting. The example I was looking at last night should have detected: the translated output was essentially just a single ES6 import statement followed by an export statement. I might try the metadata suggestion late tonight if I have time. Is there a format detection debug indicator I should look for?

**Comment by guybedford** [comment]
Perhaps try using https://github.com/peteruithoven/systemjs-debugger. Let me know if you're still having issues here at all.

**Comment by WorldMaker** [comment]
:ok_hand: Well, it was a legitimate syntax error and I'm guessing the stacktrace was from Babel. Whoops.

Now I just need to figure out why my call to `System.normalize(...)` is not doing what I would expect.
