### ISSUE TITLE
including a global module sets window.module to undefined

### ISSUE THREAD

**Issue by piebe** [systemjs/systemjs#691]
When a module of the format global is included window.module (and window.exports) is set to undefined.

For example angular-mocks defines window.module. This works fine as long as no global modules are included. As soon as I include a module with metadata exports set, my tests stop running since window.module is undefined.

The problem can be found in global.js:

```
       // disable module detection
        var define = __global.define;
        var cRequire = __global.require;
        
        __global.define = undefined;
        __global.module = undefined;
        __global.exports = undefined;

        __exec.call(loader, load);

        __global.require = cRequire;
        __global.define = define;
```

As you can see module is set to undefined but never restored. Changing this in the code below fixes  my problem.

```
  // disable module detection
        var define = __global.define;
        var cRequire = __global.require;
        var cModule = __global.module;
        
        __global.define = undefined;
        __global.module = undefined;
        __global.exports = undefined;

        __exec.call(loader, load);

        __global.require = cRequire;
        __global.define = define;
        __global.module = __global.module || cModule;
```

However, since I do not really understand the code, I have no idea if this is the proper solution. Why are these globals made undefined in the first place? Is it intentionally that they are not restored? Why is require restored but not first made undefined?

**Comment by guybedford** [comment]
These are set to undefined because typical module format detections will check existence of these so we remove them for this reason. We can certainly look at removing the nulling out of `module` though as typically CommonJS detection doesn't rely on this on its own.

**Comment by guybedford** [comment]
Actually a common check is:

```javascript
if (typeof module != 'undefined' && module.exports)
```

So that's why we need this.

You can use the `globals` configuration in SystemJS to make sure `module` is correctly defined though.

**Comment by guybedford** [comment]
I've actually added a fix to allow this in https://github.com/systemjs/systemjs/commit/851c2f6d085cc09f2435fc3c890e7a2f8f6266eb.
