### ISSUE TITLE
Docs: Clarify meta paths

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#692]
I'd like to clarify the documentation on the `meta` paths in inside of `packages` configuration. As usual I need some help understanding them so that I can improve the docs. 
Currently the [Packages documentation](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) only mentions: 
> Package-scoped meta configuration with wildcard support

As explained to me by Guy meta paths are subpaths within packages: https://github.com/systemjs/systemjs/issues/666#issuecomment-129839081

It also doesn't seem to allow for relative paths, which might be weird to use inside the config, but I was used to using them in my modules, so this is something we might want to inform users about.

**Comment by guybedford** [comment]
Sure, thanks. Yes the meta paths are basically assumed relative by default. So `sub/path` in the package meta config means `path/to/package/sub/path`.

**Comment by peteruithoven** [comment]
Alright, and could you explain shortly why relative paths don't work? So why `./sub/path` doesn't mean `path/to/package/sub/path`.

**Comment by guybedford** [comment]
We could allow `./sub/path` to mean the same thing as `sub/path`. That's a flexiblity that may be useful.

**Comment by peteruithoven** [comment]
Yeah maybe? I'm afraid people might expect that, because that's how there used to writing relative paths.

**Comment by peteruithoven** [comment]
Also relevant: https://github.com/systemjs/systemjs/issues/662#issuecomment-130269204

**Comment by guybedford** [comment]
Sure, I've added this flexibility in https://github.com/systemjs/systemjs/commit/17fc81fdbb6bb71ef94633f81370f5e06c5d756b. Will prefer to keep it undocumented though.

**Comment by peteruithoven** [comment]
https://github.com/systemjs/systemjs/pull/697 just describes that it's a subpath, it doesn't mention the smaller `./` confusion.
