### ISSUE TITLE
CORS doesn't work in IE9

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#693]
I upgraded to 0.18.9 and my app stopped working in IE9. The culprit seems to be this line:

    xhr.setRequestHeader('Accept', 'application/x-es-module */*');

I'm fetching some scripts from cdnjs. `setRequestHeader` isn't available in `XDomainRequest`. CORS in IE9 is only available through `XDomainRequest`.

Seems like applying the header if we're not using `XDomainRequest` is the way to go here.

**Comment by guybedford** [comment]
Thanks I've added https://github.com/ModuleLoader/es6-module-loader/commit/ae60fffdd835082cea0efc4eabc0554eeb18ea63. Let me know if that works for you here.

**Comment by Mosho1** [comment]
Thanks for the quick fix! This seems to work fine, but I may be crazy, but in my log on IE9 `xhr.setRequestHeader` does exist (it simply doesn't work) and if I log something inside the if block it still logs! But taking the function call out of the block breaks it again. I really don't know what to say to that.

**Comment by guybedford** [comment]
Sure, thanks for letting me know. Perhaps it's just working for the non CORS requests. If you have any further issues do post back here.
