### ISSUE TITLE
'core-js' out of date warning is wrong

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#696]
I'm seeing this message with jspm:

    warn core-js@1.0.1 is out of date. Use jspm dl-loader to update.

1.0.1 is the latest version. If I try `jspm dl-loader` it downgrades `core-js`.

**Comment by guybedford** [comment]
Thanks, I've clarified this in https://github.com/jspm/jspm-cli/commit/8d63b7f2d710fb51b44086b6bb555ec818783212.
