### ISSUE TITLE
SystemJS-related job posting?

### ISSUE THREAD

**Issue by mattfysh** [systemjs/systemjs#705]
@guybedford would this be an okay place to post a job that involves contributions back to the systemjs project? If nom, any suggestions on where I might go to post such a role would be greatly appreciated :)

**Comment by guybedford** [comment]
@mattfysh feel free to post the details here if you like. The project isn't expanding too many features at the moment, but I'd be happy to consider the suitability. I am also available for consulting work around the project and try to fund development that way - you're welcome to get in touch with me via email as well if you'd like to discuss further too.
