### ISSUE TITLE
ES6 format not detected when only exporting

### ISSUE THREAD

**Issue by timbur** [systemjs/systemjs#706]
For example, when creating `components/index.js`:

```js
export Branches from './Branches.js';
export PackageSourceName from './PackageSourceName.js';
export PackageUserName from './PackageUserName.js';
export PackageRepoBranchName from './PackageRepoBranchName.js';
export Limbs, { Limb } from './Limbs.js';
export Tabs from './Tabs.js';
export Tab from './Tab.js';
export TabContents from './TabContents.js';
export TextEditor from './TextEditor.js';
```

The format must be specified for this to work, but shouldn't it be detected as ES6?

**Comment by guybedford** [comment]
Thanks yes this is a bug for these cases in the regular expression.

**Comment by guybedford** [comment]
Actually @timbur this is invalid module syntax, as this proposal for default exports isn't actually in the ES specification.

**Comment by timbur** [comment]
I really hate the specs sometimes lol.
