### ISSUE TITLE
Unexpected token < in react js file

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#708]
I followed this [Aurelia-React](https://github.com/cscleison/AureliaReactPOC) example, and works only if I don't use JSX syntax in it. I get the **unexpected token <** error otherwise. I think the system or babel is not using the JSX Transformer to compile the js file. Should I include any setting in the config.js to make JSX transform working?

![jsx](https://cloud.githubusercontent.com/assets/12233474/9297251/05468b46-4462-11e5-9726-039e86289613.png)

**Comment by guybedford** [comment]
@varghesep make sure you are running the latest jspm beta and using Babel as your transpiler for jsx to work.

**Comment by varghesep** [comment]
I was not able to fix this problem with the newest release of jspm. I also updated all the jspm packages with a **jspm install** command.

If you look at the stack trace, you will notice that that the JSXTransformer is not participating in the process to compile the JSX syntax.

This is from the config.js file.

``` javascript
System.config({
  "baseURL": "/",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "es7.decorators",
      "es7.classProperties"
    ]
  },
  "paths": {
    "*": "*.js",
    "github:*": "jspm_packages/github/*.js",
    "npm:*": "jspm_packages/npm/*.js"
  }
});
```

**Comment by majhork** [comment]
You can add `"blacklist": [],` in `"babelOptions"` to fix this.

**Comment by guybedford** [comment]
Yes adding the empty blacklist or upgrading the to 0.16 beta is the way to go (the above is not the beta release, you need to run `npm install jspm@beta` to get the beta).

**Comment by varghesep** [comment]
I have got this working finally. I had to install the **jspm@beta**. I **did not** have to add to the blacklist to the babeloptions.

You provide awesome support!
