### ISSUE TITLE
Question | Create module during runtime for in browser source code

### ISSUE THREAD

**Issue by omerts** [systemjs/systemjs#709]
Hello,

Is it possible to create a module from source code? Kind of a systemjs eval?

**Comment by matthewbauer** [comment]
Something like this might be what you're looking for:

```
System.set('custom-module', System.newModule({ prop: 'value' }));
```

This will let you "import" that module later on.

**Comment by omerts** [comment]
I would like to create a module from source code, something like: 

```javascript
System.funcName(`
import React from "react";
export default class test extends React.Component {
render()...
}`); 
```

**Comment by guybedford** [comment]
You can use `System.define(name, source)` for this, although the use case is not advised currently.

**Comment by omerts** [comment]
Great thank you.

**Comment by abhishiv** [comment]
@guybedford can please elaborate use why it's not advised? And if there are other alternatives to evaluate src code?

I tested it out and it works perfectly - including translation from es6 via babel; but it's not clear to me how to handle relative imports while using `System.define`.

**Comment by guybedford** [comment]
It's not advised mainly because it hasn't been tested too thoroughly. In principle there is nothing at all wrong with it though.

The name passed into `System.define` would need to be the relative parent I guess? Make sure to use a name that is a normalized URL - `System.define(System.normalizeSync('test.js'), '...')` for example.

**Comment by abhishiv** [comment]
Yeah that's what I thought but it doesn't seem to work because it requests the import over networks. I'm basically trying to do something like this:

````
System.define(
  System.normalizeSync('test.js'), 
'export default { a: 3}');
System.define(
  System.normalizeSync('test2.js'), 
  'import a from "./test.js"; export default { a: 3}');
````

Or the better way to do this would be to look into plugins instead of System.define?

**Comment by guybedford** [comment]
@abhishiv imports loading over the network is exactly the way the loader works. Are you saying you want to use an import that is already present in the registry? If so it is just a matter of ensuring that `System.normalizeSync('test.js', System.normalizeSync('test2.js'))` is already present in the loader registry (this can be inspected at `Object.keys(System._loader.modules)` if you're interested).
