### ISSUE TITLE
bug(duplicate dependencies): Incorrect setter is being called for duplicate dependencies.

### ISSUE THREAD

**Issue by ttowncompiled** [systemjs/systemjs#712]
I have this module,
```JavaScript
System.register(['./reflector', './reflector', './reflection_capabilities'], function(exports_1) {
    var reflector_1, reflection_capabilities_1;
    var reflector;
    return {
        setters:[
            function (_reflector_1) {
                reflector_1 = _reflector_1;
            },
            function (_reflector_2) {
                exports_1('Reflector', _reflector_2['Reflector']);
                exports_1('ReflectionInfo', _reflector_2['ReflectionInfo']);
            },
            function (_reflection_capabilities_1) {
                reflection_capabilities_1 = _reflection_capabilities_1;
            }],
        execute: function() {
            exports_1("reflector", reflector = new reflector_1.Reflector(new reflection_capabilities_1.ReflectionCapabilities()));
        }
    }
});
//# sourceMappingURL=reflection.js.map
```
It contains a duplicate dependency because we are importing ```Reflector``` and also exporting ```Reflector``` in this module.

While I was debugging my code, I took a look at what modules were being pushed through the second setter. The second setter gets called twice: the first time, the ```reflector``` module gets pushed through, but the second time, the ```reflection_capabilities``` module is pushed through.

Because of this, my module can adequately export ```reflector```, but it cannot transitively export ```Reflector``` or ```ReflectionInfo```.

I am using systemjs@0.18.10 and the typescript compiler from 1.5.3. I noticed that in systemjs@0.18.10, you group dependencies together. I can only assume that the bug here is caused because the weak references to this module contained by ```reflector``` and ```reflection_capabilities``` are determining the setter index based on location in the grouped dependency array and not the original dependency array. That's just my initial thoughts though.

**Comment by vladima** [comment]
I guess you got this file as an output for TypeScript compiler. Can you give a try to the TS nightly build, it is 'typescript@next' on npm, this issue should already be fixed.

**Comment by ttowncompiled** [comment]
Thanks for the advice. The nightly doesn't claim duplicate dependencies so it will avoid this issue. I just wanted to file the bug since it should be fixed rather than avoided.

**Comment by ttowncompiled** [comment]
Sorry to bring this back up, but could you please provide some context as to why this was closed? I have a hack in angular that I would really like to remove, but its pending a fix for this bug.

**Comment by Tilley1234** [comment]
Buddy I didn't close anything my phone crashe and went in safe mode I can't get to my computer till Tommie

**Comment by alexeagle** [comment]
@guybedford Why was this closed?

**Comment by guybedford** [comment]
@alexeagle the latest versions of SystemJS will handle the duplicates output by TypeScript fine.
