### ISSUE TITLE
Warnings about deprecated APIs

### ISSUE THREAD

**Issue by topheman** [systemjs/systemjs#714]
On systemjs@0.18.11, with Chrome 44 / Mac OS X, I've got the following warnings :

```
'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.
```

They come from https://github.com/systemjs/systemjs/blob/0.18.11/dist/system.src.js#L2077

They were not there with previous versions (I just upgraded from `jspm@0.16.0-beta.3` to v0.16.0 and redid the `jspm install` - it worked fine by the way)

**Comment by guybedford** [comment]
If it comes from that line, it sounds like you have code that is for some reason doing `module.exports = window`? If so, the deprecation messages are completely valid.

**Comment by topheman** [comment]
@guybedford It does makes sense, so I went through my code (which is very simple since it's more of a boilerplate for jspm), I didn't find any modules exporting `window` or exporting vars out of their scope. I also made a grep on the dependencies in `jspm_packages` on `window` they don't seem like they do.

I found out something weird though ... The message is not there any more when I don't extend from export class.

Here is a minimal case:

The code bellow throws the warnings

```js
"use strict";
export class SuperMain {
  constructor(){
    console.log('SuperMain');
  }
}
class Main extends SuperMain {
  constructor(){
    super();
    console.log('Main');
  }
}
new Main();
```

The code bellow doesn't throw the warnings (it's missing `export` on the parent class) - it also works if you dont extend at all.

```js
"use strict";
class SuperMain {
  constructor(){
    console.log('SuperMain');
  }
}
class Main extends SuperMain {
  constructor(){
    super();
    console.log('Main');
  }
}
new Main();
```

I don't know where it comes from ... maybe it's not related, but it's worth to be reported.

In my case, it seems like it's because I extend from exported classes that those warnings come off.

Tophe

**Comment by lookfirst** [comment]
@guybedford 

jspm 16.0
jspm dl-loader --latest

I've done a bundle build so that all my code is in a single file. I then did a find in the file and the ONLY reference in the file to webkitStorageInfo is from system.js.

There is also nothing found for `module.exports = window`

screenshot: http://take.ms/947DA

**Comment by lookfirst** [comment]
Another screenshot of the warning in Chrome: http://take.ms/H1OLx

**Comment by guybedford** [comment]
@lookfirst any chance you can provide a test case here that contains dependencies that would trigger this? It sounds like it only happens with certain dependencies in the project.

**Comment by Mosho1** [comment]
I'm also seeing this, will investigate tomorrow if I have time.

**Comment by jobedom** [comment]
I don't know if this info is useful, but maybe is one more clue. When I reference `Promise` in the code I get those two warnings. Miminal example reproducing the problem:

``` javascript
var a = Promise;

export {}
```

I guess is not a problem with `Promise` itself but in one of all those libs which are pulled if you use it.

**Comment by guybedford** [comment]
@jobedom the above case works fine for me, which transpiler are you using in your app?

**Comment by jobedom** [comment]
@guybedford I'm using Babel. 

I'll create a minimal repo with the smallest example I can get to replicate the problem. Give me a minute.

**Comment by jobedom** [comment]
Here: https://github.com/jobedom/test-jspm
Tested in Chrome 44.0.2403.157 / Windows 7 (32 bits)

**Comment by guybedford** [comment]
@jobedom thanks for the test case. Right, this is exactly due to https://github.com/zloirock/core-js/blob/master/modules/%24.global.js, which does effectively a `module.exports = window`.

I've added https://github.com/systemjs/systemjs/commit/aecb940ac3859c4c6c20523139500ddf3b137dab to work around this, which allows this config:

```javascript
System.config({
  meta: {
    'core-js/library/modules/$.global': {
      esmExports: false
    }
  }
});
```

to then avoid the warning.

We'll be able to add that to an override in jspm 0.17 when the package.json spec includes metadata, but for now you'd need to add that manually as soon as the next SystemJS release is out.

**Comment by jobedom** [comment]
@guybedford Great! I understand I just have to wait for 0.18.17 and add that meta config in my `config.js`, is that right?

Thanks for your time and effort.

**Comment by guybedford** [comment]
:+1:

**Comment by lookfirst** [comment]
:+1: YES!

**Comment by guybedford** [comment]
Published in 0.18.17.

**Comment by lookfirst** [comment]
So, is the override still required or does this just work now?

**Comment by jobedom** [comment]
> We'll be able to add that to an override in jspm 0.17 when the package.json spec 
> includes metadata, but for now you'd need to add that manually as soon as the 
> next SystemJS release is out.

**Comment by lookfirst** [comment]
@guybedford This still happens for me. Please re-open.

jspm 0.16.2
systemjs@0.18.17

I've installed the override mentioned above.

**Comment by guybedford** [comment]
@lookfirst in the current version of core-js the configuration is now:

```javascript
System.config({
  meta: {
    'core-js/modules/$.global': {
      esmExports: false
    }
  }
});
```

**Comment by lookfirst** [comment]
@guybedford thanks! that fixed it.

**Comment by lookfirst** [comment]
@guybedford I just noticed that I'm seeing this in my `build.buildStatic` build now. It doesn't happen when  I'm just running unbundled.

**Comment by laurentgoudet** [comment]
FYI it looks like `angular2@2.0.0-alpha.37` triggers the same warnings (System `v0.19.3`). Does that mean the only way forward is to identify & setup overrides for each module causing these warning (and eventually push them upstream or in the registry)?

**Comment by guybedford** [comment]
@laurentgoudet in jspm 0.17 this will apply automatically.

**Comment by guybedford** [comment]
(from the registry - https://github.com/jspm/registry/commit/8e924257b7135c4e18e3d9f5e637dda1c4f29e62)

**Comment by lookfirst** [comment]
@guybedford see my comment above?

**Comment by guybedford** [comment]
@lookfirst thanks created https://github.com/systemjs/builder/issues/338.

**Comment by edba** [comment]
Hey guys,

Just wanted to point out that I had to do the same recently for lodash:

https://github.com/lodash/lodash-amd/blob/master/modern/internal/root.js

**Comment by rquast** [comment]
@edba I got the same problem when I used Aurelia with core-js 1.2.2, even with the meta config. Chrome only.

"Failed to read the 'frame' property from 'Window': Blocked a frame with origin "your.iframe.domain" from accessing a cross-origin frame."

**Comment by kopijunkie** [comment]
@edba @rquast piping in to say that I've also encountered this iframe issue/error alongside the Chrome deprecated API warnings in a situation where a single page app we built at work needed to be embedded in another site. our app's config was on core-js 1.1.4

**Comment by diegograsso** [comment]
@guybedford  Please reopen. I still have the warning and the same error as @rquast "Failed to read the 'frame' property from 'Window': Blocked a frame with origin "your.iframe.domain" from accessing a cross-origin frame."
Using systemjs@0.19.5, core-js@1.2.6 and the param  `esmExports: false` in the config.js.
This happens also using Aurelia in an iframe on Chrome.
My work around for the moment is forcing back core-js@0.9.18.

**Comment by guybedford** [comment]
@diegograsso the release is being tracked in https://github.com/systemjs/systemjs/issues/911.

**Comment by louismarceau** [comment]
@guybedford I still get a webkitIndexedDB is deprecated, and I'm using version 0.19.29.
