### ISSUE TITLE
Scoped CSS plugin

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#715]
I took a swing at creating a plugin for scoped css.
I'm posting a link here just in case anyone is interested.

https://github.com/smcmurray/systemjs-scopedcss

Any constructive criticism is welcome. If anyone has a better way of scoping css until more browsers implement the standard, do tell.

**Comment by guybedford** [comment]
This is an interesting approach, although I'm not sure how well it aligns with the spec work, since it loses the sense of context of the scoped style.

Did you have a look at the work happening with CSS modules? For example https://github.com/geelen/jspm-loader-css-modules.

**Comment by smcmurray** [comment]
@guybedford, Thanks.

This is not a polyfill for the scoped css spec, so it doesn't really align with it. But the :scope replacement works pretty well.

geelen is missing :scope (or at least it isn't documented in the README), but that css identifier is better, and extending stylesheets is an interesting idea.

Thanks for the pointer. I really didn't want to reinvent the wheel.
