### ISSUE TITLE
Cannot use System.constructor()

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#716]
When I run `System.constructor()`, it fail with error "Cannot redefine property: global"

**Comment by guybedford** [comment]
Try using the `new` keyword here.

**Comment by unional** [comment]
Thanks.  That does solve the problem.  You may consider updating the `system-api.md` as it was showing `var clonedSystem = System.constructor()`.

What is the better way to create a clonedSystem that carries over the config of the original one?
Currently I have to do:
````
                clonedSystem.config({
                    baseURL: System.baseURL,
                    defaultJSExtensions: System.defaultJSExtensions,
                    transpiler: System.transpiler,
                    typescriptOptions: System.typescriptOptions,
                    paths: System.paths,
                    packages: System.packages,
                    meta: System.meta,
                    map: System.map
                });
````

Thanks!

**Comment by guybedford** [comment]
Thanks, I've fixed that up in the docs. Usually you'll want to re-run the original configuration code against the cloned system.

**Comment by PhilippMi** [comment]
How can I re-run the original configuration? If you mean the `config.js` then I don't know how that should work since it uses the global `System` object directly and I have no way to replace it with `clonedSystem`.

**Comment by guybedford** [comment]
If you don't have a handle to the original config you'd need to copy the config across manually like:

```javascript
clonedSystem.config({
  paths: oldSystem.paths,
  map: oldSystem.map, ... etc
});
```
