### ISSUE TITLE
babelOptions

### ISSUE THREAD

**Issue by johngeorgewright** [systemjs/systemjs#717]
Hey,

I'm trying to configure babel to turn on `es7.decorators`. Here's what I've changed in my `config.js` file:

```js
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system",
      "es7.decorators"
    ],
    "stage": 1
  }
  // ...
});
```

As you can see I've tried adding it to the `optional` list ([as documented on their site](https://babeljs.io/docs/usage/experimental/)) and decrementing the "stage", but neither seem to be having any effect and my files with decorators are failing to load correctly. Is there anything else I'm missing?

**Comment by mikz** [comment]
@johngeorgewright I have just the 'es7.decorators' with latest SystemJS and JSPM and it works well. 

Maybe create some minimal example to reproduce it?

**Comment by guybedford** [comment]
Perhaps check you're using decorators correctly here? Note they can only apply to class methods.

**Comment by guybedford** [comment]
Let me know if you need further help here at all.

**Comment by johngeorgewright** [comment]
OK, so it does work... but there is a problem when using jsx. It must either be the jsx plugin or babel. Thanks.

**Comment by mikz** [comment]
@johngeorgewright babel supports jsx. https://github.com/mikz/gallery/blob/6b49ba63cd75e9db88b29d2df3efd2603f7d99fc/lib/components/app.js#L7-L24

**Comment by johngeorgewright** [comment]
Yep... but to use JSX with JSPM, I'm under the impression you need to use the `jsx` plugin so that JSPM handles `.jsx` extensions. Somewhere along the line, decorators aren't working in my JSX files and I'm trying to figure out why.

Compiling them with babel seems to work ok, but when they're included with JSPM they don't work :disappointed:

**Comment by mikz** [comment]
@johngeorgewright just name them .js and all will work out automatically. Check the linked gallery project. Just babel, .js and thats it.

**Comment by PinkaminaDianePie** [comment]
same problem here. im trying to move on systemjs, but all my classes with decorators become ```undefined``` in imports

**Comment by johngeorgewright** [comment]
Using a different jsx plugin worked for me in the end: https://github.com/geelen/jspm-loader-jsx

**Comment by PinkaminaDianePie** [comment]
i am using plain es6/7, without jsx

**Comment by PinkaminaDianePie** [comment]
I found the problem: systemjs handles ```export default``` different from babel, so when i imported decorators for my class in applies it wrong and failed with exception, catched by my code but without handling it. When i changed my imorts/exports on ```export {foo}``` all had worked fine.
