### ISSUE TITLE
import of function returns an object

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#718]
System.import is handing me an object, even though I imported a function.

````
System.import('module.js').then(function(foo){
  foo(bar);
})
````

If I examime foo, it is an object, not a function.

module.js is defined as:

````
export default function(){
...
};
````

**Comment by smcmurray** [comment]
````import foo from 'module,js';```` yields a function

**Comment by smcmurray** [comment]
System.import works fine when it imports an AMD module.
It breaks when the module is ES6.

**Comment by guybedford** [comment]
The behaviour here is by design. System.import will provide the namespace object for ES6 modules, this is the same as `import * as foo from 'module.js'`.

**Comment by smcmurray** [comment]
@guybedford, Is that true even for export defaults? I understand that design in general, but ES6 default exports seem more like AMD defines to me and it seems like System.import should treat them that way.

As noted above, ES6 import treats them that way.

**Comment by guybedford** [comment]
Yes we currently treat AMD and CommonJS as exceptions, allowing System.import to return their `default` values directly, but this exception will actually be the one going away. In the actual module loader spec, the return value for a CommonJS module in System.import would be the same namespace object.

**Comment by smcmurray** [comment]
@guybedford ,

If I System.import a module defined as ````export from 'somewhere/else.js';```` I get a function.

That function is the default export of somewhere/else.js

But if I System.import('somewhere/else.js') I get an object.

**Comment by guybedford** [comment]
Not sure I follow here? `export from 'somewhere/else.js';` isn't valid module syntax.
