### ISSUE TITLE
How to use mocks from a mocking framework?

### ISSUE THREAD

**Issue by ScreenDriver** [systemjs/systemjs#725]
Module A has some dependencies (imports) to libraries like bluebird, superagent and lodash. Now I want to write a unit test for that module and all his dependencies should be mocked with [Sinon.JS](http://sinonjs.org). Unfortunately I don't know how to accomplish this. I found out that I can re-map a dependency to fake file on the file system like so:

```js
import { expect } from 'chai';

describe('app', () => {
  let app;

  before((done) => {
    System.map['bluebird'] = 'test/fake.js'; // Fake bluebird implementation
    System.import('../app')
      .then((a) => app = a)
      .then(() => done());
  });
});
```
This works and my module `app` gets the `fake.js` injected. But how can I work with real mocks? I don't want to create new files / modules for every mock.

For the record: I used almost everything from [this](https://github.com/curran/jspm-mocha-example) example and my unit tests are running in the browser.

**Comment by guybedford** [comment]
You can populate modules in the registry for mocking directly via the API with:

```javascript
var bluebird = System.get(System.normalizeSync('bluebird'));
System.set(System.normalizeSync('bluebird'), System.newModule({
  mock: 'export'
});

// to revert back
System.set(System.normalizeSync('bluebird'), bluebird);
```

**Comment by guybedford** [comment]
There is also `System.define` which can set modules based on string sources:

```javascript
System.define(System.normalizeSync('bluebird'), 'string source');
```

**Comment by ScreenDriver** [comment]
Hmmm I think I don't get it. Where is the place where my mock object will be injected? For example:

```js
// Where can I change the 'bluebird' dependency to mySpy?
const mySpy = sinon.spy();

var bluebird = System.get(System.normalizeSync('bluebird'));
System.set(System.normalizeSync('bluebird'), System.newModule({
  mock: 'export'
});
```

**Comment by guybedford** [comment]
For CommonJS modules the default export is where we store the module object:

```javascript
System.set(System.normalizeSync('bluebird'), System.newModule({
  default: mySpy
});
```

**Comment by ScreenDriver** [comment]
:+1: 

Thank you very much! This one and the complete example from [curran/jspm-mocha-example](https://github.com/curran/jspm-mocha-example) or some unit test guide or something in this direction should definitively be added to the docs! :wink:

**Comment by felixkl** [comment]
Just for everyone who is copy/pasting the code: there is a closing parenthesis missing. :wink:

**Comment by peteruithoven** [comment]
@screendriver, could you maybe share a basic example? I'm very curious how you're applying this in unit tests.

**Comment by screendriver** [comment]
Here I mock a module called `person`. Person gets imported like

##### index.js

```javascript
import person from './person';

export foo function() {
  return person();
}
```
And here is my test. I mocked the person module with [Sinon.js](http://sinonjs.org)

##### index-test.js

```javascript
import chai, { expect } from 'chai';
import sinon from 'sinon';
import sinonChai from 'sinon-chai';

chai.use(sinonChai);

describe('index', () => {
  let index;

  before(() => {
    System.set(System.normalizeSync('./person'), System.newModule({
      default: sinon.stub().returns('bar'),
    }));
    return System.import('./index').then(module => index = module);
  });

  after(() => {
    System.delete(System.normalizeSync('./person'));
    System.delete(System.normalizeSync('./index'));
  });

  describe('#foo', () => {
    it('should do something', () => {
      expect(index.foo()).to.equal('bar');
    });
  });
});
```js

**Comment by peteruithoven** [comment]
Nice! Based on your example I also created an example: 
https://github.com/peteruithoven/mocking

**Comment by peteruithoven** [comment]
Would be great if there was a package that would abstract this away. Something that would enable something like this: 
``` javascript 
import chai, { expect } from 'chai';
import sinon from 'sinon';
import sinonChai from 'sinon-chai';
import mocker from 'mocker'; 

chai.use(sinonChai);

describe('index', () => {
  let mocker;
  let mocked;

  before((done) => {
    mocker = new Mocker('./index', {'./person': {default: sinon.stub().returns('bar')})
    mocker.then((module) => {
      mocked = module;
      done(); 
    })
  });

  after(() => {
    mocker.destroy();
  });

  describe('#foo', () => {
    it('should do something', () => {
      expect(index.foo()).to.equal('bar');
    });
  });
});
```
If I need it I'll give it a try.
