### ISSUE TITLE
defaultExtension does not work since 0.18.12

### ISSUE THREAD

**Issue by todoubaba** [systemjs/systemjs#728]
I use angular 2.0.0-alpha.35 bundled angular2.js, the following config works in version 0.18.11:
```
System.config({
    defaultJSExtensions: true,
    packages: {
        'angular2': {defaultExtension: false},
        'http': {defaultExtension: false},
        'rx': {defaultExtension: false}
    }
});
```
But since 0.18.2, systemjs requests rx.js.

**Comment by guybedford** [comment]
@todoubaba yes the opt-out has been refined to only apply to paths within the package but not the package name itself. This is because packages are designed to work as folders not as individual requests.

Perhaps you're meaning to configure `rx` using map config here?

```javascript
System.config({
  map: {
    'rx': 'path/to/rx.js'
  }
});
```

**Comment by todoubaba** [comment]
The rx package are bundled in the angular.js file at line 2951.
```
"format register";
System.register("rx", [], true, function(require, exports, module) {
  var global = System.global,
      __define = global.define;
  global.define = undefined;
  ...
```
Map config does not work. :(

**Comment by guybedford** [comment]
I'm unsure why you need to add the `defaultExtension` false exception here at all then?

**Comment by todoubaba** [comment]
Without defaultExtension false, systemjs will load rx.js instead of the 'rx' module in the bundle.

**Comment by guybedford** [comment]
@todoubaba are you loading the bundle file after the SystemJS config file?

**Comment by todoubaba** [comment]
The code is
```
    <script src="/static/lib/traceur-runtime.js"></script>
    <script src="/static/lib/system.js"></script>
    <script src="/static/lib/angular2.js"></script>
    <script src="/static/lib/http.min.js"></script>
    <script src="/static/core/ts-runtime.js"></script>
    <script src="/static/core/system-config.js"></script>
    <script>
        System.import("/static/plan/vision/show");
    </script>
```

**Comment by guybedford** [comment]
Load angular2 after system-config.js.

**Comment by todoubaba** [comment]
It works now, thank you very much. 
Would you like explain why original code is working in 0.18.11?

**Comment by guybedford** [comment]
Exactly as mentioned above, we stopped applying defaultExtension to the package name itself, and only to paths within the package.

**Comment by todoubaba** [comment]
Thanks again. No need packages config now.
