### ISSUE TITLE
add tsconfig.json support to typescript transpiler

### ISSUE THREAD

**Issue by chrisdostert** [systemjs/systemjs#730]
it would be nice and standardized for the typescript transpiler to make use of the projects [tsconfig.json](http://basarat.gitbooks.io/typescript/content/docs/project/tsconfig.html)

**Comment by guybedford** [comment]
This could potentially be a feature in jspm and has been suggested in https://github.com/jspm/jspm-cli/issues/935, but SystemJS doesn't assume any outside knowledge of files like this.
