### ISSUE TITLE
SystemJS fails to find babel-runtime helper files

### ISSUE THREAD

**Issue by arnaudoff** [systemjs/systemjs#732]
I've been trying to find out what's causing this for a day. Apparently, since I wrote a module that uses ES6 keywords such as class, extends etc., these errors started appearing:

```
GET http://localhost:1337/babel-runtime/helpers/get 404 (Not Found)
Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:1337/babel-runtime/helpers/get
	Error loading http://localhost:1337/babel-runtime/helpers/get as "babel-runtime/helpers/get" from http://localhost:1337/scripts/user.js
    at r (http://localhost:1337/node_modules/systemjs/dist/system.js:4:10975)
    at XMLHttpRequest.o.onreadystatechange 
GET http://localhost:1337/babel-runtime/helpers/create-class 404 (Not Found)
GET http://localhost:1337/babel-runtime/helpers/class-call-check 404 (Not Found)
```

My SystemJS config file looks like this:

```
System.config({
	transpiler: "babel",
	babelOptions: {
		optional: [
			"runtime"
		]
	},
	map: {
		'babel': 'node_modules/babel-core/browser.js'
	}
});
```

My guess was that the XHR error was caused because these files were missing (maybe they are some kind of polyfills for these keywords, which is why the error was triggered?), therefore I tried running `npm install babel-runtime` and consequently appended `'babel-runtime': 'node_modules/babel-runtime',` to the config, but no difference. Maybe there's some other hidden dependency or I'm missing something obvious out there.

**Comment by guybedford** [comment]
If you're wanting to use the single-file Babel runtime, then rather remove the `runtime` optional transformer as the external runtime is the default case.

**Comment by arnaudoff** [comment]
Thanks, removing that and using babel-runtime separately seems to work just fine.

**Comment by subchen** [comment]
A workaround used for me

```js
System.config({
    baseURL: '/',
    transpiler: 'babel',
    babelOptions: {
        'optional': [
            'runtime'
        ]
    },
    map: {
        'babel': 'node_modules/babel-core/browser.min.js',
        'babel-runtime': 'node_modules/babel-core/browser-polyfill.min.js'
    },
    meta: {
        'babel': {
            deps: ['babel-runtime']
        },
        'babel-runtime': {
            format: 'global'
        }
    }
});
```
