### ISSUE TITLE
SyntaxError: class is a reserved identifier

### ISSUE THREAD

**Issue by ScreenDriver** [systemjs/systemjs#733]
I believe I've found a bug and it's very simple to reproduce:

# index.html
```html
<!doctype html>
<html>
<head>
  <script src="jspm_packages/system.js"></script>
  <script src="config.js"></script>
  <script>
    System.import('src/index');
  </script>
</head>
<body>
</body>
</html>
```

# src/index.js

```js
class Foo {
}
```

Gives me a `SyntaxError: class is a reserved identifier`. If I change `index.js` to something like this

```js
import 'whateveryouwant';
class Foo {
}
```

It works. You **have to** import something before you can use classes.

**Comment by guybedford** [comment]
This is by design and described in https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection. In future we will separate transpilation from the module format though.

**Comment by ScreenDriver** [comment]
:+1: 
Thank you for clarification.
