### ISSUE TITLE
defaultJSExtensions: true and System.register in pre-transpiled modules

### ISSUE THREAD

**Issue by rj33** [systemjs/systemjs#734]
In attempting to update my client side code to the latest version of Systemjs, I manually added .js
extensions to all imports (both System.import and internal es6 module imports) on the assumption that
defaultJSExtensions: true is something that will go away in the future. However, I wasn't able to get the code working without setting defaultJSExtensions to true even after the manual appending of .js everywhere.

It works fine with the manual extensions as long as I also set defaultJSExtensions: true .

I was a bit confused by this, but I'm guessing this is the result of the pre-transpiling I do before hand which is producing System.register format modules like this:

System.register("modules/websockets/websockets", ["modules/i18n/i18n.js"], function (_export) {
etc etc

I'm guessing the lack of .js on the modules/websockets/websockets path is the cause of the issue I see, but wanted to make sure I wasn't missing something else. System.import returns without error , but no dependencies are resolved, and the result returned from the the promise is an empty object.

Is there a way of running with pre-transpiled modules and turning defaultJSExtensions off, or this method of operation pending future changes to Babel?

Thanks,
Richard.

**Comment by guybedford** [comment]
Your modules should only be built without `.js` extensions if you have
defaultJSExtensions: true set at build time.

If you're running a manual Babel task, try setting the module names
yourself via the `moduleName` option to include the extension.

Otherwise it is advisable to use SystemJS builder and apply the
`builder.compile('moduleName')` approach for a single-file build.

The above should really be a standard gulp-systemjs project if anyone is
interested in putting that together.

**Comment by rj33** [comment]
Thanks, I was using a Brocolli based build, and the broccoli-babel-transpiler.

The easiest way to deal with the issue, and keep the same build process seemed to be to use
Babel's getModuleId function option on their transform call which is designed for transforming supplied module names. The Broccoli transpiler plugin creates a moduleId with the source name stripped of extensions if you pass true in for the moduleId option, which you can then transform back again with the getModuleId function. For those in a similar situation the config I've used is:

```javascript
var moduleTree = babelTranspiler(es6Tree, {
    sourceMap: 'inline'
    ,modules: 'system'
    ,moduleIds: true
    ,moduleId: true
    ,getModuleId: function (name) {
        return name+".js";
    }
});
```

A bit fragile given it assumes you are only dealing with .js extended files to start with (which I am), doing better would require directly hacking on the Broccoli plugin to turn off their own internal extension stripping.

With that in place I can now run without defaultJSExtensions: true set, and everything works again.

Thanks for your help!

Regards,
Richard.

**Comment by guybedford** [comment]
Sure, no problem, glad to hear you've got it working now. If doing single-file compilations note that anonymous output is actually best - that is without any name in the `System.register` being used at all. The ensures names remain portable. It should be possible to make this work just with `moduleIds: false` or similar.
