### ISSUE TITLE
I need help setting up Aurelia and SystemJS correctly 

### ISSUE THREAD

**Issue by eyalsk** [systemjs/systemjs#737]
I don't know whether it's a bug in Aurelia, SystemJS or just a failure in the actual configuration but I know that I managed to get this to work with Angular 2.0.

I have two projects, project A is where I have the client-side application and project B is where I have all the JSPM dependencies, project B is kinda like a private CDN.

Project A is hosted at http://localhost:5000
Project B is hosted at http://localhost:5005

Here is my basic index.html setup for Aurelia that resides in project A.
```html
<!DOCTYPE html>
<html>
	<head>
		<base href="/"/>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
		<script src="http://localhost:5005/jspm_packages/system.js"></script>
		<script src="http://localhost:5005/config.js"></script>
	</head>
	<body aurelia-app>
		<script>
			System.import("aurelia-bootstrapper");
		</script>
	</body>
</html>
```
Here is the config.js for systemjs that resides in project B.
```js
System.config({
  baseURL: "http://localhost:5005",
  defaultJSExtensions: true,
  transpiler: "none",
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "aurelia/bootstrapper": "github:aurelia/bootstrapper@0.16.0",
    "github:aurelia/binding@0.8.6": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/bootstrapper@0.16.0": {
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.7.0",
      "aurelia-framework": "github:aurelia/framework@0.15.0",
      "aurelia-history": "github:aurelia/history@0.6.1",
      "aurelia-history-browser": "github:aurelia/history-browser@0.7.0",
      "aurelia-loader-default": "github:aurelia/loader-default@0.9.5",
      "aurelia-logging-console": "github:aurelia/logging-console@0.6.2",
      "aurelia-router": "github:aurelia/router@0.11.0",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "aurelia-templating-binding": "github:aurelia/templating-binding@0.14.0",
      "aurelia-templating-resources": "github:aurelia/templating-resources@0.14.0",
      "aurelia-templating-router": "github:aurelia/templating-router@0.15.0",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/dependency-injection@0.9.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/event-aggregator@0.7.0": {
      "aurelia-logging": "github:aurelia/logging@0.6.4"
    },
    "github:aurelia/framework@0.15.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/history-browser@0.7.0": {
      "aurelia-history": "github:aurelia/history@0.6.1",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/loader-default@0.9.5": {
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3"
    },
    "github:aurelia/loader@0.8.7": {
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "core-js": "npm:core-js@0.9.18",
      "webcomponentsjs": "github:webcomponents/webcomponentsjs@0.6.3"
    },
    "github:aurelia/logging-console@0.6.2": {
      "aurelia-logging": "github:aurelia/logging@0.6.4"
    },
    "github:aurelia/metadata@0.7.3": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/route-recognizer@0.6.2": {
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/router@0.11.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-event-aggregator": "github:aurelia/event-aggregator@0.7.0",
      "aurelia-history": "github:aurelia/history@0.6.1",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-route-recognizer": "github:aurelia/route-recognizer@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-binding@0.14.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-templating": "github:aurelia/templating@0.14.4"
    },
    "github:aurelia/templating-resources@0.14.0": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "aurelia-templating": "github:aurelia/templating@0.14.4",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:aurelia/templating-router@0.15.0": {
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-router": "github:aurelia/router@0.11.0",
      "aurelia-templating": "github:aurelia/templating@0.14.4"
    },
    "github:aurelia/templating@0.14.4": {
      "aurelia-binding": "github:aurelia/binding@0.8.6",
      "aurelia-dependency-injection": "github:aurelia/dependency-injection@0.9.2",
      "aurelia-html-template-element": "github:aurelia/html-template-element@0.2.0",
      "aurelia-loader": "github:aurelia/loader@0.8.7",
      "aurelia-logging": "github:aurelia/logging@0.6.4",
      "aurelia-metadata": "github:aurelia/metadata@0.7.3",
      "aurelia-path": "github:aurelia/path@0.8.1",
      "aurelia-task-queue": "github:aurelia/task-queue@0.6.2",
      "core-js": "npm:core-js@0.9.18"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "npm:core-js@0.9.18": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    }
  }
});
```
**Now, to the actual problem.**

When I'm using System.import("aurelia-bootstrapper"); I get the following error from the browser.

```text
GET XHR http://localhost:5005/aurelia-bootstrapper.js [HTTP/1.1 404 Not Found 1ms]
no element found [aurelia-bootstrapper.js:1:1]
Error: XHR error (404 Not Found) loading http://localhost:5005/aurelia-bootstrapper.js
	Error loading http://localhost:5005/aurelia-bootstrapper.js [system.js:4:0]
```
When I'm using System.import("aurelia/bootstrapper/aurelia-bootstrapper"); I get yet a different error.
```text
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create [localhost:5000:41:6]
GET XHR http://localhost:5005/aurelia-loader-default.js [HTTP/1.1 404 Not Found 0ms]
no element found [aurelia-loader-default.js:1:1]
Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:5005/aurelia-loader-default.js [es6.promise.js:139:1]
	Error loading http://localhost:5005/aurelia-loader-default.js
Stack trace:
r@http://localhost:5005/jspm_packages/system.js:4:10959
e/</M/o.onreadystatechange@http://localhost:5005/jspm_packages/system.js:4:11484
```

**Comment by eyalsk** [comment]
I'd expect this statement 'System.import("aurelia/bootstrapper/aurelia-bootstrapper");' to work.

Now, I spoke with the author of Aurelia and he told me that it has nothing to do with Aurelia but configuration with systemjs so how can I fix it to work correctly?

**Comment by eyalsk** [comment]
Okay, I managed to fix this error with a help from someone on the community.

The problem was in the paths of the map table.

I changed this.

```js
"aurelia/bootstrapper": "github:aurelia/bootstrapper@0.16.0",  
```
to the following
```js
"aurelia-bootstrapper": "github:aurelia/bootstrapper@0.16.0", 
```
However, note that I've done everything from JSPM so I didn't write the config manually, so I suspect there's a bug in the CLI of JSPM.

I fixed the error but then I got few more.

``text
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create [localhost:5000:41:6]
DEBUG [aurelia] "Loading plugin http://localhost:5005/jspm_packages/github/aurelia/templating-binding@0.14.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Configured plugin http://localhost:5005/jspm_packages/github/aurelia/templating-binding@0.14.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Loading plugin http://localhost:5005/jspm_packages/github/aurelia/templating-resources@0.14.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Configured plugin http://localhost:5005/jspm_packages/github/aurelia/templating-resources@0.14.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Loading plugin http://localhost:5005/jspm_packages/github/aurelia/history-browser@0.7.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Configured plugin http://localhost:5005/jspm_packages/github/aurelia/history-browser@0.7.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Loading plugin http://localhost:5005/jspm_packages/github/aurelia/templating-router@0.15.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Configured plugin http://localhost:5005/jspm_packages/github/aurelia/templating-router@0.15.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Loading plugin http://localhost:5005/jspm_packages/github/aurelia/event-aggregator@0.7.0." [aurelia-logging-console.js:38:7]
DEBUG [aurelia] "Configured plugin http://localhost:5005/jspm_packages/github/aurelia/event-aggregator@0.7.0." [aurelia-logging-console.js:38:7]
INFO [aurelia] Aurelia Started aurelia-logging-console.js:46:7
GET XHR http://localhost:5005/app.js [HTTP/1.1 404 Not Found 1ms]
no element found [app.js:1:1]
Unhandled promise rejection Error: XHR error (404 Not Found) loading http://localhost:5005/app.js 
	Error loading http://localhost:5005/app.js [es6.promise.js:139:13]
Stack trace:
r@http://localhost:5005/jspm_packages/system.js:4:10959
e/</M/o.onreadystatechange@http://localhost:5005/jspm_packages/system.js:4:11484
```

**Comment by guybedford** [comment]
Did you manage to make progress here?

**Comment by eyalsk** [comment]
Well, not really, what I did eventually and really didn't want to but I had to is add an additional step in my build process which basically downloads all the dependencies through the CLI of JSPM to the publish directory which is the directory that the publish task creates for deployment.

I did this to experiment different architectures and thought that SystemJS will allow me to host the dependencies in a complete different server as if it was a local CDN but as I posted I get some errors and currently I don't have deep understanding on SystemJS or JSPM to fix them, I don't even know whether it's a bug or nonissue or maybe it's by design. :)

Someone told me (I think it was Zoltu on gitter) that it can work but I need to define all the projects files in the path directory or something, something that is not very friendly or desired imo.

If you want to explore this farther I can set things just to reproduce it and maybe we can make it work?

**Comment by guybedford** [comment]
It sounds your publish task approach is sensible here to me. If you're able to share the case in more detail I'll gladly take a look as soon as I have a little more time here, but can't guarantee a quick response unfortunately.

**Comment by eyalsk** [comment]
Sure, no problem. :)

I'll play with it a bit once I'll have more time and reply back!

**Comment by guybedford** [comment]
I'm going to close this in the mean time, but feel free to reopen a new issue to come back to this.

**Comment by eyalsk** [comment]
Sure.

**Comment by k8kalyan** [comment]
Hi,

I am getting the following error

Potentially unhandled rejection [3] Error loading "aurelia-bootstrapper: npm:aurelia-bootstrapper@2.1.1" at https://registry.jspm.io/aurelia-bootstrapper: npm:aurelia-bootstrapper@2.1.1.js
: https://registry.jspm.io/aurelia-bootstrapper: npm:aurelia-bootstrapper@2.1.1.js (WARNING: non-Error used)

My index.html is

<!DOCTYPE html>
<html>

  <head>
    <link rel="stylesheet" type="text/css" href="style.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Aurelia</title>
  </head>

  <body aurelia-app="">
    <div class="splash">
      <div class="message">Loading...</div>
    </div>
    <script data-require="jspm@0.16.7" data-semver="0.16.7" src="https://jspm.io/system@0.16.7.js"></script>
    <script data-require="Aurelia@0.13.0" data-semver="0.13.0" src="https://rawgit.com/distros/aurelia/0.13.0/aurelia.js"></script>
    <script src="config.js"></script>
    <script>
      System.import("aurelia-bootstrapper": "npm:aurelia-bootstrapper@2.1.1");
    </script>
  </body>

</html>

Can anyone help me to resolve this issue.

**Comment by eyalsk** [comment]
@k8kalyan Create a new issue about it.
