### ISSUE TITLE
Support Authorization

### ISSUE THREAD

**Issue by typhonrt** [systemjs/systemjs#739]
Greets,

3rd day w/ SystemJS, so I'm new here. I converted over some sites from RequireJS and I have the need to load modules and resources between two unbundled sites that use HTTP basic authentication. As things go this addition requires changes to systemjs and es6-module-loader. Here are the pull requests:
https://github.com/systemjs/systemjs/pull/738
https://github.com/ModuleLoader/es6-module-loader/pull/431/

The forks are found here:
https://github.com/typhonrt/systemjs
https://github.com/typhonrt/es6-module-loader

Here are the details found in the Readme update:
---------

Important: This fork depends on coordinated changes in "system-fetch.js" in  "https://github.com/ModuleLoader/es6-module-loader", so as things go with this fork calling "npm install" will not pull in the changes from es6-module-loader. The changes in this fork are found in core.js adding the new configuration option "basicAuth". To test though you can take "/dist/system.src.js" and "/dist/system-csp-production.src.js" from this fork directly. The coordinated changes for es6-module-loader can be found in "https://github.com/typhonrt/es6-module-loader".

This is a SystemJS fork adding the ability to pull in modules and other resources cross-domain that require HTTP basic authorization. The necessity for this addition is that I have an unbundled admin domain / site that references modules and resources from the main unbundled development site / domain. Both the admin and developer domain have basic authentication enabled. Since SystemJS uses XMLHttpRequest it's necessary to set authentication headers from the requesting domain (in my case the admin site). To fascilitate this process a new configuration option has been added. "basicAuth" which can contain one or more authentication credentials like the following:

```
   basicAuth:
   {
      "https://private.server.com/": { username: '<USERNAME>', password: '<PASSWORD>' },
      "https://private.server2.com/": { username: '<USERNAME>', password: '<PASSWORD>' }
   },
```

SystemJS when loading resources will add the authentication header with encoded username / password for urls matching the domains provided in the config parameters.

It should be noted that an associated .htaccess file needs to be defined or other web server configuraiton needs to be setup on the private server to be accessed. The following is an example .htaccess file with the relevant details:

```
AuthType Basic
AuthUserFile /home/username/private.server.com/.htpasswd
AuthName "Private"
<LimitExcept OPTIONS>
   require valid-user
</LimitExcept>

Header always add Access-Control-Allow-Origin "https://requesting.domain.com"
Header always add Access-Control-Allow-Headers "accept, origin, x-requested-with, authorization, content-type"
Header always add Access-Control-Allow-Methods "GET"
Header always add Access-Control-Allow-Credentials "true"
```

I have only tested these changes with Chrome & Safari on OSX. Note, that the above ```<LimitExcept OPTIONS>``` is necessary for Chrome as an OPTIONS request is sent and returned before the actual GET request. 

Please note that the code in this fork has been changed in libs and the make file run, but only the complete source versions of "/dist/system.src.js" and "/dist/system-csp-production.src.js" have the actual changes. The minified and other versions are not modified. Also note the important fact that this modification depends on changes in es6-module-loader as well, so if you run the make file you won't pull in those changes.

Please also note that I'm not a security expert. It seems OK to store the basic authorization credentials in the config.js file for the requesting site. Since in my case I have basic authorization setup for the requesting site the config.js file is not accessible without authentication on the requesting site.

**Comment by guybedford** [comment]
@typhonrt I went ahead and implemented this in https://github.com/ModuleLoader/es6-module-loader/commit/e436b84cb3e13fef3de36c5ccac01403c6fcb709 and https://github.com/systemjs/systemjs/commit/70624566c9dde3220a672b9b9736a5fe20a48c86. If you're able to test it out further I'd be very grateful.

**Comment by typhonrt** [comment]
I finally got my framework and web apps converted over to ES6 (so much better!) and back running. Your authentication patch works well in my environment.

**Comment by guybedford** [comment]
:+1:
