### ISSUE TITLE
Unable to import a module

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#741]
I have been trying to import **render** module from the package [dagre-d3](https://github.com/cpettitt/dagre-d3). But I can import **dagree** only. You can see a [sample code](http://cpettitt.github.io/project/dagre-d3/latest/demo/arrows.html) of how it is done with requirejs.

This is what I've done to import in the code at the beginning of the file:

```javascript
import { dagreD3, render } from 'dagre-d3' 
// ### dagreD3 imported correctly, but render is undefined ### 
```

A snippet of code showing dagreD3 and render:

```javascript

var g = new dagreD3.graphlib.Graph().setGraph({}); // ### dagreD3 imported correctly ### 

// Create the renderer
var render = new dagreD3.render(); // ### render is not imported ### 

// Run the renderer. This is what draws the final graph.
render(inner, g);
```

Looking at the dagre-d3 code in GitHub, it exports **render** module correctly. How can I import **render** module?

**Comment by varghesep** [comment]
I made a few changes to make this work.

The index.js of dagre-d3 has this:

```javascript
module.exports = {
  graphlib: require("./lib/graphlib"),
  dagre: require("./lib/dagre"),
  intersect: require("./lib/intersect/index"),
  render: require("./lib/render"),
  util: require("./lib/util"),
  version: require("./lib/version")
};
```

I changed

```javascript
import { dagreD3, render } from 'dagre-d3'
```

to 

```javascript
import dagreD3 from 'dagre-d3'
```

I changed the first line of the code to

```javascript
var g = new dagreD3.dagre.graphlib.Graph();
```

**Comment by guybedford** [comment]
@varghesep what you were trying to do should certainly be working though here. Make sure you're running the latest version of SystemJS / jspm.
