### ISSUE TITLE
Why does this code not work in Firefox?

### ISSUE THREAD

**Issue by acopalipsis** [systemjs/systemjs#742]
**systemfile.js**
```
'use strict';

System.config({
    defaultJSExtensions: true,
    baseUrl: '/javascripts',
    map: {
        'angular': '/bower_components/angular/angular.js',
        'pixi.js': '/bower_components/pixi.js/bin/pixi.js',
        'index': '/javascripts/index.js'
    },
    meta: {
        '/bower_components/angular/angular.js': {
            'format': 'global'
        }
    }
});

System.import('index').then(function(target){
    var Index = target.Index;
    var index = new Index();
});
```
**index.js**
```
import {app} from './app';
import Test from './test';


export class Index {
    constructor(){
        new Test();
        console.log('index', app);
    }
}
```
**app.js**
```
import * as angular from 'angular';

export const app = angular.module('app', []);
```
**test.js**
```
import * as PIXI from 'pixi.js';

export default class Test{
    constructor(){
        console.log(PIXI);
    }
}
```

In google chrome works, but in Firefox -  
>Error: angular.module is not a function  
>Error loading http://localhost:8080/javascripts/index.js

Help I can't solve this problem.  

p.s. don't know it's important or not, but typescript code.

**Comment by guybedford** [comment]
This works fine for me in Firefox, logging both objects. The only thing I can see though is a syntax error in pixi.js line 1, which doesn't seem to affect execution though, and there is no load error.

**Comment by acopalipsis** [comment]
Spending a few days and so not understanding, I decided to forget about this problem and finish the application. But then will come back to this.
