### ISSUE TITLE
Has support for declaring deps inline been dropped?

### ISSUE THREAD

**Issue by vigie** [systemjs/systemjs#743]
I notice it is not mentioned in the docs for meta anymore, whereas it was circa version 0.16: https://github.com/systemjs/systemjs/blob/0.17.1/docs/config-api.md#meta . 

Has support for writing the dependencies of a global module directly into that global been dropped? If so can you explain why (I looked in the release notes but could not find reference)?

 I am writing an app using es6 modules and systemjs that takes advantage of a bunch of in house globals written previously that I am free to modify. It is a lot easier to write and maintain the dependencies directly at the top of those global files via `dep ./foo`, rather than having to remember to maintain a meta block in a config.js that is completely external to where the source of the globals reside. Another team modifying the global scripts could easily break me without knowing in that case, whereas they are likely to see the `dep` notation at the top of the scripts.

I want to know whether I should continue to rely on the inline deps method. It is working well so far, but it having disappeared from the docs makes me nervous. If not, what is the recommended way of configuring the dependencies of my in-house global modules for use in an es6 systemjs app?

Related question(s) - I tried poking around inside jspm_packages to see how it was done with other global scripts such as ui-router. I see "deps angular" at the top of that file - how did that get there and is that the metadata that systemjs relies on at runtime (or does it read it from elsewhere)? How is it related to the .jspm.json files - who produces and consumes those and is that a technique I can use?

Thanks much!

**Comment by guybedford** [comment]
Inline meta syntax is supported for all meta properties (listed under https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta), it's just not documented as it's not generally encouraged. jspm uses the meta syntax to handle shims, but will be moving to use config-only in the next major. For use cases like the one you describe, config meta is the way recommended, but inline syntax is absolutely fine here and will continue to be supported.

**Comment by vigie** [comment]
Hi Guy, thanks for the response (and jspm!). 

Would you consider the inlining feature as deprecated or just undocumented? If you agree with me that it is the best way to add the meta data in situations where you are free to modify the source, can I ask why you would not recommend/document this feature? Why are you recommending the config.js technique for my use case over that?

Are you saying jspm will stop adding the metadata to the top of the source files and rely exclusively on the metadata in the config.js file?

**Comment by guybedford** [comment]
Inline meta is definitely supported, but yes jspm will stop using it as part of its processing so that source remain unmodified.
