### ISSUE TITLE
question(plugins API): no more exposed plugin metadata in SystemJs 0.18

### ISSUE THREAD

**Issue by douglasduteil** [systemjs/systemjs#744]
Hi @guybedford 

I try to make [jspm-loader-css](https://github.com/geelen/jspm-loader-css) work on SystemJs 0.18 but I stuck on the path resolving because the `pluginArgument` on the `load.metadata` in a fetch hook is undefined (@see https://github.com/geelen/jspm-loader-css/blob/v0.1.6/index.js#L19).

Any clue of how the access it ?
Or can I get the `baseUrl` from somewhere inside a plugin ?

It suppose to be like : 

```sh
load.address
> "http://localhost:3001/src/Main.css"
load.metadata.pluginArgument
> "src/Main.css"
```

**Comment by guybedford** [comment]
@douglasduteil yes the pluginArgument was removed as `load.address` is the correct value here. the baseURL can be accessed from `System.baseURL` fine. It shouldn't be necessary to work with any other name format than URLs though.

**Comment by douglasduteil** [comment]
Alright thanks :)
