### ISSUE TITLE
Invalid anonymous System.register module load

### ISSUE THREAD

**Issue by rolandjitsu** [systemjs/systemjs#746]
I have an [app](https://github.com/rolandjitsu/ng2-play) which is written in TS and I use `"module": "system"` to compile to `es5` as a setting in my [tsconfig.json](https://github.com/rolandjitsu/ng2-play/blob/master/tsconfig.json#L5).

But for some reason I keep getting a `Uncaught TypeError: Invalid anonymous System.register module load. If loading a single module, ensure anonymous System.register is loaded via System.import. If loading a bundle, ensure all the System.register calls are named.`.

<img width="1440" alt="screenshot 2015-08-31 09 00 29" src="https://cloud.githubusercontent.com/assets/1479737/9573620/c076786a-4fbe-11e5-871e-5acd8c14d9d4.png">

I am unsure what is happening, as I found other setups that work just fine when compiling to system module with the TS compiler. If I use commonjs instead, everything works without problems.

**Comment by vladima** [comment]
This issue should be resolved in the recent TypeScript bits - it used to emit `__extends`, `__decorate` and `__metadata` helper functions in global scope thus breaking SystemJS module kind detection logic. Can you try TypeScript nightly builds available as `typescript@next` npm package to see if this resolves the problem

**Comment by rolandjitsu** [comment]
@vladima I think that might have worked, I just got into some other trouble right now, but I think it's not related to systemjs. I will let you know if the issue still occurs, but I think you are right that the newest version of TS has resolved this issue.

**Comment by rolandjitsu** [comment]
@vladima It does work with the latest release of TS (the release not yet on npm, but the nightly build). I'm closing this, thanks for the help :)

**Comment by timothysoehnlin** [comment]
I'm running with Typescript@Next, resolving to 20150908, and with System.js 0.18.17, and I'm currently getting the error above.  

This is running through gulp-typescript, but I verified that the instance of typescript it is using to compile is  typescript@next.

**Comment by guybedford** [comment]
@timothysoehnlin make sure that your transpiled file has `System.register` as the first code statement in the file for separate file System.register loading to work.

**Comment by timothysoehnlin** [comment]
Feel stupid, but the issue was my gulp file was concatenating all the files together, and the import paths were not resolved.  Which ended up with the same import path having multiple definitions.  Thanks.
