### ISSUE TITLE
Is <script type="module"> supported via SystemJS?

### ISSUE THREAD

**Issue by g0t4** [systemjs/systemjs#747]
Using ES6 Module Loader polyfill, a script block tagged with type="module" will load, see example: http://plnkr.co/edit/XcubZO2NLDGrUkRfCGNc?p=preview

Trying to demonstrate modifying that example to work with SystemJS (http://plnkr.co/edit/VCyuDEigR7d4Gi9iry1C?p=preview), doesn't seem like SystemJS has the same behavior to sniff out these modules and translate/instantiate them like ES6 Module Loader polyfill does. Is this intentional in SystemJS? I've run across a few examples where it looks like it may have been supported at one time: https://github.com/systemjs/systemjs/issues/586

**Comment by guybedford** [comment]
@g0t4 yes this feature is not included in SystemJS as there isn't a production workflow associated with it.

**Comment by g0t4** [comment]
Makes sense, thanks for confirming, I see in ESML that it's only in the dev build too.

**Comment by tomlarkworthy** [comment]
My production workflow is I want to demonstrate code about a dev centric TS project to people live, and it makes sense to have the core demo inside an in inline script tag.

**Comment by rpkilby** [comment]
@guybedford - would it make sense to load modules though? eg,
```html
<script src="system.js"></script>
<script src="system.config.js"></script>
<script src="app/main" type="module"></script>
```
This would be nicer to use over the `System.import()` call, but I'm not sure how feasible it is to implement.
