### ISSUE TITLE
Redundant angular dependencies when moving from AMD to ES6

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#748]
Consider the following AMD code:
```js
define(function(require) {
  var angular = require('angular');
  var moduleId = require('module').id;
  var componentModule = angular.module(moduleId, [
    require('./home'),
    require('./about')
  ]);
  componentModule.config(function($stateProvider) {
    $stateProvider.state('foo', {
      url: '/foo',
      template: require('foo.jade!')
    });
  });
  return moduleId;
});
```

and now ES6 code:
```js
import angular from 'angular';
import homeModule from './home';
import aboutModule from './about';
import fooTemplate from 'foo.jade!';

let componentModule = angular.module('MyMadeUpName', [
  homeModule,
  aboutModule
]);
componentModule.config(function($stateProvider) {
  $stateProvider.state('foo', {
    url: '/foo',
    template: fooTemplate
  });
});
export default 'MyMadeUpName';
```

Arguably, the AMD code allows for a couple of nice things:

* No redundancy in defining dependencies, simply require the dependency inside angular list of dependencies and module loader will automatically pick them up
* Import template inline as needed, no need to put the dependency on top
* Ability to use `module.id` to create unique angular modules if you don't care about the naming

I tried using `System.import` instead of require but this loads dependencies dynamically, module loader will not figure out the dependency tree then.

Is there any way to improve ES6 code (perhaps with some SystemJS goodies) to make it as robust convenient (not redundant) as the AMD code?

**Comment by guybedford** [comment]
`angular.module(modulename` isn't ideal for use with portable multi-version module systems like SystemJS. These patterns will go away in time with some luck.

You can access the module ID via `__moduleName` in SystemJS for es modules currently. This will be available via special meta syntax but we are waiting for the spec authors to specify this so we have `__moduleName` in the mean time.

The design of ES modules is around making modules statically analyzable and then also enabling asynchronous dynamic imports via `System.import`. CommonJS lacks these properties, and these differences are the source of a lot of friction upgrading certainly, but it is definitely for the best as these are valuable properties to have.

**Comment by guybedford** [comment]
Just let me know if you have any further questions here.

**Comment by hitmanmcc** [comment]
Sorry to be commenting on a closed issue but would you happen to know if there is a way I can access __moduleName in transpiled code?

**Comment by guybedford** [comment]
@hitmanmcc `__moduleName` was shifted to the transpiler in https://github.com/systemjs/builder/issues/416 with the PRs for the transpilers referenced there. What transpiler are you using?

**Comment by hitmanmcc** [comment]
Hey @guybedford thanks for the assistance, fortunately I eventually got this working, through some googling I eventually found some documentation that helped me. I'm using traceur, it was just a matter of setting ```moduleName: true``` in trhe traceur options object in the configurations.

**Comment by guybedford** [comment]
@hitmanmcc sure, I can't guarantee that this will continue to work in the coming releases though.
