### ISSUE TITLE
problems with systemjs v0.18.9 and cordova 4

### ISSUE THREAD

**Issue by maxgrv** [systemjs/systemjs#749]
We have just upgraded a cordova+aurelia project to systemjs v0.18.9 (with jspm@beta) and the app, while works fine in chrome desktop, no longer works inside cordova. 

The main problem is related to file:// XHR request, it seems that system.js does not recognize the environment correctly and issues XHR requests to "file://android_assets/www/.." instead of "file:///android_assets/www/.." (note the triple / which is required in cordova).

We made a quick patch to our copy of systemjs replacing brutally "file://" with "file:///" just before the XHR request is issued and the workaround does the job, but we think that this is not the correct fix :)

Thanks,
Massimo

**Comment by guybedford** [comment]
@maxgrv thanks so much for posting, this is great to know about and it would be nice to get in a fix certainly. If you can log the value of `System.baseURL`, that would be very useful to know if this is an issue with setting the baseURL or if it is happening elsewhere.

**Comment by maxgrv** [comment]
the baseURL is correct, "file:///android_asset/www/"

**Comment by guybedford** [comment]
Interesting, does the environment support `URL`? If so perhaps check `new URL('./test', 'file:///android_assets/www/').href` is normalized correctly?

**Comment by maxgrv** [comment]
new URL('./test', 'file:///android_assets/www/').href
results in 

       "file:///android_assets/www/test"

**Comment by guybedford** [comment]
Ha, well I have no idea how the `file://` might be creeping in then. Perhaps run `System.normalizeSync('x')` or `System.normalize('x').then(console.log.bind(console))` to see if you can find any module normalizations that give this value. Perhaps it's a plugin causing the issue or something like that as well. If you can share any type of test case I'd be happy to take a look.

**Comment by guybedford** [comment]
Closing without further info, but if you do look into this again, please do report back.

**Comment by weagle08** [comment]
I'm having this same issue with systemjs v0.19.9. It isn't resolving the paths to the js files correctly as posted here: http://stackoverflow.com/questions/35145962/using-systemjs-to-load-files-for-cordova-app

**Comment by weagle08** [comment]
I can publish a sample cordova project if that would help. NOTE: this happens only when installed to the device.. in the browser it works fine.

**Comment by guybedford** [comment]
In the browser it will be loading `file:///android_asset/www/jspm_packages/npm/module@1.0.0.js` too as that is how SystemJS finds the main entry point file without other information present. You should see that being requested if you look at the network tab. Perhaps given that you can clarify the question further.
