### ISSUE TITLE
'use strict' breaks importing

### ISSUE THREAD

**Issue by techniq** [systemjs/systemjs#75]
I'm just getting into ES6 modules, but I ran into an issue that surprised me.  If I import a module using strict mode (`'use strict';`), the entire application fails.

`index.js`

``` javascript
var System = require('systemjs');

System.import('main').then(function(m) {
    console.log('loaded');
})
```

`main.js`

``` javascript
console.log('before import');

import { name } from './lib';
console.log('name: ' + name);
```

`lib.js`

``` javascript
'use strict'; // <-- Breaks app
export var name = 'Foo';
```

Running `node index.js` will silently finish without logging anything to stdout, but if I remove `'use strict';` from `lib.js`, I'll get the expected output:

```
before import
name: Foo
loaded
```

Something else surprising is even if `'use strict`;` is commented, the app still fails silently.

`lib.js`

``` javascript
// 'use strict';
export var name = 'Foo';
```

**Comment by geri777** [comment]
Hm - still have the same problem in version 0.18.2. See https://plnkr.co/edit/bhSTkcZw9XaKszXuIYZQ
Please help!

**Comment by danieldram** [comment]
Still breaking for me. 
<img width="1271" alt="screen shot 2016-11-01 at 9 28 42 am" src="https://cloud.githubusercontent.com/assets/4514000/19897557/adb16c50-a015-11e6-8886-01aa370931c3.png">

**Comment by mreiche** [comment]
Is there any solution for SystemJS 0.19? Because this breaks bundling several libraries with JSPM https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/issues/444

**Comment by guybedford** [comment]
@mreiche if you have a simple replication of a module that won't load I can look into this, but wasn't able to track through these links what the exact scenario is that is failing.

**Comment by mreiche** [comment]
I can provide you simple steps to reproduce.
```
# jspm -v
0.16.53
Running against global jspm install.
```

```
# jspm install aurelia-materialize-bridge npm:materialize-css text
```

```
# jspm bundle materialize-css + [aurelia-materialize-bridge] + [aurelia-materialize-bridge/**/*.js] + 'aurelia-materialize-bridge/**/*.css!text' + 'aurelia-materialize-bridge/**/*.html!text' ./material.min.js --skip-source-maps --minify
```

```
# less material.min.js
"use strict";System.register(...
```

**Comment by guybedford** [comment]
Which transpiler and transpiler version are you using here?

**Comment by guybedford** [comment]
(the transpiler is supposed to make sure the "use strict" is inside of the System.register wrapper when built)

**Comment by mreiche** [comment]
```json
{
 transpiler: "babel",
  babelOptions: {
    "optional": [
      "es7.decorators",
      "es7.classProperties"
    ]
  }
}
```

```
# jspm inspect | grep babel
npm:babel-core 5.8.38
npm:babel-runtime 5.8.38
```

**Comment by guybedford** [comment]
I tried running this but get the error on build -

```
err  Error on dependency parsing for npm:materialize-css@0.99.0/dist/js/materialize.js at file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/materialize-css@0.99.0/dist/js/materialize.js
	Loading npm:materialize-css@0.99.0.js
	Error: Multiple anonymous defines.
         at AMDDependenciesTransformer.transformCallExpression (/Users/guybedford/Projects/jspm-cli/node_modules/systemjs-builder/compilers/amd.js:98:13)
```

**Comment by guybedford** [comment]
Actually the error I get is just:

```
Error on fetch for npm:materialize-css@0.99.0/dist/js/picker.js at file:///Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/materialize-css@0.99.0/dist/js/picker.js
	Loading npm:materialize-css@0.99.0/dist/js/materialize.js
	Loading npm:materialize-css@0.99.0.js
	Error: ENOENT: no such file or directory, open '/Users/guybedford/Projects/jspm-cli/sandbox/jspm_packages/npm/materialize-css@0.99.0/dist/js/picker.js'
```

**Comment by mreiche** [comment]
> Actually the error I get is just:

Thats right. You don't get the error when you remove "use strict"; from the beginning of "material.min.js".

**Comment by guybedford** [comment]
@mreiche I get that error on the bundle operation itself, before `materialize.min.js` is created. `materialize.js` has no use strict in it at all.

**Comment by mreiche** [comment]
Ok, I created a fresh sandbox like you. I got the same error. We're missing an override here. Please use this package.json:
```
{
  "jspm": {
    "devDependencies": {
      "aurelia-materialize-bridge": "npm:aurelia-materialize-bridge@^0.29.0",
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4",
      "materialize-css": "npm:materialize-css@^0.99.0",
      "text": "github:systemjs/plugin-text@^0.0.11"
    },
    "overrides": {
      "npm:aurelia-materialize-bridge@0.29.0": {
        "peerDependencies": {
          "materialize": "npm:materialize-css"
        }
      },
      "npm:materialize-css@0.99.0": {
        "main": "dist/js/materialize",
        "format": "global",
        "shim": {
          "js/materialize": {
            "deps": [
              "../css/materialize.css!"
            ]
          }
        }
      }
    }
  }
}
```

Please run ``jspm cache-clear`` and ``jspm update``

**Comment by guybedford** [comment]
Right, this is exactly cause by the `'use strict'` statement in the `npm:aurelia-materialize-bridge@0.29.0/common/polyfills.js` file. This is something that could be fixed through SystemJS builder potentially, but it might be quicker to just ensure that isn't present in that file.

**Comment by Thanood** [comment]
@guybedford 
The `'use strict'` is generated by (gulp-)babel and therefore it is everywhere.. 😕
Maybe there's a babel setting which can prevent that.

I'm just wondering if SystemJS would need to be able to load that from time to time.

**Comment by guybedford** [comment]
@Thanood great, thanks for looking into this.
