### ISSUE TITLE
Ability to load external scripts without CORS

### ISSUE THREAD

**Issue by Rush** [systemjs/systemjs#750]
One example that is currently not working is stripe, I define it as follows:
```
  map: {
    "stripe": "https://js.stripe.com/v2/stripe-debug"
  }
```
and then I try to load it via:
```
require(['stripe'], function() {
  
});
```

it used to work with require.js, here it is doing XHR - how can I force the script behavior?

**Comment by matthewbauer** [comment]
I think the "scriptLoad" meta option should be able to accomplish this. I'm not sure if it works in this case though. It looks like that script is global? Ideally that shouldn't be a problem but I think that SystemJS only loads AMD scripts through the script tag. I think in this case the easiest solution at the moment is to just add the script tag manually.

**Comment by Rush** [comment]
Okay, I confirmed that `scriptLoad` does make it work, but only in development mode. I think the statement about AMD scripts being loaded with script tag is wrong cause I was getting a CORS error and the request was being done through XHR. 

One problem ... when built to an SFX bundle, it's not working at all (no error either, require just doesn't do a thing)

**Comment by Rush** [comment]
Instead of doing SFX bundle I did a classical one and then I concatenated 3 files together:

* system-csp-production.src.js
* non-SFX bundle.js
* entry.js file with `System.import('bundle');`

Of course everything is done via `gulp`. Loading those external scripts now works if I load then via full url, like so:
```
require(['https://js.stripe.com/v2/stripe-debug.js'], function() {
});
```

Closing this as I solved my issue, but definitely it would be nice if system.js worked more OOTB in this regard.
