### ISSUE TITLE
Unable to load extended classes (ts-generated) with SystemJS@0.18.7

### ISSUE THREAD

**Issue by ilbmiller** [systemjs/systemjs#752]
I can not get a karma unit test to import a class that happens to extend another class.  I have written a simple test suite (webapp/test/specs/utils/SystemJSExtensionUSpec.ts) that illustrates the problem.
```
import {Child} from "abweb/test/sample/Child";
import {ChildBase} from "abweb/test/sample/ChildBase";

describe("SystemJS Imports Testing Suite", function ()
{
    it("base class succeeds if it does not extend from another class", function ()
    {
        var baseClass: ChildBase = new ChildBase();
        expect(baseClass).not.toBeNull();
    });
    it("importing a class fail if it extends from another class", function ()
    {
        var child: Child = new Child();  // This line fails
        expect(child).not.toBeNull();
    });
});
```

The first test uses the imported ChildBase.js class (which does NOT extend from another class), and this test succeeds.  However, the second test uses the imported Child class (which extends ChildBase), and this fails.  I think it fails as the debugger shows that the 'handle' for the imported Child class is an Object instead of a Module (and the handle for the imported ChildBase class is a Module):
```
[1A[2KChrome 44.0.2403 (Windows 7 0.0.0) SystemJS Imports Testing Suite importing a class fail if it extends from another class FAILED
	TypeError: Child_1.Child is not a function
	    at Object.<anonymous> (c:/sand/webcommons/webcommons/abweb/webapp/abweb/test/specs/utils/SystemJSExtensionUSpec.js:18:33)
```
Some basic debugging from a SystemJS newbie: 
  My guess is that maybe the 'preamble' that typescript@1.5.3 transpilation puts at the top of extended classes is messing up systemjs parsing the dependencies out of the file.  Below is an example __extends preamble from Child.js:
```
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};System.register(["abweb/test/sample/ChildBase"], function(exports_1) {
...
 ```

If I use the debugger, when systemjs.src.js loads Child.js  (line 2206, which is the first line of the 'function(load)' returned by the 'instantiate hook), the 'load' argument shows that the child.js content was successfully retrieved (via load.source value), but the 'load.metadata.deps' array is empty (I'd expect it to contain the imported ChildBase dependency, which clearly shows in the load.source content (e.g., '.... System.register(["abweb/test/sample/ChildBase"] ....'.  My guess is that the Child dependencies are thus not successfully processed (perhaps as a result of the preamble messing up the parse of load.source?), which in turn causes the imported Child to be an 'Object' instead of a Module.  Another debugging point: I put a 'console.log("invoking Child system.register") within the Child.js system.register function body, and it was never invoked (but was when put similar logging in the ChildBase.js class)

Some other notes:
I'm not using the 'transpilation' functionality of systemjs, as the ts transpilation happens externally before the unit test is run (either via 'gulp:compile' or via intellij typescript support).  I do this by setting the System.transpilation to null.

**To reproduce**, ensure following installed globally
First, download toy-lib.zip via:
 https://drive.google.com/file/d/0B2LU_VSuRkGLYVdPVjN5VF94TWs/view?usp=sharing

<ol>
<li>I have node@0.12.7, npm@2.13.1, jspm@0.16.2 installed globally
<li>Running under Windows 7
</ol>

Setup Example code
<ol>
<li>unzip the attached toy-lib.zip
<li>cd toy-lib
<li>npm install                // Sometimes have to run 'npm install' twice as can get spurious lock exception on Windows on first run.  sigh...
<li>jspm install               // installs jspm 0.16.2, systemjs 0.18.7
<li>gulp clean
<li>gulp compile          // typescript compilation and tslint
</ol>

Now run test
<ul>
<li>gulp test:unit:karma-jspm                 
<li>Alternative: fails the same way
gulp test:unit:karma-systemjs
</ul>

---------

Minor issue #2: in systemjs.src.js, the code for normalizePlugin will only strip the default extension (result of defaultJSExtension=true) from the filename if the explicit plugin syntax '!<plugin>' is used (e.g., 'foo.html!text').  However, when you look at the systemjs plugin doc page, it shows how to use 'map' to automatically use a plugin based on a file expression like '*.html' (and thus no '!text' suffix needed).  This no longer works when defaultJSExtension=true.  You can change the map file expression to to *.html.js to ensure the appropriate plugin is used, but the systemjs normalizePlugin method will NOT strip off the '.js' extension before trying to load the file from the server (and thus get a 404 from trying to load 'foo.html.js').

-------

Minor issue #3: why does the package.json contain the following jspm devDependencies?  Is it related to System.transpilation being set to null (or {})?  Should I be worried, or can I safely ignore?
```
"[object Object]": "npm:babel-core@^5.8.22",
"[object Object]-runtime": "npm:babel-runtime@^5.8.20"
```

**Comment by ilbmiller** [comment]
Arg!  It is a typescript 1.5 bug (https://github.com/Microsoft/TypeScript/issues/3655), where Guy correctly prescribes that ts should emit the __extends verbiage inside of they system registry.  In the forthcoming typescript 1.6, they now do that (I verified using 'typescript@next'), and my test isolating the issue (second test within SystemJSExtensionUSpec) passes with typescript@next transpiled js files.   

<snarky>When typescript 1.5 said they support loading classes with systemjs, they didn't say anything about the ability to load *subclasses* with systemjs</snarky>.  Pretty big bug...

However, not closing in the hope that someone can offer insight into the Minor issue #2 and #3 listed in this issue.  Thx!

**Comment by guybedford** [comment]
Yes it's advisable to use the TypeScript nightlies. Your `devDependencies` should certainly not contain `[object Object]`. If you can share a replication for how to make the package.json get that, that would be useful to debug this.

defaultExtension: false in the package configuration can be used to opt-out of defaultJSExtensions on a per-package basis. Something like:

```javascript
System.config({
  packages: { 
    'test/sample': {
      defaultExtension: false
    }
  }
});
```

See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages for more info here.

**Comment by ilbmiller** [comment]
Thanks Guy.  We use Intellij for our web client development, and it currently does not yet support the new ts 1.6 compiler api (ts removed the node_modules/typescript/bin/typescriptServices.js that Intellij uses in favor of a new api).  We'll have to wait until Intellij supports the new api before we can a) move to ts 1.6, and b) possibly decide that we want to live on the typescript 'edge' via nightlies.  All of this is independent of systemjs and jspm, but we won't be able to port to systemjs/jspm until our organization can use intellij with ts 1.6 (minimum) in order to avoid the ts 1.5 bug 3655.

**devDependencies:** to reproduce, use the setup described above (based on toylib), remove the rogue [object Object] lines in the devDependencies section of the package.json, and then run 'jspm install'.  The [object Object] lines will reappear.  I believe they are related to setting the System.config 'transpiler' variable to {}.  Equivalent behavior if I set transpiler=null and run jspm install; the transpiler value magically becomes {} and the [object Object] lines reappear in devDependencies).

**defaultExtension:**  We co-locate our html files (which are 'layout fragments) with the classes that use them - thus foo.ts and foo.html are in the same directory.  It is unclear how 'packages' would be applicable, as we thus need different extension behaviors for different files within the same directory (and a directory is apparently the scope of a package pattern like 'test/sample').  To put it another way, within 'test/sample' could I have foo.ts contain 'import fooLayout from "test/sample/foo.html"?  I'm just identifying the use case where I believe there is a deficiency (and was supported before defaultJSExtension was introduced); however, systemjs does provide the nice explicit plugin syntax workaround of using 'import fooLayout from "test/sample/foo.html!text', so we're not blocked.  

Thanks Again!

**Comment by guybedford** [comment]
@ilbmiller sure I've added a check in https://github.com/jspm/jspm-cli/commit/72c018f88622086ebabf2c236511e1afc1168425 to avoid the devDependencies issue.

`defaultExtension: false` is completely compatible with other extensions being loaded, it just opts out of the `defaultJSExtensions` adding.

**Comment by theangular** [comment]
> Yes it's advisable to use the TypeScript nightlies. Your `devDependencies` should certainly not contain `[object Object]`. If you can share a replication for how to make the package.json get that, that would be useful to debug this.
> 
> defaultExtension: false in the package configuration can be used to opt-out of defaultJSExtensions on a per-package basis. Something like:
> 
> ```js
> System.config({
>   packages: { 
>     'test/sample': {
>       defaultExtension: false
>     }
>   }
> });
> ```
> 
> See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages for more info here.

https://qanswer.space/questions/systemjs-is-loading-classes-that-are-extending-others
