### ISSUE TITLE
Multiple defines for anonymous module

### ISSUE THREAD

**Issue by ryanfitzer** [systemjs/systemjs#753]
I'm converting my [Example-RequireJS-jQuery-Project](https://github.com/ryanfitzer/Example-RequireJS-jQuery-Project) over to JSPM to get a better understanding of how SystemJS handles AMD. Everything works fine when I reassign the `require` and `define` globals:

```
window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;
```

As a test, I tried instead updating all the files to use `System.amdDefine` and `System.amdRequire` directly and get the error: `Multiple defines for anonymous module`. Any ideas on what I'm not understanding?

**Comment by guybedford** [comment]
`define` has special meaning inside of a module and will trigger the AMD detection. If you replace that with `System.amdDefine` it will no longer be detected as an AMD module so won't respect the AMD handling. If you really wanted to do this, you'd need to separately set meta to inform SystemJS that these are AMD modules via something like:

```javascript
System.config({
  meta: {
    'modules/*': { format: 'amd' }
  }
});
```

**Comment by ryanfitzer** [comment]
@guybedford Thanks for the explanation. My confusion stemmed from conflating AMD with RequireJS. That SystemJS treats a top-level `require` as a CommonJS module instead of an AMD module (using `require` as implemented by RequireJS) was unclear. Here is an example:

```js
require( [ 'path/to/runtime-config' ], function() {

    require( [ 'app/main' ], function( main ) {
            // initialize app now that config is loaded...
    });
});
````

When running this file, I would receive an error stating that `require` was undefined. Once I added the reassignment boilerplate:

```js
window.define = System.amdDefine;
window.require = window.requirejs = System.amdRequire;
```

everything worked as expected. I thought that changing everything over to `System.amd[Method]` would allow me to remove the boilerplate and use the same nested require-type solution. Your explanation make sense as to why that wouldn't work.

**Comment by guybedford** [comment]
@ryanfitzer it would actually work fine for `require -> System.amdRequire`, just not for `define -> System.amdDefine`.

**Comment by ca0v** [comment]
The Typescript transpiler can combine AMD modules into a single file.  How about adding support for named modules?

**Comment by guybedford** [comment]
@ca0v AMD named defines are supported by SystemJS.

**Comment by ca0v** [comment]
@guybedford Then it must be user error.  If I replace this:

    require(["app"], run => run())

with this:

    System.amdRequire(["app"], run =>  run())

System will attempt to load "app" (not app.js) instead of finding it already "defined" in run.js:

    define("app", ["require", ....

I load system.js last (I thought that might be the issue):

    <script src="bower_components/dojo/dojo.js"></script>
    <script src="built/run.js"></script>
    <script src="jspm_packages/system.js"></script>
