### ISSUE TITLE
Error message documentation

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#757]
We should have a page at `troubleshooting.md` that covers common errors and common causes.

In addition each error in SystemJS can then point to the relevant section of the error page.

**Comment by guybedford** [comment]
Work tracking in https://github.com/systemjs/systemjs/pull/771.

**Comment by dzearing** [comment]
Hey Guy - does this issue cover how errors should be handled in general? or, should i open separate issues? I can't find a lot of documentation on error handling and it's one area our team cares deeply about as we're evaluating switching over to jspm/system.js.

E.g. system.js tries to load something and it fails. Is there a global error handler that we can register with system.js to catch these and send them off to telemetry?

Also, fallbacks. If one CDN goes down, is there a way to provide a fallback? This is another way to deal with errors. Resource loading needs to be fullproof and errors need to be taken seriously.

**Comment by guybedford** [comment]
@dzearing this issue is specifically tracking the ability for error messages in SystemJS to provide links to documentation for further information.

To answer your questions - `System.import` will fail as a promise if a load fails. Typically an application should have a single top-level `System.import`, so the catch handler of that could be linked to a logging service. When promises in browsers support environment-level uncaught rejection handlers in future as I believe is the plan this would enable logging as well.

We don't currently provide a paths fallback mechanism - `<script src="x.js">` doesn't provide this mechanism either so I don't see this as a regression. The idea of CDN redundancy is interesting, but I'd be be more worried if using a CDN that doesn't already have this built in a foolproof way into its own infrastructure.
