### ISSUE TITLE
jspm is unable to write <package>@<version>.js with warning "main" not found in package.json when "main" exists.  

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#760]
I am trying to install the package overlookmotel/fs-extra-promise using jspm and I get the following warning:

```
warn Main entry point not found for npm:fs-extra-promise@0.2.0.
     Adjust this property in the package.json or with an override, setting "main": false if this is the intention.
```

The `main` field has been specified in the package.json (but it points to a folder with `index.js` inside) - see here: https://github.com/overlookmotel/fs-extra-promise/blob/master/package.json

I think jspm is unable to cope with folder being specified in `main` though it should be acceptable commonjs behaviour.

**Comment by guybedford** [comment]
Sure, thanks for posting, I've created an issue to track this at https://github.com/jspm/npm/issues/91.
