### ISSUE TITLE
Strange behaviour of system imports with/without DefaultJSExtensions

### ISSUE THREAD

**Issue by Chocoloper** [systemjs/systemjs#761]
Hey Guys,

## Short Explanation
I'm trying to experiment a little with Angular2 and SystemJS and encountered the problem that 
```html
System.config({
defaultJSExtensions: true
})
```
will make my application load the angular2 files a second time.

## Long Explanation:

First I'm already loading the angular2 files directly from github via `<script src=...>` inside my html like this:

```html
<head>
  <script src="https://rawgit.com/systemjs/systemjs/0.18.17/dist/system.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.36/angular2.dev.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.36/router.dev.js"></script>
  <script src="https://code.angularjs.org/2.0.0-alpha.36/http.dev.js"></script>
  <link rel="stylesheet" type="text/css" media="all" title="normal" href="stylesheets/index.css" />
</head>

<body>
  <app> Loading! </app>
  <script> System.import('scripts/app'); </script>
</body>
```

This pulls everything in the right way and also pulls `script/app.js` like it should do but app.js tries to import shop.js. To do this my app.ts looks like this(shortened version):
```typescript
import { Component, View, bootstrap, bind} from 'angular2/angular2';
import { ROUTER_BINDINGS, LocationStrategy, HashLocationStrategy, ....} from 'angular2/router';
import { Shop } from './shop';

@Component({selector: 'app'})
@View({ template: `...`, directives: [...] })
@RouteConfig([ { path: '/', redirectTo: '/shop' }, { path: '/shop', component: Shop, as: 'shop'} ])
export class App {
  name: String[];
  constructor() { this.name = "Test-Web-App"; }
}
bootstrap(App, [ROUTER_BINDINGS, bind(LocationStrategy).toClass(HashLocationStrategy)]);
```

This fails because it tries to reach `http://localhost/scripts/shop` instead of `http://localhost/scripts/shop.js`. Now adding 
```html
System.config({
defaultJSExtensions: true
})
```
to my `index.html` will lead to `http://localhost/scripts/shop.js` loading in the expected way but this also leads to my app.js and shop.js trying to load their angular2 imports from my local server. So I get the following errors:
```html
GET http://192.168.0.40:8080/angular2/router.js 404 (Not Found)
GET http://192.168.0.40:8080/angular2/angular2.js 404 (Not Found)
GET http://192.168.0.40:8080/angular2/angular2.js 404 (Not Found)
```

I looked through your documentation but i found no option to further manipulate this behaviour.

**Comment by Chocoloper** [comment]
Also note that the `<script> System.import('scripts/app'); </script>` works independent of the defaultJSExtensions.

**Comment by guybedford** [comment]
Yes name matching with existing bundles is error prone like this. You can force this to match up by adding:

```javascript
System.config({
  packages: {
    angular: { defaultExtension: false }
  }
});
```

Note I would just suggest using `defaultJSExtensions: false` and using `import './shop.js'` as js extensions in module names is preferable.

I've also made a note along these lines in https://github.com/systemjs/systemjs/issues/756#issuecomment-137958077.

**Comment by Chocoloper** [comment]
Hey I made a repository to test it. You can find it here with instructions:
https://github.com/Chocoloper/Systemjs-issue-webapp

This one is the non-working example! I tried to change it to ´import './shop.js'` in `./public/scripts/app.ts` like you said and the example worked but I don't really want to add the js ending in my typescript files because the typescript error checker always cries error. In my opinion it's not suitable for my use-case.

Also I still think it's strange that `DefaultJSExtension: true`will make `app.js` and `shop.js` reload the angular packages which are already loaded inside `index.html`

**Comment by Chocoloper** [comment]
ATM I'm using `import { Shop } from 'scripts/shop';` without any `System.config`. The transpiler is still crying error but now it's pulling `ET http://192.168.0.40:8080/scripts/shop`. Shouldn't the default config of systemjs 0.18.17 not append .js in this case?

**Comment by guybedford** [comment]
SystemJS doesn't append extensions by default. Did you try the `defaultExtension: false` angular package fix I suggested above?

**Comment by todoubaba** [comment]
See https://github.com/systemjs/systemjs/issues/728，put `System.config` before angular2.

**Comment by guybedford** [comment]
Just let me know if you need further help here.

**Comment by Chocoloper** [comment]
@todoubaba take a look at my index.html: https://github.com/Chocoloper/Systemjs-issue-webapp/blob/master/views/index.html . Systemjs is loaded before angular2. 

@guybedford 
The reason it didn't worked previously was that I put the System.config into the `<script>` part after loading systemjs and angular2. I know have putted it directly between systemjs and angular and now everything works fine!

Only one thing left:
You said that SystemJS doesn't append by default. Does this only apply for imports with leading dots or also without leading dots?
Example: 

- No System.config at all --> Default Case is used
- Two files available:
  * `http://localhost:8080/scripts/compA.js`
  * `http://localhost:8080/scripts/compB.js`
- CompA tries to load CompB with following lines:
  * Case a) `import { CompB } from 'scripts/compB';`
  * Case b) `import { CompB } from './compB';`

As far as I understood you, both should fail since Systemjs doesn't append `.js` in any of both cases but case a appends `.js` anyway while case b fails.

**Comment by guybedford** [comment]
@Chocoloper yes both would fail in this example with no `defaultJSExtensions`, unless `scripts/compB` was defined via an alternative method like a bundle operation.

**Comment by Chocoloper** [comment]
@guybedford 
Then we have an issue I think. Case A worked for me in 0.18.17.
Should I provide an mini-example for you to test it so you don't waste any more time if the failure was on my side?

**Comment by guybedford** [comment]
If you can reduce the problem to a simple case I'll gladly look at it. It's important to make sure you can fully isolate it though.

**Comment by Chocoloper** [comment]
NVM. Fault was on my side. 

When testing this I used `<!-- -->` instead of `//` to comment the System.config out. The default case seems to work fine!

The initial reason for this issue is also resolved as I just had to load the system.config before the angular packages. Maybe you should put that also in the docu so that others won't open issues on that!

Thanks for your great help!

**Comment by hemantjadon** [comment]
I included SystemJS before angular-2-polyfills and it worked.
```html
<!-- 1. Load libraries -->
		<!-- IE required polyfills, in this exact order -->
		<script src={% static "node_modules/es6-shim/es6-shim.min.js" %}></script>
		<script src={% static "node_modules/systemjs/dist/system-polyfills.js" %}></script>
		<script src={% static "node_modules/angular2/es6/dev/src/testing/shims_for_IE.js" %}></script>
		
		<!-- 2. Configure SystemJS -->
		<script src={% static "node_modules/systemjs/dist/system.src.js" %}></script>
		<script>
			System.config({
				defaultJSExtensions: true,
			});
			
			System.import('/static/ng-main/app/js/main')
				.then(null, console.error.bind(console));
		</script>
		
		<!-- 3. Load Angular Libraries-->
		<script src={% static "node_modules/angular2/bundles/angular2-polyfills.js" %}></script>
		<script src={% static "node_modules/rxjs/bundles/Rx.js" %}></script>
		<script src={% static "node_modules/angular2/bundles/angular2.dev.js" %}></script>
		<script src={% static "node_modules/angular2/bundles/router.dev.js" %}></script>
```
