### ISSUE TITLE
Accept header doesn't conform to spec

### ISSUE THREAD

**Issue by giovannicandido** [systemjs/systemjs#763]
The accept header in requests do not conform to the spec: http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

The consequence is that strict http servers and frameworks like Java Spring Framework, do not accept this header and refuse to serve the request, so the entire systemjs stop working.

The solution is pretty simple
Change
```
'application/x-es-module */*'
```
to 
```
'application/x-es-module, */*'
```

I think that is a typo mistake, but that "," can cause the entire system to stop working. So is better to not  hardcode this everywhere in the future

**Comment by guybedford** [comment]
Many thanks. Fixed in https://github.com/ModuleLoader/es6-module-loader/commit/16834b75e0a0cd80236ff2c2f74464e5b46f2b91.
