### ISSUE TITLE
__main__.js 404 (Not Found) error

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#765]
I was playing with the [WebCola](https://github.com/tgdwyer/WebCola), and saw an error that is attached.

![es6](https://cloud.githubusercontent.com/assets/12233474/9706976/799eb5b0-54be-11e5-8dce-1fd7572b2dbe.PNG)

**Comment by guybedford** [comment]
@varghesep this is due to WebCola not using standard CommonJS module code. We can tell jspm to load this file as if it were a global via `jspm install npm:webcola -o "{shim:{'WebCola/src/rbtree':{}}}"`, which may help here, but you will likely hit other issues even after that.

**Comment by guybedford** [comment]
Please post an issue to the jspm registry at https://github.com/jspm/registry/issues for further help configuring here.
