### ISSUE TITLE
How to write a plugin for bundling?

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#768]
I am the author of [plugin-sass](https://github.com/screendriver/plugin-sass) and am stuck in the bundling process.

My plugin depends on [sass.js](https://github.com/medialize/sass.js) so you can require / import SASS styles at **runtime** in the browser. The SASS styles are compiled to CSS and [injected](https://github.com/screendriver/plugin-sass/blob/master/src/sass.js#L22) to the HTML file as an inline style in the head at **runtime** in the browser.

So far so good. At development and test time this works great because I don't have to compile or build something locally first. But now I want to make production ready code and make a [bundle](https://github.com/jspm/jspm-cli/wiki/Production-Workflows). This should be very small and run very fast. So including the **big** sass.js library and **heavy** compile SASS to CSS in the browser at **runtime** is not an option. What I want is to compile SASS to CSS at **bundling time** local on the filesystem and only include that compiled CSS in the final bundle so that there is no need for a dependency to sass.js or something else. Only the CSS file and the injection to the HTML file should occur.

I've read the documentation about [creating-plugins](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md) and [production workflows](https://github.com/jspm/jspm-cli/wiki/Production-Workflows) many many times but I don't get it. Is there a hook or something that I can use to accomplish this? At the moment I am using the `fetch` hook that will be called at runtime. I found the [SystemJS build tool](https://github.com/systemjs/builder) but I don't understand exactly how to use it and if this is the right one for me.

Any help would be appreciated.

See also https://github.com/screendriver/plugin-sass/issues/3

**Comment by Mosho1** [comment]
Adding a translate hook should do the trick. From [creating-plugins](https://github.com/systemjs/systemjs/blob/master/docs/creating-plugins.md):

> When building via SystemJS Builder, plugins that use the translate hook will be inlined into the bundle automatically.

> In this way, the bundle file becomes independent of the plugin loader and resource.

**Comment by screendriver** [comment]
Unfortunately this does not help much. Morevoer I believe that this is not the solution for my problem.
But thank you for trying to help me :+1:

**Comment by guybedford** [comment]
Can I close this now?

**Comment by screendriver** [comment]
Yes, it can be closed

**Comment by screendriver** [comment]
But a documentation about that would be really really helpful :wink:

**Comment by cjolif** [comment]
:+1: on better document on this.

**Comment by guybedford** [comment]
Help with documentation is always welcome either with blog posts or PRs to the docs here. The first priority remains project stability, after which documentation will become the focus, so help in the mean time is very much appreciated.

**Comment by screendriver** [comment]
Yes that's true. I would do that but I don't know exactly which API's are present and which one can be used (and how).

**Comment by guybedford** [comment]
It may help to look at the other plugins as examples, eg https://github.com/systemjs/plugin-css and https://github.com/systemjs/plugin-babel.
