### ISSUE TITLE
metaDeps.concat is not a function

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#769]
If I have the following meta:
```
meta: {
  "*": {
    "deps": ["jquery"]
  },
  "someModule": {
    "deps": ["underscore"]
  }
}
```
Seems like when it gets to `someModule`, the metaDeps becomes an object thus `metaDeps.concat` is not an function.
I place `console.log(metaDeps)` at line 2670 of `system.src.js`:
```
      if (load.metadata.format == 'cjs') {
        var metaDeps = load.metadata.deps || [];
        console.log(metaDeps);
        load.metadata.deps = metaDeps.concat(getCJSDeps(load.source));
```
I'll get:
```
LOG: ['jquery']
LOG: Object(0: 'jquery')
Error: `undefined` is not a function (evaluating 'metaDeps.concat(getCJSDeps(load.source))')
```
using systemJS 0.18.17

**Comment by guybedford** [comment]
I tried to replicate this by running:

```javascript
System.config({ '*': { deps: ['jquery'] }, 'someModule.js': { deps: ['underscore'] } });
System.import('someModule.js');
```

where `someModule.js` is CommonJS, But it definitely is making a request to both `jquery` and `underscore` for me. Which version of SystemJS are you running here?

**Comment by unional** [comment]
I'm using 0.18.17.
I'm running it under karma.  I verified that it happens on both `System.import(...)` and `import "someModule.js"`

**Comment by guybedford** [comment]
@unional can you share a reduced test case, or get my test case above to break?

**Comment by unional** [comment]
Found out the issue is in `proto.js`, line 98: `val instanceof Array && a[p] instanceof Array`.  For some reasons running in karma, they return false in both count:
```
        console.log(val, a[p]);
        console.log(val instanceof Array, a[p] instanceof Array);
```

produces:
```
 LOG: ['styles/theme-pan-blue/theme-pan-blue-debug.js'], ['jquery', 'Promise']
 LOG: false, false
```

```

**Comment by unional** [comment]
Further check, the `deps` is not created as an Array thus it fail `val instanceof Array`.
I manually override `b.deps = ['jquery', 'Promise'];`, then `b.deps instanceof Array` is `true`. Before the override, it is `false`.

**Comment by unional** [comment]
Also, notice there is a typo in `meta.js`:
`bestDetph = depth;`

**Comment by unional** [comment]
Found out it is more likely `karma` or `karma-systemjs` issue.

**Comment by guybedford** [comment]
Yes that seems more likely. Thanks for spotting the typo and let me know if you need any more assistance here.
