### ISSUE TITLE
ReferenceError: 'System' is undefined on IE11 (SystemJS v0.18.17)

### ISSUE THREAD

**Issue by davidecantoni** [systemjs/systemjs#770]
On IE11 the fallback to the polyfill doesn't seems to work.
Randomly it throws errors that System is undefined.
The system-polyfills.js file is at the same place where the system is => it works well on IE9.

Here is the code that i use:

```
<script src="system.src.js"></script>
<script src="app.js"></script> //this file includes the config.js file, bundle.js and importer, see below:
```

The content of app.js looks like this:
```
<script>
    System.config({
        baseURL: "/",
        defaultJSExtensions: true,
        transpiler: "none",
        paths: {
            "github:*": "jspm_packages/github/*",
            "bower/*": "bower_components/*",
            "modules/*": "js/src/modules/*",
            "plugins/*": "js/src/plugins/*",
            "vendor/*": "js/src/vendor_local/*"
        },
        bundles: {
            "js/dist/bundle-detail-page.min.js": [
                "modules/detail-page",
                "plugins/pf-report-property",
                "plugins/slideshow",
                "bower/slick.js/slick/slick"
            ]
        },

        map: {
            "blazy": "bower/blazy/blazy.js",
            "bloodhound": "vendor/bloodhound.js",
            "cookie": "bower/jquery.cookie/jquery.cookie.js",
            "detectmobile": "vendor/detectmobilebrowsers.js",
            "form": "vendor/jquery.form.js",
            "format": "bower/number-format.js/lib/format.min.js",
            "h5validate": "bower/h5validate/h5validate.js",
            "hoverIntent": "bower/jquery-hoverintent/jquery.hoverIntent.js",
            "jquery": "vendor/jquery-global.js",
            "mediator": "modules/mediator.js",
            "mediatorlib": "bower/mediator/mediator.min.js",
            "money": "bower/money.js/money.js",
            "ractive": "bower/ractive/ractive-legacy",
            "readmore": "vendor/readmore.js",
            "replace": "plugins/pf-replace-options",
            "slick": "bower/slick.js/slick/slick.js",
            "smartbanner": "bower/jquery.smartbanner/jquery.smartbanner.js",
            "sticky": "vendor/jquery.sticky.js",
            "tooltipster": "bower/tooltipster/js/jquery.tooltipster.js",
            "typeahead": "vendor/typeahead.jquery.js",
            "underscore": "bower/underscore/underscore.js"
        }
    });
    // main bundle file (too long thats why i didn't copy it)
    System['import']('//code.jquery.com/jquery-1.11.3.min.js').then(function() {
        System['import']("js/src/main.js");

        // load detail page
        if ($('#property-frontend-page-page').length) {
            System['import']("modules/detail-page");
        }
    });
</script>
```

I assume that on IE11 the script is parsing both files and while file system.src.js is downloading the polyfill file app.js is throwing an error because System is undefined.
Can this be the case?

**Comment by guybedford** [comment]
See the comment in https://github.com/systemjs/systemjs/issues/517#issuecomment-139513928.

**Comment by guybedford** [comment]
(my guess is that the fact that it works in IE9 is likely a bug in IE9's execution semantics)

**Comment by guybedford** [comment]
Let me know if you're still having issues here.

**Comment by davidecantoni** [comment]
Hello @guybedford 
I created a demo here: https://github.com/davidecantoni/systemjs-ie
Just download and run
```
npm install
gulp
```

As you can see afterwards the first version, including the files separately works fine:
https://github.com/davidecantoni/systemjs-ie/blob/master/public/index.html#L11-L27

But this is kind of an overhead, especially regarding performance optimisation.

That's why i was concatenating the files as you can see here:
https://github.com/davidecantoni/systemjs-ie/blob/master/public/index.html#L29-L30

Unfortunately this is causing the above mentioned error:
'''
'System' is undefined
'''  
The reason is that System gets initialised before the polyfill is downloaded.

Any thoughts?

**Comment by guybedford** [comment]
Yes, SystemJS can't be concatenated with code that assumes `System` as it won't define `System` until the polyfills have been loaded. Either don't concatenate System with code that relies on `System`, or include the polyfills file separately via IE conditional comments or something like that.

**Comment by stephanbureau** [comment]
Hi, I know it is kind of an old thread and maybe related to jspm as well but I managed to make it work with `IE11` simply concatenating `system-polyfill.js` in a separate bundle loaded first.
Hope that helps someone.

**Comment by Sri276286** [comment]
Hi,

Can anyone tell me please what is the solution for it at this point of time.
