### ISSUE TITLE
System.paths unexpected behaviour (0.18.17)

### ISSUE THREAD

**Issue by sergei-maertens** [systemjs/systemjs#772]
Versions: 
* jspm 0.16.2
* systemjs 0.18.17
* babel-core 5.8.23

`config.js`

```
System.config({
  baseURL: "/static/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "*": "*",
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "URIjs": "npm:URIjs@1.16.0",
    "babel": "npm:babel-core@5.8.23",
    "babel-runtime": "npm:babel-runtime@5.8.20",
    "bootstrap": "github:twbs/bootstrap@3.3.5",
    "core-js": "npm:core-js@1.1.4",
    "css": "github:systemjs/plugin-css@0.1.16",
    "handlebars": "github:components/handlebars.js@2.0.0",
    "jquery": "github:components/jquery@2.1.4",
    "jquery-ui": "github:components/jqueryui@1.11.4",
    "perfect-scrollbar": "npm:perfect-scrollbar@0.6.4",
    "q": "npm:q@2.0.3",
    "string.prototype.startswith": "npm:string.prototype.startswith@0.2.0",
    "typeahead": "github:twitter/typeahead.js@0.11.1",
    "github:components/jqueryui@1.11.4": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.4"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:twbs/bootstrap@3.3.5": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "github:twitter/typeahead.js@0.11.1": {
      "jquery": "github:components/jquery@2.1.4"
    },
    "npm:URIjs@1.16.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:asap@2.0.3": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:babel-runtime@5.8.20": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:core-js@1.1.4": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:domain-browser@1.1.4": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:q@2.0.3": {
      "asap": "npm:asap@2.0.3",
      "pop-iterate": "npm:pop-iterate@1.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "weak-map": "npm:weak-map@1.0.5"
    }
  }
});
```

Observed behaviour:

After updating jspm from 0.15.x to 0.16.2 (which included the 0.18.17 systemjs version), in `config.js`, `paths` got 'reset'.

```
paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
```

I'm running in local mode because I'm often developing offline, so my local files were no longer loading. This was fixed by adding the wildcard again:

```
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*",
    "*": "*"
  },
```

Note that the wildcard was added at the end. In the previous version the wildcard came first too, but I thought otherwise. Anyway, with the wildcard at the bottom babel no longer loaded, because the loader was trying to load `npm:babel-core@5.8.23`, with `npm` as protocol, and not peforming the `npm:*` mapping. This was fixed by moving the complete wildcard to be first in the `paths` configuration, but unexpexcted for me. As far as I know objects have no inherent ordering, so I'd expect the ordering not to matter. Also, the docs state that the most specific entry will be applied, which clearly didn't happen either.

I debugged into system.src.js, around line `1082`:

```
  SystemLoader.prototype.fetch = function(load) {
    return new Promise(function(resolve, reject) {
      fetchTextFromURL(load.address, resolve, reject);
    });
  };
```
I noticed that load.address was not a `http*://` url, but was just the `npm:...` 'url'.

**Comment by guybedford** [comment]
Is there a reason you need to have the `"*": "*"` path mapping here?

Most specific wildcard is currently only determined by `/` depth, so that `github:*` and `*` are equal. In future better rules could be used here certainly.

Also we've given preference to the last good match of equal specificity, which I only recently changed to be the first good match of equal specificity.

Again, since only one wildcard should ever match, the `*` is sort of acting as an exit path, skipping the others which are important to have, which is the real issue here though.

**Comment by sergei-maertens** [comment]
It's very much possible that I have a misconfiguration somewhere, but without the `"*": "*"`path mapping my modules are 404-ing when I try to import them.

Case in point is https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/src/brouwers/kits/templates/kits/widgets.html#L91

* all static files are served under http://localhost:8000/static/
* the actual sources are in src/brouwers/<appname>/static/<module>, serving them under /static/ is done by Django
* the cdn SystemJS is included with script tag, falling back to the local installed version in offline development: https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/src/templates/sniplates/js.html
* at the bottom, systemjs_import generates `<script>System.import('kits/js/modelkit.widget');</script>`
* without the mapping, SystemJS tries to load https://registry.jspm.io/kits/js/modelkit.widget.js, but only if SystemJS was loaded from the CDN (so when developing with internet connection).

Relevant jspm related files:
https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/src/static/config.js
https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/package.json

Now that I tried every step to make this comment, this is feeling awfully close to a misconfiguration, but I have no idea where to look.

**Comment by guybedford** [comment]
Ah right, yes you would need a `"*": "*"` rule to override the default `"*"` rule in the CDN SystemJS which uses the jspm registry by default.

So if you manually move the `"*": "*"` rule to the top this config then works fine I assume?

**Comment by sergei-maertens** [comment]
Correct

**Comment by guybedford** [comment]
The upgrade path would actually have deleted an entry of `"*": "*.js"` which would have been used previously. And we don't currently generate the `"*": "*"` rule as the CDN-mode in jspm is currently not being prioritised. So I think this is best marked as the CDN workflow currently being lacking at the moment. I'm working hard to polish this workflow up again though for 0.17.

**Comment by sergei-maertens** [comment]
Indeed, I noticed it got deleted. I finally figured out what the issue was,
so I can continue.
