### ISSUE TITLE
Can I import ajax module from jquery only?

### ISSUE THREAD

**Issue by f15gdsy** [systemjs/systemjs#776]
I saw a [blog post](http://developer.telerik.com/featured/jquery-using-only-what-you-need/) that we can load individual modules in jquery with RequireJS.
Can I do that with systemjs too?
Thanks!

**Comment by guybedford** [comment]
@f15gdsy yes this same approach should work with SystemJS. I have tested it in the past as well myself. The configuration may take some consideration though to make it work out. I'd suggest using the SystemJS package configuration for jQuery to set the `sizzle` dependency etc something like:

```javascript
System.config({
  packages: {
    'path/to/jquery/src': {
      defaultExtension: 'js',
      main: '...',
      map:{ 
        'sizzle': './sizzle/dist/sizzle'
      }
    }
  }
});
```

**Comment by guybedford** [comment]
Let me know if you need any further help with this.
