### ISSUE TITLE
How to import cordova plugins?

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#777]
I am developing a [Cordova](http://cordova.apache.org) based application that runs on mobile devices like Android and iOS. Cordova support [plugins](http://plugins.cordova.io/npm/index.html) that can access native device functions like the camera or contacts. For example you can install a plugin that download files from the internet to the local storage of the device:

```sh
$ cordova plugin add cordova-plugin-file-transfer
```

After that you have to add an event listener for the [deviceready](http://cordova.apache.org/docs/en/5.0.0/cordova_events_events.md.html#deviceready) event in your `main.js`. When the event callback is called, every native device plugin is loaded and can be used from JavaScript.

```js
document.addEventListener('deviceready', () => {
  console.info(FileTransfer == null); // false
}, false);
```

Unfortunately most of the plugins, like the `cordova-plugin-file-transfer` mentioned above, are accessible over a magic global variable like `FileTransfer`. Some of them hook into the `window` object like [SQLite Storage](https://github.com/litehelpers/Cordova-sqlite-storage) (`window.sqlitePlugin.openDatabase()`). This is very ugly and not very clear. I want to `import` all my dependencies in the ES2015 way.

Is there a way I can make this happen with some flags in my `config.js` [meta](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta) property or something else?

**Comment by guybedford** [comment]
You could set up a module that wraps the cordova API as exports something like:

cordova.js
```javascript
export var FileTransfer;
export function deviceready() {
  FileTransfer = window.FileTransfer;
}
```

I guess its really up to what pattern you'd prefer writing with here.

**Comment by screendriver** [comment]
Hi,
thank you. I already did something similar. I thought there is maybe some magic mechanism in SystemJS that makes importing such global variables possible.

**Comment by guybedford** [comment]
Sure, yes global module detection wouldn't apply if these globals exist on page load.
