### ISSUE TITLE
Babel plugins

### ISSUE THREAD

**Issue by OliverJAsh** [systemjs/systemjs#779]
Babel has the concept of plugins, e.g. https://github.com/substack/babel-plugin-jsx-factory.

Ideally these could be configured using `babelOptions`:

```
babelOptions: { plugins: ['babel-plugin-jsx-factory'] }
```

However, I don't think SystemJS will know where to find the plugin on disk.

Do you have any ideas how we might support these? Perhaps the plugins could be installed using jspm and `babelOptions.plugins` will look for the plugin in `System.map`.

**Comment by guybedford** [comment]
Yes exactly, the plan for this is to support plugins as module names, which are loaded before running Babel transpilation.

**Comment by veggiemonk** [comment]
Hi @OliverJAsh, Hi @guybedford,

Do you know **any way** to import babel plugins? 
Even a dirty hack would do... maybe the coding necessary for that is not so big. 
I really don't want to rely on another watch/transpiler script when there is SystemJS...
If you could point me in the right direction, it would be very much appreciated.

Thanks a lot!

**Comment by guybedford** [comment]
@veggiemonk this is being worked on in https://github.com/systemjs/plugin-babel, but there is no release date set yet.
