### ISSUE TITLE
How to bundle dynamic dependencies?

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#781]
I am creating a [bundle](https://github.com/jspm/jspm-cli/blob/master/docs/production-workflows.md#creating-a-dependency-cache) for my production code:

```sh
$ jspm bundle main.js bundle.js
```

`main.js` has a static dependency to `foo.js` and a dynamic dependency to `bar.js`

```js
import foo from './foo.js';
// Do something
const myCallback = () => {
  System.import('./bar.js').then(bar => {
    // Do something
  });
};
```

Unfortunately `./bar.js` don't get included because it's dynamic. I read the [docs](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md) about `config.js` but I don't get it to work. Do I have to add `./bar.js` to [bundle](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#bundle), [debCache](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#depcache) or [meta](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta)? I tried all three but dind't get it working (my `bundle.js` always contains only `System.register('./foo.js', [], function (_export) {...`)

**Comment by guybedford** [comment]
Yes you need to manually run `jspm bundle main.js + bar.js` here.

Tracking of dynamic requires is in https://github.com/systemjs/builder/issues/75.

**Comment by screendriver** [comment]
Ok. So there is no setting in `config.js` or `package.json` for that?
Can this achieved with [SystemJS Builder](https://github.com/systemjs/builder) as well? Like

```js
new Builder().build('local/module.js', 'local/foo.js', 'local/bar.js', 'outfile.js');
```
