### ISSUE TITLE
Angular2, SystemJS not working in Chrome App

### ISSUE THREAD

**Issue by modohash** [systemjs/systemjs#782]
Hi,

First off, SystemJS is awesome:) I've been playing around with Angular2, Typescript and Chrome Web Apps. I'm running into a CSP issue:

Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self' blob: filesystem: chrome-extension-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-rAO4dXmetwgH9x6LGhP9nrsV9lBf5QHN_gR5YcdKorg='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

It seems to be having an issue with: head.appendChild(script);

Line 1241, system.src.js

The version of SystemJS is 18.17. I tried setting the CSP in the manifest but apparently that field isn't supported by web apps, only extensions. I can see code dealing with extensions in the SystemJS source, but nothing to do with apps.

Any ideas how I might fix this? I can provide an example if needed.

Cheers

**Comment by guybedford** [comment]
Hey, yes this should be supported as of a recent version via the `nonce` meta option. This is documented at https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#meta.

So I believe setting:

```javascript
System.config({
  meta: {
    '*': {
      nonce: 'sha256-...' // or the nonce
    }
  }
});
```

Should work with the CSP-compatibility.

That said, this feature hasn't been thoroughly tested, so please let me know if you have any issues with that at all.

**Comment by modohash** [comment]
Great, I'll have a go and let you know if I succeed or have issues. Thanks for your help.

**Comment by modohash** [comment]
I've added in the recommended settings, just replacing the nonce with the real hash. I'm still getting the same error. Chrome extensions support the "content_security_policy" setting in the manifest:

https://developer.chrome.com/extensions/manifest

Chrome apps don't support this setting. Any advice would be welcome! I'd be surprised if someone hasn't been able to get this to work at some point.

**Comment by modohash** [comment]
If I where to bundle all the modules I'm using with SystemJS builder and then use the CSP version would that fix these issues?

**Comment by guybedford** [comment]
Yes exactly that should avoid the issues here. You can also use an SFX bundle as well if you don't need dynamic loading during runtime.

**Comment by modohash** [comment]
Alrighty, I'll try that later and hopefully everything will be fine. Thanks.

**Comment by guybedford** [comment]
Just let me know if you need further help here.

**Comment by alisabzevari** [comment]
Did anyone solved this problem?
the nonce solution didn't work because system.js loads before config.js
