### ISSUE TITLE
Can not set properly the baseURL inside script tag

### ISSUE THREAD

**Issue by DavidGangel** [systemjs/systemjs#785]
Hi,

I have a trouble with setting the basURL config property inside a script tag in HTML.
SystemJS v0.18.17
HTML:
https://gist.github.com/DavidGangel/1b1ca4ef39ea37e5fc9d

It just ignores it. The URL where it tries to download the bootstrap.js does not contains the skins path.

**Comment by guybedford** [comment]
The config property is case sensitive - try `baseURL`.

**Comment by DavidGangel** [comment]
That worked.
Thank you!
