### ISSUE TITLE
systemJSConstructor is not getting called when extending System.constructor and transpile with Babel

### ISSUE THREAD

**Issue by katrotz** [systemjs/systemjs#786]
Trying to extend the System.constructor in a ES2015 class syntax and transpile with Babel the `SystemJSLoader` is not getting invoked.
 
The issue is only reproducible with Babel transpiler, Traceur works fine. The discrepancy hides in the way `super` is implemented:

*Babel*: `_get(Object.getPrototypeOf(SubClass.prototype), 'constructor', this).call(this);` which returns the constructor of SuperClass prototype
*Traceur*: `$traceurRuntime.superConstructor(SubClass).call(this);` which returns the SuperClass

**Note**: Related issue on babel side: https://github.com/babel/babel/issues/2048

**Comment by guybedford** [comment]
Released in 0.19.0.
