### ISSUE TITLE
Cannot import script in a folder with package.json.

### ISSUE THREAD

**Issue by f15gdsy** [systemjs/systemjs#789]
I have such a file structure:

```
- Components
  - App.js
  - ComponentA
    - ComponentA.js
    - ComponentA.css
    - package.json
```

When I try 
```javascript
import ComponentA from './ComponentA';
```
in App.js, it interprets './ComponentA' as js file.

I found that I can set defaultJSExtensions to turn off the default js thing, but it would lead to some npm packages fail to load.

Any suggestions?

**Comment by screendriver** [comment]
You can't import directories, only modules. You have to write

```js
import ComponentA from './ComponentA/ComponentA';
```
Import paths are always relative to your current script.

**Comment by guybedford** [comment]
You can use package configuration to set the main here:

```javascript
System.config({
  packages: {
    'Components/ComponentA': {
      main: 'ComponentA.js'
    }
  }
});
```

This sort of manual package configuration is necessary to make npm packages work correctly with SystemJS. Just let me know if you have any more questions.
