### ISSUE TITLE
System.get() does not return module

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#791]
I am writing unit tests for my modules and mock all of their dependencies with [Sinon.js](http://sinonjs.org):

```js
let oboe;

before(() => {
  oboe = System.get(System.normalizeSync('oboe'));
  System.set(System.normalizeSync('oboe'), System.newModule({
    default: sinon.spy()
  });
});
```

in my `after()` I want to reset the mock to the original implementation to prevent side effects to other tests

```js
after(() => {
  System.set(System.normalizeSync('oboe'), oboe);
});
```

Unfortunately this does not work because `System.get(System.normalizeSync('oboe'));` does return undefined. If I make a `System.import('oboe')` instead of `System.get()` it works though.

**Comment by guybedford** [comment]
Is this the same issue fixed as in https://github.com/systemjs/systemjs/issues/788?

**Comment by screendriver** [comment]
Unfortunately not. `System.has()` does return false as well. But if you load it first with `System.import()` it does work:

```js
let has = System.has(System.normalizeSync('oboe')); // false
System.import('oboe').then(module => {
  has = System.has(System.normalizeSync('oboe')); // true
});
```

**Comment by guybedford** [comment]
@screendriver yes the module will only exist in the loader registry if it has already been imported. Perhaps you just want to be using `System.delete(System.normalizeSync('oboe'))` here to allow the standard behaviour again?

**Comment by screendriver** [comment]
Thank you very much! `System.delete(System.normalizeSync('oboe'))` did the trick! :sunglasses:
