### ISSUE TITLE
is `plugin-typescript` still needed?

### ISSUE THREAD

**Issue by unional** [systemjs/systemjs#793]
Hi,

I have been using `plugin-typescript` with `systemjs` to load and transpile `*.ts` file, i.e., I have the following in my `config.js`:
```
{
  transpiler: "typescript",
  typescriptOptions: {
    noImplicitAny: false
  },
  meta: {
      "*.ts": {
          "loader": "ts"
      },
  },
  map: {
    "ts": "github:frankwallis/plugin-typescript@2.0.12",
    ....
  }
}
```

Is the `meta` section and/or `plugin-typescript` still needed as now `systemjs` supports typescript as transplier "natively"?

**Comment by guybedford** [comment]
I'd advise people to use the plugin over the internal support as the plugin supports more features like reading definition files.
