### ISSUE TITLE
Loading github fork + dependencies

### ISSUE THREAD

**Issue by MeoMix** [systemjs/systemjs#796]
Heya,

A couple of times I've wanted to use a fork of a given module rather than whatever's in the registry. However, when I do an install with the "github:" prefix -- it doesn't pull in dependencies.

Is there an easy way to have my cake and eat it too? Or do I need to manually install deps?

**Comment by guybedford** [comment]
A warning for this exact reason will show up in the console when you install something from GitHub. The text there explicitly mentions how to do this.

**Comment by guybedford** [comment]
Did you work this out?
