### ISSUE TITLE
One off locations?

### ISSUE THREAD

**Issue by nyarly** [systemjs/systemjs#798]
Is it possible (even permissible by the ES6 modules spec...) to change how modules are located on a case-by-case basis?

What I'm thinking about is for testing purposes, something like:

```
System.special_import('ClassUnderTest from "../src/classUnderTest.js"', {"some/dep.js" => TestImplementationOfDep})
```
(hopefully that's clear.)

It may not be within systemjs's scope to handle the actual mechanism for that, but do the loading hooks allow for it?

**Comment by guybedford** [comment]
There are a number of ways to alter resolution based on context including contextual map configuration, custom map configuration, and conditional loading.

The point is though, that once in the module registry, that resolution is set. That is if module a resolves to module b, it must always resolve to that module within the current environment and parent module load. If you want the load to be parent-specific, that is contextual map. If you want the load to be environment-specific, that is custom map or conditional loading.

**Comment by nyarly** [comment]
Since adding this, I was looking at https://github.com/systemjs/systemjs/issues/736#issuecomment-137699003 - it seems like using System.construct to build an isolated loader, configuring it - even .set()-ing dummy modules and then System.import()-ing from it might do what I want.

Is that worth trying, in terms of doing unit tests?

**Comment by guybedford** [comment]
Yes that's the most advisable workflow for unit testing currently.
