### ISSUE TITLE
Global Namespace Pollution

### ISSUE THREAD

**Issue by drieks** [systemjs/systemjs#800]
Hello,

there is a Bug in `lib/global-eval.js`. The Methods `preExec` / `postExec` are always called as a pair, but `preExec` they can be called again, before postExec.

I have created a patch for this, please have a look at the PR.

**Comment by guybedford** [comment]
This is not actually fully resolved yet as script loading would still potentially do global polluting. See https://github.com/systemjs/systemjs/blob/master/lib/scriptLoader.js#L84 where the same issue applies.

**Comment by guybedford** [comment]
Since interleaving only happens for CommonJS the above script edge case is pretty rare. We can rather come back to this if it remains an issue.

**Comment by drieks** [comment]
Hi, I have packed the source files using systemjs-builder, now I have the same problem.

In the new File there are a lot of System.get(), System.register() and System.registerDynamic() calls.

It is possible to wrap the execution of the bundled file so that system js can introduce a System instance  pointing to the correct loader inside of an closure? The global System reference should then be resolved using the closure.

**Comment by guybedford** [comment]
Are you using a normal bundle or SFX bundle? If using a normal bundle, it contains `System.register` statements which need to resolve against the loader you want to use by being loaded from that loader. Where exactly are you getting the incorrect references? Do you have dynamic `System.import` statements in the code for example?

**Comment by guybedford** [comment]
This is a good point - I've added this functionality in https://github.com/systemjs/builder/commit/a47503c017042f2b4c10a4c98a61058612d38365.

**Comment by guybedford** [comment]
@drieks due to https://github.com/systemjs/systemjs/issues/803 we can't scope System for script-based execution so I've reverted the builder wrapping and instead handled the wrapping here dynamically in the loader with https://github.com/systemjs/systemjs/commit/1ba9c6b1579a893304b7ef863032fb6275997bca as we are restricted to the global execution case. That should resolve those build issues for you now.

**Comment by guybedford** [comment]
Released in 0.19.1.

**Comment by guybedford** [comment]
Thanks again for your help here @drieks.
