### ISSUE TITLE
jspm sample configuration

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#804]
Ideally the following configuration should work completely for jspm CDN support:

```
System.config({
  paths: {
    '*': 'https://registry.jspm.io/*',
    'github:*': 'https://github.jspm.io/*',
    'npm:*': 'https://npm.jspm.io/*'
  }
});
```

The full wildcard is currently messing up. There was a precedence case for this, it would be good to ensure that use case is more justified than the above.

**Comment by guybedford** [comment]
This is working fine.

**Comment by amitev** [comment]
No changes for this issue on the code base?

**Comment by guybedford** [comment]
https://github.com/ModuleLoader/es6-module-loader/commit/2e17f6cdb89bd02b19a47375bfc0370d1e1b0dec from SystemJS 0.19.3 does apply actually.

**Comment by amitev** [comment]
Will try. As I wrote in gitter I have issues where npm: doesn't override *
I.e. "*": "build/*" path config doesn't work anymore? I.e. it breaks "github:": "jspm_packages/github/" and "npm:": "jspm_packages/npm/

**Comment by guybedford** [comment]
If you still get that against SystemJS 0.19.3 let me know please.

**Comment by amitev** [comment]
Works perfectly. Thank you very much for the fix!
