### ISSUE TITLE
__moduleName is not defined

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#808]
When I deploy my bundled application code within an [Apache Cordova](http://cordova.apache.org) project, `___moduleName` becomes `undefined` so it can't be used for `System.import()`.

Maybe because SystemJS is not running on a web server with an `http://` URI? Cordova applications does have `file://` protocol like `file:///android_asset/www/bundle.js`

**Comment by guybedford** [comment]
Thanks, created https://github.com/systemjs/builder/issues/325.
