### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by arcanis** [systemjs/systemjs#809]
Hi,

I'm building a command-line node tool using SystemJS, and despite it working quite nicely, every invocation requires a few seconds to boot, even if I only need to print the usage.

Would it be possible, as a feature request, to implement something like the Pythonic `.pyc` files (ie. to cache the transpiled code on the filesystem to reuse it if the file timestamp is higher than the original source file)? Maybe hidden behind an option.

Worth noting that in my case, I cannot build the files beforehand, since I need to import some user files too (otherwise it would have been a solution).

Thanks,

**Comment by guybedford** [comment]
Yes, SystemJS builder or another project could provide an interface along these lines (jspm also needs this and would use a project that implements it). Closing as it's not a direct SystemJS feature. If you're interested in working on it let me know.
