### ISSUE TITLE
SystemJS stack track does give useful information and it's really hard to locate the problem

### ISSUE THREAD

**Issue by larryhe** [systemjs/systemjs#810]
Recently I am trying to playing with ES6 demo (https://github.com/jspm/demo-es6). But I found the biggest problem for developer is how to quickly locate the bugs in code. because system.src.js stack trace does give very useful information. For example, In above demo, I intentionally have a typo (in my-class.js, I type this.writeMessage to this.writeMessage2), then in the browser debug console,  I saw below stack trace, which point to the same place (bootstrap() line 4532 in system.src.js). Any ideas, Thanks for your time. 

`Uncaught (in promise) Error: this.writeMessage2 is not a function(…)
t @ system.src.js:4532
g@ system.src.js:4532
(anonymous function) @ system.src.js:4532
y @ system.src.js:4532
x @ system.src.js:4532
p @ system.src.js:4532
h @ system.src.js:4532
(anonymous function) @ system.src.js:4532`

**Comment by guybedford** [comment]
@larryhe if you click on the `...` at the end of the error message instead of the `>` at the start to open the stack trace, it will show you which file it was loading when it got the error.

**Comment by guybedford** [comment]
Also if you use Babel as the transpiler it gives great errors too.

**Comment by larryhe** [comment]
@guybedford Thanks so much. Really appreciate your help.
