### ISSUE TITLE
Configuration for mixed ES6 / CJS?

### ISSUE THREAD

**Issue by typhonrt** [systemjs/systemjs#811]
Greets, 

So, I've been using Parse & Backbone for the framework I've been jamming on for the past couple of months. With Parse 1.6 released last week they dropped all support for Backbone; The JS Parse API was once a fork of Backbone. Now they did this without even announcing anything to the community et al which yet added more work on my plate.. In the last few days I've converted the latest Backbone 1.2.3 to ES6 and refactored things to be able to easily extend it for connection to the new Parse 1.6 JS API and even further fun mods in a very clean way w/ a mapped path to switch between implementations.

Right now I'm compiling against their transpiled ES5 / Browserify bundled SDK. I'd like to be able to compile / transpile my Backbone fork and Parse directly via source code with SystemJS allowing me to pull directly from their repo. All of the Parse 1.6 JS code is pure ES6 except for the main entry point and about ~9 other files which to me looks like ES6 imports and CJS export + some require statements mixed in. You can see one of the files here: 
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/src/Parse.js

If I convert Parse.js to ES6 completely it continues correctly to where it fails on the other ~9 files. 

Now Parse is using Browserify and Babel to bundle their SDK. Gulpfile here:
https://github.com/ParsePlatform/Parse-SDK-JS/blob/master/gulpfile.js#L39

I tried their Babel settings and few others... To get things to work with Flow typing I added "nonStandard": true to the Babel config, so that shouldn't be the problem. 

It seems SystemJS interprets Parse.js as a CJS file and throws an error with the top most "import" statement: "Uncaught SyntaxError: Unexpected reserved word" as would be expected.

How can I get these ~10 files to be transpiled with the rest of my ES6 code base without having to rewrite them as I'd like to link directly to the Parse git repo?

It seems Browserify supports mixed ES6 imports + CJS export / require functionality? I haven't come across any other examples like this or could find much info on how the two can be mixed; IE "import" isn't valid CJS to my understanding. 

Any ideas on how to accomplish this task via config.js for SystemJS? I tried several things and couldn't figure it out.

Thanks!

**Comment by guybedford** [comment]
Mixed ES6 + CJS is effectively a two-phase linking process, which isn't supported in SystemJS. The code will then only run as CommonJS in SystemJS after the ES6 has been compiled into CommonJS.

Surely https://www.npmjs.com/package/parse is all built into CommonJS and ready to load?

**Comment by typhonrt** [comment]
Thanks for your input!

Pulling in the Parse NPM package from JSPM pulls in everything including the Parse node and react-native runtimes and tons of unneeded dependencies for just running the Parse browser SDK. Doing this muddies up config.js considerably, so I don't think it's the best route.

I'll definitely put in a little more thought into it. There are two things I'm trying to accomplish. 

The first is creating a combined ES5 bundle of Parse + my Backbone fork; I'll likely have to use Browserify to create this bundle. This combined bundle can be used wherever including SystemJS. Basically this just entails adding my Backbone fork to a similar build process that Parse is using for building their bundle. My only concern there regarding SystemJS is making sure a meta / export can be setup in config.js to handle the export of Parse and Backbone from one bundle. 

At the same time I'd also like to expose my Backbone fork separately as an ES6 git repo and link against just the Parse browser SDK in SystemJS. Right now I'm just including the bundled Parse SDK as a raw file and setting up a mapped path and meta / export in config.js (of course that is a manual step and not desired for others). Ideally I'd like to pull from the Parse NPM or git repo to make this link. As noted above the Parse NPM route is undesirable in general. Seemingly as discussed above in the first two messages I can't link against the Parse git repo / source code because of those 10 files which seemingly have mixed ES6 import / CJS export + some bare require usage. I'll be doing a test to rewrite the Parse source in pure ES6 then post a message on the Parse SDK repo to see if there is any buy in. There would be no problems if the Parse SDK is pure ES6. 

What I'll probably have to do for the first option above is build a combined Parse/Backbone bundle for those that want to consume things in entirety. For the second option of using the ES6 Backbone fork linked against the Parse browser SDK I might just have to build the standalone Parse browser bundle and create it's own git repo just to hold it in order to install it via JSPM. That's a bit more maintenance on my side to bump things when the Parse SDK updates. 

The big benefit of getting my ES6 Backbone fork linking directly to the Parse git repo (or the repo I create with the complete build) in SystemJS is that it makes it possible to build ones Backbone web app in ES6 and potentially further modify / extend Backbone from my ES6 source in a clean way as I've modified Backbone to use constructor injection for initialization. 

I might add that I'll be providing a vanilla ES6 Backbone version along with a Parse version and a further modified version adding more functionality w/ the web app framework I'll be releasing soon.

**Comment by typhonrt** [comment]
@guybedford 
I think things will be resolved soon. After chatting with Andrew Imm @ Parse he added the bundled version of Parse to a dist/ directory of the NPM release. 
https://github.com/ParsePlatform/Parse-SDK-JS/issues/27

I tested things with JSPM CLI override so just the dist/ directory and bundled browser version of Parse is pulled into SystemJS.  I also am now able to create a proper bundled version of my Backbone + Parse fork with SystemJS Builder. 

I gather Andrew hopefully gets in a pull request for the JSPM registry soon. 

Cheers!

**Comment by guybedford** [comment]
@typhonrt great, thanks for the update here!

**Comment by Hypercubed** [comment]
@guybedford has there been any progress in this area?  Now that the latest versions of node supported many ES6 features I am encountering more and more mixed modules (ES6 features in CJS modules).  In most cases these modules work fine during development.  JSPM identifies them as CJS and skips the babel transpiler.   However, when building minification chokes and I would prefer to transpile down to ES5.   Is there something we can do now in JSPM v0.16?  Do we need to wait for v0.17 and `plugin-babel`?
