### ISSUE TITLE
Promise polyfill doesn't work if RequireJS is included on the page

### ISSUE THREAD

**Issue by laurentgoudet** [systemjs/systemjs#817]
<img width="1022" alt="screen shot 2015-10-01 at 3 13 16 pm" src="https://cloud.githubusercontent.com/assets/2169585/10221543/4ea06c9c-684f-11e5-93c8-b13e8f3c5b37.png">

When RequireJS is included on the page before SystemJS, the Promise polyfill won't work. Saving & restoring `define.amd` does the trick, although the polyfill can't be autoloaded anymore.

**Comment by guybedford** [comment]
Thanks, that's definitely a bug in the polyfills.

**Comment by guybedford** [comment]
Released in 0.19.4.
