### ISSUE TITLE
SystemJS doesn't work with latest AngularJS

### ISSUE THREAD

**Issue by juergenzimmermann** [systemjs/systemjs#818]
I'm using jspm 0.16.11 containing SystemJS 0.19.3.
Now I upgraded to AngularJS 2.0.0-alpha.38. This release requires the installation `jspm install @reactivex/rxjs=npm:@reactivex/rxjs@0.0.0-prealpha.3`. See https://github.com/angular/angular/blob/2.0.0-alpha.38/package.json#L31.
However, I get a stacktrace at load / bootstrap time. A screenshot is attached. The first lines in the troublesome file are:
```
/* */
"format esm";
'use strict';

exports.__esModule = true;
```
When I uncomment the line `"format esm";` then the loading continues until the next file of RxJS is loaded having a line `"format esm";`. I set a comment at the line and can continue until the next file with the same line is loaded and so on.
![systemjs-angularjs](https://cloud.githubusercontent.com/assets/734334/10262113/e74eb41e-69ba-11e5-90f1-197c3e4b268c.png)

**Comment by juergenzimmermann** [comment]
FYI, I'm using TypeScript as the transpiler.

**Comment by guybedford** [comment]
Did you see https://gist.github.com/robwormald/90d06f3aa4927ef555c2?

**Comment by juergenzimmermann** [comment]
Thank you, the workaround works.
