### ISSUE TITLE
Importing requirejs with text dependencies fails because of .js extension being added

### ISSUE THREAD

**Issue by ccantill** [systemjs/systemjs#819]
I'm trying to import a requirejs module that relies on the text plugin to load certain templates, like so:

    define(['../override', 'jquery', 'text!../templates/filterPane.html',
            'text!../templates/filterBox.html'], function(.....){
        ...
    });

Systemjs insists on adding .js to the paths even though the .html extension is already specified, so importing fails of course. I can't just disable defaultExtension because the js dependencies are specified without the extension.

**Comment by guybedford** [comment]
@ccantill SystemJS specifies the plugin after the module name by default. To switch this around to the RequireJS convention, you can set the `System.loaderFirst = true` property.

**Comment by ccantill** [comment]
Tried putting it before my first import statement, but it doesn't really do anything. Also, wouldn't that make it a global change, potentially breaking imports of systemjs packages that expect the loader to be last? I would expect System.amdDefine to handle this transparently.

**Comment by ccantill** [comment]
Also, I think it's detecting the loader just fine as it's clearly stripped the text! part from the url; it's just the extension that's wrong.

**Comment by guybedford** [comment]
Do you mean `System.import` statement here? It wouldn't work before the `import` syntax. When a module is loaded as a plugin, a `js` extension is not added by `defaultJSExtensions`. So this config should certainly achieve that here.

**Comment by guybedford** [comment]
Yes it is a global property - plugin syntax is not generally recommended due to its lack of portability.

**Comment by ccantill** [comment]
Ah, figured out it's called pluginFirst and not loaderFirst :)

In my case I'm trying to load both aurelia (which uses SystemJS standard way of plugin last), and PowerGrid (which uses the requirejs standard way of plugin first). So if I understand correctly, there's no way this is going to happen without modifying PowerGrid to use SystemJS natively?

**Comment by guybedford** [comment]
Ah right, yes! Unfortunately you're right that won't work - one would need to be modified to match the other. We're moving away from plugin syntax in general though for specifying loaders via meta, so in future this would work fine.
