### ISSUE TITLE
SystemJS in node ignores baseURL

### ISSUE THREAD

**Issue by Munter** [systemjs/systemjs#822]
In node:

```js
var System = require('systemjs');
System.config({
  baseURL: 'file://' + process.cwd() + '/app'
});
require('../app/config');
```

the baseURL here will be the one defined in `../app/config.js`, not the one specified in the first config call.

This gives me:
```
Unable to fetch "/jspm_packages/github/components/jquery@2.1.4.js". Only file URLs of the form file:/// allowed running in Node.
Error loading /jspm_packages/github/components/jquery@2.1.4.js
```

If I kill the `baseUrl` property in `config.js` (not an option), it resolves my dependencies correctly.

If I do
```js
var System = require('systemjs');
require('../app/config');
System.config({
  baseURL: 'file://' + process.cwd() + '/app'
});
```

I get the expected `TypeError: baseURL should only be configured once and must be configured first.`

How can I configure the `baseURL` when running systemjs in node?

**Comment by Munter** [comment]
An example setup demonstrating this: https://github.com/Munter/issue-systemjs-821

**Comment by guybedford** [comment]
@Munter this is actually completely by design. I'd describe the design but wouldn't want to bore you. Although very happy to go through it if you're interested.

The way to handle these cases is to load the config file as data or via a wrapper like we do in SystemJS builder - https://github.com/systemjs/builder/blob/master/lib/builder.js#L195.

I know it doesn't seem ideal, hence why I'd be happy to discuss the logic if you'd like to.

**Comment by Munter** [comment]
It's kind of incomprehensible that what essentially boils down to:

```js
System.config({ baseURL: 'A' });
System.config({ baseURL: 'B' }); // via require config.js

System.baseURL === 'B';
```

while

```js
System.config({ baseURL: 'B' }); // via require config.js
System.config({ baseURL: 'A' }); // Throws exception that baseURL can only be set once
```

Why is there even a difference between these two config calls? It seems there shouldn't be. And if the reasoning behind it is not simple or doesn't bring any value to the user, I think it should be reconsidered

**Comment by guybedford** [comment]
@Munter the difference is this:

```js
System.config({ baseURL: 'A' });
System.config({ baseURL: 'B', paths: { some: 'config-path' } }); // via require config.js

System.baseURL === 'B';
```

while

```js
System.config({ baseURL: 'B', paths: { some: 'config-path' } }); // via require config.js
System.config({ baseURL: 'A' }); // Throws exception that baseURL can only be set once
```

The difference between the two is that the baseURL can only be set before setting any other configuration options. Once any other configuration options have been set, the baseURL can no longer be set.

To make this slightly more intuitive I've altered it to only allow the baseURL to be set in the first `System.config` call via https://github.com/systemjs/systemjs/commit/aeef702a7364f009301de5d74a739ee7308cc8f2.

**Comment by Munter** [comment]
Since jspm always creates a `baseURL` entry in config, would it be possible to not throw when `baseURL` is configured multiple times, but simply ignore it?

It's not that I like these silent error types, but when working in environments where you need alternative `baseURL` configurations and there is no way to avoid `baseURL` in config, you're screwed. If config.js was actually config.json, then I could simply load the config file and delete that entry before loading it. But since it's full javascript it's not really that easy

**Comment by guybedford** [comment]
I don't like it either, but it's a really important error to give to users though, because there are many scenarios where this will bite people with unexpected results if we suppress the message.

**Comment by guybedford** [comment]
@Munter if your use case here is jspm-specific, perhaps the suggested api here would be to do something like `require('jspm').System` where it comes pre-configured correctly like we do for the builder?

**Comment by Munter** [comment]
Yes! This works: `var System = require('jspm').Loader(); System.import('jquery')...`

Still fails with the `AMD module ... did not define`, but that's handled in a different issue.

Ping @dmatteo

**Comment by dmatteo** [comment]
But that's not how your supposed to require SystemJS, at least according to
the docs.

How come this works and `require('systemjs')` doesn't?

P. S.  The "did not define"  stuff it's almost done.

**Comment by Munter** [comment]
My PR updates the docs so it is at least possible to discover this technique. Since we're actually using the systemjs version provided by jspm in the runtime, getting it through jspm in node does make a lot of sense in order to avoid version conflicts as well

**Comment by guybedford** [comment]
:+1:
