### ISSUE TITLE
exportedFunction is not a function

### ISSUE THREAD

**Issue by capaj** [systemjs/systemjs#827]
I was trying out something with API and noticed that:
```
System.get('http://localhost:8080/components/routes/main.js').exportedFunction();
VM6101:1 Uncaught TypeError: System.get(...).exportedFunction is not a function(…)
```

even though docs list this exactly:
https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemgetmodulename---module

So outdated docs?

**Comment by guybedford** [comment]
No this certainly works - I think the module just doesn't have an `exportedFunction`?

**Comment by capaj** [comment]
@guybedford oh sry, I was sleepy already yesterday and didn't realize that exportedFunction is an example specific code. may be a bit better to write the docs a bit differently, will try to open up a PR
