### ISSUE TITLE
SystemJS can't load SFX modules in CJS format created by SystemJS bundler

### ISSUE THREAD

**Issue by pkozlowski-opensource** [systemjs/systemjs#828]
@guybedford I'm probably trying to push those things too far but I'm experimenting with CJS SFX (static) output from the SystemJS builder. I'm generating a bundle that I'm trying to load using SystemJS (`System.import`).

What I can see that it fails with erroring XHR requests like `http://localhost/cjs-packaging/4".`

The `4` comes here from a dependency (ex.: `$__System.registerDynamic("1", ["4"], true, function(require, exports, module) {`) in the SFX bundle.

Now, from my quick look at the SystemJS loader code I can see a RegExp looking for `require()` calls and this is why a dependency on `4` gets picked up. But my impression is that this is "wrong" - that is - SystemJS loader shouldn't care about SFX bundle internals. Somehow I would expect bundler to "rewrite" calls to 'require'

Am I hitting a bug here or get this all mixed up in my head? Here is a link to the repo with few simple files: https://github.com/pkozlowski-opensource/cjs-packaging 

Would be more than happy to provide more details, step by step reproduce scenario, plunker or whatever can help in understanding / solving this issue.

BTW: I can load a CJS bundle produced by WebPack without any issues.

**Comment by guybedford** [comment]
@pkozlowski-opensource thanks yes this is a bug! I've fixed it in https://github.com/systemjs/builder/commit/3418a94164139dce19dab6fb2c14cb8024626a4f.

**Comment by pkozlowski-opensource** [comment]
@guybedford wow, this was fast! Much appreciated! Are you planning to cut a new release of a builder in the not-so-distant future?

**Comment by guybedford** [comment]
Sure, I'll aim to do one first thing tomorrow.

**Comment by guybedford** [comment]
Released in Builder 0.14.8.

**Comment by pkozlowski-opensource** [comment]
> Released in Builder 0.14.8.

Awesome, thnx @guybedford !
