### ISSUE TITLE
Automatically build DepCache based on imports

### ISSUE THREAD

**Issue by geirsagberg** [systemjs/systemjs#830]
If I understand the docs at https://github.com/systemjs/systemjs/blob/master/docs/production-workflows.md#depcache correctly, module dependencies have to be explicitly registered. 

I imagine this could become a sizeable maintenance task; are there any thoughts to build the DepCache automatically based on import declarations in the modules?

Given a file `a.js`:

    import doStuff from 'foo';
    import otherStuff from 'bar';
    
    doStuff();

I would want to register the dependencies automatically in e.g. `config.js`

    System.depCache.registerRecursive('a.js');

Should be equivalent to:

    System.depCache['a.js'] = ['foo', 'bar'];

with additional registrations for dependencies `foo` and `bar`.

**Comment by guybedford** [comment]
Certainly. This feature is currently provided by SystemJS builder in https://github.com/systemjs/builder/blob/master/lib/builder.js#L479.

**Comment by geirsagberg** [comment]
That is awesome :) is this documented anywhere? I'm sure others would also love to know about this feature :)

**Comment by guybedford** [comment]
No not yet, API documentation for builder is lacking - it will be created as soon as the API is stable. Tracking in https://github.com/systemjs/builder/issues/250.
