### ISSUE TITLE
Importing mocked module fails

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#833]
Using examples from https://github.com/systemjs/systemjs/issues/725 I'm trying to register an inline (mock) module and importing it. 

``` javascript
      var normalizedName = System.normalizeSync('custom-module');
      System.set(normalizedName, System.newModule({
        mock: 'export'
      }));
      System.import(normalizedName,function(m) {
      	console.log('imported custom-module: ', m);
      })
```
This gives the following error. When I add the code directly in a script tag, it shows on which line it fails. 
```
Uncaught TypeError: n.indexOf is not a function
  e                      @ system.src.js:4208
  (anonymous function)   @ system.src.js:4208
  (anonymous function)   @ system.src.js:4208
  r.import               @ system.src.js:4208
  e                      @ system.src.js:4208
  (anonymous function)   @ (index):13
```
This error is not thrown when I don't add a callback to the `System.import` call. 

Basically I'm looking for some way to mock dependencies of modules I'm testing with some inline code. For example to test a REST api library by mocking fetch or jQuery's ajax calls. Any and all tips are appreciated.

**Comment by guybedford** [comment]
@peteruithoven try using `System.import(normalizedName).then(console.log.bind(console))`. Don't worry, I once saw Domenic use promises incorrectly :P

**Comment by peteruithoven** [comment]
omg! I'm such an idiot. Thanks!
