### ISSUE TITLE
systemjs can't work with windows phone javascript app

### ISSUE THREAD

**Issue by hwzhou** [systemjs/systemjs#836]
Hi, I am trying to integrate Aurelia (http://aurelia.io) into my Apache Cordova app. It works on iOS and Android. But when I tried to run it under windows phone. It throws an exception:

Unhandled exception at line 4527, column 5 in ms-appx://io.cordova.myapp110a9b/www/jspm_packages/system.src.js

0x800c001c - JavaScript runtime error: Unable to add dynamic content. A script attempted to inject dynamic content, or elements previously modified dynamically, that might be unsafe. For example, using the innerHTML property to add script or malformed HTML will generate this exception. Use the toStaticHTML method to filter dynamic content, or explicitly create elements and attributes with a method such as createElement.  For more information, see http://go.microsoft.com/fwlink/?LinkID=247104.

It seems windows phone app's security settings disallow document.write int inject unsecure code. So I tried to replace the code with following code:

      // window.toStaticHTML
      if (typeof window.toStaticHTML !== 'undefined' && typeof document !== 'undefined') {
          var scripts = document.getElementsByTagName('script');
          $__curScript = scripts[scripts.length - 1];
          var curPath = $__curScript.src;
          var basePath = curPath.substr(0, curPath.lastIndexOf('/') + 1);
          window.systemJSBootstrap = bootstrap;

          var safeScriptHTML = window.toStaticHTML(
              '<' + 'script type="text/javascript" src="' + basePath + 'system-polyfills.js">' + '<' + '/script>'
          );
          document.write(safeScriptHTML);
      }
      // document.write
      else if (typeof document !== 'undefined') {

And ran it again. It throws another exception that says System is undefined.

Unhandled exception at line 1, column 1 in ms-appx://io.cordova.myapp110a9b/www/config.js

0x800a1391 - JavaScript runtime error: 'System' is undefined

Can there's a way to fix this? Thanks.

**Comment by hwzhou** [comment]
Problem sovled! I digged a little deeper into cordova's platformoverrides.js file for windows phone. It used document.body.appendChild & document.head.appendChild to inject scripts.


if (typeof document !== 'undefined') {
    var scripts = document.getElementsByTagName('script');
    $__curScript = scripts[scripts.length - 1];
    var curPath = $__curScript.src;
    var basePath = curPath.substr(0, curPath.lastIndexOf('/') + 1);
    window.systemJSBootstrap = bootstrap;

    var script = document.createElement('script');
    script.setAttribute('src', basePath + 'system-polyfills.js');
    if (document.body) {
      document.body.appendChild(script);
    } else {
      document.head.appendChild(script);
    }
  }

**Comment by guybedford** [comment]
Note that you can just include `system-polyfills.js` with a script tag in the page before SystemJS here.
