### ISSUE TITLE
Relax baseURL

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#837]
Perhaps the change was too strict here, and seems to have broken Karma jspm as well.

Reverted in https://github.com/systemjs/systemjs/commit/a77fdb9c1cc3b2954ccd9f5b59ada8d6ba63dd3e, can post out a patch release on this.

**Comment by MeoMix** [comment]
It's worth noting that I have a successful build with karma-jspm after the strict change, but it's with baseURL omitted from the config file.

**Comment by guybedford** [comment]
Released in SystemJS 0.19.5.
