### ISSUE TITLE
XHR error (404 Not Found) When build ran as Network Service

### ISSUE THREAD

**Issue by RDalziel** [systemjs/systemjs#845]
Please divert me elsewhere if this is not the right place but:

I'm having issues running my build under network service, it appears that whenever module loads are attempted under NETWORK SERVICE i receive a 404 not found. There's no issue when this is run under my own account.

Anyone have any ideas what might be the issue here or any potential resolutions?

**Comment by guybedford** [comment]
Can you clarify what you mean by network service here? I'm not sure I completely follow your setup.

**Comment by RDalziel** [comment]
Network Service as in a Windows Service account

**Comment by guybedford** [comment]
If a URL from SystemJS gives a 404 it's either because the server isn't finding it, or SystemJS is asking for the wrong path. If the URL that is giving the 404 in the browser seems correct, then I guess that would make this an issue with your network setup?

**Comment by RDalziel** [comment]
It's a little odd, when i log in as my domain account there is no issues...but as part of the build process under network service it fails. This indicates the paths etc should be fine but for whatever reason it fails under a different account.

**Comment by guybedford** [comment]
So this is a build-only issue? Can you share an example of a URL that is not building? And is the build error itself exactly the 404?

**Comment by RDalziel** [comment]
Yes it's only occurring on builds at the moment. I've switched my build accounts over to a domain service account for at the moment so will need to get back to you on url example.

**Comment by guybedford** [comment]
Closing for now, but if you can provide an example do post back here.
