### ISSUE TITLE
Error: Potentially unhandled rejection [3] 

### ISSUE THREAD

**Issue by DeanB2015** [systemjs/systemjs#846]
I have a TypeScript + Cordova project using SystemJS(v0.19.4) and Angular2 (2.0.0-alpha.42).  I get the following error when I debug on Windows Phone 10
`Potentially unhandled rejection [3] TypeError: Unable to get property "toString" of undefined or null reference` 

![system_polyfills_error](https://cloud.githubusercontent.com/assets/10567383/10497443/e9801e12-7293-11e5-8575-1cab0325f6fc.PNG)

![system_polyfills_error2](https://cloud.githubusercontent.com/assets/10567383/10497820/0bc3e254-7296-11e5-87e5-4d76a18e9dae.PNG)

SystemJS works great with other libraries. When Angular2 is boostrapped,  the code works in browsers (Chrome, IE) and Android Phone. Unfortunately, the error appears when angular2 is boostrapped in Windows Phone 10 and 8.1.

**Comment by guybedford** [comment]
This sounds like it is likely a compatibility issue in your own code somewhere. Neither `Value.preserveToString` or `overrideNative` are defined in SystemJS itself, which seem to be where the error is happening.

**Comment by guybedford** [comment]
Let me know if you need further help at all here.

**Comment by DeanB2015** [comment]
@guybedford Thanks for the help.  It looks like the problem was es6-shim.js
