### ISSUE TITLE
is there something that can auto-build a depCache for you?

### ISSUE THREAD

**Issue by davis** [systemjs/systemjs#847]
i would like to try using it instead of created sfx-bundles, but is there any way i can without manually making a dep cache?

**Comment by davis** [comment]
or is that the same thing??

**Comment by davis** [comment]
i would like a file that has just the dependency tree in it..

**Comment by wmertens** [comment]
Jspm does that…

**Comment by guybedford** [comment]
@davis `jspm depcache app`?

**Comment by guybedford** [comment]
SystemJS builder can construct a depCache via the `builder.getDepCache` api. This is demonstrated in the jspm docs at https://github.com/jspm/jspm-cli/blob/master/docs/api.md#class-builder although will work just as well in plain SystemJS.

**Comment by davis** [comment]
ah, thanks!
