### ISSUE TITLE
Possible global define leak

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#850]
`global.define` may be being set as `System.amdDefine` during builds.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/30df021fd8e632113235e3a4b57ffeee09c8b571.

//cc @gustavnikolaj

**Comment by gustavnikolaj** [comment]
I verified that it fixed our build :-) Good job!

**Comment by guybedford** [comment]
Released in SystemJS 0.19.5.

**Comment by gustavnikolaj** [comment]
Thanks! Updated the assetgraph systemjs branch with this new version, and it still works.
