### ISSUE TITLE
Typescript transpile

### ISSUE THREAD

**Issue by druppy** [systemjs/systemjs#853]
Hope this is the proper place to ask ...

I have been trying to make SystemJS (latest via jspm) and typescript transpile work out of the box, but with little luck.

I ended up using the `ts` plugin and the buildin, that works quite nice, but I really like to make use of the buildin load's without any external elements.

Can anyone provide a code snip to how a `config.js` file should look like, for a project where we use `*.ts` and `*.tsx` files, and why ?

It seems like it either try to append .js (due to the `defaultESExtensions`), ot simply don't transpile.

My current setup looks like this :

```javascript
System.config({
  baseURL: ".",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "module": "system",
    "jsx": "react",
    "typeCheck": true,
    "resolveAmbientRefs": true
  },
  
  packages: {
    "app": {
      "defaultExtension": "ts"
    },
    "comp": {
      "defaultExtension": "tsx",
      "meta": {
        "*.tsx": {
          "loader": "ts"
        }
      }
    }
  }
....
```

How can this be made more simple and correct ? why cant I setup extension in meta ?

**Comment by guybedford** [comment]
The external TypeScript plugin is the recommended way to use TypeScript. The internal layer will be deprecated.

**Comment by druppy** [comment]
Ahh, perfect ... thanks, time to look more into that plugin.

Where is the recommended source of this kind of information ? I have tried to find info on google for this subject but it was really hard to find any.

Does this mean that the top `transpiler` option will be substituted with the `package->[xxx]->meta->loader` in the future ? Or where is the most ideal place to setup this binding between extension and transpile / loaders ?

**Comment by guybedford** [comment]
Exactly, package loader meta will be the configuration system. Yes these misunderstandings are in areas that are still forming. 0.17 will properly deprecate the use of `System.transpiler`, and provide hints to know what plugins to install, and how to use package configuration, as the standard init process.
