### ISSUE TITLE
jspm not loading from the right source (alpha29 - 44)

### ISSUE THREAD

**Issue by KhaosTheory1012** [systemjs/systemjs#854]
Hey,
I tried to start working on my angular2 project from back in May again and wanted to upgrade to the newest alpha release to try some new stuff out but every version newer than alpha28 seems to break jspm for me.

"https://registry.jspm.io/scripts/app.js 404 (Not Found)"
"Potentially unhandled rejection [3] Error loading "scripts/app" at https://registry.jspm.io/scripts/app.js
Not Found: https://registry.jspm.io/scripts/app.js (WARNING: non-Error used)"

I tried to fix it with System.config but then I run into a problem with the file extensions not being used for loading angular2.dev.js and router.dev.js.

I Hope someone can help me ;)

I posted the same issue over at the angular/angular repo:
https://github.com/angular/angular/issues/4786

**Comment by SerkanSipahi** [comment]
@KhaosTheory1012 What do you want to try? Why you try to loading "https://registry.jspm.io/scripts/app.js" ? Please share you code: package.json, System.config etc....

**Comment by KhaosTheory1012** [comment]
I am not trying to load from there but I get this error ;)

{
  "name": "khaostheory.de",
  "version": "1.0.0",
  "description": "Homepage",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Jan H",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "https://github.com/KhaosTheory1012/khaostheory.de.git"
  },
  "devDependencies": {
    "gulp": "^3.8.11",
    "gulp-cached": "^1.1.0",
    "gulp-clang-format": "^1.0.4",
    "gulp-connect": "^2.2.0",
    "gulp-imagemin": "^2.2.1",
    "gulp-minify-html": "^1.0.2",
    "gulp-newer": "^0.5.0",
    "gulp-rename": "^1.2.2",
    "gulp-shell": "^0.4.1",
    "gulp-tslint": "^2.0.0",
    "gulp-typescript": "*",
    "gulp-uglify": "^1.2.0",
    "gulp-util": "^3.0.4",
    "lodash": "^3.8.0",
    "merge2": "^0.3.5",
    "typescript": "1.5.0-beta"
  },
  "dependencies": {}
}

I got no System.config atm but I am now loading app.js but i am missing all imports now

system.src.js:1021 GET http://localhost:8080/scripts/util/footerComponent 404 (Not Found)

there is no .js extension but I cant add the defaultJSfileextension because it wont load angular2 then

**Comment by SerkanSipahi** [comment]
have you ever tried JSPM ? it makes almost anything for you. Also the basic setup for coding typescript! After then I would try to setting up angular2 for systemjs.

**Comment by KhaosTheory1012** [comment]
I'll definitely try that at some point but atm I try to look for a simple fix for my problem so I can try out some stuff :)

**Comment by SerkanSipahi** [comment]
How look your System.config ?

**Comment by KhaosTheory1012** [comment]
thats a long story and the main reason is that in May some things were not working 
and my System.config is empty

**Comment by KhaosTheory1012** [comment]
okay used jspm same problem 

https://drive.google.com/folderview?id=0B6WlljycO_YQZXpHcGp1UlF1UFk&usp=sharing

**Comment by SerkanSipahi** [comment]
I think from may to now is much time has passed and angular2 is also an alpha version. I think you have to should compare your angular2 bootstrap files(index.html, etc) with in https://angular.io/docs/ts/latest/quickstart.html . 

Can you share you code on github, thanks.

**Comment by KhaosTheory1012** [comment]
structure is pretty much the same only other components: https://github.com/KhaosTheory1012/Angular2_Prototype

**Comment by guybedford** [comment]
@KhaosTheory1012 did you read the SystemJS upgrade notes at https://github.com/systemjs/systemjs/releases/tag/0.17.0? You likely need to set `defaultJSExtensions: true`.

**Comment by KhaosTheory1012** [comment]
It is set ;)

**Comment by guybedford** [comment]
@KhaosTheory1012 it looks like you're using TypeScript - how do you get `.ts` extensions to load if `defaultJSExtensions` is set to true?

**Comment by KhaosTheory1012** [comment]
well i dont know but it works :D

https://github.com/KhaosTheory1012/Test

**Comment by guybedford** [comment]
You need to include the config.js file at https://github.com/KhaosTheory1012/Test/blob/master/config.js in the page for jspm to work.

**Comment by KhaosTheory1012** [comment]
Oh. Okay well looks like I messed up some files there. At least now I get another Error:
Uncaught SyntaxError: Unexpected token <   typescript@1.6.2:1

**Comment by guybedford** [comment]
Let me know if you still need assistance here.

**Comment by KhaosTheory1012** [comment]
still getting errors like: 
TypeError: Cannot read property 'toString' of undefined(…)      angular2.dev.js (alpha.44)
TypeError: Cannot read property 'get' of undefined

Maybe the router.js file causes problems? 

I use:
<script src="angular2/angular2.dev.js"></script>
    <script src="angular2/router.dev.js"></script>
both alpha 44 

not working (got them local because i fiddle around at places where I can't go online)

System.config({
            "baseURL": "/",
            "defaultJSExtensions": false,
            packages: {
                './scripts': {
                    defaultExtension: 'js'
                }
            }
        });
        System.import('scripts/app.js');


I tried jspm but it didnt work but I found some projects where that are working like
https://github.com/bkinsey808/bk-fullstack-ts and
https://github.com/mgechev/lazy-loading-routes-angular2


I am pretty confused right now and I can't figure out what causes the problem.

**Comment by guybedford** [comment]
Perhaps stick to the tested workflows here? https://github.com/johnpapa/angular2-go is another good Angular 2 project to try.

**Comment by KhaosTheory1012** [comment]
I made it work ;) 
The router was the source of the problem or better: the way I used it is depricated 

Thanks a lot anyways
