### ISSUE TITLE
Comments with es6 in them make modules try to transpile

### ISSUE THREAD

**Issue by johnsonjo4531** [systemjs/systemjs#855]
I'm running babel to transpile some es6 modules to amd modules then I am using System.js with the plain es5 amd modules. I had this error today where System.js was trying to transpile my file even though it was an es5 amd module. I believe it's a problem with having comments that have es6 code in them.

I had comment like this at the bottom of my file then I removed it and it started working. I replaced the comment with the below comment and it triggered it as well.

/*
 export var something = {
	somePropKeyPair,
	SomeOtherPropKeyPair
};
*/

**Comment by guybedford** [comment]
Yes, SystemJS automatic module detection does not strip comments for performance. These format detections are heuristics and not designed to be completely accurate. See https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#module-format-detection for more info.
