### ISSUE TITLE
Unhandled promise rejection

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#856]
I am developing an Apache Cordova App and use the [Cordova-sqlite-storage](https://github.com/litehelpers/Cordova-sqlite-storage). I am parsing a really really large JSON object with [Oboe.js](http://oboejs.com) and create a Promise object for every SQLite INSERT. In the end I got round about 7600 promise objects which are in an Array and awaited with `Promise.all()`.

I wrote a test where every single Promise gets rejected. The whole process can take some minutes until it's completed. Strangely enough I get randomly some `Unhandled promise rejection Object` console statements in the middle of the process.

Are there any timeouts or something else in the shipped SystemJS Promise library that throws / logs this statement if something take too long to process? I've read at least 10 times my source code and can't see any place where I left a promise unhandled.

Pseudo code:

```js
const promises = [];
oboe('path/to/large.json')
  .node('item.*', item => {
    const promise = processItem(item);
    // If I make promise.catch() here the error messages disappear (???)
    promises.push(promise);
  });
Promise.all(promises).then(...).catch(...);
```

The message disappears if I make a `.catch()` for every promise :question:  :confused:

**Comment by screendriver** [comment]
It seems I am not alone with asynchronous promises: https://github.com/zloirock/core-js/issues/72
So it's not related to SystemJS and I am closing this issue.

**Comment by weagle08** [comment]
@screendriver it seems you understand systemjs with cordova pretty well.. would you have time to help me with an issue? I can't get systemjs to load files in cordova.. I just get xhr errors:
![image](https://cloud.githubusercontent.com/assets/7888478/12804966/76b3433c-cabd-11e5-8eba-19e8b022e32d.png)

I have a repo to reproduce my issue by following steps in the README: https://github.com/weagle08/aurelia-cordova-test

**Comment by screendriver** [comment]
I've created a pull request that fixes your issue: https://github.com/weagle08/aurelia-cordova-test/pull/1

**Comment by weagle08** [comment]
you sir are awesome!  wish there was a way i could buy you a beer... hmmmm.. new app idea?

**Comment by screendriver** [comment]
:+1: :grin: 
You are welcome!
