### ISSUE TITLE
a library telling its consumer how too transpile itself

### ISSUE THREAD

**Issue by capaj** [systemjs/systemjs#857]
So let's say I have a babel project and I want to use a library in typescript. When I do jspm i typescript-written-library, will I also have to edit my config and mark the library as being transpiled with typescript?

Or can we have some mechanism that will take care of this for all of us?

I am asking in relation to recently learning about deprecating the built in transpilers. While I like the idea, that JSPM will not give any transpiler an advantage and treat all of them equally, I am afraid that this will lead to more configuration needed from the developer.
Previously if I had babel/traceur, I knew I could transpile any library written in ES6 or ES5. Now, I will have to add a config after installing any ES6 library?

**Comment by guybedford** [comment]
The jspm 0.17 configuration system will allow effective sharing of SystemJS package configuration. If we just allow a `loader` to be specified in the package.json file that is not enough as we need to know how we are going to resolve the given loader name. That is, this is a jspm concern.

**Comment by capaj** [comment]
nice to hear that this will be covered by jspm
