### ISSUE TITLE
Use package.json browser field?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#860]
Browsify and possibly Webpack support path overrides using the `browser` field in `package.json` files, see:
https://github.com/substack/browserify-handbook#browser-field
Usage example in shortid package: https://github.com/dylang/shortid/blob/92683af76ebaff2f751015978ad514f9c133eae3/package.json#L33

To make packages that use that functionality compatible with jspm it would be great if it could also use this. 
Maybe turn it into a `map` config in the config?

**Comment by peteruithoven** [comment]
(Looks like this is only an issue for shortid when I retrieve it from github instead of npm)

**Comment by guybedford** [comment]
When installing from github, try adding a `registry: 'npm'` override to support the browser property. SystemJS has its own configuration which is slightly different to the browserify `browser` field, which there are no plans to support.

**Comment by peteruithoven** [comment]
Ah thanks. Hopefully that info in this issue will help people.

**Comment by jjrv** [comment]
[`cbuild`](https://github.com/charto/cbuild) wraps `systemjs-builder` to bundle packages but looks under `node_modules` to find any packages not mapped in `config.js`. It parses the `browser` field of found packages to map the correct file.

It can also automatically generate a new `config.js` file with the correct browser mappings for using SystemJS without bundling. This allows leaving `jspm` out entirely if you don't need its complexity.
