### ISSUE TITLE
TypeScript is not transpiled if only the content of the string changed

### ISSUE THREAD

**Issue by yfain** [systemjs/systemjs#862]
I was working with Angular2/TypeScript code, and after changing the content of a string the code was not transpiled. The cached version of .ts!transpiled file was used.

I described this in detail in the following blog:
http://yakovfain.com/2015/10/23/angular-typescript-systemjs-and-browser-cache/

**Comment by guybedford** [comment]
Thanks for sharing your solution for others, these are browser gotchas that all web devs need to learn!
