### ISSUE TITLE
Bundles not loading unless configured initially in config object

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#863]
@guybedford 

So after some more debugging and poking, it looks like the bottom line is that SystemJS needs my bundle configured like this:

```javascript
System.config({
    defaultJSExtensions: true,
    paths: {
        text: 'build/text'
    },
    bundles: {
        'dist/billingmanager/billing/billingSmaller': ['billingmanager/billing/billingSmaller']
    }
});
```

Neither this

`System.bundles['dist/billingmanager/billing/billingSmaller'] = ['billingmanager/billing/billingSmaller'];`

nor this

`System.config.bundles['dist/billingmanager/billing/billingSmaller'] = ['billingmanager/billing/billingSmaller'];`

work, even though the former is referenced in your docs as being valid.

Apologies if this is a known bug reported elsewhere that I missed. 

---

Here's my config

```javascript
System.config({
    defaultJSExtensions: true,
    paths: {
        text: 'build/text',
        'billingmanager/billing/billingSmaller': 'dist/billingmanager/billing/billingSmaller'
    }
});
```

This code loads the correct file, but does not parse it

```javascript
System.import('billingmanager/billing/billingSmaller').then(function (b) {
    console.log('loaded');
});
```

I can't seem to happen upon any combination of adding and removing a .js along with toggling the defaultJSExtensions config.  

What is the correct way to request a file with a custom path?

**Comment by arackaf** [comment]
So sorry - only now seeing CSP-Compatible Production section in your docs.  Let me take a look there.

Am so used to requireJS I didn't think to even look for something like this initially.  So sorry!

**Comment by arackaf** [comment]
Looking a little deeper:

this setup

```javascript
System.config({
    defaultJSExtensions: true,
    paths: {
        text: 'build/text',
        'billingmanager/billing/billingSmaller': 'dist/billingmanager/billing/billingSmaller'
    }
});

System.bundles['dist/billingmanager/billing/billingSmaller'] = ['billingmanager/billing/billingSmaller'];
```

Results in the correct bundle file being loaded, but the module therein is not parsed.

Removing 

`'billingmanager/billing/billingSmaller': 'dist/billingmanager/billing/billingSmaller'`

from paths results in the bundle file simply not being loaded at all.

If it helpers, the bundle is made up of all AMD modules, basically

```javascript
define(['a', 'b', 'etc'], function(a, b, etc){
   return result;
});
```

The bundled result looks reasonable.  I just can't quite get SystemJS to process it correctly.

**Comment by guybedford** [comment]
Thanks, I've updated the docs in https://github.com/systemjs/systemjs/commit/04f684d4e1055ffb6d008785e4a79afbd6900bac. Config should always be set through `System.config(...)` as SystemJS needs to normalization the configuration.

**Comment by guybedford** [comment]
Let me know if you need any more help here at all.
