### ISSUE TITLE
ESDoc + JSPM / SystemJS plugin

### ISSUE THREAD

**Issue by typhonrt** [systemjs/systemjs#864]
Greets Guy et al,

I just published a rather useful [ESDoc](https://esdoc.org/) plugin which makes it possible to generate end to end documentation for anyone doing ES6 development w/ JSPM / SystemJS. It allows a local source root + any number of JSPM managed packages to be linked together to generate comprehensive documentation across multiple source repos / packages. I've tested it rather thoroughly and will be actively maintaining it. I posted this message here so folks can perhaps find info on this plugin when searching issues. You can close this issue when you get to it.

https://www.npmjs.com/package/esdoc-plugin-jspm

Cheers...

**Comment by guybedford** [comment]
Nice, thanks for sharing. I've added this to the list at https://github.com/jspm/jspm-cli/wiki/Third-Party-Resources.
