### ISSUE TITLE
node-webkit / electron builtins support

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#866]
As discussed in jspm/nodelibs-path#2 please add support for `._nodeRequire` in node-webkit and atom electron.

Also, it might be nice that jspm upstream loads libraries with these builtins if available - but this would require probably use conditional loading when specifying or reading `config.js`.  I have seen a bug request previously jspm/npm#77 where a similar issue had been raised and you provide a hack. May I urge you to consider a more permanent strategy to resolve this...

**Comment by CxRes** [comment]
Maybe not an exactly replicable example but Browserify provides `--no-builtins` to not include node builtins when packaging for node. The best case scenario would be to allow `import` with builtins which translate to requires, when the user explicitly specifies their intention.

**Comment by guybedford** [comment]
@CxRes these conditional handling features are coming in jspm 0.17.

I don't know exactly what action is needed on this issue to support these environments, so will leave this up here for someone to share how to detect the `_nodeRequire` correctly.

**Comment by CxRes** [comment]
@guybedford I have been digging around webpack recently. What they seem to be doing is to ask the user to explicitly specify that the packaging is for node-webkit/atom-electron and in those cases not translate the require statements for builtins.
So once you have conditional loading, maybe based on a setting in `config.js` you might change `path:'@empty'` while mapping. 
The problem I foresee with the above approach is dev-dependencies if using node built-ins still require them to be installed. Another way could be for there to be a dynamically create a registry called `builtins:` that populates built-ins or are empty when packaging for desktop again based on a config flag. That way you can avoid _nodeRequire detection.

**Comment by guybedford** [comment]
@CxRes I've just checked and node-webkit definitely defines the `require` and `process` globals which is all that SystemJS needs to detect this environment. The only way then that `System._nodeRequire` would not be set is if the above were overwritten before SystemJS is loaded. Let me know if that makes sense.

**Comment by CxRes** [comment]
I know that nwjs does something fishy with `require` and `process`, because it makes a distinction between node context and browser context - see:https://github.com/nwjs/nw.js/wiki/Transfer-objects-between-window-and-node. By the time I go about loading SystemJS, execution is definitely in the browser side (such as inside a `<script>` tag) where the `require` and `process` are from the browser context (ie the require is overwritten by node-webkit to transfer execution results to the browser). 

Can you point me to the line again where `System._nodeRequire` is set, so that I can test a couple of things when I can spare some time.
1) Try loading SystemJS in the node context (the `node-main` file) and see what happens - does the `System._nodeRequire` work then. Doing this is not ideal because it means scripts that I really want on the browser context only (e.g. I am using jquery and angular) would also be loaded from the node context.
2) Check `require` just before `System._nodeRequire` is set, while loading in the browser context.

I guess you would be better of talking to Roger Wang than me on understanding this context business. I did put a help request on the mailing list but no help was forthcoming. Maybe we need to talk to him directly.

**Comment by guybedford** [comment]
@CxRes the detection is at https://github.com/systemjs/systemjs/blob/master/lib/cjs.js#L57. All we do is check that there is a global `require` and `process` and that the require has a `resolve` method, and then use that `require`. That's really all there is to the detection. All of those things should hold true for the nwjs environment as far as I can tell but let me know if I am mistaken.

**Comment by CxRes** [comment]
Ok. Finally something I am confident about. `require.resolve` is undefined. See issue nwjs/nw.js#1659.

**Comment by guybedford** [comment]
Ok thanks, I've added a change in https://github.com/systemjs/systemjs/commit/98bb0181c6fe9415038e4adb82771090ef2c99b4 - let me know if that helps here.

**Comment by CxRes** [comment]
In my preliminary tests, it seems to work fine. Thanks!

Now awaiting the magic of conditional loading with jspm :) !!!

**Comment by guybedford** [comment]
Released in 0.19.7.
