### ISSUE TITLE
CSS loader causes exception in translate hook

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#869]
I believe there's a bug in the CSS loader in your docs.  This, specifically 

```javascript
exports.fetch = function(load, fetch) {
    return new Promise(function(resolve, reject) {
        var cssFile = load.address;

        var link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = cssFile;
        link.onload = resolve;

        document.head.appendChild(link);
    });
}
```

On Google Chrome at the very least the onload callback has an event argument first, which of course becomes the Promise resolution value, which causes an exception here, since `load.source` is `undefined`.

![image](https://cloud.githubusercontent.com/assets/11261266/10733613/8bc055c4-7bcd-11e5-8ca3-8a2885b6bd4b.png)

One trivial workaround is of course this

```javascript
exports.fetch = function css(load, fetch) {
    return new Promise(function (resolve, reject) {
        var cssFile = load.address;

        var link = document.createElement('link');
        link.rel = 'stylesheet';
        link.href = cssFile;
        link.onload = function(){
            resolve('');
        };

        document.head.appendChild(link);
    });
};
```

Though you might consider changing that line to

```javascript
var meta = load.source && load.source.match && load.source.match(metaRegEx);
```

**Comment by guybedford** [comment]
Good point, thanks I've added https://github.com/systemjs/systemjs/commit/a230b70dbee76d8429713418edbac926fc31308a.
