### ISSUE TITLE
Normalizing resource name breaks caching

### ISSUE THREAD

**Issue by arackaf** [systemjs/systemjs#871]
I have the following normalization method so I can stay backward compatible with requireJS and how it specifies loader plugins

```javascript
var systemNormalize = System.normalize;
System.normalize = function (name, parentName, parentAddress) {
    if (/^text!/.test(name)) {
        return name.substr(5) + '!text';
    } else {
        return systemNormalize.call(this, name, parentName, parentAddress);
    }
}
```

It works fine, but it seems to break your caching.  Namely, if I load a module with either this text dependency 

`text!mixedFormatBuildTests/module1/shared/content.htm`

OR specified normally

`mixedFormatBuildTests/module1/shared/content.htm!text`

And then I load the same dependency on its own, 

`System.import('text!mixedFormatBuildTests/module1/shared/content.htm')`

I can see it reloading in the network tab.  Peaking in `System.defined` I see this after the module initially loads

![ss1](https://cloud.githubusercontent.com/assets/11261266/10749155/340bb2b6-7c35-11e5-9b85-c8af89688cb0.png)

And after the ad hoc load on the text dependency, here's what I see

![ss2](https://cloud.githubusercontent.com/assets/11261266/10749177/78f8878c-7c35-11e5-97f6-3393a722082d.png)

It seems the normalized name is getting stored differently when requested as opposed to when defined.

Note that if I load the resource the normal way

`System.import('mixedFormatBuildTests/module1/shared/content.htm!text')`

then all is well, so it does seem to be the normalized name when requesting.

**Comment by guybedford** [comment]
We actually have an option for this upgrade path via `System.config({ pluginFirst: true })`. The issue currently is that it doesn't work well with jspm which is why it is undocumented still.

**Comment by arackaf** [comment]
Can you elaborate on that a bit?  I added `pluginFirst: true` to my config (we're not using JSPM) but now my text dependency isn't loaded with my module, even when declared "properly" as

`'mixedFormatBuildTests/module1/shared/content.htm!text'`

**Comment by guybedford** [comment]
@arackaf this configuration option does what your custom normalize hook is doing, while ensuring bundling and everything will work out correctly. But then all plugins need to be in the RequireJS style - `text!resource-name` etc.

**Comment by arackaf** [comment]
Ah!  Ok, cool.  In that case I suppose I'll eschew the undocumented feature and keep things as they are.  The consequences are extremely minimal, and preventable by updating old code to specify !text at the end if this ever even comes up.

So would fixing this to use the pre-normalized name in your internal cache be a major change to the system?

**Comment by guybedford** [comment]
Names in the registry must be in the `file:///` protocol full normalized format. Breaking this contract is what is causing the issues.

I suggested the `pluginFirst` feature because it will ensure all the right normalizations for these cases of loading via `text!x`. If you rewrite the code to use `x!text` then that is also a good solution too.

**Comment by arackaf** [comment]
Is there another way I should be writing the normalize function so as to not break your protocol?

**Comment by guybedford** [comment]
Even if you get the normalization right in this hook, it will still break during bundling, as bundles need to do reverse-normalization. So the `pluginFirst` option is the only way to support this kind of syntax.

**Comment by arackaf** [comment]
Ok - thanks a bunch.  I'm only really "supporting" this syntax so I don't have to update a ton of existing code to get SystemJS in.  As this will hardly ever come up, has a tiny consequence when it does, and is fixable by using the proper syntax, I think I'll just leave it be and move on. 

Thanks for your help! :+1:

**Comment by guybedford** [comment]
Sure, no problem at all! Yeah it's not that advisable but if it works for you then great. Code replacement can often be quite easy to do here as well.
