### ISSUE TITLE
Cordova Support

### ISSUE THREAD

**Issue by ggutenberg** [systemjs/systemjs#875]
I've included the web files locally in a Cordova project, including everything under `jspm_packages`.  My script tag for system.js looks like:

`<script src="lib/js/toolkit-js/src/jspm_packages/system.js"></script>`

and my System.config baseURL looks like:

`baseURL: cordova.file.applicationDirectory + "www/" + "lib/js/toolkit-js/src/",`

`cordova.file.applicationDirectory` resolves to something like:

`file:///Users/username/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/0C307D01-9EC8-4458-9C16-54DA1B6B6A31/MyTestApp.app`

So the full path becomes:

`file:///Users/username/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/0C307D01-9EC8-4458-9C16-54DA1B6B6A31/MyTestApp.app/www/lib/js/toolkit-js/src/`

I know this path is valid as I can browse to it and see the files there.  However I get the following error/stack trace when using this method:

```
ReferenceError: Can't find variable: module
(anonymous function)main.html:10
appendChild
Usystem.js:13:16884
executesystem.js:14:6731
isystem.js:13:31859
nsystem.js:13:30421
executesystem.js:14:3452
bsystem.js:13:9955
wsystem.js:13:10328
psystem.js:13:8206
hsystem.js:13:8591
(anonymous function)system.js:13:6897
promiseReactionJob
```

I've also tried by removing the `file://` prefix and hardcoding the baseURL, but the same error occurs.

Note that if I *don't* include the files locally and set my script tag to:

`<script src="http://myserver.com/lib/js/toolkit-js/src/jspm_packages/system.js"></script>`

and my baseURL to:

`baseURL: "/lib/js/toolkit-js/src/",`

it doesn't seem to work either.  No errors, but the code that I'm loading just isn't there.  However that code works perfectly in a browser.

**Comment by guybedford** [comment]
This sounds like an execution error not a fetch error. I guess your file has the variable `module` in it somewhere?

**Comment by ggutenberg** [comment]
Ah, my code doesn't, but the Cordova library does.  It uses `module.exports` for node compatibility.  Interestingly (to me at least, since I'm not very familiar with your codebase), when I bundle system.js using

```
jspm bundle-sfx main.js toolkit-js.js
```

everything works.

Is there any way to work around this in the unbundled code?

**Comment by guybedford** [comment]
@ggutenberg would it be possible to share the error stack again against the unminified version of SystemJS?

**Comment by ggutenberg** [comment]
```
ReferenceError: Can't find variable: module
(anonymous function)main.html:10
appendChild
__execsystem.src.js:1383
executesystem.src.js:3319
linkDynamicModulesystem.src.js:2942
linksystem.src.js:2785
executesystem.src.js:3117
doDynamicExecutesystem.src.js:724
linksystem.src.js:917
doLinksystem.src.js:578
updateLinkSetOnLoadsystem.src.js:626
(anonymous function)system.src.js:439
promiseReactionJob
```

**Comment by guybedford** [comment]
@ggutenberg thanks. Perhaps try setting `System.config({ globalEvaluationScope: false })` and see if that gives a better error message?

**Comment by ggutenberg** [comment]
Setting `globalEvaluationScope: false` suppresses the error above and doesn't throw anything else - it just outputs `Promise {status: "pending"} ` after the call to `System.config()`.  But it's still not working - I can't access any of my code.

**Comment by guybedford** [comment]
I think this is firstly an issue with error reporting in Cordova. Both methods should provide useful error messages telling you what was loading.

Then that would at least narrow it down to understand which module in your dependency tree has the invalid reference to `module`.

If you're feeling brave and want to debug SystemJS at line 3319, to see if you can extract some error reporting, you can add a `console.log(load)`. That will at least help to understand which load is erroring.

**Comment by ggutenberg** [comment]
JSON.stringify'ed the output so that it pastes better:

```
{
    "name": "file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/1CA5820F-2B25-4FF7-A33D-4DFFBCD8DD33/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25.js",
    "metadata": {
        "deps": [],
        "format": "global",
        "entry": {
            "name": "file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/1CA5820F-2B25-4FF7-A33D-4DFFBCD8DD33/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25.js",
            "deps": [],
            "declare": null,
            "executingRequire": false,
            "declarative": false,
            "normalizedDeps": [],
            "groupIndex": 0,
            "evaluated": true,
            "module": {
                "exports": {},
                "id": "file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/1CA5820F-2B25-4FF7-A33D-4DFFBCD8DD33/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25.js"
            },
            "esModule": null,
            "esmExports": true,
            "originalIndices": []
        }
    },
    "address": "file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/1CA5820F-2B25-4FF7-A33D-4DFFBCD8DD33/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25.js",
    "source": "/*\n\t*\n\t*\tWeever Mobile Web App for http://weeverinternal.weeverapps.com/\n\t*\t(c) 2015 Weever Apps Inc. < http://www.weeverapps.com/ >\n\t*\n\t*\tAuthor: \tWeever Apps Server\n\t*\tVersion: \t3.13.6 \"Orange Sulphur\" (build 136)\n\t*\n\t*/\n\nmodule.exports = require(\"npm:babel-core@5.8.25/browser\");"
}
```

**Comment by ggutenberg** [comment]
So, the above output was actually from line 3309.  Our build script is injecting some stuff at the beginning of the file that I didn't notice, so it shoved it down 10 lines.  When I put a `console.log(load)` at line 3319, `System` doesn't exist anymore:

`ReferenceError: Can't find variable: System`

**Comment by guybedford** [comment]
I meant exactly that line in your version of SystemJS though.

I've posted https://github.com/systemjs/systemjs/issues/879 for the debugging issue above.

Then to see if we can work around this issue, try adding - `System.config({ meta: { 'npm:babel-core@5.8.25.js': { format: 'cjs' } } })` and let me know if that helps?

**Comment by ggutenberg** [comment]
Now I'm getting:

```
file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/F9EE4092-C39D-41F8-B717-E2A8E1DCCB21/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25/foo.js.map
[Error] Failed to load resource: The requested URL was not found on this server. (foo.js.map, line 0)
```

**Comment by screendriver** [comment]
I am also using SystemJS within a Cordova project and it works fine.

> baseURL: cordova.file.applicationDirectory + "www/" + "lib/js/toolkit-js/src/"

You don't have to prefix anything with `www/`. `www/` is your root directory. Everything that will be served within a Cordova App must exist in `www/`. So localhost ponsti directly to this directory. `baseURL: "lib/js/toolkit-js/src/"` should me enough.

> Ah, my code doesn't, but the Cordova library does. It uses module.exports for node compatibility

Cordova itself does not know anything about Node.JS, any module system or something self. It only provides a frameles App with an embedded WebView component. Nothing more. What you mean is the cordova-cli which is written in Node.JS and builds your app.

> Now I'm getting:
> 
> file:///Users/garth/Library/Developer/CoreSimulator/Devices/77094B3B-EE20-4DC0-A132-82D7A9985E91/data/Containers/Bundle/Application/F9EE4092-C39D-41F8-B717-E2A8E1DCCB21/Weever%20Internal.app/www/lib/js/toolkit-js/src/jspm_packages/npm/babel-core@5.8.25/foo.js.map
> [Error] Failed to load resource: The requested URL was not found on this server. (foo.js.map, line 0)

This is because the path mentioned above is wrong. It tries to find the source map file `foo.js.map` as a subdirectory of babel-core. Naturally this doesn't work because it does not exist.

**Comment by guybedford** [comment]
@screendriver thanks for your comments here, I would value your opinion on https://github.com/systemjs/systemjs/issues/879 here if you have anything to add.

@ggutenberg that you got a new error shows that the original error was resolved by the format config. This worries me though as the file would definitely have been detected as CommonJS in the current version of SystemJS... I'd advise checking you are running the latest version.

Closing, but let me know if I can help further here at all.
