### ISSUE TITLE
Mapping only when loading a specific module?

### ISSUE THREAD

**Issue by SomethingSexy** [systemjs/systemjs#876]
We are in the processing of converting over from RequireJS to SystemJS.  One of the features we have utilizing in RequireJS is the ability to map a dependency only in a specific module.  This is used for client extension points in our codebase.

For example in RequireJS we might do something like:
```
map : {
  'foo': {
    'bar': 'some/other/module'
  }
}
```

So whenever we load the module foo and it imports bar as a dependency, it replaces it with 'some/other/module'.  Since we don't do this globally, it allows 'some/other/module' to import the original 'bar' and override methods, etc and then return.

I have been trying to figure out how to do this in SystemJS, is it possible? Am I missing something?

Thanks!

**Comment by SomethingSexy** [comment]
I think I figured it out but I might need someone to make sure what I am doing is sane.

From the above post.  I think I need to do something like this:

```
System.config({
  packages: {
    'foo': {
      map: {
        // use local jquery for all jquery requires in this package
        './bar': 'some/other/module'
      }
    }
  }

});
```
If I wanted 'some/other/module' to still be able import 'foo/bar'.  I needed to also add this configuration.
```
  map: {
    'baseBar': 'foo/bar',
  },
```

Then in  'some/other/module' I could import 'baseBar'.

Does this make sense?

**Comment by guybedford** [comment]
Yes this is the right sort of idea. You could also set up another package for `some/other/module` to have its own contextual map too. The package map is equivalent to the RequireJS nested map like this.

**Comment by SomethingSexy** [comment]
Right on! thanks @guybedford

**Comment by SomethingSexy** [comment]
If jspm imports a package that has its own internal map set to itself (for internal reference) and it replaces that mapped named with relative paths.  It went from

```
import stuff from 'foo/my/package';
```
to
```
import stuff from '../../my/package'
```
How would I use the above packages config to override the 'my/package' module with another?

**Comment by guybedford** [comment]
I'm not sure I understand the question - that is just normal map config then to map `foo/my/package` to something else?

**Comment by SomethingSexy** [comment]
Sorry, I think part of my problem ended up being the package.json configuration we had for a package.  We have package "foo", which internally references foo when importing interanl references.  So originally in foo's package.json under jspm I had setup:

```
map: {
  foo: "src"
}
```

When using jspm to import "foo" into a new package "bar", it was replacing "foo" with relative references, "../../", etc.  Which seemed to make it difficult to override files.  I switched the configuration in "foo" to use
```
directories: {
  lib: "src"
}
```

That keep the foo name in the internal modules, then I could correctly override using the packages configuration.
