### ISSUE TITLE
System.set() second parameter must be normalizeSync string

### ISSUE THREAD

**Issue by kresli** [systemjs/systemjs#877]
Im not sure if this is a bug.
this works
```javascript
System.set( 
    'normalizeSync/path',
    System.get(System.normalizeSync('/src/core/__mocks__/ComponentBuilder'))
);
```
but this doesn't 
`System.set( 'normalizeSync/path', System.get('../__mocks__/ComponentBuilder'))`;

**Comment by guybedford** [comment]
Yes this is by design, but it is a catch. I've added a note to https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemsetmodulename-module.
