### ISSUE TITLE
Defining "define" on CJS format

### ISSUE THREAD

**Issue by gabrielalan** [systemjs/systemjs#880]
Hello devs. I'm using SystemJS on a little personal project, and I'm having some problems.

I choose CommonJS format to load my files. The files created by me are recognized and loaded successfully by SystemJS. But I added a LIB that implements UMD pattern, and it seems that SystemJS is generating a misunderstading on this block. See:

My Example Configuration:
```javascript
System.config({
	baseURL: 'js/app',
	defaultJSExtensions: true,
	format: 'cjs',
	map: {
		'SomeLib': '/js/vendor/someLib/source.js'
	}
});
			
System.import('main.js');
```

And that is the library I'm trying to load with SystemJS
```javascript
'use strict';

(function(root, functionClass) {
	/*
	**	UMD BLOCK
	*/	
	if (typeof define === 'function' && define.amd) {
		// AMD
		define([], functionClass());
	} else if (typeof exports === 'object') {
		// Node, CommonJS-like
		module.exports = functionClass();
	} else {
		// Browser globals (root is window)
		root.AnyFunctionClass = functionClass();
	}
}(typeof window !== 'undefined' ? window : {}, function() {

	function AnyFunctionClass() {}

	return AnyFunctionClass;
}));
```

Debugging this code above, I have found that the flow entered on the first IF (the AMD verification), but I'm using CommonJS pattern. As SystemJS is defining "define" function, this verification assumes that it is running it self on AMD context.

**Comment by guybedford** [comment]
The `format` option needs to be specified as part of [package configuration](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages) or meta configuration.

Try using something like `System.config({ meta: { 'SomeLib': { format: 'cjs' } } })`.

**Comment by gabrielalan** [comment]
Sorry for being late. I have setted the format options, but nothing change.

**Comment by guybedford** [comment]
If that meta is added and working, then `define` will not be defined. So it's purely about configuring the meta correctly.

**Comment by guybedford** [comment]
(you can even try adding `"format cjs"` to the top of the source file to be sure)
