### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by reppners** [systemjs/systemjs#881]
When developing and getting some path wrong it takes really long until the request for this file times out and an error is thrown. Could SystemJS open an api where a very timeout duration can be specified to enable a quicker workflow?

The alternative right now is to go to the developer tools and scan for hanging requests in the networks section manually. However this requires me as an IDE user to detach the debugger and switch back and forth between browser developer tools and IDE.

**Comment by guybedford** [comment]
For the use case you mention, a 404 from the server would avoid the need for a timeout at all. Is that not possible for this use case at all?

**Comment by reppners** [comment]
Thats true. Then my server must be doing something wrong because it takes about a minute to reply with 404.

**Comment by reppners** [comment]
Ok.. silly me had some proxy routes setup for backend requests and if a file was not found it also was send further to the proxy which somehow also not answered with an immediate 404. By checking what routes are proxyable before sending a request to the proxy I now get immediate 404's.
