### ISSUE TITLE
Typescript + es6 module, imports undefined -- not in namespace/module

### ISSUE THREAD

**Issue by dizzyone** [systemjs/systemjs#882]
I posted this problem in an issue for jspm, but after spending more time trying to figure out, I thought this might be a better place to ask.

When I create a SFX bundle, my imports don't seem to be defined correctly. The following Typescript code:

```javascript
/// <reference path="../../../typings/tsd.d.ts" />
/// <reference path="../core/core" />

import "angular";
import {Core} from "../core/core";
console.log(Core);
//...
```

will be transpiled as:
```javascript
$__System.register("1", ["8", "9"], function(exports_1) {
    var core_1;
    var AchmeaAPF;
    return {
        setters:[
            function (_1) {},
            function (core_1_1) {
                core_1 = core_1_1;
            }],
        execute: function() {
            console.log(Core); //Core is undefined
//...
        }
    }
});
```

If I transpile the same file using the typescript compiler, I get the following code:
```
System.register(["angular", "../core/core"], function(exports_1) {
    var core_1;
    var AchmeaAPF;
    return {
        setters:[
            function (_1) {},
            function (core_1_1) {
                core_1 = core_1_1;
            }],
        execute: function() {
            console.log(core_1.Core); //Core is part of the core_1 module as expected and should work now
        }
    }
});
```

Typescript does in fact transpile the Core export to core_1.Core, which seems to work, while SystemJS doesn't do this.

I'm using both jspm 0.16.12 and SystemJS builder 0.14.8 and they give me the same result creating an SFXbundle.

Not sure what I'm doing wrong but would appreciate any input.

**Comment by vadimpopa** [comment]
I think I have a similar issue, might be a systemjs issue or because of my configs. I posted on Ionic2  page https://github.com/driftyco/ionic2/issues/379, but perhaps here is more related:

The imports are empty
```javascript
__useDefault: true
default: Object
__proto__: Object
__proto__: Object
```

**Comment by guybedford** [comment]
@vadimpopa did you try running just `import ionic from 'ionic2'`?

**Comment by vadimpopa** [comment]
@guybedford thanks for suggestion, just tried that, and in the transpiled code the setters are empty, System.register also, 
```javascript
(function(System) {(function(__moduleName){System.register([], function(exports_1) {
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
        switch (arguments.length) {
            case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
            case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
            case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
        }
    };
    var __metadata = (this && this.__metadata) || function (k, v) {
        if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
    };
    var HelloIonicPage;
    return {
        setters:[],
```
with 
```javascript
import {Page, NavController} from 'ionic2/js/ionic';
```
the import object is empty

```javascript
(function(System) {(function(__moduleName){System.register(['ionic2/js/ionic'], function(exports_1) {
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") return Reflect.decorate(decorators, target, key, desc);
        switch (arguments.length) {
            case 2: return decorators.reduceRight(function(o, d) { return (d && d(o)) || o; }, target);
            case 3: return decorators.reduceRight(function(o, d) { return (d && d(target, key)), void 0; }, void 0);
            case 4: return decorators.reduceRight(function(o, d) { return (d && d(target, key, o)) || o; }, desc);
        }
    };
    var __metadata = (this && this.__metadata) || function (k, v) {
        if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
    };
    var ionic_1;
    var HelloIonicPage;
    return {
        setters:[
            function (ionic_1_1) {
                ionic_1 = ionic_1_1; //HERE IS EMPTY, BUT SHOULD RETURN Page and Nav
            }],
```

**Comment by guybedford** [comment]
That's really odd. How exactly are you using TypeScript here? The suggested way is actually through this plugin - https://github.com/frankwallis/plugin-typescript.

**Comment by dizzyone** [comment]
The plugin-typescript description is saying it allows you to load typescript in its non-transpiled form, what I would like is to transpile it and bundle it before loading it. Would plugin-typescript still be useful in this case?

**Comment by guybedford** [comment]
SystemJS Builder will use the plugin to build bundles, which will handle a lot of the quirks of managing a custom build task. A custom build task can work just as well, but it seems like these output issues may be related to configuration specifics with that process. For example, modules need to be named to form a bundle, whereas the output above is anonymous.

**Comment by dizzyone** [comment]
Thanks I'll give both a try. It sounds stupid, but I was wondering about the defining/naming modules, but wasn't sure what was meant with it. I tried defining modules in Typescript but at the time I was debugging these issues it didn't seem to make a difference.

**Comment by vadimpopa** [comment]
Yes, I'm using that plugin, wondering if could be a path issue with Ionic, will dig more in the next days.

**Comment by vadimpopa** [comment]
Tried a few format modules in Ionic2, in all of them I have problems, probably because of my configs. But I'm closer with the "esm" & typescript, seems there are path issues on imports, and asked on the plugin repo if there's a solution for this.
https://github.com/frankwallis/plugin-typescript/issues/53

**Comment by vadimpopa** [comment]
Tried a few format modules in Ionic2, in all of them I have problems, probably because of my configs. But I'm closer with the "esm" & typescript, seems there are path issues on imports, and asked on the plugin repo if there's a solution for this.
https://github.com/frankwallis/plugin-typescript/issues/53

**Comment by guybedford** [comment]
Sure, let me know if you make progress here.

**Comment by vadimpopa** [comment]
I advanced with loading the app in browser for both for typescript & es5+common, it was an issue in the typescript plugin and some wrong configs on my side, both fixed by @frankwallis, so we are good now.

**Comment by guybedford** [comment]
Great, thanks for the update.

**Comment by tom10271** [comment]
@vadimpopa I have the same issue. Which config you changed for solving this issue?

Originally I am using Angular 2 beta.16, everything works fine but facing this issue once I upgrade to Angular 2 RC.4.
