### ISSUE TITLE
analog to require.js callback configuration

### ISSUE THREAD

**Issue by dennispg** [systemjs/systemjs#883]
Is there an analog in systemjs for setting a callback after dependencies have loaded?
http://requirejs.org/docs/api.html#config-callback

I'm trying to guarantee that an additional set of modules are loaded whenever moduleA is loaded. The additional modules all have dependency on moduleA as well.

I tried using depCache, but the additional modules load asynchronously to moduleA.

I tried looking into writing a special load plugin, but am getting nowhere.

I can't find anything in the documentation to address a scenario like this. Am I missing something obvious?

**Comment by guybedford** [comment]
Do you mean something like - 

```javascript
var modules = ['modules', 'to 'callback', 'on'];
Promise.all(modules.map(function(module) {
  return System.import(module);
})).then(function(modules) 
  // ...
});
```

**Comment by dennispg** [comment]
well, no. it is more than that.. let me be more specific in what I'm trying to accomplish. I have some modules which define custom bindingHandlers for knockout, but the same could apply for something like jquery extensions or any code that defines overrides on a module.

anytime the module 'knockout' is imported, I want my modules to be subsequently and immediately loaded as well. the load of knockout should not complete until the callback completes.

For example:

```javascript
System.import('knockout')
.then(function(ko) {
  // by the time this code runs, knockout plus
  // anything i defined in the callback function would be fully loaded
});
```

I was able to define a callback function on a module shim with requirejs to accomplish this before.

**Comment by guybedford** [comment]
You can use metadata deps to add dependencies to any module via - 

```javascript
System.config({
  meta: {
    knockout: { deps: ['plugin'] }
  }
});
```

**Comment by dennispg** [comment]
tried that, the problem there is that 'plugin' also has a dep on knockout, and so knockout comes up null inside the plugin module.

**Comment by guybedford** [comment]
A better workflow might be to create a wrapper module that captures the dependency tree on knockout and the plugins, which you then require.

**Comment by dennispg** [comment]
tried this also, although I think I'm doing it wrong..

I want 'knockout' to be the module that triggers the wrapper..  how can I properly alias the actual 'knockout' budtje brought in my jspm?

**Comment by guybedford** [comment]
You can use package configuration to alias `knockout` just for a specific package, to point to a new `knockout-wrapper.js` file for example.

This is like the contextual map configuration in RequireJS.

See https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages for how to use package configuration.

**Comment by dennispg** [comment]
Thank you so much for taking the time to help, but I still cant get this to work:
```javascript
System.config({
    map: {
        "knockout": "js/knockout-wrapper"
    },
    packages: {
        'js/knockout-wrapper': {
            format: 'amd',
            map: {
                'knockout': "github:knockout/knockout@3.3.0"
            },
            modules: {
                'js/ko-extensions/*': {
                    map: {
                        'knockout': "github:knockout/knockout@3.3.0"
                    }
                }
            }
        }
    }
});
```

**Comment by dennispg** [comment]
Sorry, I got it now. I wasnt understanding the documentation at https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#packages.

'local/package' in that document seems to imply a folder, where I was thinking I could specify a file. Instead, main would be 'knockout-wrapper' located inside the 'local/package' folder, and everything under that folder would get the packages specific config.

Here is what I used which worked, in case it is helpful for others:
```javascript
var ko_path = System.map.knockout; // to use the jspm path
System.config({
    map: {
        "knockout": "js/ko-extensions"
    },
    packages: {
        'js/ko-extensions': {
            main: 'knockout-wrapper',
            format: 'amd',
            map: {
                'knockout': ko_path
            },
            modules: {
                'js/ko-extensions/*': {
                    map: {
                        'knockout': ko_path
                    }
                }
            }
        }
    }
});
```

Thanks Guy!
