### ISSUE TITLE
Error loading global modules in CSP Production mode

### ISSUE THREAD

**Issue by ALibrada** [systemjs/systemjs#885]
Hello,

I have been working a couple of days on trying to load a global module with SystemJS using "system-csp-production.js" but I had no luck. I have also isolated it in a simple project and I always get the following error:

```
Uncaught (in promise) Error: http://www.google-analytics.com/analytics.js did not call System.register or AMD define(…)
```

It works using "system.js" but not with CSP Production.
Here are my configuration files:
```javascript
System.config({
  baseURL: "/resources",
  defaultJSExtensions: true,
  transpiler: "traceur",
  paths: {
    "github:*": "jspm_packages/github/*"
  },
  meta: {
    "//www.google-analytics.com/analytics.js": {
      "format": "global",
      "exports": "ga"
    }
  },
  map: {
    "traceur": "github:jmcriffey/bower-traceur@0.0.92",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.92"
  }
});
```

The files are being loaded this way:
```html
<html>
<head>
    <script src="./jspm_packages/system-csp-production.js"></script>
    <script src="./config.js"></script>
    <script>
        System.import('//www.google-analytics.com/analytics.js');
    </script>
</head>
</html>
```

I don't know if I am doing something wrong, I tried to follow the documentation for this part but I had no luck with it.

Thanks in advance.

**Comment by guybedford** [comment]
Google analytics doesn't load like a normal script unfortunately. See https://github.com/HeinrichFilter/systemjs-plugin-googlemaps for a plugin aiming to provide this support. Previous discussion at https://github.com/systemjs/systemjs/issues/424.
