### ISSUE TITLE
babel/polyfill not included?

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#886]
I want to use the new ES2015 `Array.prototype.find()` method on arrays. This method is [not supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) by the current Android Browser but it can be [polyfilled](https://github.com/paulmillr/Array.prototype.find). This polyfill is also included in [es6-shim](https://github.com/paulmillr/es6-shim) and this one is included in [babel/polyfill](http://babeljs.io/docs/usage/polyfill/).

The docs about that say

```
To include the polyfill you need to require it at the top of the entry point to your application.

require("babel/polyfill");

Fortunately, this is also automatically loaded when using the require hook.
```

So my thought was that this all will be loaded if I use SystemJS. But it seems to be not. `Array.prototype.find()` is always undefind as long I don't make a `import 'babel/polyfill'` in my source file.

Is this behavior as intended or do I missing something?

**Comment by guybedford** [comment]
SystemJS just uses the transpilation of Babel.

If using the modular runtime, the best route here is to require just that specific function from core-js directly.

If using the full polyfill route, then you'd need to require it that way otherwise.

**Comment by screendriver** [comment]
> If using the modular runtime, the best route here is to require just that specific function from core-js directly.

What do you mean with `modular runtime`? How can I use that?

**Comment by guybedford** [comment]
Babel uses core-js. By default jspm will run Babel in a way that will use core-js as a separate package, so you can just require individual modules from core-js itself.

If not using jspm though, the above workflows are tricky, and you are better off just including the blanket polyfill as described in http://babeljs.io/docs/usage/polyfill/.
