### ISSUE TITLE
thrown values don't propagate up to the browser

### ISSUE THREAD

**Issue by BigBen1307** [systemjs/systemjs#888]
Values that are thrown don't get propagated up to the browser. Script execution just stops silently. 

[Example](http://jsbin.com/bamifefelu/edit?html,console,output)

HTML:
```Html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>systemjs throw bug</title>
  <script src="https://rawgit.com/systemjs/systemjs/master/dist/system.js"></script>
</head>
<body>
  <script>
    System.import('https://rawgit.com/anonymous/21a9cd303fc00421878a/raw/fa4aa889ee1102740ba5542cf6ee45ec96b281d7/jsbin.muboyopihi.js')
      .then(function (a)
        {
          a.main();
        }
      );
  </script>
</body>
</html>
```

JS
```Javascript
System.register([], function(exports){
  function main()
  {
    console.log('before');
    throw new Error();
    console.log('after');
  }
  exports("main", main);
  return {
    setters: [],
    execute: function(){}
  };
});
```

**Comment by guybedford** [comment]
Thanks for putting this together. Did you try adding a catch handler to the `System.import` statement?

**Comment by BigBen1307** [comment]
Yes, still no output.

http://jsbin.com/rihiwolodi/1/edit?html,console,output

**Comment by guybedford** [comment]
Because the error is in the then function, you'd need a separate `.catch` handler.

**Comment by BigBen1307** [comment]
Sorry, you are right. The next handler catches it.

I guess this is expected since this is a Promise based API? Will this be the normal behaviour with the future native Loader API?

**Comment by guybedford** [comment]
Yes it's entirely how promises work. There are uncaught exception handlers for these cases though, but it obviously didn't work here.

**Comment by BigBen1307** [comment]
I think it could be a bit confusing for library users if there are errors that get thrown explicitly by the library author and people don't see it because they forgot to add handlers for their imports - like i did :). But i guess this is a problem for the Promise implementation and not for SystemJS.
