### ISSUE TITLE
Loading global format module on a iframe throws exception.

### ISSUE THREAD

**Issue by edba** [systemjs/systemjs#890]
Using systemjs on an iframe and having a dependency with global format will result in this js exception:

*Blocked a frame with origin "your.iframe.domain" from accessing a frame with origin "your.parent.domain". Protocols, domains, and ports must match.*

This is thrown when trying to read the frameElement attribute from the window object.

Would it be possible to add **frameElement** to the **ignoredGlobalProps** array, to prevent this exception?

**Comment by guybedford** [comment]
Thanks for the suggestion, added above.

**Comment by davis** [comment]
even with that change i'm still running into this exception...
any ideas?

**Comment by guybedford** [comment]
Released in 0.19.6.
