### ISSUE TITLE
Does System.delete no longer work for stubbing modules in tests?

### ISSUE THREAD

**Issue by togakangaroo** [systemjs/systemjs#893]
I used to have the following in my unit tests's `beforeEach`

                const stubbedStores = (..generate a stubbed object...)
		System.delete('myStores')
		System.set('myStores', System.newModule({ default: stubbedStores }))

		System.delete('myEditors') //depends on myStores
		System.import('myEditors').then(({default: {foo}}) =>{
			instance = create(foo, {});
			rendered = ReactTestUtils.renderIntoDocument(instance);
			dom = () => rendered.getDOMNode();
			done();
		})

So I was basically stubbing out the `myStores` module, ensuring it was not in SystemJs, Then I'd populate it with a newly created stub. Then I'd remove the module I actually want to test from SystemJs so it would load again pulling in the newly created stub as a dependency.

The test runner was broken for a few weeks during which we went through some upgrades and now this setup doesn't seem to work. Tracing through the code I see this works the first time (which is to be expected so long as `set` still works) but the second time through neither of the `System.delete` calls seem to remove the previously registered modules and my editors components simply get back the same instance of stores from the first test.

So

* Am I even doing this remotely right? Should I be doing something else?
* What changed? What's the proposed solution?

**Comment by guybedford** [comment]
What changed here was the normalization in SystemJS 0.17, see https://github.com/systemjs/systemjs/releases/tag/0.17.0.

The fix is to use `System.set(System.normalizeSync('x'), System.newModule({}))`.

**Comment by togakangaroo** [comment]
I see. That works, thanks
