### ISSUE TITLE
on IE8 Error message is not formatted.

### ISSUE THREAD

**Issue by d3trax** [systemjs/systemjs#894]
On IE 8 using polyfills.js error message is incorrectly formatted due error object not contains stack parameter http://s13.postimg.org/cdrm8iw7b/snapshot8.png

According document http://www.ecma-international.org/publications/files/ECMA-ST-ARCH/ECMA-262,%203rd%20edition,%20December%201999.pdf Error object contains message attribute.

I'm tried to fix this adding message parameter check to formatError
https://github.com/d3trax/systemjs/blob/92e81c84140b6d88d59ae7b91f3a65f942a56f5d/dist/system-polyfills.src.js#L376
it works, but don't know if its backward compatible change.

**Comment by guybedford** [comment]
Posted https://github.com/cujojs/when/pull/472.

**Comment by guybedford** [comment]
Released in 0.19.7.
