### ISSUE TITLE
`require` being run before the module containing it is required.

### ISSUE THREAD

**Issue by phenomnomnominal** [systemjs/systemjs#896]
I am using plugin-text to inline a liquid template in a bundle. The template is for the contents of an iframe, stored as a string, and contains something along the lines of `require('{{ dependency.path }}');`

When the bundle containing the template is pulled into the browser by System, a request to `http://localhost:3000/%7B%7B%20dependency.path%20%7D%7D.js` is made. If I change the code to something like `(r = require, r('{{ dependency.path }}');` then everything works as expected, so I'm thinking that something must be looking for `require` calls within the source so that they can be preloaded or something?

I've managed to get around it so that I don't actually need the `require` call in the template, but figured that I should raise the issue anyway.

**Comment by guybedford** [comment]
@phenomnomnominal I believe this issue was actually fixed in a recent release of plugin-text by switching to AMD as the wrapper format. Are you running the latest version?

**Comment by phenomnomnominal** [comment]
You're totally right! Duh, thanks for that, sorry for wasting your time!
