### ISSUE TITLE
dagre-d3 dependency d3 is not getting loaded

### ISSUE THREAD

**Issue by myitcv** [systemjs/systemjs#897]
I notice #741 which might be related.

```
    "jspm": "0.16.14",
    "systemjs": "0.19.5",
```

As a simple repro, `jspm install npm:dagre-d3`. You will notice from `config.js` that `d3` is listed as a dependency:

```
    "dagre-d3": "npm:dagre-d3@0.4.10",
...
    "npm:dagre-d3@0.4.10": {
      "d3": "npm:d3@3.5.6",
      "dagre": "npm:dagre@0.7.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "graphlib": "npm:graphlib@1.0.7",
      "lodash": "npm:lodash@3.10.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
```

Using this simple TypeScript example:

```typescript
import "dagre-d3";

export function Run(): void {
	console.log("Running browser");
}
```

which gets transpiled to [this](https://gist.github.com/myitcv/abde649d718bd30685f6), then setting a breakpoint in Chrome on the `console.log` line. 

What I observe is that `d3` has not been loaded at this breakpoint, at least these facts lead me to believe so:

* the network tab in Chrome debugger does not show that the file has been loaded
* the `d3.js` source file (within `npm/d3@3.5.6`) is not present in the 'Sources' tab
* `window.d3` is `undefined`

This obviously breaks `dagre-d3` because it is relying on `d3` having been loaded (and available via `window.d3`)... But given the dependency tree above it would seem to suggest it _should_ have been loaded. 

Of the dependencies above, I can see the following have been loaded:

```
"process": "github:jspm/nodelibs-process@0.1.2"
"lodash": "npm:lodash@3.10.1"
"graphlib": "npm:graphlib@1.0.7"
"dagre": "npm:dagre@0.7.4"
```

whereas two, including `d3`, have not:

```
"fs": "github:jspm/nodelibs-fs@0.1.2"
"d3": "npm:d3@3.5.6"
```

Am I missing something?

Any help much appreciated!

**Comment by guybedford** [comment]
`System.import('dagre-d3')` seems to work absolutely fine for me. Perhaps try `jspm install npm:dagre-d3 -f` to clear the cache. Note that this is a jspm issue not a SystemJS issue.

**Comment by myitcv** [comment]
Closing this here and moving conversation to https://github.com/jspm/jspm-cli/issues/1280
