### ISSUE TITLE
Evaluation exception when bundling CSS

### ISSUE THREAD

**Issue by philiphendry** [systemjs/systemjs#898]
I'm working on an Aurelia application which runs and bundles fine on my Windows 10 laptop but fails to bundle on my TFS build server with the following error:

    [16:40:37] Error: Install Clean CSS via `jspm install npm:clean-css --dev` for CSS build support. Set System.buildCSS = false to skip CSS builds.
        at evalmachine.<anonymous>:94:11
        at process._tickCallback (node.js:366:9)

In the past when I've seen that message, I've followed the instruction and everything has worked. This time, however, clean-css is already installed. Here's my `package.json` for reference:

    {
      "jspm": {
        "dependencies": {
          "aurelia-bootstrapper": "github:aurelia/bootstrapper@^0.18.0",
          "aurelia-event-aggregator": "github:aurelia/event-aggregator@^0.9.0",
          "aurelia-fetch-client": "github:aurelia/fetch-client@^0.3.0",
          "aurelia-framework": "github:aurelia/framework@^0.17.0",
          "aurelia-history-browser": "github:aurelia/history-browser@^0.9.0",
          "aurelia-http-client": "github:aurelia/http-client@^0.12.0",
          "aurelia-loader-default": "github:aurelia/loader-default@^0.11.2",
          "aurelia-logging": "github:aurelia/logging@^0.8.0",
          "aurelia-logging-console": "github:aurelia/logging-console@^0.8.0",
          "aurelia-router": "github:aurelia/router@^0.13.0",
          "aurelia-task-queue": "github:aurelia/task-queue@^0.8.0",
          "aurelia-templating-binding": "github:aurelia/templating-binding@^0.16.1",
          "aurelia-templating-resources": "github:aurelia/templating-resources@^0.16.1",
          "aurelia-templating-router": "github:aurelia/templating-router@^0.17.0",
          "aurelia-validation": "github:aurelia/validation@^0.4.0",
          "bootstrap": "github:twbs/bootstrap@^3.3.5",
          "css": "github:systemjs/plugin-css@^0.1.19",
          "dragula": "npm:dragula@^3.5.3",
          "fetch": "github:github/fetch@^0.10.1",
          "font-awesome": "npm:font-awesome@^4.4.0",
          "highcharts": "npm:highcharts-release@^4.1.9",
          "jquery": "github:components/jquery@^2.1.4",
          "lodash": "npm:lodash@^3.10.1",
          "lolliclock": "github:philiphendry/lolliclock@^0.1.0",
          "moment": "npm:moment@^2.10.6",
          "philiphendry/lolliclock": "github:philiphendry/lolliclock@^0.1.0",
          "polymer/mutationobservers": "github:polymer/mutationobservers@^0.4.2",
          "sanitize-html": "npm:sanitize-html@^1.11.1",
          "sweetalert": "github:t4t5/sweetalert@^1.1.3",
          "text": "github:systemjs/plugin-text@^0.0.3",
          "toastr": "github:codeseven/toastr@^2.1.2"
        },
        "devDependencies": {
          "babel": "npm:babel-core@^5.8.24",
          "babel-runtime": "npm:babel-runtime@^5.8.24",
          "clean-css": "npm:clean-css@^3.4.6",
          "core-js": "npm:core-js@1.2.5"
        },
        "overrides": {
          "npm:highcharts-release@4.1.9": {
            "main": "highcharts"
          }
        }
      },
      "devDependencies": {
        "aurelia-bundler": "^0.1.8",
        "aurelia-tools": "^0.1.14",
        "del": "^2.0.2",
        "gulp": "^3.9.0",
        "gulp-babel": "^5.3.0",
        "gulp-changed": "^1.3.0",
        "gulp-notify": "^2.2.0",
        "gulp-plumber": "^1.0.1",
        "gulp-sourcemaps": "^1.6.0",
        "jspm": "^0.16.14",
        "object.assign": "^4.0.3",
        "require-dir": "^0.3.0",
        "run-sequence": "^1.1.4",
        "vinyl-paths": "^2.0.0"
      },
      "dependencies": {},
      "name": "",
      "version": "1.0.0",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "Philip Hendry",
      "license": "",
      "description": ""
    }

I've dug around in `system.src.js` and noticed that some error information wasn't being reported so modified it slightly:

    // global scoped eval for node
    var vmModule = 'vm';
    var vm = require(vmModule);
    __exec = function(load) {
      if (load.metadata.integrity)
        throw new TypeError('Subresource integrity checking is unavailable in Node.');
      try {
        preExec(this, load);
        vm.runInThisContext(getSource(load));
        postExec();
      }
      catch(e) {
        postExec();
        console.log("Whoops : \n" + load.address + "\n" + e.toString());
        throw addToError(e.toString(), 'Evaluating ' + load.address);
      }
    };

I've added the `console.log()` and now get the following error when I run my `gulp bundle` (which incidently is running an `aurelia-bundler` gulp task) and is including css with `**/*.css!text`:

[16:40:24] Using gulpfile C:\tfsbuild\AdminSite\gulpfile.js
    [16:40:24] Starting 'bundle'...
    Whoops :
    file:///C:/tfsbuild/AdminSite/jspm_packages/github/jspm/nodelibs-https@0.1.0.js
    SyntaxError: Invalid regular expression: missing /

    C:\tfsbuild\AdminSite\node_modules\jspm\node_modules\systemjs\dist\system.src.js:1407
            throw addToError(e.toString(), 'Evaluating ' + load.address);
            ^
    Whoops :
    file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/imports/inliner.js
    SyntaxError: Invalid regular expression: missing /
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/github/jspm/nodelibs-https@0.1.0.js
    Whoops :
    file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/clean.js
    SyntaxError: Invalid regular expression: missing /
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/github/jspm/nodelibs-https@0.1.0.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/imports/inliner.js
    Whoops :
    file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/index.js
    SyntaxError: Invalid regular expression: missing /
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/github/jspm/nodelibs-https@0.1.0.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/imports/inliner.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/clean.js
    Whoops :
    file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6.js
    SyntaxError: Invalid regular expression: missing /
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/github/jspm/nodelibs-https@0.1.0.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/imports/inliner.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/lib/clean.js
            Evaluating file:///C:/tfsbuild/AdminSite/jspm_packages/npm/clean-css@3.4.6/index.js
    [16:40:37] 'bundle' errored after 13 s
    [16:40:37] Error: Install Clean CSS via `jspm install npm:clean-css --dev` for CSS build support. Set System.buildCSS = false to skip CSS builds.
        at evalmachine.<anonymous>:94:11
        at process._tickCallback (node.js:366:9)

I can only take a wild stab-in-the-dark at this error but I think it's trying to `eval()` some module imports but failing to interpret the javascript correctly?? For example, if I take a look in the `inliner.js` file mentioned in the errors then I see this at the top:

    /* */ 
    (function(process) {
      var fs = require('fs');
      var path = require('path');
      var http = require('http');
      var https = require('https');
      var url = require('url');
      var rewriteUrls = require('../urls/rewrite');
      var split = require('../utils/split');
      var override = require('../utils/object').override;
      var MAP_MARKER = /\/\*# sourceMappingURL=(\S+) \*\//;
      var REMOTE_RESOURCE = /^(https?:)?\/\//;
      var NO_PROTOCOL_RESOURCE = /^\/\//;
      function ImportInliner(context) {
        this.outerContext = context;

Could it be that the `#` in `MAP_MARKER`, or some other character, is being interpreted as a comment and therefore the regex is never closed?

I'm honestly pushing the boundaries of my current knowledge in this field but I'll happily help where I can. Before I go here are some versions I'm using :

* node v4.2.1
* npm v3.3.10
* jspm v0.16.14
* gulp v3.9.0

**Comment by guybedford** [comment]
I've added a better error message for this in https://github.com/systemjs/plugin-css/commit/3ed425467b4341e4bee009f267c3b6c992ef8402.

I'm not sure how the underlying issue is coming up though, and haven't heard of anything like this before. Perhaps check that the file contents are exactly correct as expected? Or perhaps you can try removing lines in the source until that specific error goes away to try and isolate it? Unfortunately there is not a lot here to test it without an isolation case.

**Comment by guybedford** [comment]
Closing as I can't replicate the underlying issue, but if you come up against it again and can share an exact replication that would be a great help.

**Comment by philiphendry** [comment]
Thanks @guybedford. I'm up against the wall with trying to get business functionality working so this has gone on the back burner. I'll come back to it and try and replicate in the future though. Many thanks for taking a look.
