### ISSUE TITLE
System.import in node enviroment dont append file extention

### ISSUE THREAD

**Issue by forceuser** [systemjs/systemjs#901]
Example from readme.md for node not working 

    var System = require('systemjs');
    System.transpiler = "traceur";

    System.import("./app").then(function(){
        console.log("SYSTEM");
    },function(e){
        console.log(e);
    });

error in console:
[Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/app']

if i rewrite it to 

    System.import("./app.js").then(function(){
        console.log("SYSTEM");
    },function(e){
        console.log(e);
    });

all works fine

systemjs version 0.19.5

**Comment by guybedford** [comment]
Thanks, I've updated the README. Extensions are only added by default for packages.
