### ISSUE TITLE
importing folder module

### ISSUE THREAD

**Issue by MadMub** [systemjs/systemjs#902]
Not sure if this is something solved via some config. Some dependencies, and much of my own code likes the convention of a given folder module having the first point of entry being index.js. Wondering if it's possible to import as follows:
```
import './app';
// or
require('./app');
// instead of
import './app/index';
```
It's not a huge issue for personal code, but dependencies written with ```require('./folder')``` don't seem to work unless I manually update them to ```require('./folder/index')```.

Again this could just be some config option I'm not aware of, and also like to mention overall what an amazing project.

**Comment by fictitious** [comment]
Yes there is config option for that: https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#map

something similar to this in config.js works for me:

        System.config({
                ...
                map: {
                      './app': './app/index.js'
                }
         });

**Comment by guybedford** [comment]
Package config is the recommended way to handle this:

```javascript
System.config({
  packages: {
    'app': {
      main: 'index'
    }
  }
});
```

**Comment by jmcooper** [comment]
Is there a reason why this requires a config instead of updating SystemJs to recognize packages by the existence of index? Even if you don't want to accept the standard of "index.js" as the name, a global default where a user could specify "index" or some other value would be nice so we don't have to create a package for every folder that contains an index.js.  Still, I think it'd make sense to make index the default and just recognize those packages without the need of additional config.

**Comment by guybedford** [comment]
Global-level defaults become implicit assumptions in package creation. It might be nice to create an ES module package assumption that uses the package name as the main to avoid the issue of having multiple `index.js` files indistinguishable in a code editor. By making this an explicit configuration, we pave the road the default to be changed in this way in future, and we can add that default at any time (as soon as there seems to be momentum behind it).

**Comment by sclausen** [comment]
The thing is, sometimes it's not in our power to decide against using folder modules. Some extertal modules like MQTT.js for example have them and without browserifying the package, which needs requires to set up another build task, its not possible to use. As far as I know... Maybe I'm missing something.

**Comment by guybedford** [comment]
@sclausen yes certainly this is a problem that is up to tooling to solve. It is just not the responsibility of SystemJS. Better tooling around SystemJS is needed here rather.

**Comment by Marak** [comment]
RE: https://github.com/Marak/faker.js/issues/472
