### ISSUE TITLE
import { Component } from 'react' failing

### ISSUE THREAD

**Issue by JHKennedy4** [systemjs/systemjs#904]
`import React from 'react'` works fine, and `React.Component` is then defined, but I can't get the `import { member } from 'module'` syntax to work.

I've been able to use this syntax with Webpack before and it seems to be part of the spec (at least as documented at MDN), but this is my first time using systemjs and I'm not entirely clear on what syntax is build tool specific vs part of the spec.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by JHKennedy4** [comment]
This is likely relevant: https://discuss.reactjs.org/t/es6-import-as-react-vs-import-react/360/3

**Comment by stoiet** [comment]
import React, { Component } from 'react'; is a valid format and it works fine for me with System.js

**Comment by JHKennedy4** [comment]
Probably my fault then. Could it have something to do with jspm? Not sure
why I'm seeing this issue.

**Comment by guybedford** [comment]
It's also worth ensuring you're running the latest version of SystemJS here. Closing but if you're able to share a test case that would be great, but this is working fine for me too unfortunately otherwise.
