### ISSUE TITLE
SystemJS fails to import files which have block comments w/ lines beginning with 'export'

### ISSUE THREAD

**Issue by ntilwalli** [systemjs/systemjs#910]
SystemJS (v0.19.5) fails to import a file when the file has a multi-line block comment where any line other than the first line in the block-comment starts with the string `/^\s*export (class|function|var)/`.

I've posted a replication repository at: https://github.com/ntilwalli/systemjsIssue

There is more complete description of the issue there, but the examples below may suffice.

Example code which fails:
```
define(["require", "exports"], function (require, exports) {
    var App = (function () {
        function App() {
            console.log("Just testing...");
        }
        return App;
    })();
    exports.App = App;
});
/*
  export class */
```
Example code which does not fail:
```
define(["require", "exports"], function (require, exports) {
    var App = (function () {
        function App() {
            console.log("Just testing...");
        }
        return App;
    })();
    exports.App = App;
});
/*
  blah export class */
```

**Comment by ntilwalli** [comment]
You can also see the issue in this plunker: http://plnkr.co/edit/0y4sUolRNh56TO6DLrlR?p=preview

Open the dev console in Chrome and just toggle the comment in `app.js` between the examples where it works, like this one (because the first line of a block comment is handled correctly):
```
/*export function */
```
... and this one (because lines which don't explicitly start with `/^\s*export (class|function|var)/` are handled correctly):
```
/*
random string export function */
```
... and this one where it fails to load app.js properly and doesn't print out the expect console output:
```
/*
export function */
```

**Comment by guybedford** [comment]
Module format detection in SystemJS is not designed to be 100% accurate, it is designed to cater to the majority use case.

We detect formats in order of ES Module, System.register, AMD, CommonJS and global.

When this detection is incorrect, simply set the format via configuration rather, which is recommended anyway usually as well.

**Comment by Slumber86** [comment]
I have an issue related to this. if the file has ha leading comment, it will marked always as Global module and fail. 
ES: 
This not fail: 
```javascript
System.register([], function (_export) {
    /**
        Created by b.amico on 2015-07-16
        - v 1.1.0 edited on 2015-09-02
    **/

...

```

This will fail: 
```javascript
    /**
        Created by b.amico on 2015-07-16
        - v 1.1.0 edited on 2015-09-02
    **/
System.register([], function (_export) {
...
```

**Comment by ntilwalli** [comment]
Ah.  I now understand that you don't do comment detection at all.  I was assuming the comment detection algorithm was flawed.  This makes sense considering the format ordering you gave.  This issue came up because I'm transpiling from ES6 to AMD, so code I comment out is in one format and the live-code is in another (but the comments are left intact).  I assume the performance hit of comment filtering makes that a no-go.  I'll look into the configuration approach.

**Comment by guybedford** [comment]
@Slumber86 are you definitely running the latest version of SystemJS? I just tested your case and it is working fine for me - we do do comment removal checking for the System.register format to enable these cases.

@ntilwalli yes it is specifically ES module detection that does no comment removal.

**Comment by Slumber86** [comment]
Yes I'm using the last vesion of SystemJS and babel 6 SystemJS plugin

**Comment by guybedford** [comment]
@Slumber86 the following module loads completely fine for me - 

```javascript
    /**
        Created by b.amico on 2015-07-16
        - v 1.1.0 edited on 2015-09-02
    **/
System.register([], function (_export) {
  return {
    setters: [],
    execute: function() {
      _export('some', 'value');
    }
  };
});
```

if I save that as `test.js` and load it. So I'm not sure how this might have been happening for you unless you were using an older version of SystemJS before.
