### ISSUE TITLE
error copying properties of window

### ISSUE THREAD

**Issue by jdanyow** [systemjs/systemjs#911]
Is this a bug?
![error](http://i.imgur.com/ShkVSxz.png)

The plunker works in Edge and Firefox but hits the error above in chrome.  It works in chrome if the `--disable-web-security` flag is used.

Wondering if this error should be caught and the property skipped?

http://plnkr.co/edit/BglBnp?p=preview

If I change it to `if ((p !== 'frameElement') && (d = Object.getOwnPropertyDescriptor(exports, p)))` the plunker works.  Probably not the correct approach but was worth checking whether there were any other problems.  

For whatever reason this kind of plunker worked with an earlier version of systemjs- here's a link: http://plnkr.co/edit/LnqV8R?p=preview

**Comment by guybedford** [comment]
Yes this is a bug. It was fixed in the upcoming release via https://github.com/systemjs/systemjs/commit/a217ac0e64d881b7880c7a19d6863d338f4b5ef6.

**Comment by jdanyow** [comment]
awesome- thanks!

**Comment by guybedford** [comment]
Sure! I'll leave this open to track the release of the fix.

**Comment by guybedford** [comment]
Released in 0.19.6.
