### ISSUE TITLE
How to use SystemJS and ES2015 in Web workers?

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#913]
I want to use [Web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) in my project but don't get it running with SystemJS and ES2015 / Babel.

I've got a Web Worker script called `myworker.js` and tried following:

```js
importScripts('jspm_packages/system.js', 'config.js');

onmessage = (e) => {
  postMessage('bar');
}
```

but it tells me a SyntaxError because the arrow function is ES2015. Another option would be to have one "entry" worker script like

```js
importScripts('jspm_packages/system.js', 'config.js');

onmessage = function(e) {
  System.import('./real-worker-code.js');
}
```

and to use ES2015 syntax in `real-worker-code.js`. But that doesn't work as well.

Is there something missing or is this generally not supported at the moment? Furthermore I can't use ES2015 `import`s, right?

**Comment by guybedford** [comment]
The second example is the way to do this - `System.import('code')` inside of the web worker.

Perhaps try adding a rejection handler to the promise if it helps to see what might be causing the issue.

**Comment by screendriver** [comment]
#### index.js

```js
const worker = new Worker('js/myworker.js');
worker.onmessage = ev => {
  console.log(ev);
};
worker.postMessage(null);
```

#### myworker.js

```js
importScripts('jspm_packages/system.js', 'config.js');

onmessage = function() {
  System.import('./babelworker')
    .then(function() {
      console.log('Yes')
    })
    .catch(function(error) {
      console.error(error)
    });
};
```
#### babelworker.js

```js
class Test {
  doSomething(cb) {
    cb('Hello');
  }
}

console.log(new Test().doSomething(text => console.log(text)));
```

Gives me a

```
Error: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Function (native)
    at l.o (file:///android_asset/www/jspm_packages/system.js:4:16110)
    at o.execute (file:///android_asset/www/jspm_packages/system.js:5:6727)
    at i (file:///android_asset/www/jspm_packages/system.js:4:31855)
    at n (file:///android_asset/www/jspm_packages/system.js:4:30420)
    at Object.Promise.all.then.execute (file:///android_asset/www/jspm_packages/system.js:5:3451)
    at b (file:///android_asset/www/jspm_packages/system.js:4:9948)
    at w (file:///android_asset/www/jspm_packages/system.js:4:10327)
    at p (file:///android_asset/www/jspm_packages/system.js:4:8205)
    at h (file:///android_asset/www/jspm_packages/system.js:4:8590)
	Evaluating file:///android_asset/www/js/babelworker.js
	Error loading file:///android_asset/www/js/babelworker.js
```

**Comment by screendriver** [comment]
I've created a test browser project. There it seems to work :confused: I think I have a problem with my cordova project and my `config.js`. I will investigate my cordova project more in detail and let you know if it's working there.

**Comment by screendriver** [comment]
I've made it :+1:

**Comment by alexisargyris** [comment]
I'm trying to follow the steps of @screendriver in a browser project and I get:

````
Uncaught ReferenceError: System is not defined
````
in "myworker.js".

Any idea what could be wrong?

**Comment by screendriver** [comment]
Could you make a [Gist](https://gist.github.com/) or a sample project?

**Comment by alexisargyris** [comment]
Have a look [here](https://gist.github.com/alexisargyris/e596edc5a9dc10588d27). It's copy / paste your code really.

Thanks a lot for your time.

**Comment by screendriver** [comment]
I can see that you are importing the two scripts `'/jspm_packages/system.js'` and `'/config.js'` with a leading slash. [importScripts()](https://developer.mozilla.org/en-US/docs/Web/API/WorkerGlobalScope/importScripts) imports the scripts relatively to the current script so you don't need that.

**Comment by alexisargyris** [comment]
Yes, you were right, thanks a lot.

(I was overlooking a detail in the set up of the application that I abstracted away in "app.js").

So, SystemJS and ES2015 / Babel is a perfectly usable option from inside a Web worker!

**Comment by screendriver** [comment]
:+1:

**Comment by geometryzen** [comment]
@guybedford
Firstly, Thanks for your great work and answering these questions! 

Using the Gist as my starting point (with "use strict" in the update.js to avoid the Block-scoped declarations problem), I tried a slightly more complex scenario:

Create a sub-folder, e.g. 'down' as a sibling of jspm_packages and put both the workers in there. Modify the importScripts call by prepending a '/' to both paths in order to load system.js and config.js, and modify app.js so that the url is 'down/loader.js'.
The problem I am finding is that http-server is being requested to GET "/down/jspm_packages/npm/bable-core@5.8.34.js". Is this a bug? Do I need to use a different config.js with a baseURL?, or something else? Thx.

**Comment by guybedford** [comment]
@geometryzen sure no problem. By default the `baseURL` is the current URI of the given worker script. So if the script is at `down/x` then the baseURl will be that folder. This is to provide compatibilty with standard relative URL loading in browsers (where `./x` and `x` are both page-relative).

**Comment by peteruithoven** [comment]
@screendriver how do you bundle / build with your approach? 
How do you forward messages to and from the code you're loading in the web worker? 
Won't you miss messages since the System.import is async?

**Comment by geometryzen** [comment]
Peter,

My first postMessage to the thread includes the following;

scriptImports: string[]
moduleName: string

scriptImports include a URL for system.js as well as other modules that I
want to load. My other modules are bundled in the System.register format
using Guy's bundler.

In the worker thread file I first call

importScripts(scriptImport) for each in scriptImports.

I believe this runs synchronously, if it doesn't I don't know why my code
works!

I then call System.import with a callback. When the callback fires I grab
my module.

I then post a message back to the main thread So yes, it's synchronous, but
it can be controlled.

There's a bit more to it than that but that's mostly irrelevent
architectural details.

See ace-workers here...

https://github.com/ace2ts

David

**Comment by geometryzen** [comment]
Oops, I meant "it's asynchronous". Sorry.

**Comment by peteruithoven** [comment]
That sounds like it requires a lot of boilerplate in your worker code, specific to SystemJS? Have you tried to abstract this away in a loader plugin? 
In you're approach there is a change the worker you load misses messages that where send while the worker is loading right? 
I still don't understand how this works when bundling / building. 

My colleague has also been battling with this issue and he has come up with 2 alternatives: https://github.com/systemjs/systemjs/issues/1330#issuecomment-228342628
We're curious what you think.

**Comment by geometryzen** [comment]
Peter,
It seems that aside from the use of Blob(s), we are dealing with the same
sort of architecture and issues. I haven't tried to abstract into a loader
plugin because I have a standardized web worker file; the module URL and
class name to instantiate are parameters, so I've only got one piece of
web-worker code. In addition, I have only two scripts to import; the
system.js and the implementation (a bundle) so I'm not worrying about the
time to load two files over one.

Unlike you, I haven't gone the Blob route, and in truth I don't understand
all the issues there.

I think we have the same issues with queueing messages until a response
comes back from the thread. Promises in the main thread seem to be a nice
way clean up the code.

David
