### ISSUE TITLE
Babel 6.x support

### ISSUE THREAD

**Issue by screendriver** [systemjs/systemjs#914]
Are there any plans to support the shiny new Babel 6.x [release](http://babeljs.io/blog/2015/10/29/6.0.0/)?

**Comment by guybedford** [comment]
A plugin for Babel 6 is under development yes.

**Comment by Reinmar** [comment]
Why is this ticket closed? Keeping it open would help with tracking the status of the integration.

**Comment by guybedford** [comment]
It's not strictly a feature of this project, since we are moving transpilation out to plugins, which is being tracked in https://github.com/systemjs/systemjs/issues/579. The plugin progress can be tracked at https://github.com/systemjs/plugin-babel.
