### ISSUE TITLE
plugin delimiter clashes with valid uri character

### ISSUE THREAD

**Issue by anpross** [systemjs/systemjs#918]
usage of the "!" character as a delimiter for the plugin name makes it impossible to use this "!" character in "baseUrl" config parameter. (system.js will treat everything afterwards as plugin name)

"!" is valid URI character (see: http://tools.ietf.org/html/rfc3986#section-2) 
and should be allowed as a character in the baseUrl.

The most simple solution i can think of would be to use a different character, e.G. a Pipe "|" (its easy to type and neither a reserved or unreserved character as per the RFC)

**Comment by guybedford** [comment]
Can you not just percent-encode `!` here when needed explicitly?

**Comment by anpross** [comment]
sorry for the late response - yes adding an `.replace(/!/g, '%21')` to the baseUrl did the trick. 

what is still problematic is the way this error is presenting itself to a unsuspecting developer - it goes into an infinit loop concatenating a string (i think) - i had to kill a chrome tab at 1.3GB memory.

**Comment by guybedford** [comment]
Sure, let's handle this case better then.

**Comment by guybedford** [comment]
I tried to do some simple replications to resolve the crashing, but was unable to get this behaviour. If you're able to share a reproduction of how this crashed that would help a lot, because I can't see where the circularity might have come from here.

**Comment by anpross** [comment]
sorry for not responding yet - i hope to find time in the next few days to test.

**Comment by anpross** [comment]
backtracking the last few hours with git-reflog, local-history and all but also didnt get to the error i described above. please close, i will include a sample next time i open a bug.

**Comment by guybedford** [comment]
Sure, thanks for following up here.
