### ISSUE TITLE
Link to paths config is broken

### ISSUE THREAD

**Issue by Reinmar** [systemjs/systemjs#921]
README contains a link to [paths](https://github.com/systemjs/systemjs/blob/master/docs/overview.md#paths-config) that doesn't work. Perhaps it was supposed to link to https://github.com/ModuleLoader/es6-module-loader/wiki/Configuring-the-Loader#paths-implementation. It would also be good if the difference (if there's any) between map and paths was clarified as both things seem to work.

**Comment by guybedford** [comment]
Wow, that's been there way too long for you to have to be the first to notice! Thanks so much, corrected in https://github.com/systemjs/systemjs/commit/ba55f87d04d1870e731be4f7a49391cea4484237.
