### ISSUE TITLE
Export: invalid token when use NPM

### ISSUE THREAD

**Issue by yordis** [systemjs/systemjs#922]
I tried to use https://www.npmjs.com/package/@ubi/namespace but SystemJS is failing. If you use https://github.com/yordis/namespace which is the same, then everything is fine.

![screen shot 2015-11-19 at 11 16 24 am](https://cloud.githubusercontent.com/assets/4237280/11276193/0dc6198e-8eaf-11e5-8f8e-da2b2d0319f4.png)

**Comment by guybedford** [comment]
I beileve this is a jspm issue due to it treating npm packages as CommonJS by default, while on github the full module format detection of SystemJS will still run. See https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#npm for more info.
