### ISSUE TITLE
Handling redirects

### ISSUE THREAD

**Issue by smcmurray** [systemjs/systemjs#923]
If a module does a System.import('A/lib') and the server does a redirect to 'B/lib', systemjs remembers the resource as 'A' and remembers its location as 'A'.

If B does an import from './' or any other relative path, systemjs will try to retrieve it relative to 'A' instead of 'B'.

Also, if 'C/lib' also redirects to 'B/lib', does systemjs retrieve a redundant copy, or does it work from cache?

Is there any elegant way for systemjs to detect a redirect and tie 'A/lib' and 'C/lib' to 'B/lib'?

**Comment by guybedford** [comment]
Yes, 301 redirects do not work for modules.

The way to do module redirects is via:

```javascript
export * from '/redirect/to/module.js';
export {default} from '/redirect/to/module.js';
```
