### ISSUE TITLE
How could i import multi js modules like AMD loader

### ISSUE THREAD

**Issue by cdll** [systemjs/systemjs#925]
here 's my code snippet
```js
System.import('/bower_components/vue/dist/vue.min.js')
    .then(function(Vue){
    System.import('/bower_components/ajax/dist/ajax.min.js')
      .then(function(Ajax){})
    })
```
could i just do the import event once to load multi js modules?

**Comment by guybedford** [comment]
Apologies for the delayed response here! Closing, but just let me know if you still need any help with these techniques.

**Comment by cdll** [comment]
i wonder how could i do as ``System.import([A, B]).then(function(a, b){...})``

**Comment by tyscorp** [comment]
```js
Promise.all([
    System.import(A),
    System.import(B)
]).then(([a, b]) => {
    ...
});
```

**Comment by cdll** [comment]
@tyscorp thank u, i got it~
