### ISSUE TITLE
`System.amdDefine` don't work with `Marak/faker.js`

### ISSUE THREAD

**Issue by TsumiNa** [systemjs/systemjs#927]
When implement `window.define = System.amdDefine` before `Marak/faker.js` loaded, there will throw a `Uncaught TypeError: Unexpected anonymous AMD define.` error
![image](https://cloud.githubusercontent.com/assets/6410921/11361981/3f08fd62-92d4-11e5-9ee0-125d171bc8e4.png)

![image](https://cloud.githubusercontent.com/assets/6410921/11361911/d62b1122-92d3-11e5-8b7e-e78f29f3f121.png)

On the other hand, set `window.define` after  `Marak/faker.js` is OK because  `Marak/faker.js` will use `define` function itself.
![image](https://cloud.githubusercontent.com/assets/6410921/11361995/56dd4114-92d4-11e5-9f71-248745f672e3.png)

![image](https://cloud.githubusercontent.com/assets/6410921/11362003/65b1419a-92d4-11e5-8c1e-e6f1d0de5920.png)

I don't know whether is it a issue or I used it in a wrong way. But in a meteor app, packages always load before  `<script>` injection.

You can get a replication [here](https://github.com/TsumiNa/fake-systemjs-repo)

**Comment by guybedford** [comment]
@TsumiNa this is because AMD modules need to be loaded by SystemJS itself - rather try:

```javascript
  System.import('https://cdn.rawgit.com/Marak/faker.js/master/build/build/faker.min.js')
  .then(function(m) {
    console.log(m);
  })
```

**Comment by TsumiNa** [comment]
Thanks, worked!
2015年11月24日 19:34，"Guy Bedford" <notifications@github.com>写道：
