### ISSUE TITLE
How to manage subdependencies?

### ISSUE THREAD

**Issue by alexkolt** [systemjs/systemjs#928]
Firstly - I love jspm.

Assume a simple project with following dependencies:
angular@1.4.8,
angular-material@rc4: depends on {
    angular@1.4.7
},
angular-material-data-table: depends on {
  angular-material: 10.1
},

When the app is run all libraries will get loaded: angular 1.4.7 and 1.4.8, angular material rc4 and 10.1. Obviously this isn't what you'd want in an app, even though I understand the reason for the behavior.

Is there a way to specify that all "angular" dependencies will point to 1.4.8? How? Do I need to shim every dependency?

Guy, what would suggest? In real app I'm using adapter module and instead loading ng dependencies from CDN.

**Comment by guybedford** [comment]
If you run `jspm inspect github:angular/bower-angular`, you will see the version ranges that Angular is installed to. It should then be easy to see why both versions are installed due to the ranges not allowing a single resolution. The ranges themselves can then be corrected via a dependencies override.

There is also a command here to ensure only one version of angular is used:

```
  jspm resolve --only github:angular/bower-angular@1.4.8
```

**Comment by alexkolt** [comment]
Thank you the answer.

What if I used an adapter pattern for the "angular" dependency?

I include angular from CDN and in the jspm it is configured to point to a file with following content: "export default window.angular". How can I configure subdependencies to point to that adapter file?

**Comment by guybedford** [comment]
@alexkolt that would require manually editing the config.js file in jspm to replace all the map configs of angular to your reference file.

jspm should support this fine and respect the configuration, so if that ever gives any issues do let me know.

We could certainly look at some better shorthand for this in future possible through the `resolve` method.

**Comment by alexkolt** [comment]
@guybedford I tried to modify all sub-dependencies to point to the local adapter file. When I tried to run "jspm install" I receive an error 
```
TypeError: Path must be a string. Received undefined
```

I created a [small test repo]: https://github.com/alexkolt/JspmAdapterTest to help troubleshoot the issue. Project with Angular Material. The intent is to have all google dependencies (ng, aria, animate) load from CDN and dependencies should stick if jspm install is run.

**Comment by guybedford** [comment]
@alexkolt thanks yes that is a jspm bug. I can confirm that the test project does work in the upcoming jspm 0.17 alpha, which I am hoping to get a first release of this month. We can potentially look at backporting the fix though if necessary.

**Comment by guybedford** [comment]
Tracking at https://github.com/jspm/jspm-cli/issues/1351.
