### ISSUE TITLE
How is exactly the loader plugin selected?

### ISSUE THREAD

**Issue by bali182** [systemjs/systemjs#930]
Hi guys, 

I think, that this is a better place to ask this, than StackOverflow, since it's 100% System.js specific. 

So what I would like to ask is, how exactly does System.js specify, which loader plugin to use, and when to delegate to which? 

As far as I understand looking at [this](http://stackoverflow.com/questions/31620018/es6-imports-what-does-the-exclamation-mark-mean) post, if there is an `./file/path.extension![optionally plugin name here]` - style import, then that clearly determines, what you want to load, and with which plugin. Is this feature System.js specific, or is it also in the ES6 spec? (did read a few of [these](https://github.com/ModuleLoader/es6-module-loader/blob/master/docs/loader-extensions.md), haven't found anything about this) - So I assume, that this is System.js specific.

Which leads to my second question: What happens, if the best-effort determined loader plugin can't handle the loading? So either phase from `normalize`, `locate`, `fetch`, `translate` or `instantiate` fails in a plugin? Is there some kind of chain of responsibility pattern applied here (pick a next plugin or maybe fall back to default)? Does System.js even know about all the loader plugins available? Or it just uses the one available from the `!` logic?

If there is no such a thing, or System.js doesn't know about the whole set of available plugins, how would one implement such a plugin, which tries to intercept all imports, but if it fails, then it delegates to the defaul System.js loader. Is this even possible/does it makes sense?

(Sorry, I couldn't assign a Question label to this)

Thanks in advance for any info or help!

**Comment by guybedford** [comment]
There are only two ways to use a plugin - either it is with syntax - `import 'module!plugin'`, which takes preference. Or it is through metadata.

There is no fallback system - loading must work. Plugins can internally handle failure of network requests if they need to as they have full control over all the phases.

It may help to understand the use case you have in mind here?

**Comment by bali182** [comment]
Cool, thanks for the infos!

I'm trying to add jspm (System.js) support for a project, https://github.com/react-toolbox/react-toolbox .
It currently uses webpack, and all imports are declared without an extension, eg.:

```js
import app from './app' // app.js
import comp from './comp' // comp.jsx
import style from './style' // style.scss
```

So my first idea was, to create a custom loader plugin, which would handle all these, so it would work without touching the sources. Do you know any solution for this? It seems like this couldn't really work for System.js, since there can only be one default extension (e.g.: `js`), other imports must provide the loader plugin with the `!` syntax.

**Comment by guybedford** [comment]
The way to handle this in SystemJS is with package configuration:

```
      map: {
        './comp': './comp.jsx',
        './style': './style.scss'
      }
```

In jspm, the above map configurations can be added to the package.json file itself.

There is a scss plugin at https://github.com/theefer/plugin-sass but I'm not sure how stable that project is, so it may be worth precompiling scss rather.

Let me know how it goes.

**Comment by bali182** [comment]
Thanks, it looks good. I think it would be fairly trivial to add mapping for each of the imported files this way. But would this work for the following situation?

Let's say these are my 2 relevant files:
```
./path/to/comp.jsx
./path/to/style.scss
```

Then if I put this in `config.js`

```js
map: {
  './path/to/comp': './path/to/comp.jsx',
  './path/to/style': './path/to/style.scss'
}
```

Can I do this in `comp.jsx`?
`import style from './style'`?

Does System.js figure out this from the mapping? I will test it anyways when I get home, but if it works, then it's 100% what we need.

**Comment by giltig** [comment]
Hi by the way there is apparently a stable version of sass plugin for jspm :
https://github.com/mobilexag/plugin-sass
