### ISSUE TITLE
Class inheritance support

### ISSUE THREAD

**Issue by kburson** [systemjs/systemjs#932]
When using Babel 6 to pre-transpile ES6 to ES5, with classes that inherit from other classes, the System auto module detection fails.  The Babel injects  the following line at the top of the file above the 'System.register' call for any classes that use inheritance:
```
'use strict';

function _typeof(obj) { return obj && typeof Symbol !== "undefined" && obj.constructor === Symbol ? "symbol" : typeof obj; }

System.register(['angular', 'common/baseClasses/eventSubscriber.base'], function (_export) {
...
```
This breaks the rules for the auto-format detection.

I looked into adding a **package: {}** property to SystemJS.config that would catch all the **\*\*/\*.js** files in the app folder but that did not work.  I tried the same with the **meta: {}** property, but that does not work.  So far the only thing that is working is to individually list each file, and that is tedious and not scalable.

Is there some way I can identify all the **'./\*\*/\*.js'** files should be loaded as **register** format ?

Thanks,

**Comment by guybedford** [comment]
Meta wildcards are deep so `./*.js` should work here in the meta property.

**Comment by kburson** [comment]
thanks

**Comment by kburson** [comment]
i had a further problem with that. in my build folder i have `build/js/lib` to store all vendor libs and `build/js/app` to store my app objects.  when i use `meta:{'./*.js`: {format:'register'}` it catches all js including vendor js in the `js/lib` folder and forces them to `register` format, but many of the vendor libs want `global` format, so i get errors for that.

This was causing a problem with libs like `systemjs-plugin-json` that want to be global. 
I do not directly import `json.js`, but i do have it listed in the `paths : { 'json': './lib/json.js'}` and reference it as `import data from 'dir/to/file/data.json!'`.

So my problem is now, how to allow vendor libs to be referenced from `./js/libs` and my application from `./js/app/**` without prefixing all imports with `lib/` or `app/` ( which would not work with systemjs plugins, as far as i know)

Am I doing this all wrong? Is there a better way?

**Comment by guybedford** [comment]
Try selecting just the files that are the register format with a wildcard along the lines of:

```javascript
System.config({
  meta: {
    'build/js/lib/*.js': { format: 'register' }
  }
});
```

**Comment by kburson** [comment]
so, if I use

```
baseURL: '/js/app',
paths:{
   'json':         './js/lib/json.js',
    'angular':  './js/lib/angular.js'
    ...
},
meta:{
   './js/app/*.js':{format:'register'}
}
```

and then in my classes

```
import angular from 'angular';
import data from 'data/verify/results.json!';
import baseClass from 'baseClasses/domain.base';

class doodad extends baseClass {
...
}
```

that everything should work correctly?

Is this the correct way to do this, or did you envision a more proper way?

(btw: thanks for helping me)
