### ISSUE TITLE
Pipeline not reporting where the angular2 is loaded from

### ISSUE THREAD

**Issue by varghesep** [systemjs/systemjs#934]
In my ASP.NET 5 app, I use CDN to load angular2. I don't use *JSPM* or *config.js*

Here is what I use in the **master layout file**:

```javascript
<script src="https://code.angularjs.org/2.0.0-alpha.46/angular2.dev.js"></script>
```

In my angular component I have

```javascript
import {Component, View, bootstrap, NgFor} from 'angular2/angular2';
```

The component works fine.

My questions are:

1) I used the following code to see from where the angular2 is loaded from

```javascript
var systemFetch = System.fetch;
System.fetch = function (load) {
    console.log("fetching: " + JSON.stringify(load));
    return systemFetch.call(this, load);
};
```
The result is that it is fetching from *http://localhost:5000/angular2/angular2*. How to find out from where SystemJS is loading angular2 from? In my case, it should say it is from the *CDN* url that I provided.

2) I'm little confused by the error message that I get when I remove the CDN link from the master layout page. It will tell you that

```javascript
GET http://localhost:5000/angular2/angular2 404 (Not Found)
```
Does SystemJS load the modules from the CDN if it can't find in the folders.

**Comment by guybedford** [comment]
When you load the angular file from CDN, it contains `System.register` statements which populate the registry with the angular module. When you try to fetch it manually it will load from the default module path which is just the name of the module you attempted to load in SystemJS (`./angular2/angular2`).
