### ISSUE TITLE
Unexpected anonymous AMD define (in rx.lite)

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#935]
I'm getting this error (sporadically) when trying to load the following script:

https://cdnjs.cloudflare.com/ajax/libs/rxjs/2.5.3/rx.lite.js

**Comment by guybedford** [comment]
@Mosho1 is there any way you can share a replicate of this case? If I try:

```javascript
System.import('https://cdnjs.cloudflare.com/ajax/libs/rxjs/2.5.3/rx.lite.js').then(console.log.bind(console));
```

it works fine for me every time?

**Comment by Mosho1** [comment]
Yeah, it's pretty rare but it happens and when it does it brings the whole site down. Maybe you could share some insight as to why this could happen theoretically so I can look into it further?

**Comment by guybedford** [comment]
Are you running the latest version of SystemJS? There were some bug fixes for this on the 0.19 patch releases.

If you could share an isolated repo that replicates it more than once every 20 refreshes that would help to debug, as 20 refreshes on the above test cases works fine consistently.

Which browsers specifically are you getting this with? Firefox and IE both have separate quirks. If it's Chrome then that's even more surprising.

**Comment by guybedford** [comment]
Also is your global `define` set in your environment?

**Comment by guybedford** [comment]
Closing, but let me know if you still need help here at all.
