### ISSUE TITLE
ReferenceError: babel is not defined when importing my frontend app in nodejs

### ISSUE THREAD

**Issue by capaj** [systemjs/systemjs#939]
For the purpose of testing I tried to import my frontend app into node.js with system..js

First I required systemjs, then I required config.js from public folder and then I tried to do an System.import()
```
ReferenceError: babel is not defined\n\tEvaluating file:///home/capaj/git_projects/people.io/public/jspm_packages/npm/babel-core@5.8.34/browser.js\n\tEvaluating file:///home/capaj/git_projects/people.io/public/jspm_packages/npm/babel-core@5.8.34.js\n\tError loading file:///home/capaj/git_projects/people.io/public/jspm_packages/npm/babel-core@5.8.34.js\n\tError loading file:///home/capaj/git_projects/people.io/public/people-io.js
```

Am I doing something wrong or is it broken?

**Comment by guybedford** [comment]
This should work. Note that Babel needs to be defined as a global module to work properly.

I just tested this with:

```
  jspm install babel=npm:babel-core@5
  jspm run babel
```

Which works completely fine.

Let me know if you need any more help tracking this down.

**Comment by guybedford** [comment]
Let me know if you're still having this issue.

**Comment by capaj** [comment]
@guybedford this might have something to do with a scenario when I use babel require hook and then try to load an ES6 code with systemjs. Will have to look at it again in the next couple of days.

**Comment by scottnicolson** [comment]
@capaj did you find a solution to this problem?  i am having the same issue.

**Comment by wesleycoder** [comment]
I'm having this issue too, and couldn't find a solution, any of you have something?

**Comment by tjclement** [comment]
For anyone seeing this error, we had this in our testing suite whenever we would mock the Window object onto the global scope (i.e. setting global.window = [..]).

After the very first System.import() has completed, this no longer happens in subsequent imports. A usable workaround thus, is to perform any import, and defer mocking the window until that import completes.

```javascript
async function prepareWindowMock(){
    await System.import('./someFile.js');
    global.window = { /* Add whatever mocks are needed */ };
}

// From within unit test:
describe('ClassUsingWindow', () => {
    before(async function {
         await prepareWindowMock();
    });
    it('does something nasty with Window', () => {
        // Do something
    });
});
```

Realising it is normally not best-practise to define a window property onto the global scope, I still wonder whether there is a more robust solution to this for the edge cases where this mocking is necessary. Any thoughts are welcome!

**Comment by peteringram0** [comment]
+1 getting this issue
