### ISSUE TITLE
Global dependency not getting shimmed

### ISSUE THREAD

**Issue by isaacseymour** [systemjs/systemjs#940]
This is occurring with [nnnick/Chart.js v2.0-dev branch](https://github.com/nnnick/Chart.js/tree/v2.0-dev), which requires `window.moment` to contain [MomentJS](https://github.com/moment/moment) in order to load some time-series features ([code](https://github.com/nnnick/Chart.js/blob/f0555af8ccd774c5cc70689c9dbd09dfcdb11383/Chart.js#L5679-L5682), [issue](https://github.com/nnnick/Chart.js/issues/1614)). I was hoping to get around this using [custom globals](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#custom-globals), so set up JSPM/SystemJS as follows:

`package.json`:
```json
{
  "jspm": {
    "dependencies": {
      "chart.js": "github:nnnick/Chart.js@v2.0-dev",
      ...
    },
    "overrides": {
      "github:nnnick/Chart.js@v2.0-dev": {
        "main": "Chart",
        "format": "global",
        "files": [
          "Chart.js"
        ]
      }
    }
  }
}
```

`config.js`:
```javascript
System.config({
  ...
  meta: {
    "chart.js": {
      "globals": {
        "moment": "moment"
      }
    }
  },
  map: {
    "chart.js": "github:nnnick/Chart.js@v2.0-dev",
    ...
  }
}
```

However, when I run the app, `window.moment`/`moment` remains undefined while Chart.JS is loading (checked by popping a breakpoint in Chrome). I'm probably just not reading the docs correctly, but it looks to me like SystemJS should be temporarily setting (window.)moment while ChartJS gets loaded with these settings? I've tried using [shim dependencies](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#shim-dependencies) too, but no luck there either. Is this a bug, or poor doc-reading from me?

**Comment by isaacseymour** [comment]
Aha, seem to have fixed this my changing my config to use `github:nnnick/Chart.js@v2.0-dev/Chart.js` instead of just `chart.js` as the key in `meta`, so I'm guessing that meta overrides only apply per-file rather than per-module?

**Comment by guybedford** [comment]
Yes that would be correct! Note that this would actually work with jspm 0.17 though.
