### ISSUE TITLE
skip external dependency?

### ISSUE THREAD

**Issue by jay8t6** [systemjs/systemjs#941]
@guybedford Can we skip jspm from bundling external dependency? just like how rollup treats it?

**Comment by jay8t6** [comment]
I tried adding this in config.js, doesnt seem to do anything skip the build though.

```javascript
meta: {
    'jspm_packages/**/*': { build: false }
  }
```

**Comment by guybedford** [comment]
You should just be able to use:

```javascript
meta: {
  'jspm_packages/*': { build: false }
}
```

as wildcards are already deep.

If running an SFX bundle, you do need to also use custom exclusion for modules not included in the build, pending https://github.com/systemjs/builder/issues/407.

**Comment by jay8t6** [comment]
@guybedford Thanks! I am just using the bundle task for now. Good to know that you are working on the SFX build.

I have a custom component bundled through jspm with build set to false on all external dependencies. When using this custom component in the main project, I am getting an error 'Module not available!', any idea what might be wrong? However if I use SFX without setting build false, the module works.

**Comment by guybedford** [comment]
With `build:false` in SFX you still need to explicitly exclude the dependency in order for it to be found. This feature is tracking at https://github.com/systemjs/builder/issues/407.
