### ISSUE TITLE
Can't refer to alias in AMD define

### ISSUE THREAD

**Issue by sberney** [systemjs/systemjs#943]
I have [another issue](https://github.com/systemjs/systemjs/issues/942) about module format.

I have a project written largely in AMD style, with pre-existing module ids from requirejs. For example, instead of referring to "any-promise-es6", a `define` statement would refer to "foobar".

I added this to `meta`:

`"foobar": {
  "alias": "any-promise-es6"
}`

Importing a file called stubfile.js, these stubfile.js contents succeed:

`define([],
function() {
  System.import('foobar').then(function () { console.log('barred'); });
});`

And so do these:

`define(['any-promise-es6'],
function() {
});`

However, these fail (`Uncaught (in promise) Error: Cannot read property 'call' of null`):

`define(['foobar'],
function() {
});`

I want to keep these aliases out of path or map for two reasons: to avoid specifying the package version and registry repeatedly, and to provide aliases for modules distributed with a package (instead of using `package/module`).

I've attached my config.js, stubfile.js, package.json, and index.html.
[config.txt](https://github.com/systemjs/systemjs/files/47853/config.txt)
[index.txt](https://github.com/systemjs/systemjs/files/47854/index.txt)
[package.txt](https://github.com/systemjs/systemjs/files/47856/package.txt)
[stubfile.txt](https://github.com/systemjs/systemjs/files/47855/stubfile.txt)

**Comment by guybedford** [comment]
There is a known bug with `alias`, so I would not suggest using it.

Rather use:

```javascript
System.config({
  map: {
    foobar: 'any-promise-es6'
  }
});
```

for aliasing.

**Comment by guybedford** [comment]
Also I'd be interested to know where you found out about the `alias` configuration option?

**Comment by sberney** [comment]
search-fu, as there are some pretty frustrating problems with using map for configuration. Your example using `map` doesn't work for me. I have to add `foobar: "npm:any-promise-es6@0.1.1"` to the map instead. [From what you said](https://groups.google.com/d/msg/systemjs/VNw_7FJnP6M/lFVMwDNWyO4J), it doesn't seem like this is going to change. There's several issues with this:
- It causes a giant list of redundant information, once you start using many remappings.
- Versioning information is embedded all over the place. When a dependency is upgraded, the maintainer (who won't necessarily be me) will have to know which map items to upgrade. Because the 12,000 lines we have represent one of many anticipated components, it's conceivable that this will become very complicated over the next five years this project is being completed.
- The distinction between here-for-legacy/transitional-reasons and this-is-the-package-we-use is much foggier. I would really prefer a separate place to provide remappings.
- Dependencies must be repeatedly specified (the project was totally bower before, using Backbone/Marionette, pretty bumpy. Remapping underscore to lodash everywhere: pretty bumpy).
- Meta configuration must be repeatedly specified (and I have to specify a lot of formats and shims).

For example, I use slickgrid, and provide alternate names for most of its submodules. So, I will have the full registry/version number embedded in every single mapping.

**Comment by sberney** [comment]
Ah, I bet I found alias by [doing this](https://github.com/systemjs/systemjs/search?q=alias&type=Issues&utf8=%E2%9C%93). I didn't want to believe there wouldn't be something like alias, so I searched for a number of synonyms in various places. I was all ready to start hacking if there wasn't something already there... :) Not sure if my superiors are on board with that notion though.

I haven't started to worry about the production build yet, but [it looks like(https://github.com/systemjs/systemjs/pull/929#issuecomment-161143605) alias is concerning in that respect. Thanks for your work and support of this project.

**Comment by sberney** [comment]
Before we close this issue, I would appreciate any comment on:

- How to reduce registry:package-name@version redundancy (at first I played around with a * override, but it doesn't address module subdependencies, for example. It does in bower/requirejs!).
- Is specifying `meta` for each mapping name really required (see below)?

```javascript
meta: {
  underscore: {
    someProp: 'foobar'
  },
  lodash: {
    someProp: 'foobar'
  }
},
map: {
  underscore: 'npm:lodash@3.10.1',
  lodash: 'npm:lodash@3.10.1',
  'registry:something@version': {
    underscore: 'npm:lodash@3.10.1'
  }
}
```

**Comment by guybedford** [comment]
It sounds like this is more of a jspm question here.

When installing lodash in jspm, you can use `jspm install underscore=npm:lodash lodash=npm:lodash` to set up the custom map aliases without having to manage the versioning yourself. Then `jspm update underscore lodash` should work as expected.

In terms of ensuring that underscore as a dependency of other dependencies is replaced with lodash, that does require manually editing the config.js resolutions. The way to store this information is to use an override on install:

```javascript
jspm install registry:something@version -o "{dependencies:{all:'deps', as:'listed', underscore:'npm:lodash@^3'}}"
```

The override then gets stored in the package.json and also upgrades with the dependency.

**Comment by guybedford** [comment]
Closing as this is a jspm issue, but feel free to keep posting if you have more questions at all.

**Comment by sberney** [comment]
Thanks.
