### ISSUE TITLE
loading AMD modules from r.js bundled file

### ISSUE THREAD

**Issue by dtassone** [systemjs/systemjs#947]
Hi Guy,

I have an issue trying to load several modules from an r.js optimized package.
So I have one file containing several AMD modules as it was packaged using r.js.
myModule.js
define('myModule/controls/sidebar', function(){...})
define('myModule', ['myModule/controls/sidebar'], function(sidebar){...})

I have no problem loading the file but when systemjs is trying to load the dependency myModule/controls/sidebar it is trying to get it from myModule/controls/sidebar.js instead of looking in myModule.js.
How can I configure systemjs to load all the myModule submodules from myModule.js?

Thanks

**Comment by dtassone** [comment]
I've just found a way!
Is that the correct way to do this?

 paths: {
     myModule/*:'myModule.js'
}

**Comment by Bnaya** [comment]
I would recommend to make a custom build of this bundle that exposes the needed modules to a global object and to load it as global module
You can also try exporting it in ES6 manner inside the require callback but i don't think its ES6 complaint even if it might work
 
Add another file with
```js
require(['the module i need'], function (module) {
window.exportedRJS = {moda: module}
})
```

And if your AMD code will pass amdclean optimizations you can do much more sophisticated things 
https://github.com/gfranko/amdclean

**Comment by guybedford** [comment]
@dtassone the bundle itself will populate the registry, and as a convenience the bundle itself can take the value of one of its modules in AMD for System support, but you need to then separately import the file in the bundle - `System.import('myModule')` as the bundle is a separate module to its containing modules.

Your path approach to make the names work out sounds fine, although you could also achieve this with:

```javascript
System.config({
  packages: {
    myModule: {
      defaultExtension: false
    }
  }
});
```

**Comment by guybedford** [comment]
Did you manage to sort this out?

**Comment by simonfox** [comment]
Hi @guybedford I'm running into this issue at the moment on SystemJS 0.20.12.

I'm looking at adding initial SystemJS support to Aurelia CLI. Aurelia CLI currently generates r.js bundles, so initial idea is to try use these with SystemJS.

I've started by taking a cli generated project and then looking at what changes are required to load with SystemJS. I've published the project @ https://github.com/simonfox/cli-systemjs-loader and the current config I am using is https://github.com/simonfox/cli-systemjs-loader/blob/8ef27ae086bf69e818ca24f0000745c59bf22f4b/config.js

The r.js bundles seem to load fine, but then when I try to use modules within those bundles further requests are generated for the original file the module was defined in. I have a little more info on what I've done at https://github.com/aurelia/cli/issues/198#issuecomment-301666973 

Can you give me any tips on what I might have wrong?

**Comment by guybedford** [comment]
@simonfox reading through the issue there it seems like you've got on top of this now? Happy to help further if there's anything more you want to ask.

**Comment by simonfox** [comment]
Yes worked it out. Thanks @guybedford
