### ISSUE TITLE
Indirect question regarding path maps

### ISSUE THREAD

**Issue by pocesar** [systemjs/systemjs#949]
Are there any editors (like vscode) that actually read maps placed in files containing System.config? (like the one generated by jspm). The "go to file" shortcut usually is broken, needing to go to the path manually. I'm planning to adopt an editor that have this, to improve productivity, if there are none, how hard would be to implement this?

**Comment by guybedford** [comment]
Plugins can be developed for editors I believe along these lines. We previously did some experimentation for Atom in https://github.com/incrementallair/es-navigation, which is out of date now though. If you find any good workflows do let me know.
