### ISSUE TITLE
Cannot use lodash chains in Typescript compiling for System.register

### ISSUE THREAD

**Issue by oleg-py** [systemjs/systemjs#951]
I'm trying to adjust a Typescipt codebase to compile for System.register (used AMD previously). We use lodash chains heavily, but they don't seem to work with System.register. Here's a simple example

main.ts:
```typescript
import * as _ from 'lodash'

console.log(_([1,2,3]).map(x => x * 2))
```
which compiles to following (main.js)
```javascript
System.register(['lodash'], function(exports_1) {
    var _;
    return {
        setters:[
            function (_1) {
                _ = _1;
            }],
        execute: function() {
            console.log(_([1, 2, 3]).map(function (x) { return x * 2; }));
        }
    }
```
load.js (config included via script tag):
```javascript
System.config({
    defaultJSExtensions: true,
    map: { lodash: 'bower_components/lodash/lodash.min.js' },
    meta: { lodash: { format: 'amd' } }
});
System.import('main.js');
```
Resulting in following exception (using SystemJS v0.19.6)

    Potentially unhandled rejection [2] TypeError: _ is not a function
         at execute (http://localhost:9090/main.js:9:25)

**Comment by mhegazy** [comment]
Using `typescript@next`,  import lodash using `import _ from "lodash"`, and compiler with `--module system`, the ts compiler will not complain as it knows that the loader will load the module as a default import.

See https://github.com/Microsoft/TypeScript/issues/5285 for more details.
