### ISSUE TITLE
Babel 6 and client-side compiling

### ISSUE THREAD

**Issue by finom** [systemjs/systemjs#953]
@guybedford I am sorry, I know this is "supporting" question but I cannot find the answer the last month. Guys from gitter chat don't help me. Github issues is the last place where I hope I can get an answer.

The most of projects I made the last 4 month are based on client-side compiling. But when Babel 6 is released I don't know how to upgrade it from v5 and keep client-side compiling. It's very useful that I can run a dev version of a project with no watchers, Systemjs was really helpful for me.

Is it possible to run SystemJS + Babel 6 + client-side compiling? If yes, how can I do this?

**Comment by tomasvarg** [comment]
@finom I've been struggling wit this yesterday after updating my npm dependencies - until Babel 6.2 it was just a matter of locating browser.js from Babel distribution (node_modules/babel/dist/browser.min.js) in the baseURL path as stated on https://github.com/systemjs/systemjs#browser or pointing SystemJS out where it is (I did it with map: { babel: './lib/browser.min.js' }), which worked both for on-demand transpilation and systemjs-builder.

With its version 6.2, Babel went through a massive reworking, deprecating the browser.js approach (as stated on https://babeljs.io/docs/usage/browser/) - it still provides a possibility to build it yourself, but I'm not sure how... nevertheless a convenient drop-in bundle is no longer part of the Babel distribution.

I'm not a long-time SystemJS user and I don't use jspm (its packaging system) at all so I'm not sure my assumptions are correct, but I'd say you'd have to use Babel ~6.1 and wait until SystemJS catches up and/or updates docs (i.e. provides further instructions).

**Comment by guybedford** [comment]
Yes Babel 6 is not currently easily supported, but will be provided with the new Babel plugin being released later this month.

**Comment by Bnaya** [comment]
Is there a beta branch we can play with?

**Comment by finom** [comment]
@guybedford do you have any news?

**Comment by sandys** [comment]
hi guys,
based on these updates - https://github.com/babel/babel/commit/c0afdfd1a83aab0c25a1fc23cee0b09d560f4d35#commitcomment-15045956

babel is not planning on supporting a browser mode for babel6. They ask you to compile and build it yourself. I believe there is a big void that needs filling and systemjs could do very well here. There's no reason why I should not have an entire build system inside the browser - its javascript after all.

**Comment by sandys** [comment]
additionally, there's been another project - https://github.com/Daniel15/babel-standalone - to illustrate how to build a browser.js.

**Comment by finom** [comment]
@sandys any way to use it with SystemJS?

@guybedford can you ping us about the status of this issue? I have many outdated projects and if you're not going to implement Babel plugin I'm going to get rid of babel-browser and use CLI watchers instead.

**Comment by Izzmo** [comment]
The babel-standalone is good, but you get a weird error when trying to use it with SystemJS where SystemJS tries to use the "babel" namespace and the standalone, and Babel in general, uses "Babel" with a capital 'B'.

Updating that.. and then also taking out the `options.modules = 'system';` part too since that is now incompatible, you should get it to transpile. For me though, the transpile is creating a runtime error still which I'm still trying to figure out.

**Comment by capaj** [comment]
@Izzmo what do you mean "babel" namespace? Wouldn't that be easily solvable by just doing:
```javascript
window.babel = Babel
```
?

**Comment by Izzmo** [comment]
@capaj that would not work because babel is not instantiated yet. SystemJS does this for you. It's a simple reference update from within the system.js code.

**Comment by guybedford** [comment]
The Babel 6 plugin is available at https://github.com/systemjs/plugin-babel.

**Comment by finom** [comment]
Wow! Finally! Thanks.

**Comment by ryanhiebert** [comment]
This is awesome, thank you very much @guybedford !
