### ISSUE TITLE
SystemJS issue with es6-symbol?

### ISSUE THREAD

**Issue by peteruithoven** [systemjs/systemjs#955]
When using SystemJS, and importing [es6-symbol](https://github.com/medikoo/es6-symbol) (a Symbol ponyfill) Chrome seems to go into a infinite call loop, triggering a `Maximum call stack size exceeded` error. I already posted [the issue](https://github.com/medikoo/es6-symbol/issues/13) with es6-symbol, but it seems to be SystemJS / JSPM specific, there is no problem when using Webpack (even when using Babel 5.8.34 instead of 6). It happens since v3.0.0 of es6-symbol.
I also tried generating a Self-Executing (SFX) Bundle, this gives the same result. 

I've made an example project with both a SystemJS (JSPM) and a Webpack example: 
https://github.com/peteruithoven/systemjs-es6-symbol-issue

For more info see the es6-symbol issue: https://github.com/medikoo/es6-symbol/issues/13

**Comment by guybedford** [comment]
Odd, this seems to run fine for me in Chrome 48 returning the console.log with `Symbol(my symbol)`.

**Comment by peteruithoven** [comment]
Ah, I'm using Chrome 47.0.2526.73 (64-bit), you are running the Beta version I'm presuming. 
Those versions probably don't matter for native Symbol support though, [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) show basic support since Chrome version 38. 

I also ran my example in Firefox 42.0 and then there is no issue...

I'm using JSPM version 0.16.15 and SystemJS v0.19.5.

**Comment by guybedford** [comment]
I'm just on the standard Chrome track here. Does it go away if you update Chrome?

**Comment by guybedford** [comment]
Ah sorry yes I'm on beta!

**Comment by peteruithoven** [comment]
I also tried the Chrome Beta (48.0.2564.41) and I shows the same issue I'm afraid.

**Comment by guybedford** [comment]
Odd then that I can't replicate it here at all. I'm running jspm 0.16.15. Are you running the latest version of SystemJS as well? Did you try a `jspm install -f`?

**Comment by peteruithoven** [comment]
After running a `jspm install -f` I get the same same result. 
I'll ask a colleague to reproduce it with the same example.

**Comment by guybedford** [comment]
Sure thanks - note I'm running SystemJS 0.19.6 in my tests.

**Comment by guybedford** [comment]
Let me know if you manage to reliably reproduce this.

**Comment by peteruithoven** [comment]
My college has the same problem. Is there a way for me to switch temp to the latest (beta) SystemJS that you are using?

**Comment by guybedford** [comment]
@peteruithoven I was just using jspm 0.16.15 myself. Perhaps include your package and SystemJS files in the repo?

**Comment by peteruithoven** [comment]
I've added the `jspm_packages` folder:
https://github.com/peteruithoven/systemjs-es6-symbol-issue/tree/master/systemjs/jspm_packages
Is that what you meant?

**Comment by guybedford** [comment]
@peteruithoven thanks, I pulled from the repo and opened that page in Chrome and get no error as shown. I'm sorry I can't do more to try to replicate, but am very limited for time right now.

![screen shot 2015-12-11 at 17 12 43](https://cloud.githubusercontent.com/assets/598730/11747183/7273ef28-a02a-11e5-8173-505317afd76e.png)

**Comment by guybedford** [comment]
In my Chrome install I had Experimental JS enabled, after disabling this I got the error to happen.

I've sent and update to https://github.com/medikoo/es6-symbol/issues/13#issuecomment-163964498.
