### ISSUE TITLE
System's loader.normalize(), when given an absolute normalized windows path glob in a gulp script, concatenates the systemjs-bundle output directory to the beginning of the glob.

### ISSUE THREAD

**Issue by scottmmjackson** [systemjs/systemjs#956]
Using systemjs-builder@0.14.11 systemjs@0.19.6 aurelia-bundler@0.1.9 

aurelia-bundler is called with the following config:

```
  var config = {
    force: true,
    packagePath: '.',
    bundles: { }
  }
  config.bundles["dist/bundle.js"] = {
    includes: [
      paths.appRoot+'*'
    ],
    excludes: [
    ],
    options: {
      inject: true,
      minify: true
    }
  }
```

where paths.appRoot is an absolute Windows path.

After trying to track down why it was failing, I placed console.logs in systemjs-builder. In `arithmetic.js` lines 93-96:

```
[SYSTEMJS-BUILDER::expandGlobAndCanonicalize()] name: c:\Users\[REDACTED]\src\*
[SYSTEMJS-BUILDER::expandGlobAndCanonicalize()] normalized: file:///c:/Users/[REDACTED]/dist
/c:/Users/[REDACTED]/src/*.js
```

Is this a real issue, or just a deviation from the way the systemjs builder should be called?

**Comment by scottmmjackson** [comment]
Note: Changing the `includes:` path to a relative path (without explicit relative markers such as `./`) fixed the issue. This should probably be documented somewhere.

**Comment by guybedford** [comment]
Thanks for posting. So the point here is that the normalization space of bundles (including the includes) is the URL-like name space. Absolute windows paths should be converted into file URLs to work in includes for example.

I agree this is a documentation issue, and have included a point for this in https://github.com/systemjs/builder/issues/250.
