### ISSUE TITLE
Delete all registered modules

### ISSUE THREAD

**Issue by peterjuras** [systemjs/systemjs#957]
Hi!

I'm trying write some unit tests for my modules and I run into some troubles because the dependencies of my modules are not cleared when I delete a module from System.js. My unit tests always look something like this:

```js
// ...
before(() => {
  return System.import('./index').then(module => foo = module.foo);
});

after(() => {
  System.delete(System.normalizeSync('./index'));
}
// ...
```

This works so far, but the problem is that the dependencies of this index module are not resetted by this command. As a result, stateful changes within the unit tests will impact further unit tests.

Is there a way to reset every module that SystemJS has loaded?

**Comment by peterjuras** [comment]
I found a way to do this, by adding a *deleteAll* function to System.JS, based on the current *delete* method:

System.delete:
```js
'delete': function(name) {
    var loader = this._loader;
    delete loader.importPromises[name];
    delete loader.moduleRecords[name];
    return loader.modules[name] ? delete loader.modules[name] : false;
  }
```

Proposed System.deleteAll:
```js
deleteAll: function() {
  var loader = this._loader;
  loader.importPromises = {};
  loader.moduleRecords = {};
  loader.modules = {};
}
```

**Comment by guybedford** [comment]
The other way you can do this is by creating a separate loader instance for each test, as the loader itself provides its class at `System.constructor` which can be used to create new instances as in https://github.com/systemjs/systemjs/blob/master/docs/system-api.md#systemconstructor.

**Comment by peterjuras** [comment]
How can I clean up the created loader instance after each test? There seems to be a memory leak somewhere because the new loader instances are not cleaned up after each test.

You can test this with e.g.:
```js
function cloneSomeBuilders() {
      const promises = [];
      for (var i = 0; i < 10; i++) {
        var system = new System.constructor();
        system.config({
          baseURL: System.baseURL,
          defaultJSExtensions: System.defaultJSExtensions,
          transpiler: System.transpiler,
          babelOptions: System.babelOptions,
          packages: System.packages,
          paths: System.paths,
          meta: System.meta,
          map: System.map,
        });
        // The module you want to import
        promises.push(system.import('./index'));
      }
      Promise.all(promises).then(() => console.log('Done importing'));
    }

    cloneSomeBuilders();
```

There should be no more reference to the new system instances or any of its imports after "Done importing", but if you force garbage collection and run a memory snapshot the new system instances are still there!

**Comment by guybedford** [comment]
Thanks, I've reposted this at https://github.com/systemjs/systemjs/issues/964 for further investigation.
