### ISSUE TITLE
scriptLoad fails on 302 Moved Temporarily

### ISSUE THREAD

**Issue by MeoMix** [systemjs/systemjs#959]
Hey.

I am attempting to load Zopim's API. They suggest loading their API from `//v2.zopim.com/?1TIFyJJeUxtn1IuZpJGTUc0e3kpthpoN`

I have the following configuration:

	meta: {
		"zopim": {
			"scriptLoad": true,
			"format": "global",
			"exports": "$zopim"
		}
	},

	map: {
		"zopim": "//v2.zopim.com/?1TIFyJJeUxtn1IuZpJGTUc0e3kpthpoN.js"
	}

The given URL redirects to `http://v2.zopim.com/bin/v/widget_v2.122.js` which GETs successfully, but there is an error on the page stating `$zopim is not defined` due to the redirect.

If I modify the mapped URL to the redirect target then all works as expected.

Is this a scenario which could be potentially supported by SystemJS?

![image](https://cloud.githubusercontent.com/assets/1380995/11680380/aa5cb0a2-9e0c-11e5-8414-edeab64fad14.png)

**Comment by guybedford** [comment]
This works fine for me in my test using the exact config you shared. It may help if you could provide a repo that reproduces it?

**Comment by MeoMix** [comment]
Yeah sure. Give me a bit to throw something together. I'll try to have one up today once I can confirm reproducing it.

**Comment by MeoMix** [comment]
Odd.

In further testing I see:

- Zopim loads successfully from the redirect initially. However, refreshing the page results in the error.
- Issue does not reproduce in simplified repository although I couldn't begin to guess what the conflict is.

I'll go ahead and close this.
