### ISSUE TITLE
Over-zealous Module Normalization

### ISSUE THREAD

**Issue by EisenbergEffect** [systemjs/systemjs#965]
I'm not sure if this is a bug in the TypeScript plugin from Frank Wallis or if it's a bug in system.js. I'm attaching a simple Aurelia solution set up to use TypeScript and Frank's plugin. You can simply unzip the package and view the index.html file in FireFox...or use any web server to serve it. You will see the error in the console as similar to the following:

```
Error loading file:///Users/EisenbergEffect/Desktop/kit-typescript/src/nav-bar.html.ts!html-resource-plugin
```

The module name being requested is "file:///Users/EisenbergEffect/Desktop/kit-typescript/src/nav-bar.html!html-resource-plugin" It appears, that when a call to `normalizeSync` is made against a module id that contains a plugin and a file extension, the package attempts to override the existing file extension with its own.

If this is an error in my configuration, please let me know. It appears to be a bug of some sort though. You should have everything you need to determine the source and solution for the problem in the attached zip.

[kit-typescript.zip](https://github.com/systemjs/systemjs/files/58390/kit-typescript.zip)

**Comment by EisenbergEffect** [comment]
Cross referencing the same issue reported for the plugin: https://github.com/frankwallis/plugin-typescript/issues/71

**Comment by guybedford** [comment]
@EisenbergEffect thanks, I've fixed this in https://github.com/systemjs/systemjs/commit/0d17b4355687ce402e052c0ad37504adf99fd6c5 and will post a release very soon (hopefully over this weekend).

The workaround would likely be as hinted at in https://github.com/frankwallis/plugin-typescript/issues/71 using a config instead of plugin syntax like:

```
packages: {
    "app": {
      "main": "app",
      "defaultExtension": "ts",
      "meta": {
        "*.html": {
            "loader": "html-resource-plugin"
        },
        "*.ts": {
          "loader": "ts"
        },
        "*.js": {
          "loader": "ts"
        }
      }
    }
```

**Comment by guybedford** [comment]
(NB the workaround above is actually the preferred method over plugin syntax)

**Comment by EisenbergEffect** [comment]
@guybedford I tested out that fix by manually patching up my own system.js version and it works perfectly! Thank you! Please let me know when it is released and we'll get our kits updated :)
