### ISSUE TITLE
Possible to map module path to another module's exports?

### ISSUE THREAD

**Issue by tlancina** [systemjs/systemjs#966]
Angular published a UMD bundle: https://code.angularjs.org/2.0.0-alpha.52/angular2.umd.dev.js, with their modules as exports of the bundle:

```
/***/ function(module, exports, __webpack_require__) {

	module.exports = __webpack_require__(1);


/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	exports.core = __webpack_require__(2);
	exports.common = __webpack_require__(118);
	exports.platform = {
	  browser: __webpack_require__(161),
	  common_dom: __webpack_require__(189)
	};
	exports.http = __webpack_require__(225);
	exports.router = __webpack_require__(240);
	exports.router_link_dsl = __webpack_require__(264);
	exports.instrumentation = __webpack_require__(266);
	exports.upgrade = __webpack_require__(267);


/***/ },
```

Is there a System config to map imports from, for example, `angular2/core` to something like `require('angular2').core`? Webpack [can handle this with externals](https://github.com/webpack/webpack/tree/master/examples/externals), but for our purposes we have a lot of entry files that we'd like to avoid having to rebundle :)

**Comment by guybedford** [comment]
Thanks for posting. Unfortunately we don't have any feature like this, so the best I can advise would be to create custom wrapper modules:

angular2/core.js
```javascript
module.exports = require('angular2').core;
```

It shouldn't be too tricky to maintain those, or is this still restricting to your use case?

**Comment by tlancina** [comment]
Thanks! That isn't a problem at all, was more curious if there was a config option for it.
