### ISSUE TITLE
jsc support

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#967]
I guess we should support native JavaScript Core? Is that valuable to any use cases?

Currently `index.js` fails because `require` is undefined and `dist/system.src.js` fails because `global` is undefined. Should be relatively straightforward to fix.

**Comment by mjackson** [comment]
I'm mainly interested in exploring the possibility of using SystemJS as a generic module loader with JavaScript runtime X. I'm new to the project, so please excuse me if you've had this conversation before. But it seems like there should be a low level where I can plug in and tell SystemJS how to load a module for a given module ID it hasn't seen before, e.g.

```js
// node
SystemJS.loadModule = function (moduleID) {
  return require(moduleID)
}

// jsc
SystemJS.loadModule = function (moduleID) {
  return load(moduleID)
}
```

So the fact that SystemJS uses `require` to actually load modules could be an implementation detail. What am I missing?

**Comment by guybedford** [comment]
The module loader spec itself (https://github.com/whatwg/loader) is the generic module loader API that provides these sorts of hooks to delegate out the pipeline.

SystemJS aims to specifically support loading existing module formats with supporting configuration options and convenience features.

SystemJS would integrate into `jsc` not through the `load` function but through `readFile` and `eval`, which would bring eg CommonJS support to `jsc`. Delegating out loading like your examples through the loader hooks though is also possible, but not generally encouraged in SystemJS.

There's so many angles of looking at this stuff. Just let me know if you have any more questions at all.

**Comment by guybedford** [comment]
If there's implementation pressure on this we can certainly work on it... SystemJS should support as wide an array of environments as possible. But I'm not sure if there's enough pressure on this use case specifically to justify it right now.
