### ISSUE TITLE
Overriding evaluation process to evaluate code in a custom vm

### ISSUE THREAD

**Issue by abhishiv** [systemjs/systemjs#968]
Hey Guy

I'm trying to use something like @kevinbarabash/debugger or @amasad/debugjs with code evaluated in the browser via System.define. Essentially looking to build a in-browser IDE with debugging support backed by systemjs for module loading. 

Right now I'm just monkey patching evaluating process in system@0.19.6, but I intend on using the instantiate plugin hook in the future.

However, when I try to evaluate the code using debugger instead of javascript `eval` or `new Function(...)` it complains about 
`err Error: Invalid System.register form for ***/application/app.js(…)`. So I guess it has something to do with anonymous module loading.

This is the code I'm using with @amasad/debugjs, however with @kevinbarabash/debugger the result is the same.

```
if (!this.globalEvaluationScope)
	return evalExec.call(this, load);

if (load.name.match(/application\/(.*)/)) {
	console.log("load", load);
	console.log(getSource(load));
	preExec(this, load);
	//eval(load.source)
	
	var machine = new debugjs.Machine(__global);
	
	var debuggr = new debugjs.Debugger(machine);
	machine.evaluate(getSource(load));
	
	debuggr.run();
	
	postExec();
	return;
}

```

This might not be even possible, but do you have any suggestion on a way of accomplishing this.

**Comment by guybedford** [comment]
Evaluation must be completely synchronous, are you sure the code above is evaluating the source code before reaching the `postExec` call?

**Comment by guybedford** [comment]
Let me know if you need more help here.
