### ISSUE TITLE
SystemJS tries to transpile file contents because of commented out import

### ISSUE THREAD

**Issue by dsebastien** [systemjs/systemjs#969]
SystemJS should probably try to remove commented-out code before trying to identify whether transpilation is required or not.

ES2015+ code that is commented out will trigger transpilation by SystemJS even if transpiler: "none" is set in the config file. Setting transpiler to false will throw: 'Error: Unable to dynamically transpile ES module as System.transpiler set to false.'.

The issue lies around here: https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L3146

Also, https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L3163 should probably also take "none" into account as it might help figure out that something is wrong sooner :).

In addition, when SystemJS tries to transpile and transpiler is set to "none" it seem to try to get a "none.js" file (I assume as transpiler).

The following file triggers the faulty behavior:

```
/*
import {
  it,
  describe,
  expect,
  inject
} from 'angular2/testing';
import {
  APP_ID
} from 'angular2/angular2';


describe('default test injector', () => {
  it('should provide default id', inject([APP_ID], (id) => {
    expect(id).toBe('a');
  }));
});
*/
console.log("Please do not try to transpile me");
```

The fix could also be done on Babel or TypeScript configuration level (i.e., drop comments), but I feel like SystemJS should ignore commented out code anyways and should never try to transpile if transpiler is set to "none" or false (is false a documented config?).

To be more complete, here's some more context: https://github.com/rolaveric/karma-systemjs/issues/61

**Comment by guybedford** [comment]
This is by design. Module format detection is not accurate as we have to balance performance with accuracy, so comment removal is not part of the detection process.

Rather set the format with meta configuration to avoid detection in these cases - 

```javascript
System.config({
  meta: {
    'test/name.js': { format: 'global' }
  }
});
```

**Comment by dsebastien** [comment]
Okay I understand the reasoning, although I can imagine this causing issues for larger projects.

Configuring each module separately through meta seems cumbersome (read difficult to maintain for larger apps).

Wouldn't it be possible to include a check for transpiler: "none" at https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L3163 ?

If transpiler is set to none SystemJS should never try to load one.

**Comment by guybedford** [comment]
@dsebastien meta supports wildcards so you can do things like:

```javascript
System.config({
  meta: {
    'src/*.js': { format: 'global' }
  }
});
```

etc.

I understand that doesn't cover the detection between AMD, CommonJS and global. Added https://github.com/systemjs/systemjs/commit/f5eb44138b55ba738a56303c03b78ab8e8e394db to disable detection when `transpiler: false` is set.

That is also a jspm bug that we set `transpiler: 'none'` instead of `transpiler: false`... in turn fixed in https://github.com/jspm/jspm-cli/commit/227c120da8b8f80d9017b07b093e0dc56cc1e895... thanks for pointing this out.

**Comment by dsebastien** [comment]
:+1: 
Thanks @guybedford, those commits will fix my issue entirely! :)

**Comment by egucciar** [comment]
@guybedford that option does not work and SystemJS fails to load the file anyway.

Error: (SystemJS) Unable to dynamically transpile ES module as SystemJS.transpiler set to false.
	TypeError: Unable to dynamically transpile ES module as SystemJS.transpiler set to false.
	    at <anonymous>
