### ISSUE TITLE
pluginFirst not noticed by jspm?

### ISSUE THREAD

**Issue by sberney** [systemjs/systemjs#973]
I added `pluginFirst: true` to my `jspm.config.js` file, which mostly works.

When I install `"github:twbs/bootstrap@3.1.1"`, the bootstrap source gets set up with `"deps ../css/bootstrap.css!";`.

Does jspm even know I'm using plugin-css? It doesn't look like it checks `pluginFirst`. When I import the `bootstrap.js`, which contains the offending `"...css!"` line, I get an import error `GET http://localhost:8888/jspm_packages/github/twbs/bootstrap@3.1.1/css/bootstrap.css.js 404 (Not Found)`.

(I am using `defaultJSExtensions: true` on 0.16.15.)

**Comment by guybedford** [comment]
I guess the `main` itself would need to be `pluginFirst`. This is less of a jspm issue than just a natural consequence of the lack of portability of `pluginFirst` usage (and plugin syntax). I'd suggest using an override to fix this to be `pluginFirst`. Note that in jspm 0.17 we're moving away from plugin syntax towards plugin configuration.

**Comment by sberney** [comment]
What does plugin configuration mean? How is it different than plugin syntax? Are you referring to path matching as a primary means of determining loader?

**Comment by guybedford** [comment]
See https://github.com/systemjs/systemjs/blob/master/docs/overview.md#plugin-loaders.

**Comment by sberney** [comment]
In fact I am familiar with that page. It doesn't say "plugin configuration" anywhere on it. I'm asking what this means: "we're moving away from plugin syntax towards plugin configuration". It does say "plugin syntax" on that page, so I'm speculating that plugin configuration refers to not-plugin-syntax, aka using path matching as a primary means of determining loader. Eg, `css/* -->  *!css`.

Yes/no? (I don't particularly think it's a good idea not to allow requirejs compatible lexication, but I'm overriding normalize anyway.)

**Comment by guybedford** [comment]
Sure, to clarify, yes exactly the use of `loader` in meta configuration is deemed plugins by configuration, which is the recommended way plugin use should be declared. Syntax will continue to be allowed, just not encouraged.

**Comment by sberney** [comment]
Perfect, thanks!
