### ISSUE TITLE
Does system prevent window.onerror firing?

### ISSUE THREAD

**Issue by bnolan** [systemjs/systemjs#974]
We have a situation where when loading our app in dev mode and the server goes down, we get a bunch of XHR failure messages in the web developer console, but our error handler (window.onerror or document.addEventListener('error')) don't ever get fired, so we can't notify the developer that there is a problem with their server.

Is there some way to register an error handler with system so our code gets notified on loading failure?

**Comment by guybedford** [comment]
We use `window.onerror` at https://github.com/systemjs/systemjs/blob/master/lib/global-eval.js#L86 for global execution. This could be adjusted to respect existing handlers.

I've never been entirely happy with this global execution method, and am considering turning it off by default. It can be turned off with the configuration:

```javascript
System.config({
  globalEvaluationScope: false
});
```

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/systemjs/commit/efb268dd4c93d66763024a2b667d8f22768a7f65.
