### ISSUE TITLE
Importing plugin causes SystemJS to fail

### ISSUE THREAD

**Issue by CxRes** [systemjs/systemjs#975]
If I externally import a plugin such as by doing:
```
import 'css';
```
SystemJS does not load anything. 

The reason I am doing this is because in my production bundle I want to be able to dynamically import files based on data condition through `System.import('some.css!')`. But there also some statically loaded CSS which I am inlining in the bundle so I do not want to use `exports.build = false`.

**Comment by guybedford** [comment]
To see if I'm understanding you correctly here - you have CSS requires as part of the main bundle tree, which you are including in the bundle the normal way. The bundle itself then does not include the CSS plugin dependency itself so you are adding this as a dependency of the app itself. When you do this, you get some kind of freezing condition during dynamic loading but before bundling?

Does that mean replicating this would be as simple as:

app.js
```javascript
import 'css';
import './style.css!';
```

And then loading that file in the browser?

**Comment by guybedford** [comment]
I can confirm the above is enough to replicate this.

**Comment by guybedford** [comment]
This was a module loader bug, I believe I've fixed it.

**Comment by CxRes** [comment]
Great...Thanks!

**Comment by guybedford** [comment]
Fixed in 0.19.9.
