### ISSUE TITLE
Importing file in more than one places returns an empty module

### ISSUE THREAD

**Issue by Mosho1** [systemjs/systemjs#976]
I'm importing a file in one location and everything is fine, but if I try to import it from another module both of them receive an empty module.

Using 0.19.6

**Comment by guybedford** [comment]
Thanks for reporting, could you share the exact replication as a simple code example?

**Comment by guybedford** [comment]
Usually this sort of thing would happen with circular references.

**Comment by Mosho1** [comment]
I suspected as much, jspm-server which I use also goes haywire when I save specific files. I'll look into it, thanks.

**Comment by Mosho1** [comment]
I found and fixed all circular dependency paths and this looks like its resolved. I used [Madge](https://github.com/pahen/madge) which was really useful for this purpose, and takes the output of `getDepCache` as-is.
