### ISSUE TITLE
Separate instances, shared resources (à la requirejs context)

### ISSUE THREAD

**Issue by sberney** [systemjs/systemjs#982]
In requirejs, after you make a new context, you can do this:

```javascript
require.s.contexts['context-no-1'].defined['some-package'] = require.s.contexts._.defined['some-package']
```

And now, bam, you can load `some-package` in `context-no-1` even though it lives in the master (or some other) context.

I've created a plugin+normalization override that allow me to do much the same thing, but not quite perfectly. SystemJS has `loaderObj._loader.modules` which can be swapped around. However, because names are resolved to absolute URLs, it's not so simple if a package's dependencies aren't fully loaded at the time you move a module from one instance to another.

I would rather be doing this more fully through the plugin system, instead of performing customizations on a new System instance. However, the plugin API (definitely correct me if I'm wrong) seems to only support locate/fetch/translate/instantiate overrides, whereas I would actually like to provide a completely separate System instance as a loader.

Here is what I ultimately want (SystemOne and SystemTwo have different `baseURL`s):

```javascript
Promise.resolve()
.then(() => { SystemTwo.import('my-application'); })
.then(() => { {SystemTwo.import('my-library!one'); })
.then(myLibraryTwo => {
  SystemOne.import('my-library')
  .then(myLibraryOne => {
    myLibraryTwo === myLibraryOne // true
  });
});
```

It's not actually required that `===` hold true, but just that the two libraries are identical, and the library code preferably not be held in memory in more than one place. There are several issues with the way I have accomplished this so far (and, I have inelegant work arounds, but they are icky).

SystemJS loads itself to the window in [`preExec`](https://github.com/systemjs/systemjs/blob/b4fd67410768d85641f706ab0f86f542a74a7655/lib/global-eval.js#L14) and restores itself to the window in `postExec` defined immediately afterwards. However, that restoration occurs only after the callCounter is at zero, which to the best of my knowledge indicates that all requested dependencies and top level packages have been loaded. I need to use another System instance part way through (One loads Two loads One). Sometimes, this causes somewhat mysterious behavior (but I have thus far avoided the need to delve deeply into that). Perhaps the source of mystery is *actually* some place else, but that will have to wait its turn for inspection.

SystemJS overwrites `window.define` all over the place. Unless I explicitly reset `define`, I will be defining things into the wrong instance. Typically I am resetting the window define to `function () { return System.amdDefine.apply(System, arguments); }`, which seems to work. I really don't think this **should** be necessary...

What do you think of the behavior I am trying to introduce? Did you envision accomplishing the same thing, in a particular way? Is there a way to just stick another System instance into the chain as a `._loader` and move on with my life? Any wisdom is welcome, as I'm getting a lot closer to being done with this.

**Comment by guybedford** [comment]
Did you try doing this sort of thing with the `System.get` / `System.set` API?

Something like - 

```javascript
Promise.all([
  SystemTwo.import('my-application')
  SystemTwo.import('my-library')
])
.then(function() {
  var myLibTwo = SystemTwo.get(SystemTwo.normalizeSync('my-library'));
  SystemOne.set(SystemOne.normalizeSync('my-library'), myLibTwo);
  return SystemOne.import('my-library')
  .then(function(myLibOne) {
    // myLibOne == myLibTwo?
  });
});
```

**Comment by sberney** [comment]
It is good to use the API, so thanks. I really wasn't 100% on how `.set` was intended to be used. The documentation gives one example, and it didn't really mean anything to me when I read it.

The issue is things are the other way around: `SystemOne` knows where `my-library` is, but not so for `SystemTwo`. So the idea is more to use `SystemTwo.import(my-library!one)` to proxy to

```javascript
SystemOne.import('my-library')  // inside of a SystemTwo '*!one' import
.then(function (lib) {
  SystemTwo.set(
    SystemTwo.normalizeSync('my-library-one+mangling'), // mangling reversed with something like '!one-unmangle'
    SystemOne.get(SystemOne.normalizeSync('my-library'))); // is this always identical to lib here?
  return lib;
});
```

Most libraries I don't explicitly copy like this (but some libraries I do), while still wanting to access them from `SystemTwo`. So I skip the `.set` step and just return the result of `SystemOne.import`.

#####  (Set . Get) Not Standalone and Not Unique:
Assume that `'my-library'` (which lives in SystemOne) contains `import _ from 'lodash';`. Assume lodash maps to a file containing

```javascript
module.exports = require("npm:lodash@3.10.1/index");
```

You would hope that this would go away once we have `SystemOne.import`ed the library and gotten a stand-alone module out of it. But instead, I have a module that asks for another module by a name that can only be resolved with instance-specific configuration. And there is no way to determine where that other module is in `SystemTwo` (it isn't there), so `SystemTwo` can't handle this [lodash stub] module `.set`ted in absentia. I end up importing the library in `SystemOneClone`, and copying all `._loader.modules` from it into `SystemTwo` with appropriate normalizations. 

Because `SystemTwo` might not know about `npm:lodash...` you would want `SystemOne` to have already compiled the lodash module. So something along these lines is necessary.

Although I can imagine copying dependencies leading to conflicts, if `SystemTwo` wants to own `npm:lodash@3.10.1`. If `SystemTwo` wants to own `npm:lodash@3.10.1` and for some awful reason it is customized and not identical to any other `npm:lodash@3.10.1`, there's no way to resolve both the `*!one` package that needed this lodash version and the local homologous lodash version. And there's not any room for mangling as a solution, because `npm:lodash@3.10.1` is jspmly embedded (not unique enough! Needs to be instance-unique!). Edge case.

##### For some reason I need to copy all the imported `._loader.modules` from one instance to another

I don't see any reason for this, and I only found it out of desperation: bootstrap tabs broke after I imported things from a new nearly vanilla clone of System without copying all of its `._loader.modules` from one to the clone. I found that either not importing anything with the new instance, or copying all the modules from one to the other prevented this rather mysterious bug. I know that's probably not terribly useful to you, and if I come across any elucidation I'll certainly try to explain it.

```javascript
var SystemTwo = new System.constructor();
SystemTwo.config({
  baseURL: System.baseURL,
  defaultJSExtensions: System.defaultJSExtensions,
  pluginFirst: System.pluginFirst,
  transpiler: System.transpiler,
  babelOptions: System.babelOptions,
  packages: System.packages,
  paths: System.paths,
  meta: System.meta,
  map: _.assign({ 'foobar': 'baz-this-is-resolved-just-fine' }, System.map)
});

SystemTwo.import('foobar'); // now bootstrap tabs are broken
```

replacing the import with

```javascript
_.each(System._loader.modules, function (module, key) {
  LocalSystem._loader.modules[key] = module;
});
SystemTwo.import('foobar'); // works fine ...
```

**Comment by guybedford** [comment]
It's very difficult to advise on this without understanding why you want to share modules between two loaders. Perhaps if you could explain the use case succinctly and clearly, that would help to see where you are coming from here?

**Comment by sberney** [comment]
Yes, observations on this workflow are welcome, but save for genius ideas, the process is pretty fixed:

I have many applications independently developed and maintained. Each application has its own baseURL (and thus **namespace**), and its own System. I am working on a single application that provides all the APIs the applications will need to talk to each other. That single application guarantees management of certain larger libraries and dependencies (like Highcharts!). Through some syntax, those applications request such libraries (they have a bunch of rules to follow, so I'm not concerned about an application messing with the hosted library).

The libraries are hosted and configured within one System environment; clients want access to a subset of these resources. Did I convey this convincingly? It's possible I missed a point or two.

**Comment by guybedford** [comment]
@sberney ideally multiple applications would still share the same loader based on naming conventions that don't clash in the registry. If you really must provide this sort of feature I'd suggest a custom hook in the loader to manage it something like - 

```javascript
var systemNormalize = System.normalize;
System.normalize = function(name, parentName) {
  var loader = this;
  return systemNormalize.apply(this, arguments)
  .then(function(normalized) {
    if (anotherLoaderHas(normalized)) {
      // now that it is defined, it won't go through any other steps in the pipeline
      loader.set(normalized, otherLoader.get(normalized);
    }
    return normalized;
  });
};
```

**Comment by guybedford** [comment]
Just let me know if you have any further questions here.
