### ISSUE TITLE
Ignoring dependencies

### ISSUE THREAD

**Issue by johnste** [systemjs/systemjs#983]
I'm trying to use an external module that has optional and conditionally loaded dependencies. After transpiling, all dependencies are being loaded (unconditionally) which results in my not being able to build or use the external module.

Can I configure systemjs to ignore certain dependencies that are going to be loaded? Maybe 
sImilar to browserify.exclude or webpack.IgnorePlugin?

(Am trying to use [skin-deep](https://github.com/glenjamin/skin-deep) but it tries to handle both React 0.13 and 0.14)

**Comment by Vanuan** [comment]
Yeap, looks like systemjs parses all `require` strings without any evaluation:
```
if(false) {
  require('module'); // will still be loaded
}
```

**Comment by sandys** [comment]
I'm trying to install handsontable on github using the following override
```javascript
{
  "main": ["dist/handsontable.full.js", "dist/handsontable.full.css"],
  "format": "global",
  "shim": {
    "dist/handsontable.full.js": {
      "deps": ["zeroclipboard","moment","pikaday"],
      "exports": "Handsontable"
    }
  },
  "dependencies": {
    "zeroclipboard": "npm:zeroclipboard@^2.1.6",
    "pikaday": "npm:pikaday@^1.3.2",
    "moment": "npm:moment@^2.2.0"
  }

}
```
however, I still get errors about 

```
  Client connected. JSPM watching enabled
system.src.js:4703 Uncaught Error: Module not already loaded loading "moment" from "undefined".r @ system.src.js:4703newRequire @ handsontable.js:43(anonymous function) @ handsontable.js:6333.editors @ handsontable.js:7115newRequire @ handsontable.js:61(anonymous function) @ handsontable.js:6324.editors @ handsontable.js:3909newRequire @ handsontable.js:61(anonymous function) @ handsontable.js:6323.cellTypes @ handsontable.js:3837newRequire @ handsontable.js:61outer @ handsontable.js:69init @ handsontable.js:73(anonymous function) @ handsontable.js:79(anonymous function) @ handsontable.js:29(anonymous function) @ handsontable.js:29J @ system.src.js:4703r.execute @ system.src.js:4703i @ system.src.js:4703i @ system.src.js:4703n @ system.src.js:4703Promise.all.then.a.execute @ system.src.js:4703y @ system.src.js:4703w @ system.src.js:4703p @ system.src.js:4703h @ system.src.js:4703(anonymous function) @ system.src.js:4703
(index):1 Uncaught (in promise) Uncaught Error: Module not already loaded loading "moment" from "undefined".
	Evaluating http://localhost:4001/jspm_packages/github/handsontable/handsontable@0.20.2/dist/handsontable.js
	Error loading http://localhost:4001/js/app/index.js
```

Is this happening because of the require issue ?

**Comment by guybedford** [comment]
@johnste the way to handle this is to map out dependencies you don't want on install with an override like:

@Vanuan yes, that's because CommonJS is not naturally statically analyzable. I believe browserify behaves exactly the same way.

```
  jspm install npm:x -o "{map: { 'some-module': '@empty' }}"
```

That way a require to `require('some-module')` won't trigger, and the dependency won't be installed at all either.

@sandys your issue is unique, feel free to post a registry support issue at https://github.com/jspm/registry/issues.

**Comment by sandys** [comment]
@guybedford thanks - I filed it here - https://github.com/jspm/registry/issues/697

**Comment by chauthai** [comment]
@guybedford @johnste 
I confirm [skin-deep](https://github.com/glenjamin/skin-deep) working with this override:
`jspm install npm:skin-deep -o "{map: {'react/lib/ReactContext': '@empty'}}"`

**Comment by johnste** [comment]
@guybedford @chauthai Thank you!
