### ISSUE TITLE
require() fallbacks

### ISSUE THREAD

**Issue by strarsis** [systemjs/systemjs#986]
Let's say I want to pull jQuery from CDN in production - 
but in development I want to require it from installed node_modules, 
so when I got slow or no internet connection I can reload the page/app as quickly as possible.

Also, when jQuery is not available on the CDN - 
a fallback URL (either a second CDN or a local URL) should be used.

Pulling from CDN vs as local package would be possible by providing a different map (as below) for production/development, however, this also means that I have to build two different bundles.

The map accepts an URL per require name - is it possible to pass an array, too?
What about dependencies? Would a require to e.g. a jQuery plugin let systemjs first require jQuery from CDN, when that fails, from local fallback, then require the jQuery plugin from CDN, when that fails from local and then finally return the jQuery plugin exposed window variable?
[fallback.js](https://github.com/dolox/fallback/) offers this kind of functionality, but not as native require.

Example map (from http://stackoverflow.com/questions/31537412/how-to-use-system-js-with-CDN-and-local-fallback):
````
Systemconfig({
    "map": {
        "jquery": "https://code.jquery.com/jquery-2.1.4.js"
    }
});
````

Thank you and 
with best regards

**Comment by guybedford** [comment]
We don't have fallbacks for any other URLs in the browser, so I don't see why we should have import fallbacks?

**Comment by strarsis** [comment]
OK, arguments for fallbacks:

1. In most cases external, unmanaged CDNs are used for popular JS libraries, 
hence the issue of them being unreachable.

2. If we could easily have those fallbacks with other resources like CSS or image files from CDN, 
wouldn't we use them, too?

With best regards

**Comment by guybedford** [comment]
Sorry to be difficult here, but I'm really weary of adding new features, and this has been considered before quite a bit.

1. If using an external CDN, you should be able to trust that that CDN will work, just like I trust that domain name will resolve. DNS is designed to be distributed and direct to multiple IPs with load balancing, so ensuring availablity this way is the standard well-known technique of the web to avoid a single point of failure, making this the level of that.

2. I'd trust there is a good reason we don't have this ability, plus it would complicate development more.

If you wanted to implement something like this, you could certainly add a custom fetch hook or similar in SystemJS that handles fallbacks.

For example:

```javascript
System.import('x').catch(function(e) {
  System.config(backupConfig);
  System.import('x').then(...)
});
```

Or even:

```javascript
var systemFetch = System.fetch;
System.fetch = function(load) {
  return systemFetch.catch(function(e) {
    if (e.indexOf('404') == -1)
      return systemFetch(backPathFor(load.name));
  });
};
```

Hopefully that provides some options.

**Comment by strarsis** [comment]
Thank you for this nice explanation and time.

With best regards

**Comment by guybedford** [comment]
Sure!

**Comment by twifty** [comment]
In an ideal world CDNs would always work. The reality is, not so much.

Take China for example, anything 'google' is either outright blocked or takes forever to load. A domain name may work one day and fail for the next five. DNS queries are manipulated by governments and can be redirected at will. I've noticed more and more countries doing the same. Lately, I've started using different CDNs on a per country basis, but this puts a lot of extra effort on the server and is usually hit and miss (VPNs are becoming more popular).

The demand for a fallback, client side, or even a parallel fetch on a first done first serve basis, is becoming more apparent. Using a series of nested promises, as suggested by @guybedford above, is simply a workaround.

I came across this library while looking for a modern replacement to all the other, now unmaintained, loaders out there. And, to be honest, I am quite shocked that a fallback mechanism has been brushed off as "you should trust your CDN works".
