### ISSUE TITLE
Unable to load simple JS dependency into Angular 2/SystemJS project

### ISSUE THREAD

**Issue by jhiemer** [systemjs/systemjs#988]
Hi,
I am creating a project with AJS2, Typescript and SystemJS currently. I am having a bit of trouble integration third party JS dependencies, which do not rely on the common modularisation other projects do. Here is my setup:

```html
<html>
  <head>
    <title>Monitoring and Logging</title>
    <script src="./node_modules/angular2/bundles/angular2-polyfills.min.js"></script>
    <script src="./node_modules/systemjs/dist/system.src.js"></script>
    <script src="./node_modules/typescript/lib/typescript.js"></script>

    <script src="./node_modules/rxjs/bundles/Rx.min.js"></script>
    <script src="./node_modules/reflect-metadata/Reflect.js"></script>

    <script src="./node_modules/angular2/bundles/angular2.dev.js"></script>

    <script src="./node_modules/angular2/bundles/router.dev.js"></script>
    <script src="./node_modules/angular2/bundles/http.dev.js"></script>

    <link rel="stylesheet" href="./node_modules/bootstrap/dist/css/bootstrap.min.css">

    <link rel="stylesheet" href="app/assets/style.css">
    <script>
      System.config({
        transpiler: 'typescript',
        typescriptOptions: { emitDecoratorMetadata: true },
        defaultExtension: 'js',
        packages: {
          'app': {
            defaultExtension: 'ts'
          },
          'elasticsearch' : {
            defaultExtension: 'js'
          }
        },
        map: {
          'elasticsearch': 'node_modules/elasticsearch-browser'
        }
      });
      System.import('app/bootstrap')
        .then(null, console.error.bind(console))
    </script>
  </head>
  <body>
    <div class="container-fluid">
      <app>loading...</app>
    </div>
  </body>
</html>

```

In my service I wanted to load elasticsearch-browser like this:

```ts
...

import { Observable } from 'rxjs';
import 'rxjs/add/operator/map'

import elasticSearch from 'elasticsearch/elasticsearch'

@Injectable()
export class ElasticsearchService {
  
...
}
```

My tsconfig.json looks like that:

```json
{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules"
  ]
}
```
And my package.json like that:

```json
{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "Angular 2 Quickstart",
  "main": "index.js",
  "scripts": {
    "tsc": "tsc",
    "tsc:w": "tsc -w -m system",
    "lite": "lite-server",
    "start": "concurrent \"npm run tsc:w\" \"npm run lite\" "
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.0",
    "systemjs": "0.19.6",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10",
    "bootstrap": "^4.0.0-alpha.2",
    "elasticsearch-browser": "^10.0.1",
    "highcharts": "^4.2.0",
    "ng2-bootstrap": "1.0.0-beta.0",
    "ng2-charts": "^0.46.0"
  },
  "devDependencies": {
    "concurrently": "^1.0.0",
    "lite-server": "^1.3.1",
    "gulp": "^3.9.0",
    "typescript": "^1.7.3"
  }
}
```

Any idea what I am doing wrong? Trying on that for a couples of hours now. When I load the specific service into a component I get

```trace
Cannot find module elasticsearch/elasticsearch
```

**Comment by Izzmo** [comment]
Looks like it's just not adding the extension on. I had this problem as well. On your import, can you try just adding '.js' to it and reload your page and see if it works (not that it's an ideal solution but it is one step closer to finding the best solution.)

`import elasticSearch from 'elasticsearch/elasticsearch'` => `import elasticSearch from 'elasticsearch/elasticsearch.ts`

*I'm assuming it's a TypeScript file*

**Comment by jhiemer** [comment]
@Izzmo thanks four your response. Sadly the elasticSearch component is no typescript component but instead a pure JS file. See here: https://github.com/elastic/bower-elasticsearch-js.

I have managed to include the file via your advised: 

`import elasticSearch from 'elasticsearch/elasticsearch.js'`

But in the browser I still see:

`Error: AMD module http://localhost:3000/node_modules/elasticsearch-browser/elasticsearch.js did not define(…)`

**Comment by jhiemer** [comment]
@Izzmo any idea/suggestion? :-)

**Comment by Izzmo** [comment]
Okay, so it is at least doing the network request to download the file now, correct?

If so, I checked the elasticsearch repo and it doesn't look like it's setup as an AMD module? This would make sense with the error you are receiving. Basically SystemJS cannot load the file because there is no AMD wrapper in the file.

**Comment by jhiemer** [comment]
@Izzmo ok, then I will get back to the guys from elasticsearch and ask them how to proceed.

**Comment by jhiemer** [comment]
@Izzmo unfortunately the guys from the ES Library are not willing to upgrade to AJS soon. Do you have a recommendation how I could get the library working?

**Comment by Izzmo** [comment]
Recommendation other than the elasticsearch lib or angular?

**Comment by jhiemer** [comment]
@Izzmo hehe. :-)

No when using Angular 2 with System.js and integrating the library of elasticsearch from: https://raw.githubusercontent.com/elastic/bower-elasticsearch-js/master/elasticsearch.js

**Comment by Izzmo** [comment]
Haha, thought so! Yeah, I don't really have any experience with elasticsearch, so I can't help you there. Sorry!

**Comment by nbaua** [comment]
Hi @jhiemer ,

Writing this little late :), I also had a same issue where I needed to load a custom validation file (.js)
I googled it and oops I have no clue, even Ang2 docs are not saying anything about it.

However I was able to 'Hack' this for now,
Please use **styleUrls**  property in your @component block and try adding your external js file as under.


`
    @Component({   

    selector: 'my-content',

    templateUrl: './app/components/template.html',

    styleUrls  : ['http://www.mydomain.com/scripts/validate.js'],

    directives:[ROUTER_DIRECTIVES],

    providers:[MyContentService,HTTP_PROVIDERS] })

`

I was able to use the JS file in my component, hope it works for you too. :)

N Baua.

**Comment by AshishNR** [comment]
Thanks @nbaua .. 

i had same issue with jquery and carousel slick control in Angularjs 2 and jquery . 

used jquery paths in styleUrls   and it's able to add those libraries now . 

once again thanks.
