### ISSUE TITLE
CommonJS-format process variable inclusion by default

### ISSUE THREAD

**Issue by ptMuta** [systemjs/systemjs#991]
Several Node.js-related CommonJS-modules contain a widely used check for nodes `process.env.NODE_ENV`-variable and the current setup of CommonJS format does not provide us these variables which leads to the required usage of the bundler for the influenced modules or manually setting the `process.env` objects in the browser window-object.

Would it be possible to either include the `process = {env: {}}` to all modules loaded with CommonJS format or strip out these checks to lighten the requirements to use many of the CommonJS modules?

**Comment by ptMuta** [comment]
Nevermind, I can't write correctly. (Configuration error.)

**Comment by guybedford** [comment]
`process` is not part of the CommonJS module format itself, it is a NodeJS feature.

You can add this global using the SystemJS globals configuration though:

```javascript
System.config({
  meta: {
    'node_modules/*': {
      globals: {
        process: 'path/to/process/polyfill.js'
      }
    }
  }
});
```

In terms of the production optimization, SystemJS builder will actually automatically build out `process.env.NODE_ENV = production` when minification is enabled, although I can't guarantee that this feature will remain in future as it is the wrong layer to assume this.

**Comment by ptMuta** [comment]
Does the globals accept pure objects as a definition or only external module definitions? 
I've only seen examples of loading external files and making a full polyfill for this would be a waste in most cases when then only thing required is the `env` object from `process`

**Comment by guybedford** [comment]
A local `System.set('process', System.newModule({ default: processModuleValue }))` can be used if you want to avoid an external module.
