### ISSUE TITLE
Error with Traceur 0.0.93

### ISSUE THREAD

**Issue by m4r71n** [systemjs/systemjs#993]
Demo: https://github.com/m4r71n/systemjs-traceur-broken

After updating from `"jspm": "0.16.15"`, `"systemjs": "0.19.6"` and `"traceur": "0.0.92"` to `"jspm": "0.16.19"`, `"systemjs": "0.19.9"` and `"traceur": "0.0.93"` I get the following error in the browser console:

```
Error: babel.transform is not a function
	Error loading http://localhost:8080/app.js
    at SystemJSLoader.babelTranspile (http://localhost:8080/jspm_packages/system.src.js:1188:18)
    at http://localhost:8080/jspm_packages/system.src.js:1150:61
```
After downgrading to `"traceur": "0.0.92"` the error disappears. 
After a quick look the `transpiler` object in https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L1142 is different for `0.0.92` and `0.0.93`.

**Comment by guybedford** [comment]
Thanks SO much for posting, I forgot to add the new overrides for 0.0.93 in the registry. This should be working now.

**Comment by m4r71n** [comment]
Fixed. Thanks!
