### ISSUE TITLE
Get already imported Module object

### ISSUE THREAD

**Issue by shubhamMuttepawar** [systemjs/systemjs#994]
Is there any way that we can get the instance of already imported module?
Whenever we try System.Get(moduleName), it always returns us a new object.
Thanks In Advance!!

**Comment by Bnaya** [comment]
Can you give an example of what you are trying to achieve?
The modules values are cached under System._loader.modules

**Comment by guybedford** [comment]
`System.get` needs to be provided with the normalized module name. So `System.get(System.normalizeSync(moduleName))` should work.

**Comment by shubhamMuttepawar** [comment]
System.get doesn't give the cached module. It gives new instance every time.
But what I require is the same instance which we registered. 
One way I found out was registering the object in angular itself, using 
window['objName'] = objInstance . And then retrieve it in JavaScript using window['objName'].
Is there any way using SystemJs?

**Comment by guybedford** [comment]
@shubhamMuttepawar I'm not sure how you're seeing that behaviour! `System.get` always gives the cached module, and does nothing to generate a new instance. It will perform execution though if a module is in the registry but unexecuted, but that is an edge case.

**Comment by shubhamMuttepawar** [comment]
here is a snapshot of what I got when i tried with `window['appComponent']` and `System.get`. For using `window['appComponent']` I first registered my AppComponent like this in the `app.ts` itself
```javascript
ngOnInit()
    {
       window['appComponent'] = this;
    }
```
and in `index.html` 

```javascript
 System.config({
                packages: {
                    app: {
                        format: 'register',
                        defaultExtension: 'js'
                    }
                }
            });
            System.import('app/js/boot')
```
then I tried this in Chrome Console

![snip](https://cloud.githubusercontent.com/assets/9906235/12120093/33ce9c62-b3f5-11e5-80cb-9f4fdfd08dff.PNG)

Is it possible to achieve what I am doing using `window['appComponent']` with `SystemJs`?

**Comment by guybedford** [comment]
So `System.get('http://127.0.0.1:8080/app/js/components/app.js').AppComponent == window['appComponent']` then surely?

I'm really not sure what you're trying to accomplish.

**Comment by shubhamMuttepawar** [comment]
My use case is I want to call some method on an Angular component from plain javascript. I could get the reference using `window['appComponent']` and call the method, but it doesn't look clean. Is there any  other way?

**Comment by guybedford** [comment]
The way to load modules from JS is via `System.import`, as it can't be known if the module is loaded yet otherwise. `System.get` gives the sync module value though exactly as you want as well. I'm not sure why you're writing to `window['appComponent']` though - modules export via export syntax: `export let appComponent = ...`.

**Comment by shubhamMuttepawar** [comment]
Am not sure how `export let` works. I am writing the  code in typescript so this is my AppComponent
```javascript
export class AppComponent implements OnInit{
    public title = "The Avengers";
    public heroes;
    public selectedHero;
       
    constructor(private _heroService : HeroService) {
        console.log("Constructed");
    }
    
    private getHeroes()
    {
        this._heroService.getHeroes().then(heroes => this.heroes = heroes);
        
    }
    
    ngOnInit()
    {
       window['appComponent'] = this;
      
    }

    public methodToCall() : string 
    {
         return this.title;
    }
```
 and lets say I want to call `methodToCall` from plain javaScript.

**Comment by guybedford** [comment]
In that case `this` is the class instance, while `AppComponent` is the class - they are different objects.

**Comment by shubhamMuttepawar** [comment]
Exactly, so is there any way to get that class object using SystemJs?

**Comment by guybedford** [comment]
You'd need to export it from the module where it is instantiated - 

```javascript
export let appComponent = new AppComponent(...);
```

Closing as this is really a language question.
