### ISSUE TITLE
How to work with local AMD modules - Uncaught TypeError: Unexpected anonymous AMD define.

### ISSUE THREAD

**Issue by jbgarr** [systemjs/systemjs#995]
I have a local AMD module (not installed by jspm), and I can't seem to get it to load properly. The format of the module is as follows:
```
define
(['require',
'lib/alerts/STARTSTOP',
'lib/alerts/STOPPED',
...
],
function( require, STARTSTOP, STOPPED, ... ) {
  return {
    alert: function( data ) {
      var type = data.type;
      var ev   = data.event;
      var cls  = require( 'lib/alerts/' + ev );
      return new cls( data );
    }
  };
});
```

When I try to import/load this module I am running into the following error: `Uncaught TypeError: Unexpected anonymous AMD define.`. I have also made sure to add the following script to my index.html:
```
<script>
      window.define = System.amdDefine;
      window.require = window.requirejs = System.amdRequire;
  </script>
```

In addition to the above I have also added a meta format property to my config.js file, but that hasn't seemed to help either.

```
meta: {
    ...
    "lib/alerts/*.js": {
      "format": "amd"
    }
  }
```

What am I missing here? Nothing has seemed to work so far and I would really appreciate some help with this one.

**Comment by jbgarr** [comment]
As an update to this issue, if I add a module ID to my AMD modules by doing something like this:

    define
    (
    "AlertFactory",
    ['require',
    'lib/alerts/STARTSTOP',
    'lib/alerts/STOPPED',
    ...
    ],
    function( require, STARTSTOP, STOPPED, ... ) {
      return {
        alert: function( data ) {
          var type = data.type;
          var ev   = data.event;
          var cls  = require( 'lib/alerts/' + ev );
          return new cls( data );
        }
      };
});

then I can successfully import them by using the following syntax:
    System.import('lib/alerts/AlertFactory').then( (m) => {
      console.dir( m );
    });

The module that is logged however is an empty object that does not have any methods. For example the `alert` method in my example module is not accessible.

**Comment by Bnaya** [comment]
You are using dynamic require calls, I'm not sure if systemjs supports it.

Try do something like:
```
define
(
[
'lib/alerts/STARTSTOP',
'lib/alerts/STOPPED',
...
],
function(STARTSTOP, STOPPED, ... ) {
	var alerts = {
		STARTSTOP: STARTSTOP,
		STOPPED: STOPPED
	};

  return {
    alert: function( data ) {
      var type = data.type;
      var ev   = data.event;
      var cls  = alerts[ev];
      return new cls( data );
    }
  };
});
```

**Comment by guybedford** [comment]
Yes dynamic require calls will not work.

The error reading unexpected anonymous AMD define is odd though. How are you loading the module (in the first case)?

Did you try loading a really simple AMD module like: `define(function() { return 42; })`?

**Comment by guybedford** [comment]
Note for the second case, that value of the bundle it not the same as the value of the module.

That is you would need to do `System.import('named-define-bundle').then(function() { return System.import('module-defined-by-bundle') }).then(function(m) { ... })`.

**Comment by jbgarr** [comment]
Thanks for the help so far guys. However, I am still having issues.

@guybedford If I try to import a simple AMD module like the one you suggested (without a module ID), that's when I get the `Unhandled promise rejection Error: Unexpected anonymous AMD define.(…)` error. I get that error when I try to import the module by doing this `import {amdtest} from 'lib/alerts/amdtest';` or the following:
```
System.import('lib/alerts/amdtest').then( (m) => {
      console.log( m );
    });
```

If I add a name to the simple module so it looks like this:
```
define(
  "amdtest",
  function() {
    return 42;
});
```
then I don't get the `Unhandled promise rejection Error: Unexpected anonymous AMD define.(…)` error, but it still doesn't work. Depending on how I import it, I will either get an empty object (when using `System.import('lib/alerts/amdtest').then(...)`), or undefined (when using  `import {amdtest} from 'lib/alerts/amdtest';`). I'm sure I'm just doing something wrong, but I can't figure it out. Thanks for the help so far.

**Comment by Bnaya** [comment]
@jbgarr the following code works for me.
https://github.com/Bnaya/jspm-minimal/blob/anon-amd/index.html

It might be code in your module that breaks it. can you add the full code your amdtest?

**Comment by jbgarr** [comment]
@Bnaya Thanks for the continued help. What do you see as the contents of your alert? When I try it I can see the word "Module", but if I log it, I only see an empty object.

My test module (amdtest.js) is very simple, and looks like this:
```
define(
  "amdtest",
  function() {
    return 42;
});
```

**Comment by Bnaya** [comment]
The content of my alert is amdtest, make sure you are on `anon-amd` branch
This declaration is named module declaration,
remove the name
```js
define(function () {
return 42;
});
```

**Comment by jbgarr** [comment]
If I remove the name then I get the following error: `Error: Unexpected anonymous AMD define.`

**Comment by Bnaya** [comment]
Add here your config.js, if its long, link to pastebin
vanila jspm doesn't have issues with AMD

**Comment by jbgarr** [comment]
Ok, here is a link to a pastebin of my config.js: http://pastebin.com/0Hsh12wx

I am building an Aurelia.js app, so I'm not sure if that's why I'm running into issues.

**Comment by Bnaya** [comment]
The best would be
Add also your package.json, or share project using github with the broken code.
and i will run local copy of all your configuration.

**Comment by jbgarr** [comment]
Unfortunately I can't share my whole project since it's a work project. Let me try to do something similar to what you did and create a minimal Aurelia project that includes the modules that I'm trying to use.

**Comment by jbgarr** [comment]
Ok, I've finally found out why I'm having issues. It's because the default Aurelia gulp build is assuming that all of the code is written in ES6 and not mixed with AMD modules. If I want to use existing AMD modules then I will need to adjust my gulp build process. So sorry for any confusion I may have created here and thanks a lot to @Bnaya and @guybedford for your help. It's very much appreciated!

**Comment by Bnaya** [comment]
@jbgarr close the issue :)
