### ISSUE TITLE
Is it possible to use autoprefixer with jspm?

### ISSUE THREAD

**Issue by MeoMix** [systemjs/systemjs#996]
Hey,

I tried to use autoprefixer as a jspm package for quite some time, but was unable to get it successfully implemented.

The root issue is that the [caniuse-api](https://github.com/nyalab/caniuse-api) loads a bunch of json files without declaring their filetype. This conflicts with `defaultJSExtensions: true`.

`features.js` looks something like:

    module.exports = {"aac": function() { return require("caniuse-db/features-json/aac")},
    "ac3-ec3": function() { return require("caniuse-db/features-json/ac3-ec3")},
    ...

I played around with setting `defaultJSExtensions: false`, but encountered many issues with it. All the third-party packages in 'map' needed to be modified and given `.js`. That didn't feel correct, so I backed out of it.

I also tried declaring paths which would map the json files `caniuse-api` was requesting through json-plugin by setting their paths to `*json!`. This didn't resolve the issue, either, as the `.js` ending continued to appear.

Is it possible to tell SystemJS to not assume js-prefix on a per-file basis? Or, should it be possible to set `defaultJSExtensions: false` at this point in time?

Note: @geelen's jspm-loader-css hosts a manually edited version of autoprefixer within itself. This implies he encountered the same issue, but worked around it in a non-elegant fashion.

**Comment by geelen** [comment]
I actually hit the exact same issue, and followed the approach of [autoprefixer-rails](https://github.com/ai/autoprefixer-rails) which is hosting an embedded version of the file. It isn't elegant, but it works :)

Here's a related issue: https://github.com/jspm/npm/issues/52

Good luck!

**Comment by MeoMix** [comment]
Can I ask how you generated the file? I'd like to update it to remove postCSS deprecation warnings. I could just do a find/replace through the generated file, but it seems like it'd be good knowledge to have on how to generate it.

**Comment by guybedford** [comment]
I think it may be best just to wait for jspm 0.17 which should fix this finally.

Working hard here to get that out soon.

**Comment by guybedford** [comment]
Closing as this is a jspm issue.
