### ISSUE TITLE
Android native browser: Object [object Object] has no method 'open'

### ISSUE THREAD

**Issue by miqmago** [systemjs/systemjs#997]
Each System.import("whatever") in Android Native browser is resolving the promise with this error:

```
Error: Object [object Object] has no method 'open'
```
Modifying system.js with the following one:
```javascript
"function"==typeof s.open && s.open("GET",e,!0)
```
Gives the same error with method 'send'

Device:
```
Samsung Galaxy S3 GT-I9300
Android version: 4.3
```

index.html:

```javascript
    <script src="node_modules/angular2/bundles/angular2-polyfills.min.js"></script>
    <script src="node_modules/systemjs/dist/system.js"></script>
    <script src="node_modules/rxjs/bundles/Rx.min.js"></script>
    <script src="node_modules/es6-shim/es6-shim.min.js"></script>
    <script>
        System.config({
            defaultJSExtensions: true,
            packages: {
                "/angular2": {
                    "defaultExtension": false
                },
                "/@reactivex": {
                    "defaultExtension": false
                },
                'build': {
                    defaultExtension: 'js'
                }
            },
            map: {
                'rxjs': 'node_modules/rxjs'
            }
        });
        
        System.import('build/settings/settings').then(function () {
            console.log(ok);
        }, function (e) {
            console.log(e);
            alert(e);
        });
```

build/settings/settings.js
```javascript
System.register([], function(exports_1) {
    var urlParams;
    return {
        setters:[],
        execute: function() {
            window['DEBUG'] = true;
            window['urlParams'] = {};
            (window.onpopstate = function () {
                var match, pl = /\+/g, search = /([^&=]+)=?([^&]*)/g, decode = function (s) { return decodeURIComponent(s.replace(pl, " ")); }, query = window.location.search.substring(1);
                while (match = search.exec(query)) {
                    window['urlParams'][decode(match[1])] = decode(match[2]);
                }
                window['DEBUG'] = window['DEBUG'] || (window['urlParams'] && window['urlParams']['DEBUG']);
            })();
            exports_1("urlParams", urlParams = window['urlParams']);
        }
    }
});
```

**Comment by Bnaya** [comment]
Have you try to run the code without the external scripts?

**Comment by guybedford** [comment]
I'd suggest using the unminified version of SystemJS for debugging.

Are you sure the call to `open` is in SystemJS itself and not one of the libraries? Perhaps you can share the debugging stack?

**Comment by miqmago** [comment]
@Bnaya yes, tried to only include system.js and import any script from the web using `System.import` and the error is the same. It seems that system.js is using xhr for loading any scripts and the object lacks of methods `open` and `send`. Very weird...

@guybedford Already tried with unminified version. Then the error becomes 

```
Error: Object [object Object] has no method 'assert'
```

For `console.assert` function.

The error is produced in the only `open` method call in system.js (searching in the file there is only 1 `open` occurrence). It is at line 4 column 13239 in `system.js` (also line 1032 in `system.src.js`).

I'm almost 100% sure it is in system.js `open` method for `XMLHttpRequest` object: when modified system.js with `"function"==typeof s.open && s.open("GET",e,!0)` in the only point where `open` method is called, then the error disappears (and becomes .`.. has no method send`, some instructions below). Also tried to put `alert(typeof s.open),s.open("GET",e,!0)` and it shows `undefined`.

Can't share the debuggin stack, as it is in Android native browser and don't have acces to console logs (the only possibility is using weinre but as javascript is failing due to system.js javascript errors weinre cannot be loaded...)

**Comment by Bnaya** [comment]
https://github.com/Bnaya/jspm-minimal/blob/master/index.html
This worked for me on android 4.3 emulator and 4.1.2 real device (sgs2)
