### ISSUE TITLE
cleanup of global references in AMD modules

### ISSUE THREAD

**Issue by capricube** [systemjs/systemjs#998]
Hi, 
after using System.js for almost 6 month and having created a fairly complex application with many JSPM dependencies i realized that underscore registers itself as global dependency although i am using it as AMD module (using system-csp-production.js). The main reason for this are those lines: 
```javascript
  var root = typeof self == 'object' && self.self === self && self ||
            typeof global == 'object' && global.global === global && global ||
            this; 

  ... left out a few lines...

  root._ = _;
```
Now that underscore is globally available other modules can use it without importing it, and that is something we want to avoid as it makes the reason why we are using a module loader pointless (actually found a few of our modules are missing underscore imports). 

Because fixing the original library is out of scope, i tried to find a way to fix/delete the global dependency after it has be resolved. And i think i found one: for every resolved JSPM dependency we a have a generated file in the jspm_packages/ directory with a define() call that actually loads the dependency. See the example below for underscore:

```javascript
define(["github:jashkenas/underscore@1.8.3/underscore.js"], function(main) {
  return main;
});
```
If i could inject custom code right before the return statement i could cleanup my self. 
```javascript
define(["github:jashkenas/underscore@1.8.3/underscore.js"], function(main) {
  var root = typeof self == 'object' && self.self === self && self ||
            typeof global == 'object' && global.global === global && global ||
            this; 

  delete root._;

  return main;
});
```
And now the question: is there a way i could hook into the generation of the mentioned file and add per module specific javascript code? Does that make sense or is there another way of doing what i need?

Thanks in advance!
cheers,
Kris

**Comment by capricube** [comment]
after digging deeper i think this is not part of system.js but jspm. I found the code that generates the code here: https://github.com/jspm/jspm-cli/blob/5ca2be693086a5ed54f393bffee5048b60b351f2/lib/common.js

Does anyone have an opinion on that?

**Comment by Bnaya** [comment]
Interesting,
I believe it can be done by using a transpiler plugin, which will be supported on the next release if i'm not wrong.  
You can sandbox the scope of modules using closure and set the global object to an empty object,
or using AST to sniff the code for it and do something about it.

It's possible that systemjs is already aware to that internally in someplace, i just don't know it very well.

**Comment by capricube** [comment]
@Bnaya how could i use a closure here? underscore is a valid AMD module but registers itself globally for some reasons. 

i did a few experiments today with JSPM and realized that changing the generated code of the main entry point is not a good idea as the generated file gets cached in the JSPM cache and therefore getting used by any other project as well. 

i guess i have to solve it outside of system.js/JSPM maybe using another build step that rewrites the generated files after they have been copied from the JSPM cache. Therefore closing the issue.

**Comment by Bnaya** [comment]
For your usecase you can use your inject:
create your own underscore module in your project with that contents 
un-global-underscore.js:
```
define(["github:jashkenas/underscore@1.8.3/underscore.js"], function(main) {
  var root = typeof self == 'object' && self.self === self && self ||
            typeof global == 'object' && global.global === global && global ||
            this; 

  delete root._;

  return main;
});
```
and in your map config, remap underscore: '' to point to your un-global-underscore.js

You can also try to use 
http://underscorejs.org/#noConflict
instead of delete root._;

**Comment by guybedford** [comment]
Support for this global cleanup in SystemJS is tracking at https://github.com/systemjs/systemjs/issues/960.

**Comment by capricube** [comment]
Perfect. Did not find this issue. @guybedford do you already have an idea how this could be implemented?
