### ISSUE TITLE
Move all config to hidden state, with `System.getConfig` getter

### ISSUE THREAD

**Issue by guybedford** [systemjs/systemjs#999]
Configuration at the base-level encourages manual editing which can break down.

In addition, a single configuration namespace allows easier inspection and extraction of the loader config state to do things like `newSystem.config(oldSystem.configuration)` as well.

As this is a breaking change, it would need to go with the 0.20 release.

**Comment by guybedford** [comment]
The biggest issue with this is things like `System.babelOptions` reads having to be updated to `System.configuration.babelOptions` which is verbose as well. Argh.

**Comment by pocesar** [comment]
I don't see a problem with that, at all. Having a way to merge the additions to SystemJS is a major overhaul IMO, so anything goes

**Comment by guybedford** [comment]
Yes I guess so. I'd still prefer a shorthand form of `System.cfg` I think to save typing.

**Comment by pocesar** [comment]
:+1:

**Comment by sberney** [comment]
:+1:

**Comment by TomiS** [comment]
Does this mean it is currently not possible to extend/override a System.js configuration? (I've been trying to find a way) It would be very nice if configs could be merged from different sources? e.g. Define a base config in a 3rd party dependency and then fine-tune it locally.

**Comment by guybedford** [comment]
I've adjusted the proposal here to `System.getConfig()`.

The benefit of the above is that we can then allow multiple `System.config()` calls to happen in a row, without config order affecting them, as we can use the configuration getters to trigger configuration normalization rather than having to do it immediately each time.

**Comment by joeldenning** [comment]
If this is implemented, could it be done in phases so that I have time to migrate off of base-level properties? i.e., implement `getConfig()` before removing the properties, so that there's time to migrate.

**Comment by guybedford** [comment]
Great point, that certainly makes sense to implement something now for the upgrade path.

**Comment by guybedford** [comment]
Added in https://github.com/systemjs/systemjs/commit/de8e1807bfb6ac22d5f838f279e4083547bca798.

**Comment by guybedford** [comment]
Implemented in [0.20.0-alpha.1](https://github.com/systemjs/systemjs/releases/tag/0.20.0-alpha.1).
